### ISSUE TITLE
Nashorn considerably faster than Graal

### ISSUE THREAD

**Issue by ralleman** [oracle/graal#1004]
Hi guys. I stumbled across Graal a few days ago in looking for an alternative to Nashorn. This thing that made me jump with glee was the timeouts because I'm writing an application that runs untrusted code. Problem is that I'm finding that Graal is performing between 60x and 150x slower than Nashorn in a simple concurrency test embedded in to a JUnit test class. Here are the results (all times in milliseconds averaged over 1000 threads):

Test | Create context (b) | Compile source (c) | Get harry (d) | Get anon (e) | Get double (f)
-- | -- | -- | -- | -- | --
Nashorn (uncached) | 84 | 263 | 0 | 1 | 102
Nashorn (cached) | 107 | 107 | 0 | 1 | 2
Graal | 98 | 15700 | 766 | 269 | 2

Here's the Graal code (which I borrowed from another project testing Nashorn's thread isolation):
```java
    @Test
    public void testGraalConcurrency() throws Exception {
        String script = "" +
            "sally=0;\n" +
            "function harry() {\n" +
            "    var bob = function() {\n" +
            "        i = 0;\n" +
            "        i += 1;\n" +
            "        sally += i;\n" +
            "        return sally + 1;\n" +
            "    };\n" +
            "\n" +
            "    return function() {\n" +
            "        return bob();\n" +
            "    }\n" +
            "}\n";

        try (Engine engine = Engine.create()) {
            Source source = Source.create("js", script);

            Callable<Double> addition = () -> {
                String thread = Thread.currentThread().getName();
                long ms = System.currentTimeMillis(), a = 0, b = 0, c = 0, d = 0, e = 0, f = 0;
                a = System.currentTimeMillis() - ms;
                try (Context context = Context.newBuilder().engine(engine).build()) {
                    b = System.currentTimeMillis() - ms;
                    context.eval(source);
                    c = System.currentTimeMillis() - ms;
                    Value harry = context.eval("js", "harry");
                    d = System.currentTimeMillis() - ms;
                    Value anon = harry.execute();
                    e = System.currentTimeMillis() - ms;
                    return anon.execute().asDouble();
                } finally {
                    f = System.currentTimeMillis() - ms;

                    System.out.println(thread + "," + a + "," + (b - a) + "," + (c - b) + "," + (d - c) + "," + (e - d) + "," + (f - e));
                }
            };

            ExecutorService executor = Executors.newCachedThreadPool();
            ArrayList<Future<Double>> results = new ArrayList<>();

            long ms = System.currentTimeMillis();
            for (int i = 0; i < 1000; i++) {
                results.add(executor.submit(addition));
            }

            int miscalculations = 0;
            for (Future<Double> result : results) {
                int jsResult = result.get().intValue();

                if (jsResult != 2) {
                    System.out.println("Incorrect result from js, expected 1 + 1 = 2, but got " + jsResult);
                    miscalculations += 1;
                }
            }

            executor.awaitTermination(1, TimeUnit.SECONDS);
            executor.shutdownNow();
            System.out.println("Test total time: " + (System.currentTimeMillis() - ms));

            System.out.println("Overall: " + miscalculations + " wrong values for 1 + 1.");
        }
    }
```
Here's the Nashorn (uncached) equivalent:
```java
    @Test
    public void testNashornConcurrency() throws ScriptException, InterruptedException, ExecutionException {
        ScriptEngine engine = new NashornScriptEngineFactory().getScriptEngine("-nj");

        String script = "" +
            "sally=0;\n" +
            "function harry() {\n" +
            "    var bob = function() {\n" +
            "        i = 0;\n" +
            "        i += 1;\n" +
            "        sally += i;\n" +
            "        return sally + 1;\n" +
            "    };\n" +
            "\n" +
            "    return function() {\n" +
            "        return bob();\n" +
            "    }\n" +
            "};\n";

        Callable<Double> addition = () -> {
            String thread = Thread.currentThread().getName();
            long ms = System.currentTimeMillis(), a = 0, b = 0, c = 0, d = 0, e = 0, f = 0;
            a = System.currentTimeMillis() - ms;
            try {
                CompiledScript compiledScript = ((Compilable) engine).compile(script);
                b = System.currentTimeMillis() - ms;
                Bindings bindings = new SimpleBindings();

                compiledScript.eval(bindings);
                ScriptObjectMirror scriptObjectMirror = (ScriptObjectMirror) bindings.get("nashorn.global");
                c = System.currentTimeMillis() - ms;

                JSObject harry = (JSObject) scriptObjectMirror.get("harry");
                d = System.currentTimeMillis() - ms;

                JSObject function = (JSObject) harry.call(null);
                e = System.currentTimeMillis() - ms;

                return (Double) function.call(null);
            } catch (ScriptException ex) {
                throw new RuntimeException(ex);
            } finally {
                f = System.currentTimeMillis() - ms;

                System.out.println(thread + "," + a + "," + (b - a) + "," + (c - b) + "," + (d - c) + "," + (e - d) + "," + (f - e));
            }
        };

        ExecutorService executor = Executors.newCachedThreadPool();
        ArrayList<Future<Double>> results = new ArrayList<>();

        for (int i = 0; i < 1000; i++) {
            results.add(executor.submit(addition));
        }

        int miscalculations = 0;
        for (Future<Double> result : results) {
            int jsResult = result.get().intValue();

            if (jsResult != 2) {
                System.out.println("Incorrect result from js, expected 1 + 1 = 2, but got " + jsResult);
                miscalculations += 1;
            }
        }

        executor.awaitTermination(1, TimeUnit.SECONDS);
        executor.shutdownNow();

        System.out.println("Overall: " + miscalculations + " wrong values for 1 + 1.");
    }
```
The cached version of the Nashorn test simply places this outside the loop:
```java
CompiledScript compiledScript = ((Compilable) engine).compile(script);
```
As you can see from the results, this part of the test is running horribly with Graal:
```
context.eval(source);
Value harry = context.eval("js", "harry");
Value anon = harry.execute();
```
And it's even worse if I get "harry" using getBindings().

Am I doing something wrong here?

**Comment by ralleman** [comment]
I should point out that I find the Nashorn timings too high too. With a script as simple as the one in the test, I'd expect compilation to be < 1ms ideally.

**Comment by ralleman** [comment]
Also, I'm using graal CE 1.0.0 rc12 on a macbook pro.

**Comment by wirthi** [comment]
Hi @ralleman 

thanks for your report.

I tried to reproduce your findings. I didn't use the a-f variables, but merely the "test total time" that you already reported for the Graal.js case.

The issue why the reported value is so slow is that the benchmark is rather short-running, and starting many threads, thus potentially competing with our JIT compiler that is on a separate thread. You are not only measuring Graal.js' execution performance of a compiled script, you are also measuring warmup of the JIT compiler, and the compilation performance of the JIT. This is also true for Nashorn of course, but due to their different architecture have a much faster compilation phase.

I've taken your code and run the `testGraalConcurrency` and `testNashornConcurrency` (with and without caching) in a loop:

```java
    public static void main(String[] argv) {
        try { 
            for (int i=0;i<10;i++) {
                testGraalConcurrency();
                testNashornConcurrency(false); //without caching
                testNashornConcurrency(true); //with caching
             }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }
```
The output of the final (10th) iteration is:

```
=== Graal.js ===
Test total time: 1325
Overall: 0 wrong values for 1 + 1.
=== NASHORN uncached===
Test total time: 1337
Overall: 0 wrong values for 1 + 1.
=== NASHORN cached===
Test total time: 1421
Overall: 0 wrong values for 1 + 1.
``` 

Graal.js is slower than both cached/uncached Nashorn variant only for the first 3-4 iterations (I've measured 8834, 2127, and 3218 milliseconds as first three data points for Graal.js; YMMV) but is the equivalent in speed from then on (results are too instable to declare a winner, at least on my machine).

I'll check the compiler graphs if there is anything we can optimize for.

Best,
Christian

**Comment by ralleman** [comment]
Thanks for the explanation Christian and good idea to change the test like you've done. I did the same and came up with these using a shared executor which is more accurate to what we'd see in a web server.

```
Test total time Graal: 13870
Test total time Nashorn uncached: 3776
Test total time Nashorn cached: 1821
Test total time Graal: 2367
Test total time Nashorn uncached: 1496
Test total time Nashorn cached: 1349
Test total time Graal: 1629
Test total time Nashorn uncached: 1321
Test total time Nashorn cached: 1234
Test total time Graal: 1619
Test total time Nashorn uncached: 1225
Test total time Nashorn cached: 1198
Test total time Graal: 1427
Test total time Nashorn uncached: 1223
Test total time Nashorn cached: 1198
Test total time Graal: 1475
Test total time Nashorn uncached: 1203
Test total time Nashorn cached: 1164
Test total time Graal: 1396
Test total time Nashorn uncached: 1183
Test total time Nashorn cached: 1166
Test total time Graal: 1394
Test total time Nashorn uncached: 1145
Test total time Nashorn cached: 1185
Test total time Graal: 1350
Test total time Nashorn uncached: 1172
Test total time Nashorn cached: 1208
Test total time Graal: 1304
Test total time Nashorn uncached: 1191
Test total time Nashorn cached: 1180
```

It's still unclear to me what's going on in that first Graal run though because each of the threads have the same source compilation time of around 11-13 seconds. Is it because Graal needs equivalent warm up per thread - so the warming is not global across threads?

**Comment by ralleman** [comment]
Actually, I think I understand why the compilation times are initially the same between threads - it's because the test is "very" concurrent. The VM will be time slicing each thread at very similar parts of the Javascript compilation and is thus likely to finish each compile around the same time.

**Comment by wirthi** [comment]
Yes. Optimally, you would warm up just one thread and have it compile the code, only to start the concurrency then. All concurrent threads could then profit from the warmed-up code, without competing with the compiler thread. I think that's what is hitting performance so hard for the first iteration.

You seem to be doing the right thing (have a constant `Source` object, that you execute in different `Context`s that share the same `Engine`) in order to enable "source caching" (see https://www.graalvm.org/docs/graalvm-as-a-platform/embed/#enable-source-caching). For the first iteration that just cannot be effective, there is nothing yet to share (nothing is compiled yet), and the compiler thread is even competing with the other executor threads.
