### ISSUE TITLE
[Native Image] Build a native executable that includes FFM functionality and includes static libraries

### ISSUE THREAD

**Issue by acodervic** [oracle/graal#10058]
### Describe the Issue

I can't build a native executable that includes FFM functionality, and it doesn't include a static library when it actually runs

### Using the latest version of GraalVM can resolve many issues.

- [ ] I tried with the [latest version](https://www.graalvm.org/downloads/) of GraalVM.

### GraalVM Version

graalvm 23 
native-image 23

### Operating System and Version

ubuntu22

### Build Command

 $JAVA23_HOME/bin/native-image   --add-exports org.graalvm.nativeimage.builder/com.oracle.svm.hosted.c=ALL-UNNAMED    --add-exports org.graalvm.nativeimage.builder/com.oracle.svm.hosted=ALL-UNNAMED   --add-exports org.graalvm.nativeimage.builder/com.oracle.svm.core.jdk=ALL-UNNAMED       -H:ReflectionConfigurationFiles=native_iamge_reflection.json    --no-fallback  --allow-incomplete-classpath    -H:+PrintClassInitialization  -H:+ReportExceptionStackTraces   -Os -H:+ForeignAPISupport  -H:+UnlockExperimentalVMOptions -H:+PlatformInterfaceCompatibilityMode  -H:+GenerateEmbeddedResourcesFile    --features=graalvm.nativeimage.Luajit  -H:ConfigurationFileDirectories=.   -Ob -H:CLibraryPath="/myhome/LuaJIT-2.1.ROLLING/src"  -jar target/server-1.0-SNAPSHOT.jar

### Expected Behavior

The luajit function luaL_newstate successfully found and called

### Actual Behavior

 ./server-1.0-SNAPSHOT  
Exception in thread "main" java.util.NoSuchElementException: No value present
        at java.base@23/java.util.Optional.get(Optional.java:143)
        at lua.LuaVm.<init>(LuaVm.java:276)

>>>>
   // libraryLookup = SymbolLookup.libraryLookup(dllOrSoPath, ofConfined);
        libraryLookup=SymbolLookup.loaderLookup();
        // lua_State *L = luaL_newstate();
There is LuaVm.java:276>>>        MethodHandle lua_newstate = linker.downcallHandle(libraryLookup.find("luaL_newstate").get(),
                luaL_newstateFunctionDescriptor);
        MemorySegment lua_newstate_ = (MemorySegment) lua_newstate.invoke();
        registerFunctions(lua_newstate_, LuaVm.class, "getJavaArg", getJavaArgUpCallFunDesc);

### Steps to Reproduce

1.build a jar
2.build native-image with static libraries(from jar)
3.execute the output executeable
4.get error , because can not found the function: "luaL_newstate"

### Additional Context

graalvm.nativeimage.Luajit.java:

```java
package graalvm.nativeimage;

import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.Linker;
import java.lang.foreign.MemorySegment;
import java.lang.foreign.SegmentAllocator;
import java.lang.foreign.ValueLayout;
import java.lang.invoke.MethodHandle;
import java.lang.reflect.Field;
import java.lang.reflect.Modifier;
import java.nio.charset.StandardCharsets;
import java.lang.foreign.Arena;

import static java.lang.foreign.ValueLayout.ADDRESS;
import static java.lang.foreign.ValueLayout.JAVA_INT;
import java.lang.foreign.Linker;
import org.graalvm.nativeimage.hosted.Feature;
import org.graalvm.nativeimage.hosted.Feature;
import org.graalvm.nativeimage.hosted.Feature.DuringSetupAccess;

import lua.LuaVm;

import org.graalvm.nativeimage.hosted.RuntimeForeignAccess;
import org.graalvm.nativeimage.hosted.RuntimeResourceAccess;

import com.oracle.svm.core.annotate.AutomaticFeature;
import com.oracle.svm.core.jdk.NativeLibrarySupport;
import com.oracle.svm.core.jdk.PlatformNativeLibrarySupport;
import com.oracle.svm.hosted.FeatureImpl;
import com.oracle.svm.hosted.c.NativeLibraries;

import org.graalvm.nativeimage.hosted.Feature;

public class Luajit implements Feature {

    @Override
    public void beforeAnalysis(BeforeAnalysisAccess access) {
        NativeLibrarySupport.singleton().preregisterUninitializedBuiltinLibrary("luajit");
        NativeLibraries nativeLibraries = ((FeatureImpl.BeforeAnalysisAccessImpl) access).getNativeLibraries();
        nativeLibraries.addStaticJniLibrary("luajit");
    }

    public void duringSetup(DuringSetupAccess access) {
        for (int i = 0; i < LuaVm.downcallFunctionDescriptor.size(); i++) {
            RuntimeForeignAccess.registerForDowncall(LuaVm.downcallFunctionDescriptor.get(i));
        }

        for (int i = 0; i < LuaVm.upcallFunctionDescriptor.size(); i++) {            RuntimeForeignAccess.registerForUpcall(LuaVm.upcallFunctionDescriptor.get(i));
        }
    }

}
```

libluajit.so and libluajit.a

```bash
/myhome/LuaJIT-2.1.ROLLING/src$ ll | grep -i liblua
-rw-rw-r--  1 w w    1509336 10月 28 15:05 libluajit.a
-rwxrwxr-x  1 w w    2187640 10月 28 15:05 libluajit.so*
```

**Comment by oubidar-Abderrahim** [comment]
Could you please share the full reproducer to this issue? also, if you're trying to build a static image, you need to use `--static --libc=musl` in your native-image command

**Comment by oubidar-Abderrahim** [comment]
Any updates?

**Comment by oubidar-Abderrahim** [comment]
Closed for inactivity
