### ISSUE TITLE
[native-image] empty_class_array not in substitution class

### ISSUE THREAD

**Issue by johanvos** [oracle/graal#1008]
This snippet results in an error during native-image build (it can be circumvented by supplying -H:+ReportUnsupportedElementsAtRuntime)

```
Class clazz = Foo.class;
clazz.getMethod("bar",  (Class[])null);
```

Error: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: Unsupported field java.lang.Class.EMPTY_CLASS_ARRAY is reachable: The declaring class of this element has been substituted, but this element is not present in the substitution class

**Comment by johanvos** [comment]
The issue is more general, as getMethods0 on java.lang.Class will call  getMethodsRecursive which is also not on the substitution class

**Comment by cstancu** [comment]
Fixed in https://github.com/oracle/graal/commit/199391fcfcbfe34d07894fc9df87b88355335d6f.
