### ISSUE TITLE
native image on android termux?

### ISSUE THREAD

**Issue by lost22git** [oracle/graal#10198]
More and more tools like clojure-lsp use graalvm native image to improve startup time. But unfortunately, android termux users can't enjoy it now.

**Comment by selhagani** [comment]
Hello @lost22git,
Thank you for reaching out to us!
It seems this might not be an area where the GraalVM team can provide direct assistance. I recommend contacting the Android Termux team, as they may be better equipped to address this. Perhaps they could explore using [Substrate](https://github.com/gluonhq/substrate) to create a native executable for Termux.
