### ISSUE TITLE
Custom native JCE Provider with native-image

### ISSUE THREAD

**Issue by vmencik** [oracle/graal#1023]
I'm trying to compile a project while using a custom JCE provider that is implemented in native code. Because it loads the native library in its static initializer I took a hint from https://medium.com/graalvm/understanding-class-initialization-in-graalvm-native-image-generation-d765b7e4d6ed and used `--delay-class-initialization-to-runtime` (together with `--enable-all-security-services`).

However now I'm getting this error (and I can still see log messages from the providers initialization at image build time):
```
[error] Error: unsupported features in 2 methods
[error] Detailed message:
[error] Error: No instances are allowed in the image heap for a class that is initialized or reinitialized at image runtime: com.cisco.ciscossl.provider.ciscojce.CiscoJCEProvider
[error] Trace: 	object java.lang.Object[]
[error] 	object java.util.IdentityHashMap
[error] 	method javax.crypto.JceSecurity.getVerificationResult(Provider)
[error] Call path from entry point to javax.crypto.JceSecurity.getVerificationResult(Provider):
[error] 	at javax.crypto.JceSecurity.getVerificationResult(JceSecurity.java:176)
[error] 	at javax.crypto.JceSecurity.canUseProvider(JceSecurity.java:204)
[error] 	at javax.crypto.Mac.getInstance(Mac.java:176)
[error] 	at com.sun.security.ntlm.NTLM.<init>(NTLM.java:83)
[error] 	at com.sun.security.ntlm.Client.<init>(Client.java:78)
[error] 	at sun.net.www.protocol.http.ntlm.NTLMAuthentication.init(NTLMAuthentication.java:149)
[error] 	at sun.net.www.protocol.http.ntlm.NTLMAuthentication.<init>(NTLMAuthentication.java:129)
[error] 	at com.oracle.svm.reflect.NTLMAuthentication_constructor_5d02197437e4592f058c3de57b5325aecd37dfe1_5.newInstance(Unknown Source)
[error] 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[error] 	at sun.security.x509.OtherName.getGNI(OtherName.java:132)
[error] 	at sun.security.x509.OtherName.equals(OtherName.java:184)
[error] 	at java.util.HashMap.getNode(HashMap.java:579)
[error] 	at java.util.HashMap.get(HashMap.java:557)
[error] 	at com.oracle.svm.jni.access.JNIReflectionDictionary.getClassObjectByName(JNIReflectionDictionary.java:123)
[error] 	at com.oracle.svm.jni.functions.JNIFunctions.FindClass(JNIFunctions.java:321)
[error] 	at com.oracle.svm.core.code.IsolateEnterStub.JNIFunctions_FindClass_3ec1032c6cb9443725d1e68194130533bfb04076(generated:0)
[error] Error: No instances are allowed in the image heap for a class that is initialized or reinitialized at image runtime: com.cisco.ciscossl.provider.ciscojce.CiscoJCEProvider
[error] Trace: 	object sun.security.jca.ProviderConfig
[error] 	object sun.security.jca.ProviderConfig[]
[error] 	object sun.security.jca.ProviderList
[error] 	field sun.security.jca.Providers.providerList
[error] Error: Use -H:+ReportExceptionStackTraces to print stacktrace of underlying exception
[error] Error: Processing image build request failed
```

Without the delayed initialization I'm getting link errors at runtime even though I have `-Djava.library.path` set correctly.
I don't quite understand why`SunEC` provider does not have this problem even though it also loads native library in its static initializer. I couldn't find its initialization being pushed to runtime (I was looking at https://github.com/oracle/graal/blob/master/substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/SecurityServicesFeature.java).

Any advice on this?

**Comment by cstancu** [comment]
For SunEC we load it at runtime again. See: https://github.com/oracle/graal/blob/master/substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jdk/SecuritySubstitutions.java#L197

**Comment by vmencik** [comment]
OK. So do I understand correctly that the way the SunEC works with SubstrateVM is that it's initialization is NOT delayed to runtime (i.e. happens at image build time) and the substitution of [Provider.checkInitialized](https://github.com/oracle/graal/blob/master/substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jdk/SecuritySubstitutions.java#L169) makes sure that the native library is loaded at runtime?

**Comment by cstancu** [comment]
Yes, that's correct we rely on substitutions to make sure that `System.loadLibrary("sunec")` is executed before `SunEC` is used.  We couldn't rerun `sun.security.ec.SunEC.<clinit>` at runtime since we initialize all the available security providers at image build time, including `SunEC`, and cache them in the image heap, so we would run in the same problem: no instances are allowed in the image heap for a class that is initialized or reinitialized at image run time.

**Comment by vmencik** [comment]
I've managed to get my custom provider (almost) working using the approach suggested (i.e. don't try to delay/re-run initialization and load native library before using any crypto). I still have some issues but those seem to be a problem with my provider's native code, not SubstrateVM. So I'd be OK with closing this issue.

**Comment by cstancu** [comment]
Thank you for reporting back!
