### ISSUE TITLE
GraalVM performing much better than regular VMs. Feature of Graal or bug of regular VMs?

### ISSUE THREAD

**Issue by saoj** [oracle/graal#10298]
**Describe the issue**
A simple math Java method performs poorly on regular JVMs but not on Graal JVMs. Do you know why? Thanks!

**Steps to reproduce the issue**
1. Compile the provided source code (single, simple and small java class with everything needed)
2. Execute the Java class with Oracle JVM 23 => see the printed average latency around 200 nanoseconds
3. Execute the Java class with Graal JVM 23 => see the printed average latency around 7 nanoseconds

**Describe GraalVM and your environment:**
```
$ java -version
java version "23.0.1" 2024-10-15
Java(TM) SE Runtime Environment Oracle GraalVM 23.0.1+11.1 (build 23.0.1+11-jvmci-b01)
Java HotSpot(TM) 64-Bit Server VM Oracle GraalVM 23.0.1+11.1 (build 23.0.1+11-jvmci-b01, mixed mode, sharing)

$ java -version
java version "23.0.1" 2024-10-15
Java(TM) SE Runtime Environment (build 23.0.1+11-39)
Java HotSpot(TM) 64-Bit Server VM (build 23.0.1+11-39, mixed mode, sharing)
```
 - JDK major version: **any**
 - OS: **any**
 - Architecture: **any**

**More details**
The Oracle JVM 23 should optimize the method the same way the Graal JVM 23 is doing. There is no reason for this method not to be optimized. It is very small and only performs simple math operations. It feels like a bug or a bad decision that the Oracle JVM is doing.

The Oracle JVM 23 performs poorly. The Graal JVM 23 performs very well.

No workaround for Oracle JVMs. We would need to switch to a Graal JVM.

The code is below. Just compile and execute with both Oracle JVM 23 and Graal JVM 23 to see the difference.

```
public class OracleJvm23MathBug {

	// simple and small amount of math
	// =====> should be optimized/compiled/inlined for sure!
	private static final long doSomething(int load, int i) {
		long x = 0;
		for (int j = 0; j < load; j++) {
			long pow = (i % 8) * (i % 16);
			if (i % 2 == 0) {
				x += pow;
			} else {
				x -= pow;
			}
		}
		return x;
	}

	/*
	 * Execute this with OpenJDK/Zulu/Oracle JVM 23 => average 215 nanoseconds
	 * Now execute this with Graal23 JVM 23 => average 7 nanoseconds
	 * 
	 * This bug can be observed in any platform (I tested on Linux and Mac)
	 * 
	 * $ java -version 
	 * java version "23.0.1" 2024-10-15 
	 * Java(TM) SE Runtime Environment (build 23.0.1+11-39)
	 * Java HotSpot(TM) 64-Bit Server VM (build 23.0.1+11-39, mixed mode, sharing)
	 * 
	 * $ java -cp . OracleJvm23MathBug
	 * Value computed: -550000000000
	 * Measurements: 10000000| Avg Time: 215 nanos | Min Time: 83 nanos | Max Time: 199750 nanos
	 * 
	 * $ java -version
	 * java version "23.0.1" 2024-10-15
	 * Java(TM) SE Runtime Environment Oracle GraalVM 23.0.1+11.1 (build 23.0.1+11-jvmci-b01)
	 * Java HotSpot(TM) 64-Bit Server VM Oracle GraalVM 23.0.1+11.1 (build 23.0.1+11-jvmci-b01, mixed mode, sharing)
	 * 
	 * $ java -cp . OracleJvm23MathBug
	 * Value computed: -550000000000
	 * Measurements: 10000000| Avg Time: 7 nanos | Min Time: 0 nanos | Max Time: 178625 nanos
	 */
	public static final void main(String[] args) {
		final int iterations = 10_000_000;
		final int load = 10_000;
		NanoBench bench = new NanoBench();
		long computed = 0;
		for (int i = 0; i < iterations; i++) {
			bench.mark();
			computed += doSomething(load, i);
			bench.measure();
		}
		System.out.println("Value computed: " + computed);
		bench.printResults();
	}

	private static class NanoBench {

		private int measurements;
		private long totalTime, minTime, maxTime, time;
		private final StringBuilder sb = new StringBuilder(128);

		NanoBench() {
			reset();
		}

		public final void reset() {
			totalTime = time = measurements = 0;
			maxTime = Long.MIN_VALUE;
			minTime = Long.MAX_VALUE;
		}

		public final void mark() {
			time = System.nanoTime();
		}

		public final void measure() {
			long lastNanoTime = System.nanoTime() - time;
			totalTime += lastNanoTime;
			minTime = lastNanoTime < minTime ? lastNanoTime : minTime;
			maxTime = lastNanoTime > maxTime ? lastNanoTime : maxTime;
			measurements++;
		}

		public final void printResults() {
			sb.setLength(0);
			sb.append("Measurements: ").append(measurements);
			sb.append("| Avg Time: ").append((long) (totalTime / (double) measurements)).append(" nanos");
			sb.append(" | Min Time: ").append(minTime).append(" nanos");
			sb.append(" | Max Time: ").append(maxTime).append(" nanos\n\n");
			for (int i = 0; i < sb.length(); i++) System.out.print(sb.charAt(i));
		}
	}
}
```

**Comment by saoj** [comment]
I've just realized that Graal uses a completely different JIT compiler. And that the HotSpot C2 JIT compiler is lagging behind  :(

I've also realized that with Oracle JDK 23 you can now use the Graal JIT compiler with the options:

`-XX:+UnlockExperimentalVMOptions -XX:+UseJVMCICompiler`

Kudos to the Graal JIT team!

**Comment by merykitty** [comment]
FTR I believe the main culprit here is that while both are able to transform your `doSomething` into:

    private static final long doSomething(int load, int i) {
        long x = 0;
        long pow = (i % 8) * (i % 16);
        if (x % 2 == 0) {
            for (int j = 0; j < load; j++) {
                x += pow;
            }
        } else {
            for (int j = 0; j < load; j++) {
                x -= pow;
            }
        }
        return x;
    }

Graal is able to fold the inner loops into:

    private static final long doSomething(int load, int i) {
        long x = 0;
        long pow = (i % 8) * (i % 16);
        if (x % 2 == 0) {
            x += pow * load;
        } else {
            x -= pow * load;
        }
        return x;
    }

Next time if you want to write a benchmark please read [this stackoverflow post](https://stackoverflow.com/questions/504103/how-do-i-write-a-correct-micro-benchmark-in-java).

**Comment by dougxc** [comment]
Thanks for this issue @saoj !

Benchmarking pitfalls aside, it's an interesting demonstration of Graal's capabilities when it comes to vectorization and loop optimization. For example, if you add `-Djdk.graal.Vectorization=false` to the command line when using Graal, you'll see the performance get noticeable slower.

**Comment by saoj** [comment]
Thanks for the tips @merykitty 

>you may be able to obtain more reliable results if you warm up the methods before measuring the execution time

Yeah, we always warmup. I just didn't do it this time because it wouldn't make a difference in reproducing the issue, in other words, I was just interested in the relative time between the two JVMs. Also because I ran 10 million iterations, the outliers due to cold code would end up being diluted away. But you are absolutely right that for regular benchmarks warmup is mandatory. At least while our friends from [Project Leyden](https://openjdk.org/projects/leyden/) are still working :)

> you could also measure the execution time across many iterations then divide the obtained amount by the number of iterations, this helps avoid error from calling `System::nanoTime` dominating the actual measurement.

Can you elaborate on that? I used to calculate the average cost of `System.nanoTime()` and subtract the cost from each measurement, but I'm not sure that's a good strategy.

When I divide the total time of all iterations (all measurements) by the number of iterations (measurements) I get the average latency time. So I think I didn't understand what you were suggestion but I am interested in understanding it.

Thanks again!

**Comment by saoj** [comment]
> Thanks for this issue @saoj !
> 
> Benchmarking issues aside, it's an interesting demonstration of Graal's capabilities when it comes to vectorization and loop optimization. For example, if you add `-Djdk.graal.Vectorization=false` to the command line when using Graal, you'll see the performance get noticeably slower.

Yeah, you and the team might be interested in checking out some _"fun"_ [research](https://github.com/coralblocks/CoralBench/tree/main?tab=readme-ov-file#hotspotvm--xcomp-and-jit-vs-c-llvm-clang-vs-graalvm) I've been doing comparing C++ AOT (LLVM) with Java JIT (HotSpot). I'm getting better results for Java with two equivalent implementations of a simple hash table: one in C++ and one in Java. At the moment I'm trying to understand why. Some people in [this SO discussion](https://stackoverflow.com/questions/79268109/c-implementation-of-a-simple-map-slower-than-equivalent-implementation-in-java) (_up vote!_) have mentioned something related to how C++ allocates objects on the heap and that Java has an advantage in that area unless you write your own custom C++ allocators. Anyway, this is still a work/research in progress.

**Comment by theRealAph** [comment]
> FTR I believe the main culprit here is that while both are able to transform your `doSomething` into:

Simpler test case:

```
    @Benchmark
    public long aSum() {
        long l = 0;
        for (int n = 0; n < iters; n++) {
            l += poo;
        }
        return l;
    }

```

Addition isn't hoisted out of the loop and turned into a multiplication, so this program is O(n) when it could be O(1).
I have seen this issue before when I was benchmarking `ScopedValue`. I don't know if HotSpot should optimize this case, though, because I'm not at all sure it's common in real non-benchmark code. Any JIT compiler, even C2, is a compromise between how long compilation takes and how much is optimized in the final generated code.
