### ISSUE TITLE
Native Image JDK 21 ZGC support

### ISSUE THREAD

**Issue by AlanduzzZ** [oracle/graal#10321]
**Feature request**

Native Image JDK 21 ZGC support

**Is your feature request related to a problem? Please describe.**
Currently, GraalVM in native image mode only supports Serial GC, Epsilon GC, and G1(EE). However, Serial GC and Epsilon GC are not suitable for production environments with large-scale workloads. Since JDK 15, ZGC has been the default GC for production environments (if I’m not mistaken). As a user, I would like to use GraalVM native image mode for running Java applications in large-scale production environments, and I am particularly interested in having an efficient GC option available. I’ve noticed in other community issues that there are no plans to include ZGC in the native image roadmap. Is this a permanent decision?

**Describe the solution you'd like.**
Hope for ZGC in JDK 21 under native image mode

**Describe who do you think will benefit the most.**
I believe that GraalVM users and the community will greatly benefit from this feature, as it will transform the way Java applications are delivered—shifting from traditional JAR files to a binary format. This will lead to smaller container images for Java microservices, significantly enhancing security due to a reduced attack surface. Whether in traditional Kubernetes pods or serverless environments, microservice startup times will improve, and resources such as CPU and memory will be optimized. All of these improvements will help drive the growing popularity of GraalVM and foster a more active community.

**Describe alternatives you've considered.**
Currently, there is no alternative solution, which forces me to abandon the GraalVM native image delivery method.

**Additional context.**
I saw in this issue that there are currently no plans to implement ZGC for JDK 21 in native image mode.

              > Is including (Generational) ZGC in native-image in discussions at all?

It's listed as a non-goal of this roadmap item, so no this is not about making ZGC available in native-image. We currently don't have any plans to make ZGC available in native-image.

_Originally posted by @fniephaus in https://github.com/oracle/graal/issues/8117#issuecomment-1985748779_

**Express whether you'd like to help contributing this feature**
I am an operations engineer and not very skilled at writing Java code.

**Comment by selhagani** [comment]
Hi @AlanduzzZ, 

Thank you for reaching out to us about this. However, I'm afraid we currently have no plans to support ZGC on Native Image any time soon.

**Comment by patpatpat123** [comment]
May I ask why @selhagani ?
Because ZGC has proven performance boost for many native image compatible applications

**Comment by fniephaus** [comment]
> Because ZGC has proven performance boost for many native image compatible applications

Could you provide an example for an application that you think would benefit from ZGC when compiled into a native image?

ZGC performs quite well in applications with very large heaps (>100GB) but, at least at the moment, Native Image is primarily used for microservices and CLI applications in memory-constraints environments (e.g., VM with 1 CPU/1GB RAM or developer machines).

If you have an application with larger heaps and you'd like to try and boost its performance, maybe try out [G1 GC](https://www.graalvm.org/latest/reference-manual/native-image/optimizations-and-performance/MemoryManagement/).

**Comment by controllerface** [comment]
I happened across this issue while looking for information on ZGC for native binary builds, and I know it is closed but one use case I think this would be very useful is games and game engines. Admittedly, that is likely consider a niche for JDK as a whole, however in recent years the game dev scene around bindings like LWJGL has generated quite a bit of interest, especially with the newer FFM API, and in the (hopefully near) future, with Valhalla. 

I am just one person, but I can say for sure I would immediately jump at the chance to do native binary builds if they included ZGC. IN game dev, ZGC is pretty much the only viable option for games of any significant complexity and while tools like Jlink are useable, a platform specific, self-contained binary is a much more preferable distribution mechanism for platforms like Steam, and while such a distribution is not a solution to hacking/cheating tools, it does raise the bar signficinatly over a normal JRE distribution.

It is perhaps wishful thinking to hope that game development would become a more prevalent use case for Java as a whole, but in the last decade or so, at least in the hobbyist circles, I believe it has grown from a bit of curiosity (with the one big exception being Minecraft) to a much more viable language for the kinds of systems that a game engine requires. Aside from Graal/native-binary, I don't see that there's any other avenue to distribution that doesn't require a bundled runtime.

Maybe someday... 😄

**Comment by jakub-trzebiatowski** [comment]
@fniephaus

> Native Image is primarily used for microservices and CLI applications

Isn't that a chicken-egg problem? If Native Image doesn't provide certain functionalities, it won't be considered by the developers for new use cases.

Graal Native Image would be a great technology to use for memory-intensive desktop UI applications, but interactive applications benefit greatly from low GC pause times. ZGC offers < 1ms pauses to the best of my knowledge.

For future reference, this is a PR that adds ZGC support to GraalVM, but as I understand it, this is only for JIT, not AOT / Native Image:

- https://github.com/oracle/graal/pull/6170

**Comment by fniephaus** [comment]
> Isn't that a chicken-egg problem? If Native Image doesn't provide certain functionalities, it won't be considered by the developers for new use cases.

I agree there are many interesting use cases for Native Image, and we provide SerialGC for memory-constrained environments and G1 GC for larger heaps.

> Graal Native Image would be a great technology to use for memory-intensive desktop UI applications, but interactive applications benefit greatly from low GC pause times. ZGC offers < 1ms pauses to the best of my knowledge.

G1 should already help a lot here. I believe the bigger problem at the moment is that UI applications require native code, which currently requires additional reachability metadata to work with Native Image. The new preserve mode and [Project Crema](https://github.com/oracle/graal/issues/11327) hopefully solve this soon.

>  this is a PR that adds ZGC support to GraalVM, but as I understand it, this is only for JIT, not AOT / Native Image:

Correct. The PR you mentioned is about Graal JIT support, a prerequisite for supporting it in AOT.

On a related note, we recently announced that we are working with AWS on [Shenandoah support in Native Image](https://github.com/oracle/graal/issues/12237).

**Comment by rhyadav** [comment]
> > Because ZGC has proven performance boost for many native image compatible applications
> 
> Could you provide an example for an application that you think would benefit from ZGC when compiled into a native image?
> 
> ZGC performs quite well in applications with very large heaps (>100GB) but, at least at the moment, Native Image is primarily used for microservices and CLI applications in memory-constraints environments (e.g., VM with 1 CPU/1GB RAM or developer machines).
> 
> If you have an application with larger heaps and you'd like to try and boost its performance, maybe try out [G1 GC](https://www.graalvm.org/latest/reference-manual/native-image/optimizations-and-performance/MemoryManagement/).


> [@fniephaus](https://github.com/fniephaus)
> 
> > Native Image is primarily used for microservices and CLI applications
> 
> Isn't that a chicken-egg problem? If Native Image doesn't provide certain functionalities, it won't be considered by the developers for new use cases.
> 
> Graal Native Image would be a great technology to use for memory-intensive desktop UI applications, but interactive applications benefit greatly from low GC pause times. ZGC offers < 1ms pauses to the best of my knowledge.
> 
> For future reference, this is a PR that adds ZGC support to GraalVM, but as I understand it, this is only for JIT, not AOT / Native Image:
> 
> * [[GR-27475]  Add ZGC support #6170](https://github.com/oracle/graal/pull/6170)

@fniephaus there are so many use cases that'd be unlocked, databases is one of those, key value stores, streaming databases, game engines, a prime example is Go and because of the runtime characteristics it possesses, is used not just for micro-services but a lot of the underlying infra,  constraints like these force devs out of the jvm ecosystem.

**Comment by fniephaus** [comment]
> there are so many use cases that'd be unlocked, databases is one of those, key value stores, streaming databases, game engines, a prime example is Go and because of the runtime characteristics it possesses, is used not just for micro-services but a lot of the underlying infra, constraints like these force devs out of the jvm ecosystem.

@rhyadav I agree. Nonetheless, I am afraid ZGC support is not on our roadmap at this point. G1 is available, and AWS is working on Shenandoah. Anyone in the community is more than welcome to work on ZGC support in GraalVM.

**Comment by rhyadav** [comment]
Thanks for the response, @fniephaus. As an ex-OpenJDK Committer, some honest feedback, the contribution experience for OpenJDK and GraalVM is meaningfully less open than communities like LLVM or CPython, where I've had a much more welcoming and transparent experience. I think this is directly relevant to this issue — if the process were genuinely accessible, external contributors would have already stepped up to implement ZGC support for native-image. The fact that this remains unimplemented despite clear demand says less about technical feasibility and more about the barriers that prevent the community from contributing. This is not a critique of any individual, it's an observation about systemic process barriers. I'd encourage the team to examine those barriers, because an open process would have produced this feature by now.

**Comment by fniephaus** [comment]
Thanks for your feedback, @rhyadav.

We know there’s still room to improve the contributor experience, and we’ve been working to make collaboration more accessible over time. For example, we’re currently working together with AWS on Shenandoah support.

Your broader point is well taken, and feedback like this is valuable as we continue evolving the process.
