### ISSUE TITLE
[Native Image] Missing libraries: java, nio, net, zip when using musl on aarch64 and docker image

### ISSUE THREAD

**Issue by spockz** [oracle/graal#10375]
### Describe the Issue

When trying to compile our application statically against musl and after installing the musl [per instructions](https://www.graalvm.org/latest/reference-manual/native-image/guides/build-static-executables/) the error message of using `--static --libc=musl` using the [GraalVM21 container image @1e7548c6ff98](container-registry.oracle.com/graalvm/native-image:21
 ) is:

```
Error: Building images for org.graalvm.nativeimage.Platform$LINUX_AARCH64 (target libc: musl) requires static JDK libraries.
Use most recent JDK from https://github.com/graalvm/labs-openjdk-*/releases
Missing libraries: java, nio, net, zip
(search path: /usr/lib64/graalvm/graalvm-java21/lib/static/linux-aarch64/musl)
``` 

### Using the latest version of GraalVM can resolve many issues.

- [X] I tried with the [latest version](https://www.graalvm.org/downloads/) of GraalVM.

### GraalVM Version

# java -version
java version "21.0.5" 2024-10-15 LTS
Java(TM) SE Runtime Environment Oracle GraalVM 21.0.5+9.1 (build 21.0.5+9-LTS-jvmci-23.1-b48)
Java HotSpot(TM) 64-Bit Server VM Oracle GraalVM 21.0.5+9.1 (build 21.0.5+9-LTS-jvmci-23.1-b48, mixed mode, sharing)

### Operating System and Version

Linux 30a40ffb11f5 6.10.14-linuxkit #1 SMP Thu Oct 24 19:28:55 UTC 2024 aarch64 aarch64 aarch64 GNU/Linux

### Build Command

/usr/lib64/graalvm/graalvm-java21/bin/native-image -cp /workspace/package-schema-registry/target/kafka-schema-registry-package-7.8.0-standalone.jar:/workspace/package-schema-registry/target/kafka-schema-registry-package-7.8.0-standalone.jar --no-fallback --verbose -Ob -o /workspace/package-schema-registry/target/kafka-schema-registry-package-Linux-aarch64 --static --libc=musl io.confluent.kafka.schemaregistry.rest.SchemaRegistryMain
Apply jar:file:///workspace/package-schema-registry/target/kafka-schema-registry-package-7.8.0-standalone.jar!/META-INF/native-image/io.netty/netty-buffer/native-image.properties
Apply jar:file:///workspace/package-schema-registry/target/kafka-schema-registry-package-7.8.0-standalone.jar!/META-INF/native-image/io.netty/netty-common/native-image.properties
Apply jar:file:///workspace/package-schema-registry/target/kafka-schema-registry-package-7.8.0-standalone.jar!/META-INF/native-image/io.netty/netty-codec/native-image.properties
Apply jar:file:///workspace/package-schema-registry/target/kafka-schema-registry-package-7.8.0-standalone.jar!/META-INF/native-image/org.pcollections/pcollections/native-image.properties
Apply jar:file:///workspace/package-schema-registry/target/kafka-schema-registry-package-7.8.0-standalone.jar!/META-INF/native-image/jni-config.json
Apply jar:file:///workspace/package-schema-registry/target/kafka-schema-registry-package-7.8.0-standalone.jar!/META-INF/native-image/reflect-config.json
Apply jar:file:///workspace/package-schema-registry/target/kafka-schema-registry-package-7.8.0-standalone.jar!/META-INF/native-image/io.netty/netty-transport/reflect-config.json
Apply jar:file:///workspace/package-schema-registry/target/kafka-schema-registry-package-7.8.0-standalone.jar!/META-INF/native-image/io.netty/netty-transport/generated/handlers/reflect-config.json
Apply jar:file:///workspace/package-schema-registry/target/kafka-schema-registry-package-7.8.0-standalone.jar!/META-INF/native-image/io.netty/netty-codec/generated/handlers/reflect-config.json
Apply jar:file:///workspace/package-schema-registry/target/kafka-schema-registry-package-7.8.0-standalone.jar!/META-INF/native-image/org.glassfish.jersey.inject/jersey-hk2/reflect-config.json
Apply jar:file:///workspace/package-schema-registry/target/kafka-schema-registry-package-7.8.0-standalone.jar!/META-INF/native-image/org.glassfish.jersey.core/jersey-client/reflect-config.json
Apply jar:file:///workspace/package-schema-registry/target/kafka-schema-registry-package-7.8.0-standalone.jar!/META-INF/native-image/org.glassfish.jersey.core/jersey-server/reflect-config.json
Apply jar:file:///workspace/package-schema-registry/target/kafka-schema-registry-package-7.8.0-standalone.jar!/META-INF/native-image/org.glassfish.jersey.core/jersey-common/reflect-config.json
Apply jar:file:///workspace/package-schema-registry/target/kafka-schema-registry-package-7.8.0-standalone.jar!/META-INF/native-image/resource-config.json
Apply jar:file:///workspace/package-schema-registry/target/kafka-schema-registry-package-7.8.0-standalone.jar!/META-INF/native-image/org.glassfish.jersey.inject/jersey-hk2/resource-config.json
Apply jar:file:///workspace/package-schema-registry/target/kafka-schema-registry-package-7.8.0-standalone.jar!/META-INF/native-image/org.glassfish.jersey.core/jersey-client/resource-config.json
Apply jar:file:///workspace/package-schema-registry/target/kafka-schema-registry-package-7.8.0-standalone.jar!/META-INF/native-image/org.glassfish.jersey.core/jersey-server/resource-config.json
Apply jar:file:///workspace/package-schema-registry/target/kafka-schema-registry-package-7.8.0-standalone.jar!/META-INF/native-image/org.glassfish.jersey.core/jersey-common/resource-config.json
Apply jar:file:///workspace/package-schema-registry/target/kafka-schema-registry-package-7.8.0-standalone.jar!/META-INF/native-image/proxy-config.json
Apply jar:file:///workspace/package-schema-registry/target/kafka-schema-registry-package-7.8.0-standalone.jar!/META-INF/native-image/serialization-config.json
Apply jar:file:///workspace/package-schema-registry/target/kafka-schema-registry-package-7.8.0-standalone.jar!/META-INF/native-image/predefined-classes-config.json
Apply jar:file:///usr/lib64/graalvm/graalvm-java21/lib/svm/library-support.jar!/META-INF/native-image/com.oracle.svm/thirdparty/native-image.properties
Apply jar:file:///usr/lib64/graalvm/graalvm-java21/lib/svm/library-support.jar!/META-INF/native-image/com.oracle.svm/polyglot/native-image.properties
Executing [
HOME=/root \
LANG=en_US.UTF-8 \
PATH=/app/musl-toolchain/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin \
PWD=/workspace \
USE_NATIVE_IMAGE_JAVA_PLATFORM_MODULE_SYSTEM=true \
/usr/lib64/graalvm/graalvm-java21/bin/java \
-XX:+UseParallelGC \
-XX:+UnlockExperimentalVMOptions \
-XX:+EnableJVMCI \
-Dtruffle.TrustAllTruffleRuntimeProviders=true \
-Dtruffle.TruffleRuntime=com.oracle.truffle.api.impl.DefaultTruffleRuntime \
-Dgraalvm.ForcePolyglotInvalid=true \
-Dgraalvm.locatorDisabled=true \
-Dsubstratevm.HostLibC=glibc \
-Dsubstratevm.IgnoreGraalVersionCheck=true \
--add-exports=java.base/com.sun.crypto.provider=org.graalvm.nativeimage.builder \
--add-exports=java.base/jdk.internal.access=org.graalvm.nativeimage.builder \
--add-exports=java.base/jdk.internal.event=org.graalvm.nativeimage.builder \
--add-exports=java.base/jdk.internal.loader=org.graalvm.nativeimage.builder \
--add-exports=java.base/jdk.internal.logger=org.graalvm.nativeimage.builder \
--add-exports=java.base/jdk.internal.misc=com.oracle.svm.svm_enterprise,org.graalvm.nativeimage.builder,org.graalvm.nativeimage.objectfile,org.graalvm.nativeimage.pointsto \
--add-exports=java.base/jdk.internal.module=org.graalvm.nativeimage.base,org.graalvm.nativeimage.builder \
--add-exports=java.base/jdk.internal.org.objectweb.asm=org.graalvm.nativeimage.builder \
--add-exports=java.base/jdk.internal.perf=org.graalvm.nativeimage.builder \
--add-exports=java.base/jdk.internal.platform=org.graalvm.nativeimage.builder \
--add-exports=java.base/jdk.internal.ref=org.graalvm.nativeimage.builder,org.graalvm.nativeimage.objectfile \
--add-exports=java.base/jdk.internal.reflect=org.graalvm.nativeimage.builder \
--add-exports=java.base/jdk.internal.util=org.graalvm.nativeimage.builder \
--add-exports=java.base/jdk.internal.vm.annotation=org.graalvm.nativeimage.builder \
--add-exports=java.base/jdk.internal.vm=org.graalvm.nativeimage.builder \
--add-exports=java.base/jdk.internal=org.graalvm.nativeimage.builder \
--add-exports=java.base/sun.invoke.util=org.graalvm.nativeimage.builder \
--add-exports=java.base/sun.net.www=org.graalvm.nativeimage.builder \
--add-exports=java.base/sun.net=org.graalvm.nativeimage.builder \
--add-exports=java.base/sun.nio.ch=org.graalvm.nativeimage.builder,org.graalvm.nativeimage.objectfile \
--add-exports=java.base/sun.reflect.annotation=org.graalvm.nativeimage.builder \
--add-exports=java.base/sun.reflect.generics.factory=org.graalvm.nativeimage.builder \
--add-exports=java.base/sun.reflect.generics.reflectiveObjects=org.graalvm.nativeimage.builder \
--add-exports=java.base/sun.reflect.generics.repository=org.graalvm.nativeimage.builder \
--add-exports=java.base/sun.reflect.generics.scope=org.graalvm.nativeimage.builder \
--add-exports=java.base/sun.reflect.generics.tree=org.graalvm.nativeimage.builder \
--add-exports=java.base/sun.security.jca=org.graalvm.nativeimage.builder \
--add-exports=java.base/sun.security.provider=org.graalvm.nativeimage.builder \
--add-exports=java.base/sun.security.ssl=org.graalvm.nativeimage.builder \
--add-exports=java.base/sun.security.util=org.graalvm.nativeimage.builder \
--add-exports=java.base/sun.security.x509=org.graalvm.nativeimage.builder \
--add-exports=java.base/sun.text.spi=org.graalvm.nativeimage.builder \
--add-exports=java.base/sun.util.calendar=org.graalvm.nativeimage.builder \
--add-exports=java.base/sun.util.cldr=org.graalvm.nativeimage.builder \
--add-exports=java.base/sun.util.locale.provider=org.graalvm.nativeimage.builder \
--add-exports=java.base/sun.util.locale=org.graalvm.nativeimage.builder \
--add-exports=java.base/sun.util.resources=org.graalvm.nativeimage.builder \
--add-exports=java.base/sun.util=org.graalvm.nativeimage.builder \
--add-exports=java.management/com.sun.jmx.mbeanserver=org.graalvm.nativeimage.builder \
--add-exports=java.management/sun.management=org.graalvm.nativeimage.builder,org.graalvm.nativeimage.pointsto \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.aarch64=com.oracle.graal.graal_enterprise,com.oracle.svm.svm_enterprise,jdk.internal.vm.compiler,org.graalvm.nativeimage.builder,org.graalvm.nativeimage.objectfile \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.amd64=com.oracle.graal.graal_enterprise,com.oracle.svm.svm_enterprise,jdk.internal.vm.compiler,org.graalvm.nativeimage.builder,org.graalvm.nativeimage.objectfile \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.code.site=com.oracle.svm.svm_enterprise,jdk.internal.vm.compiler,org.graalvm.nativeimage.builder \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.code.stack=jdk.internal.vm.compiler,org.graalvm.nativeimage.builder \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.code=com.oracle.graal.graal_enterprise,com.oracle.svm.svm_enterprise,jdk.internal.vm.compiler,org.graalvm.nativeimage.builder,org.graalvm.nativeimage.objectfile,org.graalvm.nativeimage.pointsto,org.graalvm.truffle.compiler \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.common=com.oracle.graal.graal_enterprise,com.oracle.svm.svm_enterprise,jdk.internal.vm.compiler,org.graalvm.nativeimage.builder,org.graalvm.nativeimage.pointsto \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.hotspot.aarch64=jdk.internal.vm.compiler \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.hotspot.amd64=jdk.internal.vm.compiler \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.hotspot=com.oracle.graal.graal_enterprise,jdk.internal.vm.compiler,org.graalvm.nativeimage.builder \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.meta=com.oracle.graal.graal_enterprise,com.oracle.svm.svm_enterprise,jdk.internal.vm.compiler,org.graalvm.nativeimage.base,org.graalvm.nativeimage.builder,org.graalvm.nativeimage.objectfile,org.graalvm.nativeimage.pointsto,org.graalvm.truffle.compiler \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.runtime=com.oracle.graal.graal_enterprise,jdk.internal.vm.compiler,org.graalvm.nativeimage.builder,org.graalvm.nativeimage.pointsto \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.services=com.oracle.graal.graal_enterprise,com.oracle.svm.svm_enterprise,jdk.internal.vm.compiler,org.graalvm.nativeimage.builder \
--add-exports=jdk.jfr/jdk.jfr.events=org.graalvm.nativeimage.builder \
--add-exports=jdk.jfr/jdk.jfr.internal.jfc=org.graalvm.nativeimage.builder \
--add-exports=jdk.jfr/jdk.jfr.internal=org.graalvm.nativeimage.builder \
--add-exports=jdk.management/com.sun.management.internal=org.graalvm.nativeimage.builder \
-XX:+UseJVMCINativeLibrary \
-Xss10m \
-XX:MaxRAMPercentage=48.346972507110955 \
-XX:GCTimeRatio=9 \
-XX:+ExitOnOutOfMemoryError \
-Djava.awt.headless=true \
'-Dorg.graalvm.vendor=Oracle Corporation' \
-Dorg.graalvm.vendorurl=https://www.graalvm.org/ \
'-Dorg.graalvm.vendorversion=Oracle GraalVM 21.0.5+9.1' \
-Dorg.graalvm.version=23.1.5 \
-Dcom.oracle.graalvm.isaot=true \
-Djava.system.class.loader=com.oracle.svm.hosted.NativeImageSystemClassLoader \
-Xshare:off \
-Djdk.internal.lambda.disableEagerInitialization=true \
-Djdk.internal.lambda.eagerlyInitialize=false \
-Djava.lang.invoke.InnerClassLambdaMetafactory.initializeLambdas=false \
-Djava.lang.invoke.MethodHandle.DONT_INLINE_THRESHOLD=-1 \
-Djava.lang.invoke.MethodHandle.PROFILE_GWT=false \
--add-modules=ALL-DEFAULT \
--module-path \
/usr/lib64/graalvm/graalvm-java21/lib/svm/builder/svm.jar:/usr/lib64/graalvm/graalvm-java21/lib/svm/builder/svm-enterprise.jar:/usr/lib64/graalvm/graalvm-java21/lib/svm/builder/objectfile.jar:/usr/lib64/graalvm/graalvm-java21/lib/svm/builder/pointsto.jar:/usr/lib64/graalvm/graalvm-java21/lib/svm/builder/native-image-base.jar \
--module \
org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner \
-keepalive \
/proc/79/comm \
-imagecp \
/workspace/package-schema-registry/target/kafka-schema-registry-package-7.8.0-standalone.jar \
-imagemp \
/usr/lib64/graalvm/graalvm-java21/lib/svm/graal-microservices.jar:/usr/lib64/graalvm/graalvm-java21/lib/svm/library-support.jar \
-H:CLibraryPath=/usr/lib64/graalvm/graalvm-java21/lib/svm/clibraries/linux-aarch64 \
-H:Path@driver=/workspace/package-schema-registry/target \
'-H:ClassInitialization@jar:file:///workspace/package-schema-registry/target/kafka-schema-registry-package-7.8.0-standalone.jar!/META-INF/native-image/io.netty/netty-buffer/native-image.properties+api=io.netty.buffer.PooledByteBufAllocator:run_time,io.netty.buffer.ByteBufAllocator:run_time,io.netty.buffer.ByteBufUtil:run_time,io.netty.buffer.AbstractReferenceCountedByteBuf:run_time' \
'-H:ClassInitialization@jar:file:///workspace/package-schema-registry/target/kafka-schema-registry-package-7.8.0-standalone.jar!/META-INF/native-image/io.netty/netty-common/native-image.properties+api=io.netty.util.AbstractReferenceCounted:run_time,io.netty.util.concurrent.GlobalEventExecutor:run_time,io.netty.util.concurrent.ImmediateEventExecutor:run_time,io.netty.util.concurrent.ScheduledFutureTask:run_time,io.netty.util.internal.ThreadLocalRandom:run_time' \
'-H:ClassInitialization@jar:file:///workspace/package-schema-registry/target/kafka-schema-registry-package-7.8.0-standalone.jar!/META-INF/native-image/io.netty/netty-common/native-image.properties+api=io.netty.util.NetUtilSubstitutions$NetUtilLocalhost4LazyHolder:run_time' \
'-H:ClassInitialization@jar:file:///workspace/package-schema-registry/target/kafka-schema-registry-package-7.8.0-standalone.jar!/META-INF/native-image/io.netty/netty-common/native-image.properties+api=io.netty.util.NetUtilSubstitutions$NetUtilLocalhost6LazyHolder:run_time' \
'-H:ClassInitialization@jar:file:///workspace/package-schema-registry/target/kafka-schema-registry-package-7.8.0-standalone.jar!/META-INF/native-image/io.netty/netty-common/native-image.properties+api=io.netty.util.NetUtilSubstitutions$NetUtilLocalhostLazyHolder:run_time' \
'-H:ClassInitialization@jar:file:///workspace/package-schema-registry/target/kafka-schema-registry-package-7.8.0-standalone.jar!/META-INF/native-image/io.netty/netty-common/native-image.properties+api=io.netty.util.NetUtilSubstitutions$NetUtilNetworkInterfacesLazyHolder:run_time' \
'-H:ClassInitialization@jar:file:///workspace/package-schema-registry/target/kafka-schema-registry-package-7.8.0-standalone.jar!/META-INF/native-image/io.netty/netty-codec/native-image.properties+api=io.netty.handler.codec.compression.BrotliDecoder:run_time' \
'-H:ClassInitialization@jar:file:///workspace/package-schema-registry/target/kafka-schema-registry-package-7.8.0-standalone.jar!/META-INF/native-image/org.pcollections/pcollections/native-image.properties+api=org.pcollections:build_time' \
'-H:JNIConfigurationResources@jar:file:///workspace/package-schema-registry/target/kafka-schema-registry-package-7.8.0-standalone.jar!/META-INF/native-image/jni-config.json+api=META-INF/native-image/jni-config.json' \
'-H:ReflectionConfigurationResources@jar:file:///workspace/package-schema-registry/target/kafka-schema-registry-package-7.8.0-standalone.jar!/META-INF/native-image/reflect-config.json+api=META-INF/native-image/reflect-config.json' \
'-H:ReflectionConfigurationResources@jar:file:///workspace/package-schema-registry/target/kafka-schema-registry-package-7.8.0-standalone.jar!/META-INF/native-image/io.netty/netty-transport/reflect-config.json+api=META-INF/native-image/io.netty/netty-transport/reflect-config.json' \
'-H:ReflectionConfigurationResources@jar:file:///workspace/package-schema-registry/target/kafka-schema-registry-package-7.8.0-standalone.jar!/META-INF/native-image/io.netty/netty-transport/generated/handlers/reflect-config.json+api=META-INF/native-image/io.netty/netty-transport/generated/handlers/reflect-config.json' \
'-H:ReflectionConfigurationResources@jar:file:///workspace/package-schema-registry/target/kafka-schema-registry-package-7.8.0-standalone.jar!/META-INF/native-image/io.netty/netty-codec/generated/handlers/reflect-config.json+api=META-INF/native-image/io.netty/netty-codec/generated/handlers/reflect-config.json' \
'-H:ReflectionConfigurationResources@jar:file:///workspace/package-schema-registry/target/kafka-schema-registry-package-7.8.0-standalone.jar!/META-INF/native-image/org.glassfish.jersey.inject/jersey-hk2/reflect-config.json+api=META-INF/native-image/org.glassfish.jersey.inject/jersey-hk2/reflect-config.json' \
'-H:ReflectionConfigurationResources@jar:file:///workspace/package-schema-registry/target/kafka-schema-registry-package-7.8.0-standalone.jar!/META-INF/native-image/org.glassfish.jersey.core/jersey-client/reflect-config.json+api=META-INF/native-image/org.glassfish.jersey.core/jersey-client/reflect-config.json' \
'-H:ReflectionConfigurationResources@jar:file:///workspace/package-schema-registry/target/kafka-schema-registry-package-7.8.0-standalone.jar!/META-INF/native-image/org.glassfish.jersey.core/jersey-server/reflect-config.json+api=META-INF/native-image/org.glassfish.jersey.core/jersey-server/reflect-config.json' \
'-H:ReflectionConfigurationResources@jar:file:///workspace/package-schema-registry/target/kafka-schema-registry-package-7.8.0-standalone.jar!/META-INF/native-image/org.glassfish.jersey.core/jersey-common/reflect-config.json+api=META-INF/native-image/org.glassfish.jersey.core/jersey-common/reflect-config.json' \
'-H:ResourceConfigurationResources@jar:file:///workspace/package-schema-registry/target/kafka-schema-registry-package-7.8.0-standalone.jar!/META-INF/native-image/resource-config.json+api=META-INF/native-image/resource-config.json' \
'-H:ResourceConfigurationResources@jar:file:///workspace/package-schema-registry/target/kafka-schema-registry-package-7.8.0-standalone.jar!/META-INF/native-image/org.glassfish.jersey.inject/jersey-hk2/resource-config.json+api=META-INF/native-image/org.glassfish.jersey.inject/jersey-hk2/resource-config.json' \
'-H:ResourceConfigurationResources@jar:file:///workspace/package-schema-registry/target/kafka-schema-registry-package-7.8.0-standalone.jar!/META-INF/native-image/org.glassfish.jersey.core/jersey-client/resource-config.json+api=META-INF/native-image/org.glassfish.jersey.core/jersey-client/resource-config.json' \
'-H:ResourceConfigurationResources@jar:file:///workspace/package-schema-registry/target/kafka-schema-registry-package-7.8.0-standalone.jar!/META-INF/native-image/org.glassfish.jersey.core/jersey-server/resource-config.json+api=META-INF/native-image/org.glassfish.jersey.core/jersey-server/resource-config.json' \
'-H:ResourceConfigurationResources@jar:file:///workspace/package-schema-registry/target/kafka-schema-registry-package-7.8.0-standalone.jar!/META-INF/native-image/org.glassfish.jersey.core/jersey-common/resource-config.json+api=META-INF/native-image/org.glassfish.jersey.core/jersey-common/resource-config.json' \
'-H:DynamicProxyConfigurationResources@jar:file:///workspace/package-schema-registry/target/kafka-schema-registry-package-7.8.0-standalone.jar!/META-INF/native-image/proxy-config.json+api=META-INF/native-image/proxy-config.json' \
'-H:SerializationConfigurationResources@jar:file:///workspace/package-schema-registry/target/kafka-schema-registry-package-7.8.0-standalone.jar!/META-INF/native-image/serialization-config.json+api=META-INF/native-image/serialization-config.json' \
'-H:PredefinedClassesConfigurationResources@jar:file:///workspace/package-schema-registry/target/kafka-schema-registry-package-7.8.0-standalone.jar!/META-INF/native-image/predefined-classes-config.json+api=META-INF/native-image/predefined-classes-config.json' \
-H:FallbackThreshold@user+api=0 \
-H:Optimize@user+api=b \
-H:Name@user+api=kafka-schema-registry-package-Linux-aarch64 \
-H:+StaticExecutable@user+api \
-H:UseLibC@user+api=musl \
'-H:Class@explicit main-class=io.confluent.kafka.schemaregistry.rest.SchemaRegistryMain' \
-H:ImageBuildID@driver=8092fd3a-39f6-02e6-0075-32aaa08cdb86 \
'-H:Features@jar:file:///usr/lib64/graalvm/graalvm-java21/lib/svm/library-support.jar!/META-INF/native-image/com.oracle.svm/thirdparty/native-image.properties+api=com.oracle.svm.thirdparty.gson.GsonFeature' \
'-H:Features@jar:file:///usr/lib64/graalvm/graalvm-java21/lib/svm/library-support.jar!/META-INF/native-image/com.oracle.svm/polyglot/native-image.properties+api=com.oracle.svm.polyglot.groovy.GroovyIndyInterfaceFeature,com.oracle.svm.polyglot.scala.ScalaFeature' \
-H:Color@driver=always \
-H:+BuildOutputProgress@driver \
-H:+BuildOutputLinks@driver

### Expected Behavior

A successfully statically compiled binary

### Actual Behavior

Native-image cannot find the libraries present for `musl` as they are not in the `aarch64` docker image, while they are in the `amd64` docker image.

### Steps to Reproduce

The problem is simple, the `musl` libs are missing from the docker image and the github releases only have the musl libs separately for AMD64. Try to compile any jar with `--static --libc=musl` on Linux.

**Comment by selhagani** [comment]
Hi @spockz,
Thank you for reaching out to us!

As stated in the documentation, using Linux x64 is a prerequisite, as static linking is not supported on Linux AArch64. I understand how the error message may have caused some confusion so we are actually working on that [9490](https://github.com/oracle/graal/issues/9490).

**Comment by spockz** [comment]
Ah indeed. I completely missed the “x64” meaning amd64/x86_64 instead of “*64” or “any 64 bit”.Perhaps this could be clarified in the instructions as well as in the compiler message. How should I proceed with creating a feature request for this support? A significant part of our development happens on Apple silicon devices. Having to setup dynamic and static builds just for this instead of only static builds is additional overhead.On 20 Dec 2024, at 22:16, Soufiane Elhagani ***@***.***> wrote:﻿
Hi @spockz,
Thank you for reaching out to us!
As stated in the documentation, using Linux x64 is a prerequisite, as static linking is not supported on Linux AArch64. I understand how the error message may have caused some confusion so we are actually working on that 9490.
