### ISSUE TITLE
Running Java code with Graal SDK

### ISSUE THREAD

**Issue by rahmanusta** [oracle/graal#1049]
Hi, how can I run Java code via Graal API. When I try to run Java code I get the following error:

"A language with id 'java' is not installed. Installed languages are: [R, js, python, llvm, ruby]."

**Comment by neomatrix369** [comment]
Hi @rahmanusta in my limited understanding, you might be getting this error because due to Java not being available as a Truffle-d language yet, from the list of languages published in the error messages, they look like Truffle languages to me - running via the Truffle interpreter.

Someone please correct me if I'm saying wrong stuff.

**Comment by neomatrix369** [comment]
See http://www.graalvm.org/sdk/javadoc/org/graalvm/polyglot/package-summary.html - the docs talk about embedding guest languages, Java is not yet (is it still in the planning to make it a guest language?) guest language on the GraalVM.

**Comment by neomatrix369** [comment]
I'm happy to experiment with this although maybe a long shot for a single person, and I'm not sure what depth of language and compiler experience is expected.

**Comment by mukel** [comment]
There's an ongoing effort to provide Java as a Truffle guest language with all the added goodies: seamless interop, language-level sand-boxing...
Our Java implementation can already run way past HelloWorld, it can compile itself (with both `javac` and `ecj`), it can run itself (it's meta-circular) but it's still not ready for prime time.

**Comment by rahmanusta** [comment]
Thanks @neomatrix369 @mukel . I'm working on an open-source live code share project which uses GraalVM and Graal API. I noticed and surprised that it doesn't support Java :) Good to hear you work on that.

First prototype of the project:
![image](https://user-images.githubusercontent.com/1158804/54060219-30ee5300-41fc-11e9-832b-d8bc2d2a0d7e.png)

**Comment by neomatrix369** [comment]
> Thanks @neomatrix369 @mukel . I'm working on an open-source live code share project which uses GraalVM and Graal API. I noticed and surprised that it doesn't support Java :) Good to hear you work on that.
> 
> First prototype of the project:
> ![image](https://user-images.githubusercontent.com/1158804/54060219-30ee5300-41fc-11e9-832b-d8bc2d2a0d7e.png)

@rahmanusta Have you tried building GraalVM from github? See https://github.com/neomatrix369/awesome-graal/tree/master/build/x86_64/linux_macos on how it can be done.

**Comment by rahmanusta** [comment]
Thanks @neomatrix369 I'll look it. I'm currently use graalvm's docker image from oracle/graalvm-ce

**Comment by rahmanusta** [comment]
So, what is the status @boris-spas ?

**Comment by boris-spas** [comment]
https://github.com/oracle/graal/issues/1656#issuecomment-527882248
