### ISSUE TITLE
Native image - support for app icon

### ISSUE THREAD

**Issue by rsvoboda** [oracle/graal#1051]
Native image - support for app icon

This could be useful when people create custom utilities and want to use and distribute them in their favourite OS - especially macOS and Windows (Substrate VM hopefully available soon) when apps are executed from UI rather than from console.

Some OS related guidelines for app icons
 * https://developer.apple.com/design/human-interface-guidelines/macos/icons-and-images/app-icon
 * https://docs.microsoft.com/en-us/windows/uwp/design/style/app-icons-and-logos
 * https://developer.gnome.org/integration-guide/stable/desktop-files.html.en

**Comment by mbbee** [comment]
if someone uses native-image-maven-plugin:
this dirty hack works
```
<plugin><!-- add an icon to .exe   with RCEDIT64.exe from https://github.com/poidasmith/winrun4j/releases -->
 <groupId>org.codehaus.mojo</groupId>
 <artifactId>exec-maven-plugin</artifactId>
 <version>1.6.0</version>
 <executions>
   <execution>
 	<phase>package</phase>
 	<goals>
 	   <goal>exec</goal>
 	</goals>
   </execution>
 </executions>
 <configuration>
   <executable>RCEDIT64.exe</executable>
   <arguments>
 	 <argument>/I</argument>
 	 <argument>target/programfile.exe</argument>
 	 <argument>iconname.ico</argument>
   </arguments>
 </configuration>
 </plugin>
```

**Comment by soynomm** [comment]
I'm not sure why this issue has been closed. Do you consider the dirty hack above as a sufficient enough solution? Are there plans to make this a native option for GraalVM?

**Comment by 71a1562385057d498290** [comment]
Just in case somebody stumbles on this. 
On **Windows** systems, a simple solution would be to pass the resource to the Microsoft linker by using `-H:NativeLinkerOption`.  
   
Let's say your icon file is `app.ico`. Create a resource file, say `app.rc`, with the following content
```
IDI_ICON_1 ICON "app.ico"
```
Next, compile the resource file by using the resource compiler
```
rc app.rc
```
Take the resulting `app.res` and pass it to the Microsoft linker when creating the native image
```
native-image.cmd -H:NativeLinkerOption="\path\to\app.res" ...
```
The icon should now be embedded into the generated native image.  
    
    
MSVC linker reference: https://learn.microsoft.com/en-us/cpp/build/reference/linking  
Working with Resource Files: https://learn.microsoft.com/en-us/cpp/windows/working-with-resource-files  
Menus and Other Resources: https://learn.microsoft.com/en-us/windows/win32/menurc/resources  
  
  
On **Linux** systems, AFAIK, application icons are not embedded into the binary.

**Comment by elronsmith** [comment]
> Just in case somebody stumbles onto this. On **Windows** systems, a simple solution would be to pass the resource to the Microsoft linker by using `-H:NativeLinkerOption`.
> 
> Let's say your icon file is `app.ico`. Create a resource file, say `app.rc`, with the following content
> 
> ```
> IDI_ICON_1 ICON "app.ico"
> ```
> 
> Next, compile the resource file by using the resource compiler
> 
> ```
> rc app.rc
> ```
> 
> Take the resulting `app.res` and pass it to the Microsoft linker when creating the native image
> 
> ```
> native-image.cmd -H:NativeLinkerOption="\path\to\app.res" ...
> ```
> 
> The icon should now be embedded into the generated native image.
> 
> MSVC linker reference: https://learn.microsoft.com/en-us/cpp/build/reference/linking Working with Resource Files: https://learn.microsoft.com/en-us/cpp/windows/working-with-resource-files Menus and Other Resources: https://learn.microsoft.com/en-us/windows/win32/menurc/resources
> 
> On **Linux** systems, AFAIK, application icons are not embedded into the binary.

I make the .res-file, then build and have an error:
```
LINK : fatal error LNK1181: ?? ????? ?????? ????? ?? "app.res"
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.image.NativeImageViaCC.handleLinkerFailure(NativeImageViaCC.java:201)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.image.NativeImageViaCC.runLinkerCommand(NativeImageViaCC.java:151)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.image.NativeImageViaCC.write(NativeImageViaCC.java:117)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:732)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:537)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:526)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:701)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.start(NativeImageGeneratorRunner.java:140)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:95)
```
GraalVM version:
```
 Java version: 22.0.2+9, vendor version: Oracle GraalVM 22.0.2+9.1
 Graal compiler: optimization level: 0, target machine: compatibility, PGO: off
 C compiler: cl.exe (microsoft, x64, 19.40.33811)
 Garbage collector: Serial GC (max heap size: 80% of RAM)
```

**Comment by AbrashovMaxim** [comment]
> I'm not sure why this issue has been closed. Do you consider the dirty hack above as a sufficient enough solution? Are there plans to make this a native option for GraalVM?

I agree with him, will there be a built-in ability to install icons for native applications for Windows????
