### ISSUE TITLE
Unable to execute bitcode with sulong

### ISSUE THREAD

**Issue by cstehreem** [oracle/graal#1052]
I have been trying to execute a very simple C program's bitcode using Sulong but I am getting following error:

`Cannot convert LLVMTypedForeignObject+0x0 to LLVMNativePointer
	at <llvm> null(Unknown)
`
Steps I performed:
1. Checked out GraalVM code from official repo.
2. Built Graal using mx
3. Built Sulong 
4. Compiled a Hello World program with clang -c -emit-llvm -o test.bc test.c (Using Clang 8.0)

However when I try to run `mx lli test.bc` or `mx --dynamicimport /compiler --jdk jvmci lli test.bc,` I get above mentioned error. 

Related issues weren't much help as they are for Ruby. Am I missing something obvious here?

**Comment by fniephaus** [comment]
Sounds like a bug. I think there's also an `lli` binary in GraalVM's `bin/` directory. What happens when you run it with that?

**Comment by cstehreem** [comment]
Hi @fniephaus,

I checked out a clean version and rebuilt it and the error seems to have gone away. Not sure what caused it but since it's resolved I am closing the issue.

Thanks for taking time to suggest a solution.

Tehreem

**Comment by fniephaus** [comment]
Glad it's working for you now :)

**Comment by volth** [comment]
> Compiled a Hello World program with `clang -c -emit-llvm -o test.bc test.c` (Using Clang 8.0)

I just hit this problem with the latest graal 19.1.1
solved by adding -O1 to clang flags

C files are `sulong/tests/com.oracle.truffle.llvm.tests.interop/interop/interop002.c` and above (interop001.c has no problem)
