### ISSUE TITLE
Understanding how C code is JIT compiled.

### ISSUE THREAD

**Issue by cstehreem** [oracle/graal#1053]
I am new to JVM and trying GraalVM as it promises interoperability among different languages. My focus is on understanding how it interprets/JIT compiles C code. I have a few questions I wasn't able to find answers to, if the questions are too basic, please refer me to a more appropriate forum. I wasn't able to find a room on Gitter dedicated to Sulong discussion.

I have built Sulong and Graal using mx and now experimenting with different programs. From what I understand so far, `mx lli test.bc` simply interprets the C code and does not JIT compile it. But Graal can optionally be used to JIT compile hot parts of the program with `mx --dynamicimport /compiler --jdk jvmci lli test.bc`

My questions:
1. Does Sulong work as a standalone interpreter in case of no JIT compilation and doesn't need the JVM to run?
2. When compiling with Graal, JVM is needed, so is the llvm bitcode being translated into Java Bytecode first and then run on JVM?
3. What actually triggers the JIT compilation? Sulong or the underlying JVM? It says here on [GraalVM's website](http://www.graalvm.org/docs/reference-manual/languages/llvm/) 

> In contrast to static compilation that is normally used for LLVM based languages, LLI first interprets the bitcode and then dynamically compiles the hot parts of the program using the Graal compiler.

So is it the interpreter's job to decide to compile something or JVM's?

4. Is there any way I can actually see the compilation happening at run time? I wasn't able to attach jProfiler to it for some reason. Also tried `--jvm.Dgraal.TraceTruffleCompilation=true` but it doesn't print anything other than my program's output. Am I missing something?

Thank you

**Comment by cstehreem** [comment]
Hi,

Anyone around to answer these questions?

Thanks

**Comment by boris-spas** [comment]
I'll take a crack at it. Please note that I will simplify things here quite a bit and that there is quite a bit of overlapping terminology so it gets a bit confusing. Feel free to follow up.

> Does Sulong work as a standalone interpreter in case of no JIT compilation and doesn't need the JVM to run?

JIT compilation does not really play a role here. Sulong is a LLVM bitcode interpreter written in java, so in order to run it you need to execute its java bytecode (normally using a JVM). That said, GraalVM comes with a tool to ahead-of-time compile java code to native (called native-image) that will translate the interpreter from java to native allowing one to run Sulong as a native application without a JVM. 

> When compiling with Graal, JVM is needed, so is the llvm bitcode being translated into Java Bytecode first and then run on JVM?

No. Sulong is written using Truffle, a framework for implementing AST interpreters, meaning that the LLVM bitcode is interpreted directly and not translated into JVM bytecode.

> What actually triggers the JIT compilation? Sulong or the underlying JVM? It says here on GraalVM's website
> In contrast to static compilation that is normally used for LLVM based languages, LLI first interprets the bitcode and then dynamically compiles the hot parts of the program using the Graal compiler.
> 
> So is it the interpreter's job to decide to compile something or JVM's?

The interpreter. This is standard operating procedure for dynamic language runtimes. The interpreter starts interpreting the LLVM bitcode and once a part (say a function) is interpreted enough times the interpreter decides that it is "hot" (i.e. frequently executed) and should probably be compiled to make it faster. The interpreter (or to be more precise, the Truffle framework on which the interpreter is build) compiles that function (Note: this is technically wrong, since it actually partially evaluates the interpreter with the LLVM bitcode but for simplicity you can think of it as the LLVM bitcode being compiled.)

> Is there any way I can actually see the compilation happening at run time? I wasn't able to attach jProfiler to it for some reason. Also tried --jvm.Dgraal.TraceTruffleCompilation=true but it doesn't print anything other than my program's output. Am I missing something?

Dgraal.TraceTruffleCompilation=true should work but note that you need to execute the code sufficiently long for the runtime to identify the "hot" parts and compile them. Try running the function you want to see compiled in a loop 100_000 times, that should ensure it.

Hope that helps!

**Comment by cstehreem** [comment]
Thank you for explaining things. This makes sense. 

I am running a loop to 1000000 iterations and it is still not printing any compilation trace. Here is my code:

`#include<stdio.h>
int main (void) {
int a  = 0;
	while(a != 1000000) {
		a++;
	}
return 0;
}`

I am generating bitcode with Clang 6.0 using this command:
`clang -c -g -emit-llvm -o test.bc test.c`

And then running it with following command:
`mx --dynamicimport /compiler --jdk jvmci lli --vm.Dgraal.TraceTruffleCompilation=true test.bc`

Am I missing something? Nothing gets printed when I run it.

**Comment by mukel** [comment]
Try `-J-Dgraal.TraceTruffleCompilation=true` just before lli. -J... passes arguments to the underlying VM.

**Comment by mukel** [comment]
But compilation may not be triggered, not sure if Sulong supports OSR (in simple terms: jump to compiled code in the middle of a loop). As Boris mentioned put your code in a function and call it in a loop, a plain loop won't be compiled without OSR.

**Comment by boris-spas** [comment]
It will trigger some internal stuff to be compiled:
```
./bin/lli --vm.Dgraal.TraceTruffleCompilation=true test.bc                                                                                                   
[truffle] opt done         READRootNode@61bac63 <opt>                                  |ASTSize       4/    4 |Time    20(   2+18  )ms |DirectCallNodes I    0/D    0 |GraalNodes    41/  121 |CodeSize          372 |CodeAddress 0x7f8867ad9000 |Source            n/a 
[truffle] opt done         __sulong_byte_array_to_native <opt>                         |ASTSize     122/  128 |Time    72(  43+29  )ms |DirectCallNodes I    2/D    0 |GraalNodes   310/  537 |CodeSize         1447 |CodeAddress 0x7f8867ad8000 |Source      crt0.c:59 
```

**Comment by cstehreem** [comment]
ok pointing JAVA_HOME to pre-built GraalVM image is printing compilation trace fine `lli --vm.Dgraal.TraceTruffleCompilation=true test.bc `.

However, if I try it from my own build and run using `mx lli --vm.Dgraal.TraceTruffleCompilation=true test.bc`, it doesn't print anything. Any ideas?

I changed code to make it infinite loop and also calling it in a function now.

**Comment by rschatz** [comment]
You need to do `mx --dynamicimport /compiler lli --vm.Dgraal.TraceTruffleCompilation=true test.bc`. Without the `--dynamicimport /compiler` it doesn't include the Graal compiler and therefore will never compile anything.

In a built GraalVM image, the compiler is included by default.

**Comment by cstehreem** [comment]
Tried that too, no luck...

**Comment by rschatz** [comment]
Whoops, sorry, forgot a flag. It's also missing `--jdk jvmci`, to actually put the compiler onto the classpath.

```
$ mx --dy /compiler --jdk jvmci lli -Dgraal.TraceTruffleCompilation=true test.bc
[Use -Dgraal.LogFile=<path> to redirect Graal log output to a file.]
[truffle] opt done         __sulong_byte_array_to_native <opt>                         |ASTSize     129/  129 |Time   468( 390+77  )ms |DirectCallNodes I    0/D    0 |GraalNodes   205/  302 |CodeSize          877 |CodeAddress 0x7fdb1d3623d0 |Source      crt0.c:59
[truffle] opt done         foo <opt>                                                   |ASTSize      74/   74 |Time   473( 314+159 )ms |DirectCallNodes I    0/D    0 |GraalNodes   219/  249 |CodeSize          883 |CodeAddress 0x7fdb1d363f50 |Source       test.c:3
```

In general, if you want to test things that integrate multiple components of GraalVM (as in this case, Sulong + compiler), it's often easier to just build a GraalVM image containing these components, instead of working with `mx` from the source directory.

To do that, go to the `vm` directory and build it using this command:
```
mx --dynamicimport /sulong,/compiler build
```

This will build a custom GraalVM containing *only* the compiler and Sulong (i.e. no js, no native-image). You'll get a symlink `latest_graalvm_home` pointing to the result:
```
$ ./latest_graalvm_home/bin/lli --vm.Dgraal.TraceTruffleCompilation=true ~/test/c/test.bc
[Use -Dgraal.LogFile=<path> to redirect Graal log output to a file.]
[truffle] opt done         foo <opt>                                                   |ASTSize      74/   74 |Time   282( 238+44  )ms |DirectCallNodes I    0/D    0 |GraalNodes   219/  249 |CodeSize          883 |CodeAddress 0x7f6fe47af1d0 |Source       test.c:3
[truffle] opt done         __sulong_byte_array_to_native <opt>                         |ASTSize     129/  129 |Time   527( 485+42  )ms |DirectCallNodes I    0/D    0 |GraalNodes   205/  302 |CodeSize          877 |CodeAddress 0x7f6fe47e70d0 |Source      crt0.c:59
```

**Comment by cstehreem** [comment]
Trying to build native image gives me 
`OSError: [Errno 2] No such file or directory
Building com.oracle.truffle.llvm.libraries.bitcode with GNU Make failed
1 build tasks failed`

Whole Trace:
` mx --dynamicimport /sulong,/compiler build
JAVA_HOME: /home/tehreem/sulong-dev-old/labsjdk1.8.0_202-jvmci-0.57
EXTRA_JAVA_HOMES: 
Dependencies removed from build:
 project com.oracle.truffle.dsl.processor.jdk9 was removed as JDK 9 is not available
 project jdk.tools.jaotc.binformat was removed as JDK 11 is not available
 project jdk.tools.jaotc was removed as JDK 11 is not available
 project org.graalvm.compiler.hotspot.jdk11 was removed as JDK 11 is not available
 project org.graalvm.compiler.hotspot.jdk12 was removed as JDK 12 is not available
 project org.graalvm.compiler.hotspot.jdk13 was removed as JDK 13 is not available
 project org.graalvm.compiler.replacements.jdk12.test was removed as JDK 12 is not available
 project org.graalvm.compiler.core.jdk9.test was removed as JDK 9 is not available
 project org.graalvm.compiler.serviceprovider.jdk9 was removed as JDK 9 is not available
 project org.graalvm.compiler.hotspot.jdk9.test was removed as JDK 9 is not available
 project org.graalvm.compiler.lir.aarch64.jdk11 was removed as JDK 11 is not available
 project org.graalvm.compiler.replacements.jdk9.test was removed as JDK 9 is not available
 project jdk.tools.jaotc.test was removed as JDK 11 is not available
 project org.graalvm.compiler.hotspot.management.jdk11 was removed as JDK 11 is not available
 project org.graalvm.compiler.truffle.runtime.serviceprovider.jdk9 was removed as JDK 9 is not available
 project org.graalvm.compiler.replacements.jdk9_11.test was removed as JDK 9 is not available
 project org.graalvm.compiler.truffle.runtime.hotspot.jdk9 was removed as JDK 9 is not available
 distribution JAOTC was removed as all its dependencies were removed
 distribution JAOTC_TEST was removed as all its dependencies were removed
Non-default dependencies removed from build (use mx build --all to build them):
 com.oracle.truffle.llvm.tests.interop
 com.oracle.truffle.llvm.tests.irdebug
 parserTorture
 gcc_fortran
 com.oracle.truffle.llvm.tests.sulongavx
 com.oracle.truffle.llvm.pipe.native
 com.oracle.truffle.llvm.test.native
 com.oracle.truffle.llvm.tests.bitcodeformat
 gcc_c
 com.oracle.truffle.llvm.pipe
 com.oracle.truffle.llvm.tests.sulongcpp
 nwcc
 inlineassemblytests
 com.oracle.truffle.llvm.tests.sulong
 com.oracle.truffle.llvm.tests.libc
 other
 com.oracle.truffle.llvm.tests.debug
 llvm
 com.oracle.truffle.llvm.tests.bitcode
 shootout
 gcc_cpp
 JACOCOREPORT_0.8.2
 SULONG_TEST_NATIVE
 SULONG_TEST
 SULONG_TEST_SUITES
Process Process-21:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/home/tehreem/sulong-dev/mx/mx.py", line 12836, in executeTask
    task.execute()
  File "/home/tehreem/sulong-dev/mx/mx.py", line 959, in execute
    buildNeeded, reason = self.needsBuild(newestInput)
  File "/home/tehreem/sulong-dev/mx/mx.py", line 4487, in needsBuild
    cmdline, cwd, env = self._build_run_args()
  File "/home/tehreem/sulong-dev/mx/mx.py", line 4475, in _build_run_args
    env.update(self.subject.getBuildEnv())
  File "/home/tehreem/sulong-dev/mx/mx.py", line 4378, in getBuildEnv
    ret[key] = replaceVar.substitute(value, dependency=self)
  File "/home/tehreem/sulong-dev/mx/mx_subst.py", line 86, in substitute
    return re.sub(r'<([\w\-]+?)(:(.+?))?>', lambda m: self._replace(m, self.skip_unknown_substitutions, **kwArgs), string)
  File "/usr/lib/python2.7/re.py", line 155, in sub
    return _compile(pattern, flags).sub(repl, string, count)
  File "/home/tehreem/sulong-dev/mx/mx_subst.py", line 86, in <lambda>
    return re.sub(r'<([\w\-]+?)(:(.+?))?>', lambda m: self._replace(m, self.skip_unknown_substitutions, **kwArgs), string)
  File "/home/tehreem/sulong-dev/mx/mx_subst.py", line 75, in _replace
    return fn()
  File "/home/tehreem/sulong-dev/graal/sulong/mx.sulong/mx_sulong.py", line 554, in getClangImplicitArgs
    mainLLVMVersion = getLLVMVersion(mx_buildtools.ClangCompiler.CLANG)
  File "/home/tehreem/sulong-dev/graal/sulong/mx.sulong/mx_sulong.py", line 537, in getLLVMVersion
    versionString = getVersion(llvmProgram)
  File "/home/tehreem/sulong-dev/graal/sulong/mx.sulong/mx_sulong.py", line 529, in getVersion
    versionString = subprocess.check_output([program, '--version'])
  File "/usr/lib/python2.7/subprocess.py", line 216, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
Building com.oracle.truffle.llvm.libraries.bitcode with GNU Make failed
1 build tasks failed
`

**Comment by cstehreem** [comment]
as for the first method it finally worked with `mx --dynamicimport /compiler --jdk jvmci lli -Dgraal.TraceTruffleCompilation=true test.bc`
What I was doing wrong was typing `--jvm.Dgraal.TraceTruffleCompilation=true` instead of `-Dgraal.TraceTruffleCompilation=true`. Not sure why that matters though. Aren't we supposed to use vm or jvm before Dgraal?
