### ISSUE TITLE
[native-image] Static binary causes a segfault

### ISSUE THREAD

**Issue by katox** [oracle/graal#1054]
A simple application that connects to a PostgresQL database fails to run when compiled as a static linux binary. It works if there is no `--static` flag for `native-image`.

The database doesn't even have to be running - the App crashes before it connects.

```
)$ ./graal-pg-client-1.0-SNAPSHOT 
2019-03-11T10:48:19 FINE java.util.logging.LogManager$RootLogger log Trying to connect to PostgreSQL database jdbc:postgresql://localhost/postgres?user=postgres&password=postgres
[main] INFO com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Starting...
2019-03-11T10:48:19 FINE org.postgresql.Driver loadDefaultProperties Loading driver configuration via classloader java.lang.ClassLoader@1383638
...
2019-03-11T10:48:19 FINE org.postgresql.jdbc.PgConnection <init> PostgreSQL JDBC Driver 42.2.5
...
2019-03-11T10:48:19 FINE org.postgresql.core.v3.ConnectionFactoryImpl openConnectionImpl Trying to establish a protocol version 3 connection to localhost:5432
“./graal-pg-client-1.0-SNAPSHOT” terminated by signal SIGSEGV (Address boundary error)
```

The repo to reproduce the issue: https://github.com/katox/graal-pg-client

**Comment by olpaw** [comment]
@katox before I dig in deeper can you try if the problem goes away if you replace the database URL with 
`jdbc:postgresql://127.0.0.1/postgres?user=postgres&password=postgres` (i.e. avoiding DNS to be involved - see https://stackoverflow.com/questions/3430400/linux-static-linking-is-dead for more info)

**Comment by katox** [comment]
@olpaw good catch, it does work if it doesn't attempt to DNS resolve the address.

Looking at the thread it's probably a bad idea to consider static linking at all.

**Comment by olpaw** [comment]
> Looking at the thread it's probably a bad idea to consider static linking at all.

It's certainly a feature that should only be used if you know exactly what you are doing and you are aware of its limitations. But if you are fine with that .... well .... it can be quite handy to have a static executable (e.g. for docker).

**Comment by katox** [comment]
@olpaw yes, the docker was intended target. It could do without a DNS relying on some other mechanism to resolve to real addresses but I'm not sure.

I worked around this by installing graal into the target docker, let it compile and link to shared libraries within the container and then copied all used shared libraries into FROM scratch container along with the generated app binary.

**Comment by olpaw** [comment]
> I worked around this by installing graal into the target docker, let it compile and link to shared libraries within the container and then copied all used shared libraries into FROM scratch container along with the generated app binary.

Sounds legit.
