### ISSUE TITLE
SubstrateVM: instanceof retains types

### ISSUE THREAD

**Issue by ejona86** [oracle/graal#1061]
In https://github.com/grpc/grpc-java/issues/5460 there was a request for gRPC to improve compatibility with AOT/native-image with GraalVM. Looking into one of the failures, it seems it should be handled by SubstrateVM.

gRPC at one point [prints out debug information](https://github.com/grpc/grpc-java/blob/v1.18.0/netty/src/main/java/io/grpc/netty/ProtocolNegotiators.java#L406) for our SSL environment. It contains the following line:
```java
    if (engine instanceof OpenSslEngine) {
```

It appears this line causes SubstrateVM to fail with `Unsupported type io.netty.handler.ssl.ReferenceCountedOpenSslEngine is reachable` (as `OpenSslEngine` extends `ReferenceCountedOpenSslEngine`). But it seems SubstrateVM should just treat the `instanceof` result as `false`, since there is no way for that type to be created as any instantiation site would receive the error.

```
Error: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: Unsupported type io.netty.handler.ssl.ReferenceCountedOpenSslEngine is reachable
To diagnose the issue, you can add the option --report-unsupported-elements-at-runtime. The unsupported element is then reported at run time when it is accessed the first time.
Trace: 
	at parsing io.grpc.netty.ProtocolNegotiators.logSslEngineDetails(ProtocolNegotiators.java:406)
Call path from entry point to io.grpc.netty.ProtocolNegotiators.logSslEngineDetails(Level, ChannelHandlerContext, String, Throwable): 
	at io.grpc.netty.ProtocolNegotiators.logSslEngineDetails(ProtocolNegotiators.java:397)
	at io.grpc.netty.ProtocolNegotiators$ServerTlsHandler.fail(ProtocolNegotiators.java:190)
	at io.grpc.netty.ProtocolNegotiators$ServerTlsHandler.exceptionCaught(ProtocolNegotiators.java:152)
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:285)
	at io.netty.channel.AbstractChannelHandlerContext.access$400(AbstractChannelHandlerContext.java:38)
	at io.netty.channel.AbstractChannelHandlerContext$5.run(AbstractChannelHandlerContext.java:270)
	at com.oracle.svm.core.jdk.RuntimeSupport.executeHooks(RuntimeSupport.java:144)
	at com.oracle.svm.core.jdk.RuntimeSupport.executeStartupHooks(RuntimeSupport.java:89)
	at com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:144)
	at com.oracle.svm.core.code.IsolateEnterStub.JavaMainWrapper_run_5087f5482cc9a6abc971913ece43acb471d2631b(generated:0)
--------------------------------------------------------------------------------------------
-- WARNING: The above stack trace is not a real stack trace, it is a theoretical call tree---
-- If an interface has multiple implementations SVM will just display one potential call  ---
-- path to the interface. This is often meaningless, and what you actually need to know is---
-- the path to the constructor of the object that implements this interface.              ---
-- Quarkus has attempted to generate a more meaningful call flow analysis below          ---
---------------------------------------------------------------------------------------------
```

-----

To trigger this, I used https://github.com/hpehl/quarkus-grpc-quickstart which uses https://github.com/hpehl/quarkus-grpc-extension. I modified the extension [to remove the `@Substitute`](https://github.com/hpehl/quarkus-grpc-extension/blob/e461cef5f167034141daba4c73fcbf3fdf40fd94/runtime/src/main/java/io/quarkus/grpc/runtime/graal/GrpcNettySubstitutions.java#L26-L37).

I have glanced over the [LIMITATIONS](https://github.com/oracle/graal/blob/master/substratevm/LIMITATIONS.md), but I didn't see any obvious workaround that gRPC could place in its code to avoid the need for `@Substitute` so that our users could avoid the annoyance.

FYI: I'm going on ~2 weeks of vacation in a few days, so I may be delayed in responding to followup questions for a period of time.

**Comment by cstancu** [comment]
Looking at the error message it seems that `io.netty.handler.ssl.ReferenceCountedOpenSslEngine` is [`@Delete`](https://github.com/oracle/graal/blob/master/substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/annotate/Delete.java#L40)ed, although I am not sure where that is happening as I cannot find the corresponding substitution in the quarkus extension.

**Comment by ejona86** [comment]
@cstancu, hmm... I see, yeah, the error message does tend to be for a clearly "ain't gonna work" type.

I was _really_ surprised earlier that Netty worked without any real changes. #917 linked to bits of more of what I would expect, as I knew there were Unsafe field indexes that would need to be updated and I questioned some of the static initialization. I dug deeper and started figuring out how this quarkus thing works. It appears there is a quarkus-netty and quarkus-grpc has a dependency on it.

So [this appears to be the `@Delete`](https://github.com/quarkusio/quarkus/blob/549c74d/extensions/netty/runtime/src/main/java/io/quarkus/netty/runtime/graal/NettySubstitutions.java#L105). Okay, at least that part is clear. But it does still seem like an `instanceof` shouldn't retain a type.

**Comment by cstancu** [comment]
@ejona86 thanks for digging deeper. That type being `@Delete` in the quarkus-netty extension explains it. However, if you use `--report-unsupported-elements-at-runtime` as the error message suggests this should work exactly as expected, `if (engine instanceof OpenSslEngine)` should always be false at runtime. 

Check out [this gist](https://gist.github.com/cstancu/e5158a91c3e1181ea34ac8dec6509fb5) for a quick test.

**Comment by cstancu** [comment]
I am closing this as the originally reported behavior is fixed by the use of `--report-unsupported-elements-at-runtime`.
