### ISSUE TITLE
Do Graal native images run faster than the Java bytecode ordinarily produced

### ISSUE THREAD

**Issue by theonlygusti** [oracle/graal#1069]
If I compile a Java project I've been working on into a native image using Graal, will its performance increase?

**Comment by plokhotnyuk** [comment]
It depends.

Best option is to use [profile guided optimization](https://github.com/graalvm/graalvm-demos/tree/master/scala-days-2018/streams#profile-guided-optimizations-with-native-image).

**Comment by tarsa** [comment]
AFAIK currently executables produced by native-image have lower peak performance than the original Java code running under GraalVM JIT. OTOH native-image starts faster and can have much lower memory overhead for simple applications.

Here is some comparison: https://benchmarksgame-team.pages.debian.net/benchmarksgame/faster/java-substratevm.html

**Comment by theonlygusti** [comment]
So it's better (more performant) to just use Java, Graal images are less efficient at the moment?

**Comment by plokhotnyuk** [comment]
@ theonlygusti it depends on your algorithms and workload...

[Here](http://jmh.morethan.io/?sources=https://plokhotnyuk.github.io/jsoniter-scala/openjdk11graal.json,https://plokhotnyuk.github.io/jsoniter-scala/graalvmce1.json) are results of benchmark of JSON parsing and serialization of different libraries. But those which use a lot of divisions are slower (up to 4x times) on outdated Graal JIT compiler then on latest GraalVM CE 1.0.0 RC13.

**Comment by tarsa** [comment]
Peak performance of Graal AOT (native-image) is slower than Graal JIT. You need to benchmark Graal in exactly the compilation mode you're interested in.

**Comment by tarsa** [comment]
My impression is that the following properties hold:

Warm-up time (from shortest to longest):
- GraalVM AOT = native-image (compilation is fully done before execution, so there's no JIT warm-up)
- HotSpot
- GraalVM CE JIT
- GraalVM EE JIT

Peak performance (from lowest to highest):
- GraalVM AOT = native image
- HotSpot/ GraalVM CE JIT - HotSpot should be better at vectorization, GraalVM CE JIT should be better at optimizing object oriented code (smarter devirtualization, inlining, escape analysis, etc)
- GraalVM EE JIT - has both strong vectorization and strong OO code optimizations

GraalVM JIT warm-up time (and other types of overhead) should improve over time, eventually making it a drop-in replacement for HotSpot. GraalVM AOT peak performance should also improve over time, but I'm rather skeptical that it will match the JIT mode of GraalVM. OTOH GraalVM AOT could match HotSpot's performance some day as HotSpot receives little new automatic optimization techniques these days.

All of this is just rough estimation, prediction, etc You need to benchmark your program on regular basis to see which VM and which compilation mode is best for you.

**Comment by thomaswue** [comment]
Yes, these are pretty accurate estimates for the status quo.

We are working on getting warmup of GraalVM CE and GraalVM EE equal to HotSpot by linking a native-image of the Graal compiler with HotSpot. There will be a prototype of this available in the next release candidate.

And we are working on getting GraalVM AOT with PGO to the same level as GraalVM EE JIT. This is a longer term effort and will take quite some time. Assuming reasonably accurate collected profiling feedback, there are no theoretical reasons why we shouldn't reach the same performance.

**Comment by theonlygusti** [comment]
I wish graal native image was like a C program

**Comment by gmpassos** [comment]
Doing some benchmarks, GraalVM has a tendency to be faster. Compiling a DB in pure Java it shows a faster boot, running with native performance (like Hotspot JIT) from the beginning. Overall improvement of performance was from 10% to 20% depending of the operation.

**Comment by avindra** [comment]
Is there any plan to bring [PGO](https://www.graalvm.org/docs/reference-manual/native-image/#profile-guided-optimizations) to the community edition? According to the docs, it requires an enterprise license.

**Comment by thomaswue** [comment]
No, there is no such plan at the moment. Depending on the size of your installation & achieved benefit, the price may vary.
