### ISSUE TITLE
[Question] How to make the native Images faster in Graal VM CE

### ISSUE THREAD

**Issue by mercyblitz** [oracle/graal#1079]
Hi, community,

I'm a newbie and just make a native image for the`HelloWorld` example that wrote in "[Native Images](https://www.graalvm.org/docs/getting-started/#native-images)":

```
$ native-image HelloWorld
Build on Server(pid: 10425, port: 51555)
[helloworld:10425]    classlist:   3,801.59 ms
[helloworld:10425]        (cap):   2,446.27 ms
[helloworld:10425]        setup:   3,382.41 ms
[helloworld:10425]   (typeflow):   2,612.40 ms
[helloworld:10425]    (objects):     670.66 ms
[helloworld:10425]   (features):     130.83 ms
[helloworld:10425]     analysis:   3,473.34 ms
[helloworld:10425]     universe:     104.23 ms
[helloworld:10425]      (parse):     523.72 ms
[helloworld:10425]     (inline):     738.29 ms
[helloworld:10425]    (compile):   2,902.04 ms
[helloworld:10425]      compile:   4,345.18 ms
[helloworld:10425]        image:     324.88 ms
[helloworld:10425]        write:     152.25 ms
[helloworld:10425]      [total]:  15,697.12 ms
```
> My graalvm version is `1.0-RC13`

I found that this image was made too slowly, my question is how to speed up?

**Comment by cstancu** [comment]
@mercyblitz thank you for your question. We use a compilation server in the background so subsequent calls to `native-image HelloWorld` should be faster, roughly twice as fast.

**Comment by mercyblitz** [comment]
@cstancu Is it possible to use it under Build Tools, like Maven or Gradle?

**Comment by cstancu** [comment]
Yes, please read [this article](https://medium.com/graalvm/simplifying-native-image-generation-with-maven-plugin-and-embeddable-configuration-d5b283b92f57) for details on maven support.

**Comment by cstancu** [comment]
By the way, if you have questions you can also check out the `native-image` [gitter channel](https://gitter.im/graalvm/native-image). You may get a faster response there.

**Comment by mercyblitz** [comment]
@cstancu Thanks.
