### ISSUE TITLE
[RC14] Unrecognized VM option 'UseJVMCINativeCompiler'

### ISSUE THREAD

**Issue by fniephaus** [oracle/graal#1080]
The [release notes for RC14](https://www.graalvm.org/docs/release-notes/#10-rc14) explains that `libgraal` can be used by adding `-XX:+UseJVMCINativeCompiler`. However, this gives me a `Unrecognized VM option 'UseJVMCINativeCompiler'` error. Using `-XX:+UseJVMCICompiler -XX:+UseJVMCINativeLibrary`, on the other hand, works as intended. Should the `UseJVMCINativeCompiler` option exist or is it just a copy-and-paste error?

Related: https://github.com/oracle/graal/issues/1055

**Comment by farquet** [comment]
Thanks for the report.
This is indeed a typo in the release notes as you have figured out. They will be updated shortly.
Btw, using `-XX:+UseJVMCINativeLibrary` is sufficient to use libgraal on GraalVM.

**Comment by fniephaus** [comment]
Thanks for the quick fix!
