### ISSUE TITLE
[native-image] Error calling Class::getCanonicalName, as Class.reflectionData not supported

### ISSUE THREAD

**Issue by jperedadnr** [oracle/graal#1092]
In DynamicHub.java, `reflectionData` is marked as not supported yet for JDK9OrLater.

This causes an error when calling `Class::getCanonicalName`, with JDK 11.0.2.

For instance this call:

```
String canonicalName = String.class.getCanonicalName();
```

fails with:

```
Exception in thread "main" com.oracle.svm.core.jdk.UnsupportedFeatureError: JDK9OrLater: DynamicHub.reflectionData()
[SUB]   at com.oracle.svm.core.util.VMError.unsupportedFeature(VMError.java:102)
[SUB]   at java.lang.Class.reflectionData(DynamicHub.java:1182)
[SUB]   at java.lang.Class.getCanonicalName(DynamicHub.java:1608)
[SUB]   at HelloWorld.main
```

**Comment by cstancu** [comment]
This issue looks to have been fixed by https://github.com/oracle/graal/commit/d4b6d2637fca85da2d95286833e8aa5a5e022dd5. Please reopen if that is not the case.
