### ISSUE TITLE
Linking command is not valid

### ISSUE THREAD

**Issue by rmannibucau** [oracle/graal#1097]
Hi,

shouldn't https://github.com/oracle/graal/blob/master/substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/c/NativeLibraries.java#L225 use a LinkedHashSet (to keep the order but also remove duplicates)?

Note that the order in the options (+ the .so) is important and prevents the linking in a lot of cases

Here is a command currently generates graal:

    cc -v -o /home/rmannibucau/1_dev/docosh/org.tomitribe.crest.main -z noexecstack -Wl,--defsym -Wl,main=IsolateEnterStub__JavaMainWrapper__run__5087f5482cc9a6abc971913ece43acb471d2631b__a61fe6c26e84dd4037e4629852b5488bfcc16e7e -L/tmp/SVM-5630025333668814661 -L/home/rmannibucau/softwares/graalvm-ce-1.0.0-rc14/jre/lib -L/home/rmannibucau/softwares/graalvm-ce-1.0.0-rc14/jre/lib/svm/clibraries/linux-amd64 /tmp/SVM-5630025333668814661/org.tomitribe.crest.main.o -lffi -ldl -lpthread -lpthread -ldl -lz -lpthread -lstrictmath -ljvm -llibchelper -lcrypt -lrt -lrt -lrt -lrt -lrt

It outputs:

    /usr/bin/ld: /home/rmannibucau/softwares/graalvm-ce-1.0.0-rc14/jre/lib/svm/clibraries/linux-amd64/libjvm.a(JvmFuncs.o): in function `JVM_FindLibraryEntry':
    /b/b/e/main/substratevm/src/com.oracle.svm.native.jvm.posix/src/JvmFuncs.c:112: undefined reference to `dlsym'

Adding -Wl,--no-as-needed in the command helps but not sure it is the best fix.

If it helps I'm running on ubuntu 18.10

**Comment by olpaw** [comment]
Same as https://github.com/oracle/graal/issues/1098
