### ISSUE TITLE
Stream not correctly supported

### ISSUE THREAD

**Issue by rmannibucau** [oracle/graal#1098]
Hi,

I would expect this code to be supported:

        final List<String> images = lines // lines is a List<String>
                .stream()
                .map(String::trim)
                .filter(it -> it.startsWith("foo:"))
                .map(s -> s.substring("foo:".length()))
                .map(String::trim)
                .sorted()
                .collect(toList());

however it fails with:

    /b/b/e/main/substratevm/src/com.oracle.svm.native.jvm.posix/src/JvmFuncs.c:112: undefined reference to `dlsym'

To make it working I have to rewrite it with a pre-java8 style wich is not very satisfying :s :

            final List<String> lines = Files.readAllLines(path);
            for (final String line : lines) {
                String value = line.trim();
                if (value.startsWith("image:")) {
                    images.add(value.substring("image:".length()).trim());
                }
            }

**Comment by cstancu** [comment]
A similar issue was reported before. Does [this fix ](https://github.com/oracle/graal/issues/1086#issuecomment-475327862) apply to your use case? To check it you can [build a GraalVM distribution from source](https://github.com/oracle/graal/tree/master/vm#vm-suite).

**Comment by rmannibucau** [comment]
Hi @cstancu,

Is there some kind of snapshot or dev version pre-built? Otherwise I can give it a try next week.
Alternatively you can use https://github.com/rmannibucau/docosh (maybe take the broken branch https://github.com/rmannibucau/docosh/blob/broken-graal-threadlocal/ and just "fix" it uncommenting the line in the Launcher class), the code is in src/main/java/com/github/rmannibucau/docker/compose/cli/service/DockerComposeParser.java.

Romain

**Comment by olpaw** [comment]
I'm confident that 5dbe774178c59e34f886fe884dc12cb7f0f6110b also fixes this problem. After all, it ensures that `-ljvm` is not passed to the linker anymore.

Feel free to reopen if you can still reproduce with master. BTW, for this simple sample you can just build master of https://github.com/oracle/graal/tree/master/substratevm (see README.md) ... no need to perform a full graalvm release from source.

**Comment by rmannibucau** [comment]
Hi @olpaw ,

Nice trick to rebuild only substrate :+1: 

I also confirm it fixes my stream issue. Thanks a lot! Guess https://github.com/oracle/graal/issues/1097 is the same then and can be closed as well.

Romain
