### ISSUE TITLE
Weird threadlocal issue with native-image?

### ISSUE THREAD

**Issue by rmannibucau** [oracle/graal#1099]
Hi guys,

I'm not 100% sure of the thread local issue but here is my problem.

I have that code - in a main which is not the class Main referenced here, this one comes from tomitribe-crest library if you want to reproduce:

        final Map<Class<?>, Object> services = singletonMap(Foo.class, new Foo());
        final SystemEnvironment environment = new SystemEnvironment(services);
        Environment.ENVIRONMENT_THREAD_LOCAL.set(environment);
        new Main().main(environment, args);

the environment has a findServices(Class) method just looking up the instance in the services map.

Also note that the first two lines of the Main#main method are:

        final Environment old = Environment.ENVIRONMENT_THREAD_LOCAL.get();
        Environment.ENVIRONMENT_THREAD_LOCAL.set(env);

So it should be useless to set the thread local myself.

Now if I write the previous code more naturally:

        final Map<Class<?>, Object> services = singletonMap(Foo.class, new Foo());
        final SystemEnvironment environment = new SystemEnvironment(services);
        new Main().main(environment, args);

Then the lookup fails.

Can it be some ThreadLocal AOT analysis issue?

**Comment by cstancu** [comment]
I am not sure that I understand what the problem is. Can you please provide a complete example that I can use to reproduce the issue? Do you see the same issue on a JVM?

**Comment by rmannibucau** [comment]
I dont have any issue on a plain jvm. Will try to share a sample tomorrow.

**Comment by rmannibucau** [comment]
Hi @cstancu ,

I pushed my code on github in a branch called broken-graal-threadlocal at https://github.com/rmannibucau/docosh

The interesting part is https://github.com/rmannibucau/docosh/commit/826480551bbf73a1eed8da6118620f93a41b8dda

I suspect some reflection in between is making the threadlocal tracking lost somehow since in a plain main (with 4-5 classes) I didn't reproduce it so it probably means there is some indirection breaking native-image.

If you have any tip to debug such things it can be very valuable and appreciated.

Romain

**Comment by cstancu** [comment]
So the only change in the `broken-graal-threadlocal` brach is commenting out `Environment.ENVIRONMENT_THREAD_LOCAL.set(environment);`?

I tried the `broken-graal-threadlocal` brach both with that line commented and not-commented and the result is the same. The image builds and when I run it I get this, in both cases:
```
$ ./target/docosh-1.0-SNAPSHOT
Commands: 
                       
   help                
   list-images         
```
The only difference is that I use `GraalVM Version 1.0.0-rc15-dev` built from latest sources. Please try and build [from latest sources](https://github.com/oracle/graal/tree/master/vm#vm-suite). You can build a light distribution of GraalVM that only contains `native-image` using: `../graal/vm$ mx --disable-polyglot --disable-libpolyglot --dynamicimports /substratevm build`. If you still see problems please be explicit with what the actual failure is.

**Comment by rmannibucau** [comment]
I can confirm it works with master, thanks a lot!
