### ISSUE TITLE
RC14 profiler is not working

### ISSUE THREAD

**Issue by ericzconfluent** [oracle/graal#1100]
Hello, I am trying to use the profiler before building a native image, but I am getting the following error:

`/b/b/e/graal/substratevm/src/com.oracle.svm.native.agent/src/trace-agent.c:74: Agent_OnLoad: check failed, aborting: strstr(options, output_opt) == options`

**Comment by cstancu** [comment]
The native agent has been reimplemented since RC14. Please [build from source](https://github.com/oracle/graal/tree/master/vm#vm-suite).

**Comment by peter-hofer** [comment]
You're likely missing the `output=` option prefix. The argument to `java` should look like this: `-agentlib:native-image-agent=output=/path/to/output-file.json`.

**Comment by ericzconfluent** [comment]
Yes I figured that out after looking at the commit history of the documentation. However, when running the RC14 EE native-image using the profiler configuration, I am now getting this error:

`Error: Error parsing reflection configuration in /home/eric/workspace/reflection_config/reflect-config.json:
Class com.google.inject.Inject not found
Verify that the configuration matches the schema described in the -H:PrintFlags=+ output for option ReflectionConfigurationFiles.
Error: Use -H:+ReportExceptionStackTraces to print stacktrace of underlying exception
Error: Processing image build request failed
`

This is still RC14 pre re-implementation of the profiler. Do you know anything further about this error? Will the new profiler solve my problems?

**Comment by peter-hofer** [comment]
Is it possible that `com.google.inject.Inject` is not on the classpath of your `native-image` commandline?
