### ISSUE TITLE
Enable NativeImageMojo to download graalvm

### ISSUE THREAD

**Issue by rmannibucau** [oracle/graal#1101]
Hi,

This task is about adding a <graalVersion> and <graalBaseurl> parameters in NativeImageMojo which will download the distibution (CE from github typically, EE from OTN). The version enables to customize which one to download (important: please ensure it is really the maven version of svm, it simplifies the version management in the pom using a property). It can be fancy but optional to default to the latest one.

Overall goal is simply to not have to download manually graal and set up manually JAVA_HOME to use the plugin.

Implementation note: I think it is nice to download the tar.gz/zip, install it in the m2 repo as an artifact, then extract it next to the archive in the m2 to have some cache and not download graal at each build.

Hope it makes sense.

Romain

**Comment by olpaw** [comment]
> Overall goal is simply to not have to download manually graal and set up manually JAVA_HOME to use the plugin.

Our current approach is for users to ensure they have GRAALVM_HOME set up properly prior to image building via maven or gradle.

**Comment by rmannibucau** [comment]
FYI this is supportef by Apache Geronimo Arthur since years (if some user ends here).
