### ISSUE TITLE
Allow multiline <buildArgs> in native-image-maven-plugin

### ISSUE THREAD

**Issue by rmannibucau** [oracle/graal#1102]
There are a lot of options you can pass to native-image but if you try to do it with buildArgs parameter of the maven plugin it is quite hard when you use more than 3-4.

I see two nice options:

1. enable the buildArgs to be multiline and just "re-inline" it, this does not break current mojo and solves the issue,
2. alternatively you can use a List<String> instead of a String which will enable to use multiple tags in maven and also solve the issue

Romain

**Comment by olpaw** [comment]
Fixed in on master (see d1b4f2be573f08fd567bb68097f64c8cfa625849)
You can now use e.g.
```
<configuration>
  <buildArgs>
    --verbose
    -H:Log=InvokeCC
    -H:+PrintAnalysisCallTree
  </buildArgs>
</configuration>
```
instead of 
```
<configuration>
  <buildArgs>--verbose -H:Log=InvokeCC -H:+PrintAnalysisCallTree</buildArgs>
</configuration>
```
