### ISSUE TITLE
RC15 profiler adding invalid characters to trace-file.json

### ISSUE THREAD

**Issue by ericzconfluent** [oracle/graal#1107]
The trace-file.json is full of invalid characters "\00" like the line below:

`{"tracer":"reflect", "function":"newProxyInstance", "caller_class":"sun.reflect.annotation.AnnotationParser$1", "result":true, "args":["\00",["org.graalvm.compiler.graph.Node$Input"],"\00"]},`

This only appears to happen on "function":"newProxyInstance". I have built everything from latest master branch source.

**Comment by peter-hofer** [comment]
Fixed in RC16.
