### ISSUE TITLE
[Question] How can I set maximum heap into a native image?

### ISSUE THREAD

**Issue by larchanjo** [oracle/graal#1109]
Hello I have this Dockerfile

```
FROM maven:3.6.0-jdk-8-alpine as builder
COPY  . /root/app/
WORKDIR /root/app
RUN mvn install

FROM oracle/graalvm-ce:1.0.0-rc11 as graalvm
COPY --from=builder /root/app/ /home/app/
WORKDIR /home/app
RUN java -cp target/micronaut-service-0.1.jar \
            io.micronaut.graal.reflect.GraalClassLoadingAnalyzer \
            reflect.json
RUN native-image --no-server \
                 --class-path target/micronaut-service-0.1.jar \
                 -Xmx=5m \
                 -H:ReflectionConfigurationFiles=/home/app/reflect.json \
                 -H:EnableURLProtocols=http \
                 -H:IncludeResources='logback.xml|application.yml|META-INF/services/*.*' \
                 -H:+ReportUnsupportedElementsAtRuntime \
                 -H:+AllowVMInspection \
                 --rerun-class-initialization-at-runtime='sun.security.jca.JCAUtil$CachedSecureRandomHolder',javax.net.ssl.SSLContext \
                 --delay-class-initialization-to-runtime=io.netty.handler.codec.http.HttpObjectEncoder,io.netty.handler.codec.http.websocketx.WebSocket00FrameEncoder,io.netty.handler.ssl.util.ThreadLocalInsecureRandom \
                 -H:-UseServiceLoaderFeature \
                 --allow-incomplete-classpath \
                 -H:Name=micronaut-service \
                 -H:Class=micronaut.service.Application

FROM frolvlad/alpine-glibc
EXPOSE 8080
COPY --from=graalvm /home/app/micronaut-service .
ENTRYPOINT ["./micronaut-service"]

```
I am trying to pass the option -Xms=5m as specified in [Substrate VM Options](https://github.com/oracle/graal/blob/master/substratevm/OPTIONS.md), but I am receiving the error that the argument is not recognized.

To simulate the problem clone the [project](https://github.com/larchanjo/talk-tdc-2019-micronaut/tree/master/micronaut-service), edit the Dockerfile passing the -Xmx=5m and run the command `sh docker-build.sh`

**Comment by mukel** [comment]
Out of my head try `--native.Xmx5g` (maybe without the dot).

**Comment by larchanjo** [comment]
> Out of my head try `--native.Xmx5g` (maybe without the dot).

Error: Unrecognized option: --native.Xmx5m
Error: Unrecognized option: --native Xmx5m
Error: Unrecognized option: --native=Xmx5m

**Comment by cstancu** [comment]
@larchanjo if you are trying to set the max memory of the GC in the generated image you then need to use `-Xmx` as a run time argument and pass it to the generated image like so: `./myimage -Xmx5m`. You can test that it has the desired effect by printing `java.lang.Runtime.getRuntime().totalMemory()`. We will update the options documentation to make this clear.

If you are trying to set `-Xmx` as a build-time argument, i.e., for the `native-image` process itself, then you need `native-image -J-Xmx` to pass Xmx to the underlying JVM running the native image builder.

**Comment by larchanjo** [comment]
> @larchanjo if you are trying to set the max memory of the GC in the generated image you then need to use `-Xmx` as a run time argument and pass it to the generated image like so: `./myimage -Xmx5m`. You can test that it has the desired effect by printing `java.lang.Runtime.getRuntime().totalMemory()`. We will update the options documentation to make this clear.
> 
> If you are trying to set `-Xmx` as a build-time argument, i.e., for the `native-image` process itself, then you need `native-image -J-Xmx` to pass Xmx to the underlying JVM running the native image builder.

Thanks a million. It works

```
FROM maven:3.6.0-jdk-8-alpine as builder
COPY  . /root/app/
WORKDIR /root/app
RUN mvn install

FROM oracle/graalvm-ce:1.0.0-rc11 as graalvm
COPY --from=builder /root/app/ /home/app/
WORKDIR /home/app
RUN java -cp target/micronaut-service-0.1.jar \
            io.micronaut.graal.reflect.GraalClassLoadingAnalyzer \
            reflect.json
RUN native-image --no-server \
                 --class-path target/micronaut-service-0.1.jar \
                 -H:ReflectionConfigurationFiles=/home/app/reflect.json \
                 -H:EnableURLProtocols=http \
                 -H:IncludeResources='logback.xml|application.yml|META-INF/services/*.*' \
                 -H:+ReportUnsupportedElementsAtRuntime \
                 -H:+AllowVMInspection \
                 --rerun-class-initialization-at-runtime='sun.security.jca.JCAUtil$CachedSecureRandomHolder',javax.net.ssl.SSLContext \
                 --delay-class-initialization-to-runtime=io.netty.handler.codec.http.HttpObjectEncoder,io.netty.handler.codec.http.websocketx.WebSocket00FrameEncoder,io.netty.handler.ssl.util.ThreadLocalInsecureRandom \
                 -H:-UseServiceLoaderFeature \
                 --allow-incomplete-classpath \
                 -H:Name=micronaut-service \
                 -H:Class=micronaut.service.Application


FROM frolvlad/alpine-glibc
EXPOSE 8080
COPY --from=graalvm /home/app/micronaut-service .
ENTRYPOINT ["./micronaut-service", "-Xmx5m"]
```
