### ISSUE TITLE
Unable to build graal from source

### ISSUE THREAD

**Issue by cstehreem** [oracle/graal#1110]
I have been trying to build graal from source but getting a bunch of errors when I try to open the project in eclipse. But I don't seem to get any errors when I build it using mx. The steps I am performing:
1. Checked out entire graal repository.
2. Downloaded jdk-11.0.2 and set JAVA_HOME and PATH
3. cd graal/compiler
4. mx build
5. mx eclipseinit

I am getting about 400 errors currently. All of the sort:
1. The project cannot be built until build path errors are resolved
2. Project org.graalvm.compiler.core.llvm is missing required annotation processor library: '/GRAAL_NODEINFO_PROCESSOR/graal-nodeinfo-processor.jar'	org.graalvm.compiler.core.llvm

My questions are: 
1. Is there any indication graal was successfully built using mx?
2. Do I specifically need to build it using graal-jvmci-8? Although I have tried that too but errors are the same.

**Comment by dougxc** [comment]
I just tried to replicate this on a fresh Graal clone but it all seemed to load and compile fine in Eclipse. For reference, I'm using Eclipse 20180917-1800 and have `JAVA_HOME` set to `/Library/Java/JavaVirtualMachines/jdk-11.0.2.jdk/Contents/Home`. Are you sure you have JDK 11 configured as `jdk-11` in Eclipse (as instructed at the end of the output when running `mx eclipseinit`).

To answer your specific questions:
1. If `mx build` completes without any errors messages, then it succeeded.
2. No.

**Comment by cstehreem** [comment]
> I just tried to replicate this on a fresh Graal clone but it all seemed to load and compile fine in Eclipse. For reference, I'm using Eclipse 20180917-1800 and have `JAVA_HOME` set to `/Library/Java/JavaVirtualMachines/jdk-11.0.2.jdk/Contents/Home`. Are you sure you have JDK 11 configured as `jdk-11` in Eclipse (as instructed at the end of the output when running `mx eclipseinit`).
> 
> To answer your specific questions:
> 
>     1. If `mx build` completes without any errors messages, then it succeeded.
> 
>     2. No.

Is the JAVA_HOME path specific to your system or it should be like this? I have `/home/tehreem/jdk-11.0.2`. Rest everything is similar.

**Comment by dougxc** [comment]
`JAVA_HOME` is always specific to where the JDK is installed. The example I gave just happens to be the location used when installing a JDK 11 on macOS.

**Comment by cstehreem** [comment]
hmm.. I am on Ubuntu 18.04. I will checkout graal again and see if it works.

Thanks

**Comment by cstehreem** [comment]
I tried building from a clean checkout but I am still getting the same errors. Where exactly are these jar files supposed to be?

Also what does `mx vm` do after `mx build`? For me it just prints out a command help guide.

**Comment by neomatrix369** [comment]
@cstehreem Hi, maybe have a look at the code on https://github.com/neomatrix369/awesome-graal/tree/master/build/x86_64/linux_macos to see how it is done, hope this helps.

**Comment by dougxc** [comment]
> Where exactly are these jar files supposed to be?

I assume you're talking about the processor jars.
```
compiler> mx eclipseinit
compiler> find . -name graal-nodeinfo-processor.jar
./mxbuild/dists/jdk1.8/graal-nodeinfo-processor.jar
```

> what does `mx vm` do after `mx build`

Add `-v` after `mx` and you'll see exactly what command is executed. It should produce the moral equivalent of just running `java` without any arguments (which also prints a usage message).
```

**Comment by thala321** [comment]
Hủy
Vào 16:34, Th 3, 26 thg 3, 2019 Douglas Simon <notifications@github.com> đã
viết:

**Comment by angelica-moreira** [comment]
> I tried building from a clean checkout but I am still getting the same errors. Where exactly are these jar files supposed to be?
> 
> Also what does `mx vm` do after `mx build`? For me it just prints out a command help guide.

Hi Tehreem Fatima,

I know this is an old question and maybe you have figured out a way to fix it, but I wanted to let you know that I had the same problems as you. I found out that the main issue, on my side, was that I was trying to use the latest version of Eclipse instead of the recommended version (4.7.3a). You may experience some problems when running this version but the reason might be that you need to use a JDK version 8 and you can download a good match here https://github.com/graalvm/openjdk8-jvmci-builder/releases. Now in regards to your question, if I got it right `mx vm` is like running java :-), so you should pass your main class here, so inside the compiler folder you will do: `mx vm path/to/YourMainClass.java`

**Comment by wirthi** [comment]
Closing this older ticket. We are not aware of build problems currently, as Doug mentioned above, this should work nicely.
