### ISSUE TITLE
native-image-agent exits with "Agent_OnLoad: check failed, aborting"

### ISSUE THREAD

**Issue by dsyer** [oracle/graal#1112]
This happens to me for all apps I tried (e.g. in this case one of @sdeleuze [issue samples](https://github.com/sdeleuze/graal-issues/tree/master/java-util-logging)):

```
$ java -agentlib:native-image-agent=trace-output=trace-file.json -cp target/classes com.sample.App 
/b/b/e/main/substratevm/src/com.oracle.svm.native.agent/src/trace-agent.c:74: Agent_OnLoad: check failed, aborting: strstr(options, output_opt) == options
```

It says in the docks it's supposed to work on Linux, and that's what I have. So what does it mean?

**Comment by gjevardat** [comment]
It works. Actually there is typo in the doc
the command line should be 
native-image-agent=output=trace-file.json and not trace-output

**Comment by dsyer** [comment]
Excellent! Yes that works. But then the docs have other issues, it seems, because I cannot find a `native-image-configure` command anywhere in the Graal distro. Am I missing something?

**Comment by dsyer** [comment]
Nevermind: I found it ("This tool itself must first be built with the command `native-image --tool:native-image-configure`"). But why?

**Comment by peter-hofer** [comment]
We are currently extending the agent with more functionality, which is why we renamed that option to the more specific name of `trace-output` on `master`.
The `native-image-configure` tool must be built with `native-image --tool:native-image-configure` as described in the documentation.

**Comment by dsyer** [comment]
I guess that makes sense. But it doesn't help users of the latest release? Maybe the docs ought to be changed to help people who are trying rc14?

**Comment by gjevardat** [comment]
@dsyer Indeed, I had same issue. Then I reminded that the doc is in sync with current code version not with released ones.
Somehow we should be able to access rc14 doc but I did not search how actually. It should be easy

**Comment by peter-hofer** [comment]
Apologies for the confusion, GitHub most prominently displays the files of `master`, including documentation. You can access the docs of a specific distribution by selecting its tag in the top-left drop-down menu, which in this case, would give you: https://github.com/oracle/graal/blob/vm-1.0.0-rc14/substratevm/CONFIGURE.md
We don't plan on changing the name of the options again, so this issue should disappear with the next release.
