### ISSUE TITLE
Add skip configuration property to native-image-maven-plugin

### ISSUE THREAD

**Issue by pmlopes** [oracle/graal#1113]
In order to allow skiping native builds (say when running builds on environments not currently supported or CI's that are testing other sections of the project, there should be a `skip` configuration property that would avoid running the build.

This is a blocker for https://github.com/netty/netty/pull/8963

**Comment by pmlopes** [comment]
@olpaw could you advise on how to proceed here on the netty issue.

**Comment by olpaw** [comment]
@pmlopes is having such a `skip` configuration property common practice among maven-plugins?

**Comment by olpaw** [comment]
i.e. can this also be addressed by binding the plugin execution to a profile.
see https://maven.apache.org/guides/introduction/introduction-to-profiles.html

**Comment by pmlopes** [comment]
skip configuration is quite common on many pluging, e.g.: failsafe, surefire, exec, etc... profiles are another alternative but it can become quite messy or complicated to setup, specially in the netty case:

In their case, they skip plugins when the build is run with `skipTests` or a specific skip property, so their advice is to have a `skipNativeImageTestsuite` which i can use to skip other plugins but it get's hard to configure with profiles.

The native image plugin should be skipped if `skipTests` is active or `skipNativeImageTestsuite` so the hard part is to do `OR` operations to enable the profile.

**Comment by olpaw** [comment]
Ok. I will add that. It will be part of RC15.

**Comment by olpaw** [comment]
Fixed on master (d9b047d9e35f225b3e92fa60b62f03ee64ba68d0)

**Comment by normanmaurer** [comment]
@olpaw thanks for fixing.
