### ISSUE TITLE
mx libffi on cygwin

### ISSUE THREAD

**Issue by peblpebl** [oracle/graal#1120]
When doing a mx eclipseinit I get:
<pre>
$ ../mx/mx eclipseinit
WARNING: File .libs/libffi.a for archive libffi does not exist.
WARNING: File include/ffi.h for archive libffi does not exist.
WARNING: File include/ffitarget.h for archive libffi does not exist.
Error while creating project libffi
Traceback (most recent call last):
  File "/cygdrive/d/shared/git/mx/mx.py", line 19151, in <module>
    main()
  File "/cygdrive/d/shared/git/mx/mx.py", line 19062, in main
    primary_suite().recursive_post_init()
  File "/cygdrive/d/shared/git/mx/mx.py", line 9114, in recursive_post_init
    self.visit_imports(Suite._init_metadata_visitor)
  File "/cygdrive/d/shared/git/mx/mx.py", line 9161, in visit_imports
    visitor(self, suite_import, **extra_args)
  File "/cygdrive/d/shared/git/mx/mx.py", line 9128, in _init_metadata_visitor
    imported_suite._init_metadata()
  File "/cygdrive/d/shared/git/mx/mx.py", line 9145, in _init_metadata
    self._load_metadata()
  File "/cygdrive/d/shared/git/mx/mx.py", line 9371, in _load_metadata
    self._load_projects()
  File "/cygdrive/d/shared/git/mx/mx.py", line 9403, in _load_projects
    p = getattr(self.extensions, className)(self, name, deps, workingSets, theLicense=theLicense, **attrs)
  File "/cygdrive/d/shared/git/graal/truffle/mx.truffle/mx_truffle.py", line 639, in __init__
    self.libs = self.delegate.libs
  File "/cygdrive/d/shared/git/graal/truffle/mx.truffle/mx_truffle.py", line 608, in <lambda>
    libs = property(lambda self: [next(self.getArchivableResults(single=True))[0]])
StopIteration
</pre>

However:
<pre>
pebl@stationary /cygdrive/d/shared/git/fastr
$ file /usr/lib/libffi.dll.a
/usr/lib/libffi.dll.a: current ar archive
pebl@stationary /cygdrive/d/shared/git/fastr
$ file /usr/include/ffi.h
/usr/include/ffi.h: C source, ASCII text
pebl@stationary /cygdrive/d/shared/git/fastr
$ file /usr/include/ffitarget.h
/usr/include/ffitarget.h: C source, ASCII text
</pre>

What to do here?

**Comment by dougxc** [comment]
@rschatz is it realistic to expect Truffle NFI to compile on cygwin?

**Comment by rschatz** [comment]
Sure, no reason why it shouldn't work. There is the question of what it should actually do, i.e. should it use cygwin's libs (e.g. `dlopen` instead of `GetProcAddress`), or rather still use the Windows APIs? Currently it would probably use the Windows APIs, but I'm not 100% sure (might need some fixing of `#ifdef`s). It probably doesn't make a difference.

But this error rather looks like a different problem, it doesn't even get to building the NFI, it's stuck at the build of `libffi`. @pejovica do you know what's wrong here?

**Comment by peblpebl** [comment]
It was late so I forgot to mention that
<pre>
$ ls -l graal/truffle/mxbuild/cygwin-amd64/src/libffi/libffi-3.2.1/
total 0
</pre>
So I would assume mx failed at downloading libffi src for cygwin, and only complained when trying to compile.

**Comment by wirthi** [comment]
Closing this old issue from 2019. If this problem persists (on a recent version of GraalVM), feel free to re-open.
