### ISSUE TITLE
[question] unsupported java options

### ISSUE THREAD

**Issue by TisonKun** [oracle/graal#1121]
Recently I try to build [Apache Flink](https://github.com/apache/flink) with graalvm-rc13. It fails as described below. Thus I guess that graalvm support limited `java` options, and comes to here for help.

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.1:test (default-test) on project flink-runtime_2.11: There are test failures.
[ERROR] 
[ERROR] Please refer to /Users/tison/Repository/flink/flink-runtime/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] ExecutionException The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was /bin/sh -c cd /Users/tison/Repository/flink/flink-runtime && /Users/tison/.sdkman/candidates/java/1.0.0-rc-13-grl/jre/bin/java -Xms256m -Xmx2048m -Dmvn.forkNumber=3 -XX:+UseG1GC -jar /Users/tison/Repository/flink/flink-runtime/target/surefire/surefirebooter8445142954569604481.jar /Users/tison/Repository/flink/flink-runtime/target/surefire 2019-03-29T18-39-14_505-jvmRun3 surefire6416341000638166883tmp surefire_1474872550962194421133tmp
[ERROR] Process Exit Code: 0
```

**How to reproduce:**  checkout flink repo and run `mvn clean install`.

**Comment by shelajev** [comment]
can you please provide more details on the error, for example if you run this command: 
`/bin/sh -c cd /Users/tison/Repository/flink/flink-runtime && /Users/tison/.sdkman/candidates/java/1.0.0-rc-13-grl/jre/bin/java -Xms256m -Xmx2048m -Dmvn.forkNumber=3 -XX:+UseG1GC -jar /Users/tison/Repository/flink/flink-runtime/target/surefire/surefirebooter8445142954569604481.jar /Users/tison/Repository/flink/flink-runtime/target/surefire 2019-03-29T18-39-14_505-jvmRun3 surefire6416341000638166883tmp surefire_1474872550962194421133tmp` 

I tried building flink with my GraalVM EE rc14 (just had that on my machine) and it just fails the HeartbeatManagerTest normally (without a crash or anything). 
```
[INFO] Results:
[INFO]
[ERROR] Failures:
[ERROR]   HeartbeatManagerTest.testHeartbeatTimeout:181
[INFO]
[ERROR] Tests run: 3563, Failures: 1, Errors: 0, Skipped: 42
``` 

The `-XX:+G1GC` and the heap size command line options are supported. If you could please run something like to see whether it works for you? 
```
→ java -Xms256m -Xmx2048m -XX:+UseG1GC -version
java version "1.8.0_202"
Java(TM) SE Runtime Environment (build 1.8.0_202-b08)
Java HotSpot(TM) GraalVM EE 1.0.0-rc14 (build 25.202-b08-jvmci-0.56, mixed mode)
```

**Comment by TisonKun** [comment]
[Terminal Saved Output.txt](https://github.com/oracle/graal/files/3026358/Terminal.Saved.Output.txt)

@shelajev here is the whole log when I re-run `mvn clean install`. The reason I think it is a Graal specific issue is because it fails with `ExecutionException The forked VM terminated without properly saying goodbye. VM crash or System.exit called?`

And if I run `/bin/sh -c cd /Users/tison/Repository/flink/flink-runtime && /Users/tison/.sdkman/candidates/java/1.0.0-rc-13-grl/jre/bin/java -Xms256m -Xmx2048m -Dmvn.forkNumber=4 -XX:+UseG1GC -jar /Users/tison/Repository/flink/flink-runtime/target/surefire/surefirebooter5231374058795670763.jar /Users/tison/Repository/flink/flink-runtime/target/surefire 2019-03-31T16-26-53_986-jvmRun4 surefire7197805550048433614tmp surefire_5208121094404111463353tmp`, it reports `Error: Unable to access jarfile /Users/tison/Repository/flink/flink-runtime/target/surefire/surefirebooter5231374058795670763.jar`

**Comment by YuanGunGun** [comment]
@TisonKun any new please?
