### ISSUE TITLE
1.0.0-rc14 native image build error: No instances are allowed in the image heap

### ISSUE THREAD

**Issue by ahmadmo** [oracle/graal#1125]
I'm using `Quartz` in my project. building a native image results in:

```
[error] Error: No instances are allowed in the image heap for a class that is initialized or reinitialized at image runtime: sun.security.provider.NativePRNG
[error] Detailed message:
[error] Error: No instances are allowed in the image heap for a class that is initialized or reinitialized at image runtime: sun.security.provider.NativePRNG
[error] Trace:  object java.security.SecureRandom
[error]         method java.rmi.server.ObjID.<init>()
[error] Call path from entry point to java.rmi.server.ObjID.<init>(): 
[error]         at java.rmi.server.ObjID.<init>(ObjID.java:111)
[error]         at sun.rmi.transport.LiveRef.<init>(LiveRef.java:74)
[error]         at sun.rmi.server.UnicastServerRef.<init>(UnicastServerRef.java:167)
[error]         at java.rmi.server.UnicastRemoteObject.exportObject(UnicastRemoteObject.java:320)
[error]         at org.quartz.core.QuartzScheduler.bind(QuartzScheduler.java:372)
[error]         at org.quartz.core.QuartzScheduler.initialize(QuartzScheduler.java:235)
[error]         at org.quartz.impl.StdSchedulerFactory.instantiate(StdSchedulerFactory.java:1360)
[error]         at org.quartz.impl.StdSchedulerFactory.getScheduler(StdSchedulerFactory.java:1559)
[error]         at org.quartz.impl.StdSchedulerFactory.getDefaultScheduler(StdSchedulerFactory.java:1575)
```

**Comment by cstancu** [comment]
The initialization of `NativePRNG` is [rerun at run time](https://github.com/oracle/graal/blob/master/substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/SecurityServicesFeature.java#L93). This [article](https://medium.com/graalvm/understanding-class-initialization-in-graalvm-native-image-generation-d765b7e4d6ed) should help understanding class initialization on `native-image`.

**Comment by matneu** [comment]
RMI's `ObjID` is the issue here, as it has a static field that's initialized with `SecureRandom`.
For RMI, delaying initialization for the following classes should get you further:
`--initialize-at-run-time=java.rmi.server.ObjID,sun.rmi.transport.ObjectTable,sun.rmi.transport.Transport,sun.rmi.transport.tcp.TCPEndpoint,sun.rmi.registry.RegistryImpl,sun.rmi.transport.DGCImpl,sun.rmi.transport.DGCClient`

**Comment by cstancu** [comment]
@matneu thanks! @ahmadmo RMI won't work in general because object serialization is not supporoted. See https://github.com/oracle/graal/issues/1935.
