### ISSUE TITLE
TypeError: WRITE on foreign object failed due to: Message not supported: WRITE

### ISSUE THREAD

**Issue by ralleman** [oracle/graal#1134]
Hi all,

I'm getting this odd message when setting a ProxyObject property value in JavaScript: 

> TypeError: WRITE on foreign object failed due to: Message not supported: WRITE

I'm quite stuck why I'm getting this because I have a few other ProxyObject implementations that are all working fine. Oddly, I can call the other methods of the ProxyObect, but not the putMember on this specific class.

Note that the class is a non-static Inner class of another ProxyObject, however, I have moved it out and it made no difference - still get the error.

Unfortunately my code is rather complex, so I won't copy it here. I tried to make a smaller test of this but couldn't reproduce the problem.

In order to help me further, could you please tell me what are the possible causes of this error? Thanks.

**Comment by ralleman** [comment]
Another clue is that a PolyglotException is not thrown, rather the eval returns with a rejected Promise.

**Comment by chumer** [comment]
Could you provide us with a snippet of the JavaScript code you are using to access the proxy object?
Note that you should not be able to call any Java methods on a ProxyObject directly.

**Comment by ralleman** [comment]
It's a little complicated, but here goes:

I eval this, returning a Value, which is a JS class "function":

```javascript
/**
 * This returns the class containing a proxy that connects to the internal Graal ProxyObject.
 */
(() => class {
  constructor(value = null, cls = null) {

    // Accept value as an internal resource proxy if it is an object but not an
    // instance of Object. The input should be a Graal ProxyObject.
    // Question for Graal team - is it possible to positively identify "value" as ProxyObject
    // TODO - use "cls" to support the new operator using a ProxyInstantiable.
    if (typeof value !== 'object' || value instanceof Object) {
      throw new Error('Invalid constructor argument ' + value);
    }

    // Now return a JS proxy that uses "this" as the target. Using this as the
    // target insures that instanceof will continue to work. The handler overrides
    // the getter and setter and these are proxied through to the resource proxy
    // to get the actual value. If the result of a get operation is a function,
    // an attempt is made to get the function from the target and this becomes bound
    // to the proxy to fix up it's "this" pointer. The ProxyObject only contains
    // properties - no functions.
    let proxy = new Proxy(this, {

      /**
       * Retrieves the value from the underlying resource proxy.
       */
      get: function (target, name) {
        let v = target[name];
        if (v instanceof Function) {
          return v.bind(proxy);
        }
        if (v !== undefined) {
          return v;
        }

        // Get the value from the ProxyObject.
        return value[name];
      },

      /**
       * Sets the value on the underlying ProxyObject.
       */
      set: function (target, name, val) {
        value[name] = val;
        return true;
      }
    });

    // For Graal team - this is where the TypeError is occurring - but only sometimes.
    // Most of the ProxyObjects are accepting the putMember. In the case where it's failing
    // putMember is not being invoked at all, the error is occurring somewhere between
    // here and just prior to ProxyObject.putMember().
    value.$self = proxy;
    return proxy;
  }

})();
```
I then assign the value to a property in the context, e.g. com.mydomain.Object.

Then I eval something like this returning a Value containing another class "function":

```javascript
(() => class extends com.mydomain.Object {
  constructor(value = null, cls = null) {
    super(value, cls || 'com.mydomain.Lookup');
  }
  getFullName() {
    return this.$module.name + '.' + this.name;
  }
})()
```

I then assign this to a property in the context com.mydomain.Lookup.

Then I eval "com.mydomain.Lookup" within the context but later, which returns the class com.mydomain.Lookup into a Value. I call newInstance on that Value passing a ProxyObject into the constructor.

```java
public Value getProxyInstance(Context context, ClassDefinition classDefinition, ProxyObject proxyObject) {

    // This should return the class object within Graal.
    Value cls = context.eval(classDefinition.getScriptLanguage().getGraalId(), classDefinition.getName() /*com.mydomain.Lookup*/);

    // This instantiates the class and passes in a new proxy to the constructor.
    return cls.newInstance(proxyObject);
}
```

The result of getProxyInstance is a new JavaScript instance of com.mydomain.Lookup, which is internally bound to its Java ProxyObject and the value.$self assignment is an attempt to provide the converse mapping in order to get a bidirectional mapping between the two.

So, this all works wonderfully and instanceof is working a treat. But in one instance I get that TypeError and I don't know how to work out what is causing it because it seems to be hidden from my work, somewhere inside Graal.

**Comment by ralleman** [comment]
Hi guys, is there any further feedback on this?

I've found a temporary work around for the issue. Because I don't need to put properties yet, I've added "Selfer" to my ProxyObject:

```java
public class ResourceProxy implements ProxyObject {

    public class Selfer {
        public void set(Value self) {
            ResourceProxy.this.self = self;
        }
    }

```

And instead of putMembering $self, I get the Selfer object and call set on it:

```javascript
    value.$self.set(proxy);
```

This is working, but it's not pretty. I will need putMember working later though.

Note that I'm not assuming there's anything wrong with Graal here. I just need to understand what's triggering the error so I can progress further with it.

**Comment by ralleman** [comment]
This issue has now become critical for me to resolve. It was still happening on rc14, so I updated to rc16, but even my work around doesn't work on that. I'm going to continue hunting. Has anything been done on the original fault between rc14 and rc16?

**Comment by ralleman** [comment]
Can someone please tell me how to enable stack trace dumps inside truffe while running as a JVM (i.e. what -D property do I use)?

By my reckoning this problem is in one of these files:

truffle/src/com.oracle.truffle.polyglot/src/com/oracle/truffle/polyglot/PolyglotProxy.java
truffle/src/com.oracle.truffle.polyglot/src/com/oracle/truffle/polyglot/HostObject.java
truffle/src/com.oracle.truffle.polyglot/src/com/oracle/truffle/polyglot/PolyglotLanguageBindings.java
truffle/src/com.oracle.truffle.polyglot/src/com/oracle/truffle/polyglot/DefaultScope.java
truffle/src/com.oracle.truffle.api.test/src/com/oracle/truffle/api/test/polyglot/ProxyInteropObject.java

But it's impossible for me to know which one because I'm not able to dump the stacktrace.

**Comment by ralleman** [comment]
I found the problem, and as you guys suspected, it was in my code. I thought all of my ProxyObjects were the same type, but one of them was a proxy ProxyObject which was forwarding the getMember requests to an underlying proxy. Hence when I printed the class type in Java, they all looked the same. However, that proxy ProxyObject was throwing an UnsupportedOperationException on the putMember causing the error above.

For me the thing that would have helped the most is a better error message. Instead of printing "xxx on foreign object" it would be much better to print "xxx on **com.mydomain.MyProxyObject@3534434**" because that would have told me exactly which class to look at. Also I was unable to find any option to trace what truffle was doing (the truffle stacktrace is not available when printing the exception in JavaScript), so some way to enable truffle tracing would be really handy. It would also be handy I think, not to suppress exceptions getting generated on Java side because these contain info that can help find problems.

**Comment by chumer** [comment]
Sorry to hear that the debug experience was not good.

> For me the thing that would have helped the most is a better error message.

Noted! We will improve that.

>  (the truffle stacktrace is not available when printing the exception in JavaScript)

We also want to implement support for that. We have an issue tracking this internally.

> not to suppress exceptions getting generated on Java side because these contain info that can help find problems.

We only do this very selectively for the proxy interfaces. We need some way to indicate that an operation is not supported. In such cases, error messages in target languages are translated in order to provide a consistent experience for the target language (philosophy: you shouldn't need to know where the object is coming from). We should not be interpreting/swallowing exceptions for anything except those in the polyglot proxy interfaces.

What we probably should do here, is to at least incorporate the message provided by the source exception.

**Comment by ralleman** [comment]
> What we probably should do here, is to at least incorporate the message provided by the source exception.

Yup true. Anyway closing this now it's resolved. Thanks @chumer.
