### ISSUE TITLE
Developing Graal with IntelliJ Idea

### ISSUE THREAD

**Issue by cstehreem** [oracle/graal#1138]
I have been exploring Graal's code following [this article][1] and Graal's official documentation on GitHub. I am trying to import project in IntelliJ Idea but failing so far. Here is my directory structure:

    Graal-Dev
        graal
            ci_includes
            compiler
            docs
            examples
            regex
            sdk
            substratevm
            sulong
            tools
            truffle
            vm
        graal-jvmci-8
        mx

I did following steps:
1. Built Graal-JVMCI-8 with mx with java-home set to labsjdk1.8.0_202-jvmci-0.57 (downloaded from Oracle's website). 
2. Built `graal/compiler` with java-home `graal-jvmci-8/jdk1.8.0_202/linux-amd64/product`.
3. Ran `mx intellijinit` in compiler directory as described in docs.
4. Imported graal in IntelliJ using 'Create from existing sources' option.
5. Set `graal-jvmci-8/jdk1.8.0_202/linux-amd64/product` to be used as jdk.

The build is taking ages and so far I am getting following errors:

    Information:java: Errors occurred while compiling module 'org.graalvm.compiler.serviceprovider.jdk9'
    Information:java: Errors occurred while compiling module 'org.graalvm.compiler.serviceprovider'
    Information:javac 1.8.0_202 was used to compile java sources
    Information:4/7/19 2:47 PM - Build completed with 24 errors and 0 warnings in 10 m 7 s 441 ms
    /home/tehreem/Desktop/Graal-Dev/graal/compiler/src/org.graalvm.compiler.serviceprovider.jdk9/src/org/graalvm/compiler/serviceprovider/GraalServices.java
    Error:(150, 26) java: cannot find symbol
      symbol:   class Module
      location: class org.graalvm.compiler.serviceprovider.GraalServices
    Error:(59, 28) java: cannot infer type arguments for java.lang.Iterable<T>
      reason: cannot use '<>' with anonymous inner classes
    Error:(93, 9) java: cannot find symbol
      symbol:   class Module
      location: class org.graalvm.compiler.serviceprovider.GraalServices
    Error:(94, 9) java: cannot find symbol
      symbol:   class Module
      location: class org.graalvm.compiler.serviceprovider.GraalServices
    Error:(94, 35) java: cannot find symbol
      symbol:   method getModule()
      location: variable other of type java.lang.Class<?>
    Error:(101, 26) java: cannot find symbol
      symbol:   method initialize()
      location: class jdk.vm.ci.runtime.JVMCI
    Error:(147, 17) java: cannot find symbol
      symbol:   method getModule()
      location: variable c of type java.lang.Class<?>
    Error:(150, 62) java: cannot find symbol
      symbol:   method getModule()
      location: variable class of type java.lang.Class<jdk.vm.ci.services.Services>
    Error:(165, 9) java: cannot find symbol
      symbol:   class Module
      location: class org.graalvm.compiler.serviceprovider.GraalServices
    Error:(165, 26) java: cannot find symbol
      symbol:   method getModule()
      location: variable c of type java.lang.Class<?>
    Error:(166, 9) java: cannot find symbol
      symbol:   class Module
      location: class org.graalvm.compiler.serviceprovider.GraalServices
    Error:(218, 30) java: cannot find symbol
      symbol:   variable ProcessHandle
      location: class org.graalvm.compiler.serviceprovider.GraalServices
    /home/tehreem/Desktop/Graal-Dev/graal/compiler/src/org.graalvm.compiler.serviceprovider/src/org/graalvm/compiler/serviceprovider/GraalServices.java
    Error:(31, 37) java: package jdk.vm.ci.meta.SpeculationLog does not exist
    Error:(100, 12) java: cannot find symbol
      symbol:   class SpeculationReason
      location: class org.graalvm.compiler.serviceprovider.GraalServices
    /home/tehreem/Desktop/Graal-Dev/graal/compiler/src/org.graalvm.compiler.serviceprovider/src/org/graalvm/compiler/serviceprovider/SpeculationReasonGroup.java
    Error:(32, 22) java: package jdk.vm.ci.code does not exist
    Error:(33, 22) java: package jdk.vm.ci.meta does not exist
    Error:(34, 22) java: package jdk.vm.ci.meta does not exist
    Error:(35, 37) java: package jdk.vm.ci.meta.SpeculationLog does not exist
    Error:(72, 12) java: cannot find symbol
      symbol:   class SpeculationReason
      location: class org.graalvm.compiler.serviceprovider.SpeculationReasonGroup
    Error:(83, 21) java: cannot find symbol
      symbol:   class BytecodePosition
      location: class org.graalvm.compiler.serviceprovider.SpeculationReasonGroup
    Error:(96, 13) java: cannot find symbol
      symbol:   class ResolvedJavaMethod
      location: class org.graalvm.compiler.serviceprovider.SpeculationReasonGroup
    Error:(96, 61) java: cannot find symbol
      symbol:   class ResolvedJavaType
      location: class org.graalvm.compiler.serviceprovider.SpeculationReasonGroup
    Error:(127, 26) java: cannot find symbol
      symbol:   class ResolvedJavaMethod
      location: class org.graalvm.compiler.serviceprovider.SpeculationReasonGroup
    Error:(127, 59) java: cannot find symbol
      symbol:   class ResolvedJavaType
      location: class org.graalvm.compiler.serviceprovider.SpeculationReasonGroup

How do I add missing packages?

[1]: https://chrisseaton.com/truffleruby/jokerconf17/

**Comment by ralleman** [comment]
If the point of you building Graal is to run up a Graal-based project in IntelliJ, you can download prebuilt binaries for Linux and Mac here https://github.com/oracle/graal/releases. You should us rc14 in this case because the rc15 hasn't been released yet in Maven Central. You need to replace the Project JDK8 in IntelliJ with the one from Graal and it works fine thereafter.

**Comment by cstehreem** [comment]
I want to be able to modify Graal and JDK8 it is based on.

**Comment by wirthi** [comment]
I am closing this ticket. It should be possible to use IntelliJ to develop GraalVM nowadays with recent versions.
