### ISSUE TITLE
Truffle DSL: generate static methods usable from slow paths to avoid code duplication

### ISSUE THREAD

**Issue by lukasstadler** [oracle/graal#114]
I'd like to propose an extension to Truffle DSL that help Truffle language implementations avoid unnecessary code duplication.

Given a simple Node like this:

``` java
class IsFoo extends Node {
    abstract boolean execute(Object value);
    @Specialization
    static boolean fooA(A value) {
        return ...;
    }
    @Specialization
    static boolean fooB(B value) {
        return ...;
    }
    @Fallback
    static boolean fooFallback(Object value) {
        return ...;
    }
}
```

Truffle language developers often hit situations where they would like to use the same functionality in a place where they have no node in which to place the IsFoo node.
It is not feasible to enforce all code that is executed to be within compilable nodes: apart from the fact that it's sometimes just infeasible maintain nodes for deeply nested functionality, this would lead to too much (compiled) code duplication, and if the relevant code is behind a TruffleBoundary, the compilation and inlining heuristics are disturbed.
One possible solution would be to provide a "fake" node that can contain other nodes even though it does not have a parent itself, but this disturbs many assumptions that the Truffle system takes.

In reality, the simplest solution is often to accept the code duplication and create the following helper method:

``` java
static boolean isFoo(Object value) {
    if (value instanceof A) {
        return ...;
    } else if (value instanceof B) {
        return ...;
    } else {
        return ...;
    }
}
```

All information needed to create this method is available to Truffle DSL, so that adding `@NodeInfo(staticEval=true)` could automatically generate the following code in IsFooNodeGen:

``` java
static boolean eval(Object value) {
    CompilerAsserts.neverPartOfCompilation(); // or @TruffleBoundary
    if (value instanceof A) {
        return fooA((A) value);
    } else if (value instanceof B) {
        return fooB((B) value);
    } else {
        return fooFallback(value);
    }
}
```

There are some limitations on the specializations for generating these static eval methods:
- they need to be static methods, so they cannot use instance fields
- they cannot have Frame parameters (at least no VirtualFrame parameters)
- `@Cached(...)` will behave differently: they might be disallowed, implemented as static fields, or re-created every time

**Comment by smarr** [comment]
:+1: yay, this sounds like something I would also really like to have!

**Comment by chumer** [comment]
As discussed with Lukas this approach has limitations. But these limitations are verifyable in the annotation processor. Makes a lot of sense for nodes that require use behind TruffleBoundaries.

Even @Cached with Nodes could potentially be solved with a static LRU cache. I still need to work out the details about this.

**Comment by chumer** [comment]
This issue seems to be stale. We will track this issue internally as GR-1496.
