### ISSUE TITLE
[native-image] build java prj with dependencies

### ISSUE THREAD

**Issue by andreaneri** [oracle/graal#1141]
Hello,
my env:
uname -a
Darwin Macintosh.local 17.7.0 Darwin Kernel Version 17.7.0: Thu Dec 20 21:47:19 PST 2018; root:xnu-4570.71.22~1/RELEASE_X86_64 x86_64

java -version
java version "1.8.0_202"
Java(TM) SE Runtime Environment (build 1.8.0_202-b08)
Java HotSpot(TM) GraalVM EE 1.0.0-rc15 (build 25.202-b08-jvmci-0.58, mixed mode)

i have this simple prj:
AESMain.java -> depend on: AESUtil.java

i builded it with:
javac AESMain.java

i have:
-rw-r--r--  1 user  staff    727  8 Apr 10:14 AESMain.class
-rw-r--r--  1 user  staff   2567  8 Apr 10:14 AESUtil.class

i run:
native-image AESMain

ls -ltr aesmain 
-rwxr-xr-x  1 tinan291  staff  3951024  8 Apr 10:26 aesmain

./aesmain 
Exception in thread "main" java.lang.RuntimeException: java.security.NoSuchAlgorithmException: Cannot find any provider supporting AES/CBC/PKCS5Padding
	at AESUtil.encrypt(AESUtil.java:51)
	at AESMain.main(AESMain.java:8)
Caused by: java.security.NoSuchAlgorithmException: Cannot find any provider supporting AES/CBC/PKCS5Padding
	at javax.crypto.Cipher.getInstance(Cipher.java:539)
	at AESUtil.encrypt(AESUtil.java:43)
	... 1 more

thanks,

Andrea

**Comment by cstancu** [comment]
@andreaneri can you try enabling security services with `native-image --enable-all-security-services AESMain`. See the documentation on [security services support](https://github.com/oracle/graal/blob/master/substratevm/JCA-SECURITY-SERVICES.md) for more details

**Comment by andreaneri** [comment]
@cstancu wow, compilation has been very long than before, but now it work, just i have this warning:
WARNING: The sunec native library, required by the SunEC provider, could not be loaded. This library is usually shipped as part of the JDK and can be found under <JAVA_HOME>/jre/lib/<platform>/libsunec.so. It is loaded at run time via System.loadLibrary("sunec"), the first time services from SunEC are accessed. To use this provider's services the java.library.path system property needs to be set accordingly to point to a location that contains libsunec.so. Note that if java.library.path is not set it defaults to the current working directory.

it's really faster than jvm version :-O

**Comment by cstancu** [comment]
The warning (as explained [here](https://github.com/oracle/graal/blob/master/substratevm/JCA-SECURITY-SERVICES.md#native-implementations)) is shown because `libsunec.so` cannot be found. If you don't need the SunEC provider then it should not affect your application. In the future, we will statically link `libsunec.so` in the executable.
