### ISSUE TITLE
GraalVM RC15 artefacts not available on Maven Central

### ISSUE THREAD

**Issue by msteindorfer** [oracle/graal#1148]
The GraalVM RC15 artefacts still seem to be missing on Maven Central. Is there an ETA when the community can expect them to land there? /cc @ansalond

**Comment by flortsch** [comment]
The artifacts have been deployed and will be available in the next few hours.

**Comment by pmlopes** [comment]
@flortsch `truffle-nfi` refers to:

```xml
<dependency>
  <groupId>org.graalvm.truffle</groupId>
  <artifactId>truffle-nfi-native-linux-aarch64</artifactId>
  <version>1.0.0-rc15</version>
  <type>tar.gz</type>
</dependency>
```

Which isn't available on central so if your project depends on `svm` which is needed for the native image annotations then it fails...

**Comment by msteindorfer** [comment]
@flortsch thanks for the notification. 

Unfortunately I'm still blocked by issue @pmlopes was pointing out:

```
> Could not find org.graalvm.truffle:truffle-nfi-native-linux-aarch64:1.0.0-rc15.
   Required by:
     project :project > com.oracle.substratevm:svm:1.0.0-rc15 > org.graalvm.truffle:truffle-nfi:1.0.0-rc15
```

**Comment by flortsch** [comment]
The missing artifact for aarch64 should also be available on Maven Central in the next minutes or hour.

**Comment by olpaw** [comment]
Fixed by @flortsch 
Thanks a lot!
