### ISSUE TITLE
InetAddress.getLocalHost throws UnknownHostException on Alpine

### ISSUE THREAD

**Issue by raboof** [oracle/graal#1151]
`java.net.InetAddress.getLocalHost` throws a `java.net.UnknownHostException` when running in Docker and using an Alpine base image.

**Comment by raboof** [comment]
This is because doing DNS lookups requires a 'full' libc, and 'minimal' libc's such as musl and scratch aren't currently sufficient for graal. See also #571, #624.

**Comment by jorinvo** [comment]
> This is because doing DNS lookups requires a 'full' libc, and 'minimal' libc's such as musl and scratch aren't currently sufficient for graal

Since it is *currently* not possible, I wonder if there are any plans to include something for this in the binary directly at some point in the future?

It would be awesome to have the same seamless experience building Docker images "from scratch" with GraalVM as one does with Golang 😃
