### ISSUE TITLE
How to build it for armhf/aarch64?

### ISSUE THREAD

**Issue by zaoqi-unsafe** [oracle/graal#1154]

**Comment by sanzinger** [comment]
What exactly do you want to build/use?

**Comment by zaoqi-unsafe** [comment]
something like graalvm-ce-1.0.0-rc11-linux-amd64.tar.gz

**Comment by bobmcwhirter** [comment]
I've started an attempt at it:

https://github.com/oracle/graal/pull/1155

note, `bin/native-image` doesn't currently work on aarch64.  No idea if it really actually works on any platform. This is mostly focused on JDK11 work, which will be required for the aarch64 stuff to function.

**Comment by hlolli** [comment]
To build the native-image binary, you can from the substratevm directory run

`mx native-image -cp $(THE MX_BUILD_DIR_PATH)/substratevm/dists/jdk1.8/svm-driver.jar com.oracle.svm.driver.NativeImage`

I wonder how this is done to generate the `lli` binary?

In any case, it would be nice if the build script for the official community release would be made public.

**Comment by hlolli** [comment]
Ah nevermind, I somehow overlooked one thing in the build directory mxbuild, theres a graalvm directory

`mxbuild/vm/linux-amd64/GRAALVM_CMP_GU_GVM_INS_JS_LIBPOLY_NFI_NJS_POLY_POLYNATIVE_PRO_RGX_SLG_SVM_SVMAG_SVMCF_SVML_TFL_VVM/`

and there you'll find all the binaries set up like in the CE distribution. With the added bonus of source files. So it seems all make sense now :)

**Comment by bobmcwhirter** [comment]
From `vm/` dir, on AArch64, using a `JAVA_HOME` pointing to a JDK11 (such as AdoptOpenJDK-11):

    mx --dynamicimports /substratevm build

And then you should have `./latest_graalvm_home/` which represents the distribution, including `bin/native-image`.
