### ISSUE TITLE
NPE in jdk.vm.ci.code.BytecodePosition.<init>

### ISSUE THREAD

**Issue by ramymagdy** [oracle/graal#1156]
While trying to run native-image on a Spring Boot Application, I'm getting an NPE with the following stack trace:

Error: Error encountered while parsing org.springframework.core.annotation.SynthesizedAnnotation$$ProxyImpl.equals(java.lang.Object) 
Parsing context:
        parsing com.sun.org.apache.xerces.internal.util.AugmentationsImpl$SmallContainer.putItem(AugmentationsImpl.java:136)
        parsing com.sun.org.apache.xerces.internal.util.AugmentationsImpl.putItem(AugmentationsImpl.java:54)
        parsing com.sun.org.apache.xerces.internal.impl.XMLEntityManager.endEntity(XMLEntityManager.java:1397)
        parsing com.sun.org.apache.xerces.internal.impl.XMLEntityScanner.load(XMLEntityScanner.java:1916)
        parsing com.sun.org.apache.xerces.internal.impl.XML11EntityScanner.skipString(XML11EntityScanner.java:1467)
        parsing com.sun.org.apache.xerces.internal.impl.XMLVersionDetector.determineDocVersion(XMLVersionDetector.java:156)
        parsing com.sun.org.apache.xerces.internal.impl.xs.opti.SchemaParsingConfig.parse(SchemaParsingConfig.java:583)
        parsing com.sun.org.apache.xerces.internal.impl.xs.opti.SchemaParsingConfig.parse(SchemaParsingConfig.java:686)
        parsing com.sun.org.apache.xerces.internal.impl.xs.opti.SchemaDOMParser.parse(SchemaDOMParser.java:530)
        parsing com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.getSchemaDocument(XSDHandler.java:2181)
        parsing com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.parseSchema(XSDHandler.java:578)
        parsing com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaLoader.processJAXPSchemaSource(XMLSchemaLoader.java:827)
        parsing com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaLoader.loadSchema(XMLSchemaLoader.java:599)
        parsing com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaLoader.loadGrammar(XMLSchemaLoader.java:569)
        parsing com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaLoader.loadGrammar(XMLSchemaLoader.java:535)
        parsing com.sun.org.apache.xerces.internal.jaxp.validation.XMLSchemaFactory.newSchema(XMLSchemaFactory.java:254)
        parsing javax.xml.validation.SchemaFactory.newSchema(SchemaFactory.java:638)
        parsing org.apache.logging.log4j.core.config.xml.XmlConfiguration.<init>(XmlConfiguration.java:158)
        parsing org.apache.logging.log4j.core.config.xml.XmlConfigurationFactory.getConfiguration(XmlConfigurationFactory.java:46)
        parsing org.apache.logging.log4j.core.config.ConfigurationFactory$Factory.getConfiguration(ConfigurationFactory.java:472)
        parsing org.apache.logging.log4j.core.config.ConfigurationFactory.getConfiguration(ConfigurationFactory.java:266)
        parsing org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:613)
        parsing org.apache.logging.log4j.core.LoggerContext.setConfigLocation(LoggerContext.java:603)
        parsing org.apache.logging.log4j.core.selector.ClassLoaderContextSelector.locateContext(ClassLoaderContextSelector.java:157)
        parsing org.apache.logging.log4j.core.selector.ClassLoaderContextSelector.getContext(ClassLoaderContextSelector.java:74)
        parsing org.apache.logging.log4j.core.selector.ClassLoaderContextSelector.getContext(ClassLoaderContextSelector.java:57)
        parsing org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:148)
        parsing org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:45)
        parsing org.apache.logging.log4j.LogManager.getContext(LogManager.java:194)
        parsing org.apache.logging.log4j.spi.AbstractLoggerAdapter.getContext(AbstractLoggerAdapter.java:122)
        parsing org.apache.logging.slf4j.Log4jLoggerFactory.getContext(Log4jLoggerFactory.java:43)
        parsing org.apache.logging.log4j.spi.AbstractLoggerAdapter.getLogger(AbstractLoggerAdapter.java:46)
        parsing org.apache.logging.slf4j.Log4jLoggerFactory.getLogger(Log4jLoggerFactory.java:29)
        parsing org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:358)
        parsing org.apache.commons.logging.LogFactory$Slf4jDelegate.createLocationAwareLog(LogFactory.java:174)
        parsing org.apache.commons.logging.LogFactory.getLog(LogFactory.java:111)
        parsing org.apache.commons.logging.LogFactory.getLog(LogFactory.java:99)
        parsing org.springframework.boot.SpringApplication.getApplicationLog(SpringApplication.java:677)
        parsing org.springframework.boot.SpringApplication.run(SpringApplication.java:332)
        parsing com.mentor.dvt.coverageanalyzer.CoverageanalyzerApplication.main(CoverageanalyzerApplication.java:166)
        parsing com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:153)
        parsing com.oracle.svm.core.code.IsolateEnterStub.JavaMainWrapper_run_5087f5482cc9a6abc971913ece43acb471d2631b(generated:0)

com.oracle.graal.pointsto.util.AnalysisError$ParsingError: Error encountered while parsing org.springframework.core.annotation.SynthesizedAnnotation$$ProxyImpl.equals(java.lang.Object) 
Parsing context:
        parsing com.sun.org.apache.xerces.internal.util.AugmentationsImpl$SmallContainer.putItem(AugmentationsImpl.java:136)
        parsing com.sun.org.apache.xerces.internal.util.AugmentationsImpl.putItem(AugmentationsImpl.java:54)
        parsing com.sun.org.apache.xerces.internal.impl.XMLEntityManager.endEntity(XMLEntityManager.java:1397)
        parsing com.sun.org.apache.xerces.internal.impl.XMLEntityScanner.load(XMLEntityScanner.java:1916)
        parsing com.sun.org.apache.xerces.internal.impl.XML11EntityScanner.skipString(XML11EntityScanner.java:1467)
        parsing com.sun.org.apache.xerces.internal.impl.XMLVersionDetector.determineDocVersion(XMLVersionDetector.java:156)
        parsing com.sun.org.apache.xerces.internal.impl.xs.opti.SchemaParsingConfig.parse(SchemaParsingConfig.java:583)
        parsing com.sun.org.apache.xerces.internal.impl.xs.opti.SchemaParsingConfig.parse(SchemaParsingConfig.java:686)
        parsing com.sun.org.apache.xerces.internal.impl.xs.opti.SchemaDOMParser.parse(SchemaDOMParser.java:530)
        parsing com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.getSchemaDocument(XSDHandler.java:2181)
        parsing com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.parseSchema(XSDHandler.java:578)
        parsing com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaLoader.processJAXPSchemaSource(XMLSchemaLoader.java:827)
        parsing com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaLoader.loadSchema(XMLSchemaLoader.java:599)
        parsing com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaLoader.loadGrammar(XMLSchemaLoader.java:569)
        parsing com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaLoader.loadGrammar(XMLSchemaLoader.java:535)
        parsing com.sun.org.apache.xerces.internal.jaxp.validation.XMLSchemaFactory.newSchema(XMLSchemaFactory.java:254)
        parsing javax.xml.validation.SchemaFactory.newSchema(SchemaFactory.java:638)
        parsing org.apache.logging.log4j.core.config.xml.XmlConfiguration.<init>(XmlConfiguration.java:158)
        parsing org.apache.logging.log4j.core.config.xml.XmlConfigurationFactory.getConfiguration(XmlConfigurationFactory.java:46)
        parsing org.apache.logging.log4j.core.config.ConfigurationFactory$Factory.getConfiguration(ConfigurationFactory.java:472)
        parsing org.apache.logging.log4j.core.config.ConfigurationFactory.getConfiguration(ConfigurationFactory.java:266)
        parsing org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:613)
        parsing org.apache.logging.log4j.core.LoggerContext.setConfigLocation(LoggerContext.java:603)
        parsing org.apache.logging.log4j.core.selector.ClassLoaderContextSelector.locateContext(ClassLoaderContextSelector.java:157)
        parsing org.apache.logging.log4j.core.selector.ClassLoaderContextSelector.getContext(ClassLoaderContextSelector.java:74)
        parsing org.apache.logging.log4j.core.selector.ClassLoaderContextSelector.getContext(ClassLoaderContextSelector.java:57)
        parsing org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:148)
        parsing org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:45)
        parsing org.apache.logging.log4j.LogManager.getContext(LogManager.java:194)
        parsing org.apache.logging.log4j.spi.AbstractLoggerAdapter.getContext(AbstractLoggerAdapter.java:122)
        parsing org.apache.logging.slf4j.Log4jLoggerFactory.getContext(Log4jLoggerFactory.java:43)
        parsing org.apache.logging.log4j.spi.AbstractLoggerAdapter.getLogger(AbstractLoggerAdapter.java:46)
        parsing org.apache.logging.slf4j.Log4jLoggerFactory.getLogger(Log4jLoggerFactory.java:29)
        parsing org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:358)
        parsing org.apache.commons.logging.LogFactory$Slf4jDelegate.createLocationAwareLog(LogFactory.java:174)
        parsing org.apache.commons.logging.LogFactory.getLog(LogFactory.java:111)
        parsing org.apache.commons.logging.LogFactory.getLog(LogFactory.java:99)
        parsing org.springframework.boot.SpringApplication.getApplicationLog(SpringApplication.java:677)
        parsing org.springframework.boot.SpringApplication.run(SpringApplication.java:332)
        parsing com.mentor.dvt.coverageanalyzer.CoverageanalyzerApplication.main(CoverageanalyzerApplication.java:166)
        parsing com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:153)
        parsing com.oracle.svm.core.code.IsolateEnterStub.JavaMainWrapper_run_5087f5482cc9a6abc971913ece43acb471d2631b(generated:0)

        at com.oracle.graal.pointsto.util.AnalysisError.parsingError(AnalysisError.java:138)
        at com.oracle.graal.pointsto.flow.MethodTypeFlow.doParse(MethodTypeFlow.java:327)
        at com.oracle.graal.pointsto.flow.MethodTypeFlow.ensureParsed(MethodTypeFlow.java:300)
        at com.oracle.graal.pointsto.flow.MethodTypeFlow.addContext(MethodTypeFlow.java:107)
        at com.oracle.graal.pointsto.DefaultAnalysisPolicy$DefaultVirtualInvokeTypeFlow.onObservedUpdate(DefaultAnalysisPolicy.java:191)
        at com.oracle.graal.pointsto.flow.TypeFlow.notifyObservers(TypeFlow.java:352)
        at com.oracle.graal.pointsto.flow.TypeFlow.update(TypeFlow.java:394)
        at com.oracle.graal.pointsto.BigBang$2.run(BigBang.java:509)
        at com.oracle.graal.pointsto.util.CompletionExecutor.lambda$execute$0(CompletionExecutor.java:171)
        at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: java.lang.NullPointerException
        at jdk.vm.ci.code.BytecodePosition.<init>(BytecodePosition.java:57)
        at org.graalvm.compiler.graph.NodeSourcePosition.<init>(NodeSourcePosition.java:124)
        at org.graalvm.compiler.graph.NodeSourcePosition.<init>(NodeSourcePosition.java:115)
        at org.graalvm.compiler.graph.NodeSourcePosition.substitution(NodeSourcePosition.java:159)
        at org.graalvm.compiler.graph.NodeSourcePosition.substitution(NodeSourcePosition.java:155)
        at org.graalvm.compiler.replacements.GraphKit.createInvokeWithExceptionAndUnwind(GraphKit.java:284)
        at com.oracle.svm.hosted.annotation.AnnotationSupport$AnnotationEqualsMethod.buildGraph(AnnotationSupport.java:349)
        at com.oracle.graal.pointsto.meta.AnalysisMethod.buildGraph(AnalysisMethod.java:306)
        at com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.parse(MethodTypeFlowBuilder.java:186)
        at com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.apply(MethodTypeFlowBuilder.java:330)
        at com.oracle.graal.pointsto.flow.MethodTypeFlow.doParse(MethodTypeFlow.java:310)
        ... 12 more
Error: Image build request failed with exit status 1

The problem is that I cannot find the org.springframework.core.annotation.SynthesizedAnnotation$$ProxyImpl anywhere in my jars
is that related to dynamic class generation at runtime ? 

The command line option I'm using is as follows:

mx  -p /opt/graal/substratevm  native-image   -H:+ReportExceptionStackTraces  -H:ConfigurationFileDirectories=/tmp/config  -H:IncludeResources='META-INF/.*.json|META-INF/spring.factories|org/springframework/boot/logging/.*'  --allow-incomplete-classpath  --report-unsupported-elements-at-runtime  --delay-class-initialization-to-runtime='org.springframework.core.io.VfsUtils,org.springframework.boot.json.GsonJsonParser,org.springframework.http.converter.json.Jackson2ObjectMapperBuilder$XmlObjectMapperInitializer,org.springframework.data.web.XmlBeamHttpMessageConverter,org.springframework.data.web.ProjectingJackson2HttpMessageConverter,org.springframework.http.converter.json.Jackson2ObjectMapperBuilder$CborFactoryInitializer,org.springframework.http.converter.json.Jackson2ObjectMapperBuilder$SmileFactoryInitializer,org.springframework.core.annotation.SynthesizedAnnotation'  -classpath /opt/dev-graal/main/coverageanalyzer/build/libs/tmp/WEB-INF/classes:/opt/dev-graal/main/coverageanalyzer/build/libs/tmp/WEB-INF/lib/*:/opt/dev-graal/main/coverageanalyzer/build/libs/tmp/WEB-INF/lib-provided/* com.mentor.dvt.coverageanalyzer.CoverageanalyzerApplication

**Comment by cstancu** [comment]
@ramymagdy can you please provide the code for the spring boot app so I can reproduce?

**Comment by cstancu** [comment]
Can you please enable assertions by adding `-J-ea` to `native-image`? That should give us a better idea.
