### ISSUE TITLE
[Sulong] unistd.h does not exit on Windows

### ISSUE THREAD

**Issue by oroppas** [oracle/graal#1160]
… so the building of sulong fails:

```
Building com.oracle.truffle.llvm.libraries.bitcode with GNU Make... [rebuild needed by GNU Make]
C:\msys64\home\ryuta\packages\graal\graal\sulong\projects\com.oracle.truffle.llvm.libraries.bitcode/src/fork.c:31:10: fatal error: 'unistd.h' file not found
#include <unistd.h>
         ^~~~~~~~~~
1 error generated.
make: *** [C:\msys64\home\ryuta\packages\graal\graal\sulong\projects\com.oracle.truffle.llvm.libraries.bitcode\Makefile:65: bin/fork.noopt.bc] Error 1
```

**Comment by rschatz** [comment]
Sulong has some OS specific components. Currently it works only on Mac and Linux.

Windows support is planned, but I can't give you a concrete ETA yet.

**Comment by famod** [comment]
> Windows support is planned, but I can't give you a concrete ETA yet.

Has there been any progress on that matter? Thanks!

PS: I am not sure whether this is my actual root problem (see #1675, compilation of my Quarkus app failes due to missing `unistd.h`).

**Comment by fniephaus** [comment]
We are adding Windows support in the 22.3 release, see https://github.com/oracle/graal/issues/5007.
