### ISSUE TITLE
EE Download requires Oracle login, that is slow and unstable in China

### ISSUE THREAD

**Issue by paulvi** [oracle/graal#1164]
EE Download requires Oracle login, that is slow and unstable in China
(I could not get logged in this mongth, and today again 3 times)

Given that there is only 2 option to get GraalVM, and both have issues (#1162 and this). 
Please consider improving/adding more download services

**Comment by fernando-valdez** [comment]
This should be fixed by now. If that is not the case, please reopen the ticket
