### ISSUE TITLE
Substratevm - annotation member registered for reflection not found on proxy

### ISSUE THREAD

**Issue by mkouba** [oracle/graal#1167]
If I register an annotation class and method for reflection like this:
```java
RuntimeReflection.register(TestAnnotation.class);
RuntimeReflection.register(TestAnnotation.class.getDeclaredMethod("test"));
```
And then at runtime I try to invoke the method obtained from the runtime class of the annotation:
```java
TestAnnotation annotation = SomeTest.class.getAnnotation(TestAnnotation.class);
annotation.getClass().getDeclaredMethod("test").invoke(annotation);
```
I get `java.lang.NoSuchMethodException: com.github.mkouba.TestAnnotation$$ProxyImpl.test`.

I understand that the runtime class is the annotation proxy. Still, I would expect the methods of the proxy to be registered as well because there is no way to register them manually, or?

A simple reproducer can be found here:
https://github.com/mkouba/substrate-annotation-reflection

**Comment by cstancu** [comment]
@mkouba via 
```
RuntimeReflection.register(TestAnnotation.class.getDeclaredMethod("test"));
```
you are registering the method of the annotation interface for reflection, and not that of the proxy implementation. At runtime you need to access it via the annotation type, i.e., replace `getClass()` with `annotationType()`:
```
TestAnnotation annotation = SomeTest.class.getAnnotation(TestAnnotation.class);
annotation.annotationType().getDeclaredMethod("test").invoke(annotation);
```
I tried this on your reproducer and it works. (Thanks for the minimal reproducer by the way.)

Implementing annotations via a proxy is an implementation detail on JVM and we are doing it slightly different in `native-image`. The `com.github.mkouba.TestAnnotation$$ProxyImpl` class is a `native-image` specifc annotation implementation that doesn't expose the methods for reflection.

**Comment by mkouba** [comment]
@cstancu Thanks for looking into this. I know that annotation proxies are an implementation detail but I was just wondering if it would be possible to "redirect" the `getDeclaredMethod()` invocations somehow as it works fine on JVM. Anyway, the `Annotation.annotationType()` approach seems reasonable.

We've also noticed this commit: https://github.com/oracle/graal/commit/d2d4b2dbdbd996ebece4accd3f3ce8970076cfc5. Is it related?

**Comment by cstancu** [comment]
It is somewhat related, that's a fix for https://github.com/oracle/graal/issues/999, it preserves the default JDK implementation for run-time allocated annotations while maintaining the optimized implementation for ahead-of-time allocated annotation instances.
