### ISSUE TITLE
Execution times in repeated runs of a Truffle language script

### ISSUE THREAD

**Issue by jmaschad** [oracle/graal#1169]
Hi

I am working on a truffle language for data processing and have begun to measure script execution times for common workloads. A typical script is just a sequence of loops that iterate over batches of records.

I have observed, that script execution times are drastically reduced when executing the same script multiple times in the Java main class. Essentially, the second run halves the script execution time and subsequent runs give some additional but less significant improvements.

I expected this to be the overhead of the JIT compilation process but, to my surprise, the behaviour scales with input size. That is, for a dataset of 1GB, execution time of the first run is ~4 seconds and  subsequent runs take <= 2 seconds and for a dataset of 2GB the first run takes ~8 seconds and subsequent runs <= 4 seconds.

How can I investigate this behaviour further? Can I somehow mark certain parts of the code that should be JITed and optimized right away? I know that certain loops will be executed millions of times...

Thank you in advance

**Comment by fniephaus** [comment]
Graal and Truffle can make applications run really really fast, but warmup is sometimes a problem. Having said that, I would be surprised if the JIT has compiled everything it can within 8s. Instead, I would run it 50 or maybe even 100 times to see when things reach a steady state (if they don't, your code might have a problem).

If you want to see some information on Truffle compilation, I recommend to run your code with `-Dgraal.TraceTruffleCompilation=true`, maybe even with `-Dgraal.TraceTruffleCompilationDetails=true`.

Assuming you are implementing an AST interpreter for your language, I hope you are using [`LoopNode`](https://www.graalvm.org/truffle/javadoc/com/oracle/truffle/api/nodes/LoopNode.html). If you do, your loops should run as fast as possible, plus Truffle can perform on-stack-replacement on them. If you run with `-Dgraal.TraceTruffleCompilation=true`, OSR compiled loops show up with the `<OSR>` suffix.

Hope this helps!

**Comment by jmaschad** [comment]
Hey, thank you for the flags, I am going to report back any findings in this thread.

I had assumed that the decision to compile a piece of code is mainly dependent on how often that code is executed. Therefore, I expected that a `LoopNode` that calculates the average of a couple millions of doubles would be optmized and compiled very early. That would add a constant compilation overhead for the first evaluation but not a factor of the problem size.

I am running ad-hoc analytical queries that are usually executed just once. Are there optimizations that are only applied when a source is evaluated repeatedly?

**Comment by fniephaus** [comment]
> I had assumed that the decision to compile a piece of code is mainly dependent on how often that code is executed. Therefore, I expected that a LoopNode that calculates the average of a couple millions of doubles would be optmized and compiled very early. That would add a constant compilation overhead for the first evaluation but not a factor of the problem size.

Truffle applies partial evaluation and compiles methods when they get "hot". In case of a long running loop, however, it only knows how often the loop actually ran at the end of the method call. If you don't use `LoopNode`, your method might be compiled at some point, but probably not in the first iteration.

> I am running ad-hoc analytical queries that are usually executed just once. Are there optimizations that are only applied when a source is evaluated repeatedly?

Yes, you're looking for OSR for which you need `LoopNode`. The [docs](https://www.graalvm.org/truffle/javadoc/com/oracle/truffle/api/nodes/LoopNode.html) explain how to use it. Note that the default number of loop iterations until on-stack-replacement compilation is triggered is currently set to `100000`, but can be tweaked via `-Dgraal.TruffleOSRCompilationThreshold=10000` for example.

**Comment by jmaschad** [comment]
Ah sorry, I certainly use loop nodes already.

> Note that the default number of loop iterations until on-stack-replacement compilation is triggered is currently set to 100000, but can be tweaked via -Dgraal.TruffleOSRCompilationThreshold=10000 for example.

That sounds promissing!

Here is some code from my fold operator, just for reference.

```
  public Object fold() {
    frame.foldBatches(batch -> {
      AccumulatorNode accBody = new AccumulatorNode(batch);
      LoopNode loopNode = Truffle.getRuntime().createLoopNode(accBody);
      loopNode.executeLoop(null);
      intermediates.add(accBody.value);
      return true;
    });

    if (intermediates.size() == 0) {
      return unit;
    }

    if (intermediates.size() == 1) {
      return intermediates.get(0);
    }

    FolderNode foldBody = new FolderNode(intermediates);
    LoopNode loopNode = Truffle.getRuntime().createLoopNode(foldBody);

    return foldBody.result;
  }

  private class AccumulatorNode extends Node implements RepeatingNode {
    final RowPointer rowPtr;
    Object value = unit;

    public AccumulatorNode(VectorSchemaRoot inBatch) {
      rowPtr = new RowPointer(inBatch);
    }

    @Override
    public boolean executeRepeating(VirtualFrame frame) {
      value = accumulator.getCallNode().call(value, rowPtr);
      return rowPtr.advance();
    }
  }

  private class FolderNode extends Node implements RepeatingNode {
    final List<Object> intermediates;
    int idx = 1;
    Object result;

    public FolderNode(List<Object> intermediates) {
      this.intermediates = intermediates;
      result = intermediates.get(0);
    }

    @Override
    public boolean executeRepeating(VirtualFrame frame) {
      result = folder.getCallNode().call(result, intermediates.get(idx));
      idx += 1;
      return idx < intermediates.size();
    }
  }
```

**Comment by fniephaus** [comment]
First, I'd avoid Java lambdas when working with Truffle ASTs as the compiler might not be able to figure out that a node is constant. More importantly, you are missing a parent node. Your loop node is not part of any AST which will cause compilation errors. Maybe have a look at how simplelanguage implements [`SLWhileNode`](https://github.com/graalvm/simplelanguage/blob/34f29087f772de262b124aaff04169d66b7a3ae4/language/src/main/java/com/oracle/truffle/sl/nodes/controlflow/SLWhileNode.java) and its [`SLWhileRepeatingNode`](https://github.com/graalvm/simplelanguage/blob/857e81318917be6de7cd2677b62e713d7d1d5fd0/language/src/main/java/com/oracle/truffle/sl/nodes/controlflow/SLWhileRepeatingNode.java).

**Comment by jmaschad** [comment]
Hey Fabio, thank you for the advice. The missing parent node was a good catch that explains why the loop was not optimized.

**Comment by fniephaus** [comment]
Great! How's the performance improvement?

**Comment by jmaschad** [comment]
I did some quick experiments. My program performs a simple aggregation over a column of a data frame. The frame is loaded from disk in batches of 1 million rows. Batches are processed by a sequence of operators. 

I started measuring individual operator execution times as well. To my surprise I found that the performance of my fold operator is mostly constant overall. What does improve is data loading, which is done using a library function. The biggest improvement however is in the time that is not spend inside of any operator. That is, in the second and subsequent runs, overall time is almost exactly the sum of the operator times but in the first run there is some significant time spend elsewhere.

My first guess is that this additional time is simply some JVM *warming up* process that is still going on during the first run (for example compilation of the data loading library functions). I currently can not provide any better insights but I will report future findings in this thread.

~500MB
2.9070 sec, 1.1230 sec, 1.0190 sec
3.2010 sec, 1.1380 sec, 1.0630 sec
2.8850 sec, 1.0950 sec, 1.0670 sec

~1GB
4.2620 sec, 2.0770 sec, 1.7090 sec
3.6500 sec, 2.0230 sec, 1.5790 sec
5.1960 sec, 2.4650 sec, 1.7010 sec

~2GB
8.8160 sec, 3.1470 sec, 3.1110 sec
6.8290 sec, 2.8510 sec, 2.8490 sec
5.3240 sec, 3.1460 sec, 2.8740 sec

**Comment by fniephaus** [comment]
What kind of output do you get when running with `-Dgraal.TraceTruffleCompilation=true`?

**Comment by jmaschad** [comment]
I appended the output. The `JitRootNode(func)` is the aggregation function that is called in the  `AccumulatorRepeatingNode`. I was trying to see the generated assembly by copying the `-disassemble` JAVA_ARGS from SimpleLanguage but apparently this requires the hsdis library which is not included with Graal?

```
[truffle] opt done         JitRootNode(func) <opt>                                     |ASTSize      35/   35 |Time    83(  48+34  )ms |DirectCallNodes I    0/D    0 |GraalNodes   214/  701 |CodeSize         2637 |CodeAddress 0x1152efa10 |Source            n/a 
[truffle] opt done         AccumulatorRepeatingNode@183573a1<OSR> <opt>                |ASTSize       3/    3 |Time    24(  15+9   )ms |DirectCallNodes I    0/D    0 |GraalNodes    82/  292 |CodeSize         1160 |CodeAddress 0x1152f1310 |Source            n/a 
```

**Comment by fniephaus** [comment]
Cool, OSR is working. In a next step, you could analyze these compilation units with [igv](https://www.graalvm.org/docs/graalvm-as-a-platform/implement-language/#igv). Red nodes in Truffle graphs are usually performance problems (e.g. invocations, transferToInterpreter/deopt, ...).

**Comment by chumer** [comment]
Also note you should not store runtime values in your nodes. Instead they should be stored in the frame. This allows for more reliable virtualization of those values in the compiler.
You may reuse those nodes from SL for that: 
https://github.com/graalvm/simplelanguage/blob/master/language/src/main/java/com/oracle/truffle/sl/nodes/local/SLReadLocalVariableNode.java
https://github.com/graalvm/simplelanguage/blob/master/language/src/main/java/com/oracle/truffle/sl/nodes/local/SLWriteLocalVariableNode.java

**Comment by jmaschad** [comment]
Thank you for the comment, I will look into that.

I am not sure if I know what virtualization is. I believe it is an optimization that removes unnecessary copying of values. For example, if a value is passed as an argument to some function that only reads but does not update the value, it is not necessarry to create a copy for the argument but instead the original value can be read? Is this related to the difference between `VirtualFrame` and `MaterializedFrame`?

**Comment by fniephaus** [comment]
For the difference between `VirtualFrame` and `MaterializedFrame `, have a look at [this](http://fniephaus.com/2019/morevms19-efficient-activation-records.pdf).
