### ISSUE TITLE
Unable to load log4j configuration: Detected a ZipFile object in the image heap

### ISSUE THREAD

**Issue by inikolaev** [oracle/graal#1177]
I'm trying to build a native image and getting the following error in the end:

```
native-image --version
GraalVM Version 1.0.0-rc15 CE
```
```
Error: Detected a ZipFile object in the image heap. A ZipFile object contains pointers to unmanaged C memory and file descriptors, and these resources are no longer available at image run time. The object was probably created by a class initializer and is reachable from a static field. By default, all class initialization is done during native image building.You can manually delay class initialization to image run time by using the option --delay-class-initialization-to-runtime=<class-name>. Or you can write your own initialization methods and call them explicitly from your main entry point.
Trace: 	object java.util.zip.ZipFile$ZipFileInputStream
	object java.util.zip.ZipFile$ZipFileInflaterInputStream
	object sun.net.www.protocol.jar.JarURLConnection$JarURLInputStream
	object org.apache.logging.log4j.core.config.ConfigurationSource
	object org.apache.logging.log4j.core.config.properties.PropertiesConfiguration
	object org.apache.logging.log4j.core.LoggerContext
	object org.apache.logging.log4j.core.Logger
	object org.apache.logging.slf4j.Log4jLogger
```

This is similar to #495, if I understand correctly. If the fix is somewhat similar I could create a PR as well.

**Comment by cstancu** [comment]
This seems to be a `log4j` specific problem. It looks like a `ZipFile` object is initialized in the image heap. [This article](https://medium.com/graalvm/understanding-class-initialization-in-graalvm-native-image-generation-d765b7e4d6ed) should help.

**Comment by inikolaev** [comment]
Thanks, the article actually helped me to understand why it looked like the application was running, which was very confusing. Turned out I had some code in static initializer which started a thread.

As for `log4j` now I have a problem that latest version seems to be compiled against JDK 9, which, as far as I understand is not yet supported by Substrate VM.

I will close the issue then.

**Comment by inikolaev** [comment]
@cstancu Now looking at `log4j-api-2.11.2.jar` it looks like it uses multi-release jar and has several classes compiled against both JDK 7 and JDK 9. I feel like Substrate VM should ignore classes located under `META-INF/versions.9` and above until they are supported.

This is not really related to the original issue, do you want me to create a new one instead?

**Comment by cstancu** [comment]
Thanks for investigating further and for the suggestion. Yes, please open a new issue.

**Comment by amaury-mv** [comment]
what did you do to enable log4j? @inikolaev,  I have the same problem when using dynamo and micronaut

**Comment by hamadycisse** [comment]
Does this mean that as soon as you have log4j-api 2.11+ in your classpath you can no longer compile a native image using quarkus?
