### ISSUE TITLE
Missing docker image for RC16

### ISSUE THREAD

**Issue by ilopmar** [oracle/graal#1192]
The docker images for RC16 is not avaible:

```
$ docker pull oracle/graalvm-ce:1.0.0-rc16
Error response from daemon: manifest for oracle/graalvm-ce:1.0.0-rc16 not found
```

Can you please release it? Thanks!

**Comment by mzachh** [comment]
Hi Ivan,
sorry for the delay, the upload is internally pending and we will upload it as soon as possible.

If you need it earlier, you could also build it by your own:
Dockerfile: https://github.com/oracle/docker-images/tree/master/GraalVM/CE/1.0.0-rc16
```
docker build -t oracle/graalvm-ce:1.0.0-rc16 .
```

**Comment by ilopmar** [comment]
Thanks for the info. I just wanted to upgrade Micronaut documentation and profile to use rc16, but I'll wait until the image is available in docker hub.

**Comment by mzachh** [comment]
The image oracle/graalvm-ce:1.0.0-rc16 is now online.

Thanks for the report!

**Comment by ilopmar** [comment]
Thank you :)
