### ISSUE TITLE
[native-image] StringConcat indy delayed

### ISSUE THREAD

**Issue by johanvos** [oracle/graal#1198]
Running native-image with the following class will fail with the following error: 

`Error: Class that is marked for delaying initialization to run time got initialized during image building: Hello3$$StringConcat/0x00000007c09ff440`

```
public class Hello3 {

    String a = "a";
    String b = "b";

    public static void main(String[] args) throws Exception  {
        System.err.println("Hello, world");
        Hello3 me = new Hello3();
        me.bar();
    }

    void bar() {
        System.err.println("a + b = "+a+b);
    }

}
```

**Comment by vjovanov** [comment]
This issue has been fixed. Thanks @johanvos.
