### ISSUE TITLE
When start hive report 'Error calling jdk.vm.ci.services.Services.serializeSavedProperties'

### ISSUE THREAD

**Issue by yoreyuan** [oracle/graal#1203]
When I changed the JDK to `OpenJDK GraalVM CE 1.0.0-rc16`, I started the `Hive` prompt with the following error:
```
Error calling jdk.vm.ci.services.Services.serializeSavedProperties
java.io.UTFDataFormatException: encoded string too long: 83554 bytes
	at java.io.DataOutputStream.writeUTF(DataOutputStream.java:364)
	at java.io.DataOutputStream.writeUTF(DataOutputStream.java:323)
	at jdk.vm.ci.services.Services.serializeSavedProperties(Services.java:332)
```

**Comment by dougxc** [comment]
Thanks for the report. This occurs when initializing libgraal with the system properties of the VM. We hadn't considered the case of a system property value being longer than 65535 bytes. I'll fix. In the meantime, the work around is to either disable libgraal (i.e. `-XX:-UseJVMCINativeLibrary`) or to somehow avoid this long system property being passed to `Hive` by the relevant launcher.

**Comment by dougxc** [comment]
This is fixed by https://github.com/graalvm/graal-jvmci-8/commit/c6eba22155a84292220f64de4e40f0f443e3431f which should be part of the next GraalVM release. Please re-open if the problem still occurs in GraalVM 1.0.0-rc17.
