### ISSUE TITLE
unnecessary vzeroupper instruction generated with retq on x86

### ISSUE THREAD

**Issue by opportun1st** [oracle/graal#1204]
Currently vzeroupper is generated with retq as long as the CPU supports AVX. See the source code here: [AMD64HotSpotReturnOp.java#L114](https://github.com/oracle/graal/blob/87c4ce8eabe466ce13adb10a1bf527b8dc1e8c3b/compiler/src/org.graalvm.compiler.hotspot.amd64/src/org/graalvm/compiler/hotspot/amd64/AMD64HotSpotReturnOp.java#L114).

Here is a simple example and the corresponding generated code:
```
    private static int inc(int x) {
	x++;
	return x;
    }
```
```
  0x00002b0f78082ba0: nopl   0x0(%rax,%rax,1)
  0x00002b0f78082ba5: inc    %esi
  0x00002b0f78082ba7: mov    %esi,%eax
  0x00002b0f78082ba9: test   %eax,-0x8291ba9(%rip)        # 0x00002b0f6fdf1006
                                                ;   {poll_return}
  0x00002b0f78082baf: vzeroupper
  0x00002b0f78082bb2: retq
```

A vzeroupper instruction should be generated when it's really needed.

BTW, I don't see this issue with C2. We may follow what has been done there.

A simple test case is available here: [vzeroupper_test.tar.gz](https://github.com/oracle/graal/files/3124020/vzeroupper_test.tar.gz).

**Comment by mur47x111** [comment]
Thanks for the report! I agree that we are too conservative on generating `vzeroupper`. I will introduce a pass on the LIR to determine whether there is fp register usage.

**Comment by mur47x111** [comment]
Should be resolved by https://github.com/oracle/graal/commit/1b0b825a62506f52c8c01a0df30737c2fb98e625
