### ISSUE TITLE
Error with Micronaut and native-image: "class got initialized during image building"

### ISSUE THREAD

**Issue by ilopmar** [oracle/graal#1211]
It is now not possible to build a Micronaut native image with RabbitMQ support after this change https://github.com/oracle/graal/commit/b20dead4f4f0527dae948767992c82d4f43837f6 was merged in master last week.
Keep in mind that the application is using the suggested options: `--initialize-at-build-time=ch.qos.logback,com.fasterxml.jackson,fresh.graal,io.micronaut,io.netty,io.reactivex,org.reactivestreams,org.slf4j,org.yaml.snakeyaml,javax` and that this works properly with RC16.

To reproduce the issue:
- `git clone https://github.com/micronaut-graal-tests/micronaut-rabbitmq-graal`
- `cd micronaut-rabbitmq-graal`
- Use graal from master branch (currently rc18.dev)
- `./build-native-image.sh`

The image generation fails:
```
Warning: Using a deprecated option --rerun-class-initialization-at-runtime. Currently there is no replacement for this option. Try using --initialize-at-run-time or use the non-API option -H:ClassInitialization directly.
Warning: Using a deprecated option --delay-class-initialization-to-runtime. Use --initialize-at-run-time.
Warning: Using a deprecated option --delay-class-initialization-to-runtime. Use --initialize-at-run-time.
[graal-rabbitmq:7189]    classlist:   8,073.31 ms
[graal-rabbitmq:7189]        (cap):   1,800.56 ms
[graal-rabbitmq:7189]        setup:   4,026.45 ms
Warning: class initialization of class io.micronaut.configuration.rabbitmq.health.$RabbitMQHealthIndicatorDefinition failed with exception java.lang.NoClassDefFoundError: io/micronaut/management/health/indicator/AbstractHealthIndicator. This class will be initialized at run time because either option --report-unsupported-elements-at-runtime or option --allow-incomplete-classpath is used for image building. Use the option --initialize-at-run-time=io.micronaut.configuration.rabbitmq.health.$RabbitMQHealthIndicatorDefinition to explicitly request delayed initialization of this class.
[graal-rabbitmq:7189]     analysis:  84,597.71 ms
Error: Class that is marked for delaying initialization to run time got initialized during image building: com.rabbitmq.client.SocketConfigurator
Error: Use -H:+ReportExceptionStackTraces to print stacktrace of underlying exception
Error: Image build request failed with exit status 1
```

**Comment by vjovanov** [comment]
Have you tried `--initialize-at-build-time=com.rabbitmq.client.SocketConfigurator`. It probably got initialized by one of the classes in Micronaut.

**Comment by ilopmar** [comment]
Yes, I tried that and I also added `io.micronaut.configuration.rabbitmq` to the list but the error is the same.

**Comment by vjovanov** [comment]
I tried adding the two classes that fail to `--initialize-at-build-time` and it works. Also, adding `--initialize-at-build-time=com.rabbitmq.client` works well. Can you please verify?

**Comment by ilopmar** [comment]
Yes, that is working now but only using the deprecated options with the new ones. I'm also working on removing the deprecated options as discussed in #1217 and I think I tried both approaches and the same time.
I think that now everything should work.

**Comment by vjovanov** [comment]
Deprecated options do exactly the same thing as the new ones. They are deprecated because of the name change: when delay is default, it does not really make sense to say delay. 

I removed rerun and left it for internal use as the semantics is extremely complicated. I still need to see a solid use-case that justifies exposing this option.

**Comment by ilopmar** [comment]
Thanks for the clarification. Btw, I also needed to add `--initialized-to-build-time=io.netty.buffer,io.netty.util` to make it work.

**Comment by rahulkhanna2** [comment]
@ilopmar @vjovanov  can we add this to micronaut-maven-plugin.

**Comment by vjovanov** [comment]
I feel the config should not go into the maven plugin. @alvarosanchez might be a good person to decide.

**Comment by alvarosanchez** [comment]
This issue is no longer valid and there is nothing to add anywhere to compile a Micronaut application with RabbitMQ as a native executable
