### ISSUE TITLE
"No instances are allowed in the image heap for a class that is initialized or reinitialized at image runtime" in Micronaut

### ISSUE THREAD

**Issue by ilopmar** [oracle/graal#1212]
It is now not possible to build a Micronaut native image with the management and metrics endpoints enabled support after this change https://github.com/oracle/graal/commit/b20dead4f4f0527dae948767992c82d4f43837f6 was merged in master last week.

Keep in mind that the application is using the suggested options: `--initialize-at-build-time=ch.qos.logback,com.fasterxml.jackson,fresh.graal,io.micronaut,io.netty,io.reactivex,org.reactivestreams,org.slf4j,org.yaml.snakeyaml,javax` and that this works properly with RC16.

To reproduce the issue:

- `git clone https://github.com/micronaut-graal-tests/micronaut-management-graal`
- `cd micronaut-management-graal`
- Use graal from master branch (currently rc18.dev)
- `./build-native-image.sh`

The image generation fails:
```
Warning: Using a deprecated option --rerun-class-initialization-at-runtime. Currently there is no replacement for this option. Try using --initialize-at-run-time or use the non-API option -H:ClassInitialization directly.
Warning: Using a deprecated option --delay-class-initialization-to-runtime. Use --initialize-at-run-time.
Warning: Using a deprecated option --delay-class-initialization-to-runtime. Use --initialize-at-run-time.
[management-graal:12397]    classlist:   7,302.28 ms
[management-graal:12397]        (cap):   1,845.60 ms
[management-graal:12397]        setup:   4,021.09 ms
[management-graal:12397]     analysis:  81,498.24 ms
Error: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: No instances are allowed in the image heap for a class that is initialized or reinitialized at image runtime: io.micrometer.core.instrument.ImmutableTag
Detailed message:
Trace: 
	at parsing io.micronaut.configuration.metrics.binder.web.WebMetricsPublisher.uri(WebMetricsPublisher.java:223)
Call path from entry point to io.micronaut.configuration.metrics.binder.web.WebMetricsPublisher.uri(HttpResponse, String): 
	at io.micronaut.configuration.metrics.binder.web.WebMetricsPublisher.uri(WebMetricsPublisher.java:220)
	at io.micronaut.configuration.metrics.binder.web.WebMetricsPublisher.getTags(WebMetricsPublisher.java:175)
	at io.micronaut.configuration.metrics.binder.web.WebMetricsPublisher.error(WebMetricsPublisher.java:288)
	at io.micronaut.configuration.metrics.binder.web.WebMetricsPublisher.access$400(WebMetricsPublisher.java:45)
	at io.micronaut.configuration.metrics.binder.web.WebMetricsPublisher$1.onError(WebMetricsPublisher.java:147)
	at io.micronaut.http.context.ServerRequestTracingPublisher$1.lambda$onError$2(ServerRequestTracingPublisher.java:65)
	at io.micronaut.http.context.ServerRequestTracingPublisher$1$$Lambda$1825/1681011413.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:748)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:473)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:193)
	at com.oracle.svm.core.code.IsolateEnterStub.PosixJavaThreads_pthreadStartRoutine_e1f4a8c0039f8337338252cd8734f63a79b5e3df(generated:0)

Error: Use -H:+ReportExceptionStackTraces to print stacktrace of underlying exception
Error: Image build request failed with exit status 1
```

**Comment by ilopmar** [comment]
More information. Adding `--initialize-at-run-time=io.micronaut.configuration.metrics,io.micrometer` there is a new error:
```
Warning: Using a deprecated option --rerun-class-initialization-at-runtime. Currently there is no replacement for this option. Try using --initialize-at-run-time or use the non-API option -H:ClassInitialization directly.
Warning: Using a deprecated option --delay-class-initialization-to-runtime. Use --initialize-at-run-time.
Warning: Using a deprecated option --delay-class-initialization-to-runtime. Use --initialize-at-run-time.
[management-graal:8532]    classlist:  13,567.89 ms
[management-graal:8532]        (cap):   2,508.20 ms
[management-graal:8532]        setup:   6,963.92 ms
[management-graal:8532]     analysis: 125,271.13 ms
Error: Class that is marked for delaying initialization to run time got initialized during image building: io.micrometer.core.instrument.push.PushRegistryConfig
Error: Use -H:+ReportExceptionStackTraces to print stacktrace of underlying exception
Error: Image build request failed with exit status 1
```

**Comment by vjovanov** [comment]
When I composed the list I did not have metrics included. 
Try marking `io.micrometer.core.instrument.push.PushRegistryConfig` as build time. Probably adding the whole package would work as well. 

This is not technically an issue. It is just difficult to debug--I am working on providing better stack traces when this happens. To know how this class got initialized you can either print the stack trace in its static initializer or you can put a breakpoint (with `--debug-attach`) and see the stack trace.

If the application was running before with all classes initialized it will suffice to list all the packages. 

A nice way to find all the packages is to pass only `--initialize-at-build-time` and `-H:+PrintClassInitialization`. Then in the `EAGER` file, you will see all the classes that got initialized. From that list you can compose a correct list of packages.

**Comment by ilopmar** [comment]
Thank you for your quick reply. Adding `--initialize-at-build-time=io.micrometer.core` did the trick.

One question to make sure that I understand how this works. Once I add `-H:+PrintClassInitialization` the log files are generated and I can see the classes that got initialized eagerly == build-time? So I need to pass those classes to `--initialized-at-build-time` in case some of them fails?

**Comment by vjovanov** [comment]
Yes, I will rename eager to `build-time` and delay to `run-time`. It comes from the past when the default was initializing at build time.

When we fix the issue with lambdas you should never need to add `--initialize-at-build-time`. `--initialize-at-build-time` is there to make your framework start faster and that the images are smaller.

**Comment by ilopmar** [comment]
Thanks! Can you please let link here that issue so I can track it?

**Comment by vjovanov** [comment]
This is the issue: https://github.com/oracle/graal/issues/1218
