### ISSUE TITLE
Include package-info into the native image

### ISSUE THREAD

**Issue by gsmet** [oracle/graal#1216]
Hi,

Maybe it's simple but I wasn't able to figure out how to include a `package-info` into a native image.

We have a user trying to use JAXB and the generated `package-info` contains important information necessary for JAXB to work properly, namely:
```
@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.w3.org/2005/Atom", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package mapper.codegen.eforum;
```

I tried to see if the reflection API would allow me to register it but it doesn't look like it does. I tried with a reflection JSON file but it doesn't seem to change anything either.

I couldn't find any literature on the subject so I thought I might as well ask.

Thanks.

**Comment by cstancu** [comment]
We don't currently support this. Can you provide a simple example? How would you access the `package-info` at runtime?

**Comment by tcollignon** [comment]
Hi @cstancu 

I have provide a simple example here : https://github.com/tcollignon/quarkus-jaxb-test

If I run it with graalvm native image it fail like I described here : https://github.com/quarkusio/quarkus/issues/2199#issuecomment-487703960

Do you need more information? 

Thx you very much

**Comment by cstancu** [comment]
Thank you for your example. Can you show me an example of how JAXB is accessing `package-info` via reflection? The error in https://github.com/quarkusio/quarkus/issues/2199#issuecomment-487703960 `java.lang.ClassCastException: org.jboss.threads.JBossThread cannot be cast to java.lang.Thread` seems to be related to https://github.com/oracle/graal/issues/1200.

**Comment by tcollignon** [comment]
For the question "Can you show me an example of how JAXB is accessing package-info via reflection? ", I'm afraid that I can't help you :( I think it's in quarkus ? @gsmet I'm wrong?

**Comment by gsmet** [comment]
It really doesn't do anything fancy: it gets the package from the class then tries to access the package info.

From `java.lang.Package`:
```java
    private Class<?> getPackageInfo() {
        if (packageInfo == null) {
            try {
                packageInfo = Class.forName(pkgName + ".package-info", false, loader);
            } catch (ClassNotFoundException ex) {
                // store a proxy for the package info that has no annotations
                class PackageInfoProxy {}
                packageInfo = PackageInfoProxy.class;
            }
        }
        return packageInfo;
    }
```

So we would need a way to somehow register the `package-info` for reflection.

**Comment by cstancu** [comment]
This works with `native-image`:
```
package test;

public class Test {
	public static void main(String[] args) {
		TestAnnotation annotation = Test.class.getPackage().getAnnotation(TestAnnotation.class);
                System.out.println("annotation.type:  " + annotation.annotationType());
                System.out.println("annotation.value: " + annotation.value());
	}
}
```
(`Package.getAnnotation()` uses `Package.getPackageInfo()`.)
You just need to provide the reflection config:
```
[
  {
    "name" : "test.package-info"
  }
]
```
I attached [test.zip](https://github.com/oracle/graal/files/3199289/test.zip) with a complete example. You need to run `jvm.sh` to test the behavior on the JVM and `native.sh` to test the behavior on `native-image`. I Test with `GraalVM Version 19.0.0 CE`.

If you still have problems please provide a minimal reproducible example.

**Comment by tcollignon** [comment]
Hi 
So @gsmet , the fix must be in quarkus or in my application ? 
Thx

**Comment by gsmet** [comment]
Sorry for not following up here, this has been fixed in Quarkus a few months ago.
