### ISSUE TITLE
Import and Export does not work in Javascript

### ISSUE THREAD

**Issue by janostgren** [oracle/graal#1221]
Can not use import and export in JavaScript. 
Need it for subclassing of classes in my project

**Comment by wirthi** [comment]
Hi @janostgren 

we support `import` and `export`, but you need to select the newest ECMAScript version for that to work. In our default, 2019, this is not yet available.

```
js --js.ecmascript-version=2020
```

Best,
Christian

**Comment by janostgren** [comment]
Should I install and download something?

mån 6 maj 2019 kl. 13:31 skrev Christian Wirth <notifications@github.com>:

**Comment by janostgren** [comment]
I wait for a solution !

Den tis 7 maj 2019 kl 08:38 skrev Jan Östgren <jan.ostgren@gmail.com>:

**Comment by janostgren** [comment]
It works in my use case. Just changed name from .js to .mjs . Magic

tis 7 maj 2019 kl. 10:58 skrev Josef Haider <notifications@github.com>:
