### ISSUE TITLE
Passing Java Collections to from Java to Javascript

### ISSUE THREAD

**Issue by janostgren** [oracle/graal#1223]
Cannot find any examples of using Java Collections in JavaScript called from Java.
Should be possible but no documentation is avalble.

**Comment by wirthi** [comment]
Hi @janostgren 

In many cases, you can just pass them to JavaScript and access them like you would in pure JavaScript (get size, indexed access, iterate over them) - see https://www.graalvm.org/docs/graalvm-as-a-platform/embed/#access-guest-languages-directly-from-java. If you need more fine-grained access, you can use a Proxy from the Java side, like described in https://www.graalvm.org/docs/graalvm-as-a-platform/embed/#computed-arrays-using-polyglot-proxies.

Best,
Christian
