### ISSUE TITLE
Calling host method with TruffleObjects - converted to PolyglotList on the way out but not on the way back

### ISSUE THREAD

**Issue by jarohen** [oracle/graal#1228]
Hi there,

I'm currently passing one of my TruffleObjects to a Java host method - because my TruffleObject returns true from `hasArrayElements` it gets converted to a PolyglotList by ToHostNode::asJavaObject.

Let's say the Java method I'm calling just returns its parameter - I then get a PolyglotList in my guest language rather than my original TruffleObject. 

Is this expected? If so, could you maybe advise what I'm doing wrong, or whether I'm approaching the problem the wrong way?

Cheers,

James

**Comment by chumer** [comment]
Could you provide some context what you are trying to do? I assume you're implementing your own language?

If not, then you are on the wrong path. As a language embedder, you are restricted to use the GraalVM SDK Polyglot API only. You should not implement TruffleObject but use `ProxyArray` instead (you can also just pass in a Java array).
Here are the docs for embedding:

If you are implementing a language then you are also on the wrong path. Because the PolyglotList should not be passed directly to the language implementation.  I would need to know more what you are actually trying to do, maybe with a code example?

**Comment by jarohen** [comment]
Hey, thanks for the prompt reply!

Yes, I'm creating my own language. In this case, I'm creating a 'variant' object (the TruffleObject - similar to Haskell's ADTs), which can be used by users to create (e.g.) 'result' types - either a 'Success' object also containing a success value or an 'Error' type containing the error. The TruffleObject is hence the combination of the discriminator ('Success'/'Error') and any other values the user wishes to attach. I'm implementing the various array interop messages so that they can be passed to Java methods, and the Java methods can treat them as a list of their associated values.

I'm then passing one of these to a Java method by getting hold of the Java class using 'TruffleLanguage.Env.lookupHostSymbol', getting hold of an InteropLibrary and calling the Java method using `interopLibrary.invokeMember(theClass, "myMethod", theTruffleObj)` - the method (as a minimum repro) is:

```java
public static Object myMethod(Object obj) { return obj; }
```

Will attach some more code shortly once I've extracted it out into something self-contained!

Thanks again,

James

**Comment by jarohen** [comment]
examples below are in Kotlin, don't know if that'll be an issue?

VariantObject is:
```kotlin
@ExportLibrary(InteropLibrary::class)
class VariantObject(val paramCount: Int, val dynamicObject: DynamicObject) : TruffleObject {
    @ExportMessage
    fun hasArrayElements() = true

    @ExportMessage
    fun getArraySize() = paramCount

    @ExportMessage
    fun isArrayElementReadable(idx: Long) = idx < paramCount

    @ExportMessage
    fun readArrayElement(idx: Long) =
        if (isArrayElementReadable(idx)) dynamicObject[idx] else throw IndexOutOfBoundsException(idx.toInt())
}
```

I've got a `ValueNode` abstract class which is the supertype for most of my nodes:
```kotlin
@TypeSystem(
    Boolean::class, String::class,
    Long::class, Double::class,
    BigInteger::class, BigDecimal::class,
    BridjeFunction::class, RecordObject::class, VariantObject::class)
internal abstract class BridjeTypes

@TypeSystemReference(BridjeTypes::class)
@NodeInfo(language = "brj")
internal abstract class ValueNode : Node() {
    abstract fun execute(frame: VirtualFrame): Any
}
```

I write (for example) a vector expression that gets turned into a VectorNode (I've inlined a fair bit into this example - am aware, for example, that this isn't the most efficient way to get hold of the various envs/libraries).

For the case above, I'm creating a Vector expression containing one element, an expression that yields one of my VariantObjects - so the `els` array below, when it's complete, is a one-element array containing a single VariantObject. 

```kotlin
    inner class VectorNode(expr: VectorExpr) : ValueNode() {
        @Child
        var truffleEnv = getCtx().truffleEnv
        // getCtx() is essentially TruffleLanguage.getCurrentContext(BrjLanguage::class.java)
        // I store the truffle Env in that context

        val CORE = truffleEnv.lookupHostSymbol("brj.CoreKt")

        @Child
        var interop = InteropLibrary.getFactory().create(CORE)
        
        @Children
        // generates child nodes to evaluate each element of the vector
        val elNodes: Array<ValueNode> = expr.exprs.map(this@ValueExprEmitter::emitValueExpr).toTypedArray()

        @ExplodeLoop
        override fun execute(frame: VirtualFrame): Any {
            val els = truffleEnv.asGuestValue(arrayOfNulls<Any>(elNodes.size))

            for (i in 0 until elNodes.size) {
                interop.writeArrayElement(els, i.toLong(), elNodes[i].execute(frame))
            }

            return interop.invokeMember(CORE, "vector", els)
        }
    }
```

CoreKt.vector is 
```kotlin
fun vector(els: Array<*>): List<*> = els.toList()
```

When debugging, I find that this is passed an array containing a PolyglotList, my VariantObject having being converted by the ToHostNode - `vector` then returns a singleton list containing this PolyglotList, which fails when I (later) pass it to `expectVariantObject` (as generated by the TypeSystem)

I think that's all the related code! Let me know if anything's unclear

**Comment by jarohen** [comment]
I suspect my misunderstanding is around when to wrap/unwrap Truffle objects when passing them back and forth to Java. I hit a few issues earlier on when I had a mixture of Truffle objects and Java objects (the VectorNode, for example, used to just wrap its elements up in a Java list and pass the raw list around, but that hit issues with various Truffle functions that expected TruffleObjects, or wrapped HostObjects).

I'm currently attempting to deal with _everything_ as wrapped Truffle objects, including the implementation of vectors within the language. I was hoping to be able to use Java's collection types throughout, so that I don't have to reimplement them as part of the language - opting to only create Truffle types for types that don't exist in Java.

Thanks in advance for any advice you might be able to give this Truffle newbie! :)

James

**Comment by boris-spas** [comment]
Tracking internally as Issue GR-20917

**Comment by chumer** [comment]
@jarohen sorry for the late response. 

A few notes about this:
* You should not mix Java types with TruffleObject. If you want to reuse non TruffleObject Java types you may use `TruffleLanguage.Env.asGuestvalue`. Generally I'd not recommend using host interop to implement your collections. It is designed to serve embedders as a tool to pass in Java objects into guest languages, not for language implementations. That is why it tries to box lists into PolyglotLists for Object target types.
* Do not use third-party library code in paths that may be partially evaluated. This includes all the Java collection libraries. They are not built for partial evaluation. One my only use them behind a @TruffleBoundary. We want to provide more builtin collections in Truffle in the future. I agree that this can be a bit cumbersome at first for new language.
* I do not recommend using Kotlin for developing Truffle languages. It is untested and Kotlin might use abstractions that don't properly partially evaluate.

Let me know if you have further questions. 
We might be a little more responsive on the Slack channels: https://www.graalvm.org/slack-invitation/

**Comment by jarohen** [comment]
Hey @chumer, no worries at all, understand you folks are busy :)

> You should not mix Java types with TruffleObject
I suspected that'd be the case, will refactor it out. `asGuestValue` seems to be doing ok for a prototype, but I'd rather not use it longer term, for the reasons you specify

> Do not use third-party library code in paths that may be partially evaluated
yeah, I'm making sure they're behind `@TruffleBoundary` at the moment

> I do not recommend using Kotlin for developing Truffle languages
mm, I did wonder about this as well - am deliberately keeping it to very simple Kotlin, but at some point I'll hopefully get chance to port the nodes back to Java

have joined the slack now, thanks :smile:
