### ISSUE TITLE
[BUILD] Build issues on Linux Graal/GraalVM

### ISSUE THREAD

**Issue by neomatrix369** [oracle/graal#1233]
Recently the builds are failing due to a number of reasons, I have come across two of them that might be specific to the JDK usage:

Issue 1: Breaks due to gcc warnings (treated as errors)
https://circleci.com/gh/neomatrix369/awesome-graal/321

Issue 2: HotSpot version string missing
https://circleci.com/gh/neomatrix369/awesome-graal/314

Can you please recommend some other OpenJDK/JDK versions to use that wouldn't land us into these kinds of errors.

Also found an issue building `make` (see https://circleci.com/gh/neomatrix369/awesome-graal/298) and fixed it via https://github.com/neomatrix369/awesome-graal/commit/413933ad4420e0cf9bcdeebf5fb226becfee2555

**Comment by dougxc** [comment]
For what its worth, you could use the binaries at https://github.com/graalvm/openjdk8-jvmci-builder/releases instead of building them.

Issue 1 was fixed by https://github.com/graalvm/graal-jvmci-8/commit/49b68a769ebaebaf792fc03c98b3cf8e2384813e

Issue 2 should be fixed with this patch:
```
diff --git a/mx.jvmci/mx_jvmci.py b/mx.jvmci/mx_jvmci.py
index e62f463be7..992c119736 100644
--- a/mx.jvmci/mx_jvmci.py
+++ b/mx.jvmci/mx_jvmci.py
@@ -807,7 +807,7 @@ def get_hotspot_release_version(tag=mx.DEFAULT_JDK_TAG):
     #   OpenJDK 64-Bit Server VM (build 25.71-b01-internal-jvmci-0.49-dev, mixed mode)
     #   Java HotSpot(TM) 64-Bit Server VM (build 25.192-b12, mixed mode)
     last = output[-1]
-    m = re.search(r'.* \(build (\d+.\d+-b\d+)', last)
+    m = re.search(r'.*\(build (\d+.\d+-b\d+)', last)
     if m is None:
         mx.abort('Could not find HotSpot version in last line of `java -version` output:\n' + last)
     return m.group(1)
```
Please test that and I can integrate it.

**Comment by neomatrix369** [comment]
Awesome work @dougxc - super fast you guys are!

I'll give it a whirl, thanks for making the checking of HotSpot string a bit more resilient, you see different JDK versions (Free and Paid) might have formatted it differently.

**Comment by neomatrix369** [comment]
Just applied the patch to fix HotSpot string issue but now I get this:
```bash
Archiving JVMCI_HOTSPOT... [dependency jdk.vm.ci.hotspot.aarch64 updated]
Building HotSpot[product, server]... [dependency jdk.vm.ci.hotspot updated]
--------------- make command line ----------------------
env LANG=C \
make -C /home/graal/scripts/graal-jvmci-8/make ARCH_DATA_MODEL=64 HOTSPOT_BUILD_JOBS=1 ALT_BOOTDIR=/opt/java/openjdk MAKE_VERBOSE= HOTSPOT_RELEASE_VERSION=25.212-b03 USER_RELEASE_SUFFIX=jvmci-0.59 INCLUDE_JVMCI=true ZIP_DEBUGINFO_FILES=0 product docs
--------------------------------------------------------
make: Entering directory '/home/graal/scripts/graal-jvmci-8/make'

Building HotSpot[product, server] failed
1 build tasks failed
```

**Comment by neomatrix369** [comment]
Another such issue on a Linux box: https://ci.adoptopenjdk.net/job/jdk8-with-graal_build_x86-64_linux/2/console

**Comment by dougxc** [comment]
The recent failures are the same as Issue 1 which was fixed by https://github.com/graalvm/graal-jvmci-8/commit/49b68a769ebaebaf792fc03c98b3cf8e2384813e.

**Comment by dougxc** [comment]
Issue 2 is fixed by https://github.com/graalvm/graal-jvmci-8/commit/3b3f076a486faad903c6540cf64255463cbf66b5.

**Comment by dougxc** [comment]
I believe all problems in this issue have been addressed. Please reopen with a description of anything unresolved if not.

**Comment by neomatrix369** [comment]
We have made progress with the above issues but the tests JVMCI fail - see https://circleci.com/gh/neomatrix369/awesome-graal/343

I have set my build to fail if the tests fail, I'll open this one as a separate issue.

**Comment by neomatrix369** [comment]
First OOM error encountered when building GraalVM suite, see https://github.com/graalvm/graalpython/issues/92
