### ISSUE TITLE
Incomplete classpath and reflection configuration generated with native-image-agent

### ISSUE THREAD

**Issue by mduesterhoeft** [oracle/graal#1238]
I am trying to use the `native-image-agent` to generate the native image configuration files.

When running my application with the agent I need to mock out some dependencies and to do so I needed to have a few dependencies on the classpath that my "real" application does not know (e.g. WireMock).

Thus the generated `reflect-config.json` contains classes that are not inside the real jar file. 
This leads to errors when running `native-image` 
```
Error: Error parsing reflection configuration in /tmp/native-image-config/reflect-config.json:
Class com.github.tomakehurst.wiremock.admin.FindStubMappingsByMetadataTask not found
```
I tried to set `--allow-incomplete-classpath` but with no effect.

I think it would be very convenient if the `native-image` tool would just ignore missing classes (or allow configuration via `--allow-incomplete-classpath`)

What do you think?

I am using 1.0.0-rc15

**Comment by mduesterhoeft** [comment]
Please see also for a complete motivation why this is useful:
https://medium.com/@mathiasdpunkt/ease-creation-of-graalvm-native-images-using-assisted-configuration-68a86dea07c7

**Comment by peter-hofer** [comment]
Even with `--allow-incomplete-classpath`, ignoring when a class is missing that is explicitly specified in a configuration file doesn't sound ideal.
`native-image-agent` already uses a package-based filter for various JDK- and JVM-internal classes, which then are not included in the resulting configurations. We have already discussed making this filter configurable. Would this help your situation?

**Comment by mduesterhoeft** [comment]
Thanks for your response - I think that would help as well. At least a user would have a chance to work around such problems.

**Comment by peter-hofer** [comment]
Such filters have been introduced, please see [section _Access Filters_ in BuildConfiguration.md](https://github.com/oracle/graal/blob/master/substratevm/BuildConfiguration.md#access-filters).
