### ISSUE TITLE
MLE docs outdated and inconsistent

### ISSUE THREAD

**Issue by fniephaus** [oracle/graal#1242]
The [MLE example page](https://www.graalvm.org/docs/examples/mle-oracle/) mentions [`dbjs`](https://github.com/oracle/graal/blob/c8a76e616634c25beb913fccb63c58a5174b2598/docs/examples/mle-oracle/index.html#L635) which does not seem to be available in public (yet).

Moreover, https://oracle.github.io/oracle-db-mle/js/deploy/ can be found through Google and mentions `dbjs` for MLE 0.2.7. The rest of the website, however, is about MLE 0.3.0 (the latest version at the moment).

**Comment by lucasbraun** [comment]
Thanks for your comment, @fniephaus.

The newest version of MLE is 0.3.0 and, as you observed correctly, MLE 0.3.0 comes without `dbjs`. The reason for this is that `dbjs` has been factored out into a separate project. We wrote a blog that explains how to program your own "poor-man" dbjs: https://medium.com/graalvm/bringing-modern-programming-languages-to-the-oracle-database-with-graalvm-80914d0c0167

It might be worth mentioning the second-newest version of MLE (MLE 0.2.7) contains `dbjs`, the main difference between 0.2.7 and 0.3.0 being that 0.2.7 is based on Oracle Database 12.1, while 0.3.0 is based on Oracle Database 12.0. So if you do not have any specific Oracle Database version constraints, you might as well got with MLE 0.2.7 and use `dbjs` out of the box.

**Comment by fniephaus** [comment]
@lucasbraun thanks for the info. What are the plans regarding `dbjs`? We don't want to get used to `dbjs` if it's not going to be released any time soon.

**Comment by lucasbraun** [comment]
We do not plan to release a new `dbjs` version before the next MLE release (if there will be one).
