### ISSUE TITLE
jdk.internal.logger is not exposed

### ISSUE THREAD

**Issue by johanvos** [oracle/graal#1244]
FormatAccessors and other classes require jdk.internal.logger to be opened, otherwise this error is thrown:
Error loading a referenced type: java.lang.IllegalAccessError: class com.oracle.svm.core.jdk.FormatAccessors (in unnamed module @0x3fe5d9b2) cannot access class jdk.internal.logger.SurrogateLogger (in module java.base) because module java.base does not export jdk.internal.logger to unnamed module @0x3fe5d9b2

The simple fix is to add jdk.internal.logger to the list of opened packaged by java.base

**Comment by bobmcwhirter** [comment]
fwiw I think this was fixed via https://github.com/oracle/graal/pull/1245/files

**Comment by cstancu** [comment]
@bobmcwhirter thanks!
