### ISSUE TITLE
[native-image] DynamicProxyConfiguration from resource 

### ISSUE THREAD

**Issue by bufferings** [oracle/graal#1246]
GraalVM Version: 1.0.0-rc16

It would be useful for me if I can put my dynamic proxy configuration file into JAR file (resource directory) like `ReflectionConfigurationResources` and specify it in `native-image.properties` as follows:

```
Args = -H:DynamicProxyConfigurationFiles=${.}/dynamic-proxy-config.json
```

Sample Project:

https://github.com/bufferings/micronaut-petclinic

Currently I put the config file in the project directory `dynamic-proxy/config.json` and reference it from [native-image.properties](https://github.com/bufferings/micronaut-petclinic/blob/master/src/main/resources/META-INF/native-image/com.example.micronaut/petclinic-application/native-image.properties) like this:

```
Args = -H:DynamicProxyConfigurationFiles=dynamic-proxy/config.json
```

But I would like to put the file into the same directory as the reflection config JSON file if possible.

**Comment by cstancu** [comment]
@bufferings I think this should be possible (at least with the latest master) since the two configs share the same implementation.

**Comment by christianwimmer** [comment]
The option `DynamicProxyConfigurationResources` exists already, and I don't think this is a recent addition. Does the option not work on RC16?

**Comment by bufferings** [comment]
@cstancu @christianwimmer 
ah, I missed it! I will try it.

https://github.com/oracle/graal/blob/master/substratevm/DYNAMIC_PROXY.md#manual-configuration

**Comment by bufferings** [comment]
It works! Thank you @cstancu @christianwimmer !
