### ISSUE TITLE
[native-image] ClassCastException: java.lang.Object cannot be cast to com.oracle.truffle.polyglot.PolyglotLanguageContext

### ISSUE THREAD

**Issue by lburgazzoli** [oracle/graal#1247]
I'm trying to use js' arrow functions in some js code executed using truffle js from an native executable and I get 

    ClassCastException: java.lang.Object cannot be cast to com.oracle.truffle.polyglot.PolyglotLanguageContext

the goal is to use arrow functions to implement a functional interface, the js code is:

```js
from('timer:js?period=1s')
    .setBody()
        .constant('test')
    .setHeader('test')
        .constant('test')
    .process(e => e.getMessage().setBody('test'))
    .to('log:js?showAll=false&multiline=false')
```

an example project can be found here: https://github.com/lburgazzoli/camel-routes-loader-graalvm

**Comment by chumer** [comment]
Could you provide the exact arguments how you created the native image?

Also when I try to build I get
```
[INFO] Required toolchain: jdk [ id='graalvm' version='1.0.0' ]
[ERROR] No toolchain found for type jdk
[ERROR] Cannot find matching toolchain definitions for the following toolchain types:
jdk [ id='graalvm' version='1.0.0' ]
```
what am I doing wrong?

**Comment by lburgazzoli** [comment]
you need to set-up the maven toolchain plugin:

in .m2/toolchains.xml  I have:
```xml
<toolchains>
  <toolchain>
    <type>jdk</type>
    <provides>
      <id>graalvm</id>
      <version>1.0.0</version>
      <vendor>oracle</vendor>
    </provides>
    <configuration>
      <jdkHome>/opt/java/graalvm-ce-1.0.0-rc16</jdkHome>
    </configuration>
  </toolchain>
</toolchains>
``

**Comment by lburgazzoli** [comment]
The argument used to create the native images are:

```
--verbose 
--no-server 
--language:js 
-J-Xmx10G 
-H:ReflectionConfigurationFiles=${project.basedir}/src/graalvm/reflection.json
-H:DynamicProxyConfigurationFiles=${project.basedir}/src/graalvm/proxy.json
-H:IncludeResources=META-INF/.* 
-H:Features=org.apache.camel.graalvm.support.CamelFeature 
-DCamelSimpleLRUCacheFactory=true
```

**Comment by lburgazzoli** [comment]
Looks like this bug affects truffle in general, see https://github.com/apache/camel-k/issues/873

**Comment by lburgazzoli** [comment]
Seems to be fixed with the latest release
