### ISSUE TITLE
native-image won't work on windows if graalvm path contains spaces

### ISSUE THREAD

**Issue by CptMauli** [oracle/graal#1255]
The scripts on windows (native-image.cmd) which build the actual path for the call, won't work if there is a space in the path ("Program Files" anyone?).

**Comment by olpaw** [comment]
@CptMauli thanks for reporting. A fix is on its way to master and will also get backported to 19.1.

**Comment by olpaw** [comment]
Fix on masters:
https://github.com/graalvm/mx/commit/c90c34ff90bd021b9ce3c4c7b9bd21d4d6edac58
https://github.com/oracle/graal/commit/b6590ef5ef947ea86c80b9c56620455d7f9fd850
It will also be in 19.1.0
