### ISSUE TITLE
[svm] VM does not support the minimum JVMCI API version required by Graal: 0.59 < 19.1

### ISSUE THREAD

**Issue by fniephaus** [oracle/graal#1256]
I'm trying to build a native image of my language using [JVMCI 0.59](https://github.com/graalvm/openjdk8-jvmci-builder/releases/tag/jvmci-0.59), which appears to be the latest public version, but I get the following error:

>The VM does not support the minimum JVMCI API version required by Graal: 0.59 < 19.1.

I assume this work with `oraclejdk-8u212-jvmci-19-b01-linux-amd64.tar.gz` from OTN, but I'm looking for an open version that our CI can download directly. Maybe we need a new release of `openjdk8-jvmci-builder`, @dougxc?

Best,
Fabio

**Comment by dougxc** [comment]
We will make a new JVMCI release next week. However, I'm confused as to why you are hitting this problem since the `master` branch on GitHub still [only requires](https://github.com/oracle/graal/blob/d617672c972d95949eae4d5015744170637c22ae/compiler/src/org.graalvm.compiler.hotspot/src/org/graalvm/compiler/hotspot/JVMCIVersionCheck.java#L46) `0.57`. What sources are you using? What are you running?

**Comment by fniephaus** [comment]
I'm building against [`vm-19.0.0`](https://github.com/oracle/graal/tree/0721d343872c6e7e036402547d9a76ed43f69637).

**Comment by dougxc** [comment]
There are now `jvmci-19-b01` binaries at https://github.com/graalvm/openjdk8-jvmci-builder/releases/tag/jvmci-19-b01.

**Comment by fniephaus** [comment]
Great, that's perfect and works like a charm! Have a great weekend :)

**Comment by jonathansantilli** [comment]
Hello @dougxc, I hope you are great today.

Am having kind of the same issue, running the [NativeImageGeneratorRunner](https://github.com/oracle/graal/blob/master/substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/NativeImageGeneratorRunner.java#L87) through the main method, as a normal java app, I get the following exception:

```
Exception in thread "main" java.lang.UnsupportedOperationException: The VM does not support the JVMCI API.
Currently used Java home directory is /Library/Java/JavaVirtualMachines/openjdk1.8.0_212-jvmci-19-b01/Contents/Home/jre.
Currently used VM configuration is: OpenJDK 64-Bit Server VM
	at jdk.vm.ci.runtime.JVMCI.getRuntime(JVMCI.java:71)
	at com.oracle.svm.hosted.c.GraalAccess.getGraalCapability(GraalAccess.java:50)
	at com.oracle.svm.hosted.c.GraalAccess.getOriginalTarget(GraalAccess.java:38)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.isValidArchitecture(NativeImageGeneratorRunner.java:222)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.verifyValidJavaVersionAndPlatform(NativeImageGeneratorRunner.java:427)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:233)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:519)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:118)
```

I have tried with these different versions of the JVM from https://github.com/graalvm/openjdk8-jvmci-builder:
- openjdk1.8.0_212-jvmci-19-b01
- openjdk1.8.0_242-jvmci-20.0-b02
- openjdk1.8.0_242-jvmci-20.1-b01

Also with GraalVM versions:
- graalvm-ce-java11-20.0.0
- graalvm-ce-java8-20.0.0

I am running the `NativeImageGeneratorRunner#main` method with the IDE, I want to debug steps by steps the image generation process without the `mx` command. Is that possible or am I missing something?

Thanks a lot in advance for any guidance.
