### ISSUE TITLE
Apart from Isolates is there another way of marking methods to participate in region based memory management?

### ISSUE THREAD

**Issue by kimec** [oracle/graal#1268]
Greetings.

I am wondering whether the annotation based region "tagging" as originally described in @cstancu's [dissertation](https://escholarship.org/uc/item/2kv6w8m4) evolved directly into Isolates or is it still possible to have region based allocation and deallocation on region exits within a single Isolate in the current incarnation of SubstrateVM?

Thank you.

**Comment by cstancu** [comment]
@kimec the region based memory management that you are mentioning is not part of the current memory management techniques in SubstrateVM.

**Comment by kimec** [comment]
Indeed, thank you very much for the explanation.
