### ISSUE TITLE
Persistence of compiled c1/c2 state

### ISSUE THREAD

**Issue by up-to-you** [oracle/graal#1283]
Are there any plans or already implemented feature to save application's machine code (or maybe partially) compiled by c1 and c2 jit (actually graalvm) such that consequent app startups will not require warmup and related decision making ? 

I don't mean such full aot like substratevm provides , but something like implemented in openj9 (saving compiled machine code from jit compilers  for further reuse=))

**Comment by dougxc** [comment]
There are no current plans for this feature. Also, it would require extensive HotSpot changes so would probably best be done as an OpenJDK project.
