### ISSUE TITLE
Class.forName is not initializing class

### ISSUE THREAD

**Issue by johanvos** [oracle/graal#1288]
In hotspot, the class initializer is called when Class.forName() is called, but this is not the case in substratevm. 
Consider these classes:
```
public class A {
    public static void main(String[] args) throws Exception {
        System.err.println("A main");
        Class c = Class.forName("B");
        System.err.println("c = "+c);
        B b = new B();
    }
}
```
```
public class B {
  
    static {
        System.err.println("B clinit");
    }

    public B() {
        System.err.println("B init");
    }
}
```

With hotspot, running A results in
```
A main
B clinit
c = class B
B init
```

With native image, the order is different:
```
A main
c = class B
B clinit
B init
```

**Comment by dmlloyd** [comment]
Both behaviors are within spec AFAIK.

**Comment by johanvos** [comment]
Class.forName javadoc says:

```
Returns the Class object associated with the class or interface with the given string name. Invoking this method is equivalent to:
Class.forName(className, true, currentLoader)
```

The 3-arg method is 
```
public static Class<?> forName(String name,
                               boolean initialize,
                               ClassLoader loader)
```

with the initialize defined as
`initialize - if true the class will be initialized. See Section 12.4 of The Java Language Specification.
`

**Comment by dmlloyd** [comment]
Ah I thought that it defaulted `initialize` to `false`, my bad.

It looks like `DynamicHub#forName` just ignores the init parameter.  It should be a simple change to have it call `ensureInitialized` on the target class if the flag is `true`.

**Comment by vjovanov** [comment]
This has been fixed.
