### ISSUE TITLE
[native-image]How to dump more information when running into errors?

### ISSUE THREAD

**Issue by ziyilin** [oracle/graal#1289]
We have sucessfully run a native-image version of RocketMQ's ( https://github.com/apache/rocketmq) client module, but got `java.lang.OutOfMemoryError: Garbage-collected heap size exceeded` after a few days' continous running.
Is there any way to print more reports or issue a core dump other than this one line message?

**Comment by cstancu** [comment]
There are a number of options that allow you to get verbose GC output:
```
  -R:±PrintGC                                  Print summary GC information after each collection. Default: - (disabled).
  -R:±PrintGCSummary                           Print summary GC information after main completion. Default: - (disabled).
  -R:±PrintGCTimeStamps                        Print a time stamp at each collection, if +PrintGC or +VerboseGC. Default: - (disabled).
  -R:±PrintGCTimes                             Print the time for each of the phases of each collection, if +VerboseGC. Default: - (disabled).
  -R:±PrintHeapShape                           Print the shape of the heap before and after each collection, if +VerboseGC. Default: - (disabled).
  -R:±VerboseGC                                Print more information about the heap before and after each collection. Default: - (disabled).
```
(Btw, you can obtain this list via `$ native-image --expert-options-all | grep GC`).

**Comment by cstancu** [comment]
You can also generate native heap dumps on demand. See: https://www.graalvm.org/docs/reference-manual/native_heapdump/.

**Comment by ziyilin** [comment]
Great, thanks!
