### ISSUE TITLE
[native image] Is native-image portable on different Linux releases?

### ISSUE THREAD

**Issue by ziyilin** [oracle/graal#1290]
When a native-image is built on one Linux release such as CentOS 7, can it run on another Linux release such as CentOS 6 or Ubuntu?

**Comment by olpaw** [comment]
Hi @ziyilin,
for images the same restrictions as for other native-compiled binaries apply. I.e. if e.g. a C/C++ application built on CentOS 7 runs on CentOS 6 so does a native image.

**Comment by ziyilin** [comment]
Thanks.
