### ISSUE TITLE
issue with okhttp with graalvm-ce-19.0.0

### ISSUE THREAD

**Issue by ludoch** [oracle/graal#1294]
With graalvm-ce-19.0.0 I get
```
...
Caused by: java.nio.charset.UnsupportedCharsetException: UTF-32BE
	at java.nio.charset.Charset.forName(Charset.java:531)
	at okhttp3.internal.Util.<clinit>(Util.java:75)
	at com.oracle.svm.core.hub.ClassInitializationInfo.invokeClassInitializer(ClassInitializationInfo.java:347)
	at com.oracle.svm.core.hub.ClassInitializationInfo.initialize(ClassInitializationInfo.java:267)
```
Which I did not have with the RC candidates...
Is it a regression or a feature? Any workaround?
https://github.com/square/okhttp/blob/5cfa0bb3e6d1cdba89761806ff6999f59a15c0eb/okhttp/src/main/java/okhttp3/internal/Util.java#L84
did not  change in my tests between RCs and 19.0.0.

**Comment by ludoch** [comment]
Correction: I changed the okhttp version so this is not related to the 19.0.0 release.
Anyway, the bug is valid with this version of okhttp3

**Comment by ludoch** [comment]
Solution: add this in your reflect.json configuration
```
  {
  "name" : "sun.nio.cs.ext.ExtendedCharsets",
    "allDeclaredConstructors" : true,
    "allPublicConstructors" : true,
    "allDeclaredMethods" : true,
    "allPublicMethods" : true,
    "allDeclaredClasses" : true,
    "allPublicClasses" : true
  }
```

As this class in initialized via reflection in the OpenJDK Charset class.

**Comment by ludoch** [comment]
Sorry, spoke too soon... My json file does not fix this...

**Comment by causalnet** [comment]
Try the `-H:+AddAllCharsets` command line option when running the native image generator.

from the help text:
>  -H:±AddAllCharsets                           Make all hosted charsets available at run time. Default: - (disabled).

**Comment by vjovanov** [comment]
We changed class initialization to delay class to runtime by default. This exposes extra JNI functions that were not there before. You can find out more [here](https://github.com/oracle/graal/blob/master/substratevm/CLASS-INITIALIZATION.md).

**Comment by ludoch** [comment]
Great, thanks for the info in the flag which works. Feel free to close the bug, I am sure it will help others even if closed.

**Comment by szpak** [comment]
What is the best way to add just those 2 charsets (without using `-H:±AddAllCharsets`)?

I have seen implementation in [LocalizationFeature](https://github.com/oracle/graal/blob/79d85a3f0a41bb264dd396f6ff335da29525bcd1/substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jdk/LocalizationFeature.java#L116-L128), but even with static initialization in my cade, when a class is put into `build_time_classes*.txt`, it still fails with `java.nio.charset.UnsupportedCharsetException: UTF-32BE`.

**Comment by drocsid** [comment]
@szpak Did you ever figure that out?

**Comment by wirthi** [comment]
Problem has long been resolved, closing.

**Comment by gstaykov** [comment]
for those using maven plugin you can add `-H:+AddAllCharsets`  like this:

```
            <plugin>
                <groupId>org.graalvm.buildtools</groupId>
                <artifactId>native-maven-plugin</artifactId>
                <configuration>
                    <imageName>${project.name}</imageName>
                    <fallback>false</fallback>
                    <verbose>true</verbose>
                    <quickBuild>true</quickBuild>
                    <buildArgs>
                        <arg>-H:+AddAllCharsets</arg>
                    </buildArgs>
                    <metadataRepository>
                        <enabled>true</enabled>
                    </metadataRepository>
                </configuration>
            </plugin>
