### ISSUE TITLE
Minimal JDBC example hanging

### ISSUE THREAD

**Issue by elliots** [oracle/graal#1296]
Hi, I'm trying to use JDBC from a native-image but had a problem with the build executable hanging when trying to connect to the database.

When trying to isolate the problem to create an issue, my project started working. Adding back things until it broke again I've worked out if I annotate one method in my project with @CEntryPoint but build as an executable instead of a shared library, the executable will start but not connect to a database.

Which is a bit strange obviously. It hangs somewhere inside Driver.connect.
If I comment out the @CEntryPoint annotation, it works.
My main method doesn't refer to the class with the annotation.
The class with the annotation is totally empty and imports nothing except IsolateThread, CEntryPoint, and CCharPointer.

Is this known/expected? Should I make a project that demonstrates it?

**Comment by elliots** [comment]
AAaaha! Having this in the project makes database drivers hang on connect

```java
       @CEntryPoint(name = "connect")
	public static int connect(IsolateThread thread) throws Exception {
		return 123;
	}
```

This makes it all work

```java
        @CEntryPoint(name = "notconnect")
	public static int connect(IsolateThread thread) throws Exception {
		return 123;
	}
```

My entry point name is clashing with a built-in function?

**Comment by olpaw** [comment]
@elliots by using `@CEntryPoint(name = "notconnect")` you are simply changing the name under which Java method `connect` will be exposed to native. I assume some code on the native side ldopens your shared object and dlsysm for "connect". By renaming to `"notconnect"` you likely just suppress the native code path that would call static method connect.

For more info about calling into and from native code see:
https://github.com/oracle/graal/blob/master/substratevm/README.md#images-and-entry-points
https://github.com/oracle/graal/blob/master/substratevm/C-API.md

Properly calling into a Java method from C:
https://github.com/oracle/graal/blob/45461e0a765fbd7c4f0adbb01a23a3fbca5840f2/substratevm/src/com.oracle.svm.tutorial/native/cinterfacetutorial.c#L115
https://github.com/oracle/graal/blob/45461e0a765fbd7c4f0adbb01a23a3fbca5840f2/substratevm/src/com.oracle.svm.tutorial/src/com/oracle/svm/tutorial/CInterfaceTutorial.java#L198

CC @peter-hofer

**Comment by elliots** [comment]
What I'm saying is that if I have a class with an CEntryPoint whose name is "connect", I can't use JDBC drivers... in a native executable that doesn't even use the class with the CEntryPoint. I'm not calling that entrypoint. I'm not building it as a shared library.

**Comment by olpaw** [comment]
Ok, then I'd guess having a `"connect"` symbol already defined by the image prevents getting the connect symbol defined in the JDBC driver as part of interfacing with JDBC via JNI.

**Comment by elliots** [comment]
This is the test code i'm compiling with native-image.. it never returns after d.connect

```java
	public static void main(String[] args) throws Exception {
		Driver d = (Driver) Class.forName("org.postgresql.Driver").newInstance();
		Properties info = new Properties();
		info.put("user", "root");
		info.put("password", "password");
		Connection conn = d.connect("jdbc:postgresql://localhost/test?loggerLevel=DEBUG", info);

		try (Statement stmt = conn.createStatement(); ResultSet rs = stmt.executeQuery("SELECT 123;");) {
			rs.next();
			System.out.println("result: " + rs.getInt(1));
		}
	}
```

This is how I'm building the native image...

```bash
mvn compile

CLASSPATH="`mvn -q exec:exec -Dexec.executable=echo -Dexec.args='%classpath'`:`cd target/classes && pwd`"

native-image --no-server --report-unsupported-elements-at-runtime --allow-incomplete-classpath '-H:IncludeResources=.*' --no-fallback -H:+ReportExceptionStackTraces --initialize-at-build-time=com.sun.jna.platform.win32.Win32Exception,com.sun.jna.LastErrorException,org.postgresql.Driver,org.postgresql.core.Logger,org.postgresql.util.SharedTimer -cp $CLASSPATH -H:Name=simpletest SimpleTest
./simpletest "org.postgresql.Driver" "jdbc:postgresql://localhost/test?loggerLevel=DEBUG" "root" "password" "SELECT 1;"
```

I don't believe the postgres driver (or the mysql and mssql drivers I've also tried) use JNI... I think they are pure java. I'll put this all together into a repo that reproduces what I'm seeing.

**Comment by peter-hofer** [comment]
Methods that are declared as C entry points are, by design, always included in an image. (C entry points are also unrelated to JNI.) My guess is that by declaring a `connect` symbol, you replace the library function with the same name which performs a system call to connect a socket to an address. This function is called behind the scenes in `java.net` and `java.nio` and therefore likely also by your JDBC drivers. Now that the function doesn't act like it's supposed to, you might be stuck in some kind of retry loop. You can try running a tool like `strace` on your program that shows actual system calls and see if the real `connect` system call is still invoked.
