### ISSUE TITLE
Is it possible to extract JITed code and execute separately?

### ISSUE THREAD

**Issue by cstehreem** [oracle/graal#1302]
Hi,

Is it possible to extract JITed code and keep a copy of it somewhere on the disk for later use? I have been trying to extract code from OpenJDK-8 right after it is compiled, however I have faced issue a lot of hard coded addresses in instructions. Is there any point during JIT compilation using Graal where addresses have not been fixed yet and there are offsets instead?

**Comment by dougxc** [comment]
The code generated by Graal when used as a JIT by HotSpot is very specific to profiling and configuration of the runtime. When used as in AOT mode (either by `jaotc` or `native-image`), the code does not hard code such details. Before going further, maybe you can describe what it is you are trying to achieve.

**Comment by cstehreem** [comment]
I want to extract and cache the compiled hot methods and be able to execute those methods, ideally even after JVM has stopped running. Or on a different machine. I understand I can create native images, however, they won't have the profiling information right? I want to extract code according to the profiling information for methods.

While searching for it I came across [this JEP](http://hg.openjdk.java.net/jep/jeps/rev/a16daa94ba0f), which is very similar to what I am trying to achieve.

**Comment by dougxc** [comment]
We will soon be adding a feature to GraalVM that allows native images to be created with profiling information. I suggest waiting for that as trying to re-use the compiled code from one runtime in another is more complex than just saving the code. (/cc @tkrodriguez )

**Comment by dougxc** [comment]
Actually, PGO is available today in GraalVM. Please see the `--pgo-instrument` and `--pgo` options documented at https://www.graalvm.org/docs/reference-manual/aot-compilation.

**Comment by cstehreem** [comment]
Thank you for this information. I will check out pgo. Any chance of this feature making into CE?

**Comment by vjovanov** [comment]
There is a possibility for that but not in the immediate future (next 6 months). We will announce once/if that happens. Stating the desire over public channels would support the open-sourcing of PGO.
