### ISSUE TITLE
Nahsorn script engine reports nulls in lists for extensions, mime types, and names

### ISSUE THREAD

**Issue by paul-bjorkstrand** [oracle/graal#1310]
When listing out script engines in Graal, the Nashorn engine reports lists containing `null`s for these three properties: extensions, mime types, names. This is having a negative effect on applications that attempt to utilize all available script engines in the given JVM, by using these properties to list the available script engines.

It would be expected that the lists returned for these three properties would simply be smaller in Graal, since GraalJS is the replacement for Nashorn in GraalVM.

I am unsure if this is caused by Graal or GraalJS, so if this should be over at GraalJS, let me know and I will open it there.

Below is some sample code to reproduce the actual output, with the expected output at the bottom.

Code:
```java
import java.util.List;

import javax.script.ScriptEngine;
import javax.script.ScriptEngineFactory;
import javax.script.ScriptEngineManager;

public class OutputScriptEngines {
    public static void main(String[] args) {
        ScriptEngineManager manager = new ScriptEngineManager();
        List<ScriptEngineFactory> factories = manager.getEngineFactories();
        for (ScriptEngineFactory factory : factories) {
            System.out.println(factory.getEngineName());
            System.out.print("\t");
            System.out.println(factory.getEngineVersion());
            System.out.print("\t");
            System.out.println(factory.getLanguageName());
            System.out.print("\t");
            System.out.println(factory.getLanguageVersion());
            System.out.print("\t");
            System.out.println(factory.getExtensions());
            System.out.print("\t");
            System.out.println(factory.getMimeTypes());
            System.out.print("\t");
            System.out.println(factory.getNames());
        }
    }
}
```
Output (actual): 
```
Oracle Nashorn
    1.8.0_212
    ECMAScript
    ECMA - 262 Edition 5.1
    [null]
    [null, null, null, null]
    [nashorn, Nashorn, null, null, null, null, null, null]
Graal.js
    null
    ECMAScript
    ECMA - 262 Edition 9
    [js]
    [application/javascript, application/ecmascript, text/javascript, text/ecmascript]
    [Graal.js, graal.js, Graal-js, graal-js, Graal.JS, Graal-JS, GraalJS, GraalJSPolyglot, js, JS, JavaScript, javascript, ECMAScript, ecmascript]
```

Output (expected): 
```
Oracle Nashorn
    1.8.0_212
    ECMAScript
    ECMA - 262 Edition 5.1
    []
    []
    [nashorn, Nashorn]
Graal.js
    null
    ECMAScript
    ECMA - 262 Edition 9
    [js]
    [application/javascript, application/ecmascript, text/javascript, text/ecmascript]
    [Graal.js, graal.js, Graal-js, graal-js, Graal.JS, Graal-JS, GraalJS, GraalJSPolyglot, js, JS, JavaScript, javascript, ECMAScript, ecmascript]
```

**Comment by paul-bjorkstrand** [comment]
I dug into this a little further, and it appears that it is indeed caused by the way GraalJS takes over as the JS engine from Nashorn. [In GraalJSEngineFactory#clearEngineFactory](https://github.com/graalvm/graaljs/blob/master/graal-js/src/com.oracle.truffle.js.scriptengine/src/com/oracle/truffle/js/scriptengine/GraalJSEngineFactory.java#L208), the Nashorn engine's lists backing arrays are just cleared. Because everything from the [NashornScriptEngineFactory](https://github.com/openjdk/jdk/blob/master/src/jdk.scripting.nashorn/share/classes/jdk/nashorn/api/scripting/NashornScriptEngineFactory.java#L260) is final (as are all of the fields in the lists deep in the unmodifiable list), this is probably the only option at the moment.

Unless the Graal team is willing to create an custom build of the JDK, which omits Nashorn, I don't think this will be properly resolved, until both Nashorn is removed from the JDK (in some future version) and Graal is based upon that version.

**Comment by wirthi** [comment]
Hi @paul-bjorkstrand 

thanks for your question. 

> It would be expected that the lists returned for these three properties would simply be smaller in Graal, since GraalJS is the replacement for Nashorn in GraalVM.

The current decision for our JDK8 based builds is: Nashorn is part of JDK8 so we cannot just remove it (and still provide for instance the `jjs` command). But, as you state, for any requests (e.g. via the ScriptEngine) we want Graal.js to behave like a drop-in and replace Nashorn. What you describe was the best way we found to accommodate both requirements.

Do you have any suggestions on how we could improve on that?

With JDK11+, you can run Graal.js based on dropping in the relevant JARs, see https://medium.com/graalvm/graalvms-javascript-engine-on-jdk11-with-high-performance-3e79f968a819 In such a setup, you can provide your own JDK (that omits Nashorn) - it's not necessarily us having to provide such a build.

Best,
Christian

**Comment by paul-bjorkstrand** [comment]
@wirthi, I do have one suggestion that is somewhat better than nulling Nashorn's values. Since you are modifying the values, maybe prepend any that do not already contain `nashorn` with `nashorn`. That way, when an application lists the available script engines, it doesn't see unexpected `null`s everywhere.
Example:
```
Oracle Nashorn
    1.8.0_212
    Nashorn ECMAScript
    Nashorn ECMA - 262 Edition 5.1
    [nashorn-js]
    [nashorn-application/javascript, nashorn-application/ecmascript, nashorn-text/javascript, nashorn-text/ecmascript]
    [nashorn, Nashorn, nashorn-js, Nashorn-JS, Nashorn-JavaScript, nashorn-javascript, Nashorn-ECMAScript, nashorn-ecmascript]
```

In the case when GraalJS is taking over for Nashorn (aka when `RegisterAsNashornScriptEngineFactory` is `true`), then use some other sentinal-value to replace/prepend the existing ones.
Example:
```
Oracle Nashorn
    1.8.0_212
    Replaced ECMAScript
    Replaced ECMA - 262 Edition 5.1
    [replaced-js]
    [replaced-application/javascript, replaced-application/ecmascript, replaced-text/javascript, replaced-text/ecmascript]
    [replaced, Replaced, replaced-js, Replaced-JS, Replaced-JavaScript, replaced-javascript, Replaced-ECMAScript, replaced-ecmascript]
```

If it makes more sense (when `RegisterAsNashornScriptEngineFactory` is `true`), all of the values for Nashorn could be the same text (e.g. `replaced`) instead of prepending, which would simplify the implementation.

I do understand that this is a tricky part of Graal JS, since it is trying to take over from Nashorn, and Nashorn's values are hard coded. Based on my research, here are the options I see to resolve this:

1. Change nothing in the code. Add a note to GraalVM and GraalJS documentation, describing this issue and instructing application creators to check for nulls in the lists from `getExtensions()`, `getMimeTypes()`, and `getNames()`.
2. Change the code to do what is suggested above (or similar) to ensure that there are no nulls in the lists from `getExtensions()`, `getMimeTypes()`, and `getNames()`.
3. Use instrumentation to modify the field values before they are used.

I think that, at minimum, the warning should be added, for Option 1 above.

Option 2 makes it null-free, and would be a fairly straight forward change.

For Option 3, I will admit, I know very little about creating Java instrumentation agents. If this is even possible, I do know that it would require additional command-line arguments to load the agent at run time, which makes it a small barrier for many developers. If Option 3 were implemented, I think that Option 2 would be needed as a fallback.

If there were a vote, I would vote for Option 3, with Option 2 being the a close second.

**Comment by wirthi** [comment]
Closing this, Nashorn has been removed and is not available any longer in JDK17, should be less of a problem there. If still relevant, please create a new ticket at https://www.github.com/oracle/graaljs
