### ISSUE TITLE
[native-image] wrong environment value(s)

### ISSUE THREAD

**Issue by mbbee** [oracle/graal#1312]
System.getenv("JAVA_HOME") retrieves value from build time not actual value.

This seems to be for all System.getenv() entries ...

OS: Windows
Tool: native-image-maven-plugin  19.0.2

**Comment by peter-hofer** [comment]
This affects `ProcessBuilder` as well (#1185). On Linux and OS X, we substitute `java.lang.ProcessEnvironment` to avoid this. This substitution seems to be missing on Windows.

**Comment by olpaw** [comment]
I will look into that.

**Comment by olpaw** [comment]
Fixed on master ffbf4a654047b6888e3271ff479be80c75646767
