### ISSUE TITLE
Value objects should have a reference to the parent polyglot Context

### ISSUE THREAD

**Issue by pmlopes** [oracle/graal#1324]
This is an improvement request. Imagine the following scenario:

1. Context (1) is a `js` context and creates the object `{k:1}`
2. This object is passed to a Java API where it is received as a `PolyglotMap` or `Value`
3. In the java code, the map is passed to a different thread than the context (1)
4. Any call on this object will cause `IllegalStateException` due to the thread change

The solution to this is to perform any operation on the object on the same thread as context (1). This is somehow possible and trivial if there's just 1 context, however if the application uses more than 1, it is not possible to determine the parent context for the `PolyglotMap`/`Value` object.

I would like to request that the `Value` object could have a extra getter to return the parent `Context`, therefore, as a developer I could make sure that all operations would happen on the right context if any.

An example for this API:

```java
public void myAPI(Value polyglotValue) {
  Context ctx polyglotValue.getContext();
  // maybe there are cases where we can't determine the context? context closed?
  if (ctx != null) {
    // As a user I'd implement the runOnContextThread method to track the contexts
    // and their home thread
    runOnContextThread(ctx, () -> {
      polyglotValue.getMember("someMember");
      ...
```

**Comment by pmlopes** [comment]
For more context see discussion: https://gitter.im/graalvm/graaljs?at=5ce667bdad024978c6146985

**Comment by chumer** [comment]
Thank you. Excellent feature suggestion. I will return the same context instance that is also returned by Context.getCurrent(). Which means that it will have reduced functionality (e.g it cannot be closed).

**Comment by pmlopes** [comment]
That is perfect I think. We will be able to relate this object to a specific thread, and then ask that thread to run some code with that context.

**Comment by pmlopes** [comment]
Hi, any updates on this? Is there anything I can do to help this get implemented?

**Comment by chumer** [comment]
Adressed by https://github.com/oracle/graal/commit/93539359b3431e40feba6ec50b7592b4bafb2822
