### ISSUE TITLE
Open classes that serialize with JVM do not with native-image

### ISSUE THREAD

**Issue by mcred** [oracle/graal#1333]
Below is a simplified sample of nested open classes that will serialize when run with JVM, but will not serialize when running the compiled native binary. Does anyone have any insight as to why this is? I used maven to create fat JAR with all dependencies. 

```kotlin
package hello

import org.json.JSONObject

open class Second (
    open val name: String
)

open class First(
    open val name: String,
    open val second: Second
)

object Hello {
    @JvmStatic
    fun main(args: Array<String>) {
        val second = Second("nested object")
        val first = First("top level", second)

        println(JSONObject(first))
    }
}
```

```bash
$ java -jar ./target/hello-world-1.0-SNAPSHOT-jar-with-dependencies.jar 
{"name":"top level","second":{"name":"nested object"}}
```

```bash
$ native-image -cp ./target/hello-world-1.0-SNAPSHOT-jar-with-dependencies.jar\
-H:Name=hello\
-H:Class=hello.Hello\
-H:+ReportUnsupportedElementsAtRuntime\
--allow-incomplete-classpath
$ ./hello 
{}
```

**Comment by mcred** [comment]
Forgot to add a little more info. I'm using the graalvm java to run both of the commands above and it's the latest version. 

```bash
$ which java
/Users/me/graalvm-ce-19.0.0/Contents/Home/bin/java
```

**Comment by cstancu** [comment]
Does `org.json.JSONObject` uses reflection for serialization? Then you need to register the classes and their elements for reflection. You can use the [`native-image-agent`](https://github.com/oracle/graal/blob/master/substratevm/CONFIGURE.md#assisted-configuration-of-native-image-builds) for automatically detecting reflectively accessed elements.

**Comment by mcred** [comment]
Looks like this is the issue. For other people who run into this issue, this is how I solved it:

```bash
$ java -agentlib:native-image-agent=config-output-dir=./ -jar ./target/hello-world-1.0-SNAPSHOT-jar-with-dependencies.jar 
{"name":"top level","second":{"name":"nested object"}}
```

The added `-agentlib:native-image-agent=config-output-dir=./` created a few files in the working directory, including `reflect-config.json`. `native-image` then can have the added compile parameter:
`-H:ReflectionConfigurationFiles=reflect-config.json` and then the native binary works.

```bash
$ native-image -cp ./target/hello-world-1.0-SNAPSHOT-jar-with-dependencies.jar\
     -H:Name=hello\
     -H:Class=hello.Hello\
     -H:+ReportUnsupportedElementsAtRuntime\
     -H:ReflectionConfigurationFiles=reflect-config.json\
     --allow-incomplete-classpath
$ ./hello                                                                      
{"name":"top level","second":{"name":"nested object"}}
```
