### ISSUE TITLE
Abort on startup with failure to load shared library

### ISSUE THREAD

**Issue by sstewartgallus** [oracle/graal#1340]
Binaries from "GraalVM Community Edition 19.0.0" error out on startup:

```
Error occurred during initialization of VM
Unable to load JVMCI shared library: libcrypt.so.1: cannot open shared object file: No such file or directory
``` 

The problem goes away if I add the option "-XX:-UseJVMCINativeLibrary" to the command line.

The exact system I am running under is Fedora Silverblue

```
● ostree://fedora-workstation:fedora/30/x86_64/silverblue
                   Version: 30.20190525.0 (2019-05-25T00:38:21Z)
                BaseCommit: 1edbf923e410ffc6d137d30dd052b1ac7e86f2721794884ed61770c1432531f6
              GPGSignature: Valid signature by F1D8EC98F241AAF20DF69420EF3C111FCFC659B9
           LayeredPackages: SDL SDL_image SDL_ttf a2jmidid cheese chromedriver chromium clang cmake duplicity emacs-php-mode gcc gimp gnome-shell-extension-pomodoro gstreamer-plugins-good
                            hamster-time-tracker jack-audio-connection-kit-dbus java-11-openjdk java-11-openjdk-devel kernel-tools krdc libGLU libreoffice libvirt-daemon-config-network maven
                            moby-engine npm perf powertop python3-selenium qjackctl racket sshfs tlp tlp-rdw wireshark zynaddsubfx
```

**Comment by dougxc** [comment]
Hi @sstewartgallus the OpenJDK Linux builds we based GraalVM CE on can have issues in terms "expecting" certain libraries to be installed. It seems as though `libcrypt.so` is installed by default on Fedora 28. At least I see `/usr/lib64/libcrypt.so`. I am not familiar with Fedora Silverbluw but maybe it's a cut down distro that doesn't have all the libraries OpenJDK expects to see?

**Comment by happylynx** [comment]
Hi @sstewartgallus I'm using Fedora 30 Workstation and installation of package `libxcrypt-compat` solved the problem for me.

Following command helped me to find out the correct package:
```
$ dnf whatprovides '*/libcrypt.so.1'
Last metadata expiration check: 0:05:50 ago on Sat 01 Jun 2019 01:03:38 AM CEST.
libxcrypt-compat-4.4.6-1.fc30.x86_64 : Compatibility library providing legacy API functions
Repo        : @System
Matched from:
Filename    : /lib64/libcrypt.so.1

libxcrypt-compat-4.4.6-1.fc30.i686 : Compatibility library providing legacy API functions
Repo        : updates
Matched from:
Filename    : /lib/libcrypt.so.1

...
```
CentOS 7 or compatible OSs (most likely used to build OpenJDK) has `libcrypt.so.1` preinstalled as part of *glibc* package.

**Comment by sstewartgallus** [comment]
Hi @happylynx Thanks a lot for the help.

I'm still confused by why the native image libraries link to libcrypt in the first place though?

@dougxc seems to suggest this an issue in the older OpenJDK they use which might be resolved with an upgrade to a future version but I couldn't find in the sources a place where OpenJDK uses libcrypt in the first place. It kind of sounds like they need something like ld's --as-needed flag but I can't find documentation on how truffle works with shared libraries.

**Comment by dougxc** [comment]
@olpaw I'm also curious as to why `libjvmcicompiler.so` links against `libcrypt.so.1`. How do I work this out?

**Comment by olpaw** [comment]
> How do I work this out?

@dougxc libcrypt is part of the glibc shared objects. To see which part of SubstrateVM makes use of it just search for it: https://github.com/oracle/graal/search?q=%40CLibrary%28%22crypt%22%29&unscoped_q=%40CLibrary%28%22crypt%22%29

**Comment by olpaw** [comment]
It looks like we are not using `com.oracle.svm.core.posix.headers.linux.LinuxUnistd.Target_com_oracle_svm_core_posix_headers_Unistd#crypt` anywhere anymore. So we should get rid of it and also remove the link dependency to libcrypt.so.

**Comment by olpaw** [comment]
Fixed on master. Linux native-images will no more depend on `libcrypt.so`.

**Comment by dmlloyd** [comment]
Great!  Any chance of a 19.0.x backport?

**Comment by gsmet** [comment]
Yeah, it would be really helpful, we have a lot of reports for Quarkus for this issue.

**Comment by dougxc** [comment]
@olpaw which release will this show up in?
