### ISSUE TITLE
JVM Exception: #error {:cause Algorithm HmacSHA1 not available}

### ISSUE THREAD

**Issue by ashwinbhaskar** [oracle/graal#1341]
When I try to execute the native image, I get the below exception. But this works when I execute it on the normal JVM. For more details about the issue check out [this](https://github.com/ashwinbhaskar/Google-Authenticator/issues/2)

```
JVM Exception: #error {
 :cause Algorithm HmacSHA1 not available
 :via
 [{:type java.security.NoSuchAlgorithmException
   :message Algorithm HmacSHA1 not available
   :at [javax.crypto.Mac getInstance Mac.java 181]}]
 :trace
 [[javax.crypto.Mac getInstance Mac.java 181]
  [google_authenticator.core$hmac invokeStatic core.clj 39]
  [google_authenticator.core$hmac invoke core.clj 35]
  [google_authenticator.core$get_hmac invokeStatic core.clj 68]
  [google_authenticator.core$get_hmac invoke core.clj 68]
  [google_authenticator.core$get_otp invokeStatic core.clj 82]
  [google_authenticator.core$get_otp invoke core.clj 81]
  [google_authenticator.core$print_otp invokeStatic core.clj 94]
  [google_authenticator.core$print_otp invoke core.clj 93]
  [cli_matic.core$invoke_subcmd invokeStatic core.clj 797]
  [cli_matic.core$invoke_subcmd invoke core.clj 785]
  [cli_matic.core$run_cmd_STAR_ invokeStatic core.clj 831]
  [cli_matic.core$run_cmd_STAR_ invoke core.clj 817]
  [cli_matic.core$run_cmd invokeStatic core.clj 841]
  [cli_matic.core$run_cmd invoke core.clj 833]
  [google_authenticator.core$_main invokeStatic core.clj 122]
  [google_authenticator.core$_main doInvoke core.clj 117]
  [clojure.lang.RestFn applyTo RestFn.java 137]
  [google_authenticator.core main nil -1]]}
```

**Comment by cstancu** [comment]
@ashwinbhaskar do you enable [JCA Security Services](https://github.com/oracle/graal/blob/master/substratevm/JCA-SECURITY-SERVICES.md)?

**Comment by ashwinbhaskar** [comment]
@cstancu I had not enabled that. I tried it again by enabling it. It gives the below error now.

```
WARNING: The sunec native library, required by the SunEC provider, could not be loaded. This library is usually shipped as part of the JDK and can be found under <JAVA_HOME>/jre/lib/<platform>/libsunec.so. It is loaded at run time via System.loadLibrary("sunec"), the first time services from SunEC are accessed. To use this provider's services the java.library.path system property needs to be set accordingly to point to a location that contains libsunec.so. Note that if java.library.path is not set it defaults to the current working directory.
** ERROR: **
JVM Exception: #error {
 :cause No matching field found: toString for class java.lang.Integer
 :via
 [{:type java.lang.IllegalArgumentException
   :message No matching field found: toString for class java.lang.Integer
   :at [clojure.lang.Reflector getInstanceField Reflector.java 397]}]
 :trace
 [[clojure.lang.Reflector getInstanceField Reflector.java 397]
  [clojure.lang.Reflector invokeNoArgInstanceMember Reflector.java 440]
  [google_authenticator.core$paddotp_if_necessary invokeStatic core.clj 63]
  [google_authenticator.core$paddotp_if_necessary invoke core.clj 60]
  [google_authenticator.core$get_otp invokeStatic core.clj 84]
  [google_authenticator.core$get_otp invoke core.clj 81]
  [google_authenticator.core$print_otp invokeStatic core.clj 94]
  [google_authenticator.core$print_otp invoke core.clj 93]
  [cli_matic.core$invoke_subcmd invokeStatic core.clj 797]
  [cli_matic.core$invoke_subcmd invoke core.clj 785]
  [cli_matic.core$run_cmd_STAR_ invokeStatic core.clj 831]
  [cli_matic.core$run_cmd_STAR_ invoke core.clj 817]
  [cli_matic.core$run_cmd invokeStatic core.clj 841]
  [cli_matic.core$run_cmd invoke core.clj 833]
  [google_authenticator.core$_main invokeStatic core.clj 122]
  [google_authenticator.core$_main doInvoke core.clj 117]
  [clojure.lang.RestFn applyTo RestFn.java 137]
  [google_authenticator.core main nil -1]]}
```

**Comment by elliots** [comment]
Copy libsunec.so into the current directory and it should be start (its at the location it says in the error message)

**Comment by cstancu** [comment]
@ashwinbhaskar you may also need to configure your app for reflection. Uses of reflection need to be configured. You can read more about reflection [here](https://github.com/oracle/graal/blob/master/substratevm/REFLECTION.md). We also provide an [agent](https://github.com/oracle/graal/blob/master/substratevm/CONFIGURE.md) that you can use to track reflective accesses and generate reflection configuration automatically.

**Comment by ashwinbhaskar** [comment]
@cstancu @elliots sorry for late reply..But I am not able to find `libsunec.so`

**Comment by cstancu** [comment]
On my machine it is under `$JAVA_HOME/jre/lib/amd64/libsunec.so`. My JDK version is `openjdk1.8.0_222-jvmci-19.2-b02`. However, the message about the `sunec` library missing is just an warning and it is likely not the cause of your latest error. The `HmacSHA1` is enabled by the use of `-H:+EnableAllSecurityServices`. The registration of the security services can be traced with `-H:+TraceSecurityServices` and it should show you that `HmacSHA1` is provided by `SunJCE` and not by `SunEC`: 

```
`Service registered: Provider = SunJCE , Type = Mac , Algorithm = HmacSHA1 , Class = com.sun.crypto.provider.HmacSHA1`
```

The error

```
[{:type java.lang.IllegalArgumentException
   :message No matching field found: toString for class java.lang.Integer
   :at [clojure.lang.Reflector getInstanceField Reflector.java 397]}]`
```
is weird because `java.lang.Integer` has no field `toString`. Is it possible that clojure injects it? As I mentioned above, you probably need to register this element (and potentially others) for reflection. You should give the tracing agent a try.

**Comment by ashwinbhaskar** [comment]
@cstancu okay, will do that. Using the agent doesn't seem to straight forward at first glance (or is it?). I will try to get the agent working.

**Comment by peter-hofer** [comment]
@ashwinbhaskar , sorry for not responding. The agent is included with GraalVM, so if you are using a GraalVM `java` binary, `-agentlib:native-image-agent` should work out of the box. See [CONFIGURE.md](https://github.com/oracle/graal/blob/master/substratevm/CONFIGURE.md) for more details.
