### ISSUE TITLE
Big regression seen in SPECjvm crypto.rsa between RC15 and RC16 on X86

### ISSUE THREAD

**Issue by opportun1st** [oracle/graal#1344]
I saw a ~25% regression in SPECjvm crypto.rsa between RC15 and RC16 on X86. Here are the testing results (ops/m):

>     RC15	3715.95	3621.61	3607.93
>     RC16	2689.36	2604.20	2654.19

My testing was done on a Linux machine equipped with an Intel Xeon Platinum 8163 CPU (Skylake). There was no JVM option explicitly specified other than "-Xms16G -Xmx16G".

**Comment by dougxc** [comment]
Hi @opportun1st can you please provide the output of `java -version` so that we know exactly what config is being used (e.g. CE or EE). Interestingly, we don't see this regression on our internal benchmarking. Do you also see the regression with GraalVM 19.0?

**Comment by opportun1st** [comment]
@dougxc Here is the info from `java -version`:

RC15

> openjdk version "1.8.0_202"
> OpenJDK Runtime Environment (build 1.8.0_202-20190206132807.buildslave.jdk8u-src-tar--b08)
> OpenJDK GraalVM CE 1.0.0-rc15 (build 25.202-b08-jvmci-0.58, mixed mode)

RC16

> openjdk version "1.8.0_202"
> OpenJDK Runtime Environment (build 1.8.0_202-20190206132807.buildslave.jdk8u-src-tar--b08)
> OpenJDK GraalVM CE 1.0.0-rc16 (build 25.202-b08-jvmci-0.59, mixed mode)

I saw the regression with 19.0 as well. Basically 19.0 is on a par with RC16.

I'll run the testing on another machine to double check.

**Comment by opportun1st** [comment]
I've tried on 2 other machines. I don't see a regression but a big improvement from RC15 to RC16. There might be something wrong with my original testing machine.

Anyway, I'm closing this issue. Sorry for the false alarm.
