### ISSUE TITLE
Using official docker container for multi-platform builds

### ISSUE THREAD

**Issue by mcred** [oracle/graal#1347]
I've started using the official docker container `oracle/graalvm-ce:19.0.0` and I can no longer build for OSX. Is there documentation or can anyone help me figure out how to use the docker container to build for multiple platforms? I'd like to be able to automate builds from jenkins to multiple target platforms. Has anyone done this?

The following command build a linux binary and if I use the command minus the docker container, it builds for OSX.
```
docker run -v ${PWD}:/cli --workdir /cli oracle/graalvm-ce:19.0.0 native-image -cp ./target/project-$version-jar-with-dependencies.jar\
    -H:Name=project\
    -H:Class=com.project.Cli\
    -H:+ReportUnsupportedElementsAtRuntime\
    -H:ReflectionConfigurationFiles=./reflect-config.json\
    --allow-incomplete-classpath\
    --enable-url-protocols=http
```

**Comment by mcred** [comment]
I've been following the docs:
https://www.graalvm.org/docs/getting-started/#docker-containers
https://www.graalvm.org/docs/reference-manual/aot-compilation/

**Comment by elliots** [comment]
I don't believe it is possible to build for mac from linux. I'm building for mac using circle-ci mac executor. 

This is how i'm setting up the mac vm, installing graal and maven.

```bash
set -e
cd "${0%/*}"
HOMEBREW_NO_AUTO_UPDATE=1 brew install maven
curl -fLo graal.tar.gz https://glare.now.sh/oracle/graal/graalvm-ce-darwin
tar -zxf graal.tar.gz
export GRAAL_HOME=`pwd`/graalvm-ce-19.0.0
export JAVA_HOME=$GRAAL_HOME/Contents/Home
export PATH=$JAVA_HOME/bin:$PATH
gu install native-image
```

**Comment by ansalond** [comment]
Hi @mcred, thanks for your interest in GraalVM.

Unfortunately, as mentioned by @elliots, Native Image does not yet support cross-compilation (see https://github.com/oracle/graal/issues/407).
