### ISSUE TITLE
native image maven plugin has problems with non-jar projects

### ISSUE THREAD

**Issue by eginez** [oracle/graal#1351]
Hey all

I have been having problems generating a native-image with the maven plugin.
The project I am using the plugin with a bit unconventional: The project itself is maven plugin, however it exposes a java main-class allowing for command line access to the logic of the plugin.

I noticed while building the native image of my project, `native-image-maven-plugin` could not find the main-class.
I think the culprit is  line: https://github.com/oracle/graal/blob/c53864afa586192fe12ac0ac07430c936f3fc7cc/substratevm/src/native-image-maven-plugin/src/main/java/com/oracle/substratevm/NativeImageMojo.java#L264. The assumption that all artifacts as jar artifacts is probably not correct as you can have non-jar projects whose classes need to be included in the classpath

**Comment by eginez** [comment]
Luckily the work around to simply add the classes files of the build project like so
```
<buildArgs>
         -cp ${project.build.directory}/classes
</buildArgs>
```

**Comment by olpaw** [comment]
@eginez that's correct. `native-image-maven-plugin` automatic classpath detection currently relies on having all artifacts available as jar-files. The solution (workaround) you propose for your specific usecase is fine. If might be nice to add a a mojo parameter that allows switching to a directory-based classpath entry for the main artifact (`${project.build.directory}/classes`) ... maybe even with automatic detection if a directory-based cp entry is needed (if the main artifacts jar-file is missing).

Contributions are welcome :-)
