### ISSUE TITLE
Cannot create native image when has a code that invoke default method using reflection

### ISSUE THREAD

**Issue by kazuki43zoo** [oracle/graal#1353]
I'am the MyBatis commiter and I consider supporting GraalVM. But the [MyBatis](https://github.com/mybatis/mybatis-3) has [code that invoke the default method using reflection feature](https://github.com/mybatis/mybatis-3/blob/78070c9e387d4019ed90d1514dd269535003d02f/src/main/java/org/apache/ibatis/binding/MapperProxy.java#L65-L78) and it become build error. A small reproduce project is [here](https://github.com/kazuki43zoo/graal-reflection-demo).

Can I resolve this problem? or Is this behavior is limitation of GraalVM?

**Comment by cstancu** [comment]
Uses of reflection need to be configured. You can read more about reflection [here](https://github.com/oracle/graal/blob/master/substratevm/REFLECTION.md). We also provide an [agent](https://github.com/oracle/graal/blob/master/substratevm/CONFIGURE.md) that you can use to track reflective accesses and generate reflection configuration automatically.

**Comment by kazuki43zoo** [comment]
@cstancu Thanks for your quick answer!! I will read the documentation and try it. Thanks again!

**Comment by cstancu** [comment]
@kazuki43zoo I will close this issue. Please open a new issue if you have specific questions.
