### ISSUE TITLE
Which optimizations in the PLDI paper of Renaissance Suite are available in Graal CE?

### ISSUE THREAD

**Issue by opportun1st** [oracle/graal#1354]
There are 7 optimizations mentioned in the paper: 1) Escape Analysis with Atomic Operations; 2) Loop-Wide Lock Coarsening; 3) Atomic-Operation Coalescing; 4) Method-Handle Simplification; 5) Speculative Guard Motion; 6) Loop Vectorization; and 7) Dominance-Based Duplication Simulation.

I know that 6) Loop Vectorization is not available in CE. I'm wondering how about the others? Are there any options to easily turn on/off these optimizations?

Many thanks.

**Comment by thomaswue** [comment]
The optimization phases applied and also associated flags to turn them on/off can be found in the LowTier, HighTier, MidTier classes in the org.graalvm.compiler.core.phases package. Note that those flags may change between versions.
