### ISSUE TITLE
Master Graal code does not compile in IDE (intellij IDEA)

### ISSUE THREAD

**Issue by yandooo** [oracle/graal#1357]
Env details:
- MacOS (Windows reproducible)
- OpenJDK 12/11/10/9, JDK 1.8 with JVMCI support
- IntelliJ IDEA 2019.1.2

Following IDE configuration guide for Intellij IDEA there is no problem importing project into the IDE but it can not be built.

```
Information:java: Errors occurred while compiling module 'org.graalvm.compiler.truffle.runtime.serviceprovider'
Information:javac 12.0.1 was used to compile java sources
Information:Some files were changed during the build. Additional compilation may be required.
Information:2019-06-04 16:15 - Build completed with 1 error and 1 warning in 12 s 320 ms
Error:java: error: option --add-modules not allowed with target 8
Warning:Output path 
.../mx/mxbuild/java/com.oracle.mxtool.jmh_1_21/bin/../src_gen intersects with a source root. Only files that were created by build will be cleaned.
```

it looks like module misconfig `Error:java: error: option --add-modules not allowed with target 8`. Any idea how to workaround it?

**Comment by gilles-duboscq** [comment]
@steve-s, do your recent changes resolve this?

**Comment by steve-s** [comment]
I haven't tested building the compiler mx suite, but GraalPy + build time dependencies including Truffle build fine from IDE

**Comment by gilles-duboscq** [comment]
Ok, thanks. I'm closing this for now then.
