### ISSUE TITLE
WebAssembly on GraalVM

### ISSUE THREAD

**Issue by linux-china** [oracle/graal#1358]
Add WebAssembly runtime on  GraalVM with CLI and embed support, just like LLVM on GraalVM.   

Cli as following:

```
gwasm polyglot.wasm 
```

Embed as following:
```
 Context polyglot = Context.newBuilder().allowAllAccess(true).build();
        File file = new File("polyglot.wasm");
        Source source = Source.newBuilder("wasm", file).build();
        Value cpart = polyglot.eval(source);
        cpart.execute();  
```

Now no Java Runtime for WebAssembly.  https://github.com/appcypher/awesome-wasm-runtimes 

Now lots of guys did the work to make WebAssembly run from web and with huge future for FaaS, Serverless and WASM MicroVM.  If GraalVM has this feature, and Java developers can develop a real Polyglot runtime platform to accept WebAssembly module from Rust, TypeScript etc.   Please consider WebIDL and WASI support. 

Happy to see TruffleWASM  :)

**Comment by renatoathaydes** [comment]
FYI I wrote a [blog post](https://renato.athaydes.com/posts/running-wasm-on-the-jvm.html) about my experience trying to run WASM on the JVM, if anyone is interested (yes, it's possible now, but far from "complete")!.

Basically, you can use [asmble](https://github.com/cretz/asmble) to create class files from wasm and wat files... and I wrote a [Gradle plugin](https://github.com/renatoathaydes/wasm-on-jvm) that uses asmble to make using WASM in a Gradle project as easy as using any JVM language.

Get in touch if that would be of interest to you.

**Comment by KOLANICH** [comment]
I wonder if it can be possible to translate wasm into llvm and run thet llvm bitcode upon graal.

**Comment by neomatrix369** [comment]
> I wonder if it can be possible to translate wasm into llvm and run that llvm bitcode upon graal.

Check out the post referred to by @renatoathaydes above.

**Comment by KOLANICH** [comment]
I have already read it.

**Comment by renatoathaydes** [comment]
The wabt toolkit includes a `wasm2c` tool (i.e. compiles WASM to C). You can use that, then compile C to LLVM with clang, and you're done.

**Comment by KOLANICH** [comment]
There are converters that convert wasm to llvm bitcode directly.

**Comment by eliasvasylenko** [comment]
Looks like this is now being worked on here https://github.com/oracle/graal/tree/master/wasm

**Comment by thomaswue** [comment]
Tweet on the announcement about the effort is now available here: https://twitter.com/graalvm/status/1201544880364937216?s=20
Medium post: https://medium.com/graalvm/announcing-graalwasm-a-webassembly-engine-in-graalvm-25cd0400a7f2

I think the issue can be closed for now :). For follow-up suggestions and bug reports feel encouraged to open separate issues.

**Comment by renatoathaydes** [comment]
Great @thomaswue ! It's funny we met in San Francisco at a cafe, hope you remember me... now here  :) will play with GraalVM's WASM as soon as I can!!
