### ISSUE TITLE
Failed to install native-image on EE 19.0.1

### ISSUE THREAD

**Issue by dainiusjocas** [oracle/graal#1361]
Ubuntu Linux 19.04.

Steps that were taken:
1. Downloaded GraalVM EE 19.0.1 from https://www.oracle.com/technetwork/graalvm/downloads/downloads-5480109.html
2. Extracted archive to `/opt`
3. Logged in with `-U`
4. Tried to install `native-image`
```
$ /opt/graalvm-ee-19.0.1/bin/gu install native-image
Error: Component catalog request failed: No such channel
```

**Comment by MartinBalin** [comment]
native-image for GraalVM EE from OTN has to be downloaded manually from OTN and then installed by command like `./gu install --file ~/Downloads/native-image-installable-svm-svmee-linux-amd64-19.0.1.jar` 
Installation from internet server provided by GraalVM does not work for EE/OTN at this moment. It will work if you have CE version 19.0.0.
