### ISSUE TITLE
Cannot create an instance of com.amazonaws.auth.AWS4Signer

### ISSUE THREAD

**Issue by FieryCod** [oracle/graal#1367]
I'm trying to provide a basic example of SQS integration with my custom native runtime, but I'm stuck on the following error `Cannot create an instance of com.amazonaws.auth.AWS4Signer`.

**Repro:** 
1. Install leiningen & run ` wget https://raw.githubusercontent.com/FieryCod/holy-lambda/master/resources/fnative && chmod +x fnative && sudo mv fnative /usr/local/bin`
2. `git clone git@github.com:FieryCod/holy-lambda.git`
3. `cd examples/sqs-example`
5. `make install-holy-lambda compile native-compile native-sqs-invoke`

**The result is the error message:**
```
{
  "errorType": "java.lang.IllegalStateException",
  "errorMessage": "Cannot create an instance of com.amazonaws.auth.AWS4Signer"
}
```
_Spent almost 4 hours trying to somehow make it work. Would highly appreciate any help and hints._

**Comment by cstancu** [comment]
You may need to register `com.amazonaws.auth.AWS4Signer` for reflection. You can read more about reflection [here](https://github.com/oracle/graal/blob/master/substratevm/REFLECTION.md). Additionally, take a look at the [`native-image-agent`](https://github.com/oracle/graal/blob/master/substratevm/CONFIGURE.md) which can help you detect reflectively accessed elements automatically.

**Comment by FieryCod** [comment]
Thank you @cstancu. I managed it to work!!
