### ISSUE TITLE
[Truffle] Annotation processors

### ISSUE THREAD

**Issue by shishkin** [oracle/graal#1369]
Truffle heavily relies on its API annotations and annotation processors to produce compiled implementation of a language. This leads to the following limitations:

- Annotation processors are not supported in some JVM languages (most notably, Scala) and thus limit the number of languages that can be used to write Truffle languages.
- It's harder to discover which annotation is needed in which context because annotations decouple processor effects, e.g. _magical_ `@ExportMessage` annotations.
- It's harder to predict the result of an annotation after processing because the result needs to be generated by the processor first. Reading the processor's code is not very helpful either, since it operates on the level of printing Java lexemes.

I'm sure annotations bring architectural benefits as well, like freeing up generators to do optimizations upon declarative user-facing annotations in a backwards compatible way, and some that I didn't even think about. Nonetheless I would like to suggest to move user-facing API to a more ubiquitous design with interfaces and default implementations.

As a strawman example, please consider defining a simple type wrapping Java array:

```java
@ExportLibrary(InteropLibrary.class)
public class SLArray implements TruffleObject {

    private final int[] value;

    public SLArray(int[] value) {
        this.value = value;
    }

    @ExportMessage
    static boolean hasArrayElements(SLArray receiver) {
        return true;
    }

    @ExportMessage
    final Object readArrayElement(long index) {
        return value[(int) index];
    }

    @ExportMessage
    final long getArraySize() {
        return value.length;
    }

    @ExportMessage
    final boolean isArrayElementReadable(long index) {
        return 0 <= index && index < getArraySize();
    }
}
```

Instead of magical annotations, `SLArray` could implement an interface `ArrayLibraryExports`:

```java
public class SLArray implements TruffleObject, ArrayLibraryExports {

    private final int[] value;

    public SLArray(int[] value) {
        this.value = value;
    }

    @Override
    static boolean hasArrayElements(SLArray receiver) {
        return true;
    }

    @Override
    final Object readArrayElement(long index) {
        return value[(int) index];
    }

    @Override
    long getArraySize() {
        return value.length;
    }

    @Override
    boolean isArrayElementReadable(long index) {
        return 0 <= index && index < getArraySize();
    }
}
```

Or even extract basic array exports into API itself:

```java
public class SLArray implements TruffleObject, ArrayLibraryExports {

    private final int[] value;

    public SLArray(int[] value) {
        this.value = value;
    }

    static InteropLibrary exports() {
        return new ArrayInteropLibrary<SLArray>(SLArray.class, SLArray::getValue);
    }
}
```

With reduced reliance on annotations, languages could be implemented in for example Scala easier. Type checking over interface implementation would also be easier on the user. The default implementation code would be easily accessible for the user too.

Hope this suggestion make sense.

**Comment by boris-spas** [comment]
The limitations of using interfaces in these cases are explained in the motivating example of the truffle library docs: https://github.com/oracle/graal/blob/master/truffle/docs/TruffleLibraries.md#strategy-2-java-interfaces 

These limitations are, unfortunately, too big to be ignored at the moment.
