### ISSUE TITLE
System.currentTimeMillis() in native-image generated exe returns too small value on Windows

### ISSUE THREAD

**Issue by hiroSzymon** [oracle/graal#1374]
System.currentTimeMillis() and methods which are using it, generate incorrect result on Windows when run in binary generated by native-image.

Initial conditions:
- Windows 10 1803 17134.706,
- Windows Subsystem for Linux
    Distributor ID: Ubuntu
    Description:    Ubuntu 18.04.2 LTS
    Release:        18.04
    Codename:       bionic
    Linux XXXXXXX 4.4.0-17134-Microsoft #706-Microsoft Mon Apr 01 18:13:00 PST 2019
             x86_64 x86_64 x86_64 GNU/Linux   
              
App source:
```java
import java.time.LocalDateTime;

public class Main {
    public static void main(String[] args) {
        System.out.println(LocalDateTime.now());
        System.out.println(System.currentTimeMillis());
    }
}
```

Result:
- On Windows app prints:

> 1970-01-01T04:06:51.156
11211158

- In Linux subsystem, result is correct:

> 2019-06-11T07:11:22.639
1560237082640

**Comment by dougxc** [comment]
@bobvandette would you be able to look into this issue?

**Comment by bobvandette** [comment]
Sure.  There is a problem.   The currentTimeMillis() substitution is incorrect.  It should not be using nanoTime as the basis of time.  JvmFuncs.c is also incorrect.  Assuming we don't call Target_java_lang_System.currentTimeMillis inside SVM, we should remove this substitution and fix JvmFuncs.c to call the getCurrentTimeMillis that exists in this file.

**Comment by bobvandette** [comment]
A fix [GR-16453] has been integrated to resolve this issue.

**Comment by cstancu** [comment]
Fixed by https://github.com/oracle/graal/commit/41aef477f8067f325d0b89bd3b3647f87b5f1b56. Thanks @bobvandette !
