### ISSUE TITLE
No GraalVM CE 19.0.1 available

### ISSUE THREAD

**Issue by rsvoboda** [oracle/graal#1380]
https://www.oracle.com/technetwork/graalvm/downloads/index.html contains 19.0.1 release
https://github.com/oracle/graal/releases is still on 19.0.0

Is there any plan to make GraalVM CE 19.0.z available on https://github.com/oracle/graal/releases ?

**Comment by thomaswue** [comment]
Yes. 19.0.2 for all editions will be there latest in a few days. 19.0.1 was a one-off fix that did not need any changes in CE.

**Comment by rsvoboda** [comment]
Thank you for the update!
