### ISSUE TITLE
[interop] Inconsistent error handling in Polyglot API (e.g. invalid import / eval / ...)

### ISSUE THREAD

**Issue by fniephaus** [oracle/graal#1402]
Apparently, Graal.js' behavior has changed with regard to the Polyglot API in GraalVM 19.0.0. Instead of returning `null`, a `ReferenceError` is thrown when trying to import an undefined identifier from the polyglot bindings. Similarly, evaluating invalid Python code returns `None` while evaluating invalid JavaScript code from Python throws an exception. A polyglot shell session illustrating this is attached at the end.

I'm not sure what the preferred behavior would be in these cases, but it should be consistent. Throwing errors allows users to handle them somehow which I like. At the same time, it might be hard to find the right error to throw and it might not be desirable to introduce a custom polyglot error in each language (but there are some polyglot modules already).
Here's an idea how a custom error could help in Python:

```python
try:
  polyglot.eval(language='js', string=code)
except PolyglotError as e:
  if e.is_syntax_error:
    print('Invalid JavaScript code, please try again...')
  else:
    raise RuntimeError(str(e))
```

<hr>

#### Polyglot Shell Session
```
$ polyglot --shell --jvm
GraalVM MultiLanguage Shell 19.0.0
Copyright (c) 2013-2019, Oracle and/or its affiliates
  JavaScript version 19.0.0
  Python version 3.7.0
js> Polyglot.import('foo')
ReferenceError: foo is not defined
js> python>
python> import polyglot
python> polyglot.import_value('foo')
python> x = polyglot.import_value('foo')
python> x
python> x is None
True
python> js>
js> Polyglot.eval('python', '#$%^')
null
js> python>
python> polyglot.eval(language='js', string='$%^')
NotImplementedError: SyntaxError: $%^:1:2 Expected an operand but found ^
$%^
  ^
```

/cc @chumer

**Comment by boris-spas** [comment]
Tracking internally as Issue GR-20919.

**Comment by chumer** [comment]
Looks like python is not properly throwing an error here? 
Might be already fixed.

**Comment by timfel** [comment]
We throw a TruffleException when there's a SyntaxError. @fniephaus can you check that you get an exception from us when you use Smalltalk to eval invalid Python code?

**Comment by fniephaus** [comment]
GraalPython is throwing an error, but Graal.js is swallowing it which it shouldn't?

**Comment by woess** [comment]
Note that `Polyglot.eval('python', '#$%^')` is actually evaluating valid Python code (`#` starts a comment)! That's why you get `None`. JS actually throws a (JS) Error for invalid code, but not a SyntaxError currently, which we should fix.

**Comment by fniephaus** [comment]
Whoops, my bad...and good catch!
For the sake of completeness, this is what I get with `19.3.0`:
```
js> Polyglot.eval('python', '$%^&#$%^')
Error: SyntaxError: invalid syntax
```

**Comment by woess** [comment]
Should be fixed by https://github.com/graalvm/graaljs/commit/f373329271d76587a118672227b937202c5e03df to be released in GraalVM 20.1.0.

**Comment by fniephaus** [comment]
Thank you, @woess! I will close this when I have confirmed this is now working as expected.

**Comment by fniephaus** [comment]
The following works as expected now (tested against [`20.1.0-dev-20200225_0946`](https://github.com/graalvm/graalvm-ce-dev-builds/releases/tag/20.1.0-dev-20200225_0946)):

```python
try:
  polyglot.eval(language='js', string='#$%^&****&^%$')
except:
  print('Invalid JavaScript code, please try again...')
```
