### ISSUE TITLE
GraalVM rc16 docker image removed from Docker hub

### ISSUE THREAD

**Issue by gsmet** [oracle/graal#1403]
Hi,

As you know, Quarkus is still using rc16 (we are actively working on the GraalVM 19 support but it needs adjustments both in GraalVM and Quarkus).

The rc16 image was removed from Docker hub and it breaks people workflow: we had a user report this morning:
https://hub.docker.com/r/oracle/graalvm-ce/tags

Could you consider adding it back, at least until we have a stable Quarkus version supporting GraalVM 19?

Thanks!

**Comment by emmanuelbernard** [comment]
Generally, what will be your policy regarding image tagging? I don't think people will be able to rely on these images if the tags are not considered immutable.

If you look at this example (mysql) https://hub.docker.com/_/mysql?tab=tags
you can see that they never remove an exact version tag. They do shift their minor and major tags to point to the latest (e.g. latest points to -> 8, 8 to -> 8.0 and 8.0 -> 8.0.16 and 8.0.17 in a near future).
That way people can chose if they are on a sliding version or a fix ste.

**Comment by thomaswue** [comment]
Sorry, that was unintentional - still figuring out how this got triggered. We will put them back asap.

I would suggest that 8.0.latest would point to the latest 8.0. Does that seem reasonable?

**Comment by ezzarghili** [comment]
The tag is now available again.

**Comment by thomaswue** [comment]
We will make sure to not remove tags moving forward. Sorry for the inconvenience.

**Comment by gsmet** [comment]
Thanks for the quick fix!
