### ISSUE TITLE
Invalid classpath entry in MANIFEST.MF

### ISSUE THREAD

**Issue by emmanuelbernard** [oracle/graal#1417]
Hey,

A user of Quarkus found a situation where native-image trips
https://github.com/quarkusio/quarkus/issues/2852
With a reproducer here https://github.com/vietk/QuarkusReproducer
It's seems related to the fact that maven adds to the MANIFEST.MF cp a non jar file

HotSpot is fine with it but native-image fails. Do you see it as a bug or a behavioral difference?

We did workaround it in Quarkus by excluding such references but that's more a maven + native-image disagreement at heart.

**Comment by bobmcwhirter** [comment]
I'm working on a fix for this.

**Comment by olpaw** [comment]
Already fixed on master. See https://github.com/oracle/graal/pull/1418#issuecomment-504995865

**Comment by olpaw** [comment]
Fixed on master by https://github.com/oracle/graal/commit/cd316904503b87a2ff420f138d404fd22fd841ea

**Comment by olpaw** [comment]
> HotSpot is fine with it but native-image fails. Do you see it as a bug or a behavioral difference?

We try to be as close as possible to the behavior of `java -cp`. If you notice further differences in the way java processes its classpath entries please let us know.

**Comment by olpaw** [comment]
The fix will be backported to GraalVM 19.0.X.
