### ISSUE TITLE
Linux: native images are linking against libcrypt.so

### ISSUE THREAD

**Issue by dmlloyd** [oracle/graal#1419]
Not `libcrypto.so`, but `libcrypt.so`.  That's the one that implements the standard POSIX `crypt` function - a function which is seemingly unused within all of GraalVM, as far as I've been able to search it.

I can't figure out how this linkage is occurring.  I did notice that within the GraalVM distribution, the libraries `libnative-image-agent.so`, `libjvmcicompiler.so`, and `libpolyglot.so` all link against `libcrypt.so`.  I don't know *why*.  I'm also a bit skeptical that this is how the library sneaks in.

Anyway it's really undesirable to link against this library because it's causing portability issues between Linux distributions.  If someone could point me in the direction of how it's even occurring, I'll be happy to figure out a fix for it.

**Comment by dougxc** [comment]
https://github.com/oracle/graal/issues/1340#issuecomment-498653502

**Comment by dmlloyd** [comment]
Oh, excellent.  Thanks!
