### ISSUE TITLE
ImportError: No module named 'urlparse'

### ISSUE THREAD

**Issue by abhiroj** [oracle/graal#1429]
I am trying to build `truffle` via the commands `mx clean` and `mx build`. python version is 3.5.4 can someone please help me with the issue?

**Comment by mukel** [comment]
We are currently migrating the build system to Python 3. Core `mx` is already migrated (it's compatible with both Python 2 and 3) but some components in the graal repo have not been migrated yet, please use Python 2 for now.

**Comment by abhiroj** [comment]
ah! I see.
