### ISSUE TITLE
[nfi] NFI crashes if library does not exist

### ISSUE THREAD

**Issue by fniephaus** [oracle/graal#1432]
#### Repro
Execute something like this (with permissions for internal languages):
```
Polyglot.eval('nfi', 'load "NonExistingModule.dylib"')
```

#### Error

VM exists with a `dlopen(NonExistingModule.dylib, 2): image not found` error.

#### Expected Result

The VM does not quit, NFI returns some interop `Null` value instead.

*Tested with GraalVM CE 19.0.0 on macOS.*

**Comment by rschatz** [comment]
I just tested that with JS, and `Polyglot.eval` throws a polyglot exception. You can catch that exception if you want.

I would say that is the expected behavior. If you just return `NULL`, how would you get to the error message?

**Comment by fniephaus** [comment]
It looks like an `UnsatisfiedLinkError` is thrown in case a library is not found, and I was catching `Exception` and not a `Throwable`. Thanks for looking into this anyway!
