### ISSUE TITLE
native-image window 7 64 Date.getTime return value error

### ISSUE THREAD

**Issue by lilili87222** [oracle/graal#1440]
import java.util.Calendar;
import java.util.Date;
import java.util.TimeZone;

public class TestTime {

	public static void main(String[] args) {
		Calendar right=Calendar.getInstance();
		Calendar right2=Calendar.getInstance(TimeZone.getTimeZone("UTC"));

		Date signingDate = new Date();
		Date signingDate2 = new Date();
		signingDate2.setTime(1561615969719l);
		System.out.println(right2.get(Calendar.YEAR)+"   "+right2.get(Calendar.MONTH)+"        "+right2.get(Calendar.DATE));
		System.out.println(signingDate2.getTime()+"   Macho Sign Time: "+signingDate.getTime()+"     Calendar date: "+right.getTime()+"    Calendar time: "+right.getTimeInMillis()+"   "+right2.getTimeInMillis());

	}
}

/////////////////System out result////////////////////////////////////////

1970   0        1
1561615969719   Macho Sign Time: 1786317     Calendar date: Thu Jan 01 08:29:46
CST 1970    Calendar time: 1786317   1786317

**Comment by lilili87222** [comment]
version GraalVM Community Edition 19.0.2
command 
native-image.cmd -jar Test.jar

**Comment by dougxc** [comment]
This looks like #1374 .

**Comment by cstancu** [comment]
Yes, that was fixed by https://github.com/oracle/graal/commit/41aef477f8067f325d0b89bd3b3647f87b5f1b56 but it was not backported to 19.0.2. It will be part of the next 19 release.
