### ISSUE TITLE
Do Graal Native Images preserve the frame pointer?

### ISSUE THREAD

**Issue by RichardWarburton** [oracle/graal#1447]

**Comment by cstancu** [comment]
Can you please elaborate on your question?

**Comment by RichardWarburton** [comment]
Linux's perf tool (and other like it) have an approach to stackwalking that is efficient, but relies on preservation of a frame pointer. Hotspot removes this by default from JIT'd code, however, it can be enabled with -XX:+PreserveFramePointer. GCC has an "omit-frame-pointer" compiler optimisation that removes it as well. I was wondering whether native images produced by Graal preserve the frame pointer or remove it.

**Comment by christianwimmer** [comment]
Similar to HotSpot, native images by default do not preserve the frame pointer. You need to build an image with `-H:+UseStackBasePointer` (in retrospect, we should have named it PreserveFramePointer too)

**Comment by SergejIsbrecht** [comment]
@RichardWarburton , please also have a look at #916

**Comment by RichardWarburton** [comment]
Thanks!
