### ISSUE TITLE
String path = Demo.class.getProtectionDomain().getCodeSource().getLocation().getPath(); return null

### ISSUE THREAD

**Issue by lilili87222** [oracle/graal#1450]
String path = Demo.class.getProtectionDomain().getCodeSource().getLocation().getPath();

Create a Jar and convert it to native image with native-image.cmd -jar native.jar and then  the path is null.
Any way to get the path of the native.exe,so we can read and write config file to the folder next to native.exe.

**Comment by lilili87222** [comment]
I get a way
String nativepath=org.graalvm.nativeimage.ProcessProperties.getExecutableName();
but this dependent on graal-sdk.jar,
Maybe it is better to  put this value to the System.getProperties();  default

**Comment by bobmcwhirter** [comment]
This seems solved via https://github.com/oracle/graal/commit/0b876cbf5970533ad7f84543f0dc45899c5c5865#diff-811de719f750f55690c85a7e84fe2190

**Comment by cstancu** [comment]
@lilili87222 please reopen if the commit mentioned by @bobmcwhirter didn't fix the problem.
