### ISSUE TITLE
[native-image]-[plugin-maven] - executable can not find parameters

### ISSUE THREAD

**Issue by Figurante17** [oracle/graal#1468]
Hi 

I have a project made in gatling + maven and would like to use graalvm in our project.

see the code snippet below, it's working

```
`       <plugins>
      <plugin>
        <groupId>com.oracle.substratevm</groupId>
        <artifactId>native-image-maven-plugin</artifactId>
        <version>1.0.0-rc16</version>
        <configuration>
          <imageName>loadtestRun</imageName>
          <mainClass> io.gatling.app.Gatling</mainClass>
          <outputDirectory>../test-gatling-lt/</outputDirectory>
          <buildArgs> -Dgatling.conf.file=gatling-dinner-dev.conf -Dgatling.data.graphite.rootPathPrefix=test-lt.dinnerpushsimulation  </buildArgs>
        </configuration>
        <executions>
          <execution>
            <goals>
              <goal>native-image</goal>
            </goals>
            <phase>package</phase>
          </execution>
        </executions>
      </plugin>`
```

`./loadtestRun`

however this does not meet our needs, we would like it to be like this

```
   <plugins>
      <plugin>
        <groupId>com.oracle.substratevm</groupId>
        <artifactId>native-image-maven-plugin</artifactId>
        <version>1.0.0-rc16</version>
        <configuration>
          <imageName>loadtestRun</imageName>
          <mainClass> io.gatling.app.Gatling</mainClass>
          <outputDirectory>../test-gatling-lt/</outputDirectory>
        </configuration>
        <executions>
          <execution>
            <goals>
              <goal>native-image</goal>
            </goals>
            <phase>package</phase>
          </execution>
        </executions>
      </plugin>

```
`  ./loadtestRun -Dgatling.conf.file=gatling-dinner-dev.conf -Dgatling.data.graphite.rootPathPrefix=test-lt.dinnerpushsimulation `

what is happening is that ./loadtestRun does not find the file gatling-dinner-dev.conf, neither the string test-lt.dinnerpushsimulation

**Comment by olpaw** [comment]
I assume somewhere in your code you assign the system property `gatling.conf.file` to **a static field**. In native-image `1.0.0-rc16` such code always got evaluated at **image build time** (thus baked into the image with the value the property had at image build time). In newer versions this was fixed and the default is now to execute static initializers at **image runtime** (thus capturing the system property value at runtime vs. at buildtime). Please update to our latest release 19.1.0 (https://www.graalvm.org/downloads/) and see if the behavior in now in line with what you need.

**Comment by Figurante17** [comment]
I updated the maven plugin version and my graalvm

but still can not find my parameters :(

below the changes:

```
    <plugins>
      <plugin>
        <groupId>com.oracle.substratevm</groupId>
        <artifactId>native-image-maven-plugin</artifactId>
        <version>19.1.0</version>
        <configuration>
          <imageName>loadtestRun</imageName>
          <mainClass> io.gatling.app.Gatling</mainClass>
          <outputDirectory>../test-gatling-lt/</outputDirectory>
        </configuration>
        <executions>
          <execution>
            <goals>
              <goal>native-image</goal>
            </goals>
            <phase>package</phase>
          </execution>
        </executions>
      </plugin>
```

```
echo $JAVA_HOME
/usr/lib/jvm/graalvm-ee-19.1.0
```

```./loadtestRun -Dgatling.conf.file=gatling-dinner-dev.conf -Dgatling.data.graphite.rootPathPrefix=test-lt.dinnerpushsimulation```

**Comment by olpaw** [comment]
Do you have the source available? Please add steps to reproduce so that we can take a look,

**Comment by Figurante17** [comment]
I need to check if I have permission to make the code available

This may take a while.

I put another comment here when you have the answer

**Comment by olpaw** [comment]
Please reopen if this is still relevant.
