### ISSUE TITLE
SVM reporting reflection failure at runtime, bug or feature?

### ISSUE THREAD

**Issue by ziyilin** [oracle/graal#1471]
I found SVM would not report reflection failure when it cannot deduce necessary information to constant, but leave it to runtime. Given a simple case:

```
public static void main(String[] args) throws NoSuchFieldException, SecurityException, IllegalArgumentException, IllegalAccessException {
    svmCannotSolve("a");
}

 private static void svmCannotSolve(String name) throws NoSuchFieldException, IllegalAccessException {
    ExampleReflect ex=new ExampleReflect();
    Field f=ExampleReflect.class.getDeclaredField(name);
    f.setAccessible(true);
    int ret=f.getInt(ex);
    if(name.equals("a")&&ret!=1) {
        throw new RuntimeException("Get wrong field value");
    }
}
}

class ExampleReflect{
     private int a=1;
}
```

SVM will build it into a native image without any complains, but throws 
`Exception in thread "main" java.lang.NoSuchFieldException: a`
during runtime.  
I think the early to report such failures the better. Is this a bug or feature? What's the reason behind this behavior?

**Comment by cstancu** [comment]
This is a feature, some frameworks depend on this behavior, i.e., the absence of a field/method/class is considered "configuration". I personally don't like that programming style but we have decided that having an incomplete classpath is something that we need to support and the Native Image build must be succesfull. In the specific case that you mention we actually synthesize the `NoSuchFieldException` at build time and are able to eliminate following code as it is now dead code.
