### ISSUE TITLE
[native-image] native-image-agent does not start in Windows

### ISSUE THREAD

**Issue by apetrelli** [oracle/graal#1473]
Greetings
I am using GraalVM 19.1.0 in a maven project using native-image-maven-plugin 19.1.0.
I am developing a project that I would like to compile natively in Windows. I would like to use the native-image-agent to trace, in particular, calls to JNI.

However if I try to call using the following parameters:
`-agentlib:native-image-agent=config-output-dir=C:/Users/Antonio/wtf`

I see the following error:
```
Error occurred during initialization of VM
Could not find agent library native-image-agent on the library path, with error: Can't find dependent libraries
```

For reference this is the complete command line:

`C:\graalvm-ee\bin\java.exe -agentlib:native-image-agent=config-output-dir=C:/Users/Antonio/wtf -Dfile.encoding=UTF-8 -classpath C:\Users\Antonio\scafa\scafa-systray-windows\target\classes;C:\Users\Antonio\scafa\scafa-systray\target\classes;C:\Users\Antonio\scafa\scafa-server\target\classes;C:\Users\Antonio\.m2\repository\jcifs\jcifs\1.3.17\jcifs-1.3.17.jar;C:\Users\Antonio\.m2\repository\org\ini4j\ini4j\0.5.4\ini4j-0.5.4.jar;C:\Users\Antonio\.m2\repository\commons-io\commons-io\2.4\commons-io-2.4.jar;C:\Users\Antonio\.m2\repository\org\eclipse\platform\org.eclipse.swt.win32.win32.x86_64\3.109.0\org.eclipse.swt.win32.win32.x86_64-3.109.0.jar com.github.apetrelli.scafa.systray.ScafaSystrayMain`

This is the project in Github, if you wish:
https://github.com/apetrelli/scafa

The agent works well in Linux.

**Comment by peter-hofer** [comment]
Thank you for your report. Windows support is still under development and `native-image-agent` is not support on Windows yet.

**Comment by remkop** [comment]
@peter-hofer @pejovica I encountered a similar issue trying to generate a JNI config file for a command line application that uses the [jansi](https://github.com/fusesource/jansi) library to use ANSI colors and styles in the Windows command console shell.

Jansi makes extensive use of JNI, particularly its [CLibrary](https://github.com/fusesource/jansi-native/blob/master/src/main/java/org/fusesource/jansi/internal/CLibrary.java) and [Kernel32](https://github.com/fusesource/jansi-native/blob/master/src/main/java/org/fusesource/jansi/internal/Kernel32.java) classes.

Manually creating a JNI config file for these classes will be error-prone, and a lot of work... Also, I believe my application only needs a subset of the Jansi native functionality, probably just what is in CLibrary. Can anyone give me any tips for automating this task?

**Comment by Vinzce81** [comment]
Hello, could you please tell me if this is still the case ? Is `native-image-agent` supported on windows ? If not will it be the case soon ?

**Comment by dquintela** [comment]
Building on windows (from sources) I managed to build the dll and it worked - but it is currently excluded in ce-win build...

**Comment by jbreathe** [comment]
+1 to @dquintela 
I also made it work by building VM from sources.
You can copy and edit file "graal/vm/mx.vm/ce-win" or edit directly if you want.
Just remove the line
```
SKIP_LIBRARIES=native-image-agent
```
and build it from "graal/vm" directory with this command
```
mx --env ce-win build
```
I have not tried JNI and proxies with the resulting native-image-agent.dll, but reflection and resources seem to work.
There is many prerequisites before building VM from sources on Windows.
You can find some of them on the "compiler" [README](https://github.com/oracle/graal/tree/master/compiler).
#1887 is a good way to start.
Remember that for GraalVM 8 and GraalVM 11 (based on Java 8 and Java 11 accordingly) you will need different MSVC's: MSVC 2010 SP1 for Java 8 and MSVC 2017 for Java 11 (you can find more in #1852).

**Comment by dquintela** [comment]
You will need:
Visual studio 2010 express (tested with this)
Windows 7.1 SDK *
Visual Studio 2010 SP1
Windows 7.1 FIX compilers update *

* Is referenced in README

**Comment by Vinzce81** [comment]
Thank you guys for the quick answers ! I give you a feedback ASAP

**Comment by apetrelli** [comment]
I would love to test JNI, for the project I mentioned in the original issue description, since I use SWT that is very different between Linux and Windows.
If any of you manage to build from source with the Java 11 edition, could it be possible to make it available for us to use it, such as a preview for the next release, please?

**Comment by jbreathe** [comment]
@apetrelli 
I'm just an enthusiast as you are and built Graal with native-image-agent just to play with this agent.
As @peter-hofer said agent is not supported on Windows, so everything is up to you.
But if you want, you can test the DLL that I have build. I don't think that anything is wrong if I share this DLL with you. I can't attach DLL file to the comment, so I made a [repository](https://github.com/jbreathe/svm-components) with this DLL. You can clone it and copy native-image-agent.dll to the "bin" folder in GraalVM home directory, right after native-image.cmd. I tested it with simple reflection example and it works.
I don't see any OS specific code in agent except method com.oracle.svm.agent.jvmti.JvmtiDirectives#getOptions:
```java
@Override
public List<String> getOptions() {
    return Collections.singletonList("-I" + jdkIncludeDir.resolve(OS.getCurrent() == OS.WINDOWS ? "win32" : OS.getCurrent().asPackageName()));
}
```
but I think it's okay.
So maybe agent will just work like on Linux.

**Comment by apetrelli** [comment]
@jbreathe  thanks, I will try it on Monday because the win VM is on the other PC.

**Comment by nightscape** [comment]
@jbreathe I just tried it on a very simple Hello World example and get the following:
```
❯ java -agentpath:C:\Users\nightscape\scoop\apps\graalvm\current\bin\native-image-agent.dll -jar .\target\scala-2.12\scala-native-packager-example-assembly-0.1.0-SNAPSHOT.jar
com.oracle.svm.core.jdk.UnsupportedFeatureError: unimplemented
```
I haven't yet found a way to enable stack traces for the agent to find out where the `UnsupportedFeatureError` is thrown...

**Comment by jbreathe** [comment]
@nightscape 
Did you try to do it like in example in documentation?
Kind of that
```sh
java -agentlib:native-image-agent=config-output-dir=/path/to/config-dir/ -jar ...
```
What version of GraalVM are you using?

**Comment by nightscape** [comment]
@jbreathe yes, I tried that as well, with the same effect:
```
❯ java -agentpath:C:\Users\mucmaucm\scoop\apps\graalvm\current\bin\native-image-agent.dll -agentlib:native-image-agent=config-output-dir=META-INF/native-image -jar .\target\scala-2.12\scala-native-packager-example-assembly-0.1.0-SNAPSHOT.jar
com.oracle.svm.core.jdk.UnsupportedFeatureError: unimplemented
```

Java version:
```
❯ java -version
openjdk version "11.0.5" 2019-10-15
OpenJDK Runtime Environment GraalVM CE 19.3.0.2 (build 11.0.5+10-jvmci-19.3-b06)
OpenJDK 64-Bit Server VM GraalVM CE 19.3.0.2 (build 11.0.5+10-jvmci-19.3-b06, mixed mode, sharing)
```

**Comment by jbreathe** [comment]
@nightscape 
Did you try it without "-agentpath"?
Only "-agentlib" must be enough if java points to installation of GraalVM and you copy native-image-agent.dll to the "bin" folder of this installation.

**Comment by nightscape** [comment]
@jbreathe 🎉 🎉 
That fixes the problem! After creating the `META-INF` directory, the call without `-agentpath` successfully creates the native-image files:
```
❯ java -agentlib:native-image-agent=config-output-dir=META-INF/native-image -jar .\target\scala-2.12\scala-native-packager-example-assembly-0.1.0-SNAPSHOT.jar
Hello world from Windows exe
❯ ls .\META-INF\native-image\


    Directory: C:\Users\nightscape\Workspaces\scala\scala-native-packager-example\META-INF\native-image

Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----        10.01.2020    17:30              4 jni-config.json
-a----        10.01.2020    17:30              4 proxy-config.json
-a----        10.01.2020    17:30              4 reflect-config.json
-a----        10.01.2020    17:30             59 resource-config.json

**Comment by jbreathe** [comment]
Glad to hear that!
Congratulations!

**Comment by peter-hofer** [comment]
Great that you got the agent working! We'll look into the problem where the agent aborts because it can't create the target directory. Please keep us posted about your agent experiences on Windows!

**Comment by apetrelli** [comment]
@jbreathe @peter-hofer  I managed to test it and it works! It creates the jni-config.json too, now I have to check if it is correct.

**Comment by jbreathe** [comment]
@apetrelli 
Good news!

**Comment by olpaw** [comment]
This is fixed on master (3dff62cdcd1dbcc204dd21fee6ed42efebc14553). We were missing an implementation for `ProcessProperties#getProcessID()` that is needed in `com.oracle.svm.agent.Agent#transformPath()`.

**Comment by peter-hofer** [comment]
Thanks @olpaw !

**Comment by jbreathe** [comment]
Nice!
Thank you, @olpaw and @peter-hofer!
I just want to clarify.
Will the "native-image-agent.dll" be built into the next GraalVM release for Windows?
It's still excluded from build in [ce-win](https://github.com/oracle/graal/blob/master/vm/mx.vm/ce-win). But it seems that the agent works! I think there are many developers who want to test the agent on their projects and they can give a lot of feedback! :-)

**Comment by apetrelli** [comment]
@peter-hofer as @jbreathe said, either build it or reopen this issue, because this issue is about providing the agent for Windows, not fixing a bug that nobody would notice anyway because the agent is not built. I said it just for clarity of the issue itself.

**Comment by peter-hofer** [comment]
@jbreathe, I have a pull request for enabling the agent on Windows which should merge soon.

**Comment by jbreathe** [comment]
Great!
Thank you!

**Comment by Vinzce81** [comment]
Hi everyone,
I managed to compile a JDK8 version of GraalVM including native-agent.dll.
I ran the application with it and it well generated the json native-image config files (with a warning about JNI at startup).
The problem I am facing now is native-image crashes with the following error when parsing json proxies config file :

java.lang.RuntimeException: Class org.springframework.core.SerializableTypeWrapper$SerializableTypeProxy not found
Verify that the configuration matches the schema described in the -H:PrintFlags=+ output for option DynamicProxyConfigurationResources.
        at com.oracle.svm.core.util.UserError.abort(UserError.java:65)
        at com.oracle.svm.hosted.config.ConfigurationParserUtils.doParseAndRegister(ConfigurationParserUtils.java:138)
        at com.oracle.svm.hosted.config.ConfigurationParserUtils.lambda$parseAndRegisterConfigurations$3(ConfigurationParserUtils.java:119)
        at java.util.stream.ReferencePipeline$4$1.accept(ReferencePipeline.java:210)
        at com.oracle.svm.hosted.config.ConfigurationParserUtils$1.tryAdvance(ConfigurationParserUtils.java:108)
        at java.util.Spliterator.forEachRemaining(Spliterator.java:326)
        at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:647)
        at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:272)
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
        at java.util.stream.StreamSpliterators$WrappingSpliterator.forEachRemaining(StreamSpliterators.java:313)
        at java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:742)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.IntPipeline.reduce(IntPipeline.java:479)
        at java.util.stream.IntPipeline.sum(IntPipeline.java:437)
        at com.oracle.svm.hosted.config.ConfigurationParserUtils.parseAndRegisterConfigurations(ConfigurationParserUtils.java:125)
        at com.oracle.svm.reflect.proxy.hosted.DynamicProxyFeature.duringSetup(DynamicProxyFeature.java:79)
        at com.oracle.svm.hosted.NativeImageGenerator.lambda$setupNativeImage$12(NativeImageGenerator.java:843)
        at com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:63)
        at com.oracle.svm.hosted.NativeImageGenerator.setupNativeImage(NativeImageGenerator.java:843)
        at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:528)
        at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:445)
        at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Error: Image build request failed with exit status 1

I take any idea since the config file is the one generated by the agent.

**Comment by Vinzce81** [comment]
I guess I don't use the -cp argument correctly since it doesn't find reflect-config.json classes neither. FYI it is a spring-boot fat jar.
