### ISSUE TITLE
IllegalArgumentException: A language with id 'xxx' is not installed

### ISSUE THREAD

**Issue by prdoyle** [oracle/graal#1474]
I'm getting this exception:

```
Exception in thread "main" java.lang.IllegalArgumentException: A language with id 'xxx' is not installed. Installed languages are: [js].
	at com.oracle.truffle.polyglot.PolyglotEngineImpl.requirePublicLanguage(PolyglotEngineImpl.java:695)
	at com.oracle.truffle.polyglot.PolyglotContextImpl.requirePublicLanguage(PolyglotContextImpl.java:821)
	at com.oracle.truffle.polyglot.PolyglotContextImpl.eval(PolyglotContextImpl.java:792)
	at org.graalvm.polyglot.Context.eval(Context.java:341)
	at org.graalvm.polyglot.Context.eval(Context.java:367)
	at org.vena.finch.FinchApplication.main(FinchApplication.java:12)
```

Here's my `main`:

```
public static void main(String[] args) {
	try (Context polyglot = Context.newBuilder().build()) {
		polyglot.eval("xxx", "1 2 + print");
	}
}
```

I have declared this class:

```
package org.vena.finch;

import static com.oracle.truffle.api.TruffleLanguage.*;
import com.oracle.truffle.api.TruffleLanguage;

@Registration(id = "xxx", name = "Finch", contextPolicy=ContextPolicy.SHARED)
public class FinchLanguage extends TruffleLanguage<FinchContext> {
```

My classpath includes `classpath "C:\Users\pdoyle\.babun\cygwin\home\pdoyle\projects\finch\target\classes;...` which is where the above class is located.  I've used `@Registration` so I was expecting my Language class to be discovered during initialization as per its javadocs.

What am I doing wrong?  What else do I need to do to "install" my language?

**Comment by chumer** [comment]
> What am I doing wrong? What else do I need to do to "install" my language?

Either you ship your languages GraalVM component[1].
Or you add the jar using `-Dtruffle.class.path.append` [2].

[1a] https://www.graalvm.org/docs/graalvm-as-a-platform/implement-language/#simplelanguage-component-for-graalvm 
[1b] Example integration: https://github.com/graalvm/simplelanguage/tree/master/component
[2]  https://www.graalvm.org/docs/graalvm-as-a-platform/implement-language/#run-simplelanguage-using-command-line

Please close if this helps.

**Comment by prdoyle** [comment]
Thanks @chumer.  I did try adding my classes using `-Dtruffle.class.path.append` but I was pointing at the classes instead of a jar file.  I can try building a jar when I get a chance.

**Comment by prdoyle** [comment]
It's now pointing at the jar file.  Same exception.  I've confirmed that the jar file exists.

```
-Dtruffle.class.path.append=C:\{yadda yadda}\projects\finch\language/target/language-0.0.1-SNAPSHOT.jar
```

**Comment by prdoyle** [comment]
What does truffle do with such jars anyway?  Is there some kind of truffle-specific manifest in there that I'm supposed to build?

**Comment by boris-spas** [comment]
How did you build the jar? You should be using the simple language repo as a starting point as it has the correct dependencies and configs to build the jar correctly. Namely, there is an annotation processor (truffle-dsl-processor) that needs to be run on the language source code in order to generate the proper META-INF entries. Adding this annotation processor as a dependency in maven should do the trick.

**Comment by goatfryed** [comment]
For anyone else coming here, because he tried to play around with a gradle build

`
dependencies {
    annotationProcessor "org.graalvm.truffle:truffle-dsl-processor:${project.graalvmVersion}"

    implementation "org.graalvm.sdk:graal-sdk:${project.graalvmVersion}"
    implementation "org.graalvm.truffle:truffle-api:${project.graalvmVersion}"
    implementation 'org.antlr:antlr4-runtime:4.7'
    compileOnly "org.graalvm.truffle:truffle-tck:${project.graalvmVersion}"

    testCompile group: 'junit', name: 'junit', version: '4.12'
}
`

did the trick for me.
