### ISSUE TITLE
[native-image] need advice how to deal with class initialization issue

### ISSUE THREAD

**Issue by martinlippert** [oracle/graal#1490]
I am experimenting with native-image compilation, but I am running into the below mentioned error message and have no idea yet how to proceed and how to identify the issue. I marked the class `org.eclipse.jdt.internal.core.NameLookup` to be initialized at build time. Attaching the debugger to the native image builder shows that the class initialization is executed during build time. Nevertheless, the error below shows up. Any idea how I can identify the underlying reason for this message? Any advice would be super appreciated.

Thanks a lot for your help!!!

```
Error: No instances are allowed in the image heap for a class that is initialized or reinitialized at image runtime: org.eclipse.jdt.internal.core.NameLookup$1. Try marking this class for build-time initialization with --initialize-at-build-time=org.eclipse.jdt.internal.core.NameLookup$1
Detailed message:
Trace: 	field org.eclipse.jdt.internal.core.NameLookup.NO_MODULE

com.oracle.svm.core.util.UserError$UserException: No instances are allowed in the image heap for a class that is initialized or reinitialized at image runtime: org.eclipse.jdt.internal.core.NameLookup$1. Try marking this class for build-time initialization with --initialize-at-build-time=org.eclipse.jdt.internal.core.NameLookup$1
Detailed message:
Trace: 	field org.eclipse.jdt.internal.core.NameLookup.NO_MODULE

	at com.oracle.svm.core.util.UserError.abort(UserError.java:75)
	at com.oracle.svm.hosted.FallbackFeature.reportAsFallback(FallbackFeature.java:216)
	at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:732)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:522)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:440)
	at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: No instances are allowed in the image heap for a class that is initialized or reinitialized at image runtime: org.eclipse.jdt.internal.core.NameLookup$1. Try marking this class for build-time initialization with --initialize-at-build-time=org.eclipse.jdt.internal.core.NameLookup$1
Detailed message:
Trace: 	field org.eclipse.jdt.internal.core.NameLookup.NO_MODULE

	at com.oracle.graal.pointsto.constraints.UnsupportedFeatures.report(UnsupportedFeatures.java:130)
	at com.oracle.graal.pointsto.BigBang.finish(BigBang.java:565)
	at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:683)
	... 7 more
Error: Image build request failed with exit status 1
```

**Comment by SergejIsbrecht** [comment]
Do you have the source code to reproduce it?

**Comment by martinlippert** [comment]
Sure, here is the repo:
https://github.com/martinlippert/graal-simple-language-server-jdt

Execute the maven build first (inside of the `org.test.language-server-jdt` directory, then go back and run the `./compile.sh` script, it executes the native-image builder.

Oh, and btw, I would love to learn a bit more here how I could investigate this myself, so any advice how to debug this case (and similar ones) would be super appreciated.

**Comment by SergejIsbrecht** [comment]
Actually I do not know what I am doing either. I just look at the error/ stacktrace and the code and try to figure out whats wrong by trail and error and some source code reading. I will have a look at the source-code.

**Comment by SergejIsbrecht** [comment]
@martinlippert ,

does the application work? If I start it with java -cp ... and visit localhost:5556 I get following error:

```
Startup Language Server...
Connect Language Server...
Let Language Server listen...
Jul 13, 2019 9:57:57 AM org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer fireError
SEVERE: Missing header Content-Length in input "GET / HTTP/1.1
Host: localhost:5556
Connection: keep-alive
Cache-Control: max-age=0
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36
DNT: 1
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9

"
java.lang.IllegalStateException: Missing header Content-Length in input "GET / HTTP/1.1
Host: localhost:5556
Connection: keep-alive
Cache-Control: max-age=0
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36
DNT: 1
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9

"
        at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:91)
        at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

```

Info about Init.
https://github.com/oracle/graal/blob/master/substratevm/CLASS-INITIALIZATION.md

How to build native-image?
```
#!/usr/bin/env bash

rm simple-ls-jdt

export CP=org.test.language-server-jdt/target/org.test.language-server-jdt-0.0.1-SNAPSHOT.jar

printf "\n\nCompile Native Image...\n"
native-image \
  --no-server \
  -H:Name=simple-ls-jdt \
  -H:+PrintClassInitialization \
  -H:+ReportExceptionStackTraces \
  -H:DynamicProxyConfigurationFiles=generated-config/proxy-config.json \
  -H:ReflectionConfigurationFiles=generated-config/reflect-config.json \
  --no-fallback \
  --allow-incomplete-classpath \
  --report-unsupported-elements-at-runtime \
  --initialize-at-build-time \
  -cp $CP org.test.ls.ServerSocketLauncher

printf "\n\nCompiled app (clr)\n"
time ./simple-ls-jdt

```

PrintClassInitialization will give an report, which you can use in order to fine-tune the image generation. Currently all classes will be init. while RUNTIME (  --initialize-at-build-time \), except the safe ones.

I will dig a little bit further

**Comment by martinlippert** [comment]
@SergejIsbrecht 

> does the application work? If I start it with java -cp ... and visit localhost:5556 I get following error:

The app opens a server socket, but doesn't serve HTTP requests. It is a language server that talks JSON-RPC with the outside world, so its a bit hard to test without a proper client. But I already struggle with compiling it to a native image.

> How to build native-image?
> 
> ```
> #!/usr/bin/env bash
> 
> rm simple-ls-jdt
> 
> export CP=org.test.language-server-jdt/target/org.test.language-server-jdt-0.0.1-SNAPSHOT.jar
> 
> printf "\n\nCompile Native Image...\n"
> native-image \
>   --no-server \
>   -H:Name=simple-ls-jdt \
>   -H:+PrintClassInitialization \
>   -H:+ReportExceptionStackTraces \
>   -H:DynamicProxyConfigurationFiles=generated-config/proxy-config.json \
>   -H:ReflectionConfigurationFiles=generated-config/reflect-config.json \
>   --no-fallback \
>   --allow-incomplete-classpath \
>   --report-unsupported-elements-at-runtime \
>   --initialize-at-build-time \
>   -cp $CP org.test.ls.ServerSocketLauncher
> 
> printf "\n\nCompiled app (clr)\n"
> time ./simple-ls-jdt
> ```
> 
> PrintClassInitialization will give an report, which you can use in order to fine-tune the image generation. Currently all classes will be init. while RUNTIME ( --initialize-at-build-time ), except the safe ones.
> 
> ```
> Compile Native Image...
> [simple-ls-jdt:27075]    classlist:   3,159.39 ms
> [simple-ls-jdt:27075]        (cap):     923.24 ms
> [simple-ls-jdt:27075]        setup:   1,955.41 ms
> Warning: class initialization of class org.eclipse.core.internal.resources.Workspace failed with exception java.lang.ExceptionInInitializerError. This class will be initialized at run time because either option --report-unsupported-elements-at-runtime or option --allow-incomplete-classpath is used for image building. Use the option --initialize-at-run-time=org.eclipse.core.internal.resources.Workspace to explicitly request delayed initialization of this class.
> Warning: class initialization of class org.eclipse.jdt.internal.core.ClasspathEntry failed with exception java.lang.ExceptionInInitializerError. This class will be initialized at run time because either option --report-unsupported-elements-at-runtime or option --allow-incomplete-classpath is used for image building. Use the option --initialize-at-run-time=org.eclipse.jdt.internal.core.ClasspathEntry to explicitly request delayed initialization of this class.
> Warning: class initialization of class org.eclipse.core.internal.filesystem.InternalFileSystemCore failed with exception java.lang.ExceptionInInitializerError. This class will be initialized at run time because either option --report-unsupported-elements-at-runtime or option --allow-incomplete-classpath is used for image building. Use the option --initialize-at-run-time=org.eclipse.core.internal.filesystem.InternalFileSystemCore to explicitly request delayed initialization of this class.
> [simple-ls-jdt:27075]   (typeflow):  14,252.52 ms
> [simple-ls-jdt:27075]    (objects):  19,971.87 ms
> [simple-ls-jdt:27075]   (features):   7,006.08 ms
> [simple-ls-jdt:27075]     analysis:  42,019.48 ms
> Printing initializer configuration to /home/sergej/Development/GitHub/graal-simple-language-server-jdt/reports/initializer_configuration_20190713_094752.txt
> Printing initializer dependencies to /home/sergej/Development/GitHub/graal-simple-language-server-jdt/reports/initializer_dependencies_20190713_094752.dot
> Printing 0 classes that are considered as safe for build-time initialization to /home/sergej/Development/GitHub/graal-simple-language-server-jdt/reports/safe_classes_20190713_094752.txt
> Printing 6983 classes of type BUILD_TIME to /home/sergej/Development/GitHub/graal-simple-language-server-jdt/reports/build_time_classes_20190713_094752.txt
> Printing 16 classes of type RERUN to /home/sergej/Development/GitHub/graal-simple-language-server-jdt/reports/rerun_classes_20190713_094752.txt
> Printing 3 classes of type RUN_TIME to /home/sergej/Development/GitHub/graal-simple-language-server-jdt/reports/run_time_classes_20190713_094752.txt
> [simple-ls-jdt:27075]     (clinit):     550.73 ms
> [simple-ls-jdt:27075]     universe:   1,478.58 ms
> [simple-ls-jdt:27075]      (parse):   2,734.23 ms
> [simple-ls-jdt:27075]     (inline):   4,402.94 ms
> [simple-ls-jdt:27075]    (compile):  19,705.41 ms
> [simple-ls-jdt:27075]      compile:  28,400.85 ms
> [simple-ls-jdt:27075]        image:   2,397.49 ms
> [simple-ls-jdt:27075]        write:     496.41 ms
> [simple-ls-jdt:27075]      [total]:  80,061.94 ms
> 
> 
> Compiled app (clr)
> Startup Language Server...
> Connect Language Server...
> Let Language Server listen...
> Jul 13, 2019 9:49:35 AM org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer fireError
> SEVERE: Missing header Content-Length in input "GET / HTTP/1.1
> Host: localhost:5556
> Connection: keep-alive
> Upgrade-Insecure-Requests: 1
> User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36
> DNT: 1
> Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3
> Accept-Encoding: gzip, deflate, br
> Accept-Language: en-US,en;q=0.9
> 
> "
> java.lang.IllegalStateException: Missing header Content-Length in input "GET / HTTP/1.1
> Host: localhost:5556
> Connection: keep-alive
> Upgrade-Insecure-Requests: 1
> User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36
> DNT: 1
> Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3
> Accept-Encoding: gzip, deflate, br
> Accept-Language: en-US,en;q=0.9
> 
> "
>         at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:91)
>         at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
>         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
>         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
>         at java.lang.Thread.run(Thread.java:748)
>         at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:473)
>         at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:193)
> ```
> 
> I will dig a little bit further

Does that mean that building the native image works for you with the mentioned parameters? That would be awesome and would guide me one step further.

**Comment by SergejIsbrecht** [comment]
Yeah, just replace your config.sh with mine and it should work. The native image is quite big. I think it was 35mib

**Comment by martinlippert** [comment]
I did. Interestingly, when I execute the native-image builder with the arguments mentioned above, I don't get the reports output, but instead a few exceptions, complaining about classes that should be initialized at runtime (for a good reason). I wonder how you succeed building the native image.

**Comment by martinlippert** [comment]
Ok, now by adding those exceptional classes to be initialized at runtime, I can also get the native-image to be generated... Which is awesome!!! :-)

**Comment by martinlippert** [comment]
It looks like I missed the parameter `--initialize-at-build-time` without any classes and/or packages initially, wasn't aware of the fact that is makes sense to add that in that way. Many thanks for that hint, much appreciated. So no need to dive deeper from your end, I think I can make progress myself again. :-)
