### ISSUE TITLE
[native-image] "Static field or an object referenced from a static field changed during native image generation" (involving reflection types)

### ISSUE THREAD

**Issue by aclement** [oracle/graal#1495]
Note: I am on graal 19.0.2 on mac. (I can't use 19.1.0 due to the JMX issue in another bug). Is it likely to work better in 19.1?

Just wondering if this is something I can fix with configuration or not:
```
Fatal error: com.oracle.svm.core.util.VMError$HostedError: com.oracle.svm.core.util.UserError$UserException: Static field or an object referenced from a static field changed during native image generation?
  object:[Ljava.lang.reflect.TypeVariable;@b138cf3  of class: java.lang.reflect.TypeVariable[]
  reachable through:
    object: sun.reflect.generics.repository.MethodRepository@14597adf  of class: sun.reflect.generics.repository.MethodRepository
    object: public abstract void org.springframework.data.repository.CrudRepository.deleteAll(java.lang.Iterable)  of class: java.lang.reflect.Method
    root: HostedField<$Proxy259.m24 location: 4472   AnalysisField<$Proxy259.m24 accessed: false reads: true written: true>>

        at com.oracle.svm.core.util.VMError.shouldNotReachHere(VMError.java:70)
        at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:638)
        at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:441)
        at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

I found some other issues with the same error (but different objects involved) but they seemed to be resolved by fixes in graal rather than user configuration? 

thanks!

**Comment by SergejIsbrecht** [comment]
Do you have the source-code to reproduce it?

Maybe init. the class during RUN_TIME instead of BUILD_TIME?

**Comment by cstancu** [comment]
If you have code to reproduce this it would be great. This is a type of bug that we have seen before and fixed, but may have missed some corner cases.

**Comment by aclement** [comment]
@cstancu Here we go, hope this is ok:

```
git clone git@github.com:aclement/spring-boot-graal-feature.git
cd spring-boot-graal-feature
./mvnw clean package
cd samples/vanilla-jpa
./compile.sh
```
The compile script will maven build the vanilla-jpa project and then call native-image on it with the feature on the classpath. As I say this is on graal 19.0.2, I might try building my own graal latest to see if it behaves differently. I don't know if I expect the app to run clean once compiled, there may be further errors after this one.

**Comment by aclement** [comment]
This appears to be fixed, I was just retesting on graal master today. thanks!
