### ISSUE TITLE
Type Literals for Complex JS Objects w/Mixed Value Types

### ISSUE THREAD

**Issue by abhillman** [oracle/graal#1496]
`TypeLiteral` is a wonderful abstraction. Yet it doesn't seem to me that there is some type literal that can be expressed to extract values from a JS object that can be either primitives or lists/objects.

For example, the type literal for `Map<String, ?>`, when operating on `{a: 1, b: "foo", c: {d: "val}}` will result in a Java map with the keys, values "a"/1, "b"/"foo", and c/null. Ideal result would be c/map(d/"val").

```
private static final TypeLiteral<List<String>> typeLiteral = new TypeLiteral<Map<String, ?>>() {};
context.eval("js", "JSON.parse('{\"a\": 1, \"b\": \"foo\", \"c\": {\"d\": \"val\"}}')".as(typeLiteral)
```

Is there some type literal that I am missing that could result in the correct map being emitted? If not, this would be an incredibly powerful feature.

**Comment by boris-spas** [comment]
Tracking internally as Issue GR-20921.
