### ISSUE TITLE
[native-image] Can't run on Windows 10

### ISSUE THREAD

**Issue by jwedel** [oracle/graal#1509]
On Windows 10, I installed the Windows 10 SDK. This does not contain a separate command prompt as the Windows 7 SDK to run native-image as explained in the substrateVM readme.

So I can't get around the error
```
Error: Unable to compile C-ABI query code. Make sure GCC toolchain is installed on your system.
```

**Comment by olpaw** [comment]
ATM using Windows 10 SDK is not supported. Please install [Microsoft Windows SDK for Windows 7](https://www.microsoft.com/en-us/download/details.aspx?id=8442) on Windows 10. Supporting newer versions of Windows SDK/VS will be added in the future.

**Comment by jwedel** [comment]
@olpaw Thanks, I didn't know that I can install the Win7 SDK. Thanks!

**Comment by olpaw** [comment]
@jwedel be careful to use the `SDKSetup.exe` in the `Setup` subdirectory of the iso image.
see https://github.com/oracle/graal/issues/946#issuecomment-459333372

**Comment by jwedel** [comment]
@olpaw Thanks, I had the same issues and found that I get at least a little bit further. But the installation stops with that error:

> Installation of the "Microsoft Windows SDK for Windows 7" product has reported the following error: Please refer to Samples\Setup\HTML\ConfigDetails.htm document for further information.

**Comment by olpaw** [comment]
https://stackoverflow.com/questions/1901279/windows-7-sdk-installation-failure ;-)
