### ISSUE TITLE
GraalVM Updater utility not supported on windows??

### ISSUE THREAD

**Issue by json-warner** [oracle/graal#1512]
The GraalVM Updater utility doe not appear to be included in the windows zip.

I was able to pull it out of the Linux tarball, and I pulled the cmd file from GitHub, but I'm unable to get a list or install components. The result I get is

![image](https://user-images.githubusercontent.com/15092973/61565423-fec0ed80-aa46-11e9-87dd-3fa7a3376751.png)

When I look at the the referenced properties, I only see mac and linux versions.

**Comment by ansalond** [comment]
Hi @json-warner, thanks for your interest in GraalVM.
Unfortunately we do not yet provide installable components for GraalVM on Windows, therefore we do not yet support the GraalVM Updater utility on that platform.

**Comment by json-warner** [comment]
Hi @ansalond, thanks for the quick response.
I suspected as much, but wanted to confirm.

Can you tell me if this is something on the roadmap/schedule for future release?

**Comment by T3rm1** [comment]
How can we install native-image without it on Windows?

**Comment by ansalond** [comment]
Sorry for the late replies.
> Can you tell me if this is something on the roadmap/schedule for future release?

Yes, but unfortunately I don't have an ETA yet.

> How can we install native-image without it on Windows?
> Nevermind, it is already included.

Correct.

@json-warner, is it ok to close this issue?

**Comment by json-warner** [comment]
@ansalond Yes, you can close the issue

**Comment by vwiencek** [comment]
Hello

Sorry if I missed something, but what is the procedure to install fastr library under windows because we cannot use the GraalVM updated `gu`

Thanks

**Comment by MartinBalin** [comment]
Hi,
We plan to add `gu` to GraalVM Windows preview builds soon. There is no Windows build of FastR as far as I know...

**Comment by jdimeo** [comment]
Very eager to put rJava and Renjin in the rear view mirror and get R going for Windows!  can't wait!
