### ISSUE TITLE
[sulong] Error "Cannot convert $val to native pointer"

### ISSUE THREAD

**Issue by lewurm** [oracle/graal#1518]
Hello friends,

I think I'm hitting a bug somewhere around here:
https://github.com/oracle/graal/blob/64f1da79b595095722950e88bfa942971b7a226e/sulong/projects/com.oracle.truffle.llvm.runtime/src/com/oracle/truffle/llvm/runtime/library/LLVMNativeLibraryDefaults.java#L108-L119

`repro.c`:
```C
static inline int mono_icall_get_platform(void) {
        return 4;
}

int ves_icall_System_Environment_get_Platform(void) {
        return mono_icall_get_platform();
}

int main(void) {
        void *ptr = (void *)ves_icall_System_Environment_get_Platform;

        typedef void* (*T)(void);
        T ftptr = (T)ptr;
        void *val = ftptr();
        return (int)val;
}
```

```console
$ clang repro.c && ./a.out; echo $?
4
$ clang -fembed-bitcode -c repro.c
$ objcopy -O binary --only-section=.llvmbc repro.{o,bc}
$ lli --version
LLVM (GraalVM CE Native 19.1.1)
$ lli repro.bc
Cannot convert 4 to native pointer.
        at <llvm> main(Unknown)
```

**Comment by zapster** [comment]
Hi @lewurm!

Thanks for you report! Could you try compiling the sources with `clang -O1`? With `-O0`, which unfortunately is the default, llvm does not run optimizations which are crucial for our LLVM IR runtime. To be more precise, it is about the `-mem2reg` pass. Without that, every LLVM value is stored in memory, which makes it impossible for us to track those values.

**Comment by lewurm** [comment]
Thank you @zapster.

I can confirm that `-O1` fixes the problem for the reproducer I've provided. Unfortunately if I compile my application with `-O1` I still run into the problem. FWIW, with `-O2` I hit another issue: https://github.com/oracle/graal/issues/1534

The problem seems to be that `void *` and `int` isn't interchangeable, that is, if `T` is defined like this:
```c
typedef int (*T)(void);
```
then it works as expected.

In practice this seems to be accepted by most (all?) compilers, but no idea what the C spec has to say about that.

**Comment by zapster** [comment]
Thanks for digging deeper into the issue, Bernhard!
Right, it seems like we are tripping over the function pointer return type mismatch (or rather, we are more strict that the C compiler and failing in a weird way). Maybe we should be more relaxed about that. I'll reopen this issue and have another look.

**Comment by larsrh** [comment]
I may or may not have the same problem. The following attached bitcode file can be evaluated fine, but running `test` fails:

```java
Context polyglot = Context.newBuilder().allowAllAccess(true).build();
URL resource = App.class.getClassLoader().getResource("rust-embedded.bc");
Source source = Source.newBuilder("llvm", resource).build();
polyglot.eval(source);
        polyglot.getBindings("llvm").getMember("test").as(Runnable.class).run();
```

The trace is:

```
Exception in thread "main" Cannot convert com.oracle.truffle.llvm.runtime.interop.LLVMTypedForeignObject@6581dc0a to native pointer.
        at <llvm> test(rust-embedded.bc:test:1:0-20)
        at com.oracle.truffle.polyglot.FunctionProxyHandler.invoke(HostInteropReflect.java:454)
        at com.sun.proxy.$Proxy16.run(Unknown Source)
        at info.hupel.graal.App.main(App.java:17)

```

The bitcode has been produced by compiling some Rust code to LLVM bitcode, and then running:

```
llvm-link -o - build/cargo/release/deps/*.bc | \
  opt -O2 -o - | \
  llvm-dis -o build/bitcode/rust-embedded.ll
```

Attached is the file: [rust-embedded.ll.gz](https://github.com/oracle/graal/files/3481040/rust-embedded.ll.gz)

**Comment by larsrh** [comment]
After careful reading of the docs, I'm convinced that I completely misunderstood the way Sulong works and that this is in fact not a bug. Values that live in the JVM cannot be stored in native pointers. Am I getting this right? If yes, I apologize for the noise.

**Comment by zapster** [comment]
closing stale issue. please reopen if appropriate.
