### ISSUE TITLE
[native-image] 19.1.1 Logging missing reflection / NullPointerException in CompileQueue defaultCompileFunction

### ISSUE THREAD

**Issue by nhoughto** [oracle/graal#1528]
Similar to https://github.com/oracle/graal/issues/582

I am getting a NPE when building a native-image, after some further debugging, and recompiling CompileQueue with more logging, I can see its due to Xerces XML parser, so likely a reflection config problem. As per above issue, just a different library.

Debugging this problem would be greatly aided by better logging in CompileQueue, rather than just throwing a NPE if you logged what class/compilation identifier was missing it would point to the problem, or even call out its a reflection relates issue.

Line in question:
https://github.com/oracle/graal/blob/b03199134754bf35fef43ec9b96e8f5afca6d0a1/substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/code/CompileQueue.java#L931

`graph` is null in my case.

**Comment by peter-hofer** [comment]
Thank you for your report, I am in the process of merging improved error reporting.

**Comment by peter-hofer** [comment]
Fixed in 4cb4bdf3eeba212da44273f127f11b376a5eb4ee
