### ISSUE TITLE
[native-image]Could not find testing programs' own class or function name

### ISSUE THREAD

**Issue by AliredDevils** [oracle/graal#1545]
1. Environment
- [1] GraalVM 19.0.2 
- [2] Linux 16.04 X86-64
2. Test Java Program
- [1] please check the attachment HelloWorld.java
3. Native Image command:
`native-image -H:Class=HelloWorld -H:Name=helloworld`

And then,i can get the `helloworld` executable file,and the result is correct.But i could not find the class and function name in the `helloworld` file.The steps are as follows:

- `objdump -t -C -S helloworld > asm.txt`

- search the `HelloWorld` class, `fileCopy`  and `strUpAndLow` functions in the `asm.txt` file

It failed to find any key-words.So i want to know whether it will optimize the class or functions during the compiling by svm?
Can you give some tips about how to optimize the program,such as class and function during converting java byte codes into native ?
Should have some options for me to make the java class and function stayed in the native executable files?

**Comment by AliredDevils** [comment]
[HelloWorld.zip](https://github.com/oracle/graal/files/3435085/HelloWorld.zip)

**Comment by olpaw** [comment]
Building with `-H:-DeleteLocalSymbols` will give you want you want.
