### ISSUE TITLE
Kotlin interfaces cause native-image failures

### ISSUE THREAD

**Issue by yschimke** [oracle/graal#1549]
See https://github.com/oracle/graal/issues/1521

**Comment by yschimke** [comment]
Kotlin issue ticket https://youtrack.jetbrains.com/issue/KT-33097

**Comment by cstancu** [comment]
@yschimke thanks for investigating further and opening the Kotlin ticket!

**Comment by yschimke** [comment]
I didn’t. Just connecting loop

**Comment by cstancu** [comment]
I am closing this issue as it is a Kotlin bug. Please see https://github.com/square/okhttp/pull/5631 for possible workaround.
