### ISSUE TITLE
With native-image, reading a large file is more than 2X slower than Java

### ISSUE THREAD

**Issue by alvinj** [oracle/graal#1550]
I don’t know if you consider performance to be a bug, but I have a situation where I need to read a 9GB text file (Apache access log), and I found these results for a simple line-counting algorithm:

- Running with Java: ~20 seconds
- Running with a native-image executable: ~56 seconds

I’ve written several different versions of the code using BufferedReader and NIO classes, and here’s the NIO version, written in Scala:

```scala
import java.nio.file.{Files, Paths}
import java.util.stream.Stream

object JavaNioFiles extends App {

    val startTime = System.nanoTime

    val stream: Stream[String] = Files.lines(Paths.get("access_log.big"))
    val numLines = stream.count
    stream.close

    val stopTime = System.nanoTime
    val delta = (stopTime - startTime) / 1000000d

    println(s"counted $numLines lines")
    println(s"$delta ms")

}
```

If it helps to know it, I run the jar file (which I named *FIND.jar*) with Java 8 like this:

````
java -cp ".:FIND.jar:$SCALA_HOME/lib/scala-library.jar" JavaNioFiles$delayedInit$body
````

And I create the native image like this:

````
native-image --no-server -cp $SCALA_HOME/lib/scala-library.jar -jar FIND.jar
````

or this:

````
native-image --no-server -cp $SCALA_HOME/lib/scala-library.jar:FIND.jar JavaNioFiles$delayedInit$body
````

As mentioned, this is strictly a performance issue, but if there are any options to try to improve this, I’ll be glad to try them. Thanks.

**Comment by thomaswue** [comment]
Have you tried running with profile guided optimizations?

**Comment by alvinj** [comment]
No, I’m sorry, I saw that option but I’m only using the Community Edition.

**Comment by alvinj** [comment]
Okay, two problems. First, there is no `native-image` command in the “Oracle GraalVM Enterprise Edition based on JDK8 for macOS (19.1.1).” I just installed it on my Mac, unpacked it, tried to use it, then found that this command is not included. I confirmed that by searching the directory with the `find` command.

Second, an issue that doesn’t matter just yet, but are there any more docs on how to use “profile-guided optimization” other than what’s here at this link:

https://www.graalvm.org/docs/reference-manual/aot-compilation

I haven’t done this before, and I’m not sure what the process is.

Thanks,
Al

**Comment by thomaswue** [comment]
There is an extra download at https://www.oracle.com/technetwork/graalvm/downloads/index.html "Oracle GraalVM Enterprise Edition Native Image Early Adopter". After downloading you can use:

gu install --local-file my/path/to/my/file

The process for PGO is to first create an image with the "--pgo-instrument" flag. Then you run an example program. The result will be a profile.iprof file. Then you can create a second image with "--pgo profile.iprof" flag that should be significantly faster.

**Comment by alvinj** [comment]
I’m sorry that I didn’t see that download link, but I guess I wouldn’t have known what to do with it anyway.

The short summary is:

- The first native image, create with `--pgo-instrument`, takes 74 seconds to run
- The second native image, created with `--pgo`, takes 56 seconds to run
- Running the original jar file with `java` takes 26 seconds to run

More details:

I created the first image like this:

````
$ native-image --pgo-instrument -cp $SCALA_HOME/lib/scala-library.jar:FIND5.jar JavaNioFiles$delayedInit$body
````

Running that executable creates *default.iprof*. Then I *tried* to create the second image like this, but it failed with the error shown:

````
$ native-image --pgo default.iprof -cp $SCALA_HOME/lib/scala-library.jar:FIND5.jar JavaNioFiles$delayedInit$body
Build on Server(pid: 25373, port: 58567)
[JavaNioFiles:25373]    classlist:   3,364.67 ms
Error: Main entry point class 'default.iprof' not found.
Error: Use -H:+ReportExceptionStackTraces to print stacktrace of underlying exception
Error: Image build request failed with exit status 1
````

Then I read the results from `native-image --help` and it said you could use `--pgo` without any arguments to read the *default.iprof* file, so I ran this command:

````
$ native-image --pgo -cp $SCALA_HOME/lib/scala-library.jar:FIND5.jar JavaNioFiles$delayedInit$body
````

It created the second native image, and then I got the results shown above.

Everything ran a little slower today because I tried a different file-reading approach, but as shown, the native image is still significantly slower than `java`.

If I can provide any more information, just let me know. I’m glad to help, this seems like a terrific project.

**Comment by wirthi** [comment]
I am closing this 5 year old ticket. 

GraalVM and Native Image have improved a lot since then. The recent 1BRC has shown that Native Image can be quite competitive in reading large files in Java. https://github.com/gunnarmorling/1brc

**Comment by auula** [comment]
I have a similar problem, the current AOT of the Graal compiler can only do so much, the compiled binaries are very large compared to those of C#, Go, Rust and other languages, taking up a lot of disk memory, and I would like to be able to solve it amicably, I use upx for compression and it makes the program unable to start... 🙏
