### ISSUE TITLE
libgraal binary compiled with a frame pointer support

### ISSUE THREAD

**Issue by qwwdfsad** [oracle/graal#1555]
### The problem statement

Currently, libgraal uses `rbp` register as a general-purpose register (instead of storing frame pointer), thus making impossible to profile it by default Linux/MacOS X tools.

It would be nice to have a separate binary (or at least ability to build it from source) that preserves frame pointer.

### Use-case 

For an experiment, we at JetBrains tried to use Kotlin compiler along with libgraal to potentially improve startup/cold compilation times.
While investigating the new Kotlin compiler profile with [`async-profiler`](https://github.com/jvm-profiling-tools/async-profiler), I've found that most of the time is spent in the Graal itself: https://www.screencast.com/t/pHtxzWiqcbR
I would like to provide more details where the time is spent in the `libgraal` and maybe construct a more isolated code example (instead of 1k+ KLOC compiler) to see where Graal can be further improved, but for that a more detailed profile (-> frame pointer) is required.

**Comment by dougxc** [comment]
It should be possible to build a stripped down GraalVM CE that includes a libgraal that doesn't use `rbp`:
```
graal/vm> mx --env libgraal --extra-image-builder-argument=-H:+PreserveFramePointer build
graal/vm> latest_graalvm_home/bin/java -version
java version "1.8.0_221"
Java(TM) SE Runtime Environment (build 1.8.0_221-b11)
Java HotSpot(TM) 64-Bit GraalVM LIBGRAAL 19.3.0-dev (build 25.221-b11-jvmci-19.2-b02, mixed mode)
```

**Comment by cstancu** [comment]
FYI: This options used to be named `-H:+UseStackBasePointer` in older releases. Related: https://github.com/oracle/graal/issues/1447

**Comment by thomaswue** [comment]
Do you have some benchmark suite for the Kotlin compiler that we could run? Also JFRs and -Dgraal.PrintCompilation=true output of a run could be of interest.

**Comment by qwwdfsad** [comment]
Thanks, I will try to re-evaluate my experiment with `PreserveFramePointer`, though it may take a while because I've never built Graal from scratch before.

@thomaswue unfortunately, nothing really self-contained and automated.
Internally, we use something like "clean compile this project 10 times, collect statistics of each run and verify that all statistics are within error bounds".

In my case, it's as simple as 
```
export JAVA_HOME=path-to-graal
export _JAVA_OPTIONS=-XX:-UseJVMCINativeLibrary

... repeat in bash
./gradlew --no-daemon clean :project:compile
```

**Comment by fernando-valdez** [comment]
Hello @qwwdfsad I am closing this issue as it seems this issue is not relevant anymore.
