### ISSUE TITLE
Using POLYGLOT_DECLARE_TYPE fails with Don't call __polyglot_as_typeid function directly

### ISSUE THREAD

**Issue by jukowski** [oracle/graal#1556]
First of all, great work! Amazing vision!

I want to retire JNI and use a high-performance C library directly through GraalVM & Polyglot. I stumbled on the following error message when I want to return a custom C structure back to Java:
`Don't call __polyglot_as_typeid function directly, use POLYGLOT_DECLARE_* macros.`

I do use the POLYGLOT_DECLARE macro. I also get the same error when trying the examples mentioned by @rschatz in issues:  
https://github.com/graalvm/sulong/issues/867
https://github.com/oracle/graal/issues/609

e.g.
'typedef struct CPP_Point {
    double x;
    double y;
} CPP_Point;

POLYGLOT_DECLARE_TYPE(CPP_Point)'

- I tried both LLVM 8.0.1 and LLVM 7.1.0 compilers.
- I compile using 'clang -c -O1 -emit-llvm test.c'
- Symbols in the test.bc file look ok as well (no name mangling)
'                U __polyglot_as_typeid
                 U malloc
---------------- T new_Point_Alloc
---------------- d polyglot_CPP_Point_typeid.__polyglot_typeid_CPP_Point
                 U polyglot_from_typed
'

**Comment by rschatz** [comment]
Can you try compiling with `-g`? The `POLYGLOT_DECLARE_*` macros only work with debug information enabled, otherwise there is no way to find out the name of the struct members.

We should definitely improve that error message ;)

**Comment by jukowski** [comment]
It worked, thank you!
