### ISSUE TITLE
[native-image] compiled successfully with llvm-backend but running failed with "Single-threaded VM cannot create new threads"

### ISSUE THREAD

**Issue by AliredDevils** [oracle/graal#1559]
Compile rawhttp native image:
1.Default style(lir backend)

- Compile native image successfully
- Native image running successfully

2.llvm-backend compiler

- Compile native image successfully
- Native image running **failed**

> To run a HTTP server on port 8082 serving the public/ directory:
    `~/graal/substratevm/rawhttp serve ~/public/ --port 8082`

The errors:

    Exception_ in thread "main" com.oracle.svm.core.jdk.UnsupportedFeatureError: Single-threaded VM cannot create new threads
	at com.oracle.svm.core.util.VMError.unsupportedFeature(VMError.java:102)
	at java.lang.Thread.start0(Thread.java:206)
	at java.lang.Thread.start(Thread.java:717)
	at rawhttp.core.server.TcpRawHttpServer$RouterAndSocket.start(TcpRawHttpServer.java:222)
	at rawhttp.core.server.TcpRawHttpServer$RouterAndSocket.<init>(TcpRawHttpServer.java:199)
	at rawhttp.core.server.TcpRawHttpServer.start(TcpRawHttpServer.java:75)
	at rawhttp.cli.Main.serve(Main.java:217)
	at rawhttp.cli.Options.run(OptionsParser.java:149)
	at rawhttp.cli.Main.main(Main.java:44)

_Build native image commands with "llvm-backend"_

- `mx native-image -jar rawhttp-cli-0.9.1-all.jar -H:Name=rawhttp -H:CompilerBackend=llvm -H:-SpawnIsolates -H:-MultiThreaded`

The rawhttp details:https://sites.google.com/a/athaydes.com/renato-athaydes/posts/a7mbnative-imagejavaappthatrunsin30msandusesonly4mbofram

**Comment by dougxc** [comment]
@loicottet can you please offer your thoughts on this.

**Comment by AliredDevils** [comment]
The llvm compiler alse does not support multi-thread options:`MultiThreaded`  ? @loicottet

**Comment by loicottet** [comment]
You are using `-H:-MultiThreaded` which _disables_ multi-threading. Removing this option or setting `-H:+MultiThreaded` will work.

**Comment by AliredDevils** [comment]
> You are using `-H:-MultiThreaded` which _disables_ multi-threading. Removing this option or setting `-H:+MultiThreaded` will work.

If removing the options `-H:-MultiThreaded` and `-H:-SpawnIsolates`, it will be failed during compiling.

I submitted similar issue [1416](https://github.com/oracle/graal/issues/1416#issuecomment-507241082) before, the llvm currently dose not support "multithreaded" and "isolates".

The commit ID of my local source codes : `488579b038cc33391111831d4aef440cc64bf722`, should i update my source code?

**Comment by loicottet** [comment]
Isolates are still not supported by the LLVM backend, so you should still use `-H:-SpawnIsolates`, and only remove `-H:-MultiThreaded`

**Comment by AliredDevils** [comment]
> Isolates are still not supported by the LLVM backend, so you should still use `-H:-SpawnIsolates`, and only remove `-H:-MultiThreaded`

Cool, that's all right,thanks very much.
