### ISSUE TITLE
TruffleFile shouldn't use TypeLiteral

### ISSUE THREAD

**Issue by fniephaus** [oracle/graal#1560]
Had a chat with @chumer and he suggested not to use `TypeLiteral` in `TruffleFile`:

https://github.com/oracle/graal/blob/22f49a52f86bbeb0405bef1c25b38cdd969ebea8/truffle/src/com.oracle.truffle.api/src/com/oracle/truffle/api/TruffleFile.java#L185

This throws a caught ArrayIndexOutOfBoundsException.

#### Call stack
![image](https://user-images.githubusercontent.com/2368856/62214450-60694c00-b3a5-11e9-9474-e885dae91123.png)

**Comment by tzezula** [comment]
Right, the `SignatureParser.current` uses exception control flow with no reason.
```
private char current(){
        assert(index <= input.length);
        try {
            return input[index];
        } catch (ArrayIndexOutOfBoundsException e) { return EOI;}
    }
```

**Comment by fniephaus** [comment]
Maybe this deserves to be fixed in OpenJDK?

**Comment by tzezula** [comment]
Yes, I will fill an issue with patch.

**Comment by fniephaus** [comment]
Thanks!

**Comment by thurka** [comment]
This is fixed in JDK-9. https://bugs.openjdk.java.net/browse/JDK-8035424

**Comment by tzezula** [comment]
The `TruffleFile` does not use `TypeLiteral` anymore.
The issue in `SignatureParser` was fixed in JDK 9 by commit: http://hg.openjdk.java.net/jdk9/jdk9/jdk/rev/fb598740935a

**Comment by fniephaus** [comment]
Thanks!
