### ISSUE TITLE
Allow `mx native-unittest` to use `mx native-image`

### ISSUE THREAD

**Issue by bobmcwhirter** [oracle/graal#1565]
As I'm unit-testing stuff in `substratevm/` it can occasionally be surprising that `mx native-unittest` within that directory sometimes ends up using an old/out-of-date `native-image` binary from `vm/`.

If I remove `vm/mxbuild/` then it obviously will rebuild a native-image of `native-image` itself prior to building and executing the test. But that's also... not fast.

If instead it could prefer to use `mx native-image` from within `substratevm/`, it would help with productivity.

**Comment by olpaw** [comment]
The way we build everything needed to make `mx native-image` or `mx native-unittest` has change a lot. No manual deleting of vm/mxbuild should be necessary anymore. Please reopen if this is still relevant.
