### ISSUE TITLE
Appstore does not accept apps using private CF API's

### ISSUE THREAD

**Issue by johanvos** [oracle/graal#1568]
When submitting an app build using Graal to the AppStore, the app was rejected and the following message was received:

`The app references non-public symbols in App: __CFCopyServerVersionDictionary, __CFCopySystemVersionDictionary. 
`
This is due to _CFCopyServerVersionDictionary and _CFCopySystemVersionDictionary in com.oracle.svm.core.posix.headers.darwin. 
Those functions are used in com.oracle.svm.core.posix.darwin.DarwinSystemPropertiesSupport.osVersionValue and they should probably be replaced with "non-internal" functions.

**Comment by johanvos** [comment]
FWIW, by removing these 2 methods, we could upload an app to the AppStore without issues.

**Comment by olpaw** [comment]
@johanvos is this still relevant? Can we close the issue?

**Comment by johanvos** [comment]
It is still relevant. I'll create a PR for this.

**Comment by johanvos** [comment]
The approach for getting the system os version in GraalVM is not allowed by Apple (at least, apps that use it can not be uploaded to the App Store (ios) or Apple Store (mac)) because it is using an internal CoreFoundation API. 

The approach taken in OpenJDK is valid for Apple though: https://github.com/openjdk/jdk/blob/master/src/java.base/macosx/native/libjava/java_props_macosx.c#L237 -- but I don't see an easy way to replace the Java code in https://github.com/oracle/graal/blob/494b82ea2fd423b0132a13a7660bc1e500378b35/substratevm/src/com.oracle.svm.core.posix/src/com/oracle/svm/core/posix/darwin/DarwinSystemPropertiesSupport.java#L73 with the approach used in the hotspot code
