### ISSUE TITLE
Unable to call NetworkInterface#isPointToPoint

### ISSUE THREAD

**Issue by eurrow** [oracle/graal#1574]
Carrying on from issue #1522, there is another method on NetworkInterface that isn't implemented.

`Exception in thread "main" java.lang.UnsatisfiedLinkError: java.net.NetworkInterface.isP2P0(Ljava/lang/String;I)Z [symbol: Java_java_net_NetworkInterface_isP2P0 or Java_java_net_NetworkInterface_isP2P0__Ljava_lang_String_2I]
        at com.oracle.svm.jni.access.JNINativeLinkage.getOrFindEntryPoint(JNINativeLinkage.java:145)
        at com.oracle.svm.jni.JNIGeneratedMethodSupport.nativeCallAddress(JNIGeneratedMethodSupport.java:57)
        at java.net.NetworkInterface.isP2P0(NetworkInterface.java)
        at java.net.NetworkInterface.isPointToPoint(NetworkInterface.java:426)
        at TestIsP2p.main(TestIsP2p.java:12)`

Taking the fix in #1522 as in example, attached is a patch that works for us.

[isp2p-patch.txt](https://github.com/oracle/graal/files/3473387/isp2p-patch.txt)

**Comment by bobmcwhirter** [comment]
Hiya--

I'll put together a PR based on this for ya.

**Comment by bobmcwhirter** [comment]
Oracle will probably want to be sure you've sign the OCA:

https://www.oracle.com/technetwork/community/oca-486395.html

And if you can let me know what email address you use to sign the OCA, that'd be good.

You can mail me directly at bmcwhirt <at> redhat.com.

Or if you prefer to submit this as a PR directly, that's awesome. I'm just trying to help out.

**Comment by eurrow** [comment]
Doesn't #1575 just need to be merged and then both #1575 and #1574 can be closed?
