### ISSUE TITLE
[svm] Add org.graalvm.collections to blacklist?

### ISSUE THREAD

**Issue by fniephaus** [oracle/graal#1577]
@eregon recently mentioned that the methods of `BigInteger` are automatically considered boundaries in SVM due to a blacklist.

Now I am wondering... should this blacklist:
https://github.com/oracle/graal/blob/ddd736a2e8b23e1aabd08599a523f847ffc1e97d/substratevm/src/com.oracle.svm.truffle/src/com/oracle/svm/truffle/TruffleFeature.java#L604-L622

be extended with the classes from [`org.graalvm.collections`](https://github.com/oracle/graal/tree/ddd736a2e8b23e1aabd08599a523f847ffc1e97d/sdk/src/org.graalvm.collections/src/org/graalvm/collections)?

**Comment by christianwimmer** [comment]
No, if anything we want to reduce the size of the blacklist. Truffle languages are only maintainable if all `@TruffleBoundary` are explicit. The blacklist for native image generation only hides possible problems that you also have when running the partial evaluation on the Java HotSpot VM (which does not have any kind of blacklist and will therefore partially evaluate into these methods).
