### ISSUE TITLE
[sl] Use of @ReportPolymorphism unclear in SLStatementNode

### ISSUE THREAD

**Issue by fniephaus** [oracle/graal#1579]
`SLStatementNode` uses [`@ReportPolymorphism`](https://github.com/oracle/graal/blob/acb994d5fbd2dd92a50941b786b87b65c7b20e01/truffle/src/com.oracle.truffle.sl/src/com/oracle/truffle/sl/nodes/SLStatementNode.java#L64), but it's not clear to me why. As simplelanguage is a reference language, maybe the use of `@ReportPolymorphism` deserves an explanation in the comments? [`ReportingPolymorphism.md`](https://github.com/oracle/graal/blob/master/truffle/docs/splitting/ReportingPolymorphism.md) could also be linked.

**Comment by boris-spas** [comment]
Agreed, I'll take it on.

**Comment by fniephaus** [comment]
@boris-spas thanks! Just realized that `ReportingPolymorphism.md` already includes [an explanation](https://github.com/oracle/graal/blob/acb994d5fbd2dd92a50941b786b87b65c7b20e01/truffle/docs/splitting/ReportingPolymorphism.md#automated-reporting-of-polymorphic-specializations). Maybe it just needs to be linked?

**Comment by boris-spas** [comment]
Should be a one sentence explanation + link.

**Comment by fniephaus** [comment]
And we should probably merged https://github.com/oracle/graal/pull/1580. 😉

**Comment by chumer** [comment]
@boris-spas  I don't think SLStatementNode should use ReportPolymorphism. That is against selectively using it, that we generally recommend.

**Comment by boris-spas** [comment]
Sure, I plan to put it in a couple of reasonable places and document it better.

**Comment by boris-spas** [comment]
Tracking internally as Issue GR-20924.

**Comment by fniephaus** [comment]
https://github.com/oracle/graal/commit/c9ec1e9542ffd2a09a4fdf9702605529079a7584#diff-edced7f79cef978b51ff44cf05ec22cc is the corresponding commit.

**Comment by boris-spas** [comment]
^ yes! Thanks! Forgot to give context.
