### ISSUE TITLE
Array.set(..) behaves differently

### ISSUE THREAD

**Issue by martinlippert** [oracle/graal#1585]
`java.lang.reflect.Array.set(Object array, int index, Object value)` behaves differently in SVM than in a regular JDK.

Pass in `null` as the value:
-> JDK: works fine
-> SVM: throws NPE

The JavaDoc says that this could throw a NPE, but it isn't exactly clear whether this refers to the `array` or the `value` param. Looks like JDK and SVM interpret this differently. Not sure who is right, but maybe it would make sense to align them.

**Comment by bobmcwhirter** [comment]
Reproduced. I’m working on a fix.
