### ISSUE TITLE
[native-image] Throws the same error regarding: -H:IncludeResourceBundles=javax.servlet.LocalStrings even though supplied

### ISSUE THREAD

**Issue by neomatrix369** [oracle/graal#1589]
Even though I have supplied the necessary config args during the building of the native image, I get an error message asking me to perform the same step again.

Command:

```
OPTIONS="${2:-} --no-fallback --allow-incomplete-classpath --enable-all-security-services --enable-http --enable-https --enable-url-protocols"
OPTIONS="${OPTIONS} -H:ReflectionConfigurationFiles=META-INF/native-image/reflect-config.json"
OPTIONS="${OPTIONS} -H:DynamicProxyConfigurationFiles=META-INF/native-image/proxy-config.json"
OPTIONS="${OPTIONS} -H:ResourceConfigurationFiles=META-INF/native-image/resource-config.json"
OPTIONS="${OPTIONS} -H:JNIConfigurationFiles=META-INF/native-image/jni-config.json"
OPTIONS="${OPTIONS} --initialize-at-build-time=org.eclipse.jetty.util.thread.TryExecutor"
OPTIONS="${OPTIONS} -H:IncludeResourceBundles=javax.servlet.http.LocalStrings"
OPTIONS="${OPTIONS} -H:IncludeResources='.*/index.*html$'"

native-image ${OPTIONS} -jar ${JARFILE} ${IMAGE_NAME}
```

Resources config:

```
less META-INF/native-image/resource-config.json

{
  "resources":[
    {"pattern":"META-INF/services/org.eclipse.jetty.http.HttpFieldPreEncoder"},
    {"pattern":"META-INF/services/org.eclipse.jetty.websocket.api.extensions.Extension"},
    {"pattern":"javax/servlet/LocalStrings.properties"},
    {"pattern":"javax/servlet/http/LocalStrings.properties"},
    {"pattern":"org/eclipse/jetty/http/encoding.properties"},
    {"pattern":"org/eclipse/jetty/http/mime.properties"},
    {"pattern":"org/eclipse/jetty/version/build.properties"},
    {"pattern":"org/slf4j/impl/StaticLoggerBinder.class"},
    {"pattern":"public"}
  ]
}
```

Error message thrown:

```java
Exception in thread "main" java.lang.ExceptionInInitializerError
	at com.oracle.svm.core.hub.ClassInitializationInfo.initialize(ClassInitializationInfo.java:290)
	at java.lang.Class.ensureInitialized(DynamicHub.java:451)
	at com.oracle.svm.core.hub.ClassInitializationInfo.initialize(ClassInitializationInfo.java:235)
	at java.lang.Class.ensureInitialized(DynamicHub.java:451)
	at com.oracle.svm.core.hub.ClassInitializationInfo.initialize(ClassInitializationInfo.java:235)
	at java.lang.Class.ensureInitialized(DynamicHub.java:451)
	at io.javalin.Javalin.<init>(Javalin.java:52)
	at io.javalin.Javalin.create(Javalin.java:84)
	at server.Main.main(Main.java:15)
Caused by: java.util.MissingResourceException: Resource bundle not found javax.servlet.LocalStrings. Register the resource bundle using the option -H:IncludeResourceBundles=javax.servlet.LocalStrings.
	at com.oracle.svm.core.jdk.LocalizationSupport.getCached(LocalizationSupport.java:103)
	at java.util.ResourceBundle.getBundle(ResourceBundle.java:49)
	at javax.servlet.GenericServlet.<clinit>(GenericServlet.java:95)
	at com.oracle.svm.core.hub.ClassInitializationInfo.invokeClassInitializer(ClassInitializationInfo.java:350)
	at com.oracle.svm.core.hub.ClassInitializationInfo.initialize(ClassInitializationInfo.java:270)
	... 8 more
```

Maybe the error message needs to be a different one, possible I'm not supplying it with a Resource bundle via some other `-H:...` option, but then I need to be told about it.

Maybe I'm not doing something as well, but so far I have been using the error message as an indicator of next steps.

If this is not sufficient I'll try to provide a sample project where this can be reproduced. Let me know if that is required.

**Comment by neomatrix369** [comment]
Is there any relation to this issue and https://github.com/oracle/graal/issues/911

**Comment by neomatrix369** [comment]
I just rechecked the error message again and I think it is doing the right thing by suggesting the below:

```
-H:IncludeResourceBundles=javax.servlet.LocalStrings
```

since I had only added

```
-H:IncludeResourceBundles=javax.servlet.http.LocalStrings
```

Closing issue, very sorry for the bother. 😞

**Comment by swap5813** [comment]
Hi Mani,

I have a created a websocket application and was trying to build the native image using GraalVM native-image. I am also getting the same error  "Resource bundle not found javax.servlet.LocalStrings". 

I tried both approaches through commandline and through config.json file, but nothing is working me. I am working on windows 10 platform.

**Comment by neomatrix369** [comment]
@swap5813 just saw the message in case you tried to reach out earlier and didn't hear from me, my apologies - I'll try to take a look at this and get back to you, have you tried to use the tracing agent while building your image, have a look at this script, it does it for you https://github.com/neomatrix369/awesome-ai-ml-dl/blob/master/examples/deepnetts/builder.sh

Although you may have to customise it to your own app (although it should work in most instances with minor changes), have a read of the code, it's very simple to change, as you now have a template and ready to use the script from CLI.

Do let me know if this helps, while I look into your query

**Comment by swap5813** [comment]
Hi Mani,

Thanks for replying to me. My issue is fixed, For me providing the bundle names works in resource-config.json as follows 

{
  "bundles": [
    {"name":"javax.servlet.LocalStrings"},
    {"name": "javax.servlet.http.LocalStrings"}
  ]
}

I am new to GraalVM and wanted to building native image of my websocket application build using Javalin. Its working now :)

Thanks for prompt reply

cheers

**Comment by neomatrix369** [comment]
> Hi Mani,
> 
> Thanks for replying to me. My issue is fixed, For me providing the bundle names works in resource-config.json as follows
> 
> {
> "bundles": [
> {"name":"javax.servlet.LocalStrings"},
> {"name": "javax.servlet.http.LocalStrings"}
> ]
> }
> 
> Your post really helped me to fixed this issue . I am new to GraalVM and wanted to building native image of my websocket application build using Javalin. Its working now.
> 
> Thanks for prompt reply
> 
> cheers

So the solution was to add the `javax.servlet...` entries to `resource-config.json`, could you please check using the shell script if it automatically gets generated (should hopefully be picked up by the tracing agent) - this will be useful, as we could lean more on it automatically being generated as opposed to manually adding them via CLI or `.json` config.
