### ISSUE TITLE
Add support for `Frame#isIllegal()`

### ISSUE THREAD

**Issue by fniephaus** [oracle/graal#1594]
There are checks for all supported frame slot kinds except for the illegal kind. Maybe it makes sense to add  `Frame#isIllegal()`?

/cc @chumer

**Comment by woess** [comment]
Could you explain a bit what you would like to use it for? I suppose you'd like to check whether the frame slot has been set?

**Comment by fniephaus** [comment]
@woess yes, that's correct. getValue() can return a default value (if provided at creation time of frame descriptor). Frame.isIllegal() would allow a specialization that returns a default value.

**Comment by woess** [comment]
Note that frame slots start out with `frame.isObject(slot) == true` and `frame.getObject(slot) == getFrameDescriptor().getDefaultValue()` (regardless of FrameSlotKind), as if there was an implicit `setObject(slot, getDefaultValue())` at the beginning. So that can be used to check whether the frame slot was set to anything else than the default value.

**Comment by fniephaus** [comment]
Interesting, but doesn't this mean that if the default value is read first, the slot will have an Object kind and thus never specializes? If Frame.isObject(slot) is true, the generic specialization is activated and all others are excluded, right?

**Comment by woess** [comment]
If the slot is read before the first assignment, then yes, you will hit the Object specialization. But you don't actually have to exclude the other specializations, you can also allow more than one active specialization in your read node, e.g. isInt + isObject. Or if you don't want to return the default value but e.g. throw an error in that case, you could use `isObject() && getObject() == getDefaultValue()` as a guard.

**Comment by fniephaus** [comment]
Thanks! I think this can be closed for now.
