### ISSUE TITLE
[native-image] IncludeResources doesn't include resources from JRE JARs

### ISSUE THREAD

**Issue by nhoughto** [oracle/graal#1606]
It appears the `IncludeResources` option doesn't quite live upto its name, at least in `19.1.1` that i'm testing on. 

The doco says it will include any resources that is on the classpath during native-image build, but whilst trying to include some properties files from the JRE `resources.jar`, specifically in package `com/sun/org/apache/xml/internal/serializer` the files are not included unless I copy them from a JRE JAR to my local project.

Argument in question:
`-H:IncludeResources=com/sun/org/apache/xml/internal/serializer/output_xml.properties`

As mentioned if I copy the file from its original location to a matching path in my local project ir works, so I'd guess its some interaction between the native-image process and the JRE bootstrap / classloading mechanism 🤷‍♂

**Comment by nhoughto** [comment]
Testing with `-H:Log=registerResource:` on to see what is included btw :+1:

**Comment by olpaw** [comment]
Release reopen is you can still reproduce this with the latest release version.
