### ISSUE TITLE
[native-image] ThreadLocalRandom seeder is never reinitialized

### ISSUE THREAD

**Issue by wburns** [oracle/graal#1614]
The ThreadLocalRandom class has a static final field of seeder and probeGenerator. The class should be reinitialized at runtime to reset the values properly. Otherwise the numbers generated will always be the same from run to run of the same native application.

It is possible to work around this by adding a Feature that sets the class for reinitialization:

```
public class TestFeature implements Feature {
    @Override
    public void beforeAnalysis(BeforeAnalysisAccess access) {
        ImageSingletons.lookup(RuntimeClassInitializationSupport.class).rerunInitialization(ThreadLocalRandom.class,
                "Need to reinitialize this class");
    }
}
```

Since this is a standard JDK class it should be handled directly and not require a custom Feature.

**Comment by cstancu** [comment]
Thanks, I will make this a default.

**Comment by cstancu** [comment]
Fixed by https://github.com/oracle/graal/commit/39edb2661d8d4931bf364a2513c4e4c9bb75b6f5.
