### ISSUE TITLE
Reflection-config.json fails to parse

### ISSUE THREAD

**Issue by toriacht** [oracle/graal#1616]
When running a native build while including `-H:ResourceConfigurationFiles=` the build fails with the following issue

```
Error: Error parsing resource configuration in /project/classes/reflection.json:
first level of document must be an object
Verify that the configuration matches the schema described in the -H:PrintFlags=+ output for option ResourceConfigurationFiles.
com.oracle.svm.core.util.UserError$UserException: Error parsing resource configuration in /project/classes/reflection.json:
first level of document must be an object
Verify that the configuration matches the schema described in the -H:PrintFlags=+ output for option ResourceConfigurationFiles.
	at com.oracle.svm.core.util.UserError.abort(UserError.java:65)
```
File is of the format

```
[
  {
    "name" : "path.of.3pp.Class",
    "allDeclaredConstructors" : true,
    "allPublicConstructors" : true,
    "allDeclaredMethods" : true,
    "allPublicMethods" : true,
    "allDeclaredFields" : true,
    "allPublicFields" : true
  }
]

```
[Reproducer available here](https://github.com/toriacht/graalvm-issue-reproducer/)

**Comment by bobmcwhirter** [comment]
Starting with a [ makes it an array not an object. Dunno if that’s the problem.

**Comment by toriacht** [comment]
@bobmcwhirter yep, i thought that too but it then complains about not understanding the keys. The file, as far as i can see is as per the [Graal documentation](https://github.com/oracle/graal/blob/master/substratevm/REFLECTION.md) and the [Quarkus documentation](https://quarkus.io/guides/writing-native-applications-tips#registering-for-reflection)

**Comment by peter-hofer** [comment]
@toriacht You're using option `ResourceConfigurationFiles`, but are trying to provide a reflection configuration file for which you need to use option `ReflectionConfigurationFiles`. Resource configuration files and reflection configuration files have different purposes and a different structure. I'm closing the issue, feel free to reopen if this is a misunderstanding or wrong in our documentation.

**Comment by toriacht** [comment]
@peter-hofer  my bad! My apologies for wasting your time.. I must have copied/pasted from incorrect section of the `Quarkus` docs.
