### ISSUE TITLE
Some microbenchmarks for Jsoniter Scala show slowdown

### ISSUE THREAD

**Issue by thomaswue** [oracle/graal#1617]
The benchmark results at https://jmh.morethan.io/?sources=https://plokhotnyuk.github.io/jsoniter-scala/graalvmee19.json,https://plokhotnyuk.github.io/jsoniter-scala/zingjdk11.json show GraalVM EE substantially ahead in 752 out of 966 cases. We should investigate the ones where GraalVM is not fastest.

**Comment by plokhotnyuk** [comment]
It wasn't a fair match: Zing is based on JDK 11 and uses C4 GC which is designed for min. latency.

I'm waiting for GraalVM EE based on JDK 11 and some feedback from Azul about how to tune it for max throughput.

**Comment by thomaswue** [comment]
It is possible that some of the differences are library changes from JDK8 to JDK11. We will nevertheless investigate. 

I believe Zing's marketing material doesn't mention an expected substantial drop in throughput.

**Comment by plokhotnyuk** [comment]
The run of the benchmark was for the following commit: https://github.com/plokhotnyuk/jsoniter-scala/tree/50b7efddfd3973b30eef987351e71c2b3ea67c38

Bellow is the script that was used for running;
```sh
sbt -java-home /usr/lib/jvm/graalvm-ee-19 -no-colors -Dsbt.supershell=false -Dmacro.settings=print-codecs clean 'jsoniter-scala-benchmark/jmh:run -p size=128 -prof gc -rf json -rff graalvmee19.json .*' 2>&1 | tee graalvmee19.txt
sbt -java-home /usr/lib/jvm/graalvm-ce-19 -no-colors -Dsbt.supershell=false -Dmacro.settings=print-codecs clean 'jsoniter-scala-benchmark/jmh:run -p size=128 -prof gc -rf json -rff graalvmce19.json .*' 2>&1 | tee graalvmce19.txt
sbt -java-home /usr/lib/jvm/openjdk-11 -no-colors -Dsbt.supershell=false -Dmacro.settings=print-codecs clean 'jsoniter-scala-benchmark/jmh:run -jvm /usr/lib/jvm/openjdk-12/bin/java -p size=128 -prof gc -rf json -rff openjdk12.json .*' 2>&1 | tee openjdk12.txt
sbt -java-home /usr/lib/jvm/openjdk-11 -no-colors -Dsbt.supershell=false -Dmacro.settings=print-codecs clean 'jsoniter-scala-benchmark/jmh:run -p size=128 -prof gc -rf json -rff openjdk11.json .*' 2>&1 | tee openjdk11.txt
sbt -java-home /usr/lib/jvm/openjdk-8 -no-colors -Dsbt.supershell=false -Dmacro.settings=print-codecs clean 'jsoniter-scala-benchmark/jmh:run -p size=128 -prof gc -rf json -rff openjdk8.json .*' 2>&1 | tee openjdk8.txt
sbt -java-home /opt/zing/zing-jdk11 -no-colors -Dsbt.supershell=false -Dmacro.settings=print-codecs clean 'jsoniter-scala-benchmark/jmh:run -wi 10 -p size=128 -prof gc -rf json -rff zingjdk11.json .*' 2>&1 | tee zingjdk11.txt
sbt -java-home /usr/lib/jvm/openj9-jdk-11 -no-colors -Dsbt.supershell=false -Dmacro.settings=print-codecs clean 'jsoniter-scala-benchmark/jmh:run -wi 10 -p size=128 -prof gc -rf json -rff openj9jdk11.json .*' 2>&1 | tee openj9jdk11.txt
```

The environment used for this run: 
`Intel® Core™ i7-7700 CPU @ 3.6GHz (max 4.2GHz), RAM 16Gb DDR4-2400, Ubuntu 18.04`

Comparison of results from Open JDK 8/11/13 + Hotspot C2, OpenJDK 13 + Graal, and GraalVM CE/EE is available [here](https://plokhotnyuk.github.io/jsoniter-scala/) as usually

**Comment by plokhotnyuk** [comment]
Closing as outdated... most noticeable performance regressions are fixed in a separated issue: https://github.com/oracle/graal/issues/2203

**Comment by thomaswue** [comment]
OK, thank you!
