### ISSUE TITLE
JVMCIError when running graal unittest with jdk14 master.

### ISSUE THREAD

**Issue by XiaohongGong** [oracle/graal#1620]
Running graal unittest with jdk14 master failed due to a JVMCIError:

    org.graalvm.compiler.core.test.tutorial.GraalTutorial#testIntrinsicIntegerReverseBytes
    jdk.vm.ci.common.JVMCIError: expected type markOop but VM field oopDesc::_mark is of type markWord
    at jdk.internal.vm.ci/jdk.vm.ci.hotspot.HotSpotVMConfigAccess.getField(HotSpotVMConfigAccess.java:319)
    at jdk.internal.vm.ci/jdk.vm.ci.hotspot.HotSpotVMConfigAccess.getFieldOffset0(HotSpotVMConfigAccess.java:165)
    at jdk.internal.vm.ci/jdk.vm.ci.hotspot.HotSpotVMConfigAccess.getFieldOffset(HotSpotVMConfigAccess.java:147)
    at jdk.internal.vm.compiler/org.graalvm.compiler.hotspot.GraalHotSpotVMConfig.<init>(GraalHotSpotVMConfig.java:211)
    at jdk.internal.vm.compiler/org.graalvm.compiler.hotspot.HotSpotGraalRuntime.<init>(HotSpotGraalRuntime.java:144)
    ....

  This is caused by the jdk patch:

    commit f4d90f1ce52c2fabe0ff213bac92d2144f970385
    Author: stefank <unknown>
    Date: Tue Aug 6 10:48:21 2019 +0200
    8229258: Rework markOop and markOopDesc into a simpler mark word value carrier
    Reviewed-by: rkennke, coleenp, kbarrett, dcubed

  This patch changes the field type from `markOop` and `markOopDesc` to `markWord`, most if which are the hotspot vm configs. We should also update the vm configs in `GraalHotSpotVMConfig.java` to the right type.
  
   But currently the jdk14 is not released, and the graal project only contains `jdk8/jdk11/jdk12/jdk13` version. And if we use jdk14 master to run the graal unittest, it actually uses the jdk13 graal version. So I'm not sure how to fix this issue, because the jdk patch is only applied on the jdk14 master.
   Here is the command:
   
    mx -v unittest GraalTutorial

   Actually it is:

    /home/xiagon01/code/build-fastdebug/images/jdk/bin/java -server -XX:+UnlockExperimentalVMOptions -XX:+EnableJVMCI --module-path=/home/xiagon01/code/graal/sdk/mxbuild/dists/jdk14/graal-sdk.jar:/home/xiagon01/code/graal/truffle/mxbuild/dists/jdk14/truffle-api.jar --upgrade-module-path=/home/xiagon01/code/graal/compiler/mxbuild/dists/jdk13/graal.jar:/home/xiagon01/code/graal/compiler/mxbuild/dists/jdk13/graal-management.jar ...  -JUnitEagerStackTrace org.graalvm.compiler.core.test.tutorial.GraalTutorial

**Comment by dougxc** [comment]
I've opened a PR that should fix this: https://github.com/oracle/graal/pull/1621

**Comment by XiaohongGong** [comment]
Thank you!
