### ISSUE TITLE
[SVM] Confused about heap object layout

### ISSUE THREAD

**Issue by kelthuzadx** [oracle/graal#1624]
I'm confused about runtime object layout. Let's say I have a structure which holds fields' type and name:
```java
class ST{
    LinkedHashMap<String,Integer> nfields;// <Field name, Field type, 1 for int, 2 for short,etc>
}
```
And I have a byte array of an object:
```
[0x2,0x32,.....0x32]
```
In my experiment, the order of fields in the source code is not correspond to byte array. And if we don't use a field later, it would not become the part of instance data.So how can I read raw value from byte array for a specific field if I have such a structure and a byte array?

Here is my experiment result:
--------------------------------------------------------------------------------------------
```java
class Object{
	private int k = 15;
	private int p = 17;
	Object obj1 = xx;
	Object obj2 = xx;
	void foo(){
		use k,p,obj1,obj2
	}
}
```
```
[0x70][0x70][0x35][0x0][0x0][0x0][0x0][0x0][0xfffffff0][0xffffff93][0xffffff95][0x0][0x0][0x0][0x0][0x0][0xf][0x0][0x0][0x0][0x11][0x0][0x0][0x0]
```
-------------------------------------------------------------------------------------------
```java
class Object{
	private int k = 15;
	private char c = 5; //append new field, but the size of instance does not change 
	private int p = 17;
	Object obj1 = xx;
	Object obj2 = xx;
	void foo(){
		use k,p,c,obj1,obj2
	}
}
```
```
[0x70][0x70][0x35][0x0][0x0][0x0][0x0][0x0][0xfffffff0][0xffffffd3][0xffffff8d][0x0][0x0][0x0][0x0][0x0][0xf][0x0][0x0][0x0][0x11][0x0][0x0][0x0]
```
---------------------------------------------------------------------------------------------
```java
class Object{
	private int k = 15;
	private int p = 17;
	Object obj1 = xx;
	Object obj2 = xx;
	void foo(){
		use nothing
	}
}
```
```
[0x70][0x70][0x35][0x0][0x0][0x0][0x0][0x0][0xfffffff0][0x43][0xffffff9b][0x0][0x0][0x0][0x0][0x0]
```

**Comment by christianwimmer** [comment]
I'm not sure what exactly you are trying to do. But in Java, you can never treat an object like a byte array, or overwrite the contents of an object with raw data from a byte array.

Not reserving memory for fields that are never used in your application is an important optimization of Native Image. The static analysis tracks the usage of each field individually to enable this optimization.
