### ISSUE TITLE
[native-image] Can't access user home directory on Windows

### ISSUE THREAD

**Issue by isaichkindanila** [oracle/graal#1630]
Platform: Windows 10
Version: 19.2.0

Property `user.name` is always "somebody" and `user.home` is always "C:\Users\somebody"

**Comment by cstancu** [comment]
Those seem to be hardcoded values: https://github.com/oracle/graal/blob/master/substratevm/src/com.oracle.svm.core.windows/src/com/oracle/svm/core/windows/WindowsSystemPropertiesSupport.java#L47.

**Comment by eginez** [comment]
fixed by https://github.com/oracle/graal/commit/924c8d07c613a7465e8b77abd33a666f16f5666f

**Comment by borkdude** [comment]
FWIW, this is still manifesting in 19.3.0.2, but since this wasn't mentioned in the release notes, it's probably not in there.
