### ISSUE TITLE
Don't try to write symbol map when building a relocatable file only

### ISSUE THREAD

**Issue by johanvos** [oracle/graal#1636]
When NativeImageOptions.ExitAfterRelocatableImageWrite is set, there is no linker returned and there should be no linker invocation. 
When building an executable, this works fine. However, this ImageKind will now also introduce a main function in the relocatable file. This can be avoided by setting ImageKind to SharedLibrary, but this currently causes a NullPointerException as SharedLibraryViaCCBootImage will use the linker to generate a symbol map.

**Comment by olpaw** [comment]
This issue is fixed long since.
