### ISSUE TITLE
[Truffle] NPE on findTopScopes returning empty iterable (e.g., set)

### ISSUE THREAD

**Issue by mrcalvin** [oracle/graal#1641]
The docs on [`findTopScopes`](https://www.graalvm.org/truffle/javadoc/com/oracle/truffle/api/TruffleLanguage.html#findTopScopes-C-) say:

> The language may return an empty iterable to indicate no scopes.

However, my `findTopScope` implementation, for testing purposes, with

```
protected Iterable<Scope> findTopScopes(Context context) {
    	return Collections.emptySet();
}
```
runs into an NPE (or stumbles on a non-null assertion, when on) in [`com.oracle.truffle.polyglot.PolyglotLanguageContext.asValue(Object guestValue)`](https://github.com/oracle/graal/blob/ff753e55112e2f006586f6a5ed25269731c46243/truffle/src/com.oracle.truffle.polyglot/src/com/oracle/truffle/polyglot/PolyglotLanguageContext.java#L743)

at

```
PolyglotValue cache = lazy.valueCache.get(receiver.getClass());
```

`guestValue` = `receiver` happen to become `null` in this case, leading to the NPE in `receiver.getClass()`.

**Comment by mrcalvin** [comment]
I should add that this is observed running `19.1.0`, however, I don't see any differences in the post-19.1 sources.

**Comment by boris-spas** [comment]
Tracking internally as Issue GR-20925.

**Comment by hamzaGhaissi** [comment]
Closing this, since GR-20925 is closed.
