### ISSUE TITLE
Truffle 19.2.0 can no longer be shadowed

### ISSUE THREAD

**Issue by fcurts** [oracle/graal#1644]
We use `https://github.com/johnrengelman/shadow` to shadow all our dependencies, including Truffle. This is essential to avoid version conflicts. Under the hood, the shadow plugin uses ASM to remap class names in class files, e.g., `com.oracle.truffle.api.impl.Accessor` -> `com.mycompany.thirdparty.truffle.api.impl.Accessor`.

Shadowing Truffle worked fine until 19.1.0, but no longer works in 19.2.0. The reason is that `com.oracle.truffle.api.impl.Accessor` now uses a string switch on class names in its constructor, which translates to a switch on string hash codes in bytecode. While ASM correctly maps string constants containing class names, it doesn't update the hash codes used in string switches.

Even if this could be fixed in ASM, the fix would take forever to land in the shadow plugin, which isn't updated frequently and still uses ASM 7.0 beta. Hence I hope this can be fixed pragmatically in Truffle by not using a string switch in the constructor of class `Accessor`.

Maven's shadow plugin likely has the same problem, as Gradle's shadow plugin is a port of the Maven plugin.

Related ASM issue: https://gitlab.ow2.org/asm/asm/issues/317882

**Comment by fcurts** [comment]
Any takers? ASM closed this as "won't fix", and it's easily fixed in Truffle.

**Comment by boris-spas** [comment]
Tracking internally as Issue GR-20927.

**Comment by fcurts** [comment]
Any chance to get this fixed? We just spent a day diagnosing and fixing a Truffle version conflict. With people moving from Nashorn to Graal.js, this will become more common.

**Comment by chumer** [comment]
Can you maybe provide steps to reproduce? Or propose a fix? Happy to integrate if it is just a minor fix.
We don't care much about shadowing ourselves, as we want people to use GraalVM style class loader isolation instead. With the class loader isolation it is guaranteed there is no conflict with the host application.

**Comment by fcurts** [comment]
@chumer The proposed fix is to move back from string switch to if-cascade in the constructor of `com.oracle.truffle.api.impl.Accessor` (line 845 as of Truffle 20.2).

The problem should be reproducible as follows:
1. Create a fat Jar with shadowed Truffle classes for any Truffle language.
2. Run any Truffle program.
3. An exception occurs (I can check which one if necessary).

**Comment by chumer** [comment]
PR is progress and targeted for 21.2

**Comment by fcurts** [comment]
@tzezula Do you still need a reproducer from me, or do you already have one?

**Comment by tzezula** [comment]
Fixed for 21.2
https://github.com/oracle/graal/commit/a4c1350500d6e56461079ed21e8928672bab4e2f
