### ISSUE TITLE
graalvm-ce-19.2.0 src.zip source code not include org.graalvm sources

### ISSUE THREAD

**Issue by pavelmorozov** [oracle/graal#1653]
Hello!

I have imports like
```
import org.graalvm.polyglot.Context;
import org.graalvm.polyglot.Value;
import org.graalvm.polyglot.HostAccess;
```
But I cannot open sources from Eclipse IDE, so I looked to **src.zip** and it not contains **org.graalvm** package. I would like it to be available.

**Comment by gilles-duboscq** [comment]
Those sources are in `graalvm-ce-19.2.0/jre/lib/boot/graal-sdk.src.zip` you should be able to associate them with `graal-sdk.jar` in Eclipse.

**Comment by pavelmorozov** [comment]
@gilles-duboscq  thank you! This works and solved my problem. I not close the issue as soon as I not know where sources better to place. May be it have sense to make a note on manuals about sources location in case it is not in src.zip . Feel free to close ticket if this works as intended.

**Comment by ezzarghili** [comment]
These should be the available source packages:
```
jre/lib/boot/graal-sdk.src.zip
jre/lib/graalvm/launcher-common.src.zip
jre/lib/jvmci/jvmci-api.src.zip
jre/lib/jvmci/jvmci-hotspot.src.zip
jre/lib/jvmci-services.src.zip
jre/lib/truffle/locator.src.zip
jre/lib/truffle/truffle-api.src.zip
jre/lib/truffle/truffle-dsl-processor.src.zip
jre/lib/truffle/truffle-tck.src.zip
src.zip
```
@pavelmorozov please close the issue if this answers you question otherwise let us know if you need assistance.

**Comment by pavelmorozov** [comment]
Thank you
