### ISSUE TITLE
Can I assign access rights to each context member separately?

### ISSUE THREAD

**Issue by pavlomorozov** [oracle/graal#1654]
Hello

Here the question. I have a Context with few objects (members) in it like 

```
        try (Context jsContext = 
                Context.newBuilder("js").build()) {
            JSONObject jsonObject = new JSONObject(); //org.json.simple
            MyPOJO myPOJO = new MyPOJO();
            jsContext.getBindings("js").putMember("jsonObject", jsonObject);
            jsContext.getBindings("js").putMember("myPOJO", myPOJO);
            jsContext.eval("js", script);
```
Now as soon as I created **MyPOJO** class I can use `org.graalvm.polyglot.HostAccess.Export` annotation on it's methods I want to expose in JS code - this is great and I like this a lot as some of methods should be accessible from host java only.

But what to do with **JSONObject**? It is comes from external library and I would like to expose all its methods in java script code and be able to update data from java script and after it executed have this updates in Java variable. What I found possible is to use builder like:
`Context jsContext = Context.newBuilder("js").allowHostAccess(HostAccess.ALL).build();`
Though this solution makes all methods from MyPOJO class exposed to java script too. **Can I assign access rights to each context member separately? Like HostAccess.EXPLICIT for MyPOJO and HostAccess.ALL JSONObject? What is the other ways to achieve this?**

Now I see few options but really not sure are them the best of what is available. First option is to use HostAccess.EXPLICIT and instead of passing jsonObject to JS code I will pass string (jsonObject.toString()). In JS I will use it as JS object. Then after JS code done I will parse JSON String to JSONObject. Other option could be to write a wrapper class over JSONObject and annotate all methods with HostAccess.Export. This seems like a bit overhead. I also thought to use org.graalvm.polyglot.proxy.Proxy interface but as I see in JavaDoc it seems like it assumed to pass data **from** guest code:
"Proxy interfaces allow to mimic guest language objects, arrays, executables, primitives and native objects in Graal languages...", and as so it will not help in my case.

**Comment by matneu** [comment]
Hi Pavlo,

> Can I assign access rights to each context member separately? Like HostAccess.EXPLICIT for MyPOJO and HostAccess.ALL JSONObject

Simple answer: no. `HostAccess.ALL` implies full access to reflection and would render any other restriction ineffective.

> What is the other ways to achieve this?

My recommendation for your case would be to stick with `HostAccess.EXPLICIT` and implement a wrapper class for JSONObject. This way you can selectively expose the functionality actually required by the guest. Beyond that, the wrapper class can also include logic to restrict the kind of modification the guest code can make to the JSON object.

**Comment by chumer** [comment]
Wrapper is one solution, but requires the allocation of the wrapper object.
If you have vetted the JsonObject class to be safe yourself, and you repeat doing this every time you upgrade that dependency you can individually export methods using a custom host access policy.

E.g. you can do:
```
HostAccess customPolicy = HostAccess.newBuilder(HostAccess.EXPLICIT).allowAccess(JsonObject.class.getMethod("exposedMethod")).build();
```

Please close if that helps.

**Comment by pavlomorozov** [comment]
Hello.

I think both solutions can help. Thank you.
