### ISSUE TITLE
Error: Unable to compile C-ABI query code. Make sure GCC toolchain is installed on your system.

### ISSUE THREAD

**Issue by mikkelchristensen** [oracle/graal#1655]
Hi, I am trying to build a binary file for REQ (https://gitlab.pasteur.fr/GIPhy/REQ) for use in combination with JolyTree (https://gitlab.pasteur.fr/GIPhy/JolyTree).

According to the REQ manual, native-image should be able to do this using

```shell
javac REQ.java 
native-image -H:Name=REQ -H:-MultiThreaded REQ
rm REQ.class
```
I have installed 
graalvm-ce-linux-amd64-19.2.0.tar.gz
llvm-toolchain-installable-linux-amd64-19.2.0.jar
native-image-installable-svm-linux-amd64-19.2.0.jar
https://github.com/oracle/graal/archive/vm-19.2.0.tar.gz

After changing path
export PATH=../graalvm-ce-19.2.0/bin/
I am able to run native-image, but I keep getting this (error) message:

:~/REQ/src$ native-image -H:Name=REQ -H:-MultiThreaded REQ
Shutdown Server(pid: 64534, port: 34641)
Build on Server(pid: 73102, port: 36947)*

[REQ:73102]    classlist:   1,222.76 ms
[REQ:73102]        (cap):     205.46 ms
[REQ:73102]        setup:     448.40 ms

Error: Unable to compile C-ABI query code. Make sure GCC toolchain is installed on your system.
Error: Use -H:+ReportExceptionStackTraces to print stacktrace of underlying exception
Error: Image build request failed with exit status 1

Anyone able to help me out?

Best wishes, Mikkel

**Comment by cstancu** [comment]
@themanojshukla thanks for the input! As described in the [docs](https://www.graalvm.org/docs/reference-manual/aot-compilation/) the `native-image` prerequisites are "glibc-devel, zlib-devel (header files for the C library and zlib) and gcc".  @mikkelchristensen please reopen if you still have problems having installed all the prerequisites.

**Comment by mystdeim** [comment]
I have the same problem on ubuntu 16.04 x64. I installed zlib but it doesn't help
