### ISSUE TITLE
Locally built GraalVM doesn't recognize --no-server option

### ISSUE THREAD

**Issue by MarianMacik** [oracle/graal#1659]
Hi guys,

I have built a GraalVM locally using this command:
`mx --env ce build` in the `graal/vm` directory.

The build was successful and now I have 2 directories with built GraalVM:
`graal/vm/mxbuild/linux-amd64/GRAALVM_CE` - without the native-image executable
`graal/vm/mxbuild/linux-amd64/GRAALVM_CE_NI_NIL_STAGE1` - with the native-image executable

But for some reason, I cannot build a native image. I am getting:

`Error: Unrecognized option: --no-server`

Can you pleas advise what might be the issue?

Thanks.

**Comment by MarianMacik** [comment]
Issue solved by building it using `ce-complete` env file:

`mx --env ce-complete build`

Then the working GraalVM resides in the `latest_graalvm` link as usual.

Or you can use your own env file and tailor it to your needs.

**Comment by ansalond** [comment]
Hi @MarianMacik, I'm happy to read that you quickly found a solution.
Few clarifications:

1. as you noticed, GraalVM CE does not include Native Image by default. If you want to include it, you can run `$ mx --env ce --exclude-components=llp build`. This adds the `native-image` and `native-image-configure` executables, plus the `native-image-agent` library.

2. if you are only interested in Native Image, you can build just that: `$ mx --dy /substratevm --force-bash-launchers=gu,polyglot --skip-libraries=polyglot graalvm-show`. As you wrote, you can store this configuration in your own env file.

3. if you are unsure about what you are about to build, run `mx [...] graalvm-show`. Example:
```
$ mx --dy /substratevm --force-bash-launchers=gu,polyglot --skip-libraries=polyglot graalvm-show
GraalVM distribution: GRAALVM_UNKNOWN
Version: 19.3.0-dev
Config name: None
Components:
 - GraalVM license files ('gvm', /.)
 - GraalVM Locator ('loc', /truffle)
 - Truffle ('tfl', /truffle)
 - Component installer ('gu', /installer)
 - SubstrateVM ('svm', /svm)
 - Native Image licence files ('nil', /svm)
 - Native Image ('ni', /svm)
 - TRegex ('rgx', /regex)
 - Polyglot Native API ('polynative', /polyglot)
 - Truffle NFI ('nfi', /nfi)
 - Truffle Macro ('tflm', /truffle)
 - SubstrateVM LLVM ('svml', /svm)
 - Native Image JUnit ('nju', /junit)
 - Graal SDK ('sdk', /graalvm)
 - GraalVM compiler ('cmp', /graal)
Launchers:
 - gu (bash)
 - native-image-configure (native)
 - native-image (native)
 - polyglot (bash)
Libraries:
 - libnative-image-agent.so
 - libpolyglot.so (skipped)
Installables:
 - REGEX_INSTALLABLE
 - NATIVE_IMAGE_INSTALLABLE_SVM
 - NFI_INSTALLABLE
No standalone
```

4. Stage 1 distributions (named `*STAGE1`) are an intermediate result of the build process. They are not supposed to be used and they do not contain native images, but they should work. The Native Image build server is available only when `native-image` is compiled as a Native Image. In Stage 1, it's a normal Java program which does not recognize the `--no-server` option. If you don't pass this option, it should work.

I hope this helps you.
