### ISSUE TITLE
[native-install] Install fails in 19.2.0 with gu

### ISSUE THREAD

**Issue by fdelbrayelle** [oracle/graal#1665]
I failed to install "native-install" in v19.2.0. I got the following message :

```
➜  ~ $GRAALVM_HOME/bin/gu install native-image
Skipping ULN EE channels, no username provided.
Downloading: Component catalog from www.graalvm.org
Downloading: Component catalog from www.graalvm.org
Error: Unknown component: native-image
```

OS informations:

```
➜  ~ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.3 LTS"
➜  ~ uname -a
Linux zenbook 5.0.17-050017-generic #201905161857 SMP Thu May 16 18:59:46 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

I've solved the issue doing this :

`➜  ~ $GRAALVM_HOME/bin/gu install --file native-image-installable-svm-svmee-linux-amd64-19.2.0.jar`

After downloading the Early Adopter JAR here https://www.oracle.com/technetwork/graalvm/downloads/index.html

It seems there is a problem when trying to install native-install without the jar from the catalog. Am I wrong?

**Comment by olyagpl** [comment]
Hi Francois, 
Staring from 19.2 version, if you are using GraalVM Enterprise, you can only install R and llvm-toolchain by name from the catalog. The other components are available from the OTN page, and can be installed from a manually downloaded file, using `--file` or `-L` (`--local-file`) option like you did. Please see our [release notes](https://www.graalvm.org/docs/release-notes/19_2/).

**Comment by fdelbrayelle** [comment]
Hi Olga,
Thank you for your answer!

**Comment by olyagpl** [comment]
Follow our future releases https://www.graalvm.org/docs/release-notes/version-roadmap.
Thanks for trying!
