### ISSUE TITLE
[Question] how to point -H:ReflectionConfigurationFiles to a file inside the jar?

### ISSUE THREAD

**Issue by cvgaviao** [oracle/graal#1666]
I'm trying to build a native image using oracle/graalvm-ce:19.2.0

Inside my jar I have a native-image.properties with:
```
Args=-H:+ReportUnsupportedElementsAtRuntime \
 --allow-incomplete-classpath \
--initialize-at-build-time=ch.qos.logback.classic.BasicConfigurator \
-H:ReflectionConfigurationFiles=jar:graalvm_config.json
```
native-image is complaining about not finding the graalvm_config.json.

so, is there a way to tell native-image to get this file from the same jar?

**Comment by olpaw** [comment]
Use **`-H:ReflectionConfigurationResources`** instead.
```
-H:ReflectionConfigurationFiles=...          One or several (comma-separated) paths to JSON files that specify which program elements should be made available via                                               reflection.
-H:ReflectionConfigurationResources=...      Resources describing program elements to be made available for reflection
```
E.g. if you have `graalvm_config.json` in the root folder of your jar you would use `-H:ReflectionConfigurationResources=graalvm_config.json`.

**Comment by cvgaviao** [comment]
@olpaw, thanks
