### ISSUE TITLE
Multiple ReturnNodes will be generated when a function has multiple return branches.

### ISSUE THREAD

**Issue by XiaohongGong** [oracle/graal#1667]
For a function like this:

    public static int func(int[] arr, int n, int m) {
        int var = arr[n];
        if (var % 2 == 0) {
            if (arr[m] % 2 == 0)
                var += arr[n + 1];
            else
                var += arr[n + 2];
        } else {
            if (arr[m] % 2 != 0)
                var += arr[n + 3];
            else
                var += arr[n + 4];
        }
        return var;
    }

Graal will generate four return blocks like this:

      ......
      0x0000ffff6bf6d0a0: and   x0, x4, #0xffffffff
      0x0000ffff6bf6d0a4: orr   x2, xzr, #0x10
      0x0000ffff6bf6d0a8: add   x0, x2, x0, lsl #2
      0x0000ffff6bf6d0ac: ldr   w0, [x1,x0]
      0x0000ffff6bf6d0b0: add   w0, w0, w5
      0x0000ffff6bf6d0b4: ldp   x29, x30, [sp,#32]
      0x0000ffff6bf6d0b8: add   sp, sp, #0x30
      0x0000ffff6bf6d0bc: ldr   x8, [x28,#264]
      0x0000ffff6bf6d0c0: ldr   wzr, [x8]       ;   {poll_return}
      0x0000ffff6bf6d0c4: ret
      0x0000ffff6bf6d0c8: ands  w4, w4, #0x1
      0x0000ffff6bf6d0cc: b.eq  0x0000ffff6bf6d138
      0x0000ffff6bf6d0d0: add   w4, w2, #0x2
      0x0000ffff6bf6d0d4: cmp   w0, w4
      0x0000ffff6bf6d0d8: b.ls  0x0000ffff6bf6d1ac
      0x0000ffff6bf6d0dc: and   x0, x4, #0xffffffff
      0x0000ffff6bf6d0e0: orr   x2, xzr, #0x10
      0x0000ffff6bf6d0e4: add   x0, x2, x0, lsl #2
      0x0000ffff6bf6d0e8: ldr   w0, [x1,x0]
      0x0000ffff6bf6d0ec: add   w0, w0, w5
      0x0000ffff6bf6d0f0: ldp   x29, x30, [sp,#32]
      0x0000ffff6bf6d0f4: add   sp, sp, #0x30
      0x0000ffff6bf6d0f8: ldr   x8, [x28,#264]
      0x0000ffff6bf6d0fc: ldr   wzr, [x8]       ;   {poll_return}
      0x0000ffff6bf6d100: ret
      0x0000ffff6bf6d104: add   w4, w2, #0x4
      0x0000ffff6bf6d108: cmp   w0, w4
      0x0000ffff6bf6d10c: b.ls  0x0000ffff6bf6d194
      0x0000ffff6bf6d110: and   x0, x4, #0xffffffff
      0x0000ffff6bf6d114: orr   x2, xzr, #0x10
      0x0000ffff6bf6d118: add   x0, x2, x0, lsl #2
      0x0000ffff6bf6d11c: ldr   w0, [x1,x0]
      0x0000ffff6bf6d120: add   w0, w0, w5
      0x0000ffff6bf6d124: ldp   x29, x30, [sp,#32]
      0x0000ffff6bf6d128: add   sp, sp, #0x30
      0x0000ffff6bf6d12c: ldr   x8, [x28,#264]
      0x0000ffff6bf6d130: ldr   wzr, [x8]       ;   {poll_return}
      0x0000ffff6bf6d134: ret
      0x0000ffff6bf6d138: add   w4, w2, #0x1
      0x0000ffff6bf6d13c: cmp   w0, w4
      0x0000ffff6bf6d140: b.ls  0x0000ffff6bf6d1a0
      0x0000ffff6bf6d144: and   x0, x4, #0xffffffff
      0x0000ffff6bf6d148: orr   x2, xzr, #0x10
      0x0000ffff6bf6d14c: add   x0, x2, x0, lsl #2
      0x0000ffff6bf6d150: ldr   w0, [x1,x0]
      0x0000ffff6bf6d154: add   w0, w0, w5
      0x0000ffff6bf6d158: ldp   x29, x30, [sp,#32]
      0x0000ffff6bf6d15c: add   sp, sp, #0x30
      0x0000ffff6bf6d160: ldr   x8, [x28,#264]
      0x0000ffff6bf6d164: ldr   wzr, [x8]       ;   {poll_return}
      0x0000ffff6bf6d168: ret

This is due to the following codes in `simply` method of `AbstractMergeNode`:

        ......  
        } else if (currentNext instanceof ReturnNode) {
            ReturnNode returnNode = (ReturnNode) currentNext;
            if (anchored().isNotEmpty() || returnNode.getMemoryMap() != null) {
                return;
            }
            List<PhiNode> phis = phis().snapshot();
            for (PhiNode phi : phis) {
                for (Node usage : phi.usages()) {
                    if (usage != returnNode && !(usage instanceof FrameState)) {
                        return;
                    }
                }
            }
            ValuePhiNode returnValuePhi = returnNode.result() == null || !isPhiAtMerge(returnNode.result()) ? null : (ValuePhiNode) returnNode.result();
            List<EndNode> endNodes = forwardEnds().snapshot();
            for (EndNode end : endNodes) {
                try (DebugCloseable position = returnNode.withNodeSourcePosition()) {
                    ReturnNode newReturn = graph().add(new ReturnNode(returnValuePhi == null ? returnNode.result() : returnValuePhi.valueAt(end)));
                    if (tool != null) {
                        tool.addToWorkList(end.predecessor());
                    }
                    end.replaceAtPredecessor(newReturn);
                }
            }
            GraphUtil.killCFG(this);
            for (EndNode end : endNodes) {
                end.safeDelete();
            }
            for (PhiNode phi : phis) {
                if (tool.allUsagesAvailable() && phi.isAlive() && phi.hasNoUsages()) {
                    GraphUtil.killWithUnusedFloatingInputs(phi);
                }
            }
        }

Deleting the merge and phi nodes and creating multiple return nodes will actually delete the jump instructions between the return block and its predecessors. But this will also increase the whole code size. Compared to the C2 compiler, it generates only one return block. So I'm wondering how to balance the performance and the code size. Does it have any other concerns about this optimization? Thank you!

**Comment by dougxc** [comment]
Is this causing measurable performance issues? We could disable the above optimization on platforms where it is shown to cause a performance issue.

**Comment by XiaohongGong** [comment]
> Is this causing measurable performance issues? We could disable the above optimization on platforms where it is shown to cause a performance issue.

Sorry, I didn't test the performance yet. I just pay attention to the code size that there are multiple blocks to do the return job if there are several return branches in a function. I'm just curious about the main reason to do this optimization. Thank you!
This is the return codes:

    ldp   x29, x30, [sp,#32]
    add   sp, sp, #0x30
    ldr   x8, [x28,#264]
    ldr   wzr, [x8]       ;   {poll_return}
    ret

**Comment by dougxc** [comment]
I think the main reason is just to simplify working with the graph (less merges to spend useless work on). However, with the introduction of thread local safepoints (which is what I assume your code snippet is showing), it may shift the tradeoffs. @gilles-duboscq may have more thoughts on this.

**Comment by thomaswue** [comment]
The merge may create spill for the register allocator. We could merge the returns again on the low level graph. But I would expect no measurable performance impact either way.

**Comment by gilles-duboscq** [comment]
We could do that late if necessary: there can only be one phi for the return value and that's anyway going to the same register. In theory we could hide this from the reg alloc and emit the first return as a the real code and any further return be a jump to the first one.

**Comment by XiaohongGong** [comment]
> We could merge the returns again on the low level graph.

Do you mean applying the optimization on backend after register allocator?

**Comment by XiaohongGong** [comment]
Can we consider a specified optimization to merge the same blocks? And at the same time we should try to not add too much jump instructions. 
Like the following code pattern:

    0x0000ffff8a660a8c: b.ne 0x0000ffff8a660ab4
    ...
    0x0000ffff8a660ab0: b    0x0000ffff8a660c7c
    0x0000ffff8a660ab4: mov  w10, w4
    0x0000ffff8a660ab8: b    0x0000ffff8a660a94  
    0x0000ffff8a660abc: cmp  w4, w5
    0x0000ffff8a660ac0: b.ne 0x0000ffff8a660acc 
    0x0000ffff8a660ac4: mov  w10, w4
    0x0000ffff8a660ac8: b    0x0000ffff8a660a94

There are two same blocks in the above codes:

    0x0000ffff8a660ac4: mov  w10, w4
    0x0000ffff8a660ac8: b    0x0000ffff8a660a94

Because the first part is a single block that is unconditionally jumped to, we can merge it with the second one. So the codes can be optimized to:

    0x0000ffff8a660a8c: b.ne 0x0000ffff8a660ac4
    ...
    0x0000ffff8a660ab0: b    0x0000ffff8a660c7c
    0x0000ffff8a660abc: cmp  w4, w5
    0x0000ffff8a660ac0: b.ne 0x0000ffff8a660acc 
    0x0000ffff8a660ac4: mov  w10, w4
    0x0000ffff8a660ac8: b    0x0000ffff8a660a94

**Comment by XiaohongGong** [comment]
> The merge may create spill for the register allocator.

I think it's ok for the return part, because the register for return is always the same one (r0) whenever the returns are merged or not.

**Comment by fernando-valdez** [comment]
@XiaohongGong can you please confirm if this issue is present in the latest snapshot of GraalVM?

**Comment by fernando-valdez** [comment]
Closing this ticket due to the lack of response. Please feel free to reopen it of the problem persists
