### ISSUE TITLE
native image on windows Link fail with  Java_sun_security_ec_ECDH KeyAgreement_deriveKey

### ISSUE THREAD

**Issue by lilili87222** [oracle/graal#1672]
windows 7   ,graal ce 19.2 release, windows sdk 7.1 installed success before run native image. 

C:\myapp>..\graalvm-ce-19.2.0\bin\native-image --allow-incomplete-classpath --i
nitialize-at-build-time=net.appuploader.macho --initialize-at-build-time=net.app
uploader.service --initialize-at-build-time=net.appuploader.cmdparser  --report-
unsupported-elements-at-runtime -H:+PrintClassInitialization --no-fallback --ena
ble-url-protocols --enable-all-security-services -H:+ReportExceptionStackTraces
 -H:EnableURLProtocols=http -H:ReflectionConfigurationFiles=config\reflect-confi
g.json -H:ResourceConfigurationFiles=config\resource-config.json -Djava.net.pref
erIPv4Stack=true -jar myapp.jar
[myapp:3480]    classlist:   3,212.62 ms
[myapp:3480]        (cap):     936.97 ms
[myapp:3480]        setup:   2,164.89 ms
[myapp:3480]   (typeflow):  18,946.01 ms
[myapp:3480]    (objects):  12,759.20 ms
[myapp:3480]   (features):     949.38 ms
[myapp:3480]     analysis:  33,412.06 ms
Printing initializer configuration to C:\myapp\reports\initializer_configuratio
n_20190911_132422.txt
Printing initializer dependencies to C:\myapp\reports\initializer_dependencies_
20190911_132422.dot
Printing 653 classes that are considered as safe for build-time initialization t
o C:\myapp\reports\safe_classes_20190911_132422.txt
Printing 6912 classes of type BUILD_TIME to C:\myapp\reports\build_time_classes
_20190911_132422.txt
Printing 43 classes of type RERUN to C:\myapp\reports\rerun_classes_20190911_13
2422.txt
Printing 94 classes of type RUN_TIME to C:\myapp\reports\run_time_classes_20190
911_132422.txt
[myapp:3480]     (clinit):     664.35 ms
[myapp:3480]     universe:   1,552.93 ms
[myapp:3480]      (parse):   3,544.15 ms
[myapp:3480]     (inline):   5,877.26 ms
[myapp:3480]    (compile):  30,818.10 ms
[myapp:3480]      compile:  41,785.80 ms
[myapp:3480]        image:   2,577.27 ms
[myapp:3480]        write:     207.67 ms
Fatal error: java.lang.RuntimeException: java.lang.RuntimeException: host C comp
iler or linker does not seem to work: java.lang.RuntimeException: returned 2

Running command: CL /MD /Zi /PDBSTRIPPED /FeC:\myapp\myapp.exe C:\Users\admin\
AppData\Local\Temp\SVM-6605961731096857632\myapp.obj C:\graalvm-ce-19.2.0\jre\l
ib\svm\clibraries\windows-amd64\ffi.lib C:\graalvm-ce-19.2.0\jre\lib\nio.lib C:\
graalvm-ce-19.2.0\jre\lib\net.lib C:\graalvm-ce-19.2.0\jre\lib\java.lib C:\graal
vm-ce-19.2.0\jre\lib\svm\clibraries\windows-amd64\libchelper.lib C:\graalvm-ce-1
9.2.0\jre\lib\svm\clibraries\windows-amd64\strictmath.lib C:\graalvm-ce-19.2.0\j
re\lib\zip.lib C:\graalvm-ce-19.2.0\jre\lib\svm\clibraries\windows-amd64\jvm.lib
 C:\graalvm-ce-19.2.0\jre\lib\svm\clibraries\windows-amd64\ffi.lib C:\graalvm-ce
-19.2.0\jre\lib\nio.lib C:\graalvm-ce-19.2.0\jre\lib\net.lib C:\graalvm-ce-19.2.
0\jre\lib\java.lib C:\graalvm-ce-19.2.0\jre\lib\svm\clibraries\windows-amd64\lib
chelper.lib C:\graalvm-ce-19.2.0\jre\lib\svm\clibraries\windows-amd64\strictmath
.lib C:\graalvm-ce-19.2.0\jre\lib\zip.lib C:\graalvm-ce-19.2.0\jre\lib\svm\clibr
aries\windows-amd64\jvm.lib /link /INCREMENTAL:NO /NODEFAULTLIB:LIBCMT /NODEFAUL
TLIB:OLDNAMES /LIBPATH:C:\graalvm-ce-19.2.0\jre\lib /LIBPATH:C:\graalvm-ce-19.2.
0\jre\lib\svm\clibraries\windows-amd64 advapi32.lib ws2_32.lib secur32.lib iphlp
api.lib

Microsoft (R) C/C++ Optimizing Compiler Version 16.00.30319.01 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

cl : Command line warning D9002 : ignoring unknown option '/PDBSTRIPPED'
Microsoft (R) Incremental Linker Version 10.00.30319.01
Copyright (C) Microsoft Corporation.  All rights reserved.

/debug
/out:C:\myapp\myapp.exe
/INCREMENTAL:NO /NODEFAULTLIB:LIBCMT /NODEFAULTLIB:OLDNAMES
/LIBPATH:C:\graalvm-ce-19.2.0\jre\lib
/LIBPATH:C:\graalvm-ce-19.2.0\jre\lib\svm\clibraries\windows-amd64
advapi32.lib
ws2_32.lib
secur32.lib
iphlpapi.lib
C:\Users\admin\AppData\Local\Temp\SVM-6605961731096857632\myapp.obj
C:\graalvm-ce-19.2.0\jre\lib\svm\clibraries\windows-amd64\ffi.lib
C:\graalvm-ce-19.2.0\jre\lib\nio.lib
C:\graalvm-ce-19.2.0\jre\lib\net.lib
C:\graalvm-ce-19.2.0\jre\lib\java.lib
C:\graalvm-ce-19.2.0\jre\lib\svm\clibraries\windows-amd64\libchelper.lib
C:\graalvm-ce-19.2.0\jre\lib\svm\clibraries\windows-amd64\strictmath.lib
C:\graalvm-ce-19.2.0\jre\lib\zip.lib
C:\graalvm-ce-19.2.0\jre\lib\svm\clibraries\windows-amd64\jvm.lib
C:\graalvm-ce-19.2.0\jre\lib\svm\clibraries\windows-amd64\ffi.lib
C:\graalvm-ce-19.2.0\jre\lib\nio.lib
C:\graalvm-ce-19.2.0\jre\lib\net.lib
C:\graalvm-ce-19.2.0\jre\lib\java.lib
C:\graalvm-ce-19.2.0\jre\lib\svm\clibraries\windows-amd64\libchelper.lib
C:\graalvm-ce-19.2.0\jre\lib\svm\clibraries\windows-amd64\strictmath.lib
C:\graalvm-ce-19.2.0\jre\lib\zip.lib
C:\graalvm-ce-19.2.0\jre\lib\svm\clibraries\windows-amd64\jvm.lib
   Creating library C:\myapp\myapp.lib and object C:\myapp\myapp.exp
myapp.obj : error LNK2001: unresolved external symbol Java_sun_security_ec_ECDH
KeyAgreement_deriveKey
myapp.obj : error LNK2001: unresolved external symbol Java_sun_security_ec_ECDS
ASignature_signDigest
myapp.obj : error LNK2001: unresolved external symbol Java_sun_security_ec_ECDS
ASignature_verifySignedDigest
myapp.obj : error LNK2001: unresolved external symbol Java_sun_security_ec_ECKe
yPairGenerator_generateECKeyPair
myapp.obj : error LNK2001: unresolved external symbol Java_sun_security_ec_ECKe
yPairGenerator_isCurveSupported
myapp.obj : error LNK2001: unresolved external symbol Java_sun_security_mscapi_
KeyStore_loadKeysOrCertificateChains
myapp.obj : error LNK2001: unresolved external symbol Java_sun_security_mscapi_
PRNG_generateSeed
myapp.obj : error LNK2001: unresolved external symbol Java_sun_security_mscapi_
RSAKeyPairGenerator_generateRSAKeyPair
myapp.obj : error LNK2001: unresolved external symbol Java_sun_security_mscapi_
RSASignature_generatePublicKeyBlob
myapp.obj : error LNK2001: unresolved external symbol Java_sun_security_mscapi_
RSASignature_importPublicKey
myapp.obj : error LNK2001: unresolved external symbol Java_sun_security_smartca
rdio_PCSC_SCardEstablishContext
C:\myapp\myapp.exe : fatal error LNK1120: 11 unresolved externals

        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)

        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstruct
orAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingC
onstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.
java:593)
        at java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1005)
        at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.j
ava:461)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeIma
geGeneratorRunner.java:310)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGen
eratorRunner.java:448)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGene
ratorRunner.java:113)
Caused by: java.lang.RuntimeException: host C compiler or linker does not seem t
o work: java.lang.RuntimeException: returned 2

Running command: CL /MD /Zi /PDBSTRIPPED /FeC:\myapp\myapp.exe C:\Users\admin\
AppData\Local\Temp\SVM-6605961731096857632\myapp.obj C:\graalvm-ce-19.2.0\jre\l
ib\svm\clibraries\windows-amd64\ffi.lib C:\graalvm-ce-19.2.0\jre\lib\nio.lib C:\
graalvm-ce-19.2.0\jre\lib\net.lib C:\graalvm-ce-19.2.0\jre\lib\java.lib C:\graal
vm-ce-19.2.0\jre\lib\svm\clibraries\windows-amd64\libchelper.lib C:\graalvm-ce-1
9.2.0\jre\lib\svm\clibraries\windows-amd64\strictmath.lib C:\graalvm-ce-19.2.0\j
re\lib\zip.lib C:\graalvm-ce-19.2.0\jre\lib\svm\clibraries\windows-amd64\jvm.lib
 C:\graalvm-ce-19.2.0\jre\lib\svm\clibraries\windows-amd64\ffi.lib C:\graalvm-ce
-19.2.0\jre\lib\nio.lib C:\graalvm-ce-19.2.0\jre\lib\net.lib C:\graalvm-ce-19.2.
0\jre\lib\java.lib C:\graalvm-ce-19.2.0\jre\lib\svm\clibraries\windows-amd64\lib
chelper.lib C:\graalvm-ce-19.2.0\jre\lib\svm\clibraries\windows-amd64\strictmath
.lib C:\graalvm-ce-19.2.0\jre\lib\zip.lib C:\graalvm-ce-19.2.0\jre\lib\svm\clibr
aries\windows-amd64\jvm.lib /link /INCREMENTAL:NO /NODEFAULTLIB:LIBCMT /NODEFAUL
TLIB:OLDNAMES /LIBPATH:C:\graalvm-ce-19.2.0\jre\lib /LIBPATH:C:\graalvm-ce-19.2.
0\jre\lib\svm\clibraries\windows-amd64 advapi32.lib ws2_32.lib secur32.lib iphlp
api.lib

Microsoft (R) C/C++ Optimizing Compiler Version 16.00.30319.01 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

cl : Command line warning D9002 : ignoring unknown option '/PDBSTRIPPED'
Microsoft (R) Incremental Linker Version 10.00.30319.01
Copyright (C) Microsoft Corporation.  All rights reserved.

/debug
/out:C:\myapp\myapp.exe
/INCREMENTAL:NO /NODEFAULTLIB:LIBCMT /NODEFAULTLIB:OLDNAMES
/LIBPATH:C:\graalvm-ce-19.2.0\jre\lib
/LIBPATH:C:\graalvm-ce-19.2.0\jre\lib\svm\clibraries\windows-amd64
advapi32.lib
ws2_32.lib
secur32.lib
iphlpapi.lib
C:\Users\admin\AppData\Local\Temp\SVM-6605961731096857632\myapp.obj
C:\graalvm-ce-19.2.0\jre\lib\svm\clibraries\windows-amd64\ffi.lib
C:\graalvm-ce-19.2.0\jre\lib\nio.lib
C:\graalvm-ce-19.2.0\jre\lib\net.lib
C:\graalvm-ce-19.2.0\jre\lib\java.lib
C:\graalvm-ce-19.2.0\jre\lib\svm\clibraries\windows-amd64\libchelper.lib
C:\graalvm-ce-19.2.0\jre\lib\svm\clibraries\windows-amd64\strictmath.lib
C:\graalvm-ce-19.2.0\jre\lib\zip.lib
C:\graalvm-ce-19.2.0\jre\lib\svm\clibraries\windows-amd64\jvm.lib
C:\graalvm-ce-19.2.0\jre\lib\svm\clibraries\windows-amd64\ffi.lib
C:\graalvm-ce-19.2.0\jre\lib\nio.lib
C:\graalvm-ce-19.2.0\jre\lib\net.lib
C:\graalvm-ce-19.2.0\jre\lib\java.lib
C:\graalvm-ce-19.2.0\jre\lib\svm\clibraries\windows-amd64\libchelper.lib
C:\graalvm-ce-19.2.0\jre\lib\svm\clibraries\windows-amd64\strictmath.lib
C:\graalvm-ce-19.2.0\jre\lib\zip.lib
C:\graalvm-ce-19.2.0\jre\lib\svm\clibraries\windows-amd64\jvm.lib
   Creating library C:\myapp\myapp.lib and object C:\myapp\myapp.exp
myapp.obj : error LNK2001: unresolved external symbol Java_sun_security_ec_ECDH
KeyAgreement_deriveKey
myapp.obj : error LNK2001: unresolved external symbol Java_sun_security_ec_ECDS
ASignature_signDigest
myapp.obj : error LNK2001: unresolved external symbol Java_sun_security_ec_ECDS
ASignature_verifySignedDigest
myapp.obj : error LNK2001: unresolved external symbol Java_sun_security_ec_ECKe
yPairGenerator_generateECKeyPair
myapp.obj : error LNK2001: unresolved external symbol Java_sun_security_ec_ECKe
yPairGenerator_isCurveSupported
myapp.obj : error LNK2001: unresolved external symbol Java_sun_security_mscapi_
KeyStore_loadKeysOrCertificateChains
myapp.obj : error LNK2001: unresolved external symbol Java_sun_security_mscapi_
PRNG_generateSeed
myapp.obj : error LNK2001: unresolved external symbol Java_sun_security_mscapi_
RSAKeyPairGenerator_generateRSAKeyPair
myapp.obj : error LNK2001: unresolved external symbol Java_sun_security_mscapi_
RSASignature_generatePublicKeyBlob
myapp.obj : error LNK2001: unresolved external symbol Java_sun_security_mscapi_
RSASignature_importPublicKey
myapp.obj : error LNK2001: unresolved external symbol Java_sun_security_smartca
rdio_PCSC_SCardEstablishContext
C:\myapp\myapp.exe : fatal error LNK1120: 11 unresolved externals

        at com.oracle.svm.hosted.image.NativeBootImageViaCC.write(NativeBootImag
eViaCC.java:350)
        at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator
.java:657)
        at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGe
nerator.java:444)
        at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoin
Task.java:1386)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java
:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.ja
va:157)
Error: Image build request failed with exit status 1

**Comment by wirdman** [comment]
having similar issue (windows 7 ,graal ce 19.2 release, windows sdk 7.1) seems to point to the --enable-https flag from my point of view: 
```bob-1.0-SNAPSHOT-jar-with-dependencies.obj : error LNK2001: unresolved external
symbol Java_sun_security_ec_ECDHKeyAgreement_deriveKey
bob-1.0-SNAPSHOT-jar-with-dependencies.obj : error LNK2001: unresolved external
symbol Java_sun_security_ec_ECDSASignature_signDigest
bob-1.0-SNAPSHOT-jar-with-dependencies.obj : error LNK2001: unresolved external
symbol Java_sun_security_ec_ECDSASignature_verifySignedDigest
bob-1.0-SNAPSHOT-jar-with-dependencies.obj : error LNK2001: unresolved external
symbol Java_sun_security_ec_ECKeyPairGenerator_generateECKeyPair
bob-1.0-SNAPSHOT-jar-with-dependencies.obj : error LNK2001: unresolved external
symbol Java_sun_security_ec_ECKeyPairGenerator_isCurveSupported
bob-1.0-SNAPSHOT-jar-with-dependencies.obj : error LNK2001: unresolved external
symbol Java_sun_security_krb5_Config_getWindowsDirectory
bob-1.0-SNAPSHOT-jar-with-dependencies.obj : error LNK2001: unresolved external
symbol Java_sun_security_krb5_SCDynamicStoreConfig_getKerberosConfig
bob-1.0-SNAPSHOT-jar-with-dependencies.obj : error LNK2001: unresolved external
symbol Java_sun_security_mscapi_KeyStore_loadKeysOrCertificateChains
bob-1.0-SNAPSHOT-jar-with-dependencies.obj : error LNK2001: unresolved external
symbol Java_sun_security_mscapi_PRNG_generateSeed
bob-1.0-SNAPSHOT-jar-with-dependencies.obj : error LNK2001: unresolved external
symbol Java_sun_security_mscapi_RSAKeyPairGenerator_generateRSAKeyPair
bob-1.0-SNAPSHOT-jar-with-dependencies.obj : error LNK2001: unresolved external
symbol Java_sun_security_mscapi_RSASignature_generatePublicKeyBlob
bob-1.0-SNAPSHOT-jar-with-dependencies.obj : error LNK2001: unresolved external
symbol Java_sun_security_mscapi_RSASignature_importPublicKey
bob-1.0-SNAPSHOT-jar-with-dependencies.obj : error LNK2001: unresolved external
symbol Java_sun_security_smartcardio_PCSC_SCardEstablishContext
C:\Users\gigi\Downloads\bob-1.0-SNAPSHOT-jar-with-dependencies.exe : fatal error
 LNK1120: 13 unresolved externals

        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)

        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstruct
orAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingC
onstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.
java:593)
        at java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1005)
        at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.j
ava:461)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeIma
geGeneratorRunner.java:310)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGen
eratorRunner.java:448)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGene
ratorRunner.java:113)
Caused by: java.lang.RuntimeException: host C compiler or linker does not seem t
o work: java.lang.RuntimeException: returned 2```

**Comment by lilili87222** [comment]
19.2.1 not fixed this bug

**Comment by retrogradeorbit** [comment]
I'm getting this bug too. --enable-https or -H:EnableURLProtocols=https triggers it. Looks like the `CL` command generated does not include the `jre\lib\sunec.lib` file in its link list (possibly others needed too), resulting in unresolved symbol errors at link time. Mac and linux this compile option works but requires `libsunec.so` or `libsunec.dylib` to be present at run time. There is a `jre\lib\sunec.dll` to go with the `jre\lib\sunec.lib` but not sure if that is needed. Some of the other symbols appear in `jre\bin\sunmscapi.dll` and `jre\bin\j2pcsc.dll`. But I couldn't find the *krb5* symbols (kerberos support I assume) anywhere. I have no idea if it's possible to pass extra compile/link arguments to native-image.

**Comment by cstancu** [comment]
This issue is not relevant anymore. `sunec` is now statically linked when code that uses is reachable.
