### ISSUE TITLE
[native-image] Checking for dynamic class-loading capabilities without explicitly checking for SubstrateVM

### ISSUE THREAD

**Issue by roookeee** [oracle/graal#1679]
I am working on a library that wants to make use of dynamic class loading to improve performance. If dynamic class loading is not possible (like in SubstrateVM) it should fallback to normal, unoptimized routines. The check if dynamic class loading is possible should be done in a `static` context as outlined in [this](https://github.com/roookeee/datus/blob/8e20e77d500a345bae6642e0f3a5d33b36f8acfc/src/main/java/com/github/roookeee/datus/shared/LambdaHelper.java#L201) sample file (to anyone interested what I am doing in there: I am reloading simple `Function` chaining classes in different classloaders to monomorphize the callsites to make stuff like `andThen` inlineable)

I don't want to explicitly check for SubstrateVM as whitelisting / blacklisting means that new VMs / VM-names get deoptimized by default which is why I currently take the approach of catching any `Throwable` in the static block.

Is this an acceptable / supported approach to detect this? Does SubstrateVM support catching these compilation related exceptions and is it safe to do in the future? There are no JDK facilities that I know of to check whether dynamic class loading is possible or not but I also know that it's frowned upon to catch `Throwable` which I have to to include SubstrateVMs `VMError`

**Comment by christianwimmer** [comment]
You can check whether you are running in a native image or not using the methods in https://github.com/oracle/graal/blob/master/sdk/src/org.graalvm.nativeimage/src/org/graalvm/nativeimage/ImageInfo.java (or the system properties defined there if you cannot add a dependency to the API).

**Comment by christianwimmer** [comment]
Without an explicit check, your only option is to rely on side effects like exceptions. That can never be 100% reliable, so I don't want to recommend it. But of course it works.

btw, you can never catch a `VMError` from Substrate VM because that class is not even an exception class.

**Comment by roookeee** [comment]
Thanks - as I don't have a reliable way I will in fact opt for checking SubstrateVMs system properties. Better stable than wonky :)
