### ISSUE TITLE
Set heap size parameter for native-image generated shared-library

### ISSUE THREAD

**Issue by lizhanhui** [oracle/graal#1686]
We are making best of native-image to generate shared libraries out of Java assets.  The generated library works well so far. But I do not find a way to tune SVM heap for this use case in the [reference doc](https://www.graalvm.org/docs/reference-manual/aot-compilation/). Aka, how can I specify -Xmx, -Xms, -Xmn for native-image generated shared library?

**Comment by olpaw** [comment]
@lizhanhui you are right. ATM we do not have a nice (API) way to specify default -Xmx, -Xms, -Xmn at image build time. Until this is fixed you might use `native-image` option `-R:MaximumHeapSizePercent=<your_value>` as a workaround.

**Comment by olpaw** [comment]
For more info on this (and related options) use `native-image --expert-options-all` and search for `MaximumHeapSizePercent` (, `MaximumYoungGenerationSizePercent`, `AllocationBeforePhysicalMemorySize`).

**Comment by olpaw** [comment]
Reassigned to our GC expert.

**Comment by christianhaeubl** [comment]
In the upcoming GraalVM 20.0.0 release, we added the following options to set values for `-Xmx`/`-Xms`/`-Xmn`/`-Xss` at image build time:
`-R:MaxHeapSize=...`
`-R:MinHeapSize=...`
`-R:MaxNewSize=...`
`-R:StackSize=...`
