### ISSUE TITLE
[native-image + graal-ee] Native image built from EE has corrupt response for simple netty example project

### ISSUE THREAD

**Issue by nhoughto** [oracle/graal#1687]
I'm trying Graal EE out and came across this very strange behaviour, I have reproduced it in a simple graal + micronaut + netty example from here:

https://github.com/micronaut-guides/micronaut-creating-first-graal-app

So I expect it will be easy for you guys to repro in your own way.

The problem is shown in even a simple native image of a netty http server, a image built via graal-ce works as expect, but an image built with graal-ee returns strange corrupt http response.

built with `19.1.0`:
```
curl 127.0.0.1:8080/conferences/random -v
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 8080 (#0)
> GET /conferences/random HTTP/1.1
> Host: 127.0.0.1:8080
> User-Agent: curl/7.54.0
> Accept: */*
> 
/1.1 OK
Date: Tue, 17 Sep 2019 09:36:22 GMT
ent-type>??: application/json
ent-length: 28
ection>?: -alive>?
```

a second version built with `19.2.0.1` has a different response:
```
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 8080 (#0)
> GET /conferences/random HTTP/1.1
> Host: 127.0.0.1:8080
> User-Agent: curl/7.54.0
> Accept: */*
> 
/1.1 OK
Date: Tue, 17 Sep 2019 09:43:42 GMT
ent-typeFe
: application/json
ent-length: 28
ectionFe: -aliveFe
```

You can see the response header values are truncated, and various characters have been replaced, the last line should read `Connection: keep-alive`, not sure where all the question marks came from! 🤷‍♂  As mentioned this isn't reproducible in Graal CE.

This is obviously a blocker for us further evaluating Graal EE's benefits over CE :+1:

**Comment by nhoughto** [comment]
`GraalVM Version 19.2.0.1 EE` and `GraalVM Version 19.1.0 EE` on Mac Mojave

**Comment by dougxc** [comment]
Hi @nhoughto , can you please see if the error is still reproducible when you add `-Dgraal.Vectorization=false` to the `native-image.properties` file.

**Comment by nhoughto** [comment]
Ok tried that, doesn't seem any different
```
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 8080 (#0)
> GET /conferences/random HTTP/1.1
> Host: 127.0.0.1:8080
> User-Agent: curl/7.54.0
> Accept: */*
> 
/1.1 OK
Date: Tue, 17 Sep 2019 10:32:44 GMT
ent-typeFe
: application/json
ent-length: 21
ectionFe: -aliveFe
```

**Comment by nhoughto** [comment]
Ok bumped micronaut to `1.2.2` and added native image config as per https://github.com/netty/netty/pull/9515 and now it works in EE (and CE).

Needed `--initialize-at-run-time=io.netty.buffer.AbstractReferenceCountedByteBuf` to be added. I'm still not totally clear why CE works fine but EE didn't. With this option added `19.1.0 EE` and `19.2.0.1 EE` work as expect, but `19.1.0 CE` always worked 🤔 🤷‍♂

**Comment by cstancu** [comment]
@nhoughto as you found out we encountered this issue before and fixed it by updating the default Netty configuration. The underlying problem was missing some unsafe offsets recomputations. The reason that was an issue only in EE (and not in CE) is that EE uses compressed pointers (whereas CE doesn't). Compressed references together with using the wrong offset for unsafe operations created the perfect conditions for this error. A workaround would have also been to disable compressed references with `-H:-UseCompressedReferences`.
