### ISSUE TITLE
[native-image] Bouncycastle Provider

### ISSUE THREAD

**Issue by luizurias1** [oracle/graal#1693]
Hi, is it possible to add bouncy castle as a provider to compiled native image?

Even if i add "org.bouncycastle.jce.provider.BouncyCastleProvider" in java.security and use --enable-all-secyrity-services, apparentely it does not cause any effect and continues registering the same providers (I used the flag -H:+TraceSecurityServices).
I have to do something after add the provider in java.security? Or it is impossible to add another provider besides the ones already configured in java.security?

Thanks.

**Comment by fcurts** [comment]
This issue contains lots of information on how to use BouncyCastle: https://github.com/oracle/graal/issues/951

I ended up forgoing BouncyCastle because it increased binary size by 15 MB, which was too much for my use case.

**Comment by luizurias1** [comment]
I read the issue and tried some approaches. I am using the -J-D argument poiting to a file containing "security.provider.3=org.bouncycastle.jce.provider.BouncyCastleProvider". But when i dont add the BC provider via Security.addProvider i get the error: no such provider BC.

But when i add the BC provider via code, i get the error: Caused by: java.security.NoSuchAlgorithmException: no such algorithm: PKCS12 for provider BC.
It seems that the provider has been registered for native image but the implementations (services) of the provider doesnt. 

Any idea?

Thank you!

**Comment by codewhale** [comment]
@luizurias1 , sharing my adventure to enable the BC algorithm in need here:
https://github.com/codewhale/bouncycastle-graalvm-native-image

**Comment by cstancu** [comment]
As I mentioned in a related issue the Bouncy Castle, and all other providers, need to be registered and verified at Native Image build time. See: #2800 (comment).
