### ISSUE TITLE
How to bundle GraalVM with application

### ISSUE THREAD

**Issue by joerg-wille** [oracle/graal#1695]
I do understand the difference between GraalVM AOT & JIT and if my goal would be creating smallest possible deployment packages, I would use AOT.

My goal is to bundle GraalVM for distributing an OSGi based application, which cannot easily be AOT'ed. (Although, imho, combining OSGi and AOT would be an interesting path - compared to the complex task to management of many docker containers - this is not possible as of today.)
(I want to use GraalVM for my OSGi runtime to make use of the native Node.js implementation.)

So, my question is: What is the best way to bundle GraalVM with my application possibly with a maven based tooling?

(Btw, will jlink & JPMS will be supported from GraalVM in the future?)

Thanks

**Comment by dougxc** [comment]
I can comment on the last question. Once GraalVM on JDK11 is available (it's in heavy development currently), then jlink will be available in GraalVM.
