### ISSUE TITLE
Scalar replacement of arrays not working when array is inside a wrapper object

### ISSUE THREAD

**Issue by gjajoo** [oracle/graal#1697]
We encountered some issues with EA in C2 not eliminating seemingly vanilla patterns with array allocations, which we reported on [hotspot-compiler-dev/035037](https://mail.openjdk.java.net/pipermail/hotspot-compiler-dev/2019-September/035037.html).

When we tried similar patterns with graal, while it did much better overall, allocations for an idiomatic code shape still didn't get elided. Basically if you allocate an object which has an array inside it and loop over the array, graal doesn't elide the unnecessary allocations. If you however hand unroll the loop then it has an easier time eliminating them.

```java  
public class ArrayLoop {
    private static Random s_r = new Random();
    private static int next() { return s_r.nextInt() % 1000; }
    private static int loop(int... arr) {
        int sum = 0;
// this loop can be written in any way, forward, backward, for(int i:arr) etc... it doesn't matter
        for (int i = arr.length - 1; i >= 0; sum += arr[i--]) { ; }
        return sum;
    }
    // silly manually unrolled loop
    private static int unrolled(int... arr) {
        int sum = 0;
        switch (arr.length) {
            default: for (int i = arr.length - 1; i >= 4; sum += arr[i--]) { ; }
            case 4: sum += arr[3];
            case 3: sum += arr[2];
            case 2: sum += arr[1];
            case 1: sum += arr[0];
        }
        return sum;
    }
    private static class ArrayWrapper {
        final int[] arr;
        ArrayWrapper(int... many) { arr = many; }
        int loopSum() { return loop(arr); }
        int unrolledSum() { return unrolled(arr); }
    }

    @Benchmark
    public void wrappedUnrolledSum(Blackhole bh) {
        bh.consume(new ArrayWrapper(next(), next()).unrolledSum());
    }

    @Benchmark
    public void wrappedLoopSum(Blackhole bh) {
        bh.consume(new ArrayWrapper(next(), next()).loopSum());
    }
}
```
So with the jmh benchmark above, the wrappedUnrolledSum shows no gc activity as expected but wrappedLoopSum is still showing lot of gc activity. 
```
# JMH version: 1.21
# VM version: JDK 1.8.0_222, OpenJDK 64-Bit GraalVM CE 19.2.0.1, 25.222-b08-jvmci-19.2-b02
....

ArrayLoop.wrappedLoopSum                                        avgt    3    25.745 ±   11.423   ns/op
ArrayLoop.wrappedLoopSum:·gc.alloc.rate                         avgt    3   711.268 ±  317.767  MB/sec
ArrayLoop.wrappedLoopSum:·gc.alloc.rate.norm                    avgt    3    24.000 ±    0.001    B/op
ArrayLoop.wrappedLoopSum:·gc.churn.PS_Eden_Space                avgt    3   725.439 ± 2194.889  MB/sec
ArrayLoop.wrappedLoopSum:·gc.churn.PS_Eden_Space.norm           avgt    3    24.448 ±   69.128    B/op
ArrayLoop.wrappedLoopSum:·gc.churn.PS_Survivor_Space            avgt    3     0.376 ±    3.603  MB/sec
ArrayLoop.wrappedLoopSum:·gc.churn.PS_Survivor_Space.norm       avgt    3     0.013 ±    0.128    B/op
ArrayLoop.wrappedLoopSum:·gc.count                              avgt    3     9.000             counts
ArrayLoop.wrappedLoopSum:·gc.time                               avgt    3    41.000                 ms
ArrayLoop.wrappedUnrolledSum                                    avgt    3    25.056 ±   10.882   ns/op
ArrayLoop.wrappedUnrolledSum:·gc.alloc.rate                     avgt    3    ≈ 10⁻⁴             MB/sec
ArrayLoop.wrappedUnrolledSum:·gc.alloc.rate.norm                avgt    3    ≈ 10⁻⁵               B/op
ArrayLoop.wrappedUnrolledSum:·gc.count                          avgt    3       ≈ 0             counts

```
The benchmark in question is available at [gjajoo/EA](https://github.com/gjajoo/EA/)

**Comment by thomaswue** [comment]
The loop's bound is not a constant at the point in time the compiler is reaching the loop unrolling phase. While solvable, this is currently out of scope as it could substantially increase compile times; specifically if it should be solved for the most general case. The EE version of GraalVM is removing the allocation for this example.

**Comment by gjajoo** [comment]
thanks for the response. there's another example in the same benchmark suite where graal CE is unrolling the loop correctly before CA. what about this one makes the compile times increase substantially?

**Comment by thomaswue** [comment]
The loop is unrolled correctly when the loop bound it seen as constant. What is required here is applying multiple optimizations iteratively; i.e., some PEA to get the bound constant, then some unroll, then some more PEA. Applying PEA twice is what would increase compile times.
