### ISSUE TITLE
Create a native-image without console on Windows

### ISSUE THREAD

**Issue by goblinbr** [oracle/graal#1702]
Is it possible to create a native-image exe without openning the console window on Windows?

**Comment by kangzq0530** [comment]
You can write a cmd/powershell script and then you can start your build by double click. e.g.
```
@echo off
call "C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd"
native-image --no-fallback -cp target\my-jar.jar
```
Make sure your native-image is in your PATH.

**Comment by goblinbr** [comment]
@kangzq0530 Not on compilation. When I run the compiled executable it always open a console window.

**Comment by cstancu** [comment]
A solution is proposed here https://github.com/oracle/graal/issues/2256#issuecomment-624024965.
