### ISSUE TITLE
[native-image] --debug-attach flag not documented in native-image --help

### ISSUE THREAD

**Issue by graemerocher** [oracle/graal#1714]
I have to keep googling how to remote debug `native-image`, a bit of help doc will help me and others 😉

**Comment by olpaw** [comment]
```
> bin/native-image --help | grep extra
    --help-extra          print help on non-standard options
> bin/native-image --help-extra | grep debug
    --debug-attach[=<port>]
                          attach to debugger during image building (default port is 8000)
```

**Comment by graemerocher** [comment]
Interesting, why is it considered a non-standard option? My experience is that it is a pretty common occurrence right now to debug the native image tool since many of the error messages are less than clear

**Comment by olpaw** [comment]
> many of the error messages are less than clear

Agreed. There is room for improvement in our error reporting.
