### ISSUE TITLE
Support of java.net.*

### ISSUE THREAD

**Issue by kangert** [oracle/graal#1721]
Do you plan to support java.net.* or some subset of that (`java.net.URL` and `java.net.URI `are quite common in many source codes).

Currently I'm getting:

> Error: com.oracle.svm.hosted.substitute.DeletedElementException: Unsupported field java.net.URL.handlers is reachable...

**Comment by cstancu** [comment]
The Native Image currently supports `file`, `resource`, `http` and `https` URL protocols. You can read more about it in the [docs](https://github.com/oracle/graal/blob/master/substratevm/URL-PROTOCOLS.md). We delete the `java.net.URL.handlers` field and replace `java.net.URL.getURLStreamHandler()` with [our own implementation](https://github.com/oracle/graal/blob/master/substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jdk/JavaNetSubstitutions.java#L56). Can you share more details about how you reach the ` Unsupported field java.net.URL.handlers is reachable` error? Reproducible code would be ideal.

**Comment by kangert** [comment]
It seems the problem was caused by [Eclipse JarRsrcLoader.java](https://github.com/eclipse/eclipse.jdt.ui/blob/master/org.eclipse.jdt.ui/jar%20in%20jar%20loader/org/eclipse/jdt/internal/jarinjarloader/JarRsrcLoader.java) that was unnecessarily present in jar file.

```
Error: com.oracle.svm.hosted.substitute.DeletedElementException: Unsupported field java.net.URL.handlers is reachable
To diagnose the issue, you can add the option --report-unsupported-elements-at-runtime. The unsupported element is then reported at run time when it is accessed the first time.
Detailed message:
Trace:
        at parsing java.net.URL.setURLStreamHandlerFactory(URL.java:1118)
Call path from entry point to java.net.URL.setURLStreamHandlerFactory(URLStreamHandlerFactory):
        at java.net.URL.setURLStreamHandlerFactory(URL.java:1110)
        at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:48)
        at com.oracle.svm.core.JavaMainWrapper.runCore(JavaMainWrapper.java:151)

        at com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:186)
        at com.oracle.svm.core.code.IsolateEnterStub.JavaMainWrapper_run_5087f54
82cc9a6abc971913ece43acb471d2631b(generated:0)
```

**Comment by tjwatson** [comment]
I am also running into this issue (see https://oss.oracle.com/pipermail/graalvm-users/2019-October/000174.html)

While I can catch and move on without support for a URLStreamHandlerFactory I am curious if this is going to be a permanent restriction going forward.  I can understand not allowing a factory to override the native handlers for  `file`, `resource`, `http` and `https` but will it be possible for custom protocol handlers in the future?

**Comment by cstancu** [comment]
The `Unsupported field java.net.URL.handlers is reachable` error is fixed by https://github.com/oracle/graal/pull/2059. Full support for custom `URLStreamHandlerFactory` is planned for a future release.
