### ISSUE TITLE
native-image : Ability to list the contents/resources within a native-image

### ISSUE THREAD

**Issue by jaikiran** [oracle/graal#1722]
Once a `native-image` has been generated (with specific resource inclusions etc...), is there a way to "list" the contents of such a `native-image`? Imagine something along the lines of `jar -tf somejar.jar` which displays the contents.

The reason I ask is, once a native-image has been generated (through some build process), I want to verify/test that the code which lead to generation of such a native image didn't introduce any regressions by excluding (or including) resources that aren't meant to be present in that final image.

Is this currently possible?

**Comment by olpaw** [comment]
For resources you can use `-H:Log=registerResource` during image building. This will output every resource that gets embedded into your image. Using `-H:+PrintAnalysisCallTree` creates a `reports` directory during image build that contains the result of the static analysis (shows you which classes, methods get embedded into the image).

**Comment by jaikiran** [comment]
Hello @olpaw, thank you for those details and that does indeed help to some extent. 

What I was looking for was the ability to list these resources _after_ the native image has been generated. Imagine a case where the native image build process is done by some other person and isn't accessible to someone who just has the final generated native image available with them.

**Comment by jaikiran** [comment]
> For resources you can use -H:Log=registerResource during image building. This will output every resource that gets embedded into your image
I just gave this a try (using the following command):
```
graalvm/graalvm-ce-19.2.0.1/Contents/Home/bin/native-image 
-J-Dsun.nio.ch.maxUpdateArraySize=100 
 --initialize-at-build-time= -H:InitialCollectionPolicy=com.oracle.svm.core.genscavenge.CollectionPolicy$BySpaceAndTime 
 -jar foobar.jar 
 -J-Djava.util.concurrent.ForkJoinPool.common.parallelism=1 
 -H:FallbackThreshold=0 -H:+ReportExceptionStackTraces 
 -H:+PrintAnalysisCallTree -H:Log=registerResource 
 -H:-AddAllCharsets -H:EnableURLProtocols=http,https 
 --enable-all-security-services -H:+JNI --no-server -H:-UseServiceLoaderFeature -H:+StackTrace
```

This did not generate any log message(s) about the resources being included nor did it generate any file containing such a log. I can see that it does generate reports for `call tree`, `used classes` and `used packages`. I even tried `-H:Log=registerResource:verbose` and that didn't work either. Is there anything wrong with that usage? I'm on `19.2.0.1` of Graal VM

**Comment by jaikiran** [comment]
FWIW - the resources are registered dynamically/programatically through call to `com.oracle.svm.core.jdk.Resources#registerResource`. Maybe that plays a role in whether or no the resources are logged when `-H:Log=registerResource` is used?

**Comment by olpaw** [comment]
> This did not generate any log message(s) about the resources being included

This is a bog that is already fixed on master. See 7d237a1d3ed56cc41270949f3db8ba578cf17964
(the workaround is to use `--no-server` to ensure you see log output)

**Comment by jaikiran** [comment]
Hi @olpaw, the command (pasted in a previous comment) already includes the `--no-server` option.

**Comment by olpaw** [comment]
> What I was looking for was the ability to list these resources after the native image has been generated.

You can use readelf / objdump / nm to inspect the image. The symbol table will show you which methods and static fields got included into the image. Of course that only works if you image did not  get stripped.

**Comment by jaikiran** [comment]
Having looked at the code in https://github.com/oracle/graal/blob/master/substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/ResourcesFeature.java#L188, I think I know what's going on and why it isn't logging the resources being included. As I noted in a previous comment, in our case, the resources are included in the native image through a direct call to `com.oracle.svm.core.jdk.Resources#registerResource()`. The logging is implemented outside of this class/method and in the `ResourcesFeature` and only comes into play if a resource inclusion pattern (like `-H:IncludeResources`) is added to the native image generation. command

**Comment by olpaw** [comment]
> The logging is implemented outside of this class/method and in the ResourcesFeature and only comes into play if a resource inclusion pattern (like -H:IncludeResources) is added to the native image generation. command

Yes. If you do use any resources inclusion patterns you will not see any inclusions.

**Comment by jaikiran** [comment]
Thank you for confirming that.
