### ISSUE TITLE
[truffle-dsl] Check subclass with `@ExportMessage` is also annotated with `@ExportLibrary`

### ISSUE THREAD

**Issue by fniephaus** [oracle/graal#1730]
At the moment, it is possible to implement something like this:

```java
@ExportLibrary(ArrayLibrary.class)
class BufferArray {
    protected int length;
    private int[] buffer;

    /* ... */
    @ExportMessage
    boolean isArray() {
        return true;
    }

    @ExportMessage
    int read(final int index) {
        return buffer[index];
    }

    static class SpecializedBufferArray extends BufferArray {
        /* ... */
        @Override
        @ExportMessage
        boolean isArray() {
            return length < 10;
        }
    }
}
```

Note that `SpecialBufferArray` is not annotated with `@ExportLibrary`, but it needs to be in order to make the specialized `isArray()` work. Similar to how an error is thrown if `@ExportLibrary` is missing in the parent class, the annotation processor should signal that subclasses also need that annotation if they contain `@ExportMessage`.... or ...`@ExportLibrary` should be inherited? Leaving this up to @chumer.

**Comment by boris-spas** [comment]
Tracking internally as Issue GR-20929.

**Comment by chumer** [comment]
You are right this needs either an error or a generated reexport. Thanks for pointing this out.
