### ISSUE TITLE
How to do ahead of time compilation of polyglot embeddings?

### ISSUE THREAD

**Issue by stathissideris** [oracle/graal#1733]
The [documentation for native image](https://www.graalvm.org/docs/reference-manual/native-image/) says that "Polyglot embeddings can also be compiled ahead-of-time" but it’s not clear to me how this can be achieved - or what it means exactly. In my current polyglot project, I'm using `--language:js` which means that I can eval javascript from my native image. Is there a way to compile the same javascript ahead of time and call it from Java instead of evaluating it at runtime?

**Comment by boris-spas** [comment]
"Polyglot embeddings can also be compiled ahead-of-time" means that the actual embedding can be AOT compiled, not the guest language (JS) code itself.

AOT compiling guest languges (i.e. JS) is something we are experimenting with.
