### ISSUE TITLE
Document how you're building LLVM

### ISSUE THREAD

**Issue by chrisseaton** [oracle/graal#1735]
Am I right in thinking that LLVM for the toolchain currently just comes as a binary blob? Or is there an option to build from source that I've overlooked? If not, can you document how you're building LLVM so I can build it myself, have the option for experimenting with upgraded or modified LLVM, and not depend on this big opaque binary?

**Comment by rschatz** [comment]
The LLVM toolchain is built from the LLVM 8 source with a few patches applied (see https://github.com/oracle/graal/tree/master/sulong/patches). The first three patches are no longer necessary on LLVM 9, equivalent changes are already upstream.

Aside from that, we don't do anything special, just the standard cmake build procedure.
(@zapster knows more about that, please correct me if I missed something)

We will try to get the last patch upstream, too, so ideally at some point in the future, we will be shipping an unmodified LLVM. We ship it as a binary blob is just for convenience.

**Comment by chrisseaton** [comment]
Thanks I can reproduce.

```
% brew install cmake
% git clone git@github.com:llvm/llvm-project.git
% cd llvm-project
% git checkout llvmorg-8.0.0
% git apply ../graal/sulong/patches/0001...
% git apply ../graal/sulong/patches/0002...
% git apply ../graal/sulong/patches/0003...
% git apply ../graal/sulong/patches/0004...
% mkdir build
% cd build
% cmake -DLLVM_ENABLE_PROJECTS=clang "Unix Makefiles" ../llvm
% make -j 8
```
