### ISSUE TITLE
Build ce failed on windows-jdk11

### ISSUE THREAD

**Issue by kangzq0530** [oracle/graal#1736]
When I tried to build graalvm-ce-java11 by `mx --env ce-win build` on Windows10, I got a error :
`Could not find any source file for '....\labsjdk-ce-11\lib\*.a'`
I found ".lib"s in the jdk directory. Maybe on windows it should be "*.lib".

**Comment by pquiring** [comment]
If you just create an empty .a file in that folder it will get past that point.

**Comment by gilles-duboscq** [comment]
This was fixed a while ago in 5ac311e198d3090f53e2ca0babae4ce713ad5036. A merge issue re-introduced it but the fix was restored in 57400de062e9e0a4c5f14d1e980d0f3257ad9df2.
