### ISSUE TITLE
Incorrect date and time from Node.js script

### ISSUE THREAD

**Issue by paulrobinson** [oracle/graal#1738]
On my laptop (MacOs Mojave 10.14.6) the date and time coming from a Node.js script is several months in the past and the time of day does not match the current time. 

Script:

```
var today = new Date();
var date = today.getFullYear()+'-'+(today.getMonth()+1)+'-'+today.getDate();
var time = today.getHours() + ":" + today.getMinutes() + ":" + today.getSeconds();
var dateTime = date+' '+time;

console.log(dateTime);
console.log(Date.now());
```

I then run this script on the latest CE and EE of GraalVM, and also an older version I have to hand. The dates and times that I get are all significantly different. When I use the node binary from brew, I get the correct date and time. 

See:

```
date
Fri 11 Oct 2019 13:20:35 BST

/opt/graalvm-ee-19.2.0.1/Contents/Home/bin/node /Users/paul/tmp/date.js
2019-4-28 20:57:28
1556510248823

/opt/graalvm-ce-19.2.0.1/Contents/Home/bin/node /Users/paul/tmp/date.js
2019-4-28 21:2:52
1556510572555

/opt/graalvm-ee-19.1.0/Contents/Home/bin/node /Users/paul/tmp/date.js
2019-5-8 11:17:48
1557339468742

/usr/local/bin/node /Users/paul/tmp/date.js
2019-10-11 13:20:37
1570796437531
```

**Comment by maxandersen** [comment]
I can confirm this behavior. Putting the script into `t.js` and here is graalvm:

```
./node t.js
2019-4-29 14:21:2
1556572862472
```


and true node :

```
node t.js                                                      
2019-12-5 13:58:36
1575550716742
```

and the wall-clock was 13:58 so yes, graalvm is for some reason "off" by several months.

**Comment by maxandersen** [comment]
asked on slack if `--jvm` makes a difference. It does, the time is then correct:

```
$ node t.js                                                             
2019-12-8 1:6:50
1575763610576
$GRAALVM_HOME/bin/node --jvm t.js                                     
2019-12-8 1:6:53
1575763613722
$GRAALVM_HOME/bin/node t.js                                           
2019-4-30 19:58:32
1556679512264
```

**Comment by woess** [comment]
Can't reproduce this with GraalVM 19.3.0, so I believe this is already fixed.

There seems to be an issue with local time zone detection in native mode, though. Will investigate.

**Comment by paulrobinson** [comment]
I can confirm that i can't reproduce with graalvm-ce-java8-19.3.0. I agree, it seems to be fixed.
