### ISSUE TITLE
Feature request: Pass along non-NodeChild/non-NodeField arguments to the execute methods

### ISSUE THREAD

**Issue by ekmett** [oracle/graal#1740]
I have a number of node types for which it would be particularly useful to be able to pass in extra arguments to the specialized `execute` function that are not in themselves captured in the node as fields or children.

I'm working on an implementation of a Haskell-like language, where we have to carefully trim the environments to avoid space leaks. To that end I construct my own materialized frame by copying the relevant parts out of the previous frame when I construct a closure.

I'd like to be able to write something like the following

```java
public abstract class FrameBuilder extends Node {
  public abstract void execute(VirtualFrame frame, MaterializedFrame newFrame);
}
```

where the execute method we tell Truffle about potentially has several non-`@NodeField`/non-`@NodeChild` fields and just have them get plumbed through all the specializations just like the `VirtualFrame` does. (In this case there are no type parameters being specialized, just me trying to use the truffle DSL to allow for rewrites.)

The closest I think I can get with the current API and `@Specialization` support is 

```java
public abstract class FrameBuilder extends Node {
  public abstract Consumer<MaterializedFrame> execute(VirtualFrame frame);
}
```

but that wouldn't work as the exceptions I'd need to process for the specializations come from observing the situation in the `MaterializedFrame` I'm writing into. They wouldn't be known by the time the `Consumer<>` is built. Also, even if this worked, it would rely on an `@ExplodeLoop` in the context in which I perform the frame construction to be smart enough to melt away all those lambdas. (It might! but we'd definitely be working too hard.)

I think what I want is to just be able to write my specializations and have the "excess" fields in the execute method just passed through.

```java
@NodeField(name = "slot", type = FrameSlot.class)
@NodeChild(type = MyExpression.class)
public abstract class FrameSlotBuilder extends FrameBuilder {
  @Specialization(rewriteOn = {FrameSlotTypeException.class, UnexpectedResultException.class})
  void executeBoolean(VirtualFrame frame, MaterializedFrame newFrame, FrameSlot slot, MyExpression rhs) throws FrameSlotTypeException,UnexpectedResultException {
          newFrame.setBoolean(slot, rhs.executeBoolean(frame));
  }
  // more specializations to follow
}
```

where `MyExpression` is a more standard refinement of `Node` with specializations for `Boolean`, which has a normal `execute` method that returns an `Object` taking a `VirtualFrame`, like in all the tutorials.

I'm open to other suggestions for how to proceed. Right now I'm hand-rolling the specialization machinery, but as my type system gets more complicated this seems like it'd become rather brittle.

With this in hand, I can do things like have my lambda functions, contain `FrameBuilder[]` `@Children` that describe where to rummage around in the surrounding frame for their parts, and have the entry to the lambda explode that loop, then process a body which acts as a normal expression.

```java
// inside my lambda node
  @ExplodeLoop
  public Closure execute(VirtualFrame frame) {
    MaterializedFrame newFrame = Truffle.getRuntime().createMaterializedFrame(new Object[]{}, callTarget.getRootNode().getFrameDescriptor());
    for (FrameBuilder step : steps) step.run(frame, newFrame);
    return Closure.create(newFrame, callTarget);
  }
```

Everything else I can come up with to solve this seems appallingly worse. Smuggling the currently being-written-to `MaterializedFrame` in a thread local variable, or in the language's `Context`, which is currently shared, etc. are all significantly heavier weight solutions, and just feel wrong. All of my frames are read-only after construction so they aren't a good place for me to scribble temporary values like this either.

Did I just miss something about how this sort of thing should be done?

**Comment by fniephaus** [comment]
> I'd like to be able to write something like the following
>
> `public abstract class FrameBuilder extends Node {
  public abstract void execute(VirtualFrame frame, MaterializedFrame newFrame);
}`

Maybe it's too obvious or I didn't understand what you are trying to do, but of course you can pass in additional arguments. Here's an example:

```java
public abstract class FrameBuilder extends Node {
    public abstract void execute(VirtualFrame frame, MaterializedFrame newFrame);
    
    @Specialization(guards="newFrame.getArguments().length == 2")
    void do2Args(VirtualFrame frame, MaterializedFrame newFrame) {
        // ...
    }
    
    @Specialization(guards="newFrame.getArguments().length == 3")
    void do3Args(VirtualFrame frame, MaterializedFrame newFrame) {
        // ...
    }
}
```

Does that already answer your question? If not, it'd be easier if you could point us at the relevant code of your project. Also note that you don't have to use `@NodeField` or `@NodeChild`, you can manage fields and children on your own if you like.

**Comment by ekmett** [comment]
Using basically your exact code:

```java
package core;

import com.oracle.truffle.api.dsl.Specialization;
import com.oracle.truffle.api.frame.MaterializedFrame;
import com.oracle.truffle.api.frame.VirtualFrame;
import com.oracle.truffle.api.nodes.Node;

public abstract class Issue extends Node {
    public abstract void execute(VirtualFrame frame, MaterializedFrame newFrame);

    @Specialization(guards="newFrame.getArguments().length == 2")
    void do2Args(VirtualFrame frame, MaterializedFrame newFrame) { }

    @Specialization(guards="newFrame.getArguments().length == 3")
    void do3Args(VirtualFrame frame, MaterializedFrame newFrame) { }
}
```

I get 
```
/Users/ekmett/core/src/main/java/core/Issue.java:11: error: Method signature (VirtualFrame, MaterializedFrame) does not match to the expected signature: 
    @Specialization(guards="newFrame.getArguments().length == 2")
    ^
      void do2Args([VirtualFrame frame])
```

Dropping the `MaterializedFrame` from the argument list and retargeting the guard to `frame`, however typechecks and compiles just fine. 

Hence my confusion.

When I had the other arguments tapped in it basically gave an error almost exactly along these lines.

I'm on `graalvm-ee-19.2.0.1`.

**Comment by fniephaus** [comment]
Oh, I see. It looks like you found a bug in the DSL.  Seems like the annotation processor does not like this particular combination of frame arguments (it has special support for `VirtualFrame` as the first argument). @chumer should know more.

In the meantime, this seems to compile without any problems:

```java
public abstract class Issue extends Node {
    public abstract void execute(VirtualFrame newFrame, Object foo, MaterializedFrame frame);

    @Specialization(guards = "newFrame.getArguments().length == 2")
    void do2Args(final VirtualFrame frame, final Object foo, final MaterializedFrame newFrame) {
    }

    @Specialization(guards = "newFrame.getArguments().length == 3")
    void do3Args(final VirtualFrame frame, final Object foo, final MaterializedFrame newFrame) {
    }
}
```

**Comment by ekmett** [comment]
Great! Thanks. Feel free to close this or use this to track the issue with the annotation parser.

**Comment by hamzaGhaissi** [comment]
Using the above code that was failing with `graalvm-ee-19.2.0.1`, I was able to compile it with `graalvm-espresso-jdk-21.0.1+12.1`
using `graalvm-espresso-jdk-21.0.1+12.1/Contents/Home/bin/java -truffle Issue.java`
