### ISSUE TITLE
Native Image simple java program

### ISSUE THREAD

**Issue by Megatron997** [oracle/graal#1744]
Hello, I'm trying to use graal vm on Windows 10 platform.
`class t1{
	public static void main(String[] args){
		final int nmax=50000;
		int[] a=new int[nmax];
		int[] b=new int[nmax];
		for(int i=0;i<nmax;++i){
			a[i]=i;
			b[i]=i;
		}
		final long st = System.nanoTime();
		double s=0.0;
		for(int i=1;i<nmax;++i)
			for(int j=1;j<nmax;++j)
				s+=1.0/(a[i]*b[j]);
		System.out.println((System.nanoTime()-st)/1000000);
	}
}`
And then I'm trying with Developer Command Prompt VS 2019
C:\Users\Sergei-Pc\Desktop\1>C:\graalvm-ee-19.2.0.1\bin\javac t1.java

And then I got:
C:\Users\Sergei-Pc\Desktop\1>native-image.cmd t1
`[t1:22508]    classlist:   4,036.43 ms
[t1:22508]        (cap):   1,075.48 ms
[t1:22508]        setup:   1,771.98 ms
Error: Error compiling query code (in C:\Users\SERGEI1\AppData\Local\Temp\SVM-783868234815391842\LibFFIHeaderDirectives.cpp). Compiler command  CL -IC:\graalvm-ee-19.2.0.1\jre\lib\svm\clibraries\windows-amd64\include C:\Users\SERGEI~1\AppData\Local\Temp\SVM-783868234815391842\LibFFIHeaderDirectives.cpp /FeC:\Users\SERGEI~1\AppData\Local\Temp\SVM-783868234815391842\LibFFIHeaderDirectives.exe output included error: [?ЇвЁ?Ё?ЁагойЁ? Є??ЇЁ?пв?а Microsoft (R) C/C++ ў?абЁЁ 19.23.28008 ¤?п x86, (C) ??аЇ?а жЁп ? ?Єа?б?дв (Microsoft Corporation).  ?б? Їа ў  ? йЁй??л., ]
Error: Use -H:+ReportExceptionStackTraces to print stacktrace of underlying exception
Error: Image build request failed with exit status 1`

**Comment by RUSshy** [comment]
make effort when report issues

this is unreadable


here a fix

```java
class t1 {
 public static void main(String[] args) {
  final int nmax = 50000;
  int[] a = new int[nmax];
  int[] b = new int[nmax];
  for (int i = 0; i < nmax; ++i) {
   a[i] = i;
   b[i] = i;
  }
  final long st = System.nanoTime();
  double s = 0.0;
  for (int i = 1; i < nmax; ++i)
   for (int j = 1; j < nmax; ++j) s += 1.0 / (a[i] * b[j]);
      System.out.println((System.nanoTime() - st) / 1000000);
 }
}
```

Error:

```
C:\Users\Sergei-Pc\Desktop\1>native-image.cmd t1
[t1:22508] classlist: 4,036.43 ms
[t1:22508] (cap): 1,075.48 ms
[t1:22508] setup: 1,771.98 ms
Error: Error compiling query code (in C:\Users\SERGEI1\AppData\Local\Temp\SVM-783868234815391842\LibFFIHeaderDirectives.cpp). Compiler command CL -IC:\graalvm-ee-19.2.0.1\jre\lib\svm\clibraries\windows-amd64\include C:\Users\SERGEI1\AppData\Local\Temp\SVM-783868234815391842\LibFFIHeaderDirectives.cpp /FeC:\Users\SERGEI1\AppData\Local\Temp\SVM-783868234815391842\LibFFIHeaderDirectives.exe output included error: [?ЇвЁ?Ё?ЁагойЁ? Є??ЇЁ?пв?а Microsoft (R) C/C++ ў?абЁЁ 19.23.28008 ¤?п x86, (C) ??аЇ?а жЁп ? ?Єа?б?дв (Microsoft Corporation). ?б? Їа ў  ? йЁй??л., ]
Error: Use -H:+ReportExceptionStackTraces to print stacktrace of underlying exception
Error: Image build request failed with exit status 1
```

**Comment by pejovica** [comment]
This issue is not reproducible anymore.
