### ISSUE TITLE
[native-image] Don't include classes declared in META-INF/services in output from tracing agent

### ISSUE THREAD

**Issue by graemerocher** [oracle/graal#1749]
See https://github.com/micronaut-projects/micronaut-core/issues/2191

Currently the tracing agent when used with Micronaut will include `reflect.json` information for classes that are already declared in `META-INF/services` via ServiceLoader

This forces uses to filter out those classes afterwards otherwise they are loaded twice when running the app via a constructed native image.

This is a request to automatically filter out classes declared in `META-INF/services` from the generated `reflect.json` since they are not needed.

**Comment by fernando-valdez** [comment]
Closing this ticket as I think it doesn't apply to the current state of native-image + micronaut
