### ISSUE TITLE
[native-image] LLVM object file in different location

### ISSUE THREAD

**Issue by johanvos** [oracle/graal#1753]
When using the LLVM backend, a file llvm.o is generated in a different directory than the directory specified by -H:TempDirectory.
When the linker is invoked, this file is copied to the TempDirectory (where the imageheap is located as well). 
When using -H:+ExitAfterRelocatableImageWrite is used, the linker is not invoked, and the llvm.o file is not copied. This makes it harder to use, as tools need to search for this.

I see 2 solutions:
1. the llvm compilation is done in TempDirectory as well (if specified)
2. the llvm.o file is copied to TempDirectory before the linker is invoked.

**Comment by dougxc** [comment]
@loicottet I think is one for you.

**Comment by loicottet** [comment]
Solution 1 is probably better. I’ll fix this.

**Comment by johanvos** [comment]
Thanks, I agree that would be the best solution.

**Comment by loicottet** [comment]
Fixed in 098d70
