### ISSUE TITLE
native compilation incorrectly detects ZipFile object in image heap

### ISSUE THREAD

**Issue by tjwatson** [oracle/graal#1770]
Using a Mac:
```
java -version
openjdk version "1.8.0_232"
OpenJDK Runtime Environment (build 1.8.0_232-20191009173705.graal.jdk8u-src-tar-gz-b07)
OpenJDK 64-Bit GraalVM CE 19.2.1 (build 25.232-b07-jvmci-19.2-b03, mixed mode)
```

I tried to distill this into an isolated testcase, but to no avail.  Please pardon the use of my larger project to reproduce (https://github.com/tjwatson/atomos).

My Atomos project is investigating running of OSGi bundles in a substrate image among other things like running in a jlink image or from the flat class path.  I have been making progress with using a substrate native image as long as I keep framework initialization and starting of bundles out of static initializers at build-time.

Now I am attempting to move some of the framework creation into static init at build-time to reduce the cost of the framework even more.  To do that I have delayed any creation of threads or attempts to keep files open to things like JarFiles in the construction of the framework during <clinit>.  But I am still end up with errors like this during native-image compilation:

```
Error: Detected a ZipFile object in the image heap. A ZipFile object contains pointers to unmanaged C memory and file descriptors, and these resources are no longer available at image run time. Object has been initialized without the native-image initialization instrumentation and the stack trace can't be tracked. The object was probably created by a class initializer and is reachable from a static field. You can request class initialization at image run time by using the option --initialize-at-build-time=<class-name>. Or you can write your own initialization methods and call them explicitly from your main entry point.
Trace: 	object org.atomos.framework.substrate.SubstrateConnectContent
	object org.atomos.framework.substrate.AtomosRuntimeSubstrate$AtomosLayerSubstrate$AtomosBundleInfoSubstrate
	object java.util.HashMap$Node
	object java.util.HashMap$Node[]
	object java.util.HashMap
	object java.util.HashSet
	object org.atomos.framework.substrate.AtomosRuntimeSubstrate$AtomosLayerSubstrate
	object org.atomos.framework.substrate.AtomosRuntimeSubstrate
	method org.atomos.service.substrate.GogoConsole.main(String[])
Call path from entry point to org.atomos.service.substrate.GogoConsole.main(String[]): 
	at org.atomos.service.substrate.GogoConsole.main(GogoConsole.java:28)
	at com.oracle.svm.core.JavaMainWrapper.runCore(JavaMainWrapper.java:151)
	at com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:186)
	at com.oracle.svm.core.code.IsolateEnterStub.JavaMainWrapper_run_5087f5482cc9a6abc971913ece43acb471d2631b(generated:0)
```

What is confusing about this is that the entry point is coming out of my main method.  It is true that that leads to opening JarFiles, but that is outside of <clInit>.  When I try to create a small testcase that does something similar in static <clinit> that opens and closes ZipFiles and then reopening the ZipFile in the static main() method the static compilation works.  So there is something specific about my project causing this, but at this point I have no idea what.

To reproduce:
```
export JAVA_HOME=path/to/java11/home
git clone -b osgiConnectStatic https://github.com/tjwatson/atomos atomos-connect
cd atomos-connect
mvn clean install -Pjava8
export JAVA_HOME=path/to/graal-19.2.1/home
cd atomos.tests/service.substrate
mvn clean package
```
Note that the initial build requires Java 11 and the use of `-Pjava8` to compile the main project.  This ensures that Java 8 bytecode is produced so it can be used by Graal.

In `service.substrate/src/main/java/org/atomos/service/substrate/GogoConsole.java` you will see the following in the main method:

```
    	// Printing out the name of each AtomosBundleInfo calculated at build time works fine
    	// proving that the build time static <clinit> of GogoConsoleStatic worked
    	atomosBundles.forEach((b) -> System.out.println(b.getSymbolicName()));

    	// Trying to open the JarFile for each AtomosBundleFile cause native compilation to fail
    	// even though this should only be done at run-time.
    	// Comment out the following 2 lines and the substrate native-image will compile fine
    	atomosBundles.forEach(GogoConsole::open);
    	startFramework();
```

If you comment out the last two lines from main then native compilation works.  Also, if you remove `org.atomos.service.substrate.GogoConsoleStatic` from `--initialize-at-build-time` in the pom.xml it works as expected because no framework creation will be done in <clinit> at all.

**Comment by tjwatson** [comment]
I was able to get to the bottom of the issue.  There was still a ZipFile open from the `<clinit>`.  When some lines are commented out the native-image generation detects that some objects are never actually used and it removes them from the heap.  Not sure if there are ways to improve the detection for cases like this.  But I will go ahead and close the issue.  If anyone is interested I fixed this in my branch `osgiConnectStaticFixed` in https://github.com/tjwatson/atomos

**Comment by cstancu** [comment]
@tjwatson good to hear that you figured it out!

> What is confusing about this is that the entry point is coming out of my main method. 

The reason for that is because the offending object, i.e., the `ZipFile`, is found via heap scanning starting from roots. For the Graal compiler roots are both static final fields and constant objects embeded in method graphs. In this case the graph of the main method embeds the constant object reached from `GogoConsoleStatic.atomos`.

I am working on improving the object trace in the reporting. The work in progress version looks like:

```
Error: Detected a ZipFile object in the image heap. A ZipFile object contains pointers to unmanaged C memory and file descriptors, and these resources are no longer available at image run time.  Object has been initialized without the native-image initialization instrumentation and the stack trace can't be tracked. The object was probably created by a class initializer and is reachable from a static field. You can request class initialization at image run time by using the option --initialize-at-build-time=<class-name>. Or you can write your own initialization methods and call them explicitly from your main entry point.
Trace: Object was reached by 
	reading field org.atomos.framework.substrate.SubstrateConnectContent.zipFile
	reading field org.eclipse.osgi.internal.connect.ConnectBundleFile.content
	indexing into org.eclipse.osgi.storage.bundlefile.BundleFile[] array
	reading field org.eclipse.osgi.storage.bundlefile.MRUBundleFileList.bundleFileList
	reading field org.eclipse.osgi.storage.Storage.mruList
	reading field org.eclipse.osgi.internal.framework.EquinoxContainer.storage
	reading field org.eclipse.osgi.internal.framework.EquinoxBundle.equinoxContainer
	reading field org.eclipse.osgi.launch.Equinox.systemBundle
	scanning method org.atomos.service.substrate.GogoConsole.startFramework(GogoConsole.java:56)
```

Here the graph of `GogoConsole.startFramework` embeds the constant reached from `GogoConsoleStatic.framework`, which eventually reaches the `ZipFile` object.
