### ISSUE TITLE
NoClassDefFoundError Exception

### ISSUE THREAD

**Issue by lilili87222** [oracle/graal#1773]
Exception Error where run native binary created by native command.
I have add those class in reflect-config.json ,but it show error continue.
Timeout exception,file not found exception,the same.
graalvm ce 19.2.1,windows,native image.

![classnotfound](https://user-images.githubusercontent.com/2214998/67535257-6d77ac00-f704-11e9-984a-3742f976f76f.png)

**Comment by kangzq0530** [comment]
Same with #1710 . Add Ljava/net/SocketTimeoutException to jni-config.

**Comment by jramirez-isc** [comment]
@lilili87222 as @kangzq0530 commented, try adding `Ljava/net/SocketTimeoutException` to the JNI configuration. See the [JNI documentation](https://github.com/oracle/graal/blob/master/substratevm/JNI.md) to register it properly.

It's also useful to use the [native-image-agent](https://github.com/oracle/graal/blob/master/substratevm/CONFIGURE.md) to automatically detect the reflectively accessed elements, it can help you with the config files.

However, it may be necessary to add the class manually in this case, according to [this comment](https://github.com/oracle/graal/issues/1710#issuecomment-536347910).
