### ISSUE TITLE
NativeImageBuildServer "leaks"?

### ISSUE THREAD

**Issue by rmannibucau** [oracle/graal#1774]
Hi,

I noticed that with 19.2.1, NativeImageBuildServer leaks (at least when the build fails) and it can lead to another server being started but some classpath jars being already hold which prevents the build to pass.

Not sure it is a bug or intended but it is quite misleading to end up on a FileNotFoundException in ServiceLoaderFeature due to that.
Killing the process before launching native-image works but is quite unnatural.

Romain

**Comment by jaikiran** [comment]
Perhaps related to https://github.com/oracle/graal/pull/1860?

**Comment by rmannibucau** [comment]
Don't think so since #1860 does not leak cause the buffered reader closes the underlying inputstream.
Here the issue is more about a state leak than a memory leak.

**Comment by jaikiran** [comment]
> Don't think so since #1860 does not leak cause the buffered reader closes the underlying inputstream.

The `BufferedReader` closes the underlying `InputStreamReader` but none of them close the `InputStream` itself. That's left to the callers who pass the `InputStream` to the reader.

**Comment by rmannibucau** [comment]
@jaikiran java.io.InputStreamReader#close does through the StreamDecoder

**Comment by jaikiran** [comment]
You are right indeed. I hadn't noticed the code in `StreamDecoder#implClose()`. Thank you.

So it looks like the issue that I'm running into, which was similar to what you reported here is caused by something else and I'll need to debug more.

**Comment by vjovanov** [comment]
We are not using the server anymore as it was too hard to maintain.
