### ISSUE TITLE
Question - How do I do a call to "super" in my @Substitute

### ISSUE THREAD

**Issue by jaikiran** [oracle/graal#1776]
Imagine these classes:

```

public class A {
	public void sayHello() {
		... // some code
	}		
}

public class B extends A {
	
	public void sayHello() {
		super.sayHello();
		... // now do additional work
		doAdditionalWork();
	}
}

public class C {
	
	public void someReachableCode() {
		new B().start();
	}
}
```

In my native image that I generate, I want to substitute the B#sayHello() implementation to only include a call to the `super.sayHello()` and get rid of the rest of the code in that method.

I started to write a substitution, but can't seem to find a way to do a "super.sayHello()" in my substitution without having my substituting class extend A. Here's what I mean:

```
@TargetClass(B.class)
final class SubstituteB {

    @Substitute
    public void start() {
        // how do I call "super.start()" here to imply a call on "A.start()"
    }

}
```

I've read about `Alias` and that too, I don't think, fits this usecase.

**Comment by ams-tschoening** [comment]
Just came across the following API distinguishing native images from anything else in some [YouTube-video](https://youtu.be/z0jedLjcWjI?t=2170):

    inImageCode()
    Returns true if (at the time of the call) code is executing in the context of image building or during image runtime, else false.

https://www.graalvm.org/sdk/javadoc/org/graalvm/nativeimage/ImageInfo.html#inImageCode--

That way you might not need to substitute existing code during creating the native image, but simply implement a branch always.
