### ISSUE TITLE
[native-image] launch headless NativeImageGeneratorRunner on macOS

### ISSUE THREAD

**Issue by danielcompton** [oracle/graal#1789]
When running `native-image`, the `NativeImageGeneratorRunner` is launched as a separate process. https://github.com/oracle/graal/blob/86e065bd8f2b2ea722fd0687e3da1edba4fb3f00/substratevm/src/com.oracle.svm.driver/src/com/oracle/svm/driver/NativeImage.java#L1139-L1156

On macOS, this launches a new Java application which takes the focus. It also shows in the Dock with the title `NativeImageGeneratorRunner`. This is a very minor annoyance, but is also pretty easy to fix.

If you add `-Djava.awt.headless=true` to the command, then the application is launched without having any effect on the desktop environment. I took a look at the code, but wasn't really sure where the best place to add this was. Wherever it goes, you'd probably want to make sure the same change applies to the `NativeImageServer` as well.

You can easily check how this would work by running a `native-image` command with `--verbose`, copying the command that is printed, and then adding `-Djava.awt.headless=true` to the flags.

I also noticed https://github.com/oracle/graal/commit/c7679b1c89d32915a21c3a6ba4675078ed705c44, which suggests that this should probably be gated to Darwin OS's? It looks like [JDK-8159956](https://bugs.openjdk.java.net/browse/JDK-8159956) is only fixed in JDK 9 and up?

**Comment by olpaw** [comment]
Hi @danielcompton 
I will add a fix that ensures `-Djava.awt.headless=true` is used for the JVM that runs the image builder whenever possible (i.e. not for Windows when Java 8 is used).
Thanks for the suggestion!

**Comment by danielcompton** [comment]
Fixed in https://github.com/oracle/graal/commit/7ff42caaa3f09e528af040bc75e2d9f245f967ff.
