### ISSUE TITLE
[Documentation] Character Sets supported by Truffle is not documented anywhere

### ISSUE THREAD

**Issue by jayadevanraja** [oracle/graal#1803]
Does Truffle support making a programming language in a new character set?

This is with reference to [this question](https://stackoverflow.com/questions/58615652/making-a-new-programming-language-in-a-new-character-set-in-graalvm). My [understanding](https://stackoverflow.com/questions/58615652/making-a-new-programming-language-in-a-new-character-set-in-graalvm#comment103609727_58639057) is that, “if we have all the characters in any arbitrary character-set encoded as [16-bit unsigned integers](https://stackoverflow.com/questions/24095187/char-size-8-bit-or-16-bit/24095210#24095210), then Truffle can handle it”. But it is not documented whether or not this is indeed the case.

That is, if I want to implement a new programming language in a character set which is neither Unicode nor ASCII, like EBCDIC, or TRON or something entirely new, can that be done in Graal & Truffle?

**Comment by jayadevanraja** [comment]
It has been almost 3 years and 3 months, since nobody was able to answer this question. So, I am copy-pasting the answer which ChatGPT gave me when I presented the exact same question to it. Truffle developers, please confirm this answer, or present a better answer. I am closing this issue, but please reopen it if necessary. 🙏

---

Truffle is a framework for building high-performance dynamic languages that runs on the GraalVM. It is designed to be flexible and extensible, and can potentially support implementing a new programming language in a character set that is different from Unicode or ASCII.

The key requirement for Truffle to support a new character set would be the ability to encode the characters in that set as 16-bit unsigned integers. If this is possible, Truffle should be able to handle it.

However, you should be aware that Truffle and GraalVM are not specifically designed to handle other character set than Unicode. You may need to do some modification of the framework to handle the specific character set you want to use.

It is also worth noting that it would be an uncommon and complex task, as most of the modern programming languages and tools are designed to work with Unicode.


---

The above is the answer which ChatGPT gave me. I am posting it, in the faith that this will be helpful for others.

**Comment by smarr** [comment]
Truffle builds on Java, as such, the "native" representation for strings is the same as Java strings (see https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/lang/String.html for details).

Though, one can of course use plain byte arrays to do custom things, and that's as hard or easy as working with byte arrays in Java.

**Comment by jayadevanraja** [comment]
I happened to ask this to Sage AI Chatbot. That AI Chatbot gave me an answer very different from the above. I request any human expert to help clarify the situation. I am posting Sage's answer below.

---

Yes, Truffle can be used to create programming languages that use character sets other than Unicode or ASCII. In fact, Truffle is designed to be flexible enough to support a wide range of character sets and encodings.

Java's string representation uses UTF-16 encoding, which means that each character is represented using 16 bits. However, Truffle provides a mechanism for defining custom character encodings that can be used in your language runtime. You can define your own character set and encoding scheme, and then use Truffle's API to convert between your encoding and UTF-16.

In addition, Truffle provides support for working with byte arrays, which can be used to store and manipulate data in any format. This means that you can use Truffle to create programming languages that work with binary data, or that use specialized encodings such as EBCDIC.

Overall, Truffle's flexibility and extensibility make it well-suited for creating programming languages that support a wide range of character sets and encodings.


Truffle provides a framework for implementing custom character encodings that can be used in your language runtime. This framework is based on the concept of a "source section", which is a representation of a contiguous region of source code in your language.

In Truffle, a source section is associated with a particular character encoding. When your language runtime encounters a source section, it can use the associated encoding to convert the raw bytes of the source code into a stream of characters that can be processed by your language implementation.

To define a custom character encoding, you need to implement a Truffle source section provider that can interpret the raw bytes of your source code according to your encoding scheme. This provider is responsible for converting the raw bytes into a stream of characters that can be processed by your language implementation.

Here's an example of how to define a custom character encoding in Truffle:

```java
import com.oracle.truffle.api.source.*;

public class MyEncodingProvider implements SourceSectionProvider {
    private final String encodingName;

    public MyEncodingProvider(String encodingName) {
        this.encodingName = encodingName;
    }

    @Override
    public SourceSection createSection(byte[] bytes, int offset, int length, Source source) {
        // Convert the bytes according to your custom encoding scheme
        String text = myConvert(bytes, offset, length);

        // Create a new source section with the converted text
        return source.createSection(offset, text);
    }

    // Implement your custom encoding scheme here
    private String myConvert(byte[] bytes, int offset, int length) {
        // ...
    }
}
```

In this example, `MyEncodingProvider` is a Truffle source section provider that can interpret source code encoded using a custom encoding scheme. The `createSection` method is called by Truffle when it encounters a source section that is associated with this provider. The method converts the raw bytes of the source code into a stream of characters using the custom encoding scheme, and returns a new source section object that represents the converted text.

Once you have implemented your custom source section provider, you can register it with Truffle using the `Source.newBuilder` method. For example:

```java
Source.newBuilder("mySourceCode", new MyEncodingProvider("myCustomEncoding")).build();
```

This creates a new source object that represents the source code "mySourceCode", encoded using the custom encoding scheme "myCustomEncoding".

Overall, Truffle's support for custom character encodings provides a powerful mechanism for creating programming languages that can work with a wide range of character sets and encodings.

**Comment by chumer** [comment]
> That is, if I want to implement a new programming language in a character set which is neither Unicode nor ASCII, like EBCDIC, or TRON or something entirely new, can that be done in Graal & Truffle?

If you build your own Truffle language you can use your own String representation as long as it converts either to java.lang.String or [TruffleString](https://github.com/oracle/graal/blob/master/truffle/docs/TruffleStrings.md)

In order to handle Source input from embedders you can use your own implementation of CharSequence to pass in strings from the outside, or binary sources. If sources are loaded are only loaded within your language and never passed from the outside, you can also use your own source representation class.
