### ISSUE TITLE
AtomicBoolean#set code seems to not be as compact as it could be

### ISSUE THREAD

**Issue by chrisseaton** [oracle/graal#1806]
I have a Truffle node in which I do `AtomicBoolean#set(true)`.

The code generated looks like this:

```
  0x000000010c0c108a: movabs $0x5c00086c8,%rax  ;   {oop(a 'java/util/concurrent/atomic/AtomicBoolean')}
  0x000000010c0c1094: movl   $0x1,0xc(%rax)     ;*putfield value {reexecute=0 rethrow=0 return_oop=0}
                                                ; - java.util.concurrent.atomic.AtomicBoolean::set@10 (line 128)

  0x000000010c0c109b: lock addl $0x0,(%rsp)
```

Why does it do `rax = 0x5c00086c8; *(rax + 0xc) = 1` instead of folding that into `*0x5C00086D4 = 1` and a single `movl` instruction?

I also noticed that if I set an `AtomicBoolean` to the same constant value multiple times in a row they aren't removed as redundant. I know the memory model around volatile somewhat, but I don't see any way that another thread could observe the difference between these two:

```
flag = 1
fence
flag = 1
fence
```

and

```
flag = 1
fence
```

So why repeat it? Is it just there's no mechanism to look inside volatile writes and see if they the same like this?

**Comment by tkrodriguez** [comment]
The reason the base oop and offset are separate is that HotSpot has no support for derived constant oops so you have to separately materialize the constant base and the offset.  In practice it likely makes no difference.

It's true that some patterns of volatile operations like you describe probably could be optimized but generally we don't optimize volatile accesses at all.  Why are you getting repeated sets to true?  Does it really seem to affect performance?

**Comment by chrisseaton** [comment]
Ah right - problems like moving objects, GC roots, all need a proper OOP in the code, not an inner pointer, I see.

The cause for the repeated pattern was the flag being set by multiple nodes in a Truffle interpreter, so when PEd they all came together in a sequence.

No, I didn't measure any performance impact - I was just curious.

Thanks very much for both explanations, that's clear now.

**Comment by tkrodriguez** [comment]
It's likely that some logic could be added [here](https://ol-bitbucket.us.oracle.com/projects/g/repos/graal/browse/compiler/src/org.graalvm.compiler.nodes/src/org/graalvm/compiler/nodes/memory/WriteNode.java?at=81b3086a702c06c5f6b36b0ab8abc969a05d0264#79-79) to capture your case.  Even in the volatile case this code seems safe to me but you could restrict it to repeated stores of the same value which certainly seems safe for volatile.
