### ISSUE TITLE
[jvmci-8] on darwin fails to build

### ISSUE THREAD

**Issue by hlolli** [oracle/graal#1816]
For the following c++ line

https://github.com/graalvm/graal-jvmci-8/blob/jvmci-19.3-b04/src/share/vm/code/compiledIC.cpp#L225

I'm getting 

```
/private/var/folders/9k/hr12t49132lgnpzq88w_h6740000gn/T/nix-build-jvmci-19.3-b04.drv-0/source/src/share/vm/code/compiledIC.cpp:225:15: error: comparison between pointer and integer ('address' (aka 'unsigned char *') and 'bool')

    if (entry == false) {

        ~~~~~ ^  ~~~~~
```

I'm building with tag 19.3-b04 using clang version 7.1.0 (tags/RELEASE_710/final).

**Comment by wirthi** [comment]
Closing stale old issue. We are not supporting 19.3 any longer; if you experience a similar issue on a recent release, please create a new ticket for it, thanks!
