### ISSUE TITLE
[native-image] Ask question: how to build the "labs-openjdk-11" on AArch64 for native-image? 

### ISSUE THREAD

**Issue by XiaohongGong** [oracle/graal#1820]
Hi there,

I tried to download a latest released labsjdk (jvmci-19.3-b04) for AArch64 to build the native image. But currently it only has the amd64 version. So I have to build the image by myself.  I checked out the `"labs-openjdk-11-jvmci-19.3-b04.tar.gz"` and directly use `"bash configure; make images"` to build the jdk image. And there are some issues when I use the image to build the native image.
So do I need to add some options when configuration? And how can I build a "jvmci-19.3-b04" for AArch64 ? Thank you so much!

**Comment by dougxc** [comment]
I have added the AArch64 binaries now to https://github.com/graalvm/labs-openjdk-11/releases/tag/jvmci-19.3-b04.
