### ISSUE TITLE
fastR or python installation with windows

### ISSUE THREAD

**Issue by vwiencek** [oracle/graal#1827]
Hello

I'm trying to install fastR package with graalVM under windows but I cannot find the `gu` utility (I understand it's not yet available).

But what are my options to get additional polyglot languages with windows ?

**Comment by fniephaus** [comment]
GraalVM's Windows support is still very experimental, plus fastr and GraalPython aren't even officially supported on Linux and macOS, neither is `gu` at the moment. AFAIK, the GraalVM team is actively working on adding support for `gu` on Windows.

If you'd like to use these additional languages now, it's probably best to do it through the [WSL](https://en.wikipedia.org/wiki/Windows_Subsystem_for_Linux).

**Comment by jobdiogenes** [comment]
I don't recommend 

> Hello
> 
> I'm trying to install fastR package with graalVM under windows but I cannot find the `gu` utility (I understand it's not yet available).
> 
> But what are my options to get additional polyglot languages with windows ?

I really did not recommend to use Windows for high performance needs. 
Even WSL, which help to have a Linux environment in Windows, its not for high performance.
But, if want to try GraalVM and R, to check compatibility with yours scripts. 
An easy way is with Docker and a FastR container.
To install [Docker for Windows](https://docs.docker.com/docker-for-windows/install/)
GraalVM FastR Docker. Available [Here](https://hub.docker.com/r/jobdiogenes/fastr)

**Comment by fernando-valdez** [comment]
closing this issue as it no longer applies.
