### ISSUE TITLE
Mitigation of Jump Conditional Code (JCC) Erratum wanted to avoid performance loss on Intel CPUs

### ISSUE THREAD

**Issue by plokhotnyuk** [oracle/graal#1829]
While largely overlooked due to the new TAA vulnerability and other security related issues, the new microcode from Intel includes a fix for the Jump Conditional Code (JCC) Erratum which carries a significant performance penalty:

https://www.intel.com/content/dam/support/us/en/documents/processors/mitigations-jump-conditional-code-erratum.pdf

https://www.intel.com/content/dam/www/public/us/en/documents/corporate-information/SA00270-microcode-update-guidance.pdf

On the latest version of microcode slow and inefficient code is almost not affected, while for highly optimized with a lot of branching in hot loops throughput slowdown is up to 50% compared to results on the previous version of microcode.

Previous:
```
model		: 158
model name	: Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz
stepping	: 9
microcode	: 0xb4
```

Current:
```
model		: 158
model name	: Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz
stepping	: 9
microcode	: 0xc6
```
Microcode updates for Linux (binaries and release notes):
https://github.com/intel/Intel-Linux-Processor-Microcode-Data-Files

Bellow are comparisons of results for the same benchmarks when running on different versions of microcode:

![image](https://user-images.githubusercontent.com/890289/69005178-8dbf1300-091e-11ea-9d70-b0a2fd6c67d4.png)
[Full results for GraalVM CE 19.2.1 (0xb4 vs 0xc6)](https://jmh.morethan.io/?sources=https://raw.githubusercontent.com/plokhotnyuk/jsoniter-scala/1df65ad1df664f74e5c4cc1f32bf57e32ca025ae/graalvmce19.json,https://raw.githubusercontent.com/plokhotnyuk/jsoniter-scala/e1b61601ff17a3dc28b7f547b2ec9dff9ad14366/graalvmce19.json)

![image](https://user-images.githubusercontent.com/890289/69005194-c19a3880-091e-11ea-9d2d-af36f720ad90.png)
[Full results for GraalVM EE 19.2.1 (0xb4 vs 0xc6)](https://jmh.morethan.io/?sources=https://raw.githubusercontent.com/plokhotnyuk/jsoniter-scala/1df65ad1df664f74e5c4cc1f32bf57e32ca025ae/graalvmee19.json,https://raw.githubusercontent.com/plokhotnyuk/jsoniter-scala/e1b61601ff17a3dc28b7f547b2ec9dff9ad14366/graalvmee19.json)

**Comment by dougxc** [comment]
Thanks for the report @plokhotnyuk . We will look into this but the window for 19.3 is pretty much closed for a change this size. That sadi, we will look into implementing something like the `-mbranches-within-32B-boundaries` option in the gnu assembler as oon as possible.

**Comment by plokhotnyuk** [comment]
@dougxc @mur47x111 In the issue description I've added links to Intel CPU microcode updates (for Linux) and links for benchmarks comparison on different versions of microcode.

**Comment by mur47x111** [comment]
Given the short window for 19.3, we won't be able to include such fix in the 19.3 release. I have a nop-based prototype, and will convert it into a prefix-based solution and push into the next update release.

**Comment by plokhotnyuk** [comment]
@mur47x111 great work!

Could you please share a branch with your prototype?
Can it be built by [standard steps](https://github.com/oracle/graal/tree/master/compiler#building-the-graalvm-compiler)?
I would like to build and test it locally...

**Comment by mur47x111** [comment]
Let me polish it first. Still many //TODO ;)
It will land in the master (before the next update release), and then you can use the standard steps to build it.

**Comment by plokhotnyuk** [comment]
IFYK: The initial patch landing in LLVM 10 https://github.com/llvm/llvm-project/commit/14fc20ca62821b5f85582bf76a467d412248c248

**Comment by mur47x111** [comment]
This is more complicated than I thought initially.. anyway, with https://github.com/oracle/graal/commit/07ae939513d1eb2f40402eb9304938c20f8bb611 and https://github.com/oracle/graal/commit/de73dbb3bc031756061426391920fc52f2b7a815 we are now able to enable the jcc paddings. You only need to pass -Dgraal.UseBranchesWithin32ByteBoundary=true while running the application. When http://cr.openjdk.java.net/~eosterlund/8234160/webrev.01/ is merged, I will then set this option accordingly.

@plokhotnyuk would you please give it a try and report if the patch helps addressing the regression?

**Comment by plokhotnyuk** [comment]
@mur47x111 Great work, Yudi!

Just tried a couple of benchmarks on my laptop with Intel Core i7 and the latest version of microcode.

## graalvm-libgraal-java8-20.0.0 with -Dgraal.UseBranchesWithin32ByteBoundary=false
```
[info] REMEMBER: The numbers below are just data. To gain reusable insights, you need to follow up on
[info] why the numbers are the way they are. Use profilers (see -prof, -lprof), design factorial
[info] experiments, perform baseline and negative tests that provide experimental control, make sure
[info] the benchmarking environment is safe on JVM/OS/HW level, ask for reviews from the domain experts.
[info] Do not assume the numbers tell you what you want them to tell.
[info] Benchmark                                           (size)   Mode  Cnt        Score       Error  Units
[info] StringOfAsciiCharsWriting.jsoniterScalaPrealloc        128  thrpt    5  2794838.945 ± 11302.004  ops/s
[info] StringOfEscapedCharsWriting.jsoniterScalaPrealloc      128  thrpt    5  1974297.307 ±  3173.319  ops/s
[info] StringOfNonAsciiCharsWriting.jsoniterScalaPrealloc     128  thrpt    5  2075002.940 ±   466.351  ops/s
```

## graalvm-libgraal-java8-20.0.0 with -Dgraal.UseBranchesWithin32ByteBoundary=true
```
[info] REMEMBER: The numbers below are just data. To gain reusable insights, you need to follow up on
[info] why the numbers are the way they are. Use profilers (see -prof, -lprof), design factorial
[info] experiments, perform baseline and negative tests that provide experimental control, make sure
[info] the benchmarking environment is safe on JVM/OS/HW level, ask for reviews from the domain experts.
[info] Do not assume the numbers tell you what you want them to tell.
[info] Benchmark                                           (size)   Mode  Cnt        Score      Error  Units
[info] StringOfAsciiCharsWriting.jsoniterScalaPrealloc        128  thrpt    5  5864945.579 ± 8776.218  ops/s
[info] StringOfEscapedCharsWriting.jsoniterScalaPrealloc      128  thrpt    5  2307407.851 ± 1047.652  ops/s
[info] StringOfNonAsciiCharsWriting.jsoniterScalaPrealloc     128  thrpt    5  2924913.938 ± 6584.358  ops/s
```

**Comment by mur47x111** [comment]
Hmm I did not expect the effect to be so huge..

**Comment by plokhotnyuk** [comment]
BTW, does this flag align only branches? What about jumps, calls, and returns will be they aligned with this option turned on?

**Comment by mur47x111** [comment]
All of them are covered. The jumps calls returns are the easy ones

**Comment by plokhotnyuk** [comment]
@mur47x111 You've made Intel CPUs great again!

[Here](https://jmh.morethan.io/?sources=https://raw.githubusercontent.com/plokhotnyuk/jsoniter-scala/gh-pages/graalvm-ce-java8-branch-alignment-off.json,https://raw.githubusercontent.com/plokhotnyuk/jsoniter-scala/gh-pages/graalvm-ce-java8-branch-alignment-%D0%BEn.json) is a comparison of results for the latest version of benchmark on GraalVM CE Java8 20.0.0-dev with the `UseBranchesWithin32ByteBoundary` option turned off/on:
![image](https://user-images.githubusercontent.com/890289/72660437-457baa00-39ce-11ea-81c5-8224be3b4c90.png)

**Comment by plokhotnyuk** [comment]
@mur47x111 @dougxc I had built `libgraal` using [the standard steps from the docs](https://github.com/oracle/graal/blob/master/compiler/README.md#libgraal), but now wondering if it possible to turn this option on when building native images or `libgraal` itself?

**Comment by dougxc** [comment]
For native images, it should just be a matter of using the `-H:+UseBranchesWithin32ByteBoundary` option.

**Comment by dougxc** [comment]
@mur47x111 do you have some insight as to what the cost of building libgraal with this option enabled will cost in terms of performance of libgraal on platforms that are not subject to the JCC erratum?

**Comment by plokhotnyuk** [comment]
@mur47x111 I see that [mitigations for jcc erratum are merged to the JDK master](https://github.com/openjdk/jdk/commit/ccdde497287175933982a5907d1bb8611c0e15a8). Will you reuse their approach of turning on a branch alignment by default for affected CPUs?

**Comment by plokhotnyuk** [comment]
Closing as resolved... Works fine in early access builds of OpenJDK 15 too!

**Comment by mur47x111** [comment]
Sorry for not replying earlier. With the new JVMCI https://github.com/graalvm/labs-openjdk-11/releases/tag/jvmci-20.1-b01 and https://github.com/oracle/graal/commit/6fe68785c8a20ebd905e922d42e6ed22a431702b we are now able to turn on the branch alignment by default on affected CPUs. Latest JDK should contain the necessary patch as well.
