### ISSUE TITLE
NPE using tracing agent

### ISSUE THREAD

**Issue by degenaro** [oracle/graal#1830]
Downloaded Open Liberty, then attempted to use tracing agent which reports NPE.  See console below.

/opt/graalvm/graalvm-ce-19.2.1/jre/bin/java
-agentlib:native-image-agent=config-output-dir=META-INF/native-image
 -javaagent:/home/degenaro/liberty/start/target/liberty/wlp/bin/tools/ws-javaagent.jar
-Djava.awt.headless=true -Djdk.attach.allowAttachSelf=true -jar
/home/degenaro/liberty/start/target/liberty/wlp/bin/tools/ws-server.jar
defaultServer
Launching defaultServer (Open Liberty
19.0.0.11/wlp-1.0.34.cl191120191031-0300) on OpenJDK 64-Bit GraalVM CE
19.2.1, version 1.8.0_232-20191008104205.buildslave.jdk8u-src-tar--b07
(en_US)[AUDIT   ] CWWKE0001I: The server defaultServer has been launched.
[AUDIT   ] CWWKG0093A: Processing configuration drop-ins resource:
/home/degenaro/liberty/start/target/liberty/wlp/usr/servers/defaultServer/configDropins/overrides/liberty-plugin-variable-config.xml
[AUDIT   ] CWWKZ0058I: Monitoring dropins for applications.
[AUDIT   ] CWWKT0016I: Web application available (default_host):
https://urldefense.proofpoint.com/v2/url?u=http-3A__9.59.151.248-3A9080_ibm_api_&d=DwIBaQ&c=RoP1YumCXCgaWHvlZYR8PZh8Bv7qIrMUB65eapI_JnE&r=CUkXBxBNT_D5N6HMJ5T9Z6rmvNKYsqupcbk72K0lcoQ&m=aqTvd74mJVdMV_xtGG_64vms7nCpoPI3WeX3-YWLX-E&s=qG1fH6RY3gk48Rk5_lvpYibzhlzsszAcDbKTnipjLO8&e= 
[AUDIT   ] CWWKT0016I: Web application available (default_host):
https://urldefense.proofpoint.com/v2/url?u=http-3A__9.59.151.248-3A9080_metrics_&d=DwIBaQ&c=RoP1YumCXCgaWHvlZYR8PZh8Bv7qIrMUB65eapI_JnE&r=CUkXBxBNT_D5N6HMJ5T9Z6rmvNKYsqupcbk72K0lcoQ&m=aqTvd74mJVdMV_xtGG_64vms7nCpoPI3WeX3-YWLX-E&s=ynh90zvGz7fu9gcZIm-otVJHwKV8dc4TMlGt6K7pUgs&e= 
WARNING: Error processing trace entry: java.lang.NullPointerException:
{caller_class=org.jboss.weld.util.reflection.Reflections, result=null,
args=[], function=getEnclosingConstructor, tracer=reflect}
WARNING: Error processing trace entry: java.lang.NullPointerException:
{caller_class=org.jboss.weld.util.reflection.Reflections, result=null,
args=[], function=getEnclosingMethod, tracer=reflect}

**Comment by peter-hofer** [comment]
@degenaro apologies for overlooking this issue. There have been many improvements to the agent since, please try again with a recent release (and ideally with Java 11). If you encounter this issue again, please reopen.
