### ISSUE TITLE
[native-image] - Should IncludeAllTimeZones be defaulted to true?

### ISSUE THREAD

**Issue by jaikiran** [oracle/graal#1833]
Right now, when a native image is created, it includes only a limited number of timezones (`GMT`, `UTC` and the default zone of the build host) in the generated image. The `IncludeAllTimezones` (boolean) option allows the generated image to include all timezones. This, by default, is `false`, which means that not all timezones are included.

During a disucssion here https://github.com/oracle/graal/pull/1819#discussion_r345179617, there was a question if the current default value is worthwhile or whether changing it to default `true`, to include all timezones by default would be more reasonable. A similar discussion is currently going on in Quarkus project https://groups.google.com/forum/#!msg/quarkus-dev/J1afzAhpShI/A5vmUGJLAQAJ

In terms of the change in size when `IncludeAllTimeZones` is set to true, my experiments with the `HelloWorld` example included in the `substratevm` project and even a quickstart from Quarkus project has shown that the size doesn't increase by more than 1MB. 

Would it be reasonable to change the default value of `IncludeAllTimeZones` to true?

**Comment by eginez** [comment]
This is no longer an issue after https://github.com/oracle/graal/commit/03d7d0cb244941f1a2835844b9889bb3d06b003a
