### ISSUE TITLE
com.oracle.svm.core.util.UserError$UserException: Already registered

### ISSUE THREAD

**Issue by zhaolin81** [oracle/graal#1842]
sample project,when i run “mvn package -Pnative”, error occured.

[INFO] [io.quarkus.creator.phase.nativeimage.NativeImagePhase] /opt/graalvm-ce-19.2.1//bin/native-image -J-Djava.util.logging.manager=org.jboss.logmanager.LogManager -H:InitialCollectionPolicy=com.oracle.svm.core.genscavenge.CollectionPolicy$BySpaceAndTime -jar getting-started-1.0-SNAPSHOT-runner.jar -J-Djava.util.concurrent.ForkJoinPool.common.parallelism=1 -H:FallbackThreshold=0 -H:+ReportExceptionStackTraces -H:+PrintAnalysisCallTree -H:-AddAllCharsets -H:EnableURLProtocols=http -H:-SpawnIsolates -H:-JNI --no-server -H:-UseServiceLoaderFeature -H:+StackTrace
[getting-started-1.0-SNAPSHOT-runner:1032]    classlist:  15,931.57 ms
[getting-started-1.0-SNAPSHOT-runner:1032]        setup:     991.55 ms
Error: Already registered: java.lang.reflect.Method.getDefaultValue()
com.oracle.svm.core.util.UserError$UserException: Already registered: java.lang.reflect.Method.getDefaultValue()
        at com.oracle.svm.core.util.UserError.abort(UserError.java:65)
        at com.oracle.svm.core.util.UserError.guarantee(UserError.java:86)
        at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.register(AnnotationSubstitutionProcessor.java:708)
        at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.handleMethodInAliasClass(AnnotationSubstitutionProcessor.java:334)
        at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.handleAliasClass(AnnotationSubstitutionProcessor.java:298)
        at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.handleClass(AnnotationSubstitutionProcessor.java:274)
        at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.init(AnnotationSubstitutionProcessor.java:230)
        at com.oracle.svm.hosted.NativeImageGenerator.createDeclarativeSubstitutionProcessor(NativeImageGenerator.java:875)
        at com.oracle.svm.hosted.NativeImageGenerator.setupNativeImage(NativeImageGenerator.java:824)
        at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:524)
        at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:444)
        at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

**Comment by jaikiran** [comment]
Hello @zhaolin81, do you have a Quarkus application which reproduces this? Maybe you can share that through a github repo, to help reproduce this issue?

**Comment by zhaolin81** [comment]
> Hello @zhaolin81, do you have a Quarkus application which reproduces this? Maybe you can share that through a github repo, to help reproduce this issue?

Here is the github repo, [https://github.com/zhaolin81/getting-started](url)

the project was generated by :

mvn io.quarkus:quarkus-maven-plugin:0.15.0:create \
    -DprojectGroupId=org.acme \
    -DprojectArtifactId=getting-started \
    -DclassName="org.acme.quickstart.GreetingResource" \
    -Dpath="/hello"

**Comment by jaikiran** [comment]
I just gave this project a try with:
```
mvn clean package -Pnative
```
and it builds fine and generates the native image. Which vendor and version of Java are you using? Can you post the output of:

```
echo $JAVA_HOME/bin/java -version
```

**Comment by zhaolin81** [comment]
> I just gave this project a try with:
> 
> ```
> mvn clean package -Pnative
> ```
> 
> and it builds fine and generates the native image. Which vendor and version of Java are you using? Can you post the output of:
> 
> ```
>  $JAVA_HOME/bin/java -version
> ```

Thanks for reply, i rnu this inside docker with image oracle/graalvm-ce.

bash-4.2#  $JAVA_HOME/bin/java -version
openjdk version "1.8.0_232"
OpenJDK Runtime Environment (build 1.8.0_232-20191008104205.buildslave.jdk8u-src-tar--b07)
OpenJDK 64-Bit GraalVM CE 19.2.1 (build 25.232-b07-jvmci-19.2-b03, mixed mode)

bash-4.2# echo $GRAALVM_HOME
/opt/graalvm-ce-19.2.1
bash-4.2# echo $JAVA_HOME
/opt/graalvm-ce-19.2.1

**Comment by jaikiran** [comment]
Hello @zhaolin81, thank you for the details so far. However, I haven't been able to reproduce this with the same verison of GraalVM/Java.
Having said that, the log message you pasted in the first comment in this thread, does indeed seem odd. For example, it is missing certain parameters/options that Quarkus by default passes to the native image generation. These misses itself shouldn't contribute to the issue you are seeing, but that is a sign that something is odd with this setup/environment.

Can you also please paste the output of `mvn -version` from within the container where this is failing? And I think the best thing to do is run:

```
mvn -X clean package -Pnative > build.log
```
and attach that build log to this issue.

**Comment by zhaolin81** [comment]
> Hello @zhaolin81, thank you for the details so far. However, I haven't been able to reproduce this with the same verison of GraalVM/Java.
> Having said that, the log message you pasted in the first comment in this thread, does indeed seem odd. For example, it is missing certain parameters/options that Quarkus by default passes to the native image generation. These misses itself shouldn't contribute to the issue you are seeing, but that is a sign that something is odd with this setup/environment.
> 
> Can you also please paste the output of `mvn -version` from within the container where this is failing? And I think the best thing to do is run:
> 
> ```
> mvn -X clean package -Pnative > build.log
> ```
> 
> and attach that build log to this issue.

I updated my project repo,Please try pull and reproduce ,thank you.

bash-4.2# mvn -version
Apache Maven 3.6.2 (40f52333136460af0dc0d7232c0dc0bcf0d9e117; 2019-08-27T15:06:16Z)
Maven home: /opt/apache-maven-3.6.2
Java version: 1.8.0_232, vendor: Oracle Corporation, runtime: /opt/graalvm-ce-19.2.1/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.4.0-116-generic", arch: "amd64", family: "unix"

**Comment by zhaolin81** [comment]
[build.log](https://github.com/oracle/graal/files/3873052/build.log)

**Comment by jaikiran** [comment]
From the attached log:
```
quarkus.version=0.15.0
```
```
[INFO] --- quarkus-maven-plugin:0.15.0:native-image (default) @ getting-started ---
```
So it looks like it's using quarkus version `0.15.0` instead of the `1.0.0.CR1` (the right version) which you shared in the linked github repo. Can you check and make sure the quarkus version being used in that container build is `1.0.0.CR1` and if it works with that version? 

P.S: At this point, this now looks like a Quarkus (usage) issue than graal VM issue. So maybe we should discuss this in the Quarkus project and sort this out there?

**Comment by zhaolin81** [comment]
> From the attached log:
> 
> ```
> quarkus.version=0.15.0
> ```
> 
> ```
> [INFO] --- quarkus-maven-plugin:0.15.0:native-image (default) @ getting-started ---
> ```
> 
> So it looks like it's using quarkus version `0.15.0` instead of the `1.0.0.CR1` (the right version) which you shared in the linked github repo. Can you check and make sure the quarkus version being used in that container build is `1.0.0.CR1` and if it works with that version?
> 
> P.S: At this point, this now looks like a Quarkus (usage) issue than graal VM issue. So maybe we should discuss this in the Quarkus project and sort this out there?

Hi，@jaikiran

When i change to 1.0.0CR1,it works fine.
I'll close this issue,thanks a lot.
