### ISSUE TITLE
List of tuneable params for Graal

### ISSUE THREAD

**Issue by tomerz90** [oracle/graal#1845]
Where can I find a list of all the tuneable params on Graal?

**Comment by plokhotnyuk** [comment]
@tomerz90 you can use [VM Options Explorer - GraalVM CE 19](https://chriswhocodes.com/graalvm_ce_19_options.html) for that.

**Comment by tomerz90** [comment]
@plokhotnyuk Thanks!

**Comment by tomerz90** [comment]
Is there a metric of how much each influence performance?
Im creating a high performance netty based client for downloads.
I ran the EE version on it and the improvement was crazy (x3-x4), unfortunately thats not an potion for me and with the CE there was no improvement at all.

**Comment by farquet** [comment]
@tomerz90 the list of all options can be retrieved with
```
$GRAALVM_HOME/bin/java -XX:+JVMCIPrintProperties
```
The website given by @plokhotnyuk parses the output of that command to generate the tables.

But please be aware that changing the values of options that are not listed on [that page](https://www.graalvm.org/docs/reference-manual/languages/jvm/#compiler-configuration-on-jvm) are not officially supported and can lead to slowdowns, crashes, long compilation times, etc. So play with them at your own risk.
