### ISSUE TITLE
Graal native image runtime dependencies as shared object

### ISSUE THREAD

**Issue by mryvz** [oracle/graal#1846]
All native images generated by native-image tool contains SubstrateVM bytecode.  Is it possible  create native image runtime dependencies as external shared object so native runnable and shared object modules can share same SubstrateVM bytecode.

Update :
Is it possible to create java module like ( or based ) native image generation system ? Modules can be dependent other native compiled modules and we can reuse them without compiling same bytecode 
myapp.exe
substratevm.dll
openjfx.base.13.dll
openjfx.controls.13.dll
vertx.base.3.8.dll
vertx.web.3.8.dll

**Comment by christianwimmer** [comment]
Currently we have no plans for modular native images. That is difficult because of the aggressive closed-world analysis.
