### ISSUE TITLE
Can't download Graal VM - CE

### ISSUE THREAD

**Issue by suyashjoshi** [oracle/graal#1851]
Download link for GraalVM on the main website is broken. See the "Download" link on this page (https://www.graalvm.org/docs/#graalvm-distributions) ###

**Comment by suyashjoshi** [comment]
<img width="1005" alt="Screen Shot 2019-11-20 at 12 55 45 PM" src="https://user-images.githubusercontent.com/395039/69277668-835a7e80-0b95-11ea-9ec3-05b8a8a494b3.png">

**Comment by thomaswue** [comment]
Thank you for the report!

**Comment by olyagpl** [comment]
Thanks for catching, corrected https://www.graalvm.org/docs.
