### ISSUE TITLE
[website] Downloads page for 19.3 release points to release notes of 19.2

### ISSUE THREAD

**Issue by jaikiran** [oracle/graal#1853]
The download page https://www.graalvm.org/downloads/ has this:
```
The most notable changes between the versions can be found in the release notes. 
```
The "release notes" link is pointing to https://www.graalvm.org/docs/release-notes/19_2/ instead of https://www.graalvm.org/docs/release-notes/19_3/

**Comment by olyagpl** [comment]
Thank you for noticing!
We've updated the link https://www.graalvm.org/downloads 
Olya

**Comment by jaikiran** [comment]
Thank you @olyagpl
