### ISSUE TITLE
java.io.File.getCanonicalPath returns wrong result

### ISSUE THREAD

**Issue by hrj** [oracle/graal#1859]
The canonical path for relative paths seems to be wrong. Tested with `graalvm-ce-java11-19.3.0`

### test.java
```java
class test {
  public static void main(String[] args) throws java.io.IOException {
    System.out.println(new java.io.File("xyz").getCanonicalPath());
  }
}
```

### Output mismatch
```
$ pwd
/home/usr/graalBug
$ javac test.java
$ java test
/home/usr/graalBug/xyz
$ native-image test
$ ./test
/home/usr/.native-image/machine-id-xxx/session-id-xxx/server-id-xxx/xyz
```

**Comment by pquiring** [comment]
Still seeing a similar issue with Version 20.0 (JDK11) on Windows.
Although now it seems all files are relative to the folder the program was compiled in, even if the exe is executed from another folder, moved to another folder (or another PC) which causes file not found exceptions.

**Comment by hrj** [comment]
I tried the same test case with `graal ce 20.1.0` and it passes.

I guess it was fixed as part of https://github.com/oracle/graal/issues/2316

Closing, thanks!
