### ISSUE TITLE
Unsupported type java.lang.StackFrameInfo is reachable

### ISSUE THREAD

**Issue by kaspernielsen** [oracle/graal#1862]
I'm getting the following exception when trying to create a native image for an application using the latest release 19.3.0.
```
Fatal error: com.oracle.svm.hosted.substitute.DeletedElementException: Unsupported type java.lang.StackFrameInfo is reachable
To diagnose the issue, you can add the option --report-unsupported-elements-at-runtime. The unsupported element is then reported at run time when it is accessed the first time.
	at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.lookup(AnnotationSubstitutionProcessor.java:115)
```
Does this mean StackFrameInfo is currently not supported when trying to generate an image?

**Comment by cstancu** [comment]
`java.lang.StackFrameInfo` is currently [`@Delete`ed](https://github.com/oracle/graal/blob/master/substratevm/src/com.oracle.svm.core.jdk11/src/com/oracle/svm/core/jdk/Target_java_lang_StackWalker.java#L294). We have a custom implementation for `java.lang.StackWalker` introduced in https://github.com/oracle/graal/commit/33883b8c61d3d06401bcddaf176c03db139a33aa.
