### ISSUE TITLE
JavaFX applications running on GraalVM 19.3 (11) loose text color

### ISSUE THREAD

**Issue by mipastgt** [oracle/graal#1867]
I have observed that a large JavaFX application seems to work
correctly at first but then suddenly all text on all controls turns white and
white on white or light grey is not really readable anymore. I've never observed
such a behaviour on any other VM before. There is also no error message or
warning associated with this. It just happens.
This is for an application just running on the GraalVM and not via native-image!
Others have reported this same issue on Twitter too, although with a different color.

Some more observations:
This behaviour was observed on a MacBook Pro with Retina display on macOS 10.14.6.
All controls seem to be affected by this problem but a pure Text object, which had its color set explicitly in the code was not affected.
Another observation is that the application is still fully functional and when you work with it, the colors sometimes reappear and then vanish again after a few seconds. It's a mystery.
Up to know I have not been able to reproduce this behaviour in a small test case (just in case somone should ask.)

**Comment by dougxc** [comment]
Hi @mipastgt , is this on GraalVM CE or EE? Does the application behave correctly on OpenJDK 11?

**Comment by mipastgt** [comment]
This was on GraalVM CE and yes, the application runs correctly on OpenJDK 11 (actually on all other VMs ranging from 11 to 14 EA).

**Comment by mipastgt** [comment]
I just ran the test on the EE edition too. The result is technically the same, just the color is different. With the EE edition the switch is to cyan instead of white.
<img width="368" alt="Bildschirmfoto 2019-11-22 um 11 05 32" src="https://user-images.githubusercontent.com/16735714/69416971-1a4f4400-0d18-11ea-8be7-4846883a1c92.png">

**Comment by dougxc** [comment]
This is indeed a very strange failure mode. To help narrow it down, can you please disable the Graal compiler (`-XX:-UseJVMCICompiler`) and see if the problem still occurs.

**Comment by mipastgt** [comment]
Just checked this. Without the above flag I can reliably reproduce the error within a few seconds of operating the app. With the above flag set I cannot reproduce the error anymore.

**Comment by mipastgt** [comment]
As reported here on the openjfx-dev mailing list
https://mail.openjdk.java.net/pipermail/openjfx-dev/2019-November/024091.html
the bug can also be reproduced on Linux.

**Comment by dougxc** [comment]
I think this is going to get very hard to investigate without a reproducer. Are you aware of any free JavaFX apps that we could use to reproduce this? Best of course would be one that you've confirmed it reproduces on.

Until then, the workaround is to use `-XX:-UseJVMCICompiler`.

**Comment by mipastgt** [comment]
Unfortunately I do not yet have such an example and the next few days I will also not be able to search for one due to other responsibilities. So, if someone else should find one in the meantime, please report it here.
Concerning the workaround: Using the GraalVM as a regular VM is of course just the preparation for the next step which is to create a native image and I fear that the workaround will then not be applicable.

**Comment by mipastgt** [comment]
I have found a little program which can reproduce the bug.
1. Compile and run via Maven.
`mvn compile javafx:run`
2. Grab the lower right corner of the window with the mouse
and resize the window for a few seconds. After a while the
text colors should change which reproduces the bug.
I have also included two screen shots before and after the bug shows up.

[SimpleGraalVMBugDemo.zip](https://github.com/oracle/graal/files/3880183/SimpleGraalVMBugDemo.zip)

**Comment by gergo-** [comment]
Thanks for the reproducer @mipastgt . Could you check if running your application with `-Dgraal.GraalArithmeticStubs=false` makes the problem go away?

**Comment by mipastgt** [comment]
Yes, I can confirm that with this option I cannot reproduce the problem. I cross-checked it twice with my full application. This seems to pin-point the root of the problem.

**Comment by mur47x111** [comment]
Hi @mipastgt , would it be possible for you to build Graal and test whether https://github.com/oracle/graal/commit/12f6d0eddb045527767943ef716267c4c751763d addresses the issue?

**Comment by mipastgt** [comment]
@mur47x111 I fear that is a little bit beyond my knowledge and time budget. But if you could point me to a nightly build or so for the macOS-version of the GraalVM, then I would be more than happy to give it a try.

**Comment by dougxc** [comment]
Please re-open if not fixed in the next GraalVM release.

**Comment by mipastgt** [comment]
I can confirm that this bug seems to be fixed in 19.3.0.2. Thanks a lot.
