### ISSUE TITLE
`polyglot` not a valid Windows (64-bit) executable

### ISSUE THREAD

**Issue by veganaize** [oracle/graal#1874]
When trying to run `polyglot` in 64-bit Windows it produces an error in the console, as well as a dialog box, which state that `polyglot` executable is incompatible with Windows.

Console output:

```
C:\graalvm-ce-java11-19.3.0\bin>polyglot
This version of C:\graalvm-ce-java11-19.3.0\bin\polyglot.exe is not compatible w
ith the version of Windows you're running. Check your computer's system informat
ion and then contact the software publisher.
```
GUI output:
![polyglot_error_dialog](https://user-images.githubusercontent.com/7102064/69447730-fdad0f00-0d0b-11ea-8ea7-daebb7735e71.png)

**Comment by boris-spas** [comment]
Tracking internally as Issue GR-20938.

**Comment by fernando-valdez** [comment]
issue has being fixed in later releases
