### ISSUE TITLE
[native-image] native-image-agent does not detect resource bundles

### ISSUE THREAD

**Issue by fhoeben** [oracle/graal#1880]
When I run my programming using `java -agentlib:native-image-agent=config-output-dir=...` the resource bundles that are used (both .properties and .xml) end up in `resource-config.json` as `pattern` below`resources` and not as `name` below `bundles`.

That's unfortunate as I then have to add the bundles manually to my call to `native-image` (using `-H:IncludeResourceBundles=...`)

**Comment by peter-hofer** [comment]
Thank you for your report @fhoeben . Support for resource bundles in the agent is on my agenda.

**Comment by peter-hofer** [comment]
Agent support for resource bundles has been introduced in bd1c10b61cb146e949fef0a1d1b957564328a859.
