### ISSUE TITLE
[native-image] Introduce a flag to ignore all META-INF/native-image

### ISSUE THREAD

**Issue by Sanne** [oracle/graal#1884]
We had some situations in which the contents of the `META-INF/native-image` rules included by a dependency were wrong or conflicting with framework requirements.

It would be great to have a global flag which disables the loading of any such resource, or ignores their content.

In Quarkus the plan would be to:

1. Enable such flag
2. Load such resources ourselves
3. (By default) pass all their content to `native-image`, likely as-is in most cases but this would allow validation, resolving conflicts or override as needed.

Since we will likely want to load all such resources and pass them on, I don't think you would need to make this option too fine-grained. Just disabling to load these would be great.

Thanks in advance!

**Comment by maxandersen** [comment]
@thomaswue you asked to be assigned to this - we don't have triage permissions so you'll have to survive with a comment notification ;)

**Comment by galderz** [comment]
I found myself needing this today and found that it was asked again earlier this year: #2535

**Comment by cstancu** [comment]
Closing this in favor of #2535.
