### ISSUE TITLE
graal 19.2.1 - windows docker native image failed

### ISSUE THREAD

**Issue by gengraphael** [oracle/graal#1896]
**Setup Docker:**
FROM microsoft/dotnet-framework:4.7.1
RUN choco install windows-sdk-7.1 kb2519277 -y
RUN choco install maven --version=3.6.2 -y
RUN choco install graalvm --version=19.2.1 -y
RUN choco install vcredist2010 -y

**Building:**
"C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd"
set JAVA_HOME=C:\tools\openjdk1.8.0_232-jvmci-19.3-b05
set GRAALVM_HOME=c:\GraalVM\graalvm-ce-19.2.1
...
c:\GraalVM\graalvm-ce-19.2.1\bin\native-image.cmd -jar runner.jar  -H:+ReportExceptionStackTraces  --verbose

**Env:**
java -version
openjdk version "1.8.0_232"
OpenJDK Runtime Environment (build 1.8.0_232-20191009144847.buildslave.jdk8u-src-tar--b07)
OpenJDK 64-Bit Server VM (build 25.232-b07-jvmci-19.3-b05, mixed mode)

mvn -version
Apache Maven 3.6.2 (40f52333136460af0dc0d7232c0dc0bcf0d9e117; 2019-08-27T08:06:16-07:00)
Maven home: C:\ProgramData\chocolatey\lib\maven\apache-maven-3.6.2\bin\..
Java version: 1.8.0_232, vendor: Oracle Corporation, runtime: C:\reactor\dbcredential\quarkus\windows_graalvm\tools\openjdk1.8.0_232-jvmci-19.3-b05\jre
Default locale: en_US, platform encoding: Cp1252
OS name: "windows server 2016", version: "10.0", arch: "amd64", family: "windows"

**Result:**
Error: Image build request failed with exit status 1
com.oracle.svm.driver.NativeImage$NativeImageError: Image build request failed with exit status 1
        at com.oracle.svm.driver.NativeImage.showError(NativeImage.java:1447)
        at com.oracle.svm.driver.NativeImage.build(NativeImage.java:1225)
        at com.oracle.svm.driver.NativeImage.performBuild(NativeImage.java:1187)
        at com.oracle.svm.driver.NativeImage.main(NativeImage.java:1146)

**Can i create more output?**
**Is my setup correct?**

Thanks for you advice!

**Comment by gengraphael** [comment]
Hi,

does somebody else have the same issue?

Best regards
Raphael

**Comment by pejovica** [comment]
It's hard to tell based on this output alone, but could you verify that you're using a 64-bit toolchain.

**Comment by gengraphael** [comment]
hi,

yes the docker host is 64 bit!

best regards
Raphael

**Comment by thatsIch** [comment]
You should set `JAVA_HOME` to the same directory as `GRAALVM_HOME`. This is important, that Maven uses the same JDK as GraalVM uses. If you use Maven, add the parameter `-e` to expand the error statements like `mvn -e clean install`

**Comment by wirthi** [comment]
Closing this older GraalVM 19 ticket. If you experience this problem still with a recent GraalVM version, feel free to reopen or create a new ticket.
