### ISSUE TITLE
Question: Release Assets location

### ISSUE THREAD

**Issue by jasonkarns** [oracle/graal#1899]
Prior releases (19.2.1 and before) included their built assets as part of the GitHub Release itself.

![image](https://user-images.githubusercontent.com/119972/69739469-c4a6dd00-1105-11ea-99cb-702ae3e55c84.png)

The current release (19.3.0) doesn't contain any built assets. 
![image](https://user-images.githubusercontent.com/119972/69739509-d5575300-1105-11ea-9392-3cd0b465af0c.png)

However, it does link to _another_ github repo which includes the expected assets. Will this be the procedure moving forward, that assets should only be downloaded from https://github.com/graalvm/graalvm-ce-builds ?

As mentioned in other issues, I maintain a [scraper](https://github.com/nodenv/node-build-update-defs) which builds definitions for [node-build](https://github.com/nodenv/node-build) (for inclusion in [nodenv](https://github.com/nodenv/nodenv))

The most recent release is not being successfully scraped due to the missing assets.

```
$ $(npm bin)/nodenv-update-version-defs --graal -d share/node-build/
Checking for new graal+ce versions
graal+ce-19.3.0 skipped (Error: no source or binaries)
```

Are all future releases expected to be posted to graalvm/graalvm-ce-builds? In other words, should our scraper be pulling from there instead of this repo from this point forward?

**Comment by jasonkarns** [comment]
It's also worth pointing out that the asset filename format has changed between assets released on this repo and those from the graalvm org.

The consistency of the asset names (absent a manifest) is critical for tooling.

**Comment by gilles-duboscq** [comment]
> Are all future releases expected to be posted to graalvm/graalvm-ce-builds? In other words, should our scraper be pulling from there instead of this repo from this point forward?

Correct. We expect future releases to appear on `graalvm/graalvm-ce-builds`.

> It's also worth pointing out that the asset filename format has changed between assets released on this repo and those from the graalvm org.

I assume you mean the addition of `java8`/`java11`. If yes, then indeed we had to break naming to reflect this additional dimension in our release matrix.

**Comment by jasonkarns** [comment]
Cool, thanks for confirming!!

> I assume you mean the addition of `java8`/`java11`. If yes, then indeed we had to break naming to reflect this additional dimension in our release matrix.

Is there any chance that a manifest could be published? For reference, the scraper operates on https://nodejs.org/dist/index.json for node releases (node, nightlies, RCs, and chakra all use the same manifest format)

Not that I think that manifest is the _best_, but it at least gives us a consistent format to scrape from. Pulling from github, (we pull the asset list using github's REST API), all we have is the filename, which is obviously brittle and hard to extract the meta information from reliably.

But I also acknowledge the extra work that would be required and nodenv/node-build _may_ be the only ones attempting to scrape your releases. 😄 🤷‍♂ (And the filename at least does have all the information necessary, as long as it can remain as stable as possible.)

**Comment by gilles-duboscq** [comment]
Yes, we are thinking about a manifest.
Thank you for the reference to the node manifest.
