### ISSUE TITLE
Getting-started-knative with quarkus is not working

### ISSUE THREAD

**Issue by PachoJGaviria** [oracle/graal#1907]
Getting-started-knative with quarkus is not working

**Environment**

- ProductName:	Mac OS X Darwin
- ProductVersion:	10.14.6
- BuildVersion:	18G103
- Model Name: MacBook Pro
- Model Identifier: MacBookPro12,1
- Processor Name: Intel Core i5
- Memory: 8 GB
- openjdk version "11.0.5" 2019-10-15
   OpenJDK Runtime Environment (build 11.0.5+10-jvmci-19.3-b05-LTS)
   OpenJDK 64-Bit GraalVM CE 19.3.0 (build 11.0.5+10-jvmci-19.3-b05-LTS, mixed mode, sharing)
- graalvm         19.3.0       GraalVM Core     
- native-image       19.3.0       Native Image    github.com

**Steps**

- Install GraalVM 19.3.0
- Clone https://github.com/quarkusio/quarkus-quickstarts/tree/master/getting-started-knative
- run ./mvnw test

**Error**
```
[INFO] Running org.acme.quickstart.GreetingResourceTest
[ERROR] Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 1.751 s <<< FAILURE! - in org.acme.quickstart.GreetingResourceTest
[ERROR] testHelloEndpoint Time elapsed: 0.013 s <<< ERROR!
org.junit.jupiter.api.extension.TestInstantiationException: TestInstanceFactory [io.quarkus.test.junit.QuarkusTestExtension] failed to instantiate test class [org.acme.quickstart.GreetingResourceTest]: class io.quarkus.deployment.steps.NativeImageAutoFeatureStep (in unnamed module @0x72e5a8e) cannot access class org.graalvm.nativeimage.impl.RuntimeClassInitializationSupport (in module org.graalvm.sdk) because module org.graalvm.sdk does not export org.graalvm.nativeimage.impl to unnamed module @0x72e5a8e
Caused by: java.lang.IllegalAccessError: class io.quarkus.deployment.steps.NativeImageAutoFeatureStep (in unnamed module @0x72e5a8e) cannot access class org.graalvm.nativeimage.impl.RuntimeClassInitializationSupport (in module org.graalvm.sdk) because module org.graalvm.sdk does not export org.graalvm.nativeimage.impl to unnamed module @0x72e5a8e
```

**Comment by jaikiran** [comment]
Hello @PachoJGaviria, Quarkus doesn't yet support Graal 19.3. There are a couple of PRs open in the Quarkus repo (which is where I think this issue should have been raised) to bring in this support for an upcoming Quarkus release.

**Comment by PachoJGaviria** [comment]
Hi, @jaikiran, Thank you. 👍

**Comment by martijnburger** [comment]
https://github.com/quarkusio/quarkus/issues/5691
