### ISSUE TITLE
'js' language not found with JAR on OpenJDK 8

### ISSUE THREAD

**Issue by Anuken** [oracle/graal#1909]
Creating a simple Gradle-built application JAR that evaluates JS will lead to a "language not found" exception. Running the same application through a Gradle `JavaExec` task **works fine**, for whatever reason. OpenJDK 8 is used for both situations.

### Code
```java
Context.create("js").eval("js", "2+2");
```

### Gradle Script

```gradle

//in dependencies
compile "org.graalvm.js:js:19.3.0
```

Note that I've also tried adding `truffle-api`, `graal-sdk` and `tregex` to the dependencies. This did not change the error. Considering the application executed correctly while running through gradle, I do not think the issue is related to missing dependencies.

### Output

```
> java -jar output.jar
java.lang.IllegalArgumentException: A language with id 'js' is not installed. Installed languages are: [].
	at com.oracle.truffle.polyglot.PolyglotEngineImpl.requirePublicLanguage(PolyglotEngineImpl.java:853)
	at com.oracle.truffle.polyglot.PolyglotContextImpl.requirePublicLanguage(PolyglotContextImpl.java:842)
	at com.oracle.truffle.polyglot.PolyglotContextImpl.eval(PolyglotContextImpl.java:813)
	at org.graalvm.polyglot.Context.eval(Context.java:344)
	at org.graalvm.polyglot.Context.eval(Context.java:370)
        <more application-specific stack trace>
```

### Java Version

```
openjdk version "1.8.0_232-ea"
OpenJDK Runtime Environment (build 1.8.0_232-ea-8u232-b09-0ubuntu1-b09)
OpenJDK 64-Bit Server VM (build 25.232-b09, mixed mode)
```

### Additional Information

This seems to be caused by the fact that `Truffle.getRuntime().getCapability(TruffleLocator.class)` returns `null`. I do not know why this is, but, interestingly, the problem does not occur when I run the application through Gradle.

**Comment by zohar-soul** [comment]
Had the same problem

**Comment by social-uni** [comment]
+1，
Has no one solved this problem yet?

java11
```
<graalvm.version>21.1.0</graalvm.version>


<dependency>
            <groupId>org.graalvm.js</groupId>
            <artifactId>js-scriptengine</artifactId>
            <version>${graalvm.version}</version>
        </dependency>

        <dependency>
            <groupId>org.graalvm.truffle</groupId>
            <artifactId>truffle-api</artifactId>
            <version>${graalvm.version}</version>
        </dependency>

        <dependency>
            <groupId>org.graalvm.sdk</groupId>
            <artifactId>graal-sdk</artifactId>
            <version>${graalvm.version}</version>
        </dependency>

```

**Comment by rsengupta-chwy** [comment]
Any update on this issue? Facing the same with my application.

**Comment by fernando-valdez** [comment]
this issue is no longer present in recent builds

**Comment by syncloop-rnd** [comment]
I am getting the exact same error. It fails when at eval function in the following code.  Using jdk-21.0.6+7. It works on windows but 
          Context ctx=Context.newBuilder("js").allowAllAccess(true).build();
          ctx.eval("","2+2"); // this line fails with error "java.lang.IllegalArgumentException: A language with id 'js' is not installed. Installed languages are: []"

I am getting this issue on Ubuntu OS:

NAME="Ubuntu"
VERSION="20.04.6 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.6 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal


POM Dependencies:

		
		<dependency>
			<groupId>org.graalvm.truffle</groupId>
			<artifactId>truffle-api</artifactId>
			<version>24.1.1</version>
		</dependency>
		
		<dependency>
			<groupId>org.graalvm.js</groupId>
			<artifactId>js-community</artifactId>
			<version>24.1.1</version>
			<type>pom</type>
		</dependency>
		
		<dependency>
			<groupId>org.graalvm.js</groupId>
			<artifactId>js-scriptengine</artifactId>
			<version>24.1.1</version>
		</dependency>
		<dependency>
			<groupId>org.graalvm.polyglot</groupId>
			<artifactId>polyglot</artifactId>
			<version>24.1.1</version>
		</dependency>
