### ISSUE TITLE
release file insufficiently distinguishes java versions

### ISSUE THREAD

**Issue by ekmett** [oracle/graal#1911]
I have a language for which I'd like to support both jdk1.8 and jdk11 builds, more or less automagically depending on where `GRAALVM_HOME` is set.

With the current release file it is rather awkward to tell if we're looking at a `GRAALVM_HOME` that is built with `jdk11` or `jdk1.8`. 

The `release` file names the `GRAALVM_VERSION`, but no `JAVA_VERSION`, forcing me to at best guess that it is java 11 based on the URL of the `component_catalog`, but that strikes me as a particularly brittle distinction to draw.

**Comment by dougxc** [comment]
You can use the standard `java.specification.version` system property, just like [JavaVersionUtil](https://github.com/oracle/graal/blob/a9db7dd44c3a6a37f6805bc93e7c366a201d2e9a/compiler/src/org.graalvm.compiler.serviceprovider/src/org/graalvm/compiler/serviceprovider/JavaVersionUtil.java#L32) does.

**Comment by ekmett** [comment]
I can, but that does mean running a small java program in the middle of another build to get at the information, rather than looking at a nice properties file. 

Currently I might have 2-3 JVMs to work with, one for whatever is being used to run `gradle` itself (often set by IntelliJ), which is what I'd see if I tried accessing `java.specification.version` in my build script, one for wherever the `JAVA_HOME` is actually set, one for whatever is set as `GRAALVM_HOME`, which is where I try to find `gu` when running registered builds of my language project, but otherwise isn't needed now that JDK11 works out of the box with enough options.

**Comment by dougxc** [comment]
Maybe this is a possibility:
```
java -XshowSettings:properties 2>&1 | grep java.specification.version
    java.specification.version = 1.8
```

**Comment by gastaldi** [comment]
Would it be possible to add the JDK version to the `native-image -version` output?

**Comment by jaikiran** [comment]
> Would it be possible to add the JDK version to the native-image -version output?

https://github.com/oracle/graal/pull/2148 contains an implementation of this proposal.

**Comment by ansalond** [comment]
In the [upcoming GraalVM 20.0 release](https://www.graalvm.org/docs/release-notes/version-roadmap/), the GraalVM release file will be a superset of the one of the base JDK. It will therefore contain a `JAVA_VERSION` field.

**Comment by jaikiran** [comment]
I think this is now resolved based on what @ansalond noted as well as https://github.com/oracle/graal/pull/2148 being merged.

**Comment by fernando-valdez** [comment]
Closing this issue as it was resolved
