### ISSUE TITLE
SIGSEGV error when running benchmarks on GraalVM EE 19.3.0

### ISSUE THREAD

**Issue by plokhotnyuk** [oracle/graal#1915]
Got SIGSEGV errors when tried to run benchmarks with sbt-jmh for the master branch of [jsoniter-scala](https://github.com/plokhotnyuk/jsoniter-scala)'s repo. It happened only 2 times for more than 10 attempts immediately before actual forking and running them:
```
$ sbt -java-home /usr/lib/jvm/graalvm-ee-java11 -no-colors 'jsoniter-scala-benchmark/jmh:run -p size=128 -jvmArgsAppend "-XX:-TieredCompilation" -prof perfasm ArrayOfLongsReading.jsoniterScala'
[info] Loading global plugins from /home/andriy/.sbt/1.0/plugins
[info] Loading settings for project jsoniter-scala-build from plugins.sbt ...
[info] Loading project definition from /home/andriy/Projects/com/github/plokhotnyuk/jsoniter-scala/project
[info] Loading settings for project jsoniter-scala from release.sbt,build.sbt,version.sbt ...
[info] Set current project to jsoniter-scala (in build file:/home/andriy/Projects/com/github/plokhotnyuk/jsoniter-scala/)
Processing 2902 classes from /home/andriy/Projects/com/github/plokhotnyuk/jsoniter-scala/jsoniter-scala-benchmark/target/scala-2.13/classes with "reflection" generator
Writing out Java source to /home/andriy/Projects/com/github/plokhotnyuk/jsoniter-scala/jsoniter-scala-benchmark/target/scala-2.13/src_managed/jmh and resources to /home/andriy/Projects/com/github/plokhotnyuk/jsoniter-scala/jsoniter-scala-benchmark/target/scala-2.13/resource_managed/jmh
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007fd62a32339a, pid=5623, tid=5640
#
# JRE version: Java(TM) SE Runtime Environment GraalVM LIBGRAAL_EE_BASH 19.3.0 (11.0.5+10) (build 11.0.5+10-jvmci-19.3-b05-LTS)
# Java VM: Java HotSpot(TM) 64-Bit Server VM GraalVM LIBGRAAL_EE_BASH 19.3.0 (11.0.5+10-jvmci-19.3-b05-LTS, mixed mode, sharing, tiered, jvmci, jvmci compiler, compressed oops, parallel gc, linux-amd64)
# Problematic frame:
# V  [libjvm.so+0xcc339a]  oopDesc* PSPromotionManager::copy_to_survivor_space<false>(oopDesc*)+0x2da
#
# Core dump will be written. Default location: Core dumps may be processed with "/usr/share/apport/apport %p %s %c %d %P" (or dumping to /home/andriy/Projects/com/github/plokhotnyuk/jsoniter-scala/core.5623)
#
# An error report file with more information is saved as:
# /home/andriy/Projects/com/github/plokhotnyuk/jsoniter-scala/hs_err_pid5623.log
[thread 5639 also had an error]
[thread 5641 also had an error]
[thread 5625 also had an error]
#
# If you would like to submit a bug report, please visit:
#   https://bugreport.java.com/bugreport/crash.jsp
#
/opt/sbt-1.3.0/bin/sbt: line 104:  5623 Aborted                 (core dumped) "$@"
```
[hs_err_pid5623.log](https://github.com/oracle/graal/files/3912562/hs_err_pid5623.log)

**Comment by dougxc** [comment]
Hi @plokhotnyuk it appears as though SBT forces the use of the Parallel collector which is not the default in JDK 11. We will look into this failure but you may be able to workaround this by explicitly forcing the VM to use G1 (`-XX:+UseG1GC`).

**Comment by plokhotnyuk** [comment]
@plokhotnyuk Yeap, that is explicitly set for benchmarks [here](https://github.com/plokhotnyuk/jsoniter-scala/blob/master/jsoniter-scala-benchmark/src/main/scala/com/github/plokhotnyuk/jsoniter_scala/benchmark/CommonParams.scala#L18). Parallel collector is a winner in throughput and used a lot for processing batched workload when GC latency is not an issue.

**Comment by tkrodriguez** [comment]
I'm able to reproduce this fairly easy and verification flags indicate that it's a missing card mark on instances of jdk/internal/org/objectweb/asm/Item and java/util/jar/JarFile$1.  Hopefully should be easy to track down.

**Comment by tkrodriguez** [comment]
Some changes in the support for ReduceInitialCardMarks in 11 have broken some assumptions of our bulk allocation code.  -Dgraal.OptBulkAllocaiton=false should disable the problematic code.  The performance impact should be negligable for most programs.

**Comment by XanderAtBackboneSystems** [comment]
I was using native-image today and it seemed that this tools (under certain circumstance) suffers from the same issue with the wrong garbage collector being selected. When adding the option `-J-XX:+UseG1GC` it worked better. 

The circumstances where using the oracle docker image: oracle/graalvm-ce:19.3.0-java11 running in google cloud build on a relative small instance ([n1-standard-1](https://cloud.google.com/compute/docs/machine-types#n1_machine_type)). When using the same docker image on a large instance or on my macbook it choose the correct gc by it self.

Hope this helps solving the issue.

Here is the output:
```
#
# A fatal error has been detected by the Java Runtime Environment:
#
# SIGSEGV (0xb) at pc=0x00007f3b7c6fc6df, pid=23, tid=29
#
# JRE version: OpenJDK Runtime Environment (11.0.5+10) (build 11.0.5+10-jvmci-19.3-b05-LTS)
# Java VM: OpenJDK 64-Bit GraalVM CE 19.3.0 (11.0.5+10-jvmci-19.3-b05-LTS, mixed mode, sharing, tiered, jvmci, jvmci compiler, compressed oops, serial gc, linux-amd64)
# Problematic frame:
# V [libjvm.so+0xbf36df] oopDesc::verify()+0x4f
#
# Core dump will be written. Default location: Core dumps may be processed with "/usr/share/apport/apport %p %s %c %d %P" (or dumping to /workspace/core.23)
#
# An error report file with more information is saved as:
# /workspace/hs_err_pid23.log
#
# If you would like to submit a bug report, please visit:
# http://bugreport.java.com/bugreport/crash.jsp
#
Error: Image build request failed with exit status 134
```

**Comment by dougxc** [comment]
This is fixed by https://github.com/graalvm/labs-openjdk-11/commit/96ba3963b6833c6e2e472bc974f1ae3121172051 and will be in the GraalVM 19.3.1 release.
