### ISSUE TITLE
DynamicProxySupport is not thread safe

### ISSUE THREAD

**Issue by stuartwdouglas** [oracle/graal#1927]
I have seen a random failure in the Quarkus test suite where a JDK proxy was not created. It appears that DynamicProxySupport.addProxyClass is called from multiple threads, but is not thread safe. I think com.oracle.svm.reflect.proxy.DynamicProxySupport#proxyCache needs to be changed to a ConcurrentHashMap.

**Comment by cstancu** [comment]
Thank you for reporting, I will merge the fix soon. You are right `DynamicProxySupport.proxyCache`  can be modified concurrently via `SubstrateGraphBuilderPlugins.interceptProxyInterfaces()`.

**Comment by cstancu** [comment]
Fixed by https://github.com/oracle/graal/commit/a5aa34b2d23a303e879e14512d0f28950dc71013.

**Comment by jaikiran** [comment]
@cstancu, a general question about GraalVM releases - does this fix (that has landed in master branch) end up in 19.3.x releases or should one specifically request them to be backported to 19.3.x, given that master branch appears to be 20.x?

**Comment by gsmet** [comment]
Yes, looks like we will need this one in 19.3.1 if we want to be able to support JDK 11 with GraalVM in Quarkus.

Thanks for considering it.

**Comment by geoand** [comment]
Hopefully we'll be able to catch things like sooner in the future when we introduce Quarkus `master`  / GraalVM `master` tests.

**Comment by cstancu** [comment]
Yes, this fix will be included in 19.3.1. In general, we automatically backport critical fixes like this one, but you can request a backport if you need it.

**Comment by emmanuelbernard** [comment]
Hey @cstancu do you do backports at the last minute or as the upstream fix happen?
It would be great for quarkus to get it as the upstream fix happen so we could test early. 
In our case, your jan release will be just a couple of days before the Quarkus 1.2 if things go as planned so not a lot of time to test before the release.

someone is working on a CI job for Quarkus master on GraalVM master for info.

**Comment by cstancu** [comment]
We usually try to do the backports as the fixes happen. @gilles-duboscq when is the 19.3.1 release branch planned?

**Comment by emmanuelbernard** [comment]
Gilles told me, trying to make it happen in a week or two.
