### ISSUE TITLE
java.rmi does not work due to lack of support for java Serialization

### ISSUE THREAD

**Issue by eginez** [oracle/graal#1935]
Customers might want to use java.rmi. Currently that is not possible since we lack support for serialization.

**Comment by eginez** [comment]
Some example code can be found here: https://github.com/eginez/native-image-examples

**Comment by eginez** [comment]
related to https://github.com/oracle/graal/issues/460

**Comment by vjovanov** [comment]
@eginez can we print a proper error message saying `java.rmi` and serialization are not supported? This should be a substitution of one of the core serialization methods that would throw an `UnsupportedFeatureException` with a detailed explanation.

**Comment by eginez** [comment]
Definitely, that sounds reasonable.

**Comment by rodrigar-mx** [comment]
Serialization support was introduced with [graalvm 21.0.0](https://www.graalvm.org/release-notes/21_0/#2100)
