### ISSUE TITLE
Allow embedder to set a current working directory for Truffle filesystem.

### ISSUE THREAD

**Issue by tzezula** [oracle/graal#1938]
Add `Context.Builder.setCurrentWorkingDirectory` to allow embedder to set a directory used by a `TruffleFile`s to resolve relative paths.

**Comment by chumer** [comment]
I suggest we name it `Context.Builder.currentWorkingDirectory`. We don't use setter names for the builder pattern.

**Comment by tzezula** [comment]
Fixed for GraalVM 20.0 by commit: https://github.com/oracle/graal/commit/78625ae1838e13d62a1d2d37aa593b63b3d870e5
