### ISSUE TITLE
[native-image] Resources in package com.sun are not loaded at build time

### ISSUE THREAD

**Issue by maxum2610** [oracle/graal#1944]
Resources such as com.sun.org.apache.xml.internal.serializer.utils.SerializerMessages, com.sun.org.apache.xml.internal.serializer.utils.output_xml.properties etc. are not loaded at build time because they are in package com.sun and must be available to all modules. 
This cannot be done with an opens or exports directive, but must be done in class LocalizationResourceBundles with a getBundle statement like so:

ResourceBundle.getBundle("com.sun.org.apache.xml.internal.serializer.utils.SerializerMessages", Object.class.getModule() );

See also issue #1648.

**Comment by maxum2610** [comment]
Ignore the com.sun bit. I managed to get it to work by calling the above ResourceBundle.getBundle in a Feature during building, storing in ImageSingleton and substituting the relevant resource calls in the java.xml classes with a call to ImageSingleton.

**Comment by eginez** [comment]
fixed with https://github.com/oracle/graal/commit/563408ea34f8593f488e1b8cd6d7101effb91f2d
