### ISSUE TITLE
[native-agent] Inclusion of lambda classes is not necessary in reflect-config.json.

### ISSUE THREAD

**Issue by aclement** [oracle/graal#1948]
When I run with the agent on my spring app, the created reflect-config.json includes Lambda related entries:
```
{
 "name":"org.springframework.boot.autoconfigure.http.codec.CodecsAutoConfiguration$JacksonCodecConfiguration$$Lambda$340/0x0000000840295c40",
  "allDeclaredFields":true,
  "allDeclaredMethods":true
},
```
then when I start the app I get:
```
WARNING: Could not resolve org.springframework.boot.autoconfigure.http.codec.CodecsAutoConfiguration$JacksonCodecConfiguration$$Lambda$340/0x0000000840295c40 for reflection configuration.
```

Are lambda names stable enough to be included? If I delete these entries it doesn't seem to make any difference to app execution.

**Comment by vjovanov** [comment]
The answer is no. We rename them internally into stable names that this config will not match. I will change this into a bug and rephrase the name. Thanks for reporting!

**Comment by peter-hofer** [comment]
@vjovanov , based on your changed title, is it never necessary to make a lambda (and any of its members) reflectively accessible? Or should we rather use the stable names instead?

**Comment by vjovanov** [comment]
AFAIK Lambdas are never accessed reflectively in native-image. I think we should simply avoid adding them to the config altogether.

**Comment by peter-hofer** [comment]
I'm still curious what happens here because we already filter internal accesses to lambda classes, and shouldn't see this unless filters are turned off (which is not advisable). Do you run code that explicitly calls `getClass` and then `getDeclaredMethods` and `getDeclaredFields` on the lambda object? Is there a relevant use case for that?

**Comment by aclement** [comment]
I'm not sure what has changed but I haven't been seeing them in the reflection config for a little while now. (I don't believe I ever turn the filters off). The agent output has been pretty good lately.

What I did see that scared me a little was lambdas mentioned in the initialization messages:
```
Classes that should be initialized at run time got initialized during image building:
 io.r2dbc.spi.ConstantPool$$Lambda$1/938549709 was unintentionally initialized at build time. io.r2dbc.spi.ConstantPool$$Lambda$1/938549709 has been initialized without the native-image initialization instrumentation and the stack trace can't be tracked. Try marking this class for build-time initialization with --initialize-at-build-time=io.r2dbc.spi.ConstantPool$$Lambda$1/938549709
```
and I don't want to start writing `--initialize-at-build-time=io.r2dbc.spi.ConstantPool$$Lambda$1/938549709` - that sounds fragile. 
In this instance I could get away with specifying initialize-at-build-time for the package `io.r2dbc.spi`.   (I had to push ConstantPool to init at build time because it is being used from a proxy - I know @eginez is looking at proxies not forcing build time init).

**Comment by peter-hofer** [comment]
Thanks for the feedback. Maybe @vjovanov knows what is happening with class initialization here.

**Comment by vjovanov** [comment]
I am fixing this issue now. It should be in next week. I will also try to backport it for 20.1.

**Comment by vjovanov** [comment]
The initialization issue has been fixed. @peter-hofer is the agent bug also fixed so we can close this issue?

**Comment by peter-hofer** [comment]
Lambdas should already be filtered, so I don't know why these entries showed up, but now that they apparently no longer do, I believe we can close this.
