### ISSUE TITLE
Java object message resolution does not handle overloads well

### ISSUE THREAD

**Issue by grddev** [oracle/graal#195]
I would expect that Java interop message handling to dispatch messages in accordance with Java overload resolution rules, but the current implementation just chooses the first candidate with matching name and matching number of arguments.

The current implementation doesn't even work well for single-argument overloads, where (the equivalent of) `System.out.println(0)` could dispatch either to the version with `double` and print `0.0`, or dispatch to the `Object` version and (by chance) do the right thing, or the `String` version that would cause a dispatch error.

Handling overloads with multiple arguments correctly would be even trickier, as the method selection might be ambiguous.

**Comment by jtulach** [comment]
Can you formulate your request in form of unit test please? I probably see the point, but it is always easier to get a failing test. This could be a [good starting point](https://github.com/graalvm/truffle/blob/master/truffle/com.oracle.truffle.api.interop.java.test/src/com/oracle/truffle/api/interop/java/test/JavaInteropTest.java).

**Comment by grddev** [comment]
By adding methods like

```java
public String overloads(double x) { return "double"; }
public String overloads(int x) { return "int"; }
public String overloads(Object x) { return "Object"; }
public String overlaods(String x) { return "String"; }
```

and similar signatures to the `XYPlus` interface, you can add tests like:

```java
assertEquals("double", xyp.overloads(0.0));
assertEquals("int", xyp.overloads(0));
assertEquals("Object", xyp.overloads(new Object()));
assertEquals("String", xyp.overloads("foo"));
```

The rules when multiple arguments are involved are more complicated, especially when taking varargs-methods into account. See https://docs.oracle.com/javase/specs/jls/se7/html/jls-15.html#jls-15.12 for details.

**Comment by chumer** [comment]
Since 0.32, Java interop overloads are now properly supported. It is documented here:
http://www.graalvm.org/sdk/javadoc/org/graalvm/polyglot/Context.html#asValue-java.lang.Object-

See "Mapping to Java methods and fields".
