### ISSUE TITLE
Add llvm platform specific shadowed jar for AArch64

### ISSUE THREAD

**Issue by tshull226** [oracle/graal#1951]
Currently it is not possible to use the llvm backend of native-image while running on a AArch64 machine due to the lack of a llvm platform specific shadowed jar at https://lafo.ssw.uni-linz.ac.at/pub/graal-external-deps/native-image/.

Can this please be added?

**Comment by vjovanov** [comment]
Thanks for reporting! @loicottet can we add the shadowed JAR for AArch64 as well?

**Comment by loicottet** [comment]
This is planned with the switch to JavaCPP 1.5.2, which should be merged fairly soon.

**Comment by vjovanov** [comment]
Is this done @loicottet ?

**Comment by loicottet** [comment]
Yes, this is merged. Keep in mind that compiling on AArch64 still requires a custom-built llc binary until we switch to our modified LLVM toolchain, which is currently under review.
