### ISSUE TITLE
[native-image] agent misses a class for reflection that needs manually adding

### ISSUE THREAD

**Issue by aclement** [oracle/graal#1958]
Possibly another case of whatever is happening in #1940. I am running a spring app with the agent, it fails to add a type to the reflect-config.json and the app won't run until I add it. The class that is missing is: `org.springframework.web.reactive.HandlerResult`.

To recreate:
```
git clone git@github.com:spring-projects-experimental/spring-graal-native.git
git checkout upgrade_19_3
cd spring-graal-native/spring-graal-native-feature
mvn clean package
cd ../spring-graal-native-samples/webflux-netty/agent
Run `./1prepare.sh`
Run `. ./2setcp.sh`
Run `../../../3runWithAgent.sh` // this bit is producing the bad data...
Edit graal/META-INF/native-image/resource-config.json and replace all the $ with '.' (this is a separate bug I have open). (e.g. :1,$ s/\$/\./g in vi)
Run `../../../4compile.sh`
Run `./wn`
This will fail.
Edit graal/META-INF/native-image/reflect-config.json and add (on line 2):
{"name":"org.springframework.web.reactive.HandlerResult"},
Now re-run `../../../4compile.sh`
Run `./wn`
It will start OK
```

**Comment by peter-hofer** [comment]
I commented on #1940 with my observations. Could this also apply here? Also, how did you find out that `HandlerResult` is missing?

**Comment by aclement** [comment]
I saw that comment Peter, yes it is the same thing! The `OnWebApplicationCondition` calls `ClssNameFilter.isPresent()` which calls `resolve`.  You make a good observation here too:

> how did you find out that HandlerResult is missing?
It is a real nightmare to find these problems because the manifestation can be so weird.  The lack of that class being around means a piece of configuration conditional on it existing doesn't fire and you can see a seemingly somewhat unrelated error. In my case I have seen so many I can dig through it a little more quickly and here I could run the app with `--debug` to get a bean output report showing me why a particular bean wasn't created and following that chain of what didn't happen I can find which condition check failed, check the impl of that and see what it was looking for.

**Comment by aclement** [comment]
But in more cryptic cases I have to compare the agent output to the feature output and spot the differences...

**Comment by peter-hofer** [comment]
Closing because #1940 is fixed. Please give us feedback on #1940 on whether you believe this is ready to be enabled by default now.
