### ISSUE TITLE
RegisterDumper for AArch64 Darwin/ios/android

### ISSUE THREAD

**Issue by johanvos** [oracle/graal#1959]
The RegisterDumper feature currently distinguishes between 3 options:
1. amd64
2. aarch64
3. darwin

The first 2 options also contain linux-specific code, the 3th option has AMD64 specific code. Hence, it is not trivial to add AArch64-specific Darwin code (which is the combo used by iOS).

**Comment by johanvos** [comment]
A workaround (which doesn't do register dumps) is in PR #1960

**Comment by vjovanov** [comment]
CC @loicottet

**Comment by loicottet** [comment]
Register dumpers are both target-specific by their purpose and OS-specific by their implementation, so I think there should be four of those, renaming 1, 2 and 3 to linux-amd64, linux-aarch64, and darwin-amd64 respectively, and adding darwin-aarch64 for iOS.

**Comment by johanvos** [comment]
I agree with that. It's a bigger refactory though, as the current directory structure under posix requires the darwin-aarch64 to go either under aarch64 or darwin.
Apart from that, there is also android-aarch64 which is *almost* linux-aarch64 but not 100%. Do we need a separate Platform for that?

**Comment by vjovanov** [comment]
I would say that if the difference is only minor and it is more convenient to go with a few simple conditionals we can go with a single platform.
