### ISSUE TITLE
-XX:+EagerJVMCI javax.management.InstanceAlreadyExistsException: org.graalvm.compiler.hotspot:type=HotSpotGraalRuntime_VM

### ISSUE THREAD

**Issue by spangaer** [oracle/graal#1961]
When starting `graalvm-ce-java8-19.3.0` on linux with option `-XX:+EagerJVMCI`  JMX exception is printed to std-out.
Full sequence of options:
` -Xmx2048m -Xms2m -Xss1m -XX:+UseG1GC -XX:+DoEscapeAnalysis -XX:CompileThreshold=1000 -XX:+UseCompressedOops -XX:MaxInlineLevel=31 -XX:MetaspaceSize=32m -XX:MaxMetaspaceSize=256m -XX:ReservedCodeCacheSize=256m -XX:MaxDirectMemorySize=275m -Dcom.sun.management.jmxremote -XX:+EagerJVMCI`

(I know some might be ignored by Graal)
Full exception
```
[Use -Dgraal.LogFile=<path> to redirect Graal log output to a file.]
javax.management.InstanceAlreadyExistsException: org.graalvm.compiler.hotspot:type=HotSpotGraalRuntime_VM
        at com.sun.jmx.mbeanserver.Repository.addMBean(Repository.java:437)
        at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerWithRepository(DefaultMBeanServerInterceptor.java:1898)
        at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerDynamicMBean(DefaultMBeanServerInterceptor.java:966)
        at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerObject(DefaultMBeanServerInterceptor.java:900)
        at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerMBean(DefaultMBeanServerInterceptor.java:324)
        at com.sun.jmx.mbeanserver.JmxMBeanServer.registerMBean(JmxMBeanServer.java:522)
        at org.graalvm.compiler.hotspot.management.libgraal.runtime.SVMHotSpotGraalRuntimeMBean$Factory.process(SVMHotSpotGraalRuntimeMBean.java:548)
        at org.graalvm.compiler.hotspot.management.libgraal.runtime.SVMHotSpotGraalRuntimeMBean$Factory.poll(SVMHotSpotGraalRuntimeMBean.java:521)
        at org.graalvm.compiler.hotspot.management.libgraal.runtime.SVMHotSpotGraalRuntimeMBean$Factory.run(SVMHotSpotGraalRuntimeMBean.java:477)

```
I guess there's some race conditions in the JMX init.

**Comment by dougxc** [comment]
Can you please see if this still happens when you disable libgraal with `-XX:-UseJVMCINativeLibrary`.

**Comment by spangaer** [comment]
Aha, the error is indeed no longer printed.

I might have guessed that one. The `-XX:+EagerJVMCI` flag originates from a Windows context, where it looks to have favorable effects. Due to the lack of that native library I guess.

A bug none the less of course, just not a critical one :wink:

**Comment by spangaer** [comment]
This discussion, some benchmarking blog posts, the benchmark leading to the above issue and some deployments got me thinking.

I observe that running GraalVM Linux, which defaults to native JVMCI, leads to an increase in memory usage of about 200 MB. Studying the composition of the distribution, combined with how the native-image stuff works, seems to point at that being the cost of the SubstrateVM needed to run the Graal Native code. 

And indeed, when I run the same benchmark, this time comparing Graal Java with Graal SVM, using those two flags `-XX:+EagerJVMCI -XX:-UseJVMCINativeLibrary`, I effectively improve my memory load by 100-200 MB, on par or better than C1/C2, while I only loose 2% in performance. This while both Graals gain 10-20 %  over C1/C2 (AdoptJDK JRE), for running this Scala code benchmark.

That 200 MB might be a bargain when running multi-GB heaps, when running a 300-500 MB heap, that is a big cost. It also seems to step away from the eat-your-own-dog-food principle. In a situation where we have a HotSpot JVM, why do we really need a SubstrateVM next to it?

Given that, **shouldn't the default be inverted?** So allowing to enable Graal SVM instead of needing to disable it.

**Comment by dougxc** [comment]
We are working on addressing the memory usage of libgraal. The idea is to have each libgraal compiler thread be in a separate [isolate](https://medium.com/graalvm/isolates-and-compressed-references-more-flexible-and-efficient-memory-management-for-graalvm-a044cc50b67e). This means we can discard isolates when the compiler thread is idle, completely releasing the memory back to the system. During this process, we will also tune the heap size of each libgraal isolate.

We cannot invert the default value for `UseJVMCINativeLibrary` as it avoids all the warm up issues of jargraal. We're confident that we can address any issues related to libgraal such that there's no reason to use jargraal (apart from debugging Graal itself). In addition to the memory issue, we're also working on making native images have peak performance on par with normal JVM execution. In terms of libgraal, this will mean faster compilation times. Other plans for libgraal are mention at the bottom of [this article](https://medium.com/graalvm/libgraal-graalvm-compiler-as-a-precompiled-graalvm-native-image-26e354bee5c).

**Comment by spangaer** [comment]
Well, I can't really oppose faster and if it exhibits memory behavior as shown in the isolates post that would be swell.

On the other hand, it does feel like I'm somewhat more in control with jargraal, e.g. by controlling both the heap size and the headroom left on top of that (for stacks, meta and code cache). Other then the profile pollution your blog post seems to agree, concerning the state of the art.

While my Graal experience will be insignificant compared to that of the Graal team. It seems to accelerate at rate which is perfectly acceptable  (any chance the `-XX:CompileThreshold=1000` is a help there?). The way I've always understood HotSpot I don't get peak performance the very first second. But for something that runs a couple of minutes to years, that's fine.

I'd also guess most JDK class profiles will be quite polluted in server applications anyway.

For now, when applied, it looks like I succeeded in slashing 120-130 MB(?) per java process, while I should still get a ~15% speedup. So at the moment I'm glad to at least have the possibility to use jargraal instead.

**Comment by dougxc** [comment]
I would think that you can tune the heap size *for your app* better with libgraal given that with jargraal, it's hard to predict its heap usage.

Wrt profile pollution, if you are deploying in a multi-tenant server context, then indeed profile pollution is something you just have to accept. However, there are many other scenarios where the main source of profile pollution would be coming from jargraal.

In any case, you can continue to use `-XX:-UseJVMCINativeLibrary` as a workaround until the memory issue of libgraal is resolved.

**Comment by tzezula** [comment]
Fixed during rewrite to multi isolate libgraal.
