### ISSUE TITLE
Clear AArch64 PR Backlog

### ISSUE THREAD

**Issue by teshull** [oracle/graal#1964]
There seems to be a substantial backlog of old compiler optimization PRs submitted by Arm which have been yet to be merged, including:
#884 
#1059
#1193 
#1797 
#1278 

Is there anything we (Arm) or others can do to help expedite merging and/or reaching a resolution on these PRs?

**Comment by dougxc** [comment]
Hi @tshull226 , we will give these issues immediate attention.

**Comment by tshull226** [comment]
Great! Thank you @dougxc
