### ISSUE TITLE
[native-image] Invalid or corrupt jarfile svm-hosted-native-darwin-amd64-19.3.0.tar.gz

### ISSUE THREAD

**Issue by maxum2610** [oracle/graal#1974]
/Library/Java/JavaVirtualMachines/graalvm-ce-java11-19.3.0/Contents/Home/bin/native-image --report-unsupported-elements-at-runtime -Djdk.internal.lambda.eagerlyInitialize=false -H:+ExitAfterRelocatableImageWrite -H:TempDirectory=/Users/brunoposthuma/WORK/client-samples-master/Maven/HelloFXML/target/client/x86_64-darwin/gvm/tmp -H:+SharedLibrary -H:+AddAllCharsets -H:EnableURLProtocols=http,https -H:ReflectionConfigurationFiles=/Users/brunoposthuma/WORK/client-samples-master/Maven/HelloFXML/target/client/x86_64-darwin/gvm/reflectionconfig-x86_64-darwin.json -H:JNIConfigurationFiles=/Users/brunoposthuma/WORK/client-samples-master/Maven/HelloFXML/target/client/x86_64-darwin/gvm/jniconfig-x86_64-darwin.json -H:+PrintAnalysisCallTree -H:IncludeResources=.*/.*frag$ -H:IncludeResources=.*/.*fxml$ -H:IncludeResources=.*/.*css$ -H:IncludeResources=.*/.*gls$ -H:IncludeResources=.*/.*ttf$ -H:IncludeResources=.*/.*xml$ -H:IncludeResources=.*/.*png$ -H:IncludeResources=.*/.*jpg$ -H:IncludeResources=.*/.*jpeg$ -H:IncludeResources=.*/.*gif$ -H:IncludeResources=.*/.*bmp$ -H:IncludeResources=.*/.*license$ -H:IncludeResources=.*/.*json$ -H:IncludeResources=.*frag$ -H:IncludeResources=.*fxml$ -H:IncludeResources=.*css$ -H:IncludeResources=.*gls$ -H:IncludeResources=.*ttf$ -H:IncludeResources=.*xml$ -H:IncludeResources=.*png$ -H:IncludeResources=.*jpg$ -H:IncludeResources=.*jpeg$ -H:IncludeResources=.*gif$ -H:IncludeResources=.*bmp$ -H:IncludeResources=.*license$ -H:IncludeResources=.*json$ -H:IncludeResourceBundles=hellofx.hello,com/sun/javafx/scene/control/skin/resources/controls,com.sun.javafx.tk.quantum.QuantumMessagesBundle -Dsvm.platform=org.graalvm.nativeimage.Platform$DARWIN_AMD64 -cp /Users/brunoposthuma/WORK/client-samples-master/Maven/HelloFXML/target/classes:/Users/brunoposthuma/.m2/repository/org/graalvm/compiler/compiler/19.3.0/compiler-19.3.0.jar:/Users/brunoposthuma/.m2/repository/org/graalvm/nativeimage/objectfile/19.3.0/objectfile-19.3.0.jar:/Users/brunoposthuma/.m2/repository/org/graalvm/nativeimage/pointsto/19.3.0/pointsto-19.3.0.jar:/Users/brunoposthuma/.m2/repository/org/graalvm/nativeimage/svm/19.3.0/svm-19.3.0.jar:/Users/brunoposthuma/.m2/repository/org/graalvm/nativeimage/svm-hosted-native-darwin-amd64/19.3.0/svm-hosted-native-darwin-amd64-19.3.0.tar.gz:/Users/brunoposthuma/.m2/repository/org/graalvm/nativeimage/svm-hosted-native-linux-amd64/19.3.0/svm-hosted-native-linux-amd64-19.3.0.tar.gz:/Users/brunoposthuma/.m2/repository/org/graalvm/nativeimage/svm-hosted-native-windows-amd64/19.3.0/svm-hosted-native-windows-amd64-19.3.0.tar.gz:/Users/brunoposthuma/.m2/repository/org/graalvm/sdk/graal-sdk/19.3.0/graal-sdk-19.3.0.jar:/Users/brunoposthuma/.m2/repository/org/graalvm/truffle/truffle-api/19.3.0/truffle-api-19.3.0.jar:/Users/brunoposthuma/.m2/repository/org/graalvm/truffle/truffle-nfi/19.3.0/truffle-nfi-19.3.0.jar:/Users/brunoposthuma/.m2/repository/org/graalvm/truffle/truffle-nfi-native-darwin-amd64/19.3.0/truffle-nfi-native-darwin-amd64-19.3.0.tar.gz:/Users/brunoposthuma/.m2/repository/org/graalvm/truffle/truffle-nfi-native-linux-aarch64/19.3.0/truffle-nfi-native-linux-aarch64-19.3.0.tar.gz:/Users/brunoposthuma/.m2/repository/org/graalvm/truffle/truffle-nfi-native-linux-amd64/19.3.0/truffle-nfi-native-linux-amd64-19.3.0.tar.gz:/Users/brunoposthuma/.m2/repository/org/openjfx/javafx-base/13.0.1/javafx-base-13.0.1-mac.jar:/Users/brunoposthuma/.m2/repository/org/openjfx/javafx-base/13.0.1/javafx-base-13.0.1.jar:/Users/brunoposthuma/.m2/repository/org/openjfx/javafx-controls/13.0.1/javafx-controls-13.0.1-mac.jar:/Users/brunoposthuma/.m2/repository/org/openjfx/javafx-controls/13.0.1/javafx-controls-13.0.1.jar:/Users/brunoposthuma/.m2/repository/org/openjfx/javafx-fxml/13.0.1/javafx-fxml-13.0.1-mac.jar:/Users/brunoposthuma/.m2/repository/org/openjfx/javafx-fxml/13.0.1/javafx-fxml-13.0.1.jar:/Users/brunoposthuma/.m2/repository/org/openjfx/javafx-graphics/13.0.1/javafx-graphics-13.0.1-mac.jar:/Users/brunoposthuma/.m2/repository/org/openjfx/javafx-graphics/13.0.1/javafx-graphics-13.0.1.jar hellofx.HelloFXML --verbose

Error: Invalid or corrupt jarfile /Users/brunoposthuma/.m2/repository/org/graalvm/nativeimage/svm-hosted-native-darwin-amd64/19.3.0/svm-hosted-native-darwin-amd64-19.3.0.tar.gz
Caused by: java.util.zip.ZipException: zip END header not found
com.oracle.svm.driver.NativeImage$NativeImageError: Invalid or corrupt jarfile /Users/brunoposthuma/.m2/repository/org/graalvm/nativeimage/svm-hosted-native-darwin-amd64/19.3.0/svm-hosted-native-darwin-amd64-19.3.0.tar.gz
	at com.oracle.svm.driver.NativeImage.showError(NativeImage.java:1486)
	at com.oracle.svm.driver.NativeImage.processJarManifestMainAttributes(NativeImage.java:948)
	at com.oracle.svm.driver.NativeImage.processManifestMainAttributes(NativeImage.java:935)
	at com.oracle.svm.driver.NativeImage.addImageClasspathEntry(NativeImage.java:1407)
	at com.oracle.svm.driver.NativeImage.addCustomImageClasspath(NativeImage.java:1377)
	at com.oracle.svm.driver.DefaultOptionHandler.processClasspathArgs(DefaultOptionHandler.java:230)
	at com.oracle.svm.driver.DefaultOptionHandler.consume(DefaultOptionHandler.java:103)
	at com.oracle.svm.driver.NativeImage$NativeImageArgsProcessor.apply(NativeImage.java:1326)
	at com.oracle.svm.driver.NativeImage.processNativeImageArgs(NativeImage.java:1526)
	at com.oracle.svm.driver.NativeImage.completeImageBuild(NativeImage.java:988)
	at com.oracle.svm.driver.NativeImage.build(NativeImage.java:1252)
	at com.oracle.svm.driver.NativeImage.performBuild(NativeImage.java:1222)
	at com.oracle.svm.driver.NativeImage.main(NativeImage.java:1181)
	at com.oracle.svm.driver.NativeImage$JDK9Plus.main(NativeImage.java:1665)
Caused by: java.util.zip.ZipException: zip END header not found
	at java.util.zip.ZipFile$Source.zerror(ZipFile.java:1535)
	at java.util.zip.ZipFile$Source.findEND(ZipFile.java:1436)
	at java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1443)
	at java.util.zip.ZipFile$Source.<init>(ZipFile.java:1274)
	at java.util.zip.ZipFile$Source.get(ZipFile.java:1237)
	at java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:727)
	at java.util.zip.ZipFile$CleanableResource.get(ZipFile.java:52)
	at java.util.zip.ZipFile.<init>(ZipFile.java:247)
	at java.util.zip.ZipFile.<init>(ZipFile.java:177)
	at java.util.jar.JarFile.<init>(JarFile.java:346)
	at java.util.jar.JarFile.<init>(JarFile.java:317)
	at java.util.jar.JarFile.<init>(JarFile.java:283)
	at com.oracle.svm.driver.NativeImage.processJarManifestMainAttributes(NativeImage.java:940)
	... 12 more

The file:

/Users/brunoposthuma/.m2/repository/org/graalvm/nativeimage/svm-hosted-native-darwin-amd64/19.3.0/svm-hosted-native-darwin-amd64-19.3.0.tar.gz

exists and is valid, and can be extracted no problem.

I'm using the folowing maven dependencies:

        <dependency>
            <groupId>org.graalvm.nativeimage</groupId>
            <artifactId>svm</artifactId>
            <version>19.3.0</version>
        </dependency>
        <dependency>
            <groupId>org.graalvm.sdk</groupId>
            <artifactId>graal-sdk</artifactId>
            <version>19.3.0</version>
        </dependency>
        <dependency>
            <groupId>org.graalvm.nativeimage</groupId>
            <artifactId>pointsto</artifactId>
            <version>19.3.0</version>
         <dependency>

which are dependent on svm-hosted-native-darwin-amd64-19.3.0.tar.gz

Any ideas on how I can solve this or a possible work-around? 

java -version
openjdk version "11.0.5" 2019-10-15
OpenJDK Runtime Environment (build 11.0.5+10-jvmci-19.3-b05-LTS)
OpenJDK 64-Bit GraalVM CE 19.3.0 (build 11.0.5+10-jvmci-19.3-b05-LTS, mixed mode, sharing)

System Version:	macOS 10.14.5 (18F132)
Kernel Version:	Darwin 18.6.0

**Comment by olpaw** [comment]
@maxum2610 I cannot reproduce the problem. Building e.g. the maven examples we have at https://github.com/graalvm/graalvm-demos/tree/master/native-image-configure-examples works perfectly fine on OSX with [graalvm-ce-java11-darwin-amd64-19.3.0.tar.gz](https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-19.3.0/graalvm-ce-java11-darwin-amd64-19.3.0.tar.gz) as your `JAVA_HOME`.

If you can still reproduced the issue please create a reproducer and reopen the issue,
