### ISSUE TITLE
Cannot corelate Context object to Value.getContext()

### ISSUE THREAD

**Issue by pmlopes** [oracle/graal#1978]
In order to ensure polyglot `js` code can be used across several threads, I'm creating a `Context` for each thread. I keep the contexts on a java Map where I can associate the `Context` to the right `Thread`.

Now the next step is allowing objects to jump across contexts, to do this, when an object tries to go over I'm trying to:

1. Get context from the `Value` object with `value.getContext()`
2. Lookup the context on the java Map
3. Enqueue a task to serialize the object on the right thread
4. Deserialize the object back on the target thread

My current problem is that I can't match `Value.getContext()` to the entries on the Map. I know the objects are different as the context from the value cannot close the context for example, but shouldn't it have the same `equals` as the base `Context` where the value was created?

**Comment by chumer** [comment]
Both the creator and the current context of a value should be equal. At least thats how I tried to implement it. Can you provide a reproducer?

Can you `Context.enter` and `Context.leave` explicitly on the thread and then use `Context.getCurrent()` instead?

**Comment by pmlopes** [comment]
Sorry, my mistake, the equality check is correct, I was putting the context as the key on a map but doing the lookup using the value object instead.
