### ISSUE TITLE
Buliding Mongonaut required an extra bit of initialization config

### ISSUE THREAD

**Issue by vjovanov** [oracle/graal#1981]
This config should be verified and pushed to the micronaut repo. To reproduce follow instructions at 
https://github.com/dekstroza/mongonaut

And try to build a native image. The error shows that it is necessary to add: 
```
--initialize-at-build-time=io.micrometer.shaded.org.pcollections
```
to the command.  To make micronaut work at runtime it is necessary to add: 
```
--initialize-at-run-time="io.micronaut.configuration.mongo.reactive.test.AbstractMongoProcessFactory,com.mongodb.UnixServerAddress,com.mongodb.internal.connection.SnappyCompressor,io.micronaut.tracing.brave.BraveTracerFactory,io.micronaut.tracing.brave.instrument.http.HttpTracingFactory,io.micronaut.tracing.brave.log.Slf4jCurrentTraceContextFactory,io.micronaut.tracing.brave.sender.HttpClientSenderFactory,io.micronaut.tracing.instrument.rxjava.RxJava1TracingInstrumentation" \
--initialize-at-build-time=io.micrometer.core,io.micrometer.prometheus,io.micrometer.shaded.org.pcollections
```

**Comment by jkremser** [comment]
wrt the metrics part: I was hitting the similar issue 2 days ago w/ micronaut @ version `1.2.0` and updating to `1.2.5` helpled so I will try to reproduce the issue w/ that repo https://github.com/dekstroza/mongonaut with newer version of micronaut (currently it's `1.2.2`)

However there are more things than metrics, so I guess I need to open a PR to that repo anyway.

**Comment by jkremser** [comment]
Ok so I was wrong, the project was already on `micronaut@1.2.8`, I will try to move these build properties to upstream projects to their configs for native image:

* first pr - https://github.com/micronaut-projects/micronaut-mongodb/pull/17

**Comment by jkremser** [comment]
other two:
* https://github.com/mongodb/mongo-java-driver/pull/527 (for `com.mongodb.UnixServerAddress`,`com.mongodb.internal.connection.SnappyCompressor`)
* https://github.com/micronaut-projects/micronaut-core/pull/2504/files (for `io.micronaut.tracing.*`)

**Comment by jkremser** [comment]
and last 2:
* https://github.com/micrometer-metrics/micrometer/pull/1749
* https://github.com/hrldcpr/pcollections/pull/80

**Comment by vjovanov** [comment]
Has this been fixed?

**Comment by jkremser** [comment]
yes, the issue can be closed now. However, it obviously requires also new releases of all the upstream libraries (where the PRs were done) and then bumping the corresponding versions in the mongonaut for the changes to land in there.
