### ISSUE TITLE
Package `javax.xml` needs to be full supported by Native Image

### ISSUE THREAD

**Issue by vjovanov** [oracle/graal#1982]
It is necessary to supply the correct reflection config and verify that all the `javax.xml` tests pass. 

Furthermore, it is very important to see if initialization at build time is valid for all the classes in `javax.xml`.

**Comment by vjovanov** [comment]
We need to run all of the `javax.xml` tests that we can find (e.g., in the JCK or in [`jtreg`](https://openjdk.java.net/jtreg/index.html)) with the agent for JDK 8 and JDK 11. Then we need to fuse those configs into a single file that we will include whenever an element from `java.xml` is detected by analysis.

In our test suite we should add all the relevant tests that we find and run them daily.

@peter-hofer is the agent support for a subset of the JDK ready?

**Comment by peter-hofer** [comment]
@vjovanov Support for filter lists in the agent has been merged. We still need to come up with a reasonably fine-grained filter list to use as the default in the future. Have you looked into that already?

**Comment by vjovanov** [comment]
I think the right approach is to start with a small subset that we certainly support. Then we can augment this on a case-by-case basis. In general, the libraries that we fully support should be filtered out.

Do you have a document or comment describing how to set up a filter in the agent so @arodionov can use it for this issue?

**Comment by peter-hofer** [comment]
@vjovanov I'm working on it.

**Comment by thomaswue** [comment]
Was this merged or is this still open and should we retarget to a different milestone?

**Comment by vjovanov** [comment]
This was merged.
