### ISSUE TITLE
C Parser to create a ArchUnit for C

### ISSUE THREAD

**Issue by stefaneicher** [oracle/graal#1986]
Hi you may can help me with my idea.
I would like to have a archunit https://www.archunit.org/ for c (optional for c++).
Therefore I am looking for a C-File Parser of which I can access an AST.

Do you have some hint and tip whether I can use some parts of GraalVM for that?

Some thins what i would like:
- get function names
- get function parameter
- variable name types ...
- File name
- ....

Regards Stefan

**Comment by johnbanq** [comment]
GraalVM's support for C is by interpreting the LLVM bitcode generated by compiler, which have little to do with C's syntax.
I think you should look into clang or ANTLR, which might help you in parsing C and hacking with the AST.

**Comment by dougxc** [comment]
As mentioned above, GraalVM does not include any useful technology for parsing C sources.

**Comment by stefaneicher** [comment]
Hi John and Duglas, Thanks for your help! I will have a look at ANTLR. Regards Stefan
