### ISSUE TITLE
NPE mac osx travis ci

### ISSUE THREAD

**Issue by Christewart** [oracle/graal#1987]
org.graalvm.compiler.java.BytecodeParser$BytecodeParserError: java.lang.NullPointerException

https://travis-ci.org/bitcoin-s/bitcoin-s/jobs/624195685#L553

Introduced when upgrading to scala 2.13.1 here:

https://github.com/bitcoin-s/bitcoin-s/pull/747

**Comment by dougxc** [comment]
What version of GraalVM are you using? That looks like a somewhat old version as the `guardIntrinsic` method was removed about 6 months ago (fd44f1a1f68debdd3822540a2d4999acad947eca).

**Comment by dougxc** [comment]
Please re-open if problem still exists.
