### ISSUE TITLE
[native-image] Classpath not honored when adding resources

### ISSUE THREAD

**Issue by ozppupbg** [oracle/graal#1988]
Hello,

I have an application, which reads its version information from the META-INF/MANIFEST.MF file. I added this file to the image resources, but the file I get at runtime is not from my jar.

I checked the resource inclusion with the option "-H:Log=registerResource:" and see 5 or 6 MANIFEST.MF files added.
Of course the last one wins and is the one present in the native image. As my only input is a single jar file I would have expected my version be in the image. But interesting enough it is neither the first MANIFEST.MF file in the classpath, but one in the middle.
As all jar files except mine, are from "graalvm/lib/svm/builder/" I don't see an easy way to fix this from my side.

I'm using the latest GraalVM Community Edition 19.3.0 amd64 for Linux.

Thank you!

Regards,

Oz

**Comment by jaikiran** [comment]
Hello @ozppupbg,
> I have an application, which reads its version information from the META-INF/MANIFEST.MF file.

Which API do you use to get hold of that file? Can you paste that snippet? Is it the `ClassLoader.getResource` or `ClassLoader.getResourceAsStream`? Can you try `ClassLoader.getResources` instead?

**Comment by ozppupbg** [comment]
Hello @jaikiran,

I tried `clazz.getResource`, but for now have settled with `manifestPath = "resource:META-INF/MANIFEST.MF"; manifest = new Manifest(new URL(manifestPath).openStream());`, which should work, as it is native-image specific.

By now I also verified, that all included MANIFEST.MF files seem to present in the binary as strings.

These should be the code parts resposible for getting the resource file if I use this method:
https://github.com/oracle/graal/blob/d30871fc3a61f0a8d7195b13aa41a1d5126d6f2e/substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jdk/JavaNetSubstitutions.java#L187-L197

https://github.com/oracle/graal/blob/36e9f9b7f9f8f845ad3d729eff2c43d2356a9739/substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jdk/Resources.java#L72-L108

If multiple resources with the same name are registered, the first one should be "winning".

Regards,

Oz

**Comment by peter-hofer** [comment]
Thank you for your report @ozppupbg and apologies for the late reply. The resources should indeed be in the order in which they are found on the class path for `ClassLoader.getResources` and `getSystemResources`, and `getResource` and `getSystemResource` should pick the first one. However, this is still different to how multiple `ClassLoader`s (can) provide resources and might not be a universal solution.

**Comment by jovanstevanovic** [comment]
PR #3315 will fix this issue.

**Comment by jovanstevanovic** [comment]
The PR that fixes this problem is on a master for a while, so I'm going to close this issue.
