### ISSUE TITLE
Add JAVA_VERSION into version file

### ISSUE THREAD

**Issue by gurinderu** [oracle/graal#1990]
A lot of tools use a version file to determine a current java version by tag JAVA_VERSION.
Unfortunately, graalvm doesn't provide this tag.

**Comment by dougxc** [comment]
Hi @gurinderu , can you please some example tools.
Would processing the output of one of the following commands be sufficient:
* `java -version`
* `java -fullversion`
* `java -XshowSettings:properties -version 2>&1 | grep java.specification.version`

**Comment by dougxc** [comment]
@ansalond @gilles-duboscq is there some reason the `release` file in the root of a graalvm installation is not a superset of `release` file in a stock JDK installation?

**Comment by gilles-duboscq** [comment]
I can't think of a reason. We should probably add it along with some other fields that are missing in the Java 11 version (`IMPLEMENTOR`, `IMPLEMENTOR_VERSION`, `JAVA_VERSION_DATE`, and `MODULES`).

**Comment by ansalond** [comment]
Hi @gurinderu, this should now be fixed in [master](https://github.com/oracle/graal/commit/f6cfe0d12f473ec9a6b68ee1cb7bbc71d0b46718) and it will be part of our [20.0 release](https://www.graalvm.org/docs/release-notes/version-roadmap/).
