### ISSUE TITLE
Building native-image for app with log4j 2.12.1 fails with "Unsupported features in 11 methods"

### ISSUE THREAD

**Issue by kopper** [oracle/graal#1991]
When I try to build native-image of trivial app using log4j 2.12.1 using native-image config generated with native-image-agent I get:

```
Error: Unsupported features in 11 methods
Detailed message:
Error: Field org.apache.logging.log4j.core.impl.ContextDataFactory.EMPTY_STRING_MAP has declared type org.apache.logging.log4j.util.StringMap which is incompatible with types in state: MTypeMObject<5347:
...
Call path from entry point to org.apache.logging.log4j.core.impl.Log4jLogEvent.<init>(String, Marker, String, Level, Message, Throwable, ThrowableProxy, StringMap, ThreadContext$ContextStack, long, String, int, StackTraceElement, long, int, long, Log4jLogEvent$1): 
	at org.apache.logging.log4j.core.impl.Log4jLogEvent.<init>(Log4jLogEvent.java:53)
```

GraalVM 19.3.0 CE on Mac OSX 10.14.6
Sample project https://github.com/kopper/graalvm

**Comment by mipastgt** [comment]
Log4J uses MethodHandles, which are not supported by native-image, since version 2.8.
See: https://github.com/oracle/graal/issues/2008#issuecomment-569530312

**Comment by cstancu** [comment]
Cannot replicate the original issue reported here, the error message for unsupported MethodHandle use has been improved since. As for proper support of the latest Log4j, as mentioned in the issue linked above, we will need proper MethodHandle support first.
