### ISSUE TITLE
sysconf(_SC_PAGE_SIZE()) failing on Android

### ISSUE THREAD

**Issue by johanvos** [oracle/graal#1994]
The PosixVirtualMemoryProvider has a method returning the pagesize (`getPageSize()`) in which it uses `long queried = Unistd.NoTransitions.sysconf(Unistd._SC_PAGE_SIZE())`
This returns a value < 1.

When I set this value manually to 4096, applications run fine on Android.
Adding some debug shows that the native method should work:

`fprintf(stderr, "PAGESIZE = %ld\n", sysconf(_SC_PAGE_SIZE));
`
prints

`PAGESIZE = 4096`

**Comment by vjovanov** [comment]
What is the value of `_SC_PAGE_SIZE` in Linux and what is it on Android?

**Comment by johanvos** [comment]
That was the issue indeed:
_SC_PAGE_SIZE on Linux is 0x1E where it is 0x28 on Android.
I manually changed that in the CAP cache file and that works now.

**Comment by johanvos** [comment]
fixed in Gluon Substrate (https://github.com/gluonhq/substrate/pull/215 )
