### ISSUE TITLE
Remove gh-pages branch from TravisCI

### ISSUE THREAD

**Issue by lazar-mitrovic** [oracle/graal#1996]
As of today Travis is misconfigured to try to build ` gh-pages ` branch (https://travis-ci.org/oracle/graal/requests). 
I believe this could be fixed by hacking .travis.yml using [these commands](https://docs.travis-ci.com/user/customizing-the-build/#safelisting-or-blocklisting-branches) to blacklist said branch.

**Comment by gilles-duboscq** [comment]
According to [travis](https://docs.travis-ci.com/user/customizing-the-build/#safelisting-or-blocklisting-branches),
> By default, the `gh-pages` branch is not built unless you add it to the safelist.

However the documentation also says that
> Note that for historical reasons `.travis.yml` needs to be present on all active branches of your project.

so maybe we should have some empty `.travis.yml` on the `gh-pages` branch?
