### ISSUE TITLE
enterSlowPathNativeToJava called while in Java

### ISSUE THREAD

**Issue by johanvos** [oracle/graal#2002]
(on Android)
When calling Java code from native code, I can see a crash with the following trace:
```
VMError_shouldNotReachHere_c5b94b5a36d4ec9ecab1dc8b763f947e888a3612+72
VMError_guarantee_18caf46ef6d672f2c7aab3ad271ff5117b823ec1+40
Safepoint_enterSlowPathNativeToJava_7405606951b146d1e5a18c3861fef52afd34fa42+52
PosixParkEvent_condWait_e56b1f736bc25db0e6b8d534448b6e861923815f+620
JavaThreads_park_755a1b244969a8d0cb7054e95d9df6e2d73ee8da+148
Unsafe_park_8e78b5f196bf0524b1490ff9abb68dc337e02cca+104
AbstractQueuedSynchronizer_parkAndCheckInterrupt_5f77ccdb5d848784815a610576e6a7d474e2c6b6+84
AbstractQueuedSynchronizer_doAcquireSharedInterruptibly_45d39ee7e51ec281fae273eb218ebe42e5365209+372
AbstractQueuedSynchronizer_acquireSharedInterruptibly_986e79924c5cddba9f884d538a5457f24373785c+128
CountDownLatch_await_cae569b700a03cdda8dbc533815f014324b9a239+52
MonocleWindowManager_repaintFromNative_d2c47725d544f3ebd13059104a8dbef9cc63006c+240
JNIJavaCallWrappers_jniInvoke_VARARGS:Lcom_sun_glass_ui_monocle_MonocleWindowManager_2_0002erepaintFromNative_00028_00029V_575e77e954c3b7b3fb82257fc2af51fec94e27b5+88
Java_com_gluonhq_helloandroid_MainActivity_nativeSurfaceRedrawNeeded+72

```

The last line (`nativeSurfaceRedrawNeeded`) is a native method, and it will invoke a Java method 
`MonocleWindowManager_repaintFromNative`

From that moment, all subsequent methods are in Java, so I wonder why the NativeToJava suddenly appears.
Looking into the code for `PosixJavaThreads.condWait()` it seems there are transitions to native in that method though.

**Comment by loicottet** [comment]
This may be because `PosixParkEvent_condWait` calls a native function and fails to restore the Java context correctly upon return, which would then cause this error. It's hard to tell from just this stacktrace though...

**Comment by vjovanov** [comment]
@johanvos can we close this issue?

**Comment by johanvos** [comment]
Yes, this was actually due to a different issue in my native code where 2 native threads were linked to the same Java thread (only 1 of them was attached). Would be nice to have early asserts for this case, but this is not in scope of this issue.
