### ISSUE TITLE
Executable Signature

### ISSUE THREAD

**Issue by marcom1981** [oracle/graal#2004]
Hello,
Currently graalvm executables are not signed.
It is possible in future releases to sign them so that antivirus does not delete them automatically.

**Comment by gilles-duboscq** [comment]
On which OS are you having this issue? I suppose Windows or MacOS?
Are you looking at the Java 8 or Java 11 version?
Also, are you looking at CE or EE?

We started signing some artifacts for GraalVM EE 19.3.0 / Java11 on Windows and MacOS but that's mostly for the artifacts of the underlying JDK not for the native images included in the GraalVM.

**Comment by marcom1981** [comment]
It occurs on windows with AVG and graalvm CE.

**Comment by gilles-duboscq** [comment]
The 20.3.0 release for WIndows and macOS should have all its binaries signed. Please re-open if this is still an issue.
