### ISSUE TITLE
native-image leads to wrong execution / code

### ISSUE THREAD

**Issue by ptrd** [oracle/graal#2011]
Given this simple sample

```
package sample;

public class Simple {

    public static void main(String[] args) {
        byte ca = (byte) 0xca;
        System.out.println("Result: " + checkType(ca));
    }

    static boolean checkType(byte type) {
        byte masked = (byte) (type & 0xf0);
        boolean result = (masked == (byte) 0xc0);
        return result;
    }
}
```
When compiled and run with java, it returns true (which it obviously should).

When compiled with native-image however, it returns false.

GraalVM Version 19.3.0 CE
MacOS Catalina 10.15.2
Using -H:Optimize=0 doesn't make any difference.

**Comment by olpaw** [comment]
@dougxc this looks like a compiler bug. If I run `checkType` in a hot loop if get to the point where it returns false.

**Comment by olpaw** [comment]
```
public class Simple {

    public static void main(String[] args) {
        byte ca = (byte) 0xca;
        int x = 0;
        while(x++ < 2 << 20) {
            boolean res = checkType(ca);
            assert res : "Fails after " + x + " iterations.";
            System.out.print(res ? "X" : "x");
        }
    }

    static boolean checkType(byte type) {
        byte masked = (byte) (type & 0xf0);
        boolean result = (masked == (byte) 0xc0);
        return result;
    }

}
```
Passes `java -ea Simple` with stock JDK but not when run on GraalVM

**Comment by olpaw** [comment]
@ptrd thanks a lot for this bug report!

**Comment by ptrd** [comment]
You're welcome. Can't wait to experiment with kwik.tech compiled to native....

**Comment by dougxc** [comment]
Hi @ptrd , thanks for reporting. This is related to #1995 and is fixed in master (https://github.com/oracle/graal/commit/276ff2b4426fd93f2aa4fd62cb409e71169aeef1). It will be in GraalVM CE 19.3.1.

**Comment by ptrd** [comment]
Ok, cool. Made a note in my agenda for Jan 14. ;-)
