### ISSUE TITLE
Any specific build instructions to build the graal repo on MacOS 10.15.2?

### ISSUE THREAD

**Issue by jaikiran** [oracle/graal#2017]
I just tried a few times to build the graal vm locally using the following command:

```
cd vm
mx --env ce build
```
This keeps failing with:

```
Building com.oracle.truffle.llvm.tests.native with GNU Make... [dependency LLVM_TOOLCHAIN updated]
graal/sulong/tests/com.oracle.truffle.llvm.tests.native/src/callbackLibrary.cgraal/sulong/tests/com.oracle.truffle.llvm.tests.native/src/caller.c::3030::1010::  fatal errorfatal error: : 

            'stdlib.h''stdio.h'  filefile  notnot  foundfound

#include <stdlib.h>#include <stdio.h>

         ^~~~~~~~~~         ^~~~~~~~~

1 error generated.
1 error generated.
make: *** [bin/caller.o] Error 1
make: *** Waiting for unfinished jobs....
make: *** [bin/callbackLibrary.o] Error 1
```
I'm on mac OS 10.15.2 with XCode (latest) installed along with CommandLineTools. `clang -v` shows:
```
Apple clang version 11.0.0 (clang-1100.0.33.16)
Target: x86_64-apple-darwin19.2.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**Comment by dougxc** [comment]
Maybe this helps: https://stackoverflow.com/questions/58232595/missing-system-headers-usr-include-on-macos-catalina

**Comment by jaikiran** [comment]
Hello @dougxc, that indeed helped. Thank you very much.

I don't know if it's my lack of knowledge of C ecosystem or if it's a genuine issue which others might run into. If it indeed is something that others should be aware, then adding a note to the readme document would help. So I've opened https://github.com/oracle/graal/pull/2020/ to address it.

**Comment by fniephaus** [comment]
IIRC, this worked for me: 
```bash
SDKROOT=`xcrun --show-sdk-path` mx --env ce build
```

**Comment by jaikiran** [comment]
Closing this, since I no longer run into this, plus the suggestions in this issue already helped me get past this when I first ran into it.
