### ISSUE TITLE
_ghash_processBlocks intrinsic for Java 8

### ISSUE THREAD

**Issue by helloguo** [oracle/graal#2023]
Not sure if I should post the question here or in graal-jvmci-8 repo https://github.com/graalvm/graal-jvmci-8. However, is there any plan to port the _ghash_processBlocks intrinsic for Java 8?

**Comment by dougxc** [comment]
GraalVM CE will automatically pick this up once it's in a jdk8u release. This appears to be [on the horizon|https://bugs.openjdk.java.net/browse/JDK-8073108?focusedCommentId=14301512&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-14301512].
