### ISSUE TITLE
Unused GraalOptions

### ISSUE THREAD

**Issue by helloguo** [oracle/graal#2024]
While I was trying to tune the flags based on https://github.com/oracle/graal/blob/master/compiler/src/org.graalvm.compiler.core.common/src/org/graalvm/compiler/core/common/GraalOptions.java, I noticed there are a few options that are not used in the source code. I was wondering if I miss anything here and how to use these options. Any suggestions are appreciated. Here is a list that may be interesting to use:

- PEAInliningHints
- TailDuplicationProbability
- TailDuplicationTrivialSize
- OptEliminatePartiallyRedundantGuards
- OptFilterProfiledTypes

**Comment by fniephaus** [comment]
According to https://chriswhocodes.com/graalvm_native_image_ee_jdk8_options.html, TailDuplicationTrivialSize is a flag for the enterprise edition (GraalVM EE). I'm guessing this is also true for all others you mentioned?

**Comment by dougxc** [comment]
I'm pushing a change that removes unused options and adds a test to ensure they are prevented in future.

**Comment by dougxc** [comment]
Done: 699f2fbf3a0847e8edca2eb1c4fe6a8e93928085
