### ISSUE TITLE
Truffle host interop - can't pass TruffleObject to host method

### ISSUE THREAD

**Issue by jarohen** [oracle/graal#2032]
Hey Graal/Truffle folks :smile: If I have a host method signature accepting a parameter that extends TruffleObject, the `HostExecuteNode/asJavaObject` call fails with the 'Unsupported target type' error message

e.g.

```
public class MyObject implements TruffleObject { ... }

public void myHostMethod(MyObject o) { ... }
```

As a potential solution, would it be possible to add another clause to that method, where the `targetType` is a subclass of TruffleObject and the `value` is an subclass of the `targetType`, passing the value directly to the host method?

Cheers!

**Comment by boris-spas** [comment]
Tracking internally as Issue GR-20944.

**Comment by jarohen** [comment]
I suspect, related to @chumer's suggestions on #1228, that I probably shouldn't be sending TruffleObjects through to host code? :smile:

**Comment by chumer** [comment]
Value from the guest must not be passed directly to the host. This is deliberate decision to not mix up guest and host world. I discuss why here: https://github.com/oracle/graal/issues/1228
