### ISSUE TITLE
[native-image] new File(".") points to native-image's cwd

### ISSUE THREAD

**Issue by bsideup** [oracle/graal#2040]
It seems that after the AOT compilation, `new File(".")` in my code points to `/Users/bsideup/.native-image/machine-id-hostid-0/session-id-11bf2/server-id-13a9cc69f0211a6fd8aec094a69254d6de5e1cea1bfc68ee02c4ef1da82c52d4da8c85912863a846a7993e5c03a118421e5fa02ecd9e69e16df6cc1a76e30c48/.` instead of the current workdir of the process.

Since ` Paths.get(".")` works fine, I would assume this is a bug.

**GraalVM version:** 19.3.0.2 (Java 11 mode)

**Comment by SergejIsbrecht** [comment]
@bsideup , could you please expand your example? Are you using new File(".") in the constructor or as a static field?

I would assume it depends on the implementation. Probably Paths#get will be evaulated lazy and new File("."). 

You could probably resolve this issue by defering the init. of the class until runtime (-delay-class-initialization-to-runtime=YourClassHere)

https://medium.com/graalvm/understanding-class-initialization-in-graalvm-native-image-generation-d765b7e4d6ed

**Comment by eginez** [comment]
fixed by https://github.com/oracle/graal/commit/b1c2a49cc7b892ccea64ae2e888fb0d0565c5f82
