### ISSUE TITLE
Strange error message about class initialisation in Native Image

### ISSUE THREAD

**Issue by chrisseaton** [oracle/graal#2043]
Someone posted this error message in Slack https://graalvm.slack.com/archives/CN9KSFB40/p1577587139042400

```
Error: Detected a started Thread in the image heap. Threads running in the image
generator are no longer running at image run time.  To see how this object got
instantiated use -H:+TraceClassInitialization. The object was probably created
by a class initializer and is reachable from a static field. You can request
class initialization at image run time by using the option
--initialize-at-build-time=<class-name>. Or you can write your own
initialization methods and call them explicitly from your main entry point.
```

The confusing part is `You can request class initialization at image run time by using the option --initialize-at-build-time=<class-name>` - seems nonsensical to me? `at .. run time by using ... build-time`

They're using 19.3, but seem to be no relevant changes up to 19.3.0.2 https://github.com/oracle/graal/compare/vm-19.3.0...vm-19.3.0.2.

**Comment by jaikiran** [comment]
Hello @chrisseaton,
This has been fixed in https://github.com/oracle/graal/pull/1854
