### ISSUE TITLE
Easier configuration for limited IO in contexts

### ISSUE THREAD

**Issue by zolstein** [oracle/graal#2056]
I need to give my Contexts read access to particular files outside of any language directory. (Specifically `/usr/lib/libSystem.B.dylib`.) However, I can't use `allowIO(true)` because that exposes far too much of the filesystem to pieces of code that shouldn't have access to it.

Allowing (limited) access to particular files seems like a common usage pattern. As is, configuring this is _possible_ but enormously painful. One has to essentially duplicate a bunch of the FileSystems code to implement a custom FileSystem enabling access to those particular paths. Having the ability to add a public filesystem without overriding the default language-home internal filesystem would also help.

I propose creating an IOAccess builder similar to HostAccess or PolyglotAccess, that (possibly among other things) allows the user to configure a list of accessible paths and the allowed AccessModes for these files. Then replace the Context.Builder.allowIO method with one taking an IOAccess object.

You may also want to make several methods on the FileSystems somehow accessible through the API. I.e. the ability to construct a newDefaultFileSystem() or a newNoIOFileSystem() as a delegate. This would make writing a custom file system much easier in the more-complicated situations that require it.

**Comment by boris-spas** [comment]
Tracking internally as Issue GR-20946.

**Comment by ralleman** [comment]
Not sure if it's the same thing, bit I've been after a way to offer a file system per request that isn't the same file system that gets assigned to ECMA imports. So the context would be assigned a blank file system for users to muck about in (and within this I may mount a folder to S3 when needed by the request) and the script imports use another one that is more controlled by the engine I'm writing.

**Comment by jazdw** [comment]
#2190 would certainly make this easier

**Comment by tzezula** [comment]
The  `FileSystem.newDefaultFileSystem` was added, commit https://github.com/oracle/graal/commit/36db4c027d1807ebebde7d8001937910a339e003.
