### ISSUE TITLE
Are all engine/VM options connected up properly?

### ISSUE THREAD

**Issue by chrisseaton** [oracle/graal#2061]
https://github.com/oracle/graal/blob/41ccc2cc0efb93b62bf8f9e3a4ed2f8c5d7f14e3/compiler/src/org.graalvm.compiler.truffle.common.processor/src/org/graalvm/compiler/truffle/common/processor/Option.java

For example `TruffleCompilationExceptionsAreFatal` is connected up to `PerformanceWarningsAreFatal`, is that right? Some of the others seem confusing as well.

Found by @kipply.

**Comment by eregon** [comment]
cc @tzezula

**Comment by eregon** [comment]
Could you detail a specific issue with it?
Is it that either of them causes a compilation exceptions and perf warnings to System.exit()?

**Comment by chrisseaton** [comment]
I think it's a typo. The option and the alias seem reversed. `TruffleCompilationExceptionsAreFatal` is an deprecated by `PerformanceWarningsAreFatal` and `TrufflePerformanceWarningsAreFatal` is deprecated by `CompilationExceptionsAreFatal`, but then they both have a comment `// COMPILER` that we don't understand.

The specific issue is we think this list might have multiple errors and needs auditing.

**Comment by eregon** [comment]
I see, I must have swapped both lines, I'll fix it.

Both styles of options should work, this should only affect the deprecation documentation and default values (false for both options).

**Comment by boris-spas** [comment]
Tracking internally as Issue GR-20947.

**Comment by eregon** [comment]
Fixed in 403b874bdcf69ea75cc83c3760236eaeb2ee0c87, thanks for the report.
