### ISSUE TITLE
Truffle DSL processor throws NPE in generateServicesRegistration() for LanguageRegistrationProcessor

### ISSUE THREAD

**Issue by greedy** [oracle/graal#2064]
This seems to happen when prior processing rounds had errors (i.e. roundEnv.errorRaised() is true) which then causes the provider class to not have an associated TypeElement (maybe the error happened in the same round the provider was generated and thus it is not actually created?). This NPE then masks the errors that would have been reported by the compiler which is quite frustrating.

**Comment by greedy** [comment]
Possible fixes:

1. Skip providers in generateServicesRegistration() that don't have a TypeElement (i.e. te is null)
2. In the processingOver case don't generate the registrations if roundEnv.errorRaised() is true

**Comment by boris-spas** [comment]
Tracking internally as Issue GR-20950.

**Comment by tzezula** [comment]
Already fixed by a60e864.
