### ISSUE TITLE
Build graalvm-java8

### ISSUE THREAD

**Issue by helloguo** [oracle/graal#2069]
My use case of GraalVM is to replace OpenJDK8, which means I don't need polyglot nor native image. The downloaded graalvm-ce-java8-linux-amd64-19.3.0.2.tar.gz
seems a bit larger for me because it contains something I don't need. Can anyone share instructions how to build GraalVM which only contains OpenJDK8+Graal JIT compiler? Thanks.

**Comment by olyagpl** [comment]
Hi @helloguo, please find the instructions on how to build the base GraalVM CE image https://github.com/oracle/graal/tree/master/vm#example-build-the-base-graalvm-ce-image

**Comment by helloguo** [comment]
@olyagpl Thanks for your information. I followed the instructions and could build the CE image ( I ran `mx --env ce build`). However, I need an image with smaller binary size as I don't need native-image tool, polyglot, sulong, nodejs and so on. Could you share instructions how to build CE image which only contains openjdk8 and GraalVM Compiler? Thank you!

**Comment by olyagpl** [comment]
You might also want  [LibGraal](https://github.com/oracle/graal/tree/master/compiler#libgraal) (the native image of the GraalVM compiler) for faster startup. 
In this case:
$ cd graal/vm
$ mx --env libgraal build 
The GraalVM will be in:
$ mx --env libgraal graalvm-home

**Comment by helloguo** [comment]
Thank you! @olyagpl I'm closing this issue now.
