### ISSUE TITLE
Graal's corresponding flag to C2's AutoBoxCacheMax

### ISSUE THREAD

**Issue by helloguo** [oracle/graal#2079]
Not sure if this is the right place to ask this question. However, does Graal's JIT Compiler have the corresponding flag to C2's AutoBoxCacheMax? If not, is there any plan to enable it in Graal? Thank you!

**Comment by dougxc** [comment]
The `AutoBoxCacheMax` flags seems to be an alias for setting the `java.lang.Integer.IntegerCache.high` system property (https://github.com/graalvm/graal-jvmci-8/blob/fc8a493bac33d35405c4361a134a812222c3d14b/src/share/vm/runtime/arguments.cpp#L2033) so you should be able to just set that property directly.
