### ISSUE TITLE
Thread-Safety of Frames

### ISSUE THREAD

**Issue by smarr** [oracle/graal#208]
Currently, the implementations of `VirtualFrame` and `MaterializedFrame` are not thread-safe.

This causes data races in languages with lexical scope that are shared between multiple threads (typically on `MaterializedFrame` objects).

From my perspective there are two possible ways forward:
1. acknowledge the fact and documented as 'by design' in the JavaDoc, ideally with a description of possible solutions for language implementers
2. try to find a way to make it safe as part of the framework

Related post on mailing list: http://mail.openjdk.java.net/pipermail/graal-dev/2016-October/004592.html

This might actually already be observable in languages like Ruby with multiple threads, @eregon @chrisseaton?

**Comment by chrisseaton** [comment]
I'll put it on my to-do list to try to reproduce in Ruby.

**Comment by smarr** [comment]
It is probably hard to see it in a language though, because it would happen only the first time, either for type specialization, or for `FrameWithBoxing` to expand the array for a previously unused slot. So, one has to get the time exactly wrong once...

**Comment by chumer** [comment]
VirtualFrame must not be thread-safe. MaterializedFrame maybe should, but can be synchronized manually in the language. 
FrameDescriptor thread safety is tracked in GR-2509.
Closing this issue as it is stale.

**Comment by smarr** [comment]
I am unhappy with the conclusion that MaterializedFrame should be synchronized manually.
This is something as fundamental and relevant for performance as a thread-safe object model.
And it is hard to get right.

Possibly the object model would also be the simplest way forward: @eregon's thread-safe object model could be used for materialized frames.
