### ISSUE TITLE
[native-image]A Java process still worked after the native-image compile finished

### ISSUE THREAD

**Issue by MakHoCheung** [oracle/graal#2081]
I used the native-image to compile a "HelloWorld" java class. But compile process still worked after the compile task finished.
![image](https://user-images.githubusercontent.com/22256775/72680889-d26f5200-3af9-11ea-80ba-0f211f0ce2b0.png)
![image](https://user-images.githubusercontent.com/22256775/72680904-ddc27d80-3af9-11ea-802d-3586d616cd3b.png)
![image](https://user-images.githubusercontent.com/22256775/72680939-27ab6380-3afa-11ea-8c74-86563ff979cc.png)

**Comment by boris-spas** [comment]
This is intended behavior. 
The java process is a build server that will be reused for the next native-image build.
If you don't want to use the server based building you can use the `--no-server` option (more info: https://www.graalvm.org/docs/reference-manual/native-image/#image-generation-options )
