### ISSUE TITLE
[native-image] Cannot get default locale normally on Native image

### ISSUE THREAD

**Issue by Glavo** [oracle/graal#2082]
I executed `export LC_ALL=zh_CN.UTF-8` to switch the language to Chinese, but `en_US` will still be obtained in native-image:
```
glavo@DESKTOP-IISF56J:~/Test$ cat Main.java
import java.util.*;

public class Main {
    public static void main(String[] args) {
        System.out.println(Locale.getDefault());
    }
}
glavo@DESKTOP-IISF56J:~/Test$ java Main
zh_CN
glavo@DESKTOP-IISF56J:~/Test$ ./main
en_US
```
Even if I use the `native-image -J-Duser.language=zh_CN Main` command to compile, I still cannot get zh_CN correctly:
```
glavo@DESKTOP-IISF56J:~/Test$ ./main
zh_cn_US
```

**Comment by maxum2610** [comment]
Setting 
Locale.setDefault(Locale.FRANCE); in my code
worked for me. In your case I suppose Locale.setDefault(Locale.SIMPLIFIED_CHINESE); would be correct.
Also, the LocalizationSupport.java class uses Local.getDefault() to get resource bundles.
