### ISSUE TITLE
[native-image] Question: Connecting native-image with GraalVM

### ISSUE THREAD

**Issue by RazvanN7** [oracle/graal#2083]
I am using lli to execute llvm bitcode. As far as my understanding goes, the Truffle layer interprets the LLVM bitcode and at some point decides that some code must be partially evaluated. It then passes the command to GraalVM that does some cool optimizations and then it generates machine code. My question is: instead of generating machine code is there any possibility to generate an LLVM bitcode version of the optimized code? I was thinking that the optimized representation (AST?)  could be easily forwarded to the native-image tool, but that would require some hacking as native-image requires a .class file.

Thanks in advance.

**Comment by wirthi** [comment]
Many things can be possible in theory. But what you suggest seems quite far from the current focus and implementation of Native Image. Our approach focuses on ahead-of-time compiling Java applications, not gust language applications in another language (LLVM, in your case).
