### ISSUE TITLE
[native-image] libawt fails to work correctly due to no init call

### ISSUE THREAD

**Issue by maxum2610** [oracle/graal#2084]
When trying to create an ICC_Profile with liblcms, a call is made to libawt (Disposer.c) to Disposer_AddRecord. Here the corresponding sun/java2d/Disposer.java class is called which contains a static block with a JNDI native call to Java_sun_java2d_Disposer_initIDs where a NewGlobalRef should happen. This last step does not happen because the init call in the static block is preceded by a loadLibrary call which I believe fails (another issue?). The result is as expected, Segmentation fault: 11.

Test case:
// profile sRGB.pf should be loaded as local resource in the project (see issue #2073) 
s = PCMM.class.getResourceAsStream("profiles/sRGB.pf");
profile = ICC_Profile.getInstance(getProfileResource());

NOTE: calling Java_sun_java2d_Disposer_initIDs in Disposer_AddRecord resolves the issue.

**Comment by peter-hofer** [comment]
Hi @maxum2610, apologies for the delay. I suspect that the static initializer that loads the `awt` library and calls `initIDs` is called at image generation time instead of runtime. You can try to defer the initialization to runtime using `--initialize-classes-at-runtime` on the `Disposer` class. We currently don't support AWT, so calling `initIDs` manually is probably the best workaround at this time. (Does that mean that you also also call `loadLibrary("awt")`?)

**Comment by maxum2610** [comment]
Hi @peter-hofer, I've tried that but it does not solve the problem. We have to define the Disposer class as part of the -H:JNIConfigurationFiles entries, as it is invoked from within the dynamic library at runtime, and doing so invokes it at build time. I'm actually using static versions of LCMS and awt in order to trace the internal calls and pointer values passed to and from java code. There are other classes that cause similar problems (one of them being java.lang.System which gives a Error: Detected a direct Buffer in the image heap when trying to include in the JNI file). The strange thing is, calling loadLibrary for liblcms and libawt works perfectly when calling from the main() entry point, but not when in a static initializer at runtime? Also, the problem with calling the initID function manually (which I currently do from with the static lib) does not solve much as the whole disposer logic java side does not get initialised which means memory allocations are not released as should be. I hope someone finds the time to look at the whole awt module soon, as this is a major blocking factor for a lot of people. PDFBox, FOP and countless other frameworks denpend on it.
