### ISSUE TITLE
Add support for Java 14

### ISSUE THREAD

**Issue by SR-Lut3t1um** [oracle/graal#2097]
Since Java 14 is going to be the next major (LTS) release after 11 I'm sure many devs want to adapt the newer JDK. So having Java 14 support in graal asap would help adopt the newer version even faster.

**Comment by tarsa** [comment]
Java 14 is not a LTS: https://www.oracle.com/technetwork/java/java-se-support-roadmap.html
IIRC LTS version will be released every 3 years, i.e. every 6 releases. So if Java 11 is LTS then the next LTS will be Java 17.

**Comment by SR-Lut3t1um** [comment]
Oh nvm my bad. Still how hard would it be to implement?

**Comment by dougxc** [comment]
I believe @bobvandette is actively looking into this and may be able provide an update.
@SR-Lut3t1um have you tried building graalvm with JAVA_HOME=/path/to/jdk14?

**Comment by bobvandette** [comment]
You should be able to build graal with JDK 14.  I pushed some changes to enable this a while ago.  I pushed some fixes to enable JDK 15 sometime around Jan 15th under the branch [GR-20582].  Since JDK 15 is still under development I'm certain more changes will be needed.

**Comment by cemo** [comment]
Will GraalVM officially support only LTS?

**Comment by pquiring** [comment]
Can you build graal with official JDK14 or do you need something like custom labsjdk (which is JDK11)?
If a custom JDK like labsjdk is required, would it be too much to ask if nightly graal builds started to include a JDK14 version?

**Comment by pquiring** [comment]
JDK-8232748 added option to build static native libraries for graal.  This was delivered with JDK14.   So I guess labsjdk is no longer needed, but you'll need to build the JDK from source and add that option.

**Comment by wirthi** [comment]
GraalVM currently supports JDK11 and JDK17. GraalVM 22.3.0 will also ship with JDK19 support.
