### ISSUE TITLE
Question about ConfigurableClassInitialization.checkDelayedInitialization()

### ISSUE THREAD

**Issue by XanderAtBackboneSystems** [oracle/graal#2099]
On several occasions i get the error message: 

> Classes that should be initialized at run time got initialized during image building:
> &lt;class-name&gt; the class was requested to be initialized at build time (from the command line). 

In some of those situations i was explicitly setting this class to be initialized on runtime by using: 
`-H:ClassInitialization=<class-name>:run_time`

This was giving me some confusion as i was already doing what the error message suggested to me. And also the last part of the error message `(from the command line)` wasn't true. I used a debugger to figure out what was going on and i noticed that the `ClassInitializationConfiguration.lookupKind()` returned the correct InitKind (which is `InitKind.RUN_TIME`). 

Then i was looking in the method: `ConfigurableClassInitialization.checkDelayedInitialization()` which generates this error message.

And i found that in the beginning of this method all registered types are checked as follows:
- Is the initialization type for the class one that `isDelayed()` (only true for `InitKind.RUN_TIME`)
- And does UNSAFE.shouldBeInitialized() return false for the class

If both conditions are valid then the above error is emitted. I'm not sure why the error indicates that the class is initialized at build time as nothing in the code of this method suggests this. So i'm still a bit confused and maybe the error message should be improved. But it might also be possible that the check isn't correct. I don't know how to configure this as a user of native-image, let alone that i know how to improve the code and/or the error message.

I must note that:
- I interpreted the error message as that i was trying to initialize the class at build time rather than at run time and should change that by adding or removing command line arguments.
- I'm not 100% sure what the intentions of the check are (there are no comments)
- And i also don't know when `UNSAFE.shouldBeInitialized()` returns true (or false).   

I used:
- jdk11 of graalvm (version 19.3.1)

EDIT:
- after re-reading fixed some small grammar things

**Comment by guitcastro** [comment]
I am facing the same error:

I have: -H:ClassInitialization=org.flywaydb.core.internal.scanner.classpath.ClassPathScanner:run_time still my build fails with:

`
 This error is reported at image build time because class org.flywaydb.core.internal.scanner.classpath.ClassPathScanner is registered for linking at image build time by command line
`

**Comment by vjovanov** [comment]
Without a complete reproducer it is hard to help here. Also, `-H:ClassInitialization` is an internal flag so it should never be used. 

Please provide a complete reproducer for us the help you.

**Comment by XanderAtBackboneSystems** [comment]
Note that this issue was created in 2020 when graal-vm world was a bit diffrent. Besides that: I don't have the option to reproduce this anymore as the project i was working on is no longer within my reach. I also don't have the time to reproduce this on a diffrent project. Therefore this issue may be closed. But it leave that up to @guitcastro.

**Comment by guitcastro** [comment]
I've moved on as well and don't have a reproducible example. Maybe this should be closed.
