### ISSUE TITLE
[native-image] java.lang.management.ManagementFactory.getPlatformMBeanServer() support.

### ISSUE THREAD

**Issue by borissmidt** [oracle/graal#2103]
Dear fellow graal users,

Is there a way to override an already overwritten method with graal.

For example if you include a library that already substitudes a class then you cannot override it once more to cutomise it to your own behavior. 

A concrete example, graal override ManagementFactory.getPlatformMBeanServer` to return null.

I would like to override it so i could return my own ManagementFactory and thus be able to use the jmx api for reporting. 
Then i could decide to write a http server or just log to the jmxBeans to still get some reporting out of the app.
```
@TargetClass(java.lang.management.ManagementFactory.class)
@SuppressWarnings("unused")
final class ManagementFactory {
    @Substitute
    public static synchronized MBeanServer getPlatformMBeanServer() {
        return ReplacementServer.server;
    }
}
```

At compile time it fails since this class has already been substituted by graal itself and there is no way to substitude it again.
i'm currently using graal 19.3.0

**Comment by borissmidt** [comment]
Or atleast i could just use libraries that use the server for reporting like kafka, without substituting each class that uses this jmx part.
the current replacement server i would have used:
[server.txt](https://github.com/oracle/graal/files/4118951/server.txt)

**Comment by borissmidt** [comment]
I think it more like a feature request then a question to be honest.

**Comment by borissmidt** [comment]
@vjovanov any idea on how to resolve this?

**Comment by vjovanov** [comment]
The solution here would probably be to implement: `java.lang.management.ManagementFactory#getPlatformMBeanServer` properly. I would re-phrase this question into a feature request and then we can prioritize it. @cstancu are there any fundamental blockers for supporting this feature?

Having a substitution for substitution is a slippery slope. If you want to try it out I would simply build from source and then replace our substitution with yours.

**Comment by borissmidt** [comment]
Thank you for the answer, i will try to create a simple replacement server and if it works as expected create a PR for it.

**Comment by cstancu** [comment]
@borissmidt substituting an already substituted method is not supported and I don't think we want to go down that path. The best approach would be to enhance the existing substitution and get proper support for `ManagementFactory`. I am not aware of any fundamental blockers, we just never got around to implement it.

**Comment by borissmidt** [comment]
@cstancu   I think it has beeen solved in the newer relasees since the implementation of ManagementFactory has changed thank you for upgrading graal :)
