### ISSUE TITLE
[native-image] Dynamic proxy of nested class

### ISSUE THREAD

**Issue by dboyan** [oracle/graal#2104]
I think there might be some issue with support of dynamic proxy of nested classes in native-image. Here is a minimal case.

```java
import java.lang.reflect.InvocationHandler;
import java.lang.reflect.Method;
import java.lang.reflect.Proxy;

class DIHandler implements InvocationHandler {
    public Object invoke(Object proxy, Method method, Object[] args)
        throws Throwable {
        System.out.println(method.getName());

        return 42;
    }
}

public class Test {
    interface TestIntf {
        int foo(int bar);
    }

    public static void main(String[] args) {
        System.out.println("Hello");
        TestIntf proxyInstance = (TestIntf) Proxy.newProxyInstance(
                Test.class.getClassLoader(),
                new Class[] { TestIntf.class },
                new DIHandler());
        proxyInstance.foo(100);
    }
}
```

native-image will always produce the following error, even if I add `Test$TestIntf` to proxy configuration file and `--initialize-at-build-time=Test$TestIntf` argument.

> Error: Classes that should be initialized at run time got initialized during image building:
>  Test$TestIntf was unintentionally initialized at build time. To see why Test$TestIntf got initialized use -H:+TraceClassInitialization

However, if the interface `TestIntf` is moved out of class `Test`, previous configuration can work with the two settings above. So I guess there is some problem with nested class here?

**Comment by dmlloyd** [comment]
Before digging in too much: did you remember to escape the `$` in your shell?  If not, you may have entered `--initialize-at-build-time=Test$TestIntf` but the shell would see only `--initialize-at-build-time=Test`, because `$TestIntf` would likely not correspond to any set env var.

I only suggest it because we've (Quarkus team) seen that a couple of times and in a couple different contexts already.

**Comment by dboyan** [comment]
Ah, my bad. I wasn't properly escaping it. Great thanks for the quick response!
