### ISSUE TITLE
Automate release to Maven Central

### ISSUE THREAD

**Issue by pniederw** [oracle/graal#212]
Maven Central releases always lag behind GitHub releases (typically between a day and a week).

Please automate the release process so that all release events (tagging, publishing, etc.) happen at the same time.

**Comment by chumer** [comment]
We are working on this. Unfortunately doing automated maven central releases sounds easier than it is.

**Comment by pniederw** [comment]
One way is to publish to bintray/jcenter, which then syncs to maven central.

**Comment by pniederw** [comment]
Thanks for the timely Maven Central release of 0.22.
