### ISSUE TITLE
[native-image] After upgrading to GraalVM 19.3.1 docker build crashes

### ISSUE THREAD

**Issue by akoufatzis** [oracle/graal#2122]
Hello to all. I opened a similar [issue](https://github.com/quarkusio/quarkus/issues/6935) in the Quarkus repo but it seems that it could be more related to GraalVM. After upgrading to GraalVM 19.3.1 and running the native-image build through docker I am getting the following error: `Image build request failed with exit status 137` . In Docker I have memory set to 2GB Ram. After retrying with 6GB Ram the build works successfully. Is it possible that the native-image build is leaking? The strange thing is that using GraalVM 19.2.1 the 2GB where sufficient. If it is helpful you can use this [repository](https://github.com/akoufatzis/quarkus_dev) for reproducing the issue running: `docker build -f src/main/docker/Dockerfile.native -t quarkus_dev .`

**Comment by petrbouda** [comment]
Please, let me know if you need better reproducer, I could minimize my example into a separated repo.

**Comment by olpaw** [comment]
From 19.3 on we changed the approach we use to support different platforms and different Java versions. The old approach of providing explicit substitution-methods for native-methods directly in Java (using "SystemJava") does not scale to our (Platform x Arch x JavaVersion) ambitions.

The new approach reuses static-library variants of JDK native libraries. This is a bit more heavy on the image building side but has advantages in most other aspects. The amount of Java APIs that we can support is much bigger and relatively easy to extend further.

Now that this transition has been made, future versions of native-image will likely not increase memory requirements for building images any further.

**Comment by akoufatzis** [comment]
Thank you for your reply. I will close the issue then.
