### ISSUE TITLE
After 1.0.0-rc11 truffle seems broken

### ISSUE THREAD

**Issue by DmitryMiroshnichenko** [oracle/graal#2131]
**Describe GraalVM and your environment :**
 - GraalVM version or commit id if built from source: **[19.3] and any version starting 1.0.0-rc12**
 - JDK version: **[JDK8]**
 - OS and OS Version: **[macOS Catalina]**
 - Architecture: **[amd64]**
```

java.lang.IllegalArgumentException: A language with id 'js' is not installed. Installed languages are: [].

	at com.oracle.truffle.polyglot.PolyglotEngineImpl.requirePublicLanguage(PolyglotEngineImpl.java:676)
	at com.oracle.truffle.polyglot.PolyglotContextImpl.requirePublicLanguage(PolyglotContextImpl.java:773)
	at com.oracle.truffle.polyglot.PolyglotContextImpl.eval(PolyglotContextImpl.java:744)
	at org.graalvm.polyglot.Context.eval(Context.java:335)
	at org.graalvm.polyglot.Context.eval(Context.java:361)
```

**Description**
This is the same issue as #956 

Something changed and Graal works in OSGI container only for rc-11. I'm getting error above on rc-12 and upper versions. 

Seems next piece of code below probably requires else for if (JDK8_OR_EARLIER) condition. I haven't looked deeply but if we loaded engine for jdk8 we don't need to iterate again. Deeply sorry if I'm missing something, but we really want to use fresh version of Graal so I might help. 
@chumer helped to find class /src/org.graalvm.polyglot/src/org/graalvm/polyglot/Engine.java by commit https://github.com/oracle/graal/commit/e38aa347e1de8f8f0474247eb90d193e5ea373d0

**Code snippet(probably buggy code)**
```
if (JDK8_OR_EARLIER) {
                    try {
                        servicesClass = Class.forName("jdk.vm.ci.services.Services");
                    } catch (ClassNotFoundException e) {
                    }
                    if (servicesClass != null) {
                        try {
                            Method m = servicesClass.getDeclaredMethod("loadSingle", Class.class, boolean.class);
                            engine = (AbstractPolyglotImpl) m.invoke(null, AbstractPolyglotImpl.class, false);
                        } catch (Throwable e) {
                            // Fail fast for other errors
                            throw new InternalError(e);
                        }
                    }
                }

                // As of JDK9, the JVMCI Services class should only be used for service
                // types
                // defined by JVMCI. Other services types should use ServiceLoader directly.
                Iterator<AbstractPolyglotImpl> providers = ServiceLoader.load(AbstractPolyglotImpl.class).iterator();
                if (providers.hasNext()) {
                    engine = providers.next();
                    if (providers.hasNext()) {

                        throw new InternalError(String.format("Multiple %s providers found", AbstractPolyglotImpl.class.getName()));
                    }
                }
```
</details>

**Comment by boris-spas** [comment]
Hey @DmitryMiroshnichenko ,

Could you provide a bit more info on how to reproduce this? From your issue description I can only conclude that OSCi is used somewhere but not much else.

**Comment by DmitryMiroshnichenko** [comment]
Hi @boris-spas! 

We use next dependencies below. On 1.0.0-rc11 everything is working, on 1.0.0-rc12 - no.
There is Tomcat 8. And Felix is used as OSGI implementation. We don't have ability to add jars inside Tomcat folders since we build on top of third party app.  
``
            <dependency>
	        <groupId>org.graalvm.sdk</groupId>
	        <artifactId>graal-sdk</artifactId>
	        <version>${graal.version}</version>
	        <scope>compile</scope>
	    </dependency>
	    <dependency>
	        <groupId>org.graalvm.js</groupId>
	        <artifactId>js</artifactId>
	        <version>${graal.version}</version>
	        <scope>compile</scope>
	    </dependency>
	    <dependency>
	        <groupId>org.graalvm.js</groupId>
	        <artifactId>js-scriptengine</artifactId>
	        <version>${graal.version}</version>
	        <scope>compile</scope>
	    </dependency>
	    <dependency>
		  <groupId>org.graalvm.truffle</groupId>
		  <artifactId>truffle-api</artifactId>
		  <version>${graal.version}</version>
		  <scope>compile</scope>
		</dependency>
                        
                <Require-Capability>
    			<![CDATA[osgi.ee;filter:="(&(osgi.ee=JavaSE)(version=1.8))"]]>
  		</Require-Capability>
<properties>
     ....
     <graal.version>1.0.0-rc11</graal.version>
     ....
</properties>
``

**Comment by DmitryMiroshnichenko** [comment]
I did some tests on our environment with both versions. Here are comparison for the rc-11 and rc-12. You will notice where the bug is. Invalid engine is loaded that is intended to be used for JDK9.

[rc-11.txt](https://github.com/oracle/graal/files/4205713/rc-11.txt)
[rc-12.txt](https://github.com/oracle/graal/files/4205714/rc-12.txt)

**Comment by DmitryMiroshnichenko** [comment]
@boris-spas I believe I can fix the problem. Is it ok to send PR?

**Comment by boris-spas** [comment]
Most definitely! We welcome it!

**Comment by warrenc5** [comment]
Hi, I think I also may have this issue.
I'm using 

```
<groupId>org.graalvm.nativeimage</groupId>
<artifactId>native-image-maven-plugin</artifactId>
<version>20.0.0</version>

<buildArgs> --language:js --allow-incomplete-classpath </buildArgs>
```

And 

 `System.err.println("available " + scriptEngineManager.getEngineFactories().stream().map(f -> f.getLanguageName() + " " + f.getEngineName() + " " + f.getEngineVersion()).collect(toList()).toString());
`

results in

>  available []

However I can get an engine with
`engine = scriptEngineManager.getEngineByName("nashorn");`

but "js" returns null engine.

With Graalvm it returns 

> available [ECMAScript Graal.js 20.0.0, ECMAScript Oracle Nashorn 11.0.6]

Is this the same issue? Seems like it to me.

**Comment by hberrayana** [comment]
I have the same issue which started to appear suddenly when executing maven surefire tests.
```
 echo $JAVA_HOME 
 ~/.sdkman/candidates/java/22.2.r17-grl
```

It doesn't happen when I execute the tests on Intellij using the same JDK.

**Comment by wirthi** [comment]
closing an old issue, we have released many times since then, I don't believe this bug is relevant in this current form any longer.
