### ISSUE TITLE
"TypeError: invokeMember" on ProxyObject parameter

### ISSUE THREAD

**Issue by pvanlammeren** [oracle/graal#2139]
- GraalVM version or commit id if built from source: 19.3.1
 - CE or EE: CE
 - JDK version: JDK11
 - OS and OS Version: 4.15.0-76-generic GNU/Linux
 - Architecture: amd64
 - The output of `java -Xinternalversion`: 
```
OpenJDK 64-Bit Server VM (11.0.6+9-jvmci-19.3-b07) for linux-amd64 JRE (11.0.6+9-jvmci-19.3-b07), built on Jan 13 2020 20:43:28 by "buildslave" with gcc 7.3.0
```

When invoking a method with a parameter that implements ProxyObject, a TypeError is thrown:

```
pubic class TypeErrorTest {
	static public class A {
		@HostAccess.Export
		public int test(B b) {
			return b.value;
		}
	}

	static public class B implements ProxyObject {
		public final int value = 1;

		@Override
		public Object getMember(String key) {
			return null;
		}
		@Override
		public Object getMemberKeys() {
			return null;
		}
		@Override
		public boolean hasMember(String key) {
			return false;
		}
		@Override
		public void putMember(String key, Value value) {
		}
	}
	
	static public void main(String[] args) {
		try (Context context = Context.create("js")) {
			context.getBindings("js").putMember("a", new A());
			context.getBindings("js").putMember("b", new B());
			Value value = context.eval("js", "a.test(b);");
			System.out.println(value);
		}
	}
}
```

When the implements clause of B is removed, the above works without issue.

**Expected behavior**
Invoking a method with an argument that implements ProxyObject is expected to behave the same as invoking a method with a (arbitrarily) different type argument. When in the above example method "test" is given a parameter of type org.graalvm.polyglot.Value the ProxyObject implementation is accepted, but this means method overloading cannot be used effectively.

```
Exception in thread "main" TypeError: invokeMember (test) on JavaObject[nl.crossmarx.graal.test.TypeErrorTest$A@6986852 (nl.crossmarx.graal.test.TypeErrorTest$A)] failed due to: UnsupportedTypeException
	at <js> :program(Unnamed:1:0-8)
	at org.graalvm.sdk/org.graalvm.polyglot.Context.eval(Context.java:370)
	at nl.crossmarx.graal.test.TypeErrorTest.main(TypeErrorTest.java:46)
```

**Comment by abhinashood** [comment]
I am also hitting the same error. Could someone please look into it?
When I am trying to pass ProxyObject type of object to Java function called in js it converts to HostProxy (TruffleObject) internally and is unable to cast it to desired Java type.

**Comment by abhinashood** [comment]
@pvanlammeren Were you able to resolve this issue?

**Comment by abhinashood** [comment]
@wirthi @chumer Could you guys also have a look into this.

**Comment by abhinashood** [comment]
@chumer @woess Any update on this ? 
I have added more detailed overview of the issue and also some findings here : https://github.com/oracle/graal/issues/8060

**Comment by chumer** [comment]
Proxy object types can intentionally not be mapped to target types. The of proxy objects is that you fully mimic guest objects and they also don't look like host objects. If you want to support this mapping you should probably use a host object instead.

If you really need this, you can use a target type mapping to resolve this:
```java
	static public class A {
		@HostAccess.Export
		public int test(B b) {
			return b.value;
		}
	}

	static public class B implements ProxyObject {
		public final int value = 1;

		@Override
		public Object getMember(String key) {
			return null;
		}
		@Override
		public Object getMemberKeys() {
			return null;
		}
		@Override
		public boolean hasMember(String key) {
			return false;
		}
		@Override
		public void putMember(String key, Value value) {
		}
	}
	
	static public void main(String[] args) {
		HostAccess access = HostAccess.newBuilder(HostAccess.EXPLICIT) 
				.targetTypeMapping(Value.class, B.class, 
						(v) -> v.isProxyObject() && v.asProxyObject() instanceof B, 
						(v) -> v.asProxyObject()).build();
		try (Context context = Context.newBuilder("js").allowHostAccess(access).build()) {
			context.getBindings("js").putMember("a", new A());
			context.getBindings("js").putMember("b", new B());
			Value value = context.eval("js", "a.test(b);");
			System.out.println(value);
		}
	}
```
