### ISSUE TITLE
Back port JDK-8215355 to GraalVM for CE version 20.0 Java8/11

### ISSUE THREAD

**Issue by helloguo** [oracle/graal#2142]
**Feature request**

Back port JDK-8215355 to GraalVM for CE version 20.0 Java8/11

**Is your feature request related to a problem? Please describe.**
As JDK-8215355 described here https://bugs.openjdk.java.net/browse/JDK-8215355, one bug inside JDK causes deadlock when using jemalloc 5.1. 

**Describe the solution you'd like.**
The fix has been backported to 8u251 and 11.0.7. However, the latest GraalVM dev 20.0 are not based on 8u251 nor 11.0.7. The solution, which is 4 lines of code, should be easy to back ported to the base JDKs that GraalVM is using currently.

**Describe who do you think will benefit the most.**
Folks can enjoy GraalVM 20.0 + jemalloc 5.1 to save more memory.

**Describe alternatives you've considered.**
An alternative solution to upgrade the base JDKs. However, since 11.0.7 is not GA, this alternative solution is not as feasible as the backporting one.

**Additional context.**
https://bugs.openjdk.java.net/browse/JDK-8215355
https://hg.openjdk.java.net/jdk/jdk/rev/189f47d990b5

**Express whether you'd like to help contributing this feature**
If you'd like to contribute, please read the [contribution guide](https://www.graalvm.org/community/contributors/).

**Comment by helloguo** [comment]
Not sure if this is the right place to ask the feature. Or should I post the question at repo https://github.com/graalvm/labs-openjdk-11? Please kindly let me where I should post the question :) However, this feature is a must have feature for us to evaluate the latest Graal. It will be great to have it in version 20.0.

**Comment by dougxc** [comment]
Hi @helloguo , it's too late for this to be in GraalVM 20.0. However, since it's in 8u251 and 11.0.7, it will be included in GraalVM 20.0.1 ([Apr 14](https://www.graalvm.org/docs/release-notes/version-roadmap/)). We may consider backporting it earlier into a labsjdk release in which case it would show up in a GraalVM 20.1 nightly snapshot build.

**Comment by dougxc** [comment]
BTW, this is the right place to request such JDK backports if you're doing so to get them into  GraalVM.

**Comment by helloguo** [comment]
@dougxc Thanks for sharing the information. It's great to know that the fix may be back ported into 20.1 nightly build. Does the nightly build go though the same tests that are used by the release candidates? Just curious how stable the nightly build is.

**Comment by dougxc** [comment]
The nightlies go through the same "gates" as the release builds I believe (@gilles-duboscq can confirm/correct me). However, there is still some extra testing for releases.

**Comment by gilles-duboscq** [comment]
Nightly and release builds are built from branches which pass all the gate tests. However the release branch is subject to some stabilization period which means some bugs discovered in daily, weekly, and manual testing have a chance to get fixed.
While nightly builds from master have passed a fair amount of testing, i wouldn't consider them as stable as the builds from the release branch.

**Comment by helloguo** [comment]
I'm curious whether the fix will be only included in 20.0.1? Or both 20.0.1 and 19.3.2?

**Comment by dougxc** [comment]
It will be in both.
