### ISSUE TITLE
Support SoftReference properly

### ISSUE THREAD

**Issue by bourgesl** [oracle/graal#2145]
As indicated in the GraalVM native image LIMITATIONS about References:
"Support Status: Mostly Supported

What: The package java.lang.ref defines the base class Reference, as well as subclasses for weak, soft, and phantom references. The object that the reference refers to can be deallocated, in which case the reference is updated to contain the value null. With the help of a ReferenceQueue, user code can be executed when a reference gets deallocated.
"

As SoftReference are often used to implement caches that are flushed in the GC detects low memory.
For now in GraalVM 19.3.1, SoftReferences are cleared very early and behaves like WeakReference (short-lived).

For example, the Marlin renderer (used by OpenJFX) uses a SoftReference to hold its own renderer context. Using WeakReference, many contexts are created, everytime a GC young generation clears weak references.

Workaround for OpenJFX: set the System property in the nativeArgs: -Dprism.marlin.useRef=hard

**Comment by bourgesl** [comment]
I agree it is a feature request.
Does this improvement fit in your roadmap soon ?

**Comment by christianwimmer** [comment]
Support for soft references is now merged.
