### ISSUE TITLE
[visualvm] Unable to install plugins

### ISSUE THREAD

**Issue by fniephaus** [oracle/graal#2158]
When I try to install the Visual GC plugin, I get the following error. Unfortunately, I'm unable the resolve the problem.

![image](https://user-images.githubusercontent.com/2368856/74733892-93920080-524d-11ea-94ee-c269e8369e40.png)

```

Version: 

2.0 (Build 200206); platform 20191008-unknown-revn

System: 

Mac OS X (10.15.3) , x86_64 64bit

Java: 

11.0.6; OpenJDK 64-Bit Server VM (11.0.6+9-jvmci-20.0-b02, mixed mode, sharing)

Vendor: 

Oracle Corporation, https://openjdk.java.net/

Environment: 

UTF-8; en_US (visualvm)

User directory: 

/Users/fniephaus/Library/Application Support/VisualVM/graalvm/20.0.0

Cache directory: 

/Users/fniephaus/Library/Caches/VisualVM/graalvm/20.0.0

Clusters: 

/Users/fniephaus/bin/graalvm-ce-java11-20.0.0-dev/Contents/Home/lib/visualvm/platform
/Users/fniephaus/bin/graalvm-ce-java11-20.0.0-dev/Contents/Home/lib/visualvm/visualvm


```

**Comment by jisedlac** [comment]
The 20.0 has not been released yet. Please try again after the release.

**Comment by jisedlac** [comment]
Works fine for me at this moment.

**Comment by fniephaus** [comment]
Thanks, just wanted to make sure this is not an oversight before releasing 20.0. I can confirm it's now working with the 20.0 release.
