### ISSUE TITLE
[gu] Opening up the catalog to the community

### ISSUE THREAD

**Issue by fniephaus** [oracle/graal#2159]
It'd be great if the GraalVM CE Updater catalog could be opened up to the community, so that third-party languages, tools, etc. can be added.
This also requires some sort of documentation for how to contribute to the catalog.

Somewhat related, what are these two undocumented catalog files for?
https://github.com/graalvm/graalvm-ce-dev-builds/blob/55f41bd3c9606ca8296651c110d7637ac0486090/catalog.jdk_8.properties
https://github.com/graalvm/graalvm-ce-dev-builds/blob/55f41bd3c9606ca8296651c110d7637ac0486090/catalog.jdk_11.properties

**Comment by fniephaus** [comment]
Are there any updates on this?

**Comment by performantdata** [comment]
The property names appear to be defined [in `BundleConstants`](https://github.com/oracle/graal/blob/master/vm/src/org.graalvm.component.installer/src/org/graalvm/component/installer/BundleConstants.java). [`RemotePropertiesStorage.loadComponentMetadata`](https://github.com/oracle/graal/blob/89e4cfc7aeea69970b60c64cd075ceb2a104e864/vm/src/org.graalvm.component.installer/src/org/graalvm/component/installer/remote/RemotePropertiesStorage.java#L175) appears to be central to the loading.

**Comment by fniephaus** [comment]
GraalVM updater has been removed [#6855](https://github.com/oracle/graal/issues/6855) so this is no longer relevant.
