### ISSUE TITLE
JNI can't access field of Java object

### ISSUE THREAD

**Issue by aliegeois** [oracle/graal#2163]
**GraalVM and environment :**
 - GraalVM version : **19.3.1**
 - **CE**
 - JDK version: **OpenJDK 1.8.0_242-b06** (bundled with GraalVM)
 - Native compiler/linker information: **clang 8.0.0** (bundled with GraalVM)

 - OS and OS Version: **WSL Debian on Windows 10 Pro**
 - The output of `java -Xinternalversion`: 
```
OpenJDK 64-Bit GraalVM CE 19.3.1 (25.242-b06-jvmci-19.3-b07) for linux-amd64 JRE (8u242), built on Jan 13 2020 23:00:49 by "buildslave" with gcc 7.3.0
```

Hello!

I'm trying to create a simple application that can execute some c code from a java context and interact with it (so basically JNI) but it must be portable (thanks to llvm) so GraalVM seems the best option.
I've managed to make Java and C interact with each other but when I try to build an application with native-image, JNI suddenly can't interact with Java.
A small repository with minimal code is available here: https://github.com/aliegeois/native-image-jni/

The relevant code is the following:
- Java code:
```java
public class App {
	static {
		System.loadLibrary("native");
	}

	private int x = 4;

	public int getX() {
		return x;
	}

	public native void change();

	public static void main(String[] args) {
		App app = new App();
		System.out.println("Before JNI: x = " + app.getX());
		app.change();
		System.out.println("After JNI: x = " + app.getX());
	}
}
```
- C code:
```c
#include "App.h"

JNIEXPORT void JNICALL Java_App_change(JNIEnv *env, jobject thisObject)
{
	jclass thisObjectClass = (*env)->GetObjectClass(env, thisObject);
	jfieldID xField = (*env)->GetFieldID(env, thisObjectClass, "x", "I");

	(*env)->SetIntField(env, thisObject, xField, 7);
}
```

Then I build the app with native-image (no problem) and an executable is created.
But when I start it I have the following error:

```
native-image-jni$ ./app
Before JNI: x = 4
Exception in thread "main" java.lang.NoSuchFieldError: App.x
        at com.oracle.svm.jni.functions.JNIFunctions$Support.getFieldID(JNIFunctions.java:1041)
        at com.oracle.svm.jni.functions.JNIFunctions.GetFieldID(JNIFunctions.java:393)
        at App.change(App.java)
        at App.main(App.java:17)
```

I have the following `jni-config.json` to indicate which fields can be accessed/modified:
```json
[
	{
		"name": "App",
		"fields": [
			{
				"name": "x",
				"allowWrite": true
			}
		]
	}
]
```

Without native-image the code is executed correctly:
```
native-image-jni$ java -cp . -Djava.library.path=. App
Before JNI: x = 4
After JNI: x = 7
```

I'm a bit lost so I'm looking for advice on how to make all of this work.

Thanks

**Comment by dougxc** [comment]
Hi @aliegeois , looks like you're reflection configuration: https://github.com/oracle/graal/blob/master/substratevm/JNI.md#reflection

**Comment by jramirez-isc** [comment]
Hi @aliegeois ,
I can see in [this line](https://github.com/aliegeois/native-image-jni/blob/master/makefile#L7) that you are using `-H:ReflectionConfigurationFiles=./jni-config.json` to specify the JNI config. But the correct option to use is `-H:JNIConfigurationFiles`. If you replace it the native image works fine with your code.
As @dougxc commented, you can see this in the [docs](https://github.com/oracle/graal/blob/master/substratevm/JNI.md#reflection).
