### ISSUE TITLE
I don't understand nothing at Community Edition installation on Windows

### ISSUE THREAD

**Issue by Leznodc** [oracle/graal#2165]
Commands that are described within the on-line documentation aren't where they are described to be.

**Comment by xzel23** [comment]
Maybe it would be easier if you pointed out the exact document and text passage that you are referring to. A report without sufficient information just wastes developer time.

**Comment by olyagpl** [comment]
@Leznodc, have you tried steps provided on https://docs.oracle.com/en/graalvm/enterprise/20/guide/overview/install/installation-windows.html ? They are the same for both GraalVM Enterprise and Community. 

Let me know your experience. 
Olya

**Comment by jbreathe** [comment]
@olyagpl, It would be great to see the information from this guide in the documentation on graalvm.org/docs too. In the "Prerequisites" on [this page](https://www.graalvm.org/docs/reference-manual/native-image/) for example.
I thought #1852 is also about this.

**Comment by olyagpl** [comment]
@Leznodc, your suggestion has been followed https://www.graalvm.org/docs/getting-started/#install-graalvm. We mention also the prerequisites for using Native Image on Windows.
Thank you,
Olya

**Comment by Leznodc** [comment]
Thanks.

I stopped using it from windows anyway. Running into Ubuntu in Virtual Box
is far easier.

Regards

Le ven. 3 avr. 2020 à 16:45, Olga Gupalo <notifications@github.com> a
écrit :
