### ISSUE TITLE
[native-image]com.oracle.svm.core.util.VMError$HostedError: class com.sun.xml.internal.bind.v2.ContextFactory not found on Windows

### ISSUE THREAD

**Issue by legendaryhero1981** [oracle/graal#2169]
Tested with graalvm-ce-java11-20.0.0-dev.

`D:\games>native-image -jar jar\graalvm\game.jar native\game --verbose --no-fallback --static -H:+ReportExceptionStackTraces -cp "jmod\jaxb\jaxb-runtime-2.3.2.jar;jmod\jaxb\jakarta.xml.bind-api-2.3.2.jar;jmod\jaxb\txw2-2.3.2.jar;jmod\jaxb\stax-ex-1.8.1.jar;jmod\jaxb\FastInfoset-1.2.16.jar;jmod\jaxb\istack-commons-runtime-3.0.8.jar;jmod\jaxb\jakarta.activation-api-1.2.1.jar"
Executing [
E:\Java\graalvm-ce-java11-20.0.0-dev\bin\java.exe \
-XX:+UnlockExperimentalVMOptions \
-XX:+EnableJVMCI \
-Dtruffle.TrustAllTruffleRuntimeProviders=true \
-Dtruffle.TruffleRuntime=com.oracle.truffle.api.impl.DefaultTruffleRuntime \
-Dgraalvm.ForcePolyglotInvalid=true \
-Dgraalvm.locatorDisabled=true \
-Dsubstratevm.IgnoreGraalVersionCheck=true \
-Djava.lang.invoke.stringConcat=BC_SB \
--add-exports \
jdk.internal.vm.ci/jdk.vm.ci.runtime=ALL-UNNAMED \
--add-exports \
jdk.internal.vm.ci/jdk.vm.ci.code=ALL-UNNAMED \
--add-exports \
jdk.internal.vm.ci/jdk.vm.ci.aarch64=ALL-UNNAMED \
--add-exports \
jdk.internal.vm.ci/jdk.vm.ci.amd64=ALL-UNNAMED \
--add-exports \
jdk.internal.vm.ci/jdk.vm.ci.meta=ALL-UNNAMED \
--add-exports \
jdk.internal.vm.ci/jdk.vm.ci.hotspot=ALL-UNNAMED \
--add-exports \
jdk.internal.vm.ci/jdk.vm.ci.services=ALL-UNNAMED \
--add-exports \
jdk.internal.vm.ci/jdk.vm.ci.common=ALL-UNNAMED \
--add-exports \
jdk.internal.vm.ci/jdk.vm.ci.code.site=ALL-UNNAMED \
--add-exports \
jdk.internal.vm.ci/jdk.vm.ci.code.stack=ALL-UNNAMED \
--add-opens \
jdk.internal.vm.compiler/org.graalvm.compiler.debug=ALL-UNNAMED \
--add-opens \
jdk.internal.vm.compiler/org.graalvm.compiler.nodes=ALL-UNNAMED \
--add-opens \
jdk.unsupported/sun.reflect=ALL-UNNAMED \
--add-opens \
java.base/jdk.internal.module=ALL-UNNAMED \
--add-opens \
java.base/jdk.internal.ref=ALL-UNNAMED \
--add-opens \
java.base/jdk.internal.reflect=ALL-UNNAMED \
--add-opens \
java.base/java.io=ALL-UNNAMED \
--add-opens \
java.base/java.lang=ALL-UNNAMED \
--add-opens \
java.base/java.lang.reflect=ALL-UNNAMED \
--add-opens \
java.base/java.lang.invoke=ALL-UNNAMED \
--add-opens \
java.base/java.lang.ref=ALL-UNNAMED \
--add-opens \
java.base/java.net=ALL-UNNAMED \
--add-opens \
java.base/java.nio=ALL-UNNAMED \
--add-opens \
java.base/java.nio.file=ALL-UNNAMED \
--add-opens \
java.base/java.security=ALL-UNNAMED \
--add-opens \
java.base/javax.crypto=ALL-UNNAMED \
--add-opens \
java.base/java.util=ALL-UNNAMED \
--add-opens \
java.base/java.util.concurrent.atomic=ALL-UNNAMED \
--add-opens \
java.base/sun.security.x509=ALL-UNNAMED \
--add-opens \
java.base/jdk.internal.logger=ALL-UNNAMED \
--add-opens \
org.graalvm.sdk/org.graalvm.nativeimage.impl=ALL-UNNAMED \
--add-opens \
org.graalvm.sdk/org.graalvm.polyglot=ALL-UNNAMED \
--add-opens \
org.graalvm.truffle/com.oracle.truffle.polyglot=ALL-UNNAMED \
--add-opens \
org.graalvm.truffle/com.oracle.truffle.api.impl=ALL-UNNAMED \
-XX:+UseJVMCINativeLibrary \
-Xss10m \
-Xms1g \
-Xmx14g \
-Duser.country=US \
-Duser.language=en \
-Djava.awt.headless=true \
-Dorg.graalvm.version=20.0.0-dev \
-Dorg.graalvm.config=CE \
-Dcom.oracle.graalvm.isaot=true \
-Djava.system.class.loader=com.oracle.svm.hosted.NativeImageSystemClassLoader \
-Xshare:off \
--module-path \
E:\Java\graalvm-ce-java11-20.0.0-dev\lib\truffle\truffle-api.jar \
-javaagent:E:\Java\graalvm-ce-java11-20.0.0-dev\lib\svm\builder\svm.jar \
-Djdk.internal.lambda.disableEagerInitialization=true \
-Djdk.internal.lambda.eagerlyInitialize=false \
-Djava.lang.invoke.InnerClassLambdaMetafactory.initializeLambdas=false \
-cp \
E:\Java\graalvm-ce-java11-20.0.0-dev\lib\svm\builder\objectfile.jar;E:\Java\graalvm-ce-java11-20.0.0-dev\lib\svm\builder\pointsto.jar;E:\Java\graalvm-ce-java11-20.0.0-dev\lib\svm\builder\svm.jar \
com.oracle.svm.hosted.NativeImageGeneratorRunner$JDK9Plus \
-imagecp \
E:\Java\graalvm-ce-java11-20.0.0-dev\lib\svm\builder\objectfile.jar;E:\Java\graalvm-ce-java11-20.0.0-dev\lib\svm\builder\pointsto.jar;E:\Java\graalvm-ce-java11-20.0.0-dev\lib\svm\builder\svm.jar;E:\Java\graalvm-ce-java11-20.0.0-dev\lib\svm\library-support.jar;D:\games\jmod\jaxb\jakarta.xml.bind-api-2.3.2.jar;D:\games\jmod\jaxb\txw2-2.3.2.jar;D:\games\jmod\jaxb\istack-commons-runtime-3.0.8.jar;D:\games\jmod\jaxb\stax-ex-1.8.1.jar;D:\games\jmod\jaxb\FastInfoset-1.2.16.jar;D:\games\jmod\jaxb\jakarta.activation-api-1.2.1.jar;D:\games\jar\graalvm\game.jar;D:\games\jmod\jaxb\jaxb-runtime-2.3.2.jar \
-H:Path=D:\games \
-H:Class=legend.Main \
-H:FallbackThreshold=0 \
-H:+StaticExecutable \
-H:+ReportExceptionStackTraces \
-H:CLibraryPath=E:\Java\graalvm-ce-java11-20.0.0-dev\lib\svm\clibraries\windows-amd64 \
-H:Name=native\game
]
[native\game:6096]    classlist:   1,291.69 ms,  1.21 GB
[native\game:6096]        (cap):   7,492.68 ms,  1.21 GB
[native\game:6096]        setup:   9,039.14 ms,  1.21 GB
[native\game:6096]     analysis:   6,421.41 ms,  1.46 GB
Fatal error: com.oracle.svm.core.util.VMError$HostedError: class com.sun.xml.internal.bind.v2.ContextFactory not found
        at com.oracle.svm.core.util.VMError.guarantee(VMError.java:85)
        at com.oracle.svm.core.jdk.JNIRegistrationUtil.clazz(JNIRegistrationUtil.java:78)
        at com.oracle.svm.hosted.config.JAXBClassAndResourcesLoaderFeature.registerReflectionClasses(JAXBClassAndResourcesLoaderFeature.java:70)
        at com.oracle.svm.hosted.config.JAXBClassAndResourcesLoaderFeature.registerJavaxXmlConfigs(JAXBClassAndResourcesLoaderFeature.java:62)
        at com.oracle.svm.hosted.ReachabilityHandlerFeature.duringAnalysis(ReachabilityHandlerFeature.java:114)
        at com.oracle.svm.hosted.NativeImageGenerator.lambda$runPointsToAnalysis$8(NativeImageGenerator.java:715)
        at com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:63)
        at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:715)
        at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:530)
        at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:445)
        at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
Error: Image build request failed with exit status 1
com.oracle.svm.driver.NativeImage$NativeImageError: Image build request failed with exit status 1
        at com.oracle.svm.driver.NativeImage.showError(NativeImage.java:1527)
        at com.oracle.svm.driver.NativeImage.build(NativeImage.java:1289)
        at com.oracle.svm.driver.NativeImage.performBuild(NativeImage.java:1250)
        at com.oracle.svm.driver.NativeImage.main(NativeImage.java:1209)
        at com.oracle.svm.driver.NativeImage$JDK9Plus.main(NativeImage.java:1707)`

Special Note:
I used the same command to compile successfully under graalvm-ce-java11-windows-amd64-19.3.1, but I will get an error when running game.exe. The error information is the same as this link: [https://github.com/oracle/graal/issues/1871]

In addition, I checked the source code of the jaxb-ri version 2.3.2 project, and I can confirm that the project does not reference the package com.sun.xml.internal.bind.v2, but instead references com.sun.xml.bind.v2, because I have paid close attention to the release of previous JDK versions, I can confirm that the package com.sun.xml.internal.bind has been removed from java11 and marked as outdated in java9 and java10, I am surprised to report this error. Repeated adjustment of the parameter test can not compile successfully multiple times, only to ask the graalvm project team to solve it.

**Comment by legendaryhero1981** [comment]
### Attach the latest test results.
**1. Test scenario: use jaxb-ri version 2.3.2 in game.jar.
Tested with graalvm-ee-java11-20.0.0.**



`d:\games>native-image -jar jar\jvm\game.jar "native\native" --verbose --no-fallback --static -H:+ReportExceptionStackTraces -cp "jmod\jaxb\2.3.2\jaxb-runtime-2.3.2.jar;jmod\jaxb\2.3.2\jakarta.xml.bind-api-2.3.2.jar;jmod\jaxb\2.3.2\txw2-2.3.2.jar;jmod\jaxb\2.3.2\stax-ex-1.8.1.jar;jmod\jaxb\2.3.2\FastInfoset-1.2.16.jar;jmod\jaxb\2.3.2\istack-commons-runtime-3.0.8.jar;jmod\jaxb\2.3.2\jakarta.activation-api-1.2.1.jar"
Executing [
E:\Java\graalvm-java11\bin\java.exe \
-XX:+UnlockExperimentalVMOptions \
-XX:+EnableJVMCI \
-Dtruffle.TrustAllTruffleRuntimeProviders=true \
-Dtruffle.TruffleRuntime=com.oracle.truffle.api.impl.DefaultTruffleRuntime \
-Dgraalvm.ForcePolyglotInvalid=true \
-Dgraalvm.locatorDisabled=true \
-Dsubstratevm.IgnoreGraalVersionCheck=true \
-Djava.lang.invoke.stringConcat=BC_SB \
--add-exports \
jdk.internal.vm.ci/jdk.vm.ci.runtime=ALL-UNNAMED \
--add-exports \
jdk.internal.vm.ci/jdk.vm.ci.code=ALL-UNNAMED \
--add-exports \
jdk.internal.vm.ci/jdk.vm.ci.aarch64=ALL-UNNAMED \
--add-exports \
jdk.internal.vm.ci/jdk.vm.ci.amd64=ALL-UNNAMED \
--add-exports \
jdk.internal.vm.ci/jdk.vm.ci.meta=ALL-UNNAMED \
--add-exports \
jdk.internal.vm.ci/jdk.vm.ci.hotspot=ALL-UNNAMED \
--add-exports \
jdk.internal.vm.ci/jdk.vm.ci.services=ALL-UNNAMED \
--add-exports \
jdk.internal.vm.ci/jdk.vm.ci.common=ALL-UNNAMED \
--add-exports \
jdk.internal.vm.ci/jdk.vm.ci.code.site=ALL-UNNAMED \
--add-exports \
jdk.internal.vm.ci/jdk.vm.ci.code.stack=ALL-UNNAMED \
--add-opens \
jdk.internal.vm.compiler/org.graalvm.compiler.debug=ALL-UNNAMED \
--add-opens \
jdk.internal.vm.compiler/org.graalvm.compiler.nodes=ALL-UNNAMED \
--add-opens \
jdk.unsupported/sun.reflect=ALL-UNNAMED \
--add-opens \
java.base/jdk.internal.module=ALL-UNNAMED \
--add-opens \
java.base/jdk.internal.ref=ALL-UNNAMED \
--add-opens \
java.base/jdk.internal.reflect=ALL-UNNAMED \
--add-opens \
java.base/java.io=ALL-UNNAMED \
--add-opens \
java.base/java.lang=ALL-UNNAMED \
--add-opens \
java.base/java.lang.reflect=ALL-UNNAMED \
--add-opens \
java.base/java.lang.invoke=ALL-UNNAMED \
--add-opens \
java.base/java.lang.ref=ALL-UNNAMED \
--add-opens \
java.base/java.net=ALL-UNNAMED \
--add-opens \
java.base/java.nio=ALL-UNNAMED \
--add-opens \
java.base/java.nio.file=ALL-UNNAMED \
--add-opens \
java.base/java.security=ALL-UNNAMED \
--add-opens \
java.base/javax.crypto=ALL-UNNAMED \
--add-opens \
java.base/java.util=ALL-UNNAMED \
--add-opens \
java.base/java.util.concurrent.atomic=ALL-UNNAMED \
--add-opens \
java.base/sun.security.x509=ALL-UNNAMED \
--add-opens \
java.base/jdk.internal.logger=ALL-UNNAMED \
--add-opens \
org.graalvm.sdk/org.graalvm.nativeimage.impl=ALL-UNNAMED \
--add-opens \
org.graalvm.sdk/org.graalvm.polyglot=ALL-UNNAMED \
--add-opens \
org.graalvm.truffle/com.oracle.truffle.polyglot=ALL-UNNAMED \
--add-opens \
org.graalvm.truffle/com.oracle.truffle.api.impl=ALL-UNNAMED \
-XX:+UseJVMCINativeLibrary \
-Xss10m \
-Xms1g \
-Xmx14g \
-Duser.country=US \
-Duser.language=en \
-Djava.awt.headless=true \
-Dorg.graalvm.version=20.0.0 \
-Dorg.graalvm.config=EE \
-Dcom.oracle.graalvm.isaot=true \
-Djava.system.class.loader=com.oracle.svm.hosted.NativeImageSystemClassLoader \
-Xshare:off \
--module-path \
E:\Java\graalvm-java11\lib\truffle\truffle-api.jar \
-javaagent:E:\Java\graalvm-java11\lib\svm\builder\svm.jar \
-Djdk.internal.lambda.disableEagerInitialization=true \
-Djdk.internal.lambda.eagerlyInitialize=false \
-Djava.lang.invoke.InnerClassLambdaMetafactory.initializeLambdas=false \
-cp \
E:\Java\graalvm-java11\lib\svm\builder\objectfile.jar;E:\Java\graalvm-java11\lib\svm\builder\pointsto.jar;E:\Java\graalvm-java11\lib\svm\builder\svm-enterprise.jar;E:\Java\graalvm-java11\lib\svm\builder\svm.jar \
com.oracle.svm.hosted.NativeImageGeneratorRunner$JDK9Plus \
-imagecp \
E:\Java\graalvm-java11\lib\svm\builder\objectfile.jar;E:\Java\graalvm-java11\lib\svm\builder\pointsto.jar;E:\Java\graalvm-java11\lib\svm\builder\svm-enterprise.jar;E:\Java\graalvm-java11\lib\svm\builder\svm.jar;E:\Java\graalvm-java11\lib\svm\library-support-enterprise.jar;E:\Java\graalvm-java11\lib\svm\library-support.jar;D:\games\jmod\jaxb\2.3.2\jakarta.xml.bind-api-2.3.2.jar;D:\games\jmod\jaxb\2.3.2\txw2-2.3.2.jar;D:\games\jmod\jaxb\2.3.2\istack-commons-runtime-3.0.8.jar;D:\games\jmod\jaxb\2.3.2\stax-ex-1.8.1.jar;D:\games\jmod\jaxb\2.3.2\FastInfoset-1.2.16.jar;D:\games\jmod\jaxb\2.3.2\jakarta.activation-api-1.2.1.jar;D:\games\jar\jvm\game.jar;D:\games\jmod\jaxb\2.3.2\jaxb-runtime-2.3.2.jar \
-H:Path=d:\games \
-H:Class=legend.Main \
-H:FallbackThreshold=0 \
-H:+StaticExecutable \
-H:+ReportExceptionStackTraces \
-H:CLibraryPath=E:\Java\graalvm-java11\lib\svm\clibraries\windows-amd64 \
-H:Name=native\native
]
[native\native:10084]    classlist:   1,530.82 ms,  1.23 GB
[native\native:10084]        (cap):   2,292.26 ms,  1.23 GB
[native\native:10084]        setup:   4,649.92 ms,  1.23 GB
[native\native:10084]   (typeflow):   9,453.92 ms,  2.76 GB
[native\native:10084]    (objects):   7,354.91 ms,  2.76 GB
[native\native:10084]   (features):     621.58 ms,  2.76 GB
[native\native:10084]     analysis:  17,924.05 ms,  2.76 GB
[native\native:10084]     (clinit):     326.70 ms,  2.76 GB
[native\native:10084]     universe:     861.72 ms,  2.76 GB
[native\native:10084]      (parse):   2,009.74 ms,  2.76 GB
[native\native:10084]     (inline):   1,825.20 ms,  3.89 GB
[native\native:10084]    (compile):  23,209.87 ms,  3.89 GB
[native\native:10084]      compile:  28,233.65 ms,  3.89 GB
[native\native:10084]        image:   1,793.53 ms,  3.89 GB
Warning: Generating and stripping of debug info not supported on Windows[native\native:10084]        write:   1,096.92 ms,  3.89 GB
[native\native:10084]      [total]:  56,299.73 ms,  3.89 GB`

**The native image command can be compiled successfully, but it is wrong to run native.exe.**

`javax.xml.bind.JAXBException - with linked exception:
[java.lang.NoSuchMethodException: com.sun.xml.bind.v2.ContextFactory.createContext([Ljava.lang.Class;, java.util.Map)]`


**2. Test scenario: use the latest JAXB RI version 2.4.0 in game.jar.
Tested with graalvm-ee-java11-20.0.0.**

**The native image command failed to compile.**

`d:\games>native-image -jar jar\jvm\game.jar "native\native" --verbose --no-fallback --static -H:+ReportExceptionStackTraces -cp "jmod\jaxb\new\jaxb-impl-2.4.0.jar;jmod\jaxb\new\jakarta.xml.bind-api-2.3.2.jar;jmod\jaxb\new\stax-ex-1.8.2.jar;jmod\jaxb\new\FastInfoset-1.2.17.jar;jmod\jaxb\new\jakarta.activation-1.2.1.jar"
Executing [
E:\Java\graalvm-java11\bin\java.exe \
-XX:+UnlockExperimentalVMOptions \
-XX:+EnableJVMCI \
-Dtruffle.TrustAllTruffleRuntimeProviders=true \
-Dtruffle.TruffleRuntime=com.oracle.truffle.api.impl.DefaultTruffleRuntime \
-Dgraalvm.ForcePolyglotInvalid=true \
-Dgraalvm.locatorDisabled=true \
-Dsubstratevm.IgnoreGraalVersionCheck=true \
-Djava.lang.invoke.stringConcat=BC_SB \
--add-exports \
jdk.internal.vm.ci/jdk.vm.ci.runtime=ALL-UNNAMED \
--add-exports \
jdk.internal.vm.ci/jdk.vm.ci.code=ALL-UNNAMED \
--add-exports \
jdk.internal.vm.ci/jdk.vm.ci.aarch64=ALL-UNNAMED \
--add-exports \
jdk.internal.vm.ci/jdk.vm.ci.amd64=ALL-UNNAMED \
--add-exports \
jdk.internal.vm.ci/jdk.vm.ci.meta=ALL-UNNAMED \
--add-exports \
jdk.internal.vm.ci/jdk.vm.ci.hotspot=ALL-UNNAMED \
--add-exports \
jdk.internal.vm.ci/jdk.vm.ci.services=ALL-UNNAMED \
--add-exports \
jdk.internal.vm.ci/jdk.vm.ci.common=ALL-UNNAMED \
--add-exports \
jdk.internal.vm.ci/jdk.vm.ci.code.site=ALL-UNNAMED \
--add-exports \
jdk.internal.vm.ci/jdk.vm.ci.code.stack=ALL-UNNAMED \
--add-opens \
jdk.internal.vm.compiler/org.graalvm.compiler.debug=ALL-UNNAMED \
--add-opens \
jdk.internal.vm.compiler/org.graalvm.compiler.nodes=ALL-UNNAMED \
--add-opens \
jdk.unsupported/sun.reflect=ALL-UNNAMED \
--add-opens \
java.base/jdk.internal.module=ALL-UNNAMED \
--add-opens \
java.base/jdk.internal.ref=ALL-UNNAMED \
--add-opens \
java.base/jdk.internal.reflect=ALL-UNNAMED \
--add-opens \
java.base/java.io=ALL-UNNAMED \
--add-opens \
java.base/java.lang=ALL-UNNAMED \
--add-opens \
java.base/java.lang.reflect=ALL-UNNAMED \
--add-opens \
java.base/java.lang.invoke=ALL-UNNAMED \
--add-opens \
java.base/java.lang.ref=ALL-UNNAMED \
--add-opens \
java.base/java.net=ALL-UNNAMED \
--add-opens \
java.base/java.nio=ALL-UNNAMED \
--add-opens \
java.base/java.nio.file=ALL-UNNAMED \
--add-opens \
java.base/java.security=ALL-UNNAMED \
--add-opens \
java.base/javax.crypto=ALL-UNNAMED \
--add-opens \
java.base/java.util=ALL-UNNAMED \
--add-opens \
java.base/java.util.concurrent.atomic=ALL-UNNAMED \
--add-opens \
java.base/sun.security.x509=ALL-UNNAMED \
--add-opens \
java.base/jdk.internal.logger=ALL-UNNAMED \
--add-opens \
org.graalvm.sdk/org.graalvm.nativeimage.impl=ALL-UNNAMED \
--add-opens \
org.graalvm.sdk/org.graalvm.polyglot=ALL-UNNAMED \
--add-opens \
org.graalvm.truffle/com.oracle.truffle.polyglot=ALL-UNNAMED \
--add-opens \
org.graalvm.truffle/com.oracle.truffle.api.impl=ALL-UNNAMED \
-XX:+UseJVMCINativeLibrary \
-Xss10m \
-Xms1g \
-Xmx14g \
-Duser.country=US \
-Duser.language=en \
-Djava.awt.headless=true \
-Dorg.graalvm.version=20.0.0 \
-Dorg.graalvm.config=EE \
-Dcom.oracle.graalvm.isaot=true \
-Djava.system.class.loader=com.oracle.svm.hosted.NativeImageSystemClassLoader \
-Xshare:off \
--module-path \
E:\Java\graalvm-java11\lib\truffle\truffle-api.jar \
-javaagent:E:\Java\graalvm-java11\lib\svm\builder\svm.jar \
-Djdk.internal.lambda.disableEagerInitialization=true \
-Djdk.internal.lambda.eagerlyInitialize=false \
-Djava.lang.invoke.InnerClassLambdaMetafactory.initializeLambdas=false \
-cp \
E:\Java\graalvm-java11\lib\svm\builder\objectfile.jar;E:\Java\graalvm-java11\lib\svm\builder\pointsto.jar;E:\Java\graalvm-java11\lib\svm\builder\svm-enterprise.jar;E:\Java\graalvm-java11\lib\svm\builder\svm.jar \
com.oracle.svm.hosted.NativeImageGeneratorRunner$JDK9Plus \
-imagecp \
E:\Java\graalvm-java11\lib\svm\builder\objectfile.jar;E:\Java\graalvm-java11\lib\svm\builder\pointsto.jar;E:\Java\graalvm-java11\lib\svm\builder\svm-enterprise.jar;E:\Java\graalvm-java11\lib\svm\builder\svm.jar;E:\Java\graalvm-java11\lib\svm\library-support-enterprise.jar;E:\Java\graalvm-java11\lib\svm\library-support.jar;D:\games\jar\jvm\game.jar;D:\games\jmod\jaxb\new\jaxb-impl-2.4.0.jar;D:\games\jmod\jaxb\new\jakarta.xml.bind-api-2.3.2.jar;D:\games\jmod\jaxb\new\stax-ex-1.8.2.jar;D:\games\jmod\jaxb\new\FastInfoset-1.2.17.jar;D:\games\jmod\jaxb\new\jakarta.activation-1.2.1.jar \
-H:Path=d:\games \
-H:Class=legend.Main \
-H:FallbackThreshold=0 \
-H:+StaticExecutable \
-H:+ReportExceptionStackTraces \
-H:CLibraryPath=E:\Java\graalvm-java11\lib\svm\clibraries\windows-amd64 \
-H:Name=native\native
]
[native\native:21176]    classlist:   2,025.28 ms,  1.00 GB
[native\native:21176]        (cap):   6,247.30 ms,  1.00 GB
[native\native:21176]        setup:   8,898.33 ms,  1.20 GB
[native\native:21176]   (typeflow):  11,867.15 ms,  2.04 GB
[native\native:21176]    (objects):   9,273.86 ms,  2.04 GB
[native\native:21176]   (features):     811.11 ms,  2.04 GB
[native\native:21176]     analysis:  22,646.76 ms,  2.04 GB
Error: Detected a started Thread in the image heap. Threads running in the image generator are no longer running at image run time.  To see how this object got instantiated use -H:+TraceClassInitialization. The object was probably created by a class initializer and is reachable from a static field. You can request class initialization at image run time by using the option --initialize-at-run-time=<class-name>. Or you can write your own initialization methods and call them explicitly from your main entry point.
Detailed message:
Trace: Object was reached by
        reading field sun.awt.AWTAutoShutdown.blockerThread of
                constant sun.awt.AWTAutoShutdown@43fede49 reached by
        scanning method sun.awt.AWTAutoShutdown.getInstance(AWTAutoShutdown.java:132)
Call path from entry point to sun.awt.AWTAutoShutdown.getInstance():
        at sun.awt.AWTAutoShutdown.getInstance(AWTAutoShutdown.java:132)
        at java.awt.EventQueue.detachDispatchThread(EventQueue.java:1152)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:96)
        at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:527)
        at com.oracle.svm.core.windows.WindowsJavaThreads.osThreadStartRoutine(WindowsJavaThreads.java:138)
        at com.oracle.svm.core.code.IsolateEnterStub.WindowsJavaThreads_osThreadStartRoutine_4bc03aa26f8cdfc97ebd54050e8ae4bce1023851(generated:0)

com.oracle.svm.core.util.UserError$UserException: Detected a started Thread in the image heap. Threads running in the image generator are no longer running at image run time.  To see how this object got instantiated use -H:+TraceClassInitialization. The object was probably created by a class initializer and is reachable from a static field. You can request class initialization at image run time by using the option --initialize-at-run-time=<class-name>. Or you can write your own initialization methods and call them explicitly from your main entry point.
Detailed message:
Trace: Object was reached by
        reading field sun.awt.AWTAutoShutdown.blockerThread of
                constant sun.awt.AWTAutoShutdown@43fede49 reached by
        scanning method sun.awt.AWTAutoShutdown.getInstance(AWTAutoShutdown.java:132)
Call path from entry point to sun.awt.AWTAutoShutdown.getInstance():
        at sun.awt.AWTAutoShutdown.getInstance(AWTAutoShutdown.java:132)
        at java.awt.EventQueue.detachDispatchThread(EventQueue.java:1152)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:96)
        at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:527)
        at com.oracle.svm.core.windows.WindowsJavaThreads.osThreadStartRoutine(WindowsJavaThreads.java:138)
        at com.oracle.svm.core.code.IsolateEnterStub.WindowsJavaThreads_osThreadStartRoutine_4bc03aa26f8cdfc97ebd54050e8ae4bce1023851(generated:0)

        at com.oracle.svm.core.util.UserError.abort(UserError.java:79)
        at com.oracle.svm.hosted.FallbackFeature.reportAsFallback(FallbackFeature.java:221)
        at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:741)
        at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:530)
        at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:445)
        at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
Caused by: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: Detected a started Thread in the image heap. Threads running in the image generator are no longer running at image run time.  To see how this object got instantiated use -H:+TraceClassInitialization. The object was probably created by a class initializer and is reachable from a static field. You can request class initialization at image run time by using the option --initialize-at-run-time=<class-name>. Or you can write your own initialization methods and call them explicitly from your main entry point.
Detailed message:
Trace: Object was reached by
        reading field sun.awt.AWTAutoShutdown.blockerThread of
                constant sun.awt.AWTAutoShutdown@43fede49 reached by
        scanning method sun.awt.AWTAutoShutdown.getInstance(AWTAutoShutdown.java:132)
Call path from entry point to sun.awt.AWTAutoShutdown.getInstance():
        at sun.awt.AWTAutoShutdown.getInstance(AWTAutoShutdown.java:132)
        at java.awt.EventQueue.detachDispatchThread(EventQueue.java:1152)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:96)
        at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:527)
        at com.oracle.svm.core.windows.WindowsJavaThreads.osThreadStartRoutine(WindowsJavaThreads.java:138)
        at com.oracle.svm.core.code.IsolateEnterStub.WindowsJavaThreads_osThreadStartRoutine_4bc03aa26f8cdfc97ebd54050e8ae4bce1023851(generated:0)

        at com.oracle.graal.pointsto.constraints.UnsupportedFeatures.report(UnsupportedFeatures.java:126)
        at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:738)
        ... 8 more
Error: Image build request failed with exit status 1
com.oracle.svm.driver.NativeImage$NativeImageError: Image build request failed with exit status 1
        at com.oracle.svm.driver.NativeImage.showError(NativeImage.java:1527)
        at com.oracle.svm.driver.NativeImage.build(NativeImage.java:1289)
        at com.oracle.svm.driver.NativeImage.performBuild(NativeImage.java:1250)
        at com.oracle.svm.driver.NativeImage.main(NativeImage.java:1209)
        at com.oracle.svm.driver.NativeImage$JDK9Plus.main(NativeImage.java:1707)`

**Comment by legendaryhero1981** [comment]
3. Attach the detailed test result file after the adjustment of parameters.
[file.log.gz](https://github.com/oracle/graal/files/4271784/file.log.gz)

**Comment by legendaryhero1981** [comment]
4. This is the command line that I can use the JLINK command to generate the image successfully and run normally:
**jlink --verbose --compress 2 --strip-debug --output jlink\jvm\game -p jar\jvm;jmod\jaxb\new --add-modules legend,com.sun.xml.bind**

**Comment by legendaryhero1981** [comment]
@thomaswue

**Comment by galderz** [comment]
I've just encountered a very similar exception testing master with quarkus: https://github.com/quarkusio/quarkus/issues/7914.

**Comment by jaikiran** [comment]
I suspect, with the recent commit[1] that went into master, this should no longer be an issue. Is that right @vjovanov ?

[1] https://github.com/oracle/graal/commit/5ce84f4f975128c3dc28d2e4d9b61bd0274c9b35

**Comment by thomaswue** [comment]
@galderz Does the mentioned commit fix your issue?

**Comment by galderz** [comment]
@thomaswue I've not tried yet, something else has come up. However, I hope I'll be able to try shortly.

**Comment by galderz** [comment]
Actually, I'm indirectly testing again with the latest graalvm code, so let's see if I can get as far as this particular test...

**Comment by galderz** [comment]
Some other errors are happening, so I've not been able to reach to test this again.

**Comment by galderz** [comment]
@thomaswue The error appears to be different now (see [here](https://github.com/quarkusio/quarkus/issues/7914#issuecomment-605817754)), but I don't yet know if the issue is still present until I resolved the existing issue now.

**Comment by galderz** [comment]
The error is gone after we added the missing dependency and updating graalvm master :)

**Comment by vjovanov** [comment]
Thanks for testing it out!
