### ISSUE TITLE
Make NIOFileSystem available 

### ISSUE THREAD

**Issue by oobles** [oracle/graal#2190]
**Feature request**

Please include the following information:

**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. E.g. I'm always frustrated when [...]

We wish to map a specific path to be available to graalvm.  We used something like:

Context.newBuilder().engine(engine).allowAllAccess(true).allowIO(true).allowHostAccess(access).**fileSystem(fileSystem)**.build();

Unfortunately, the only implementations of FileSystem are embedded inside the FileSystems class of truffle.  We copied and pasted the NIOFileSystem which provided the exactly implementation we needed, but it would be better if this could be made available.

**Describe the solution you'd like.**

Move NIOFileSystem and potentially other file system implementations into graalvm package to be available to developers that require it.,

**Describe who do you think will benefit the most.**
GraalVM users, GraalVM contributors, developers of libraries and frameworks which depend on GraalVM, or somebody else?

Anyone wanting to map a file system to graalvm.

**Describe alternatives you've considered.**

Only alternative is copy/paste or write our own which duplicates effort already done.

**Additional context.**
Add any other context about the feature request here.
For example, link to the relevant projects, documentation, standards.

**Express whether you'd like to help contributing this feature**
If you'd like to contribute, please read the [contribution guide](https://www.graalvm.org/community/contributors/).

**Comment by tzezula** [comment]
Is it enough for your use case to decorate the `NIOFileSystem` by and delegate to it from your implementation? Adding a factory method for `NIOFileSystem` will be much nicer API than making the `NIOFileSystem` public.

**Comment by oobles** [comment]
Yes, a factory would be fine.  My specific use case requires NIOFileSystem, however, the other implementations in FileSystems I'm sure would be useful for others in future. In addition, there's the MemoryFileSystem used for testing which I could see being useful.  

In summary, making the factory APIs in FileSystems available would be a great start. :)

**Comment by warrenc5** [comment]
I want to build a context with a custom filesystem to load file resources from the network/classpath. 
I noticed it was an interface so I created a java.lang.reflect.Proxy for FileSystem to intercept a few methods and went looking for the Contexts "default" FileSystem to delegate to.  
But I saw NIOFileSystem in Engine and it's Impl is a heavily decorated nio.spi.FileSystemProvider.
And the engine is package protected and private static.  
I will make a local source copy for now.   Please consider making it accessible from the Engine or even the Context so I can use it like this.  **Thank Graal.**

**Comment by boris-spas** [comment]
Tracking internally as Issue GR-23076.

**Comment by warrenc5** [comment]
FYI for a greater detail how I work around the existing design to intercept calls to the file system.

[](https://github.com/oracle/graal/issues/2147)

**Comment by tzezula** [comment]
The `FileSystem.newDefaultFileSystem` was added, commit https://github.com/oracle/graal/commit/36db4c027d1807ebebde7d8001937910a339e003
