### ISSUE TITLE
Where is the README?

### ISSUE THREAD

**Issue by rahmanusta** [oracle/graal#220]
I don't see any README file for the Graal project. Where can I find it?

Thanks.

**Comment by smarr** [comment]
Quick answer: https://github.com/graalvm/graal/tree/master/compiler#readme

But I agree, the Graal project could really should use at least a 'Hello' readme.
Looks not very inviting.

**Comment by koctbik** [comment]
Depends on what you need, maybe compiler apart
https://github.com/graalvm/graal-core/blob/master/README.md
Or tool for creating languages
https://github.com/graalvm/graal/blob/master/docs/Publications.md
Or maybe even a presentation of them both in bundle
https://www.slideshare.net/ThomasWuerthinger/2015-cgo-graal

I hope autors would write something brilliant, they don't lack descriptions at the moments.
