### ISSUE TITLE
Requirements for building native images are not fulfilled

### ISSUE THREAD

**Issue by cup** [oracle/graal#2202]
First I get these:

- <https://github.com/graalvm/openjdk8-jvmci-builder/releases/download/jvmci-20.0-b02/openjdk-8u242-jvmci-20.0-b02-windows-amd64.tar.gz>
- <https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-20.0.0/native-image-installable-svm-java8-windows-amd64-20.0.0.jar>

Then run:

~~~
$ cat HelloWorld.java
public class HelloWorld {
  public static void main(String[] args) {
    System.out.println("Hello, World!");
  }
}

$ openjdk1.8.0_242-jvmci-20.0-b02/bin/javac HelloWorld.java

$ JAVA_HOME=openjdk1.8.0_242-jvmci-20.0-b02 \
> native-image-installable-svm-java8-windows-amd64-20.0.0/bin\
> /native-image.cmd HelloWorld
Error: Requirements for building native images are not fulfilled [cause: Unable
to use jar-files from directory C:\native-image-installable-svm-java8-windows-
amd64-20.0.0\jre\lib\svm\builder]
~~~

<https://www.graalvm.org/docs/getting-started#native-images>

**Comment by olpaw** [comment]
You are doing it wrong ;-)
1. Download: https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-20.0.0/graalvm-ce-java8-windows-amd64-20.0.0.zip
2. Unzip `graalvm-ce-java8-windows-amd64-20.0.0.zip` (it will create `graalvm-ce-java8-20.0.0`).
3. Run `graalvm-ce-java8-20.0.0\bin\gu install native-image` (this will download and install https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-20.0.0/native-image-installable-svm-java8-windows-amd64-20.0.0.jar into `graalvm-ce-java8-20.0.0` for you).

Now you may build your image with `graalvm-ce-java8-20.0.0\bin\native-image HelloWorld`

**Comment by cup** [comment]
@olpaw is it possible to install `native-image` manually, similar to what I
tried?

**Comment by olpaw** [comment]
@cup yes.
```
graalvm-ce-java8-20.0.0\bin\gu install --file native-image-installable-svm-java8-windows-amd64-20.0.0.jar
```
should also work. (for more info see `gu --help`)

**Comment by cup** [comment]
@olpaw no I mean manually, as in install `native-image` without using `gu`.

**Comment by olpaw** [comment]
You could extract the contents of the installable and manually merge its contents into the `graalvm-ce-java8-20.0.0` subdir. But why would you do that if you have a tool that does it all for you ... boredom ;-)

**Comment by cup** [comment]
I decided to take your original advice here:

~~~
bin/gu.cmd install native-image
~~~

thank you!
