### ISSUE TITLE
Native Image Agent Causes Asynchronous Based Minecraft Server to Slow To A Crawl On World Loading

### ISSUE THREAD

**Issue by alexis-evelyn** [oracle/graal#2209]

**Comment by pczmr8v5n454iycf** [comment]
I can reproduce it. but...What's the meaning of this? PaperMC and its plugins are full of dynamic class loading and ASM, so it cannot be compiled into nativeimage

**Comment by pczmr8v5n454iycf** [comment]
It has another issue with papermc and some plugins, that is many reflection operations are not traced

**Comment by Iltotore** [comment]
I didn't have problems with a native image of Paper:
- It successfully loads plugins
- I didn't find any severe bug
- I thought it will take less memory than the JVM but the used native image is a fallback one. Howerver, it took __very less__ CPU than the original JAR.

Try checking [This page about Spigot/Paper and native image](https://www.spigotmc.org/threads/compile-spigot-into-a-native-executable-using-graals-native-image.418927/)

**Comment by alexis-evelyn** [comment]
> I didn't have problems with a native image of Paper:
> 
> * It successfully loads plugins
> * I didn't find any severe bug
> * I thought it will take less memory than the JVM but the used native image is a fallback one. Howerver, it took **very less** CPU than the original JAR.
> 
> Try checking [This page about Spigot/Paper and native image](https://www.spigotmc.org/threads/compile-spigot-into-a-native-executable-using-graals-native-image.418927/)

Using this [build of Graal](https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-20.0.0/graalvm-ce-java11-linux-amd64-20.0.0.tar.gz) with Native-Image downloaded via `gu install native-image`, I was able to replicate producing the fallback image of patched-1.15.2.jar. While that isn't a full conversion, but it is a lot farther than I was anticipating ever getting. I know only use around 800 mb or ram whereas I used to use 2.3 thousand mb. Also, the cpu cycle is far faster than the full java counterpart, even compared to running the server under Graal's Java. Using CE 19.3.1 fails to build the fallback image, however 20.0.0 works just fine.

I just ran `native-image -jar cache/patched-1.15.2.jar`. Moving the native build's output seems to break it, but it's not that hard to build the native build into the server's directory. Thanks for the link @Iltotore

**Comment by pczmr8v5n454iycf** [comment]
@Iltotore I mean non-fallback nativeimage.

**Comment by peter-hofer** [comment]
@alexis-evelyn thanks, I'll look into it. The `native-image-agent` is not intended for production use and relies on tooling and debugging features which can significantly slow down an application, but it should be usable to generate a configuration for a program's run in reasonable time.

@Iltotore A fallback image is essentially a launcher for the full JVM and should not be too different from launching the JVM directly. The difference might come from other factors, such comparing the JVM/JDK that is bundled with GraalVM to a different one that you have tested with before.
