### ISSUE TITLE
com.oracle.svm.hosted.substitute.DeletedElementException: Unsupported method creating native-image with Micronaut and Tomcat

### ISSUE THREAD

**Issue by ilopmar** [oracle/graal#2217]
**Describe GraalVM and your environment :**
 - GraalVM version or commit id if built from source: **20.0.0** and master branch **(`5a3e32467ad5f3e2d1bbc7f8e81986c97960bad1`)**
 - CE or EE: **CE**
 - Build Time or run time failure: **build time**
 - JDK version: **JDK8**
 - Native compiler information:
```
$ gcc --version
gcc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPO
```
 - Native linker information:
```
collect2 version 7.4.0
/usr/bin/ld -plugin /usr/lib/gcc/x86_64-linux-gnu/7/liblto_plugin.so -plugin-opt=/usr/lib/gcc/x86_64-linux-gnu/7/lto-wrapper -plugin-opt=-fresolution=/tmp/ccWzqz9c.res -plugin-opt=-pass-through=-lgcc -plugin-opt=-pass-through=-lgcc_s -plugin-opt=-pass-through=-lc -plugin-opt=-pass-through=-lgcc -plugin-opt=-pass-through=-lgcc_s --sysroot=/ --build-id --eh-frame-hdr -m elf_x86_64 --hash-style=gnu --as-needed -dynamic-linker /lib64/ld-linux-x86-64.so.2 -pie -z now -z relro /usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/Scrt1.o /usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/crti.o /usr/lib/gcc/x86_64-linux-gnu/7/crtbeginS.o -L/usr/lib/gcc/x86_64-linux-gnu/7 -L/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu -L/usr/lib/gcc/x86_64-linux-gnu/7/../../../../lib -L/lib/x86_64-linux-gnu -L/lib/../lib -L/usr/lib/x86_64-linux-gnu -L/usr/lib/../lib -L/usr/lib/gcc/x86_64-linux-gnu/7/../../.. --version -lgcc --push-state --as-needed -lgcc_s --pop-state -lc -lgcc --push-state --as-needed -lgcc_s --pop-state /usr/lib/gcc/x86_64-linux-gnu/7/crtendS.o /usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/crtn.o
GNU ld (GNU Binutils for Ubuntu) 2.30
Copyright (C) 2018 Free Software Foundation, Inc.
This program is free software; you may redistribute it under the terms of
the GNU General Public License version 3 or (at your option) a later version.
This program has absolutely no warranty.

```
 - OS and OS Version: **Linux Mint 19.3. Kernel 5.3.0-40-generic**
 - Architecture: **AMD64**
 - The output of `java -Xinternalversion`: 
```
OpenJDK 64-Bit Server VM GraalVM CE 20.0.0 (25.242-b06-jvmci-20.0-b02) for linux-amd64 JRE (8u242), built on Jan 20 2020 20:45:17 by "buildslave" with gcc 7.3.0
```

**Have you verified this issue still happens when using the latest snapshot?**
Yes, I also tried it with GraalVM 20.1.0-dev built from master branch.

**Describe the issue**
When building a native-image using GraalVM 20.0.0 (or master branch) with Micronaut and Tomcat the native image generation fails with the error:
```
[mn-servlet-tomcat-graal:2310]    classlist:   9,670.26 ms,  1.76 GB
[mn-servlet-tomcat-graal:2310]        (cap):     919.79 ms,  2.42 GB
The URL protocol jar is not tested and might not work as expected.
Supported URL protocols enabled by default: file,resource. Supported URL protocols available on demand: http,https.
The URL protocol jrt is not tested and might not work as expected.
Supported URL protocols enabled by default: file,resource. Supported URL protocols available on demand: http,https.
Registering the jrt URL protocol failed. It will not be available at runtime.

[mn-servlet-tomcat-graal:2310]        setup:   4,039.98 ms,  2.42 GB
Warning: class initialization of class io.micronaut.http.bind.binders.ContinuationArgumentBinder failed with exception java.lang.NoClassDefFoundError: kotlin/TypeCastException. This class will be initialized at run time because option --allow-incomplete-classpath is used for image building. Use the option --initialize-at-run-time=io.micronaut.http.bind.binders.ContinuationArgumentBinder to explicitly request delayed initialization of this class.
[mn-servlet-tomcat-graal:2310]   (typeflow):  50,094.43 ms,  4.74 GB
[mn-servlet-tomcat-graal:2310]    (objects):  31,650.17 ms,  4.74 GB
[mn-servlet-tomcat-graal:2310]   (features):   3,883.02 ms,  4.74 GB
[mn-servlet-tomcat-graal:2310]     analysis:  91,632.08 ms,  4.74 GB
Error: com.oracle.svm.hosted.substitute.DeletedElementException: Unsupported method sun.misc.URLClassPath.getLookupCacheForClassLoader(ClassLoader, String) is reachable
To diagnose the issue, you can add the option --report-unsupported-elements-at-runtime. The unsupported element is then reported at run time when it is accessed the first time.
Detailed message:
Trace: 
	at parsing sun.misc.URLClassPath.getLookupCache(URLClassPath.java:410)
Call path from entry point to sun.misc.URLClassPath.getLookupCache(String): 
	at sun.misc.URLClassPath.getLookupCache(URLClassPath.java:406)
	at sun.misc.URLClassPath.findResource(URLClassPath.java:223)
	at java.net.URLClassLoader$2.run(URLClassLoader.java:572)
	at java.net.URLClassLoader$2.run(URLClassLoader.java:570)
	at com.oracle.svm.core.jdk.Target_java_security_AccessController.doPrivileged(SecuritySubstitutions.java:99)
	at sun.security.ssl.SSLSocketImpl$NotifyHandshakeThread.run(SSLSocketImpl.java:2688)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:517)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:193)
	at com.oracle.svm.core.code.IsolateEnterStub.PosixJavaThreads_pthreadStartRoutine_e1f4a8c0039f8337338252cd8734f63a79b5e3df(generated:0)

Error: Use -H:+ReportExceptionStackTraces to print stacktrace of underlying exception
Error: Image build request failed with exit status 1
com.oracle.svm.driver.NativeImage$NativeImageError: Image build request failed with exit status 1
	at com.oracle.svm.driver.NativeImage.showError(NativeImage.java:1527)
	at com.oracle.svm.driver.NativeImage.build(NativeImage.java:1289)
	at com.oracle.svm.driver.NativeImage.performBuild(NativeImage.java:1250)
	at com.oracle.svm.driver.NativeImage.main(NativeImage.java:1209)


```

**Everything works and there is no error with GraalVM 19.3.1.**

If I add the flag `--report-unsupported-elements-at-runtime` as suggested then I'm able to build the image but as we have discussed in another issues (https://github.com/oracle/graal/issues/1726) the GraalVM teams discourage the usage of that flag.
Also, the fact that it works with 19.3.1 but fails now with 20.0.0 and 20.1.0-dev makes me think that maybe it's a regression on your side.

**Describe the full native-image command**
<details><summary>Capture full native-image command by running with the `--verbose` flag e.g.:</summary>

```
```
Executing [
/home/ivan/workspaces/misc/graal/graal/sdk/mxbuild/linux-amd64/GRAALVM_UNKNOWN_JAVA8/graalvm-unknown-java8-20.1.0-dev/jre/bin/java \
-XX:+UseParallelGC \
-XX:+UnlockExperimentalVMOptions \
-XX:+EnableJVMCI \
-Dtruffle.TrustAllTruffleRuntimeProviders=true \
-Dtruffle.TruffleRuntime=com.oracle.truffle.api.impl.DefaultTruffleRuntime \
-Dgraalvm.ForcePolyglotInvalid=true \
-Dgraalvm.locatorDisabled=true \
-d64 \
-XX:-UseJVMCIClassLoader \
-XX:-UseJVMCICompiler \
-Xss10m \
-Xms1g \
-Xmx14g \
-Duser.country=US \
-Duser.language=en \
-Djava.awt.headless=true \
-Dorg.graalvm.version=20.1.0-dev \
-Dorg.graalvm.config= \
-Dcom.oracle.graalvm.isaot=true \
-Djava.system.class.loader=com.oracle.svm.hosted.NativeImageSystemClassLoader \
-Xshare:off \
-Djvmci.class.path.append=/home/ivan/workspaces/misc/graal/graal/sdk/mxbuild/linux-amd64/GRAALVM_UNKNOWN_JAVA8/graalvm-unknown-java8-20.1.0-dev/jre/lib/jvmci/graal.jar \
-javaagent:/home/ivan/workspaces/misc/graal/graal/sdk/mxbuild/linux-amd64/GRAALVM_UNKNOWN_JAVA8/graalvm-unknown-java8-20.1.0-dev/jre/lib/svm/builder/svm.jar \
-Djdk.internal.lambda.disableEagerInitialization=true \
-Djdk.internal.lambda.eagerlyInitialize=false \
-Djava.lang.invoke.InnerClassLambdaMetafactory.initializeLambdas=false \
-Xbootclasspath/a:/home/ivan/workspaces/misc/graal/graal/sdk/mxbuild/linux-amd64/GRAALVM_UNKNOWN_JAVA8/graalvm-unknown-java8-20.1.0-dev/jre/lib/boot/graal-sdk.jar \
-cp \
/home/ivan/workspaces/misc/graal/graal/sdk/mxbuild/linux-amd64/GRAALVM_UNKNOWN_JAVA8/graalvm-unknown-java8-20.1.0-dev/jre/lib/svm/builder/svm.jar:/home/ivan/workspaces/misc/graal/graal/sdk/mxbuild/linux-amd64/GRAALVM_UNKNOWN_JAVA8/graalvm-unknown-java8-20.1.0-dev/jre/lib/svm/builder/objectfile.jar:/home/ivan/workspaces/misc/graal/graal/sdk/mxbuild/linux-amd64/GRAALVM_UNKNOWN_JAVA8/graalvm-unknown-java8-20.1.0-dev/jre/lib/svm/builder/pointsto.jar:/home/ivan/workspaces/misc/graal/graal/sdk/mxbuild/linux-amd64/GRAALVM_UNKNOWN_JAVA8/graalvm-unknown-java8-20.1.0-dev/jre/lib/svm/builder/svm-llvm.jar:/home/ivan/workspaces/misc/graal/graal/sdk/mxbuild/linux-amd64/GRAALVM_UNKNOWN_JAVA8/graalvm-unknown-java8-20.1.0-dev/jre/lib/svm/builder/llvm-platform-specific-shadowed.jar:/home/ivan/workspaces/misc/graal/graal/sdk/mxbuild/linux-amd64/GRAALVM_UNKNOWN_JAVA8/graalvm-unknown-java8-20.1.0-dev/jre/lib/svm/builder/graal-llvm.jar:/home/ivan/workspaces/misc/graal/graal/sdk/mxbuild/linux-amd64/GRAALVM_UNKNOWN_JAVA8/graalvm-unknown-java8-20.1.0-dev/jre/lib/svm/builder/javacpp-shadowed.jar:/home/ivan/workspaces/misc/graal/graal/sdk/mxbuild/linux-amd64/GRAALVM_UNKNOWN_JAVA8/graalvm-unknown-java8-20.1.0-dev/jre/lib/svm/builder/llvm-wrapper-shadowed.jar:/home/ivan/workspaces/misc/graal/graal/sdk/mxbuild/linux-amd64/GRAALVM_UNKNOWN_JAVA8/graalvm-unknown-java8-20.1.0-dev/jre/lib/jvmci/graal-truffle-jfr-impl.jar:/home/ivan/workspaces/misc/graal/graal/sdk/mxbuild/linux-amd64/GRAALVM_UNKNOWN_JAVA8/graalvm-unknown-java8-20.1.0-dev/jre/lib/jvmci/jvmci-hotspot.jar:/home/ivan/workspaces/misc/graal/graal/sdk/mxbuild/linux-amd64/GRAALVM_UNKNOWN_JAVA8/graalvm-unknown-java8-20.1.0-dev/jre/lib/jvmci/graal-management.jar:/home/ivan/workspaces/misc/graal/graal/sdk/mxbuild/linux-amd64/GRAALVM_UNKNOWN_JAVA8/graalvm-unknown-java8-20.1.0-dev/jre/lib/jvmci/jvmci-api.jar:/home/ivan/workspaces/misc/graal/graal/sdk/mxbuild/linux-amd64/GRAALVM_UNKNOWN_JAVA8/graalvm-unknown-java8-20.1.0-dev/jre/lib/jvmci/graal.jar:/home/ivan/workspaces/misc/graal/graal/sdk/mxbuild/linux-amd64/GRAALVM_UNKNOWN_JAVA8/graalvm-unknown-java8-20.1.0-dev/jre/lib/resources.jar \
com.oracle.svm.hosted.NativeImageGeneratorRunner \
-watchpid \
2273 \
-imagecp \
/home/ivan/workspaces/misc/graal/graal/sdk/mxbuild/linux-amd64/GRAALVM_UNKNOWN_JAVA8/graalvm-unknown-java8-20.1.0-dev/jre/lib/boot/graal-sdk.jar:/home/ivan/workspaces/misc/graal/graal/sdk/mxbuild/linux-amd64/GRAALVM_UNKNOWN_JAVA8/graalvm-unknown-java8-20.1.0-dev/jre/lib/svm/builder/svm.jar:/home/ivan/workspaces/misc/graal/graal/sdk/mxbuild/linux-amd64/GRAALVM_UNKNOWN_JAVA8/graalvm-unknown-java8-20.1.0-dev/jre/lib/svm/builder/objectfile.jar:/home/ivan/workspaces/misc/graal/graal/sdk/mxbuild/linux-amd64/GRAALVM_UNKNOWN_JAVA8/graalvm-unknown-java8-20.1.0-dev/jre/lib/svm/builder/pointsto.jar:/home/ivan/workspaces/misc/graal/graal/sdk/mxbuild/linux-amd64/GRAALVM_UNKNOWN_JAVA8/graalvm-unknown-java8-20.1.0-dev/jre/lib/svm/builder/svm-llvm.jar:/home/ivan/workspaces/misc/graal/graal/sdk/mxbuild/linux-amd64/GRAALVM_UNKNOWN_JAVA8/graalvm-unknown-java8-20.1.0-dev/jre/lib/svm/builder/llvm-platform-specific-shadowed.jar:/home/ivan/workspaces/misc/graal/graal/sdk/mxbuild/linux-amd64/GRAALVM_UNKNOWN_JAVA8/graalvm-unknown-java8-20.1.0-dev/jre/lib/svm/builder/graal-llvm.jar:/home/ivan/workspaces/misc/graal/graal/sdk/mxbuild/linux-amd64/GRAALVM_UNKNOWN_JAVA8/graalvm-unknown-java8-20.1.0-dev/jre/lib/svm/builder/javacpp-shadowed.jar:/home/ivan/workspaces/misc/graal/graal/sdk/mxbuild/linux-amd64/GRAALVM_UNKNOWN_JAVA8/graalvm-unknown-java8-20.1.0-dev/jre/lib/svm/builder/llvm-wrapper-shadowed.jar:/home/ivan/workspaces/misc/graal/graal/sdk/mxbuild/linux-amd64/GRAALVM_UNKNOWN_JAVA8/graalvm-unknown-java8-20.1.0-dev/jre/lib/jvmci/graal-truffle-jfr-impl.jar:/home/ivan/workspaces/misc/graal/graal/sdk/mxbuild/linux-amd64/GRAALVM_UNKNOWN_JAVA8/graalvm-unknown-java8-20.1.0-dev/jre/lib/jvmci/jvmci-hotspot.jar:/home/ivan/workspaces/misc/graal/graal/sdk/mxbuild/linux-amd64/GRAALVM_UNKNOWN_JAVA8/graalvm-unknown-java8-20.1.0-dev/jre/lib/jvmci/graal-management.jar:/home/ivan/workspaces/misc/graal/graal/sdk/mxbuild/linux-amd64/GRAALVM_UNKNOWN_JAVA8/graalvm-unknown-java8-20.1.0-dev/jre/lib/jvmci/jvmci-api.jar:/home/ivan/workspaces/misc/graal/graal/sdk/mxbuild/linux-amd64/GRAALVM_UNKNOWN_JAVA8/graalvm-unknown-java8-20.1.0-dev/jre/lib/jvmci/graal.jar:/home/ivan/workspaces/misc/graal/graal/sdk/mxbuild/linux-amd64/GRAALVM_UNKNOWN_JAVA8/graalvm-unknown-java8-20.1.0-dev/jre/lib/resources.jar:/home/ivan/workspaces/misc/graal/graal/sdk/mxbuild/linux-amd64/GRAALVM_UNKNOWN_JAVA8/graalvm-unknown-java8-20.1.0-dev/jre/lib/svm/library-support.jar:/home/ivan/workspaces/micronaut-graal-tests/micronaut-servlet-graal/build/libs/micronaut-servlet-graal-0.1-all.jar \
-H:Path=/home/ivan/workspaces/micronaut-graal-tests/micronaut-servlet-graal \
-H:+StaticExecutable \
-H:FallbackThreshold=0 \
-H:ClassInitialization=io.netty.util.AbstractReferenceCounted:run_time \
-H:ClassInitialization=io.netty.buffer.PooledByteBufAllocator:run_time,io.netty.buffer.ByteBufAllocator:run_time,io.netty.buffer.ByteBufUtil:run_time,io.netty.buffer.AbstractReferenceCountedByteBuf:run_time \
-H:ReflectionConfigurationResources=META-INF/native-image/io.netty/transport/reflection-config.json \
-H:ClassInitialization=io.netty.handler.ssl.util.ThreadLocalInsecureRandom:run_time \
-H:ClassInitialization=io.netty:build_time \
-H:ClassInitialization=io.netty.handler.codec.http.HttpObjectEncoder:run_time,io.netty.handler.codec.http.websocketx.WebSocket00FrameEncoder:run_time,io.netty.handler.codec.http.websocketx.extensions.compression.DeflateDecoder:run_time \
-H:IncludeResources=META-INF/http/mime.types \
-H:ReflectionConfigurationResources=META-INF/native-image/javax/servlet/reflection-config.json \
-H:ClassInitialization=org.apache.catalina:build_time,org.apache.tomcat:build_time,org.apache.juli:build_time \
-H:ClassInitialization=org.apache.tomcat.util.net.openssl.OpenSSLEngine:run_time,org.apache.tomcat.jni:run_time \
-H:EnableURLProtocols=http,https,jar,jrt \
-H:+AllowIncompleteClasspath \
-H:EnableURLProtocols=http,https \
-H:ReflectionConfigurationResources=META-INF/native-image/io.micronaut/http/reflection-config.json \
'-H:ClassInitialization=com.sun.jndi.dns.DnsClient:run_time,io.netty.handler.ssl.ConscryptAlpnSslEngine:run_time,io.netty.handler.ssl.JettyNpnSslEngine:run_time,io.netty.handler.ssl.ReferenceCountedOpenSslEngine:run_time,io.netty.handler.ssl.JdkNpnApplicationProtocolNegotiator:run_time,io.netty.handler.ssl.ReferenceCountedOpenSslServerContext:run_time,io.netty.handler.ssl.ReferenceCountedOpenSslClientContext:run_time,io.netty.handler.ssl.util.BouncyCastleSelfSignedCertGenerator:run_time,io.netty.handler.ssl.ReferenceCountedOpenSslContext:run_time,io.micronaut.buffer.netty.NettyByteBufferFactory:run_time,io.netty.handler.ssl.JettyAlpnSslEngine$ClientEngine:run_time,io.netty.handler.ssl.JettyAlpnSslEngine$ServerEngine:run_time,io.netty.util.concurrent.GlobalEventExecutor:run_time,io.netty.util.concurrent.ImmediateEventExecutor:run_time,io.netty.util.concurrent.ScheduledFutureTask:run_time' \
-H:ReflectionConfigurationResources=META-INF/native-image/io.micronaut/http-netty/reflection-config.json \
-H:ClassInitialization=io.micronaut.reactive.reactor.ReactorInstrumentation:run_time \
-H:ClassInitialization=ch.qos.logback:build_time,com.fasterxml.jackson:build_time,io.micronaut:build_time,io.reactivex:build_time,org.reactivestreams:build_time,org.slf4j:build_time,org.yaml.snakeyaml:build_time,javax:build_time \
-H:ReflectionConfigurationResources=META-INF/native-image/io.micronaut/health/reflection-config.json \
-H:ReflectionConfigurationResources=META-INF/native-image/io.micronaut/http-server/reflection-config.json \
'-H:IncludeResources=logback.xml|application.yml|bootstrap.yml' \
-H:Name=mn-servlet-tomcat-graal \
-H:Class=micronaut.servlet.graal.Application \
-H:ReflectionConfigurationResources=META-INF/native-image/micronaut.servlet/graal/reflection-config.json \
-H:JNIConfigurationResources=META-INF/native-image/io.micronaut.servlet/micronaut-servlet-tomcat/jni-config.json \
-H:ReflectionConfigurationResources=META-INF/native-image/io.micronaut.servlet/micronaut-servlet-tomcat/reflect-config.json \
-H:ResourceConfigurationResources=META-INF/native-image/io.micronaut.servlet/micronaut-servlet-tomcat/resource-config.json \
-H:CLibraryPath=/home/ivan/workspaces/misc/graal/graal/sdk/mxbuild/linux-amd64/GRAALVM_UNKNOWN_JAVA8/graalvm-unknown-java8-20.1.0-dev/jre/lib/svm/clibraries/linux-amd64 \

]

```
```
</details>

**Code snippet or code repository that reproduces the issue**

**Steps to reproduce the issue**
Please include both build steps as well as run steps
1. `git clone https://github.com/micronaut-graal-tests/micronaut-servlet-graal`
2. `cd micronaut-servlet-graal`
3. `git checkout tomcat`
4. Use GraalVM 20.0.0 or latest from master
5. Edit file `src/main/resources/META-INF/native-image/micronaut.servlet.graal/micronaut-servlet-graal-application/native-image.properties` and remove the option `--report-unsupported-elements-at-runtime`
6.- Execute `./build-native-image.sh`

If you add `--report-unsupported-elements-at-runtime` back and execute `build-native-image.sh` again the native image will be created.

**Expected behavior**

I expect the native-image be created without the flag `--report-unsupported-elements-at-runtime` as it was with GraalVM 19.3.1

**Additional context**

In Tomcat documentation (https://tomcat.apache.org/tomcat-9.0-doc/graal.html#Building_the_native_image) they explictly mention that it's necessary to add the flag `-H:+ReportUnsupportedElementsAtRuntime`, although, as mentioned before, with GraalVM 19.3.1 it is working without it.

**Comment by mostafacs** [comment]
I have the same issue with quarkus project is any progress or work around for this issue

**Comment by FWiesner** [comment]
having this problem with an internal Oracle project as well. I my case it is just `jdk.internal.reflect.MethodAccessorGenerator` that causes the exception

**Comment by zakkak** [comment]
@mostafacs @jmaister this is probably because Quarkus is using the `--initialize-at-build-time` flag, please open an issue with more details at https://github.com/quarkusio/quarkus/issues if you are still facing this.
