### ISSUE TITLE
-XX:+PreserveFramePointer is broken since 20.0.0

### ISSUE THREAD

**Issue by christhalinger** [oracle/graal#2219]
**Describe GraalVM and your environment :**
 - GraalVM version or commit id if built from source: **20.0.0**
 - CE or EE: **CE**
 - JDK version: **JDK11**
 - OS and OS Version: **macOS**
 - Architecture: **amd64**
 - The output of `java -Xinternalversion`: 
```
$ ./graalvm-ce-java11-20.0.0/Contents/Home/bin/java -Xinternalversion
OpenJDK 64-Bit Server VM (11.0.6+9-jvmci-20.0-b02) for bsd-amd64 JRE (11.0.6+9-jvmci-20.0-b02), built on Jan 20 2020 14:32:51 by "graal1" with gcc 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.2)
```

**Have you verified this issue still happens when using the latest snapshot?**
You can find snapshot builds here: https://github.com/graalvm/graalvm-ce-dev-builds/releases

**Describe the issue**
At Twitter we enabled `PreserveFramePointer` by default for debugging purposes. This worked fine before but since:

https://github.com/oracle/graal/commit/151118a96f0

it crashes.

**Steps to reproduce the issue**

```
$ ./graalvm-ce-java11-20.0.0/Contents/Home/bin/java -jar dacapo-9.12-MR1-bach.jar avrora
===== DaCapo 9.12-MR1 avrora starting =====
===== DaCapo 9.12-MR1 avrora PASSED in 8194 msec =====
$ ./graalvm-ce-java11-20.0.0/Contents/Home/bin/java -XX:+PreserveFramePointer -jar dacapo-9.12-MR1-bach.jar avrora
===== DaCapo 9.12-MR1 avrora starting =====
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  Internal Error (compiledMethod.cpp:216), pid=70422, tid=37635
#  guarantee(pd != NULL) failed: scope must be present
#
# JRE version: OpenJDK Runtime Environment GraalVM CE 20.0.0 (11.0.6+9) (build 11.0.6+9-jvmci-20.0-b02)
# Java VM: OpenJDK 64-Bit Server VM GraalVM CE 20.0.0 (11.0.6+9-jvmci-20.0-b02, mixed mode, sharing, tiered, jvmci, jvmci compiler, compressed oops, g1 gc, bsd-amd64)
# No core dump will be written. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /Users/cthalinger/hs_err_pid70422.log
#
# If you would like to submit a bug report, please visit:
#   https://bugreport.java.com/bugreport/crash.jsp
#
Abort trap: 6
```

**Comment by tkrodriguez** [comment]
There's a problem with the offset used when patching the return address in the exception handler stub and we end up returning to the nmethod and rolling forward into the deopt handler. This fix is in progress.

**Comment by tkrodriguez** [comment]
This was fixed in https://github.com/oracle/graal/commit/cec31521c063dcb0bec9b211675f9e60635955ce and should appear in the next release.
