### ISSUE TITLE
MSI installer for GraalVM on Windows

### ISSUE THREAD

**Issue by johanjanssen** [oracle/graal#2226]
**Feature request**

Please include the following information:

**Is your feature request related to a problem? Please describe.**
I'm maintaining the Chocolatey (package manager for Windows) packages for GraalVM. 

Currently that means I scripted the steps to unzip, set the JAVA_Home and add Java to the PATH. For the uninstallation I had to do more or less the same but then to remove everything.

It would be easier (and less error prone) for me and other Windows users if you could provide an MSI installer. 

**Describe the solution you'd like.**
An MSI installer.

**Describe who do you think will benefit the most.**
All Windows users.

**Describe alternatives you've considered.**
The current ZIP solution is doable, but less convenient.

**Additional context.**
You might be able to use the elements AdoptOpenJDK produced to create MSI's of AdoptOpenJDK: https://github.com/AdoptOpenJDK/openjdk-installer/tree/master/wix

**Express whether you'd like to help contributing this feature**
Depends what you want me to do :)

**Comment by fernando-valdez** [comment]
Closing this ticket until there is a PR that contributes to this effort.
