### ISSUE TITLE
Graal Updater (gu)  "Error: The GraalVM directory ... is invalid"

### ISSUE THREAD

**Issue by agentgt** [oracle/graal#2231]
**Describe GraalVM and your environment :**
 - GraalVM version or commit id if built from source: **[20.0]**
 - CE or EE: **[CE]**
 - JDK version: **[JDK8]**
 - OS and OS Version: **macOS Mojave**
 - Architecture: **[amd64]**

Installed graalvm. Java and all the commands works fine.

However when I run any gu command other than help I get
```
$ gu info
Error: The GraalVM directory [ommited directory] is invalid
```
I tried turning on logging and debug but it fails to quickly for any logging.

**Comment by agentgt** [comment]
I figured out the issue.

In my bash profile I was originally doing something like:

```
GRAAL_HOME=/some/directory/graalvm-ce-java8-20.0.0
export GRAALVM_HOME=${GRAAL_HOME}/Contents/Home
export PATH=$GRAAL_HOME/Contents/Home/bin:$PATH
export JAVA_HOME=$GRAAL_HOME/Contents/Home
```

I was just using the GRAAL_HOME variable to help construct the correct path.

Than for whatever reason I changed it to export GRAAL_HOME

```
export GRAAL_HOME=/some/directory/graalvm-ce-java8-20.0.0
```

Apparently the gu tool uses the `GRAAL_HOME` environment variable.

I googled around and could not find any documentation on that environment variable.

Anyway once I stopped exporting the variable the tool worked as expected.

Feel free to close.

**Comment by MartinBalin** [comment]
GU will use $GRAALVM_HOME env. variable instead of GRAAL_HOME

**Comment by aucampia** [comment]
working with GraalVM Updater 20.2.0

I also get this error unless I set `GRAAL_HOME`:

```
20201115T200432 iwana@iwana-ub.zoic.eu.org:~/d.sws/conan-envs/default
$ env | grep GRAAL
GRAALVM_HOME=/home/iwana/.conan/data/graalvm-ce-prebuilt/20.2.0/aucampia/default/package/56f0443cd1e67a6394d0ba61f9aac996bafae6a9
GRAAL_HOME=/home/iwana/.conan/data/graalvm-ce-prebuilt/20.2.0/aucampia/default/package/56f0443cd1e67a6394d0ba61f9aac996bafae6a9
20201115T200437 iwana@iwana-ub.zoic.eu.org:~/d.sws/conan-envs/default
$ gu list
ComponentId              Version             Component name      Origin 
--------------------------------------------------------------------------------
js                       20.2.0              Graal.js            
graalvm                  20.2.0              GraalVM Core        
20201115T200439 iwana@iwana-ub.zoic.eu.org:~/d.sws/conan-envs/default
$ unset GRAAL_HOME
20201115T200442 iwana@iwana-ub.zoic.eu.org:~/d.sws/conan-envs/default
$ env | grep GRAAL
GRAALVM_HOME=/home/iwana/.conan/data/graalvm-ce-prebuilt/20.2.0/aucampia/default/package/56f0443cd1e67a6394d0ba61f9aac996bafae6a9
20201115T200444 iwana@iwana-ub.zoic.eu.org:~/d.sws/conan-envs/default
$ gu list
Error: The GraalVM directory /home/iwana/.conan/data/graalvm-ce-prebuilt/20.2.0/aucampia/default/package is invalid.
```

**Comment by MartinBalin** [comment]
I just tried and gu worsk without setting any environment property on my computer.
`~/graalvm-ce-java11-20.2.0/bin$ ./gu available`
running it like this returns list of all components. I don't have anything set on my machine no $GRAAL_HOME, $GRAALVM_HOME, no $JAVA_HOME.
Can you try it without these env. variables set?

**Comment by aucampia** [comment]
Okay I figured out why this was happening:

Clean extract from archive works well:

```
$ \rm -rf graalvm-ce-java11-20.2.0/
$ bsdtar -xf ~/.conan/data/graalvm-ce-prebuilt/20.2.0/aucampia/default/source/graalvm-ce-java11-linux-amd64-20.2.0.tar.gz 
$ ./graalvm-ce-java11-20.2.0/bin/gu --version
GraalVM Updater 20.2.0
```

However if bin/gu is not a symlink to `../lib/installer/bin/gu` but instead the actual file it does not work:

```
$ ls -ld ./graalvm-ce-java11-20.2.0/bin/gu
lrwxrwxrwx. 1 iwana iwana 23 Aug 16 10:31 ./graalvm-ce-java11-20.2.0/bin/gu -> ../lib/installer/bin/gu
$ \cp -v --remove-destination $(readlink -f ./graalvm-ce-java11-20.2.0/bin/gu) ./graalvm-ce-java11-20.2.0/bin/gu
removed './graalvm-ce-java11-20.2.0/bin/gu'
'/var/tmp/graalvm-ce-java11-20.2.0/lib/installer/bin/gu' -> './graalvm-ce-java11-20.2.0/bin/gu'
$ ls -ld ./graalvm-ce-java11-20.2.0/bin/gu
-rwxr-xr-x. 1 iwana iwana 27338772 Nov 18 23:19 ./graalvm-ce-java11-20.2.0/bin/gu
```

```
$ ./graalvm-ce-java11-20.2.0/bin/gu --version
Error: The GraalVM directory /var/tmp is invalid.
```

**Comment by MartinBalin** [comment]
Pardon me, why to replace symlink created in graalvm /bin folder with a file copied from `installer/bin/gu`? I miss the reason for this change, sorry.

**Comment by aucampia** [comment]
No good reason, I was installing it with conan and conan defaults to this behaviour. When instructing conan to copy symlinks this problem goes away. Hopefully the detail can help someone who has this problem in the future.

**Comment by MartinBalin** [comment]
OK, thank you for investigation and posting the root cause of your problem here.

**Comment by pei-wang** [comment]
> Okay I figured out under what circumstance this was happening.
> 
> Clean extract from archive works well:
> 
> ```
> $ \rm -rf graalvm-ce-java11-20.2.0/
> $ bsdtar -xf ~/.conan/data/graalvm-ce-prebuilt/20.2.0/aucampia/default/source/graalvm-ce-java11-linux-amd64-20.2.0.tar.gz 
> $ ./graalvm-ce-java11-20.2.0/bin/gu --version
> GraalVM Updater 20.2.0
> ```
> 
> However if `bin/gu` is not a symlink to `../lib/installer/bin/gu` but instead the actual file it does not work:
> 
> ```
> $ # Check that file is a symlink:
> $ ls -ld ./graalvm-ce-java11-20.2.0/bin/gu
> lrwxrwxrwx. 1 iwana iwana 23 Aug 16 10:31 ./graalvm-ce-java11-20.2.0/bin/gu -> ../lib/installer/bin/gu
> 
> $ # replace symlink with file it points to:
> $ \cp -v --remove-destination $(readlink -f ./graalvm-ce-java11-20.2.0/bin/gu) ./graalvm-ce-java11-20.2.0/bin/gu
> removed './graalvm-ce-java11-20.2.0/bin/gu'
> '/var/tmp/graalvm-ce-java11-20.2.0/lib/installer/bin/gu' -> './graalvm-ce-java11-20.2.0/bin/gu'
> 
> $ # no longer a symlink
> $ ls -ld ./graalvm-ce-java11-20.2.0/bin/gu
> -rwxr-xr-x. 1 iwana iwana 27338772 Nov 18 23:19 ./graalvm-ce-java11-20.2.0/bin/gu
> ```
> 
> ```
> $ ./graalvm-ce-java11-20.2.0/bin/gu --version
> Error: The GraalVM directory /var/tmp is invalid.
> ```
> 
> Unless you set GRAAL_HOME:
> 
> ```
> $ export GRAAL_HOME=$(readlink -f ./graalvm-ce-java11-20.2.0)
> $ ./graalvm-ce-java11-20.2.0/bin/gu --version
> GraalVM Updater 20.2.0
> ```

export GRAAL_HOME works for me.

**Comment by masx200** [comment]
I found the same problem if I installed graalvm into a directory with Chinese names.

**Comment by rubyFeedback** [comment]
I just ran into this issue. The issue tracker here gave me some help, but the error message
was mega-super-unhelpful. It did not indicate any problem with the env variable, for instance.
I also could not use "gu --help" - it just screams at me like a ravaging beaver on a quest for
glory. May I suggest to improve the error message, and to NOT make --help auto-fail? Whoever
came up with that current implementation clearly did not think this through. How should people
understand that env variables they may have set, say, two years ago, and then forgot about it,
cause this problem? Without this issue here I may still google like a madman ...

**Comment by rubyFeedback** [comment]
I also think --help should work at all times. Right now I need to google to find out all commandline options for "gu".
