### ISSUE TITLE
add a option to allow all unintentional initializing at build time

### ISSUE THREAD

**Issue by pczmr8v5n454iycf** [oracle/graal#2233]
**Describe the issue**
The complete initialize-at-build-time list is too long and sometimes not easy to write correctly

**Describe GraalVM and your environment:**
 - GraalVM version CE 20.0

**Comment by cstancu** [comment]
Class initialization has been significantly refactored. Please see the details in  https://github.com/oracle/graal/blob/master/substratevm/ClassInitialization.md.
