### ISSUE TITLE
Agent misses Class.getMethod() for inherited static methods

### ISSUE THREAD

**Issue by sbrannen** [oracle/graal#2237]
# Overview

There is a discrepancy in the reflection support for `java.lang.Class.getMethod()` when using the GraalVM native image agent and looking up inherited `static` methods.

Specifically, the agent generates proper entries in `reflect-config.json` for invocations of `java.lang.Class.getMethod()` if the method in question is an inherited instance method, but the agent does **not** generate proper entries in `reflect-config.json` if the method in question is an inherited `static` method.

If you consult my [detailed report](https://github.com/sbrannen/graalvm-playground/tree/master/reflection_inherited_static_method), you will see three separate test cases.

- **Inherited Instance Method**: the agent generates a proper entry in `reflect-config.json` for the inherited instance method.
- **Inherited Static Method**: the agent does not generate a proper entry in `reflect-config.json` for the inherited static method, and manual reflection configuration is required as a workaround. 
- **Inherited Static and Instance Methods**: if the code in question performs lookups for both instance and static methods in the same class, the agent generates proper entries in `reflect-config.json` for the inherited instance method and the inherited static method. No manual reflection configuration is required.

# Deliverables

The agent should treat lookups of inherited methods via `java.lang.Class.getMethod()` equivalent for instanced methods and static methods. In other words, users should not be required to include any manual reflection configuration for static methods looked up via
`java.lang.Class.getMethod()`.

# Real-world Use Case

In order to support automatic conversions from a given `sourceType` to a `targetType`, the Spring Framework invokes a static `valueOf(sourceType)`, `of(sourceType)`, or `from(sourceType)` method on the `targetType`, if such a method exists. `ZoneId.of` is one such method.

# Environment

- GraalVM version: CE 20.0
- JDK major version: 8
- OS: macOS 10.14.6
- Architecture: i386 / x86_64

**Comment by petermz** [comment]
Seems fixed! Works for me in version 21.0.0.2

**Comment by peter-hofer** [comment]
This should have been fixed in 1b42c79, see also #1788.
I believe that before, it only worked when the instance class was also overridden, in this case `ZoneRegion.getId`.
