### ISSUE TITLE
Class path resources have invalid last-modified timestamps

### ISSUE THREAD

**Issue by sbrannen** [oracle/graal#2253]
# Overview

Class path resources have invalid last-modified timestamps. They are in fact always `0` since the custom `URLConnection` for resources within a native image does not override `java.net.URLConnection.getHeaderField(String)`.

https://github.com/oracle/graal/blob/b98be8370e9e6e1fe888ba13e393630e7681c77e/substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jdk/Resources.java#L110-L141

# Example

```java
import java.net.URL;
import java.net.URLConnection;
import java.time.LocalDateTime;
import java.time.ZoneId;

import static java.time.Instant.ofEpochMilli;

public class LastModifiedClasspathResource {

	public static void main(String[] args) throws Exception {
		new LastModifiedClasspathResource().test();
	}

	void test() throws Exception {
		String name = LastModifiedClasspathResource.class.getName() + ".class";
		URL resource = getClass().getResource(name);
		if (resource == null) {
			System.err.println("FAILURE: could not find classpath resource " + name);
			return;
		}
		System.err.println("SUCCESS: found classpath resource " + name);

		URLConnection connection = resource.openConnection();

		int contentLength = connection.getContentLength();
		if (contentLength <= 0) {
			System.err.println("FAILURE: non-positive content-length " + contentLength);
		}
		else {
			System.err.println("SUCCESS: content-length " + contentLength);
		}

		long lastModified = connection.getLastModified();
		if (lastModified <= 0) {
			System.err.println("FAILURE: non-positive last-modified " + lastModified);
		}
		else {
			LocalDateTime date = LocalDateTime.ofInstant(ofEpochMilli(lastModified), ZoneId.systemDefault());
			System.err.format("SUCCESS: last-modified timestamp %d / date %s%n", lastModified, date);
		}
	}

}
```

Given the above `LastModifiedClasspathResource` test case, the output when using a standard JDK results in the following.

```diff
+SUCCESS: found classpath resource LastModifiedClasspathResource.class
+SUCCESS: content-length 469
+SUCCESS: last-modified timestamp 1584104196000 / date 2020-03-13T13:56:36
```

If you compile the test case into a native image, the output is the following.

```diff
-FAILURE: could not find classpath resource LastModifiedClasspathResource.class
```

If you execute the test case with the GraalVM native image agent, it generates the following in `resource-config.json`:

```json
{
  "resources":[
    {"pattern":"\\QLastModifiedClasspathResource.class\\E"}, 
    {"pattern":"\\QMETA-INF/services/jdk.vm.ci.hotspot.HotSpotJVMCIBackendFactory\\E"}, 
    {"pattern":"\\QMETA-INF/services/jdk.vm.ci.services.JVMCIServiceLocator\\E"}
  ],
  "bundles":[]
}
```

If you then build the native image with the configuration generated by the agent, the output is the following.

```diff
+SUCCESS: found classpath resource LastModifiedClasspathResource.class
+SUCCESS: content-length 469
-FAILURE: non-positive last-modified 0
```
The above **FAILURE** points out the bug within a native image.

`LastModifiedClasspathResource.class` is now available as a classpath resource, and the content length is properly supported (see #1683). However, the last-modified timestamp is not available.

See https://github.com/sbrannen/graalvm-playground/tree/master/last_modified_classpath_resource for full details.

# Proposal

Rework the implementation of `com.oracle.svm.core.jdk.Resources` and related classes so that the `last-modified` timestamp of the original class path resource is available in the native image.

# Related Issues

- #1683

# Environment

- GraalVM version: CE 20.0
- JDK major version: 8
- OS: macOS 10.14.6
- Architecture: i386 / x86_64

**Comment by sbrannen** [comment]
@jovanstevanovic, perhaps you'd be interested in looking into this issue at some point since it's related to your work on `resource:` support, although it's a _minor_ issue with (currently) low priority from my perspective.

**Comment by jovanstevanovic** [comment]
Not sure by hand what is cause, but anyways, If you have permission, feel free to re-assign it to me.

**Comment by sbrannen** [comment]
Hi, @jovanstevanovic.

I only have Author status, so I cannot assign issues.

**Comment by jovanstevanovic** [comment]
Internally tracked as GR-43643.

**Comment by jovanstevanovic** [comment]
The fix is on the master.
