### ISSUE TITLE
Doublekill: SEGFAULT during reporting about SEGFAULT

### ISSUE THREAD

**Issue by vektory79** [oracle/graal#2254]
**Describe the issue**
I continue to experiments with [PlantUML compilation](https://github.com/vektory79/plantuml-native-image). Some time ago I report issue #1716, that is not reproduced on GraalVM CE 20.0.0.

But now I meet a wery curiosus error. When plantuml running without parameters it should open Swing window, but SEGFAULT'ed. SVM trying to generate report, but crashed again. Report is uncompleted.

**Steps to reproduce the issue**
1. **git clone https://github.com/vektory79/plantuml-native-image.git**
2. **cd plantuml-native-image**
3. **mvn clean compile**
4. **zip -d ~/.m2/repository/org/graalvm/nativeimage/svm/20.0.0/svm-20.0.0.jar "com/oracle/svm/core/jdk/Target_java_awt_Toolkit.class" **
5. **zip -d ${JAVA_HOME}/jre/lib/svm/builder/svm.jar "com/oracle/svm/core/jdk/Target_java_awt_Toolkit.class" **
6. **mvn package**
7. **./target/plantuml**

**Describe GraalVM and your environment:**
 - GraalVM version: **OpenJDK 64-Bit Server VM GraalVM CE 20.0.0 (build 25.242-b06-jvmci-20.0-b02, mixed mode)**
 - JDK version: **openjdk version "1.8.0_242"**
 - OS: **Ubuntu 18.04.4 LTS**
 - Architecture: **AMD64**

**More details**
 - [Build log](https://gist.github.com/vektory79/659163caba7f99b5cd9e6eec1d98e4f9)
 - [Crash log](https://gist.github.com/vektory79/08f3571eeab01e0dec864b9f5b744628)

**Comment by wirthi** [comment]
Closing other ticket, was likely solved in the meantime.
