### ISSUE TITLE
Add an option to launch a native image without opening a console/terminal

### ISSUE THREAD

**Issue by mbarbeaux** [oracle/graal#2256]
**Feature request**

Please include the following information:

**Is your feature request related to a problem? Please describe.**
On Windows (maybe also on other systems, didn't check that), when creating a native image and then double-clicking the built executable, I couldn't find a way to not display a console/terminal (for example, when your native image opens a window/GUI with Swing/JavaFX/SWT).

The additionnal option should behave the same way the "javaw" command works on Windows : being able to start the program without opening a console/terminal if your program doesn't need it. 

**Describe the solution you'd like.**
An option while calling native-image ?

**Describe who do you think will benefit the most.**
GraalVM users that doesn't need a console/terminal to open each time they double-click their native-image program (programs with GUI, services in background, etc)

**Describe alternatives you've considered.**
None

**Additional context.**
Example SWT Hello world project : https://github.com/mbarbeaux/graalvm-swt-native-image/
Just set your JAVA_HOME to a GraalVM 20.0.0 java8 on Windows, and then do `mvnw.cmd -Pnative clean package` to build the native image, and double click the result. A console prompt opens and stays in background of the SWT window. If you close the console prompt, programs is stopped.

**Express whether you'd like to help contributing this feature**
If you'd like to contribute, please read the [contribution guide](https://www.graalvm.org/community/contributors/).

**Comment by Barteks2x** [comment]
This is the answer I got on slack, so leaving it here, for anyone else who runs into this issue

The compiled executable can be easily modified with a [tool that comes with windows SDK](https://docs.microsoft.com/en-us/cpp/build/reference/subsystem?view=vs-2019):
```
EDITBIN /SUBSYSTEM:WINDOWS executable.exe
```

**Comment by ITSweets** [comment]
However, after removing the console window with this command, the process remains resident after the program is closed

**Comment by ITSweets** [comment]
@Barteks2x However, after removing the console window with this command, the process remains resident after the program is closed

**Comment by apocalyptech** [comment]
> @Barteks2x However, after removing the console window with this command, the process remains resident after the program is closed

Hello!  I'm wondering what you'd used to find that the process remains resident after close, btw.  I admit that Windows isn't my usual OS, so I'm less adept at digging into things like this, but at least from Task Manager, it looks to me like my app with the `EDITBIN /SUBSYSTEM:WINDOWS foo.exe` treatment still closes out properly.  I don't quite trust my Windows skills enough to be able to say it for sure.  (Perhaps it's something that might depend on the specifics of what the app's doing?)

**Comment by petermz** [comment]
The Microsoft linker also accepts the `/SUBSYSTEM:WINDOWS` option. However the linker expects the entry symbol to be called `WinMain` in this mode. So one needs to use something like
```
native-image -H:NativeLinkerOption=/SUBSYSTEM:WINDOWS -H:NativeLinkerOption=/ENTRY:mainCRTStartup ...
```
With these two flags, the resulting executable runs without terminal window.

**Comment by apocalyptech** [comment]
> With these two flags, the resulting executable runs without terminal window.

Oh nice, thanks for the tip!  Can save my build scripts one extra step, then.  :)

**Comment by wirthi** [comment]
question seems to be answered above, closing this ticket.

**Comment by tkslaw** [comment]
@wirthi I don't think this issue should have been closed. At best, petermz's solution is a workaround for the missing feature. There should be a simple command line flag for this. Like the *opposite* of `--win-console` from the `jpackage` tool.

**Comment by thibaultmeyer** [comment]
Any news about this feature ? with Quarkus FX, it could be nice too dont show terminal when run a graphical application.

@tkslaw  @wirthi  @apocalyptech  @petermz  @ITSweets   @Niko-sk2x @mbarbeaux
