### ISSUE TITLE
Error in compilation when crosscompiling using LLVM

### ISSUE THREAD

**Issue by johanvos** [oracle/graal#2259]
**Describe the issue**

When using the LLVM backend, with cached CAP files (and no CCompiler) VMFeature fails with this error:

Error: ImageSingletons do not contain key com.oracle.svm.hosted.c.codegen.CCompilerInvoker
com.oracle.svm.core.util.UserError$UserException: ImageSingletons do not contain key com.oracle.svm.hosted.c.codegen.CCompilerInvoker

**Comment by loicottet** [comment]
Fixed by [6f7e0e3e](https://github.com/oracle/graal/commit/6f7e0e3eab80ff613081d3f50fb5274f2e1cd551)
