### ISSUE TITLE
[Native Image] Non-heap memory of DirectByteBuffer in SubstrateVM caused to free only by GC

### ISSUE THREAD

**Issue by Konstantin773** [oracle/graal#2267]
In common JVM native memory freed up regardless of the amount used heap. Perhaps a different thread checks references to DirectByteBuffers in "Cleaner" object pool and clean non-heap memory early
In native image APPCRASH happens( PhantomReference problem

Example:
`for(int i = 0;i<100000;i++) {
	ByteBuffer.allocateDirect(128*1024*1024);
}`

Are there any solutions?

**Comment by sleipnir** [comment]
Hi @Konstantin773  Why was this closed? Was it a bug or was it not? I would like to know
