### ISSUE TITLE
BufferOverflowException 

### ISSUE THREAD

**Issue by kangzq0530** [oracle/graal#2268]
I've found a native image bug for Windows version. 
The bug is in  [PECoffSymtabStruct](https://github.com/oracle/graal/blob/bc8b8424f1b45ec97912c7409d9f9c8d88ec3cc2/substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/pecoff/PECoffSymtabStruct.java)
[Line87](https://github.com/oracle/graal/blob/bc8b8424f1b45ec97912c7409d9f9c8d88ec3cc2/substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/pecoff/PECoffSymtabStruct.java#L87) used String.getBytes() and cached it's length for allocate memory.
` int nameSize = name.getBytes().length;`
But [Line139](https://github.com/oracle/graal/blob/bc8b8424f1b45ec97912c7409d9f9c8d88ec3cc2/substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/pecoff/PECoffSymtabStruct.java#L139) actually write String.getBytes(StandardCharset.UTF_8) to the buffer.
`byte[] strs = strTabContent.toString().getBytes(StandardCharsets.UTF_8);`

This can cause a BufferOverflowException when native image building (See #2134 ). If the default charset is GBK or other Chinese language encoding, for a Chinese characters, `String.getBytes().length != String.getBytes(StandardCharset.UTF_8).length`. Under GBK, every Chinese character is encoded to 2 bytes, but under UTF_8 it is encoded to 3 bytes. So the allocated buffer's length is not enough and a BufferOverflowException will throw.

For current version, change the default charset by set -Dfile.encoding=UTF8 when building image can avoid this bug, But I hope this can be fix in next release.

**Comment by bobvandette** [comment]
Thank you for determining the root cause of this issue.  Symbols are stored as UTF_8 in PE Coff files so yes, the name.getBytes().length should have been name.getBytes(StandardCharset.UTF_8).  I will submit a PR to fix this.
