### ISSUE TITLE
[LLVM] AArch64 current failures

### ISSUE THREAD

**Issue by a74nh** [oracle/graal#2276]
These are all the failures on AArch64 from running
`mx gate --tags "build,sulongBasic,sulongLL,nwcc,llvm,toolchain"`

I plan on blacklisting all of the failures. Everything was run on Ubuntu 18.04.3. As far as I understand it, these are all the tests that we should care about for AArch64.

I've categorised them into groups. Each group should hopefully be a single piece of work. Formatting of the lists changes throughout, but it should hopefully all be obvious.

**FP128 (double) support missing**
  test[c/lfplayout]: FAILED
  test[c/stdlib/math/fmodl]: FAILED
  test[c/stdlib/math/sqrt]: FAILED
  test[c/longdouble/longdouble-add]: FAILED
  test[c/longdouble/longdouble-sub]: FAILED
  test[c/longdouble/add]: FAILED
  test[c/longdouble/longdouble-mul]: FAILED
  test[c/longdouble/longdouble-div]: FAILED
  test[c/builtin_gcc/__builtin_isfinite]: FAILED
  test[c/builtin_gcc/__builtin_fpclassify]: FAILED
  test[c/builtin_gcc/__builtin_signbit]: FAILED
  test[c/builtin_gcc/__builtin_isnan]: FAILED
  test[c/builtin_gcc/__builtin_copysign]: FAILED
  test[c/builtin_gcc/__builtin_fabsl]: FAILED
  test[c/builtin_gcc/__builtin_isinf]: FAILED
  test[c/builtin_gcc/__builtin_signbitl]: FAILED

**Shift output differences**
test[gen/shl_3xi8]: FAILED
test[gen/shl_2xi8]: FAILED
test[gen/ashr_4xi8]: FAILED
test[gen/lshr_3xi8]: FAILED
test[gen/lshr_2xi8]: FAILED
test[gen/lshr_4xi8]: FAILED
test[gen/ashr_3xi8]: FAILED
test[gen/shl_4xi8]: FAILED

**JVM segfault: Using Var-args**
tests/com.oracle.truffle.llvm.tests.libc.native/libc/vfprintf/vfprintf.c tests/com.oracle.truffle.llvm.tests.libc.native/libc/vprintf/vprintf.c tests/com.oracle.truffle.llvm.tests.sulong.native/c/varargs/var80bit.c tests/com.oracle.truffle.llvm.tests.sulong.native/c/varargs/varFloatVec.c tests/com.oracle.truffle.llvm.tests.sulong.native/c/varargs/varFunctionPointer.c tests/com.oracle.truffle.llvm.tests.sulong.native/c/varargs/varSmallStruct.c tests/com.oracle.truffle.llvm.tests.sulong.native/c/varargs/varStructBeforePrimitive.c tests/com.oracle.truffle.llvm.tests.sulong.native/c/varargs/varStructBeforePrimitiveAMD64Explicite.c tests/com.oracle.truffle.llvm.tests.sulong.native/c/varargs/varStructDouble.c tests/com.oracle.truffle.llvm.tests.sulong.native/c/varargs/varStructDoubleAMD64Explicite.c tests/com.oracle.truffle.llvm.tests.sulong.native/c/varargs/varStructLong.c tests/com.oracle.truffle.llvm.tests.sulong.native/c/varargs/varStructLongAMD64Explicite.c tests/com.oracle.truffle.llvm.tests.sulong.native/c/varargs/varStructModify.c tests/com.oracle.truffle.llvm.tests.sulong.native/c/varargs/varStructModifyPtr.c tests/com.oracle.truffle.llvm.tests.sulong.native/c/varargs/varStructPtr.c tests/com.oracle.truffle.llvm.tests.sulong.native/c/varargs/varStructStackOnly.c tests/com.oracle.truffle.llvm.tests.sulong.native/c/varargs/varStructStackOnlyAMD64Explicite.c
tests/com.oracle.truffle.llvm.tests.sulong.native/c/builtin_gcc/__builtin_va_list.c
"test-suite-3.2.src/SingleSource/Regression/C/PR640.c",
"test-suite-3.2.src/SingleSource/UnitTests/2003-05-07-VarArgs.c",
"test-suite-3.2.src/SingleSource/UnitTests/2003-07-09-SignedArgs.c",
"test-suite-3.2.src/SingleSource/UnitTests/2003-08-11-VaListArg.c",
"test-suite-3.2.src/SingleSource/UnitTests/2007-03-02-VaCopy.c",
"test-suite-3.2.src/SingleSource/UnitTests/2009-12-07-StructReturn.c"

**JVM segfault: Passing structures as arguments**
sulong/tests/com.oracle.truffle.llvm.tests.sulong.native/c/truffle-c/structTest/passPerValue9.c
sulong/tests/com.oracle.truffle.llvm.tests.sulong.native/c/truffle-c/structTest/structTest23.c
sulong/tests/com.oracle.truffle.llvm.tests.sulong.native/c/truffle-c/structTest/structTest24.c
sulong/tests/com.oracle.truffle.llvm.tests.sulong.native/c/truffle-c/structTest/structTest25.c
sulong/tests/com.oracle.truffle.llvm.tests.sulong.native/c/truffle-c/structTest/structTest26.c

**Char signed/unsigned issues**
test[c/truffle-c/unionTest/memberInitialization2]: FAILED
test[c/truffle-c/unionTest/unionTest12]: FAILED
test[c/truffle-c/charTest/charArray]: FAILED
test[c/truffle-c/arrayTest/arrayTest22]: FAILED
tests/com.oracle.truffle.llvm.tests.bitcode.uncommon.native/uncommon/fptox.c

**JVM segfault:  after test throws signal**
sulong/tests/com.oracle.truffle.llvm.tests.sulongcpp.native/cpp/test004
sulong/tests/com.oracle.truffle.llvm.tests.sulongcpp.native/cpptest005
sulong/tests/com.oracle.truffle.llvm.tests.sulongcpp.native/cpptest011
sulong/tests/com.oracle.truffle.llvm.tests.sulongcpp.native/cpptest013
sulong/tests/com.oracle.truffle.llvm.tests.sulongcpp.native/cpptest014
sulong/tests/com.oracle.truffle.llvm.tests.sulongcpp.native/cpptest015
sulong/tests/com.oracle.truffle.llvm.tests.sulongcpp.native/cpptest016
sulong/tests/com.oracle.truffle.llvm.tests.sulongcpp.native/cpptest017
sulong/tests/com.oracle.truffle.llvm.tests.sulongcpp.native/cpptest018
sulong/tests/com.oracle.truffle.llvm.tests.sulongcpp.native/cpptest019
sulong/tests/com.oracle.truffle.llvm.tests.sulongcpp.native/cpptest020
sulong/tests/com.oracle.truffle.llvm.tests.sulongcpp.native/cpptest021
sulong/tests/com.oracle.truffle.llvm.tests.sulongcpp.native/cpptest022
sulong/tests/com.oracle.truffle.llvm.tests.sulongcpp.native/cpptest025
sulong/tests/com.oracle.truffle.llvm.tests.sulongcpp.native/cpptest026
sulong/tests/com.oracle.truffle.llvm.tests.sulongcpp.native/cpptest027
sulong/tests/com.oracle.truffle.llvm.tests.sulongcpp.native/cpptest028
sulong/tests/com.oracle.truffle.llvm.tests.sulongcpp.native/cpptest029
sulong/tests/com.oracle.truffle.llvm.tests.sulongcpp.native/cpptest030
sulong/tests/com.oracle.truffle.llvm.tests.sulongcpp.native/cpptest031
sulong/tests/com.oracle.truffle.llvm.tests.sulongcpp.native/cpptest032
sulong/tests/com.oracle.truffle.llvm.tests.sulongcpp.native/cpptest033
sulong/tests/com.oracle.truffle.llvm.tests.sulongcpp.native/cpptest035
sulong/tests/com.oracle.truffle.llvm.tests.sulongcpp.native/cpptest041
sulong/tests/com.oracle.truffle.llvm.tests.sulongcpp.native/cpptest045
sulong/tests/com.oracle.truffle.llvm.tests.sulongcpp.native/cpptest050
sulong/tests/com.oracle.truffle.llvm.tests.sulongcpp.native/cpptest051

**JVM segfault: When using destructors**
sulong/tests/com.oracle.truffle.llvm.tests.sulongcpp.native/cpp/test024 sulong/tests/com.oracle.truffle.llvm.tests.sulongcpp.native/cpp/test034 sulong/tests/com.oracle.truffle.llvm.tests.sulongcpp.native/cpp/test042 sulong/tests/com.oracle.truffle.llvm.tests.sulongcpp.native/cpp/test043 sulong/tests/com.oracle.truffle.llvm.tests.sulongcpp.native/cpp/test044 sulong/tests/com.oracle.truffle.llvm.tests.sulongcpp.native/cpp/test052 sulong/tests/com.oracle.truffle.llvm.tests.sulongcpp.native/cpp/test053

**JVM segfault: When using destructors (different segfault)**
sulong/tests/com.oracle.truffle.llvm.tests.sulongcpp.native/cpp/test014 sulong/tests/com.oracle.truffle.llvm.tests.sulongcpp.native/cpp/test017 sulong/tests/com.oracle.truffle.llvm.tests.sulongcpp.native/cpp/test035 sulong/tests/com.oracle.truffle.llvm.tests.sulongcpp.native/cpp/test036 sulong/tests/com.oracle.truffle.llvm.tests.sulongcpp.native/cpp/test037 sulong/tests/com.oracle.truffle.llvm.tests.sulongcpp.native/cpp/test038 sulong/tests/com.oracle.truffle.llvm.tests.sulongcpp.native/cpp/test039 sulong/tests/com.oracle.truffle.llvm.tests.sulongcpp.native/cpp/test040 sulong/tests/com.oracle.truffle.llvm.tests.sulongcpp.native/cpp/test045 sulong/tests/com.oracle.truffle.llvm.tests.sulongcpp.native/cpp/test046 sulong/tests/com.oracle.truffle.llvm.tests.sulongcpp.native/cpp/test047 sulong/tests/com.oracle.truffle.llvm.tests.sulongcpp.native/cpp/test048 sulong/tests/com.oracle.truffle.llvm.tests.sulongcpp.native/cpp/test049 sulong/tests/com.oracle.truffle.llvm.tests.sulongcpp.native/cpp/test050

**AArch64 Loop Vectorisation nodes (eg llvm.experimental.vector.reduce.add.v4i32) missing**
  test[c/arrays/intArray]: FAILED
  test[c/truffle-c/programTest/programTest0]: FAILED
  test[c/truffle-c/arrayTest/arrayTest18]: FAILED
  test[c/truffle-c/arrayTest/arrayTest5]: FAILED

**Individual errors:**
SulongSuite libc/memcpy/memcpy-struct-mixed - final passed value is wrong.

./tests/com.oracle.truffle.llvm.tests.sulongcpp.native/cpp/test026.cpp - throwing exception crashes the JVM.

./tests/com.oracle.truffle.llvm.tests.sulong.native/c/stdlib/stat.c - opening a file fails

./tests/com.oracle.truffle.llvm.tests.sulong.native/c/stdlib/signal_errno.c - cannot create signal handler

./tests/com.oracle.truffle.llvm.tests.sulong.native/c/max-unsigned-int-to-double-cast.c - values after casting different

./tests/com.oracle.truffle.llvm.tests.libc.native/libc/errno/errno.c - errno value wrong

tests/com.oracle.truffle.llvm.tests.sulongcpp.native/cpp/testRuntimeError.cpp - Java.lang.ArrayIndexOutOfBoundsException

tests/com.oracle.truffle.llvm.tests.bitcode.uncommon.native/uncommon/fptoui1.ll - output differences

**LLVM suite failures (no investigation done):**
"test-suite-3.2.src/SingleSource/Regression/C++/2008-01-29-ParamAliasesReturn.cpp",
"test-suite-3.2.src/SingleSource/Regression/C/globalrefs.c",
"test-suite-3.2.src/SingleSource/UnitTests/2006-01-23-UnionInit.c"

**interop suite failures (no investigation done):**
testCallDerefHandleMember
testAliasedPointer
testFillPoints
testAddAndSwapPoint
testFillNested
testFillFusedArray

**debug suite failures (no investigation done):**
primitives.ll
testPrimitives.c testStructures.c testReenterArgsAndVals.c testFunctionPointer.c testLongDouble.cpp testBitFields.cpp

**Bitcodeformat suite failures (no investigation done):**
checkNumbers[hello-linux-link-fembed-bitcode]
checkNumbers[hello-linux-link-fembed-bitcode.so]

**toolchain**
Suite fails early on. Need to investigate.

**Comment by rschatz** [comment]
Thanks for the detailed investigation!

I'm a bit surprised by the interop test failures. I would have expected those to make the least problems, since they don't depend on anything native ;) Still it's good to know where we stand.

I will merge https://github.com/oracle/graal/pull/2280 asap.

**Comment by rschatz** [comment]
I think all of those have been fixed in various changes recently, and the fixes will be in 21.2.

Some of the interop tests are still ignored on master, but I just double checked and they all pass.
