### ISSUE TITLE
Upgrading from 19.3.1 to 20.1.0-dev (java8) increases binary size with 8mb + 1gb more memory usage

### ISSUE THREAD

**Issue by borkdude** [oracle/graal#2281]
**Insights from after this issue was created**

The larger binary size can be explained by reachable methods in `java.util.Properties` which triggers inclusion of XML functionality in 20.+. See https://github.com/oracle/graal/issues/2136#issuecomment-619351276.

The only unresolved bit here is the 1GB extra memory usage in 20.1-dev. This could also be explained by more reachable classes. Still it might be good to have a look if memory consumption in version 20 didn't go up for some other reason.

**Describe the issue**

With my Clojure interpreter [babashka](https://github.com/borkdude/babashka/) I'm seeing the following issues when upgrading from java8 19.3.1 to java8 20.1.0-dev:

1) Cannot build on CircleCI anymore. I'm restricted to 4gb in total and have to set the max heap size for GraalVM to 3gb to leave some room for other processes. This used to work until 19.3.1 java8. It no longer works with 20.1.0-dev. There I have to set the max heap size to 4gb instead of 3gb in order to compile succesfully.
2) The binary size increases with roughly 8mb, up from 42mb to 49.5mb. Smaller binaries are preferred in general. 

**Steps to reproduce the issue**

- Clone the [babashka](https://github.com/borkdude/babashka/) repository. Note, you have to clone recursively as described in: https://github.com/borkdude/babashka/blob/master/doc/dev.md:

      $ git clone https://github.com/borkdude/babashka --recursive

- Install [lein](https://github.com/technomancy/leiningen). This tool is used to compile the Clojure project into an uberjar which will then be used with GraalVM.

- Build with GraalVM: https://github.com/borkdude/babashka/blob/master/doc/dev.md#build. This is as simple as setting `$GRAALVM_HOME` and running `script/compile`. To tweak memory settings:

      $ BABASHKA_XMX="-J-Xmx4g" script/compile

For windows, there is a `script/compile.bat` script, although I haven't tested that concerning this issue.

**Describe GraalVM and your environment:**

 - GraalVM version: GraalVM CE 19.3.1 and GraalVM CE 20.1.0-dev-20200321_0524
 - JDK major version: 8
 - OS: macOS Mojave
 - Architecture: AMD64 (Macbook Pro 2019)

**Comment by borkdude** [comment]
Comment that could also be relevant to this issue:

https://github.com/oracle/graal/issues/2136#issuecomment-618285261

**Comment by cstancu** [comment]
@borkdude we reduced the memory footprint of the image build process since this issue was opened. It would be interesting to check if it fits in CircleCI again. I'm closing this issue as I don't believe that it is relevant anymore.
