### ISSUE TITLE
ImageClassLoader holds on to large number of irrelevant Method(s) and Field(s)

### ISSUE THREAD

**Issue by jaikiran** [oracle/graal#2287]
The `ImageClassLoader` seems to be responsible for initializing all classes on the classpath during native image generation (during classlist phase). During this process, it loads the class (through `Class.forName` with `initialize` param as `false`) and then for each such loaded class, it goes on to check if annotations can be loaded from that class (i.e. `AnnotatedElement.getAnnotations` doesn't throw any error). If it can't load the annotations on that class, for whatever reason, it skips this class and moves on to the next. 

For classes that can successfully load the annotations, it does further checks to see if there are certain Graal specific annotations that classify it as a "hosted only" class or an "application class". Based on this check, it stores that class in a relevant `Set` (called `applicationClasses` or `hostedOnlyClasses`). All this seems fine.

For each such identified class, it then goes on to "find system elements". This involves checking each method and field on the class to see if any annotations are available on them. If there are any annotations available on them, then the `ImageClassLoader` stores that Method/Field into a `Set` called `systemMethods`, `systemFields` respectively. These `Set`s are (only) used whenever there's a call on the `ImageClassLoader` to find and return any method/field that may have certain specific annotations (for example, the `CEntryPoint`, `CConstant`, `CFunction`, `NativeImageReinitialize` and such). The problem in this code is the current `annotationsAvailable` method which returns `true` even if there may be 0 annotations on the method/field:

```
private static boolean annotationsAvailable(AnnotatedElement element) {
        try {
            element.getAnnotations();
            return true;
        } catch (Throwable t) {
            handleClassLoadingError(t);
            return false;
        }
    }

```
This causes the `ImageClassLoader` to unnecessarily hold on to a large number of unnecessary `Method` and `Field` instances that aren't really relevant and thus cause both unnecessary additional memory usage as well as unnecessary time spent on iterating over these additional methods/fields whenever a call is made on the `ImageClassLoader` to find any specific annotation.

**Comment by jaikiran** [comment]
I've issued https://github.com/oracle/graal/pull/2288 with a potential fix.

**Comment by adinn** [comment]
Hmm, that looks worth having ;-) Nice work, Jaikiran!

**Comment by jaikiran** [comment]
Hello @dougxc, I'm closing this since the linked PR has been merged (thanks!). However, I don't know what milestone to add as the fix version for this issue.
