### ISSUE TITLE
Fatal errors when building native image of Kotlin/Native compiler

### ISSUE THREAD

**Issue by qwwdfsad** [oracle/graal#2289]
**Describe the issue**

Attempt to build a native image of Kotlin/Native compiler fails with fatal errors: `com.oracle.graal.pointsto.util.AnalysisError$ParsingError: Error encountered while parsing...` with cause `JVMCIError: failed guarantee: DynamicNewInstanceNode.instanceType is constant, should have been canonicalized to NewInstanceNode`.

**Steps to reproduce the issue**

1) Download Kotlin/Native: https://github.com/JetBrains/kotlin/releases/tag/v1.3.70 (link after a changelog, `kotlin-native-macos-1.3.70.tar.gz`)
2) Unpack it, target JAR lies in `kotlin-native-macos-1.3.70/konan/lib/kotlin-native.jar`
3) Try to run `./native-image -cp kotlin-native-macos-1.3.70/konan/lib/kotlin-native.jar org.jetbrains.kotlin.cli.utilities.MainKt`

**Describe GraalVM and your environment:**
 - GraalVM version: reproducible with both stable Graal 20.0.0 and https://github.com/graalvm/graalvm-ce-dev-builds/releases/tag/20.1.0-dev-20200325_0537
 - JDK major version: 11
 - OS:  macOS Catalina
 - Architecture: AMD64

**More details**
`--native-image-info` and  `--verbose` flags don't really add any information about these errors.
Gist with all the stacktaces: https://gist.github.com/qwwdfsad/b4ac5deeeffda0befb4c4d5fb2c6e4f4

**Comment by qwwdfsad** [comment]
Hi, should I provide some additional details?

**Comment by christianwimmer** [comment]
I think this problem has already been fixed in the last months. If it is still reproducible, please re-open the issue.
