### ISSUE TITLE
GraalVM 20.0.0 CE catalog seems to only have native-image available.

### ISSUE THREAD

**Issue by rmoquin** [oracle/graal#2295]
**Describe the issue**
I wanted to experiment with graalpython, so I downloaded GraalVM 2.0.0.  When I open a windows command prompt and run:

gu install python

I get the following output:

Downloading: Component catalog from www.graalvm.org
Error: Unknown component: python

If I run:

gu available

I get  the following output:

Downloading: Component catalog from www.graalvm.org
ComponentId              Version             Component name      Origin
--------------------------------------------------------------------------------
native-image             20.0.0              Native Image        github.com

I thought I was able to install more extensions with the community edition than just native-image?

**Steps to reproduce the issue**

1. Run cmd.exe
2. Run gu install python

**Describe GraalVM and your environment:**
 - GraalVM 20.0.0
 - JDK major version: 11
 - OS: Windows 10
 - Architecture: AMD64

**More details**

**Comment by olyagpl** [comment]
@rmoquin, GraalVM 20.0  distribution for  Windows platforms currently includes the JDK with the GraalVM compiler enabled, the gu utility, JavaScript support and the developer tools (e.g., Chrome inspector based debugger, Profiler, etc.). Node.js support is scheduled to be included in the next GraalVM release (20.1).  
The support for other languages  Python, Ruby and R is on the roadmap but we don't have exact timeframe. 
GraalPython is configured to use an internal  GraalVM LLVM toolchain to compile the C/C++ code and produce both native code and bitcode. Compiling native programs via the GraalVM LLVM runtime on Windows OS is under development now. 
GraalVM 20.1 is planned for May 19. Stay tuned!

**Comment by rmoquin** [comment]
Gotcha, thanks.  It wasn't clear in the docs that this wasn't ready yet on Windows.  Thanks for letting me know! Looking forward to being able to try it out.
