### ISSUE TITLE
Looking up language services without TruffleContext entered causes a NullPointerException

### ISSUE THREAD

**Issue by kustosz** [oracle/graal#2297]
**Describe GraalVM and your environment :**
 - GraalVM version or commit id if built from source: **20.0**
 - CE or EE: **EE**
 - JDK version: **JDK8**
 - OS and OS Version: **macOS Catalina**
 - Architecture: **x86_64**
 - The output of `java -Xinternalversion`: 
```
Java HotSpot(TM) 64-Bit Server VM GraalVM EE 20.0.0 (25.241-b07-jvmci-20.0-b02) for bsd-amd64 JRE (8u241), built on Jan 20 2020 12:55:56 by "graal" with gcc 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.42)
```

**Have you verified this issue still happens when using the latest snapshot?**
You can find snapshot builds here: https://github.com/graalvm/graalvm-ce-dev-builds/releases

No.

**Describe the issue**
Trying to call `TruffleInstrument.Env.lookup(LanguageInfo, Class)` from instrument implementation, without calling `TruffleContext.enter` first causes a NullPointerException.

**Code snippet or code repository that reproduces the issue**

**Steps to reproduce the issue**
Please include both build steps as well as run steps
1. Create a `TruffleLanguage` and register a service in `createContext`.
2. Define an instrument and try looking up the service defined in step 1. in `onCreate` method.
3. Run the instrument.
4. A `NullPointerException` is thrown.

**Expected behavior**
A more informative error should be reported instead.

**Additional context**
Add any other context about the problem here. Specially important are stack traces or log output. Feel free to link to gists or to screenshots if necesary
<details><summary>Details</summary>

```
[info] org.enso.interpreter.test.instrument.ContextManagementTest *** ABORTED ***
[info]   org.graalvm.polyglot.PolyglotException: java.lang.NullPointerException
[info]   at com.oracle.truffle.polyglot.EngineAccessor$EngineImpl.lookup(EngineAccessor.java:280)
[info]   at com.oracle.truffle.api.instrumentation.TruffleInstrument$Env.lookup(TruffleInstrument.java:331)
[info]   at org.enso.interpreter.instrument.RuntimeServerInstrument.onCreate(RuntimeServerInstrument.java:40)
[info]   at com.oracle.truffle.api.instrumentation.TruffleInstrument$Env.onCreate(TruffleInstrument.java:379)
[info]   at com.oracle.truffle.api.instrumentation.InstrumentationHandler$InstrumentClientInstrumenter.create(InstrumentationHandler.java:1623)
[info]   at com.oracle.truffle.api.instrumentation.InstrumentationHandler.createInstrument(InstrumentationHandler.java:383)
[info]   at com.oracle.truffle.api.instrumentation.InstrumentAccessor$InstrumentImpl.createInstrument(InstrumentAccessor.java:103)
[info]   at com.oracle.truffle.polyglot.PolyglotInstrument.ensureCreated(PolyglotInstrument.java:127)
[info]   at com.oracle.truffle.polyglot.PolyglotEngineImpl.ensureInstrumentsCreated(PolyglotEngineImpl.java:420)
[info]   at com.oracle.truffle.polyglot.PolyglotEngineImpl.createInstruments(PolyglotEngineImpl.java:413)
[info]   ...
```
</details>

**Comment by boris-spas** [comment]
Tracking internally as Issue GR-23073.

**Comment by tzezula** [comment]
Fixed by https://github.com/oracle/graal/commit/f85f90ea02afa5cdd2ead6890e93d15befcce6a4
