### ISSUE TITLE
Java objects injected in Javascript runtime do not behave as expected

### ISSUE THREAD

**Issue by sir-ion** [oracle/graal#2298]
**Describe GraalVM and your environment :**
 - GraalVM version: **20.0.0**
 - CE or EE: **CE**
 - JDK version: **JDK11**
 - OS and OS Version: **Ubuntu 19.10**
 - Architecture: **amd64**
 - The output of `java -Xinternalversion`:
```
 OpenJDK 64-Bit Server VM (11.0.6+9-jvmci-20.0-b02) for linux-amd64 JRE (11.0.6+9-jvmci-20.0-b02), built on Jan 20 2020 20:06:41 by "buildslave" with gcc 7.3.0
```

**Have you verified this issue still happens when using the latest snapshot?** No

**Describe the issue**
I'm opening this issue as I have been asked to do so after a couple of discussions on the Slack channel graalvm#polyglot.
What I am trying to achieve is the following: on my website users are allowed to enter javascript code that I execute on the server side. Inside the javascript runtimes that run their code I must provide them some helper functions (e.g. something like `JsHelpers.dateFromString(...)`). These helpers are actually functions written in Java and then injected inside javascript runtimes.
Now, my problem is with the type of the objects returned by these helper functions inside Javascript. As I have been told on Slack when a Java object is passed inside Javascript the strategy of GraalVM is not to provide the corresponding Javascript native object of the appropriate type, but rather to expose "something" that behaves like one would expect (hope I got it right, mostly...).
However, when I need to pass from Java to Javascript instances of bytes[] or LocalDateTime I have come across some unexpected(?) behaviour as shown in the following piece of code.

Remark: I do not know whether or not when I pass some objects from Java to Javascript it must be wrapped with `Value.asValue(myJavaObject)`, therefore in the following snippet I try all the possibilities (with no different results).

**Code snippet or code repository that reproduces the issue**
```
package com.gullivernet.goal.scripting.services;

import java.time.LocalDateTime;

import org.graalvm.polyglot.Context;
import org.graalvm.polyglot.HostAccess;
import org.graalvm.polyglot.Value;


public class MWE {
    public static void main (String[] args) {
        Context ctx = Context.newBuilder("js").allowHostAccess(HostAccess.EXPLICIT).build();
        ctx.initialize("js");

        // Set up data and put it inside javascript
        byte[] bytes = new byte[] { 0, 1, 2, 3 };
        ctx.getBindings("js").putMember("bytes", bytes);
        ctx.getBindings("js").putMember("valueBytes", Value.asValue(bytes));

        LocalDateTime dateTime = LocalDateTime.of(2000,1,1,1,1,1);
        ctx.getBindings("js").putMember("dateFromJava", dateTime);
        ctx.getBindings("js").putMember("valueDateFromJava", Value.asValue(dateTime));

        // Now make some tests
        System.out.println("Bytes behaviour;");
        ctx.eval("js", "console.log(bytes);");                          // Print from javascript: BAD
        ctx.eval("js", "console.log(bytes.constructor);");              // Print from javascript: BAD (undefined)
        System.out.println(ctx.eval("js", "bytes"));                    // Print from java:       OK
        ctx.eval("js", "newArray = new Uint8Array(bytes);");            // Try as suggested on slack
        ctx.eval("js", "console.log(newArray);");                       // Print from javascript: BAD (no output)
        ctx.eval("js", "console.log(newArray.constructor);");           // Print from javascript: OK  (obviously)
        System.out.println(ctx.eval("js", "newArray"));                 // Print from java:       BAD (empty Uint8Array)
        System.out.println("--------------------");

        System.out.println("ValueBytes behaviour:");
        ctx.eval("js", "console.log(valueBytes);");                     // Print from javascript: BAD
        ctx.eval("js", "console.log(valueBytes.constructor);");         // Print from javascript: BAD (undefined)
        System.out.println(ctx.eval("js", "valueBytes"));               // Print from java:       OK
        ctx.eval("js", "newValueArray = new Uint8Array(valueBytes);");  // Try as suggested on slack
        ctx.eval("js", "console.log(newValueArray);");                  // Print from javascript: BAD (no output)
        ctx.eval("js", "console.log(newValueArray.constructor);");      // Print from javascript: OK  (obviously)
        System.out.println(ctx.eval("js", "newValueArray"));            // Print from java:       BAD (empty Uint8Array)
        System.out.println("--------------------");

        System.out.println("DateFromJava behaviour;");
        ctx.eval("js", "console.log(dateFromJava);");                   // Print from javascript: OK
        ctx.eval("js", "console.log(dateFromJava.constructor)");        // Print from javascript: BAD (undefined)
        System.out.println(ctx.eval("js", "dateFromJava"));             // Print from java:       OK
        ctx.eval("js", "newDate = new Date(dateFromJava);");            // Try as suggested on slack
        ctx.eval("js", "console.log(newDate);");                        // Print from javascript: OK
        ctx.eval("js", "console.log(newDate.constructor)");             // Print from javascript: OK  (obviously)
        System.out.println(ctx.eval("js", "newDate"));                  // Print from java:       OK
        System.out.println("--------------------");

        System.out.println("ValueDateFromJava behaviour:");
        ctx.eval("js", "console.log(valueDateFromJava);");              // Print from javascript: OK
        ctx.eval("js", "console.log(valueDateFromJava.constructor)");   // Print from javascript: BAD (undefined)
        System.out.println(ctx.eval("js", "valueDateFromJava"));        // Print from java:       OK
        ctx.eval("js", "newValueDate = new Date(valueDateFromJava);");  // Try as suggested on slack
        ctx.eval("js", "console.log(newValueDate);");                   // Print from javascript: OK
        ctx.eval("js", "console.log(newValueDate.constructor)");        // Print from javascript: OK  (obviously)
        System.out.println(ctx.eval("js", "newValueDate"));             // Print from java:       OK
    }
}
```
**Output:**
```
Bytes behaviour;
[B@fd8294b
undefined
[0, 1, 2, 3]

function Uint8Array() { [native code] }
Uint8Array[]
--------------------
ValueBytes behaviour:
[B@fd8294b
undefined
[0, 1, 2, 3]

function Uint8Array() { [native code] }
Uint8Array[]
--------------------
DateFromJava behaviour;
2000-01-01T01:01:01
undefined
2000-01-01T01:01:01
Sat Jan 01 2000 02:01:01 GMT+0100 (CET)
function Date() { [native code] }
2000-01-01T01:01:01.000Z
--------------------
```

**Steps to reproduce the issue**
Just run the above snippet.

**Expected behavior**
When I pass a byte[] entity from Java to Javascript using `.putMember("jsBytes", bytes)` what is made available inside Javascript is only a wrapper of the Java object: inside Javascript I can't use it for no good (except `jsBytes[i]`) and the attempt to create a real Javascript array with `new Uint8Array(jsBytes)` (as told on Slack) fails.

When I pass a LocalDateTime object from Java to Javascript using `.putMember("jsDate", javaDateTime)` the object made available inside Javascript can be printed as a date, but its `constructor` property is `undefined`, therefore it is not possible to use any method provided by the Javascript Date API.
At least in this case I'm able to obtain a real Javascript Date object using `new Date(jsDate)`.

**Additional context**
As I have already told, in the Javascript environment I have to run some user generated code, therefore instructing users to wrap the results of `JsHelper.someDateMethod()` with the corresponding real Javascript constructor is not an option (and does not always work, as in the case of byte[]).
For this reasons at the moment I fallback to do the following inside `.someDateMethod()`:

```
    long timestamp = 123456789L;
    return ctx.eval("js", "new Date(" + timestamp + ")");
```

Since it's the first time I use GraalVM any suggestions or thoughts about how to achieve my needs with the current implementation of GraalVM is extremely welcome.

**Comment by boris-spas** [comment]
Tracking internally as Issue GR-23074.

**Comment by wirthi** [comment]
Hi @sir-ion 

sorry for the delay in answering your question. For JavaScript-specific questions, you might get faster replies at the JS engine's repository at https://github.com/graalvm/graaljs/.

**byte[]**

I think using a `org.graalvm.polyglot.proxy.ProxyArray` is the best solution here:
```
ctx.getBindings("js").putMember("bytes", ProxyArray.fromArray(1,2,3,4));
```
Watch out for a pitfall here - `ProxyArray.fromArray` expects an `Object ...` argument, thus you can ONLY pass in an object arrays, or use constants in the call directly (like in my example above). Thanks to Java's varargs semantics, passing in your `bytes` array would result in an one-element array on the JavaScript side, whose only member is a `byte[]` (with the same accessibility problems as you started with). You have to manually copy your bytes to a fresh `Object[]` first. A cleaner solution would be to implement your own type based on `ProxyArray`, thus allowing you to e.g. grow or shrink the array.

**Date**

Creating a JavaScript Date object manually as you do is probably the best solution at the moment. This seems to solve all your problems, right? The issue with the `Date.constructor` we have solved for other data types already, see the [FAQ entry on js.experimental-foreign-object-prototype](https://github.com/graalvm/graaljs/blob/master/docs/user/FAQ.md#builtin-functions-like-arraymap-or-fnapply-are-not-available-on-non-javascript-objects-like-proxyarrays-from-java). It might be possible to extend this behavior to `Date` as well.

Best,
Christian
