### ISSUE TITLE
Can't run mx gate in graal/compiler anymore

### ISSUE THREAD

**Issue by rwestrel** [oracle/graal#2303]
**Describe the issue**

mx gate fails in graal/compiler

**Steps to reproduce the issue**

mx gate fails with:

Running: mx --java-home /home/roland/openjdk1.8.0_242-jvmci-20.0-b02 pylint --primary
Detected pylint version: 2.4.4
Running pylint on /mnt/ssd/rwestrel/graal-repos/graal/compiler/mx.compiler/mx_compiler.py...
************* Module mx_compiler
mx.compiler/mx_compiler.py:163:12: R1720: Unnecessary "else" after "raise" (no-else-raise)
mx.compiler/mx_compiler.py:433:37: E1135: Value 'Task.tags' doesn't support membership test (unsupported-membership-test)
mx.compiler/mx_compiler.py:935:0: R1721: Unnecessary use of a comprehension (unnecessary-comprehension)

gate: 31 Mar 2020 11:26:16(+00:10) END:   Pylint [0:00:09.240178] [disk (free/total): 166.3GB/234.7GB]
Traceback (most recent call last):
  File "/mnt/ssd/rwestrel/graal-repos/mx/mx_gate.py", line 422, in gate
    _run_gate(cleanArgs, args, tasks)
  File "/mnt/ssd/rwestrel/graal-repos/mx/mx_gate.py", line 542, in _run_gate
    if mx.command_function('pylint')(['--primary']) != 0:
  File "/mnt/ssd/rwestrel/graal-repos/mx/mx_commands.py", line 147, in __call__
    return self.command_function(*args, **kwargs)
  File "/mnt/ssd/rwestrel/graal-repos/mx/mx.py", line 14142, in pylint
    run([pylint_exe, '--reports=n', '--rcfile=' + rcfile, pyfile] + additional_options, env=env)
  File "/mnt/ssd/rwestrel/graal-repos/mx/mx.py", line 12575, in run
    abort(retcode)
  File "/mnt/ssd/rwestrel/graal-repos/mx/mx.py", line 3815, in abort
    raise SystemExit(error_code)
SystemExit: 10

mx gate -t Pylint -x fails with:

unning: mx --java-home /home/roland/openjdk1.8.0_242-jvmci-20.0-b02 verifylibraryurls 
gate: 31 Mar 2020 11:31:48(+02:44) END:   VerifyLibraryURLs [0:00:08.503940] [disk (free/total): 166.3GB/234.7GB]
gate: 31 Mar 2020 11:31:48(+02:44) BEGIN: UnitTests: hosted-product compiler
gate: 31 Mar 2020 11:31:48(+02:44) END:   UnitTests: hosted-product compiler [0:00:00.000093] [disk (free/total): 166.3GB/234.7GB]
Traceback (most recent call last):
  File "/mnt/ssd/rwestrel/graal-repos/mx/mx_gate.py", line 422, in gate
    _run_gate(cleanArgs, args, tasks)
  File "/mnt/ssd/rwestrel/graal-repos/mx/mx_gate.py", line 625, in _run_gate
    runner(args, tasks)
  File "/mnt/ssd/rwestrel/graal-repos/graal/compiler/mx.compiler/mx_compiler.py", line 730, in _graal_gate_runner
    compiler_gate_runner(['compiler', 'truffle'], graal_unit_test_runs, graal_bootstrap_tests, tasks, args.extra_vm_argument)
  File "/mnt/ssd/rwestrel/graal-repos/graal/compiler/mx.compiler/mx_compiler.py", line 546, in compiler_gate_runner
    r.run(suites, tasks, ['-XX:-UseJVMCICompiler'] + _remove_empty_entries(extraVMarguments))
  File "/mnt/ssd/rwestrel/graal-repos/graal/compiler/mx.compiler/mx_compiler.py", line 433, in run
    if 'coverage' not in Task.tags:
TypeError: argument of type 'NoneType' is not iterable

**Describe GraalVM and your environment:**

Latest mx and graal github repo on fedora 31

**Comment by ansalond** [comment]
Hi @rwestrel, thanks for your report. You are running with Pylint 2.4.4:
```
Detected pylint version: 2.4.4
```

while we run our gates with Pylint 1.9.3:
https://github.com/oracle/graal/blob/master/common.hocon#L47

Could you please try running the gate with Pylint 1.9.3?

**Comment by rwestrel** [comment]
> Could you please try running the gate with Pylint 1.9.3?

Note that I pasted 2 mx gate commands that both fail. The second one skips pylint. So it's not only about pylint.

**Comment by ansalond** [comment]
You are right, there's a bug in `mx_compiler.py`:
```
diff --git a/compiler/mx.compiler/mx_compiler.py b/compiler/mx.compiler/mx_compiler.py
index 56698b10c92..4e352354b14 100644
--- a/compiler/mx.compiler/mx_compiler.py
+++ b/compiler/mx.compiler/mx_compiler.py
@@ -430,7 +430,7 @@ class UnitTestRun:
                     extra_args = ['--verbose', '--enable-timing']
                 else:
                     extra_args = []
-                if 'coverage' not in Task.tags:
+                if Task.tags is None or 'coverage' not in Task.tags:
                     # If this is a coverage execution, we want maximal coverage
                     # and thus must not fail fast.
                     extra_args += ['--fail-fast']
```

I'll merge it in my next PR. Thanks!

**Comment by rwestrel** [comment]
Thanks. That fixes the main failure.

**Comment by ansalond** [comment]
Fixed in https://github.com/oracle/graal/commit/c006ed92251fccb602233df452e129353d6f055e.
