### ISSUE TITLE
JDK build error after "mx updategraalinopenjdk".

### ISSUE THREAD

**Issue by XiaohongGong** [oracle/graal#2304]
**Describe the issue**
Updating graal compiler in openjdk, and then building the updated jdk will report the error:

    jdk_src/src/jdk.internal.vm.compiler/share/classes/org.graalvm.compiler.hotspot/src/org/graalvm/compiler/hotspot/SymbolicSnippetEncoder.java:107:
    error: package org.graalvm.nativeimage does not exist
    import org.graalvm.nativeimage.Platform;
                              ^

The package defined in native image is used and it does not exist in jdk src. 

**Steps to reproduce the issue**
Please include both build steps as well as run steps

    1.  cd graal/compiler & mx updategraalinopenjdk jdk_src 15
    2.  cd jdk_src & ./configure [options] & make images

**Describe GraalVM and your environment:**
 - GraalVM version (latest snapshot builds can be found [here](https://github.com/graalvm/graalvm-ce-dev-builds/releases)), or commit id if built from source: **master**
 - JDK major version: **15**
 - OS: **linux**
 - Architecture: **AArch64**

**More details**
Add any other information about the problem here. Especially important are stack traces or log output. Feel free to link to gists or to screenshots if necessary.
```
   This is caused by this patch:
   commit a859e4e45fee739c54bdaad645b71548bc409a1d
```

**Comment by tkrodriguez** [comment]
This is fixed by the above referenced commit.
