### ISSUE TITLE
Native image app crashes during runtime with `--static` build option in http4s scala application in linux environment

### ISSUE THREAD

**Issue by drocsid** [oracle/graal#2309]
**Describe the issue**

When building a native image using the --static argument, the application crashes during runtime. I think it might be happening specifically when a SSL POST request is made within the application

**Steps to reproduce the issue**

git clone https://github.com/drocsid/https_example

then to reproduce:

Run `native-image-build-cmd.sh` to build the image. Execute the `native-image` binary `./weatherdemo` after creation. Finally run `425.sh` to make a request trigger the application code. Assuming that the last client request execution gives a segfault.

https://github.com/drocsid/https_example/blob/fc2203815f1f5f03547971048bef929b6634cff0/src/main/scala/com/example/weatherdemo/WeatherdemoRoutes.scala#L75

From the logs:

```
[scala-execution-context-global-11] INFO  c.e.w.WeatherdemoRoutes - request IO(Request(method=POST, uri=https://api.flowroute.com/v2/messages, headers=Headers(Content-Type: application/json, Content-Length: 95))) 
[ioapp-compute-0] DEBUG o.h.c.PoolManager - Requesting connection: curAllocated=1 idleQueues.size=1 waitQueue.size=0 maxWaitQueueLimit=256 closed=false 
[ioapp-compute-0] DEBUG o.h.c.PoolManager - Active connection not found. Creating new one. curAllocated=1 idleQueues.size=1 waitQueue.size=0 maxWaitQueueLimit=256 closed=false

Segmentation Fault
```

**Describe GraalVM and your environment:**

java --version
openjdk 11.0.6 2020-01-14
OpenJDK Runtime Environment GraalVM CE 20.0.0 (build 11.0.6+9-jvmci-20.0-b02)
OpenJDK 64-Bit Server VM GraalVM CE 20.0.0 (build 11.0.6+9-jvmci-20.0-b02, mixed mode, sharing)

 - OS: Debian 4.19.0-4-amd64 bullseye 
 - Architecture: AMD64

**Comment by drocsid** [comment]
When time allows will attempt the solution on https://github.com/oracle/graal/issues/1919#issuecomment-589085506 to use muslc vs glibc and see 

and report back if it resolve the issue.

**Comment by eginez** [comment]
Great let us know if you still have a problem after switching to muslc, we are closing this issue for now

**Comment by drocsid** [comment]
I'm building the bundle and my app and test against it now. But I think this is really a bug. It seems necessary to build a bundle with the --static flag. Then you should probably make the bundle path part of the static flag arguments and document it right there.

**Comment by drocsid** [comment]
I made successful requests after building with muslc using my host OS gcc libstdc++.a . Then I think it did resolve the issue but will watch more requests in production.
