### ISSUE TITLE
[native-image] relative paths are based on compile time and not run-time working folder

### ISSUE THREAD

**Issue by pquiring** [oracle/graal#2316]
Relative paths created are based on the working folder at compile time and not during run-time.
Using graal 20.0 JDK 11 (Windows).

test.java
```
class test {
  public static void main(String[] args) throws java.io.IOException {
    System.out.println(new java.io.File("canonical").getCanonicalPath());
    System.out.println(new java.io.File("absolute").getAbsolutePath());
  }
}
```

Sample Output:

```
c:\bug>cd
c:\bug

c:\bug>javac test.java

c:\bug>java test
C:\bug\canonical
c:\bug\absolute

c:\bug>cd folder

c:\bug\folder>java -cp .. test
C:\bug\folder\canonical
c:\bug\folder\absolute

c:\bug\folder>cd ..

c:\bug>native-image test

c:\bug>test
C:\bug\canonical
c:\bug\absolute

c:\bug>cd folder

c:\bug\folder>..\test
C:\bug\canonical
c:\bug\absolute

c:\bug\folder>

```

The output from the native test.exe that is executed from \bug\folder creates paths based on the directory that native image was created (\bug), even if the exe is copied to another PC causing file not found exceptions.

This is similar to bug #1859

**Comment by pejovica** [comment]
Thanks for the report @pquiring. I'll look into it.

**Comment by pquiring** [comment]
I think the problem is with useCanonPrefixCache which is defined at:

https://github.com/oracle/graal/blob/master/substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jdk/FileSystemProviderSupport.java#L434

Try disabling it for Windows too.

**Comment by pquiring** [comment]
Nope that wasn't it.

**Comment by pquiring** [comment]
Looks like java.io.WinNTFileSystem.userDir needs to be re-initialized during run-time.  Trying to figure out how to do that.

**Comment by pejovica** [comment]
@pquiring Yes, the `userDir` field is the culprit. The fix will be merged shortly.

**Comment by pquiring** [comment]
I tested the changes and it works!  Thanks!

**Comment by pquiring** [comment]
How often are the 20.1-dev builds created?

**Comment by pquiring** [comment]
Never mind, there was a build last night, thanks!
