### ISSUE TITLE
JDWP/jvmti crashes 

### ISSUE THREAD

**Issue by TheGoesen** [oracle/graal#2320]
**Describe the issue**
I debug my java application using intellij. If I use adoptopenjdk the application runs fine. If I use graal I get roughly one crash per day. 

JDWP exit error AGENT_ERROR_NULL_POINTER(201): thread list corrupted [:2148]
FATAL ERROR in native method: JDWP thread list corrupted, jvmtiError=AGENT_ERROR_NULL_POINTER(201)

**Steps to reproduce the issue**
No specific pattern to reproduce, seems to occur at random.  

**Describe GraalVM and your environment:**
 - GraalVM version CE 20.0, 
 - JDK major version: 11
 - OS: Windows 10
 - Architecture: AMD64

**More details**
Not much more to say here, graal simply exits and it doesn't seem like its writing a log or dump. Are there some options i can enable to provide more verboose output?

**Comment by a701440** [comment]
I have the same issue running 20.0 on MacOS. Testing javascript embedded in a java app. I use VisualVM to sample the CPU. If I put some load on the app at around 5 concurrent requests the entire JVM crashes and the only info I get in the logs is this:

20200413.093014 JDWP exit error AGENT_ERROR_NULL_POINTER(201): thread list corrupted [:2148]
20200413.093014 FATAL ERROR in native method: JDWP thread list corrupted, jvmtiError=AGENT_ERROR_NULL_POINTER(201)

**Comment by RajeevKumarMarrapu** [comment]
I have the same issue running 20.0 on Windows. 

FATAL ERROR in native method: JDWP thread list corrupted, jvmtiError=AGENT_ERROR_NULL_POINTER(201)
JDWP exit error AGENT_ERROR_NULL_POINTER(201): thread list corrupted [:2148]

**Comment by gilles-duboscq** [comment]
Do you get an `hs_err*` file associated with this crash? That would be very helpful.

**Comment by TheGoesen** [comment]
Didn't see any dumps or logs. The hs_err* are still supposed to be in the working directory of the crashed application or has this changed?

**Comment by gilles-duboscq** [comment]
> the hs_err* are still supposed to be in the working directory of the crashed application

Yes that should still be the case.

**Comment by fernando-valdez** [comment]
The solution for this issue may be related to https://github.com/oracle/graal/issues/2164
Please don't hesitate to re-open if this issue continues in a recent GraalVM release.
