### ISSUE TITLE
Spring Boot on GraalVM - Disabling Forks During test Phase Displays Classpath Error

### ISSUE THREAD

**Issue by justinnichols** [oracle/graal#2325]
**Preface**

Given that it requires Spring Boot in the mix, I cannot say for certain if this is an issue with Spring Boot, or an issue with GraalVM.  It was suggested on Slack by @chumer to go ahead and submit this issue just in case.

**Repo with example project**

https://github.com/justinnichols/graalvm-mvn-test-bug

**Issue**

In order to breakpoint debug the test phase of a maven project in IntelliJ IDEA, we have to disable forks during the test phase.  When doing so, for a Spring Boot application on GraalVM, this causes truffle-api.jar to not be found on the classpath.  However, when simply running `mvn test`, the test works perfectly fine, but makes it so that the IDE cannot breakpoint debug the test.

**Prerequisites**
1. GraalVM must be installed
2. GraalVM must be set as `JAVA_HOME`
3. GraalVM must have `$JAVA_HOME/bin` on the `PATH`
4. Maven must be installed

**Steps to reproduce the issue**
1. `git clone https://github.com/justinnichols/graalvm-mvn-test-bug.git`
2. `mvn clean compile`
3. `mvn -DforkCount=0 -DreuseForks=false test`

**Describe GraalVM and your environment:**
```
openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment GraalVM CE 20.0.0 (build 11.0.6+9-jvmci-20.0-b02)
OpenJDK 64-Bit Server VM GraalVM CE 20.0.0 (build 11.0.6+9-jvmci-20.0-b02, mixed mode, sharing)
```
 - OS: macOS Catalina (10.15.4)
 - Architecture: 64-bit

**More details**
Error output:
```
  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v2.2.6.RELEASE)

2020-04-08 11:51:02.128  INFO 3322 --- [           main] o.e.g.m.t.b.components.MavenTestBugTest  : Starting MavenTestBugTest on spock with PID 3322
2020-04-08 11:51:02.130  INFO 3322 --- [           main] o.e.g.m.t.b.components.MavenTestBugTest  : No active profile set, falling back to default profiles: default
2020-04-08 11:51:02.426  INFO 3322 --- [           main] o.e.g.m.t.b.components.MavenTestBugTest  : Started MavenTestBugTest in 0.465 seconds (JVM running for 3.446)
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.807 s <<< FAILURE! - in org.example.graalvm.mvn.test.bug.components.MavenTestBugTest
[ERROR] runTest  Time elapsed: 0.222 s  <<< ERROR!
java.lang.IllegalStateException: No language and polyglot implementation was found on the classpath. Make sure the truffle-api.jar is on the classpath.
	at org.example.graalvm.mvn.test.bug.components.MavenTestBugTest.runTest(MavenTestBugTest.java:16)

[INFO]
[INFO] Results:
[INFO]
[ERROR] Errors:
[ERROR]   MavenTestBugTest.runTest:16 » IllegalState No language and polyglot implementa...
[INFO]
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
```

**Comment by tzezula** [comment]
Thanks for the report.
The JavaScript language is not found because the polyglot SDK is using an invalid polyglot.
The invalid polyglot is used because the Spring boot provides the `IsolatedClassLoader` as a context class loader and the `ServiceLoader` is not able to find out the `PolyglotImpl` in this class loader. 
Setting the Thread’s context class loader to the system class loader before creation the Context (Engine) seems to resolve the problem.

The following change fixes the test:
https://github.com/tzezula/graalvm-mvn-test-bug/commit/07de9959c82790920278e429490b49c6244790db

**Comment by nsoubelet** [comment]
Hi, I am still facing this issue. However my scenario is slightly different.
When I run the application directly via maven `spring-boot:run`, it works like a charm, but when packaging the app into a Jar and running the SpringBoot app using regular jar command, then it fails.
Both are using the same JVM.

I tried what @tzezula suggested but with no luck.
Anyone else having this issue? (preferably having also the solution).

Thanks
