### ISSUE TITLE
 Apache POI and GraalVM

### ISSUE THREAD

**Issue by konevts** [oracle/graal#2326]
**Feature request**

Hi!

I have small enterprise project based Quarkus and have some issuies with couple of Apache POI and GraalVM.

I created an issue on git hub https://github.com/konevts/apache-poi-quarkus/issues/2

Thanks for your job!
Konstantin

**Comment by fernando-valdez** [comment]
hello @konevts, please use the latest release of GraalVM and Quarkus to test your project. I am closing this ticket as it is a very old one, but feel free to reopen it in case the problem persists.
