### ISSUE TITLE
nativ-image java 8 graalvm 20.0.0 win64 static compile error

### ISSUE THREAD

**Issue by DoctorW00** [oracle/graal#2332]
bin\nativ-image --static -jar c:\myjar.jar

`Error: com.oracle.svm.hosted.substitute.DeletedElementException: Unsupported field java.net.URL.handlers is reachable
To diagnose the issue, you can add the option --report-unsupported-elements-at-runtime. The unsupported element is then reported at run time when it is accessed the first time.
Detailed message:
Trace:
        at parsing java.net.URL.setURLStreamHandlerFactory(URL.java:1140)
Call path from entry point to java.net.URL.setURLStreamHandlerFactory(URLStreamHandlerFactory):
        at java.net.URL.setURLStreamHandlerFactory(URL.java:1132)
        at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:48)
        at com.oracle.svm.core.JavaMainWrapper.runCore(JavaMainWrapper.java:151)
        at com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:186)
        at com.oracle.svm.core.code.IsolateEnterStub.JavaMainWrapper_run_5087f5482cc9a6abc971913ece43acb471d2631b(generated:0)

Error: Use -H:+ReportExceptionStackTraces to print stacktrace of underlying exception
Error: Image build request failed with exit status 1`

**Comment by DoctorW00** [comment]
Same error occurs on Ubuntu Linux using Java 11 (openjdk 11.0.6 2020-01-14).

**Comment by DoctorW00** [comment]
Warning: Reflection method java.lang.Class.forName invoked at org.apache.commons.logging.LogFactory.createFactory(LogFactory.java:1146)
Warning: Reflection method java.lang.Class.forName invoked at org.apache.commons.logging.LogFactory.createFactoryStore(LogFactory.java:331)
Warning: Reflection method java.lang.Class.forName invoked at org.apache.commons.logging.LogFactory.class$(LogFactory.java:1021)
Warning: Reflection method java.lang.Class.forName invoked at org.apache.commons.net.ftp.parser.DefaultFTPFileEntryParserFactory.createFileEntryParser(DefaultFTPFileEntryParserFactory.java:105)
Warning: Reflection method java.lang.Class.newInstance invoked at org.apache.commons.net.ftp.parser.DefaultFTPFileEntryParserFactory.createFileEntryParser(DefaultFTPFileEntryParserFactory.java:107)
Warning: Reflection method java.lang.Class.newInstance invoked at org.apache.commons.logging.LogFactory.createFactory(LogFactory.java:1047)
Warning: Reflection method java.lang.Class.newInstance invoked at org.apache.commons.logging.LogFactory.createFactoryStore(LogFactory.java:332)
Warning: Reflection method java.lang.Class.newInstance invoked at org.apache.commons.logging.LogFactory.createFactory(LogFactory.java:1147)
Warning: Reflection method java.lang.Class.getMethod invoked at org.fusesource.hawtjni.runtime.Library.chmod755(Library.java:505)
Warning: Reflection method java.lang.Class.getMethod invoked at org.fusesource.hawtjni.runtime.Library.chmod755(Library.java:509)
Warning: Reflection method java.lang.Class.getMethod invoked at org.fusesource.hawtjni.runtime.Library.chmod755(Library.java:502)
Warning: Reflection method java.lang.ClassLoader.loadClass invoked at org.fusesource.hawtjni.runtime.Library.chmod755(Library.java:507)
Warning: Reflection method java.lang.ClassLoader.loadClass invoked at org.fusesource.hawtjni.runtime.Library.chmod755(Library.java:508)
Warning: Reflection method java.lang.ClassLoader.loadClass invoked at org.fusesource.hawtjni.runtime.Library.chmod755(Library.java:500)
Warning: Reflection method java.lang.ClassLoader.loadClass invoked at org.apache.commons.logging.LogFactory.createFactory(LogFactory.java:1020)

**Comment by olpaw** [comment]
@DoctorW00 this sounds like something worth investigating. But without steps to reproduce we cannot do much. Please provide a proper native-image issue as described by template: https://github.com/oracle/graal/issues/new?assignees=&labels=bug%2C+native-image&template=1_issues_native_image.md&title=

**Comment by DoctorW00** [comment]
I do you one better and get you the source code https://github.com/DoctorW00/jSFDLSauger/releases/tag/1.0.1
