### ISSUE TITLE
[GR-51563] Use human readable output for time to compile

### ISSUE THREAD

**Issue by davsclaus** [oracle/graal#2340]
**Feature request**

Please include the following information:

**Is your feature request related to a problem? Please describe.**

When compiling the output is reported in milli seconds for both each individual steps and the total time at the end. 

**Describe the solution you'd like.**

I would like to see the time taken in human readable format where its reported in minute:seconds.

For example today graalvm CE 20.0.0 reports:
```
[total]: 106,304.07 ms, 11.55 GB
```

Instead say for example

```
[total]: 01:53 min, 11.55 GB
[total]: 1m53s, 11.55 GB
```

This was reported on twitter
https://twitter.com/davsclaus/status/1249627975215124480?s=20

**Comment by fernando-valdez** [comment]
Thanks for making this request. I created this ticket for internal tracking GR-51563

**Comment by wirthi** [comment]
This has actually been implemented a while back.
