### ISSUE TITLE
Musl-based static native-images no longer compile on master.

### ISSUE THREAD

**Issue by gradinac** [oracle/graal#2353]
Due to changes on the master branch, musl-based static native-images no longer compile on master.

There are currently two known issues:
 - The specified compiler options are now also passed to the query code compiler. This results in the duplication of some options passed over to GCC.
 - A GNU specific optimization that has been added to the `PosixTruffleNFIFeature`.

**Comment by starkgate** [comment]
You absolute legend. Thank you so much for debugging this.

**Comment by gradinac** [comment]
No problem at all! :)

**Comment by gradinac** [comment]
The fix for this issue has been merged to master so I will close this issue.
