### ISSUE TITLE
Make it possible to initialized proxified interfaces at runtime

### ISSUE THREAD

**Issue by sdeleuze** [oracle/graal#2357]
In an application that is using runtime initialization by default, it seems that proxified interfaces must  be initialized at build time. It is expected that proxies are created at build time, but I don't think this limitation about initialization makes sense.

This behavior can be reproduced with our `vanilla-tx` sample from [`spring-graal-native`](https://github.com/spring-projects-experimental/spring-graal-native):
 - `git clone https://github.com/spring-projects-experimental/spring-graal-native.git`
 - `./build.sh`
 - `cd spring-graal-native-samples/vanilla-tx`
 - Open `compile.sh` and remove the `--initialize-at-build-time=app.main.Finder \` line
 - `./build.sh`

You should see this error:
```
com.oracle.svm.core.util.UserError$UserException: Classes that should be initialized at run time got initialized during image building:
 app.main.Finder was unintentionally initialized at build time. com.sun.proxy.$Proxy208 caused initialization of this class with the following trace:
	at app.main.Finder.<clinit>(Finder.java)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at com.sun.proxy.$Proxy208.<clinit>(Unknown Source)
```

**Comment by eginez** [comment]
@sdeleuze I can not replicate this issue in the head of master. What version of graalvm are you using?

**Comment by eginez** [comment]
Never mind. I was able to trigger the problem by manually starting the class at runtime.

**Comment by eginez** [comment]
We are currently taking an overly optimistic policy when dealing `Proxy` classes in our class initialization logic (see https://github.com/oracle/graal/blob/dfab304406916b239935b9b70179e57ff3d1eadf/substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/classinitialization/ConfigurableClassInitialization.java#L618)

We have to  find more specific ways to handling Proxy classes to allow for the custom initialization of proxies, including dealing with `Proxy` classes being created as  a by-product of `Annotation` processing (see: https://github.com/graalvm/labs-openjdk-11/blob/42e00947be342877ab34f86f7fdbbb7b0421f7f9/src/java.base/share/classes/sun/reflect/annotation/AnnotationParser.java#L306)

**Comment by eginez** [comment]
fixed with https://github.com/oracle/graal/commit/9381ac96af8c45d71f2cff4f2de23e168b28bd26
