### ISSUE TITLE
Publish SHAs for GraalVM CE downloads

### ISSUE THREAD

**Issue by fcurts** [oracle/graal#2377]
I'd like to verify GraalVM downloads. I can find SHAs for EE but not for CE. Could you please publish CE SHAs as well?

**Comment by gilles-duboscq** [comment]
@ezzarghili / @soufianenassih can we add some hashes in the release descriptions (releases and dev builds). I suppose sha256 would work.

**Comment by soufianenassih** [comment]
sure will do.

**Comment by ezzarghili** [comment]
I would actually go with adding .sh256 companion files so this can be automation friendly.

**Comment by vkukk** [comment]
Any ETA for this?

**Comment by ezzarghili** [comment]
sha264 files will be available with releases starting next release.

**Comment by ezzarghili** [comment]
We have now a companion sha256 file each release artifact. see https://github.com/graalvm/graalvm-ce-builds/releases/tag/vm-20.3.0

**Comment by mjulianotq** [comment]
This is very helpful. Can you adjust the formatting of the file to work with `sha256sum`? Currently, I have to append the name of the graalvm-ce archive before that command works in my automation routine. Thanks in advance.

**Comment by fcurts** [comment]
Closing because obsolete (SHAs are now published).
