### ISSUE TITLE
Add callee-based filters to the tracing agent

### ISSUE THREAD

**Issue by sdeleuze** [oracle/graal#2381]
As [pointed out](https://graalvm.slack.com/archives/CN9KSFB40/p1587030771130700?thread_ts=1587026997.128900&cid=CN9KSFB40) by @shelajev on GraalVM Slack, the tracing agent currently only support  [caller-based filters](https://github.com/oracle/graal/blob/master/substratevm/CONFIGURE.md#caller-based-filters).

This issue is a feature request to add callee-based filters in order to be able to leverage GraalVM and Surefire Maven plugins to generate GraalVM configuration files (reflection, proxy and resource ones) via Maven configuration. We would like to leverage that in the next release of [Spring GraalVM native](https://github.com/spring-projects-experimental/spring-graal-native) support (agent and hybrid modes).

Few notes:
 - Since the goal is to use only Maven configuration, using bash based filtering is not an option hence the need for such feature
 - The support would be pretty similar to [caller-based filters](https://github.com/oracle/graal/blob/master/substratevm/CONFIGURE.md#caller-based-filters) currently supported
 - Such calle-based filters would be typically used to filter test related packages (or classes) like `org.junit.**`, `org.mockito.**` or `org.springframework.test.**`.

Thanks to tag this issue with the `spring` label.

**Comment by peter-hofer** [comment]
@sdeleuze , @sbrannen is #2422 what you had in mind?

**Comment by sdeleuze** [comment]
@peter-hofer Thanks, yes it looks like what I had in mind. Feel free to rename this issue and/or close it if needed.

**Comment by sbrannen** [comment]
Yes, I think that looks good. Thanks!
