### ISSUE TITLE
native-image fails on windows with command size limit (CreateProcess error=206)

### ISSUE THREAD

**Issue by Mobe91** [oracle/graal#2387]
I am using io.quarkus:quarkus-maven-plugin:1.3.2.Final and GraalVM CE 20.0.0 (Java 11) to build a native image on Windows 10 that issues to following command: 
```
native-image.cmd -J-DCoordinatorEnvironmentBean.transactionStatusManagerEnable=false -J-Dsun.nio.ch.maxUpdateArraySize=100 -J-Djava.util.logging.manager=org.jboss.logmanager.LogManager -J-Dvertx.logger-delegate-factory-class-name=io.quarkus.vertx.core.runtime.VertxLogDelegateFactory -J-Dvertx.disableDnsResolver=true -J-Dio.netty.leakDetection.level=DISABLED -J-Dio.netty.allocator.maxOrder=1 -J-Duser.language=de -J-Dfile.encoding=Cp1252 --initialize-at-build-time= -H:InitialCollectionPolicy=com.oracle.svm.core.genscavenge.CollectionPolicy$BySpaceAndTime -H:+JNI -jar quarkus-runner.jar -H:FallbackThreshold=0 -H:+ReportExceptionStackTraces -H:-AddAllCharsets -H:-IncludeAllTimeZones -H:EnableURLProtocols=http,https --enable-all-security-services -H:-UseServiceLoaderFeature -H:+StackTrace quarkus-runner
```
This in turn launches another command targeting java.exe but the -imagecp argument is way too long which is why it fails with "CreateProcess error=206, file name or extension too long".

The problem is caused by `https://github.com/oracle/graal/blob/00e729aa62e22646015f3051be7f3c1ae066ff01/substratevm/src/com.oracle.svm.driver/src/com/oracle/svm/driver/NativeImage.java#L1169`. Rather than concatenating all the paths and passing it to the command, this should generate a classpath jar and pass it instead. Alternatively, an args file could be used for Java 9+ as described [here](https://stackoverflow.com/a/54270831/412446).

**Describe GraalVM and your environment:**
 - GraalVM version: **CE 20.0.0**
 - JDK major version: **11**
 - OS: **Windows 10**
 - Architecture: **AMD64**

**Comment by quintesse** [comment]
I created a PR with a possible solution. Is that what you were looking for @Mobe91 ?
