### ISSUE TITLE
Extremely slow NPM actions on WSL2

### ISSUE THREAD

**Issue by williamhaw** [oracle/graal#2390]
**Describe the issue**
A clear and concise description of the issue. We recommend using the [latest snapshot builds](https://github.com/graalvm/graalvm-ce-dev-builds/releases) to replicate the issue as  bugs are constantly being fixed in the master branch

In the Ubuntu distro of WSL2, when using NPM/Node from GraalVM 20.0.0, NPM actions are much slower (3-5x) than using the installed NPM/Node. So far affected actions that I have tested are:
- `install`
- `test`
- `tsc`

**Steps to reproduce the issue**
Please include both build steps as well as run steps
1. git clone https://github.com/heroku/node-js-getting-started.git
2. cd node-js-getting-started
3. sdk use java 20.0.0.r11-grl
4. npm install (takes ~24 seconds)
5. rm -rf node_modules
6. sdk use java 11.0.7.hs-adpt
7. npm install (takes ~4 seconds) 

**Describe GraalVM and your environment:**
 - GraalVM version: 20.0.0 (20.0.0.r11-grl from sdkman)
 - JDK major version: 11
 - OS: Windows 10 (WSL2 Ubuntu)
 - Architecture: AMD64
 - Regular NodeJS version: 12.16.2
 - Regular NPM version: 6.14.4

**Comment by arielcarrera** [comment]
Graalvm's embedded node implementation works slow, impossible to have graalvm in the path and work with node.js using WSL2.

**Comment by williamhaw** [comment]
The source files were inside the WSL 2 file system. When using GraalVM’s node executable on Mac, there is no slowdown.

**Comment by fernando-valdez** [comment]
Please let me know if this issue still happens in the latest snapshot
