### ISSUE TITLE
Results of AnnotatedElement.getDeclaredAnnotations() can be an array with null entries

### ISSUE THREAD

**Issue by aclement** [oracle/graal#2405]
**Describe the issue**
With either the recent 20.1 graal dev release build or master (commit 78f22e7892) some of the Spring samples have started failing (notably webflux-netty). This appears to be due to a call to `AnnotatedElement.getDeclaredAnnotations()` made on a spring `RestController` annotation type returning an array with null entries:
```
annotation number 0 is @java.lang.annotation.Retention
annotation number 1 is null
annotation number 2 is null
annotation number 3 is @java.lang.annotation.Target
```
when it previously returned:
```
annotation number 0 is @java.lang.annotation.Target
annotation number 1 is @java.lang.annotation.Retention
annotation number 2 is @org.springframework.stereotype.Controller
annotation number 3 is @org.springframework.web.bind.annotation.ResponseBody
```

Esteban thought it might be related to fix for #2243

Code is tripping up over the null entries.

**Steps to reproduce the issue**
```
git clone git@github.com:spring-projects-experimental/spring-graal-native.git
cd spring-graal-native
./build.sh
cd spring-graal-native-samples/webflux-netty
./build.sh
```
**Describe GraalVM and your environment:**
- Graal 20.1 dev build (20200419) or master ( commit 78f22e7892)
- JDK8
- MacOS Catalina

**More details**
The spring app will fail with messages like this:
```
2020-04-27 08:25:16.496  INFO 56025 --- [ctor-http-nio-2] o.s.core.annotation.MergedAnnotation     : Failed to introspect annotations on class com.example.demo.DemoApplication$Foo: java.lang.NullPointerException
```
But the NPE is caused by tripping over the nulls in the array shown above.

**Comment by eginez** [comment]
should have been fixed with https://github.com/oracle/graal/commit/26fdc9cbbdbb29110f0ffeb53f1dd818928974b3
