### ISSUE TITLE
Truffle DSL: Excess parameters to execute methods are ignored

### ISSUE THREAD

**Issue by arthurp** [oracle/graal#242]
It appears that under some circumstances excess arguments in the signature of an abstract `execute` method (to be implemented by the NodeGen) are totally ignored. This seems like it's probably a bug since in other cases an error is produced for the excess arguments.

For example, the following code compiles fine. The generated implementations of `executeWeird` calls `run` (with a type check and cast as expected), but never even references the `v` argument to `executeWeird` silently dropping it.
```java
@NodeChild(value = "value", type = TestNode.class)
public abstract class TestNode extends Node {
	public abstract Object execute(VirtualFrame frame);

	abstract Object executeWeird(VirtualFrame frame, Object value, Object v);

	@Specialization
	public Object run(VirtualFrame frame, int value) {
		return value;
	}
}
``` 

However, if the `value` argument is type `int` then I get an error as I would kind of expect:
```java
@NodeChild(value = "value", type = TestNode.class)
public abstract class TestNode extends Node {
	public abstract Object execute(VirtualFrame frame);

	abstract Object executeWeird(VirtualFrame frame, int value, Object v);

	@Specialization
	public Object run(VirtualFrame frame, int value) {
		return value;
	}
}
```
Error:
```
Incompatible abstract execute methods found [Object execute(VirtualFrame,[])].
```

All of this is on the version of the Truffle DSL that comes with GraalVM 0.26.

**Comment by arthurp** [comment]
PS: @eregon told me to cc @chumer. So I'm mentioning both of you.

**Comment by chumer** [comment]
Thanks for the report.

Excess arguments in execute signatures are ignored on purpose. This makes it easier to share the execute signature in the base node with varying number of specialization parameters in subclasses.

The second error however is wrong. I think these execute signatures should be accepted. Will investigate.

**Comment by boris-spas** [comment]
Tracked internally as GR-20788.

**Comment by alina-yur** [comment]
@chumer @boris-spas I would assume this can be closed?
