### ISSUE TITLE
Substitution for ClassValue#get cannot handle null

### ISSUE THREAD

**Issue by rsteppac** [oracle/graal#2421]
**Describe the issue**
I am trying to build a service as a native image that utilizes Apache WSS4J. WSS4J's `org.apache.wss4j.dom.util.WSSecurityUtil` implements a `java.lang.ClassValue<Method>` with an implementation of `java.lang.ClassValue#computeValue` that may return `null`. This causes an NPE in GraalVM's substitute `Target_java_lang_ClassValue`, which stores the result of `computeValue` in a `ConcurrentHashMap`, which does not allow `null` as key or value.

**Describe GraalVM and your environment:**
 - GraalVM version: GraalVM Version 20.0.0 CE
 - JDK major version: 11
 - OS: Linux Mint 19.3 Tricia
 - Architecture: AMD64

**More details**
WSS4J's implementation of ClassValue<Method>:
```
    private static final ClassValue<Method> GET_DOM_ELEMENTS_METHODS = new ClassValue<Method>() {
        @Override
        protected Method computeValue(Class<?> type) {
            try {
                return getMethod(type, "getDomElement");
            } catch (NoSuchMethodException e) {
                //best effort to try, do nothing if NoSuchMethodException
                return null;
            }
        }
    };
```
Substitution of `ClassValue#get` in GraalVM

```
    @Substitute
    private Object get(Class<?> type) {
        Object result = values.get(type);
        if (result == null) {
            Object newValue = computeValue(type);
            Object oldValue = values.putIfAbsent(type, newValue);
            result = oldValue != null ? oldValue : newValue;
        }
        return result;
    }
```
`values` is of type `ConcurrentHashMap`. Executing the WSS4J code for a type like `com.sun.org.apache.xerces.internal.dom.ElementNSImpl` yields an NPE:
```
java.lang.NullPointerException
	at java.util.concurrent.ConcurrentHashMap.putVal(ConcurrentHashMap.java:1011)
	at java.util.concurrent.ConcurrentHashMap.putIfAbsent(ConcurrentHashMap.java:1541)
	at java.lang.ClassValue.get(JavaLangSubstitutions.java:509)
	at org.apache.wss4j.dom.util.WSSecurityUtil.getDomElement(WSSecurityUtil.java:699)
	at org.apache.wss4j.dom.util.WSSecurityUtil.prependChildElement(WSSecurityUtil.java:370)
	at org.apache.wss4j.dom.util.WSSecurityUtil.findWsseSecurityHeaderBlock(WSSecurityUtil.java:497)
	at org.apache.wss4j.dom.message.WSSecHeader.insertSecurityHeader(WSSecHeader.java:167)
...
```

**Comment by jaikiran** [comment]
FWIW - The javadoc (contract of the) `ClassValue#get` API does state[1] that this method is expected to throw a `NullPointerException` if the passed parameter is `null` (as in this case). So it does appear to be behaving as expected.

[1] https://docs.oracle.com/javase/8/docs/api/java/lang/ClassValue.html#get-java.lang.Class-

**Comment by rsteppac** [comment]
The argument, i.e. the type, is not `null`. In the WSS4J case it is a type that does not declare a method `getDomElement`. WSS4J's implementation of `computeValue(Class<?> type)` then returns null, which causes the NPE in the substituted `get(Class<?> type)`.

**Comment by jaikiran** [comment]
Thank you for clarifying that. I now see what you mean.
