### ISSUE TITLE
Truffle DSL Documentation: Undocumented features

### ISSUE THREAD

**Issue by arthurp** [oracle/graal#243]
I have encountered two DSL behaviors that are not documented and in one case could be really confusing for a user. They should probably be documented.

Both these features seem to be used in code I have seen or be in the Truffle test suite.

### NodeFields are passed as arguments to specializations
Specialization methods can have additional parameters **before** the NodeChild "dynamic input" parameters. If present these parameters are filled from the NodeFields of the class. 

This is particularly surprising when a NodeField has the same type as a specialized input parameter. For example, in the following code `run1` will receive the result of the `value` child as `a`, but `run2` will receive the `test` field as `a`.
```java
@NodeChild(value = "value", type = TestNode.class)
@NodeField(name = "test", type = int.class)
public abstract class TestNode extends Node {
	@Specialization
	public Object run1(int a) {
		return a;
	}
	
	@Specialization
	public Object run2(int a, int b) {
		return a;
	}
}
```

### NodeChild accepts array types as `type`
When an array type is passed to NodeChild it seems to generate code where the number of values in the array is assumed to be a fixed value set by the number of arguments accepted by the Specialization methods. This is rather confusing for code like this:
```java
@NodeChild(value = "value", type = TestNode[].class)
public abstract class TestNode extends Node {
	@Specialization
	public Object run(Object[] a) {
		return a;
	}
}
```
This code will execute the element 0 of the `TestNode[]` array which was passed as value and then attempt to cast the result to `Object[]`. All the other elements of the array are ignored and if the array is empty then the generated code will NPE at runtime. A getter for an array child also behaves strangely, returning an array of exactly the size defined by the Specialization methods regardless of the array passed in.

Note: All of the annotation processing to figure out what these do was done on the processor which comes with GraalVM 0.26.

**Comment by chumer** [comment]
I plan to deprecate @NodeField for these reasons. They make the code hard to understand. Using the @NodeField annotation is by no means easier than to just pass the field using the constructor into a final field (which is the way I would recommend it).

Using arrays in @NodeChild is indeed not properly documented. Its rational is similar to the ignored parameters in execute signatures (its like varargs for nodes). So only the number of dynamic specialization parameters are executed from the child node array. In case of child arrays ignoring trailing nodes might not be ideal and should probably be verified in the constructor.

**Comment by boris-spas** [comment]
Tracking internally as GR-20789.
