### ISSUE TITLE
`jaotc` missing from download

### ISSUE THREAD

**Issue by jendrikw** [oracle/graal#2432]
If I interpret https://openjdk.java.net/jeps/295 correctly, a JDK build should have a `jaotc` tool. It seems like that's missing from the GraalVM 20.0.0 amd64 linux build at https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-20.0.0/graalvm-ce-java11-linux-amd64-20.0.0.tar.gz.

**Comment by solaanan** [comment]
Hi @jendrikw, please choose one of the templates mentioned in [this link](https://github.com/oracle/graal/issues/new/choose) that corresponds to your needs. Thank you!
