### ISSUE TITLE
object files can't be inspected with nm/otool/objdump

### ISSUE THREAD

**Issue by johanvos** [oracle/graal#2435]
**Describe the issue**
object files generated by native-image for Darwin can not be inspected with tools like nm, otool or objdump, since the headers are not set correctly:

nm: error: hello.helloworld.o truncated or malformed object (load command 0 filesize field in LC_SEGMENT_64 greater than vmsize field)

**Steps to reproduce the issue**
`native-image -H:+ExitAfterRelocatableImageWrite -H:+SharedLibrary hello.HelloWorld` generates the object file that can't be inspected with `nm`

**Describe GraalVM and your environment:**
master

**Comment by loicottet** [comment]
Fixed by [4128b8ab](https://github.com/oracle/graal/commit/4128b8ab5a776731dcaf350dfb0198cae9ca1a53)
