### ISSUE TITLE
Support alias of super-class methods in substitutions

### ISSUE THREAD

**Issue by sdeleuze** [oracle/graal#2458]
While working on Spring support for GraalVM native, I found a blocking limitation in substitutions. It seems currently not supported to create an alias for a method invoking a method originally defined in a super class.

It is annoying when the said method is long, and it is blocking when for example your want to access a private field via a public/protected/package private getter. Most of my use case are substitutions to remove some code in order to reduce the memory footprint (typically XML support).

If you consider following code:

```
public class Foo extends Bar {
	public Foo() {
		method1();
		method2();
	}
}

public class Bar {
	public void method1() {
		// ...
	}
	public void method2() {
		// ...
	}
}

@TargetClass(className = "Foo")
public final class Target_Foo {
	@Substitute
	public Target_Foo() {
		method2();
	}
	@Alias
	public void method2() {
	}
}
```

It currently fails (tested with 20.1 branch) with following error:

```
Error: could not find target method: public void Target_Foo.method2()
com.oracle.svm.core.util.UserError$UserException: could not find target method: public void Target_Foo.method2()
	at com.oracle.svm.core.util.UserError.abort(UserError.java:68)
	at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.findOriginalMethod(AnnotationSubstitutionProcessor.java:637)
	at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.handleMethodInAliasClass(AnnotationSubstitutionProcessor.java:330)
	at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.handleAliasClass(AnnotationSubstitutionProcessor.java:302)
	at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.handleClass(AnnotationSubstitutionProcessor.java:274)
	at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.init(AnnotationSubstitutionProcessor.java:230)
	at com.oracle.svm.hosted.NativeImageGenerator.createDeclarativeSubstitutionProcessor(NativeImageGenerator.java:908)
```

I would expect such substitution works as expected, like it does when all methods are defined in the same class.

Please tag this issue with the `spring` label.

**Comment by eginez** [comment]
@sdeleuze can you points us to a concrete use case of this new feature how you would use it in the context of spring?

**Comment by christianwimmer** [comment]
I don't understand entirely what you are trying to do. But on first glance, it seems like you want to make a `@Alias` to a method in `Bar`, which means you need a `TargetClass` for `Bar`.

You cannot model a class hierarchy of target classes. But you can freely cast between them. So when you have a `Target_Foo` and a `Target_Bar`, then you can cast a `Target_Foo` instance to a `Target_Bar` without the possibility for a `ClassCastException` at run time. In fact, these casts will be removed by the AOT compiler.

**Comment by christianwimmer** [comment]
And for all issues and requests like this I want to point out that you should use substitutions as little as possible, because they lead to code that is difficult to maintain.

**Comment by essobedo** [comment]
I've just faced a similar issue and confirm that the approach described by @christianwimmer did the trick, thank you very much 🙏 

For this particular case, here is the code that works:

```
@TargetClass(Foo.class)
final class Target_Foo {
    @Substitute
    public Target_Foo() {
        ((Target_Bar) (Object) this).method2();
    }
}

@TargetClass(Bar.class)
final class Target_Bar {

    @Alias
    public void method2() {
    }
}
```

**Comment by wirthi** [comment]
Solution was given above, no additional request for several years. Closing this ticket.
