### ISSUE TITLE
Improve the Page response for the user(Page components overlap)

### ISSUE THREAD

**Issue by rohits06oct** [oracle/graal#2460]
**Feature request**

This page https://www.graalvm.org/docs/examples/ Components are overloaded because of this ```(class="sidebar")```
If you scroll up and scroll down then you get to know the sidebar component is overlap with the footer.
please improve the page for the user experience.
<img width="1154" alt="Screenshot 2020-05-14 at 10 41 59 PM" src="https://user-images.githubusercontent.com/49077126/81964524-54006800-9634-11ea-887c-c31f7f94506f.png">

**Comment by selhagani** [comment]
Thank you for the suggestion! This is no longer an issue with the new design of the website.
