### ISSUE TITLE
Error when building jdk "test-image-hotspot-jtreg-graal"after "mx updategraalinopenjdk".

### ISSUE THREAD

**Issue by XiaohongGong** [oracle/graal#2463]
**Describe the issue**
Building jdk image `test-image-hotspot-jtreg-graal` reports error after updating the latest `graal/compiler` by running `mx updategraalinopenjdk`. 

Here is the error log: 
 
```
jdk_src/src/jdk.internal.vm.compiler/share/classes/org.graalvm.compiler.hotspot.test/src/org/graalvm/compiler/hotspot/test/VerifyJNILibGraalScope.java:35: error: package jdk.internal.vm.compiler.libgraal.jni does not exist
import jdk.internal.vm.compiler.libgraal.jni.JNILibGraalScope;
                                                ^
```

Package `jdk.internal.vm.compiler.libgraal.jni` is not generated in JDK code, but it is used in the package `org.graalvm.compiler.hotspot.test` which will be updated in JDK. 

So could test `VerifyJNILibGraalScope.java` be removed to other module that is in the excluded list when updating graal in openjdk?

**Steps to reproduce the issue**
Please include both build steps as well as run steps

    1.  cd graal/compiler & mx updategraalinopenjdk jdk_src 15
    2.  cd jdk_src & ./configure [options] & make images & make test-image-hotspot-jtreg-graal

**Describe GraalVM and your environment:**
 - GraalVM commit id if built from source: **master**
 - JDK major version: **[15]**
 - OS: **[linux]**
 - Architecture: **[AMD64, AArch64]**

**More details**
Codes created by:
```
    commit 34e0ba1fd63caefd9551b67be58bfea143df42e7
    support libgraal with multiple JVMCI runtimes
```

**Comment by dougxc** [comment]
Thanks for reporting. Fix is in the pipeline.

**Comment by XiaohongGong** [comment]
Thank you so much!

**Comment by dougxc** [comment]
Should be fixed by https://github.com/oracle/graal/commit/052a7d097d93650a7555ed1118ed0a3f660744af - please re-open if not.
