### ISSUE TITLE
Question about truffle implementation with lightweight "contexts"

### ISSUE THREAD

**Issue by mikera** [oracle/graal#247]
Hello,

Thanks for the Truffle / Graal project - it seems very interesting!

I'm experimenting with a JVM Lisp (https://github.com/mikera/magic) and wondering if Truffle / Graal can be used as a compiler.

I have a few things that need to fit:
1. I have a custom set of AST nodes that represent analysed code. I believe these can extend the Truffle Rootnode
2. AST nodes may have either resolved or unresolved dependencies, meaning that analysis must be repeated if definition change and/or lazily compiled later
3. All compilation happens within a `Context` which is a custom, lightweight, immutable definition of the language environment including all definitions.
4. Contexts can be fully erased once compilation is complete, but are needed during code loading / interpretation, during macro expansion and for arbitrary `eval` operations
5. There is a custom type system, which also depends on the definitions held within a `Context`

Would this be a good fit for Truffle? If so any pointers on how to make the Contexts work in particular?

**Comment by smarr** [comment]
> I have a custom set of AST nodes that represent analysed code. I believe these can extend the Truffle Rootnode

Normally, AST nodes simply extend the `Node` class. `RootNode` is specifically for the root of a function/method. So, if you haven't specific needs to treat functions in various different ways, which is very rare, that's probably not the node you need.

> AST nodes may have either resolved or unresolved dependencies, meaning that analysis must be repeated if definition change and/or lazily compiled later

Truffle has the concept of [`Assumptions`](http://graalvm.github.io/graal/truffle/javadoc/com/oracle/truffle/api/Assumption.html). These can be invalidated. So, if a node [specialization](http://graalvm.github.io/graal/truffle/javadoc/com/oracle/truffle/api/dsl/Specialization.html) depends on it, it can be globally invalidated to force rechecking invariants, for instance after code loading or similar operations that change definitions.

I am not sure where the complexity of your `Context` lies, but Truffle should not prevent to model a language like that. However, it seems to be a bit outside of what Truffle covers. In the sense, that it doesn't provide a mechanism specifically for your needs. Note however, that Truffle has its own notion of [`Context`](http://graalvm.github.io/graal/truffle/javadoc/com/oracle/truffle/api/TruffleContext.html).

If you haven't seen it already, here is the overview on how to start new languages with Truffle:
http://graalvm.github.io/graal/truffle/javadoc/com/oracle/truffle/tutorial/newlanguage/package-summary.html

And, I got another list with material as well as languages here, which also includes another Lisp (Mumbler): https://gist.github.com/smarr/d1f8f2101b5cc8e14e12
On the [Gitter channel](https://gitter.im/graalvm/graal-core), there is also someone implementing a Shen.

**Comment by dougxc** [comment]
@mikera , please re-open if your questions have not been answered.
