### ISSUE TITLE
cross-compilation not possible unless using LLVM backend

### ISSUE THREAD

**Issue by johanvos** [oracle/graal#2476]
There is currently a hard check on using the LLVM backend in order to be able to do cross compilation (e.g. from Linux AMD64 to Android Aarch64).

A check in NativeImageGenerator will verify if the host compiler is suitable for the target unless all following conditions are satisfied
* the backend is LLVM
* NativeImageOptions.ExitAfterRelocatableImageWrite is set
* A CAP cache is used

The last 2 checks are probably sufficient for not doing the compiler check.

**Comment by loicottet** [comment]
Fixed by [5471ed3](https://github.com/oracle/graal/commit/5471ed3f59b74c2b84f997f9514772581b342e15)
