### ISSUE TITLE
java.lang.UnsatisfiedLinkError:  java.lang.UnsatisfiedLinkError: sun.security.smartcardio.PCSC.SCardListReaders

### ISSUE THREAD

**Issue by Azimuts** [oracle/graal#2488]
**Describe the issue**

```
Exception in thread "main" java.lang.UnsatisfiedLinkError: sun.security.smartcardio.PCSC.SCardListReaders(J)[Ljava/lang/String; [symbol: Java_sun_security_smartcardio_PCSC_SCardListReaders or Java_sun_security_smartcardio_PCSC_SCardListReaders__J]
        at com.oracle.svm.jni.access.JNINativeLinkage.getOrFindEntryPoint(JNINativeLinkage.java:145)
        at com.oracle.svm.jni.JNIGeneratedMethodSupport.nativeCallAddress(JNIGeneratedMethodSupport.java:57)
        at sun.security.smartcardio.PCSC.SCardListReaders(PCSC.java)
        at sun.security.smartcardio.PCSCTerminals.list(PCSCTerminals.java:80)
        at javax.smartcardio.CardTerminals.list(CardTerminals.java:72)

```

**Just a simple code with access to smartcard.io** 

import javax.smartcardio.CardTerminal;
import javax.smartcardio.CardTerminals;
import javax.smartcardio.TerminalFactory;

public class SmartCardSample {

	public static void getReaders() throws Exception {
        try {
            TerminalFactory fac = TerminalFactory.getDefault();
            CardTerminals terminals = fac.terminals();
            List<CardTerminal> list = terminals.list();
            if (list != null) {
                System.out.println("Number of terminals: " + list.size());
            } else {
                System.out.println("List is null.");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
				
	public static void main(String[] args) {
        try {
            while (true) {
                getReaders();
                BufferedReader reader = new BufferedReader(new InputStreamReader(System.in));
                System.out.println("Press enter to continue.");
                reader.readLine(); //wait until user press entesr
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }	
}

**Describe GraalVM and your environment:**
 -**GraalVM version** 

-  openjdk version "1.8.0_242"
- OpenJDK Runtime Environment (build 1.8.0_242-b06)
- OpenJDK 64-Bit Server VM GraalVM CE 20.0.0 (build 25.242-b06-jvmci-20.0-b02, mixed mode)

 - JDK major version: *** :  8
 - OS: ****    Windows
 - Architecture: **** AMD64.

```

**Comment by Azimuts** [comment]
Shared sample code at   https://github.com/Azimuts/graalcardreader

After loading manually the library  j2pcsc  () + adding java.library.path () to native image   :

SmartCard -Djava.library.path=C:\\develop\graalvm\graalvm-ce-java8-20.0.0/jre/bin/

i get this new error: javax.smartcardio.CardException:  Caused by: ### sun.security.smartcardio.PCSCException: WINDOWS_ERROR_INVALID_HANDLE

The code works fine as a java program with the graalvm  (and withour manually loading of library j2pcsc  ), but no way to get a working native image

**Comment by Azimuts** [comment]
Hi. @dougxc  @peter-hofer  is this a known bug ? Is there any workaround? " "To do in Native Image via automation" what does it means?    Thank you in advance!!! 

I see deepinng in the sdk code that " j2pcsc" ddl library is loaded via a static initializer ... and this static initializer also is loaded via spi, providers, reflection... 
 1. SunPSC loads a terminal factory  via spi provider
 2. The factoy calls to a CardTerminal wich has the static initializer.

**Comment by dougxc** [comment]
"To do in Native Image via automation" seems to be the message that GitHub adds automatically when an issue is added to a Project on the right.

**Comment by peter-hofer** [comment]
`SCardListReaders` has a single parameter that is an operating system handle that is used to query the readers, and throws an exception with a Windows-specific error code that the handle is invalid. I'm assuming that `PCSCTerminals.initContext()`, which initializes that handle, is called during image generation and the handle is included in the image, but of course no longer valid at runtime.

You can try delay initialization of the PCSC classes to runtime if that's possible (see https://medium.com/graalvm/updates-on-class-initialization-in-graalvm-native-image-generation-c61faca461f7 ) or to manually reset the pre-initialized static variables, using reflection, for example. Please let us know if that helps.

**Comment by wimdeblauwe-volvo** [comment]
Did you get this working? If so, how exactly?
