### ISSUE TITLE
A typo in graalvm 'getting-started' page

### ISSUE THREAD

**Issue by ty5491003** [oracle/graal#2494]
On https://www.graalvm.org/docs/getting-started/linux page, i see:

> Navigate to the GraalVM Releases repository on GitHub. Depending on the workload, select **graalvm-ce-java8-linux-amd64-20.1.0.tar.gz** or **graalvm-ce-java8-linux-amd64-20.1.0.tar.gz** and download. We will focus on GraalVM Community based on OpenJDK 8.

The two bold parts are exactly the same, i think it's a typo.

**Comment by olyagpl** [comment]
@ty5491003, thank you for catching.
Updated https://www.graalvm.org/docs/getting-started/linux
