### ISSUE TITLE
JDK build error with "mx updategraalinopenjdk" due to "SPARC" jvmci is missing

### ISSUE THREAD

**Issue by XiaohongGong** [oracle/graal#2498]
**Describe the issue**
Updating the graal master in jdk/jdk master by running "mx updategraalinopenjdk", and building jdk fails with error, due to:
```
package jdk.vm.ci.sparc does not exist
```

Since jdk/jdk has removed the SPARC ports (See https://bugs.openjdk.java.net/browse/JDK-8244224), is there any plan for "SPARC" in Graal compiler to make it compatible with jdk/jdk? At least, the sparc packages/modules should be excluded from the update list?

**Steps to reproduce the issue**
Please include both build steps as well as run steps
```
1.  cd graal/compiler & mx updategraalinopenjdk jdk_src 15
2.  cd jdk_src & ./configure [options] & make images
```

**Describe GraalVM and your environment:**
 - GraalVM commit id if built from source: **master**
 - JDK major version: **[e.g.:11]**
 - OS: **[linux]**
 - Architecture: **[all]**

**More details**
Add any other information about the problem here. Especially important are stack traces or log output. Feel free to link to gists or to screenshots if necessary.
```
    PASTE YOUR LOG/STACK TRACE HERE
```

**Comment by XiaohongGong** [comment]
Build `graal/compiler` with the` jdk/jdk` also reports this error.

**Comment by dougxc** [comment]
Thanks @XiaohongGong. We're aware of this problem and are working to address it. (cc @dean-long @vnkozlov )

**Comment by XiaohongGong** [comment]
It's very well that it's in the addressing schedule! Thanks so much!
