### ISSUE TITLE
native-image shell script requires a modded JDK to work.

### ISSUE THREAD

**Issue by zakkak** [oracle/graal#2502]
**Describe the issue**
When building Graal bits for use with openJDK, `native-image` needs to pass the following arguments to the jvm `--upgrade-module-path ${location}/../../jvmci/graal.jar --add-modules "org.graalvm.truffle,org.graalvm.sdk" --module-path ${location}/../../truffle/truffle-api.jar:${location}/../../jvmci/graal-sdk.jar` and `-J--add-exports=jdk.internal.vm.ci/jdk.vm.ci.code=jdk.internal.vm.compiler` to native-image.

**Steps to reproduce the issue**
Please include both build steps as well as run steps:
```
curl -sL https://github.com/AdoptOpenJDK/openjdk11-upstream-binaries/releases/download/jdk-11.0.9%2B2/OpenJDK11U-jdk_x64_linux_11.0.9_2_ea.tar.gz -o jdk.tar.gz
curl -sL https://github.com/AdoptOpenJDK/openjdk11-upstream-binaries/releases/download/jdk-11.0.9%2B2/OpenJDK11U-static-libs_x64_linux_11.0.9_2_ea.tar.gz -o jdk-static-libs.tar.gz
mkdir -p openjdk
tar xf jdk.tar.gz -C openjdk --strip-components=1
tar xf jdk-static-libs.tar.gz -C openjdk --strip-components=1
export JAVA_HOME=$(pwd)/openjdk
git clone --depth 1 https://github.com/oracle/graal
pushd graal/substratevm
mx --components="Native Image" build
popd

export GRAAL_REPO=./graal
export MANDREL_JDK=./mandrel

cp -r ${JAVA_HOME} ${MANDREL_JDK}

mkdir ${MANDREL_JDK}/lib/svm
cp ${GRAAL_REPO}/substratevm/mxbuild/dists/jdk1.8/library-support.jar ${MANDREL_JDK}/lib/svm

mkdir ${MANDREL_JDK}/lib/svm/builder
cp ${GRAAL_REPO}/substratevm/mxbuild/dists/jdk11/{svm,pointsto}.jar ${MANDREL_JDK}/lib/svm/builder
cp ${GRAAL_REPO}/substratevm/mxbuild/dists/jdk1.8/objectfile.jar ${MANDREL_JDK}/lib/svm/builder

mkdir ${MANDREL_JDK}/languages
cp ${GRAAL_REPO}/truffle/mxbuild/dists/jdk11/truffle-nfi.jar ${MANDREL_JDK}/languages

mkdir ${MANDREL_JDK}/lib/graalvm
cp ${GRAAL_REPO}/substratevm/mxbuild/dists/jdk1.8/svm-driver.jar ${MANDREL_JDK}/lib/graalvm

mkdir ${MANDREL_JDK}/lib/jvmci
cp ${GRAAL_REPO}/sdk/mxbuild/dists/jdk11/graal-sdk.jar ${MANDREL_JDK}/lib/jvmci
cp ${GRAAL_REPO}/compiler/mxbuild/dists/jdk11/graal.jar ${MANDREL_JDK}/lib/jvmci

mkdir ${MANDREL_JDK}/lib/truffle
cp ${GRAAL_REPO}/truffle/mxbuild/dists/jdk11/truffle-api.jar ${MANDREL_JDK}/lib/truffle

mkdir -p ${MANDREL_JDK}/lib/svm/clibraries/linux-amd64/include
cp ${GRAAL_REPO}/substratevm/src/com.oracle.svm.native.libchelper/include/amd64cpufeatures.h ${MANDREL_JDK}/lib/svm/clibraries/linux-amd64/incl
ude
cp ${GRAAL_REPO}/substratevm/src/com.oracle.svm.native.libchelper/include/aarch64cpufeatures.h ${MANDREL_JDK}/lib/svm/clibraries/linux-amd64/in
clude
cp ${GRAAL_REPO}/substratevm/src/com.oracle.svm.libffi/include/svm_libffi.h ${MANDREL_JDK}/lib/svm/clibraries/linux-amd64/include
cp ${GRAAL_REPO}/truffle/src/com.oracle.truffle.nfi.native/include/trufflenfi.h ${MANDREL_JDK}/lib/svm/clibraries/linux-amd64/include
cp ${GRAAL_REPO}/substratevm/mxbuild/linux-amd64/src/com.oracle.svm.native.libchelper/amd64/liblibchelper.a ${MANDREL_JDK}/lib/svm/clibraries/l
inux-amd64
cp ${GRAAL_REPO}/substratevm/mxbuild/linux-amd64/src/com.oracle.svm.native.jvm.posix/amd64/libjvm.a ${MANDREL_JDK}/lib/svm/clibraries/linux-amd
64

mkdir ${MANDREL_JDK}/lib/svm/bin
cp ${GRAAL_REPO}/sdk/mxbuild/linux-amd64/native-image.image-bash/native-image ${MANDREL_JDK}/lib/svm/bin/native-image

ln -s ../lib/svm/bin/native-image ${MANDREL_JDK}/bin/native-image

./mandrel/bin/native-image -version
```

Note that the `cp` commands just copy graalvm bits in the openjdk filesystem adding them where `native-image` expects to find them.

**Describe GraalVM and your environment:**
 - GraalVM version: **16a2a120ee3f23eab2ec4b58335f5339c5ac5cf4**
 - JDK major version: **11**
 - OS: **Linux**
 - Architecture: **AMD64**

**More details**
```
./mandrelJDK/bin/native-image --native-image-info --verbose HelloWorld
Exception in thread "main" java.lang.NoClassDefFoundError: org/graalvm/word/UnsignedWord
        at com.oracle.svm.driver.NativeImage.getPlatform(NativeImage.java:104)
        at com.oracle.svm.driver.NativeImage.<clinit>(NativeImage.java:101)
        at com.oracle.svm.driver.NativeImage$JDK9Plus.main(NativeImage.java:1753)
Caused by: java.lang.ClassNotFoundException: org.graalvm.word.UnsignedWord
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        ... 3 more
```

Applying the following patch to `./mandrelJDK/lib/svm/bin/native-image` makes it work.

```diff
diff --git a/graal/sdk/mxbuild/linux-amd64/native-image.image-bash/native-image b/mandrel/lib/svm/bin/native-image
index 992d85b..11d365a 100755
--- a/graal/sdk/mxbuild/linux-amd64/native-image.image-bash/native-image
+++ b/mandrel/lib/svm/bin/native-image
@@ -108,4 +108,4 @@ if [[ "${VERBOSE_GRAALVM_LAUNCHERS}" == "true" ]]; then
     set -x
 fi
 
-exec "${location}/../../../bin/java" --add-exports=java.base/jdk.internal.module=ALL-UNNAMED -XX:+UnlockExperimentalVMOptions -XX:+EnableJVMCI "${jvm_args[@]}" -cp "${cp}" 'com.oracle.svm.driver.NativeImage$JDK9Plus' "${launcher_args[@]}"
+exec "${location}/../../../bin/java" --upgrade-module-path ${location}/../../jvmci/graal.jar --add-modules "org.graalvm.truffle,org.graalvm.sdk" --module-path ${location}/../../truffle/truffle-api.jar:${location}/../../jvmci/graal-sdk.jar --add-exports=java.base/jdk.internal.module=ALL-UNNAMED -XX:+UnlockExperimentalVMOptions -XX:+EnableJVMCI "${jvm_args[@]}" -cp "${cp}" 'com.oracle.svm.driver.NativeImage$JDK9Plus' -J--add-exports=jdk.internal.vm.ci/jdk.vm.ci.code=jdk.internal.vm.compiler "${launcher_args[@]}"
```

Results after patch:
```
$ ./mandrel/bin/native-image HelloWorld                                
[helloworld:238051]    classlist:   1,176.86 ms,  1.00 GB
[helloworld:238051]        (cap):     627.54 ms,  1.00 GB
[helloworld:238051]        setup:   1,760.69 ms,  1.58 GB
[helloworld:238051]     (clinit):     222.38 ms,  1.92 GB
[helloworld:238051]   (typeflow):   4,243.92 ms,  1.92 GB
[helloworld:238051]    (objects):   3,886.14 ms,  1.92 GB
[helloworld:238051]   (features):     219.58 ms,  1.92 GB
[helloworld:238051]     analysis:   8,828.33 ms,  1.92 GB
[helloworld:238051]     universe:     319.31 ms,  1.92 GB
[helloworld:238051]      (parse):     922.83 ms,  1.92 GB
[helloworld:238051]     (inline):   1,381.27 ms,  2.42 GB
[helloworld:238051]    (compile):   7,252.56 ms,  2.42 GB
[helloworld:238051]      compile:   9,986.78 ms,  2.42 GB
[helloworld:238051]        image:   1,291.74 ms,  2.42 GB
[helloworld:238051]        write:     156.78 ms,  2.42 GB
[helloworld:238051]      [total]:  23,738.09 ms,  2.42 GB

$ ./helloworld 
Hello world!!!
```

**Comment by zakkak** [comment]
What would be the best way to get the flags there without disrupting other use cases?

**Comment by olpaw** [comment]
@zakkak is this still relevant? Can you still reproduce this problem?

**Comment by olpaw** [comment]
`/../graal/sdk/mxbuild/linux-amd64/native-image.image-bash/native-image` is a bash-launcher for the native-image program (in production native-image is itself compiled to a native image but as part of bootstrapping we also run it as bash-launcher. The generation of such bash launchers is performed by mx. See https://github.com/oracle/graal/blob/master/sdk/mx.sdk/vm/launcher_template.sh

**Comment by zakkak** [comment]
Hi @olpaw,

This is still relevant, but the instructions were outdated. I have now updated the steps to reproduce the issue.

In Mandrel we rely on the bash-launcher for the production native-image as well. Till now the only major difference we have noticed is the lack of the image build server when using the launcher. Are there any other differences you can think of that we should be aware of?

Would patching https://github.com/oracle/graal/blob/master/sdk/mx.sdk/vm/launcher_template.sh to include the additional parameters that we need be OK with graal? Do you foresee any implications?

Thanks

**Comment by olpaw** [comment]
> Would patching https://github.com/oracle/graal/blob/master/sdk/mx.sdk/vm/launcher_template.sh to include the additional
> parameters that we need be OK with graal? Do you foresee any implications?

Hmm, I guess so. Do you agree @dougxc ?

**Comment by dougxc** [comment]
Sorry, I'm rusty on launcher_template.sh so I leave that call up to you Paul.

**Comment by olpaw** [comment]
@zakkak I see no problems with making the launcher template mechanism flexible enough to suite your needs.
Keep in mind that we also need to support Windows. So whatever you add should also work with https://github.com/oracle/graal/blob/master/sdk/mx.sdk/vm/launcher_template.cmd (or at least not break it). The instantiations of those templates happens via `GraalVmBashLauncherBuildTask`. See https://github.com/oracle/graal/blob/master/sdk/mx.sdk/mx_sdk_vm_impl.py#L1719
cc @ansalond

**Comment by ansalond** [comment]
If I understand correctly, the underlying issue is that you are packaging things differently. For example, in Mandrel `org.graalvm.word.UnsignedWord` is part of `lib/jvmci/graal-sdk.jar` while in GraalVM it is part of `jmods/org.graalvm.sdk.jmod`.

Your proposed command line is correct only on Mandrel, not on GraalVM. Therefore, at run time, our launchers should adapt the command line to the current JDK layout. Alternatively, would it be acceptable to keep patching the `native-image` launcher as part of your build pipeline?

Minor -- I think the `truffle-nfi.jar` is misplaced:
```
- mkdir ${MANDREL_JDK}/languages
- cp ${GRAAL_REPO}/truffle/mxbuild/dists/jdk11/truffle-nfi.jar ${MANDREL_JDK}/languages
+ mkdir -p ${MANDREL_JDK}/languages/nfi
+ cp ${GRAAL_REPO}/truffle/mxbuild/dists/jdk11/truffle-nfi.jar ${MANDREL_JDK}/languages/nfi
```

**Comment by zakkak** [comment]
> If I understand correctly, the underlying issue is that you are packaging things differently. For example, in Mandrel `org.graalvm.word.UnsignedWord` is part of `lib/jvmci/graal-sdk.jar` while in GraalVM it is part of `jmods/org.graalvm.sdk.jmod`.

Correct.

I have tested packaging mandrel using `makegraaljdk` as part of the packaging process to perform the jlinking for me and it went well, however it looks like `makegraaljdk` does more than what we need/want, so I will try to extract the parts that we need.

Thanks for the pointer @ansalond 
Since I can fix this issue in Mandrel's packaging I will close this issue.

Out of curiosity, if I was to make mandrel packaging more graal-like would you be able to share the scripts you use for packaging GraalVM CE?

**Comment by ansalond** [comment]
> Out of curiosity, if I was to make mandrel packaging more graal-like would you be able to share the scripts you use for packaging GraalVM CE?

Sure! Our CI scripts are not easy to read, but all the relevant code is open source. For example, the builder that builds and uploads a JDK8 GraalVM CE image and the CE installables for Linux is defined here:
https://github.com/oracle/graal/blob/master/vm/ci_common/common.hocon#L304-L317

Simplifying a bit and assuming that you want to build only the base image (which does not include `native-image`):
```
$ cd graal/vm
$ mx --env ce graalvm-show  # check what you are about to build
$ mx --env ce build
$ mx --env ce graalvm-home  # path to the new GraalVM image
```

For a small GraalVM image that includes Native Image and its dependencies:
```
$ mx --dy /substratevm --components="Native Image" --native-images=false graalvm-show
GraalVM distribution: GRAALVM_83A3F67E14_JAVA8
Version: 20.2.0-dev
Config name: None
Components:
 - Native Image ('ni', /svm)
 - SubstrateVM ('svm', /svm)
 - Native Image licence files ('nil', /svm)
 - GraalVM compiler ('cmp', /graal)
 - Truffle Macro ('tflm', /truffle)
 - Truffle NFI ('nfi', /nfi)
 - Truffle ('tfl', /truffle)
 - Graal SDK ('sdk', /graalvm)
Launchers:
 - native-image (bash)
Libraries:
 - libnative-image-agent.so (skipped)
Installables:
 - NATIVE_IMAGE_INSTALLABLE_SLIBNATIVE-IMAGE-AGENT.SO_JAVA8
No standalone
$ mx --dy /substratevm --components="Native Image" --native-images=false build
$ mx --dy /substratevm --components="Native Image" --native-images=false graalvm-home
```

This last GraalVM image does not match any of our registered configurations, therefore it has a generated name (`GRAALVM_83A3F67E14_JAVA8` rather than, e.g., `GRAALVM_CE_JAVA8`).
To register a new GraalVM config, add a line here:
https://github.com/oracle/graal/blob/master/vm/mx.vm/mx_vm.py#L82-L95

These steps are documented [here](https://github.com/oracle/graal/blob/master/vm/README.md).

Feel free to ping me if you have questions or suggestions.

**Comment by ansalond** [comment]
From the steps to reproduce this issue:
```
pushd graal/substratevm
mx --components="Native Image" build
```

This is equivalent to what I suggested above:
```
$ mx --components="Native Image" graalvm-show
GraalVM distribution: GRAALVM_83A3F67E14_JAVA8
Version: 20.2.0-dev
Config name: None
Components:
 - Native Image ('ni', /svm)
 - SubstrateVM ('svm', /svm)
 - Native Image licence files ('nil', /svm)
 - GraalVM compiler ('cmp', /graal)
 - Truffle Macro ('tflm', /truffle)
 - Truffle NFI ('nfi', /nfi)
 - Truffle ('tfl', /truffle)
 - Graal SDK ('sdk', /graalvm)
Launchers:
 - native-image (bash)
Libraries:
 - libnative-image-agent.so (skipped)
No installable
No standalone
```

As you can see, it generates a base GraalVM image with the same set of components.

**Comment by zakkak** [comment]
Thanks for all the info @ansalond 

After toying around with what `makegraaljdk` does and trying manually `jlinking` the jmods it looks like there is no way to achieve what Mandrel aims for this way.
In Mandrel we aim to provide a vanilla upstream OpenJDK build along with the "extras" that are required to run `native-image`. Unfortunately using `jlink` results in a different (modded) OpenJDK which is not desired.

So this brings us back to the fact that the `native-image` shell script requires a modded JDK to work.
Since `java -version` prints something like `OpenJDK Runtime Environment GraalVM CE 20.1.0 (build 11.0.7+10-jvmci-20.1-b02)` in the modded JDK I could use this info to determine at runtime whether the extra flags should be added or not (as mentioned in https://github.com/oracle/graal/issues/2502#issuecomment-674010275).

Would something like this:
```diff
diff --git a/sdk/mx.sdk/vm/launcher_template.sh b/sdk/mx.sdk/vm/launcher_template.sh
index 225261f48d4..b5951f3c64e 100644
--- a/sdk/mx.sdk/vm/launcher_template.sh
+++ b/sdk/mx.sdk/vm/launcher_template.sh
@@ -48,6 +48,13 @@ done
 jvm_args=("-Dorg.graalvm.launcher.shell=true" "-Dorg.graalvm.launcher.executablename=$0")
 launcher_args=()
 
+${location}/<jre_bin>/java 2>&1 | grep GraalVM
+if [[ $? != 0 ]];
+then
+    jvm_args+=("--upgrade-module-path=${location}/../../jvmci/graal.jar" "--add-modules=org.graalvm.truffle,org.graalvm.sdk" "--module-path=${location}/../../truffle/truffle-api.jar:${location}/../../jvmci/graal-sdk.jar")
+    launcher_args+=("-J--add-exports=jdk.internal.vm.ci/jdk.vm.ci.code=jdk.internal.vm.compiler")
+fi
+
 # Unfortunately, parsing of `--jvm.*` and `--vm.*` arguments has to be done blind:
 # Maybe some of those arguments where not really intended for the launcher but were application arguments
 
```
be acceptable? (we will need to do the same for windows of course)

**Comment by ansalond** [comment]
I would rather keep patching the `native-image` executable as part of the Mandrel build pipeline. This logic would not be tested by our gates and it depends on the Mandrel layout, which is not defined here. @gilles-duboscq, @olpaw, any opinion?

**Comment by zakkak** [comment]
Note that the packaging differences create other issues as well (see https://github.com/graalvm/mandrel/issues/108).
So moving forward we essentially need to decide whether upstream graal is willing to accept patches that enable that kind of differences between the two packaging approaches or not.

**Comment by gilles-duboscq** [comment]
Using paths like `${location}/../../jvmci/graal.jar` is not very robust since the relative path depends on where the launcher ends up. We'd at least need to build customized relative paths when instantiating the template.

Just adding this little snippet in the general template looks like a hack: in general the set of modules and their location depends on the specific launcher and the configuration of the GraalVM.
One possibility would be to add a flag that allows building on 11 without jlinking the GraalVM modules in. However that's a larger change.

The other question is native launchers, this change affects the scripted launchers but not native ones.
So far the native launchers are the only really supported option for a production build. The scripted launchers are a build and development convenience.

**Comment by dougxc** [comment]
> that allows building on 11 without jlinking the GraalVM modules in

This would be a very useful change in general, especially for development as it would allow us to avoid the length jlink step.

**Comment by zakkak** [comment]
> Using paths like `${location}/../../jvmci/graal.jar` is not very robust since the relative path depends on where the launcher ends up. We'd at least need to build customized relative paths when instantiating the template.
> 

Would relative paths to `${location}/<jre bin>/` be OK?
This is already used to get the `java` command in https://github.com/oracle/graal/blob/master/sdk/mx.sdk/vm/launcher_template.sh#L111
Alternatively we will need to add more `<placeholders>`, possibly on for each module.

> Just adding this little snippet in the general template looks like a hack: in general the set of modules and their location depends on the specific launcher and the configuration of the GraalVM.

True. A new configuration along with the appropriate changes in `mx` extensions would be much cleaner. Unfortunately, we have not been able to use `mx` (other than for simple commands) in our internal build system due to its dependency fetching (the build system does not have internet access). We have tried to improve things on that front (see https://github.com/graalvm/mx/pull/213), but we are still not there.

> One possibility would be to add a flag that allows building on 11 without jlinking the GraalVM modules in. However that's a larger change.

That would be interesting.

> The other question is native launchers, this change affects the scripted launchers but not native ones.
> So far the native launchers are the only really supported option for a production build. The scripted launchers are a build and development convenience.

For GraalVM the scripted launchers are indeed a build and development convenience, but in Mandrel we have seen that they work fine in the production build as well (they miss some features, like the build image server, but that's OK for now) and make packaging a lot simpler.

Out of curiosity what's the motivation behind the native launchers, why aren't scripts enough for production?
Are there any other reasons than avoiding the overhead of starting a new JVM instance?

**Comment by gilles-duboscq** [comment]
> Would relative paths to `${location}/<jre bin>/` be OK?

Yes, that would work.

> Unfortunately, we have not been able to use mx (other than for simple commands) in our internal build system due to its dependency fetching (the build system does not have internet access).

We also don't pull from the internet when building. We use `MX_URLREWRITES` ([some docs](https://github.com/graalvm/mx#url-rewriting)) to fetch dependencies from a server hosting a curated list of dependencies.

> Out of curiosity what's the motivation behind the native launchers, why aren't scripts enough for production?

For most language launchers we want the execution to happen in a native image so we need a native binary anyway. Adding a shell script and/or java process in front of that is just making things more complex and slower for no good reason.
The native-image script is a bit special since it forks out to a JVM in any case. However, the build server was easier to do in native mode.
A minor thing is platform support: the windows scripts have been a nightmare to get kind of close to something that works.
Another minor reason was a bit of dog-fooding of native-image.

**Comment by zakkak** [comment]
Nice, thanks for all the info Gilles.
I will get back after some more experimentation :)

**Comment by zakkak** [comment]
[This is getting a bit out of topic so please let me know if you wan to move this conversation or rename the issue]

After toying a bit more with mx suites and configurations I see the following issues:

1. No way to to define our own "Mandrel Native Image" component and add the dependencies we want and/or a `custom_launcher_script`:
I am getting `Conflicting native-image configs: Native Image and Mandrel Native Image both declare a config called bin/native-image`
I even tried creating a different binary and then it complains about the native-image-agent lib.

2. Didn't find a way to remove dependencies. E.g., in mandrel we are using the system provided libffi so we don't want to include https://github.com/oracle/graal/blob/09eca26a04053334af8c385b5bc651aa96593998/substratevm/mx.substratevm/suite.py#L1021

3. The closest I could get to a minimal build (without packaging) is: 
```
$ mx -V --primary-suite-path substratevm --native-images=native-image --components='Native Image' build --projects "SVM,com.oracle.svm.native.libchelper,com.oracle.svm.native.jvm.posix,native-image.image" 2>&1 | grep -i download     
Downloading ANTLR4
Downloading LIBFFI_SOURCES
Downloading HAMCREST
Downloading JUNIT [depends on HAMCREST]
Downloading JLINE
```
Where we would like to:
* not use `LIBFFI_SOURCES` (See 2 above), a potential fix could come from something like https://github.com/graalvm/mx/pull/213
* not download JUNIT and HAMCREST since I don't see why they are needed (please correct me if I am wrong) 
* (ideally) also skip JLINE since it's only used by `MultiLanguageShell` which AFAIU we don't need in Mandrel

4. Even with the above we still need to patch makegraaljdk for mandrel so that it doesn't patch the JDK with the jmods.

**Comment by gilles-duboscq** [comment]
Re 1.:
I think the main difference between Mandrel and GraalVM is whether some base libraries such as the SDK and Truffle and jlink'd in or shipped as separate JARs. If we add a mode to ship those as JARs then it would be a generic thing for the launchers to add the modules through JVM command-line options rather than expect them to already be there.

Re 2.:
It seems what you want it introduce a way to build and link against the system provided libffi, not just remove that dependency. The way this is typically done is to introduce a global flag + env variable. For example in `mx_sdk_vm_impl.py`:
```
mx.add_argument('--no-sources', action='store_true', help='Do not include the archives with the source files of open-source components.')
...
def _include_sources():
    return not (mx.get_opts().no_sources or _env_var_to_bool('NO_SOURCES'))
```
And then use that flag where necessary. Things in `suite.py` are rather static, if things need to be created more dynamically, there is a hook called `mx_register_dynamic_suite_constituents`:

```
def mx_register_dynamic_suite_constituents(register_project, register_distribution):
    if register_project:
        some_project = ...
        register_project(some_project)
    some_distribution = ...
    register_distribution(some_distribution)
```

Re. 3.:
* `LIBFFI_SOURCES` would not be downloaded if we were building in a mode where we link against system library and headers
* `JUNIT` and `HAMCREST` are needed to build some SVM stuff (project `com.oracle.svm.junit` that goes into `LIBRARY_SUPPORT`)
* I wonder how you pick up `JLINE`. I guess it must be through `native-image.image`: since you ask for it as a native-image, it must build a bootstrap GraalVM which will include `LAUNCHER_COMMON` which in turn depends on `JLINE` because of `MultiLanguageShell` as you mentioned.

Re 4.:
See my answer to point 1.

**Comment by zakkak** [comment]
HI @gilles-duboscq sorry for the late reply

Re 1.:
So would a flag like `--no-jlinking` be welcome?

Re 2.:

So I need to remove all distributions and dependencies that depend on libraries built from source from the corresponding suite.py files and dynamically create them by defining `mx_register_dynamic_suite_constituents` in the corresponding suite modules. 
For LIBFFI those would be dist `substratevm:SVM_HOSTED_NATIVE` and dep `truffle:libffi`.
I think I will start with this :)

Re 3.:

* `com.oracle.svm.junit` is needed to run junit tests in a native image right?
BTW why is `--macro:junit` missing from the releases?
```
graalvm-ce-java11-20.1.0/bin/native-image --macro:junit test
Error: Unknown name in option specification: macro:junit
Available macro options are:
    --macro:polyglot-launcher
    --macro:gu-launcher
    --macro:native-image-agent-library
    --macro:graalvm-native-binutil-launcher
    --macro:graalvm-native-clang-launcher
    --macro:truffle
    --macro:graalvm-native-ld-launcher
    --macro:js-launcher
    --macro:jvmcicompiler-library
    --macro:graalvm-native-clang++-launcher
    --macro:lli-launcher
    --macro:polyglot-library
    --macro:native-image-launcher
```

* Do you think there is any way to remove the `JLINE` dependency without breaking things?

**Comment by zakkak** [comment]
Re 2: I have opened https://github.com/oracle/graal/pull/2852

Could someone please provide some feedback on my latest questions regarding 1 and 3 in https://github.com/oracle/graal/issues/2502#issuecomment-693024160?

I am especially interested in getting some feedback for 1!

cc @gilles-duboscq

**Comment by gilles-duboscq** [comment]
> So would a flag like `--no-jlinking` be welcome?

I'm not sure how the result will not be a rather awkward GraalVM in which the `java` command will not be using the Graal compiler and using `-XX:+UseJVMCICompiler` there will use an old outdated version of the Graal compiler.
The fundamental issue I see here is that there's no way for the JDK to pickup additional module just based on their presence in a special location (this was the design we had in JDK8).

However beside changing that upstream in HotSpot i don't really see a way forward. As a result i agree a `--no-jlinking` option is the only way forward. There should be some explicit mention that the result cannot be a GraalVM to avoid user confusion when the result of building with `--no-jlinking` doesn't behave like a typical GraalVM.

Regarding `com.oracle.svm.junit`, yes, i think that's what is used to run the unittest in native images.
It's not part of the releases because it's just considered an internal testing helper.
I think there is a projects that aims at making it easy for graalvm users to run junit tests on a native-image but i don't really know much about that. Maybe @christianwimmer knows?

**Comment by zakkak** [comment]
> > So would a flag like `--no-jlinking` be welcome?
> 
> I'm not sure how the result will not be a rather awkward GraalVM in which the `java` command will not be using the Graal compiler and using `-XX:+UseJVMCICompiler` there will use an old outdated version of the Graal compiler.

You are actually describing Mandrel here :)
The `--no-jlinking` would essentially allow one to take a JDK and augment it with the necessary bits to work with `native-image`.
The end goal here is being able to run `native-image`, not producing a GraalVM.

> The fundamental issue I see here is that there's no way for the JDK to pickup additional module just based on their presence in a special location (this was the design we had in JDK8).

This is only relevant if we want to have a GraalVM (i.e. a JDK using graal by default, or at least when using `-XX:+UseJVMCICompiler`), right?
 
> However beside changing that upstream in HotSpot i don't really see a way forward. As a result i agree a `--no-jlinking` option is the only way forward. There should be some explicit mention that the result cannot be a GraalVM to avoid user confusion when the result of building with `--no-jlinking` doesn't behave like a typical GraalVM.

Maybe we could come up with a better flag to indicate that the end result will not be GraalVM, something like `--native-image-only`? Suggestions are welcome!

> Regarding `com.oracle.svm.junit`, yes, i think that's what is used to run the unittest in native images.
> It's not part of the releases because it's just considered an internal testing helper.
> I think there is a projects that aims at making it easy for graalvm users to run junit tests on a native-image but i don't really know much about that. Maybe @christianwimmer knows?

Nice, thanks for the info!

**Comment by gilles-duboscq** [comment]
> Maybe we could also come up with a better flag to indicate that the end result will not be GraalVM, something like --native-image-only? Suggestions are welcome!

Between those two options, i personally prefer `--no-jlinking` since it is orthogonal to what is included or not (native-image present or not, orther components present or not etc.).
