### ISSUE TITLE
exception "Option name "TruffleIntrinsifyFrameAccess" has multiple definitions" when use native-image-maven-plugin to build native image

### ISSUE THREAD

**Issue by skyguard1** [oracle/graal#2503]
Hello, when I used graalvm, it threw an exception when building the native image with the native image-maven-plugin:
Fatal error: com. Oracle. SVM. Core. Util. VMError $HostedError: the Option name "TruffleIntrinsifyFrameAccess" has multiple definitions: Org.graalvm.compiler.truffle.com piler. Substitutions. TruffleGraphBuilderPlugins $Options. TruffleIntrinsifyFrameAccess and Org.graalvm.compiler.truffle.com piler. TruffleCompilerOptions. TruffleIntrinsifyFrameAccess
At com. Oracle. SVM. Core. Util. VMError. ShouldNotReachHere (VMError. Java: 66)
At com. Oracle. SVM. Hosted. Option. HostedOptionParser. CollectOptions (HostedOptionParser. Java: 88)
At com. Oracle. SVM. Hosted. Option. HostedOptionParser. < init > (HostedOptionParser. Java: 61)
At com. Oracle. SVM. Hosted. NativeImageGeneratorRunner. BuildImage (NativeImageGeneratorRunner. Java: 204)
At com. Oracle. SVM. Hosted. NativeImageGeneratorRunner. Build (NativeImageGeneratorRunner. Java: 448)
At com. Oracle. SVM. Hosted. NativeImageGeneratorRunner. Main (NativeImageGeneratorRunner. Java: 113)

I don't know if it is a version compatibility problem, but the highest version of this plug-in is 19.2.1. I would like to ask the specific reason. Thank you very much for your answer

**Steps to reproduce the issue**
mvn clean package

graalVm version:OpenJDK 64-Bit GraalVM CE 19.3.0 (build 25.232-b07-jvmci-19.3-b05, mixed mode)
 - JDK major version: 1.8
 - OS: macOS
maven plugin:

            <plugin>
                <groupId>com.oracle.substratevm</groupId>
                <artifactId>native-image-maven-plugin</artifactId>
                <version>19.2.1</version>
                <configuration>
                    <imageName>${project.artifactId}</imageName>
                </configuration>
                <executions>
                    <execution>
                        <goals>
                            <goal>native-image</goal>
                        </goals>
                        <phase>package</phase>
                    </execution>
                </executions>
            </plugin>

Looking forward to your reply. Thank you very much.

**Comment by skyguard1** [comment]
i change the graalvm version to 19.2.1,It doesn't throw this exception, but my json serialization tool compiled throw this exception:
Trace: 
	at parsing com.alibaba.fastjson.util.ASMClassLoader.defineClassPublic(ASMClassLoader.java:174)
Call path from entry point to com.alibaba.fastjson.util.ASMClassLoader.defineClassPublic(String, byte[], int, int): 
	at com.alibaba.fastjson.util.ASMClassLoader.defineClassPublic(ASMClassLoader.java:174)
	at com.alibaba.fastjson.serializer.ASMSerializerFactory.createJavaBeanSerializer(ASMSerializerFactory.java:412)
	at com.alibaba.fastjson.serializer.SerializeConfig.createASMSerializer(SerializeConfig.java:90)
	at com.alibaba.fastjson.serializer.SerializeConfig.createJavaBeanSerializer(SerializeConfig.java:242)
	at com.alibaba.fastjson.serializer.SerializeConfig.createJavaBeanSerializer(SerializeConfig.java:118)
	at com.alibaba.fastjson.serializer.SerializeConfig.getObjectWriter(SerializeConfig.java:508)
	at com.alibaba.fastjson.serializer.SerializeConfig.getObjectWriter(SerializeConfig.java:430)
	at com.alibaba.fastjson.serializer.JSONSerializer.getObjectWriter(JSONSerializer.java:410)
	at com.alibaba.fastjson.serializer.JSONSerializer.write(JSONSerializer.java:282)
	at com.alibaba.fastjson.JSON.toJSONString(JSON.java:740)
	at com.alibaba.fastjson.JSON.toJSONString(JSON.java:678)
	at com.alibaba.fastjson.JSON.toJSONString(JSON.java:643)
	at com.skyguard.test.MainApplication.main(MainApplication.java:29)
	at com.oracle.svm.core.JavaMainWrapper.runCore(JavaMainWrapper.java:151)
	at com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:186)
	at com.oracle.svm.core.code.IsolateEnterStub.JavaMainWrapper_run_5087f5482cc9a6abc971913ece43acb471d2631b(generated:0)

 I know this may be normal, because there are some problems with the support for reflection, but json operation is a very important operation, is there any way to solve it? In addition, is there any plan for maven plug-in update?Thank you very much.

**Comment by javahippie** [comment]
I was running into the same issues, and I realized I used the "oracle" group id for the plugin. For me it works with the following configuration. I am not able to find documentation of it, but I guess the groupId was moved to `org.graalvm.nativeimage` instead?

```xml
  <dependencies>
        <dependency>
            <groupId>org.graalvm.nativeimage</groupId>
            <artifactId>svm</artifactId>
            <version>20.1.0</version>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.graalvm.nativeimage</groupId>
                <artifactId>native-image-maven-plugin</artifactId>
                <version>20.1.0</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>native-image</goal>
                        </goals>
                        <phase>package</phase>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
```

**Comment by skyguard1** [comment]
Yes, I have solved the problem and it does seem that there is a version compatibility issue.appreciate it.

**Comment by skyguard1** [comment]
In addition,I would like to ask if there is a way to debug the native image application,or how can see the runtime data?

**Comment by cstancu** [comment]
@skyguard1 see https://github.com/oracle/graal/blob/master/substratevm/DebugInfo.md

**Comment by buptzyf** [comment]
@skyguard1  how to solve the problem? 怎么解决fastjson的错误呢？
