### ISSUE TITLE
Introduce TruffleString

### ISSUE THREAD

**Issue by fniephaus** [oracle/graal#2505]
The goal of this issue is to publicly collect requirements and document the design and implementation of `TruffleString`, a language-agnostic string representation for string-like objects within Truffle languages.

Quoting @chumer:

> The current design is immutable. Buffers are a different story we won’t cover in the first design. [...] lots of Ruby requirements coming in from the Ruby team. Now TruffleString (is) in the hand of the regex team, which is naturally a cross language team.

| Language Implementation | Type | Comments |
|:----------|:----------:|:-----------|
| Espresso | *immutable* | *Implementation not (yet) public.* |
| FastR | *mutable* | Uses `byte[]` and `String` within its [`CharSXPWrapper`](https://github.com/oracle/fastr/blob/ebb15e3d5dc27f80a570c29f2548998f98e37ee9/com.oracle.truffle.r.runtime/src/com/oracle/truffle/r/runtime/data/CharSXPWrapper.java#L54), which is used in [`RStringVecNativeData`](https://github.com/oracle/fastr/blob/ebb15e3d5dc27f80a570c29f2548998f98e37ee9/com.oracle.truffle.r.runtime/src/com/oracle/truffle/r/runtime/data/RStringVecNativeData.java#L40-L52) |
| GraalPython    | *immutable* | Uses Java `CharSequence` as part of its [`PString`](https://github.com/graalvm/graalpython/blob/05b0c88948968e1a60ee4b2a4be67215ef0a9019/graalpython/com.oracle.graal.python/src/com/oracle/graal/python/builtins/objects/str/PString.java#L63). |
| Graal.js | *immutable* | Uses Java `CharSequence` within a `DynamicObject` as part of its [`JSString`](https://github.com/graalvm/graaljs/blob/a36b978aa328a8da3a7f9e2b354257f8a817409d/graal-js/src/com.oracle.truffle.js/src/com/oracle/truffle/js/runtime/builtins/JSString.java#L103). |
| SOMns | *immutable* | Uses Java `String` as [internal string representation](https://github.com/smarr/SOMns/blob/e56f4c2815cef4cae2045a9b05dc1fd190315ba6/src/som/primitives/StringPrims.java#L45). Has support for immutable [symbols](https://github.com/smarr/SOMns/blob/e56f4c2815cef4cae2045a9b05dc1fd190315ba6/src/som/vmobjects/SSymbol.java#L36). |
| TruffleRuby | *mutable* | Uses [ropes](https://github.com/oracle/truffleruby/blob/516b3ee9d51d79ccd9c2820c11f6531a9b177e97/src/main/java/org/truffleruby/core/rope/Rope.java) to provide mutability, has multiple encodings, not all encodings fully compatible with Unicode, zero-copy concatenation critical for performance of production code. |
| TruffleSqueak | *mutable* | Supports [`ByteString`](https://github.com/hpi-swa/trufflesqueak/blob/7779278aac2255244c16b494f4c4e76f8543b5cc/src/de.hpi.swa.trufflesqueak/src/de/hpi/swa/trufflesqueak/image/SqueakImageContext.java#L582-L584) (`byte[]`) and [`WideString`](https://github.com/hpi-swa/trufflesqueak/blob/7779278aac2255244c16b494f4c4e76f8543b5cc/src/de.hpi.swa.trufflesqueak/src/de/hpi/swa/trufflesqueak/image/SqueakImageContext.java#L586-L588) (`int[]`). A `ByteString` *becomes* a `WideString` when a value outside the byte-range (e.g. a unicode char) is put into it. |

*Please put this issue on the [Truffle project](https://github.com/oracle/graal/projects/4) and assign it to @chumer and @djoooooe.*

**Edit 1**: Add Espresso.
**Edit 2**: Incorporate @chrisseaton's Ruby comment extension (see https://github.com/oracle/graal/issues/2505#issuecomment-633982977).

**Comment by smarr** [comment]
For TruffleSOM and derivates (SOMns, Moth (a Grace)) we indeed expect Strings and Symbols (interned Strings) to be immutable like in Java.
Rope-like append and sharing of substrings might be a nice things to have, though, I am not too sure about the tradeoffs.

**Comment by fniephaus** [comment]
I wonder if the ropes optimization could somehow be implemented in an optional manner, so that language implementations could decide if they want to use it or not. Implementing ropes again and again in some languages seems redundant.

Also, I'm of course interested in what `TruffleString` means for interop: will it replace `String` as the exchange representation between languages? Does my language have to create `TruffleString`s on the fly for interop if it does not use it internally?

**Comment by djoooooe** [comment]
The current plan would be to replace `String` with `TruffleString` in interop, but offer native support for `String`, i.e. the actual parameter type in Java will be `Object`, and passing a `String` would still be valid.

**Comment by chrisseaton** [comment]
Language Implementation | Type | Comments
-- | -- | --
TruffleRuby | mutable | Uses ropes to provide mutability, has multiple encodings, not all encodings fully compatible with Unicode, zero-copy concatenation critical for performance of production code

**Comment by fcurts** [comment]
You might want to consider support for viewing strings as sequences of extended grapheme clusters, which is increasingly supported by modern languages (e.g., Dart, Swift).

https://medium.com/flutter-community/working-with-unicode-and-grapheme-clusters-in-dart-b054faab5705

**Comment by boris-spas** [comment]
Tracking internally as GR-17176.

**Comment by chrisseaton** [comment]
Thanks Boris. Please engage with us early and often on your designs and prototypes. My use-case is very sensitive to string performance and I can experiment on real workloads.

**Comment by SchrodingerZhu** [comment]
any update

**Comment by fniephaus** [comment]
TruffleString was merged last night via https://github.com/oracle/graal/commit/845231e651d611ecbe5cffc0535fda0d0e83bad1.
