### ISSUE TITLE
[igv] igv 20.1 not signed for macOS Catalina

### ISSUE THREAD

**Issue by fniephaus** [oracle/graal#2517]
When trying to start igv 20.1 for macOS on Catalina, I get the following error:

<img width="420" alt="image" src="https://user-images.githubusercontent.com/2368856/83236730-44386600-a194-11ea-8bc2-bf60f34f429d.png">

> “libjnidispatch-440.jnilib” cannot be opened because the developer cannot be verified.

Nonetheless, igv opens after pressing the "Cancel" button. I'm not sure what kind of functionality is affected by this, but I do know this is due to igv not being signed and notarized for macOS Catalina. Therefore, this is a workaround:

```
sudo xattr -r -d com.apple.quarantine /full/path/to/idealgraphvisualizer
```

**Comment by olyagpl** [comment]
@fniephaus,  I've tested IGV 20.2  for macOS Catalina and it launches as expected from command line. 
Do you still encounter the same problem with 20.2?

**Comment by fniephaus** [comment]
For some reason, I no longer get the error in IGV 20.2, even though the jnilib is still unsigned:
```bash
$ codesign -v platform/modules/lib/libjnidispatch-nb.jnilib 
platform/modules/lib/libjnidispatch-nb.jnilib: code object is not signed at all
In architecture: x86_64
```

Closing this for now...
