### ISSUE TITLE
[native-image] provide more information about missing JNI Method

### ISSUE THREAD

**Issue by johanvos** [oracle/graal#2523]
**Describe the issue**
When native wants to invoke a Java method, the corresponding methodID is searched via `JNIFunctions.getMethodID`. In case the class holding this method is not registered for JNI, this `getMethodID` will throw a NullPointerException without information about the method we want to invoke.

This can be improved by checking on `hclazz == null` and in that case, the name and signature of the method can be printed.

**Comment by johanvos** [comment]
PR #2524 has a fix for this.

**Comment by peter-hofer** [comment]
Closing: the JNI specification requires `must not be NULL`. HotSpot does not have any conservative checks either.
