### ISSUE TITLE
Bad link in Truffle documentation

### ISSUE THREAD

**Issue by sidkshatriya** [oracle/graal#253]
Clicking on the truffle readme "GPL 2 with class path exception"  link leads to a 404 
![screenshot-2017-9-7 graalvm graal](https://user-images.githubusercontent.com/638477/30170289-57a40aca-940c-11e7-83d0-5cc876947c49.png)

**Comment by dougxc** [comment]
This appears to now be resolved: https://github.com/oracle/graal/tree/master/truffle#license
