### ISSUE TITLE
Latest IGV fails to open dumps created from Graal HEAD.

### ISSUE THREAD

**Issue by a74nh** [oracle/graal#2536]
I'm using the following HEAD:
`12cd99f144 2020-06-03.. Josef Eisl      [GR-23836] SulongTestSuite: allow bitcode tests to be linked with C files.`

I have the latest released version of IGV: 20.0.1 downloaded from https://www.oracle.com/downloads/graalvm-downloads.html.  (as suggested by "mx igv")

When opening a graal dump, IGV errors with "File format version 7.0 unsupported. Current version is 6.1"

**Comment by fniephaus** [comment]
AFAIK, the latest release should be 20.1.0. Could you please have another look and try again?

**Comment by fniephaus** [comment]
Oha, it looks like the EE download pages says 20.0.1, but it's actually 20.1.0?

**Comment by MartinBalin** [comment]
BGV version increased from last release, so 20.0 IGV can't read 20.1 GraalVM dumps.
Resolution: Update IGV version on: https://www.oracle.com/downloads/graalvm-downloads.html
There is wrong version number on OTN download page. Will be resolved...
