### ISSUE TITLE
Supporting fibers using puniverse/quasar has issues from instrumentation and quasar-core implementation

### ISSUE THREAD

**Issue by doctorpangloss** [oracle/graal#2546]
**Describe the issue**
The bytecode emitted by `puniverse/quasar` fiber and coroutines instrumentation cannot be compiled by `native-image`.  Includes reproduction with a carefully embedded quasar-core and instrumentation script to make it very easy for you to investigate a fix.

Fixing this issue would fix #477 and could give you a path to support fibers in dynamic languages today without Loom.

This is also related to #955 because `quasar-core` uses `VarHandle` / `MethodHandle`.

A useful fibers implementation would not need to be able to instrument at runtime so maybe some changes to `quasar-core` would be possible to Just Work on GraalVM.

**Steps to reproduce the issue**

https://github.com/hiddenswitch/quasar-fibers-bytecodes-graal

```
git clone git@github.com:hiddenswitch/quasar-fibers-bytecodes-graal.git
cd quasar-fibers-bytecodes-graal
gu install native-image
./gradlew testapp:shadowJar
native-image -jar testapp/build/libs/testapp-all.jar -H:+ReportExceptionStackTraces --no-fallback --native-image-info --verbose &>output.log
```

[output.log](https://github.com/oracle/graal/files/4738894/output.log)

These errors are related to the implementation of `quasar-core` rather than the instrumentation:

```
./gradlew uninstrumentedtestapp:shadowJar
native-image -jar uninstrumentedtestapp/build/libs/uninstrumentedtestapp-all.jar -H:+ReportExceptionStackTraces --no-fallback --native-image-info --verbose &>output2.log
```

[output2.log](https://github.com/oracle/graal/files/4738908/output2.log)

# Environment

***GraalVM version:***

```
openjdk version "11.0.7" 2020-04-14
OpenJDK Runtime Environment GraalVM CE 20.1.0 (build 11.0.7+10-jvmci-20.1-b02)
OpenJDK 64-Bit Server VM GraalVM CE 20.1.0 (build 11.0.7+10-jvmci-20.1-b02, mixed mode, sharing)
```

 - JDK major version: **11**
 - OS: **macOS Catalina**
 - Architecture: **AMD64**

**Comment by cstancu** [comment]
The underlying issue here is incomplete `MethodHandle` support. That is under development and is being tracked by https://github.com/oracle/graal/issues/2761.
