### ISSUE TITLE
NoClassDefFoundError condition should be flipped or removed

### ISSUE THREAD

**Issue by galderz** [oracle/graal#2556]
The original PR for https://github.com/oracle/graal/pull/2294 has a bug. This condition:

```
if (!NativeImageOptions.AllowIncompleteClasspath.getValue()) {
       return false;
}
```

Should be flipped (assuming the condition stays, follow discussion https://github.com/oracle/graal/pull/2294#discussion_r436146094). Condition should read:

```
if (NativeImageOptions.AllowIncompleteClasspath.getValue()) {
       return false;
}
```

The bug in the fix means that with the integrated PR https://github.com/apache/camel-quarkus/issues/1319 does not happen. However, you can temporarily trigger it by adding:

```
-Dquarkus.native.additional-build-args=--allow-incomplete-classpath
```

**Comment by cstancu** [comment]
Fixed in d383d80a0e0acc13006da932f052f8c1177bec2b.
