### ISSUE TITLE
Document static linking more precisely

### ISSUE THREAD

**Issue by sdeleuze** [oracle/graal#2560]
As detailed in [my recent blog post](https://spring.io/blog/2020/06/10/the-path-towards-spring-boot-native-applications), a key use cases for server-side applications is to be able to use minimal (`FROM scratch`) Docker images via `--static` flag.

When I try to use this option with any Spring Boot sample, even basic ones like [`commandlinerunner`](https://github.com/spring-projects-experimental/spring-graalvm-native/tree/master/spring-graalvm-native-samples/commandlinerunner), I got a segmentation fault.

If I try to compile a simple app with just `System.out.println("Hello");` it works.

To reproduce just add `--static` to the compile options then try to run the executable (fails even in a regular Ubuntu).

Could you please fix that for upcoming 20.1.1 and tag this issue with the `spring` label?

**Comment by eginez** [comment]
This is probably due to a bug in  glibc @gradinac will work on document native-image `musl` c integration

**Comment by sdeleuze** [comment]
Indeed with the right instructions, we were able to make it work. I am closing this issue since we are going to open a more specific one on allowing distroless support via more flexybility on GCC linking flags.

**Comment by sdeleuze** [comment]
Maybe better to let it open with an up to date title after all.

**Comment by gradinac** [comment]
Static native-image support has been documented at https://github.com/oracle/graal/blob/master/substratevm/STATIC-IMAGES.md

**Comment by sdeleuze** [comment]
I think we can close this issue now.
