### ISSUE TITLE
StringReader has no method reset in native image

### ISSUE THREAD

**Issue by piranha** [oracle/graal#2561]
My application works fine with GraalVM as JVM, but after compilation with native image I've got this stack trace:

```
java.lang.IllegalArgumentException: No matching field found: reset for class java.io.StringReader
	at clojure.lang.Reflector.getInstanceField(Reflector.java:397)
	at clojure.lang.Reflector.invokeNoArgInstanceMember(Reflector.java:440)
	at markdown.core$parse_references.invokeStatic(core.clj:38)
```

Initially I thought that this is some reflection issue, so I added a hint and tried to recompile it, which lead me to this error:

```
Fatal error:com.oracle.svm.core.util.VMError$HostedError: com.oracle.svm.core.util.VMError$HostedError: markdown.common$heading_level.invokeStatic(Object): has no code address offset set.
	at com.oracle.svm.core.util.VMError.shouldNotReachHere(VMError.java:72)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:647)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:451)
```

So it seems like StringReader.reset is not available in native image? I'm not really sure.

That's for graalvm-ce-java11-20.1.0.

**Comment by cstancu** [comment]
`java.io.StringReader` doesn't have a `reset` field. Maybe it is injected by clojure? Please provide steps to reproduce.

**Comment by piranha** [comment]
Hmm, am I misunderstanding something?

https://docs.oracle.com/javase/8/docs/api/java/io/StringReader.html#reset--

**Comment by cstancu** [comment]
The error message complaints about a missing field `No matching field found: reset for class java.io.StringReader`, which indeed doesn't exist.

**Comment by piranha** [comment]
Hm, this is really weird. It's calling a method `reset` [there](https://github.com/yogthos/markdown-clj/blob/master/src/clj/markdown/core.clj#L38), it even checks it's a `StringReader`. I wonder what the issue could be then. :\

**Comment by dougxc** [comment]
Does your reflection configuration specify `java.io.StringReader.reset` as a _field_ or a _method_? Judging purely by the comments in this issue, that seems to be at least one source of confusion.

**Comment by piranha** [comment]
Well, to specify as a field I would have to write `(.-reset StringReader)`, so it should be a method. But if I remove reflection and specifically point out it's a `StringReader`, this code dies during compilation (rather than in runtime). It has no problems working in GraalVM without native-image though.

**Comment by fernando-valdez** [comment]
Hello @piranha, can you please let us know if this issue is still happening in the latest release of GraalVM when using the Tracing Agent?

**Comment by piranha** [comment]
Yep, seems to be working fine now! Thanks!
