### ISSUE TITLE
Need to specify file extension when importing JavaScript files using the Context API from Java.

### ISSUE THREAD

**Issue by Charanor** [oracle/graal#2564]
**Describe GraalVM and your environment :**
 - GraalVM version or commit id if built from source: **20.1.0**
 - CE or EE: **CE**
 - JDK version: **JDK8**
 - OS and OS Version: **Windows 10**
 - Architecture: **amd64**
 - The output of `java -Xinternalversion`:
```
OpenJDK 64-Bit Server VM GraalVM CE 20.1.0 (25.252-b09-jvmci-20.1-b02) for windows-amd64 JRE (1.8.0), built on Apr 21 2020 14:28:43 by "BuildBot" with MS VC++ 10.0 (VS2010)
```

**Have you verified this issue still happens when using the latest snapshot?**
Yes, using `graalvm-ce-java8-20.2.0-dev`.

**Describe the issue**
When using the Context API to run JavaScript files from Java you need to specify the file extension when importing an ES6 module, e.g. `import testFn from "testFn.js"; // need to specify .js extension`

**Code snippet or code repository that reproduces the issue**
```
// Java code
try (final Context jsContext = Context.newBuilder("js").allowAllAccess(true).build()) {
    final URL resource = this.getClass().getClassLoader().getResource("index.mjs");
    final File file = Paths.get(resource.toURI()).toFile();
    final Source source = Source.newBuilder("js", file).mimeType("application/javascript+module").build();
    final Value value = jsContext.eval(source);

    System.out.println(value);
} catch (final IOException e) {
    e.printStackTrace();
} catch (final URISyntaxException e) {
    e.printStackTrace();
}
```
-----
```
// index.mjs
import testFn from "./testFn"; // add .js and it works
testFn; // return value to Java

```
-----
```
// testFn.js
function testFn() {
    print("Test!");
}

export default testFn;
```

**Steps to reproduce the issue**
Place code above into files, compile, and run.

**Expected behavior**
Expected to not have to specify file extension when importing a module using ES6 imports.

**Additional context**
If no file extension is specified, the code fails to run with the very undescriptive error 
```
Exception in thread "main" Error: C:/path/to/testFn.js
    at org.graalvm.polyglot.Context.eval(Context.java:345)
    // This error points to "final Value value = jsContext.eval(source);" in the Java code
```

**Comment by eleinadani** [comment]
Hi @Charanor,

by default, the ES module resolution mechanism of Graal.js does not append file extensions, and expects the module identifier to be a valid file name.

In your case, you could implement a [custom FS](https://www.graalvm.org/truffle/javadoc/org/graalvm/polyglot/Context.Builder.html#fileSystem-org.graalvm.polyglot.io.FileSystem-) and return `indexFs.js` whenever the file `indexFs` is loaded by the context. [This](https://github.com/graalvm/graaljs/blob/master/graal-js/src/com.oracle.truffle.js.test/src/com/oracle/truffle/js/test/builtins/ImportWithCustomFsTest.java#L99) is an example usage from JS.

**Comment by Charanor** [comment]
I understand! Thanks for the answer @eleinadani. If this expected behaviour feel free to close this issue.

P.S. I don't mean to circumvent the system and give you extra work but is it possible that you can take a look at this issue: #2636? It's something I've been struggling with for a while now and can't find a solution in the documentation unfortunately.

**Comment by boris-spas** [comment]
> If this expected behaviour feel free to close this issue.

@eleinadani  Can we close this issue?
