### ISSUE TITLE
GraalVM 20.1.0 CE catalog seems to only have native-image available.

### ISSUE THREAD

**Issue by miloslavskacel** [oracle/graal#2565]
Describe the issue
I wanted to experiment with graalpython, so I downloaded GraalVM 20.1.0 (see #2295). When I open a windows command prompt and run:

gu install python

I get the following output:

Downloading: Component catalog from www.graalvm.org
Error: Unknown component: python

If I run:

gu available

I get the following output:

Downloading: Component catalog from www.graalvm.org
ComponentId Version Component name Origin
native-image 20.1.0 Native Image github.com

GraalVM 20.1.0
JDK major version: 11
OS: Windows 10

**Comment by ansalond** [comment]
Hi @miloslavskacel, thanks for your question.
Unfortunately we do not yet have a Graal.Python release for Windows. At the moment, the only installable component for Windows is Native Image.
