### ISSUE TITLE
chrome-devtools:// is now devtools://

### ISSUE THREAD

**Issue by miloslavskacel** [oracle/graal#2573]
Debugging URL `chrome-devtools://devtools/bundled/js_app.html?ws=127.0.0.1:9229/tv5VL8...` does not work now in Chrome (updated to version 83.0.4103.106).
URL is not usable, because the URL scheme was recently changed to just devtools://

**Steps to reproduce the issue**
```
git clone https://github.com/graalvm/graalvm-demos.git
cd graalvm-demos/functionGraphDemo
npm i
node --jvm --polyglot  --inspect server.js
```
It suggests:
```
To start debugging, open the following URL in Chrome:
chrome-devtools://devtools/bundled/js_app.html?ws=127.0.0.1:9229/tv5VL8QY3hTglBErqP7zkaSSOAiCSkjvwfoDVRVap9I
```
URL does not open debugger.

**Describe GraalVM and your environment:**
 
```
node --version
v12.15.0

which node
C:\java\graalvm-ce-java11-20.1.0\bin\node.CMD

java --version
openjdk 11.0.7 2020-04-14
OpenJDK Runtime Environment GraalVM CE 20.1.0 (build 11.0.7+10-jvmci-20.1-b02)
OpenJDK 64-Bit Server VM GraalVM CE 20.1.0 (build 11.0.7+10-jvmci-20.1-b02, mixed mode, sharing)
```

**Comment by boris-spas** [comment]
Tracked internally as GR-24146, and already fixed. Should land in 20.2.0
