### ISSUE TITLE
have -g enable generation of debug symbols

### ISSUE THREAD

**Issue by maxandersen** [oracle/graal#2592]
**Feature request**

Please include the following information:

**Is your feature request related to a problem? Please describe.**
"-g" are traditionally used in both javac and gcc to declare debug info are enabled/included or not.

**Describe the solution you'd like.**
have `-g` enable `-H:GenerateDebugInfo=1` to be consistent with javac, gcc and GraalVM EE feature flags.

**Describe who do you think will benefit the most.**
GraalVM users.

**Describe alternatives you've considered.**
the current situation where behavior changes between GraalVM CE and EE but that does not seem wanted.

**Express whether you'd like to help contributing this feature**
I'm sure @adinn will be helpful :)

**Comment by olpaw** [comment]
Currently `-g` is used to enable our closed-source debug info generation for GraalVM EE. As of now the open source implementation provided by RedHat does not support

* Generation of type and program structure information (`.debug_types` & `.debug_info` section).
* Support for displaying live data (parameters, locals, static and instance fields) i.e. emitting location expression data.

If those featured are added and the open source implementation in on par with our closed-source implementation switching `-g` to use the RedHat implementation seems to be a good option.

/cc @christianwimmer @thomaswue

**Comment by maxandersen** [comment]
I understand there are differences but why not have `-g` be the flag that enables debug symbols no matter if you are using the CE or EE edition ?

**Comment by christianwimmer** [comment]
@maxandersen Agreed. Since this requires not much code in CE that you can provide, it is easiest if @olpaw does this.
