### ISSUE TITLE
Support application arguments for the image builder

### ISSUE THREAD

**Issue by christianwimmer** [oracle/graal#2601]
The `native-image` command line currently allows to pass options to the image generator, but there is no nice API way to provide application options that can be queried by a `Feature`.

Current ways to pass arguments:
* Pass arguments as system properties: All system properties passed via `-Dname-value` to the image generator can be accessed via `System.getProperty("name")`.
* Use the GraalVM option mechanism: discouraged because that is not API and can change at any point.

Unfortunately, the current command line for `native-image` has two optional arguments that are not prefixed, and options can be at any place:
```
Usage: native-image [options] class [imagename] [options]
           (to build an image for a class)
   or  native-image [options] -jar jarfile [imagename] [options]
           (to build an image for a jar file)
```
The main class name is optional (because it can come from a .jar file or be provided in a native-image.properties file), and the imagename is optional. So the most straightforward approach of
`native-image [options] MyClassname my application options` does not work without a general change of the command line.
A possibility that works is `native-image [options] MyClassName -- my application options`. The `--` as a separator is reasonably well established (but not for `java [options] MyClassName my application options`).

Approaches to wrap the argument in another option, e.g., `native-image MyClassName --arguments="my application options"` is probably not really better than providing a system property.

**Comment by zakkak** [comment]
+1 for `native-image [options] MyClassName -- my application options`

**Comment by olpaw** [comment]
> native-image [options] MyClassName -- my application options
IDK, this looks dangerous because it looks  as if native-image should build a image where the `String[]` passed to `main()` contains `{"my", "application", "parameters"}` which is not what you actually intend.
