### ISSUE TITLE
Native image agent filter: exclude resources

### ISSUE THREAD

**Issue by pelletier197** [oracle/graal#2602]
**Feature request**
**Wished behavior**
As stated in the [agent documentation](https://github.com/oracle/graal/blob/master/substratevm/CONFIGURE.md), it is possible to exclude classes from filtering, but it's not possible to exclude resources from being added to the resource config. For now, they have to be manually removed

**Who do you think will benefit the most.**
GraalVM users

**Describe alternatives you've considered.**
Have a file containing excluded resources and filter out the resources that manually.

**Comment by fernando-valdez** [comment]
It is possible to do that. Resources can be specified directly in the native-image command using the -H:IncludeResources and -H:ExcludeResources options. These options accept Java regular expressions to match resources for inclusion or exclusion and can be passed multiple times to define different patterns.
