### ISSUE TITLE
jdk/jdk compiling error after updategraalinopenjdk

### ISSUE THREAD

**Issue by XiaohongGong** [oracle/graal#2605]
**Describe the issue**
After updating the latest graal in jdk/jdk master by running "mx updategraalinopenjdk", building jdk reports the error:
```
jdk_build/support/gensrc/jdk.internal.vm.compiler/module-info.java:86: error: cannot find symbol

    uses org.graalvm.compiler.nodes.graphbuilderconf.NodeIntrinsicPluginFactory;

                                                    ^

  symbol:   class NodeIntrinsicPluginFactory

  location: package org.graalvm.compiler.nodes.graphbuilderconf
```

I checked the codes and found that ` "org.graalvm.compiler.nodes.graphbuilderconf.NodeIntrinsicPluginFactory.java"` has been renamed to ` "org.graalvm.compiler.nodes.graphbuilderconf.GeneratedNodeIntrinsicInvocationPlugin.java"`. And the `module-info.java` in ` jdk/jdk` should be updated when updating graal in openjdk either. 

**Steps to reproduce the issue**
Please include both build steps as well as run steps
1.  cd graal/compiler & mx updategraalinopenjdk jdk_src 16
2.  cd jdk_src & ./configure [options] & make images

**Describe GraalVM and your environment:**
 - GraalVM version : **[master]**
 - JDK major version: **[16]**
 - OS: **[Linux]**
 - Architecture: **[AMD64, AArch64]**

**More details**
Add any other information about the problem here. Especially important are stack traces or log output. Feel free to link to gists or to screenshots if necessary.
```
    PASTE YOUR LOG/STACK TRACE HERE
```

**Comment by dougxc** [comment]
@dean-long I think you're taking care of this right?

**Comment by dean-long** [comment]
There's a patch attachment in https://bugs.openjdk.java.net/browse/JDK-8247922 to fix this in the next "Update Graal".   If we thought this kind and rename that breaks module-info.java is going to happen often, then I guess we could try to have updategraalinopenjdk auto-generate that section of module-info.java, but this kind of breakage should be rare.
Or maybe we should have updategraalinopenjdk locate and apply JDK patches auto-magically.

**Comment by dean-long** [comment]
Hi @XiaohongGong, I just pushed a fix.

**Comment by XiaohongGong** [comment]
> Hi @XiaohongGong, I just pushed a fix.

Great! Thanks!
