### ISSUE TITLE
Transition from travis CI to github actions

### ISSUE THREAD

**Issue by zakkak** [oracle/graal#2609]
**Feature request**

In #2608 the transition from Travis CI to github actions was brought up.

Potential benefits of such a transition:
1. Users and Developers won't have to have a Travis CI account to see the build results
2. Better integration with github workflow and UI
3. The Mandrel distribution of graal is already using github actions. Such a transition would thus make testing across the community distributions more consistent.

**Describe the solution you'd like.**
Rewrite the existing travis CI pipeline in a github workflow.

**Describe who do you think will benefit the most.**
GraalVM contributors and developers of libraries and frameworks which depend on GraalVM.

**Express whether you'd like to help contributing this feature**
Given my recent involvement in a number of github workflows I volunteer to perform the transition.

**Comment by zakkak** [comment]
As pointed out by @dougxc https://github.com/oracle/graal/issues/2608#issuecomment-648826007 github still lacks AArch64 support

**Comment by dougxc** [comment]
This is definitely something we will consider once the oracle organization on GitHub is configured to allow GitHub Actions.

**Comment by maxandersen** [comment]
> This is definitely something we will consider once the oracle organization on GitHub is configured to allow GitHub Actions.

what is blocking it ?

**Comment by maxandersen** [comment]
> As pointed out by @dougxc [#2608 (comment)](https://github.com/oracle/graal/issues/2608#issuecomment-648826007) github still lacks AArch64 support

we could explore https://github.com/uraimo/run-on-arch-action ?

**Comment by zakkak** [comment]
My experience with building Maxine in QEMU is that it's a terribly slow process. Building on x86 (cross-compiling for AArch64) and then running only the tests using QEMU could be a more viable alternative. Not sure if such testing would be enough though.

**Comment by dougxc** [comment]
If the run-on-arch action is using emulation, then it will not be sufficient to run the current Travis AArch64 gates.

**Comment by zakkak** [comment]
After the recent changes announced by Travis CI (see #2956) the decision to migrate the CI to GH actions has been taken. However as we have already discussed here, GH actions do not provide AArch64 runners, so we need to decide how we would like to keep testing AArch64.

So far I see the following options:
1. Test in emulation through https://github.com/uraimo/run-on-arch-action
2. Keep the travis.yml around only for AArch64 tests (not sure if the free tier will be enough for this)
3. Setup a github runner on a graalvm-org maintained AArch64 machine (we will need someone to provide the HW and volunteer to maintain the runner)

(1) Seems the simplest, but might introduce limitations in what can be tested and will certainly introduce longer running times.
(2) Might be OK (if the free tier suffices for our needs) but it will require maintaining two CI pipelines which is something I would vote against.
(3) Seems the best approach but requires some investment in hardware and maintainance of the said hardware.

**Comment by dougxc** [comment]
Wrt (1), longer running times are not a problem per se. However, I suspect emulation will slow down things so much that these jobs will never succeed in the GitHub Actions time limit (whatever it is).
(3) is indeed the best. However, we don't have the resources for that currently.
So that leaves us with (2) as the path I would recommend for now.

**Comment by RoxaBee** [comment]
Regarding option 3 the self-hosted runner in terms of security

```
https://docs.github.com/en/free-pro-team@latest/actions/hosting-your-own-runners/about-self-hosted-runners#self-hosted-runner-security-with-public-repositories
We recommend that you do not use self-hosted runners with public repositories.
—
This is not an issue with GitHub-hosted runners because each GitHub-hosted runner is always a clean isolated virtual machine, and it is destroyed at the end of the job execution.

```
We would need to build something similar to GitHub-hosted runners, essentially a cloud service, which would not be trivial.
