### ISSUE TITLE
User guide to decrease the output of executable

### ISSUE THREAD

**Issue by strogiyotec** [oracle/graal#2619]
Good day, I'm working on small CLI app and I want to build native image from it. The app itself is not complicated , the only dependency it has is Jline3. You can check my pom file [here](https://github.com/strogiyotec/jfillin/blob/master/pom.xml). The problem is that the final size of executable is 15MB which is too big for me, I already found this [ticket](https://github.com/oracle/graal/issues/287) which has similar problem(I use java 11 and I don't think that footprint comes from javafx). What I want is the user guide on how to trouble shoot such problems and fix them. Maybe I can explicitly remove gc and specify some parameters as buildArgs for maven plugin. I didn't find anything related to it in official [documentation](https://www.graalvm.org/getting-started/#native-images). My final goal is to decrease the size to 3Mb because I already have the same program written in GoLang and I want to prove that Java version could have the same size. Thank you 
This is my graal info
```
gu list
ComponentId              Version             Component name      Origin
--------------------------------------------------------------------------------
graalvm                  20.0.0              GraalVM Core
native-image             20.0.0              Native Image        github.com
```
And java
```
java -version
openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment GraalVM CE 20.0.0 (build 11.0.6+9-jvmci-20.0-b02)
OpenJDK 64-Bit Server VM GraalVM CE 20.0.0 (build 11.0.6+9-jvmci-20.0-b02, mixed mode, sharing)
```

**Comment by wirthi** [comment]
Our documentation on this can be found at https://www.graalvm.org/jdk23/reference-manual/native-image/guides/optimize-for-file-size/

There now is the `-Os` flag to optimize for size. 3MB seems a bit ambitious but it should bring you lower than what you had before.
