### ISSUE TITLE
Discovered unresolved type during parsing: org.apache.maven.project.ReactorModelPool

### ISSUE THREAD

**Issue by borkdude** [oracle/graal#2626]
**Describe the issue**
I'm getting this error message:

```
Discovered unresolved type during parsing: org.apache.maven.project.ReactorModelPool
```

while compiling a project that resolves dependencies using maven libraries.

**Steps to reproduce the issue**
Please include both build steps as well as run steps
1. `git clone https://github.com/borkdude/tools-deps-native-experiment`
2. install the `clojure` CLI: https://clojure.org/guides/getting_started
3. point `GRAALVM_HOME` to the GraalVM installation
4. Run `script/compile`

**Describe GraalVM and your environment:**
 - GraalVM version CE 20.2.0-dev-20200627_0204
 - JDK major version: 11
 - OS: macOS Mojave
 - Architecture: AMD64

**More details**

[compile.txt](https://github.com/oracle/graal/files/4847732/compile.txt)

**Comment by cstancu** [comment]
This is not a bug, `org.apache.maven.project.ReactorModelPool` is missing from the class path. Use `--allow-incomplete-classpath` as the error message suggests. We are planning to make that the default in the near feature.
