### ISSUE TITLE
Change default folder for native-image

### ISSUE THREAD

**Issue by strogiyotec** [oracle/graal#2629]
Good day. I do use native-image and it created a dot folder in my home directory `cd ~/.native-image/` . This folder contains a lot of sub folders whose name match the following pattern `session-id-*`.
```
ls
.   session-id-116e  session-id-23eb  session-id-3a10  session-id-de0  create-server.lock
..  session-id-19ca  session-id-2cd1  session-id-70d   session-id-fe2
```

 I don't like keeping those kind folders in my home directory and usually move them to .local or .config folder. In this case, I want to move `.native-image` folder to ~/.local/share . I read help page for native-image `native-image --help` and didn't find an option to do it. Is it possible to specify folder path when I execute `native-image` ?
Native image version is 20.0.0

**Comment by olpaw** [comment]
You can use a different directory by setting environment variable `NATIVE_IMAGE_USER_HOME`. E.g
```bash
export NATIVE_IMAGE_USER_HOME=$HOME/.config/native-image
```
See: https://github.com/oracle/graal/blob/master/substratevm/src/com.oracle.svm.driver/src/com/oracle/svm/driver/NativeImage.java#L693..L700

**Comment by strogiyotec** [comment]
@olpaw thank you for response, even if this ticket is closed I want to ask , maybe it does make sense to add this information to documentation ,if so I can contribute to add it

**Comment by olpaw** [comment]
@strogiyotec please create a new Ticket that suggests adding the info https://github.com/oracle/graal/issues/2629#issuecomment-651622566 to our documentation.

**Comment by strogiyotec** [comment]
@olpaw Done https://github.com/oracle/graal/issues/2633
