### ISSUE TITLE
Add NATIVE_IMAGE_USER_HOME variable to documentation

### ISSUE THREAD

**Issue by strogiyotec** [oracle/graal#2633]
Good day, the original problem was described and solved [here](https://github.com/oracle/graal/issues/2629) (How to change default folder for native-image). I suggest adding the solution to the documentation . In my opinion it should look like this

>Native-image by default stores build information in HOME directory ($HOME/.native-image/).
> In order to change it you should set 
>path using environment variable NATIVE_IMAGE_USER_HOME 
>(Example in your bashrc add this line **export NATIVE_IMAGE_USER_HOME= $HOME/.local/share/native-image**)

If anyone is interested then I could contribute to this problem

**Comment by olyagpl** [comment]
Done https://www.graalvm.org/reference-manual/native-image/BuildConfiguration/#changing-the-configuration-directory
@strogiyotec, thank you!

**Comment by strogiyotec** [comment]
@@olyagpl  thank you so much
