### ISSUE TITLE
Native application doesn't honour java.net.preferIPv4Stack system property and instead always has IPv6 enabled

### ISSUE THREAD

**Issue by jaikiran** [oracle/graal#2645]
Imagine this simple application:

```
import java.net.URL;
import java.io.InputStream;
import java.net.*;
import java.io.*;
import java.lang.reflect.*;

public class HelloWorld {
	public static void main(String[] args) throws Exception { 
		System.out.println("Prefer IPv4? " + System.getProperty("java.net.preferIPv4Stack"));
		final Field implField = Class.forName("java.net.InetAddress").getDeclaredField("impl");
		implField.setAccessible(true);
		System.out.println("InetAddess#impl is " + implField.get(null).getClass());
		final InetAddress[] addrs = InetAddress.getAllByName("google.com");
		for (final InetAddress addr : addrs) {
			System.out.println("Address " + addr + " type " + addr.getClass().getName());
		}
		System.out.println("Done");
	} 
}

```
which gets the `InetAddress` of a host by name and prints it.

Build it into a native image using:

```
$GRAALVM_HOME/bin/native-image --no-server -cp . -H:ReflectionConfigurationFiles=reflection-config.json HelloWorld
```
where `reflection-config.json` contains:
```
[
  
  {
    "name" : "java.net.InetAddress",
    "fields" : [
      { "name" : "impl" }
    ]
  }
]
```

Now run the native application:
```
./helloworld -Djava.net.preferIPv4Stack=true
```
The output is:
```
Prefer IPv4? true
InetAddess#impl is class java.net.Inet6AddressImpl
Address google.com/172.217.31.206 type java.net.Inet4Address
Address google.com/2404:6800:4007:809:0:0:0:200e type java.net.Inet6Address
Done
```
As you can notice from the output, the internal implementation of `InetAddress` ends up using IPv6 even when `-Djava.net.preferIPv4Stack=true`. 

Doing the same in a regular JVM:

```
$GRAALVM_HOME/bin/java -Djava.net.preferIPv4Stack=true HelloWorld 
```
works fine and shows:
```
Prefer IPv4? true
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by HelloWorld (file:/Users/jaikiran/data/jaikiran/business/graal/substratevm/) to field java.net.InetAddress.impl
WARNING: Please consider reporting this to the maintainers of HelloWorld
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
InetAddess#impl is class java.net.Inet4AddressImpl
Address google.com/172.217.31.206 type java.net.Inet4Address
Done
```
I looked into the https://github.com/oracle/graal/blob/master/substratevm/LIMITATIONS.md document and I couldn't find anything which states that what's being attempted here won't work. So this appears to be a bug in native-image.

P.S: The only reason why the reflection is used in that sample code is to debug/prove that the internal detail of `InetAddress` class is using a IPv6 impl. That reflection code and config plays no other role in this issue.

**Comment by jaikiran** [comment]
Hello @dougxc, would it be possible to take a look into this issue? Having read the latest update on limitations (and the plan to address them), I don't see IPv4 support being considered as a limitation. So this issue looks like genuine bug.

**Comment by christianwimmer** [comment]
Fixed in https://github.com/oracle/graal/commit/c6cfbe276d34833e092bbe7c5b42938849db9ac7
System properties from the command line are now parsed earlier, so that the JDK initialization code reads the correct system property value.
