### ISSUE TITLE
Outdated debug options in Options.md 

### ISSUE THREAD

**Issue by galderz** [oracle/graal#2647]
[OPTIONS.md#debug-options](https://github.com/oracle/graal/blob/master/substratevm/OPTIONS.md#debug-options) appears to be outdated.

`HostedAssertions` does not appear to exist any more:

```
$ native-image --expert-options-all | grep Hosted
Error: Image build request failed with exit status 3
```

The options that exist now are `-H:±ExtendedAsserts` and `-H:±DetailedAsserts`, none of which are equivalent. Is the equivalent of `HostedAssertions` to pass `-J-ea` and/or `-J-esa`?

**Comment by olpaw** [comment]
Fixed by https://github.com/oracle/graal/commit/e6c493be6e4091d772011394621bf7064c18ca63
