### ISSUE TITLE
NoClassDefFOundError: [Z when running a compiled program

### ISSUE THREAD

**Issue by zcaudate** [oracle/graal#2660]
I'm having issues compiling jep with graalvm -> currently using the jdk11 version.

The program compiles okay but when I run the program and it tries to create a SharedInterpreter, it gives this error:

```
╰─$ target/ex11-jep
WARNING: Failed to get and cache frequent class types!
WARNING: Failed to get and cache primitive class types!
Exception in thread "Thread-1" java.lang.NoClassDefFoundError: [Z
        at com.oracle.svm.jni.functions.JNIFunctions.FindClass(JNIFunctions.java:326)
        at jep.Jep.init(Jep.java)
        at jep.Jep.<init>(Jep.java:278)
        at jep.SharedInterpreter.<init>(SharedInterpreter.java:56)
```

I'm not sure if it's an issue with graal, jep or my native image settings and would be thankful for any pointers

```
:opts     ["--report-unsupported-elements-at-runtime"
                            "--initialize-at-build-time"
                            "--allow-incomplete-classpath"
                            "--no-server"]}
```

**Comment by mukel** [comment]
You have to provide additional configuration files for the native image to include those classes, see [JNI.md](https://github.com/oracle/graal/blob/master/substratevm/JNI.md#reflection) and [REFLECTION.md](https://github.com/oracle/graal/blob/master/substratevm/REFLECTION.md#manual-configuration)

**Comment by zcaudate** [comment]
thanks @mukel, the error has `java.lang.NoClassDefFoundError: [Z` so how would I add a native boolean array to the config?

**Comment by zcaudate** [comment]
I think I get it. The native code being called is here:

```
https://github.com/ninia/jep/blob/master/src/main/java/jep/Jep.java#L329-L330
```

from here:

```
https://github.com/ninia/jep/blob/master/src/main/java/jep/Jep.java#L278-L279
```

In the JNI Config do I register the `jep.Jep` itself? and maybe some of the dependencies as well?

**Comment by mukel** [comment]
You must include all everything used by JNI/Reflection, this is a tedious trial an error process that you can easily automate with [the native image agent](https://www.graalvm.org/docs/Native-Image/user/CONFIGURE). The agent will give you a config to start from.

**Comment by zcaudate** [comment]
@mukel: The agent worked but I'm running into some issues. I'm not sure what is [going on](https://github.com/oracle/graal/issues/2724) with the current error I'm getting.

The sample repo is here:
https://github.com/zcaudate/sample-deploy

**Comment by cstancu** [comment]
Closing this in favor of https://github.com/oracle/graal/issues/2724.
