### ISSUE TITLE
Error "Fatal error: (null) (code 0)" deploying to iOS

### ISSUE THREAD

**Issue by jperedadnr** [oracle/graal#2663]
**Describe the issue**

Building native images for iOS with GraalVM and the Gluon Client plugin has been working fine for me for quite some time, until a few days ago that with the latest GraalVM 20.2.0-dev builds some of the apps started failing on runtime with the message `Fatal error: (null) (code 0)`, right after the app starts and `run_main` is invoked.

I managed to build GraalVM myself and get the same apps working, but if I modify certain conditions the app failed again.

**Steps to reproduce the issue**

From Mac OS, and with an iOS device,

1. **git clone --depth 1 https://github.com/jperedadnr/HelloWorldIOS**
2. **mvn clean client:compile**
3. **mvn client:link** This step will fail if there is no valid provisioning profile found. To sign the app, follow https://docs.gluonhq.com/client/#_ios_deployment, and run again.
4. These libraries are required for deployment: `libusbmuxd` and `libimobiledevice`, as explained [here](https://github.com/gluonhq/client-samples#additional-requirements).
5. With a connected iOS device, run: **mvn client:run**. 

**Describe GraalVM and your environment:**

 - GraalVM version: GraalVM CE 20.2.0-dev-20200707_0203 for [Mac](https://github.com/graalvm/graalvm-ce-dev-builds/releases/download/20.2.0-dev-20200707_0203/graalvm-ce-java11-darwin-amd64-20.2.0-dev.tar.gz)

 - JDK major version: **JAVA_HOME=$GRAALVM_HOME** (Java 11)
 - OS: **macOS Catalina 10.15.4**, target **iPhone X 13.4**
 - Architecture: host: **AMD64**, target: **ARM64**

**More details**

The output in the terminal should be something like:

```
[INFO] [SUB] 2020-07-09 11:09:55.317952+0200 helloWorld[58558:17253058] Done creating user.home at /var/mobile/Containers/Data/Application/80578DE9-390D-428B-BB25-309A173943FD/Library/gluon
[INFO] [SUB] Hello World!!
[INFO] [SUB] Process 58558 exited with status = 0 (0x00000000)
[INFO] result = true
```

(note there is no UI, the app won't show anything, it just starts, prints the message to the console, and exits)

However I get:

```
[INFO] [SUB] 2020-07-09 11:09:55.317952+0200 helloWorld[58558:17253058] Done creating user.home at /var/mobile/Containers/Data/Application/80578DE9-390D-428B-BB25-309A173943FD/Library/gluon
[INFO] [SUB] Fatal error: (null) (code 0)
[INFO] [SUB] Process 58558 exited with status = 9 (0x00000009) 
[INFO] result = true
```

**Comment by loicottet** [comment]
For the record: the trouble comes from using the page size of the host to align the heap section at compile time. As the iOS page size is 16K and not the regular 4K for macOS, a call to `mprotect` fails at runtime because of failed alignment requirements.
