### ISSUE TITLE
Debug info generator fails to find JDK sources for graal compiler

### ISSUE THREAD

**Issue by adinn** [oracle/graal#2679]
The debug info generator expects jdk11u sources to be listed in the JDK src.zip file with a path derived from the module name and the elements of the associated class's package name e.g. `java.base/java/lang/System.java`. Sources for modules jdk.internal.vm.compiler and jdk.internal.vm.ci are not always found because the path to the source can include two intervening elements, the name of the source group in the Graal repo source hierarchy and  `src`" e.g. `jdk.internal.vm.ci/jdk.vm.ci.meta/src/jdk/vm/ci/meta/JavaMethod.java` or `jdk.internal.vm.compiler/org.graalvm.compiler.hotspot/src/org/graalvm/compiler/hotspot/replacements/UnsafeLoadSnippets.java`.

The JDK source cache needs to special case lookups for classes in these modules (when running on jdk11+) so that all paths below the relevant module which end in `src` are used as roots for source file lookups.

This issue applies to the graal repo head running the native image generator with debug enabled on jdk11+ for all architectures.

**Comment by zakkak** [comment]
@adinn I think we can close this now

**Comment by adinn** [comment]
Agreed.
