### ISSUE TITLE
Segmentation failure (core image recorded) --- Program ends abruptly

### ISSUE THREAD

**Issue by tretonis** [oracle/graal#2684]
Ubuntu 20.04 LTS
client-maven-plugin
last release graalvm

Error 

After loading the native program it closes suddenly
and displays the message:
**Segmentation failure (core image recorded)**

**Comment by cstancu** [comment]
Please use the [Native Image issue template](https://github.com/oracle/graal/issues/new?assignees=&labels=bug%2C+native-image&template=1_issues_native_image.md&title=) and provide details necessary to reproduce.
