### ISSUE TITLE
Truffle Api

### ISSUE THREAD

**Issue by bhavyamakkar** [oracle/graal#2688]
org.graalvm.polyglot.PolyglotException: java.lang.NoSuchMethodError: com.oracle.truffle.api.profiles.ConditionProfile.create()Lcom/oracle/truffle/api/profiles/ConditionProfile;

**Comment by fniephaus** [comment]
It looks like you're running something linked against Truffle 20.2.0-dev on a GraalVM 20.1.0, which does not have `ConditionProfile.create()` yet (see [Changelog](https://github.com/oracle/graal/blob/master/truffle/CHANGELOG.md#version-2020)). Make sure the both versions match or use `createBinaryProfile()` as a workaround.
