### ISSUE TITLE
Inlined methods not referenceable from gdb when compiling with `-g`.

### ISSUE THREAD

**Issue by zakkak** [oracle/graal#2701]
**Describe the issue**
When compiling with `-g` to generate debug info, inlined methods are not properly handled by `native-image`'s debug info genarator, resulting in users being unable to reference them from `gdb`, e.g. to set a breakpoint.

**Steps to reproduce the issue**
```bash
$ cat <<EOF > HelloWorld.java
public class HelloWorld {
    public static void main(String[] args) {
        System.out.println("Hello World!");
    }
}
EOF
$ javac HelloWorld
$ native-image -g HelloWorld
$ gdb helloworld
Reading symbols from helloworld...
(gdb) b HelloWorld::main
Function "HelloWorld::main" not defined.
Make breakpoint pending on future shared library load? (y or [n])
```

**Describe GraalVM and your environment:**
 - GraalVM version: a17ccc50e838f59e69e0db89e72c65feac803cb5
 - JDK major version: **11**
 - OS: **Linux Fedora 32**
 - Architecture: **AMD64**

**More details**
According to DWARF v2.0.0 
> Each inline expansion of an inlinable subroutine is represented by a debugging information entry with the tag DW_TAG_inlined_subroutine.  Each such entry should be a direct child of the entry that represents the scope within which the inlining occurs.

At the moment graal uses only the following two tags though https://github.com/oracle/graal/blob/a17ccc50e838f59e69e0db89e72c65feac803cb5/substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/elf/dwarf/DwarfDebugInfo.java#L65-L69

**Comment by zakkak** [comment]
Please assign this issue to me, as I plan to work on fixing it.

**Comment by zakkak** [comment]
For reference I have compiled:
```c
#include "stdio.h"

__attribute__((always_inline))
void foo() {
    printf("Hello World!\n");
}

int main(int argc, char *argv[]) {
    foo();
    return 0;
}
```
with `gcc -gdwarf-2` and  I append the two entries of an inlined (by `gcc -g`) method named `foo` look like:

```
...
 <2><b7>: Abbrev Number: 7 (DW_TAG_inlined_subroutine)
    <b8>   DW_AT_abstract_origin: <0xd6>
    <bc>   DW_AT_low_pc      : 0x401146
    <c4>   DW_AT_high_pc     : 0x401151
    <cc>   DW_AT_call_file   : 1
    <cd>   DW_AT_call_line   : 9
    <ce>   DW_AT_call_column : 5
...
 <1><d6>: Abbrev Number: 8 (DW_TAG_subprogram)
    <d7>   DW_AT_external    : 1
    <d8>   DW_AT_name        : foo
    <dc>   DW_AT_decl_file   : 1
    <dd>   DW_AT_decl_line   : 4
    <de>   DW_AT_decl_column : 6
    <df>   DW_AT_inline      : 1        (inlined)
...
```

We see that the first entry contains information about the location of the inlining and the second entry contains information about the method (also marking it as inlined).

**Comment by zakkak** [comment]
In addition to the aforementioned issue:

The current implementation creates a compilation unit for each class and adds a debug entry for each graal compilation (e.g. each compiled method). Then different segments of each compiled method are attributed to different classes/methods (due to inlining) through the line table. This results in gdb producing relevant output regarding the current location but failing to produce a representative callgraph when using backtrace. For instance:

```
$ gdb hello.hello
(gdb) b main
(gdb) r
....
(gdb) ni
41              throw new IllegalStateException("Cannot access address of global data during native image generation");
(gdb) bt
#0  com.oracle.svm.core.code.IsolateEnterStub::JavaMainWrapper_run_5087f5482cc9a6abc971913ece43acb471d2631b(int, org.graalvm.nativeimage.c.type.CCharPointerPointer)(void) () at com/oracle/svm/core/c/CGlobalData.java:41
```

We see that `throw new IllegalStateException("Cannot access address of global data during native image generation");` is indeed at `com/oracle/svm/core/c/CGlobalData.java:41` but there is no info regarding the caller (which is `com.oracle.svm.core.JavaMainWrapper.EnterCreateIsolateWithCArgumentsPrologue#enter` at `com/oracle/svm/core/JavaMainWrapper.java:268`).

Producing debug entries for inlined methods should also tackle the above issue.

**Comment by Karm** [comment]
@zakkak Is this still an issue? I recon I could break / list in a method that was surely inlined...  gonna try to be sure.

**Comment by zakkak** [comment]
Yes, this is still an issue:
```
$ /opt/jvms/graalvm-ce-java11-20.3.0/bin/native-image -g HelloWorld 
$ gdb helloworld
(gdb) b HelloWorld::main
Function "HelloWorld::main" not defined.
Make breakpoint pending on future shared library load? (y or [n]) n
(gdb) b HelloWorld.main
Function "HelloWorld.main" not defined.
Make breakpoint pending on future shared library load? (y or [n]) n
(gdb) info func HelloWorld
All functions matching regular expression "HelloWorld":
(gdb) info func main(
All functions matching regular expression "main(":

File com/oracle/svm/core/hub/DynamicHub.java:
        void com.oracle.svm.core.hub.DynamicHub.getProtectionDomain(void);
(gdb)
```
