### ISSUE TITLE
Auto vectorization support (dependency graph algorithm)

### ISSUE THREAD

**Issue by rwestrel** [oracle/graal#2703]
I've been experimenting with an auto-vectorization pass based on a common family of algorithms (first few chapters of this book: https://www.elsevier.com/books/optimizing-compilers-for-modern-architectures/allen/978-0-08-051324-9). Instead of requiring extensive unrolling such as the superword algorithm that C2 uses (and that https://github.com/oracle/graal/pull/1692 proposes to port to Graal), the new pass builds a dependency graph for each leaf counted loops and vectorizes the loop directly if possible. One benefit of this approach is that it's self contained (no need for unrolling to have its own set of heuristics to prepare for vectorization the way C2 does) and should be easier to review. The intent is not for this work to replace an implementation of the superword algorithm. The two work best on different loop patterns and are complementary.
Anyway, this is still a work in progress but I intend to submit a PR once it is ready.

**Comment by 8Keep** [comment]
Any update on this?

**Comment by fernando-valdez** [comment]
@dougxc, what are your thoughts on this?

**Comment by dougxc** [comment]
We can close this issue and re-open it when an associated PR is submitted.
