### ISSUE TITLE
Spring native image issue

### ISSUE THREAD

**Issue by halimpuckjava** [oracle/graal#2707]
hi

i used GraalVM Version 20.1.0 (Java Version 11.0.7) with spring boot 2.4.0-snapshot, os = ubuntu 20.04 and java 11.0.7

when try to create native image with spring boot i found this issue:

```
Caused by: java.lang.ClassNotFoundException: jdk.vm.ci.services.Services
```

i check this class in jdk 11.0.7 and i found it, so what's wrong and why graalvm not found this class when it create native image ??

**Comment by jaikiran** [comment]
Hello @halimpuckjava, can you paste the complete exception stacktrace that you see for this error?

**Comment by cstancu** [comment]
Please reopen if this is still reproducible with the latest Spring/GraalVM versions.
