### ISSUE TITLE
Starting a Eclipse RCP from within eclipse triggers a breakpoint

### ISSUE THREAD

**Issue by spirritus** [oracle/graal#2710]
Hi there,

we found an issue that appears with the graalvm but not the openjdk.
We develop eclipse rcp applications. For that purpose we start the eclipse rcp from within eclipse (in debug mode).
When running on a graal vm 20.1.0 there is an exception thrown, a thread is halted and the debugger starts.
See picture for thread and code.
When starting the same application using the openjdk this does not happen.
If I remember correctly that issue did also not appear with GraalVM 20.0.0.

Regards

System:
GraalVM 20.1.0 
Debian 10, Windows 7 and Windows 10
amd64

![GraalVm-jdk internal loader BuiltinClassLoader - Eclip](https://user-images.githubusercontent.com/1154316/88391668-ee122880-cdba-11ea-984c-a5201eb8db10.png)

**Comment by fniephaus** [comment]
I've got the same issue, but am using a LabsJDK. Interesting, I thought my Eclipse setup is screwed up.

**Comment by spirritus** [comment]
I did not test with openjdk 11.0.7 - it worked with openjdk 11.0.6.

**Comment by dougxc** [comment]
@spirritus what class is not being found? What happens if you let the thread continue?
I suspect this is a side-effect of the fact that libgraal still loads certain compiler classes. @tkrodriguez is currently working a solution to remove this behavior.

**Comment by spirritus** [comment]
cn is: org.graalvm.compiler.hotspot.management.SVMToHotSpotEntryPoints
resolve is: false
c is: null

If i let it continue the code works fine in most cases (depends on when i hit continue, better later than earlieer)
Glad to hear a solution is in the making.

**Comment by dougxc** [comment]
Turns out that this exception is the one that occurs when libgraal tries to inject classes into HotSpot for the purpose of implementing JMX bean in libgraal. We are thinking of a way to avoid it.
Note that you should only hit this if you have Eclipse configured to catch CNFEs.

**Comment by tzezula** [comment]
The exception is  harmless.
The `CNFE` is throw to an isolate when the management classes are not yet defined in the HotSpot and the isolate should define them (it's the first isolate).
Another possibility to "synchronize" these isolates is implementing spin lock over SVM `CGlobalData`.

**Comment by tzezula** [comment]
Fixed by https://github.com/oracle/graal/commit/60995305b2e5cfbf944308ae2c3635a82bfe4dc0

**Comment by spirritus** [comment]
With graalvm 20.2 another Exception is thrown:
org.graalvm.compiler.hotspot.management.JMXToLibGraalCalls
