### ISSUE TITLE
GraalVM does not work on Solaris 10 SPARC

### ISSUE THREAD

**Issue by pmarino90** [oracle/graal#272]
Hi,
I had the chance to test GraalVM to run a small node application on a Solaris 10 SPARC server.
I downloaded the latest version available on the Oracle's website (which seems to be behind the Mac and linux version).

I extracted the package and set the environment variables in order to have the binaries into the path, when I issue a `node -v` I get the following output:
```
root@210 # node -v
ld.so.1: node: fatal: libsocket.so.1: version 'SUNW_1.7' not found (required by file /opt/test-node/graalvm-0.25/language/js/bin/node)
ld.so.1: node: fatal: libsocket.so.1: open failed: No such file or directory
Killed
```
It seems that the binary requires a different version of `libsocket`.

This is the `uname` output
```
root@210 # uname -a
SunOS rtos210 5.10 Generic_150400-55 sun4v sparc SUNW,SPARC-Enterprise-T5220
```

Did someone get the same issue?

Thank you!

**Comment by dougxc** [comment]
Hi @pmarino90 , we only build and test GraalVM on Solaris 11. We will see if it's possible to add an OS check in the launcher or signal handler to improve the error message if run on an incompatible OS. (/cc @gilles-duboscq , @ansalond).

**Comment by dougxc** [comment]
@pmarino90 , please reopen this issue if you have further comments.
