### ISSUE TITLE
Issues while converting R into native-image

### ISSUE THREAD

**Issue by dhruba15** [oracle/graal#2725]
I am trying to deploy my functions written in R onto Graalvm as native image.
Below are the approaches I am following and am not able to proceed because of the challenges :-
1) Calling R code from Renjins - The challenges I found with this approach are that libraries like fread, data.table are not supported so alternative need to be used.
2) Deployed native R code into graalvm - I see the same challenges with this approach to support libraries like fread, data.table.

Also, please let me know how to convert the R script into native-image in GraalVm for AOT compilation. Thank you.

Please help me with a solution approach.

**Comment by steve-s** [comment]
Hello,

you are right that there is a challenge w.r.t. supported R packages in both cases: with Renjin and with GraalVM R engine also known as "FastR". R packages, especially packages like `data.table` and `fread`, often misuse or abuse the R extensions API and it is nearly impossible for an alternative R implementation to support all the packages out there at given point in time.

That being said, FastR can run `data.table` to the extent that `examples("data.table")` works. We do not do any other testing of `data.table` and we have not looked at `fread` -- it may or may not work. You can test your concrete use-cases and submit concrete issues to FastR: github.com/oracle/fastr/issues. Please read the issue template carefully if you want to increase the chances that your issue will be addressed in a timely manner.

Moreover, please bear in mind that FastR is in an experimental state and building native-image of FastR is even "more" experimental as the post-installation message of FastR explains:

```
The R component comes without native image by default. If you wish to build the native image, which provides faster startup, but slightly slower peak performance, then run the following:

    gu rebuild-images R

The native image is then used by default. Pass '--jvm' flag to the R or Rscript launcher to use JVM instead of the native image. Note that the native image is not stable yet and is intended for evaluation and experiments for curious users. Some features may not work in the native image mode. Most notably, the --polyglot switch works only in JVM mode (when --jvm is used).

See http://www.graalvm.org/docs/reference-manual/languages/r for more.
```

To use FastR in native-image of your Java application, you can just use the `Context` API in you Java code (https://www.graalvm.org/docs/reference-manual/embed/) and then build the native-image out of it passing flag `--language:R`.
