### ISSUE TITLE
The GraalVM directory ... is invalid when using GraalVM Updater

### ISSUE THREAD

**Issue by jultabary** [oracle/graal#2731]
**Describe GraalVM and your environment :**

- GraalVM version or commit id if built from source: [20.1]
- CE or EE: [CE]
- JDK version: [JDK11.0.7]
- OS and OS Version: macOS Catalina (10.15.6)
- Architecture: [amd64]

I have just installed GraalVM for MacOS. (graalvm-ce-java11-darwin-amd64-20.1.0.tar.gz)

The `java` command works well and `java --version` confirms that i'm using graalVM JDK.

```
openjdk 11.0.7 2020-04-14
OpenJDK Runtime Environment GraalVM CE 20.1.0 (build 11.0.7+10-jvmci-20.1-b02)
OpenJDK 64-Bit Server VM GraalVM CE 20.1.0 (build 11.0.7+10-jvmci-20.1-b02, mixed mode, sharing)
```

I have not set any other env variable regarding JAVA or GRAAL.

when i call command `gu` i have the following return :

```
GraalVM Component Updater v2.0.0

Usage: 
	gu info [-cClLnprstuvV] <param>         prints info about specific component (from file, URL or catalog)
	gu available [-aClvV] <expr>            lists components available in catalog
	gu install [-0CcDfiLMnosruvyxY] <param> installs a component package
	gu list [-clv] <expression>             lists installed components, or components from catalog
	gu remove [-0DfMxv] <id>                uninstalls a component
	gu update [-cCnLsux] [<ver>] [<param>]  upgrades to recent GraalVM
	gu rebuild-images                       rebuilds native images. Use -h for detailed usage
...
```

when i call command `gu` with a param -> `gu --version`, or `gu install` it returns
```
Error: The GraalVM directory /Library/Java/JavaVirtualMachines/graalvm-ce-java11-20.1.0/Contents is invalid.
```

**Comment by jaikiran** [comment]
Hello @jultabary, what's the output of:

```
echo $JAVA_HOME
```
It should be `/Library/Java/JavaVirtualMachines/graalvm-ce-java11-20.1.0/Contents/Home`. It looks like in your case, the `/Home` part is missing from it.

**Comment by jultabary** [comment]
echo $JAVA_HOME return empty.
In the other hand `/usr/libexec/java_home` (specific to macosx) command returns 
```
/Library/Java/JavaVirtualMachines/graalvm-ce-java11-20.1.0/Contents/Home
```
If i define the variable like this
export JAVA_HOME=/Library/Java/JavaVirtualMachines/graalvm-ce-java11-20.1.0/Contents/Home

`echo $JAVA_HOME` returns correctly
```
/Library/Java/JavaVirtualMachines/graalvm-ce-java11-20.1.0/Contents/Home
```

,but the command `gu --version` still returns
```
Error: The GraalVM directory /Library/Java/JavaVirtualMachines/graalvm-ce-java11-20.1.0/Contents is invalid.
```

tt quite strange because i have no issue with `java` command. I have also try to run a maven project with this settings and i have no issue.

**Comment by jultabary** [comment]
I have tried to test the following settings. It is working now better.

I have set GRAAL_HOME environment variable:
```
export GRAAL_HOME=/Library/Java/JavaVirtualMachines/graalvm-ce-java11-20.1.0/Contents/Home
```

command `gu --version` now returns
```
GraalVM Updater 20.1.0
```
and command `gu available`returns

```
Downloading: Component catalog from www.graalvm.org
ComponentId              Version             Component name      Origin 
--------------------------------------------------------------------------------
llvm-toolchain           20.1.0              LLVM.org toolchain  github.com
native-image             20.1.0              Native Image        github.com
python                   20.1.0              Graal.Python        github.com
R                        20.1.0              FastR               github.com
ruby                     20.1.0              TruffleRuby         github.com
wasm                     20.1.0              GraalWasm           github.com
```

But command `gu install native-image` (it is same for other components) ask me for privilege rights, so i try `sudo -E gu install native-image`and it is working.

It is quite strange that i have had to define GRAAL_HOME env ?

**Comment by jaikiran** [comment]
> Is it quite strange that i had to define GRAAL_HOME env ?

Yes, it is strange IMO. I have never set it myself nor have I seen it documented (https://www.graalvm.org/docs/getting-started/macos#installation-on-macos-platforms)

**Comment by veixuan** [comment]
> I have tried to test the following settings. It is working now better.
> 
> I have set GRAAL_HOME environment variable:
> 
> ```
> export GRAAL_HOME=/Library/Java/JavaVirtualMachines/graalvm-ce-java11-20.1.0/Contents/Home
> ```
> 
> command `gu --version` now returns
> 
> ```
> GraalVM Updater 20.1.0
> ```
> 
> and command `gu available`returns
> 
> ```
> Downloading: Component catalog from www.graalvm.org
> ComponentId              Version             Component name      Origin 
> --------------------------------------------------------------------------------
> llvm-toolchain           20.1.0              LLVM.org toolchain  github.com
> native-image             20.1.0              Native Image        github.com
> python                   20.1.0              Graal.Python        github.com
> R                        20.1.0              FastR               github.com
> ruby                     20.1.0              TruffleRuby         github.com
> wasm                     20.1.0              GraalWasm           github.com
> ```
> 
> But command `gu install native-image` (it is same for other components) ask me for privilege rights, so i try `sudo -E gu install native-image`and it is working.
> 
> Is it quite strange that i had to define GRAAL_HOME env ?

works for me, thanks

**Comment by Aleksey2093** [comment]
> export GRAAL_HOME=/Library/Java/JavaVirtualMachines/graalvm-ce-java11-20.1.0/Contents/Home

it don't  work for me :(

```
192:~ alex$ java -version
openjdk version "17.0.3" 2022-04-19
OpenJDK Runtime Environment GraalVM CE 21.3.2 (build 17.0.3+7-jvmci-21.3-b14)
OpenJDK 64-Bit Server VM GraalVM CE 21.3.2 (build 17.0.3+7-jvmci-21.3-b14, mixed mode, sharing)
192:~ alex$ gu list
Error: The GraalVM directory /Library/Java/JavaVirtualMachines/graalvm-ce-java17-21.3.2/Contents is invalid.
```

I added to .bash_profile:
```
export JAVA_HOME="/Library/Java/JavaVirtualMachines/graalvm-ce-java17-21.3.2/Contents/Home"
export GRAAL_HOME="/Library/Java/JavaVirtualMachines/graalvm-ce-java17-21.3.2/Contents/Home"
export GRAALVM_HOME="/Library/Java/JavaVirtualMachines/graalvm-ce-java17-21.3.2/Contents/Home"
export PATH="/Library/Java/JavaVirtualMachines/graalvm-ce-java17-21.3.2/Contents/Home/bin:${PATH}"
```
