### ISSUE TITLE
crash on win7 (using JNI) - works on win10

### ISSUE THREAD

**Issue by spirritus** [oracle/graal#2741]
Hey there,

we use some native code (c/c++) and java bindings to access that code.
The used libraries are VTK (vtk.org) and OpenCascase (opencascade.com).

Some calls to the native code chrash graalvm on windows 7. The identical code (I copied the source and the libs) runs fine on windows 10. 

Compiler was VS2019 on windows 10, graalvm 20.0.1.

What further  informatione do you need to debug this?

Best regards
Jens
[hs_err_pid20248.log](https://github.com/oracle/graal/files/5047992/hs_err_pid20248.log)

**Comment by spirritus** [comment]
Looking at the log, is it possible that the ucrt (dlls) packaged with graal and the ucrt (dlls) packaged with our code is somehow responsible for the crash?

**Comment by pejovica** [comment]
Closing as resolved.
