### ISSUE TITLE
[community] Labeling of Quarkus related issues

### ISSUE THREAD

**Issue by zakkak** [oracle/graal#2767]
**Feature request**

Now that graal has a github action testing the latest Quarkus release with the latest Graal (#2349) and a [new label 'quarkus'](https://github.com/oracle/graal/issues?q=is%3Aopen+is%3Aissue+label%3Aquarkus), it would be nice to have some help in labelling all the existing quarkus-related [issues](https://github.com/oracle/graal/issues?q=is%3Aissue+is%3Aopen+quarkus)/[PRs](https://github.com/oracle/graal/pulls?q=is%3Apr+is%3Aopen+quarkus) as well as the future ones.

**Is your feature request related to a problem? Please describe.**
Currently there is no way for third parties 

**Describe the solution you'd like.**
Ideally I would like this to be automated.
Quarkus is using an [autolabel workflow](https://github.com/quarkusio/quarkus/blob/master/.github/workflows/autolabel.yml) that runs periodically and automatically labels issues matching some criteria. Using a similar workflow would be of great help.

**Describe who do you think will benefit the most.**
* GraalVM contributors
* Quarkus contributors

**Describe alternatives you've considered.**
Alternatively, we could have a new issue template for quarkus-related issues and possibly give "Triage" permissions to some Quarkus contributors.

**Express whether you'd like to help contributing this feature**
I would happily contribute the workflow and configuration for the autolabel part.

Relates to #2764

**Comment by mcraj017** [comment]
@zakkak Thanks for suggestion,
We will work on it and let you know our thoughts

**Comment by dougxc** [comment]
@RoxaBee I like the idea of the automated labelling of Quarkus issues - do you see any problem with it?

**Comment by dougxc** [comment]
@zakkak I like the automated labelling. I see it has a dependency on `docker://maxandersen/jbang-issuelabeler`. Can you please explain more about that dependency.

**Comment by zakkak** [comment]
> @zakkak I like the automated labelling. I see it has a dependency on `docker://maxandersen/jbang-issuelabeler`. Can you please explain more about that dependency.

Hello @dougxc to label the issues Quarkus is using the issuelabeler GitHub action. GitHub actions can be written either as:
* javascript actions (most popular, and that's the format of the official actions, like checkout)
* docker container actions (this enables devs to write the action in the language of their choice)
* composite run steps actions (that's fairly new, and allows simple steps to be packaged in an action for reuse across workflows)

For more info [see here](https://docs.github.com/en/actions/creating-actions)

Now the issuelabeler action is a docker container action (thus the dependency on docker://maxandersen/jbang-issuelabeler).
The source code of the action is available in [this repo](https://github.com/maxandersen/jbang-issuelabeler) (it contains both the action source, the dockerfile and the scripts that generate the docker image).
To have a look at what the action does please [see the java source code](https://github.com/maxandersen/jbang-issuelabeler/blob/master/issue_labeler.java)

**Comment by dougxc** [comment]
@RoxaBee please update here once we know how to assign the Triage role to our Quarkus collaborators.

**Comment by RoxaBee** [comment]
Our policy is to only allow GitHub and in-org published actions. There is a GitHub published issue labeling action.Looking at the code this uses GITHUB_TOKEN which is overprivileged since it allows full write access to a repo. Any action that does labeling should really run with an Oauth token that has triage permission level. I am following up on this.

However we can have as previously suggested we can have a new issue template for quarkus-related issues and possibly give "Triage" permission to a Quarkus contributors. That Triage permission level is not currently available in our org but will be soon.

**Comment by RoxaBee** [comment]
Yes we can now give Triage permissions to Quarkus contributors! Please someone email me or slack me.

**Comment by zakkak** [comment]
Triage permissions have now been granted. Thank you!
