### ISSUE TITLE
[Quarkus-CI] Maven-tooling test failures

### ISSUE THREAD

**Issue by zakkak** [oracle/graal#2783]
**Describe the issue**
The `Maven Tooling` integration test is failing in https://github.com/oracle/graal/blob/master/.github/workflows/quarkus.yml
See https://github.com/oracle/graal/runs/1019872326?check_suite_focus=true#step:17:1134

This is a known issue being tracked here https://github.com/quarkusio/quarkus/issues/11493

**Comment by dougxc** [comment]
Why do we need an issue here if it's already being tracked elsewhere?

**Comment by zakkak** [comment]
Since this is an error appearing in this repository I thought we needed an issue to track it even if it's being worked on elsewhere.

I see the following benefits in doing this:
1. In case someone from the graal community wants to see why the tests are not passing they can easily land on this issue by searching in this repo. Otherwise they would need to search the Quarkus repo instead. Additionally, in this case the linkage between the two issues is obvious but there will probably be other cases where that linkage might not be obvious (so even a search in Quarkus repo want help)
2. Even when the upstream fix lands and solves the problem there, we still need to verify that it's also fixes the issue we are seeing here.

The way I see it there can be at least 4 causes for the Quarkus tests to fail:
1. Something broke in Graal
2. Something changed in Graal and breaks compatibility with Quarkus
3. Something is broken in Quarkus
4. Something is wrong in the CI pipeline/workflow 

If you prefer we could just track 1, 2 and 3 here, although 2 might sometimes be easily fixed in Quarkus as well.

**Comment by dougxc** [comment]
Ok, sounds reasonable. For such issues, I then assign them to you.

**Comment by zakkak** [comment]
The `Maven Tooling` integration test is no longer failing. Unfortunately, due to #3272 I was not able to track when and how it stopped appearing.
