### ISSUE TITLE
NoSuchBeanDefinitionException even with reflection and resource configuration

### ISSUE THREAD

**Issue by sendev1** [oracle/graal#2799]
**Describe the issue**
I am using native-image-agent to generate config files to create native image. I am using spring boot application to create native image.

I am getting `Unsatisfied dependency expressed through constructor parameter 1; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'com.commons.http.ssl.KeystoreConfig' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Qualifier}.` when running native image. But I see that KeystoreConfig is present in reflect-config.json and resource-config.json.

```
reflect-config.json
{
  "name":"com.commons.http.ssl.KeystoreConfig",
  "allDeclaredMethods":true,
  "allPublicMethods":true
},
{
  "name":"com.commons.http.ssl.KeystoreConfigImpl",
  "allDeclaredFields":true,
  "allDeclaredMethods":true,
  "allDeclaredConstructors":true
}
```
resource-config.json
```
{"pattern":"\\Qcom/commons/http/ssl/KeystoreConfig.class\\E"}, 
{"pattern":"\\Qcom/commons/http/ssl/KeystoreConfigImpl.class\\E"}, 
```

**Describe GraalVM and your environment:**
 - GraalVM version 20.3-dev
 - JDK major version: 8
 - OS: windows
 - Architecture: intel

**Comment by fernando-valdez** [comment]
Hello @sendev1 Can you please share a reproducer to I can take a closer look at this issue?

**Comment by sendev1** [comment]
Hi @fernando-valdez due to restrictions I would not able to share code. Kindly let me know if you need any additional information.

**Comment by sendev1** [comment]
The KeystoreConfig(interface) and KeystoreConfigImpl are present inside a jar and jar is added into class path during image generation.

KeystoreConfigImpl is defined with @Component
```
@Component("keystoreConfig")
public final class KeystoreConfigImpl
```

I have org.springframework.experimental:spring-graalvm-native and org.springframework:spring-context-indexer in my gradle dependency and I would expect that component keystoreConfig should be identified during native image build. But for some reason the component is ignored.

I am not sure my expectation is correct but I could not see KeystoreConfigImpl inside the below log block.

```
Computed spring.components is
vvv
.
.
.
^^^
```

**Comment by fernando-valdez** [comment]
I understand if you cannot share your code. Is it possible to set up a very simple (shareable) project that has this error?

Not having a reproducer will make the testing/diagnosis process really slow.

**Comment by sendev1** [comment]
I generated spring.components in the dependency jar using spring-indexer and started using jar with spring components and that helped me to over come this issue.
