### ISSUE TITLE
How realistic is it to AOT Android applications?

### ISSUE THREAD

**Issue by thezhangwei** [oracle/graal#280]
Hi, 

I'm been out of loop for a while now.. :)
I'm not quite sure about the current status of SVM. Can it AOT all Truffle language VMs now?
How realistic do you think it is to use SVM to AOT a portion of an Android app?
To contribute I still need to sign a CLA right?

Thanks in advance!

**Comment by vjovanov** [comment]
Hi, 

Yes, at the moment SVM can AOT all language VMs that are built by us. 

It is very realistic, however, Android has not been our priority and we have not tried it out yet. There will certainly be things to fix, but overall, most of the hard work is already done. 

Yes, to contribute you need sign the Oracle CLA. The process simple and it is described here: 
 
  http://www.oracle.com/technetwork/community/oca-486395.html
 
Let me know if you need any further information.
