### ISSUE TITLE
nodejs: Running Meteor's production bundle throws an assertion failed exception

### ISSUE THREAD

**Issue by doctorpangloss** [oracle/graal#2806]
**Describe the issue**
An empty `meteor` project will not run on Graal's nodejs.

It would appear the `node-fibers` package is the culprit.

**Steps to reproduce the issue**

On **macOS**:

```
sdk install java 20.2.0.r11-grl
sdk use java 20.2.0.r11-grl
curl https://install.meteor.com/ | sh
meteor create test-meteor
cd test-meteor
meteor build --directory ../test-build
cd ../test-build
# you have lots of ways to run mongo, but you don't have to bother to just see the error
#   brew tap mongodb/brew
#   brew install mongodb-community@3.6
#   mkdir -pv mongo && mongod --dbpath mongo &
#   export MONGO_URL='mongodb://localhost:27017/test'
(cd programs/server && npm install)
node main.js
```

Observe the following console output:

```
Assertion failed: (thread_data_key != 0x7777), function find_thread_id_key, file ../src/coroutine.cc, line 120.
[1]    16939 abort      node main.js
```

**Describe GraalVM and your environment:**
 - GraalVM version: 20.2.0
 - JDK major version: 11
 - OS: macOS Catalina
 - Architecture: AMD64

**Comment by oubidar-Abderrahim** [comment]
Thank you for reporting this, I will look into it.

**Comment by oubidar-Abderrahim** [comment]
`node-fibers` contains some native parts that rely heavily on low-level implementations of the V8 engine. Unfortunately, these hacks do not work and cannot be replicated on Node in GraalVM (where V8 is replaced by GraalJS).

Note that even the author of fibers admits that his package is obsolete and that its use should be avoided if possible: https://github.com/laverdet/node-fibers
