### ISSUE TITLE
nodejs: create-react-app development starts slow

### ISSUE THREAD

**Issue by doctorpangloss** [oracle/graal#2807]
**Describe the issue**

`create-react-app`'s development server is very slow.

**Steps to reproduce the issue**

On **macOS**:

```
sdk install java 20.2.0.r11-grl
sdk use java 20.2.0.r11-grl
npx create-react-app my-app
cd my-app
npm start
```

Graal log:

Approximately 120s:
```
Starting the development server...
```

```

You can now view my-app in the browser.

  Local:            http://localhost:3000
  On Your Network:  http://10.0.0.194:3000

Note that the development build is not optimized.
To create a production build, use npm run build.

```

**Describe GraalVM and your environment:**
 - GraalVM version: 20.2.0
 - JDK major version: 11
 - OS: macOS Catalina
 - Architecture: AMD64

**Comment by oubidar-Abderrahim** [comment]
This might be related to #2805

**Comment by oubidar-Abderrahim** [comment]
There is a known issue related to warm-up in GraalVM; while NodeJS is interpreted and can start fast on a V8 engine, GraalJS is compiled and takes time to do so. there is a lot of efforts done in this area to reduce the start-up time but we do not expect it to be as fast as NodeJS.

The real peak of performance is seen in long-running Node applications, applications that consume resources and memory. There, GraalVM's optimizations make it better performing in the long term.

**Comment by oubidar-Abderrahim** [comment]
Same as #2805; closed as duplicated.
