### ISSUE TITLE
GraalVM src.zip is missing source files

### ISSUE THREAD

**Issue by ericlabouve** [oracle/graal#2808]
Both Linux and Mac version for graalvm-ee-java11-20.2.0 are missing source files from src.zip that are present in jmod files. For starters, java.base is missing all the javax.net.ssl sources whereas they are clearly present in jmods/java.base.jmod

**Steps to reproduce the issue**
Download and unzip graalvm-ee-java11-20.2.0 from Oracle: https://www.oracle.com/downloads/graalvm-downloads.html?selected_tab=20 (consider GRAAL_HOME as the root directory) then unzip lib/src.zip. Step into the new GRAAL_HOME/lib/src/ directory and search for any reference to javax.net.ssl:
`> find . | grep javax.net.ssl`
There should be no output. 

Next step into GRAAL_HOME/jmods, list the contents of java.base.jmod and search for any references to javax.net.ssl:
```
> jmod list java.base.jmod | grep "javax/net/ssl"
classes/javax/net/ssl/HandshakeCompletedListener.class
classes/javax/net/ssl/SSLEngineResult.class
classes/javax/net/ssl/DefaultSSLServerSocketFactory.class
classes/javax/net/ssl/TrustManagerFactorySpi.class
classes/javax/net/ssl/SSLContextSpi.class
classes/javax/net/ssl/HttpsURLConnection.class
classes/javax/net/ssl/SSLEngine.class
classes/javax/net/ssl/SSLKeyException.class
classes/javax/net/ssl/SSLEngineResult$Status.class
classes/javax/net/ssl/SSLEngineResult$HandshakeStatus.class
classes/javax/net/ssl/CertPathTrustManagerParameters.class
classes/javax/net/ssl/SSLPeerUnverifiedException.class
classes/javax/net/ssl/SSLSocketFactory$1.class
classes/javax/net/ssl/KeyManagerFactory$1.class
classes/javax/net/ssl/SSLSession.class
classes/javax/net/ssl/SSLSessionContext.class
classes/javax/net/ssl/SSLException.class
classes/javax/net/ssl/SSLSocketFactory.class
classes/javax/net/ssl/StandardConstants.class
classes/javax/net/ssl/X509KeyManager.class
classes/javax/net/ssl/TrustManagerFactory$1.class
classes/javax/net/ssl/KeyManager.class
classes/javax/net/ssl/SNIServerName.class
classes/javax/net/ssl/DefaultSSLSocketFactory.class
classes/javax/net/ssl/SSLServerSocketFactory.class
classes/javax/net/ssl/HostnameVerifier.class
classes/javax/net/ssl/KeyManagerFactory.class
classes/javax/net/ssl/SSLProtocolException.class
classes/javax/net/ssl/X509TrustManager.class
classes/javax/net/ssl/SNIMatcher.class
classes/javax/net/ssl/TrustManagerFactory.class
classes/javax/net/ssl/SSLSessionBindingEvent.class
classes/javax/net/ssl/SSLPermission.class
classes/javax/net/ssl/KeyManagerFactorySpi.class
classes/javax/net/ssl/HttpsURLConnection$DefaultHostnameVerifier.class
classes/javax/net/ssl/X509ExtendedTrustManager.class
classes/javax/net/ssl/SSLHandshakeException.class
classes/javax/net/ssl/KeyStoreBuilderParameters.class
classes/javax/net/ssl/SNIHostName.class
classes/javax/net/ssl/SSLSessionBindingListener.class
classes/javax/net/ssl/HandshakeCompletedEvent.class
classes/javax/net/ssl/SSLParameters.class
classes/javax/net/ssl/ManagerFactoryParameters.class
classes/javax/net/ssl/SSLSocket.class
classes/javax/net/ssl/ExtendedSSLSession.class
classes/javax/net/ssl/SSLServerSocket.class
classes/javax/net/ssl/SNIHostName$SNIHostNameMatcher.class
classes/javax/net/ssl/TrustManager.class
classes/javax/net/ssl/SSLContext.class
classes/javax/net/ssl/X509ExtendedKeyManager.class
```

There are many more examples other than javax.net.ssl but in general, the source files within src.zip are sparse and incomplete. It would be helpful to ship all sources with graal. Thank you.

**Comment by oubidar-Abderrahim** [comment]
Actually, this is not a bug. In GraalVM EE we ship the same source code provided in OracleJDK. some internal classes like javax.net.ssl are not shipped in OracleJDK and thus, are not shipped in GraalVM EE too.

The GraalVM team cannot expose source file of internal classes to the JDK unless the Java team do so.

**Comment by ericlabouve** [comment]
@oubidar-Abderrahim is it possible for me to get in contact with your Java team? Is there any way to download the full source? OpenJDK's version of src.zip comes with all the .java files from the sdk.

**Comment by dougxc** [comment]
OracleJDK 11 has been closed source since April 16, 2019 (https://www.oracle.com/java/technologies/javase-jdk11-downloads.html). If you need Java sources for everything in GraalVM, I recommend using GraalVM CE.

**Comment by oubidar-Abderrahim** [comment]
@ericlabouve, Sure, it is possible to get in contact with the Java team but as @dougxc mentioned. OracleJDK is closed source and cannot be made public under any circumstances. GraalVM CE, on the other hand, is based on OpenJDK which is open source.

**Comment by shaunsmith** [comment]
Oracle does have source licenses available for both Oracle Java SE and Oracle GraalVM Enterprise for customers who need access to source.  You can reach out to your Oracle sales contact or we can put you in touch.
