### ISSUE TITLE
Xcheck:jni option misses validation of usage of signature value as NULL

### ISSUE THREAD

**Issue by sjmini** [oracle/graal#2815]
**Describe the issue**
GraalVM misses validation in usage of NULL value when calling GetFieldID JNI function.
Because of the NULL value, a segmentation fault occurs.
According to JNI specification, GetFieldID function receives the field signature as 4th argument, and the value must not be NULL.
https://docs.oracle.com/en/java/javase/11/docs/specs/jni/functions.html#GetFieldID

However, GraalVM accepts the NULL value leading to a segmentation fault.
GraalVM does not validate the NULL value even when the -Xcheck:jni is enabled.

**Steps to reproduce the issue**
Please include both build steps as well as run steps
1. Call GetFieldID JNI function as follow:
(*env)->GetFieldID(env,jcl,"fieldName",NULL);

Compare with other JVMs, OpenJ9 properly validate the NULL value and throws a error message when -Xcheck:jni option is enabled.
```
JNI error in GetFieldID: Argument #4 is NULL
```

It is recommended that GraalVM also validates the NULL value when the -Xcheck:jni option is turned on.

**Describe GraalVM and your environment:**
openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment GraalVM CE 20.0.0 (build 11.0.6+9-jvmci-20.0-b02)
OpenJDK 64-Bit Server VM GraalVM CE 20.0.0 (build 11.0.6+9-jvmci-20.0-b02, mixed mode, sharing)

**More details**
```
    #
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007fd1e7096681, pid=14888, tid=14889
#
# JRE version: OpenJDK Runtime Environment GraalVM CE 20.0.0 (11.0.6+9) (build 11.0.6+9-jvmci-20.0-b02)
# Java VM: OpenJDK 64-Bit Server VM GraalVM CE 20.0.0 (11.0.6+9-jvmci-20.0-b02, mixed mode, sharing, tiered, jvmci, jvmci compiler, compressed oops, g1 gc, linux-amd64)
# Problematic frame:
# C  [libc.so.6+0x16f681]  __strlen_sse2_pminub+0x11
#
# Core dump will be written. Default location: Core dumps may be processed with "/usr/share/apport/apport %p %s %c %d %P %E" (or dumping to /hsj/unspec_new_list/test_case/testreport/core.14888)
#
# An error report file with more information is saved as:
# /hsj/unspec_new_list/test_case/testreport/hs_err_pid14888.log
#
# If you would like to submit a bug report, please visit:
#   https://bugreport.java.com/bugreport/crash.jsp
#
Aborted (core dumped)
```

**Comment by oubidar-Abderrahim** [comment]
@sjmini could you provide a small reproducer?

**Comment by oubidar-Abderrahim** [comment]
We didn't get any answer for 2 months so I am closing this ticket. If you still want us to investigate this. please re-open and provide a reproducer for this issue.
