### ISSUE TITLE
Documentation on https://www.graalvm.org/advanced-tools/

### ISSUE THREAD

**Issue by frank-dspeed** [oracle/graal#2817]
https://docs.oracle.com/en/graalvm/enterprise/19/guide/tools/ideal-graph-visualizer.html

is the correct link and i did not found the source to correct it on https://www.graalvm.org/advanced-tools/

so i open a issue here to get pointed into the right direction.

**Comment by olyagpl** [comment]
@frank-dspeed, thank you for pointing at the link. It's been updated 
 to https://docs.oracle.com/en/graalvm/enterprise/20/docs/tools/igv/
Feel free to submit GraalVM website or documentation issues to https://github.com/graalvm/graalvm-website.
Olya
