### ISSUE TITLE
Update VisualVM

### ISSUE THREAD

**Issue by chrisseaton** [oracle/graal#2818]
When you build GraalVM from scratch you get VisualVM `Build 200521`, also called version `830` in the file it downloads.

But when I download a build of GraalVM I get `2.0.4`. `Build 200521` seems to be quite old and is incompatible with for example the go-to-source plugin.

<img width="642" alt="Screenshot 2020-08-31 at 16 24 05" src="https://user-images.githubusercontent.com/341094/91737236-b8751200-eba6-11ea-8c65-37b1f0682cae.png">

How do you build GraalVM to get a newer VisualVM? How can I do that myself?

**Comment by fniephaus** [comment]
You may looking for this: https://github.com/oracle/graal/blob/eae2da1d4f39eee558d82ce39a66a470fd6dd5c1/tools/mx.tools/suite.py#L276

**Comment by chrisseaton** [comment]
That's the old one - but now I look in https://lafo.ssw.uni-linz.ac.at/pub/graal-external-deps/visualvm/ again maybe these are GraalVM version numbers not VisualVM version numbers?

**Comment by gilles-duboscq** [comment]
This was fixed by https://github.com/oracle/graal/commit/5987b4bc6d091af7f9e6d73a8135855643756e0a
