### ISSUE TITLE
Create GraalVM CE releases with GitHub Actions

### ISSUE THREAD

**Issue by fniephaus** [oracle/graal#2821]
**Feature request**

Please include the following information:

**Is your feature request related to a problem? Please describe.**
Currently, the release process is not transparent to the community. It'd be good to open it up, which in turn would also eliminate issues like https://github.com/oracle/graal/issues/2818.

**Describe the solution you'd like.**
I'd like to see the release process to be moved to GitHub Actions. This action could be responsible for generating nightly builds as well as final releases from the corresponding release branch on the corresponding release day. Since CE release binaries are part of other repositories ([graalvm-ce-builds](https://github.com/graalvm/graalvm-ce-builds/releases) and [graalvm-ce-dev-builds](https://github.com/graalvm/graalvm-ce-dev-builds/releases)), it may be easier to set up similar actions in those two repositories instead of one within this repository.

**Describe who do you think will benefit the most.**
GraalVM users and contributors.

**Describe alternatives you've considered.**
n/a

**Additional context.**
The [create-release action](https://github.com/actions/create-release) might be useful to implement this.

**Express whether you'd like to help contributing this feature**
Happy to help write or review some of the GitHub action configuration.

**Comment by aalmiray** [comment]
The create-release-action has been marked as no longer supported. Users are encouraged to migrate to other options.

Alternatives are:

* https://github.com/marvinpinto/actions
* https://github.com/jreleaser/release-action

**Comment by aalmiray** [comment]
Any additional comments on why this was closed as "not planned"?

**Comment by fniephaus** [comment]
> Any additional comments on why this was closed as "not planned"?

There are a lot of things that need to be done to make this work. One blocker, for example, is the lack of GitHub runners for all the platforms that GraalVM CE is built for.
