### ISSUE TITLE
Android port?

### ISSUE THREAD

**Issue by Malaska678** [oracle/graal#2822]
Actually there's open jdk port but i think graal port can be better.
It benifits porters who port pc-only java games to android (Like minecraft java edition or the pc only version)

**Comment by Malaska678** [comment]
Want it to support all android 5+ and above

**Comment by Malaska678** [comment]
Accident

**Comment by mcraj017** [comment]
@Malaska678 Please provide the detailed information of this feature in the below format:

**1. Is your feature request related to a problem? Please describe.**
**2. Describe the solution you'd like.**
**3. Describe who do you think will benefit the most.**
**4. Describe alternatives you've considered.**
**5. Additional context.**
