### ISSUE TITLE
undefined reference to `JNI_OnLoad_jaas' and `JNI_OnLoad_sunec'

### ISSUE THREAD

**Issue by ziyilin** [oracle/graal#2839]
**Describe the issue**
This commit https://github.com/oracle/graal/commit/8fb8fc502411b3c84308ff5cda4d6c1f775f3920 generates symbol such as JNI_OnLoad_jaas for all JDK versions. However, JDK 8 doesn't mandatory require JNI_OnLoad_L method for static libraries. And in fact sunec and jaas libraries in JDK8 don't have such method. 

**Describe GraalVM and your environment:**
 - GraalVM version (latest snapshot builds can be found [here](https://github.com/graalvm/graalvm-ce-dev-builds/releases)), or commit id if built from source: **vm-20.2.0**
 - JDK major version: **OpenJDK8U262**
 - Operation System:**Linux** 
 

**More details**
Here is the compilation failure stack trace:
```
    /tmp/SVM-6070230337245410331/app.o:(.data+0x280): undefined reference to `JNI_OnLoad_jaas'
    /tmp/SVM-6070230337245410331/app.o:(.data+0x5c8): undefined reference to `JNI_OnLoad_sunec'
collect2: error: ld returned 1 exit status

        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:593)
        at java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1005)
        at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:483)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:349)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:508)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:114)
Caused by: java.lang.RuntimeException: There was an error linking the native image: Linker command exited with 1
```

**Comment by arodionov** [comment]
@ziyilin are you using `graalvm-ce-java8-20.2.0` for Linux?
It contatins all required static libraries:
```
 ~/vm/graalvm-ce-java8-20.2.0/jre/lib$ ls *.a
libfdlibm.a  libjaas.a  libjava.a  libnet.a  libnio.a  libsctp.a  libsunec.a  libzip.a
```

Regarding mandatory of `JNI_OnLoad_L` method please read the following discussion  https://github.com/oracle/graal/commit/8fb8fc502411b3c84308ff5cda4d6c1f775f3920#commitcomment-39100664

**Comment by ziyilin** [comment]
I'm using a GraalVM built from tag `vm-20.2.0` with Alibaba's own JDK8 which is also a downstream of OpenJDK. Copying existed static libraries from `graalvm-ce-java8-20.2.0` release can be a temporary workaround, but not an ideal solution. Adding new symbol into libraries is not so simple, we may need to evaluate the impact to our users in Alibaba.

**Comment by olpaw** [comment]
@ziyilin you are probably looking for
https://github.com/graalvm/graal-jvmci-8/commit/792248241ec6a48fad9a5fe631bb40903e175f90

**Comment by ziyilin** [comment]
> @ziyilin you are probably looking for
> [graalvm/graal-jvmci-8@7922482](https://github.com/graalvm/graal-jvmci-8/commit/792248241ec6a48fad9a5fe631bb40903e175f90)

Thanks. Are the patches in `patches/jdk` and `patches/static-libs` automatically applied while running `mx build`, or should I apply them manually before building?

**Comment by olpaw** [comment]
ATM we do not have applying the patches integrated. But it should be possible. The patches are in a directory hierarchy that tells you exactly where in the JDK sources (`.`, `jdk`, `hotspot`) and when (building `jdk`, `static-libs`) you need to apply them. This could be automated.

**Comment by ziyilin** [comment]
Thanks, I'll create our own script then.

**Comment by dougxc** [comment]
There's two more changes to `patches/` that should land in the next few hours:
* the patch files are prefixed with a number so that they can be applied in sort order
* the symlinks from `patches/static-libs` to `patches/jdk` have been removed. You now need to apply all the patches in `patches/jdk` first and then those in `patches/static-libs`.

**Comment by ziyilin** [comment]
Are the contents of the upcoming commit same as the previous one? Is it necessary to reapply the upcoming patch if I have already applied the previous one?

**Comment by dougxc** [comment]
No, the content of the patches is the same: https://github.com/graalvm/graal-jvmci-8/commit/d1fe9b10fa4986920e3e258a835a94658cd92756
