### ISSUE TITLE
This is not feature request but a simple question

### ISSUE THREAD

**Issue by Malaska678** [oracle/graal#2848]
Is the graal vm for linux amd64 also for android aarch32/aarch64?

**Comment by oubidar-Abderrahim** [comment]
We do have a distribution for Aarch64 (you can find the full list [here](https://github.com/graalvm/graalvm-ce-builds/releases/tag/vm-20.2.0). 
There was a discussion about using GraalVM on top of Android in this [thread](https://github.com/oracle/graal/issues/632) a few examples can be found [here](https://github.com/gluonhq/client-samples/).

**Comment by oubidar-Abderrahim** [comment]
Duplicate of #632

**Comment by Malaska678** [comment]
I already know that

**Comment by Malaska678** [comment]
So the one that for linux aarch64 is the one that for android aarch64

**Comment by Malaska678** [comment]
Hey! What about 32 bit devices support?

**Comment by oubidar-Abderrahim** [comment]
@vjovanov
