### ISSUE TITLE
com.oracle.svm.hosted.substitute.DeletedElementException: Unsupported method 

### ISSUE THREAD

**Issue by yildiz-online** [oracle/graal#2853]
**Describe the issue**
Exception when building native app using maven plugin with update4j dependency

**Steps to reproduce the issue**

1. git clone --depth 1 https://github.com/yildiz-online/test-build-graalvm-linux.git
2. docker run -e NO_DEPLOY=true -v $PWD:/src -v $HOME/.m2:/root/.m2 moussavdb/build-graalvm-amd64-linux64

**Describe GraalVM and your environment:**

 - GraalVM version 20.2.0 
 - JDK major version: 11
 - OS: Ubuntu 20.04
 - Architecture: AMD64

openjdk version "11.0.8" 2020-07-14
OpenJDK Runtime Environment GraalVM CE 20.2.0 (build 11.0.8+10-jvmci-20.2-b03)
OpenJDK 64-Bit Server VM GraalVM CE 20.2.0 (build 11.0.8+10-jvmci-20.2-b03, mixed mode, sharing)

**More details**
build log: https://travis-ci.org/github/yildiz-online/test-build-graalvm-linux

**Comment by fernando-valdez** [comment]
Hello @yildiz-online, 

I will review this issue. I will let you know if I have any questions.

Thank you for reporting it.

**Comment by christianwimmer** [comment]
Support for the module system is currently under development. So there is no real resource lookup based on the module path possible yet. But I added some more substitutions in https://github.com/oracle/graal/commit/3af85e58222988710f542e5285d69dca133b5196 that should avoid the problem that you have seen.
