### ISSUE TITLE
More help for newcomers

### ISSUE THREAD

**Issue by ianopolous** [oracle/graal#286]
I've just managed to get substratevm to build and run for the first time. Thanks so much for open sourcing your excellent work. 

There were a few hurdles I had to over come which weren't obvious and might be nice to add to the readme instructions for ubuntu builds:
The first problem was I needed to download and point to a jvm from https://github.com/dougxc/openjdk8-jvmci-builder/releases
The oracle link (https://www.oracle.com/technetwork/oracle-labs/program-languages/downloads/index.html) won't open in firefox because of an infinite redirect loop. 

Then I needed to install the build-essential and zlib1g-dev packages to get necessary headers etc (which took a while to figure out). 

The final hurdle was substrate wouldn't build because of a file path longer than 255 characters which is the limit on ext. The only way I could fix this was to move the graal cloned dir to the root directory (/home/ian wasn't enough).

**Comment by eregon** [comment]
The filename problem is very likely the same as #270. cc @chumer @dougxc
Maybe there should be a mx command to check that no filename (after build) is longer than the eCryptfs limit?

**Comment by dougxc** [comment]
I'm not sure a check in mx will help depending on when the error occurs. I assume it happens when a Truffle annotation processor is trying to write a generated source file. Ether that or when javac later in the pipeline tries to open the class file for the generated source. In both cases, too late for mx to do anything. This looks like something that has to be fixed in Truffle itself (if that's possible @chumer ?).

**Comment by eregon** [comment]
@dougxc I meant a lint-like check in `mx` at the end of `mx build` or maybe in some `mx check*` command, so it would check basenames longer than 143 characters, which [doesn't work on eCryptFS](https://bugs.launchpad.net/ecryptfs/+bug/344878) (but could easily be detected with such a check on other filesytems). It's easy to have filenames longer than 143 characters on any project, so project-specific checks don't scale so well.

**Comment by eregon** [comment]
In short, we could add https://github.com/oracle/graal/commit/7c3e1262e5022a87ad26cf504063f599da7013c6#diff-d1bcb545ca76590caf01819bbbb85887R395 to mx. That check should be run after `mx build` to also checks generated sources.

**Comment by dougxc** [comment]
But won't the generation of the sources already fail if file name length limits are being exhausted?

**Comment by eregon** [comment]
Only on eCryptFS, other filesystems accept longer filename lengths and so there it's useful to run this check to make sure the project can also be built on eCryptFS.

**Comment by dougxc** [comment]
Ok, makes sense. Can you please create an mx PR for this then.

**Comment by alina-yur** [comment]
@ianopolous hi, do you think this issue can be closed now as we have docs here on GitHub and at https://www.graalvm.org/ ?

**Comment by ianopolous** [comment]
Yep, build instructions are there now, and ecryptfs issue is fixed. Thank you!
