### ISSUE TITLE
i got the same error but on windows platform

### ISSUE THREAD

**Issue by Sahil308** [oracle/graal#2868]
i got the same error but on windows platform
os-windows 10 64-bit
jdk version-11
graalvm version-20.2.0
visual studio version-2019

I am using a maven project in eclipse ide and executed using mvn package command

can anyone help me out

_Originally posted by @Sahil308 in https://github.com/oracle/graal/issues/343#issuecomment-697576354_

**Comment by cstancu** [comment]
Please use the issue-reporting template and make sure that your report includes all the necessary details to allow us to reproduce.
