### ISSUE TITLE
Duplicate resources at runtime if specified twice in resources-config.json

### ISSUE THREAD

**Issue by lbeuster** [oracle/graal#2870]
I have one resource in the classpath and I add it twice to my resources-config.json files with 2 **different** patterns. If I run the native-image I see the resource twice (ClassLoader.getResources(name)).

**Steps to reproduce the issue**
1. **https://github.com/lbeuster/graalvm-dup-resources.git**
2. **mvn clean verify**
3. **target/my-native-image**

**Describe GraalVM and your environment:**
 - GraalVM **CE 20.2.0**, **CE 20.3.0-dev-20200924_0204**
 - JDK major version: **11**
 - OS: **macOS Catalina**
 - Architecture: **AMD64**

**Comment by oubidar-Abderrahim** [comment]
Thank you for reporting this, we will look into it

**Comment by teshull** [comment]
Commit 5dcdc28fb1265406c8f6038b3232831e83c6f2bf fixes this issue.
