### ISSUE TITLE
How to determine which class causes 'Image heap writing found a class not seen during static analysis'?

### ISSUE THREAD

**Issue by fhoeben** [oracle/graal#2875]
**Describe the issue**
I'm trying to build a native image of wiremock. I get an exception during image build time about a class encountered that was not seen before. How do I determine which class this is (so I can add it to the reflection config)?

**Steps to reproduce the issue**
Please include both build steps as well as run steps
1.  git clone https://github.com/fhoeben/wiremock-docker.git
2. git checkout graal2
3. docker build --pull .

**Describe GraalVM and your environment:**
 - oracle/graalvm-ce:20.2.0-java8

**More details**

```
Fatal error:com.oracle.svm.core.util.VMError$HostedError: com.oracle.svm.core.util.UserError$UserException: Image heap writing found a class not seen during static analysis. Did a static field or an object referenced from a static field change during native image generation? For example, a lazily initialized cache could have been initialized during image generation, in which case you need to force eager initialization of the cache before static analysis or reset the cache using a field value recomputation.
    object: ()J  of class: java.lang.String
  reachable through:
    object: ()long  of class: java.lang.invoke.MethodType
    object: MethodHandle()long  of class: java.lang.invoke.SimpleMethodHandle
    object: LambdaForm.zero_J  of class: java.lang.invoke.LambdaForm$NamedFunction
    object: [Ljava.lang.invoke.LambdaForm$NamedFunction;@1701317a  of class: java.lang.invoke.LambdaForm$NamedFunction[]
    root: java.lang.invoke.LambdaForm.buildEmptyNames(int, String)

        at com.oracle.svm.core.util.VMError.shouldNotReachHere(VMError.java:72)
        at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:661)
        at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:468)
        at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:163)
```

**Comment by oubidar-Abderrahim** [comment]
You can use the native image agent to generate the necessary config files using `java -agentlib:native-image-agent=config-output-dir=ConfigFolderName -jar YourApp.jar` and try to cover most use cases in your application to make sure the agent scans most of the code.
Finally, specify the config folder when generating the native image by adding the flag: `-H:ConfigurationFileDirectories=ConfigFolderName`

**Comment by fhoeben** [comment]
@oubidar-Abderrahim unfortunately I already did what you suggest (see the branch in my repo), I even added an extra class the agent did not pick up (to fix the first error I got), and I still get this error.
So my question is: what next, where do I start look?

**Comment by alexh2o17** [comment]
I've the same error. Tried with agent but nothing changed.

**Comment by collinpeters** [comment]
I have this same issue that started with 20.2

**Comment by oubidar-Abderrahim** [comment]
This code is only reached when trying to use `VarHandles` or `MethodHandles`, which are not supported by Native Image yet. The code you’re trying to compile probably uses one of these, which gets pulled by the agent into the reflection configuration.
We are currently developing support for `MethodHandles`, in the meantime, you can work around this by finding where the LambdaForm code gets called and substituting it away.

I suggest to manually delete entries from the reflection configuration and rebuilding, this can give you an indication of where this code is reachable from.

**Comment by cstancu** [comment]
With the new shadow heap implementation this issue is largely gone.
