### ISSUE TITLE
Feature avalibility chart

### ISSUE THREAD

**Issue by Dmole** [oracle/graal#2876]
A list of features and what OS and architectures they are limited to would be nice.

```
> uname -rm
5.4.68-dirty aarch64

> /opt/graalvm-ce-java11-20.2.0/bin/gu available
Downloading: Component catalog from www.graalvm.org
ComponentId              Version             Component name      Origin 
--------------------------------------------------------------------------------
llvm-toolchain           20.2.0              LLVM.org toolchain  github.com
native-image             20.2.0              Native Image        github.com
```

**Comment by Dmole** [comment]
Limitations are not mentioned in the documentation here;
https://www.graalvm.org/reference-manual/python/

**Comment by fniephaus** [comment]
IIRC `gu` will only show components compatible to the system's architecture, but it could list others as well.

What kind of features would you expect to see in the listing? I'd much rather see a URL (e.g. to the corresponding project page).

**Comment by Dmole** [comment]
> What kind of features would you expect to see in the listing?

I'd expect the linked documentation to mention "gu install python" is only available on amd64 Linux or wherever, and a Limitations/Availability section of the documentation.

**Comment by fniephaus** [comment]
The command `gu available` suggests that it only lists components available for the current platform. Maybe a new command should be added to list what's available in the current catalog, e.g. `gu catalog` `gu outline`, independently from the current platform/architecture.

**Comment by MartinBalin** [comment]
Adding something like `gu outline` to list all components all platforms for given version is possible. We will consider it.

**Comment by MartinBalin** [comment]
Will not do, non trivial feature to implement.
