### ISSUE TITLE
No way to change Runtime.availableProcessors() return value

### ISSUE THREAD

**Issue by pshirshov** [oracle/graal#2878]
Sometimes it's necessary to override`Runtime.availableProcessors()` to affect hidden states of various threadpools/etc.

Though it's not possible to do that for an app compiled with `native-image`. `-XX:ActiveProcessorCount` is not supported by NI apps so the only way to do it is to use Graal's monkeypatching capabilities.

Could you please support `-XX:ActiveProcessorCount`?

**Comment by christianwimmer** [comment]
GraalVM 20.3 will have the option `ActiveProcessorCount` with the same semantics as HotSpot.

**Comment by zakkak** [comment]
FWIW the corresponding commit is https://github.com/oracle/graal/commit/e3ef0368e4882cdf6d9d89ddd9d1e47b9148e104
