### ISSUE TITLE
Compiler reference manual does not load

### ISSUE THREAD

**Issue by jryans** [oracle/graal#2884]
The [reference manual](https://www.graalvm.org/reference-manual/) page has a link to a "Compiler" manual which points to https://www.graalvm.org/reference-manual/compiler/, but that page seems to reference various missing files that can't be loaded, so it just shows a blank page.

Here's a network log from the browser tools:

<img width="779" alt="image" src="https://user-images.githubusercontent.com/279572/94742142-214dd680-036d-11eb-9202-a5008ea1a15c.png">

The page content is mostly there when viewing the source of the (visually blank) page, so hopefully fixing up the scripts and such will make it work without too much trouble. (It seems like it was maybe copied from https://docs.oracle.com/en/graalvm/enterprise/20/docs/reference-manual/compiler/ without updating the scripts to new paths...?)

Thanks for all the work on GraalVM and docs! 😄

**Comment by dougxc** [comment]
Triage hint: @olyagpl

**Comment by olyagpl** [comment]
@oubidar-Abderrahim, thanks for the report ;-)
We resolved that.
