### ISSUE TITLE
Unresolved Conflict in "Release Notes"

### ISSUE THREAD

**Issue by sparkyspider** [oracle/graal#2887]
https://www.graalvm.org/release-notes/

![Oops](https://user-images.githubusercontent.com/1888768/94826921-20b64e00-0408-11eb-872d-635c9c2e6e3d.png)

**Comment by olyagpl** [comment]
@sparkyspider , we've just fixed. Thank you!
By the way, you now can submit documentation related issues to https://github.com/graalvm/graalvm-website.
