### ISSUE TITLE
Please allow executing of complete NPM packages from Java code (like NodeJVM)

### ISSUE THREAD

**Issue by sparkyspider** [oracle/graal#2888]
**Feature request**

Please include the following information:

**Is your feature request related to a problem? Please describe.**
The most useful feature of Graal or Truffle in my opinion should be to execute npm modules from Java. I've tried this using the Java API but it's no means trivial trying to include all the "system" libraries through the API.

**Describe the solution you'd like.**
It would be really cool if one could simple execute NPM scripts like you can from NodeJVM by Mike Hearn.

**Describe who do you think will benefit the most.**
People with build tools on the backend. Compressing, bundling, packaging, purging. Web builders, online dev tools, etc. In fact, any dynamic app that requires access to NPM's vast array of JS tools. Also, running a GraalVM buildpack on Heroku is one thing. Now needing to try and fudge in an alternative java executable is another.

**Describe alternatives you've considered.**
NodeJVM

**Additional context.**
3rd Party Implementation: https://mikehearn.github.io/nodejvm/using-from-java/

**Comment by wirthi** [comment]
Hi @sparkyspider 

thanks for your request.

We have some documentation on the possible embeddings in https://github.com/graalvm/graaljs/blob/master/docs/user/NodeJSVSJavaScriptContext.md 

To use Node.js AND Java to the full extend (including the Node.js event loop), our preferred solution is to start from a Node.js app and interop to Java from there. This is fully supported today. And basically, that's what NodeJVM does.

We currently don't actively work on providing additional support in that area, or include NodeJVM in our codebase.

Best,
Christian

**Comment by frank-dspeed** [comment]
@sparkyspider i am working on such a context at present you can follow me on github to be uptodate 

at present i am working on mapping the fundamentals to get node/interals/* running inside the context.

**Comment by sparkyspider** [comment]
Thank you for your Christian and Frank.

Christian, unfortunately I need to call the node scripts from Java, not the
other way around.

Frank, very exciting. Please send me a link!

Thank you,

**Comment by wirthi** [comment]
Closing older ticket. Our documentation is still the one linked above.
