### ISSUE TITLE
Incomplete HTTP responses with Tomcat causing timeout on client side

### ISSUE THREAD

**Issue by dsyer** [oracle/graal#2891]
This seems to be a regression between GraalVM 19.2 and 20.1. See https://github.com/spring-projects-experimental/spring-graalvm-native/issues/306#issuecomment-702932959 for more background. To observe it you can build a native image with Tomcat and run ApacheBench with no concurrency (`-c 1`). You will see each request is fast with 19.2 and takes precisely 1000ms with 20.1 and above (presumably a timeout on the client side).

**Comment by oubidar-Abderrahim** [comment]
Would you mind providing a reproducer for this issue?

**Comment by dsyer** [comment]
This sample has the performance issue: https://github.com/spring-projects-experimental/spring-graalvm-native/tree/master/spring-graalvm-native-samples/webmvc-tomcat. I'm not sure if it can be compiled with 19.2, so you might not be able to see the regression.

**Comment by fhanik** [comment]
Linking a reproducible test case:

https://github.com/oracle/graal/issues/2902

**Comment by oubidar-Abderrahim** [comment]
Closing this issue for duplication, the progress should be tracked in #2902
