### ISSUE TITLE
Please create an updated Heroku Buildpack

### ISSUE THREAD

**Issue by sparkyspider** [oracle/graal#2894]
Seems that Heroku (an extremely useful, convenient and quick way to deploy Java applications) no longer has support for GraalVM. The older buildpack by Joe Kutner (https://elements.heroku.com/buildpacks/jkutner/graal-buildpack) no longer works.

It would be great if there was a buildpack that installs the latest GraalJVM on Heroku that also then will pick up your build.gradle specifically and then execute the Procfile.

I think it would be extremely useful to anyone wanting to try out GraalVM in a live environment to be able to do so, without having to set up your own virtual private server.

At the moment, we have rolled back to OpenJDK and are calling node.js applications through REST hosted on a node server in another app instance. This is costing us an additional app for hosting node as well as a relatively slow http link between the two apps.

**Comment by mcraj017** [comment]
Hello @sparkyspider 
thank you for the feature request

Please provide the information in the form of below template

Feature request

**1. Is your feature request related to a problem? Please describe.
2. Describe the solution you'd like.
3. Describe who do you think will benefit the most.
4. Describe alternatives you've considered.
5. Additional context.**

**Comment by dougxc** [comment]
Hi @sparkyspider I see that you've already opened an issue with the existing buildpack (https://github.com/jkutner/graal-buildpack/issues/4). That's the best path to get the problem resolved.
