### ISSUE TITLE
Performance Regression on Apache Tomcat from Graal v19 -> v20

### ISSUE THREAD

**Issue by fhanik** [oracle/graal#2902]
**Describe the issue**
Using Apache Bench we're noticing that socket data is not getting flushed when running Apache Tomcat as a native image.
The delay, which is almost exactly `1 second` seems to be happening in the Apache Tomcat run time.

**Highlights**

- We're not seeing this with curl or other http clients
- We're not seeing this with Graal v19.2 native-image, `ab` works fine here too
- Putting a network sniffer, we see that the data packet doesn't get sent out on the socket until after the delay
- This issue is related to: https://github.com/spring-projects-experimental/spring-graalvm-native/issues/306

**Prerequisites**

1. Apache Ant `ant` on path - https://ant.apache.org/bindownload.cgi
2. `native-image` on path
3. Apache Bench `ab` on path - https://httpd.apache.org/docs/2.4/programs/ab.html

**Steps to reproduce the issue**

```
git clone -b 9.0.x https://github.com/apache/tomcat.git
cd tomcat/res/graal/
./run-tomcat-native.sh build native
```

**Run Apache Bench**
```
ab -n 1000 -c 50 http://localhost:8080/
```

**Results with Graal 19.2**
```
Server Hostname:        localhost
Server Port:            8080

Document Path:          /
Document Length:        32 bytes

Concurrency Level:      50
Time taken for tests:   0.050 seconds
Complete requests:      1000
Failed requests:        0
Total transferred:      225000 bytes
HTML transferred:       32000 bytes
Requests per second:    20096.87 [#/sec] (mean)
Time per request:       2.488 [ms] (mean)
Time per request:       0.050 [ms] (mean, across all concurrent requests)
Transfer rate:          4415.82 [Kbytes/sec] received
```

_Repeat the build with Graal 20.2 and run Apache Bench again_

**Results with Graal 20.2**
_20.2/graal/sdk/mxbuild/linux-amd64/GRAALVM_BCF68E8E09_JAVA8/graalvm-bcf68e8e09-java8-20.2.1-dev_

```
Server Hostname:        localhost
Server Port:            8080

Document Path:          /
Document Length:        32 bytes

Concurrency Level:      50
Time taken for tests:   1.060 seconds
Complete requests:      1000
Failed requests:        0
Total transferred:      225000 bytes
HTML transferred:       32000 bytes
Requests per second:    943.68 [#/sec] (mean)
Time per request:       52.984 [ms] (mean)
Time per request:       1.060 [ms] (mean, across all concurrent requests)
Transfer rate:          207.35 [Kbytes/sec] received
```

**Describe GraalVM and your environment:**
```
Linux fhanik-pc2 5.4.0-48-generic #52-Ubuntu SMP Thu Sep 10 10:58:49 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by jramirez-isc** [comment]
Hi @fhanik thanks for reporting this.
I'm able to run your steps and I tested on different versions. I found this issue starting from version 19.3.0. 

**Results with Graal 19.2.1**
Server Software:        
Server Hostname:        localhost
Server Port:            8080

Document Path:          /
Document Length:        33 bytes

Concurrency Level:      50
Time taken for tests:   0.040 seconds
Complete requests:      1000
Failed requests:        0
Total transferred:      226000 bytes
HTML transferred:       33000 bytes
Requests per second:    24876.86 [#/sec] (mean)
Time per request:       2.010 [ms] (mean)
Time per request:       0.040 [ms] (mean, across all concurrent requests)
Transfer rate:          5490.40 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        1    1   0.2      1       2
Processing:     0    1   0.3      1       2
Waiting:        0    1   0.2      1       2
Total:          1    2   0.3      2       3

Percentage of the requests served within a certain time (ms)
  50%      2
  66%      2
  75%      2
  80%      2
  90%      2
  95%      3
  98%      3
  99%      3
 100%      3 (longest request)

**Results with Graal 19.3.0**
Server Hostname:        localhost
Server Port:            8080

Document Path:          /
Document Length:        33 bytes

Concurrency Level:      50
Time taken for tests:   1.042 seconds
Complete requests:      1000
Failed requests:        0
Total transferred:      226000 bytes
HTML transferred:       33000 bytes
Requests per second:    960.14 [#/sec] (mean)
Time per request:       52.076 [ms] (mean)
Time per request:       1.042 [ms] (mean, across all concurrent requests)
Transfer rate:          211.91 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        0    1   0.2      1       2
Processing:     1    4  54.7      1    1001
Waiting:        0    1   0.2      1       2
Total:          2    5  54.7      2    1003

Percentage of the requests served within a certain time (ms)
  50%      2
  66%      2
  75%      2
  80%      2
  90%      2
  95%      3
  98%      3
  99%      3
 100%   1003 (longest request)

I'll continue investigating.

**Comment by sdeleuze** [comment]
Please add the `spring` label to this issue, and please let us know any progress since we are working heavily on benchmarks these days.

**Comment by sdeleuze** [comment]
Any chance to do progresse on that one for 20.3?

**Comment by fhanik** [comment]
Platform: Linux (Ubuntu 20.04 LTS)
Download from: https://github.com/graalvm/graalvm-ce-builds/releases/tag/vm-20.2.0

The bug/performance regression only exists in the [Java 8 bundle](https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-20.2.0/graalvm-ce-java8-linux-amd64-20.2.0.tar.gz).

The [Java 11 bundle](https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-20.2.0/graalvm-ce-java11-linux-amd64-20.2.0.tar.gz) does not exhibit the performance slow down.

**Comment by vjovanov** [comment]
Thanks for reporting this! We looked into this and this issue is only on JDK 8. The GraalVM team will not prioritize performance issues on JDK 8 as there are more important things to tackle.
