### ISSUE TITLE
Provide a way to call the original method from a @Substitute method

### ISSUE THREAD

**Issue by ppalaga** [oracle/graal#2904]
**Feature request**

I'd need to change the behavior of a method only if some condition is fulfilled and otherwise delegate to the original implementation. 

Here is an example:

```
class Original {
  String hello(boolean isMorning) {
    return "Hello";
  }
}

@TargetClass(Original.class)
final class OriginalSubstitution {
  @Substitute
  String hello(boolean isMorning) {
    if (isMorning) {
      return "Good morning";
    }
    return originalHello(isMorning); // <-- This is currently not possible 
  }
}
```

**Is your feature request related to a problem? Please describe.**
The only solution known to me is to copy the code from the original method to the substituted method. That might be tedious as I might have to alias many internal methods and it is often hard to maintain in the long term because the copy can diverge from the original.

**Describe the solution you'd like.**

Maybe a way to rename the original method would be an elegant solution to the problem. Something like

```
@TargetClass(Original.class)
final class OriginalSubstitution {
  @Substitute(renameOriginal="originalHello")
  String hello(boolean isMorning) {
    if (isMorning) {
      return "Good morning";
    }
    return originalHello(isMorning);
  }

  // a placeholder for the renamed Original.hello()
  String originalHello(boolean isMorning) {
    return null;
  }

}
```

**Describe who do you think will benefit the most.**
developers of libraries and frameworks which depend on GraalVM

**Describe alternatives you've considered.**
Copying the code from the original method is impractical as I mentioned above.

**Express whether you'd like to help contributing this feature**
I'd like to, although this doesn't look like an issue for a newcomer.

**Comment by dougxc** [comment]
Hi @ppalaga as far as I understand, this is currently not supported by SVM. @christianwimmer can comment on plans, if any, to add such support.

**Comment by christianwimmer** [comment]
My usual disclaimer first: you should not use method substitutions.

Doug is correct, preserving the original method is not supported and would also be very difficult to support: as the name of the annotation suggest, the new method really is a substitution that replaces the original implementation. There is never a new "method entity" created (in JVMCI terminology a `ResolvedJavaMethod`). All method resolution and linking is done by the JVMCI on the hosting HotSpot VM, which of course knows only of one method and not two. To preserve both the new and the original method, we would need a significantly more complicated method resolution code, which is something that is not worth the effort.

**Comment by ppalaga** [comment]
Thanks for the explanations, @dougxc and @christianwimmer. I see that "preserving" would be rather hard to do, but can't the solution be approached as "method renaming"? Renaming seems to be a substitution of a special kind, where all method characteristics are kept except for the name. This alone looks doable with the current JVMCI means. But yes, what I actually want is to both rename and substitute the same method - maybe there are some details hidden to me that indeed make that combination hard to implement or even impossible. I'd be thankful for any comments.
