### ISSUE TITLE
Document the limitations in Locale support

### ISSUE THREAD

**Issue by ppalaga** [oracle/graal#2907]
As of GraalVM 20.2.0, native executables produced by the `native-image` command contain only the single locale that has been returned by `Locale.getDefault()` in the building JVM. That's at least my understanding of what happens in [LocaleSubstitutions](https://github.com/oracle/graal/blob/master/substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jdk/LocaleSubstitutions.java) and [LocalizationFeature](https://github.com/oracle/graal/blob/master/substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jdk/LocalizationFeature.java). 

This has far-reaching implications on any code using locale. Even such a basic thing as `String.format(Locale.ROOT, "%.1f", 0.1)` may work unexpectedly (returns `0,1` instead of `0.1`) if the native image is built on a machine having `LANG` set to some locale using comma as a decimal delimiter.

Googling for "GraalVM native-image locale" or similar does not bring any official documentation page that would (1) mention that only the building JVM default locale is supported in the native image and (2) list all important consequences of (1). Such page would be very useful and I am hereby asking for it.

**Comment by ppalaga** [comment]
Related https://github.com/oracle/graal/issues/1645 and https://github.com/oracle/graal/issues/911

**Comment by oubidar-Abderrahim** [comment]
The issue will be closed and the progress can be tracked on the feature request. see #2908
