### ISSUE TITLE
Support for non-default locale

### ISSUE THREAD

**Issue by ppalaga** [oracle/graal#2908]
**Feature request**

As of GraalVM 20.2.0, native executables produced by the native-image command contain only the single locale that has been returned by `Locale.getDefault()` in the building JVM. This is implemented in [LocaleSubstitutions](https://github.com/oracle/graal/blob/master/substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jdk/LocaleSubstitutions.java) and [LocalizationFeature](https://github.com/oracle/graal/blob/master/substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jdk/LocalizationFeature.java). This has far-reaching implications on any code using locale.

So I am kindly asking for a way to instruct the `native-image` command to include additional locales. 

**Is your feature request related to a problem? Please describe.**

A very basic example of a related problem: `String.format(Locale.ROOT, "%.1f", 0.1)` may work unexpectedly (returns 0,1 instead of 0.1) if the native image is built on a machine having LANG set to some locale using comma as a decimal delimiter. 
Other issues are described in #1645 and #911.

**Describe the solution you'd like.**
I'd be fine with any single or some combination of the following options:

* Introduce a new command line argument and/or dedicated configuration file to specify additional locales by their IETF BCP 47 language tags
* Introduce a new command line flag, e.g. `-H:+AddAllLocales`, to include all available locales, 

**Describe who do you think will benefit the most.**
GraalVM users and developers of libraries and frameworks which depend on GraalVM

**Describe alternatives you've considered.**

Substitutions may help for some specific scenarios. E.g. `String.format(Locale.ROOT, "%.1f", 0.1)` can be made to behave consistently with sock JVMs by substituting `java.text.DecimalFormatSymbols.getInstance(Locale)`. Substitutions are generally hard to maintain and they cannot help with all locale-related issues, because many important methods are substituted in [LocaleSubstitutions](https://github.com/oracle/graal/blob/master/substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jdk/LocaleSubstitutions.java) already.

**Additional context.**

Issues #1645 and #911 are related, but they are not explicit feature requests and hence they may eventually get solved by other means then by introducing a support for non-default locale.

**Express whether you'd like to help contributing this feature**
Yes, I can try.

**Comment by ppalaga** [comment]
Seems to be fixed in GraalVM 21.1. Citing from https://medium.com/graalvm/graalvm-21-1-96e18f6806b :

> GraalVM 21.1 adds support for multiple locales in Native Image. Now you can specify at build time which locales should be included in the generated executable. For example, to switch the default locale to German and also include French and English, use -H:DefaultLocale=de -H:IncludeLocales=fr,en. All locales can be included via -H:+IncludeAllLocales. ResourceBundles are included by default for all selected locales, but this can be changed by providing a locale-specific substring when requesting the bundle.

**Comment by christianwimmer** [comment]
> Seems to be fixed in GraalVM 21.1

We are not calling it "fixed" yet because there are still fixes and improvements that we will do over the next releases. But this release was indeed an important step forward.

**Comment by mipastgt** [comment]
What are these "fixes and improvements"? Are there any visible limitations?

**Comment by christianwimmer** [comment]
We want to reduce the memory footprint, and put the locale data into separate files, so that you can decide which locales to include without re-building the image. But all of that is in the design state, so plans might change.

**Comment by mipastgt** [comment]
Just tested this with a large GluonHQ based JavaFX application and it works. I included English and German language bundles and could switch between the two. Thanks to everybody involved.

**Comment by wirthi** [comment]
From the comments above I take this is fixed and supported on newer GraalVM versions.
