### ISSUE TITLE
Failed to build native executable for Quarkus app using Graalvm v20.2

### ISSUE THREAD

**Issue by davidchang168** [oracle/graal#2911]
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildStep] /home/david/tools/graalvm-ce-java11-20.2.0/bin/native-image -J-Djava.util.logging.manager=org.jboss.logmanager.LogManager -J-Dsun.nio.ch.maxUpdateArraySize=100 -J-Dvertx.logger-delegate-factory-class-name=io.quarkus.vertx.core.runtime.VertxLogDelegateFactory -J-Dvertx.disableDnsResolver=true -J-Dio.netty.leakDetection.level=DISABLED -J-Dio.netty.allocator.maxOrder=1 -J-Duser.language=en -J-Dfile.encoding=UTF-8 -H:ResourceConfigurationFiles=resources-config.json --initialize-at-build-time= -H:InitialCollectionPolicy=com.oracle.svm.core.genscavenge.CollectionPolicy$BySpaceAndTime -H:+JNI -jar radio-monitor-sim-1.0.1-SNAPSHOT-runner.jar -H:FallbackThreshold=0 -H:+ReportExceptionStackTraces -H:-AddAllCharsets -H:-IncludeAllTimeZones -H:EnableURLProtocols=http -H:NativeLinkerOption=-no-pie --no-server -H:-UseServiceLoaderFeature -H:+StackTrace radio-monitor-sim-1.0.1-SNAPSHOT-runner
-H:IncludeAllTimeZones and -H:IncludeTimeZones are now deprecated. Native-image includes all timezones by default.
[radio-monitor-sim-1.0.1-SNAPSHOT-runner:192852]    classlist:   9,271.02 ms,  0.94 GB
[radio-monitor-sim-1.0.1-SNAPSHOT-runner:192852]        (cap):   1,354.88 ms,  0.94 GB
[radio-monitor-sim-1.0.1-SNAPSHOT-runner:192852]        setup:   3,740.05 ms,  0.93 GB
11:33:39,799 INFO  [org.jbo.threads] JBoss Threads version 3.0.1.Final
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007ff29d7ead50, pid=192852, tid=193368
#
# JRE version: OpenJDK Runtime Environment GraalVM CE 20.2.0 (11.0.8+10) (build 11.0.8+10-jvmci-20.2-b03)
# Java VM: OpenJDK 64-Bit Server VM GraalVM CE 20.2.0 (11.0.8+10-jvmci-20.2-b03, mixed mode, tiered, jvmci, jvmci compiler, compressed oops, parallel gc, linux-amd64)
# Problematic frame:
# C  0x00007ff29d7ead50

[hs_err_pid192852.log](https://github.com/oracle/graal/files/5359434/hs_err_pid192852.log)

**Comment by oubidar-Abderrahim** [comment]
Could you please follow the template at (https://github.com/oracle/graal/issues/new?assignees=&labels=bug%2C+native-image&template=1_issues_native_image.md&title=) when reporting a bug and provide a reproducer for this issue

Thank you

**Comment by davidchang168** [comment]
Re-submitted using the template you provided (new issue #2916)

**Comment by oubidar-Abderrahim** [comment]
Closing this issue, progress is tracked on #2916
