### ISSUE TITLE
gu install native-image fails on linux

### ISSUE THREAD

**Issue by DeanWookey** [oracle/graal#2917]
**Describe the issue**
When building a native image on Linux I got the following error:
```
[ERROR] Please, use gu to install native-image running the following command:
[ERROR] $GRAALVM_HOME/bin/gu install native-image
```
After following those instructions I got this error:
```
Error: The GraalVM directory /opt/java is invalid.
```
GRAALVM_HOME is /opt/java/graalvm-ce-java11-20.2.0

After doing some digging into where the error is reported, specifically this line (potentially): https://github.com/oracle/graal/blob/0dee9ea640a96137e72d2583a02b828b9a0deb87/vm/src/org.graalvm.component.installer/src/org/graalvm/component/installer/ComponentInstaller.java#L542

I copied gu into a subfolder called gu, and executed $GRAALVM_HOME/bin/gu/gu install native-image *which worked*. I'm not sure if the code was designed for mac, or if the directory resolution on my setup (Windows Subsystem for Linux) is to blame. Basically, it resolves $GRAALVM_HOME/bin/../../ as the GraalVM home instead of $GRAALVM_HOME/bin/../

**Steps to reproduce the issue**
- Download graalvm-ce-java11-20.2.0
- Extract it to /opt/java/
```
export GRAALVM_HOME=/opt/java/graalvm-ce-java11-20.2.0
export JAVA_HOME=$GRAALVM_HOME
$GRAALVM_HOME/bin/gu install native-image
```

**Describe GraalVM and your environment:**
 - GraalVM version graalvm-ce-java11-20.2.0
 - JDK major version: 11
 - OS: Ubuntu 20.04 LTS
 - Architecture: AMD64

**More details**
Note I'm using Windows Subsystem for Linux https://docs.microsoft.com/en-us/windows/wsl/install-win10
This may be related to issue #2916
**Note:** Just to reiterate, it's working for me using the workaround I mentioned above.

**Comment by sdedic** [comment]
Sorry to react this late. I have tried to reproduce the issue using the following steps:
- Download graalvm-ce-java11-20.2.0
- expand it (in my case `/space/tmp/graal/graalvm-ce-java11-20.2.0`)

Then

```
export GRAALVM_HOME=/opt/java/graalvm-ce-java11-20.2.0
export JAVA_HOME=$GRAALVM_HOME
$GRAALVM_HOME/bin/gu install native-image```
```
Worked well (run from a different directory):
```
sdedic@xxxx:/$ $GRAALVM_HOME/bin/gu install native-image
Downloading: Component catalog from www.graalvm.org
Processing Component: Native Image
Downloading: Component native-image: Native Image  from github.com
[###                 ]^C
```

Env:
```
$ grep VERSION $GRAALVM_HOME/release
JAVA_VERSION="11.0.8"
JAVA_VERSION_DATE="2020-07-14"
GRAALVM_VERSION="20.2.0"

sdedic@xxx:/$ echo $JAVA_HOME
/space/tmp/graal/graalvm-ce-java11-20.2.0

sdedic@xxx:/$ echo $GRAALVM_HOME
/space/tmp/graal/graalvm-ce-java11-20.2.0
```

Please check your GraalVM installation. Under normal circumstances, `gu` is actually placed into `./lib/installer/bin`, so it uses relative paths appropriate for *that* placement to determine root of the GraalVM installation. The other `gu`s are just symlinks.

Tested on Ubuntu 19.04 / x86_64

Note that usage of environment variables and/or system properties that the GU may be using to determine graalvm home **is not documented** (AFAIK) and therefore may be changed without any notice.
