### ISSUE TITLE
The inspector/Chrome Devtools Protocol implementation forces to show "this" as a local variable on any language

### ISSUE THREAD

**Issue by guillermomolina** [oracle/graal#2920]
I am implementing a language that does not use a "this" (or "self") variable. But the debugger in visual studio is forced to show a "this" local variable (initialized as null). It would be nice that there should be a way of not doing that:

In [InspectorDebugger.java](https://github.com/oracle/graal/blob/master/tools/src/com.oracle.truffle.tools.chromeinspector/src/com/oracle/truffle/tools/chromeinspector/InspectorDebugger.java) from line 494 to 501:

```java
            RemoteObject thisObj;
            if (thisValue != null) {
                thisObj = context.getRemoteObjectsHandler().getRemote(thisValue);
            } else {
                thisObj = RemoteObject.createNullObject(context.getEnv(), frame.getLanguage());
            }
            CallFrame cf = new CallFrame(frame, depth++, script, sourceSection, anchor, functionSourceSection,
                            thisObj, returnObj, scopes.toArray(new Scope[scopes.size()]));
```

As you can see thisObj is always added to the CallFrame, even forced as null.

![Use of this](https://user-images.githubusercontent.com/16609390/95943189-66e6b680-0de5-11eb-970d-6573950fba11.png)

**Comment by entlicher** [comment]
This is fixed by https://github.com/oracle/graal/commit/53815995d3bb825e87cd670fd1aafe847aa80da6
We show `this` only when the language provides it (`NodeLibrary.getReceiverMember()`) and we use the receiver's name (e.g. `self` in Ruby).
