### ISSUE TITLE
"cannot find symbol SpeculationReasonEncoding" when building with vanilla OpenJDK

### ISSUE THREAD

**Issue by zakkak** [oracle/graal#2933]
**Describe the issue**
As discussed in https://github.com/graalvm/mandrel/issues/146 after @2d5eee0 GraalVM no longer builds with vanilla OpenJDK.

> It looks like oracle@2d5eee0 depends on https://bugs.openjdk.java.net/browse/JDK-8220623 which got backported to labsJDK11 in graalvm/labs-openjdk-11@fbbdf5f

Unfortunately https://bugs.openjdk.java.net/browse/JDK-8220623 is rather big and includes many changes that are not all related to the issue at hand. I tried creating a minimal backport/patch for jdk11u by pulling in only the needed changes but I ended up pulling more and more dependencies (especially after entering the C++ code).  The main issue seems to be the way that failed speculations are gathered after https://bugs.openjdk.java.net/browse/JDK-8220623. I also tried pulling in only the necessary changes without changing the way that failed speculations are gathered, but then the `SpeculationReasonEncoding` is not actually used making this kind of patch kind of pointless.

So I am openning this issue to ask for directions on how to approach this and discuss possible alternatives.

Thanks! 

**Steps to reproduce the issue**
```
export JAVA_HOME=/tmp/openjdk11ea
curl -sL https://api.adoptopenjdk.net/v3/binary/latest/11/ea/linux/x64/jdk/hotspot/normal/openjdk -o jdk.tar.gz
curl -sL https://api.adoptopenjdk.net/v3/binary/latest/11/ea/linux/x64/staticlibs/hotspot/normal/openjdk -o jdk-static-libs.tar.gz
mkdir -p ${JAVA_HOME}
tar xf jdk.tar.gz -C ${JAVA_HOME} --strip-components=1
tar xf jdk-static-libs.tar.gz -C ${JAVA_HOME} --strip-components=1
git clone git@github.com:oracle/graal.git --depth 1
cd graal
mx --primary-suite-path substratevm build --projects=com.oracle.svm.graal
```

**Describe GraalVM and your environment:**
 - GraalVM version: **master branch (60faf95321609669bcf0a01e0e134c3b7906e435)**
 - JDK major version: **11**
 - OS: **Linux Fedora 32**
 - Architecture: **AMD64**

**More details**
```
$ mx --primary-suite-path substratevm build --projects=com.oracle.svm.graal         
Compiling com.oracle.svm.graal with javac-daemon(JDK 11)... [dependencies were added, removed or re-ordered]
/home/zakkak/code/graal/substratevm/src/com.oracle.svm.graal/src/com/oracle/svm/graal/isolated/IsolatedSpeculationReason.java:41: error: cannot find symbol
    public SpeculationLog.SpeculationReasonEncoding encode(Supplier<SpeculationLog.SpeculationReasonEncoding> encodingSupplier) {
                                                                                  ^
  symbol:   class SpeculationReasonEncoding
  location: interface SpeculationLog
/home/zakkak/code/graal/substratevm/src/com.oracle.svm.graal/src/com/oracle/svm/graal/isolated/IsolatedSpeculationReason.java:41: error: cannot find symbol
    public SpeculationLog.SpeculationReasonEncoding encode(Supplier<SpeculationLog.SpeculationReasonEncoding> encodingSupplier) {
                         ^
  symbol:   class SpeculationReasonEncoding
  location: interface SpeculationLog
/home/zakkak/code/graal/substratevm/src/com.oracle.svm.graal/src/com/oracle/svm/graal/isolated/IsolatedSpeculationReasonEncoding.java:40: error: cannot find symbol
final class IsolatedSpeculationReasonEncoding extends ByteArrayOutputStream implements SpeculationLog.SpeculationReasonEncoding {
                                                                                                     ^
  symbol:   class SpeculationReasonEncoding
  location: interface SpeculationLog
3 errors

Compiling com.oracle.svm.graal with javac-daemon(JDK 11) failed
1 build tasks failed
```

**Comment by peter-hofer** [comment]
This is how @dougxc and I think this can be fixed:
1. Unimplement interface `SpeculationReasonEncoding` in `IsolatedSpeculationReasonEncoding` and create and implement a new interface that is identical.
1. `UnencodedSpeculationReason` is the class instantiated by `GraalServices` when `EncodedSpeculationReason` and `SpeculationReasonEncoding` are not available. Duplicate the code in `EncodedSpeculationReason` that does the encoding and change it so it does the same on an `UnencodedSpeculationReason` using reflection, using the new encoding interface created in step 1.
1. In `IsolatedSpeculationLog.maySpeculate` and `.speculate`, do an `instanceof` check on the argument. If it is an `UnencodedSpeculationReason`, use the duplicated code to get a byte array to pass over the isolate boundary. If it is any other class, use a `java.lang.Proxy` to implement `SpeculationReasonEncoding` that delegates to `IsolatedSpeculationReasonEncoding` and use reflection to invoke the `encode` method. Cache the proxy and reflection accessors in static variables.

**Comment by zakkak** [comment]
Thanks a lot @peter-hofer and @dougxc! I'll give it a go and come back :)

**Comment by zakkak** [comment]
Hello @peter-hofer, please find a draft PR [here](https://github.com/oracle/graal/pull/2945) implementing the above suggestions. I am not sure how to test these specific parts though, so please let me know how to test them if they are not covered by the standard `mx gate`.
