### ISSUE TITLE
PrinterJob.lookupPrintServices()

### ISSUE THREAD

**Issue by indalaterre** [oracle/graal#2949]
**Describe the issue**
I writter an app using quarkus that should use all the printers of the running host.
To do this a record the execution of that code for retrieving the printers in a Runtime Recorder of quarkus but seems that once the code is executed, it can't find any printer.

I created an issue on Quarkus board but they suggest me that could be a GraalVM problem

Attached there is a sample code:
[local-devices-client.zip](https://github.com/oracle/graal/files/5463622/local-devices-client.zip)

**Describe GraalVM and your environment:**
 - GraalVM version 20.2.0
 - JDK major version: 11
 - OS: macOS
 - Architecture: AMD64

**Comment by jramirez-isc** [comment]
Hi @indalaterre, I think you'd need to use the [native-image-agent](https://github.com/oracle/graal/blob/master/substratevm/BuildConfiguration.md#assisted-configuration-of-native-image-builds) to help you with the config files.

**Comment by dloiacono** [comment]
Hi @jramirez-isc unfortunately this didn't fix the issue.
Seems that the AWT support is not yet implemented.

**Comment by fernando-valdez** [comment]
Hello @dloiacono, 
In GraalVM version 21, it was included AWT support. Please test that version, if you find an error, please open a new ticket.
