### ISSUE TITLE
Build fails in PolyglotValue.java

### ISSUE THREAD

**Issue by oflebbe** [oracle/graal#295]
Using http://www.oracle.com/technetwork/oracle-labs/program-languages/downloads/index.html jvm and current graal git head to compile and I am hitting this compilation error 

`/tmp/graal/truffle/src/com.oracle.truffle.api.vm/src/com/oracle/truffle/api/vm/PolyglotValue.java:1243: error: method does not override or implement a method from a supertype
        @Override
        ^
/tmp/graal/truffle/src/com.oracle.truffle.api.vm/src/com/oracle/truffle/api/vm/PolyglotValue.java:1273: error: method does not override or implement a method from a supertype
        @Override
        ^
/tmp/graal/truffle/src/com.oracle.truffle.api.vm/src/com/oracle/truffle/api/vm/PolyglotValue.java:1723: error: cannot find symbol
                    polyglot.removeArrayElementUnsupported(receiver);
                            ^
  symbol:   method removeArrayElementUnsupported(Object)
  location: variable polyglot of type PolyglotValue
/tmp/graal/truffle/src/com.oracle.truffle.api.vm/src/com/oracle/truffle/api/vm/PolyglotValue.java:1864: error: cannot find symbol
                    polyglot.removeMemberUnsupported(receiver);
                            ^
  symbol:   method removeMemberUnsupported(Object)
  location: variable polyglot of type PolyglotValue
/tmp/graal/truffle/src/com.oracle.truffle.api.vm/src/com/oracle/truffle/api/vm/PolyglotProxy.java:461: error: cannot find symbol
                    return object.removeMember(key);
                                 ^
  symbol:   method removeMember(String)
  location: variable object of type ProxyObject
/tmp/graal/truffle/src/com.oracle.truffle.api.vm/src/com/oracle/truffle/api/vm/PolyglotProxy.java:474: error: cannot find symbol
                result = object.remove(index.longValue());
                               ^
  symbol:   method remove(long)
  location: variable object of type ProxyArray
6 errors

Compiling com.oracle.truffle.api.vm with javac-daemon failed
1 build tasks failed
`

**Comment by chumer** [comment]
It seems that you are trying to develop Graal/Truffle with GraalVM. In GraalVM Graal and Truffle are already part of the system, so if you want to develop Graal with it you are potentially getting two incompatible versions of Truffle and Graal on the classpath. Its like trying to modify the JDK while having a binary version of the JDK on the classpath.

So instead of using GraalVM to develop Truffle you should use the JVMCI JDK download also downloadable from the OTN page.

If you are trying to develop your own Truffle language, I'd recommend to use a similar setup as simplelanguage: https://github.com/graalvm/simplelanguage . There GraalVM is used and Truffle is used from the GraalVM binary and is not built from source.

Please close if this resolves your problem.

**Comment by oflebbe** [comment]
Nope. I just want to compile substratevm .

I followed the instructions at https://github.com/oracle/graal/blob/master/substratevm/README.md (Quickstart) using the labvm linked

**Comment by chumer** [comment]
You can download to separate VMs from the linked:
http://www.oracle.com/technetwork/oracle-labs/program-languages/downloads/index.html
GraalVM and LabsJDK. The latter is the one you need and is at the bottom of the page.

I have no other explanation for the problem you are seeing.

**Comment by dougxc** [comment]
Just to be sure, by "labvm", do you mean http://download.oracle.com/otn/utilities_drivers/oracle-labs/graalvm-0.31-linux-amd64-jdk8.tar.gz or http://download.oracle.com/otn/utilities_drivers/oracle-labs/labsjdk-8u151-jvmci-0.40-linux-amd64.tar.gz? By "JVMCI JDK", @chumer is referring to the latter.

**Comment by oflebbe** [comment]
Holy moly. I did not  see the labvm ! On my laptop screen, one has to actively scroll down beyond the legalise texts to the bottom of the page, suboptimal design IMHO. Thanks! Will try with this download.

**Comment by oflebbe** [comment]
Works now
