### ISSUE TITLE
migrate to travis-ci.com

### ISSUE THREAD

**Issue by dougxc** [oracle/graal#2956]
Given that travis-ci.org is shutting down on Dec 31st 2020m the Graal Travis config needs to be migrated to travis-ci.com.

https://mailchi.mp/3d439eeb1098/travis-ciorg-is-moving-to-travis-cicom

**Comment by zakkak** [comment]
Hello it looks like there is another change coming to travis

> We love our OSS teams who choose to build and test using TravisCI and we fully want to support that community. However, in recent months we have encountered significant abuse of the intention of this offering (increased activity of cryptocurrency miners, TOR nodes operators etc.). Abusers have been tying up our build queues and causing performance reductions for everyone. In order to bring the rules back to fair playing grounds, we are implementing some changes for our public build repositories.
>
>    For those of you who have been building on public repositories (on travis-ci.com, with no paid subscription), we will upgrade you to our trial (free) plan with a 10K credit allotment (which allows around 1000 minutes in a Linux environment).
    You will not need to change your build definitions when you are pointed to the new plan
    When your credit allotment runs out - we’d love for you to consider which of our plans will meet your needs.
    We will be offering an allotment of OSS minutes that will be reviewed and allocated on a case by case basis. Should you want to apply for these credits please open a request with Travis CI support stating that you’d like to be considered for the OSS allotment. Please include:
        Your account name and VCS provider (like travis-ci.com/github/[your account name] )
        How many credits (build minutes) you’d like to request (should your run out of credits again you can repeat the process to request more or discuss a renewable amount)
    Usage will be tracked under your account information so that you can better understand how many credits/minutes are being used

Source: https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing

**Comment by dougxc** [comment]
Hi @zakkak since you [migrated mx from Travis to GitHub actions](https://github.com/graalvm/mx/pull/224), is there any chance you could try do the same for the graal repo?

**Comment by zakkak** [comment]
Hi @dougxc, sure. In that case I suggest we close this issue in favour to https://github.com/oracle/graal/issues/2609 (which you can assign to me).

**Comment by dougxc** [comment]
Excellent - thanks for stepping up to this task!
