### ISSUE TITLE
Why is Oracle's "safe" AOT compilation so much expensive than others AOT strategies from compiled languages like C/C++ or Rust or even C#?

### ISSUE THREAD

**Issue by UltraBurstXD** [oracle/graal#2963]
Why is Java's AOT compilation more expensive (huge amount of resources usage) than others languages, that it requires 8GB+ (or maybe 16GB+ - DDR4 or DDR5 tech?) RAM or mid-end to high-end PCs? What is so especial about it? Does Oracle offers at least cloud AOT compilation function (It would waste all my data plan)? What about low end PCs with 4GB RAM and weak CPU (In these cases virtual memory doesn't help at all) like mine? Will there be at least native image "lite" version to reduce those impacts? And besides the RAM issue there is also the processor. I assume it requires a powerful one like i3 10th  gen (turbo boost), i5 8th gen (hyper threading), i7 7th gen (maybe 7700HQ...) or i9 7-8th gen (I think) and greater. But They're very, very expensive in many occasions. Ohh... I forgot the storage device type, I assume too that it requires SSD? About the processors there is AMD Ryzen series too... A very powerful model of AMD processors.

But what surprises me most, Google uses Java for AOT compilation on android studio and I personally used it few days ago. I think there's no much difference in terms of the AOT strategies used by both parts, that with only 4GB RAM and 2GB of Swap (I use RAM * 1/2 logic for swap), Ubuntu 20.04. But Google native image technology's well optimized. I don't wanna say that Java uses too much resources (What I think it's true), but is Java not going to work anymore on computers with only 4GB RAM in future? Is that what is being said indirectly?

**Comment by tarsa** [comment]
I am not involved in development of any AOT mechanism so I'll take some wild guesses here. All of the AOT approaches for high level languages needs some LTO (link time optimization) for good performance. LTO is expensive, both in terms of memory and CPU time as you need to track a lot of data through many compilation units. There are many factor affecting LTO resource usage, e.g.:
- amount of code that is LTO'd at once. Java's standard library is vastly bigger than Rust/ C/ C++ ones. Android standard library is probably much smaller than standard Java ones too. Standard library is not the only library a typical program uses, there are probably a lot of frameworks / libraries on the classpath and the Java ones are often quite fat. Android apps are optimized for quick installation and startup so they use lightweight solutions, therefore there's less code to LTO in AOT phase.
- amount of metadata needed for generating efficient code. Java relies a lot more on virtual methods than C#/ Rust/ C++ and static (closed world) devirtualization in AOT probably needs keeping a lot of metadata (for class hierarchy analysis) at once compared to dealing with non-virtual methods.

**Comment by UltraBurstXD** [comment]
JIT uses too much resources compared to GraalVM (I think it's more suitable for development time only), for my end users I was thinking about native image because it's nearly on par with C/C++ or Rust. And Workstation PC isn't so easy to find for AOT compilation. I think there was misunderstanding, I meant Java AOT compilation is very costly. Not the native image.

**Comment by tarsa** [comment]
I think Java code that is compatible with (currently memory hungry) AOT is also compatible with JIT, so you can develop using GraalVM JIT and then occasionally compile with GraalVM AOT. Also since you've asked about Oracle's offerings, there's a new (?) cloud offer that is cheaper than competition according to Oracle's website: https://www.oracle.com/cloud/economics/

**Comment by fernando-valdez** [comment]
Hi @UltraBurstXD,

As described at https://www.graalvm.org/reference-manual/native-image/, the executable generated by native-image "includes the application classes, classes from its dependencies, runtime library classes, and statically linked native code from JDK."
In contrast, when you compile a C program, you do not compile the entire C library, and all other dependencies, along with it. The two approaches are simply not comparable.

One reason GraalVM native image analyzes the entire library is to only compile the classes that the application really needs. Another reason is to allow initialization of classes at build time (https://www.graalvm.org/reference-manual/native-image/ClassInitialization/).
