### ISSUE TITLE
Clean up file descriptors opened by java.net.PlainSocketImpl#initProto on isolate tear-down

### ISSUE THREAD

**Issue by antonliauchuk-tealium** [oracle/graal#2967]
**Describe the issue**
hello @peter-hofer 
I have a question about opened file descriptors during the http requests inside the isolate. The example of code for showing the issue:
```         import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.HttpURLConnection;
import java.net.URL;
import java.nio.charset.StandardCharsets;
import java.util.stream.Collectors;
import org.graalvm.nativeimage.IsolateThread;
import org.graalvm.nativeimage.Isolates;
import org.graalvm.nativeimage.Isolates.CreateIsolateParameters;
import org.graalvm.nativeimage.c.function.CEntryPoint;
public class OpenedFileDescriptors {
	private static final String URL = "http://localhost:8085";
	public static void main(String[] args) throws IOException, InterruptedException {
		//no opened file descriptors
		httpConnectionOutsideIsolate();
		printOpenedFileDescriptors();
		//a lot of file descriptors
		httpConnectionInsideIsolate();
		printOpenedFileDescriptors();
	}
	private static void printOpenedFileDescriptors() throws IOException, InterruptedException {
		String[] cmd = { "/bin/sh", "-c", "lsof -n | cut -f1 -d' ' | uniq -c | sort | tail" };
		Process pr = Runtime.getRuntime().exec(cmd);
		BufferedReader input = new BufferedReader(new InputStreamReader(pr.getInputStream()));
		String line;
		try {
			while ((line = input.readLine()) != null)
				System.out.println(line);
		} catch (IOException e) {
			e.printStackTrace();
		}
		int exitVal = pr.waitFor();
	}
	public static void httpConnectionOutsideIsolate() {
		System.out.println("------------ HTTP Requests Without Isolate ------------");
		var iterations = 5000;
		while (iterations > 0) {
			iterations--;
			try {
				httpRequestsInsideLoop();
			} catch (Throwable t) {
				t.printStackTrace();
			}
		}
	}
	public static void httpConnectionInsideIsolate() {
		System.out.println("------------ HTTP Requests Inside Isolate ------------");
		var iterations = 5000;
		while (iterations > 0) {
			iterations--;
			var context = Isolates.createIsolate(CreateIsolateParameters.getDefault());
			nativeWrapper(context);
			Isolates.tearDownIsolate(context);
		}
	}
	@CEntryPoint
	public static void nativeWrapper(@CEntryPoint.IsolateThreadContext IsolateThread context) {
		try {
			httpRequestsInsideLoop();
		} catch (Exception e) {
			e.printStackTrace();
		}
	}
	public static void httpRequestsInsideLoop() {
		try {
			//open connection
			var connection = (HttpURLConnection) new URL(URL).openConnection();
			//set method
			connection.setRequestMethod("POST");
			//ensure connection will be closed
			connection.setRequestProperty("Connection", "close");
			connection.setDoOutput(true);
			try (var out = connection.getOutputStream()) {
				out.write("{'param':'value'}".getBytes(StandardCharsets.UTF_8));
				out.flush();
			}
			//get response code
			int responseCode = connection.getResponseCode();
			var responseMessage = connection.getResponseMessage();
			//process response body
			String response = null;
			try (var inputStream = is2xx(responseCode) ? connection.getInputStream() : connection.getErrorStream()) {
				if (inputStream != null) {
					try (var in = new BufferedReader(new InputStreamReader(inputStream))) {
						response = in.lines().collect(Collectors.joining("\n"));
					}
				}
			}
			var headers = connection.getHeaderFields();
//			System.out.println("HTTP call is completed, code = " + responseCode + ", response message = " + responseMessage + ", response = " + response);
		} catch (Exception e) {
			e.printStackTrace();
		}
	}
	private static boolean is2xx(int code) {
		return code >= 200 && code <= 299;
	}
}
```

Commands for running the sample:
```echo "Main-Class: OpenedFileDescriptors" > manifest.txt && javac OpenedFileDescriptors.java &&  jar -cvfm OpenedFileDescriptors.jar manifest.txt OpenedFileDescriptors.class && native-image -H:EnableURLProtocols=http -jar OpenedFileDescriptors.jar
./OpenedFileDescriptors
```

After running this sample, I have about ~5000 opened file descriptors, I’m checking that by command:
```lsof -n | cut -f1 -d' ' | uniq -c | sort | tail
...
5014 OpenedFil
```

in the case of listing these files by particular OpenedFileDescriptors, I’m getting big list with rows like:
```sudo lsof -n | grep OpenedFil
...
OpenedFil 67476      antonliauchuk *195u     unix 0xc95dc6f223059c6b         0t0                     ->(none)
OpenedFil 67476      antonliauchuk *196u     unix 0xc95dc6f223059ba3         0t0                     ->(none)
OpenedFil 67476      antonliauchuk *197u     unix 0xc95dc6f223059adb         0t0                     ->(none)
OpenedFil 67476      antonliauchuk *198u     unix 0xc95dc6f22305a503         0t0                     ->(none)
```

After changing the number of iterations from 5000 to 50 000, locally I’m getting the errors like ‘java.net.SocketException: Too many open files’.
It looks like we have this issue because after closing the isolate, we don’t have executed logic of ‘finalize’ of sockets for cleaning up the file descriptors. Do you have any idea how to clean these file descriptors  during the closing of isolate? and is it expected behavior for isolates? In the case of running this logic without isolates, everything is fine.

We have this issues because of executing java.net.PlainSocketImpl#initProto for each isolate, please view the comment for details.

**Describe GraalVM and your environment:**
 - GraalVM 20.1.0

**Comment by antonliauchuk-tealium** [comment]
@peter-hofer 
I found out that the issue is in java.net.PlainSocketImpl#initProto which is executed inside static block during first accessing to PlainSocketImpl class.
inside native code, there is a logic of creating marker_fd http://hg.openjdk.java.net/jdk8/jdk8/jdk/file/tip/src/solaris/native/java/net/PlainSocketImpl.c (getMarkerFD() function)
in the case of isolates, we are creating this marker_fd each time of accessing to PlainSocketImpl

It's critical issue in the case of creating/tearing down multiple isolates for a long time of application. We will get ‘java.net.SocketException: Too many open files’ after some critical number of opened file descriptors

**Comment by peter-hofer** [comment]
@antonliauchuk-tealium , thank you for your analysis. I don't think there is a good way to work around this for now, as `marker_fd` is declared as a `static` variable and so it won't have a symbol with which it can be accessed.

**Comment by antonliauchuk-tealium** [comment]
yes, we discussed with team this issue and also, didn't find good working solution. For now, we are preparing workaround for our project but it's not clear how to prepare good fix for that.

It looks like good solution can with overriding .c/.h sources for PlainSocketImpl but it's not clear how much sources will be copied from jdk in this case

**Comment by peter-hofer** [comment]
This is no longer an issue in GraalVM distributions based on JDK 17 or later after sockets have been reimplemented with NIO as of JDK 13 and the legacy implementation has been removed as of JDK 18.
