### ISSUE TITLE
Native image fatal error building trivial program

### ISSUE THREAD

**Issue by kirillp** [oracle/graal#2969]
**Describe the issue**

```
class ClassB { }
class ClassC extends ClassB { }
class ClassA {
  public static ClassB I = new ClassB();
}
public class MainClass {
  public static void main(String[] args) {
    ClassA.I = new ClassC();
  }
}
```

**Steps to reproduce the issue**
Please include both build steps as well as run steps
 - Build the file with native image

**Describe GraalVM and your environment:**
 - GraalVM version: graalvm-ce-java11-20.2.0
 - JDK major version: 11
 - OS: macOS 
 - Architecture: AMD64, ARM

**Comment by kirillp** [comment]
exception message
https://gist.githubusercontent.com/kirillp/1cdb773aaaf454aa07a637de3b6f0e50/raw/becc42bf283a83d912b59b2ee5c8cfe98e057629/gistfile1.txt

**Comment by jramirez-isc** [comment]
Hi @kirillp 
Thanks for reporting this.

I was able to reproduce the error you mentioned.
Interestingly, if you do something like this in your main method the native image builds and runs fine:

```
  public static void main(String[] args) {
    ClassA.I = new ClassC();
    System.out.println(ClassA.I);
  }
```

**Comment by shafqatevo** [comment]
We are also waiting for this to resolve. Our use case is to be able to use Akka in iOS.

**Comment by cstancu** [comment]
Fixed by https://github.com/oracle/graal/commit/d2a004ce948c3789aaaa92214b1d537b108e906b
