### ISSUE TITLE
GraalVM on s390x: Build steps

### ISSUE THREAD

**Issue by AnitaNayak** [oracle/graal#2980]
We are exploring on Quarkus and want to build cloud native applications. But GraalVM is not available on s390x. Could this be available on s390x soon.

Could anyone please send the build steps to build GraalVM on s390x.

**Comment by dougxc** [comment]
The major blocker for s390x will be the lack of a [JVMCI port](https://openjdk.java.net/jeps/243) for that platform.

**Comment by adinn** [comment]
JVMCI is part of OpenJDK so porting JVMCI to s390x really requires co-operation and support from the OpenJDK project. You might possibly convince the project to make the necessary changes in the OpenJDK dev tree but it would be extremely difficult to get them backported to jdk11u. Alternatively, you could try to convince the Oracle GraalVM team to add s390x to JVMCI in the downstream OpenJDK releases from which they build GraalVM without trying to upstream it first. I'd advise against that as it invariably causes significant extra maintenance work.

Note that that latter resolution would be far from perfect for other reasons. Red Hat do endeavour to provide community support for Quarkus on Oracle releases of GraalVM and we would aim to do so for a s390x release if it were available. However, currently we have no plan to provide paid support for Quarkus running on anything other than our own Mandrel releases of GraalVM. Those are based on upstream jdk11u and only provided for x86_64 or AArch64.

Also, -- and this is perhaps a much more significant issue - porting JVMCI only fixes part of the problem. You would still need to port the Graal compiler and GraalVM native linker to work on s390x, or convince Oracle to do so -- Red Hat certainly has no plans at present to extend GraalVM to support s390x. I am fairly sure this would be a bigger job than the JVMCI port. The one aspect of this second task that would be simpler is that it would be solely within the control of the GraalVM project.

**Comment by AnitaNayak** [comment]
Thank you so much for the detail @adinn @dougxc .
