### ISSUE TITLE
Graalvm does not start on Mac OS Big Sur

### ISSUE THREAD

**Issue by valdo404** [oracle/graal#2984]
**Describe the issue**
Graalvm does not start on bigsur

**Steps to reproduce the issue**
Try to use graalvm on Mac OS X

**Describe GraalVM and your environment:**
 - graalvm-ce-java11-20.2.0
 - OS: **Mac OS Big Sur**
 - Architecture: **x86-64**

**More details**
Add any other information about the problem here. Especially important are stack traces or log output. Feel free to link to gists or to screenshots if necessary.
```
ERROR: java.lang.IllegalStateException: com.oracle.truffle.llvm.runtime.except.LLVMLinkerException: Library "/usr/lib/libSystem.B.dylib" does not exist.
org.graalvm.polyglot.PolyglotException: java.lang.IllegalStateException: com.oracle.truffle.llvm.runtime.except.LLVMLinkerException: Library "/usr/lib/libSystem.B.dylib" does not exist.```

**Comment by dougxc** [comment]
Tracked internally by GR-26569.

**Comment by oubidar-Abderrahim** [comment]
The issue with Big Sur was already mentioned in #2897, but since this one is clearer and easier to search we will keep it for tracking and close the first one.

**Comment by rschatz** [comment]
Should be fixed by https://github.com/oracle/graal/commit/d260d6834c9e52adbf26b8f2fe477d4b78e400c1
