### ISSUE TITLE
Rogue proxy/lambda entries in the agent captured reflect-config.json files

### ISSUE THREAD

**Issue by aclement** [oracle/graal#2990]
**Describe the issue**
When collecting configuration via the agent, the `reflect-config.json` can sometimes contain entries that I'm not sure should be there. Entries for JDK proxies and entries for lambdas:
```
{
  "name":"com.sun.proxy.$Proxy34",
  "allDeclaredFields":true,
  "allDeclaredMethods":true,
  "methods":[
...
{
"name":"org.springframework.boot.autoconfigure.jdbc.metadata.DataSourcePoolMetadataProvidersConfiguration$HikariPoolDataSourceMetadataProviderConfiguration$$Lambda$347/0x0000000840241040",
  "allDeclaredFields":true,
  "allDeclaredMethods":true,
```

**Steps to reproduce the issue**
I am using graalvm-ce-java11-20.3.0-dev-20201112

1. **git clone https://github.com/spring-projects-experimental/spring-graalvm-native.git**
2. **cd spring-graalvm-native/spring-graalvm-native-samples/batch**
3. **mvn clean package**
4. **mkdir -p graal/META-INF/native-image**
5. **java -agentlib:native-image-agent=config-output-dir=graal/META-INF/native-image -jar target/batch-0.0.1-SNAPSHOT.jar**
6. app should terminate after a few seconds
Review graal/META-INF/native-image/reflect-config.json see the unexpected entries.

**Describe GraalVM and your environment:**
 -  graalvm-ce-java11-20.3.0-dev-20201112
 - OS: **macOS Catalina**

**Comment by vjovanov** [comment]
How would I verify that the image still works after I remove these inputs?

**Comment by vjovanov** [comment]
After a discussion with @peter-hofer we agreed that the best solution is to: 
1. For lambdas try and introduce a stable name that would be valid across the agent and Native Image runs. We need this anyhow for serialization.
2. For proxies, we should filter them out, but we should also allow all the methods and fields in proxies to be accessible by reflection. We would take this approach only if allowing access to proxies doesn't increase image size overly much.

This is not a blocker or a breaking feature so I am pushing it to 21.1. due to the complexity of the required change.

**Comment by aclement** [comment]
Hey,

> How would I verify that the image still works after I remove these inputs?

I'l include this for completeness for the future. Basically we would rebuild the app with that config on the class path and ensure it doesn't fall over. This is possible via:
1. open `compile.sh`, where it supplies `-cp $CP` near the bottom, tweak that to `-cp $CP:../../graal` to add the agent generated config as input. 
2. Now run `build.sh` - this will run `compile.sh` and then automatically test the image according to what is in `verify.sh`

**Comment by Eng-Fouad** [comment]
Any updates regarding this issue?

**Comment by peter-hofer** [comment]
@Eng-Fouad thanks for the reminder! Proxy classes have already been filtered for a while, and I have recently added filtering for lambdas too, which is part of 22.2: 18c276f625350ea50c695971068f5b758756c5db
Please report if there are still issues.
