### ISSUE TITLE
native-image-maven-plugin crash on windows with long command lines

### ISSUE THREAD

**Issue by jonenst** [oracle/graal#2995]
**Describe the issue**
Using native-image-maven-plugin 20.3, in my case the command line generated by native-image-maven-plugin is about 15k characters (all the jars) and maven crashes with "The command line is too long."

More details on
https://github.com/oracle/graal/pull/2596#issuecomment-730310898

**Steps to reproduce the issue**
To reproduce, you need jars with a long prefix.. example public run:
https://github.com/powsybl/powsybl-open-loadflow/runs/1414612072 

**Describe GraalVM and your environment:**
 - GraalVM version CE 20.3

**More details**
```
[INFO] Executing: C:\hostedtoolcache\windows\jdk\11.0.0\x64\bin\native-image.cmd -cp [... many many jars ] --no-fallback --allow-incomplete-classpath -H:Class=com.powsybl.tools.Main -H:Name=olf
The command line is too long.
```

**Comment by Paradox98** [comment]
I encountered the same problem, has it been resolved?

**Comment by ch4mpy** [comment]
Hi all, trying to build a  spring-boot app native image on windows, I'm stuck on this too.

Any plan to such builds on Windows platform?

**Comment by olpaw** [comment]
Hi @ch4mpy 
The original native-image-maven-plugin is not used anymore. There is now a new plugin instead
https://github.com/graalvm/native-build-tools/blob/master/native-maven-plugin/README.md
maintained by @lazar-mitrovic

**Comment by lazar-mitrovic** [comment]
Related issue: https://github.com/graalvm/native-build-tools/issues/85

**Comment by olpaw** [comment]
Closing this issue since this is now tracked under https://github.com/graalvm/native-build-tools/issues/85
