### ISSUE TITLE
Core dump using native image agent with 20.3.0 and Java 8

### ISSUE THREAD

**Issue by ilopmar** [oracle/graal#2998]
**Describe the issue**

I was trying to use the native image agent with 20.3.0 release and when I start my application it fails. This was working with 20.2.0.

This fails using Java 8 but it works with Java 11.

**Steps to reproduce the issue**

- `git clone https://github.com/micronaut-graal-tests/micronaut-basic-app`
- `cd micronaut-basic-app`
- `git checkout 2.2.x`
- `echo "run.jvmArgs('-agentlib:native-image-agent=config-output-dir=tmp')" >> build.gradle` 
- Use GraalVM 20.3.0 for Java 8
- `./gradlew run`

**Describe GraalVM and your environment:**
 - GraalVM version: **[CE 20.3.0**
 - JDK major version: **8**
 - OS: **Linux**
 - Architecture: **AMD64**

**More details**

```
$ ./gradlew run

> Task :compileJava FROM-CACHE
> Task :processResources
> Task :classes

> Task :run FAILED
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007ff7fef8b48a, pid=95205, tid=0x00007ff8042b9700
#
# JRE version: OpenJDK Runtime Environment (8.0_272-b10) (build 1.8.0_272-b10)
# Java VM: OpenJDK 64-Bit Server VM GraalVM CE 20.3.0 (25.272-b10-jvmci-20.3-b06 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  [libnative-image-agent.so+0x5248a]
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /tmp/micronaut-basic-app/hs_err_pid95205.log
#
# If you would like to submit a bug report, please visit:
#   https://github.com/oracle/graal/issues
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#

FAILURE: Build failed with an exception.
```

[hs_err_pid95205.log](https://github.com/oracle/graal/files/5573235/hs_err_pid95205.log)

**Comment by mcraj017** [comment]
@ilopmar thanks for reporting the issue
we will check it out

**Comment by vjovanov** [comment]
This is a Java 8 issue for native-image. We tend to prioritize Java 11 issues as they are more impactful for the community.

**Comment by ilopmar** [comment]
I understand that it's good to prioritize Java 11 issues but this one seems to be important enough to give it some love :-), and I don't know, maybe release a 20.3.1 with the fix.

Btw, I always try Micronaut applications first with Java 8 and once they work I try them with Java 11. I've found in the past issues that were only present in Java 11 (and reported them, of course).

**Comment by vjovanov** [comment]
@ilopmar can you give an example where building a native-image on Java 8 can't be replaced with a native-image on Java 11? Even in the case of the agent, I believe all Java 8 code should run on Java 11. I can't find this to be dangerous because the agent run on Java 11 is not a production run so there is really no potential fears of crashing.

Also, when building a native-image, the change of technology is already so big that moving to 11  should not be much of a problem. 

In the future, Java 11 will be better supported than Java 8 so it would be good to change the workflow to simply use Java 11 from the get go.

**Comment by ilopmar** [comment]
@vjovanov the latest issue I've found that works on Java 8 but fails in Java 11 is this https://github.com/oracle/graal/issues/3028
  
> Also, when building a native-image, the change of technology is already so big that moving to 11 should not be much of a problem.
> In the future, Java 11 will be better supported than Java 8 so it would be good to change the workflow to simply use Java 11 from the get go.

Right, I totally agree with this, we should move forward and start using Java 11. In our new Maven plugin for Micronaut we are defaulting to Java 11 if the users want to build an static image because we can use musl.
Maybe what you (the GraalVM team) can do to "push" the move to Java 11 is simply deprecate Java 8. Saying something like: _Starting in GraalVM x.y.x Java 8 is not supported anymore and no improvements or bug fixing will be done_. You can put a blog post explaining the decision with details and I'm pretty sure the community won't have problems following you.
After all Java 8 is EOL since quite sometime (although there are a lot of vendors that still support it) and when you choose a new technology like native images it makes sense to use the latest version (i.e. Java 11).

**Comment by peter-hofer** [comment]
I debugged this and the problem occurs during agent initialization when we don't receive a `VMStart` event and get `VMInit` right away and crash because we assume that initializations in `VMStart` have already happened. This was bug [JDK-8254673](https://bugs.openjdk.java.net/browse/JDK-8254673) in OpenJDK 8 and has been fixed since. Please try GraalVM 21.0 or 20.3.1 which are based on newer JDK 8 releases and reopen if this problem still occurs.

**Comment by ilopmar** [comment]
Thanks! I've tried again with 21.0 and it works properly :)

**Comment by qianyiyong** [comment]
> I debugged this and the problem occurs during agent initialization when we don't receive a `VMStart` event and get `VMInit` right away and crash because we assume that initializations in `VMStart` have already happened. This was bug [JDK-8254673](https://bugs.openjdk.java.net/browse/JDK-8254673) in OpenJDK 8 and has been fixed since. Please try GraalVM 21.0 or 20.3.1 which are based on newer JDK 8 releases and reopen if this problem still occurs.

Thanks! I got the same problem on 20.3.0, I'll try 21.0....
