### ISSUE TITLE
Semantics of TruffleBoundary.allowInlining changed in GraalVM

### ISSUE THREAD

**Issue by arthurp** [oracle/graal#300]
The semantics of TruffleBoundary.allowInlining seems to have changed in GraalVM 0.31. Specifically, if allowInlining = true the function may be inlined *during partial evaluation*. This causes errors such as overly deep inlining due to trying to partial evaluation of j.l.invoke.MethodHandle.asType (and internally makeImpl). But this is also visible using neverPartOfCompilation.

I have written an example: https://gist.github.com/arthurp/bbfe1a72b350647e9deb1ab12db504ce

This problem is a regression if the intended allowInlining semantics is that Graal is allowed to do inlining, but the boundary still prevents partial evaluation. If however allowInlining is supposed to allow optional partial evaluation through the boundary then this is a documentation bug.

**Comment by chumer** [comment]
Your assumption is right, partial evaluation should always stop at the boundary, independent whether its inlined or not.

**Comment by chumer** [comment]
We have verified your example. Thanks! It seems a change sneaked in that made this methods already inline during bytecode parsing. We will fix ASAP.

In the meantime, as a workaround, you need to keep allowInlining false.

**Comment by axel22** [comment]
This should be fixed in: https://github.com/oracle/graal/commit/0ef59f0f331702dc9bb4b3621563fc63c7133b02
