### ISSUE TITLE
-H:IncludeResources stopped working in GraalVM 20.3.0

### ISSUE THREAD

**Issue by ppalaga** [oracle/graal#3003]
**Describe the issue**

`-H:IncludeResources` used to be a common way in GraalVM 20.2.0's `native-image` to include native resources. It does not seem to work anymore in 20.3.0

**Steps to reproduce the issue**

I have created a simple reproducer project in https://github.com/ppalaga/include-resources

```
git clone git@github.com:ppalaga/include-resources.git
cd include-resources

# Test with 20.2.0
export JAVA_HOME=~/bin/graalvm/graalvm-ce-java11-20.2.0

$JAVA_HOME/bin/java -version
openjdk version "11.0.8" 2020-07-14
OpenJDK Runtime Environment GraalVM CE 20.2.0 (build 11.0.8+10-jvmci-20.2-b03)
OpenJDK 64-Bit Server VM GraalVM CE 20.2.0 (build 11.0.8+10-jvmci-20.2-b03, mixed mode, sharing)

mvn clean package

./app/target/app # the output is as expected, both resources are there in the image
app/app-resource.txt: Hello from the app
module/module-resource.txt: Hello from the module

# Now test with 20.3.0
export JAVA_HOME=~/bin/graalvm/graalvm-ce-java11-20.3.0

$JAVA_HOME/bin/java -version
openjdk version "11.0.9" 2020-10-20
OpenJDK Runtime Environment GraalVM CE 20.3.0 (build 11.0.9+10-jvmci-20.3-b06)
OpenJDK 64-Bit Server VM GraalVM CE 20.3.0 (build 11.0.9+10-jvmci-20.3-b06, mixed mode, sharing)

mvn clean package

./app/target/app # the output is not OK, none of the resources is there in the image
app/app-resource.txt not available
module/module-resource.txt not available
```

**Describe GraalVM and your environment:**
 - GraalVM version: see above
 - JDK major version: see above
 - OS: Fedora 31
 - Architecture: AMD64

**Comment by ppalaga** [comment]
Attaching debugger to the native-image process and setting a breakpoint straight at the beginning of `com.oracle.svm.hosted.NativeImageGeneratorRunner.JDK9Plus.main(String[])` reveals that backslashes in the command line arguments are doubled where they should not be:
![image](https://user-images.githubusercontent.com/1826249/99908241-c471fb00-2ce1-11eb-8588-ce6d8e2e6b7e.png)

This is perhaps the reason why the resource paths do not match the regular expressions passed via `-H:IncludeResources`

**Comment by ppalaga** [comment]
Running the same scenario with 20.2.0 shows the slashes non-doubled as expected:
![image](https://user-images.githubusercontent.com/1826249/99908393-b670aa00-2ce2-11eb-8172-0576f4ec210f.png)

**Comment by ppalaga** [comment]
This might be caused by d72991abcc1346be7f87bec18ef329c0b7310c51, esp. [here](https://github.com/oracle/graal/commit/d72991abcc1346be7f87bec18ef329c0b7310c51#diff-9e053bec9eca0799896bd471363fa6aa1df70269e454b89dff1ea5fb844a480cR1263) I guess the [quoteFileArg() method](https://github.com/oracle/graal/commit/d72991abcc1346be7f87bec18ef329c0b7310c51#diff-9e053bec9eca0799896bd471363fa6aa1df70269e454b89dff1ea5fb844a480cR1279) was designed to work well on Windows and it perhaps does not work well on Linux (and possibly also on Mac)? WDYT @quintesse?

**Comment by ppalaga** [comment]
Looking at how the backslash escaping in java argument files is explained in https://docs.oracle.com/javase/9/tools/java.htm#JSWOR-GUID-BE93ABDC-999C-4CB5-A88B-1994AAAC74D5 

> To output the following:
>
> `-cp c:\Program Files (x86)\Java\jre\lib\ext;c:\Program Files\Java\jre9\lib\ext`
>
> The backslash character must be specified in the argument file as:
>
> `-cp  "c:\\Program Files (x86)\\Java\\jre\\lib\\ext;c:\\Program Files\\Java\\jre9\\lib\\ext"`

I guess we need to circumfix args containing backslashes with double quotes like we do with args containing spaces.

**Comment by ppalaga** [comment]
I am working on a fix @gradinac if you do not mind.

**Comment by gradinac** [comment]
Hey @ppalaga! Thank you for contributing to the project! :)
@d-kozak iz working on this, he will integrate a fix for it as part of a larger change. I will reassign the issue to him

**Comment by ppalaga** [comment]
I have proposed a fix in https://github.com/oracle/graal/pull/3015

**Comment by ppalaga** [comment]
https://github.com/oracle/graal/commit/e54f5cfb0dcc21c777bafec9bcba02be2208afd5 fixed the scenario described in this issue, but it is still possible to construct a set of arguments that do not work as expected - see https://github.com/oracle/graal/issues/3033
