### ISSUE TITLE
GraalVM's Node does not support WebAssembly.

### ISSUE THREAD

**Issue by pergamonster** [oracle/graal#3004]
Currently, GraalVM's Node does not support WebAssembly.

There are plans for adding support to WebAssembly for GraalVM's Node. But there is no guarantee when It will be ready.

Unfortunately, there is no workaround for this, using GraalVM.

_Originally posted by @oubidar-Abderrahim in https://github.com/oracle/graal/issues/2804#issuecomment-686354440_

Any update on progress?

**Comment by wirthi** [comment]
Our plan is to support it roughly the same time we switch to the Node.js 14.x branch in GraalVM 21.x.

We cannot promise any exact date of availability.

**Comment by doctorpangloss** [comment]
In the meantime, using this https://github.com/Kagami/wasm-polyfill.js as a polyfill seems to work for me and fixes https://github.com/oracle/graal/issues/2804

**Comment by wirthi** [comment]
The GraalVM 21.1 release (expected to be released on April 20th) will have some prelimiary, experimental support for WASM. Don't expect a fully working engine, but it should be able to execute basic usecases already. Looking forward to your feedback on this and extend and improve the support in the next releases.

https://github.com/oracle/graaljs/blob/master/CHANGELOG.md#version-2110

**Comment by wirthi** [comment]
Graal.js and GraalVM's Node.js implementation now supports WASM. To enable it, you might have to pass the `--js.webassembly` flag and/or add `--jvm --polyglot`, depending on your setup.

Note that it still is considered an experimental feature, thus the `--experimental-options` needs to be passed as well. We are collecting feedback at the moment to improve this feature, with the goal of providing it with full support. Let us know of any bugs or incompatibilities you might find.

**Comment by apatrida** [comment]
Vite seems to use wasm, so I tried this on a solid start app and it just locks up hard.

```
/somewhere/native-version/bin/node --polyglot --js.webassembly --experimental-options ../../node_modules/.pnpm/solid-start@0.3.5_@solidjs+meta@0.28.6_@solidjs+router@0.8.3_solid-js@1.7.11_solid-start-node@0.3.5_vite@4.4.9/node_modules/solid-start/bin.cjs dev  

```

that last command `dev` doesn't matter. change to `build` or `start` and they all lockup somewhere after they start the WASM.

error without WASM turned on:

```
ReferenceError: WebAssembly is not defined

/node_modules/.pnpm/vite@4.4.9_@types+node@20.5.0_sass@1.62.0/node_modules/vite/dist/node/chunks/dep-df561101.js:16472:1125
```
