### ISSUE TITLE
Other targets ?

### ISSUE THREAD

**Issue by RUSshy** [oracle/graal#301]
Hello

Do you plan to support other targets such as win32, iOS, web assembly ?

Thanks!

**Comment by thomaswue** [comment]
We do have concrete plans to support Windows. We are exploring iOS and WebAssembly as possible targets, but there are no plans at this point in time. For WebAssembly, one blocker is the inability to walk the stack.

**Comment by volth** [comment]
> We do have concrete plans to support Windows

Roughly when? Any estimation?

**Comment by thomaswue** [comment]
We are targeting mid of this year for Windows support.

**Comment by tonykero** [comment]
Perhaps you could get some stuff knowledge from https://github.com/konsoletyper/teavm ?

**Comment by tonykero** [comment]
Perhaps you could get some stuff from https://github.com/konsoletyper/teavm ?

**Comment by RUSshy** [comment]
Is there progress on windows ?

**Comment by thomaswue** [comment]
Yes. There is a Windows preview for download at the bottom of http://www.oracle.com/technetwork/oracle-labs/program-languages/downloads/index.html. It does not yet support native image at the moment, but only the OpenJDK-based target platform.

**Comment by RUSshy** [comment]
Thanks!!
