### ISSUE TITLE
Tracing agent crash with 20.3.0 and Java 8

### ISSUE THREAD

**Issue by sdeleuze** [oracle/graal#3010]
Spring builds with the tracing agent shows that some (not all) samples crashes with the agent when Java 8 is used, Java 11 is fine. See attached report for more information.

[hs_err_pid992.log](https://github.com/oracle/graal/files/5581806/hs_err_pid992.log)

**Comment by zakkak** [comment]
Possible duplicate of #2998

**Comment by peter-hofer** [comment]
@zakkak thanks for linking this issue, it crashes at the exact same location.
As I've commented on #2998, this is likely caused by a JDK bug that has been fixed since. Please try GraalVM 21.0 or 20.3.1 which are based on newer JDK 8 releases and reopen if this problem still occurs.
