### ISSUE TITLE
[vscode] VS Code extension for GraalVM 20.3 not yet published to VS Marketplace

### ISSUE THREAD

**Issue by fniephaus** [oracle/graal#3014]
**Describe GraalVM and your environment :**
 - GraalVM version or commit id if built from source: **20.3**
 - CE or EE: **CE**
 - JDK version: **JDK11**
 - OS and OS Version: **macOS Catalina**
 - Architecture: **amd64**

**Describe the issue**
I understand the VS Code extension is released as Technology Preview. Nonetheless, I think it makes sense to update it in the VS Marketplace whenever a new GraalVM is released. Currently, `0.0.10` from 8/7/2020 is the latest version available (see screenshot below). However, [the GraalVM 20.3 release contains `0.0.11`](https://github.com/oracle/graal/blob/e97ad6237638246ff555657ddf48976a03a53d2e/vscode/graalvm/package.json#L5).

As a side note, our [Polyglot Live Programming extension](https://github.com/hpi-swa/polyglot-live-programming) requires `0.0.11` or later. So our users currently have to build the updated extension manually and can't just download it from the marketplace.

<img width="770" alt="image" src="https://user-images.githubusercontent.com/2368856/99966540-bd58f480-2d96-11eb-889e-c222d2a8c1d7.png">

**Comment by MartinBalin** [comment]
Extensions went live today morning.

**Comment by fniephaus** [comment]
Excellent, thank you!
