### ISSUE TITLE
[interop] Unable to export all interop messages due to "State space too big"

### ISSUE THREAD

**Issue by fniephaus** [oracle/graal#3023]
**Describe GraalVM and your environment :**
 - GraalVM version or commit id if built from source: **20.3**
 - CE or EE: **CE**
 - JDK version: **JDK8**
 - OS and OS Version: **macOS Catalina**
 - Architecture: **amd64**

**Have you verified this issue still happens when using the latest snapshot?**
yes

**Describe the issue**
As [`InteropLibrary`](https://github.com/oracle/graal/blob/dcf9e763901cab8f955ad54cc16c6c3a41232f79/truffle/src/com.oracle.truffle.api.interop/src/com/oracle/truffle/api/interop/InteropLibrary.java) keeps growing, I am now hitting problems with the annotation processor when exporting "too many" interop messages (e.g. "State space too big 68. Only <= 64 supported.").

Instead of generating one specialization per exported message, maybe a node should be generated? Increasing the specialization limit does not seem to be a good solution. Alternatively, `InteropLibrary` could be split into smaller chunks (e.g. `InteropMemberLibrary`, `InteropExceptionLibrary`, ...). I assume it is rather common that the user calls related methods on the same library (e.g. for accessing members, dealing with exceptions, ...). For PE, it makes sense to use multiple specialized interop libraries anyway. So maybe splitting up `InteropLibrary` is a better solution?

/cc @chumer

**Comment by chumer** [comment]
Tracked internally as GR-27711

**Comment by chumer** [comment]
Arbitrary state space is now supported.
See https://github.com/oracle/graal/commit/ce51ea5eb89d072bda8b0fb6b36152950fd6eb8f
