### ISSUE TITLE
Failing to use native image with Kawa Scheme

### ISSUE THREAD

**Issue by duncanmak** [oracle/graal#3024]
**Describe the issue**

I'm trying to build a native image with JavaFX code using Kawa Scheme.

**Steps to reproduce the issue**
https://github.com/duncanmak/kawa-javafx-graalvm, run `mvn client:build`.

This is a project that uses the GluonHQ maven plugins.

**Describe GraalVM and your environment:**
 - GraalVM version - 
```
graalvm-ce-java11-20.3.0
```
 - JDK major version: 
```
openjdk 13.0.2 2020-01-14
OpenJDK Runtime Environment (build 13.0.2+8)
OpenJDK 64-Bit Server VM (build 13.0.2+8, mixed mode, sharing)
```
 - OS:
```
ProductName:	Mac OS X
ProductVersion:	10.15.7
BuildVersion:	19H15
```
 - Architecture: Intel x86_64.

**More details**
```
[SUB] Warning: Aborting stand-alone image build. Unsupported features in 3 methods
[SUB] Detailed message:
[SUB] Error: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: 
Invoke with MethodHandle argument could not be reduced to at most a single call or single field access. 
The method handle must be a compile time constant, e.g., be loaded from a `static final` field. 
Method that contains the method handle invocation: 
gnu.expr.CompiledProc.init(boolean, MethodHandle, Object, int)
```
https://gist.github.com/duncanmak/de4f4789f8ec9053766bcfd6346d9196

**Comment by mcraj017** [comment]
@duncanmak thanks for reporting the issue
we will look into it and update you

**Comment by mcraj017** [comment]
@duncanmak This exception is because method handle support for GraalVM Native Image is still in progress
please check the below feature request for your reference
https://github.com/oracle/graal/issues/2761

Once the support is added you can try again

**Comment by mcraj017** [comment]
Closing this issue for now, if you have any question, please reopen it
