### ISSUE TITLE
Native Image --initialize-at-run-time doesn't work with package names

### ISSUE THREAD

**Issue by brunocaballero** [oracle/graal#3025]
**Describe the issue**
The parameter "--initialize-at-run-time" doesn't work when using package names. It works when specifying single classes.

**Steps to reproduce the issue**
Consider the following code:

`package Main;
import A.A1;
import A.A2;
public class Hello {
  public static void main(String args[]) {
    A1 a1 = new A1();
    A2 a2 = new A2();
    System.out.println("Hello World " + a1.toString() + " "  + a2.toString());
  }
}
`
`package A;
public class A1 {
}
`
`package A;
public class A2 {
}
`

when generating a native image using the following command:

OPTS="-H:ConfigurationFileDirectories=META-INF/native-image \
    --initialize-at-run-time=A \
    --native-image-info \
    --verbose \
    -H:Name=test \
    -H:+PrintClassInitialization \
    --no-server"
    
graalvm-ce-java11-20.3.0/bin/native-image \
    $OPTS \
    -cp bin \
    Main.Hello

The classes A.A1 and A.A2 are in the file reports/build_time_classes. It is expected to be included in the file reports/run_time_classes
**Describe GraalVM and your environment:**
 - graalvm-ce-java11-20.3.0
 - OS: Linux
 - Architecture: AMD64

**More details**
Consider adding the `--native-image-info` and  `--verbose` flags when building your native image and paste output below.

Add any other information about the problem here. Especially important are stack traces or log output. Feel free to link to gists or to screenshots if necessary.
```
./native-image.sh 
Executing [
/home/bca/proj/graalvm/graalvm-ce-java11-20.3.0/bin/java \
-XX:+UseParallelGC \
-XX:+UnlockExperimentalVMOptions \
-XX:+EnableJVMCI \
-Dtruffle.TrustAllTruffleRuntimeProviders=true \
-Dtruffle.TruffleRuntime=com.oracle.truffle.api.impl.DefaultTruffleRuntime \
-Dgraalvm.ForcePolyglotInvalid=true \
-Dgraalvm.locatorDisabled=true \
-Dsubstratevm.IgnoreGraalVersionCheck=true \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.aarch64=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.amd64=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.code.site=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.code.stack=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.code=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.common=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.hotspot.aarch64=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.hotspot.amd64=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.hotspot.sparc=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.hotspot=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.meta=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.runtime=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.services=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.sparc=ALL-UNNAMED \
--add-exports=org.graalvm.truffle/com.oracle.truffle.api=ALL-UNNAMED \
--add-opens=jdk.internal.vm.compiler/org.graalvm.compiler.debug=ALL-UNNAMED \
--add-opens=jdk.internal.vm.compiler/org.graalvm.compiler.nodes=ALL-UNNAMED \
--add-opens=jdk.unsupported/sun.reflect=ALL-UNNAMED \
--add-opens=java.base/jdk.internal.module=ALL-UNNAMED \
--add-opens=java.base/jdk.internal.ref=ALL-UNNAMED \
--add-opens=java.base/jdk.internal.reflect=ALL-UNNAMED \
--add-opens=java.base/java.io=ALL-UNNAMED \
--add-opens=java.base/java.lang=ALL-UNNAMED \
--add-opens=java.base/java.lang.reflect=ALL-UNNAMED \
--add-opens=java.base/java.lang.invoke=ALL-UNNAMED \
--add-opens=java.base/java.lang.ref=ALL-UNNAMED \
--add-opens=java.base/java.net=ALL-UNNAMED \
--add-opens=java.base/java.nio=ALL-UNNAMED \
--add-opens=java.base/java.nio.file=ALL-UNNAMED \
--add-opens=java.base/java.security=ALL-UNNAMED \
--add-opens=java.base/javax.crypto=ALL-UNNAMED \
--add-opens=java.base/java.util=ALL-UNNAMED \
--add-opens=java.base/java.util.concurrent.atomic=ALL-UNNAMED \
--add-opens=java.base/sun.security.x509=ALL-UNNAMED \
--add-opens=java.base/jdk.internal.logger=ALL-UNNAMED \
--add-opens=java.desktop/sun.java2d.cmm.profiles=ALL-UNNAMED \
--add-opens=org.graalvm.sdk/org.graalvm.nativeimage.impl=ALL-UNNAMED \
--add-opens=org.graalvm.sdk/org.graalvm.polyglot=ALL-UNNAMED \
--add-opens=org.graalvm.truffle/com.oracle.truffle.polyglot=ALL-UNNAMED \
--add-opens=org.graalvm.truffle/com.oracle.truffle.api.impl=ALL-UNNAMED \
-XX:+UseJVMCINativeLibrary \
-Xss10m \
-Xms1g \
-Xmx13012739680 \
-Duser.country=US \
-Duser.language=en \
-Djava.awt.headless=true \
-Dorg.graalvm.version=20.3.0 \
-Dorg.graalvm.config= \
-Dcom.oracle.graalvm.isaot=true \
-Djava.system.class.loader=com.oracle.svm.hosted.NativeImageSystemClassLoader \
-Xshare:off \
--module-path \
/home/bca/proj/graalvm/graalvm-ce-java11-20.3.0/lib/truffle/truffle-api.jar \
-Djdk.internal.lambda.disableEagerInitialization=true \
-Djdk.internal.lambda.eagerlyInitialize=false \
-Djava.lang.invoke.InnerClassLambdaMetafactory.initializeLambdas=false \
-javaagent:/home/bca/proj/graalvm/graalvm-ce-java11-20.3.0/lib/svm/builder/svm.jar \
-cp \
/home/bca/proj/graalvm/graalvm-ce-java11-20.3.0/lib/svm/builder/javacpp-shadowed.jar:/home/bca/proj/graalvm/graalvm-ce-java11-20.3.0/lib/svm/builder/objectfile.jar:/home/bca/proj/graalvm/graalvm-ce-java11-20.3.0/lib/svm/builder/pointsto.jar:/home/bca/proj/graalvm/graalvm-ce-java11-20.3.0/lib/svm/builder/llvm-platform-specific-shadowed.jar:/home/bca/proj/graalvm/graalvm-ce-java11-20.3.0/lib/svm/builder/llvm-wrapper-shadowed.jar:/home/bca/proj/graalvm/graalvm-ce-java11-20.3.0/lib/svm/builder/svm-llvm.jar:/home/bca/proj/graalvm/graalvm-ce-java11-20.3.0/lib/svm/builder/svm.jar \
'com.oracle.svm.hosted.NativeImageGeneratorRunner$JDK9Plus' \
-watchpid \
260014 \
-imagecp \
/home/bca/proj/graalvm/graalvm-ce-java11-20.3.0/lib/svm/library-support.jar:/home/bca/proj/ctp-demo/workspace/Test/bin \
-H:Path=/home/bca/proj/ctp-demo/workspace/Test \
-H:ConfigurationFileDirectories=META-INF/native-image \
-H:ClassInitialization=A:run_time \
-H:+DumpTargetInfo \
-H:Name=test \
-H:+PrintClassInitialization \
-H:CLibraryPath=/home/bca/proj/graalvm/graalvm-ce-java11-20.3.0/lib/svm/clibraries/linux-amd64 \
-H:Class=Main.Hello \

]
[test:260033]    classlist:   1,231.94 ms,  0.96 GB
[test:260033]        (cap):     686.24 ms,  0.96 GB
[test:260033]        setup:   2,100.33 ms,  0.96 GB
# Building image for target platform: org.graalvm.nativeimage.Platform$LINUX_AMD64
# Using native toolchain:
#   Name: GNU project C and C++ compiler (gcc)
#   Vendor: linux
#   Version: 10.2.0
#   Target architecture: x86_64
#   Path: /usr/bin/gcc
# Using CLibrary: com.oracle.svm.core.posix.linux.libc.GLibC
Printing initializer configuration to /home/bca/proj/ctp-demo/workspace/Test/reports/initializer_configuration_20201125_142511.txt
Printing initializer dependencies to /home/bca/proj/ctp-demo/workspace/Test/reports/initializer_dependencies_20201125_142523.dot
Printing 0 classes that are considered as safe for build-time initialization to /home/bca/proj/ctp-demo/workspace/Test/reports/safe_classes_20201125_142523.txt
Printing 2567 classes of type BUILD_TIME to /home/bca/proj/ctp-demo/workspace/Test/reports/build_time_classes_20201125_142523.txt
Printing 62 classes of type RERUN to /home/bca/proj/ctp-demo/workspace/Test/reports/rerun_classes_20201125_142523.txt
Printing 7 classes of type RUN_TIME to /home/bca/proj/ctp-demo/workspace/Test/reports/run_time_classes_20201125_142523.txt
[test:260033]     (clinit):     222.26 ms,  1.21 GB
# Static libraries:
#   ../../../graalvm/graalvm-ce-java11-20.3.0/lib/svm/clibraries/linux-amd64/liblibchelper.a
#   ../../../graalvm/graalvm-ce-java11-20.3.0/lib/static/linux-amd64/glibc/libnet.a
#   ../../../graalvm/graalvm-ce-java11-20.3.0/lib/svm/clibraries/linux-amd64/libffi.a
#   ../../../graalvm/graalvm-ce-java11-20.3.0/lib/static/linux-amd64/glibc/libnio.a
#   ../../../graalvm/graalvm-ce-java11-20.3.0/lib/static/linux-amd64/glibc/libjava.a
#   ../../../graalvm/graalvm-ce-java11-20.3.0/lib/static/linux-amd64/glibc/libfdlibm.a
#   ../../../graalvm/graalvm-ce-java11-20.3.0/lib/static/linux-amd64/glibc/libzip.a
#   ../../../graalvm/graalvm-ce-java11-20.3.0/lib/svm/clibraries/linux-amd64/libjvm.a
# Other libraries: pthread,dl,z,rt
[test:260033]   (typeflow):   6,377.80 ms,  1.21 GB
[test:260033]    (objects):   4,921.72 ms,  1.21 GB
[test:260033]   (features):     273.13 ms,  1.21 GB
[test:260033]     analysis:  12,064.89 ms,  1.21 GB
[test:260033]     universe:     398.37 ms,  1.21 GB
[test:260033]      (parse):   1,827.42 ms,  1.71 GB
[test:260033]     (inline):   1,373.85 ms,  1.71 GB
[test:260033]    (compile):   8,428.25 ms,  2.34 GB
[test:260033]      compile:  12,184.58 ms,  2.34 GB
[test:260033]        image:   1,072.02 ms,  2.34 GB
[test:260033]        write:     156.41 ms,  2.34 GB
[test:260033]      [total]:  29,406.96 ms,  2.34 GB
```

**Comment by mcraj017** [comment]
@brunocaballero Thanks for reporting the issue
We will look into it and update you

**Comment by vjovanov** [comment]
Because they are proven to be safe to initialize. If you want to prevent such classes, you will have to list them explicitly.

**Comment by brunocaballero** [comment]
Ok, make sense. Perhaps the documentation in https://github.com/oracle/graal/blob/master/substratevm/ClassInitialization.md needs a warning or something, for me it was not clear that the automatic initialization of safe classes prevails over the option ---initialize-at-runtime for packages.

**Comment by vjovanov** [comment]
Yes, this decision was added later and not documented. We also need to improve printing to show the reason why a class was initialized at build-time.

**Comment by brodin** [comment]
@vjovanov is there a practical reason to `initialize-at-run-time` not accepting package names or some kind of regex? :) Trying to build something using netty, logback and slf4j resluts in enormous amounts of packages that needs to be manually found and specified.

**Comment by vjovanov** [comment]
It is accepting package prefixes. I would avoid regexes as debugging this way is already a difficult task--adding another layer of complexity

**Comment by brodin** [comment]
> It is accepting package prefixes. I would avoid regexes as debugging this way is already a difficult task--adding another layer of complexity

So for example, 

```
      "--initialize-at-run-time=ch.qos.logback.classic.Level",
      "--initialize-at-run-time=ch.qos.logback.classic.Logger",
      "--initialize-at-run-time=ch.qos.logback.classic.LoggerContext",
      "--initialize-at-run-time=ch.qos.logback.classic.PatternLayout",
      "--initialize-at-run-time=ch.qos.logback.core.CoreConstants",
      "--initialize-at-run-time=ch.qos.logback.core.spi.AppenderAttachableImpl",
      "--initialize-at-run-time=ch.qos.logback.core.status.InfoStatus",
      "--initialize-at-run-time=ch.qos.logback.core.status.StatusBase",
```

Should be replace by... `"--initialize-at-run-time=ch.qos.logback"`?

**Comment by vjovanov** [comment]
Yes, `"--initialize-at-run-time=ch.qos.logback"` should work as described [here](https://github.com/oracle/graal/blob/master/docs/reference-manual/native-image/ClassInitialization.md#explicitly-specifying-class-initialization).

**Comment by faermanj** [comment]
I changed from class names to package names and started getting several errors like this:
`Classes that should be initialized at run time got initialized during image building`

Should i have enabled anything else?

**Comment by mageddo** [comment]
> Because they are proven to be safe to initialize. If you want to prevent such classes, you will have to list them explicitly: `--initialize-at-run-time=A.A1`.

@vjovanov 

So, if I add `--initialize-at-run-time=A` but the image was initialized at build time because "they are proven to be safe to initialize" then my explicit requirement for the entire package to not initialize at build time is not being respected! So I don't have any other option instead of explicitly add  `--initialize-at-run-time` for every class, that's really boring.

**Comment by vjovanov** [comment]
Yes, but if they are proven to be safe there is no reason not to initialize them. What is the problem with the class being initialized at build time if they are safe?

**Comment by mageddo** [comment]
Yep, I think you're right, I'm with a issue related to this but I realized that it's not the root cause apparently

**Comment by mig23ang** [comment]
Hello, good morning. I have the same issue when launching a Quarkus app and generating the native image. @vjovanov , did you find a solution to the problem? The one in charge of creating the image in my pom is the profile:

xml
Copy code
<profiles>
    <profile>
        <id>native</id>
        <activation>
            <property>
                <name>native</name>
            </property>
        </activation>
        <properties>
            <skipITs>false</skipITs>
            <quarkus.package.type>native</quarkus.package.type>
            <args>--initialize-at-build-time=io.netty</args>
            <args>
                --initialize-at-run-time=io.netty.handler.codec.http.HttpObjectEncoder,io.netty.handler.codec.http.websocketx.WebSocket00FrameEncoder,io.netty.handler.codec.http.websocketx.extensions.compression.DeflateDecoder
            </args>
        </properties>
    </profile>
</profiles>
However, it doesn't take this when launching it in Azure DevOps. Any solution?

**Comment by mig23ang** [comment]
> The `initalize-at-run-time` and `build-time` can never work properly with package names due to the complexity of the whole problem.
> 
> We will likely, deprecate this behavior in the future so it would be better to specify individual classes.
I have also passed the classes individually but it throws up a new error

Before you add the classes that error
Error: Classes that should be initialized at run time got initialized during image building:
 io.netty.channel.unix.FileDescriptor the class was requested to be initialized at run time (from feature io.quarkus.runner.Feature.beforeAnalysis with 'FileDescriptor.class'). To see why io.netty.channel.unix.FileDescriptor got initialized use --trace-class-initialization=io.netty.channel.unix.FileDescriptor
io.netty.util.AbstractReferenceCounted the class was requested to be initialized at run time (from 'META-INF/native-image/io.netty/netty-common/native-image.properties' in 'file:///project/lib/io.netty.netty-common-4.1.100.Final.jar' with 'io.netty.util.AbstractReferenceCounted' and from 'META-INF/native-image/com.azure/azure-core-http-netty/native-image.properties' in 'file:///project/lib/com.azure.azure-core-http-netty-1.13.1.jar' with 'io.netty.util.AbstractReferenceCounted'). To see why io.netty.util.AbstractReferenceCounted got initialized use --trace-class-initialization=io.netty.util.AbstractReferenceCounted

After Adding the Classes

Fatal error: com.oracle.graal.pointsto.util.AnalysisError$ParsingError: Error encountered while parsing com.nimbusds.oauth2.sdk.auth.JWTAuthentication.<init>(com.nimbusds.oauth2.sdk.auth.ClientAuthenticationMethod, com.nimbusds.jwt.SignedJWT) 
Parsing context:
   at com.nimbusds.oauth2.sdk.auth.JWTAuthentication.<init>(JWTAuthentication.java:131)
   at com.nimbusds.oauth2.sdk.auth.PrivateKeyJWT.<init>(PrivateKeyJWT.java:249)
   at com.nimbusds.oauth2.sdk.auth.PrivateKeyJWT.parse(PrivateKeyJWT.java:284)
   at com.microsoft.aad.msal4j.ConfidentialClientApplication.createClientAuthFromClientAssertion(ConfidentialClientApplication.java:97)
   at com.microsoft.aad.msal4j.ConfidentialClientApplication.initClientAuthentication(ConfidentialClientApplication.java:68)
   at com.microsoft.aad.msal4j.ConfidentialClientApplication.<init>(ConfidentialClientApplication.java:56)
   at com.microsoft.aad.msal4j.ConfidentialClientApplication.<init>(ConfidentialClientApplication.java:32)
helpme please

**Comment by vjovanov** [comment]
I would first use GraalVM 21 and use the option `--strict-image-heap`. We did an overhaul of the class initializtion.
