### ISSUE TITLE
[vscode] "Cannot read property 'JAVA_HOME' of undefined"

### ISSUE THREAD

**Issue by fniephaus** [oracle/graal#3040]
**Describe GraalVM and your environment :**
 - GraalVM version or commit id if built from source: **20.3**
 - CE or EE: **CE/EE**
 - JDK version: **JDK11**
 - OS and OS Version: **macOS Catalina**
 - Architecture: **amd64**
- VS Code extension: **0.5.0**

### Description

When I click on the "Home" icon of a GraalVM installation, the following error is raised:

> Error running command extension.graalvm.selectGraalVMHome: Cannot read property 'JAVA_HOME' of undefined. This is likely caused by the extension that contributes extension.graalvm.selectGraalVMHome.

<img width="1198" alt="image" src="https://user-images.githubusercontent.com/2368856/100886371-09e9b180-34b4-11eb-8d9f-8146011198f1.png">

/cc @eschulte

**Comment by MartinBalin** [comment]
This could also happen when RH Java ext is uninstalled and it was previously set. Is it happening in 0.5.3?

**Comment by fniephaus** [comment]
Seems to work fine now, thanks!

**Comment by RainerXE** [comment]
FYI - as I just found out, this can also be a problem with "sdkman". Check inf Netbeans Lnaguage Server comes up....
