### ISSUE TITLE
[vscode] Behavior of languageServer.inProcessServer option is unclear

### ISSUE THREAD

**Issue by fniephaus** [oracle/graal#3041]
I’m not sure I understand the [`languageServer.inProcessServer` option](https://github.com/oracle/graal/tree/41f21fde7086a507c4e6100fd89cb560bb496789/vscode/graalvm#extension-settings). The description says:
> Start GraalVM’s Language Server Protocol within processes being run or debugged.

And it’s set to `true` by default.

According to the code, it looks like this will spawn an LSP server whenever I “launch” something through the extension. But why would that be the default behavior? I thought I need an LSP when writing code, not when debugging or running an application? The latter behavior, I get when I turn off the `languageServer.inProcessServer` option. At the very least, the description should be more specific about the behavior. It doesn’t say what happens when it’s turned off.

**Comment by MartinBalin** [comment]
It is default  behavior to run LSP during any execution from VSCode as we want to gather more information about types as being executed during runtime from GraalVM. But after some experience with this we are inclined towards setting this FALSE by default for next version.

**Comment by fniephaus** [comment]
I think it might make sense to split the option into two. `languageServer.inProcessServer` could become:

- `languageServer.launchServerWithProcesses`, which is what `languageServer.inProcessServer` is expected to do at the moment, essentially just passing in `--lsp` whenever a process is launched,
- and `languageServer.runServerInBackground`, which is what `languageServer.inProcessServer` does right now when it's set to `false`: running a LSP server in background when launching VS Code.

I'd like `languageServer.launchProcessesWithServer` to be set to `true` by default, but I'm not sure it would make sense to have both options set to `true` at the same time.

If they are mutually exclusive, the extension could either validate that and notify the user...or it may indeed be reasonable to keep them as one option (e.g. `languageServer.launchServerWithProcesses`: *Enable this option to start an LSP server with processes that are being run or debugged. Note that this will disable the LSP server in the background.* Default is `false`.)

**Comment by MartinBalin** [comment]
Should be fixed in 21.0 - 0.5.3 release.

**Comment by fniephaus** [comment]
Thanks! Seems to be fixed in https://github.com/graalvm/vscode-extensions/commit/ead143295d2f12788cd23428e75a7b61fe18eefa.
