### ISSUE TITLE
native-image hangs in Linux but works in macOS and Windows

### ISSUE THREAD

**Issue by robby-phd** [oracle/graal#3042]
**Describe the issue**
For a [jar file](http://pub.santoslab.org/sireum.jar) from my project, native-image hangs in Linux but compiles successfully in macOS (and Windows).

**Steps to reproduce the issue**
```bash
curl -JLo sireum.jar http://pub.santoslab.org/sireum.jar
native-image --native-image-info --verbose --initialize-at-build-time --no-fallback --report-unsupported-elements-at-runtime -H:+ReportExceptionStackTraces -jar sireum.jar sireum
```

**Describe GraalVM and your environment:**
 - GraalVM version: 20.3.0, 21.0.0-dev
 - JDK major version: 15
 - OS: macOS Catalina and Ubuntu 20.04 (and Windows 10)
 - Architecture: amd64

**More details**

It seems the issue is triggered from this [line](https://github.com/sireum/runtime/blob/e78941a001d0b54d48bf9f894f4ab4ef57e1fad5/library/jvm/src/main/scala/org/sireum/Os_Ext.scala#L766), which eventually calls `Thread.join()`/`Object.wait()`.

Logs:

* macOS, Graal 20.3.0: [graal-mac.log](https://github.com/oracle/graal/files/5637448/graal-mac.log)
* Linux, Graal 20.3.0: [graal-linux.log](https://github.com/oracle/graal/files/5637524/graal-linux.log)
* Linux, Graal 21.0.0-dev: [graal-dev-linux.log](https://github.com/oracle/graal/files/5637529/graal-dev-linux.log)

**Comment by mcraj017** [comment]
@robby-phd Thanks for reporting the issue
we will check it out and let you know our thoughts

**Comment by christianwimmer** [comment]
No idea what the class initializer
```
org.sireum.Os_Ext$.<clinit>
```
is doing. But definitely something that should not run at image build time. Why do you have `--initialize-at-build-time` on the native image command line? Unless you have manually inspected all classes to be safe for initialization at image build time, this is not an option to use.

**Comment by robby-phd** [comment]
I thought I did, but I changed a field initialization that used to be simple and forgot to make the modified unsafe-at-build-time initialization lazy.
It is interesting that the problem only manifests in Linux. 
Anyway, I have [made the field lazy](https://github.com/sireum/runtime/commit/ce432861ee6603da91f09eeb2e8ddba136048a42) and confirmed that it workarounds the issue. Thanks.

**Comment by mcraj017** [comment]
as the issue has been resolved, closing the issue

**Comment by robby-phd** [comment]
It would be great if native-image behaves the same/similarly on the different platforms that it supports for the same input and options specified.

**Comment by christianwimmer** [comment]
> It would be great if native-image behaves the same/similarly on the different platforms that it supports for the same input and options specified.

But in that case the *application* is behaving differently on the different platforms.

**Comment by robby-phd** [comment]
Ah yes, you are right. Just curious, will there be a feature to abort native compilation with `--initialize-at-build-time` when an init hits an unsafe method (and perhaps output a nice error message with the relevant call chain)?
