### ISSUE TITLE
Unable to build Native Image when using GitLab4J

### ISSUE THREAD

**Issue by alexweide** [oracle/graal#3044]
**Description**
I am trying to build a program which depends on [GitLab4J](https://github.com/gitlab4j/gitlab4j-api) using GraalVM Native Image and the build fails all the time. I also tried to build it using the latest development version, but it also failed.

**Steps to reproduce the issue**
Please include both build steps as well as run steps
1. `git clone https://github.com/alexweide/reproducer`
2. `mvn clean package` or `mvn.bat clean package` on Windows

**GraalVM and environment:**
 - GraalVM version: CE 20.3.0 and CE 21.0.0-dev
 - JDK major version: 11
 - OS: Windows 10 1909 with Visual Studio Build Tools 2019
 - Architecture: AMD64

**Build log**
https://gist.github.com/alexweide/8e58ba2d1cbe80143c495327f224350c

**Comment by oubidar-Abderrahim** [comment]
From the logs, it seems an issue with MethodHandle, Support of MethodHandles is in progress and can be tracked in #2761
