### ISSUE TITLE
Runs a little slower clojure

### ISSUE THREAD

**Issue by Robson96** [oracle/graal#3045]
**Describe the issue**
When working with recursion the compile grail performs more

**Steps to reproduce the issue**
Please include both build steps as well as run steps
1. save this code in file .clj with name app.clj
```
(defn transacao-aleatoria []
  {:valor (* (rand-int 100001) 0.01M)
   :tipo (rand-nth ["despesa" "receita"])})

(def transacoes
  [{:valor 33.0M :tipo "despesa" :comentario "Almoço"
    :moeda "R$" :data "19/11/2016"}
   {:valor 2700.0M :tipo "receita" :comentario "Bico"
    :moeda "R$" :data "01/12/2016"}
   {:valor 29.0M :tipo "despesa" :comentario "Livro clojure"
    :moeda "R$" :data "03/12/2016"}])

(defn aleatorias
  ;;começando a sequencia criando a primeira transacao
  ([quantidade]
   (aleatorias quantidade 1 (list (transacao-aleatoria))))  ;; imcrementando a sequencia ate que a quantidade desejada seja atendida
  ([quantidade quantas-ja-foram transacoes]
    (if (= quantas-ja-foram quantidade)
      transacoes
      (recur quantidade
             (inc quantas-ja-foram)
             (cons (transacao-aleatoria)
                   transacoes)))))

(println (time (class (aleatorias 4))))
(println (time (class (aleatorias 900000))))

```
2. set env export JAVA_TOOL_OPTIONS="-XX:+UnlockExperimentalVMOptions -XX:+EnableJVMCI -XX:+UseJVMCICompiler -XX:+UseParallelGC"

3. $ time clojure app.clj 

 - JDK major version: **11**
 - OS: **Ubuntu 20.04**
 - Architecture: **Intel® Core™2 Duo CPU T7500 @ 2.20GHz × 2**

```
   real	0m22,415s
   user	0m26,157s
   sys	0m1,370s
```

**Comment by mcraj017** [comment]
@Robson96 Thanks for reporting the issue
We will check it out and update you

**Comment by mcraj017** [comment]
@Robson96 When I run it multiple times, I see no difference, in some runs GraalVM is better also
Please try your side also and let me know

**Comment by Robson96** [comment]
I had a problem with ubuntu, now I'm using opensuse, but on my machine it's still slower: /

robson@localhost:~/Documentos/github> time clojure app.clj
Picked up JAVA_TOOL_OPTIONS: -XX:+UnlockExperimentalVMOptions -XX:+EnableJVMCI -XX:+UseJVMCICompiler -XX:+UseParallelGC
"Elapsed time: 9.425947 msecs"
clojure.lang.Cons
"Elapsed time: 7871.466342 msecs"
clojure.lang.Cons

real	0m12,523s
user	0m20,721s
sys	0m0,948s
robson@localhost:~/Documentos/github> unset JAVA_TOOL_OPTIONS 
robson@localhost:~/Documentos/github> time clojure app.clj
"Elapsed time: 1.057626 msecs"
clojure.lang.Cons
"Elapsed time: 2273.875005 msecs"
clojure.lang.Cons

real	0m6,603s
user	0m9,681s
sys	0m0,811s

**Comment by mcraj017** [comment]
@Robson96 just to confirm, in both cases are you using graalvm java and just changing -XX:+UseJVMCICompiler, because to use hotspot you need to use -XX:-UseJVMCICompiler, otherwise it still graalvm only

**Comment by Robson96** [comment]
yes, I want to use the graal instead of the hotspot

**Comment by Robson96** [comment]
I made some changes and used the lazy-seq macro that returns a lazy list, with that the grail has the same format without using it, apparently the bottleneck is in using the recur "function".

robson@localhost:~/Documentos/github> clojure app.clj
Picked up JAVA_TOOL_OPTIONS: -XX:+UnlockExperimentalVMOptions -XX:+EnableJVMCI -XX:+UseJVMCICompiler -XX:+UseParallelGC
"Elapsed time: 0.750737 msecs"
clojure.lang.LazySeq
"Elapsed time: 0.107348 msecs"
clojure.lang.LazySeq

**Comment by mcraj017** [comment]
@Robson96 it seems the performance it better now

**Comment by mcraj017** [comment]
@Robson96 Closing this for now, if you have any other concern please reopen or create new issue
