### ISSUE TITLE
How can I use GraalVm agentlib in graalvm version 20.3.0

### ISSUE THREAD

**Issue by ahTy** [oracle/graal#3057]
**Describe GraalVM and your environment :**
 - GraalVM version or commit id if built from source: **[20.3.0]**
 - CE or EE: **[e.g.: CE]**
 - JDK version: **[JDK8]**
 - OS and OS Version: **[Ubuntu 16.04.6 LTS]**
 - Architecture: **[Intel(R) Core(TM) 64]**
 - The output of `java -Xinternalversion`:
```
 **PASTE OUTPUT HERE**
```
```
[hs_err_pid19138.log](https://github.com/oracle/graal/files/5676763/hs_err_pid19138.log)

    PASTE YOUR LOG/STACK TRACE HERE
```
</details>

How can I use GraalVm's reflection configuration assistant tool agentlib to assist in generating relevant configuration files in my spring cloud project (springcloud version 2020.0.0-SNAPSHOT, springboot version 2.4.0, graalvm version 20.3.0)

When i try to use
‘java -agentlib:native-image-agent=config-output-dir=./native-image/ -jar myproject.jar’
it break down and return me core error

I need to import my own configuration file in my spring cloud project and use agentlib to export the corresponding reflection configuration

**Comment by jramirez-isc** [comment]
Hi @ahTy 
Can you share the error log?

**Comment by oubidar-Abderrahim** [comment]
The command is `java -agentlib:native-image-agent=config-output-dir=native-image -jar myproject.jar` 
If you're still facing this issue, please try with the latest version 21.0.0 and if the issue still persist, share the complete error log with us.

**Comment by oubidar-Abderrahim** [comment]
I am closing this issue. If you still need assistance please re-open.
