### ISSUE TITLE
I can't use graalVM on jvdroid (JVDroid - java compiler for android)

### ISSUE THREAD

**Issue by SavagePy10** [oracle/graal#3062]
![Screenshot_2020-12-12-14-11-29-58](https://user-images.githubusercontent.com/75002427/101976810-f8f32a00-3c83-11eb-849a-2903cc985ff9.jpg)

**Comment by SavagePy10** [comment]
=(

**Comment by SavagePy10** [comment]
Nothing works

**Comment by mcraj017** [comment]
@SavagePy10 please provide the reproducer

**Comment by SavagePy10** [comment]
> @SavagePy10 please provide the reproducer

First i install graal on jvdroid in a normal way... (Setting PATH and JAVA_HOME). Then try commands. It didn't work

**Comment by SavagePy10** [comment]
Also, if u want to reproduce, u will need to know that changing PATH and JAVA_HOME on jvdroid is a bit different.

**Comment by SavagePy10** [comment]
https://www.google.com/amp/s/m.apkpure.com/jvdroid-ide-for-java/ru.iiec.jvdroid/amp

**Comment by SavagePy10** [comment]
Swipe from left to right. U will see `terminal`. Click it...

**Comment by SavagePy10** [comment]
Btw i think its app issue

**Comment by SavagePy10** [comment]
I think this issue is useless

**Comment by BryleHelll** [comment]
> @SavagePy10 please provide the reproducer

Oh. Its android security. Libs must be on /data/data/... Or /lib
