### ISSUE TITLE
Headless property is baked in, can no longer run heady

### ISSUE THREAD

**Issue by kristofdho** [oracle/graal#3064]
**Describe the issue**
The awt invocation plugin causes the headless property to be stored at build-time, which means you can no longer switch between headless and heady execution at runtime. Since on windows, `-Djava.awt.headless=true` is set by native-image itself, this breaks any heady application.

The plugin seems to be directed at unix environments, as that's also the only awt support that's already added, so it might make sense to only conditionally add the plugin if we're targetting unix.

Additionally I think it's not preferable to have to decide at build-time if the application will run headless or heady.

The invocation plugin this is about:
https://github.com/oracle/graal/blob/6fc5aaf330c09dc78bec4c662ede73c37364e17f/substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/snippets/SubstrateGraphBuilderPlugins.java#L1033-L1048

**Steps to reproduce the issue**
- run any natively compiled windows app with `-Djava.awt.headless=false` and it will still be headless

**Describe GraalVM and your environment:**
 - GraalVM version: **72439a3924dfe0391764a3f326dfb7da30cda8b4** (as good as up to date with master)
 - JDK major version: **11**
 - OS: **Windows 10**
 - Architecture: **x64**

**Comment by mcraj017** [comment]
@kristofdho please provide reproducer

**Comment by kristofdho** [comment]
file: BakedInHeadlessPoc.java
```java
import java.awt.GraphicsEnvironment;

class BakedInHeadlessPoc {
    public static void main(String[] args) throws Exception {
		System.out.println(GraphicsEnvironment.isHeadless());
	}
}
```

compile & build:
```bat
javac BakedInHeadlessPoc.java
native-image -H:Name=BakedInHeadlessPoc -H:Class=BakedInHeadlessPoc --verbose --no-fallback
```

run compiled binary:
```bat
> BakedInHeadlessPoc.exe
true

> BakedInHeadlessPoc.exe -Djava.awt.headless=true
true

> BakedInHeadlessPoc.exe -Djava.awt.headless=false
true
```


expected output:
```bat
> BakedInHeadlessPoc.exe
false

> BakedInHeadlessPoc.exe -Djava.awt.headless=true
true

> BakedInHeadlessPoc.exe -Djava.awt.headless=false
false
```

marking `GraphicsEnvironment` for run-time initialization doesn't work as the plugin appears to require it to be initialized at build-time.

suggested fix in #3068

**Comment by kristofdho** [comment]
Should this not be included in the 21.0 milestone as well? It is regression so it would make sense.
There is quite some stuff depending on this flag as well, like anything javafx, or awt functionality. I personally depend on both so this would render 21.0 unusable for me.

**Comment by kristofdho** [comment]
I would like to restate the importance of this regression for us. Could I have some context on why this is not making 21.0, and what a possible workaround would be?

**Comment by pejovica** [comment]
@kristofdho, I wouldn't necessarily call this a regression, because AWT is not yet supported on Windows (see #3084), but I also agree that this plugin should not be needed.

So until this is fixed, you can pass `-Djava.awt.headless=false` to `native-image` when building an image as a workaround, i.e.:
```cmd
> native-image -H:Name=BakedInHeadlessPoc -H:Class=BakedInHeadlessPoc --verbose --no-fallback -Djava.awt.headless=false
...

> BakedInHeadlessPoc
false

> BakedInHeadlessPoc -Djava.awt.headless=true
false

> BakedInHeadlessPoc -Djava.awt.headless=false
false
```

**Comment by zakkak** [comment]
Can someone please add the `platform-windows` label to this issue?

**Comment by mcraj017** [comment]
@zakkak done

**Comment by zakkak** [comment]
Thank you @mcraj017 !
