### ISSUE TITLE
Potential multiple reflection type processing and initialization

### ISSUE THREAD

**Issue by galderz** [oracle/graal#3069]
**Describe the issue**
ReflectionDataBuilder tracks processed classes during points-to analysis in a non-concurrent collection (HashSet), hence there's no guarantee that one thread's inserts are not seen in a timeline fashion by other threads, potentially leading to reflection classes being processed and initialized multiple times.

**Steps to reproduce the issue**
This was observed during the study of how reflection is handled.

**Describe GraalVM and your environment:**
GraalVM master

**Comment by mcraj017** [comment]
@galderz please provide the reproducer

**Comment by mcraj017** [comment]
Closing the issue as there is no response for the last month

**Comment by galderz** [comment]
@mcraj017 Do you really need a reproducer for this? Could you be more specific on what counter arguments you have to the description of the issue that makes you think you need a reproducer?

**Comment by gradinac** [comment]
Hey @galderz! Thanks for reporting the issue!

Looking at ReflectionDataBuilder, I assume you are referring to the following set: https://github.com/oracle/graal/blob/master/substratevm/src/com.oracle.svm.reflect/src/com/oracle/svm/reflect/hosted/ReflectionDataBuilder.java#L85 ?
If that's the case - there shouldn't be an issue: if we look at this set's usages, it's only used in: https://github.com/oracle/graal/blob/master/substratevm/src/com.oracle.svm.reflect/src/com/oracle/svm/reflect/hosted/ReflectionDataBuilder.java#L182
If we look at where that method's usages, we only find: https://github.com/oracle/graal/blob/master/substratevm/src/com.oracle.svm.reflect/src/com/oracle/svm/reflect/hosted/ReflectionDataBuilder.java#L174
The `DuringAnalysis` callback is called for each feature separately after an analysis iteration. Analysis continues only once all registered feature's `DuringAnalysis` callbacks have finished. This means that at most one thread is executing that callback at any given time. Therefore, we shouldn't have a concurrency problem.

**Comment by galderz** [comment]
Hmmm, that doesn't seem right to me. `NativeImageGenerator.run` instructs points to analysis to run in a multi-threaded way (see [here](https://github.com/oracle/graal/blob/master/substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/NativeImageGenerator.java#L469)). That in turn ends up calling `NativeImageGenerator.runPointsToAnalysis` which, for each feature, calls `duringAnalysis`. What guarantees do you offer to say that a single feature, e.g. `ReflectionDataBuilder`, will only be called by one thread at the time?

**Comment by gradinac** [comment]
Ah, `NativeImageGenerator` submits the image build itself to the executor - bear in mind that this is only one task.
This means that [doRun](https://github.com/oracle/graal/blob/master/substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/NativeImageGenerator.java#L479) is executed by a single thread from the executor.
As part of the image build, we call `NativeImageGenerator.runPointsToAnalysis`. While that method may run an analysis iteration in parallel, the forEachFeature step that triggers the duringAnalysis callback is single-threaded.
