### ISSUE TITLE
[sdk] The SDK launcher doesn't handle GetExecutableName returning null

### ISSUE THREAD

**Issue by chrisseaton** [oracle/graal#307]
`com.oracle.svm.core.posix.GetExecutableName` can return `null` if `realpath` fails. `realpath` can fail if `/proc` isn't mounted, which is sometimes the case in minimal environments like in a chroot. We've seen this happen for real.

The problem is that `org.graalvm.launcher.Launcher#getCurrentExecutablePath` does not handle `com.oracle.svm.core.posix.GetExecutableName` returning `null`, and you get an NPE.

It's probably reasonable to not work without `/proc`, but we should give a nice error message.

Reported by @liamwhite

**Comment by gilles-duboscq** [comment]
On Linux, if the `/proc` method does not work we should try `getauxval(AT_EXECFN)`

**Comment by chrisseaton** [comment]
I think in some other issue, that I can't find, we decided to just say that not having `/proc` mounted is unreasonable and is going to cause many other issues.
