### ISSUE TITLE
"os.name" property on Native Image on Android

### ISSUE THREAD

**Issue by rnayabed** [oracle/graal#3074]
`System.getProperty("os.name")` returns `linux` on android aarch64 app and on traditional linux desktop as well (Ubuntu 20.10). I am using [Gluon Client](https://github.com/gluonhq/substrate) to compile my javafx app into a native image for Android.

It should return `android` or something which is different from `linux` as it may cause confusions when using platform specific code.

Currently, I am just specifying on runtime and have to create separate compilations specifying the Platform.

**Comment by vjovanov** [comment]
This is an issue for @lazar-mitrovic.

**Comment by lazar-mitrovic** [comment]
`System.getProperty("os.name")` implementation [on Android itself](https://android.googlesource.com/platform/libcore/+/15d8280/luni/src/main/java/java/lang/System.java#321) returns "Linux" (as it is the `uname` value). Returning something else could potentially break compatibility, which (I believe) should be discussed at JDK project.

Better solution might be to add new client-facing system property which would contain platform name (for example `System.getProperty("graal.platform.name") == "android"`).

In the meantime you can specify your own `os.name` value using `-Dsvm.targetName=android` - or more specifically if you are using Gluon Substrate + client-maven-plugin it would look something like this
```xml
    <profiles>
        ...
        <profile>
            <id>android</id>
            <properties>
                <clientTarget>android</clientTarget>
                <additionalArgs>-Dsvm.targetName=android</additionalArgs>
            </properties>
        </profile>
    </profiles>
    ...
    <build>
        <plugins>
            <plugin>
                <groupId>com.gluonhq</groupId>
                <artifactId>client-maven-plugin</artifactId>
                <version>${client.version}</version>
                <configuration>
                    <target>${clientTarget}</target>
                    <nativeImageArgs>
                        <list>${additionalArgs}</list>
                        ....
                    </nativeImageArgs>
                    ...
                </configuration>
            </plugin>
        </plugins>
    </build>
```

**Comment by rnayabed** [comment]
Sounds good. Thanks for the reply :)

**Comment by rnayabed** [comment]
I tried setting `-Dsvm.targetName=android` but `os.name` still returns the same (`linux`).

**Comment by lazar-mitrovic** [comment]
Hmm, that really shouldn't happen:
https://github.com/oracle/graal/blob/4794b8ca7360958cc888536cae21af10a81c64a1/substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jdk/SystemPropertiesSupport.java#L125-L130
(code that initializes "linux" value is on line 129. 

Can you copy output of `--verbose` from your `native-image` invocation?

**Comment by rnayabed** [comment]
Sorry Im dumb, it works!
