### ISSUE TITLE
VSCode extension attempt to attach debugger fails with "Cannot find runtime 'node' within your GraalVM installation"

### ISSUE THREAD

**Issue by davidpcaldwell** [oracle/graal#3087]
When attempting to attach VSCode to a process launched with `--inspect` (or `--inspect-brk`), the debugger fails immediately, popping up a dialog with the message in the issue title.

I tried this with both `graalpython` and `js`.

In both cases, it was possible to connect Chrome DevTools to the given target using the URL each tool provided in its console output. I could launch the `node` tool from within the GraalVM distribution and it behaved as expected.

**Steps to reproduce the issue**

1. Install GraalVM CE 20.3.0 on macOS Big Sur
1. Configure it in VSCode and observe that it appears in the extension's UI
1. Add the appropriate debug target to `launch.json` (for GraalVM: Attach)
1. Start a process with `--inspect`
1. Attempt to attach the debugger by selecting and running the Graal VM Attach debug configuration
1. Observe the dialog above

**Environment**

 - GraalVM version: **20.3.0 CE**
 - VSCode extension version: **0.5.0**
 - Visual Studio Code version: **1.52.1**
 - JDK major version: **8**
 - OS: **macOS Big Sur 11.1**
 - Architecture: **AMD64**

**Comment by oubidar-Abderrahim** [comment]
Could you please provide more detailed reproducing steps? What is the content of your `launch.json`? what is the full command used to debug? were you able to test on another macOS distribution?
Any more context you can provide will be much appreciated.

**Comment by davidpcaldwell** [comment]
Yes. I uninstalled the extension because it wasn't fitting into my current workflow. I'll re-install it and try to come up with a more comprehensive reproduction case.

I'm porting a pretty complicated Rhino/Nashorn setup, so it might be hard for me to reproduce the exact command I'm runnjing to launch the process being inspected. But I'll try to boil it down as small as I can, or see whether I can reproduce it with a toy example. I'll do all of this when I have a few minutes.

**Comment by oubidar-Abderrahim** [comment]
@davidpcaldwell Could you please confirm if this is still an issue?

Could you please install the latest version of the GraalVM extension and from within the extension click "Add Existing GraalVM" and point to your GraalVM installation? please let us know if you still face an issue with it.

Thank you

**Comment by davidpcaldwell** [comment]
Thanks, I'll have a look again today (maybe tomorrow) and see what the state of this is.

**Comment by davidpcaldwell** [comment]
Going to try to get back to this today! Thanks for sticking with me.

**Comment by oubidar-Abderrahim** [comment]
Hi, Any updates if this is still an issue?

**Comment by davidpcaldwell** [comment]
@oubidar-Abderrahim I re-tested with 20.3.0 and the extension and was unable to reproduce this problem now. I am having other problems, but I'll look into those and file new reports if I can narrow them down. Thanks!
