### ISSUE TITLE
Include directory from resources while compiling native Image via gluon client maven plugin

### ISSUE THREAD

**Issue by rnayabed** [oracle/graal#3092]
I wrote a custom alert/combobox implementation for my project. Could not
use Gluon Mobile because its integrated tightly with our custom Theme
API. It works now!!

However, I have a small issue. My project root currently looks like this

root

     - src

     - resources

         - default/

             - config.xml

             - Themes/

             - Profiles/

             - Icons/

         - style.css

         - Roboto.ttf

When the config.xml file isnt found on local disk, the program just
copies all the contents of the `default` directory to the disk.

I am using gluon client and their maven plugin
However, when i try to get `Main.class.getResource("default/").toURI()`
it returns a nullpointer. i added `-H:IncludeResources='*/*.*'` to
`<nativeImageArgs>` but it doesnt work. I also tried adding that under
`<resourcesList>` but that too did not work.

Any leads on how I can embed all the directories/files/ everything from
the resources folder onto the native image

GraalVM Version : 20.2.0
Platform : x64 Linux

**Comment by kkriske** [comment]
The pattern passed to `IncludeResources` is a regex, see the docs: https://github.com/oracle/graal/blob/master/substratevm/Resources.md

So the "regex" `*/*.*` simply does not what you think it does. To include everything in the default dir, adding `default/.*` should normally do the trick.

As for the `resourceList` option of the gluon maven plugin, it writes the pattern to a resources-config.json file, you have exactly the same problem there.

**Comment by rnayabed** [comment]
@kkriske i tried `-H:IncludeResources='Default/.*'` but it did not work as well :(

The line `new File(Main.class.getResource("Default/").toURI())` is causing `NullPointerException`

**Comment by kkriske** [comment]
What I think that's happening, without having the stacktrace: You are looking up a directory, which is not a resource, so `getResource` returns null. Looking up a file in the directory should work.

Walking through resources as a directory structure is not (yet) supported, as mentioned here: https://github.com/oracle/graal/issues/2762 under **Improve support for resource registration**

**Comment by rnayabed** [comment]
@kkriske yes, looking up a file inside the resources folder work, but looking up directory doesnt. Ill try something like this `new File(Main.class.getResource("Default/config.xml").toURI()).getAbsoluteFile().getParentFile()`

**Comment by rnayabed** [comment]
@kkriske so now after pointing to the file and then going up one direcotry, it throws a `java.lang.IllegalArgumentException: URI is not hierarchical` :/

**Comment by rnayabed** [comment]
I think i need to zip the folder into a zip, and then unzip it

**Comment by rnayabed** [comment]
@kkriske I think I discovered an issue

`class.getResourceAsStream("filename")` works. But `class.getResource("filename")` returns `resource:<file location>`, which doesn't work if I want to read a file, copy it somewhere.

Closing it because in the end, what the workaround was to zip the directory, and then extract it to a location.
