### ISSUE TITLE
Got "java.util.zip.ZipException: zip END header not found" error when running image

### ISSUE THREAD

**Issue by jameshugit** [oracle/graal#3093]
Environment:
java -version
openjdk version "11.0.9" 2020-10-20
OpenJDK Runtime Environment GraalVM CE 20.3.0 (build 11.0.9+10-jvmci-20.3-b06)
OpenJDK 64-Bit Server VM GraalVM CE 20.3.0 (build 11.0.9+10-jvmci-20.3-b06, mixed mode, sharing)

native-image --version
GraalVM Version 20.3.0 (Java Version 11.0.9+10-jvmci-20.3-b06)

Steps:
1) /usr/lib/jvm/graalvm-ce-java11-20.3.0/lib/svm/bin/native-image --no-fallback -jar /opt/springbootapp/cams.jar
2) ./cams

Comments:
without "--no-fallback" option for native-image command, the app is runuable, but native-image gave the warning about "--no-fallback"

**Comment by oubidar-Abderrahim** [comment]
1. What is cams.jar? is it your application? in this case please provide the repository containing the source code and the steps to build and run it.
2. What is the complete stack trace of the exception?
3. Did you try with the latest snapshot of 21.0.0?
4. Did you try generating config files for your application using the [native-image-agent](https://www.graalvm.org/reference-manual/native-image/BuildConfiguration/#assisted-configuration-of-native-image-builds)?

**Comment by dzou** [comment]
Hi there, we seem to have the same issue reported over here: https://github.com/GoogleCloudPlatform/google-cloud-graalvm-support/issues/58

Here is a reproducible sample that our user provided: https://github.com/lpellegr/micronaut-graalvm-gcp
Instructions -- Clone the repo, then run `gradle nativeImage -i`

You will see the error:

```
Error: Invalid or corrupt jarfile /home/dzou/.gradle/caches/modules-2/files-2.1/org.graalvm.nativeimage/svm-hosted-native-linux-amd64/20.3.0/1eb9f7ea955f02c49cc5f3fa722f388cb15e8dd5/svm-hosted-native-linux-amd64-20.3.0.tar.gz
Caused by: java.util.zip.ZipException: zip END header not found
:nativeImage (Thread[Execution worker for ':',5,main]) completed. Took 0.152 secs.
```

The app is a basic application using Micronaut and GraalVM compilation with Gradle. This is targetting version 20.3.0 of GraalVM, and seems to be a problem if the user's application somehow depends on the `org.graalvm.nativeimage:svm:20.3.0` artifact.

I found some additional context; looks like people encountered this similar issue in other tools as well: https://youtrack.jetbrains.com/issue/KT-41313

Not quite sure I understand the solution; however this appears to be related to the following dependencies pulled in by `org.graalvm.nativeimage:svm`:

```
<dependency>
      <groupId>org.graalvm.nativeimage</groupId>
      <artifactId>svm-hosted-native-linux-amd64</artifactId>
      <version>20.2.0</version>
      <type>tar.gz</type>
    </dependency>
    <dependency>
      <groupId>org.graalvm.nativeimage</groupId>
      <artifactId>svm-hosted-native-darwin-amd64</artifactId>
      <version>20.2.0</version>
      <type>tar.gz</type>
    </dependency>
    <dependency>
      <groupId>org.graalvm.nativeimage</groupId>
      <artifactId>svm-hosted-native-windows-amd64</artifactId>
      <version>20.2.0</version>
      <type>tar.gz</type>
    </dependency>
```

**Comment by dzou** [comment]
We eventually figured out the problem. The solution is to mark the `org.graalvm.nativeimage:svm` dependency as `provided` scope in your project. Usually it's some dependency which imports this library, so you'll have to dig a bit to find where it's 
imported. It seems that the graalvm compiler provides the dependency for the project during compilation.

From what it looks like, if the library is added as a standard dependency in the project, the GraalVM compiler will interpret it as JAR sources that need to be considered for the native image and this seems to trigger the issue.

**Comment by oubidar-Abderrahim** [comment]
Tracked internally on GR-28692

**Comment by olpaw** [comment]
> We eventually figured out the problem. The solution is to mark the `org.graalvm.nativeimage:svm` dependency as `provided` scope in your project.

This is the correct answer. Note that this is also explained in (see _About `<scope>provided</scope>`_ in https://medium.com/graalvm/simplifying-native-image-generation-with-maven-plugin-and-embeddable-configuration-d5b283b92f57)

**Comment by MarioMO98** [comment]
Hi,
I'm still getting the same error trying to run the native-image .exe generated file of one of the spring graalvm native samples after doing the proposal solution, **in Windows environment**: (https://github.com/spring-projects-experimental/spring-native/tree/master/samples/cloud-function-netty).

I'm using the same Graalvm version too: 
openjdk version "11.0.9" 2020-10-20
OpenJDK Runtime Environment GraalVM CE 20.3.0 (build 11.0.9+10-jvmci-20.3-b06)
OpenJDK 64-Bit Server VM GraalVM CE 20.3.0 (build 11.0.9+10-jvmci-20.3-b06, mixed mode, sharing)
**OS: Windows 10**

**Steps to reproduce the issue**

1. Open x64 Native Tools Command Prompt for VS 2019
2. cd to the spring sample folder (spring-native/spring-native-samples/cloud-function-netty)
3. mvn clean install
4. native-image -jar cloud-function-netty-0.0.1-SNAPSHOT.jar --no-fallback --verbose

Looking to the spring-native [pom.xml](https://github.com/spring-projects-experimental/spring-native/blob/master/spring-native/pom.xml), all dependencies are marked as provided scope.
I've added the org.graalvm.nativeimage:svm dependency as provided scope in my project too, but I always get the "zip END header not found error".

I have seen that this will be probably a graalvm Windows error, but I would like to know if someone could solve this error in Windows environment, if it's possible.

Thank you in advance.
