### ISSUE TITLE
os.version reports wrong number on Windows 10

### ISSUE THREAD

**Issue by denara** [oracle/graal#3094]
The system property os.version reports "6.2" after building the native image with GraalVM 20.3. 

**Steps to reproduce the issue**
1. Create a simple app to print the system properties
2. Start the app the usual way with GraalVM 20.3
3. "os.version" -> 10.0
4. "os.name "-> Windows 10
5. Build the native image (I am using the gluon client-maven-plugin 0.1.35) *
6. Start the created exe file
7. "os.version" -> 6.2
8. "os.name "-> Windows 10

*Buildscript:
`set JAVA_HOME=%GRAALVM_HOME%`
`call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars64.bat"`
`mvn clean client:build`

**Describe GraalVM and your environment:**
 - GraalVM version 20.3.0
 - JDK 11.0.9
 - OS: Windows 10 20H2
 - Architecture: amd64
 - IntelliJ 2020.3 Terminal - to build and run the final app
 - com.gluonhq:client-maven-plugin:0.1.35

**More details**
[Di. Dez. 29 12:35:29 MEZ 2020][FINE] PB Command for compile: C:\Java\graalvm-ce-java11-20.3.0\bin\native-image.cmd "-Djdk.internal.lambda.eagerlyInitialize=false" --no-server -H:+ExitAfterRelocatableImageWrite -H:+SharedLibrary -H:+AddAllCharsets -H:+ReportExcepti
onStackTraces -H:-DeadlockWatchdogExitOnTimeout "-H:DeadlockWatchdogInterval=0" -H:+RemoveSaturatedTypeFlows "--features=org.graalvm.home.HomeFinderFeature" "-H:TempDirectory=C:\...\target\client\x86_64
-windows\gvm\tmp" "-H:EnableURLProtocols=http,https" -H:+PrintAnalysisCallTree "-H:Log=registerResource:" "-H:ReflectionConfigurationFiles=C:\...\target\client\x86_64-windows\gvm\reflectionconfig-x86_64
-windows.json" "-H:JNIConfigurationFiles=C:\...\target\client\x86_64-windows\gvm\jniconfig-x86_64-windows.json" "-H:ResourceConfigurationFiles=C:\...\target\client\x86_64-windows\gvm\resourceconfig-x86_64-windows.json" "-Dsvm.platform=org.graalvm.nativeimage.Platform$WINDOWS_AMD64" -cp "C:\Users\...\AppData\Local\Temp\classpathJar13609332523791308069.jar" --allow-incomplete-classpath com....Application
[Di. Dez. 29 12:35:29 MEZ 2020][FINE] Start process compile...
```

**Comment by oubidar-Abderrahim** [comment]
Hi, thank you for reporting this issue. it's a known bug that was internally tracked (GR-27257) and fixed by this [commit](https://github.com/oracle/graal/commit/b254ed5cde7c0aa582092b71372b4e063fd8f8e2). 
You can try the fix in the snapshot of 21.0.0. if you still face this issue with the latest snapshot please reopen the issue.
