### ISSUE TITLE
performance of the genetared native-image decreased  by 2x

### ISSUE THREAD

**Issue by cyw3** [oracle/graal#3095]
**Describe the issue**
When I native-image and get the binary file, I found that the performance of the binary file deteriorated, and it took twice as long. How can I improve performance?

**Describe GraalVM and your environment:**
GraalVM version 20.3.0
JDK major version: "1.8.0_144"
OS: macOS Mojave
Architecture: AMD64

**Comment by mcraj017** [comment]
@cyw3 please provide the reproducer

**Comment by mcraj017** [comment]
Closing the issue as no reproducer has been shared
