### ISSUE TITLE
Graal Executable as Windows Service.

### ISSUE THREAD

**Issue by Azimuts** [oracle/graal#3097]
I have  build  a small _http / java service (based on vertx)_ and compiled it for Windows. (Exe) It works perfectly for me, but my intention is to run it as a Windows service. I do it through SC:

```
sc create MyService binPath = "MyServiceGraalExecutable.exe" start = auto
sc start MyService
```

**StartService FAILED 1053: The service did not respond.**

Is it possible to do this with the Graal executables?  Do i need any wrapper like Procrum ?

Thank you

**Comment by mcraj017** [comment]
@Azimuts Please provide the reproducer

**Comment by lazar-mitrovic** [comment]
This shouldn't be marked as a bug, but as a feature request.

In order for Windows to accept arbitrary executable as service, it must implement `ServiceMain` function as an entry point (which our executables never do). See https://stackoverflow.com/a/3582179

Implementing this as opt-in feature shouldn't be hard, but I doubt this should be high on our list of priorities.

As a workaround you can look into something like this: https://stackoverflow.com/a/26626771

**Comment by pquiring** [comment]
This is already possible, build the native image as a shared library instead of an executable and build your own native launcher.
I have code here that should work:
https://github.com/pquiring/javaforce/blob/master/stubs/windows/windows.c
Basically the native shared library has the same API that a full JRE provides (JNI_CreateJavaVM)

**Comment by mcraj017** [comment]
@Azimuts does the above comments resolved your issue, if not then please provide the reproducer

**Comment by mcraj017** [comment]
@Azimuts please try the solution s provided above, if that doesn't work then please reopen or report new issue

**Comment by sean-scott-lr** [comment]
@mcraj017 , and @pquiring I am curious what the linked solution was as I have the same requirement.

**Comment by nadirvishun** [comment]
Has anyone followed up on this issue? Does the new version of graalvm implements `ServiceMain`? I test 21 version still can not work.
