### ISSUE TITLE
There is no chance to update class initialization state from RUN_TIME to BUILD_TIME

### ISSUE THREAD

**Issue by ziyilin** [oracle/graal#3100]
**Describe the issue**
When a class is decided to be initialized at **RUN_TIME**, there is no chance to change its state to **BUILD_TIME** even if it actually can be safely initialized at build time. 

Given 3 classes `Test`, `A` and `C`:
```Java
public class Test {
    static public void main(String[] args){
        A.print();
    }
}

public class A {
    static C c = new C();
    static public void print(){
        System.out.println("123");
    }
}

public class C {
}
```
Class `A` is actually safe to initialize at build time, but it is eventually initialized at run time. This issue may affect run time performance. A PR(https://github.com/oracle/graal/pull/3102) is proposed to fix this issue.

**Steps to reproduce the issue**
Please include both build steps as well as run steps
1. Unzip the attached file
[testcase.zip](https://github.com/oracle/graal/files/5764360/testcase.zip)
2. Set `GRAALVM_HOME` environment variable to your GraalVM home
3. Run test.sh in unzipped testcase directory
4. Check the generated reports/run_time_classes_[time].txt, class `A` that is safe to initialize at build time is initialized at run time.

**More details**
Class `A`'s initialization state is set in  `com.oracle.svm.hosted.classinitialization.ClassInitializationFeature.duringAnalysis`. In the first iteration, `A` is considered as **RUN_TIME** because it depends on uninitialized class `C`. Later in the same iteration, class `C` is set **BUILD_TIME**. But there is no chance to update `A`'s state in the following up iterations, and the `A` class is eventually delayed to run time to initialize.

**Comment by vjovanov** [comment]
@ziyilin the class A gets initialized at build-time, just it doesn't do so before analysis (see the build-time list). This means that the class initializer will be omitted, but there will be no constant folding of fields. 

Do you have a use-case where this made a big impact on performance? 

We definitely need to improve error reporting here to explain what happens when, and what is the impact of that.

**Comment by ziyilin** [comment]
> the class A gets initialized at build-time, just it doesn't do so before analysis

So the class is actually initialized at build time, and it's only a reporting error? This issue was discovered by merely examining initialization reports. I didn't do any performance testing. I say it may affect runtime performance because the delayed initialization of classes that can be early initialized will impact the performance. 

If it's only a reporting issue, there is no performance problem.

**Comment by vjovanov** [comment]
It is initialized at bulid-time (and will be in the build_time) list of classes. It is just proven after analysis so constant folding doesn't happen.

I think we need to augment the list of classes as 'safe before analysis', and `safe after analysis`. The build time list will then contain `safe before analysis`, `safe after analysis`, and anything that was marked by the user.

**Comment by gilles-duboscq** [comment]
This is still open on the 21.1 milestone, is this already resolved or should it be moved to another milestone?

**Comment by vjovanov** [comment]
I consider this not to be an issue anymore. The reporting is better now, and our proofs are getting more precise.
