### ISSUE TITLE
Unbox-box operations don't seem to cancel out

### ISSUE THREAD

**Issue by chrisseaton** [oracle/graal#3101]
This may be a general Truffle PE or Graal issue but I'll illustrate using Ruby.

```java
/*
 * % javac Test.java
 * % java -XX:-UseOnStackReplacement -XX:+PrintCompilation -Dgraal.Dump=:3 Test
 */

import java.util.Random;

public class Test {
    private final static Random RANDOM = new Random();

    public static void main(String[] args) {
        while (true) {
            methodUnderTest(RANDOM.nextDouble() < 0.9 ? 1000 : 1000 + RANDOM.nextInt(1000));
        }
    }

    public static Integer methodUnderTest(Integer n) {
        if (n == 1000) {
            // 90% likely branch
            return n;
        } else {
            // 10% likely branch
            return n * 2;
        }
    }
}
```

This code does exactly what I'd expect. The more common branch returns `n` directly. This is a zero-allocation-path.

![methodUnderTest](https://user-images.githubusercontent.com/341094/103490539-66722080-4e14-11eb-8a5e-f29fc23dc8c0.png)

```ruby
# % ruby --jvm --experimental-options --engine.CompileOnly=method_under_test --engine.TraceCompilation --vm.Dgraal.Dump=Truffle:3 test.rb

def method_under_test(n)
  if n == 1000
    # 90% likely branch
    n
  else
    # 10% likely branch
    n * 2
  end
end

RANDOM = Random.new

loop do
  method_under_test RANDOM.rand < 0.9 ? 1000 : 1000 + Random.rand(1000)
end
```

This code doesn't do what I'd expect - the more common branch unboxes, then reboxes. We've got a method that is almost always the identity method, but it allocates every time!

![method_under_test](https://user-images.githubusercontent.com/341094/103490563-a2a58100-4e14-11eb-8971-b0fae01f8f8f.png)

This doesn't seem to go away in later tiers - this is after the low tier - it's still there.

![method_under_test-after-low-tier](https://user-images.githubusercontent.com/341094/103490596-db455a80-4e14-11eb-9e4f-a2666c1e18f2.png)

A related question - I've specifically used integer values above 1,000 in all cases here... but this code still includes the case for using the cache - which is completely wasted it's never going to be used! Does the range or branch not get profiled? I guess the Truffle interpreter doesn't provide any data on boxing!

**Comment by eregon** [comment]
Thanks for the report, I've moved the issue to oracle/graal since I don't think it's specific to Ruby.

Maybe a missing optimization in graal to remove the BoxNode#AllocatingBox following an UnboxNode?

Maybe it has to do with the Java code not needing any duplication, because of the two `return`, vs Truffle PE actually merging the result of `if/else`?

For curiosity I tried if two explicit `return` in Ruby would change something:
```ruby
def method_under_test(n)
  if n == 1000
    # 90% likely branch
    return n if true
  else
    # 10% likely branch
    return n * 2 if true
  end
end
```
The `if true` are to prevent the `return`-in-tail-position AST optimization, which would otherwise remove them.
But it's the same graph, it still re-boxes.

**Comment by eregon** [comment]
Here are the dumps for that method:
[TruffleHotSpotCompilation-10833[Object#method_under_test].zip](https://github.com/oracle/graal/files/5764478/TruffleHotSpotCompilation-10833.Object.method_under_test.zip)

Which can be reproduced with:
```ruby
def method_under_test(n)
  if n == 1000
    # 90% likely branch
    n
  else
    # 10% likely branch
    n * 2
  end
end

RANDOM = Random.new

2000.times do
  method_under_test RANDOM.rand < 0.9 ? 1000 : 1000 + Random.rand(1000)
end
```
and:
```
jt build --env jvm-ce
jt -u jvm-ce ruby --jvm --experimental-options --fg --engine.CompileOnly=method_under_test --trace --vm.Dgraal.Dump=Truffle:3 rebox.rb
```
(`jt` is https://github.com/oracle/truffleruby/blob/master/doc/contributor/workflow.md)

**Comment by chrisseaton** [comment]
By the way this a practical problem in larger more realistic code not just this contrived identity pattern - anything that makes a call with box a primitive argument, and if that primitive itself came from an argument we get this pattern.

**Comment by davleopo** [comment]
@eregon  based on the ruby graph supplied by @chrisseaton  I am a bit puzzled with the semantic in the ruby case: why does it return the value used for the comparison and reboxes it? shouldn't it use exactly the value supplied as an argument? I don't see why this would be an optimization, the fact that the true branch in the java version does not box anything is not an optimization but simply the program given: it returns n not anything boxed. I might overlook something here, but to me it seems the ruby version simply uses a "wrong" value.

**Comment by chrisseaton** [comment]
> why does it return the value used for the comparison and reboxes it? shouldn't it use exactly the value supplied as an argument?

Well that's the bug - what does it does this and why doesn't it use exactly the value supplied an argument?

> I don't see why this would be an optimization

The optimisation I'm hoping for is to replace `BOX(UNBOX(n))` with `n`. Is that safe to do? It seems like a valid and useful optimisation to me do you not look at it that way?

Note that `n` in Ruby goes via a local variable and is stored unboxed in the frame, and then boxed again, so I guess that's where the unboxing and boxing comes from in the first place. Maybe I should do a Java demo where I store `n` in an `int` local variable after reading it from the boxed parameter, and see if Java removes the `BOX(UNBOX(...`.

Does that all make sense or are we still not on the same page?

**Comment by chrisseaton** [comment]
This adds some more context:

```java
/*
 * % javac Test.java
 * % java -XX:-UseOnStackReplacement -XX:+PrintCompilation -Dgraal.Dump=:3 Test
 */

import java.util.Random;

public class Test {
    private final static Random RANDOM = new Random();

    public static void main(String[] args) {
        while (true) {
            methodUnderTest(RANDOM.nextDouble() < 0.9 ? 1000 : 1000 + RANDOM.nextInt(1000));
        }
    }

    public static Integer methodUnderTest(Integer n) {
        final int nUnboxed = n;

        if (nUnboxed == 1000) {
            // 90% likely branch
            return nUnboxed;
        } else {
            // 10% likely branch
            return nUnboxed * 2;
        }
    }
}
```

![a](https://user-images.githubusercontent.com/341094/103657660-13a67f00-4f62-11eb-9848-d50c650f02bd.png)

Still reboxing after the final phase even in Java:

![b](https://user-images.githubusercontent.com/341094/103657696-1b662380-4f62-11eb-8a6d-852a0129c9a3.png)

So is it a general Graal limitation that it doesn't simplify `BOX(UNBOX(...`? It's more of a problem in Truffle languages due to argument boxing.

**Comment by smarr** [comment]
My memory is very hazy, but this rings a bell.
Is there something in the Java spec that prevents the optimization because of object identity issues?

I do remember having a discussion at some conference, perhaps it was around 2015 at ICOOOLPS in Prague. I did also have some issues with storing doubles in frames and not getting the boxing eliminated.

**Comment by chrisseaton** [comment]
Sounds probable. Maybe we can relax that rule in Truffle if that's the case?

**Comment by davleopo** [comment]
>  Well that's the bug - what does it does this and why doesn't it use exactly the value supplied an argument?

Yes, it seems, might be related to the boxing usages but that seems unrelated of any optimizations involved.

> The optimisation I'm hoping for is to replace BOX(UNBOX(n)) with n. Is that safe to do? It seems like a valid and useful optimisation to me do you not look at it that way?

Well I dont want to think about the original issue like that, that is a different question and orthogonal to what seems to be going on in the ruby version of the program. In graal we optimize `unbox(box(n))` with `n`, that is safe. But the other way around generally not IMHO, there is caching involved on the java level: `box(unbox(n))` can be a different object (with different identity) if the value is out of range to fall into Integer$IntegerCache. Though the JLS states that  `For other values, the rule
disallows any assumptions about the identity of the boxed values on the programmer's part.
This allows (but does not require) sharing of some or all of these references.` jls 5.1.7 we currently do not perform optimizations around this in Graal. cc @tkrodriguez  any thoughts on this?

Nevertheless, the issue with not returning the argument in the ruby version looks wrong.

Regarding the second example the byte codes are different (probably related to the usage of a local variable)

(Compiled with javac)
Original version
```
       0: aload_0
       1: invokevirtual #10                 // Method java/lang/Integer.intValue:()I
       4: sipush        1000
       7: if_icmpne     12
      10: aload_0
      11: areturn
      12: aload_0
      13: invokevirtual #10                 // Method java/lang/Integer.intValue:()I
      16: iconst_2
      17: imul
      18: invokestatic  #7                  // Method java/lang/Integer.valueOf:(I)Ljava/lang/Integer;
      21: areturn
```


with a local variable 
```
       0: aload_0
       1: invokevirtual #10                 // Method java/lang/Integer.intValue:()I
       4: istore_1
       5: iload_1
       6: sipush        1000
       9: if_icmpne     17
      12: iload_1
      13: invokestatic  #7                  // Method java/lang/Integer.valueOf:(I)Ljava/lang/Integer;
      16: areturn
      17: iload_1
      18: iconst_2
      19: imul
      20: invokestatic  #7                  // Method java/lang/Integer.valueOf:(I)Ljava/lang/Integer;
      23: areturn

```

and thus the generated graal code.

**Comment by eregon** [comment]
> Nevertheless, the issue with not returning the argument in the ruby version looks wrong.

It would happen for any Truffle interpreter.

`n` in Ruby is a local variable, and as such it's stored in the VirtualFrame using https://github.com/oracle/truffleruby/blob/f9201a59830304c64a33933ddeaac97529ebc735/src/main/java/org/truffleruby/language/locals/WriteFrameSlotNode.java#L38-L42
which itself unboxes the value since it's passed to:
https://github.com/oracle/graal/blob/1a10caabf3c8c0319bf5bc447098a6041975de9a/truffle/src/com.oracle.truffle.api/src/com/oracle/truffle/api/frame/Frame.java#L137

**Comment by davleopo** [comment]
> It would happen for any Truffle interpreter.

Right, but that is for the specialized int version right? So the parameter itself is only used in its specialized, unboxed version, then the return boxes. Sounds like identity would not be necessary here.

**Comment by eregon** [comment]
To clarify, the identity of the Integer object is irrelevant in TruffleRuby and I would think in other languages too, so it seems fine to reuse the boxed Integer, even if the value is in the Integer$IntegerCache range and would somehow not be a cached Integer. 
Ruby's identity equal (`BasicObject#equal?`) would unbox and compare the actual values, rather than use Java's identity for Integer objects.

Furthermore, I'd think nobody does `new Integer(42)` in Truffle languages, might be something we could verify with Native Image.

**Comment by chrisseaton** [comment]
I'll see if I can find some relevant production examples and get back to you.

**Comment by tkrodriguez** [comment]
I think it would be safe to reuse the incoming box for values outside the range of the cache and just ensure that values in the caching range come from the cache.  That would avoid the overhead of the allocation while still preserving the documented semantics of valueOf.

**Comment by chrisseaton** [comment]
I looked at Truffle graphs produced by a large Ruby production application, using Shopify's [Seafoam](https://github.com/Shopify/seafoam) and [this script](https://github.com/Shopify/seafoam/blob/master/demos/box-unbox-stats).

```
     How many boxes take a value from an unbox?  9.1%
How many graphs contain at least one box-unbox?  9.7%
```

That's pretty amazing to me! ~9% of all box operations are unnecessary (given Truffle semantics, maybe not standard Java) and unnecessary box operations are found in ~10% of all our graphs!

Some are at return sites:

![1](https://user-images.githubusercontent.com/341094/103779756-1372b600-502c-11eb-9c64-692cea9ff1a8.png)

Some are from a load, an unbox, a box, a store:

![2](https://user-images.githubusercontent.com/341094/103779759-14a3e300-502c-11eb-9bf5-981676be6d01.png)

Some occur for values with lots of users:

![3](https://user-images.githubusercontent.com/341094/103779765-153c7980-502c-11eb-833c-1bf769ea12a6.png)

Quite a lot come out of a call and go into another call:

![4](https://user-images.githubusercontent.com/341094/103780396-d3600300-502c-11eb-82d5-dd44b5727916.png)

I don't think many are as a simple a case as returning an argument!

**Comment by davleopo** [comment]
Hi, @chrisseaton ,

I pushed a, cache-respecting, version of this optimization in https://github.com/oracle/graal/blob/0c68b7caf0571cee160fc8c798035ea7b5e9c7a0/compiler/src/org.graalvm.compiler.phases.common/src/org/graalvm/compiler/phases/common/BoxNodeOptimizationPhase.java  that should be sufficient for the truffle use case since the allocation is skipped now and we re-use a dominating unbox's value (or a dominating box altogether). The javadoc in the phase shows the patterns.

**Comment by chrisseaton** [comment]
Thanks very much I'll try it, get new data, and get back to you.

**Comment by chrisseaton** [comment]
Before:

<img width="693" alt="before" src="https://user-images.githubusercontent.com/341094/107387981-4279bd00-6aed-11eb-81de-52465ea14e01.png">

```asm
	0x10f9892c0:	mov	r10d, dword ptr [rsi + 8]
	0x10f9892c4:	shl	r10, 3
	0x10f9892c8:	cmp	rax, r10
	0x10f9892cb:	jne	0x10e471ba0
	0x10f9892d1:	nop	
	0x10f9892d2:	nop	word ptr [rax + rax]
	0x10f9892dc:	nop	
	0x10f9892e0:	mov	dword ptr [rsp - 0x14000], eax
	0x10f9892e7:	sub	rsp, 0x18
	0x10f9892eb:	mov	qword ptr [rsp + 0x10], rbp
	0x10f9892f0:	mov	eax, dword ptr [rdx + 0x2c]
	0x10f9892f3:	mov	esi, dword ptr [rax*8 + 0xc]
	0x10f9892fa:	movabs	r10, 0x7c00115f0
	0x10f989304:	cmp	esi, 0x3e8
	0x10f98930a:	jne	0x10f989367
	0x10f989310:	mov	rax, qword ptr [r15 + 0x60]
	0x10f989314:	lea	rsi, [rax + 0x10]
	0x10f989318:	nop	dword ptr [rax + rax]
	0x10f989320:	cmp	rsi, qword ptr [r15 + 0x70]
	0x10f989324:	ja	0x10f9893fd
	0x10f98932a:	mov	qword ptr [r15 + 0x60], rsi
	0x10f98932e:	prefetchw	byte ptr [rax + 0xd0]
	0x10f989335:	mov	rsi, qword ptr [r10 + 0xa8]
	0x10f98933c:	mov	qword ptr [rax], rsi
	0x10f98933f:	mov	dword ptr [rax + 8], 0xf80022be
	0x10f989346:	mov	dword ptr [rax + 0xc], 0
	0x10f98934d:	mov	dword ptr [rax + 0xc], 0x3e8
	0x10f989354:	mov	rbp, qword ptr [rsp + 0x10]
	0x10f989359:	add	rsp, 0x18
	0x10f98935d:	test	dword ptr [rip - 0x8b6c35d], eax
	0x10f989363:	vzeroupper	
	0x10f989366:	ret	
```

(Assembly only shows 90% path.)

After:

<img width="760" alt="after" src="https://user-images.githubusercontent.com/341094/107387993-460d4400-6aed-11eb-9de0-f14fd27abbcd.png">


```asm
	0x11302cf20:	mov	r10d, dword ptr [rsi + 8]
	0x11302cf24:	shl	r10, 3
	0x11302cf28:	cmp	rax, r10
	0x11302cf2b:	jne	0x111bd0ba0
	0x11302cf31:	nop	
	0x11302cf32:	nop	word ptr [rax + rax]
	0x11302cf3c:	nop	
	0x11302cf40:	mov	dword ptr [rsp - 0x14000], eax
	0x11302cf47:	sub	rsp, 0x18
	0x11302cf4b:	mov	qword ptr [rsp + 0x10], rbp
	0x11302cf50:	mov	eax, dword ptr [rdx + 0x2c]
	0x11302cf53:	mov	esi, dword ptr [rax*8 + 0xc]
	0x11302cf5a:	nop	word ptr [rax + rax]
	0x11302cf60:	cmp	esi, 0x3e8
	0x11302cf66:	jne	0x11302cf83
	0x11302cf6c:	shl	rax, 3
	0x11302cf70:	mov	rbp, qword ptr [rsp + 0x10]
	0x11302cf75:	add	rsp, 0x18
	0x11302cf79:	test	dword ptr [rip - 0x1148ef79], eax
	0x11302cf7f:	vzeroupper	
	0x11302cf82:	ret	
```

What this new node is is to pass through boxes outside the cache, and use the cache for values inside the cache. So there's still a simple cache check to maintain Java semantics. This may be useful anyway - canonicalising boxes may let objects die younger and reduce the working set.

Still gathering some large-scale numbers on our production app but it takes a while to dump that many graphs.

**Comment by chrisseaton** [comment]
Thanks this works well on our application!
