### ISSUE TITLE
GCC Windows

### ISSUE THREAD

**Issue by 89z** [oracle/graal#3111]
If I try to use `native-image`, I get this:

~~~
Error: Unable to compile C-ABI query code. Make sure native software development
toolchain is installed on your system.
~~~

Running again gives this:

~~~
java.io.IOException: Cannot run program "CL"
~~~

Its true, I dont have `CL.exe` on my system, but I do have GCC. It seems
currently, with Windows only the MSVC compiler is allowed:

https://github.com/oracle/graal/blob/d1b5c422b48859c7d65d5d599dc67727640a0dbb/substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/c/codegen/CCompilerInvoker.java#L108-L126

I think people should be able to choose what compiler they use.

**Comment by mcraj017** [comment]
@89z Yes you need to use MSVC to use native-image in windows
please follow this guide for using native-image
https://www.graalvm.org/docs/getting-started/windows/
