### ISSUE TITLE
Class initialization Exception building EMF related project

### ISSUE THREAD

**Issue by spket** [oracle/graal#3116]
**Describe the issue**
```
Error: Classes that should be initialized at run time got initialized during image building:
 org.eclipse.emf.ecore.resource.impl.BinaryResourceImpl$BinaryIO was unintentionally initialized at build time. To see why org.eclipse.emf.ecore.resource.impl.BinaryResourceImpl$BinaryIO got initialized use --trace-class-initialization=org.eclipse.emf.ecore.resource.impl.BinaryResourceImpl$BinaryIO
org.eclipse.emf.ecore.resource.impl.BinaryResourceImpl$EObjectInputStream was unintentionally initialized at build time. To see why org.eclipse.emf.ecore.resource.impl.BinaryResourceImpl$EObjectInputStream got initialized use --trace-class-initialization=org.eclipse.emf.ecore.resource.impl.BinaryResourceImpl$EObjectInputStream
```

**Steps to reproduce the issue**
attach file is the code to product the issue.
1. **mvn dependency:sources**
2. **./build.sh**
3. **./build.sh -native**

**Describe GraalVM and your environment:**
 - GraalVM version: **20.3, 21.1-dev**
 - JDK major version: **11**
 - OS: **Debian 10**
 - Architecture: **AMD64 & aarch64**

[test.zip](https://github.com/oracle/graal/files/5790310/test.zip)

**Comment by gilles-duboscq** [comment]
This is still open on the 21.1 milestone, is this already resolved or should it be moved to another milestone?
