### ISSUE TITLE
java.util.zip.ZipException: zip END header not found

### ISSUE THREAD

**Issue by MarioMO98** [oracle/graal#3117]
**Describe the issue**
Hi, we are getting an error trying to execute one of the spring native samples (https://github.com/spring-projects-experimental/spring-native/tree/master/spring-native-samples/cloud-function-netty).

We have been able to compile the project with native-image in Windows but we are getting java.util.zip.ZipException once we open the .exe file generated 

I have seen that this issue has been also reported here https://github.com/oracle/graal/issues/3093 with no solutions yet.

**Steps to reproduce the issue**
1. Open x64 Native Tools Command Prompt for VS 2019
2. cd to the spring sample folder (spring-native/spring-native-samples/cloud-function-netty)
2. mvn clean install
3. native-image -jar cloud-function-netty-0.0.1-SNAPSHOT.jar --no-fallback --verbose

**Describe GraalVM and your environment:**
 - GraalVM Version 20.3.0 (Java Version 11.0.9+10-jvmci-20.3-b06)
 - spring-graalvm-native 0.9.0-SNAPSHOT
 - JDK major version: openjdk version "11.0.9" 2020-10-20
 - OS: Windows 10
 - Architecture: AMD64

**More details**
This is the native-image building output:
native-image -jar ../cloud-function-netty-0.0.1-SNAPSHOT.jar --no-fallback --verbose
Executing [
'C:\graalvm-ce-java11-20.3.0\bin\java.exe' \
-XX:+UseParallelGC \
-XX:+UnlockExperimentalVMOptions \
-XX:+EnableJVMCI \
-Dtruffle.TrustAllTruffleRuntimeProviders=true \
-Dtruffle.TruffleRuntime=com.oracle.truffle.api.impl.DefaultTruffleRuntime \
-Dgraalvm.ForcePolyglotInvalid=true \
-Dgraalvm.locatorDisabled=true \
-Dsubstratevm.IgnoreGraalVersionCheck=true \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.aarch64=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.amd64=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.code.site=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.code.stack=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.code=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.common=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.hotspot.aarch64=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.hotspot.amd64=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.hotspot.sparc=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.hotspot=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.meta=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.runtime=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.services=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.sparc=ALL-UNNAMED \
--add-exports=org.graalvm.truffle/com.oracle.truffle.api=ALL-UNNAMED \
--add-opens=jdk.internal.vm.compiler/org.graalvm.compiler.debug=ALL-UNNAMED \
--add-opens=jdk.internal.vm.compiler/org.graalvm.compiler.nodes=ALL-UNNAMED \
--add-opens=jdk.unsupported/sun.reflect=ALL-UNNAMED \
--add-opens=java.base/jdk.internal.module=ALL-UNNAMED \
--add-opens=java.base/jdk.internal.ref=ALL-UNNAMED \
--add-opens=java.base/jdk.internal.reflect=ALL-UNNAMED \
--add-opens=java.base/java.io=ALL-UNNAMED \
--add-opens=java.base/java.lang=ALL-UNNAMED \
--add-opens=java.base/java.lang.reflect=ALL-UNNAMED \
--add-opens=java.base/java.lang.invoke=ALL-UNNAMED \
--add-opens=java.base/java.lang.ref=ALL-UNNAMED \
--add-opens=java.base/java.net=ALL-UNNAMED \
--add-opens=java.base/java.nio=ALL-UNNAMED \
--add-opens=java.base/java.nio.file=ALL-UNNAMED \
--add-opens=java.base/java.security=ALL-UNNAMED \
--add-opens=java.base/javax.crypto=ALL-UNNAMED \
--add-opens=java.base/java.util=ALL-UNNAMED \
--add-opens=java.base/java.util.concurrent.atomic=ALL-UNNAMED \
--add-opens=java.base/sun.security.x509=ALL-UNNAMED \
--add-opens=java.base/jdk.internal.logger=ALL-UNNAMED \
--add-opens=java.desktop/sun.java2d.cmm.profiles=ALL-UNNAMED \
--add-opens=org.graalvm.sdk/org.graalvm.nativeimage.impl=ALL-UNNAMED \
--add-opens=org.graalvm.sdk/org.graalvm.polyglot=ALL-UNNAMED \
--add-opens=org.graalvm.truffle/com.oracle.truffle.polyglot=ALL-UNNAMED \
--add-opens=org.graalvm.truffle/com.oracle.truffle.api.impl=ALL-UNNAMED \
-XX:+UseJVMCINativeLibrary \
-Xss10m \
-Xms1g \
-Xmx6740410368 \
-Duser.country=US \
-Duser.language=en \
-Djava.awt.headless=true \
-Dorg.graalvm.version=20.3.0 \
-Dorg.graalvm.config= \
-Dcom.oracle.graalvm.isaot=true \
-Djava.system.class.loader=com.oracle.svm.hosted.NativeImageSystemClassLoader \
-Xshare:off \
--module-path \
'C:\graalvm-ce-java11-20.3.0\lib\truffle\truffle-api.jar' \
-Djdk.internal.lambda.disableEagerInitialization=true \
-Djdk.internal.lambda.eagerlyInitialize=false \
-Djava.lang.invoke.InnerClassLambdaMetafactory.initializeLambdas=false \
'-javaagent:C:\graalvm-ce-java11-20.3.0\lib\svm\builder\svm.jar' \
-cp \
'C:\graalvm-ce-java11-20.3.0\lib\svm\builder\objectfile.jar;C:\graalvm-ce-java11-20.3.0\lib\svm\builder\pointsto.jar;C:\graalvm-ce-java11-20.3.0\lib\svm\builder\svm.jar' \
'com.oracle.svm.hosted.NativeImageGeneratorRunner$JDK9Plus' \
-imagecp \
'C:\graalvm-ce-java11-20.3.0\lib\svm\library-support.jar;C:\Users\m.maeso.oliveros\Downloads\spring-native-master\spring-native-samples\cloud-function-netty\target\cloud-function-netty-0.0.1-SNAPSHOT.jar' \
'-H:Path=C:\Users\m.maeso.oliveros\Downloads\spring-native-master\spring-native-samples\cloud-function-netty\target\native-image' \
-H:Class=org.springframework.boot.loader.JarLauncher \
-H:Name=cloud-function-netty-0.0.1-SNAPSHOT \
-H:FallbackThreshold=0 \
'-H:CLibraryPath=C:\graalvm-ce-java11-20.3.0\lib\svm\clibraries\windows-amd64' \

]
[cloud-function-netty-0.0.1-SNAPSHOT:2436]    classlist:   4,187.62 ms,  0.96 GB
[cloud-function-netty-0.0.1-SNAPSHOT:2436]        (cap):  55,792.56 ms,  0.96 GB
[cloud-function-netty-0.0.1-SNAPSHOT:2436]        setup:  63,952.27 ms,  0.96 GB
[cloud-function-netty-0.0.1-SNAPSHOT:2436]     (clinit):     566.76 ms,  1.71 GB
[cloud-function-netty-0.0.1-SNAPSHOT:2436]   (typeflow):  13,476.56 ms,  1.71 GB
[cloud-function-netty-0.0.1-SNAPSHOT:2436]    (objects):   9,891.65 ms,  1.71 GB
[cloud-function-netty-0.0.1-SNAPSHOT:2436]   (features):     785.19 ms,  1.71 GB
[cloud-function-netty-0.0.1-SNAPSHOT:2436]     analysis:  25,308.94 ms,  1.71 GB
[cloud-function-netty-0.0.1-SNAPSHOT:2436]     universe:   1,289.35 ms,  1.71 GB
[cloud-function-netty-0.0.1-SNAPSHOT:2436]      (parse):   3,649.32 ms,  1.72 GB
[cloud-function-netty-0.0.1-SNAPSHOT:2436]     (inline):   2,703.46 ms,  2.28 GB
[cloud-function-netty-0.0.1-SNAPSHOT:2436]    (compile):  29,838.58 ms,  2.57 GB
[cloud-function-netty-0.0.1-SNAPSHOT:2436]      compile:  38,290.48 ms,  2.57 GB
[cloud-function-netty-0.0.1-SNAPSHOT:2436]        image:   4,720.73 ms,  2.57 GB
[cloud-function-netty-0.0.1-SNAPSHOT:2436]        write:   6,169.51 ms,  2.58 GB
[cloud-function-netty-0.0.1-SNAPSHOT:2436]      [total]: 144,421.38 ms,  2.58 GB

Native-image building seems to be fine, but once we open the .exe file generated we get the following output:

cloud-function-netty-0.0.1-SNAPSHOT.exe
_Exception in thread "main" java.lang.IllegalStateException: java.util.zip.ZipException: zip END header not found
        at org.springframework.boot.loader.ExecutableArchiveLauncher.<init>(ExecutableArchiveLauncher.java:52)
        at org.springframework.boot.loader.JarLauncher.<init>(JarLauncher.java:48)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)
Caused by: java.util.zip.ZipException: zip END header not found
        at java.util.zip.ZipFile$Source.zerror(ZipFile.java:1567)
        at java.util.zip.ZipFile$Source.findEND(ZipFile.java:1462)
        at java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1469)
        at java.util.zip.ZipFile$Source.<init>(ZipFile.java:1274)
        at java.util.zip.ZipFile$Source.get(ZipFile.java:1237)
        at java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:727)
        at java.util.zip.ZipFile$CleanableResource.get(ZipFile.java:844)
        at java.util.zip.ZipFile.<init>(ZipFile.java:247)
        at java.util.zip.ZipFile.<init>(ZipFile.java:177)
        at java.util.jar.JarFile.<init>(JarFile.java:348)
        at java.util.jar.JarFile.<init>(JarFile.java:319)
        at java.util.jar.JarFile.<init>(JarFile.java:285)
        at org.springframework.boot.loader.jar.AbstractJarFile.<init>(AbstractJarFile.java:39)
        at org.springframework.boot.loader.jar.JarFile.<init>(JarFile.java:128)
        at org.springframework.boot.loader.jar.JarFile.<init>(JarFile.java:123)
        at org.springframework.boot.loader.jar.JarFile.<init>(JarFile.java:109)
        at org.springframework.boot.loader.jar.JarFile.<init>(JarFile.java:100)
        at org.springframework.boot.loader.archive.JarFileArchive.<init>(JarFileArchive.java:57)
        at org.springframework.boot.loader.archive.JarFileArchive.<init>(JarFileArchive.java:53)
        at org.springframework.boot.loader.Launcher.createArchive(Launcher.java:162)
        at org.springframework.boot.loader.ExecutableArchiveLauncher.<init>(ExecutableArchiveLauncher.java:48)
        ... 2 more_

**Comment by oubidar-Abderrahim** [comment]
Issue tracked on #3093 and internally on GR-28692
