### ISSUE TITLE
updategraalinopenjdk broken with latest openjdk source

### ISSUE THREAD

**Issue by a74nh** [oracle/graal#3119]
**Describe the issue**
Using latest openjdk master, copying Graal source into it using updategraalinopenjdk is broken.

We currently use this to test run the jtreg tests using Graal. 

**Steps to reproduce the issue**

with latest master branch of Graal, MX, and OpenJDK

```
cd ~foo/graal_src
mx --java-home=/usr/lib/jvm/master updategraalinopenjdk ~/foo/jdk_src 17
```

```
Removing src/jdk.internal.vm.compiler/share/classes/org.graalvm.compiler.code/src/org/graalvm/compiler/code/ObjdumpDisassemblerProvider.java
Removing src/jdk.internal.vm.compiler/share/classes/org.graalvm.compiler.core.common/src/org/graalvm/compiler/core/common/SpectrePHTMitigations.java
Removing src/jdk.internal.vm.compiler/share/classes/org.graalvm.compiler.core.test/src/org/graalvm/compiler/core/test/CountedLoopOverflowTest.java
Removing src/jdk.internal.vm.compiler/share/classes/org.graalvm.compiler.core.test/src/org/graalvm/compiler/core/test/IntegerBoxEqualsTest.java

<SNIP>

Processing jdk.aot:compiler
  removed /home/alahay01/foo/jdk_src/src/jdk.aot/share/classes/jdk.tools.jaotc
  removed /home/alahay01/foo/jdk_src/src/jdk.aot/share/classes/jdk.tools.jaotc.binformat
  removed /home/alahay01/foo/jdk_src/src/jdk.aot/share/classes/jdk.tools.jaotc.test
  copying: /home/alahay01/foo/graal_src/compiler/src/jdk.tools.jaotc/src
       to: /home/alahay01/foo/jdk_src/src/jdk.aot/share/classes/jdk.tools.jaotc/src
  copying: /home/alahay01/foo/graal_src/compiler/src/jdk.tools.jaotc.binformat/src
       to: /home/alahay01/foo/jdk_src/src/jdk.aot/share/classes/jdk.tools.jaotc.binformat/src
  copying: /home/alahay01/foo/graal_src/compiler/src/jdk.tools.jaotc.test/src
       to: /home/alahay01/foo/jdk_src/src/jdk.aot/share/classes/jdk.tools.jaotc.test/src
Updating /home/alahay01/foo/jdk_src/make/CompileJavaModules.gmk...
Traceback (most recent call last):
  File "/home/alahay01/graal/mx/mx.py", line 17197, in <module>
    main()
  File "/home/alahay01/graal/mx/mx.py", line 17178, in main
    retcode = c(command_args)
  File "/home/alahay01/graal/mx/mx_commands.py", line 147, in __call__
    return self.command_function(*args, **kwargs)
  File "/home/alahay01/foo/graal_src/compiler/mx.compiler/mx_updategraalinopenjdk.py", line 403, in updategraalinopenjdk
    replace_lines(CompileJavaModules_gmk, begin_lines, end_line, new_lines, old_line_check, preserve_indent=True)
  File "/home/alahay01/foo/graal_src/compiler/mx.compiler/mx_updategraalinopenjdk.py", line 351, in replace_lines
    assert line, begin_line + ' not found'
AssertionError: jdk.internal.vm.compiler_EXCLUDES += \ not found
```

**More details**

This is caused by the following OpenJDK commit:

commit 1bd015fb0c29e1e4ea3ada86b6c83bf000956c02
Author: Magnus Ihse Bursie <ihse@openjdk.org>
Date:   Mon Jan 11 11:28:29 2021 +0000

    8258407: Split up CompileJavaModules.gmk into make/modules/$M/Java.gmk

    Reviewed-by: erikj

mx_updategraalinopenjdk.py is doing the following: 
    # Update jdk.internal.vm.compiler.EXCLUDES in make/CompileJavaModules.gmk
    # to exclude all test, benchmark and annotation processor packages.  

But, CompileJavaModules.gmk no longer contains jdk.internal.vm.compiler.EXCLUDES.
The contents have been refactored into multiple files.

The patch to resolve this is going to be a little more involved than a "quick" fix.

**Comment by dougxc** [comment]
@a74nh it would be great if you could help out with this.

**Comment by a74nh** [comment]
I was hoping there was someone who knew this area and could fix fairly quickly.

But, I'm happy to look at it.

**Comment by dougxc** [comment]
Unfortunately, since https://bugs.openjdk.java.net/browse/JDK-8255616, there has not been as much focus on maintaining Graal in the JDK.
Thanks for taking it on.

**Comment by a74nh** [comment]
This is actually a little simpler than I expected. Patch incoming on Monday....

**Comment by a74nh** [comment]
The merged patch fixes the issue I was seeing.
However, since then, there have been additional changes in OpenJDK. This causes updategraalinopenjdk to fail in a different way.

I wonder if this is worth fixing?
http://openjdk.java.net/jeps/410 will remove the Graal compiler code from OpenJDK.
Once this happens, will updategraalinopenjdk become deprecated?

**Comment by dougxc** [comment]
> Once this happens, will updategraalinopenjdk become deprecated?
It will certainly become unused for newer JDKs.
If there are people who still want to maintain/update Graal in earlier JDKs, then we will continue to accept PRs to keep it working.

**Comment by a74nh** [comment]
Ok, given the above, I've no plans on fixing the new issue(s). We've migrated away from using updategraalinopenjdk internally now.

I'm closing this because the merged patches fix the issue I was seeing.
