### ISSUE TITLE
Blindly using javascript inside java

### ISSUE THREAD

**Issue by eix128** [oracle/graal#3129]
**Feature request**

Please include the following information:

**Is your feature request related to a problem? Please describe.**

Hi , my friend had found optic calculation javascript library.
He wanted to use all huge library in java.
There are many functions to call.
He should look all functions and call them with GraalVM manually

We have looked at example:
https://blog.yuzutech.fr/blog/java-api-on-javascript-lib-graalvm/

We want automatically wrap javascript functions to java.
So we dont need to implement class ourself.
public class ChromaInstance implements Chroma {
//Bla bla bla
}
Is there any tool that i will give target javascript library
Example:
MakeWrapper opticLib.js OpticLibWrapped.java

//Autogenerated by MakeWrapper 
public class OpticLibWrapped implements Optic {
 public Vector void ray(Vector vec1,Vector vec2) {
    Vector newRay = context.eval("js", "ray"); 
}
//bla bla bla
}

There are many libraries in javascript with thousands of functions.
Many people using javascript and its popularity increasing.
Wrapping all functions manually tedious.

There are solution on C++ side on java project named JavaCPP
But we need same solution for javascript.

**Comment by wirthi** [comment]
Hi @eix128,

I don't think you need any wrapper here at all. Here is how I would solve the problem:

```
import org.graalvm.polyglot.Context;
import org.graalvm.polyglot.Value;
import org.graalvm.polyglot.Source;
import java.io.File;
import java.io.IOException;

public class Main {

    public static void main(String[] args) throws IOException {
	Source chromaSource = Source.newBuilder("js", new File("chroma.min.js")).build();

        Context context = Context.newBuilder("js").build();
        context.eval(chromaSource);
        
        //do it in JavaScript
        context.eval("js", "print('in JavaScript: '+chroma('pink').darken().saturate(2).hex());");

        //do it in Java
        Value chroma = context.eval("js", "chroma");
        Value pink = chroma.execute("pink");
        Value finalize = pink.invokeMember("darken").invokeMember("saturate", 2).invokeMember("hex");
        System.out.println("in Java: "+finalize.asString());
        context.close();
    }
}
```

Note I used two different variants: either you call the JavaScript code directly, or you use GraalVM's `Value` class to access the constructs in a more Java-style way.

Of course, your question is a different one: you would want to wrap the whole functionality in a Java class structure (automatically). But what is the reasoning for that? I can see why a Java-only programmer would prefer that. It would probably possible in _some cases_ to create a static Java class structure for a given JavaScript API.

Note, however, that this is not technically possible in the general case. In JavaScript, you can dynamically add/remove properties - while in Java, you cannot change a class once it is defined (you can only subclass it to add more fields/methods). How should that be represented in such a scenario? The `Value` class abstracts that away. While it might be a bit unusual for a Java programmer to access a class structure this way, it leaves all the flexibility on the JavaScript side and will work every time.

Best,
Christian

**Comment by eix128** [comment]
No , i want to utilize autocomplete on java ide and the thing you said is not a wrapper.
I need to look all method calls in javascript side.

**Comment by woess** [comment]
If you write/generate a Java interface for a JavaScript library, then can just use `Value.as(JavaInterface.class)` and GraalVM will automatically generate a wrapper class for this interface.

e.g.:
```java
public interface Chroma {
  Chroma darken();
  Chroma saturate(int value);
  String hex();
  List<Integer> rgba();
}
// ...
context.eval(source); 
Value chroma = context.eval("js", "chroma");
Chroma c = chroma.as(Chroma.class);
Chroma d = c.darken();
```

You still need to define the Java interface yourself. This isn't something GraalVM can do for you. You'd need a TypeScript definition file (.d.ts) to Java compiler for that.

**Comment by eix128** [comment]
Why there is no java interface generator script ? 
It wont be hard to make such utility for GraalVM.

**Comment by woess** [comment]
> Why there is no java interface generator script?

JavaScript sources do not provide the type information that would be needed to generate a typed Java interface (which I think is what you want), and parsing TypeScript is out of scope of GraalVM currently. We welcome community contributions, though!

Closing this since we don't have plans to make such a tool.

**Comment by eix128** [comment]
With transcoder facebook project , you can convert javascript to java directly.
Maybe you can use such tool in future.
I just give you links maybe you can look detailed.
These tools will help you:

https://www.youtube.com/watch?v=1VHtP5FV0kM
https://www.youtube.com/watch?v=xTzFJIknh7E
https://github.com/facebookresearch/TransCoder
