### ISSUE TITLE
Implement native method sun.misc.VM.latestUserDefinedLoader()

### ISSUE THREAD

**Issue by ConradGroth** [oracle/graal#3132]
**Feature request**

**Is your feature request related to a problem? Please describe.**
For a legacy system which provides health data via JMX, I'm using a check_jmx.jar from [here](https://exchange.nagios.org/directory/Plugins/Java-Applications-and-Servers/check_jmx/details). It basically opens an RMI connection, reads a mbean attribute and prints it to standard out, where it is then picked up by a monitoring system. Because every invocation of this check_jmx.jar spins up a JVM I was curious whether this is possible as a native-image as well. I was able to execute the check_jmx.jar with the native-image-agent enabled so that I got the native-image metadata. Compiling to a native-image on CentOS 7.6 **64bit** with graalvm-**21.1.0-dev** was also possible, but during execution I get the following exception:
Fatal error reported via JNI: JVM_LatestUserDefinedLoader called:  Unimplemented
[This file contains the relevant stack](https://github.com/oracle/graal/files/5837573/stack.txt)

**Describe the solution you'd like.**
I'm not quite sure if this is a bug or a feature request. In pull request [2465](https://github.com/oracle/graal/pull/2465) I read that these native calls should be intercepted and redirected in a native-image. Is that correct?

**Describe who do you think will benefit the most.**
Nearly every GraalVM user that uses serialization.

**Describe alternatives you've considered.**
Not using a native-image for the check_jmx code, but a native-image would most likely reduce our server load very much.

**Additional context.**

**Express whether you'd like to help contributing this feature**
Maybe possible.

**Comment by ConradGroth** [comment]
Maybe I found the problem: For supporting serialization the private method `latestUserDefinedLoader` of `ObjectInputStream` was substituted [here](https://github.com/oracle/graal/blob/657ab3c9045ece0ef166239443631dae7eccd7de/substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jdk/JavaIOSubstitutions.java#L63). But the subclass `sun.rmi.server.MarshalInputStream` also has a method `latestUserDefinedLoader` which itself calls `sun.misc.VM.latestUserDefinedLoader`. Maybe it's better to substitute that static method instead of its callers.

**Comment by ConradGroth** [comment]
I've solved the problem. I added this class to my app:
`@SuppressWarnings("restriction")
@TargetClass(sun.rmi.server.MarshalInputStream.class)
public final class sun_rmi_MarshallInputStream {

    @Substitute                                       
    private static ClassLoader latestUserDefinedLoader() {
    	return sun_rmi_MarshallInputStream.class.getClassLoader();
    }
}`

After that I got the following exception during execution of the native image:
`Exception in thread "main" java.lang.UnsatisfiedLinkError: no rmi in java.library.path
        at com.oracle.svm.core.jdk.NativeLibrarySupport.loadLibraryRelative(NativeLibrarySupport.java:132)
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:275)
        at java.lang.Runtime.loadLibrary0(Runtime.java:830)
        at java.lang.System.loadLibrary(System.java:1871)
        at sun.rmi.transport.GC$1.run(GC.java:89)
        at sun.rmi.transport.GC$1.run(GC.java:87)
        at java.security.AccessController.doPrivileged(AccessController.java:84)
        at sun.rmi.transport.GC.<clinit>(GC.java:87)`

I solved this by adding  `--initialize-at-build-time=sun.rmi.transport.GC` to the native-image call, because I read [here](https://gitter.im/graalvm/native-image?at=5b5f61f395988830b08b9607) that `System.loadLibrary` calls in static initializers are not recognized during image creation without this option.

After that the native app was executed successfully but always throwing this exception:
`Exception in thread "RMI GC Daemon" java.lang.UnsatisfiedLinkError: sun.rmi.transport.GC.maxObjectInspectionAge()J [symbol: Java_sun_rmi_transport_GC_maxObjectInspectionAge or Java_sun_rmi_transport_GC_maxObjectInspectionAge__]`

So I added another Substitute to my app:
`@TargetClass(className = "sun.rmi.transport.GC")
public final class sun_rmi_transport_GC {
    @Substitute                                       
    public static long maxObjectInspectionAge() {
    	return 0; //don't run a garbage collection. The process will die in some milliseconds anyway.
    }
}`

All this together executes remote JMX checks in a 10th of the time it needed before with a JVM.

**Comment by christianwimmer** [comment]
Fixed in 1a02532e1cd
