### ISSUE TITLE
How to post Java String to java entryPoint method with CCharPointer type using GraalVM?

### ISSUE THREAD

**Issue by Alicus-Shiqinghuayi** [oracle/graal#3146]
I am trying to create a shared library(so with header and lib files) of a java code using graalvm.

There will be one java method with 2 parameters of type String which I will call from Java

**My NativeNativeImpl java method analysis with annotation CEntryPoint looks like this**:
```
@CEntryPoint(name = "Java_net_luculent_liems_license_apinative_Native_analysis")
public static CCharPointer analysis(Pointer jniEnv, Pointer clazz,
                               @CEntryPoint.IsolateThreadContext long isolateId, CCharPointer dataCharStr) {
	//logic code
}
```
My Native java code to call analysis looks like this :
```
//declare native method 
private static native String analysis(long isolateThread, CCharPointer dataDomStr);

public static String analysisDataDom() {
        System.loadLibrary("nativeimpl");
        long isolateThread = createIsolate();
        String helloStr = "Hello from Java";
        //how to convert helloStr to CCharPointer type ???
        return analysis(isolateThread, helloStr);
}
```
My question likes comment: **how to post java String value to CCharPointer for native method?** 

I have tried to use CTypeConversion util to convert, like following:
```
CTypeConversion.CCharPointerPointerHolder cCharPointerHolder = CTypeConversion.toCStrings(strArr);
CCharPointer cCharPointer = analysis(isolateThread, cCharPointerHolder.get().read());
```
But in running time, there always has an error : 
```
2021-01-22 10:41:30.909 ERROR 1811 --- [nio-8080-exec-1] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Handler dispatch failed; nested exception is java.lang.Error: The class ImageSingletons can only be used when building native images, i.e., when using the native-image command.] with root cause

java.lang.Error: The class ImageSingletons can only be used when building native images, i.e., when using the native-image command.
        at org.graalvm.nativeimage.impl.ImageSingletonsSupport.checkInstalled(ImageSingletonsSupport.java:69) ~[graal-sdk-20.3.0.jar!/:na]
        at org.graalvm.nativeimage.impl.ImageSingletonsSupport.get(ImageSingletonsSupport.java:63) ~[graal-sdk-20.3.0.jar!/:na]
        at org.graalvm.nativeimage.ImageSingletons.lookup(ImageSingletons.java:86) ~[graal-sdk-20.3.0.jar!/:na]
        at org.graalvm.nativeimage.c.type.CTypeConversion.toCString(CTypeConversion.java:94) ~[graal-sdk-20.3.0.jar!/:na]
```

I don't konw the reason of **The class ImageSingletons can only be used when building native images**, but in my java code ,how to transter java String to CCharPointer? I have no idea.

Thanks for all answers!

**Comment by kirillp** [comment]
It is not a bug. Please post how-to`s to Graal slack group
https://app.slack.com/client/TN37RDLPK/CN9KSFB40/thread/CNBFR78F9-1611324425.015700

**Comment by kirillp** [comment]
To pass java string to native one needs:
- get char[] data = stirng.toCharArray()
- lock char[] data content pointer via `try (PinnedObject pinnedObject = PinnedObject.create(data)) { pointers use here  }`
- get address as local var inside the block pinnedObject.addressOfArrayElement(0).rawValue()
- call blocking "C" method passing the pointer and length in the try ... finally block

**Comment by kirillp** [comment]
If u need utf8 string you need to use byte[]

**Comment by JiangWork** [comment]
@Alicus-Shiqinghuayi same issue here, do you find any solution?
