### ISSUE TITLE
error 404 on dockerhub oracle/graalvm-ce:20.1.0-java11

### ISSUE THREAD

**Issue by davorceman** [oracle/graal#3147]
**Describe the issue**
Hello, at Friday suddenly my CI/CD pipelines started failing with error
>Error response from daemon: pull access denied for oracle/graalvm-ce, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

Is it moved somewhere?

**Comment by khampal** [comment]
Looks like they're all in the GitHub container registry (GHCR) now

See https://www.graalvm.org/docs/getting-started/container-images/ for details

**Comment by sandroalm** [comment]
@khampal in my case i'm graalvm-ce:20.1.0-java11-ol8 that is not there :(

**Comment by oubidar-Abderrahim** [comment]
As @khampal mentioned, all images are in GHCR.
@sandroalm for graalvm-ce:20.1.0-java11-ol8, unfortunately, we do not plan to add outdated and not LTS images to GHCR. please either update to the latest release or you can try and build the image yourself from this repo: https://github.com/graalvm/container/tree/master/community
