### ISSUE TITLE
Main entry point not found when using library flying-saucer-pdf !?!?

### ISSUE THREAD

**Issue by cmoine** [oracle/graal#3148]
**Describe the issue**
I am using GraalVM for a long time with several dependencies (such as AWS...). But as soon as I am using the dependency 'org.xhtmlrenderer:flying-saucer-pdf:9.1.20' the native compilation fails in a very weird way:

> Error: Main entry point class 'com.itemis.fotahub.aws.lambda.restapi.Main' not found.
> Error: Use -H:+ReportExceptionStackTraces to print stacktrace of underlying exception
> Error: Image build request failed with exit status 1

I have isolated the problem: I have commented all code which use this library. Even though, simply by adding this dependency in the gradle build script, it raises this very strange error. 

**Steps to reproduce the issue**
1. create a gradle project
2. Add 'org.xhtmlrenderer:flying-saucer-pdf:9.1.20' as dependency 
3. Run native compilation

**Describe GraalVM and your environment:**
 - GraalVM version 21.0.0 and 20.1.0
 - JDK major version: **8**
 - OS: **Ubuntu**
 - Architecture: **AMD64**

**More details**
All the option (--native-image-info, --verbose, and H:+ReportExceptionStackTraces) don't give anymore info.

**Comment by cmoine** [comment]
I am not able to reproduce the problem on a simple project. Maybe the error pops up by mixing several libraries. Problem is that the error doesn't give any hint on the problem... :-(

**Comment by oubidar-Abderrahim** [comment]
Could you please provide a working reproducer for this issue?

**Comment by cmoine** [comment]
Sorry, but I cannot reproduce it on a simple project, and I cannot give you the entire project. I guess you can close the ticket. Who knows maybe someone will have the same problem!

**Comment by hminukuri-chwy** [comment]
I am running into this error when I add this library , 
java.lang.ClassNotFoundException: com.lowagie.text.pdf.PdfName 

 implementation group: 'com.lowagie', name: 'itext', version: '2.1.7', ext: 'pom'
Tried to add above lib to resolve it , still running into same error

any thoughts ?

**Comment by wushuartgaro** [comment]
> I am running into this error when I add this library ('org.xhtmlrenderer', 'flying-saucer-pdf', '9.1.20') java.lang.ClassNotFoundException: com.lowagie.text.pdf.PdfName
> 
> implementation group: 'com.lowagie', name: 'itext', version: '2.1.7', ext: 'pom' Tried to add above lib to resolve it , still running into same error
> 
> any thoughts ?

Not sure whether you're using Quarkus 2.8 and above. If yes, the best way to deal with this is to import all the required libs to ensure the class path complete at build time. 
https://github.com/quarkusio/quarkus/issues/25526#issuecomment-1161955498

You can refer to the pom.xml of the flying-saucer-pdf library itself.
https://github.com/flyingsaucerproject/flyingsaucer/blob/v9.1.20/flying-saucer-pdf/pom.xml

For my case, I would need to add in these three libs to build the native image successfully
implementation group 'com.lowagie', name: 'itext', version: '2.1.7'
implementation group 'org.bouncycastle', name: 'bcprov-jdk14', version: '1.64'
implementation group 'org.bouncycastle', name: 'bcmail-jdk14', version: '1.64'

**Comment by faskan** [comment]
Hi,
I am facing the same problem with my AWS lambda that uses flying-saucer pdf library [https://github.com/TECHROOTS-BV/monorepo/tree/main/apis/ezytix](https://github.com/TECHROOTS-BV/monorepo/tree/main/apis/ezytix)

`quarkus build --native --no-tests -Dquarkus.native.container-build=true` results in the following failure

```
Error: Unsupported features in 3 methods
Detailed message:
Error: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved method during parsing: com.lowagie.text.pdf.PdfPublicKeySecurityHandler.<init>(). To diagnose the issue you can use the --allow-incomplete-classpath option. The missing method is then reported at run time when it is accessed the first time.
Trace: 
        at parsing com.lowagie.text.pdf.PdfEncryption.<init>(Unknown Source)
Call path from entry point to com.lowagie.text.pdf.PdfEncryption.<init>(): 
        no path found from entry point to target method

Error: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved method during parsing: com.lowagie.text.pdf.PdfPublicKeySecurityHandler.getRecipientsSize(). To diagnose the issue you can use the --allow-incomplete-classpath option. The missing method is then reported at run time when it is accessed the first time.
Trace: 
        at parsing com.lowagie.text.pdf.PdfEncryption.getEncryptionDictionary(Unknown Source)
Call path from entry point to com.lowagie.text.pdf.PdfEncryption.getEncryptionDictionary(): 
        no path found from entry point to target method

Error: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved method during parsing: org.bouncycastle.cms.RecipientId.match(java.security.cert.Certificate). To diagnose the issue you can use the --allow-incomplete-classpath option. The missing method is then reported at run time when it is accessed the first time.
Trace: 
        at parsing com.lowagie.text.pdf.PdfReader.readDecryptedDocObj(Unknown Source)
Call path from entry point to com.lowagie.text.pdf.PdfReader.readDecryptedDocObj(): 
        no path found from entry point to target method
```
At the same time, when with `--allow-incomplete-classpath` flag the build was successful and the application works as intended. 
I tried adding all flying-saucer dependencies explicitly in pom.xml as mentioned by @wushuartgaro. But it doesn't work.

**Comment by emakunin** [comment]
Thank you @wushuartgaro. Your comment so far is the only working version and solution i've found for quarkus. All new versions cannot pass Quarkus's validations. I believe they've started using language features that are not supported by GraalVM. Even trying to move all the checks to runtime does not help. With this version and dependencies list it works.
