### ISSUE TITLE
Compiler error: Detected a started Thread in the image heap

### ISSUE THREAD

**Issue by kirillp** [oracle/graal#3150]
GraalVM version 21.0.0

For the following code 
```
public class Socket11 {
  static final HttpClient client = HttpClient.newBuilder()
      .connectTimeout(Duration.ofSeconds(5)).build();
.....
}

```

I`m getting  build time error (see next comment)
The Socket11 class **does not** have build time initialization.

**Comment by kirillp** [comment]
Fatal error:com.oracle.svm.core.util.VMError$HostedError: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: Detected a started Thread in the image heap. Threads running in the image generator are no longer running at image runtime.  To see how this object got instantiated use --trace-object-instantiation=jdk.internal.net.http.HttpClientImpl$SelectorManager. The object was probably created by a class initializer and is reachable from a static field. You can request class initialization at image runtime by using the option --initialize-at-run-time=<class-name>. Or you can write your own initialization methods and call them explicitly from your main entry point.
	at com.oracle.svm.core.util.VMError.shouldNotReachHere(VMError.java:72)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:669)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:476)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)

**Comment by oubidar-Abderrahim** [comment]
Could you please provide steps to reproduce this issue?

**Comment by oubidar-Abderrahim** [comment]
I'm closing this issue for lack of reproducer, if you still face this issue please follow the template of reporting issues and provide clear detailed steps to reproduce the issue

**Comment by kirillp** [comment]
The reproducing code is in the 1st post.
This is compiler crash, what is the point in closing compiler bugs without resolution ?

**Comment by oubidar-Abderrahim** [comment]
@kirillp we didn't ask for much, we only asked to respect the template and to provide clear steps to reproduce. there's a lot of work to be done and all help we can get is much appreciated

**Comment by shelajev** [comment]
If I have the class like: 

```
import java.net.http.*;
import java.time.*;

public class Socket11 {
  static final HttpClient client = HttpClient.newBuilder()
      .connectTimeout(Duration.ofSeconds(5)).build();

  public static void main(String[] args) {
    System.out.println("The template is there for a reason, please follow it when submitting issues");
  }
}
```
Generating the config is necessary, so: 
```
java -agentlib:native-image-agent=config-output-dir=META-INF/native-image Socket11
```

Then building the native image like this fails with the error about the Thread above: 
```
native-image -cp . Socket11
```

Using the `-H:+PrintClassInitialization` I can see that `reports/build_time_classes_date_time.txt` does indeed have `Socket11` class. 

Initializing it at runtime from the command line makes the program work: 
```
native-image --initialize-at-run-time=Socket11 -cp . Socket11
...
./socket11
The template is there for a reason, please follow it when submitting issues
```

I don't currently know why the class gets configured to be initialized at build time.

**Comment by zapster** [comment]
With GraalVM 21.1.0, this is no longer an issue.
