### ISSUE TITLE
Make svm_heap as heapdump to analyze in VisualVM

### ISSUE THREAD

**Issue by kirillp** [oracle/graal#3158]
It would be useful to make svm_heap as heap dump, so we can open it in VisualVM and analyze.
Same way we can create a dashboard file.

**Comment by mcraj017** [comment]
@kirillp Please provide the following information:

1.     Is your feature request related to a problem? Please describe.
2.     Describe the solution you'd like.
3.     Describe who do you think will benefit the most.
4.     Describe alternatives you've considered.
5.     Additional context.

**Comment by kirillp** [comment]
The problem is executable and svm_heap sizes are large
 VisualVM dump significantly help understand svm_heap content and **retained** size

**Comment by mcraj017** [comment]
@kirillp Thanks for the feature request
We will check it out and come back to you

**Comment by christianwimmer** [comment]
GraalVM EE already supports heap dumps.
