### ISSUE TITLE
native-image toolchain check (cl.exe) on Windows doesn't work on some locales

### ISSUE THREAD

**Issue by FilipJirsak** [oracle/graal#3161]
**Description**
native-image on Windows uses string comparison to verify there is a correct `vc.exe` toolchain. Unfortunately, `vc.exe` prints its messages in a language determined by computer locale. With some languages the strings `Microsoft (R)` and `C/C++`are swapped.

**Steps to reproduce the issue**
Please include both build steps as well as run steps
1. Use Windows with display language set to Czech
1. or replace `cl.exe` on `PATH` with `cl.bat` which mimics the output of `cl.exe` in Czech (see below)
2. Run `native-image Hello`

Output:
```
[hello:805948]    classlist:   2,208.74 ms,  0.96 GB
[hello:805948]        setup:   1,471.09 ms,  0.96 GB
Error: Unable to detect supported WINDOWS native software development toolchain.
Error: To prevent native-toolchain checking provide command-line option -H:-CheckToolchain
Error: Use -H:+ReportExceptionStackTraces to print stacktrace of underlying exception
Error: Image build request failed with exit status 1
```

**Describe GraalVM and your environment:**
 - GraalVM version: 11.0.10+8 2021-01-19
 - JDK major version: 11
 - OS: Windows 10
 - Architecture: AMD64

**More details**
For example `cl.exe` in the Czech language prints this:
```
Optimalizující kompilátor C/C++ společnosti Microsoft (R) verze 19.28.29336 pro procesory x64
Copyright (C) Microsoft Corporation. Všechna práva vyhrazena.

použití: cl [ parametr... ] název_souboru... [ /link parametr_propojení... ]
```

See the `C/C++` is before `Microsoft (R)`. So the test on line [152 of CCompilerInvoker.java](https://github.com/oracle/graal/blob/cf4cf49c7858b367cadfe08b534eccfd08d6b197/substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/c/codegen/CCompilerInvoker.java#L152) fails:
```
if (scanner.findInLine("Microsoft.*\\(R\\) C/C\\+\\+") == null) {
  return null;
}
```
RegExp expects `C/C++` to continue right after `Microsoft (R)`.

One possible solution is to test both variants:
```
if (scanner.findInLine("Microsoft.*\\(R\\) C/C\\+\\+") == null &&
    scanner.findInLine("C/C\\+\\+.*Microsoft.*\\(R\\)") == null) {
  return null;
}
```

I didn't found any environment variable or command line argument which could switch `cl.exe` to print messages in English. I know there is a trick with deleting locale-specific resources, but I think this is no sustainable solution.

Workaround with `-H:-CheckToolchain` works (see #2522), but it's quite difficult to pass it in some environments.

**Comment by olpaw** [comment]
Hi @FilipJirsak !
Thanks for your request. Sounds like a good candidate for a PR that could be merged without much effort. :wink:

**Comment by FilipJirsak** [comment]
Hi @olpaw,
is the solution with two regexps the right one? Then I'll prepare PR.

**Comment by olpaw** [comment]
> is the solution with two regexps the right one?

Yes. It's low risk & fixes the issue.
