### ISSUE TITLE
Support `zig cc` as a toolchain/compiler on Windows

### ISSUE THREAD

**Issue by s5bug** [oracle/graal#3167]
**Feature request**

Please include the following information:

**Is your feature request related to a problem? Please describe.**
I'm having issues with using `cl`, having to disable the "windows toolchain check" and such, or install more components.

**Describe the solution you'd like.**
I'm pretty sure all this needs is a way to force using Linux/clang compiler flags on Windows.

**Describe who do you think will benefit the most.**
native-image users on Windows, or people who want to try native-image without VS installed.

**Describe alternatives you've considered.**
Using `cl` and dealing with the warnings/errors and installing the required components.

**Additional context.**
[`zig cc`: a Powerful Drop-In Replacement for GCC/Clang](https://andrewkelley.me/post/zig-cc-powerful-drop-in-replacement-gcc-clang.html)

**Express whether you'd like to help contributing this feature**
I have no clue how native-image works or what the internals look like, so I won't be able to contribute.

**Comment by mcraj017** [comment]
@s5bug thanks for the feature request
We will check it out and come back to you

**Comment by christianwimmer** [comment]
We are happy to accept pull requests that add support for different compiler tool chains, but do not have the time to work on that.

Please also keep in mind that all the libraries that a native image needs to be linked with are compiled using Microsoft's compiler tool chain in GraalVM releases, and that is something we can certainly not change.

**Comment by fernando-valdez** [comment]
Closing this ticket until we have a contribution PR associated with this feature
