### ISSUE TITLE
java11 native-image Optimized size and compilation speed

### ISSUE THREAD

**Issue by 362228416** [oracle/graal#3169]
**Feature request**

java11 native-image Optimized size and compilation speed? 

Now I am using the app opened by Quarkus to pack the native, which takes about 6-7 minutes and the size is about 90M. Is there any room for optimization? My compilation environment is 4-core 8G ubuntu

Please include the following information:

**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. E.g. I'm always frustrated when [...]

**Describe the solution you'd like.**

**Describe who do you think will benefit the most.**
GraalVM users, GraalVM contributors, developers of libraries and frameworks which depend on GraalVM, or somebody else?

**Describe alternatives you've considered.**

**Additional context.**
Add any other context about the feature request here.
For example, link to the relevant projects, documentation, standards.

**Express whether you'd like to help contributing this feature**
If you'd like to contribute, please read the [contribution guide](https://www.graalvm.org/community/contributors/).

**Comment by christianwimmer** [comment]
We are constantly working to improve image build time and the size of native images. But this issue is too generic to track any progress.
