### ISSUE TITLE
GraalVM does not seem to call substituted method during build-time initialization

### ISSUE THREAD

**Issue by dzou** [oracle/graal#3181]
I have a class which will create a static variable when initialized:

```
public class Properties {
  private static final String VERSION = getRuntimeVersion();

  /** Returns the current runtime version */
  private static String getRuntimeVersion() {
    return "old-version";
  }
}
```

I'm trying to substitute the `getRuntimeVersion` method with this substitution.

```
@TargetClass(className = "package.to.my.Properties")
final class PropertiesSubstitutions {

  private PropertiesSubstitutions() {
  }

  @Substitute
  private static String getRuntimeVersion() {
    return "new-version";
  }
}
```

I am also using `--initialize-at-build-time`.

I ran the graalvm build through the debugger and it looked like the original `getRuntimeVersion()` was being called during build-time initialization time, not the substituted method. So the static variable `VERSION` is always "old-version" and not "new-version".

I was wondering if this was intended ? (i.e. substitutions are only active at run-time?) Or will there be support for build-time level substitutions?

**Comment by gradinac** [comment]
Hey @dzou!

It is working as intended - substitutions only "kick in" at runtime - you will have the original class' code run at build-time. If your goal was to change the static field variable's value, you can do so by `@Alias`-ing the original field in the substitution class and using `@RecomputeFieldValue` to change it. That way, your class would still be initialized at build-time, but the static field would have a different value at runtime.

Do note, however, that you shouldn't normally use substitutions in your application - they introduce a large maintenance and debugging overhead. If possible, always try to solve the original problem without substitutions

**Comment by dzou** [comment]
Gotcha. Thanks for the guidance!

`@RecomputeFieldValue` works for me; I'll try seeing if there is a no-substitution-based solution.
