### ISSUE TITLE
java.awt.Toolkit was unintentionally initialized at build time - 21.0.0-java11

### ISSUE THREAD

**Issue by brianwyka** [oracle/graal#3186]
**Describe the issue**
I upgraded a build from `20.3.0-java11` to `21.0.0-java11` with no other changes and received this error.  Seems like this is a side-effect of the added `java.awt` and `java.swing` support added in this release.  Is there any way to disable this?

**Steps to reproduce the issue**
Please include both build steps as well as run steps
1. `git clone https://github.com/optum/sourcehawk`
2. `git checkout installation-fixes`
3. `./mvnw install -P distributions-build`

**Describe GraalVM and your environment:**
 - GraalVM version: **21.0.0-java11**
 - JDK major version: **11**
 - OS: **Linux**
 - Architecture: **x86_64**

**More details**
Consider adding the `--native-image-info` and  `--verbose` flags when building your native image and paste output below.

GIthub Actions build failure:
https://github.com/Optum/sourcehawk/runs/1827987005?check_suite_focus=true

```
Error: Classes that should be initialized at run time got initialized during image building: 

java.awt.Toolkit was unintentionally initialized at build time. To see why java.awt.Toolkit got initialized use --trace-class-initialization=java.awt.Toolkit
```

And after useing `--trace-class-initialization`:
```
Error: Classes that should be initialized at run time got initialized during image building:

java.awt.Toolkit was unintentionally initialized at build time. javax.swing.text.html.HTMLEditorKit caused initialization of this class with the following trace: 
  at java.awt.Toolkit.<clinit>(Toolkit.java:136)
  at java.awt.Cursor.<clinit>(Cursor.java:185)
  at javax.swing.text.html.HTMLEditorKit.<clinit>(HTMLEditorKit.java:642)
```

I haven't gotten any further.

Here is the `Dockerfile` I am using for building the image:

```Dockerfile
FROM optum-docker-builders.bintray.io/nativeimage:graalvm-ce-21.0.0-java11

# Build Arguments
ARG JAR
ARG WORKDIR

# Copy shaded native jar into build
COPY ${JAR} ${WORKDIR}/native-image.jar

# Define the working directory
WORKDIR ${WORKDIR}

# Build the native image
RUN native-image -cp native-image.jar \
    -H:+ReportExceptionStackTraces \
    --report-unsupported-elements-at-runtime \
    --no-fallback \
    --static
```

Effective `native-image.properties`:

```properties
Args = -H:Class=com.optum.sourcehawk.cli.Sourcehawk \
       -H:Name=sourcehawk \
       --no-server \
       --enable-url-protocols=http,https \
       --initialize-at-build-time=ch.qos.logback,org.fusesource.jansi \
       --initialize-at-build-time=com.fasterxml.jackson,org.slf4j,org.yaml.snakeyaml \
       --initialize-at-build-time=javax,jdk.xml.internal \
       --initialize-at-build-time=com.sun.xml.internal.stream.util,com.sun.xml.internal.stream.XMLEntityStorage \
       --initialize-at-build-time=com.sun.org.apache.xerces.internal.impl,com.sun.org.apache.xerces.internal.util,com.sun.org.apache.xerces.internal.xni,com.sun.org.apache.xerces.internal.utils
```

There are also some reflection configurations for custom classes in this repository which are irrelevant.

**Comment by oubidar-Abderrahim** [comment]
I am facing some issues with reproducing the issue using this example, is it possible to provide a smaller/simpler reproducer for this issue? that would be helpful

**Comment by brianwyka** [comment]
@oubidar-Abderrahim, would a project with just the JAR and `Dockerfile` be sufficient?

**Comment by oubidar-Abderrahim** [comment]
The ideal is to have an example I can run on the JVM (a JAR for example) to make sure that is working correctly, then generate the native-image.
unless you have another reason for using docker I have the native-image utility installed locally so I can generate the native image without the dockerfile, assuming I have a list of the exact args you're using.

**Comment by brianwyka** [comment]
@oubidar-Abderrahim, here is a repo which reproduces: https://github.com/brianwyka/oracle-graal-3186

You should be able to use that jar in graalvm 21.0.0 java 11 runtime to reproduce the issue

I've been using a `Dockerfile` since I am targeting cross-platform and java version builds.

**Comment by brianwyka** [comment]
I also just updated the issue to reference java `11`.  I had incorrectly tagged java `8`.  Java `8` seems to build just fine, only having the issue in java `11`.

**Comment by brianwyka** [comment]
I've done a little bit more research with `jdeps` and found that since I am using Lombok with generates a `@java.beans.ConstuctorProperties` annotation.  This annotation is in the `java.desktop` module which also has these `java.awt` and `javax.swing` classes...

**Comment by brianwyka** [comment]
It seems that `SnakeYAML` also uses `java.beans` classes (which I am using).

**Comment by IgorEulalio** [comment]
Has this been resolved?

**Comment by cstancu** [comment]
AWT has been improved in recent releases and the class initialization strategy has been updated. Please open a new issue if you still have problems with the latest realease.
