### ISSUE TITLE
Java Virtual Machine Launcher Error: error loading .../server/jvm.dll

### ISSUE THREAD

**Issue by FrannDzs** [oracle/graal#3187]
**Describe the issue**
A serious problem trying to run minecraft on windows 10 64 bits with the latest stable version 21.1.0 and also with the development updates

**Steps to reproduce the issue**
Install Java 8 Graal VM Stable 21.0.0
Pointing the java executable from the game launcher

**Describe GraalVM and your environment:**
 - GraalVM version *CE 21.0.0*
 - JDK major version: *8*
 - OS: *Win10*
 - Architecture: *AMD64]*

**More details** When pointing the javaw executable from the game launcher I immediately get an error of "Java Virtual Machine Launcher: error loading c:/.../jre/bin/server/jvm.dll" The versions that began to fail start from graal java 8 21.0.0 stable and development version, all the previous ones to this one worked without problems, and all the later ones do not work except the development version of January 25th.
```
    PASTE YOUR LOG/STACK TRACE HERE
```

**Comment by oubidar-Abderrahim** [comment]
Could you please provide a link to the most recent build that is working? and the oldest build that introduced this issue? also, is there a way to get more logs? that would be helpful

**Comment by FrannDzs** [comment]
> Could you please provide a link to the most recent build that is working? and the oldest build that introduced this issue? also, is there a way to get more logs? that would be helpful

Hello! Excuse me, how can I provide you with logs? this happens in the game launcher, when I point to javaw.exe, and the game console does not show anything because it does not start. tell me the argument or the way to provide the logs and I will send them immediately. the development version that worked was removed from github, it is from the 25th, the one from the 26th no longer works. How can i solve this? It is a headache.

**Comment by FrannDzs** [comment]
Is there any way to know which compilation I am using and it works? tell me please and I will provide it.

**Comment by FrannDzs** [comment]
@oubidar-Abderrahim Where do I get the error log from? I really want to repair this problem.

**Comment by oubidar-Abderrahim** [comment]
Unfortunately, I have no experience with Minecraft and I don't have a windows machine. So, I'll try to assist you as much as I can.
Surfing the internet I found this :
Navigate to your game directory as specified in your installation in the Launcher.

- On Windows, it is %appdata%\.minecraft\ by default

Navigate into the crash-reports directory in the game directory

- If the crash reports directory does not exist, the game may have crashed of a JVM failure, and one or multiple hs_err_pid#####.log file may be present in the game directory instead. Upload this file.

There should be files named like crash-yyyy-mm-dd_hh.mm.ss-(client/server).txt. The crash reports are named by the time of crash, with which you can decide which file is your crash report.

**Comment by shelajev** [comment]
another thing to try is to run it from the command line, usually the output there is a bit more verbose. 
I'm not sure how to do that, but probably something like navigating to the directory location of the launcher in the command line and running it by typing it's name in to the command line. 

I don't know about the minecraft launcher specifically. 
hs_err_pid#####.log files could be in the user home directory too I think.

**Comment by FrannDzs** [comment]
Hello! @shelajev @oubidar-Abderrahim  thanks for answering. Regarding the error, it is an error of the JVM and not of the launcher, since in the game folder no crashlog appears, I know what they are talking about, but no logs appear in the home java directory or in the crashlogs directory of the game.
I have tried to run the launcher via cmd as Oleg told me, showing me its operations in real time but at the time of the error it does not show anything, because the log it shows is from the launcher and not from the JVM ... :( It's driving me crazy Also the error message appears 2 or 3 times in a row. I have no way to find the error log, it is something that never happened to me, maybe there is a more advanced way to do it but I am an end user and I really don't know how.
The launcher runs, but when I point to the javaw which is so that the game knows which version to use, I immediately receive the error, as if it were performing some check and it gives an unsuccessful result, that's what I understand superficially

The problem recurs on linux if I'm not mistaken. I have tested on Ubuntu and I also had that error. Maybe you could reproduce the problem I have, it would take you 1 minute surely. The launcher is light and you do not need to download the game, just from the configuration you must point to the javaw.exe and that's all, the error will appear. There are many open source launchers out there, you can choose any one.

This is the launcher I use, could you please reproduce the problem?
Regards!
#launcher download
https://ci.huangyuhui.net/job/HMCL/181/artifact/HMCL/build/libs/HMCL-3.3.181.jar

**Comment by Xeonkryptos** [comment]
I'm having this error too and I don't use it in combination with Minecraft or anything else. I get this error by simply calling in the unpacked graal directory:
**bin\java -version**
I'm using a Windows 10 machine, too, and used the same download of the newest GraalVM version available via Github.

Hint, any call to any of the binaries instantiating a JVM instance (java.exe, javaw.exe, etc.) leading to this error just by starting them.

**Comment by oubidar-Abderrahim** [comment]
@Xeonkryptos Could you provide steps to reproduce this issue? that should make it easier
@fernando-valdez could you please verify this on your windows machine after @Xeonkryptos provides us with the steps to reproduce?

**Comment by fernando-valdez** [comment]
Hello @Xeonkryptos, @FrannDzs  I am taking a look at this issue. If I have any questions I will let you know

**Comment by fernando-valdez** [comment]
@Xeonkryptos, I think your error is due to an `>` in the path of your bin folder. Please change that and let us know if that fixed your issue

**Comment by fernando-valdez** [comment]
@FrannDzs, @Xeonkryptos, GraalVM CE is based on OpenJDK. By default OpenJDK does not include JavaFX, which is required to run the Minecraft launcher.

**Comment by FrannDzs** [comment]
> @FrannDzs, @Xeonkryptos, GraalVM CE is based on OpenJDK. By default OpenJDK does not include JavaFX, which is required to run the Minecraft launcher.

Hi Fernando, how are you? I know that the launcher needs JavaFX to start, but I don't use GraalVM as main JVM, so I run the launcher with Oracle's Java 8. Also I have GraalVM builds running without problems, even one (1) from January 25th, version after the stable CE 21.0.0 which is the build that started with the problems. I have absolutely the same problem as @Xeonkryptos. It doesn't differ at all, it just appears that way to me in this case.

**Comment by Xeonkryptos** [comment]
@fernando-valdez The `>` as you mentioned isn't a part of the path. It is displayed only by the Windows Command Prompt window but not a part of the path itself.
Additionally, I'm targeting to use the Windows GraalVM to compute a native binary with the native-image tool. It should compile a native binary (exe) based on Java code for Windows. It fails, obviously, as it can't instantiate the JVM in the native image calculation process (as mentioned above).


> 
> 
> @Xeonkryptos, I think your error is due to an `>` in the path of your bin folder. Please change that and let us know if that fixed your issue

@fernando-valdez The `>` as you mentioned isn't a part of the path. It is displayed only by the Windows Command Prompt window but not a part of the path itself.

Additionally, I'm targeting to use the Windows GraalVM to compute a native binary with the native-image tool. It should compile a native binary (exe) based on Java code for Windows. It fails, obviously, as it can't instantiate the JVM in the native image calculation process (as mentioned above).

I successfuly created a native binary for Linux systems on my Linux computer with the GraalVM but for Windows it fails as, again, mentioned above.

**Comment by gilles-duboscq** [comment]
@Xeonkryptos, regarding the issue were you get `Error: loading: ...\jre\bin\server\jvm.dll` when trying to start any JVM process, this might be due to `jvm.dll` requiring `MSVCR100.dll` which is [not shipped in the JDK anymore|https://www.oracle.com/java/technologies/javase/8u261-relnotes.html#JDK-8246783].
At least this is something we have seen on GraalVM EE. `MSVCR100.dll` Use to be shipped in the `jre\bin` directory next to other executable.

**Comment by Xeonkryptos** [comment]
@gilles-duboscq Thanks a lot! Installing the redistributable package from Microsoft as linked in the release notes http://support.microsoft.com/kb/2019667 solved my issue. The MSVCR100.dll was missing on my system...

**Comment by FrannDzs** [comment]
@gilles-duboscq, you are the master, my goodness, I had so much trouble and in the end the solution was so simple, sorry for the inconvenience caused, and thank you all so much!
