### ISSUE TITLE
Native Image build error response codes to help in troubleshooting

### ISSUE THREAD

**Issue by amitpal-source** [oracle/graal#3203]
Native Image error response codes to help in troubleshooting

Please include the following information:

Often times when native image has an error its hard to determine the root cause and troubleshoot
E.g. Execution failed for task ':nativeImage'.
> A problem occurred starting process 'command 'native-image''
and this is despite having to run it in --stacktrace --debug --info modes

other examples ....

it would be good to know if there is a specific error code with description related to either the hardware or missing dependency e.g. glibc in the above case and there could be a look up table for these error response codes similar to what we see in for example ldap 

Have the error codes map to the exceptions e.g. shown here in an RFC
https://ldapwiki.com/wiki/LDAP%20Result%20Codes

This will help to benefit the downstream usage and feedback of graalvm native image in embedded scenarios

**Comment by wirthi** [comment]
We are not working on error codes directly, but have merged many improvements over the last years to improve error messages, and generally, make it easier for users to figure out what is going wrong. Latest versions of Native Image will give you much more straightforward output if something is missing.
