### ISSUE TITLE
Enable better volatile read/write translation on AArch64

### ISSUE THREAD

**Issue by adinn** [oracle/graal#321]
AArch64 is currently generating ldr or str combined with one or more dmb instructions to ensure that volatile Java field loads and stores execute with the correct memory model semantics. It would be much better for AArch64 if the generated code employed a simple ldar or stlr, since these provide exactly the desired semantics.

In order to enable this it would be helpful if a volatile access were explicitly modelled in the front end, delegating the decision to expand the access it into into a Membar ; Access ; Membar sequence or, alternatively, a combined access and barrier like ldar/stlr to the back end. Of course, this will also require various front end phases to be changed

1. to preserve volatile semantics across access node substtiutions
2. to  limit movement of other memory nodes past volatile accesses in recognition of their function as memory barriers
3. to ensure that inserted gc barriers remain located with associated volatile write

An alternative approach to this problem is to explicitly associate volatile memory barriers with the volatile access and use an AArch64-specific phase running late in the front end to elide the barriers and replace the associated reads/writes with nodes which the back end can recognise as volatile (this has been successfully prototyped [here](https://github.com/oracle/graal/pull/313)). The benefit of the first approach is that it allows for the possibility that a smarter node relocation algorithm might be able to move non-volatile accesses around volatile accesses in special cases where it might be of benefit.

**Comment by wks** [comment]
Another Benefit of the first approach is that it works for multiple architectures.  AArch64 is not the only architecture that has special instructions that has volatile load/store semantics without needing explicit fence instructions.  RISCV, for example, has “acquire” and “release” flags on the load/store instructions, too.  [This page](http://www.cl.cam.ac.uk/~pes20/cpp/cpp0xmappings.html) has examples for x86 and AArch32, too.  So it will help extending the system for supporting other platform.
