### ISSUE TITLE
Include license file with Espresso releases

### ISSUE THREAD

**Issue by lucaswerkmeister** [oracle/graal#3212]
**Feature request**

Please include the following information:

**Is your feature request related to a problem? Please describe.**
As the maintainer of other GraalVM-related packages on the Arch User Repository ([jdk11-graalvm-bin](https://aur.archlinux.org/packages/jdk11-graalvm-bin/), [fastr-jdk8-bin](https://aur.archlinux.org/packages/fastr-jdk8-bin/), etc.), I would like to package Espresso as well. However, the releases for Espresso so far (21.0.0 and 21.0.0.2) do not include a license file, unlike other languages (e.g. `LICENSE_FASTR` in `r-installable-java11-linux-amd64-21.0.0.2.jar`, `LICENSE_GRAALPYTHON.txt` in `python-installable-svm-java11-linux-amd64-21.0.0.2.jar`, etc.). Worse, the license information in the source tree seems to be inconsistent – for example, as of current master, [espresso/mx.espresso/suite.py](https://github.com/oracle/graal/blob/master/espresso/mx.espresso/suite.py#L262-L275) declares the `ESPRESSO_LAUNCHER` distribution, whose main class is `EspressoLauncher`, to have the UPL license, but [EspressoLauncher.java](https://github.com/oracle/graal/blob/499aa32ec37e98b1b1e6f8537f6aec2bf142c719/espresso/src/com.oracle.truffle.espresso.launcher/src/com/oracle/truffle/espresso/launcher/EspressoLauncher.java#L5-L7) has a GPL2 license header. Consequently, I do not feel confident to infer any license information about this software, and will not distribute it in its present state.

**Describe the solution you'd like.**
Include a license file in the released packages (`LICENSE_ESPRESSO`, `LICENSE_ESPRESSO.txt`, or similar), which can be installed under `/usr/share/licenses/$pkgname/LICENSE`.

**Describe who do you think will benefit the most.**
GraalVM users.

**Describe alternatives you've considered.**
I asked about this in the GraalVM slack, where I was told that everything is GPL2 except for the polyglot API, which is UPL, but that statement alone is not enough for me to publish the package. I have considered publishing provisional Espresso packages with a custom license file to the effect of “here’s what I know, if you need more details please email Oracle’s lawyers”, but I would rather not do that.

**Additional context.**
I seem to recall that this has happened with another language in the past, probably GraalWASM, which was [announced](https://medium.com/graalvm/announcing-graalwasm-a-webassembly-engine-in-graalvm-25cd0400a7f2) for GraalVM 19.3.0 but for whose [first AUR release](https://aur.archlinux.org/cgit/aur.git/commit/?h=graalwasm-jdk11-bin&id=f86a381ff2dc8290d3ae558ee17316e2856da164) was for GraalVM 20.0.0. (However, the [GraalVM CE dev builds](https://github.com/graalvm/graalvm-ce-dev-builds/releases) where GraalWASM 19.3.0 could be downloaded seem to have been deleted in the meantime, so I can no longer verify whether they contained a license file or not.)

**Express whether you'd like to help contributing this feature**
No, I think this must be Oracle’s responsibility.

**Comment by mukel** [comment]
Fixed in 8d74bb543c556c25
All components in Espresso are licensed under GPLv2, (shipped as LICENSE_JAVAONTRUFFLE), except the optional `polyglot.jar` which is UPL (shipped inside polyglot.jar as LICENSE_POLYGLOT).
