### ISSUE TITLE
Calling polyglot Java (Espresso) on Arch Linux causes symbol lookup error: /usr/lib/libnss_files.so.2: undefined symbol: _nss_files_getcanonname_r

### ISSUE THREAD

**Issue by lucaswerkmeister** [oracle/graal#3215]
**Describe the issue**
Trying to run polyglot Java code from another guest language crashes the whole process.

```console
$ /usr/lib/jvm/java-11-graalvm/bin/graalpython --polyglot
Python 3.8.5 (Sun Feb 14 19:07:59 CET 2021)
[Graal, GraalVM CE, Java 11.0.10] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import polyglot
>>> polyglot.eval(language='java', string='1 + 1')
[To redirect Truffle log output to a file use one of the following options:
* '--log.file=<path>' if the option is passed using a guest language launcher.
* '-Dpolyglot.log.file=<path>' if the option is passed using the host Java launcher.
* Configure logging using the polyglot embedding API.]
[java] WARNING: Disabling multi-threading since the context seems to contain single-threaded languages: [R, python, wasm, js]
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.oracle.truffle.espresso.substitutions.Target_java_lang_ref_Reference (file:/usr/lib/jvm/java-11-graalvm/languages/java/espresso.jar) to method java.lang.ClassLoader.defineClass1(java.lang.ClassLoader,java.lang.String,byte[],int,int,java.security.ProtectionDomain,java.lang.String)
WARNING: Please consider reporting this to the maintainers of com.oracle.truffle.espresso.substitutions.Target_java_lang_ref_Reference
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[java] WARNING: Thread.start() called on Klass<Ljava/lang/ref/Reference$ReferenceHandler;> but thread support is disabled. Use --java.MultiThreaded=true to enable thread support.
[java] WARNING: Thread.start() called on Klass<Ljava/lang/ref/Finalizer$FinalizerThread;> but thread support is disabled. Use --java.MultiThreaded=true to enable thread support.
/usr/lib/jvm/java-11-graalvm/lib/polyglot/bin/../../../bin/java: symbol lookup error: /usr/lib/libnss_files.so.2: undefined symbol: _nss_files_getcanonname_r
```
A similar thing happens with FastR instead of GraalPython (`eval.polyglot('java', '1 + 1')`); also, the issue happens with JDK8 as well.

I have not yet tried to reproduce the issue on a snapshot build.

**Steps to reproduce the issue**
1. Use Arch Linux, probably. (I haven’t tested this on any other OS.)
2. Build and install the [jdk11-graalvm-bin](https://aur.archlinux.org/packages/jdk11-graalvm-bin/) package.
3. Build and install the [fastr-jdk11-bin](https://aur.archlinux.org/packages/fastr-jdk11-bin/) package.
4. Build and install the [espresso-jdk11-bin](https://gist.github.com/lucaswerkmeister/223a1dd4119c8cafcb5dfc454374dd79) package. (Not yet available on the Arch User Repository due to oracle/graal#3212.)
5. Run `/usr/lib/jvm/java-11-graalvm/bin/R --polyglot`
6. Type into the REPL `eval.polyglot('java', '1 + 1')`

**Describe GraalVM and your environment:**
 - GraalVM version: **CE 21.0.0.2**
   - `java -Xinternalversion`: OpenJDK 64-Bit Server VM (11.0.10+8-jvmci-21.0-b06) for linux-amd64 JRE (11.0.10+8-jvmci-21.0-b06), built on Jan 15 2021 11:41:46 by "buildslave" with gcc 7.3.0
 - JDK major version: **8 and 11**
 - OS: **Arch Linux**
 - Architecture: **AMD64**

**More details**
[graalpython-ld_debug.tar.gz](https://github.com/oracle/graal/files/5983485/graalpython-ld_debug.tar.gz) is a tarball with `LD_DEBUG=all` output files (the errors are in `graalpython-ld_debug.8295`). There are several other NSS-related symbol lookup errors (as well as ones for JVM and Java symbols, which might be expected, I don’t know), `_nss_files_getcanonname_r` just happens to be the first NSS symbol lookup error (but not the first symbol lookup error overall).

I haven’t figured out yet where this symbol is being referred to, but I’m not especially familiar with dynamic linking either.

**Comment by lucaswerkmeister** [comment]
Running Java code with `java -truffle` works, by the way.

**Comment by mukel** [comment]
`java -truffle` loads native libraries directly (only allowing a single context), while Espresso on HotSpot uses glibc's dlmopen in order to load (the same) native libraries isolated from HotSpot's (e.g. libjava.so, libnio.so ...). dlmopen is known to be buggy, `LD_DEBUG=unused` should fix the lookup errors, but dlmopen brings some limitations/bugs e.g. no graphical applications can run in this mode. We are currently working on running the OpenJDK native libraries on top of Sulong.
I've seen the same error for `fstatat64`, but never for `_nss_files_getcanonname_r` I'll try to reproduce.

**Comment by mukel** [comment]
It seems that glibc 2.33 added a few non-existing symbols and broke symbol lookup inside isolated linking namespaces (dlmopen). `LD_DEBUG=unused` is now required to run Espresso on HotSpot.

**Comment by mukel** [comment]
Please use `LD_DEBUG=unused` as a workaround, I'll report the issue to glibc.
