### ISSUE TITLE
Add support for Thread#stop even though it is deprecated

### ISSUE THREAD

**Issue by borkdude** [oracle/graal#3220]
It would be really great if GraalVM could add support for Thread#stop even though it's deprecated.

In Clojure this is a very useful tool for development in a REPL.

This is explained here: https://github.com/jafingerhut/dontstop

Right now [babashka](https://github.com/babashka/babashka), a natively compiled Clojure interpreter, cannot support interrupted eval due to this missing functionality.

**Comment by chrisseaton** [comment]
I guess you mean Native Image here.

Some context is that Truffle, which is what Native Image was originally designed for, implements the same functionality using assumptions https://ssw.jku.at/Research/Papers/Daloze15.pdf. (I know that doesn't solve your problem - just giving the context.)

**Comment by borkdude** [comment]
@chrisseaton Yes, native image (I assumed the method wasn't available at all in the JVM either). 

Thanks for the pointer.

The interpreter component in babashka ([sci](https://github.com/borkdude/sci)) does not use any Truffle specific code as this interpreter also works in non-GraalVM JVMs and even in JavaScript.

So all code in babashka is just regular JVM code agnostic to Truffle.

Is there still a way I could leverage this, while babashk/sci is not a Truffle guest language?

**Comment by chumer** [comment]
You could embed an Espresso (Java on Truffle) JVM that runs the JVM byte codes. From the outside you can interrupt the execution on all threads using https://www.graalvm.org/truffle/javadoc/org/graalvm/polyglot/Context.html#interrupt-java.time.Duration-. This keeps the state of the application consistent, but is also not guaranteed to succeed if the application e.g. catches all errors and ignores them. It is still early days for espresso and we are currently improving that interrupt mechanism (e.g. to no longer rely on Assumptions), but we'd appreciate the feedback.

**Comment by chrisseaton** [comment]
@borkdude have you investigated using `SwitchPoint`? https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/invoke/SwitchPoint.html and Section 5.1 of https://ssw.jku.at/Research/Papers/Daloze15.pdf.

**Comment by mcraj017** [comment]
@borkdude does the above comments solve your issue?

**Comment by borkdude** [comment]
I still have to wrap my head around @chrisseaton's comments. Can I write a GraalVM/Truffle-agnostic "Thread#stop" replacement using this? A small example would help.

Is there a technical reason GraalVM native-image doesn't support Thread#stop or is this just a "deprecated so we don't support it" decision?

**Comment by fernando-valdez** [comment]
@chumer, does this apply to the current state of GraalVM?
