### ISSUE TITLE
Disambiguate Maven Properties

### ISSUE THREAD

**Issue by dansiviter** [oracle/graal#3221]
**Feature request**

**Is your feature request related to a problem? Please describe.**
Unable to override properties on command line that may have unintended consequences with other plugins. e.g. `-Dskip=true` may cause other plugins to also skip requiring more complex `pom.xml` setup.

**Describe the solution you'd like.**
Prefix properties with something like `graalvm.nativeImage.` so skip would become:

```java
@Parameter(property = "graalvm.nativeImage.skip", defaultValue = "false")
private boolean skip;
```

**Describe who do you think will benefit the most.**
GraalVM users.

**Describe alternatives you've considered.**
Using custom properties, but requires implementation in every project the maven plugin is used and skip is required.

**Additional context.**
N/A

**Express whether you'd like to help contributing this feature**
Yes, I'm happy to contribute.

**Comment by MartinBalin** [comment]
Is this about native-image agent? Or what tool is this about?

**Comment by dansiviter** [comment]
Apologies, it's the Graal maven plugin.

**Comment by olpaw** [comment]
@dansiviter adding this will not break
```
        <plugin>
            <groupId>org.graalvm.nativeimage</groupId>
            <artifactId>native-image-maven-plugin</artifactId>
            <version>${graalvm.version}</version>
            <configuration>
                <skip>false</skip>
            </configuration>
        </plugin>
```
right?

**Comment by dansiviter** [comment]
@olpaw Correct. However, if I was to skip this on the command line, I'd have to use `-Dskip` which does not differentiate this plugin from others. For example, in Helidon's similar plugin, they've used `native.image.skip` (see [`GraalNativeMojo.java#L168`](https://github.com/oracle/helidon-build-tools/blob/master/helidon-maven-plugin/src/main/java/io/helidon/build/maven/graal/GraalNativeMojo.java#L168)). If you look at a more established plugin such as surefire, they've [purposefully deprecated](https://github.com/apache/maven-surefire/blob/master/maven-surefire-common/src/main/java/org/apache/maven/plugin/surefire/AbstractSurefireMojo.java#L205) `skipTests` due to it ambiguity.

**Comment by olpaw** [comment]
> @olpaw Correct. However, if I was to skip this on the command line, I'd have to use `-Dskip` which does not differentiate this plugin from others. For example, in Helidon's similar plugin, they've used `native.image.skip` (see [`GraalNativeMojo.java#L168`](https://github.com/oracle/helidon-build-tools/blob/master/helidon-maven-plugin/src/main/java/io/helidon/build/maven/graal/GraalNativeMojo.java#L168)). If you look at a more established plugin such as surefire, they've [purposefully deprecated](https://github.com/apache/maven-surefire/blob/master/maven-surefire-common/src/main/java/org/apache/maven/plugin/surefire/AbstractSurefireMojo.java#L205) `skipTests` due to it ambiguity.

Your request makes sense. Please provide a PR for this change.

**Comment by gilles-duboscq** [comment]
This is still open on the 21.1 milestone, is this already resolved or should it be moved to another milestone?

**Comment by lazar-mitrovic** [comment]
As of latest [graalvm/native-build-tools](https://github.com/graalvm/native-build-tools) release (0.9.12 at the moment) we support  `skipNativeBuild` and `skipNativeTests` tags and system properties. You can consult [the documentation](https://graalvm.github.io/native-build-tools/latest/maven-plugin.html#configuration-options) for more info.

If there are more conflicting options feel free to open an issue [on issue tracker for native-build-tools](https://github.com/graalvm/native-build-tools/issues) project.
