### ISSUE TITLE
native-image compiler consumes too much disk IO

### ISSUE THREAD

**Issue by qiujiangkun** [oracle/graal#3235]
**Describe the issue**
I've noticed that native-image compiler consumes too much disk IO on my project. I have seen 5 TiB in activity monitor.
There must be a misuage for memory, maybe some page is mapped to disk, the cache of file not working or simply native-image requires this much memory.
![image](https://user-images.githubusercontent.com/33482468/108698575-3ce59380-753f-11eb-9dfb-186cd55927b0.png)
```log
$ top -pid <xxx>
Processes: 336 total, 8 running, 5 stuck, 323 sleeping, 2674 threads                        18:55:55
Load Avg: 4.29, 3.48, 3.76  CPU usage: 18.17% user, 37.94% sys, 43.88% idle
SharedLibs: 161M resident, 37M data, 7264K linkedit.
MemRegions: 192936 total, 1728M resident, 40M private, 753M shared.
PhysMem: 7475M used (1769M wired), 65M unused.
VM: 119T vsize, 3210M framework vsize, 397400697(28483) swapins, 402360920(28197) swapouts.
Networks: packets: 23674229/30G in, 22174747/17G out.
Disks: 53466432/6853G read, 33574484/6314G written.

PID    COMMAND      %CPU  TIME     #TH  #WQ  #POR MEM    PURG CMPR PGRP  PPID  STATE   BOOSTS
33105  java         183.7 19:21.24 37/4 1    204  5819M+ 0B   20G- 33017 33102 running *0[1]
$ native-image
[/Users/jack/Dev/ngapi/target/native-image/ngapi:33105]    classlist: 127,572.95 ms,  2.65 GB
[/Users/jack/Dev/ngapi/target/native-image/ngapi:33105]        (cap):   9,503.86 ms,  2.65 GB
```

**Describe GraalVM and your environment:**
```
 - ComponentId              Version             Component name                Stability           Origin
--------------------------------------------------------------------------------------------------------
js                       21.0.0              Graal.js                      -
graalvm                  21.0.0              GraalVM Core                  -
native-image             21.0.0              Native Image                  Early adopter       github.com
```
 - JDK major version: 11
 - OS: MacOS Big Sur
 - Architecture: aarch64

`ps aux | grep <pid of native-image>`
[command_line.txt](https://github.com/oracle/graal/files/6021456/command_line.txt)

**Comment by SergejIsbrecht** [comment]
Dear @qiujiangkun,

your command-line output shows a JVM, not a native-image (SubstrateVM).

Output: command_line.txt
`/Users/jack/Library/Caches/Coursier/jvm/graalvm-java11@20.2.0/Contents/Home/bin/java -XX:+UseParallelGC -XX:+UnlockExperimentalVMOptions -XX:+EnableJVMCI -Dtruffle.TrustAllTruffleRuntimeProviders=true`

Are you certain, that you have a native-image process? 

> There must be a misuage for memory, maybe some page is mapped to disk, the cache of file not working or simply native-image requires this much memory.

You have to provide some more details: `pmap -X <pid>` will show you which files are mapped into memory. Furthermore, if you have problems with IO, you could use `perf` to sample page faults. On macOS there is probably something simular (DTrace?)

**Comment by qiujiangkun** [comment]
> your command-line output shows a JVM, not a native-image (SubstrateVM).
Sorry for the confusion, I'm just compiling my application with native-image compiler. The graalvm native image AOT compiler is written in java.

**Comment by qiujiangkun** [comment]
I think It's because my memory is only 8 GB. And native-image compiler requires a lot of memory, which my macbook can't handle without swap partition on disk.
```log
$ top -pid <native-image compiler>
Processes: 365 total, 5 running, 10 stuck, 350 sleeping, 3076 threads                       18:29:41
Load Avg: 1.87, 2.49, 2.45  CPU usage: 8.69% user, 23.30% sys, 67.99% idle
SharedLibs: 163M resident, 40M data, 9200K linkedit.
MemRegions: 192203 total, 1662M resident, 66M private, 1218M shared.
PhysMem: 7459M used (1617M wired), 77M unused.
VM: 129T vsize, 3210M framework vsize, 627853325(37264) swapins, 633802049(21259) swapouts.
Networks: packets: 34646775/40G in, 40450101/31G out.
Disks: 73820027/10T read, 51416834/9896G written.
```

**Comment by SergejIsbrecht** [comment]
If you have not enough memory (unlimited heap), your OS will probably swap out memory to disc, if swap is enabled. Which would explain why your process is writing too 'much' to disc.

You could specify a max heap-size for your native-image process when generating, but this could result in an OutOfMemoryError, when your specified heap is too small.

See: https://www.graalvm.org/reference-manual/native-image/BuildConfiguration/#memory-configuration-for-native-image-build

Does your memory run out on your device? You could use DTrace to sample page-faults. I think `/usr/bin/time -v native-image ...` can also sample page-faults.

Example-output:
```
32 actionable tasks: 32 up-to-date
        Command being timed: "./gradlew cJ cTJ"
        User time (seconds): 0.77
	System time (seconds): 0.08
	Percent of CPU this job got: 41%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 0:02.06
	Average shared text size (kbytes): 0
	Average unshared data size (kbytes): 0
	Average stack size (kbytes): 0
	Average total size (kbytes): 0
	Maximum resident set size (kbytes): 94396
	Average resident set size (kbytes): 0
	Major (requiring I/O) page faults: 0
	Minor (reclaiming a frame) page faults: 20119
	Voluntary context switches: 1853
	Involuntary context switches: 80
	Swaps: 0
	File system inputs: 0
	File system outputs: 352
	Socket messages sent: 0
	Socket messages received: 0
	Signals delivered: 0
	Page size (bytes): 4096
	Exit status: 0
```

**Comment by mcraj017** [comment]
@qiujiangkun thanks for reporting the issue
native-image compiles all the possible classes at build time to create native-image which consumes memory, but when you will run you application image, it will consume less memory.
If you will use --fallback option, then your application wont use java when running.

You command_line.txt is showing that you are using java and not native-image.

to read more about native-image, please check out 
https://www.graalvm.org/docs/getting-started/#native-images

If you still need further assistance, please share a reproducer.

**Comment by qiujiangkun** [comment]
> If you will use --fallback option, then your application wont use java when running.

I can't see a --fallback, but `--no-fallback`, `--auto-fallback` and `--force-fallback`

> You command_line.txt is showing that you are using java and not native-image.

command_line.txt is the argument I call native-image compiler itself(with sbt-native-image plugin), not my application

Thank you for the assistence, I had no luck compiling my application into native-image and gave up.

**Comment by mcraj017** [comment]
@qiujiangkun my bad, I meant --no-fallback
