### ISSUE TITLE
Update the tracing agent to create automatically the configuration output directory

### ISSUE THREAD

**Issue by sdeleuze** [oracle/graal#3250]
When using the tracing agent configured with paths like `config-merge-dir=target/classes/META-INF/native-image` or `config-output-dir=target/classes/META-INF/native-image`, the agent fails if the directory does not exists. As a consequence, it forces our users to configure that kind of Maven entry which is not very practical:
```
<plugin>
    <artifactId>maven-antrun-plugin</artifactId>
    <executions>
        <execution>
            <id>make-native-image-config-folder</id>
            <phase>test-compile</phase>
            <configuration>
                <target>
                    <mkdir dir="target/classes/META-INF/native-image"/>
                </target>
            </configuration>
            <goals>
                <goal>run</goal>
            </goals>
        </execution>
    </executions>
</plugin>
```
Could you please update the tracing agent to create the configuration output directory if it does not exists?

**Comment by gradinac** [comment]
Hey @sdeleuze!
The fix for this has been merged to master: https://github.com/oracle/graal/commit/d704ad5be087ee8a4f71f215aac7217430d9c079
The agent will now create the missing parent directories on top of creating the config directory. The extra maven task should no longer be needed :)
