### ISSUE TITLE
NativeImage report "Invalid maximum heap size: -Xmx0" error

### ISSUE THREAD

**Issue by ziyilin** [oracle/graal#3255]
**Describe the issue**
There are cases when run native-image inside docker container, JDK can't get correct physical total memory, leading to native-image startup failure "Invalid maximum heap size: -Xmx0". As shown in the picture below:
![image](https://user-images.githubusercontent.com/6834162/109908727-bc155d00-7cdf-11eb-938f-239a864280c3.png)
Still fails even the -J-Xmx1g is set:
![image](https://user-images.githubusercontent.com/6834162/109908675-a43dd900-7cdf-11eb-8bf4-a13a30521054.png)

**Steps to reproduce the issue**
This issue can be reproduced when JDK API `OperatingSystemImpl.getTotalPhysicalMemorySize()` returns 0.

**More details**
The root cause is some customized Linux OS kernels generate incorrect `/proc/self/mountinfo` file in the docker container. 
The `mountinfo` file should have this line for memory's mount information:
`218 210 0:29 / /sys/fs/cgroup/memory ro,nosuid,nodev,noexec,relatime - cgroup cgroup rw,memory`
But the incorrect version looks like:
`6728 7908 0:25 /docker/35e6caf352283b19ceee4f63ec152266f1d5107e9ab87e0b0ea5922c08359a7f /sys/fs/cgroup/memory ro,nosuid,nodev,noexec,relatime - cgroup cgroup rw,memory`
The `root` information is wrong. As a result, JDK API `OperatingSystemImpl.getTotalPhysicalMemorySize()` can't get the correct memory size and returns 0.

Although the root cause of this issue is not Native Image, there are two things can be improved in Native Image to avoid the failure.
1. Don't pass `-Xmx0` from `NativeImage` to `NativeImageGeneratorRunner`.
2. User's customized argument `-J-Xmx` should prior to the automatically generated one. 

A PR is proposed to apply the improvements: https://github.com/oracle/graal/pull/3254

**Comment by petermz** [comment]
Thank you for posting this issue, I encountered this error a few times but did not take time to investigate.


> 2. User's customized argument -J-Xmx should prior to the automatically generated one.

That doesn't help BTW, Java still complains about 0 being invalid size and exits

**Comment by ziyilin** [comment]
> That doesn't help BTW, Java still complains about 0 being invalid size and exits

Yes, user's argument is omitted by NativeImage now. My proposed PR fixes both of 1 and 2.

**Comment by ziyilin** [comment]
@petermz What are your OS kernel and docker environment when the same issue occurred? We track the issue to the incompatible  between Alibaba's OS kernel and Alibaba's docker. Docker version >= 1.13 is fine. I'm curious about your environment. May be this issue is more common than I think it is.

**Comment by petermz** [comment]
> What are your OS kernel and docker environment when the same issue occurred?

I believe the container was Alpine Linux 3.11, and Docker version must have been 19.03

> 2. User's customized argument -J-Xmx should prior to the automatically generated one.

Doesn't the latest `-Xmx` option win? If it does, user-supplied option must come after the default one

**Comment by olpaw** [comment]
Fix is already on master. See https://github.com/oracle/graal/pull/3254
