### ISSUE TITLE
Windows 10 detected a virus in graalvm-ce download

### ISSUE THREAD

**Issue by ebremer** [oracle/graal#3269]
I just downloaded https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-21.0.0.2/graalvm-ce-java11-windows-amd64-21.0.0.2.zip

and my Windows 10 system complained of an infected file in lib\svm\builder\svm.jar

![image](https://user-images.githubusercontent.com/4094961/110656917-67199100-818e-11eb-8845-f5fbf47e9807.png)

**Comment by mcraj017** [comment]
@ebremer thanks for reporting the issue
we will check it

**Comment by LarsEckart** [comment]
I'm running into the same issue. When using [this GitHub action](https://github.com/marketplace/actions/setup-graalvm-environment) on a self hosted windows runner, the build will fail with the following message `Error opening zip file or JAR manifest missing : C:\...\GraalVM\21.0.0-2-java11-amd64\x64\lib\svm\builder\svm.jar` and indeed, the file is not present. 

When I download the installer zip and extract it myself, the jar file is present though. When I tried copying it to the runner's folder, I got the following virus warning. I guess that is also what happens during the extraction inside the github action and therefore the file is missing.
![Screenshot 2021-03-19 at 17 20 02](https://user-images.githubusercontent.com/4414802/111804955-3f869f00-88d9-11eb-9783-1c37563d5c2a.png)

**Comment by mcraj017** [comment]
@ebremer I tried to use it on win 10, but i dont get this erro
is there anything specific you are doing with svm.jar?

**Comment by ebremer** [comment]
@mcraj017 nothing special at all.  I've been downloading and doing the same thing I do each time.  My machine is completely up to date including Windows Defender.

**Comment by mcraj017** [comment]
@ebremer please try the latest release 21.1.0

**Comment by ebremer** [comment]
@mcraj017 I didn't have the problem with 21.1.0.  Everything is working fine.

**Comment by mcraj017** [comment]
@ebremer great closing it now
