### ISSUE TITLE
Unknown name in option specification: tool:native-image-configure

### ISSUE THREAD

**Issue by pys-arhs** [oracle/graal#3270]
I tried to compile a native image from a jar file with the procedure described in https://blogs.oracle.com/javamagazine/graalvm-native-images-in-containers

Using graalvm-ce-java8-21.0.0.2 on Windows 10 from the x64 native command prompt for VS 2019.
I installed native-image:
```
>native-image --version
GraalVM Version 21.0.0.2 (Java Version 1.8.0_282-b07)
```

However, the following command to build native-image-configure is not recognized:
`native-image --tool:native-image-configure `

```
Error: Unknown name in option specification: tool:native-image-configure
Available tool options are:
    --tool:coverage
    --tool:insight
    --tool:dap
    --tool:chromeinspector
    --tool:lsp
    --tool:profiler
```

This command is also mentioned in the documentation :
https://www.graalvm.org/reference-manual/native-image/BuildConfiguration/#the-configuration-tool

Am I missing something? 
Maybe it is not supported on Windows? Not available in CE? Not available in Java 8 version? Or the command changed since the documentation was written?

**Comment by mcraj017** [comment]
@pys-arhs this tool has been removed as the same can be achieved by tracing agent, check the below link to use tracing agent
https://docs.oracle.com/en/graalvm/enterprise/19/guide/reference/native-image/tracing-agent.html

**Comment by mcraj017** [comment]
@olyagpl please check, if we still this in documentation
https://www.graalvm.org/reference-manual/native-image/BuildConfiguration/#the-configuration-tool

**Comment by olyagpl** [comment]
@pys-arhs, It's just that this option at one point was renamed from `--tool:native-image-configure` to `--macro:native-image-configure-launcher`. Another point is that this option is only available if native-image got built via `mx` (https://github.com/oracle/graal/blob/master/substratevm/SubstrateVM.md). The Native Image Configure Tool component is not part of any GraalVM release that a user can download from www.graalvm.org. The documentation should be updated soon.
