### ISSUE TITLE
Quarkus Nightly consistently failing

### ISSUE THREAD

**Issue by andrewcraik** [oracle/graal#3272]
**Describe the issue**
The Graal github.com action `Nightly quarkus tests` has been failing for the last 6 months. There are a number of different issues in the builds. See [https://github.com/oracle/graal/actions/workflows/quarkus.yml](https://github.com/oracle/graal/actions/workflows/quarkus.yml)

**Steps to reproduce the issue**
[https://github.com/oracle/graal/actions/workflows/quarkus.yml](https://github.com/oracle/graal/actions/workflows/quarkus.yml). The action is run every night and is also triggered for some PRs from what I can see.

**Describe GraalVM and your environment:**
 - GraalVM version **HEAD every night**
 - JDK major version: **11**
 - OS: **Ubuntu 18.04**
 - Architecture: **AMD64**

I am not sure if the tests should continue running if they are unmonitored or if the issues should be investigated and fixed to keep the build green.

**Comment by dougxc** [comment]
@zakkak can you please look into this.

**Comment by zakkak** [comment]
Hi Andrew and Doug,

The Quarkus team is aware of this (see https://github.com/quarkusio/quarkus/issues/14904) and working on improving the situation.

**Comment by fniephaus** [comment]
Should we maybe disable the GitHub workflow until quarkusio/quarkus#14904 has been fixed? Seems quite wasteful to run CI for 6 months if it fails consistently.

**Comment by zakkak** [comment]
Please note that the workflow has indeed been failing for quite some time but mostly because of 1-2 tests (e.g. https://github.com/oracle/graal/issues/2783), which unfortunately there is no easy way to turn on/off on demand since the tests list changes between versions and we fetch it from the quarkus repository:
https://github.com/oracle/graal/blob/85eb61d7e07ea694b438edf8187e5b2887c439fe/.github/workflows/quarkus.yml#L83-L88

The explosion of failing tests happened with https://github.com/oracle/graal/commit/11b9817fb341f9447c300304fe461933bf79c2aa

That said, before https://github.com/oracle/graal/commit/11b9817fb341f9447c300304fe461933bf79c2aa the workflow was quite valuable, even though it was failing.

In any case, I am fine with temporarily disabling the workflow.

**Comment by zakkak** [comment]
Hello,

Just an update on this.

Most issues have now been fixed except for;
- Version parsing issue: https://github.com/quarkusio/quarkus/issues/16131 (This one is not causing failures though)
- Bouncy Castle FIPS: https://github.com/quarkusio/quarkus/issues/15889
  PR: https://github.com/quarkusio/quarkus/pull/16105
- Bouncy Castle JSSE: https://github.com/quarkusio/quarkus/issues/14139
- Elytron Security LDAP: https://github.com/oracle/graal/issues/3297
  PR: https://github.com/oracle/graal/pull/3298
- JGIT: https://github.com/oracle/graal/issues/3317
  PR: https://github.com/oracle/graal/pull/3318 
  
Unfortunately https://github.com/quarkusio/quarkus/pull/15971 didn't make it into 1.13.0.Final so the workflow is still all red...
With the next release most tests should be back to green.

**Comment by zakkak** [comment]
Hello,

Another update on this:

The only issues left to make the CI green again are:
* https://github.com/oracle/graal/pull/3298
* https://github.com/oracle/graal/pull/3407

**Comment by manodupont** [comment]
Hi,

Im using quarkus 1.12.0.Final,

I always have this coming into the log when using `./mvnw package -Pnative`

```
[student-app-1.0.0-SNAPSHOT-runner:79633]    classlist:   6,425.11 ms,  1.20 GB
[student-app-1.0.0-SNAPSHOT-runner:79633]        (cap):   3,803.10 ms,  1.20 GB
[student-app-1.0.0-SNAPSHOT-runner:79633]        setup:   5,902.96 ms,  1.20 GB
java.lang.NoClassDefFoundError: com/oracle/svm/core/jdk/LocalizationFeature
        at io.quarkus.runner.AutoFeature.beforeAnalysis(AutoFeature.zig:1149)
        at com.oracle.svm.hosted.NativeImageGenerator.lambda$runPointsToAnalysis$13(NativeImageGenerator.java:726)
        at com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:71)
        at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:726)
        at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:582)
        at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$2(NativeImageGenerator.java:495)
        at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
```

Im not sure i understand whats the fix here ?

I do use the latest version released of Quarkus.

Am I ?

**Comment by zakkak** [comment]
Hi @manodupont 

> Im using quarkus 1.12.0.Final
> ...
> I do use the latest version released of Quarkus.
> 
> Am I ?

The latest is 1.13.7.Final and should be used with GraalVM 21.0.0 not 21.1.0

If you have still have issues with that combination please open an issue at https://github.com/quarkusio/quarkus

**Comment by manodupont** [comment]
oh!

looks great. I'll try that. thanks for that.

**Comment by zakkak** [comment]
Closing this, as "Quarkus Nightly" is green the last 4 days
![image](https://user-images.githubusercontent.com/1435395/123605877-fc579880-d804-11eb-8c76-b82a3ca0f183.png)
