### ISSUE TITLE
Executable size regression in 21.1 

### ISSUE THREAD

**Issue by kirillp** [oracle/graal#3280]
**Describe the issue**
My simple app compiled by graalvm-ce-java11-21.0.0 is 7500k executable
And if compiled by graalvm-ce-java11-21.1.0-dev - 8M executable

So executable is 500k size bigger, have no differences in source code.

**Steps to reproduce the issue**
Please include both build steps as well as run steps

Use trivial System.out.println(); program
Compile it using graalvm-ce-java11-21.0.0 and graalvm-ce-java11-21.1.0-dev

**Describe GraalVM and your environment:**

 - GraalVM version 
 - GRAALVM_VERSION="21.1.0-dev" JAVA_VERSION_DATE="2021-01-19"
 - GRAALVM_VERSION="21.0.0" JAVA_VERSION="11.0.10"

 - JDK major version:  11
 - OS: Windows
 - Architecture: AMD64

**Comment by mcraj017** [comment]
@kirillp please provide the reproducer

**Comment by kirillp** [comment]
What is not clear?
To reproduce compile a trivial single line program.
System.out.println();  with 21.0 and 21.1

**Comment by shelajev** [comment]
I assume this is reproducible with the hello world: 
``` 
public class Main { 
  public static void main(String[] args) {
     System.out.println("Kirill, is this it?"); 
  }
}
``` 

@kirillp  please confirm if that's the case, thank you.

**Comment by kirillp** [comment]
Right, the issue here is that we see +500k grow in executable size

**Comment by jaikiran** [comment]
FWIW - there's a similar discussion going on right now related to this here https://github.com/oracle/graal/issues/3422. I see that you created this issue on 15 March and were using 21.1.0.dev version. The commit/change which is being discussed in the other issue was done on March 10, so it's likely that what you are seeing here is the same as what's being discussed in that other issue.

**Comment by borkdude** [comment]
I see about 3MB size increase with 21.1 compared to 21.0.

Here is a report of each version:

[used_classes_bb_21.1.txt](https://github.com/oracle/graal/files/6526343/used_classes_bb_21.1.txt)
[used_classes_bb_21.0.txt](https://github.com/oracle/graal/files/6526344/used_classes_bb_21.0.txt)

**Comment by borkdude** [comment]
I see a 3MB increase when upgrading [babashka](http://babashka.org/) to 21.1.0.

The diff shows that classes from `sun.security.pkcs11`, `javax.security.auth`, `sun.security.util` are being pulled in extra.

[used_classes_bb_20210522_140854_21.0.0.txt](https://github.com/oracle/graal/files/6526376/used_classes_bb_20210522_140854_21.0.0.txt)

[used_methods_bb_20210522_141515_21.1.0.txt](https://github.com/oracle/graal/files/6526378/used_methods_bb_20210522_141515_21.1.0.txt)

[diff.txt](https://github.com/oracle/graal/files/6526381/diff.txt)

**Comment by wirthi** [comment]
Closing this older ticket. Note we now have the -Os argument to optimize for size, if that is your main pain point. https://www.graalvm.org/jdk23/reference-manual/native-image/guides/optimize-for-file-size/
