### ISSUE TITLE
[native-image] Error "Native library already loaded in classloader" depends on the server's lifetime

### ISSUE THREAD

**Issue by smelc** [oracle/graal#329]
The error message of native-image changes from the first to the second run, because of the server. Here are the steps to reproduce:

* Download http://dl.free.fr/sCWlTe9i1 (dm-18-03-31.jar, an ascii roguelike)
* Unzip dm-18-03-31.jar in /tmp/
* Execute `./native-image -Djava.library.path=/tmp/dm-18-03-31 -jar dm-18-03-31.jar`

At the first execution the error is :

```
Original error: com.oracle.svm.hosted.analysis.flow.SVMMethodTypeFlowBuilder$UnsafeOffsetError: Field AnalysisField<MemoryUtilSun$AccessorUnsafe.address accessed: false reads: true written: false> is used as an offset in an unsafe operation, but no value recomputation found. 
```

Then when executing it again, the error is :

```
Original exception that caused the problem: java.lang.UnsatisfiedLinkError: Native Library /home/churlin/PERSONNEL/hgames/www/dm-18-03-31/liblwjgl64.so already loaded in another classloader
```

This issue was first discussed in issue #304.

**Comment by vjovanov** [comment]
The build server is not supported anymore.
