### ISSUE TITLE
java run c++ find LoadNativeNode is called with unexpected arguments Exception

### ISSUE THREAD

**Issue by ruanzhi** [oracle/graal#3296]
Describe GraalVM and your environment :

openjdk version "11.0.10" 2021-01-19
OpenJDK Runtime Environment GraalVM CE 20.3.1 (build 11.0.10+8-jvmci-20.3-b09)
OpenJDK 64-Bit Server VM GraalVM CE 20.3.1 (build 11.0.10+8-jvmci-20.3-b09, mixed mode, sharing)

Hello there,

I use the "https://www.graalvm.org/reference-manual/llvm/Interoperability/" link to learn how to execute C/C++ in java
code show as below:
```
import org.graalvm.polyglot.*;

import java.io.File;
import java.io.IOException;

public class App4 {
    public static void main(String[] args) throws Exception {
            Context polyglot = Context.newBuilder().
                    allowAllAccess(true).build();
            String url=App4.class.getResource("/").getPath()+ "hello";
            System.out.println(url);
            File file = new File(url);
            Source source = null;
            try {
                source = Source.newBuilder("llvm", file).build();
            } catch (IOException e) {
                e.printStackTrace();
            }
            Value cpart = polyglot.eval(source);
            System.out.println(cpart.execute().asInt());
    }
}
```
The C code is as follows:
```
#include <stdio.h>

int main() {
    printf("Hello from GraalVM!\n");
    return 0;
}
```
I execute it through the "clang hello.c -o hello" command, and then execute it through the above java code, and report the following error
```
LoadNativeNode is called with unexpected arguments
        at <llvm> null(Unknown)
```

I used the "clang hello.c -lgraalvm-llvm -o hello1" command to execute, and the following error was reported:
```
ld: library not found for -lgraalvm-llvm
```
Therefore, how do I need to solve this problem? Is there any more detailed information to learn how to execute C/C++ in Java?

**Comment by mcraj017** [comment]
@ruanzhi thanks for reporting the issue
We will take a look and get back to you

**Comment by mcraj017** [comment]
@ruanzhi please use the below command and it will work
`clang hello.c -lgraalvm-llvm -o hello`
remember to use the clang provided by graalvm
