### ISSUE TITLE
About the error when building native-image with WSL2 

### ISSUE THREAD

**Issue by BoyceMa** [oracle/graal#3311]
![image](https://user-images.githubusercontent.com/11460761/112644336-43d62d80-8e80-11eb-97c9-9c74958d7217.png)

**Comment by oubidar-Abderrahim** [comment]
Hi @BoyceMa 

Please respect the template for opening issues in Graal Project providing a clear description of the issue, code & steps to reproduce, and information about the environment used for it.

I will close this issue, please create a new one with the required information and we will gladly look into it and provide support for it.

Thank you.
