### ISSUE TITLE
Can we implement JEP 295 in GraalVM, as we have with OpenJDK?

### ISSUE THREAD

**Issue by jessielesbian** [oracle/graal#3320]
Can we implement JEP 295 in GraalVM, as we have with OpenJDK?
https://openjdk.java.net/jeps/295

I want to combine the startup performance of native-image with the flexibility of not having to AOT-compile everything and the flexibility of getting to use reflection and JNI more freely of `jaotc`. Also, I want you guys to add profile-guided optimizations and LLVM backend to your implementation of `jaotc` as well.

Simply take the jdk.aot module from HotSpot OpenJDK 11. It may need a bit of porting to work on GraalVM.

GraalVM users will benefit the most.

I won't be able to contribute to this feature.

**Comment by mcraj017** [comment]
@dougxc please advise

**Comment by dougxc** [comment]
Hi @jessielesbian , for various internal reasons, we have omitted `jaotc` from GraalVM binaries from the very beginning. This decision is very unlikely to be reversed, especially now that OpenJDK has also stopped including `jaotc` by default in binaries (https://bugs.openjdk.java.net/browse/JDK-8255616).
That said, it would be interesting to hear of workloads where you found `jaotc` provided significant benefit.

**Comment by dougxc** [comment]
This seals the fate of any further effort to add `jaotc` to GraalVM: https://bugs.openjdk.java.net/browse/JDK-8264805
