### ISSUE TITLE
Wrong parameters in call to RuntimeClassInitialization.initializeAtBuildTime()

### ISSUE THREAD

**Issue by petermz** [oracle/graal#3322]
https://github.com/oracle/graal/blob/37989b2fe40feffd7f69f28cbfe46ff231b8cd35/substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jdk/management/ManagementFeature.java#L86

I believe this method expects all parameters to be package names. Same for `RuntimeClassInitialization.initializeAtBuildTime`.

I will submit a PR shortly.

**Comment by mcraj017** [comment]
@petermz noted and thanks

**Comment by petermz** [comment]
Hi @mcraj017 -- I see you've assigned this one to me, but I'm not sure how to proceed. There's a PR, but it is unreviewed, and I don't have commit rights anyway. Please advice.

**Comment by mcraj017** [comment]
@petermz no worries, I will assign it to the reviewer 
thanks

**Comment by petermz** [comment]
It seems all the problematic calls have been either fixed or removed. I can identify no other problems with calls to these two methods, so let's close this issue.
