### ISSUE TITLE
native-image build DLL dependency issue

### ISSUE THREAD

**Issue by lizhanhui** [oracle/graal#3325]
**Describe the issue**

We are building a DLL out of jar files on the Windows platform with the help of GraalVM native-image. The problem is that the artifact native-image generates depends on private Windows system DLLs, which are not supposed to be used according to this [thread](https://social.msdn.microsoft.com/Forums/en-US/a28331ae-19a3-4a34-b3ba-1e8fd4430375/missing-apimswincore-dlls). This makes the DLL non-portable.

![image](https://user-images.githubusercontent.com/641819/113260739-334f0880-9301-11eb-82ee-e6844233b3c5.png)

**Steps to reproduce the issue**
Please include both build steps as well as run steps
1. **[e.g.: git clone --depth 1 https://git.myrepo.com/projectone ]**
2. **[e.g.: mvn clean package]**

**Describe GraalVM and your environment:**
GraalVM CE 21.0
 - JDK major version: **[e.g.:8]**
  JDK 8
 - OS: **[e.g. macOS Catalina]**
 Windows
 - Architecture: **[e.g.: AMD64]**
x64

**More details**
Consider adding the `--native-image-info` and  `--verbose` flags when building your native image and paste output below.

Add any other information about the problem here. Especially important are stack traces or log output. Feel free to link to gists or to screenshots if necessary.
```
    PASTE YOUR LOG/STACK TRACE HERE
```

**Comment by kirillp** [comment]
It is not an issue, this DLLs are not private. 
Also Microsoft toolchain was sued to build the image, so that all is related to the underlying Visual Studio toolchain.
This is not related to GraalVM.
