### ISSUE TITLE
Improve support for resource registration

### ISSUE THREAD

**Issue by jovanstevanovic** [oracle/graal#3326]
**TASK** 
All resources that should be available at the run time need to be listed at image build time. Currently, all listed resources are included in a non-structured form, i.e., it is not possible to navigate resources like a file system. Also, resources are not separated by the class loader, i.e., every class loader sees all resources.
The image heap must include a virtual file system for the included resources that allows navigation.

**OVERVIEW**
- We need to add a possibility to navigate resources like a file system. This will be done by creating a custom filesystem using classes from `java.nio.file` package i.e. next classes: `FileSystem` which is representing the system itself, `FileSystemProvider` which is used to create new filesystems, `Path` which is representing paths in a filesystem, `FileAttributes` and `FileAttributesView` which are containing information about files in a filesystem.
- After that, we need to separate resources between different class loaders. Currently, we are using URLClassLoader to load resources in build time.

**PULL REQUEST**
PR is created, #3315.

**Comment by mcraj017** [comment]
@christianwimmer please advise
