### ISSUE TITLE
license question for Substrate

### ISSUE THREAD

**Issue by jlovejoy** [oracle/graal#333]
Your readme at the top level directory says GPL2 for Substrate, and the source files in Substrate have that license notice. But the license file in the Substrate sub-directory has the Classpath exception - is this a mistake?
Also, are all contributions to any sub-component (Substrate and others) under the OCA?

**Comment by jlovejoy** [comment]
also, would you consider using SPDX identifiers, for example: GPL-2.0-only WITH Classpath-exception-2.0 
as per https://spdx.org/spdx-specification-21-web-version#h.twlc0ztnng3b
:)

**Comment by olyagpl** [comment]
@jlovejoy , the question of licensing for Substrate VM has been clarified - Substrate VM is licensed under the GPL 2 with Classpath Exception and source files are marked as  "Oracle designates this particular  file as subject to the "Classpath" exception ...".

Thank you!
