### ISSUE TITLE
Cannot do ntlm authentication in a native image

### ISSUE THREAD

**Issue by neoludo** [oracle/graal#3331]
Hi,

I'm Using HttpUrlConnection that supports ntlm authentication.
I've modified conf/net.properties file :
jdk.http.ntlm.transparentAuth=trustedHosts

unit tests are working but when I launch the native compiled EXE file,  have an error with 401 

Is there a special configuration to be done ?

Thanks in advance for your help
Ludovic

**Comment by mcraj017** [comment]
@neoludo please provide a reproducer

**Comment by mcraj017** [comment]
Closing this issue as there is no response from user for more than 30 days
