### ISSUE TITLE
Does anyone follow up on this issue? 

### ISSUE THREAD

**Issue by zonghaishang** [oracle/graal#3344]
**Feature request**

Please include the following information:

go wasm support: https://github.com/oracle/graal/issues/381

**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. E.g. I'm always frustrated when [...]

**Describe the solution you'd like.**

**Describe who do you think will benefit the most.**
GraalVM users, GraalVM contributors, developers of libraries and frameworks which depend on GraalVM, or somebody else?

**Describe alternatives you've considered.**

**Additional context.**
Add any other context about the feature request here.
For example, link to the relevant projects, documentation, standards.

**Express whether you'd like to help contributing this feature**
If you'd like to contribute, please read the [contribution guide](https://www.graalvm.org/community/contributors/).

**Comment by mcraj017** [comment]
@dougxc Pleas advise on https://github.com/oracle/graal/issues/381

**Comment by dougxc** [comment]
@zonghaishang please don't open a new issue that simply asks "whats up" with an existing issue. I see that you left a comment already on the original issue. When time allows, the assignees on #381 will respond.
