### ISSUE TITLE
NoSuchMethodError for Toolkit.getDefaultToolkit() when using packed jar.

### ISSUE THREAD

**Issue by Berstanio** [oracle/graal#3352]
**Describe the issue**
I am using the newest dev-build with JDK 11. I try to build with native-image a very simple programm with awt but when I try to run the created executable I get a NoSuchMethodError(see below).
The strange thing is when I build this programm without bundeling it into a jar it runs perfectly fine. It doesn't matter whether I run the native-image-agent or not.

**Steps to reproduce the issue**
git clone https://github.com/Berstanio/GraalVM-Bug.git
native-image -jar Test.jar --no-fallback
Test.exe
(There should be the error)
native-image Test --no-fallback
Test.exe
(This should run fine)

**Describe GraalVM and your environment:**
 - GraalVM version: graalvm-ce-dev-builds-21.1.0-dev-20210413_0116
 - JDK major version: 11
 - OS: *Windows 10
 - Architecture: AMD64

**More details**
```
Exception in thread "main" java.lang.NoSuchMethodError: java.awt.Toolkit.getDefaultToolkit()Ljava/awt/Toolkit;
        at com.oracle.svm.jni.functions.JNIFunctions$Support.getMethodID(JNIFunctions.java:1104)
        at com.oracle.svm.jni.functions.JNIFunctions$Support.getMethodID(JNIFunctions.java:1089)
        at com.oracle.svm.jni.functions.JNIFunctions.GetStaticMethodID(JNIFunctions.java:416)
        at java.awt.Toolkit.initIDs(Toolkit.java)
        at java.awt.Toolkit.<clinit>(Toolkit.java:1427)
        at com.oracle.svm.core.classinitialization.ClassInitializationInfo.invokeClassInitializer(ClassInitializationInfo.java:375)
        at com.oracle.svm.core.classinitialization.ClassInitializationInfo.initialize(ClassInitializationInfo.java:295)
        at Test.main(Test.java:6)
```

**Comment by kkriske** [comment]
This is JNI configuration (You can know this as the exception comes from the `JNIFunctions` class.

I tried to recreate your issue with your build artifacts, same dev release, same environment. The produced native images from both the jar and the class file give me the `NoSuchMethodError`, so I cannot reproduce your issue.

**Comment by Berstanio** [comment]
Oh I'm really sorry, I found my mistake. As it looks like during testing I forgot to delete the META-INF/native-image/ folder for the .class file that I generated way earlier. In the .jar there obviously wasn't the jni configuration so the .jar failed on my pc and the .class not. I'm sorry I didn't realized it earlier!

**Comment by Jason5Lee** [comment]
I'm having this issue with agent config. It seems that the native image agent cannot detect this usage. My program is just a sample GUI. This function must have been invoked during agent running since the GUI showed up. Is it a limitation of the agent or did I do something wrong?

**Comment by Karm** [comment]
Hello @Jason5Lee , in my own experience, some config had to be added by hand. It also requires extensive testing including erroneous code paths, e.g. when C code invokes an exception in Java code, you need to register that etc.  This is not a GraalVM bug.
Lemme take a look at your reproducer to see what would I add on top of agent's work.
