### ISSUE TITLE
can't solve /usr/bin/id: cannot find -lz

### ISSUE THREAD

**Issue by Naihua-TW** [oracle/graal#3355]
**Describe the issue**
I also get `/usr/bin/id: cannot find -lz` error message,  I try flow [doc](https://www.graalvm.org/reference-manual/native-image/StaticImages/), but can't solve this issue, I know this issue high possibility not about graalvm, I'm sorry for any  problems that I may have caused.

**Steps to reproduce the issue**
./mvnw package -Pnative -DquarkusNativeArgs=-H:+StaticExecutableWithDynamicLibC

**Describe GraalVM and your environment:**
 - Java & graalvm version:
  openjdk 11.0.10 2021-01-19
  OpenJDK Runtime Environment GraalVM CE 21.0.0.2 (build 11.0.10+8-jvmci-21.0-b06)
  OpenJDK 64-Bit Server VM GraalVM CE 21.0.0.2 (build 11.0.10+8-jvmci-21.0-b06, mixed mode, sharing)
 - OS version:
    Red Hat Enterprise Linux Server 7.7
  

**More details**
![image](https://user-images.githubusercontent.com/62601980/114993050-fde41680-9ecd-11eb-87a4-36e467e16a0f.png)

**Comment by zakkak** [comment]
Hi @Naihua-TW it looks like you need to install `zlib-devel` can you please try the following?
```
yum install zlib-devel
```

**Comment by YihongGao** [comment]
Sorry response late, I found some problem about my server OS, I need a few day solve that.
I will try it command after fix OS problem, thanks you help.

**Comment by Naihua-TW** [comment]
us need more fix OS problem than I think, So I close this issue now. thanks you

**Comment by mcraj017** [comment]
ok thanks for the response, closing this issue now
