### ISSUE TITLE
SimpleLanguage test failure

### ISSUE THREAD

**Issue by OlegPliss** [oracle/graal#3361]
cd simplelanguage
mvn package

Failed tests:   testInteropStackAtGuest(com.oracle.truffle.sl.test.SLJavaInteropDebugTest): expected:<[com.oracle.truffle.sl.test.SLJavaInteropDebugTest$HostCalls.apply]> but was:<[doCall]>

GraalVM version:
OpenJDK 64-Bit Server VM GraalVM CE 21.0.0.2 (build 25.282-b07-jvmci-21.0-b06, mixed mode)

**Comment by oubidar-Abderrahim** [comment]
@OlegPliss please provide a more descriptive issue body so that we can understand where the issue is coming from. We encourage you to follow our issue's template

**Comment by OlegPliss** [comment]
`simplelanguage-graalvm-native` failed to link without zlib dev package installed.
