### ISSUE TITLE
Make GraalVM available in operating system package managers

### ISSUE THREAD

**Issue by edthamm** [oracle/graal#3363]
**Feature request**

Please include the following information:

**Is your feature request related to a problem? Please describe.**
When trying to install GraalVM globally for production images, which is useful in some contexts, the current installation paths are unconvincing. SDKMan does not help, manually upgrading versions every X units of time is not very fun either.

**Describe the solution you'd like.**
Publish GraalVM to popular Operating System repositories or host your own. Debian based would be my most burning concern, but other distributions should follow.

**Describe who do you think will benefit the most.**
Developers that want to run their stuff in production (by reduced friction). Operators that have to maintain these kinds of things.

**Describe alternatives you've considered.**
- Install via SDKMan globally -> Not a thing SDKMan does well (or at all)
- Install from Github and check for updates every X units of time -> Error prone and loads of manual work
- Complain at the SDKMan people
- Force every project that wants to run GraalVM to install and maintain versions on their own.
- Install some potentially old version globally and run  `gu upgrade` until that old version will not update anymore or breaks

**Additional context.**
This is not about upgrading in place once the install is complete. It is about building base images that others can rely on and installing GraalVM globally in a current version.

If you do not have time/find this is not a feature worth investing we will probably go with the `gu upgrade` route.

**Express whether you'd like to help contributing this feature**
- I currently have 0 time budget to build this myself. Should I ever get time for this, I am absolutely willing to help.

**Comment by msgilligan** [comment]
I would really like to see GraalVM CE available as a Debian Package (and although I'd prefer it be in the main repo, a "non-free" package would be preferable to no package at all). I've done a little bit of research and thought it might be helpful to share a few related links here:

* [Discussion on Debian-java list](https://www.mail-archive.com/debian-java@lists.debian.org/msg24908.html)
* [Community-developed Debian Package](https://github.com/dongjinleekr/graalvm-ce-deb)

The [Mandrel](https://github.com/graalvm/mandrel) project is interesting and provides a subset of GraalVM suitable for compiling Java apps with `native-image`. That distribution might be easier to adapt to Debian Free Software Guidelines as it has fewer dependencies. Although the response to https://github.com/graalvm/mandrel-packaging/issues/138 is somewhat negative on the prospects of an RPM or DEB.

**Comment by dongjinleekr** [comment]
Sorry for being late. [here](https://launchpad.net/graalvm-ce) it is.

As of present, it supports java 11 based, amd64 only. However, the other packages will be added soon.

**Comment by msgilligan** [comment]
@oubidar-Abderrahim You closed the issue as "completed" has there been a release (or will there soon be a release) for one or more Linux package managers (besides SDKMAN)?
