### ISSUE TITLE
https://graalvm.org/ reports invalid SSL certificate in Chrome, Firefox

### ISSUE THREAD

**Issue by rhencke** [oracle/graal#338]
The README.md links to `https://graalvm.org`, but this link appears as insecure (big red 'Your connection is not private' warning page when you click it.

(The certificate given over HTTPS is valid for `https://www.graalvm.org`, but not for `https://graalvm.org`.  Interestingly, they are not the same certificate, either.)

I am happy to provide more information if desired.

**Comment by thomaswue** [comment]
Thanks for the report! This seems to be related to our URL forwarding from https://www.graalvm.org to the GitHub pages site hosted by GitHub. I fixed now in the README.md to everywhere properly quality with https://www.graalvm.org. Please reopen if there is any additional issue related to this.
