### ISSUE TITLE
svm.jar package is defect. cant build native-image

### ISSUE THREAD

**Issue by StevenHachel** [oracle/graal#3380]
In the graalvm 21.1.0 Java 16/11 is the svm.jar "...\graalvm-ce-java16-21.1.0\lib\svm\builder\svm.jar"

**Comment by kristofdho** [comment]
Are you on windows? windows sometimes flags svm.jar als a thread, and removes it. Check defender.

If you are not on windows, please elaborate, there is very little to go on..

**Comment by StevenHachel** [comment]
Yes, windows 10 64. Sorry!
Under GraalVM 21.0.0 works perfectly.

I cannot open the svm.jar directly from the zip file either. Then a message comes up that the package is damaged.

Steven

**Comment by mcraj017** [comment]
@christianwimmer please advise

**Comment by mcraj017** [comment]
@StevenHachel please share the steps you are performing when getting this error

**Comment by mcraj017** [comment]
@StevenHachel I have tried building Helloworld native-image using graalvm 21.1.0 Java 16 on windows 10 64 bit and it worked fine

**Comment by StevenHachel** [comment]
Hey @mcraj017,
i downloaded the current graalv Java 16 again. Now the svm.jar can be opened in the archive and the native image can be generated. It's just strange that the archive was corrupted the last time it was downloaded.
Thank you for your efforts!

**Comment by mcraj017** [comment]
@StevenHachel great
