### ISSUE TITLE
IGV Fails Loading Graphs

### ISSUE THREAD

**Issue by smarr** [oracle/graal#3385]
**Describe the issue**
IGV currently has issues loading graphs generated by Graal.

Loading fails with errors such as:

```
Error loading null / TruffleIR::Planner>>#addPropagate:mark:() / Node 8,589 / Property nodeSourcePosition:
    Corrupted graph data: null, loading terminated. Previous object: org.graalvm.visualizer.data.serialization.BinaryReader$$Lambda$142/354682182@4fa99e95
```

It doesn't fail with all graphs, at the moment, it's perhaps 10%. 
To find the cause for this, I bisected through the Graal history and identified the following commit as likely related:
https://github.com/oracle/graal/commit/8ec6c62fad2442dd4ef47d82783bde7c2cf46286

With this merge, I have the issue, before, I don't.

Please find attached the smallest failing graph I was able to find.

[TruffleHotSpotCompilation-12402[Planner>>#addPropagate:mark:].bgv.zip](https://github.com/oracle/graal/files/6399477/TruffleHotSpotCompilation-12402.Planner.addPropagate.mark.bgv.zip)

This is tested with the latest IGV (release 21.1) from OTN.

**Comment by smarr** [comment]
Looking at the mentioned merge a little more, the line that breaks IGV is the addition to `GraphPrinterDumpHandler`.

If I remove it on `HEAD`, I can load all graphs.

```patch
diff --git a/compiler/src/org.graalvm.compiler.printer/src/org/graalvm/compiler/printer/GraphPrinterDumpHandler.java b/compiler/src/org.graalvm.compiler.printer/src/org/graalvm/compiler/printer/GraphPrinterDumpHandler.java
index 84f581d9cb52..1ef51ce8a124 100644
--- a/compiler/src/org.graalvm.compiler.printer/src/org/graalvm/compiler/printer/GraphPrinterDumpHandler.java
+++ b/compiler/src/org.graalvm.compiler.printer/src/org/graalvm/compiler/printer/GraphPrinterDumpHandler.java
@@ -195,7 +195,7 @@ public final class GraphPrinterDumpHandler implements DebugDumpHandler {
                     } catch (Throwable t) {
                         properties.put("node-cost-exception", t.getMessage());
                     }
-                    properties.put("StageFlags", ((StructuredGraph) graph).getStageFlags());
+                    // properties.put("StageFlags", ((StructuredGraph) graph).getStageFlags());
                 }
                 printer.print(debug, graph, properties, nextDumpId(), format, arguments);
             } catch (IOException e) {
```

/cc @davleopo and perhaps @chumer

**Comment by chrisseaton** [comment]
Seafoam also cannot read this file!

It causes something to get out of place and it fails while reading a node where the class is what appears to be a method for some reason.

**Comment by chrisseaton** [comment]
This property value is an `EnumSet`, but I don't think there's any code in the graph dumper to handle that class, and we get some kind of broken stream.

It looks like if you have a property of an unexpected type it ends up thinking it's a `String`? But that should be ok as then that means later on it prints it using `toString()`, so still not sure.

https://github.com/oracle/graal/blob/3e9680a269181289df946f0e46ce778b2097b61f/compiler/src/org.graalvm.graphio/src/org/graalvm/graphio/GraphProtocol.java#L529

https://github.com/oracle/graal/blob/3e9680a269181289df946f0e46ce778b2097b61f/compiler/src/org.graalvm.graphio/src/org/graalvm/graphio/GraphProtocol.java#L782

**Comment by chrisseaton** [comment]
The `EnumSet` pool object entry is getting pool ID 0, even though we're well into the file by this point, and there's already a string with that ID.

Two pool object entries with the same ID should I think never happen, so the file is corrupt.

**Comment by smarr** [comment]
Perhaps the bug isn't in the reader but the writer?

My investigation only went as far as bisecting Graal, and reverting the line that seems to cause it, but it is probably not the root cause.

**Comment by smarr** [comment]
This bug also prevents me to load GraalPython graphs.

Can be reproduced with `graalpython --vm.Xss2m --vm.Dgraal.Dump=Truffle,TruffleTree:2 harness.py Permute 2000 1000` with the code from here https://github.com/smarr/are-we-fast-yet/tree/932b44ec0a5f004454720a2069413cb9ada76bcb/benchmarks/Python

/cc @timfel

**Comment by MartinBalin** [comment]
This issue is being solved and it is harder as it is broken on BGV generation side.

**Comment by Ondrej-Douda** [comment]
It seems that there is failure in type resolution of dumped data and/or data pool mismatch during dump generation, this creates a couple of similar problems, currently investigating (don't have functioning reproduction case)...
@smarr Your reproduction case didn't made graphs with such error or at least it worked for me with GVM EE 21.1.0 version.
Did you try newest GVM and could you perhaps include more details..?

**Comment by smarr** [comment]
I am working with CE, not EE. For the GraalPython case, I just went to https://github.com/oracle/graalpython/releases to download a release. So, the 21.1.0 one.

I could probably put a script together if need be.

To get the mentioned benchmarks, it should be something like:

```
git clone https://github.com/smarr/are-we-fast-yet.git awfy
cd awfy
git checkout 932b44ec0a5f004454720a2069413cb9ada76bcb
cd benchmarks/Python
graalpython --vm.Xss2m --vm.Dgraal.Dump=Truffle,TruffleTree:2 harness.py Permute 2000 1000
```

(untested)

**Comment by tkrodriguez** [comment]
A fix for this should land in the next day or so.  The graph protocol maintains a limited cache of data elements that have been sent over the wire and it uses a LinkedHashMap to maintain the cache.  If you insert a collection into a map and then mutate the collection you can no longer find or delete that entry.   This causes our cache to go haywire because when that entry becomes the oldest slot it stays around since we can't delete it.  So from then on every new pool entry uses the same cache id, which unsurprisingly breaks the decoder.  It only happens for larger graphs which are more likely to fill the cache.

**Comment by smarr** [comment]
Ha. A classic.

Thanks!

**Comment by tkrodriguez** [comment]
This should be fixed by https://github.com/oracle/graal/commit/9cb8cf2b2e1930b99f3c53220203b638a63fd0b7

**Comment by smarr** [comment]
@tkrodriguez thanks, I am just trying it now.
Though, doesn't look too promising.

https://github.com/oracle/graal/blob/master/compiler/src/org.graalvm.graphio/src/org/graalvm/graphio/GraphProtocol.java#L906 trips the assertion.

Patching it to:

```Java
assert key.toString().equals(value) : "Key (" + key.toString() + ") should match value (" + value + ")";
```

outputs: `AssertionError: Key (a -) should match value (a java.lang.Object)`

```
    [thread:14] scope: TruffleCompilerThread-14.Truffle.CreateGraph
    Context: StructuredGraph:8{Vector_class>>#new:, HotSpotMethod<OptimizedCallTarget.profiledPERoot(Object[])>}
      [thread:14] scope: TruffleCompilerThread-14.Truffle.CreateGraph.AgnosticInliningPhase
      Exception raised in scope TruffleCompilerThread-14.Truffle.CreateGraph.AgnosticInliningPhase: java.lang.AssertionError: Key (a -) should match value (a java.lang.Object)
      	at org.graalvm.graphio.GraphProtocol$ConstantPool.get(GraphProtocol.java:906)
      	at org.graalvm.graphio.GraphProtocol.writePoolObject(GraphProtocol.java:479)
      	at org.graalvm.graphio.GraphProtocol.writePropertyObject(GraphProtocol.java:836)
      	at org.graalvm.graphio.GraphProtocol.writeProperties(GraphProtocol.java:865)
      	at org.graalvm.graphio.GraphProtocol.writeNodes(GraphProtocol.java:555)
      	at org.graalvm.graphio.GraphProtocol.writeGraph(GraphProtocol.java:538)
      	at org.graalvm.graphio.GraphProtocol.writePropertyObject(GraphProtocol.java:839)
      	at org.graalvm.graphio.GraphProtocol.writeProperties(GraphProtocol.java:865)
      	at org.graalvm.graphio.GraphProtocol.writeNodes(GraphProtocol.java:555)
      	at org.graalvm.graphio.GraphProtocol.writeGraph(GraphProtocol.java:538)
      	at org.graalvm.graphio.GraphProtocol.print(GraphProtocol.java:138)
      	at org.graalvm.graphio.GraphOutput.print(GraphOutput.java:100)
      	at org.graalvm.compiler.printer.BinaryGraphPrinter.print(BinaryGraphPrinter.java:318)
      	at org.graalvm.compiler.printer.GraphPrinterDumpHandler.dump(GraphPrinterDumpHandler.java:200)
      	at org.graalvm.compiler.debug.ScopeImpl.dump(ScopeImpl.java:223)
      	at org.graalvm.compiler.debug.DebugContext.dump(DebugContext.java:1363)
      	at org.graalvm.compiler.truffle.compiler.phases.inlining.CallTree.dumpBasic(CallTree.java:109)
      	at org.graalvm.compiler.truffle.compiler.phases.inlining.AgnosticInliningPhase.run(AgnosticInliningPhase.java:82)
      	at org.graalvm.compiler.truffle.compiler.phases.inlining.AgnosticInliningPhase.run(AgnosticInliningPhase.java:38)
      	at org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:212)
      	at org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:147)
      	at org.graalvm.compiler.truffle.compiler.PartialEvaluator.inliningGraphPE(PartialEvaluator.java:646)
      	at org.graalvm.compiler.truffle.compiler.PartialEvaluator.evaluate(PartialEvaluator.java:348)
      	at org.graalvm.compiler.truffle.compiler.TruffleCompilerImpl.compileAST(TruffleCompilerImpl.java:508)
```

I'll try to investigate further.

**Comment by smarr** [comment]
Looks to me like the `ObjectStamp` objects have issues with `hashCode`/`equals` when the `type` is not set vs is set.

So, here two stamps that clash (also appropriately that's the `stamp` property that is to be serialized):

<img width="469" alt="Screen Shot 2021-06-14 at 15 27 48" src="https://user-images.githubusercontent.com/40815/121908925-58aaba80-cd25-11eb-88de-96420cdf2f63.png">


<img width="436" alt="Screen Shot 2021-06-14 at 15 27 04" src="https://user-images.githubusercontent.com/40815/121908940-5ea09b80-cd25-11eb-8f75-d2bcbf0c35d3.png">

**Comment by smarr** [comment]
Looks to me like this might even be on purpose, but causes issues here.

https://github.com/oracle/graal/blob/master/compiler/src/org.graalvm.compiler.core.common/src/org/graalvm/compiler/core/common/type/AbstractObjectStamp.java#L371-L382

```Java
        // null == java.lang.Object
        if (type == null) {
            if (other.type != null && !other.type.isJavaLangObject()) {
                return false;
            }
        } else if (other.type == null) {
            if (type != null && !type.isJavaLangObject()) {
                return false;
            }
        } else if (!type.equals(other.type)) {
            return false;
        }
```

**Comment by tkrodriguez** [comment]
Yes, we've got a fix in progress for this.  It's a weird inconsistency I'd missed.  Previously we'd just silently pick one toString form or the other and use it for both objects.  And our gate got the assertion failure but wasn't detected as an error because it buried in the dumping.

**Comment by smarr** [comment]
I guess removing the assertion here is the final fix https://github.com/oracle/graal/commit/368d23fcc5f5fc3b77c1c879a31f81010262eeb9

I can confirm that IGV now loads the graphs, I previously had issues with.

Thanks a lot!

**Comment by tkrodriguez** [comment]
Removal of the assert puts things back to where they were in regards to slightly incorrect strings for a small number of Objects.  There is a follow on fix to resolve that but that only affects the output for the inlining graphs in a minor way.
