### ISSUE TITLE
Links to documentation in README are broken

### ISSUE THREAD

**Issue by tuleism** [oracle/graal#339]
>A comprehensive GraalVM documentation can be found on the website.

1. The website (graalvm.org) is having issue with certificate:

>This server could not prove that it is graalvm.org; its security certificate is from *.github.com. This may be caused by a misconfiguration or an attacker intercepting your connection.

2. Links to section, e.g *Getting Started* don't exist: https://github.com/oracle/graal/blob/master/docs/docs/getting-started

**Comment by thomaswue** [comment]
Thanks for the report! It should be fixed now. Also the issue with the SSL certificate. The GitHub pages SSL support is very new and it seems to not work when linking without a "www." as the URL prefix. Please reopen the issue if there is still a problem.
