### ISSUE TITLE
RSS Memory Utilization was high with GraalVM CE Edition - java11-21.0.0

### ISSUE THREAD

**Issue by dinesh-nithyanandam** [oracle/graal#3396]
Hi Team,

RSS Memory utilisation was very high  constantly (~80 to 90% all the time )across all the micro services deployed with GraalVM CE Edition 

Version - **GraalVM CE java11-21.0.0**

Garbage collection pauses also very dominant across the runtime, below were the JVM options being used - 

`-XX:+UseParallelOldGC -XX:+UseParallelGC -Xms1g -Xmx1g -XX:+AlwaysPreTouch -XX:ParallelGCThreads=4 -XX:MaxGCPauseMillis=100 -XX:GCTimeRatio=19 -Xss512k -XX:+UseAdaptiveSizePolicy -XX:+ResizePLAB -XX:+ResizeTLAB
`

Can someone please shed some light here on whether I am using the right parameter

**Comment by mcraj017** [comment]
@dinesh-nithyanandam please try the latest version 21.1.0
https://github.com/graalvm/graalvm-ce-builds/releases/tag/vm-21.1.0
And provide some context or a reproducer for this issue

**Comment by mcraj017** [comment]
Closing this issue as there is no response from the user in the last 30 days
Please reopen, if you still required any assistance
