### ISSUE TITLE
Linux debuginfo abbrev section does not include terminating null abbreviation

### ISSUE THREAD

**Issue by adinn** [oracle/graal#3428]
The .debug_abbrev section in generated Linux debuginfo should include of a sequence of abbrev records terminated with an empty abbrev record, the latter consisting of a single 0 tag with no trailing list of tag+form pairs. The current code omits this terminating record. As a result subsequent abbrev records belonging to non-Java compile units may be included in the abbreviation table for compiled Java code. This has the potential to redefine the record layout for Java abbrev records info, leading to consequent misinterpretation of associated info records. An error has not so far manifested with gdb versions 8, 9 and 10 but it shows up with early builds of gdb 11.

**Steps to reproduce the issue**
Build a native image with '-g' and try to debug it with gdb 11. gdb will usually fail while reading the debug info and hence will report no debug symbols in the binary.

**Describe GraalVM and your environment:**
Current graal head, jdk11, Linux, gdb 11

**Comment by mcraj017** [comment]
@dougxc please advise

**Comment by olpaw** [comment]
The fix for this issue is already on master. See https://github.com/oracle/graal/pull/3429
