### ISSUE TITLE
native-image (built from latest HEAD) not respecting `-J-Xmx`

### ISSUE THREAD

**Issue by zakkak** [oracle/graal#3437]
**Describe the issue**
`native-image` appears to no longer respect `-J-Xmx`, this used to work in 21.1.0.

**Steps to reproduce the issue**

1. Build `native-image` from source using:
```
mx --primary-suite-path substratevm --native=native-image --components='Native Image' build
```

2. Compare 21.1.0 behavior with freshly built 21.2.0-dev
```
/opt/jvms/graalvm-ce-java11-21.1.0/bin/native-image HelloWorld
...
[helloworld:1471847]      [total]:  32,831.18 ms,  2.36 GB

/opt/jvms/graalvm-ce-java11-21.1.0/bin/native-image -J-Xmx2g HelloWorld
...
[helloworld:1472430]      [total]:  44,002.89 ms,  1.21 GB

$(mx --primary-suite-path substratevm --native=native-image --components='Native Image' graalvm-home)/bin/native-image HelloWorld
...
[helloworld:1470629]      [total]:  34,848.34 ms,  3.29 GB

$(mx --primary-suite-path substratevm --native=native-image --components='Native Image' graalvm-home)/bin/native-image -J-Xmx2g HelloWorld
...
[helloworld:1472626]      [total]:  46,982.46 ms,  3.30 GB
```

**Describe GraalVM and your environment:**
 - GraalVM version: **e279970ab8ff7ce76c7be938e47a0f2ab2e4c68e**
 - JDK major version: **11**
 - OS: **Fedora 34**
 - Architecture: **AMD64**

**Comment by olpaw** [comment]
I will have a look. @zakkak thanks for reporting!

**Comment by zakkak** [comment]
Thanks Paul.

Note: It's reproducible with https://github.com/graalvm/graalvm-ce-dev-builds/releases/tag/21.2.0-dev-20210519_2024 as well.

```$ /opt/jvms/graalvm-ce-java11-21.2.0-dev/bin/native-image -J-Xmx2g HelloWorld 
...
[helloworld:1477682]      [total]:  40,581.06 ms,  3.28 GB
```

**Comment by zakkak** [comment]
Thanks for the fix Paul.
