### ISSUE TITLE
native-image: allow to use regular expressions in config JSON files

### ISSUE THREAD

**Issue by JnRouvignac** [oracle/graal#3439]
**Feature request**

To configure Graal native image, we have similar lines like the `com.company.*` lines repeated 200+ times in JSON files:
```
// reflect-config.json
[
...
{
  "name":"javax.security.auth.x500.X500Principal",
  "fields":[{"name":"thisX500Name"}],
  "methods":[{"name":"<init>","parameterTypes":["sun.security.x509.X500Name"] }]
},
...
{
  "name":"com.company.DbComponentCfgDefn",
  "methods":[{"name":"getInstance","parameterTypes":[] }]
},
{
  "name":"com.company.LoggingComponentCfgDefn",
  "methods":[{"name":"getInstance","parameterTypes":[] }]
},
{
  "name":"com.company.MetricsComponentCfgDefn",
  "methods":[{"name":"getInstance","parameterTypes":[] }]
},
...
{
  "name":"sun.misc.Unsafe"
},
]
```

```
// resource-config.json
{
  "resources":{
    "includes":[
      {"pattern":...},
      ...
    ]},
  "bundles":[
    {"name":"com.company.DbComponentCfgDefn"},
    {"name":"com.company.LoggingComponentCfgDefn"},
    {"name":"com.company.MetricsComponentCfgDefn"},
    ...
}
```

That's a lot of lines nobody wants to read, see or maintain.
Furthermore, adding new components requires us to add a line (twice).

**Describe the solution you'd like.**

It would be more readable (less lines of code) and more maintainable (nothing to change when a new component is added) if these configuration files supported glob or regular expression patterns.

It's interesting to note that `resource-config.json` supports include patterns for the `"resources"` section, but not for the `"bundles"` section.

**Describe who do you think will benefit the most.**
GraalVM native-image users.

**Describe alternatives you've considered.**

A workaround may be to use code generation, that would work for these 200+ lines, but not for the rest of the lines which are fairly static but then you also need to include more static content like JDK, library classes, etc. (as described in the example above).

It seems to me it may be possible to generate a [`Feature`](https://www.graalvm.org/sdk/javadoc/index.html?org/graalvm/nativeimage/hosted/Feature.html) and compiling it statically with the [`native-image --features`](https://www.graalvm.org/reference-manual/native-image/Reflection/). But it is unclear whether this would solve both problems above, and it is more work from the user anyway.

**Additional context.**
n/a

**Express whether you'd like to help contributing this feature**
n/a

**Comment by vjovanov** [comment]
I agree this would improve usability, however, I have two concerns: 
1) The wildcards will make it easy for people to accidentally include elements that are not needed, thus, making larger binaries. 
2) The wildcards would require us to scan all the jars in Native Image, which we do now but want to remove.

I don't see a way around these two problems.

**Comment by christianwimmer** [comment]
@JnRouvignac the easiest for you might to write a `Feature` that does the reflection registration programmatically. You can do classpath scanning yourself if you need to. Or if you know a certain naming pattern of the classes, you might be even able to avoid that and look up all the individual classes by their constructed name.

**Comment by JnRouvignac** [comment]
Thanks for you feedback, I know what to expect now.
I will try to go with the `Feature` solution when I get a chance.
