### ISSUE TITLE
[interop] `isMetaInstance` true for interop `null` values when host meta-object is passed in

### ISSUE THREAD

**Issue by fniephaus** [oracle/graal#3441]
**Describe GraalVM and your environment :**
 - GraalVM version or commit id if built from source: 21.1.0
 - CE or EE: CE
 - JDK version: JDK11
 - OS and OS Version: macOS Big Sur
 - Architecture: amd64

According to [this line](https://github.com/oracle/graal/blob/f99631396f42d8f1b8850cf5efc34f136cdef8ff/truffle/src/com.oracle.truffle.polyglot/src/com/oracle/truffle/polyglot/ToHostNode.java#L290), interop `null` values can always be converted to non-primitive target types. As a result, `isMetaInstance` always returns true for Ruby's `nil` and for all host types, even though it's not an instance of any of them.

#### Repro session
```
$ polyglot --shell --jvm
GraalVM MultiLanguage Shell 21.1.0
Copyright (c) 2013-2020, Oracle and/or its affiliates
  Java version 1.8|11
  JavaScript version 21.1.0
  Python version 3.8.5
  R version 3.6.1
  Ruby version 2.7.2
  Squeak/Smalltalk version 21.2.0-dev
...
java> ruby>
ruby> Truffle::Interop.meta_instance?(Java.type('java.lang.System'), 42)
false
ruby> Truffle::Interop.meta_instance?(Java.type('java.lang.System'), nil)
true
ruby> Truffle::Interop.meta_instance?(Java.type('java.lang.Integer'), nil)
true
```

Java `null` is never an instance of a class:

```
$ jshell
|  Welcome to JShell -- Version 11.0.11
|  For an introduction type: /help intro

jshell> null instanceof java.lang.System
$1 ==> false

jshell> null instanceof Integer
$2 ==> false
```

Please assign to @chumer. /cc @eregon @janehmueller

**Comment by chumer** [comment]
Thanks for the report. 

Here is a quick fix if you are blocked by this:
{code}
@ExportMessage
    @TruffleBoundary
    boolean isMetaInstance(Object other,
                    @Shared("error") @Cached BranchProfile error) throws UnsupportedMessageException {
        if (isClass()) {
            Class<?> c = asClass();
            if (HostObject.isInstance(other)) {
                Object otherHostObj = HostObject.valueOf(other);
                if (otherHostObj == null) {
                    return false;
                } else {
                    return c.isInstance(otherHostObj);
                }
            } else if (PolyglotProxy.isProxyGuestObject(other)) {
                PolyglotProxy otherHost = (PolyglotProxy) other;
                return c.isInstance(otherHost.proxy);
            } else {
                InteropLibrary library = InteropLibrary.getFactory().getUncached(other);
                if (library.isNull(other)) {
                    return false;
                } else {
                    boolean canConvert = ToHostNode.canConvert(other, c, c,
                                    ToHostNode.allowsImplementation(context, c),
                                    context, ToHostNode.LOWEST,
                                    library,
                                    TargetMappingNode.getUncached());
                    return canConvert;
                }
            }
        } else {
            error.enter();
            throw UnsupportedMessageException.create();
        }
    }
{code}

**Comment by fniephaus** [comment]
Thanks, @chumer!
