### ISSUE TITLE
"GraalVM Gate" CI workflow fails with "bugs found"

### ISSUE THREAD

**Issue by zakkak** [oracle/graal#3442]
**Describe the issue**

"GraalVM Gate" CI workflow fails with "bugs found":
```
H C NP: Null passed for non-null parameter of org.graalvm.compiler.truffle.compiler.TruffleCompilerImpl.doCompile(TruffleDebugContext, TruffleCompilation, Map, TruffleCompilationTask, TruffleCompilerListener) in org.graalvm.compiler.truffle.compiler.hotspot.libgraal.TruffleToLibGraalEntryPoints.doCompile(JNI$JNIEnv, JNI$JClass, long, long, long, long, JNI$JByteArray, JNI$JObject, JNI$JObject)  Method invoked at TruffleToLibGraalEntryPoints.java:[line 259]
FindBugs warnings were found
```

See https://github.com/oracle/graal/runs/2721025476?check_suite_focus=true#step:9:1643 for more details

First failure observed in https://github.com/oracle/graal/actions/runs/878635217 (@ https://github.com/oracle/graal/commit/15679bdc4d74f92a5872b6ab46e010902b332aba )
Last success was observed in https://github.com/oracle/graal/actions/runs/878297693 (@ https://github.com/oracle/graal/commit/2b3fc59e72e18b9d1bc01ce6abbab2a51d0db8ac )

So the issue should be caused by a change between https://github.com/oracle/graal/commit/2b3fc59e72e18b9d1bc01ce6abbab2a51d0db8ac and https://github.com/oracle/graal/commit/15679bdc4d74f92a5872b6ab46e010902b332aba.

**Comment by dougxc** [comment]
I think @olpaw has a fix for this that is in the process of being merged.

**Comment by zakkak** [comment]
Fixed by https://github.com/oracle/graal/commit/bd34f5a08d476c909a42c7b2b860f85573a088a9

Thanks Paul.
