### ISSUE TITLE
Frames not working in JavaDoc

### ISSUE THREAD

**Issue by arthurp** [oracle/graal#345]
The Java docs at http://www.graalvm.org/truffle/javadoc are mildly broken in that the "Frames" link does not work to turn on the side bar.

To reproduce go to http://www.graalvm.org/truffle/javadoc/org/graalvm/polyglot/package-summary.html and then click "Frames" in the header. I would expect it to open the side bar, but instead it jumps back to the top-level index and stays in "No Frames" mode.

**Comment by chumer** [comment]
Are you using the frames view a lot? But yeah we will fix.

**Comment by chumer** [comment]
This link still works:
http://www.graalvm.org/truffle/javadoc/overview-frames.html

**Comment by arthurp** [comment]
Thanks for the work around. I use the frames view almost exclusively since it allows me to hop between classes quickly and use text search to find classes by name without switching pages.

**Comment by chumer** [comment]
I recently switched the default view to non-frames. I thought it to be less intimidating if you see a list of packages first.  We also had some discussions to switch to doxygen for all APIS. To have a place for native apis as well.

**Comment by boris-spas** [comment]
Should fixed now.
