### ISSUE TITLE
native-image fails with an error yet returns an exit code indicating success

### ISSUE THREAD

**Issue by phdoerfler** [oracle/graal#3451]
## Description
Please see this issue for a complete description including GraalVM version and console output: https://github.com/scalameta/sbt-native-image/issues/29

In short: `native-image` fails with an error yet returns an exit code indicating success:

```
Default native-compiler executable 'cl.exe' not found via environment variable PATH
```

## More details
```
Installing new component: Native Image (org.graalvm.native-image, version 20.2.0)
[info] C:\Users\fearis\AppData\Local\Coursier\cache\jvm\graalvm-java11@20.2.0\bin\native-image.cmd -cp C:\Users\fearis\Documents\workspace\CloseProcess\target\scala-2.13\classes;C:\Users\fearis\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\org\scala-lang\scala-library\2.13.5\scala-library-2.13.5.jar;C:\Users\fearis\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\org\scalameta\svm-subs\101.0.0\svm-subs-101.0.0.jar io.doerfler.ReaperMain C:\Users\fearis\Documents\workspace\CloseProcess\target\native-image\closeprocess
[C:\Users\fearis\Documents\workspace\CloseProcess\target\native-image\closeprocess:3360]    classlist:   2,269.72 ms,  0.96 GB
[C:\Users\fearis\Documents\workspace\CloseProcess\target\native-image\closeprocess:3360]        setup:     506.26 ms,  0.96 GB
Error: Default native-compiler executable 'cl.exe' not found via environment variable PATH
Error: To prevent native-toolchain checking provide command-line option -H:-CheckToolchain
Error: Use -H:+ReportExceptionStackTraces to print stacktrace of underlying exception
Error: Image build request failed with exit status 1
[info] Native image ready!
[info] C:\Users\fearis\Documents\workspace\CloseProcess\target\native-image\closeprocess
```

![](https://user-images.githubusercontent.com/163428/117266162-3fc10680-ae55-11eb-9d38-252950feae83.png)

## Remarks

Apologies for the brevity of this bug report, I'm very much pressed for time at the moment. Feel free to @ me if you require more information, thank you!

**Comment by mcraj017** [comment]
@phdoerfler Please use x64 Native Tools Command Prompt to run native-image in windows.
follow the windows section in the below link
https://www.graalvm.org/reference-manual/native-image/

**Comment by phdoerfler** [comment]
@mcraj017 thanks for the link. However, I believe there is a misunderstanding! **This issue is not about „how do I make it work“** but about that native-image returns an exit code indicating success rather than failure.
This makes it harder for other tools that are using native-image to detect whether it succeeded. Please consider reopening the issue.

**Comment by mcraj017** [comment]
@phdoerfler thanks for pointing out that, I will raise a bug internally to correct this message

**Comment by mcraj017** [comment]
@phdoerfler When I am tried native-image it doesn't show success 
```
native-image HelloWorld
[helloworld:10316]    classlist:     930.52 ms,  0.96 GB
[helloworld:10316]        setup:   1,152.66 ms,  0.96 GB
Error: Default native-compiler executable 'cl.exe' not found via environment variable PATH
Error: To prevent native-toolchain checking provide command-line option -H:-CheckToolchain
Error: Use -H:+ReportExceptionStackTraces to print stacktrace of underlying exception
Error: Image build request failed with exit status 1
```

**Comment by mcraj017** [comment]
@phdoerfler When I tired this with HelloWorld.java, I don't see any success message:
```
native-image HelloWorld
[helloworld:10316]    classlist:     930.52 ms,  0.96 GB
[helloworld:10316]        setup:   1,152.66 ms,  0.96 GB
Error: Default native-compiler executable 'cl.exe' not found via environment variable PATH
Error: To prevent native-toolchain checking provide command-line option -H:-CheckToolchain
Error: Use -H:+ReportExceptionStackTraces to print stacktrace of underlying exception
Error: Image build request failed with exit status 1
```

**Comment by mcraj017** [comment]
@phdoerfler please provide the reproducer, so that we can check it further

**Comment by phdoerfler** [comment]
@mcraj017 Curious! I’ll try to get to that by tomorrow evening. In the meantime: @olafurpg any thoughts on this?

**Comment by phdoerfler** [comment]
@mcraj017 I just now realized that your question was about the "success message": It comes from [sbt](https://www.scala-sbt.org/), a build tool not unlike maven and the [sbt-native-image](https://github.com/scalameta/sbt-native-image) plugin specifically. It runs `native-image`, checks its exit code ([here](https://github.com/scalameta/sbt-native-image/blob/main/plugin/src/main/scala/sbtnativeimage/NativeImagePlugin.scala#L236) and [here](https://github.com/scalameta/sbt-native-image/blob/main/plugin/src/main/scala/sbtnativeimage/NativeImagePlugin.scala#L278)) and reports this back to sbt which then in turn prints `success` or details about the failure to the console.
However, in this case it apparently still reports a `0` (which traditionally indicates that everything went well) since these two checks don't fail.

Does this help?

**Comment by olafurpg** [comment]
@phdoerfler To minimize this issue, what happens if you run native-image command directly? The full command is printed in the logs from `sbt nativeImage`, from your example above it's
```
C:\Users\fearis\AppData\Local\Coursier\cache\jvm\graalvm-java11@20.2.0\bin\native-image.cmd -cp C:\Users\fearis\Documents\workspace\CloseProcess\target\scala-2.13\classes;C:\Users\fearis\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\org\scala-lang\scala-library\2.13.5\scala-library-2.13.5.jar;C:\Users\fearis\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\org\scalameta\svm-subs\101.0.0\svm-subs-101.0.0.jar io.doerfler.ReaperMain C:\Users\fearis\Documents\workspace\CloseProcess\target\native-image\closeprocess
```

If the exit code is 0 for that command, you can confirm this issue is unrelated to sbt-native-image.

**Comment by phdoerfler** [comment]
@olafurpg I'm not sure when I'll next have access to my Windows machine again to try this. Probably some time next week.

**Comment by mcraj017** [comment]
@phdoerfler did you get any chance to check the exit code?

**Comment by phdoerfler** [comment]
@mcraj017 Not yet, unfortunately. Later this week I should have both access and time again.

**Comment by mcraj017** [comment]
@phdoerfler any progress?

**Comment by phdoerfler** [comment]
@mcraj017 Not yet, I'm afraid. In the meantime if you have access to a Windows machine: I'm normally avoiding the Windows shells like the plague but supposedly this is how you get the exit code:

## cmd.exe

```
echo %errorlevel%
```

## Powershell

```
$LastExitCode
```

Running that after this…

> ```
> native-image HelloWorld
> [helloworld:10316]    classlist:     930.52 ms,  0.96 GB
> [helloworld:10316]        setup:   1,152.66 ms,  0.96 GB
> Error: Default native-compiler executable 'cl.exe' not found via environment variable PATH
> Error: To prevent native-toolchain checking provide command-line option -H:-CheckToolchain
> Error: Use -H:+ReportExceptionStackTraces to print stacktrace of underlying exception
> Error: Image build request failed with exit status 1
> ```

… would in essence be what I'll be doing once time and physical location allow for it. So if you want to go ahead and give this a try we'd know how native-image behaves in isolation and I can some time later check how it behaves with the full command posted by @olafurpg if still necessary.

**Comment by mcraj017** [comment]
@phdoerfler I tired your suggestion:
```
github\3451>native-image HelloWorld      
[helloworld:17888]    classlist:     854.42 ms,  0.96 GB
[helloworld:17888]        setup:   3,168.87 ms,  0.96 GB
Error: Default native-compiler executable 'cl.exe' not found via environment variable PATH
Error: To prevent native-toolchain checking provide command-line option -H:-CheckToolchain
Error: Use -H:+ReportExceptionStackTraces to print stacktrace of underlying exception     
Error: Image build request failed with exit status 1

github\3451>echo %errorlevel%
1
```

**Comment by mcraj017** [comment]
@phdoerfler do you still need any assistance from our side?

**Comment by phdoerfler** [comment]
@mcraj017 thanks for the heads up! We can close this issue until I find the time to give this a try on my machine.
