### ISSUE TITLE
install graal on mac: "graalvm-ce-java11-21.1.0" is damaged and can't be opened

### ISSUE THREAD

**Issue by paulvi** [oracle/graal#3454]
also on https://stackoverflow.com/questions/67904532/graalvm-on-macos-catalina

I have just downloaded and manually install GraalVM on MacOS Catalina as said on https://www.graalvm.org/docs/getting-started/macos/ :

download  
unzip 
 
     sudo mv graalvm-ce-java11-21.1.0 /Library/Java/JavaVirtualMachines

```
/usr/libexec/java_home -V
Matching Java Virtual Machines (3):
    11.0.11, x86_64:	"GraalVM CE 21.1.0"	/Library/Java/JavaVirtualMachines/graalvm-ce-java11-21.1.0/Contents/Home
```

configuer in `.zshenv` :

    export GRAALVM_HOME=/Library/Java/JavaVirtualMachines/graalvm-ce-java11-21.1.0/Contents/Home
    export JAVA11_HOME=/Library/Java/JavaVirtualMachines/amazon-corretto-11.jdk/Contents/Home
    export JAVA8_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_281.jdk/Contents/Home
    export JAVA_HOME=$JAVA11_HOME
    export MAVEN_HOME=/opt/apache-maven-3.6.3
    export PATH=$PATH:$GRAALVM_HOME/bin
    export PATH=$PATH:$JAVA_HOME/bin:$MAVEN_HOME/bin

```
ls $GRAALVM_HOME/bin
gu		javadoc		jdeprscan	jinfo		jps		jstat		pack200		serialver
jar		javap		jdeps		jjs		jrunscript	jstatd		polyglot	unpack200
jarsigner	jcmd		jfr		jlink		js		jvisualvm	rmic
java		jconsole	jhsdb		jmap		jshell		keytool		rmid
javac		jdb		jimage		jmod		jstack		lli		rmiregistry
```

However when I try to run `gu`, `javac` or anything from GRAALVM_HOME, I get MacOS warning

> "graalvm-ce-java11-21.1.0" is damaged and can't be opened

![][1]

 `sudo xattr -r -d com.apple.quarantine $GRAALVM_HOME` as suggested in https://www.graalvm.org/docs/getting-started/macos/ notes does not help.

How to setup/fix GraalVM on Mac ?

  [1]: https://i.stack.imgur.com/nqI4w.png

**Describe the issue**
See above

**Steps to reproduce the issue**
See above

**Describe GraalVM and your environment:**
 - GraalVM version graalvm-ce-java11-21.1.0
 - JDK major version: not yet used
 - OS: **macOS Catalina**
 - Architecture: **AMD64**

**Comment by mcraj017** [comment]
@paulvi thanks for reporting the issue, we will check and get back to you

**Comment by mcraj017** [comment]
@paulvi Download from here 
https://github.com/graalvm/graalvm-ce-builds/releases/tag/vm-21.1.0 and try
sudo xattr -r -d com.apple.quarantine <path to graalvm folder>  instead of $GRAALVM_HOME

**Comment by mcraj017** [comment]
@paulvi as I see you are setting amazon-corretto-11.jdk
can you please share the output of the following commands:
```
$which java
$java -version
```

**Comment by paulvi** [comment]
Possibly MacOS operation for double click on .gz file produces output different to using `tar -xzf` command

So I did this, and got usable binaries

```
Downloads % tar -xzf graalvm-ce-java11-darwin-amd64-21.1.0.tar.gz 
Downloads % sudo xattr -r -d com.apple.quarantine ./graalvm-ce-java11-21.1.0/*
```

```
bin % pwd
/Library/Java/JavaVirtualMachines/graalvm-ce-java11-21.1.0/Contents/Home/bin
bin % ./javac --version
javac 11.0.11 <- this is from GraalVM
bin % javac -version
javac 11.0.10 <- this is from Corretto
(base) paul.verest@C02DQHXPMD6M bin % 
```

@mcraj017 for second comment `which java` is useless
as it says `/usr/bin/java`

I use JAVA_HOME env var to define what Java to use as default.
And I can use any other defined:
```
$GRAALVM_HOME/bin/javac --version
javac 11.0.11
```

--

For this issue to close, I think documentation at https://www.graalvm.org/docs/getting-started/macos/ should 
add step `2b)`

> If you are using macOS Catalina and later you may need to remove the quarantine attribute from the bits before you can use them
To do this, run the following:

> `sudo xattr -r -d com.apple.quarantine path/to/graalvm/folder/`

as actually in https://github.com/graalvm/graalvm-ce-builds/releases/tag/vm-21.1.0 note

that is before moving into /Library/Java/JavaVirtualMachines/

**Comment by mcraj017** [comment]
@paulvi if you scroll down a bit more in https://www.graalvm.org/docs/getting-started/macos/
you will see this in installation notes

**Comment by paulvi** [comment]
Exactly, it is written as after note, while most people read and do it step by step

**Comment by mcraj017** [comment]
@paulvi ok sure, I will check with documentation team and let you know

**Comment by olyagpl** [comment]
The macOS install steps were updated with a notification: https://www.graalvm.org/docs/getting-started/macos/#installation-on-macos-platforms.
Thanks for the feedback.

**Comment by paulvi** [comment]
Thanks

> Note: If you are using macOS Catalina and later you may need to remove the quarantine attribute. See Installation Notes below.

I bet nobody will run into same error from now.

**Comment by connorsadlervelo** [comment]
For anyone else reading this, the crucial difference is that GRAALVM_HOME includes the "/Contents/Home" suffix
BUT
when you run the xattr command you must NOT include that "/Contents/Home" suffix
If you do include it by accident, you'll get the "corrupt" error message when you try to run java

**Comment by olyagpl** [comment]
We updated the guide to use `sudo xattr -r -d com.apple.quarantine /path/to/graalvm`. Thanks @connorsadlervelo!

**Comment by erickok** [comment]
@olyagpl The install notes in https://www.graalvm.org/22.1/docs/getting-started/macos/#installation-notes still refer to `/path/to/GRAALVM_HOME` which is confusing (to me). Perhaps update this as well? Just a tiny tip.

**Comment by shubham-damkondwar** [comment]
> For anyone else reading this, the crucial difference is that GRAALVM_HOME includes the "/Contents/Home" suffix BUT when you run the xattr command you must NOT include that "/Contents/Home" suffix If you do include it by accident, you'll get the "corrupt" error message when you try to run java

This really helped.

**Comment by mcalisterkm** [comment]
I ran into this exact problem, having skipped the "sudo xattr …." step.
So for an apple arm64 architecture the steps are (assuming you are in "Downloads" at a zsh prompt):

a) We need to start again, so remove using finder the folder "\Library\Java\JavaVirtualMachines\graalvm-jdk-21.0.1+12.1"
If you have graalvm-jdk-21_macos-aarch64_bin.tar.gz in "Downloads", then fine otherwise get it back from bin or re-download.

b) Start a terminal window and run 

```
% sudo xattr -r -d com.apple.qaurantine graalvm-jdk-21_macos-aarch64_bin.tar.gz
% tar -xzf  graalvm-jdk-21_macos-aarch64_bin.tar.gz
```

This produces a "Downloads" folder "graalvm-jdk-21.0.1+12.1"

c) Open two finder windows one in "Downloads" and the other in \Library\Java\JavaVirtualMachines.
The finder showing "JavaVirtual Machines" will show a sub-folder for each version of java you previously installed.
Move "graalvm-jdk-21.0.1+12.1" by drag and drop  to the JavaVirtual Machines finder window .

d) Run

```
% java -version
java version "21.0.1" 2023-10-17
```

e) To list out the envs run 

```
% /usr/libexec/java_home -V
Matching Java Virtual Machines (4):
    21.0.1 (arm64) "Oracle Corporation" - "Oracle GraalVM 21.0.1+12.1" /Library/Java/JavaVirtualMachines/graalvm-jdk-21.0.1+12.1/Contents/Home
    17.0.9 (arm64) "Azul Systems, Inc." - "Zulu 17.46.19" /Library/Java/JavaVirtualMachines/zulu-17.jdk/Contents/Home
    11.0.21 (arm64) "Azul Systems, Inc." - "Zulu 11.68.17" /Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home
    1.8.0_392 (arm64) "Azul Systems, Inc." - "Zulu 8.74.0.17" /Library/Java/JavaVirtualMachines/zulu-8.jdk/Contents/Home
/Library/Java/JavaVirtualMachines/graalvm-jdk-21.0.1+12.1/Contents/Home
```
