### ISSUE TITLE
Improve `-H:+TraceSecurityServices` to list Security Services/Providers removed by recent change that filters out "unused" security providers

### ISSUE THREAD

**Issue by zakkak** [oracle/graal#3457]
**Feature request**

Improve `-H:+TraceSecurityServices` to list Security Services/Providers removed by https://github.com/oracle/graal/commit/10cc640cd8d5878b0c91f66ec908771357807adf.

**Is your feature request related to a problem? Please describe.**

At the moment (3061677b82f3a44d7580db187d6bc08f05f7d24a), `-H:+TraceSecurityServices` reports the reachable providers but provides no info regarding those that are being filtered out making hard to understand what providers one might need to explicitly add in order to make an application work (see https://github.com/quarkusio/quarkus/pull/17774#issuecomment-857878631 for instance).

**Describe the solution you'd like.**
I would like to see a mark/annotation next to providers that end up being filtered out, or a separate list with the filtered out providers (probably easier to implement).

**Describe who do you think will benefit the most.**
GraalVM users, GraalVM contributors, developers of libraries and frameworks which depend on GraalVM.

**Express whether you'd like to help contributing this feature**
If needed, I am willing to help contributing this feature.

cc @gradinac

**Comment by gradinac** [comment]
Hey @zakkak!
In cases where the security services feature has been disabled, all providers are by default filtered out. However, I agree with you, it would be useful to see exactly which providers got removed.
I propose that we print a list of removed providers' class names after analysis, once the provider caches have the final value. This will be very simple to implement, and provide the whole list in one place. What do you think? cc @cstancu

**Comment by zakkak** [comment]
Hi Aleksandar

> In cases where the security services feature has been disabled, all providers are by default filtered out. 

In https://github.com/quarkusio/quarkus/pull/17774#issuecomment-857878631 the security services feature is enabled, however as we are using some services that are not specified in the JCA it would be useful to be able to list the filtered out services/providers with `-H:+TraceSecurityServices` and then figure out which of them we need to explicitly include.
If there is any other way to achieve the same result please let me know.

> However, I agree with you, it would be useful to see exactly which providers got removed.
> I propose that we print a list of removed providers' class names after analysis, once the provider caches have the final value. This will be very simple to implement, and provide the whole list in one place. What do you think? 

It sounds good to me.
Thanks

**Comment by gradinac** [comment]
Ah, my bad! Hmm, we do not really filter service types in the `SecurityServicesFeature` - we only filter the security providers that got included in the image but weren't observed as used by the feature. The security services themselves are handled in a different way: at first, none are included and we incrementally include more as specific methods become reachable. If a service gets included, all providers that offer such a service are included as well.

One note: even if the service type isn't specified by the JCA, you can still have it automatically registered, provided that the service is in a specific format (see https://github.com/oracle/graal/blob/master/substratevm/src/com.oracle.svm.test/src/com/oracle/svm/test/SecurityServiceTest.java#L121 and https://github.com/oracle/graal/blob/master/substratevm/JCASecurityServices.md#custom-service-types)

**Comment by zakkak** [comment]
> (see https://github.com/oracle/graal/blob/master/substratevm/src/com.oracle.svm.test/src/com/oracle/svm/test/SecurityServiceTest.java#L121 and https://github.com/oracle/graal/blob/master/substratevm/JCASecurityServices.md#custom-service-types)

Thanks for extra info @gradinac.

I guess you meant https://github.com/oracle/graal/blob/cbc5a97e39f060108d9c245178ea358635d8ce55/substratevm/src/com.oracle.svm.test/src/com/oracle/svm/test/SecurityServiceTest.java#L135 instead of https://github.com/oracle/graal/blob/master/substratevm/src/com.oracle.svm.test/src/com/oracle/svm/test/SecurityServiceTest.java#L121, right?

**Comment by gradinac** [comment]
Ah yes, both the provider and the service are important in this case.
On the provider side, the provider adds a service with the type "JCACompliantNoOpService", which is the simple name of the service class. On the service side, we have a `getInstance` method that returns the appropriate service. Both of these assumptions are needed to provide automatic service registration.
