### ISSUE TITLE
Install native-image failed with 20.3.1

### ISSUE THREAD

**Issue by lic9** [oracle/graal#3459]
**Describe the issue**
Install native-image with graalvm ce 20.3.1 doesn't seem to work.

**Steps to reproduce the issue**
```
gu install native-image
Downloading: Component catalog from www.graalvm.org
Could not load channel https://www.graalvm.org/component-catalog/graal-updater-component-catalog.properties: Unsupported Graal VM version: 20.3.1, platform linux/amd64
Error: Unsupported Graal VM version: 20.3.1, platform linux/amd64
```

**Describe GraalVM and your environment:**
 - GraalVM version **CE 20.3.1**
 - JDK major version: **11**
 - OS: **CentOS**
 - Architecture: **amd64**

**More details**
Other versions (20.2.0, 20.3.0, 21.0.0) all work.

**Comment by mcraj017** [comment]
@lic9 I tried and it worked fine 
```
graalvm-ce-java11-20.3.1/bin$ ./gu install native-image
Downloading: Component catalog from www.graalvm.org
Processing Component: Native Image
Downloading: Component native-image: Native Image  from github.com
Installing new component: Native Image (org.graalvm.native-image, version 20.3.1)
```
Please download from here and try again
https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-20.3.1/graalvm-ce-java11-linux-amd64-20.3.1.tar.gz

**Comment by lic9** [comment]
Thanks @mcraj017 ! It's actually working with your download link. It might be just a bad download previously. I'll close the issue.
