### ISSUE TITLE
offline installation for GraalVM Components (with or without gu)

### ISSUE THREAD

**Issue by paulvi** [oracle/graal#3460]
**Feature request**

gu GraalVM Updater https://www.graalvm.org/reference-manual/graalvm-updater/
can download optional component. However that will not work for offline environment
Please support alternative GraalVM Component installation, for example by specifying `gu` to use local folder where

**Is your feature request related to a problem? Please describe.**
There are GraalVM downloads, but optional packages installation require being online.

**Describe the solution you'd like.**
1. Have GraalVM Component also freely downloadable
2. `gu` can install them from folder

**Describe who do you think will benefit the most.**
Well, there is fewer cases where computer cant or should not have Internet access.
But there is also case for GraalVM developer/test that should be able to try newly (locally) compiled GraalVM Components.
Maybe there is already such option, that can address offline installation.

**Describe alternatives you've considered.**
As GraalVM Component are not downloadable, there is maybe no option, that to compile from sources,
but
1. It is not how many repositories should be compiled
2. Compilation, e.g. on Linux, may require even more online access for some compiler and packages to download.

**Additional context.**
Sometimes offline installation is better if computer has slow on not stable access to update server.
For example if GraalVM Components hosting is not yet scaled for different regions.

**Express whether you'd like to help contributing this feature**
minimal README extending would be enough to shown alternative offline installation.

**Comment by mcraj017** [comment]
@paulvi you can download the instalable jar of the component and use

gu install -L <path to jar/<component>.jar>

**Comment by paulvi** [comment]
So simple.

How to download the installable jar of the component ?

**Comment by mcraj017** [comment]
@paulvi you can download from GitHub
https://github.com/graalvm/graalvm-ce-builds/releases

**Comment by paulvi** [comment]
yes, indeed

it is all possible

**Comment by paulvi** [comment]
Maybe https://www.graalvm.org/reference-manual/graalvm-updater/#manual-installation should be updated a bit

Where is doc sources?

**Comment by mcraj017** [comment]
@paulvi its clearly mentioned here https://www.graalvm.org/reference-manual/graalvm-updater/#manual-installation
Please let us know, if there is something we can add

**Comment by paulvi** [comment]
Maybe just word offline into caption
https://www.graalvm.org/reference-manual/graalvm-updater/#manual-installation

# Manual or Offline Installation

Is it sure that 
`gu -L install component.jar` will not be trying to download something else?
