### ISSUE TITLE
[Documentation] Would it be possible to consider adding an article about deployment of graalVM, in particular the creation of an .exe, as pointed out by an article in 2019 (see content of this issue request)

### ISSUE THREAD

**Issue by rubyFeedback** [oracle/graal#3462]
Hey there graal devs/users,

Before I describe my request in more detail, allow me to briefly preface that
I have been using ruby for almost 20 years now, java for only ~2 years, so
I definitely know ruby much better than java at this point. Evidently I am
also looking at jruby, truffleruby etc... in the long run, but this is 
secondary to my issue request here.

In my personal environment there are a few elderly folks who are not very
computer/tech savvy in general. Even setting up ruby is quite a challenge
for them, and using it is hard for them as well. So I am looking for 
the simplest possibilities to distribute code to them.

Recently I read this article from 2019:

https://dev.to/skhmt/creating-a-native-executable-in-windows-with-graalvm-3g7f

It praises graal but mentions some limitations (back then at the least).

Among one thing mentioned is the creation of a simple .exe file:

    \path\to\graalvm-ce-19.0.0\bin\native-image \path\to\helloworld.class --no-fallback

(The file size is no issue, because the harddiscs are huge so even 10MB or
more is a complete non-issue.)

I haven't yet gone through it; will first clean up some local java code
before I give the above a try, but while I was contemplating doing so,
I looked at the main README at https://github.com/oracle/graal.

The only time "executable" is mentioned is here:

"Substrate VM framework that allows ahead-of-time (AOT) compilation of
Java applications under closed-world assumption into executable
images or shared objects."

Now this made me wonder a little whether the use case described by that
article is very rare. I'd love to explore graalVM more; there is so 
much ruby code I wrote, which would be great to be able to integrate
and let use. I wrote tons of ruby-gtk3 code as well and while getting
gtk on windows is also not trivial, I tried java+swing and it works
quite ok.

So my issue request is:

- Would it be possible to integrate some article into the github-wiki
or some other place, which may be linked in from the main README too,
in particular for any use cases related to deploying graalVM-based 
code? I assume the author of that article is not the only one who 
went that way, so it may be useful for other folks to look at it,
ideally when it is documented. Does not have to be at the github-wiki
as such, could also be a document within the release of graalVM, 
but just some link from the main README, directly or indirectly, to
be able to find it would be great.

I don't necessarily need a lengthy guide as such (I'll figure that
one out at a later time, using the tried-and-tested google-it 
method that I have been using for a long time), but more like an
article that confirms that the above all works (similar to that
linked in article) in 2021, and that people may use it. It would
be helpful to know that the graal-team can confirm that this 
works and is used. Of course I would not mind useful details
in this regard either but a short article should suffice perfectly
well.

Also the article mentions:

"As of GraalVM 19.3.0, still no support for Swing nor JavaFX."

So any updates in this regard would be interesting too. For my
particular use case, I literally don't need a whole lot of 
functionality as such - even simple buttons, and text, in a 
GUI, would work just fine. Or I could simply generate .html
files on the fly as well, no problem. My use case is really
solely related to elderly people; I myself just use the 
commandline on linux anyway, so everything is about 1000x
easier than on windows used by people who never had much
exposure to technology where they were younger. 

At any rate please feel free to close this issue at any moment in
time; I just wanted to suggest that right ~after reading that 
article.

**Comment by oubidar-Abderrahim** [comment]
Hi @rubyFeedback 
Thank you for reaching out to us, I will be happy to clarify some things for you

> Now this made me wonder a little whether the use case described by that
> article is very rare.

Not really, what you're referring to is native-image, one of the most used features in GraalVM, And there are many examples out there on how to use such feature.

> Would it be possible to integrate some article into the github-wiki
>   or some other place, which may be linked in from the main README too

We have a link from the README to our official website: https://www.graalvm.org in which you can find a [guides section](https://www.graalvm.org/guides/) on how to use GraalVM, [examples section](https://www.graalvm.org/docs/examples/) with some small example of what you can achieve with GraalVM, also a [reference manual](https://www.graalvm.org/docs/reference-manual/) on how to use different GraalVM features including native-image.

Also, we have articles published on [Medium platform](https://medium.com/graalvm) detailing some use cases of GraalVM. and an [examples repository](https://github.com/graalvm/graalvm-demos) to check.

> but more like an
> article that confirms that the above all works

The Medium articles and the examples repository mentioned above are published by the GraalVM team and we can guarantee their usability.

> and that people may use it.

Native-image is licensed under the [GPL 2 with Classpath exception](https://github.com/oracle/graal/blob/master/substratevm/LICENSE). So you're free to use it under that license.

> "As of GraalVM 19.3.0, still no support for Swing nor JavaFX."
> 
> So any updates in this regard would be interesting too.

JavaFX is mostly supported on the latest GraalVM releases. Much work was done by the https://gluonhq.com/ team to provide Working JavaFX examples with native-image ([demos](https://github.com/gluonhq/gluon-samples))

If you have any more questions, don't hesitate to ask.

**Comment by oubidar-Abderrahim** [comment]
I'll be closing the issue, if you have more question please feel free to reopen
