### ISSUE TITLE
Wrong href location in Official gh-pages

### ISSUE THREAD

**Issue by tdkn** [oracle/graal#347]
https://github.com/oracle/graal/blob/b69b3c8f9df00b48576503b893427a13481671fc/docs/index.html#L25

**Comment by thomaswue** [comment]
Thanks for reporting! Should be fixed now.

**Comment by shelajev** [comment]
This is fixed by [0aa9114](https://github.com/oracle/graal/commit/0aa9114d689c8555b945bee71863f9dd0ae27d24). Please close.
