### ISSUE TITLE
 JVM_GetTemporaryDirectory called:  Unimplemented

### ISSUE THREAD

**Issue by Consulting4J** [oracle/graal#3494]
Hi,
I'm writing an utility which would attach to the JVM process, it runs perfectly with JIT mode.
Now I'm trying to run it in AOT mode, build sucessfully without errors but faild to run the native executable.
I found the root cause is there is an dependency of sun.misc.VMSupport.getVMTemporaryDirectory in my code.
It seems that this function is not implemented in SVM,  it make no sense, can graal team add an implementation ?

**Steps to reproduce the issue**
the code which would trigger function call sun.misc.VMSupport.getVMTemporaryDirectory
for instance

			Class clazz =Class.forName("sun.misc.VMSupport"); 
			Method method = clazz.getMethod("getVMTemporaryDirectory");
			Object dir =method.invoke(null);

The build script looks like this:

GRAAL_HOME=/home/graalvm/graalvm-ce-java8-21.1.0
ARTIFACT=nativeagent
MAINCLASS=Util
CP=./:$GRAAL_HOME/lib/tools.jar

$GRAAL_HOME/bin/native-image \
	        --verbose \
	        -H:Name=$ARTIFACT \
	        -H:TraceClassInitialization=true \
	        -H:+JNI \
		--report-unsupported-elements-at-runtime \
	        --no-fallback \
                -Djava.library.path=$GRAAL_HOME/jre/lib/amd64/ \
	        --initialize-at-build-time=com.sun.tools.attach.VirtualMachine,sun.tools.attach.HotSpotVirtualMachine,sun.misc.VMSupport \
		-H:+ReportExceptionStackTraces \
		--enable-http --enable-https --enable-url-protocols=http,https --enable-all-security-services \
		-cp $CP $MAINCLASS 

**Describe GraalVM and your environment:**
 - GraalVM version  graalvm-ce-java8-linux-amd64-21.1.0
 - JDK major version:  java 8
 - OS:  Ubuntu 18.04
 - Architecture:  amd4

**More details**

The following trace was given when I run the sucessfully build executable :

Fatal error reported via JNI: JVM_GetTemporaryDirectory called:  Unimplemented

JavaFrameAnchor dump:

  Anchor 00007fff6aa18920 LastJavaSP 00007fff6aa18900 LastJavaIP 000056178fa4ec06
  
TopFrame info:

  TotalFrameSize in CodeInfoTable 80
  
VMThreads info:

  VMThread 0000561792082f00  STATUS_IN_JAVA (safepoints disabled)  java.lang.Thread@0x7f840017fa38
  
VM Thread State for current thread 0000561792082f00:

  0 (8 bytes): com.oracle.svm.jni.JNIThreadLocalEnvironment.jniFunctions = (bytes) 
    0000561792082f00: 00007f83fffca010
  
  8 (8 bytes): com.oracle.svm.core.graal.snippets.StackOverflowCheckImpl.stackBoundaryTL = (Word) 140734974021632  00007fff6a225000
  16 (4 bytes): com.oracle.svm.core.thread.Safepoint.safepointRequested = (int) 2147482150  7ffffa26
  20 (4 bytes): com.oracle.svm.core.thread.VMThreads$StatusSupport.statusTL = (int) 1  00000001
  24 (32 bytes): com.oracle.svm.core.genscavenge.ThreadLocalAllocation.regularTLAB = (bytes) 
    0000561792082f18: 00007f8400900000 00007f8400a00000
    0000561792082f28: 00007f8400903068 0000000000000000
    
  
  56 (8 bytes): com.oracle.svm.core.stack.JavaFrameAnchors.lastAnchor = (Word) 140734982359328  00007fff6aa18920
  64 (4 bytes): com.oracle.svm.core.thread.JavaThreads.currentThread = (Object) java.lang.Thread  00007f840017fa38
  68 (4 bytes): com.oracle.svm.enterprise.core.f.a.zG = (Object) com.oracle.svm.enterprise.core.f.a  00007f8400901088
  72 (8 bytes): com.oracle.svm.core.thread.VMThreads.IsolateTL = (Word) 140204909264896  00007f83ffd00000
  80 (8 bytes): com.oracle.svm.core.thread.VMThreads.OSThreadHandleTL = (Word) 140239294606208  00007f8c0156ab80
  88 (8 bytes): com.oracle.svm.core.thread.VMThreads.OSThreadIdTL = (Word) 140239294606208  00007f8c0156ab80
  96 (8 bytes): com.oracle.svm.core.thread.VMThreads.nextTL = (Word) 0  0000000000000000
  104 (8 bytes): com.oracle.svm.core.thread.VMThreads.unalignedIsolateThreadMemoryTL = (Word) 94659234246352  0000561792082ed0
  112 (4 bytes): com.oracle.svm.core.heap.NoAllocationVerifier.openVerifiers = (Object) null
  116 (4 bytes): com.oracle.svm.core.identityhashcode.IdentityHashCodeSupport.hashCodeGeneratorTL = (Object) null
  120 (4 bytes): com.oracle.svm.core.snippets.ExceptionUnwind.currentException = (Object) null
  124 (4 bytes): com.oracle.svm.core.thread.ThreadingSupportImpl.activeTimer = (Object) null
  128 (4 bytes): com.oracle.svm.graal.isolated.IsolatedCompileClient.currentClient = (Object) null
  132 (4 bytes): com.oracle.svm.graal.isolated.IsolatedCompileContext.currentContext = (Object) null
  136 (4 bytes): com.oracle.svm.jni.JNIObjectHandles.handles = (Object) com.oracle.svm.core.handles.ThreadLocalHandles  00007f84009010a8
  140 (4 bytes): com.oracle.svm.jni.JNIThreadLocalPendingException.pendingException = (Object) null
  144 (4 bytes): com.oracle.svm.jni.JNIThreadLocalPinnedObjects.pinnedObjectsListHead = (Object) null
  148 (4 bytes): com.oracle.svm.jni.JNIThreadOwnedMonitors.ownedMonitors = (Object) null
  152 (4 bytes): com.oracle.svm.core.graal.snippets.StackOverflowCheckImpl.yellowZoneStateTL = (int) 1  00000001
  156 (4 bytes): com.oracle.svm.core.snippets.ImplicitExceptions.implicitExceptionsAreFatal = (int) 0  00000000
  160 (4 bytes): com.oracle.svm.core.thread.ThreadingSupportImpl.currentPauseDepth = (int) 0  00000000
  164 (4 bytes): com.oracle.svm.core.thread.VMThreads$ActionOnExitSafepointSupport.actionTL = (int) 0  00000000
  168 (4 bytes): com.oracle.svm.core.thread.VMThreads$ActionOnTransitionToJavaSupport.actionTL = (int) 0  00000000
  172 (4 bytes): com.oracle.svm.core.thread.VMThreads$StatusSupport.safepointsDisabledTL = (int) 1  00000001
  
VMOperation dump:

  No VMOperation in progress
  
  The 10 most recent VM operation status changes (oldest first):
    
  
Dump Counters:

  
Raw Stacktrace:

  00007fff6aa188a0: 00007f84000a8368 00005617900b9878
  00007fff6aa188b0: 0000561792082f00 0000000000000455
  00007fff6aa188c0: 0000561792082f00 00007f83ffd00000
  00007fff6aa188d0: 00007fff6aa18920 000056178fa4ec06
  00007fff6aa188e0: 00007f8400840160 00005617900ae3b4
  00007fff6aa188f0: 0000000000000455 000056178fa4ec19
  00007fff6aa18900: 0000000000000014 00007f84009010a8
  00007fff6aa18910: 00007f8400902e68 000000018f807f12
  
Stacktrace Stage 0:

  SP 00007fff6aa188a0 IP 000056178ee93346  FrameSize 80
  SP 00007fff6aa18900 IP 000056178fa4ec06  FrameSize 64
  SP 00007fff6aa18940 IP 000056178f0545f5  FrameSize 48
  SP 00007fff6aa18970 IP 000056178f64240b  FrameSize 48
  SP 00007fff6aa189a0 IP 000056178ee767df  FrameSize 560
  SP 00007fff6aa18bd0 IP 000056178ee9f187  FrameSize 144
  
Stacktrace Stage 1:

  SP 00007fff6aa188a0 IP 000056178ee93346  com.oracle.svm.core.code.CodeInfo@0x7f840012d4a4 name = image code
  SP 00007fff6aa18900 IP 000056178fa4ec06  com.oracle.svm.core.code.CodeInfo@0x7f840012d4a4 name = image code
  SP 00007fff6aa18940 IP 000056178f0545f5  com.oracle.svm.core.code.CodeInfo@0x7f840012d4a4 name = image code
  SP 00007fff6aa18970 IP 000056178f64240b  com.oracle.svm.core.code.CodeInfo@0x7f840012d4a4 name = image code
  SP 00007fff6aa189a0 IP 000056178ee767df  com.oracle.svm.core.code.CodeInfo@0x7f840012d4a4 name = image code
  SP 00007fff6aa18bd0 IP 000056178ee9f187  com.oracle.svm.core.code.CodeInfo@0x7f840012d4a4 name = image code
  
Stacktrace Stage 2:

  SP 00007fff6aa188a0 IP 000056178ee93346  [image code] com.oracle.svm.core.code.IsolateEnterStub.JNIFunctions_FatalError_dea4272cf8e20ff701a0a73f7a6d5d75e3401653(IsolateEnterStub.java:0)
  SP 00007fff6aa18900 IP 000056178fa4ec06  [image code] sun.misc.VMSupport.getVMTemporaryDirectory(VMSupport.java)
  SP 00007fff6aa18940 IP 000056178f0545f5  [image code] com.oracle.svm.reflect.VMSupport_getVMTemporaryDirectory_890c615302fe734ee1692e8ef32cfd8bd470f80d.invoke(Unknown Source)
  SP 00007fff6aa18970 IP 000056178f64240b  [image code] java.lang.reflect.Method.invoke(Method.java:498)
  SP 00007fff6aa189a0 IP 000056178ee767df  [image code] Util.main(Util.java:101)
  SP 00007fff6aa18bd0 IP 000056178ee9f187  [image code] com.oracle.svm.core.JavaMainWrapper.runCore(JavaMainWrapper.java:146)
  SP 00007fff6aa18bd0 IP 000056178ee9f187  [image code] com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:182)
  SP 00007fff6aa18bd0 IP 000056178ee9f187  [image code] com.oracle.svm.core.code.IsolateEnterStub.JavaMainWrapper_run_5087f5482cc9a6abc971913ece43acb471d2631b(IsolateEnterStub.java:0)
  
[Heap settings and statistics: 
  Supports isolates: true
  Object reference size: 4
  Incremental collections: 0
  Complete collections: 0]

[Native image heap boundaries: 
  ReadOnly Primitives: 0x7f83ffd01028 .. 0x7f83fff03908
  ReadOnly References: 0x7f83fff03918 .. 0x7f83fffc9860
  ReadOnly Relocatables: 0x7f83fffca000 .. 0x7f8400061750
  Writable Primitives: 0x7f8400062000 .. 0x7f840015ea60
  Writable References: 0x7f840015ea70 .. 0x7f84002a88d0
  Writable Huge: 0x0 .. 0x0
  ReadOnly Huge: 0x7f8400300030 .. 0x7f8400840160]

[Heap:
  [Young generation: 
    [Eden: 
      [edenSpace:
        aligned: 0/0 unaligned: 0/0]]
    [Survivors: 
      ]]
  [Old generation: 
    [oldFromSpace:
      aligned: 0/0 unaligned: 0/0]
    [oldToSpace:
      aligned: 0/0 unaligned: 0/0]
    ]
  [Unused:
    aligned: 0/0]]

**Comment by oubidar-Abderrahim** [comment]
Thank you for reporting this, we will look into it

**Comment by oubidar-Abderrahim** [comment]
Tracked internally on GR-32203

**Comment by Consulting4J** [comment]
thanks for tracking this.
I belive this issue could be reproduced on  Java 9 +  jdk/internal/vm/VMSupport.getVMTemporaryDirectory as well

**Comment by teshull** [comment]
Support for VMSupport.getVMTermporaryDirectory was just added in https://github.com/oracle/graal/commit/716fbdcb3e5da98d30fe868e5319784cf7aefe80
