### ISSUE TITLE
native crash on MacOS Big sur, exceptionStructure requires 16-bytes align

### ISSUE THREAD

**Issue by kirillp** [oracle/graal#3499]
When build with native image for iOS simulator, the resulting exe crashed due to 
exceptionStructure mis-alignment.
The fix is here: 
https://github.com/Montura/graal/commit/43e315f5a35e4feaf5fa3fdc4ddf4dc5be50a424

however due to recent changes to StackValue and alignment the fix probably should be reworked.

please see related commit
https://github.com/oracle/graal/commit/28c32c4525c8d252916ac3195532fbb04e86ae9e

**Comment by kirillp** [comment]
@gilles-duboscq

**Comment by gilles-duboscq** [comment]
Do you mean that 28c32c4 did not fix #3356?
/cc @christianwimmer

**Comment by kirillp** [comment]
I need more time to check if the https://github.com/oracle/graal/commit/28c32c4525c8d252916ac3195532fbb04e86ae9e fixes the problem without applying 
https://github.com/Montura/graal/commit/43e315f5a35e4feaf5fa3fdc4ddf4dc5be50a424

**Comment by kirillp** [comment]
@gilles-duboscq do you mean that now every StackValue.get invocation always align to 16 bytes ? 

Is not clear that "alignment required by the operating system for stack  frames" is the same a 
alignment required for _Unwind_Exception structure.

**Comment by christianwimmer** [comment]
> do you mean that now every StackValue.get invocation result is always aligned to 16 bytes?

Correct.

Please check if the commit Gilles mentioned fixes the problem, and if not re-open the issue.
