### ISSUE TITLE
'IncludeLocales' argument does not correctly parse comma separated values

### ISSUE THREAD

**Issue by kkriske** [oracle/graal#3500]
**Describe the issue**
Including locales does not work as expected.

The `-H:IncludeLocales=de-DE,es-ES,fr-FR` should parse into 3 locales, but the value is not split on commas, so it tries to make a locale from the string `"de-DE,es-ES,fr-FR"` instead, which runs ito the `default: return null;` flow here, since I was lucky enough that my string split up into 4 parts:
https://github.com/oracle/graal/blob/192eaf62331679907449ee60dad9d6d6661a3dc8/substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jdk/localization/LocalizationFeature.java#L278-L295

I have to say that this bug seriously saddens me, as I already reported the same thing (but for service loader options) more than half a year ago in #3055, which did not receive the slightest bit of attention (which has been the case for most PR's I opened).
Back then I assumed that https://github.com/oracle/graal/commit/cb793452f5241c9bc3101e610dc1ad2d5917b4e0 fixed the issue but I never went back to verify. This bug leads me to believe it is still an issue for service loader options as well.

**Steps to reproduce the issue**
Build a native image with the arguments `-H:DefaultLocale=en-GB -H:IncludeLocales=de-DE,es-ES,fr-FR`

**Describe GraalVM and your environment:**
 - GraalVM version: **CE 21.1.0**
 - JDK major version: **11**
 - OS: **Windows**
 - Architecture: **AMD64**

**Comment by mcraj017** [comment]
@kkriske Thanks for the contribution and we surely will review the  pull requests you submitted

**Comment by kristofdho** [comment]
> @kkriske Thanks for the contribution and we surely will review the pull requests you submitted

Great! They are getting pretty outdated though, but feel free to give me a shout and I'll take a look at whichever one is receiving some attention. The general ideas should still be relevant.

**Comment by mcraj017** [comment]
@kkriske just an update, I have assigned a review to your PR, please check it out for new comments or changes 
https://github.com/oracle/graal/pull/3055

**Comment by d-kozak** [comment]
@kkriske Thank you for the contribution. I've integrated your changes in https://github.com/oracle/graal/pull/3558 , in which I'll also fix the same problem for LocalizationFeature.
