### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by misiek08** [oracle/graal#351]
I didn't find quickly any repository with website sources. If there is one - let me know and I will make a PR.

**Here**: https://www.graalvm.org/docs/why-graal/
**is link**: Find out [how to get started](https://www.graalvm.org/docs/graalvm-as-a-platform/simple-language/) implementing a language.

It's a 404 know, a the correct URL is (probably): https://www.graalvm.org/docs/graalvm-as-a-platform/implement-language/

**Comment by thomaswue** [comment]
Thanks a lot for the report! We will fix asap.

**Comment by shelajev** [comment]
This is fixed in [8c94de6](https://github.com/oracle/graal/commit/8c94de61115afa9c0966e4c609840565a056e0ac).
