### ISSUE TITLE
Canonicalisation of Multiply by Constants can Cause x86 Performance Degradation

### ISSUE THREAD

**Issue by AndyJGraham** [oracle/graal#3512]
**Issue Description** 

The canonicalisation of multiplications by positive constants into shifts, additions and subtractions causes performance degradation on some “x86” machines. 

**Issue Details** 

The performance was investigated of canonicalisation of multiplication by positive constants into combinations of left shifts, additions and subtractions. e.g., replacing x * 4 with x << 2. 

This canonicalisation is present in cannonical(...) in the file “MulNode.java”. 

Benchmarking (more details below) showed that canonicalisation of multiplications by positive integers generally has a performance downgrade on some x86 platforms. The exception to this is replacing multiplication by a power of two into a single shift instruction. 

**Steps to Reproduce the Issue** 

A relevant snippet from the micro-benchmark:  

@Benchmark 
public void jmhTimeMulRefAp4() { 
  for (int i = 0; i < 1_000_000; i++) { 
    int j = i % NUM_RANDS; 
    result += (rand_long1[j] * rand_long2[j]) * 4L; 
  } 
} 

Equivalent benchmarks are used for the following cases: 

    x * 4	(x ^ 2) 
    x * 5	(x ^ 2) + x 
    x * 15	(x ^ 4) - x 10% 
    x * 12	(x ^ 3) + (x ^ 2) 
    x * 252	(x ^ 8) – (x ^ 2) 

The benchmarks were run on two x86 machines. 

In each case, the benchmarks were run on code that had the canonicalisation included and run on code that did not have the canonicalisation included.  

**Test Environment** 

    GraalVM version:	commit 9c4fbd117ce7c9f8ee2c95dc025672250856b293 
    JDK:			labsjdk-ce-11.0.11+8-jvmci-21.1-b04 
    OS:			Ubuntu 
    Architecture:		AMD64 (Further details follow in later sections) 

**Observations** 

**Benchmark Machine 1** 

This comparison was run on an E5-2609 machine. 

Removing the canonicalisation entirely results in an **5.3%** performance improvement. 

If we keep the canonicalisation of powers of two, but remove the others, that figure rises to an **8%** performance improvement. 

**Benchmark Machine 2** 

This comparison was run on a GOLD-2165 machine. 

Removing the canonicalisation entirely results in an **8%** performance improvement. 

If we keep the canonicalisation of powers of two, but remove the others, that figure rises to a **10%** performance improvement.

**Comment by AndyJGraham** [comment]
The line that reads "**replacing x * 2 with x << 2**" should, of course, read "**replacing x * 2 with x << 1**".

**Comment by mcraj017** [comment]
@AndyJGraham thanks for reporting the issue, we will check it out and get back to you

**Comment by mcraj017** [comment]
@AndyJGraham please provide the reproducer

**Comment by AndyJGraham** [comment]
@mcraj017 Hi Munish. Could you please let me know what exactly you would like me to provide?

**Comment by mcraj017** [comment]
@AndyJGraham You provided a code snippet, but it will be helpful if you provide the sample code where we can see the difference in performance

**Comment by AndyJGraham** [comment]
This attached Java file (renamed to .txt from .java to allow upload) was run as a JMH microbenchmark.
The benchmarks were run with the standard Graal compiler and with a version that had the canonicalisation of multiplication by positive constants to shifts, additions and subtractions commented out. This code can be found in file "MulNode.java".

home/andgra01/MulBench.txt

**Comment by AndyJGraham** [comment]
Second attempt at attaching file. Once again, this is really a .java file.

[MulBench.txt](https://github.com/oracle/graal/files/6747208/MulBench.txt)

**Comment by AndyJGraham** [comment]
It is worth noting that the canonicalisation causes a significant performance improvement on Arm platforms.

**Comment by plokhotnyuk** [comment]
@AndyJGraham Please take in account that MUL operation has latency ~3 cycles and can be executed only on one port on contemporary CPUs, while shift and ADD operations have 1 cycle latency and can be executed on 2-4 ports simultanuosly for not dependent operations.

**Comment by mcraj017** [comment]
@AndyJGraham thanks for the reproducer, I have shared this with our Dev team, they will check it out and get back to you

**Comment by mur47x111** [comment]
@AndyJGraham I cannot reproduce this degradation. I have 
```
-canonicalization  MulBench.jmhTimeMulRefAp4 1966.213 us/op +- 4.935
+canonicalization  MulBench.jmhTimeMulRefAp4 1838.209 us/op +- 111.988 
```
(lower the better).
Could you please share your benchmark as a jar in a repo? maybe I missed some configuration.
