### ISSUE TITLE
xattr: No such file: ./graalvm-ce-java16-21.1.0/Contents/MacOS/libjli.dylib

### ISSUE THREAD

**Issue by paulvi** [oracle/graal#3516]
When trying to download and install GraalVM using
https://www.graalvm.org/docs/getting-started/macos/ and https://github.com/graalvm/graalvm-ce-builds/releases/tag/vm-21.1.0

I got warning about missing file for GraalVM java16

```
Downloads % sudo xattr -r -d com.apple.quarantine ./graalvm-ce-java16-21.1.0/*
xattr: No such file: ./graalvm-ce-java16-21.1.0/Contents/MacOS/libjli.dylib
```

But there was no such warnig for GraalVM java11

```
Downloads % tar -xzf graalvm-ce-java11-darwin-amd64-21.1.0.tar.gz 
Downloads % sudo xattr -r -d com.apple.quarantine ./graalvm-ce-java11-21.1.0/*
```

The file `./graalvm-ce-java16-21.1.0/Contents/MacOS/libjli.dylib` is actually present in both java11 and java16 distributions, but it is shown as symlink in Finder

I don't know what is real result of this file , 
but I cannot be sure that `sudo xattr -r -d com.apple.quarantine` did actually processed all files.

**Comment by oubidar-Abderrahim** [comment]
Hi, Thank you for reporting this issue, this is a known issue for the GraalVM team. we replaced this file with a link to workaround some JDK issue which I believe has been fixed at some point. In the meanwhile, the files moved in the JDK and our workaround link points to the wrong location.
I think you can use GraalVM jdk16 directly by setting it to your `PATH` without the need for `sudo xattr -r -d com.apple.quarantine`, please give it a try and let us know if you face any issues.

**Comment by paulvi** [comment]
I'll stick to LTS versions

**Comment by oubidar-Abderrahim** [comment]
Issue tracked internally on GR-30831

**Comment by wirthi** [comment]
Internally this is reported as fixed, so I am closing this ticket. Let us know if this is still not working for you on a recently released version.
