### ISSUE TITLE
native-image-maven-plugin - CreateProcess error=206, The filename or extension is too long

### ISSUE THREAD

**Issue by ebremer** [oracle/graal#3518]
When building a native image on a Windows 2000 machine, for a fairly detailed project, I get a:
"CreateProcess error=206, The filename or extension is too long"
when native-image.exe is called.  I had a similar problem with building the same project in NetBeans but adding a exec.longClasspath=true to the actions for Maven run resolved the issue with the normal builds.  Is there a similar option for native-image-maven-plugin to follow what exec.longClasspath did for org.codehaus.mojo:exec-maven-plugin:1.5.0:exec?

https://www.mojohaus.org/exec-maven-plugin/exec-mojo.html

**Comment by vjovanov** [comment]
We moved the maven plugin to the following location: 

https://github.com/graalvm/native-build-tools/blob/master/native-maven-plugin/README.md

Please try with the latest plugin and see if it fails. If it does, then report an issue there.

**Comment by ebremer** [comment]
Same error.

**Comment by vjovanov** [comment]
Cool (not cool), can you please report the error at:

https://github.com/graalvm/native-build-tools

This will make it fixed the fastest.

**Comment by ebremer** [comment]
will do.
