### ISSUE TITLE
CSS URL Protocol

### ISSUE THREAD

**Issue by dkim19375** [oracle/graal#3531]
**Describe the issue**
A clear and concise description of the issue. We recommend using the [latest snapshot builds](https://github.com/graalvm/graalvm-ce-dev-builds/releases) to replicate the issue as  bugs are constantly being fixed in the master branch
When using TornadoFX with GraalVM Native Image, I am unable to run the program due to the CSS URL Protocol not being supported. So far, I couldn't find a way to disable it inside of TornadoFX, but I'll keep looking..
I've opened this issue in case there is an alternative or a fix to this problem.

**Steps to reproduce the issue**
Please include both build steps as well as run steps
1. Create a project involving TornadoFX or using the CSS URL Protocol
2. Run the `native-image` command and attempt to run the program

Alternative:
1. Clone the repository: https://github.com/dkim19375/Tag - `git clone https://github.com/dkim19375/Tag`
2. Run `gradlew nativeImage --info`, on Windows you'll have to use Native Tools Command Prompt, not sure if there are others you can use or what to do on other operating systems
3. Run `build\libs\exe\TagEXE`

**Describe GraalVM and your environment:**
 - GraalVM version: 21.1.0
 - JDK major version: 15
 - OS: Windows 10
 - Architecture: AMD64

**More details**
Log when running `native-image`: 
```
The URL protocol css is not tested and might not work as expected.
Supported URL protocols enabled by default: file,resource. Supported URL protocols available on demand: http,https.
Registering the css URL protocol failed. It will not be available at runtime.
```
Log when running program: https://paste.helpch.at/otevoqubeb

**Comment by mcraj017** [comment]
@dkim19375 thanks for reporting the issue, we will check it out and get back to you

**Comment by vjovanov** [comment]
I think the issue here is a missing configuration for JavaFX. Have you tried running with the [agent first](https://www.graalvm.org/reference-manual/native-image/BuildConfiguration/).

Can you please try with the agent first and see if the issue persists?

**Comment by mcraj017** [comment]
@dkim19375 I am closing this issue, if you still face any error, please report a new issue
