### ISSUE TITLE
Website main page: Get Started button is not working

### ISSUE THREAD

**Issue by Kopilov** [oracle/graal#3533]
**Describe the issue**
`Get Started` button is not working on https://www.graalvm.org/

**Steps to reproduce the issue**
1. Open https://www.graalvm.org/
2. Click `Get Started` button
 
**Expected action**
https://www.graalvm.org/docs/getting-started/ is opened

**Actual action**
https://www.graalvm.org/docs/getting-started-with-graalvm/ is opened, displays 404

**Comment by Kopilov** [comment]
Sorry if Website issues should be reported in another way but I have not found any

**Comment by oubidar-Abderrahim** [comment]
Thank you for reporting this, we will fix this soon

**Comment by olyagpl** [comment]
Thanks for spotting, fixed https://www.graalvm.org/.
