### ISSUE TITLE
Support wildcard usage in native-image -cp

### ISSUE THREAD

**Issue by olpaw** [oracle/graal#355]
See https://github.com/oracle/graal/issues/346#issuecomment-382526763

**Comment by olpaw** [comment]
https://docs.oracle.com/javase/8/docs/technotes/tools/windows/classpath.html#A1100762

**Comment by cstancu** [comment]
Fixed in https://github.com/oracle/graal/commit/1b2ab7f971337fcbb74e18937c44ae2601c42961.
