### ISSUE TITLE
Unnecessary (?) entries in reflect-config.json produced by the agent

### ISSUE THREAD

**Issue by aclement** [oracle/graal#3559]
**Describe the issue**
I am finding the agent continues to include some entries that really shouldn't be there (I think we tidied up some before but maybe haven't caught all routes to them), but also some that seem (on the face of it) superfluous, at least for my use cases.

I am running a spring pet clinic rest app with the agent, just starting it up and shutting it down. My agent output `reflect-config.json` includes:

Lambdas:
```
{
"name":"org.springframework.boot.autoconfigure.data.web.SpringDataWebAutoConfiguration$$Lambda$935/0x00000008406eb040",
  "allDeclaredFields":true,
  "allDeclaredMethods":true,
  "methods":[{"name":"customize","parameterTypes":["org.springframework.data.web.PageableHandlerMethodArgumentResolver"] }]
},
```

Proxies (these shouldn't be in here right?)
```
{
  "name":"com.sun.proxy.$Proxy107",
  "allDeclaredFields":true,
  "allDeclaredMethods":true,
  "allPublicMethods":true
},
```

and in the area of why are they recorded if not absolutely necessary:
```
{
  "name":"sun.security.provider.MD5",
  "methods":[{"name":"<init>","parameterTypes":[] }]
},
{
  "name":"sun.security.provider.NativePRNG",
  "methods":[{"name":"<init>","parameterTypes":[] }]
},
{
  "name":"sun.security.provider.SHA",
  "methods":[{"name":"<init>","parameterTypes":[] }]
},
{
  "name":"sun.security.provider.SHA2$SHA256",
  "methods":[{"name":"<init>","parameterTypes":[] }]
},
{
  "name":"sun.security.rsa.RSAKeyFactory$Legacy",
  "methods":[{"name":"<init>","parameterTypes":[] }]
}
```
For this last set, I imagine there could be good reasons for these but some apps seem to work perfectly without them which makes it hard to justify inclusion in any manual configuration I'm managing. It is as if they are there because I've initialized some bit of security infra which I don't actually need? Just interested in some guidance on these.

**Steps to reproduce the issue**
Please include both build steps as well as run steps
1. git clone https://github.com/aclement/spring-petclinic-rest
2. mvn clean package
3. java -agentlib:native-image-agent=config-output-dir=generated -jar target/spring-petclinic-rest-2.4.5.jar
4. open generated/reflect-config.json

**Describe GraalVM and your environment:**
- GraalVM 21.1.0 Java 11 CE (Java Version 11.0.11+8-jvmci-21.1-b05)
- MacOS BigSur

**Comment by oubidar-Abderrahim** [comment]
Thank you for reporting this, we will take a look into it.

**Comment by gradinac** [comment]
Hey @aclement, thank you for reporting this! :)
 - Regarding lambdas, we should most likely filter those out from the configuration. I don't think there's an easy way to check if a given class is a lambda or not - we would most likely need a similar heuristic as the one that will be merged for proxies
 - Regarding proxies, those should be filtered out once https://github.com/oracle/graal/pull/3550/ is merged
 - Regarding security, I'm not sure if those are necessary anymore - this depends on what exactly these entries are: `SecurityServicesFeature` will automatically register the necessary providers and security services for reflection, but if those services then use reflection in their code - that will need manual registration. 
 If you want to find out exactly how those entries got included in the image, you can run the agent with `experimental-configuration-with-origins` - this will give you the exact call path that caused the inclusion of each configuration entry
cc @peter-hofer

**Comment by aclement** [comment]
I didn't know about that flag. I just tried it (`experimental-configuration-with-origins`). I did get some info out but it failed producing the reflection config: (This is Graal 21.2 J11 MacOS):

```
java.lang.NegativeArraySizeException: null
    at com.oracle.svm.core.genscavenge.ThreadLocalAllocation.slowPathNewArray(ThreadLocalAllocation.java:181)
    at com.oracle.svm.configure.json.JsonWriter.newline(JsonWriter.java:95)
    at com.oracle.svm.agent.predicatedconfig.ConfigurationWithOriginsResultWriter$MethodCallNode.writeJson(ConfigurationWithOriginsResultWriter.java:186)
    at com.oracle.svm.agent.predicatedconfig.ConfigurationWithOriginsResultWriter$MethodCallNode.writeJson(ConfigurationWithOriginsResultWriter.java:172)
    at com.oracle.svm.agent.predicatedconfig.ConfigurationWithOriginsResultWriter.writeToDirectory(ConfigurationWithOriginsResultWriter.java:282)
    at com.oracle.svm.agent.NativeImageAgent.writeConfigurationFiles(NativeImageAgent.java:455)
    at com.oracle.svm.agent.NativeImageAgent.onUnloadCallback(NativeImageAgent.java:528)
    at com.oracle.svm.jvmtiagentbase.JvmtiAgentBase.onUnload(JvmtiAgentBase.java:267)
```

**Comment by peter-hofer** [comment]
Lambdas filtered with: 18c276f625350ea50c695971068f5b758756c5db
Proxies should have been filtered already.
