### ISSUE TITLE
[Native Image] Cannot register reflection call for java.lang.ClassLoader.defineClass

### ISSUE THREAD

**Issue by dzou** [oracle/graal#3564]
**Describe the issue**
I have some code which makes a reflective call to `java.lang.ClassLoader.defineClass(..)` and want to register this class in my reflect-config.json like so:

```
[
  {
    "name":"java.lang.ClassLoader",
    "methods":[{"name":"defineClass","parameterTypes":["java.lang.String","byte[]","int","int","java.security.ProtectionDomain"] }]
  }
]
```

However, it doesn't seem to work, I still get this error:

```
Exception in thread "main" java.lang.NoSuchMethodException: java.lang.ClassLoader.defineClass(java.lang.String, [B, int, int, java.security.ProtectionDomain)
	at java.lang.Class.getDeclaredMethod(DynamicHub.java:2475)
	at com.example.Driver.main(Driver.java:10)
```

**Steps to reproduce the issue**

Reproducer application: https://github.com/dzou/define-class-repro
Config located in src/main/resources/META-INF/native-image/reflect-config.json 

Build steps:
1. `git clone https://github.com/dzou/define-class-repro`
2. `mvn package -Pnative`
3. `./target/com.example.driver`

**Describe GraalVM and your environment:**

GraalVM Java version: 21.0.0
```
openjdk version "11.0.10" 2021-01-19
OpenJDK Runtime Environment GraalVM CE 21.0.0 (build 11.0.10+8-jvmci-21.0-b06)
OpenJDK 64-Bit Server VM GraalVM CE 21.0.0 (build 11.0.10+8-jvmci-21.0-b06, mixed mode, sharing)
```

**Additional Notes**

Maybe `ClassLoader.defineClass` is not supported altogether?

**Comment by pquiring** [comment]
NativeImage (aka SubstrateVM) is a closed world, pre-compiled executable that doesn't include a JIT or AOT compilers (which would require local C++ toolchain).  
defineClass() wouldn't be supported.

**Comment by dzou** [comment]
Does the feature in this PR create a workaround for this? https://github.com/oracle/graal/pull/2442

Wasn't sure if this was officially documented.

**Comment by pquiring** [comment]
Hmm.. that PR which was merged does allow defineClass() to work as long as the defineClass() is invoked during the agent process.  It's still a closed word app, so you can't invoke defineClass() for any bytecode that is added AFTER the build process.
It basically allows the classpath to be expanded at compile time (not run time).

**Comment by mcraj017** [comment]
@dzou Thanks for reporting the issue, we will check it out and get back to you

**Comment by mcraj017** [comment]
@dzou I have tried with GraalVM 21.2 and it is resolved, please use the new version 21.2 and let us know

**Comment by mcraj017** [comment]
```
define-class-repro/target/define-class-test-1.0-SNAPSHOT.jar --no-fallback --no-server -H:Class=com.example.Driver
Warning: Ignoring server-mode native-image argument --no-server.
[com.example.driver:12085]    classlist:   2,056.28 ms,  0.96 GB
[com.example.driver:12085]        (cap):  13,563.63 ms,  0.96 GB
[com.example.driver:12085]        setup:  15,723.55 ms,  0.96 GB
[com.example.driver:12085]     (clinit):     204.34 ms,  1.74 GB
[com.example.driver:12085]   (typeflow):   7,146.48 ms,  1.74 GB
[com.example.driver:12085]    (objects):   6,896.68 ms,  1.74 GB
[com.example.driver:12085]   (features):     588.06 ms,  1.74 GB
[com.example.driver:12085]     analysis:  15,152.19 ms,  1.74 GB
[com.example.driver:12085]     universe:     991.10 ms,  1.74 GB
[com.example.driver:12085]      (parse):   1,590.49 ms,  1.76 GB
[com.example.driver:12085]     (inline):   2,399.65 ms,  1.76 GB
[com.example.driver:12085]    (compile):  14,380.84 ms,  3.24 GB
[com.example.driver:12085]      compile:  19,161.87 ms,  3.24 GB
[com.example.driver:12085]        image:   2,501.40 ms,  3.04 GB
[com.example.driver:12085]        write:     530.79 ms,  3.04 GB
[com.example.driver:12085]      [total]:  56,401.72 ms,  3.04 GB
# Printing build artifacts to: /Users/hv0ij4/Desktop/issues/github/3564/define-class-repro/target/com.example.driver.build_artifacts.txt
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:05 min
[INFO] Finished at: 2021-07-22T15:36:56+08:00
[INFO] ------------------------------------------------------------------------
define-class-repro % ./target/com.example.driver
Success: 
defineClass
```

**Comment by dzou** [comment]
Thanks @mcraj017 for checking. Looks like it is now accessible via reflection in the newer version; it seems to be unsupported if you try to invoke it though for reasons described above.

Will close for now, will do some more research into seeing if invoking this function is possible.
