### ISSUE TITLE
[Native Image] -J parameter is not work

### ISSUE THREAD

**Issue by nganh1** [oracle/graal#3565]
> https://www.graalvm.org/reference-manual/native-image/BuildConfiguration/#memory-configuration-for-native-image-build
 
I followed and tried to use `native-image --auto-fallback -J-Xmx4G -J-Xms4G -jar pan.jar pan` command compiles the JAR file. 
There is no error in the process, but the jvm memory is not set to 4G after running. 
What am I doing wrong?

Console output:

> [root@localhost pan]# native-image --auto-fallback -J-Xmx4G -J-Xms4G -jar pan.jar pan
[pan:3927]    classlist:   1,968.79 ms,  0.96 GB
[pan:3927]        (cap):     508.56 ms,  0.96 GB
[pan:3927]        setup:   2,345.48 ms,  0.96 GB
[pan:3927]     (clinit):     347.95 ms,  1.90 GB
[pan:3927]   (typeflow):  14,983.97 ms,  1.90 GB
[pan:3927]    (objects):  10,863.57 ms,  1.90 GB
[pan:3927]   (features):     688.95 ms,  1.90 GB
[pan:3927]     analysis:  27,457.17 ms,  1.90 GB
[pan:3927]     universe:     872.87 ms,  1.90 GB
Warning: Reflection method java.lang.Class.forName invoked at org.springframework.boot.loader.jar.Handler.getFallbackHandler(Handler.java:158)
Warning: Reflection method java.lang.Class.forName invoked at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:46)
Warning: Reflection method java.lang.Class.getMethod invoked at org.springframework.boot.loader.jar.JarFileEntries.<clinit>(JarFileEntries.java:66)
Warning: Reflection method java.lang.Class.getDeclaredMethod invoked at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:47)
Warning: Reflection method java.lang.Class.getDeclaredConstructor invoked at org.springframework.boot.loader.jar.Handler.getFallbackHandler(Handler.java:159)
Warning: Aborting stand-alone image build due to reflection use without configuration.
Warning: Use -H:+ReportExceptionStackTraces to print stacktrace of underlying exception
[pan:4012]    classlist:   2,061.68 ms,  0.96 GB
[pan:4012]        (cap):     545.34 ms,  0.96 GB
[pan:4012]        setup:   2,443.41 ms,  0.96 GB
[pan:4012]     (clinit):     182.51 ms,  1.72 GB
[pan:4012]   (typeflow):   6,503.67 ms,  1.72 GB
[pan:4012]    (objects):   4,844.75 ms,  1.72 GB
[pan:4012]   (features):     339.59 ms,  1.72 GB
[pan:4012]     analysis:  12,094.24 ms,  1.72 GB
[pan:4012]     universe:     509.27 ms,  1.72 GB
[pan:4012]      (parse):   1,796.94 ms,  1.72 GB
[pan:4012]     (inline):   1,610.66 ms,  1.72 GB
[pan:4012]    (compile):  11,057.05 ms,  2.39 GB
[pan:4012]      compile:  15,013.15 ms,  2.39 GB
[pan:4012]        image:   1,351.76 ms,  2.39 GB
[pan:4012]        write:     364.70 ms,  2.39 GB
\# Printing build artifacts to: pan.build_artifacts.txt
[pan:4012]      [total]:  34,064.82 ms,  2.39 GB
Warning: Image 'pan' is a fallback image that requires a JDK for execution (use --no-fallback to suppress fallback image generation and to print more detailed information why a fallback image was necessary).

CentOS Linux release 8.3.2011
GraalVM Version: graalvm-ce-java11-21.1.0

**Comment by nganh1** [comment]
I [tried](https://www.graalvm.org/reference-manual/native-image/MemoryManagement/#java-heap-size) But it didn't work.

The two commands are:
`native-image --auto-fallback -R:MinHeapSize=4096m -R:MaxHeapSize=4096m -jar pan.jar`
and
`./pan -Xms4096m -Xmx4096m`

**Comment by mcraj017** [comment]
@nganh1 please try 
https://docs.oracle.com/en/graalvm/enterprise/21/docs/reference-manual/native-image/BuildConfiguration/ > Native Image > Build Configuration > Assisted configuration of the native image build

**Comment by mcraj017** [comment]
@nganh1 do you still need our assistance?

**Comment by nganh1** [comment]
> @nganh1 do you still need our assistance?

I tried to introduce "native image Maven plugin" into the project, but I received an error message when compiling:

> ...
[interview:15112]    classlist:   3,731.36 ms,  1.19 GB
[interview:15112]        (cap):   1,348.62 ms,  1.19 GB
[interview:15112]        setup:   2,014.52 ms,  1.19 GB
Error: Error compiling query code (in C:\Users\14561\AppData\Local\Temp\SVM-337522698088331873\NativeInfoDirectives.c). Compiler command ''C:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Tools\MSVC\14.30.30401\bin\Hostx64\x64\cl.exe' /WX /W4 /wd4244 /wd4245 /wd4800 /wd4804 /wd4214 '/FeC:\Users\14561\AppData\Local\Temp\SVM-337522698088331873\NativeInfoDirectives.exe' 'C:\Users\14561\AppData\Local\Temp\SVM-337522698088331873\NativeInfoDirectives.c'' output included error: [NativeInfoDirectives.c, C:\Users\14561\AppData\Local\Temp\SVM-337522698088331873\NativeInfoDirectives.c(11): fatal error C1083: 无法打开包括文件: “unistd.h”: No such file or directory]
com.oracle.svm.core.util.UserError$UserException: Error compiling query code (in C:\Users\14561\AppData\Local\Temp\SVM-337522698088331873\NativeInfoDirectives.c). Compiler command ''C:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Tools\MSVC\14.30.30401\bin\Hostx64\x64\cl.exe' /WX /W4 /wd4244 /wd4245 /wd4800 /wd4804 /wd4214 '/FeC:\Users\14561\AppData\Local\Temp\SVM-337522698088331873\NativeInfoDirectives.exe' 'C:\Users\14561\AppData\Local\Temp\SVM-337522698088331873\NativeInfoDirectives.c'' output included error: [NativeInfoDirectives.c, C:\Users\14561\AppData\Local\Temp\SVM-337522698088331873\NativeInfoDirectives.c(11): fatal error C1083: 无法打开包括文件: “unistd.h”: No such file or directory]
        at com.oracle.svm.core.util.UserError.abort(UserError.java:139)
        at com.oracle.svm.hosted.c.NativeLibraries.reportErrors(NativeLibraries.java:370)
        at com.oracle.svm.hosted.NativeImageGenerator.processNativeLibraryImports(NativeImageGenerator.java:1589)
        at com.oracle.svm.hosted.NativeImageGenerator.setupNativeLibraries(NativeImageGenerator.java:1072)
        at com.oracle.svm.hosted.NativeImageGenerator.setupNativeImage(NativeImageGenerator.java:888)
        at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:530)
        at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:491)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:380)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:543)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:119)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner$JDK9Plus.main(NativeImageGeneratorRunner.java:573)
[interview:15112]      [total]:   5,787.67 ms,  1.19 GB
\# Printing build artifacts to: C:\Users\14561\Documents\Development\JAVA\IDEA\my_project_template\target\interview.build_artifacts.txt
Error: Image build request failed with exit status 1
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  07:34 min (Wall Clock)
[INFO] Finished at: 2021-07-31T18:47:19+08:00
[INFO] ------------------------------------------------------------------------

pom.xml:

        ...
	<properties>
		<java.version>11</java.version>
		<start-class>cn.qwq.interview.InterviewApplication</start-class>
	</properties>

	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-data-jdbc</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
			<exclusions>
				<exclusion>
					<groupId>org.springframework.boot</groupId>
					<artifactId>spring-boot-starter-tomcat</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-data-redis</artifactId>
			<version>2.5.3</version>
		</dependency>
		
		<dependency>
			<groupId>mysql</groupId>
			<artifactId>mysql-connector-java</artifactId>
			<version>8.0.26</version>
		</dependency>
		<dependency>
			<groupId>org.projectlombok</groupId>
			<artifactId>lombok</artifactId>
			<optional>true</optional>
		</dependency>
		
		<dependency>
			<groupId>com.baomidou</groupId>
			<artifactId>mybatis-plus-boot-starter</artifactId>
			<version>3.2.0</version>
		</dependency>
		<dependency>
			<groupId>com.baomidou</groupId>
			<artifactId>mybatis-plus-generator</artifactId>
			<version>3.2.0</version>
		</dependency>
		<dependency>
			<groupId>org.freemarker</groupId>
			<artifactId>freemarker</artifactId>
			<version>2.3.28</version>
		</dependency>
		<dependency>
			<groupId>com.alibaba</groupId>
			<artifactId>fastjson</artifactId>
			<version>1.2.76</version>
		</dependency>
		
		<dependency>
			<groupId>commons-io</groupId>
			<artifactId>commons-io</artifactId>
			<version>2.11.0</version>
		</dependency>
		
		<dependency>
			<groupId>org.apache.commons</groupId>
			<artifactId>commons-pool2</artifactId>
			<version>2.10.0</version>
		</dependency>
		
		<dependency>
			<groupId>org.springframework.kafka</groupId>
			<artifactId>spring-kafka</artifactId>
			<version>2.7.5</version>
		</dependency>
		
		<dependency>
			<groupId>com.baomidou</groupId>
			<artifactId>dynamic-datasource-spring-boot-starter</artifactId>
			<version>3.4.1</version>
		</dependency>
		
		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-context-indexer</artifactId>
		</dependency>
		
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-undertow</artifactId>
		</dependency>
	</dependencies>

	<repositories>
		<repository>
			<id>spring-milestones</id>
			<name>Spring Milestones</name>
			<url>https://repo.spring.io/milestone</url>
		</repository>
	</repositories>

	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
				<version>2.5.3</version>
				<configuration>
					<excludes>
						<exclude>
							<groupId>org.projectlombok</groupId>
							<artifactId>lombok</artifactId>
						</exclude>
					</excludes>
				</configuration>
			</plugin>
		</plugins>
	</build>

	<profiles>
		<profile>
			<id>native</id>
			<build>
				<plugins>
					<plugin>
						<groupId>org.graalvm.nativeimage</groupId>
						<artifactId>native-image-maven-plugin</artifactId>
						<version>21.2.0</version>
						<configuration>
							<buildArgs>-J-Xmx4G -H:TraceClassInitialization=true -H:+ReportExceptionStackTraces -Dspring.graal.remove-unused-autoconfig=true -Dspring.graal.remove-yaml-support=true</buildArgs>
							<imageName>${project.artifactId}</imageName>
						</configuration>
						<executions>
							<execution>
								<goals>
									<goal>native-image</goal>
								</goals>
								<phase>package</phase>
							</execution>
						</executions>
					</plugin>
					<plugin>
						<groupId>org.springframework.boot</groupId>
						<artifactId>spring-boot-maven-plugin</artifactId>
					</plugin>
				</plugins>
			</build>
		</profile>
	</profiles>
</project>

**Comment by mcraj017** [comment]
@nganh1 for building native images on Windows you need to install Microsoft Visual C++ (MSVC) that comes with Visual Studio 2017 15.5.5 or later and builds using x64 Native Tools Command Prompt.
PLease check out the prerequisites here for native-image:

**Comment by nganh1** [comment]
> @nganh1 for building native images on Windows you need to install Microsoft Visual C++ (MSVC) that comes with Visual Studio 2017 15.5.5 or later and builds using x64 Native Tools Command Prompt.
> Please check out the prerequisites here for native-image:
> https://www.graalvm.org/reference-manual/native-image/#prerequisites

Sorry, I didn't make it clear before, I have installed visual studio community 2022 and MSVC 2019. The environment variables are configured as follows:

> GRAALVM_HOME=C:\Program Files\Java\graalvm-ce-java11-21.2.0
JAVA_HOME=C:\Program Files\Java\graalvm-ce-java11-21.2.0
INCLUDE=C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\ucrt;C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um;C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\shared;C:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Tools\MSVC\14.30.30401\include.;
LIB=C:\Program Files (x86)\Windows Kits\10\Lib\10.0.19041.0\um\x64;C:\Program Files (x86)\Windows Kits\10\Lib\10.0.19041.0\ucrt\x64;C:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Tools\MSVC\14.30.30401\lib\x64;
PATH=%PATH%;C:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Tools\MSVC\14.30.30401\bin\Hostx64\x64

**Comment by mcraj017** [comment]
@nganh1 please provide reproducer

**Comment by nganh1** [comment]
> @nganh1 please provide reproducer

what is the reproducer

**Comment by mcraj017** [comment]
@nganh1 sample code to reproduce this error

**Comment by mcraj017** [comment]
@nganh1 As I see you are using springboot, please migrate to spring native project and try
https://docs.spring.io/spring-native/docs/current/reference/htmlsingle/

**Comment by mcraj017** [comment]
@nganh1 any update on this?
do you still need our assistance from our side?

**Comment by mcraj017** [comment]
Closing this issue as there is no response from User in last 30 days
