### ISSUE TITLE
[Native Image] Debug section doesn't support non-ASCII characters

### ISSUE THREAD

**Issue by jovanstevanovic** [oracle/graal#3586]
**Describe the issue**
Currently, the native image doesn't support adding non-ASCII symbols in debug section. In this example written in Scala, the class is declaring field **ε**, which will result in an exception during build time.

**Steps to reproduce the issue**
`mx --env ni-ce benchmark renaissance-native-image:finagle-chirper -- --jvm=native-image --jvm-config=default-ce`

**Describe GraalVM and your environment:**
```
$ java -version

openjdk 11.0.11 2021-04-20
OpenJDK Runtime Environment GraalVM 21.3.0-dev (build 11.0.11+8-jvmci-21.2-b02)
OpenJDK 64-Bit Server VM GraalVM 21.3.0-dev (build 11.0.11+8-jvmci-21.2-b02, mixed mode, sharing)

$ native-image --version

native-image dev CE (Java Version 11.0.11+8-jvmci-21.2-b02)
```

**More details**

```
Fatal error:com.oracle.svm.core.util.VMError$HostedError: java.lang.RuntimeException: oops : expected ASCII string! ε
  at com.oracle.svm.core.util.VMError.shouldNotReachHere(VMError.java:72)
  at com.oracle.svm.hosted.image.NativeImage.write(NativeImage.java:172)
  at com.oracle.svm.hosted.image.NativeImageViaCC.write(NativeImageViaCC.java:409)
  at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:658)
  at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:489)
  at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:382)
  at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:545)
  at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:119)
  at com.oracle.svm.hosted.NativeImageGeneratorRunner$JDK9Plus.main(NativeImageGeneratorRunner.java:575)
```

**Comment by olpaw** [comment]
@adinn this is probably something you want to take a look at.

**Comment by adinn** [comment]
> this is probably something you want to take a look at.

@olpaw Yes, for some definition of 'want' :-)

I'll take a look.

**Comment by adinn** [comment]
@olpaw @jovanstevanovic 

I patched the DWARF info generator to generate all string text as UTF8 and flag compile units as employing UTF-8 for text.

The DWARF spec I started working from did not mention anything about string encoding which is why I originally implemented support only for ASCII. DWARF4, which I am using now, recommends using UTF-8 and marking info compile units as employing UTF-8.

I checked the gdb source code and it appears to accept UTF8 for all text, not just strings in the .debug_str section but also text in other sections like class, method and field names etc in .debug_info or dir and file names in .debug_line sections. So, the fix ought ot be ok.

Running the test before the patch I saw the exception reported above during image generation for renaissance-0.11.0-finagle-chirper-default-ce. After the patch I now see it pass the generation stage. It fails on my machine during the run with a bind exception as follows:

    java.net.BindException: Failed to bind to 0.0.0.0/0.0.0.0:0: Unable to create Channel from class class io.netty.channel.socket.nio.NioServerSocketChannel

clearly that is unrelated to the DWARF issue.
@olpaw could you please assign this issue to me and also link the proposed fix in PR  #3594 to this issue.

**Comment by olpaw** [comment]
> @olpaw could you please assign this issue to me and also link the proposed fix in PR #3594 to this issue.

Done.

**Comment by olpaw** [comment]
> I checked the gdb source code and it appears to accept UTF8 for all text, not just strings in the .debug_str section but also text in other sections like class, method and field names etc in .debug_info or dir and file names in .debug_line sections. So, use of UTF-8 everywhere ought ot be ok.

Nice :sunglasses:

**Comment by jovanstevanovic** [comment]
> @olpaw @jovanstevanovic
> 
> I patched the DWARF info generator to generate all string text as UTF8 and flag compile units as employing UTF-8 for text.
> 
> The DWARF2 spec I started working from did not mention anything about string encoding which is why I originally implemented support only for ASCII. DWARF4, which I am using now, recommends using UTF-8 and marking info compile units as employing UTF-8.
> 
> I checked the gdb source code and it appears to accept UTF8 for all text, not just strings in the .debug_str section but also text in other sections like class, method and field names etc in .debug_info or dir and file names in .debug_line sections. So, use of UTF-8 everywhere ought ot be ok.
> 
> Running the test before the patch I saw the exception reported above during image generation for renaissance-0.11.0-finagle-chirper-default-ce. After the patch I now see it pass the generation stage. It fails on my machine during the run with a bind exception as follows:
> 
> ```
> java.net.BindException: Failed to bind to 0.0.0.0/0.0.0.0:0: Unable to create Channel from class class io.netty.channel.socket.nio.NioServerSocketChannel
> ```
> 
> clearly that is unrelated to the DWARF issue.
> @olpaw could you please assign this issue to me and also link the proposed fix in PR #3594 to this issue.

`finagle-chirper` and `finagle-http` benchmarks contain two problems. One is a problem with debug symbols, which will hopefully be fixed with your PR. The second problem with `java.net.BindException` is the one I'm trying to solve with this PR (#3574). I'll try to combine these two PRs and see if everything works fine. Let you know once the tests finish!

**Comment by jovanstevanovic** [comment]
Actually, combining these 3 PRs (#3594, #3570, and #3574) makes finagle benchmarks works without any workarounds. Great! :+1:

**Comment by adinn** [comment]
@jovanstevanovic Nice work! Thanks for confirming the fix is ok.

**Comment by adinn** [comment]
@christianwimmer @peter-hofer

Since Paul Woegerer is away on holiday at the moment would one of you be able to review my PR (#3594) and shepherd it through the back end gate into the product?
