### ISSUE TITLE
run Python in GraalVM - `import requests` fails with Exception: You need either charset_normalizer or chardet installed (requests init failure)

### ISSUE THREAD

**Issue by paulvi** [oracle/graal#3588]
Also asked on https://stackoverflow.com/questions/68390276/run-python-in-graalvm-import-requests-fails-with-exception-you-need-either

I try to run Python script in GraalVm and it fails on 
```python
import requests
```
And it seems GraalVM issue, as the script work with usual `python3`.

Java code:

```java
import org.graalvm.polyglot.Context;
import org.graalvm.polyglot.Source;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.nio.file.Paths;

public class RunPython4 {
    public static String PYTHON = "python";
    // venv/**/* must be included into resources in pom.xml
    private static String VENV_EXECUTABLE = RunPython4.class.getClassLoader().getResource(Paths.get("venv", "bin", "graalpython").toString()).getPath();
    private static String SOURCE_FILE_NAME = "health.py";

    public static void log(String s){
        System.out.println(s);
    }

    public static void main(String[] args) {
        log("Hello Java!");
        log(System.getProperty("java.version"));
        log(System.getProperty("java.runtime.version"));

        String pyFilename = "./health.py";

        try (Context context = Context.newBuilder("python").
                allowAllAccess(true).
                option("python.ForceImportSite", "true").
                option("python.Executable", VENV_EXECUTABLE).
                build();) {
            context.eval(PYTHON, "print('Hello Python!')");

            context.eval(PYTHON, "import sys; print(sys.version)");

            //4
            try(BufferedReader br = new BufferedReader(new FileReader(pyFilename))) {
                int i = 0;
                for(String line; (line = br.readLine()) != null; ) {
                    i++;
                    log(""+i+": "+line);
                    context.eval("python", line);
                }
            }catch ( IOException e){
                log("IOException "+e);
            }
```

Output:
```
Hello Java!
11.0.11
11.0.11+8-jvmci-21.1-b05
Hello Python!
3.8.5 (Fri Jun 25 17:55:09 CST 2021)
[Graal, GraalVM CE, Java 11.0.11]
1: # Checking subgraph health v1.1
2: # https://thegraph.com/docs/deploy-a-subgraph#checking-subgraph-health
3: 
4: import requests
Exception in thread "main" Exception: You need either charset_normalizer or chardet installed
	at org.graalvm.sdk/org.graalvm.polyglot.Context.eval(Context.java:379)
	at RunPython4.main(RunPython4.java:54)

Process finished with exit code 1

```

I searched deeper, `"You need either charset_normalizer or chardet installed"` is string from 

https://github.com/psf/requests/blob/master/requests/__init__.py#L57-L85
```python
def check_compatibility(urllib3_version, chardet_version, charset_normalizer_version):
    urllib3_version = urllib3_version.split('.')
    assert urllib3_version != ['dev']  # Verify urllib3 isn't installed from git.

    # Sometimes, urllib3 only reports its version as 16.1.
    if len(urllib3_version) == 2:
        urllib3_version.append('0')

    # Check urllib3 for compatibility.
    major, minor, patch = urllib3_version  # noqa: F811
    major, minor, patch = int(major), int(minor), int(patch)
    # urllib3 >= 1.21.1, <= 1.26
    assert major == 1
    assert minor >= 21
    assert minor <= 26

    # Check charset_normalizer for compatibility.
    if chardet_version:
        major, minor, patch = chardet_version.split('.')[:3]
        major, minor, patch = int(major), int(minor), int(patch)
        # chardet_version >= 3.0.2, < 5.0.0
        assert (3, 0, 2) <= (major, minor, patch) < (5, 0, 0)
    elif charset_normalizer_version:
        major, minor, patch = charset_normalizer_version.split('.')[:3]
        major, minor, patch = int(major), int(minor), int(patch)
        # charset_normalizer >= 2.0.0 < 3.0.0
        assert (2, 0, 0) <= (major, minor, patch) < (3, 0, 0)
    else:
        raise Exception("You need either charset_normalizer or chardet installed")
```

So it is clear that `requests` init fails over `charset_normalizer_version` that is likely undefined

https://github.com/psf/requests/blob/master/requests/__init__.py#L47
```python
try:
    from charset_normalizer import __version__ as charset_normalizer_version
except ImportError:
    charset_normalizer_version = None
```

The `requests` package is present of course

[![enter image description here][1]][1]

  [1]: https://i.stack.imgur.com/vTOiZ.png

**Describe the issue**
above

**Steps to reproduce the issue**
Please include both build steps as well as run steps
1. **[e.g.: git clone --depth 1 https://git.myrepo.com/projectone ]**
2. **[e.g.: mvn clean package]**

**Describe GraalVM and your environment:**
 - GraalVM version 
21.1.0 set as JAVA_HOME
3.8.5 (Fri Jun 25 17:55:09 CST 2021)
[Graal, GraalVM CE, Java 11.0.11]

 - JDK major version: **[e.g.:8]**
 - OS: **[e.g. macOS Catalina]**
 - Architecture: **[e.g.: AMD64]**

**More details**
above should be enough

**Comment by rodrigar-mx** [comment]
Hi @paulvi, I'll take care of this issue. I will take a closer look to it and reproduce it. Any questions or updates, I will let you know.

**Comment by rodrigar-mx** [comment]
I noticed you solved your problem and posted the solution on StackOverflow. Does that completely fix your issue?

**Comment by paulvi** [comment]
well, the issue is not actually of this repository, nor of https://github.com/oracle/graalpython but of packages

I suggest to have summary for packages are "known"(already provided), and for any other package installed with `pip`, that existing problem could  be known.

See https://github.com/oracle/graalpython/issues/228


https://stackoverflow.com/questions/68390276/run-python-in-graalvm-import-requests-fails-with-exception-you-need-either answer gives suggest to use `graalpython -m ginstall install requests` for anyone who runs into the same problem.

**Comment by rodrigar-mx** [comment]
@paulvi we will take your suggestion into account. Thank you for contributing to graalvm project.
