### ISSUE TITLE
`gu install python` fails, python is not in `gu available` for graalvm-ce-java16-21.1.0

### ISSUE THREAD

**Issue by paulvi** [oracle/graal#3600]
**Describe the issue**
I am trying latest GraalVM graalvm-ce-java11-21.1.0 and graalvm-ce-java16-21.1.0 on mac,
and they both fail to install Python 

```
gu install python
Downloading: Component catalog from www.graalvm.org
Error: Unknown component: python
```

https://www.graalvm.org/python/quickstart/ exactly says to use `gu install python`

`gu available` also does not show Python component:

```
$ gu available
Downloading: Component catalog from www.graalvm.org
ComponentId              Version             Component name                Stability                     Origin 
---------------------------------------------------------------------------------------------------------------------------------
llvm-toolchain           21.1.0              LLVM.org toolchain            Experimental                  github.com
native-image             21.1.0              Native Image                  Experimental                  github.com
nodejs                   21.1.0              Graal.nodejs                  Experimental                  github.com
R                        21.1.0              FastR                         Experimental                  github.com
wasm                     21.1.0              GraalWasm                     Experimental                  github.com
```

After installing llvm-toolchain (with `gu install llvm-toolchain`) that Python is dependent, Python is still not available.

**Steps to reproduce the issue**
Please include both build steps as well as run steps
1. get, install new GraalVM instance
2. `gu install python`

**Describe GraalVM and your environment:**
 -  GraalVM graalvm-ce-java11-21.1.0 and graalvm-ce-java16-21.1.0 on mac
 - JDK major version: **11 & 16**
 - OS: **macOS Catalina**
 - Architecture: **[e.g.: AMD64]**

**More details**
I guess this is some kind of network or downloads server issue, so I tag it as today 2021-7-18 17:00 UTC0

**Comment by rodrigar-mx** [comment]
Hi @paulvi. I have just downloaded and installed again graalvm 21.1.0 (java 11 based), and then installed llvm-toolchain + python with gu command on MacOS BigSur and did not have any problem. Let me investigate if there is any issue with Catalina version or it was a temporary server issue as you have already commented. Can you confirm your GraalVM Updater is 21.1.0 version.

**Comment by paulvi** [comment]
I have 2 Mac notebooks with Catalina, and it works OK on first one, then problem is on my second (home) one.
So Mac OS version should not be related.

On moth notebooks I am trying the latest 21.1 

```
gu --version
GraalVM Updater 21.1.0
```

I saw, 21.2 is expected within weeks, so I am going to see how different components will be updated

**Comment by paulvi** [comment]
I tried again, so it works in graalvm-ce-java11-21.1.0 and not in graalvm-ce-java16-21.1.0 (11 vs 16)

graalvm-ce-java11-21.1.0
```
pauls-mbp:~ paulverest$ which gu
/Users/paulverest/opt/graalvm-ce-java11-21.1.0/Contents/Home/bin/gu
pauls-mbp:~ paulverest$ gu list
ComponentId              Version             Component name                Stability                     Origin 
---------------------------------------------------------------------------------------------------------------------------------
graalvm                  21.1.0              GraalVM Core                  -                             
js                       21.1.0              Graal.js                      Supported                     
pauls-mbp:~ paulverest$ gu install
Missing filename(s) of component bundle(s) to install.
pauls-mbp:~ paulverest$ gu available
Downloading: Component catalog from www.graalvm.org
ComponentId              Version             Component name                Stability                     Origin 
---------------------------------------------------------------------------------------------------------------------------------
espresso                 21.1.0              Java on Truffle               Experimental                  github.com
llvm-toolchain           21.1.0              LLVM.org toolchain            Supported                     github.com
native-image             21.1.0              Native Image                  Early adopter                 github.com
nodejs                   21.1.0              Graal.nodejs                  Supported                     github.com
python                   21.1.0              Graal.Python                  Experimental                  github.com
R                        21.1.0              FastR                         Experimental                  github.com
ruby                     21.1.0              TruffleRuby                   Experimental                  github.com
wasm                     21.1.0              GraalWasm                     Experimental                  github.com
```

graalvm-ce-java16-21.1.0
```
which gu
/Users/paulverest/opt/graalvm-ce-java16-21.1.0/Contents/Home/bin/gu
Pauls-MacBook-Pro:~ paulverest$ gu list
ComponentId              Version             Component name                Stability                     Origin 
---------------------------------------------------------------------------------------------------------------------------------
graalvm                  21.1.0              GraalVM Core                  -                             
js                       21.1.0              Graal.js                      Experimental                  
llvm-toolchain           21.1.0              LLVM.org toolchain            Experimental                  github.com
Pauls-MacBook-Pro:~ paulverest$ gu available
Downloading: Component catalog from www.graalvm.org
ComponentId              Version             Component name                Stability                     Origin 
---------------------------------------------------------------------------------------------------------------------------------
llvm-toolchain           21.1.0              LLVM.org toolchain            Experimental                  github.com
native-image             21.1.0              Native Image                  Experimental                  github.com
nodejs                   21.1.0              Graal.nodejs                  Experimental                  github.com
R                        21.1.0              FastR                         Experimental                  github.com
wasm                     21.1.0              GraalWasm                     Experimental                  github.com
```

**Comment by rodrigar-mx** [comment]
Thank you @paulvi. GraalVM distributions based on Oracle JDK 16 and OpenJDK 16 are currently under development and provided for evaluation and testing purposes (see [known-issues](https://www.graalvm.org/release-notes/known-issues/)). The python extension is not available for JDK16 distributions. We suggest you using JDK11. 
Indeed, GraalVM 21.2.0 is released today (2021-07-20).

**Comment by paulvi** [comment]
From https://www.graalvm.org/release-notes/21_2/

> Java 16 support: GraalVM builds based on Oracle JDK 16 or OpenJDK 16 remain experimental in this release, but have become more “mature” by overcoming some known limitations and adding support for Ruby, Python, and WebAssembly runtimes.

So Python on JDK16-based GraalVM is from 21.2 only

**Comment by paulvi** [comment]
Though actually there's no downloads for java8 or java16 in https://github.com/graalvm/graalvm-ce-builds/releases/tag/vm-21.2.0

**Comment by rodrigar-mx** [comment]
Hi @paulvi. The CE builds for Java 8 and 16 will be published next week.

**Comment by paulvi** [comment]
Hooray

**Comment by timothy-sampair** [comment]
Why is it so painful to install  Python for GraalVM? I use to use "gu" but now that doesn't work and there is no instruction on how to install it. Anyone have an idea how to install it?
