### ISSUE TITLE
`gu` breaks on `21.3.0-dev` when installing manually using `sdkman` (likely symlink issue)

### ISSUE THREAD

**Issue by GavinRay97** [oracle/graal#3602]
**Describe GraalVM and your environment :**
```
openjdk 16.0.2 2021-07-20
OpenJDK Runtime Environment GraalVM CE 21.3.0-dev (build 16.0.2+7-jvmci-21.2-b05)
OpenJDK 64-Bit Server VM GraalVM CE 21.3.0-dev (build 16.0.2+7-jvmci-21.2-b05, mixed mode, sharing)
OpenJDK 64-Bit Server VM (16.0.2+7-jvmci-21.2-b05) for linux-amd64 JRE (16.0.2+7-jvmci-21.2-b05), built on Jun 25 2021 12:47:53 by "buildslave" with gcc 10.2.0
```

**Have you verified this issue still happens when using the latest snapshot?**
Yes

**Describe the issue**
Download the nightly release into some folder, let's say `~/Downloads`, and then untar it and attempt to use it:
```ps1
~/Downloads
❯ sdk install java 21.3.0.r16-grl ./21.3.0-dev.r16-grl
Linking java 21.3.0.r16-grl to /home/user/Downloads/./21.3.0-dev.r16-grl
Done installing!

~/Downloads
❯ sdk use java 21.3.0.r16-grl

Using java version 21.3.0.r16-grl in this shell.

~
❯ java --version
openjdk 16.0.2 2021-07-20
OpenJDK Runtime Environment GraalVM CE 21.3.0-dev (build 16.0.2+7-jvmci-21.2-b05)
OpenJDK 64-Bit Server VM GraalVM CE 21.3.0-dev (build 16.0.2+7-jvmci-21.2-b05, mixed mode, sharing)

~
❯ gu --help
Error: The GraalVM directory /home/user/Downloads is invalid.

~
❯ /home/user/.sdkman/candidates/java/21.3.0.r16-grl/bin/gu --help
Error: The GraalVM directory /home/user/Downloads is invalid.
```

**Expected behavior**
`gu` does not break

**Additional context**

If you install from another directory, the directory in the error message you get here:
```
Error: The GraalVM directory /home/user/Downloads is invalid.
```

Will always be the one you did `sdk install java` from.

**Comment by GavinRay97** [comment]
After looking at the code, what's happening is that it's silently defaulting to a set of behaviors, and those aren't allowing it to find what it needs. But the behavior seems very strange to me.

IE, I'm not sure how it's resolving the place where it was originally installed from by `sdkman` as the `graalPath` in this method:

https://github.com/oracle/graal/blob/89e4cfc7aeea69970b60c64cd075ceb2a104e864/vm/src/org.graalvm.component.installer/src/org/graalvm/component/installer/Bundle.properties#L59

https://github.com/oracle/graal/blob/89e4cfc7aeea69970b60c64cd075ceb2a104e864/vm/src/org.graalvm.component.installer/src/org/graalvm/component/installer/ComponentInstaller.java#L489-L498

https://github.com/oracle/graal/blob/89e4cfc7aeea69970b60c64cd075ceb2a104e864/vm/src/org.graalvm.component.installer/src/org/graalvm/component/installer/ComponentInstaller.java#L539-L544

So then setting `GRAALVM_HOME` fixes it. I guess the suggestion here would maybe be to expand the error message and say how the code tries to find Graal before throwing this error?

```ps1
~
❯ export GRAALVM_HOME=$HOME/.sdkman/candidates/java/current

~
❯ gu --help
Usage:
        gu info [-cClLnprstuvV] <param>         prints info about specific component (from file, URL or catalog)
        gu available [-aClvV] <expr>            lists components available in catalog
        gu install [-0CcDfiLMnosruvyxY] <param> installs a component package
```

**Comment by GavinRay97** [comment]
```properties
ERROR_InvalidGraalVMDirectory=The GraalVM directory {0} is invalid. 
A value for the GraalVM home directory is required, and could not be resolved through 
either the "GRAALVM_HOME" or "GRAAL_HOME" environment variables, or by checking the location of the executing JAR.
```

**Comment by mcraj017** [comment]
@GavinRay97 Thanks for reporting the issue
we will check it out and get back to you

**Comment by GavinRay97** [comment]
Hey @mcraj017 there's no issue here, it's more of a developer experience thing with the error message that is displayed (IMO)

I submitted a PR to fix this and signed the CLA after filing this issue:
https://github.com/oracle/graal/pull/3603

**Comment by mcraj017** [comment]
@GavinRay97 ok noted, thansk for the contribution

**Comment by MartinBalin** [comment]
GRAALVM_HOME will not be used by GU in 21.3.0

**Comment by Ondrej-Douda** [comment]
No longer an issue with GraalVM CE 22.1.0...
