### ISSUE TITLE
Graalvm EE - Fatal error in JVMCI

### ISSUE THREAD

**Issue by WarnDangerous** [oracle/graal#3610]
**Describe the issue**
Hello,
I'm new so I don't now if I can report issues with GraalVM EE.
I use Graalvm EE 21.1.0 Java 11 on a minecraft server using docker/pterodactyl and I sometimes get crashs with crash reports

**Describe GraalVM and your environment:**
 - GraalVM version **EE 21.1.0**
 - JDK major version: **11 for my server** (but docker is using java 16)
 Here are my server start : 
https://pastebin.com/Gpf2FCYu

 - OS: **Linux 10 (buster) kernel 5.12.11**
 - Architecture: **AMD64**

Server start : 
Crash Report : 
https://pastebin.com/0CXyEpk5

**Comment by mcraj017** [comment]
@WarnDangerous thanks for reporting the issue
Please share a reproducer

**Comment by mcraj017** [comment]
@WarnDangerous FYI we have released GraaalVM 21.2 this week, please try that too and let us know

**Comment by WarnDangerous** [comment]
I tried Graalvm EE 21.2, but it has some issues with "special caracters" such as accent é è à (I'm a french user) that transforms into caracter. It worked well on graalvm 21.1 EE.

Are you aware of this error ?
In this screenshot in "création" the é become a special caracter
https://cdn.discordapp.com/attachments/868164111354167366/868460140922294292/unknown.png

I'm using UTF-8 on a minecraft server.

(Should I open a new issue for this ?)

**Comment by WarnDangerous** [comment]
> @WarnDangerous thanks for reporting the issue
> Please share a reproducer

I don't get any reproducer sorry

**Comment by mcraj017** [comment]
@WarnDangerous thanks for the information
@dougxc please advise

**Comment by dougxc** [comment]
Hi @WarnDangerous , thanks for the report. The hs-err log shows that some kind of fatal error check in libgraal failed:
```
C  [libjvmcicompiler.so+0x63f598]  VMError_shouldNotReachHere_69b48699f21fae37d1b51c5c0e0abcfd77b28768+0x18
C  [libjvmcicompiler.so+0x949db7]  Thread_start_d043f016dd75eb113f895de55f2e129bad1ee51a+0x1a37
C  [libjvmcicompiler.so+0x10e6851]  LibGraalHotSpotGraalManagement_initialize_8e1118abbbe915766077a14932e0094f547e7563+0x691
```

We've only [recently](https://bugs.openjdk.java.net/browse/JDK-8269416) added support for capturing the error message printed by `VMError_shouldNotReachHere` in a hs-err file. In the version of GraalVM you are using, the message and extra libgraal crash data will be printed to the console. Do you have the console output from the time of the crash?

Also, I note that you are running GraalVM 21.1. We just released 21.2 last week so it would be interesting to know if the crash still occurs on 21.2.

**Comment by WarnDangerous** [comment]
> Also, I note that you are running GraalVM 21.1. We just released 21.2 last week so it would be interesting to know if the crash still occurs on 21.2.

As I told you, I got some issues with graalvm 21.2, so I can't use it, I write the errors upper, and also created another issue, hope it can be checked soon

**Comment by dougxc** [comment]
> also created another issue

Thanks - I just saw it now: #3627

**Comment by dougxc** [comment]
Tracked with: GR-32804

**Comment by WarnDangerous** [comment]
> > In the version of GraalVM you are using, the message and extra libgraal crash data will be printed to the console. Do you have the console output from the time of the crash?
> 
> @WarnDangerous have you seen this crash again recently and maybe have the console output?

Hello,

DIdn't get any crash since a month (using latest graalvm EE 21.2.0.1 java 11) ! :)
