### ISSUE TITLE
[web-site] Downloads from https://www.graalvm.org/downloads/21/ still point to 21.1.0

### ISSUE THREAD

**Issue by paulvi** [oracle/graal#3617]
Downloads from https://www.graalvm.org/downloads/21/ still point to  
https://github.com/graalvm/graalvm-ce-builds/releases/tag/vm-21.1.0
(page needs update to 21.2.0)

**Comment by mcraj017** [comment]
@paulvi thanks for reporting the issue
@olyagpl please check

**Comment by olyagpl** [comment]
That's fixed, https://www.graalvm.org/downloads/21, thanks!
