### ISSUE TITLE
Native image  with dependency netty

### ISSUE THREAD

**Issue by hoangvantu** [oracle/graal#3619]
I use spring native to build 
with error 

> Error: Classes that should be initialized at run time got initialized during image building:
 io.netty.util.concurrent.GlobalEventExecutor the class was requested to be initialized at run time (from jar:file:///C:/Users/ADMIN/.m2/repository/io/netty/netty-common/4.1.66.Final/netty-common-4.1.66.Final.jar!/META-INF/native-image/io.netty/common/native-image.properties and from the command line). To see why io.netty.util.concurrent.GlobalEventExecutor got initialized use --trace-class-initialization=io.netty.util.concurrent.GlobalEventExecutor
io.netty.buffer.PooledByteBufAllocator the class was requested to be initialized at run time (from jar:file:///C:/Users/ADMIN/.m2/repository/io/netty/netty-buffer/4.1.65.Final/netty-buffer-4.1.65.Final.jar!/META-INF/native-image/io.netty/buffer/native-image.properties). To see why io.netty.buffer.PooledByteBufAllocator got initialized use --trace-class-initialization=io.netty.buffer.PooledByteBufAllocator
io.netty.util.concurrent.ScheduledFutureTask the class was requested to be initialized at run time (from jar:file:///C:/Users/ADMIN/.m2/repository/io/netty/netty-common/4.1.66.Final/netty-common-4.1.66.Final.jar!/META-INF/native-image/io.netty/common/native-image.properties and from the command line). To see why io.netty.util.concurrent.ScheduledFutureTask got initialized use --trace-class-initialization=io.netty.util.concurrent.ScheduledFutureTask
io.netty.util.AbstractReferenceCounted the class was requested to be initialized at run time (from jar:file:///C:/Users/ADMIN/.m2/repository/io/netty/netty-common/4.1.66.Final/netty-common-4.1.66.Final.jar!/META-INF/native-image/io.netty/common/native-image.properties). To see why io.netty.util.AbstractReferenceCounted got initialized use --trace-class-initialization=io.netty.util.AbstractReferenceCounted
io.netty.buffer.ByteBufUtil the class was requested to be initialized at run time (from jar:file:///C:/Users/ADMIN/.m2/repository/io/netty/netty-buffer/4.1.65.Final/netty-buffer-4.1.65.Final.jar!/META-INF/native-image/io.netty/buffer/native-image.properties). To see why io.netty.buffer.ByteBufUtil got initialized use --trace-class-initialization=io.netty.buffer.ByteBufUtil
io.netty.channel.DefaultFileRegion the class was requested to be initialized at run time (subtype of io.netty.util.AbstractReferenceCounted and from the command line). To see why io.netty.channel.DefaultFileRegion got initialized use --trace-class-initialization=io.netty.channel.DefaultFileRegion
io.netty.util.concurrent.ImmediateEventExecutor the class was requested to be initialized at run time (from jar:file:///C:/Users/ADMIN/.m2/repository/io/netty/netty-common/4.1.66.Final/netty-common-4.1.66.Final.jar!/META-INF/native-image/io.netty/common/native-image.properties and from the command line). To see why io.netty.util.concurrent.ImmediateEventExecutor got initialized use --trace-class-initialization=io.netty.util.concurrent.ImmediateEventExecutor
io.netty.buffer.ByteBufAllocator the class was requested to be initialized at run time (from jar:file:///C:/Users/ADMIN/.m2/repository/io/netty/netty-buffer/4.1.65.Final/netty-buffer-4.1.65.Final.jar!/META-INF/native-image/io.netty/buffer/native-image.properties). To see why io.netty.buffer.ByteBufAllocator got initialized use --trace-class-initialization=io.netty.buffer.ByteBufAllocator

com.oracle.svm.core.util.UserError$UserException: Classes that should be initialized at run time got initialized during image building:
 io.netty.util.concurrent.GlobalEventExecutor the class was requested to be initialized at run time (from jar:file:///C:/Users/ADMIN/.m2/repository/io/netty/netty-common/4.1.66.Final/netty-common-4.1.66.Final.jar!/META-INF/native-image/io.netty/common/native-image.properties and from the command line). To see why io.netty.util.concurrent.GlobalEventExecutor got initialized use --trace-class-initialization=io.netty.util.concurrent.GlobalEventExecutor
io.netty.buffer.PooledByteBufAllocator the class was requested to be initialized at run time (from jar:file:///C:/Users/ADMIN/.m2/repository/io/netty/netty-buffer/4.1.65.Final/netty-buffer-4.1.65.Final.jar!/META-INF/native-image/io.netty/buffer/native-image.properties). To see why io.netty.buffer.PooledByteBufAllocator got initialized use --trace-class-initialization=io.netty.buffer.PooledByteBufAllocator
io.netty.util.concurrent.ScheduledFutureTask the class was requested to be initialized at run time (from jar:file:///C:/Users/ADMIN/.m2/repository/io/netty/netty-common/4.1.66.Final/netty-common-4.1.66.Final.jar!/META-INF/native-image/io.netty/common/native-image.properties and from the command line). To see why io.netty.util.concurrent.ScheduledFutureTask got initialized use --trace-class-initialization=io.netty.util.concurrent.ScheduledFutureTask
io.netty.util.AbstractReferenceCounted the class was requested to be initialized at run time (from jar:file:///C:/Users/ADMIN/.m2/repository/io/netty/netty-common/4.1.66.Final/netty-common-4.1.66.Final.jar!/META-INF/native-image/io.netty/common/native-image.properties). To see why io.netty.util.AbstractReferenceCounted got initialized use --trace-class-initialization=io.netty.util.AbstractReferenceCounted
io.netty.buffer.ByteBufUtil the class was requested to be initialized at run time (from jar:file:///C:/Users/ADMIN/.m2/repository/io/netty/netty-buffer/4.1.65.Final/netty-buffer-4.1.65.Final.jar!/META-INF/native-image/io.netty/buffer/native-image.properties). To see why io.netty.buffer.ByteBufUtil got initialized use --trace-class-initialization=io.netty.buffer.ByteBufUtil
io.netty.channel.DefaultFileRegion the class was requested to be initialized at run time (subtype of io.netty.util.AbstractReferenceCounted and from the command line). To see why io.netty.channel.DefaultFileRegion got initialized use --trace-class-initialization=io.netty.channel.DefaultFileRegion
io.netty.util.concurrent.ImmediateEventExecutor the class was requested to be initialized at run time (from jar:file:///C:/Users/ADMIN/.m2/repository/io/netty/netty-common/4.1.66.Final/netty-common-4.1.66.Final.jar!/META-INF/native-image/io.netty/common/native-image.properties and from the command line). To see why io.netty.util.concurrent.ImmediateEventExecutor got initialized use --trace-class-initialization=io.netty.util.concurrent.ImmediateEventExecutor
io.netty.buffer.ByteBufAllocator the class was requested to be initialized at run time (from jar:file:///C:/Users/ADMIN/.m2/repository/io/netty/netty-buffer/4.1.65.Final/netty-buffer-4.1.65.Final.jar!/META-INF/native-image/io.netty/buffer/native-image.properties). To see why io.netty.buffer.ByteBufAllocator got initialized use --trace-class-initialization=io.netty.buffer.ByteBufAllocator

	at com.oracle.svm.core.util.UserError.abort(UserError.java:68)
	at com.oracle.svm.hosted.classinitialization.ConfigurableClassInitialization.checkDelayedInitialization(ConfigurableClassInitialization.java:545)
	at com.oracle.svm.hosted.classinitialization.ClassInitializationFeature.duringAnalysis(ClassInitializationFeature.java:228)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$runPointsToAnalysis$14(NativeImageGenerator.java:765)
	at com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:71)
	at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:765)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:582)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$2(NativeImageGenerator.java:495)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Error: Image build request failed with exit status 1

**Comment by rodrigar-mx** [comment]
Hi @hoangvantu. Thank you for reporting the issue. Can you please provide more information about the execution environment (OS and graalvm), and share a reproducer.

**Comment by rodrigar-mx** [comment]
@hoangvantu  this issue will be closed because of inactivity for past months. 
*similar error was solved by adding the following flags:  `--initialize-at-run-time=io.netty.channel.epoll.Epoll,io.netty.channel.epoll.EpollEventLoop,io.netty.channel.epoll.Native,io.netty.channel.epoll.EpollEventArray,io.netty.channel.DefaultFileRegion,io.netty.channel.unix.Errors`
