### ISSUE TITLE
GraalVM Architecture Diagram image is broken on the website

### ISSUE THREAD

**Issue by alllex** [oracle/graal#3623]
**Describe the issue**
GraalVM Architecture Diagram image is broken on the website.

![image](https://user-images.githubusercontent.com/2759152/126901680-15560657-107a-4cb5-ad97-50fd9899fb44.png)

**More details**
It seems the link should be fixed in this document:
https://github.com/oracle/graal/blob/master/docs/introduction.md

**Comment by mcraj017** [comment]
@alllex thanks for reporting the issue
@olyagpl please check

**Comment by olyagpl** [comment]
Thank you, we fixed the image.
