### ISSUE TITLE
Error with accent on Graalvm EE 21.2 java 11

### ISSUE THREAD

**Issue by WarnDangerous** [oracle/graal#3627]
**Describe the issue**
I tried Graalvm EE 21.2 EE java 11, but it has some issues with "special caracters" such as accent é è à (I'm a french user) that randmoly transforms into special caracters. It worked well on graalvm 21.1 EE java 11.

Are you aware of this error ?
In this screenshot in "création" the é become a special caracter
https://cdn.discordapp.com/attachments/868164111354167366/868460140922294292/unknown.png

I'm using UTF-8 files on a minecraft server, the problem doesn't come from my files.

On Graalvm 21.2 EE java 16 it has NO issue
On Graalvm 21.1 EE java 16 it has NO issue
On Graalvm 21.1 EE java 16 it has NO issue

BUT
On Graalvm 21.2 EE java 11 the issue is here.

**Steps to reproduce the issue**
Run Graalvm 21.2 EE java 11 on a minecraft server (using papermc 1.16.5)

**Describe GraalVM and your environment:**
 - GraalVM version **EE 21.2.0**
 - JDK major version: **11**
 - OS: **Linux 10 (buster) kernel 5.12.11**
 - Architecture: **AMD64**

**More details**
It works well on Graalvm 21.2 Java 16, but not on the java 11 version.

**Comment by WarnDangerous** [comment]
Edit : 
- Even on graalvm 21.2 EE java 16 the error occurs, but less often.

**Comment by dougxc** [comment]
To narrow down if this is a Graal compiler issue, is it possible for you to see if it still reproduces with the `-XX:-UseJVMCICompiler` option?

In order to try reproducing, do you know what environment variables should be set to have the minecraft server use the French characters?

**Comment by dougxc** [comment]
Are the Java sources for the minecraft server you are using available?

**Comment by WarnDangerous** [comment]
> To narrow down if this is a Graal compiler issue, is it possible for you to see if it still reproduces with the -XX:-UseJVMCICompiler option?

I don't get the issue **without** -XX:-UseJVMCICompiler on Graalvm 21.1 EE java 11

**Comment by WarnDangerous** [comment]
> In order to try reproducing, do you know what environment variables should be set to have the minecraft server use the French characters?

I'm using this server.jar : 
https://ci.tivy.ca/view/Purpur/job/Airplane-Purpur-1.16/

- Graalvm 21.2
- And using accents ( é è ) in plugins ( for example in this plugin I had issues : https://github.com/BG-Software-LLC/SuperiorSkyblock2)

It's a bit weird to reproduce, as you don't use minecraft at all, but I don't know if there is a way to reproduce it on another environnement to make it easier to reproduce.

**Comment by dougxc** [comment]
> I don't get the issue without -XX:-UseJVMCICompiler on Graalvm 21.1 EE java 11

Ok, that does imply it might be a Graal compiler issue. However, there are also a lot of upstream changes from OracleJDK in 21.2 that were not in 21.1 so ruling them out would help.

**Comment by WarnDangerous** [comment]
> > I don't get the issue without -XX:-UseJVMCICompiler on Graalvm 21.1 EE java 11
> 
> Ok, that does imply it might be a Graal compiler issue. However, there are also a lot of upstream changes from OracleJDK in 21.2 that were not in 21.1 so ruling them out would help.

No sorry, I thought it was the other tickets (with my crashes) so I deleted my comment.
I'm trying right now to reproduce WITH and WITHOUT -XX:-UseJVMCICompiler

**Comment by WarnDangerous** [comment]
I get the issue WITH and WITHOUT 'XX:+EnableJVMCIProduct -XX:+EnableJVMCI -XX:+UseJVMCICompiler'

So I can't really help more :/

**Comment by WarnDangerous** [comment]
First it works, during 1-2 minutes, then it 'bugs' and it will everytime 'bug' and transform caracters

![Screenshot_5326](https://user-images.githubusercontent.com/31826333/127143262-a52642e1-935e-491f-859e-c9bc83326b23.png)

**Comment by dougxc** [comment]
> I get the issue WITH and WITHOUT 'XX:+EnableJVMCIProduct -XX:+EnableJVMCI -XX:+UseJVMCICompiler'

On GraalVM, those are the default values for those flags so unless you explicitly specify `-XX:-UseJVMCICompiler`, Graal will be used instead of C2.

It would really help if you can provide rough steps for us to try reproduce. I'm imagining you are doing something like:
```
$GRAALVM_HOME/bin/java -jar launcher-airplanepurpur.jar
# Start a minecraft client and attach to the server
# Randomly play minecraft for 1 or 2 minutes and wait for incorrect text to show up on console within minecraft
```
Is that right?

**Comment by WarnDangerous** [comment]
> # Randomly play minecraft for 1 or 2 minutes and wait for incorrect text to show up on console within minecraft
No, I use plugins.

I'll send an 'example' so you can test yourself

**Comment by dougxc** [comment]
> I'll send an 'example' so you can test yourself

Thanks. Please be sure to let me know the value of any relevant environment variables that select the French localization for the plugins.

**Comment by WarnDangerous** [comment]
I can't give a way to reproduce, seems it needs my full environnement to test :/

Do you get another way for me to debug that ? to provide more informations

**Comment by WarnDangerous** [comment]
> On GraalVM, those are the default values for those flags so unless you explicitly specify -XX:-UseJVMCICompiler, Graal will be used instead of C2.

Ohh okay !
So I added -XX:-UseJVMCICompiler, I don't get the issue anymore !

But when I remove -XX:-UseJVMCICompiler the error appear again.

**Comment by dougxc** [comment]
Here's some other things to try:

* Try disabling some of the [advanced optimizations](https://www.graalvm.org/reference-manual/java/options/#performance-tuning-options) (one at a time). Try these in particular, `-Dgraal.UsePriorityInlining=false`, `-Dgraal.Vectorization=false` and `-Dgraal.OptDuplication=true`.
* It may be possible to see which Graal compilation produces the unexpected behavior with `-XX:JVMCIThreads=1 -Dgraal.PrintCompilation=true`. That will serialize Graal compilation and print out the methods as they are compiled. You can watch the console output and see which compilations complete just before you start seeing the incorrect characters. If we're lucky, we may be able to isolate it to just a few methods or even a single method. Then `-Dgraal.GraalCompileOnly` can be used to restrict Graal compilation to just these methods. The syntax for this option is described [here](https://raw.githubusercontent.com/oracle/graal/master/compiler/src/org.graalvm.compiler.debug/src/org/graalvm/compiler/debug/doc-files/MethodFilterHelp.txt). The goal is to isolate the Graal compilation(s) that cause the problem and then capture graphs for them. For example, if the compilation of `com.foo.Bar.someMethod` is a suspect, the graph for this method is captured with `-Dgraal.Dump=:2 -Dgraal.MethodFilter=com.foo.Bar.someMethod`.

**Comment by dougxc** [comment]
Another option to try is `-Dgraal.CompilerConfiguration=community` which will let us know if it's really an EE specific problem.

**Comment by WarnDangerous** [comment]
> Another option to try is `-Dgraal.CompilerConfiguration=community` which will let us know if it's really an EE specific problem.

I tried this flag, I don't get the issue anymore, so it's EE only

**Comment by WarnDangerous** [comment]
I tried -XX:JVMCIThreads=1 -Dgraal.PrintCompilation=true

wrote /ééèààîïïîi 

and it returned : 
![Screenshot_5331](https://user-images.githubusercontent.com/31826333/127157017-8eaf0fc3-00f0-42a3-8b50-e55164c5238b.png)

Here are the logs : 
https://pastebin.com/5rzqbCij

**Comment by WarnDangerous** [comment]
With -Dgraal.UsePriorityInlining=false
I still get the error.

With -Dgraal.Vectorization=false
I still get the error

With -Dgraal.OptDuplication=true
I still get the error

**Comment by dougxc** [comment]
I'm not 100% sure how to interpret https://pastebin.com/5rzqbCij. Are you saying that the badly formatted output is correlated with the second INFO line:
```
[14:54:02 INFO]: <WarnD> ./ééèààîïïîi 
```
If so, then I would suspect these compilations:
```
HotSpotCompilation-39980       Lorg/mineacademy/chatcontrol/lib/TimedCharSequence;                    charAt                                        (I)C                                                | 1059us   294B bytecodes   381B codesize
HotSpotCompilation-39982       Lcom/google/gson/Gson;                                                 fromJson                                      (Lcom/google/gson/stream/JsonReader;Ljava/lang/reflect/Type;)Ljava/lang/Object;  | 14164us  2288B bytecodes  4664B codesize
```
Could you now try this: `-Dgraal.GraalCompileOnly=TimedCharSequence.charAt,Gson.fromJson`

**Comment by WarnDangerous** [comment]
> I'm not 100% sure how to interpret https://pastebin.com/5rzqbCij. Are you saying that the badly formatted output is correlated with the second INFO line:
> 
> [14:54:02 INFO]: <WarnD> ./ééèààîïïîi 

I'm not native french so I tried to understand what you said, but the "./ééèààîïïîi" is the input, not the output I saw.
The output is the screen just under

**Comment by dougxc** [comment]
Ignore the rest of my message if you don't understand. Please just try `-Dgraal.GraalCompileOnly=TimedCharSequence.charAt,Gson.fromJson` to see if the error still reproduces.

**Comment by WarnDangerous** [comment]
> -Dgraal.GraalCompileOnly=TimedCharSequence.charAt,Gson.fromJson

I don't get the issue anymore with this flag

**Comment by WarnDangerous** [comment]
With -Dgraal.OptDuplication=false
I still get the issue.

I joined stack (I'm named 'Emilien Raclot')

**Comment by dougxc** [comment]
@mur47x111 has determined this is most likely fixed by `-Dgraal.OptStringConcat=false`. Please let me know if he is correct.

**Comment by WarnDangerous** [comment]
> @mur47x111 has determined this is most likely fixed by `-Dgraal.OptStringConcat=false`. Please let me know if he is correct.

I tried many times, didn't see the issue (on the test I show you on zoom), I hope the issue won't appear in another form.

Did you find the issue on your side ? So you can fixes it for next release

**Comment by dougxc** [comment]
Yes, it's almost certainly related to the `StringBuilderOptimizationPhase` mentioned at https://www.graalvm.org/release-notes/21_2/#java-and-compiler-updates

**Comment by dougxc** [comment]
Tracked with: GR-32848

**Comment by WarnDangerous** [comment]
Possible to get a release that fixes the issue UNTIL October with the 21.3 ?

**Comment by dougxc** [comment]
Yes, we will get a fix into 21.3.

**Comment by WarnDangerous** [comment]
It's possible to get a release until 21.3 ? Just to get this issue fixed without java flags ?

**Comment by dougxc** [comment]
It should be possible but I cannot give a time estimate right now.

**Comment by WarnDangerous** [comment]
Thanks a lot, hope it can be soon 👍

**Comment by WarnDangerous** [comment]
I did some tests, it seems fixed on 21.2.0.1, I'll keep you informed if it occurs again 👍

**Comment by luxjava** [comment]
I wrote this:

**// campo39: DefaultTableModel se è una JTable**

ans I received the following error im java 21.0.2:

**testWinGenMagaz.java:349: error: unmappable character (0xE8) for encoding UTF-8
// campo39: DefaultTableModel se ? una JTable**

_But it was just a comment!!!!_

**Comment by 13572864374** [comment]
[自动回复] copilot交流群:891721335,文档下载:https://wwht.lanzouu.com/b01rnnfvg密码:fbys
