### ISSUE TITLE
Interoperability Java + LLVM

### ISSUE THREAD

**Issue by joaofouyer** [oracle/graal#3644]
**Describe GraalVM and your environment :**
 - GraalVM version or commit id if built from source: GraalVM CE 21.1.0
 - CE or EE: CE
 - JDK version: JDK11
 - OS and OS Version: Ubuntu 20.04.2
 - Architecture: amd64
 - The output of `java -Xinternalversion`: 
```
OpenJDK 64-Bit Server VM (11.0.11+8-jvmci-21.1-b05) for linux-amd64 JRE (11.0.11+8-jvmci-21.1-b05), built on Apr 12 2021 15:17:53 by "buildslave" with gcc 7.3.0
```

**Have you verified this issue still happens when using the latest snapshot?**
Yes.

**Describe the issue**
Reading [the docs](https://www.graalvm.org/reference-manual/llvm/Interoperability/) I could see an example of Interoperability of LLVM and Javascript. I wonder if I could do the with Java and LLVM, and how. I tried to run the same C code in the example, but could not compile successfully the Java code.

**Code snippet or code repository that reproduces the issue**
```c
// cpart.c
#include <graalvm/llvm/polyglot.h>

#include <stdlib.h>
#include <stdio.h>

struct Point {
    double x;
    double y;
};

POLYGLOT_DECLARE_STRUCT(Point)

void *allocNativePoint() {
    struct Point *ret = malloc(sizeof(*ret));
    return polyglot_from_Point(ret);
}

void *allocNativePointArray(int length) {
    struct Point *ret = calloc(length, sizeof(*ret));
    return polyglot_from_Point_array(ret, length);
}

void freeNativePoint(struct Point *p) {
    free(p);
}

void printPoint(struct Point *p) {
    printf("Point<%f,%f>\n", p->x, p->y);
}
```

```java
PolyglotInteroperability
public class PolyglotInteroperability {
    public static void main(String[] args) throws IOException {
        File file = new File("cpart.so"); // the path to the file
        Source source = Source.newBuilder("llvm", file).build();
        Context polyglot = Context.newBuilder().allowAllAccess(true).build();
        Value cpart = polyglot.eval(source);

        cpart.allocNativeClock(); //doesn't compile

    }
}

```

If possible, where could I find some examples or instructions to so? Thanks in advance!

**Comment by oubidar-Abderrahim** [comment]
> cpart.allocNativeClock(); //doesn't compile

Java is not quite as dynamic as JavaScript, try with `cpart.getMember("allocNativePoint").execute()`, that should work

you can check the example on the docs as well: https://www.graalvm.org/reference-manual/llvm/Interoperability/#embedding-in-java
