### ISSUE TITLE
Pass arguments from Java (start language) to LLVM (C++) target language

### ISSUE THREAD

**Issue by joaofouyer** [oracle/graal#3645]
**Describe GraalVM and your environment :**
 - GraalVM version or commit id if built from source:  21.1.0
 - CE or EE: CE
 - JDK version:  JDK11
 - OS and OS Version: Ubuntu 20.04.2
 - Architecture: amd64
 - The output of `java -Xinternalversion`:
```
OpenJDK 64-Bit Server VM (11.0.11+8-jvmci-21.1-b05) for linux-amd64 JRE (11.0.11+8-jvmci-21.1-b05), built on Apr 12 2021 15:17:53 by "buildslave" with gcc 7.3.0
```

**Have you verified this issue still happens when using the latest snapshot?**
Yes

**Describe the issue**
Ì'm trying to pass some arguments from Java (start language) to LLVM (C++) as target language. I followed the tutorial [in the docs](https://docs.oracle.com/en/graalvm/enterprise/19/guide/reference/polyglot-programs.html), changed it to pass some arguments with a help from [Roland Schatz](https://app.slack.com/client/TN37RDLPK/CP6RTC4LT/user_profile/UPDJW3W00) on GraalVM Slack Workspace and got it working, but it isn't performing as desired because I need to rebuild and re-evaluate every time the argument changes (and it will change a hundred times per second). Then how could I only pass the arguments without rebuild or evaluating every time it changes?

The example, that consumes around a seconds to rebuild and re-evaluate every time the argument changes:

**C++ Target Language (in a separeted file called polyglot.cpp)**

```cpp
#include <iostream>
using namespace std;
int main(int argc, char** argv){
    cout << "You have entered " << argc << " arguments:" << "\n";
    for (int i = 0; i < argc; ++i) cout << argv[i] << "\n";   
    return 0;
}
```

**Java - Start Language**
```java
public class HelloPolyglot {
    public static void main(String[] args) throws IOException {
        File file = new File("polyglot"); 
        Source source = Source.newBuilder("llvm", file).build();
        String[] args = {"hello", "world"};
        Context polyglot = Context.newBuilder().arguments("llvm", args).allowAllAccess(true).build();
        Value cpart = polyglot.eval(source);
        cpart.executeVoid();
    }
}
```
I tried to pass the arguments in executeVoid or execute method, but it throws `Exception in thread "main" org.graalvm.polyglot.PolyglotException: java.lang.ClassCastException: class java.lang.String cannot be cast to class com.oracle.truffle.llvm.runtime.pointer.LLVMPointerImpl (java.lang.String is in module java.base of loader 'bootstrap'; com.oracle.truffle.llvm.runtime.pointer.LLVMPointerImpl is in unnamed module of loader com.oracle.graalvm.locator.GraalVMLocator$GuestLangToolsLoader @5f150435)`

```java
public class HelloPolyglot {
    public static void main(String[] args) throws IOException {
        File file = new File("polyglot"); // the path to the file
        Source source = Source.newBuilder("llvm", file).build();

        String[] arguments = {"hello", "world", "42"};
        Context polyglot = Context.newBuilder().allowAllAccess(true).build();
        Value cpart = polyglot.eval(source);
        Value withArguments = cpart.getMember("main");
        withArguments.execute(1, arguments);
    }
}
```

**Comment by rodrigar-mx** [comment]
Hi @joaofouyer. I will take a closer look to it and get back to you.

**Comment by rodrigar-mx** [comment]
I will close this issue. @joaofouyer please feel free to reopen the issue or create a new one for any other inquiry or any problem implementing the proposed solutions.
