### ISSUE TITLE
Provide a Github Action

### ISSUE THREAD

**Issue by aalmiray** [oracle/graal#3650]
**Feature request**

**Is your feature request related to a problem? Please describe.**
Building applications with Graal and Graal Native Image on a GitHub Actions workflow requires some setup. There are (at the moment) 4 3rd-party options https://github.com/marketplace?type=actions&query=graal+ with https://github.com/DeLaGuardo/setup-graalvm being the most popular so far.

**Describe the solution you'd like.**
An official GH action that sets up Graal and Graal Native Image. Note, Windows runners require one extra step to set up `cl.exe`.

**Describe who do you think will benefit the most.**
Everyone building with GH actions.

**Describe alternatives you've considered.**
https://github.com/DeLaGuardo/setup-graalvm but requires using https://github.com/ilammy/msvc-dev-cmd on Windows runners. See https://github.com/kcctl/kcctl/blob/main/.github/workflows/early-access.yml

**Express whether you'd like to help contributing this feature**
I love to test drive the feature 😄

**Comment by dzou** [comment]
+1 to this. Our company is interested in incorporating native image unit testing into our GHA workflows for a large number of projects using the GraalVM [Native Build Tools](https://github.com/graalvm/native-build-tools).

During our prototyping we've used one of the community-contributed actions, but it would be very helpful to have an officially supported one for more security and maintenance.

**Comment by zakkak** [comment]
FWIW Ubuntu 20.04 based github runners include GraalVM see https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-README.md#graalvm

**Comment by fniephaus** [comment]
Good news: we're working on a GitHub Action for setting up GraalVM, Native Image, and other components.
Please join the discussion and updates at https://github.com/oracle/graal/discussions/4150.

**Comment by aalmiray** [comment]
@fniephaus thank you for opening a discussion topic. Just a matter of how the team handles issues and discussions. Strictly speaking this is still an open issue as no fix has been supplied nor a final decisions to say FIX or WONTFIX has been posted.

Having an open discussion to brainstorm possible solutions is not IMHO a reason to close an issue. If your intention is to move all discussions to the Discussion topic then you'd also have to mark this issue as read-only so that further comments are no longer allowed at this location.

Then again, that still leaves the issue unresolved until a decision has been reached.

**Comment by fniephaus** [comment]
Hi @aalmiray, you are of course correct. This issue has not yet been resolved yet. Nonetheless, I'd like to have the discussion around a GitHub Action in one place. So as per your suggestion, I am going to reopen the issue and mark is as read-only.

**Comment by fniephaus** [comment]
@aalmiray Please give [the new GitHub Action for GraalVM](https://github.com/marketplace/actions/github-action-for-graalvm) a try and file any issues or feature requests [here](https://github.com/graalvm/setup-graalvm/issues).

Marking this issue as resolved now...
