### ISSUE TITLE
Please clarify the license issue for native-image.

### ISSUE THREAD

**Issue by jc-lab** [oracle/graal#3651]
Related Issues:
* https://github.com/devonfw-forge/devonfw-microservices/issues/44
* https://github.com/oracle/graal/issues/389

The license for binaries generated as native-images on the site or in the LICENSE file is not clear.
If I make Java code into a native shared library through native-image and use this library in an "application", is this "application" affected by the GPL?

I hope it has been added to the faq.

(Please change the label from bug to feature request.)

**Comment by christianwimmer** [comment]
We are not allowed to discuss, interpret, or "clarify" license terms. The LICENSE file https://github.com/oracle/graal/blob/master/substratevm/LICENSE is the one and only thing that matters. If you have legal questions, you need to consult with your company lawyer.

One important note though: you wrongly state that GraalVM Native Image is licensed under the GPL. It is licensed under "GPL with Classpath Exception", which is a crucial difference.
