### ISSUE TITLE
[Documentation] Would it be possible to add how jruby may relate to GraalVM at https://www.graalvm.org/why-graalvm/#for-ruby-r-python-or-webassembly ?

### ISSUE THREAD

**Issue by rubyFeedback** [oracle/graal#3661]
Hey graal-folks,

I picked "feature request", but this is more a documentation request, so I was not sure under which issue template to file this; I did not find "documentation" or something like that. Hope that is still ok.

Before I explain this documentation-request, allow me to just briefly comment the background:

- I have been using ruby since about 15 years or so, give or take. I am using java since about 2 years or so; still quite a noob though. JRuby is a logical step past that point. Ok that's the brief background. :)

GraalVM is quite in hype in the last some months IMO. You can see it being mentioned several times, on reddit and elsewhere. My own "logical" path/steps are, while maintaining my ruby-projects, to improve my java skills and work with jruby too. So now I am asking myself "where/how does GraalVM fit into this".

You have quite a lot of documentation already as-is:

See https://www.graalvm.org/why-graalvm/#for-ruby-r-python-or-webassembly

But reading the documentation takes time so I have to do this in smaller steps; like 20 minutes, then have to do something else, repeat at a later time. Not sure how others approach this but I found I am more efficient when I capture new information in smaller steps. Anyway.

Right now the documentation shows this:

"At this point in time, we can run simpler applications of Ruby, R, and Python but we do not have the same full compatibility we provide for Java and Node.js applications"

And naturally, I wonder how jruby, if at all, taps into this. Does GraalVM make jruby obsolete or vice versa? I could ask at the jruby issue tracker but I think headius is already mega-busy so I don't want to ask there and distract. They need all the time to work on more recent ruby versions! Last supported one is ruby 2.5 right now, I am using ruby 3.0.x. :D

So my request would be:

- Could perhaps a sentence or a paragraph be added to that subsection mentioning jruby? If it may still have a use case or not? How it may fit in? Right now I am wondering whether I may need jruby if I could just run ruby on GraalVM (and java, anyway). This is a genuine question by the way, not a "loaded" or "testing" question - I'd really like to know from an objective point of view. Currently I simply don't know either way.

Thanks for reading anyway!

PS: It does not need to be a lengthy explanation, just if someone has time to write a sentence or two and perhaps add it to the official documentation. And I understand that it may be of lower priority compared to other things, totally fine.

**Comment by oubidar-Abderrahim** [comment]
Hi @rubyFeedback, Thank you for taking the time to reach to us about this.

About your question, GraalVM's Ruby implementation is called TruffleRuby which is technically a competitor of JRuby, it doesn't make much sense to use both technologies together unless you're doing a performance benchmarking (in which case TruffleRubby will be victorious :slightly_smiling_face: ) 

So basically, you can use Ruby directly with TruffleRuby and GraalVM without the need for JRuby or any knowledge of Java in general. And you will get better performance. 

You can check https://www.graalvm.org/ruby/ at the bottom of the page you can see the Optcarrot benchmark and the Rubycon benchmark, and TruffleRuby is around 4 times faster than JRuby.

Hope this clarifies things for you, if you still have questions please ask.
