### ISSUE TITLE
java.lang.NoSuchFieldError: java.awt.Component.x when built from .jar, not when built from .class

### ISSUE THREAD

**Issue by ScottAtManta** [oracle/graal#3669]
Starting with a simple java class involving AWT, package in a jar and native-image with that jar as the classpath. Program raises `NoSuchFieldError`. Same program works fine built with native-image from the class file rather than from a JAR.

I originally encountered the problem while using native-image on a much larger project, with a few JARs. I was able to reproduce it using a simple class, by creating a JAR containing that class.

**Steps to reproduce the issue**
Obtain Light.java from https://github.com/ScottAtManta/scottg_public_misc/tree/main/graaltest/light

Build class and jar. Use the agent to create META-INF using the jar:
```
javac Light.java
jar cf lightjar.jar *.class
java -agentlib:native-image-agent=config-output-dir=META-INF/native-image -cp lightjar.jar Light
# Now you have META-INF related to the class, and a JAR containing the class
```

Build native from the class file:
```
native-image --native-image-info --verbose --no-fallback --report-unsupported-elements-at-runtime -H:+ReportExceptionStackTraces -Djava.awt.headless=false Light
# ./light works
```

Build native from the JAR:
```
time native-image --native-image-info --verbose --no-fallback --report-unsupported-elements-at-runtime -H:+ReportExceptionStackTraces -Djava.awt.headless=false -cp lightjar.jar Light
# Run fails
$ ./light
Exception in thread "main" java.lang.NoSuchFieldError: java.awt.Component.x
        at com.oracle.svm.jni.functions.JNIFunctions$Support.getFieldID(JNIFunctions.java:1126)
        at com.oracle.svm.jni.functions.JNIFunctions.GetFieldID(JNIFunctions.java:428)
        at java.awt.Component.initIDs(Component.java)
        at java.awt.Component.<clinit>(Component.java:624)
        at java.lang.Class.ensureInitialized(DynamicHub.java:548)
```
**Version info**
My version info (Ubuntu 18.04 on WSL):
```
$ cat /proc/version
Linux version 4.4.0-19041-Microsoft (Microsoft@Microsoft.com) (gcc version 5.4.0 (GCC) ) #488-Microsoft Mon Sep 01 13:43:00 PST 2020
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.3 LTS
Release:        18.04
Codename:       bionic
$ java -version
openjdk version "11.0.12" 2021-07-20
OpenJDK Runtime Environment GraalVM CE 21.3.0-dev (build 11.0.12+5-jvmci-21.3-b01)
OpenJDK 64-Bit Server VM GraalVM CE 21.3.0-dev (build 11.0.12+5-jvmci-21.3-b01, mixed mode, sharing)
$ java -Xinternalversion
OpenJDK 64-Bit Server VM (11.0.12+5-jvmci-21.3-b01) for linux-amd64 JRE (11.0.12+5-jvmci-21.3-b01), built on Jul 16 2021 17:18:18 by "buildslave" with gcc 7.3.0
```

**More details**

Output from the native-image runs is here: 
https://github.com/ScottAtManta/scottg_public_misc/tree/main/graaltest/light/native-image-output

The file "goodbuild.txt" was captured while building from the class file and "badbuild.txt" was captured while building from the jar file.

**Comment by oubidar-Abderrahim** [comment]
Hi, Thank you for reporting this, we will look into it and get back to you.

**Comment by oubidar-Abderrahim** [comment]
Hi, I tested the reproducer locally and managed to run the native image in both cases successfully.

the `Exception in thread "main" java.lang.NoSuchFieldError: java.awt.Component.x` is related to missing configuration
this is due to using `-cp Lightjar.jar`, which excluded META-INF/native-image from the build.

You can fix this either by using `-cp Lightjar.jar:.` to include the current directory, or explicitly provide the configuration directory using `-H:ConfigurationFileDirectories=META-INF/native-image`
