### ISSUE TITLE
[native-image] Document the prerequisites for native-image on linux.

### ISSUE THREAD

**Issue by sureshg** [oracle/graal#368]
I created a new VM on digital ocean and download the Graal CE 1.0.0 RC1. Getting following errors when trying to generate a native-image for my application jar.

* `gcc` not found. Had to install it manually.

```# graalvm-1.0.0-rc1/bin/native-image -jar secrets-cli-1.0.4-uber.jar
Build on Server(pid: 24973, port: 26681)*
   classlist:   8,541.74 ms
       (cap):     604.84 ms
       setup:   1,851.50 ms
fatal error: com.oracle.svm.core.util.VMError$HostedError: java.io.IOException: Cannot run program "gcc" (in directory "/tmp/SVM-6654701256180913937"): error=2, No such file or directory
	at com.oracle.svm.core.util.VMError.shouldNotReachHere(VMError.java:68)
	at com.oracle.svm.hosted.c.codegen.CCompilerInvoker.compileAndParseError(CCompilerInvoker.java:83)
```

* `zlib` not found.

```[root@centos-7-sfo-01 ~]# graalvm-1.0.0-rc1/bin/native-image -jar secrets-cli-1.0.4-uber.jar
Build on Server(pid: 24973, port: 26681)
   classlist:   3,538.37 ms
       (cap):   1,873.92 ms
       setup:   2,165.85 ms
error: Error compiling query code (in /tmp/SVM-7354486464663256205/PosixDirectives.c). Compiler command  gcc /tmp/SVM-7354486464663256205/PosixDirectives.c -o /tmp/SVM-7354486464663256205/PosixDirectives output included error: /tmp/SVM-7354486464663256205/PosixDirectives.c:60:18: fatal error: zlib.h: No such file or directory
    C file contents around line 60:
    /tmp/SVM-7354486464663256205/PosixDirectives.c:59: #include <unistd.h>
    /tmp/SVM-7354486464663256205/PosixDirectives.c:60: #include <zlib.h>
    /tmp/SVM-7354486464663256205/PosixDirectives.c:61: #include <arpa/inet.h>
```

If these are the prerequisites for running `native-image`, it would be great to add this details to the documentation.

**Comment by shelajev** [comment]
Thank you for reporting it! I added it to the native-images [page](http://www.graalvm.org/docs/reference-manual/aot-compilation/).

**Comment by thomaswue** [comment]
Can we also change the error message in addition to documenting it better? @olpaw

**Comment by olpaw** [comment]
> Can we also change the error message in addition to documenting it better?

Fixed in https://github.com/oracle/graal/commit/6ff678ac8d5c48cc57ddb0fc1681dceb29fcd635

**Comment by dougxc** [comment]
Maybe in a follow up change you can augment the missing dependency error message with an os-dependent hint such as `This may be resolvable with "yum install .<package name(s)>"` or `This may be resolvable with `brew install <package name(s)>`. This is what the [configure step does when building the JDK](http://hg.openjdk.java.net/jdk/jdk/file/1da3a463a499/make/autoconf/help.m4#l60) and is very helpful.

**Comment by olpaw** [comment]
I don't think this is a good idea. Do we really want to get into maintaining os-dependent hints in a simple help message. On Linux alone i can think of at least 5 distribution-specifc variants (think of Fedora, Arch, Suse, Debian/Ubuntu, Centos, ....). Also this info changes over time. On Fedora it used to be yum now it's dnf. I think a brief generic description is the better choice here.

**Comment by dougxc** [comment]
How often do you think the hint will have to change? I doubt very often at all and the support in JDK seems very straightforward. Seems like a small investment for improving an initial first impression but I leave the final call up to you.
