### ISSUE TITLE
Upgrade javacpp-preset llvm version >= 1.5.3

### ISSUE THREAD

**Issue by Berstanio** [oracle/graal#3684]
**Feature request**

Please include the following information:

**Is your feature request related to a problem? Please describe.**
Currently for substratevm and the llvm backend the javacpp(-presets) version 1.5.2 is used. This version didn't include the "DebugInfo.h" header of the llvm-c api into the generation of the bindings. That makes generating debug information for the llvm backend pretty hard. 

**Describe the solution you'd like.**
It would be great if it is possible to upgrade the javacpp version to 1.5.3 or higher. In this versions the DebugInfo.h header is included.

**Describe who do you think will benefit the most.**
I think developers of libraries or frameworks which depend on the native-image generation will benefit the most. They could use the llvm compiler backend and then debug the programm with meaningful debug information (when the debug info generation is also implemented).

**Describe alternatives you've considered.**
I tried to add debug info with the current methods but when researching about it I always ended up reading "use the c++ api" or "it isn't possible" so if I didn't miss something I think the specific methods are needed to generate debug information.

**Express whether you'd like to help contributing this feature**
I couldn't find any open source script that generates the presets for graalvm and building the presets for myself was hard because of the different packages so I wasn't able to test this. But if there is a more or less easy possibility for me to test the new presets version for emitting debug info I could do it and this could proof the usability of this feature.

**Comment by christianwimmer** [comment]
@Berstanio We do not have many resources on the LLVM backend right now, so I don't know when we can get to this.

Can you give it a try to update to the latest version? If it is just a minor version update, I would hope it is not too difficult.

**Comment by Berstanio** [comment]
Yes I can give it a second try. The last time I failed was because mx didn't picked up my updated dependencies correctly. Maybe I get it this time working. I will post here whether I managed to update this or where I failed, right?

**Comment by christianwimmer** [comment]
> I will post here whether I managed to update this or where I failed, right?

Correct. And when you have a working fix, please open a pull request and link it to this issue.

**Comment by oubidar-Abderrahim** [comment]
fixed by 2b22a926c03037cfaa91bd58966dd1792af86f46
