### ISSUE TITLE
Graal's JIT compiler is not used even though the necessary flags are passed

### ISSUE THREAD

**Issue by boris-petrov** [oracle/graal#3704]
**Describe GraalVM and your environment :**
 - GraalVM version or commit id if built from source: **21.2.0**
 - CE or EE: **CE**
 - JDK version: **JDK 16**
 - OS and OS Version: **Arch Linux 5.13.12-arch1-1**
 - Architecture: **amd64**
 - The output of `java -Xinternalversion`:
```
OpenJDK 64-Bit Server VM (16.0.2+7) for linux-amd64 JRE (16.0.2+7), built on Jul 22 2021 03:33:00 by "builduser" with gcc 11.1.0
```

**Have you verified this issue still happens when using the latest snapshot?**
No.

**Describe the issue**
Graal's JIT compiler is not used even though the necessary flags are passed.

**Code snippet or code repository that reproduces the issue**
https://github.com/boris-petrov/graal-tomcat-bug

**Steps to reproduce the issue**
Clone the repo. Copy-paste the commands from the README in the terminal. Check the `apache-tomcat-9.0.52/logs/catalina.out` file - you'll see `WARNING: The polyglot context is using an implementation that does not support runtime compilation.` inside.

**Expected behavior**
The warning should not be there.

**Additional context**
[Here's](https://graalvm.slack.com/archives/CN9L59P61/p1629722846024000) a relevant thread in Slack.

cc @chumer

**Comment by chumer** [comment]
I haven't started Tomcat in a while. This was a fun ride into memory land for me ;-) 

The problem is that Tomcat creates subclass loaders that cannot Truffle cannot properly look through. I don't think this is fixable for us. So Tomcat itself needs to be booted up with Truffle. You are already trying this correctly by setting module-path and upgrade-module-path correctly in setenv.sh:
```
export CATALINA_OPTS="$CATALINA_OPTS  -Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=8000 -XX:+UnlockExperimentalVMOptions -XX:+EnableJVMCI -XX:-UseJVMCICompiler --module-path=$(pwd)/apache-tomcat-$TOMCAT_VERSION/webapps/company/graal-compiler --upgrade-module-path=$(pwd)/apache-tomcat-$TOMCAT_VERSION/webapps/company/graal-compiler"
```

However the problem is that the same jar files are also located in WEB-INF/lib which gets picked up by Tomcat. The jars in WEB-INF/lib cannot see graal so Graal cannot be used and you get the warning.

I could fix this problem by removing all Graal/Truffle related jars from WEB-INF/lib.


Here is my recommendation for a layout inside Tomcat:
`webapps/company/module-path` contains the following files:
```
icu4j-69.1.jar
js-21.2.0.jar
regex-21.2.0.jar
```

webapps/company/upgrade-module-path
```
compiler-21.2.0.jar
compiler-management-21.2.0.jar
graal-sdk-21.2.0.jar
truffle-api-21.2.0.jar
```
Make sure there are no such jars in `WEB-INF/lib`.

And then you can use the following setenv.sh like this:
```
export CATALINA_OPTS="$CATALINA_OPTS  -Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=8000 -XX:+UnlockExperimentalVMOptions -XX:+EnableJVMCI -XX:-UseJVMCICompiler --module-path=$(pwd)/apache-tomcat-$TOMCAT_VERSION/webapps/company/module-path --upgrade-module-path=$(pwd)/apache-tomcat-$TOMCAT_VERSION/webapps/company/upgrade-module-path"
```

This prints correctly in catalina.out:
```
=== Graal.js via org.graalvm.polyglot.Context === 
warming up ...
warmup finished, now measuring
iteration: 126
iteration: 119
iteration: 127
iteration: 120
iteration: 122
iteration: 109
iteration: 122
iteration: 130
iteration: 109
iteration: 127
=== Graal.js via javax.script.ScriptEngine ===
*** Graal.js not found ***
=== Nashorn via javax.script.ScriptEngine ===
Warning: Nashorn engine is planned to be removed from a future JDK release
warming up ...
warmup finished, now measuring
iteration: 169
iteration: 172
iteration: 178
iteration: 178
iteration: 179
iteration: 174
iteration: 170
iteration: 177
iteration: 176
iteration: 177
23-Aug-2021 18:24:00.089 INFO
```

**Comment by chumer** [comment]
This was the output with JDK 11. This is the output with JDK 16:
```
=== Graal.js via org.graalvm.polyglot.Context === 
warming up ...
warmup finished, now measuring
iteration: 116
iteration: 108
iteration: 110
iteration: 114
iteration: 119
iteration: 124
iteration: 111
iteration: 114
iteration: 119
iteration: 127
=== Graal.js via javax.script.ScriptEngine ===
*** Graal.js not found ***
=== Nashorn via javax.script.ScriptEngine ===
*** Nashorn not found ***
```

**Comment by boris-petrov** [comment]
@chumer - thanks a lot for digging in this and finding a solution! It does indeed work. I'm not sure I completely understand why it doesn't work in the first place - I would guess it is somehow related to the fact that the JARs are available on the classpath instead of the modulepath... but in any case, your idea works fine.

Just a question - I guess I'll go the easy road and just put all these JARs in the same directory, remove them from `lib` and point `module-path` and `upgrade-module-path` to that dir. That's also fine, right? I guess you recommend different directories for "safety" but it's not *really* necessary, right?

Thank you again!

**Comment by boris-petrov** [comment]
For completeness' sake and for future readers, this is my final `build.gradle`:

```gradle
plugins {
	id 'war'
}

repositories {
	mavenCentral()
}

configurations {
	graal
}

ext.graalVmVersion = '21.2.0'

dependencies {
	compileOnly "org.graalvm.sdk:graal-sdk:$graalVmVersion"

	implementation 'org.apache.tomcat:tomcat-catalina:9.0.52'

	graal "org.graalvm.compiler:compiler:$graalVmVersion"
	graal "org.graalvm.compiler:compiler-management:$graalVmVersion"
	graal "org.graalvm.sdk:graal-sdk:$graalVmVersion"
	graal "org.graalvm.truffle:truffle-api:$graalVmVersion"
	graal "org.graalvm.js:js:$graalVmVersion"
}

def graalCompilerDir = "$buildDir/graal-compiler"

tasks.register('prepareGraalCompiler', Copy) {
	doFirst {
		delete graalCompilerDir
	}

	into graalCompilerDir
	from configurations.graal
}

war {
	dependsOn prepareGraalCompiler

	from(configurations.graal) {
		into 'graal-compiler'
	}

	classpath "${buildDir}/classes"

	duplicatesStrategy = DuplicatesStrategy.FAIL
	archiveFileName = 'company.war'
}
```

Note how 1) I've added a `compileOnly` dependency on `graal-sdk` (as I don't want Gradle putting it in as a classpath dependency at runtime); 2) I've added all needed Graal dependencies to the `graal` configuration which then goes into a `graal-compiler` directory inside the WAR. And then I can point Tomcat to it by setting the following in `bin/setenv.sh`:

```sh
export CATALINA_OPTS="$CATALINA_OPTS -XX:+UnlockExperimentalVMOptions -XX:+EnableJVMCI -XX:-UseJVMCICompiler --module-path=/apache-tomcat-directory/webapps/company/graal-compiler --upgrade-module-path=/apache-tomcat-directory/webapps/company/graal-compiler"
```
