### ISSUE TITLE
Missing darwin java8 binaries for community edition in sdkman

### ISSUE THREAD

**Issue by justhecuke** [oracle/graal#3730]
New darwin builds are not being made for java8 and, while GitHub has an archive for 21.0.0.2's darwin java8 binary, sdkman does not have that binary anymore.

Darwin users who rely on sdkman for version management can no longer use GraalVM if they require java 8.

Fix would be to publish 21.0.0.2's darwin java8 binary so that sdkman users can still have access to a java 8 binary.

**Comment by rodrigar-mx** [comment]
Hi @justhecuke. I will check it out and get back to you.

**Comment by rodrigar-mx** [comment]
Hi @justhecuke. As you already noticed, we will no longer provide jdk8 support for the community, so we strongly suggest you moving to jdk 11 based versions. However, you can download older versions in github for dev and testing. On the other hand, we  are not responsible for sdkman distributions, hence, you should ask sdkman this particular question. Thanks for using GraalVM.
