### ISSUE TITLE
“graalvm-ce-java16-21.2.0” cannot be opened because the developer cannot be verified. (graalvm-ce-java11-21.2.0 without such problem)

### ISSUE THREAD

**Issue by madeinquant** [oracle/graal#3731]
**Describe the issue**
Installed both versions “graalvm-ce-java16-21.2.0" and "graalvm-ce-java11-21.2.0", "graalvm-ce-java11-21.2.0" is able to be launched normally. Unfortunately,  “graalvm-ce-java16-21.2.0" cannot be launched and encounter this error message in a popup dialog box “graalvm-ce-java16-21.2.0” cannot be opened because the developer cannot be verified.

Hardware : MacBook Pro (Retina, 15-inch, Late 2013)
OS : OSX 11.5.2

**On JAVA_HOME Command**

```
$ /usr/libexec/java_home -V
Matching Java Virtual Machines (6):
    16.0.2 (x86_64) "Oracle Corporation" - "Java SE 16.0.2" /Library/Java/JavaVirtualMachines/jdk-16.0.2.jdk/Contents/Home
    16.0.2 (x86_64) "GraalVM Community" - "GraalVM CE 21.2.0" /Library/Java/JavaVirtualMachines/graalvm-ce-java16-21.2.0/Contents/Home
    11.0.12 (x86_64) "GraalVM Community" - "GraalVM CE 21.2.0" /Library/Java/JavaVirtualMachines/graalvm-ce-java11-21.2.0/Contents/Home
    11.0.8 (x86_64) "AdoptOpenJDK" - "AdoptOpenJDK 11" /Library/Java/JavaVirtualMachines/adoptopenjdk-11.jdk/Contents/Home
    1.8.301.09 (x86_64) "Oracle Corporation" - "Java" /Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home
    1.8.0_112 (x86_64) "Oracle Corporation" - "Java SE 8" /Library/Java/JavaVirtualMachines/jdk1.8.0_112.jdk/Contents/Home
/Library/Java/JavaVirtualMachines/jdk-16.0.2.jdk/Contents/Home

```

1. After decompress these archives, copy both decompressed directory in the directory /Library/Java/JavaVirtualMachines/.

2. update $HOME/.bash_profile

```
export JAVA_HOME=/Library/Java/JavaVirtualMachines/graalvm-ce-java11-21.2.0/Contents/Home
export GRAALVM_HOME=/Library/Java/JavaVirtualMachines/graalvm-ce-java11-21.2.0/Contents/Home

#export JAVA_HOME=/Library/Java/JavaVirtualMachines/graalvm-ce-java16-21.2.0/Contents/Home
#export GRAALVM_HOME=/Library/Java/JavaVirtualMachines/graalvm-ce-java16-21.2.0/Contents/Home

export PATH=${GRAALVM_HOME}/bin:${PATH}

```
2. remove the quarantine attribute  

```
sudo xattr -r -d com.apple.quarantine /Library/Java/JavaVirtualMachines/graalvm-ce-java11-21.2.0/Contents/Home
sudo xattr -r -d com.apple.quarantine /Library/Java/JavaVirtualMachines/graalvm-ce-java16-21.2.0/Contents/Home

```
3. Activating an environment  (JAVA_HOME and GRAALVM_HOME are pointing to java11)
`source $HOME/.bash_profile 
`
4. When JAVA_HOME and GRAALVM are pointing to java11, it works normally.

```
$ java --version
openjdk 11.0.12 2021-07-20
OpenJDK Runtime Environment GraalVM CE 21.2.0 (build 11.0.12+6-jvmci-21.2-b08)
OpenJDK 64-Bit Server VM GraalVM CE 21.2.0 (build 11.0.12+6-jvmci-21.2-b08, mixed mode, sharing)
```

5. update $HOME/.bash_profile again

```
#export JAVA_HOME=/Library/Java/JavaVirtualMachines/graalvm-ce-java11-21.2.0/Contents/Home
#export GRAALVM_HOME=/Library/Java/JavaVirtualMachines/graalvm-ce-java11-21.2.0/Contents/Home

export JAVA_HOME=/Library/Java/JavaVirtualMachines/graalvm-ce-java16-21.2.0/Contents/Home
export GRAALVM_HOME=/Library/Java/JavaVirtualMachines/graalvm-ce-java16-21.2.0/Contents/Home

export PATH=${GRAALVM_HOME}/bin:${PATH}

```

6. Activating an environment again  (JAVA_HOME and GRAALVM_HOME are pointing to java16)
`source $HOME/.bash_profile 
`
7.  When JAVA_HOME and GRAALVM are pointing to java16, “graalvm-ce-java16-21.2.0" cannot be launched and encounter this error message in a popup dialog box “graalvm-ce-java16-21.2.0” cannot be opened because the developer cannot be verified.

**Comment by oubidar-Abderrahim** [comment]
Thank you for reporting this, we will take a look into it

**Comment by oubidar-Abderrahim** [comment]
I tried it on Catalina and it works fine, might be specific to BigSur. I'll try to acquire a BigSur for testing, is it possible for you to test on macOS Catalina to be sure?

**Comment by madeinquant** [comment]
> I tried it on Catalina and it works fine, might be specific to BigSur. I'll try to acquire macOS BigSur for testing, is it possible for you to test on macOS Catalina just to be sure?

Sorry, I have a Macbook only. My Macbook has been upgraded to 11.5.2.

**Comment by rodrigar-mx** [comment]
Hi @madeinquant. I have macOS Big Sur 11.5.1 and I have no problem with neither graalvm versions. You probably have done it, but please try download it again and verify its sha code. Also check that in System Preferences > Security & Privacy you have checked "Allow apps download from App Store and identified developers". In same menu, when you execute the java command an alert message will appear where you can click the button "Open Anyway".

**Comment by fniephaus** [comment]
Sorry for the inconvenience, @madeinquant! This is related to #1724 and the fix is simple: you must run the `sudo xattr ...` command against the root of your GraalVM installation (not against `../Contents/Home`):

```bash
sudo xattr -r -d com.apple.quarantine /Library/Java/JavaVirtualMachines/graalvm-ce-java11-21.2.0
sudo xattr -r -d com.apple.quarantine /Library/Java/JavaVirtualMachines/graalvm-ce-java16-21.2.0
```

Please re-open this issue if you need further assistance.

**Comment by madeinquant** [comment]
Thanks for your comment.

**Comment by fniephaus** [comment]
You are welcome! :)
