### ISSUE TITLE
Dynamic Proxy configuration does not support the definition of unordered interfaces

### ISSUE THREAD

**Issue by arielcarrera** [oracle/graal#3735]
**Describe the issue**
When you define a manual dynamic proxy, interfaces in array need some kind of ordering. 
If you interchange items position you get an exception like this:
> Caused by: com.oracle.svm.core.jdk.UnsupportedFeatureError: Proxy class defined by interfaces [interface org.springframework.web.bind.anno tation.RequestMapping, interface org.springframework.core.annotation.SynthesizedAnnotation] not found.

If you use a configuration like this it doesn't works:
```
[[
    "org.springframework.core.annotation.SynthesizedAnnotation",
    "org.springframework.web.bind.annotation.RequestMapping"
  ]]
```
instead if your configuration is like this it works:
```
[[
    "org.springframework.web.bind.annotation.RequestMapping",
    "org.springframework.core.annotation.SynthesizedAnnotation"
  ]]
```

So some kind of order defined by the code is required and the docs doesn't talk about it [(https://www.graalvm.org/reference-manual/native-image/DynamicProxy/#manual-configuration](https://www.graalvm.org/reference-manual/native-image/DynamicProxy/#manual-configuration)).

So I think that some kind of mention in docs about this could be cool enough to avoid developers defining manually bad configurations.

**Steps to reproduce the issue**
Please include both build steps as well as run steps
1.  add a custom manual dynamic proxy configuration with a proxy for two or more interfaces
2. try building images with different ordering in items in the array and running them

**Describe GraalVM and your environment:**
 - GraalVM 21.2.0 (spring native paketo buildpack)
 - JDK major version: 11
 - OS: Windows 10
 - Architecture: Intel x64

**Comment by oubidar-Abderrahim** [comment]
Thank you for reporting this, we will take a look into it

**Comment by oubidar-Abderrahim** [comment]
Hi, is it possible to provide a reproducer I can run to test this?

**Comment by arielcarrera** [comment]
> Hi, is it possible to provide a reproducer I can run to test this?

As I said in the first comment, I think that it's not a bug. A.Clement (spring-native) made me realise that it's the expected behavior because the list of interfaces needs an order due to how the java dynamic proxy api works.
By the way, maybe it could be explained in the GraalVm documentation [Dynamic Proxy - manual configuration section](https://www.graalvm.org/reference-manual/native-image/DynamicProxy/#manual-configuration).

When it says:
> Dynamic proxy classes can be generated at native image build time by specifying the list of interfaces that they implement. 

Maybe it could be:
> Dynamic proxy classes can be generated at native image build time by specifying the list of interfaces that they implement.
> Note that the order of the specified proxy interfaces is significant: two requests for a proxy class with the same combination of interfaces but in a different order will result in two distinct proxy classes. (for more detailed information, please refer to [creating proxy class](https://docs.oracle.com/javase/7/docs/technotes/guides/reflection/proxy.html) or [proxy javadocs](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/reflect/Proxy.html#newProxyInstance(java.lang.ClassLoader,java.lang.Class%5B%5D,java.lang.reflect.InvocationHandler)))

**Comment by olyagpl** [comment]
@arielcarrera, thanks for suggestion. It was followed, https://github.com/oracle/graal/blob/master/docs/reference-manual/native-image/DynamicProxy.md#manual-configuration.
