### ISSUE TITLE
--exclude-config not working when provided after -jar

### ISSUE THREAD

**Issue by galderz** [oracle/graal#3742]
~`exclude-config` is not working when the metadata to be excluded is within classpath jar files referenced by the runnable jar (e.g. via the manifest). In this case, the exclusions are queried before `exclude-config` parameter has been parsed.~

Update: the real issue is that the order of of `--exclude-config` and `-jar` can cause exclude-config not to be applied. Checks for exclusion happen while processing `-jar`, so if `--exclude-config` is provided after that, it will be ignored. A temporary workaround is to provide `--exclude-config` before `-jar`, but a better solution is needed that is not relying on the order in which parameters are given.

Issue is present in the latest GraalVM CE release, 21.2.0.

Please assign this to me.

**Comment by olpaw** [comment]
See https://github.com/oracle/graal/pull/3749#issuecomment-913479146
