### ISSUE TITLE
Add JFR events for the garbage collector

### ISSUE THREAD

**Issue by jiekang** [oracle/graal#3743]
As title says. It would be nice to have events to cover configuration, pauses, heap and metaspace data.

**Comment by jiekang** [comment]
@christianhaeubl @christianwimmer 

Hi! We'll be looking to add these. However there is one significant blocker at the moment, the location of code:

JFR is in com.oracle.svm.jfr
GC is in com.oracle.svm.core.genscavenge

How do you envision JFR events are added to core functionality, including more than the GC? Do we move the 'native' bits into `com.oracle.svm.core.jfr`? Or maybe expose some kind of listener API for core pieces similar to `com.oracle.svm.core.thread.ThreadListenerSupport`?

**Comment by christianwimmer** [comment]
@jiekang The GC projects (like `genscavenge`) should implement the JFR support directly without any further indirection. I think this can be achieved fairly easily by splitting the current `com.oracle.svm.jfr` project into a `com.oracle.svm.core.jfr` and `com.oracle.svm.hosted.jfr` part. The `core` part depends only on the `svm.core` project, and then `genscavenge` can depend on `svm.core.jfr`.

Looking at the source code (but without doing any refactoring myself), I think there are very few parts that need to be in `svm.hosted.jfr`. I see `JfrFeature` and `JfrEventSubstitution` have imports from `svm.hosted`, but nothing else.

**Comment by fernando-valdez** [comment]
Native JFR event support changes merged from this PR https://github.com/oracle/graal/pull/3770
