### ISSUE TITLE
Classes loaded through HostClassLoader do not return ProtectionDomains

### ISSUE THREAD

**Issue by kustosz** [oracle/graal#3744]
**Describe GraalVM and your environment :**
 - GraalVM version or commit id if built from source: **21.1.0**
 - CE or EE: **CE**
 - JDK version: **JDK11**
 - OS and OS Version: **MacOS Big Sur**
 - Architecture: **amd64**
 - The output of `java -Xinternalversion`:
```
 **OpenJDK 64-Bit Server VM (11.0.11+8-jvmci-21.1-b05) for bsd-amd64 JRE (11.0.11+8-jvmci-21.1-b05), built on Apr 12 2021 09:12:59 by "graal1" with gcc 4.2.1 Compatible Apple LLVM 10.0.0 (clang-1000.11.45.5)**
```

**Have you verified this issue still happens when using the latest snapshot?**
You can find snapshot builds here: https://github.com/graalvm/graalvm-ce-dev-builds/releases
No.

**Describe the issue**
Certain libraries (such as the Amazon Redshift JDBC Driver) depend strongly on `Class.getProtectionDomain()` returning a non-null result, but the `HostClassLoader` does not set it up. Supporting this would really help with full compatibility with the java ecosystem.

**Code snippet or code repository that reproduces the issue**
js:
```js
Java.addToClasspath('redshift-jdbc42-2.0.0.7.jar');
Java.addToClasspath('proxy');
var proxy = Java.type('JdbcProxy');
proxy.getConnection('jdbc:redshift://fake-cluster.fake-host.us-west-1.redshift.amazonaws.com:5439/fake_db');
```
java:
```java
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;

public class JdbcProxy {
  public static Connection getConnection(String url) throws SQLException {
    if (!com.amazon.redshift.jdbc.Driver.isRegistered()) {
      com.amazon.redshift.jdbc.Driver.register();
    }
    return DriverManager.getConnection(url);
  }
}
```
**Steps to reproduce the issue**
1. Download the [Redshift Driver Jar](https://s3.amazonaws.com/redshift-downloads/drivers/jdbc/2.0.0.7/redshift-jdbc42-2.0.0.7.jar)
2. Create a directory called `proxy` next to the downloaded jar. Place the java snippet above in it, in a file called `JdbcProxy.java`.
3. Enter the `proxy` directory and run `javac -cp ../redshift-jdbc42-2.0.0.7.jar JdbcProxy.java`
4. Place the JS snippet next to the jar and `proxy` directories and run it with `js --polyglot repro.js`

Note that it fails with:
```
java.lang.NullPointerException
        at com.amazon.redshift.Driver.getJdbcIniFile(Driver.java:877)
        at com.amazon.redshift.Driver.connect(Driver.java:258)
        at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
        at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:251)
        at JdbcProxy.getConnection(JdbcProxy.java:10)
        at <js> :program(repro.js:4:118-224)
```
[The line it fails on](https://github.com/aws/amazon-redshift-jdbc-driver/blob/master/src/main/java/com/amazon/redshift/Driver.java#L877) is:
```java
  			String filePath = Driver.class.getProtectionDomain().getCodeSource().getLocation().getPath();					
```
Which assumes a non-null location (the call to `getPath()` is what actually fails here).

**Expected behavior**
The line in question working without a problem. Note that the repro given in this issue will definitely fail further down the line, probably with a `NoClassDefFound`, due to non-included dependencies.

**Comment by tzezula** [comment]
Fixed in master https://github.com/oracle/graal/commit/51a681f6320e1abec4c27772907f96881b81115a.

**Comment by tzezula** [comment]
Back-ported into graalvm 21.3.
