### ISSUE TITLE
Lambda functions serialization is not supported

### ISSUE THREAD

**Issue by filozof50** [oracle/graal#3756]
Lambda functions serialization is currently not supported in GraalVM native-image because of unstable hash values of lambdas (unstable names). There are 2 possible solutions for this problem.

##### Solution 1:

Add lambdas to serialization configuration by their hash value (name).
Problem with this approach is that even small changes (re-ordering the code or small changes) can lead to problems in serialization.

Example:
```java
public class Write {
    public static void main(String[] args) throws IOException, ClassNotFoundException {
        testComparators();
    }

    private static void testComparators() throws IOException, ClassNotFoundException {
        SerializableDoubleFunction func = new SerializableDoubleFunction(5);
        Comparator<Integer> comp = Comparator.comparingDouble(func);
        serializeObject(comp);
    }

    private static void serializeObject(Object o) throws IOException, ClassNotFoundException {
        FileOutputStream fileOutputStream = new FileOutputStream("serialized.txt");
        ObjectOutputStream objectOutputStream = new ObjectOutputStream(fileOutputStream);
        objectOutputStream.writeObject(o);
        objectOutputStream.close();
    }
}

class SerializableDoubleFunction implements Serializable, ToDoubleFunction<Integer> {
    private final double value;
    
    public SerializableDoubleFunction(double inputValue) {
        value = inputValue;
    }

    @Override
    public double applyAsDouble(Integer o) {
        return value;
    }
}
```

```java
public class Write {
    public static void main(String[] args) throws IOException, ClassNotFoundException {
        testComparators();
        testComparators();
    }

    private static void testComparators() throws IOException, ClassNotFoundException {
        SerializableDoubleFunction func = new SerializableDoubleFunction(5);
        Comparator<Integer> comp = Comparator.comparingDouble(func);
        serializeObject(comp);
    }

    private static void serializeObject(Object o) throws IOException, ClassNotFoundException {
        FileOutputStream fileOutputStream = new FileOutputStream("serialized.txt");
        ObjectOutputStream objectOutputStream = new ObjectOutputStream(fileOutputStream);
        objectOutputStream.writeObject(o);
        objectOutputStream.close();
    }
}

class SerializableDoubleFunction implements Serializable, ToDoubleFunction<Integer> {
    private final double value;
    
    public SerializableDoubleFunction(double inputValue) {
        value = inputValue;
    }

    @Override
    public double applyAsDouble(Integer o) {
        return value;
    }
}
```

Hash value of the second lambda is changed when adding new lambda instance of the same kind above. This is a breaking change, because serialization configuration does not work anymore. 

##### Solution 2:

Lambdas are serialized and deserialized in special maner. Every lambda function has $writeReplace$ method which is being used to serialize lambda by replacing it with the instance of SerializedLambda class.
For deserialization, method $deserializeLambda$ from every lambda capturing class is used. (In the example ). We can add capturing classes of lambda functions present in the code to serialization configuration as following:

`"lambdaCapturingClass":capturingClassName`

##### Configuration file example:
```
[
  {
    "name":"SerializableDoubleFunction"
  },
  {
    "name":"java.lang.Object[]"
  },
  {
    "name":"java.lang.String"
  },
  {
    "name":"java.lang.invoke.SerializedLambda"
  },
  {
    "name":"java.util.Comparator"
  },
  {
    "lambdaCapturingClass":"java.util.Comparator"
  }
]
```
For every reachable lambda that is being captured by some of the registered classes, we should register proper method for reflection, to be able to serialize every lambda instance needed. Metod used for serialization is automatically generated method during build and is also member of lambda instance.
Since we know all the capturing classes of interest (from the serialization configuration file), during native image build, we can also register proper methods used for deserialization of lambda instances from those classes. Described methods are also automatically generated during build and delegated to those classes in runtime.

This solution is not dependent on the hash values of lambdas, but on the lambda instances and capturing classes (saved in cofiguration).

**Comment by zhfeng** [comment]
Sine the potential fix https://github.com/oracle/graal/commit/b455f23b624a1af149c7d5769443a4775bedd087 has been included in graalvm-ce 22.1.0, this issue could be resolved or is there anything else need to concern?
