### ISSUE TITLE
Corrupted array values after JIT compilation

### ISSUE THREAD

**Issue by TheMode** [oracle/graal#3783]
**Describe the issue**
I was generating arrays using https://github.com/Minestom/Minestom/blob/master/src/main/java/net/minestom/server/utils/chunk/ChunkUtils.java#L164 which is a pure method and noticed that it failed after some time using graal JIT but worked perfectly with openjdk 17

**Steps to reproduce the issue**
Run https://github.com/TheMode/GraalBugReport/blob/master/src/main/java/fr/themode/report/Main.java with GraalVM, possibly a second time with hotspot

You should see `Not found [-2, -1, -8589934592, -8589934591, -8589934590, -2, -1, -4294967296, -4294967295, -4294967294, -2, -1, 0, 1, 2, -2, -1, 4294967296, 4294967297, 4294967298, -2, -1, 8589934592, 8589934593, 8589934594]`

I tried to isolate the issue further but haven't been able to reproduce with everything on the same class.

**Describe GraalVM and your environment:**
 - GraalVM version: EE 21.2.0.1
 - JDK major version: 11
 - OS: Windows 11
 - Architecture: AMD64 (i7-10875h)

**Comment by davleopo** [comment]
@TheMode  thanks for the report and reproducer. We are looking into it.

**Comment by gergo-** [comment]
We have merged the fix for this bug, it should no longer appear in the upcoming 21.3 release. Please reopen the issue if you see this problem again.
Thanks again for the report and the excellent reproducer!
