### ISSUE TITLE
Graal JS devtools debug: Cannot remote debugging via the Internet

### ISSUE THREAD

**Issue by chenjie100** [oracle/graal#3800]
I want to debug Graal JS through the Internet in devtools, similar to the following URL:
devtools://devtools/bundled/js_app.html?ws=oracle.com:4242/aa/bb
But no success

In the line of code [builder.option("inspect", url)], only localhost/LAN IP can succeed, but the Internet domain name and IP cannot succeed.

The following is the test code:

`import org.graalvm.polyglot.Context;

public class Test {

	public static void main(String[] args) {
		

        var builder = Context.newBuilder();
		builder.allowAllAccess(true);
		builder.option("js.strict", "true");
		builder.option("js.intl-402", "true");
		builder.option("js.foreign-object-prototype", "true");

                builder.option("inspect", "localhost:4242"); // success, but cannot debug via the Internet
		builder.option("inspect", "192.168.0.108:4242"); //success, but cannot debug via the Internet
                builder.option("inspect", "oracle.com:4242"); //failed, throw "Cannot assign requested address: NET_Bind"
                builder.option("inspect", "137.254.120.50:4242"); //failed, throw "Cannot assign requested address: NET_Bind"

		builder.option("inspect.Path", "aa/bb");
		builder.option("inspect.Secure", "false");
		builder.option("inspect.Suspend", "false");
		builder.option("inspect.WaitAttached", "true");
		var context = builder.build();
                context.eval("js","debugger;let a=3;\nlet b=4;");
                context.close();
	}

}`

**Comment by mcraj017** [comment]
@chenjie100 thanks for reporting the issue, please share the GraalVM version you are using
Please try latest build and let us know, if you still face the issue
https://github.com/graalvm/graalvm-ce-dev-builds/releases/tag/21.3.0-dev-20210914_2058

**Comment by fniephaus** [comment]
Instead of exposing your debugger sessions to the internet, why not use remote port forwarding via SSH?

**Comment by chenjie100** [comment]
@fniephaus thanks a lot

**Comment by fniephaus** [comment]
You are welcome. It is much safer to work with an SSH tunnel. Can this issue be closed?
