### ISSUE TITLE
[Regression] Micronaut Redis app stuck at runtime

### ISSUE THREAD

**Issue by ilopmar** [oracle/graal#3820]
**Describe the issue**

Our CI has detected a regression this morning with the Redis application. It is possible to build the native image but when sending a request it gets stuck.
I've been trying a few things and this happens even if no Redis class is involved during the execution, just having it on the classpath (the Lettuce driver). I've also setup the Micronaut log to `TRACE` to try to find where it is getting stuck and nothing is shown when I send a curl request that just returns a "Hello World" message.

The Friday execution worked ok with commit 2b19e3a74839139f86fc6e53bf26fbe1b153f0c4 and this morning it failed with cd693b9452d728536b9a5e208dd889ad30536273. This is a diff between those two commits: https://github.com/oracle/graal/compare/2b19e3a74839139f86fc6e53bf26fbe1b153f0c4..cd693b9452d728536b9a5e208dd889ad30536273

**Steps to reproduce the issue**

- `git clone https://github.com/micronaut-graal-tests/micronaut-redis-graal`
- `cd micronaut-redis-graal`
- `git checkout redis-freeze`
- Use GraalVM compiled from source code
- `./gradlew nativeImage`
- `./build/native-image/redis`
- `curl localhost:8080/hello`

Nothing is shown on the log and the curl request gets stuck. If you start the application with `./gradlew run` and send the same curl request you will see a lot of log messages.

**Describe GraalVM and your environment:**
 - GraalVM version: **cd693b9452d728536b9a5e208dd889ad30536273**
 - JDK major version: **11**
 - OS: **Linux**
 - Architecture: **AMD64**

**Comment by rodrigar-mx** [comment]
Hi @ilopmar. I will take a closer look into it, and report the bug if necessary. Any updates or questions I will let you know.

**Comment by rodrigar-mx** [comment]
I have reported this issue with the native-image team. They will respond you accordingly.

**Comment by ilopmar** [comment]
Now the PR with the fix have been merged, I've tried compiling from master branch and it now works. Closing this issue. Thanks!
