### ISSUE TITLE
Linked Identity HashMap?

### ISSUE THREAD

**Issue by senderic** [oracle/graal#3823]
I see the following class was developed in Nov 2014, however I don't think it is part of the master branch or part of the JAR on mvncentral.

https://github.com/oracle/graal/blob/86f9ead4d5ade316c5953a1210df6a6cb9e272fe/graal/com.oracle.graal.compiler.common/src/com/oracle/graal/compiler/common/remote/LinkedIdentityHashMap.java#L34

I am in need of an IdentityHashMap that is ordered by insertion, so this class may be right up my ally. I am wondering what the history of it is? Is there a reason it never got lumped in to master? I suppose I could always just copy the code as it were my own, but just wondering of any details. 

Tagging @dougxc as he committed this code.

**Comment by dougxc** [comment]
This was part of an experiment to add replay compilation support to Graal. Unfortunately, it never panned out.

**Comment by esend7881** [comment]
I made a class that accomplishes this here: https://gist.github.com/esend7881/aa5c1d26753205b6bd0d3af64e86234b I credit StackOverflow but what I have here works in my projects (tests, etc).
