### ISSUE TITLE
Propagate annotations for constructor parameter types of node classes to generated code

### ISSUE THREAD

**Issue by fcurts** [oracle/graal#3826]
We use JSR-305 nullability annotations in the Java code of our Truffle language. Specifically, we annotate nullable method parameter types with our own `@Nullable` annotation, which is itself annotated with JSR-305 annotations. The nullability annotations are leveraged by IntelliJ and the Kotlin compiler.

Even though we annotate nullable constructor parameter types of our Truffle node classes, the corresponding static factory methods generated by the DSL processor no longer carry these annotations, causing many nullability related warnings. It would be great if the DSL processor could propagate constructor parameter type annotations to the corresponding factory methods.

**Comment by chumer** [comment]
@fcurts  thanks for there report. since we are not using the Nullable annotation ourselves, would you mind posting a small example so we can verify the feature with the expected behavior?

**Comment by fcurts** [comment]
Here is a contrived example. Let me know if this is good enough.

Nullable.java (uses Maven dependency com.google.code.findbugs:jsr305:3.0.2):
```java
import java.lang.annotation.*;
import javax.annotation.Nonnull;
import javax.annotation.meta.TypeQualifierNickname;
import static javax.annotation.meta.When.MAYBE;

@Target(ElementType.TYPE_USE)
@Retention(RetentionPolicy.RUNTIME)
@Documented
@Nonnull(when = MAYBE)
@TypeQualifierNickname
public @interface MyNullable {}
```

MyAdditionNode.java:
```java
public abstract class MyAdditionNode extends MyBinaryExpressionNode {
  private final @MyNullable String someString; // used for something (not shown here)
  
  protected MyAdditionNode(@MyNullable String someString) {
    this.someString = someString;
  }
  
  @Specialization
  protected long evaluate(long left, long right) {
    return left + right;
  }
}
```

MyAstBuilder.java:
```java
...
// WARNING: passing null argument to parameter annotated with @NotNull
// (note: method parameter types default to @NotNull if not annotated)
var node = MyAdditionNodeGen.create(null, leftChild, rightChild); 
```

**Comment by chumer** [comment]
@fcurts impl is ready would be great if you have time verify it.
https://github.com/oracle/graal/pull/3832

**Comment by chumer** [comment]
Implemented in master. Will land in 22.0.
