### ISSUE TITLE
JDK test java/security/Policy/SignedJar/SignedJarTest.java fails with GraalVM 21.2.0 and OpenJDK 11.0.12

### ISSUE THREAD

**Issue by usrinivasan** [oracle/graal#3831]
**Description**
The OpenJDK test java/security/Policy/SignedJar/SignedJarTest.java fails with a JVM build of GraalVM 21.2.0 and JDK 11.0.12 sources, and JVM options -XX:+UnlockExperimentalVMOptions -XX:+EnableJVMCI -XX:+UseJVMCICompiler to run with the Graal compiler. The test passes with the default C2 compiler. 

**Steps to reproduce the issue**
1. 'make images' with GraalVM 21.2.0 and OpenJDK 11.0.12
2. make run-test CONF=macosx-x86_64-normal-server-release TEST="test/jdk/java/security/Policy/SignedJar/SignedJarTest.java" JTREG="VM_OPTIONS=-XX:+UseConcMarkSweepGC -XX:+ShowMessageBoxOnError -XX:+UnlockExperimentalVMOptions -XX:+EnableJVMCI -XX:+UseJVMCICompiler"

**GraalVM and environment:**
 - GraalVM version: commit e9c54823b71cdca08e392f6b8b9a283c01c96571 (tag: vm-ce-21.2.0, tag: vm-21.2.0)
 - JDK major version: 11
 - OS: macOS Catalina
 - Architecture: Intel Core i9 (amd64 Graal target)

**More details**
The stack trace from the hanging test is attached. The problem seems to be related to https://bugs.openjdk.java.net/browse/JDK-8262762. 
The relevant portion from the attached stack trace is given below.

[SJT_st.txt](https://github.com/oracle/graal/files/7214610/SJT_st.txt)

Found one Java-level deadlock:
\=======================
"main":
  waiting to lock monitor 0x00007fb191aefd00 (object 0x00000007e01b8a00, a java.lang.Class),
  which is held by "JVMCI CompilerThread0"
"JVMCI CompilerThread0":
  waiting to lock monitor 0x00007fb191aeff00 (object 0x00000007e01c1000, a java.util.jar.JarFile),
  which is held by "main"

**Comment by dougxc** [comment]
As shown in https://bugs.openjdk.java.net/browse/JDK-8262762, there's not much Graal can do to avoid this kind of deadlock. The only reliable solution is to use libgraal which avoids all class loading related to Graal.
Unless you have other ideas, I'd prefer to close this until JDK-8262762 is resolved.

**Comment by usrinivasan** [comment]
> As shown in https://bugs.openjdk.java.net/browse/JDK-8262762, there's not much Graal can do to avoid this kind of deadlock. The only reliable solution is to use libgraal which avoids all class loading related to Graal.

Were you able to reproduce this issue on your side? 
If not, what build and runtime configurations are you using for the Graal 21.2.0 + JDK 11.0.12 testing?

> Unless you have other ideas, I'd prefer to close this until JDK-8262762 is resolved.

I think it's okay to close this issue as being dependent on JDK-8262672.

**Comment by dougxc** [comment]
> Were you able to reproduce this issue on your side?

No but there's not much point given that the deadlock cause is clear.

> If not, what build and runtime configurations are you using for the Graal 21.2.0 + JDK 11.0.12 testing?

When we test with jtreg tests, it's with libgraal.
