### ISSUE TITLE
[GR-34638] Add option to pick which kind of reports one wants to generate

### ISSUE THREAD

**Issue by zakkak** [oracle/graal#3843]
**Feature request**

Now that https://github.com/oracle/graal/pull/3128 is merged it would be nice to have the option to disable the generation of the call-tree in text format when passing `-H:+PrintAnalysisCallTree`.

**Is your feature request related to a problem? Please describe.**
In complex applications the text-formatted call-tree can quickly get really big, while the CSV files are quite smaller.

E.g. for the Quarkus' integration test jpa-postgressql the text call-tree is 82G big, while the aggregated size of the CSV files is only ~17MB.

**Describe the solution you'd like.**
The addition of a new option to disable the generation of the call tree in text format.
An initial thought was to change `PrintAnalysisCallTree` from `boolean` to `String` and pass the format we want as the value, however such a solution will conflict with https://github.com/oracle/graal/pull/3227. 

As a result I am thinking about adding an extra boolean option, like `PrintAnalysisCallTreeInCSV`. The value of the option should be `false` by default, and the call tree should thus be dumped in text format only. When set to true the call tree should be dumped in csv files only. 

**Describe who do you think will benefit the most.**
GraalVM users, GraalVM contributors, developers of libraries and frameworks which depend on GraalVM.

**Express whether you'd like to help contributing this feature**
I would like to contribute this once we come to an agreement on how it should be implemented.

cc @galderz

**Comment by galderz** [comment]
I'm not sure about adding another extra boolean option. How would things work if `PrintAnalysisCallTreeInCSV` and `PrintAnalysisCallTree` where set? It doesn't seem very intuitive. IMO #3227 should use a separate property for the filter, since that is complementary to either the txt or csv outputs.

**Comment by galderz** [comment]
Then you'd have `PrintAnalysisCallTree` being an enum. One more doubt I have is how'd that work from a backwards compatibility perspective. A lot of native image builds out there are using `+PrintAnalysisCallTree` so if we change that we'd have to maintain the old format as possibility to avoid breaking things. It's a popular option.

Another option would be, leave `PrintAnalysisCallTree` as boolean, then have a `AnalysisCallTreeType` enum option, with default option being `text` and optionally set to `csv`, and then have a complementary `AnalysisCallTreeFilter` option for implementing #3227

**Comment by zakkak** [comment]
Thanks for the feedback Galder, I really like your last proposal:

> leave PrintAnalysisCallTree as boolean, then have a AnalysisCallTreeType enum option, with default option being text and optionally set to csv, and then have a complementary AnalysisCallTreeFilter option for implementing #3227

since it offers the needed functionality without breaking backwards compatibility.

@christianwimmer, WDYT?

**Comment by christianwimmer** [comment]
Having `PrintAnalysisCallTreeType` and `PrintAnalysisCallTreeFilter` sound good - they can implicitly set `PrintAnalysisCallTree` to `true` when they are specified so that only one option needs to be set.

**Comment by galderz** [comment]
One more detail, when we add the `PrintAnalysisCallTreeType` and print either text or csv, we can remove the `csv_` prefix from the `.csv` files. It doesn't serve any purpouse.
