### ISSUE TITLE
Context sensitive analysis fails with/without type flow saturation

### ISSUE THREAD

**Issue by marjanasolajic** [oracle/graal#3849]
**Describe the issue**
Running several dacapo benchmarks with allocsens context-sensitivity produces runtime NullPointerException.

**Describe GraalVM and your environment:**
 - GraalVM version: **CE**
 - JDK version: **JDK11**
 - OS: **Ubuntu**
 - Architecture: **AMD64**
 - The output of java -Xinternalversion:
 ```
OpenJDK 64-Bit Server VM (11.0.12+5-jvmci-21.3-b02) for linux-amd64 JRE (11.0.12+5-jvmci-21.3-b02), built on Sep  3 2021 19:54:31 by "buildslave" with gcc 7.3.0
```

**Steps to reproduce the issue**
Example for running xalan with type flow saturation enabled
1. **mx --env ni-ce clean --all**
2. **mx --env ni-ce build**
3. **mx  -v --env ni-ce benchmark dacapo-native-image:xalan -- --jvm=native-image --jvm-config=default-ce -Dnative-image.benchmark.extra-image-build-argument=-H:+RemoveSaturatedTypeFlows -Dnative-image.benchmark.extra-image-build-argument=-H:AnalysisContextSensitivity="allocsens"**

Also tried to add **-Dnative-image.benchmark.extra-image-build-argument=-H:NumberOfThreads=1** and to run with GraalVM EE version but same happens. 

**More details**
I get the following:
```
Failed in stage run for dacapo-svm-xalan-default-ce with exit code 255
java.lang.NullPointerException
        at org.dacapo.parser.Config$Size.addOutputFile(Config.java:131)
        at org.dacapo.parser.Config.addOutputFile(Config.java:389)
        at org.dacapo.parser.ConfigFile.outputFile(ConfigFile.java:248)
        at org.dacapo.parser.ConfigFile.sizeClause(ConfigFile.java:207)
        at org.dacapo.parser.ConfigFile.sizeSpec(ConfigFile.java:139)
        at org.dacapo.parser.ConfigFile.configFile(ConfigFile.java:40)
        at org.dacapo.parser.Config.parse(Config.java:213)
        at org.dacapo.harness.TestHarness.<init>(TestHarness.java:242)
        at org.dacapo.harness.TestHarness.main(TestHarness.java:120)
        at java.lang.reflect.Method.invoke(Method.java:566)
        at Harness.main(Unknown Source)
Command exited with non-zero status 255
```

**Steps to reproduce the issue**
Example for running xalan with type flow saturation disabled
1. **mx --env ni-ce clean --all**
2. **mx --env ni-ce build**
3. **mx  -v --env ni-ce benchmark dacapo-native-image:xalan -- --jvm=native-image --jvm-config=default-ce -Dnative-image.benchmark.extra-image-build-argument=-H:-RemoveSaturatedTypeFlows -Dnative-image.benchmark.extra-image-build-argument=-H:AnalysisContextSensitivity="allocsens"**

Also tried to add **-Dnative-image.benchmark.extra-image-build-argument=-H:NumberOfThreads=1** and to run with GraalVM EE version but same happens. 

**More details**
I get the following:
```
Failed in stage run for dacapo-svm-xalan-default-ce with exit code 255
java.lang.NullPointerException
        at org.dacapo.parser.ConfigFileTokenManager.getNextToken(ConfigFileTokenManager.java:1118)
        at org.dacapo.parser.ConfigFile.jj_consume_token(ConfigFile.java:556)
        at org.dacapo.parser.ConfigFile.config(ConfigFile.java:66)
        at org.dacapo.parser.ConfigFile.configFile(ConfigFile.java:35)
        at org.dacapo.parser.Config.parse(Config.java:213)
        at org.dacapo.harness.TestHarness.<init>(TestHarness.java:242)
        at org.dacapo.harness.TestHarness.main(TestHarness.java:120)
        at java.lang.reflect.Method.invoke(Method.java:566)
        at Harness.main(Unknown Source)
Command exited with non-zero status 255

```

**Comment by marjanasolajic** [comment]
@cstancu I'll continue with further testing and add more information if I come to new conclusions.

**Comment by cstancu** [comment]
@marjanasolajic thanks for the report. I tried it and I can reproduce the issue. To better debug it, and other potential similar issues:
1. Can we generate an IntelliJ project definition for the benchmark? A project for the benchmark and all its classpath dependencies, including all the sources, would allow to import the benchmark code in the IDE to easily inspect the stack traces.
2. Can we run the benchmarks on JDK 17? It has better error messages for NPE. I currently get `Unsupported argument --add-opens`.

cc: @vjovanov

**Comment by marjanasolajic** [comment]
2. @cstancu I also tried to run the benchmarks on JDK17 and get the same error. Then, I tried this:

-  add '--add-opens'  to the list ['-D', '-Xmx', '-Xmn', '-XX:-PrintGC', '-XX:+PrintGC'] in mx_vm_bencmark.py
For this change, I get: 
```
 File "/opt/graal/graal/vm/mx.vm/mx_vm_benchmark.py", line 364, in __enter__
    self.stdout_file = open(self.stdout_path, 'w')
IOError: [Errno 2] No such file or directory: '/opt/graal/graal/vm/mxbuild/native-image-benchmarks/java.base/java.lang=all-unnamed-xalan-default-ce/java.base/java.lang=all-unnamed-xalan-default-ce-agent-stdout.log'

```
- then I look at mentioned path and compare to what I have in file system - there is a directory  /opt/graal/graal/vm/mxbuild/native-image-benchmarks/java.base/java.lang=all-unnamed-xalan-default-ce/ but in it, java.base directory is missing, so I tried to fix the path from error message to print in the '/opt/graal/graal/vm/mxbuild/native-image-benchmarks/java.base/java.lang=all-unnamed-xalan-default-ce/java.lang=all-unnamed-xalan-default-ce-agent-stdout.log
- when I fixed the problem with the paths for stdout and stderr (same as above), I get a new error:
```
Error: Could not find or load main class java.base.java.lang=ALL-UNNAMED
Caused by: java.lang.ClassNotFoundException: java.base.java.lang=ALL-UNNAMED
Failed in stage agent for java.base/java.lang=all-unnamed-xalan-default-ee with exit code 1
--------- Standard output:
Error: Could not find or load main class java.base.java.lang=ALL-UNNAMED
Caused by: java.lang.ClassNotFoundException: java.base.java.lang=ALL-UNNAMED

--------- Standard error:
```

It seems that more adjustment is needed to run benchmarks on JDK17.

**Comment by marjanasolajic** [comment]
For 1. maybe the source code mentioned in the stack trace can help:

- addOutputFile: https://github.com/dacapobench/dacapobench/blob/master/benchmarks/harness/src/org/dacapo/parser/Config.java#L130

- outputFile is generated from method outputFile in ConfigFile.jj:
https://github.com/dacapobench/dacapobench/blob/master/benchmarks/harness/src/org/dacapo/parser/ConfigFile.jj

I still don't have the whole project example...

**Comment by cstancu** [comment]
Should be fixed by https://github.com/oracle/graal/pull/4230. Now the benchmark can be successfully built and executed with `allocsens` context-sensitivity using:
```
mx --env ni-ce benchmark dacapo-native-image:xalan -- --jvm=native-image --jvm-config=default-ce -Dnative-image.benchmark.extra-image-build-argument=-H:-RemoveSaturatedTypeFlows -Dnative-image.benchmark.extra-image-build-argument=-H:+AliasArrayTypeFlows -Dnative-image.benchmark.extra-image-build-argument=-H:AnalysisContextSensitivity="allocsens"
```
Note that the benchmark needs to be built with the `-H:+AliasArrayTypeFlows` option.
