### ISSUE TITLE
commit author in release file is incorrect

### ISSUE THREAD

**Issue by jaikiran** [oracle/graal#3856]
The `release` file that gets generated graal installation/home contains a section for `COMMIT_INFO`. It looks like this currently has a bug where the commit author is incorrect. For example, this is what it generated when I built graal `vm` locally:
```
COMMIT_INFO={"compiler": {"commit.committer": "Jaikiran Pai <myemailid>", "commit.committer-ts": 1633078462, "commit.rev": "e45e0d36850c149a856bbbb12dd3147eabd8a241"}, "java-benchmarks": {"commit.committer": "Jaikiran Pai <myemailid>", "commit.committer-ts": 1633078462, "commit.rev": "e45e0d36850c149a856bbbb12dd3147eabd8a241"}, "sdk": {"commit.committer": "Jaikiran Pai <myemailid>", "commit.committer-ts": 1633078462, "commit.rev": "e45e0d36850c149a856bbbb12dd3147eabd8a241"}, "substratevm": {"commit.committer": "Jaikiran Pai <myemailid>", "commit.committer-ts": 1633078462, "commit.rev": "e45e0d36850c149a856bbbb12dd3147eabd8a241"}, "truffle": {"commit.committer": "Jaikiran Pai <myemailid>", "commit.committer-ts": 1633078462, "commit.rev": "e45e0d36850c149a856bbbb12dd3147eabd8a241"}, "vm": {"commit.committer": "Jaikiran Pai <myemailid>", "commit.committer-ts": 1633078462, "commit.rev": "e45e0d36850c149a856bbbb12dd3147eabd8a241"}}
```
Notice that it marks me as the commit author for all these commits in those modules, whereas I'm not. I even had a look at a released Graal VM version `21.2.0` and that too appears to have the same issue. It marks Doug as the commit author for all those commits in those modules.

**Comment by ansalond** [comment]
Hi @jaikiran, thank you for the report.

Could you please tell me which GraalVM `21.2.0` artefact has Doug listed as a committer in the `release` file? I think all these base artefacts list only Gilles: https://github.com/graalvm/graalvm-ce-builds/releases/tag/vm-21.2.0

I also cannot reproduce the issue locally:
```
$ git clone git@github.com:oracle/graal.git
$ cd graal/sdk
$ mx build
$ cat `mx graalvm-home`/release
...
COMMIT_INFO={"sdk": {"commit.committer": "Thomas Garcia <...>", "commit.committer-ts": 1633075105, "commit.rev": "a8f1b4b1b0be28e9a7c641eb180ff0ae5e030f97"}}
$ git log -n 1
commit a8f1b4b1b0be28e9a7c641eb180ff0ae5e030f97 (HEAD -> master, origin/master, origin/HEAD)
Merge: 9a6a1024a10 3e90ff7d826
Author: Thomas Garcia <...>
Date:   Fri Oct 1 07:58:25 2021 +0000

    [GR-33781] Invalidate interface methods leaf assumptions during itable creation
    
    PullRequest: graal/9900

```

**Comment by jaikiran** [comment]
@ansalond, thank you for checking this. Unfortunately, I no longer have access to such a setup to reproduce this. So I'm closing this as not an issue.
