### ISSUE TITLE
Remainder nodes are always fixed, even when they can't divide-by-zero

### ISSUE THREAD

**Issue by chrisseaton** [oracle/graal#3866]
For example this Ruby code:

```ruby
def foo(x)
  x.times do |n|
    if (n % 5 == 0) && (n % 3 == 0)
      out :fizzbuzz
    elsif n % 5 == 0
      out :fizz
    elsif n % 3 == 0
      out :buzz
    else
      out n
    end
  end
end
```

I'd expect `n % 5 == 0` and `n % 3 == 0` to be calculated once each, but they aren't, as the nodes are fixed and so GVN fails. They needn't be fixed, as they can't divide-by-zero.

![graph](https://user-images.githubusercontent.com/341094/136081937-31e70ffd-bc12-4e9b-93c4-37611b9611b1.png)

@davleopo

**Comment by davleopo** [comment]
@chrisseaton  thanks for the report, Ill have a look.

**Comment by davleopo** [comment]
https://github.com/oracle/graal/commit/39bbdedcaefbccb9369fbf2dab4cec5e88b446c9 adds support to float integer division nodes early on in the compilation pipeline if we know they can never trap. Additionally, we float all fixed div nodes during lowering under certain conditions and can gvn them as well if they have equal, non-constant inputs. Late in the compilation pipeline we can also fold them together again to remove the explicit check if we can perform the div by zero check implicitly.

**Comment by chrisseaton** [comment]
Wow that's a huge commit to fix this. Thanks very much!
