### ISSUE TITLE
`java.lang.OutOfMemoryError: Garbage-collected heap size exceeded` with JDK17

### ISSUE THREAD

**Issue by ilopmar** [oracle/graal#3876]
**Describe the issue**

Our CI has detected this morning an error when starting a Micronaut app with Oracle and JDK17 (it worked with JDK11).
The error is `java.lang.OutOfMemoryError: Garbage-collected heap size exceeded` and it's the first time I see this kind of error. See execution on CI: https://gitlab.com/micronaut-projects/micronaut-graal-tests/-/jobs/1657285826#L72

The issue happened with this commit 0df802f56cc18e111a24ae5846549e8d1a770bc9 and it worked yesterday with eace35dd209c58a25fe29b55f2d547f00d2d9d28.

I'm not able to reproduce it locally because it seems it only happens in a memory-constrained environment like the CI. I've also tried to run it in a docker container limiting the memory (and the cpu) but it also worked.

**Steps to reproduce the issue**

- `git clone https://github.com/micronaut-graal-tests/micronaut-data-jdbc-graal`
- `cd micronaut-data-jdbc-graal`
- `git checkout oracle-jdk17`
- Use GraalVM compiled from master branch for JDK17
- `./build-native-image.sh`
- Start Oracle DB in a docker container: `docker run -it --rm -p 1521:1521 registry.gitlab.com/micronaut-projects/micronaut-graal-tests/oracle-database:18.4.0-xe`
- `./data-jdbc-oracle`

**Describe GraalVM and your environment:**
 - GraalVM version: **22.0.0-dev commit 0df802f56cc18e111a24ae5846549e8d1a770bc9**
 - JDK major version: **17**
 - OS: **Linux Mint 20.2**
 - Architecture: **AMD64**

**Comment by mcraj017** [comment]
@ilopmar thanks for the issue, we will check and get back to you

**Comment by ilopmar** [comment]
@mcraj017 As I mentioned, I'm not able to reproduce this locally:

> I'm not able to reproduce it locally because it seems it only happens in a memory-constrained environment like the CI. I've also tried to run it in a docker container limiting the memory (and the cpu) but it also worked.

It has been failing consistently on our CI since I reported this issue. These are some of the last runs:

- https://gitlab.com/micronaut-projects/micronaut-graal-tests/-/jobs/1682320966
- https://gitlab.com/micronaut-projects/micronaut-graal-tests/-/jobs/1691568877

Surprisingly, this morning it has worked https://gitlab.com/micronaut-projects/micronaut-graal-tests/-/jobs/1695851252, so maybe some of the changes merged yesterday have fixed this.
Please keep this issue on hold. I'll check the runs during this week and I'll update any new information here.
