### ISSUE TITLE
InheritableThreadLocal doesn't work in native-image

### ISSUE THREAD

**Issue by alexfedorenchik** [oracle/graal#3878]
**Describe the issue**
The child thread doesn't receive initial values for inheritable thread-locals from the parent.

**Steps to reproduce the issue**
Example source (Test.java)
```java
public class Test {

	public static final InheritableThreadLocal<String> ITL = new InheritableThreadLocal<>();

	public static void main(String[] args) throws InterruptedException {
		ITL.set("It works!");
		var thread = new Thread(() -> System.out.println(Test.ITL.get()));
		thread.start();
		thread.join();
	}
}
```

Build:
```
echo "Main-Class: Test" > manifest.txt && javac Test.java &&  jar -cvfm Test.jar manifest.txt Test.class && native-image -jar Test.jar
```

Run native-image: 
```
./Test
```

Expected Result:

```
It works!
```

Actual Result:

```
null
```

**Describe GraalVM and your environment:**
 - GraalVM version CE 21.2.0
 - JDK major version: 11
 - OS: macOS BigSur 11.5.2
 - Architecture: x86

**Comment by christianwimmer** [comment]
Fixed by [#4394](https://github.com/oracle/graal/pull/4394)
