### ISSUE TITLE
[licensing] GPLv2 impact for projects using native-image

### ISSUE THREAD

**Issue by lbialy** [oracle/graal#389]
I've noticed that most stuff here is licensed under GPLv2 with small modifications, most notably SubstrateVM is. Am I right to assume that every application compiled using `native-image` tool has to be released under GPLv2 since SubstrateVM is statically linked?

**Comment by thomaswue** [comment]
We are in the process of adding Classpath Exception to all components that can form part of the resulting native image.

**Comment by djhaskin987** [comment]
Does that mean I don't have to license something as gpl if I build it using native-image?

**Comment by thomaswue** [comment]
Yes, correct.

**Comment by jakirkham** [comment]
What about Docker images where components of this stack may need to be bundled to run an application?

**Comment by fcurts** [comment]
What's the status of this? More clarification with regard to licensing would be very welcome.

**Comment by thomaswue** [comment]
@jakirkham Distribution is generally allowed. See point "3." of GPL+CPE for details. https://github.com/oracle/graal/blob/master/compiler/LICENSE.md

@fcurts Yes, this is coming soon. We treat this as top priority and will also add a clarifying guidance re licensing.

**Comment by djhaskin987** [comment]
I apologize -- to be *super* clear, it sounds like if I use `native-image` to compile my source code, *once native-image is licensed with the classpath exception*, I'll be able to distribute that binary even though my code is using a different, incompatible license to the GPL without the classpath exception?

**Comment by dougxc** [comment]
Hi @djhaskin987 , we are working on enhancing the [FAQ](http://www.graalvm.org/docs/faq/) to provide a clear response to this and other related legal questions.

**Comment by djhaskin987** [comment]
I'm on the edge of my seat

**Comment by Tradias** [comment]
Any updates on this?

**Comment by thomaswue** [comment]
The first question at https://www.graalvm.org/docs/faq/ contains information regarding licensing. We cannot give specific legal advice. When creating a native image, code ending up in the binary image in addition to your application code includes JDK code as well as SubstrateVM code; both of which is licensed via GPL 2 + Classpath exception. See the section "CLASSPATH" EXCEPTION TO THE GPL at https://openjdk.java.net/legal/gplv2+ce.html for more information about the Classpath exception. It specifically addresses a scenario where GPLv2+CPE code is linked with other code.
