### ISSUE TITLE
[gu rebuild native-images] Rebuilding of polyglot and libpolyglot fail (using the gu tool)

### ISSUE THREAD

**Issue by neomatrix369** [oracle/graal#3916]
**Describe the issue**

Rebuilding the `polyglot` and `libpolyglot` components using the `gu` tool lead to a failure related to blacklisted methods (more details in the attached logs)

I did follow the steps mentioned on https://github.com/oracle/truffleruby/blob/master/doc/user/installing-graalvm.md#installing-ruby-and-other-languages and other TruffleRuby docs, see [here](https://github.com/graalvm/graalvm-demos/issues/95), for further conversations.

**Steps to reproduce the issue**
Clone the repo:
```
$ git clone https://github.com/graalvm/graalvm-demos
$ cd graalvm-demos
$ git checkout provide-Docker-scripts
```

By default it runs GraalVM version: 21.2.0 for Java 11, other examples on [PR description](https://github.com/graalvm/graalvm-demos/pull/93)

Run the docker container from the project root folder:
```
$ DEMO_TYPE="gui" ./runDockerImage.sh "java11-21.2.0"
```
Log onto the container interface using VNCViewer or equivalent (also mentioned in the PR description) on http://127.0.0.1:5900.

Once logged in, an `xterm` console is provided, perform the below steps, just like we would do on a console interface:

```
$ cd galaaz-ggplot
$ gu rebuild-images --verbose polyglot libpolyglot
```

Ensure the system has good enough resources for the native-image building process.

PS: VNCViewer does not have copy-paste features between host and container environments :( sorry about that, but it should be good enough to 

**Describe GraalVM and your environment:**
 - GraalVM version: 21.2.0 for Java 11 (and for Java 8)
 - JDK major version: 11 (openjdk 11.0.12 2021-07-20)
 - OS: Linux 1775e81eac93 4.19.76-linuxkit #1 SMP Tue May 26 11:42:35 UTC 2020 x86_64 GNU/Linux 
 - Architecture: x86_64 (using `lscpu` command)

**More details**
Snapshot of the log messages:

```
<--snipped-->
 ---> Running in a1a9abadc1b4
Building polyglot...
/graalvm/jre/lib/svm/bin/../../../bin/native-image --macro:polyglot-launcher --language:all
[polyglot:37]    classlist:   7,877.54 ms,  2.53 GB
--initialize-at-build-time without arguments has been deprecated and will be removed in GraalVM 22.0.
[polyglot:37]        (cap):     736.91 ms,  2.53 GB
[polyglot:37]        setup:   3,418.67 ms,  2.53 GB
[polyglot:37]     (clinit):  17,345.73 ms, 12.41 GB
[polyglot:37]   (typeflow): 1,335,031.71 ms, 12.41 GB
[polyglot:37]    (objects): 449,727.51 ms, 12.41 GB
[polyglot:37]   (features):  51,044.42 ms, 12.41 GB
[polyglot:37]     analysis: 1,860,857.31 ms, 12.41 GB
[polyglot:37]     universe:  14,410.16 ms, 12.41 GB
41376 method(s) included for runtime compilation

=== Found 4 compilation blacklist violations ===

Blacklisted method
  com.oracle.truffle.r.launcher.RMain$PrintHelp.fillInStackTrace()
called from
  java.lang.Throwable.<init>(Throwable.java:251) -> java.lang.Exception.<init>(Exception.java:54) -> java.lang.RuntimeException.<init>(RuntimeException.java:51) -> java.lang.NegativeArraySizeException.<init>(NegativeArraySizeException.java:43) -> com.oracle.truffle.espresso.meta.StringUtil.newBytesFor(StringUtil.java:118)
  com.oracle.truffle.espresso.meta.StringUtil.toBytes(StringUtil.java:78)
  com.oracle.truffle.espresso.meta.StringUtil.toBytes(StringUtil.java:41) -> com.oracle.truffle.espresso.meta.StringConversion$CompactGuestCharHost.toGuest(StringConversion.java:253)
  com.oracle.truffle.espresso.meta.Meta.toGuestString(Meta.java:1734) -> com.oracle.truffle.espresso.meta.Meta.throwExceptionWithMessage(Meta.java:1517)
  com.oracle.truffle.espresso.nodes.BytecodeNode.checkNonZero(BytecodeNode.java:2243)
  com.oracle.truffle.espresso.nodes.BytecodeNode.executeBody(BytecodeNode.java:900)
  com.oracle.truffle.espresso.nodes.EspressoBaseMethodNode.execute(EspressoBaseMethodNode.java:43)
  com.oracle.truffle.espresso.nodes.EspressoRootNode$Default.execute(EspressoRootNode.java:287)
  org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.executeRootNode(OptimizedCallTarget.java:632)
  org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.profiledPERoot(OptimizedCallTarget.java:603)
<--snipped-->
```

Detailed logs provided in the attached log file [ruby-polyglot-rebuild-native-images.log](https://github.com/oracle/graal/files/7340066/ruby-polyglot-rebuild-native-images.log), experience is the same for both Java 8 and Java 11.

@eregon has been kindly helping and following this issue and we have a dedicated [issue raised here](https://github.com/graalvm/graalvm-demos/issues/95).

One more comment, this build takes a lot of time and resources for both the components - any chance of helping improve this experience? Happy to help and investigate it as a separate issue.

**Comment by neomatrix369** [comment]
> I think the blacklisted method should not be reachable anymore because of the `@TruffleBoundary` annotations introduced by this commit: [c8fbbdb](https://github.com/oracle/graal/commit/c8fbbdbf1a5b99dc0ebe99f7862f770324e97d1f)
> 
> If you have time, could you please try one of the nightly builds? https://github.com/graalvm/graalvm-ce-dev-builds/releases
 Certainly, I'll build an image from this release and get back to you with the outcome.

**Comment by eregon** [comment]
> **Question:** Does it install the `-dev` versions of the respective components?

Yes, it automatically picks the dev components, from the same "GitHub Pre-release" of the dev builds.
Anything else would be incorrect of course.
Best to always use `gu install component_name` and not manually download them if you can.
