### ISSUE TITLE
gu upgrade doesn't upgrade

### ISSUE THREAD

**Issue by ccleve** [oracle/graal#3921]
`gu upgrade` returns:

```
% gu upgrade
Downloading: Component catalog from www.graalvm.org
No GraalVM upgrade is found for the version 21.0.0.2
```

The GraalVM site says that the current version is 21.2.0

Oddly, the components catalog here (https://www.graalvm.org/component-catalog/graal-updater-component-catalog.properties), linked on this page (https://github.com/oracle/graal/blob/master/vm/GRAALVM-README.md), only goes up to 19.2.1. Scroll to the bottom to see.

**Comment by MartinBalin** [comment]
Fixed in 22.1.0
