### ISSUE TITLE
Can AOT compilations run without an operating system?

### ISSUE THREAD

**Issue by ashtonhogan** [oracle/graal#393]
Is it possible to place compiled binary into `address 0` and execute it without an operating system?

**Comment by Peter-B-Kessler** [comment]
The binaries SubstrateVM generates still need a linker, for references to libraries and relocation of symbols.  I think of those as coming from the operating system.  We rely on the OS for things like thread creation, mutexes and condvars, etc.  How much "without an operating system" are you thinking of?

**Comment by olpaw** [comment]
@ashtonhogan, although we currently do not support it, conceptually this is quite possible. One could take a bare-metal C library like newlib and customize the linking step of our image building to output a bare metal executable that would run on a system without OS. Now if you combine that with the ongoing efforts to have a decent ARM64 backend for Graal this could take an interesting direction.
