### ISSUE TITLE
[native-image] Memory management documentation clarifications about "just-in-time" compile code

### ISSUE THREAD

**Issue by aldettinger** [oracle/graal#3930]
**Describe the issue**
The native-image documentation about [performance considerations](https://www.graalvm.org/reference-manual/native-image/MemoryManagement/#performance-considerations) states that:

> Native Image places some data such as thread stacks, just-in-time compiled code, and internal data structures in memory that is separate from the Java heap.

Is there really any "just-in-time compiled code" when using native-image ?

**Comment by wirthi** [comment]
I have clarified that in our documentation. Merged, but will take a while to show on the website.

**Comment by aldettinger** [comment]
Many thanks @wirthi :+1:
