### ISSUE TITLE
Improve module support for native-image building

### ISSUE THREAD

**Issue by olpaw** [oracle/graal#3935]
https://github.com/oracle/graal/issues/1962 was implemented for 21.3. Basic support for building images from modules is available. But more work is needed.

- While all of the images coming from the substratevm suite (`native-image-launcher`, `native-image-agent-library`, ...) are already built on module-path our other GraalVM images from other suites are still built in the classpath. This needs to be fixed.
- Currently the image builder only runs on the module-path if an image should be built from the module-path. This needs to changes so that the image-builder always runs on the module-path.
- Module-info at image runtime is generated at image-buildtime. This is still incomplete. Hosted module access setup needs to be translated to runtime module-info access state so that module-related checks pass at image runtime as expected. One instance of this problem is explained in detail in https://github.com/oracle/graal/issues/3911
- Currently `StackTraceElement.getModuleName()` does not return module names. (see https://github.com/oracle/graal/issues/4008)

**Comment by mcraj017** [comment]
@olpaw There is a request to add module name in stack traces of native image, please add that in this effort also
https://github.com/oracle/graal/issues/4008
