### ISSUE TITLE
Support building static final binary

### ISSUE THREAD

**Issue by kmrozek-shareablee** [oracle/graal#394]
I would like the binary output was static linked like with Go compiled programs. Is it possible?

**Comment by cstancu** [comment]
We're currently experimenting with static linking the binary. See for example: https://github.com/oracle/graal/issues/386#issuecomment-385974629.

**Comment by olpaw** [comment]
I'm already working on that.

**Comment by io7m** [comment]
Is this something that's intended to be optional? I could see situations where I'd prefer a statically linked binary, but others where I'd prefer to keep them dynamically linked.

**Comment by olpaw** [comment]
@io7m the default will remain as it is (output dynamically linked binaries). I'm just adding `--static` to optionally allow building of statically linked executables.

**Comment by io7m** [comment]
Sounds good, thanks! Looking forward to this.

**Comment by olpaw** [comment]
Fixed. See https://github.com/oracle/graal/commit/622cd8acc818bfccb1c9a4ee750b488b8c1fcbcc

**Comment by olpaw** [comment]
The new option is
```
--static              build statically linked executable (requires static libc and zlib)
```
To use it you must install static variants of libc and zlib first.
(On fedora you would use `sudo dnf install glibc-static zlib-static`)
