### ISSUE TITLE
[Documentation] "Quick start" for experienced users?

### ISSUE THREAD

**Issue by rubyFeedback** [oracle/graal#3966]
Hey there GraalVM devs,

I know ruby fairly well; and I know java semi-ok-ish. I know python fairly well too.

I still haven't extensively tested GraalVM but I finally intend to do so in November/December 2021.

Personally I use Linux, but my laptop runs Win10 and I need to make available programs for
elderly relatives, so I have to use windows too.

The guide here specifies what to do on windows:

https://www.graalvm.org/docs/getting-started/windows/

But I'd ideally love to see a "hello world" example for all of java, ruby and python. This may not
fit into the link, but perhaps there could be a link from the official documentation to an article
that does a step-by-step walk-through. I am sure I can figure it out on my own eventually, but
any initial help related via the documentation may be useful - after all someone else would have
followed that guide, so it would help us bypass any frustration or mistakes we may have made 
from trying to run e. g. python or ruby on GraalVM. So I am mostly looking for obligatory
"Hello world" examples - perhaps as a separate document just showing the main commands
used. (Actually if it could be copy/pasted that would be even cooler ... but I want to understand
what is going on too).

**Comment by rubyFeedback** [comment]
Hmm ... Github seems to automatically add a label. The above is incorrect, though, as it was not me who added the "bug" label, but github. I would have added a [documentation] label but I don't know how to change that...

**Comment by oubidar-Abderrahim** [comment]
Thank you for your proposition. Unfortunately, both python and ruby are not supported in Windows, therefore it won't make much sense to add examples for those languages for the Windows platform.
