### ISSUE TITLE
Documentation - Installation on Windows Platforms - setx Usage

### ISSUE THREAD

**Issue by scientificware** [oracle/graal#3971]
**Description**
In the [Documentation - Installation on Windows Platforms](https://github.com/oracle/graal/blob/1e3022f74100d54c80d2710ee6449f8c785b5d15/docs/getting-started/graalvm-community/windows.md?plain=1#L19) you suggest to use the `setx` command. But this command has some [limitations](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/setx#remarks). Wouldn't it be more prudent to not apply it to the `Path` variable ?

>Be aware there's a limit of 1024 characters when assigning contents to a variable using setx.
>
>This means that the content is cropped if you go over 1024 characters, and that the cropped text is what's applied to the target variable. If this cropped text is applied to an existing variable, it can result in loss of data previously held by the target variable.

**Comment by oubidar-Abderrahim** [comment]
Thank you for sharing this, using `setx` was a suggestion only, the main objective is to set the `PATH` variable. Could you please share another tool to use instead without this limitation?

**Comment by scientificware** [comment]
Sorry @oubidar-Abderrahim, I don't know another command line to use. At least a warning message could be added about `setx` usage.

I prefer set `path` through a Windows GUI : 
- Reach the Environment variable
  - Windows Start Menu - Settings - ... - Advanced
  - One can simply type `SystemPropertiesAdvanced` in a command prompt or in a Search Field (Windows Tool Bar or Windows + r) to direct access.
- Click Environment Variables. In the section `System Variables` find the `path` variable and select it.
- Click Edit.
- Click New.
- Click Browse and reach the folder to add.
- Close all remaining windows by clicking OK.
- Reopen Command prompt window.

**Comment by olyagpl** [comment]
The windows guides have been updated. Thanks for the suggestions!
