### ISSUE TITLE
NullPointerException when building native image with experimental-class-define-support

### ISSUE THREAD

**Issue by raphw** [oracle/graal#3974]
When using the *experimental-class-define-support* flag, the *native-image* build fails with the following null pointer exception. I attached a sample project which reproduces the issue: [sample.zip](https://github.com/oracle/graal/files/7460347/sample.zip).

It's run with:

    native-image -cp bb.jar:. Sample

The META-INF was created using:

    java -agentlib:native-image-agent=config-output-dir=META-INF/native-image,experimental-class-define-support -cp bb.jar:. Sample

Note that the *reflection-config.json* needs to be edited as described in https://github.com/oracle/graal/issues/3968.

> Fatal error:java.lang.NullPointerException
> 	at com.oracle.svm.hosted.ClassPredefinitionFeature$PredefinedClassesRegistryImpl.add(ClassPredefinitionFeature.java:132)
> 	at com.oracle.svm.core.configure.PredefinedClassesConfigurationParser.parseClass(PredefinedClassesConfigurationParser.java:91)
> 	at com.oracle.svm.core.configure.PredefinedClassesConfigurationParser.parseOrigin(Predefined
ClassesConfigurationParser.java:82)
> 	at com.oracle.svm.core.configure.PredefinedClassesConfigurationParser.parseAndRegister(PredefinedClassesConfigurationParser.java:69)
> 	at com.oracle.svm.core.configure.PredefinedClassesConfigurationParser.parseAndRegister(PredefinedClassesConfigurationParser.java:52)
> 	at com.oracle.svm.hosted.config.ConfigurationParserUtils.doParseAndRegister(ConfigurationParserUtils.java:127)
> 	at com.oracle.svm.hosted.config.ConfigurationParserUtils.lambda$parseAndRegisterConfigurations$3(ConfigurationParserUtils.java:113)
> 	at java.base/java.util.stream.ReferencePipeline$4$1.accept(ReferencePipeline.java:212)
> 	at com.oracle.svm.hosted.config.ConfigurationParserUtils$1.tryAdvance(ConfigurationParserUtils.java:106)
> 	at java.base/java.util.Spliterator.forEachRemaining(Spliterator.java:326)
> 	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
> 	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:274)
> 	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
> 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
> 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
> 	at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.forEachRemaining(StreamSpliterators.java:312)
> 	at java.base/java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:734)
> 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
> 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
> 	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
> 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
> 	at java.base/java.util.stream.IntPipeline.reduce(IntPipeline.java:491)
> 	at java.base/java.util.stream.IntPipeline.sum(IntPipeline.java:449)
> 	at com.oracle.svm.hosted.config.ConfigurationParserUtils.parseAndRegisterConfigurations(ConfigurationParserUtils.java:115)
> 	at com.oracle.svm.hosted.ClassPredefinitionFeature.afterRegistration(ClassPredefinitionFeature.java:73)
> 	at com.oracle.svm.hosted.NativeImageGenerator.lambda$setupNativeImage$15(NativeImageGenerator.java:825)
> 	at com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:73)
> 	at com.oracle.svm.hosted.NativeImageGenerator.setupNativeImage(NativeImageGenerator.java:825)
> 	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:527)
> 	at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:488)
> 	at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:403)
> 	at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:569)
> 	at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:122)
> 	at com.oracle.svm.hosted.NativeImageGeneratorRunner$JDK9Plus.main(NativeImageGeneratorRunner.java:599)
>

**Comment by oubidar-Abderrahim** [comment]
Thank you for reporting this, we will take a look into it and get back to you

**Comment by oubidar-Abderrahim** [comment]
Could you please specify the following information:
- version of GraalVM?
- JDK version?
- Edition (EE or CE)?
- OS version?

**Comment by raphw** [comment]
I have used:

penjdk version "11.0.13" 2021-10-19
OpenJDK Runtime Environment GraalVM CE 21.3.0 (build 11.0.13+7-jvmci-21.3-b05)
OpenJDK 64-Bit Server VM GraalVM CE 21.3.0 (build 11.0.13+7-jvmci-21.3-b05, mixed mode, sharing)

On Linux (Ubuntu 21.04).

**Comment by raphw** [comment]
I debugged this, and the null pointer stems [from a call with a null value](https://github.com/oracle/graal/blob/1fde5c48a53f5bf10bc11eb48b751b2274360204/substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/configure/PredefinedClassesConfigurationParser.java#L52) which is [later attempted to be resolved](https://github.com/oracle/graal/blob/61bc720709fc6c68341db6063809b7cb92b9cf72/substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/ClassPredefinitionFeature.java#L132).

There is absolutely no way that this does not yield a null pointer as the passed argument to the configuration parser is [always a URL which is always resolved to a reader](https://github.com/oracle/graal/blob/dfe307ecb3d6093453e0513f4df9d09857a9dcc9/substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/config/ConfigurationParserUtils.java#L113).

**Comment by raphw** [comment]
I also created a simplified [sample project](https://github.com/oracle/graal/files/7591051/sample.zip).

You can provoke the error by running `./run.sh /location/of/graal`.

**Comment by peter-hofer** [comment]
Fixed with 1bdc9f8991a785352bcb9c2542e5978d944abbb0.
