### ISSUE TITLE
OpenJDK VM warning

### ISSUE THREAD

**Issue by matteoturini** [oracle/graal#3995]
**Describe the issue**
This warning appears with NodeJS.
```
OpenJDK VM warning: the use of signal() and sigset() for signal chaining was deprecated in version 16.0 and will be removed in a future release. Use sigaction() instead.
````

**Steps to reproduce the issue**
Please include both build steps as well as run steps
1. gu install nodejs
2. npm i -g yarn
3. yarn add webpack

**Describe GraalVM and your environment:**
 - GraalVM version: GraalVM CE 22.0.0-dev-20211105_2059
 - JDK major version: 17
 - OS: Ubuntu 20.04 via WSL 2
 - Architecture: AMD64

**Comment by rodrigar-mx** [comment]
Thanks for sharing. We will take a look into it.

**Comment by rodrigar-mx** [comment]
I have reported this warning with the js team. They will respond you accordingly.

**Comment by iamstolis** [comment]
Fixed by https://github.com/oracle/graaljs/commit/38f0a682586a6a9a97243507e9a4aa017ca8aa1d

**Comment by matteoturini** [comment]
Thanks
