### ISSUE TITLE
Unable to generate a shared library without main manifest attribute

### ISSUE THREAD

**Issue by RIvance** [oracle/graal#3999]
when i use the following command to generate a shared library
```
native-image -jar test.jar --shared -H:Name=libtest
```
the output is
```
Error: No main manifest attribute, in /xxxx/test.jar
```

the same error also occurs when i try to generate a shared library with a single class file
```
native-image Test.class --shared -H:Name=libtest -H:+ReportExceptionStackTraces
```
output:
```
[libtest:20233]    classlist:     701.11 ms,  0.96 GB
Error: Main entry point class 'Test.class' not found.
com.oracle.svm.core.util.UserError$UserException: Main entry point class 'Test.class' not found.
	at com.oracle.svm.core.util.UserError.abort(UserError.java:68)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:323)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:543)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:119)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner$JDK9Plus.main(NativeImageGeneratorRunner.java:573)
[libtest:20233]      [total]:     718.68 ms,  0.96 GB
Error: Image build request failed with exit status 1
```

however, with `main` method, everything is fine

the only code in the jar file is
```java
import org.graalvm.nativeimage.c.function.CEntryPoint;

public class Test {
    @CEntryPoint(name = "hello")
    public static void hello() {
        System.out.println("Hello, world");
    }
}
```

**Comment by petermz** [comment]
The second command fails because it is unclear where Test.class comes from. It needs a classpath, e.g.
native-image -cp test.jar Test --shared ...

**Comment by rodrigar-mx** [comment]
Hi @RIvance. Yes, please try with the classpath and the compiled class like `native-image --shared -H:Name=libtests -cp Test.class`

**Comment by RIvance** [comment]
> Hi @RIvance. Yes, please try with the classpath and the compiled class like `native-image --shared -H:Name=libtests -cp Test.class`

> The second command fails because it is unclear where Test.class comes from. It needs a classpath, e.g. native-image -cp test.jar Test --shared ...

It works! Thanks!
