### ISSUE TITLE
Please provide JSON schemas for *-config.json files

### ISSUE THREAD

**Issue by sdeleuze** [oracle/graal#4004]
Native configuration files have grown in term of complexity, also the documentation usually shows only a subset of what is possible to achieve (or is not up to date). JSON schemas could improve the discoverability of capabilities and could be used by tooling to validate the format of such files against a specific GraalVM version upfront providing them to `native-image` compiler.

Please tag this issue with the `spring` label.

**Comment by mcraj017** [comment]
@sdeleuze thanks for reporting the issue, we will check it out and get back to you

**Comment by wirthi** [comment]
The schema files have been provided a few months back, see https://github.com/oracle/graal/blob/master/docs/reference-manual/native-image/assets/
