### ISSUE TITLE
Show module name in stacktrace

### ISSUE THREAD

**Issue by Thihup** [oracle/graal#4008]
Currently the stacktraces in native image doesn't show the module name, even when using a Java module.

One example is the following:
```
public class Main {

    public static void main(String[] args) {
        if (!Main.class.getModule().isNamed())
            throw new AssertionError("Must be in a named module");
        StackTraceElement stackTraceElement = new Exception().getStackTrace()[0];
        String moduleName = stackTraceElement.getModuleName();
        if (moduleName == null || "".equals(moduleName))
            throw new AssertionError("Must be in a named module");
        System.out.println("Hello from " + moduleName);
    }
}
```
When using the module-path, I guess it should return the module name.

**Comment by mcraj017** [comment]
@Thihup thanks for reporting the issue, we will check it out and get back to you

**Comment by mcraj017** [comment]
@Thihup I will add this request in the ongoing effort of improving module support on native-image

**Comment by mcraj017** [comment]
please follow https://github.com/oracle/graal/issues/3935 for more updates, closing this issue now

**Comment by olpaw** [comment]
@Thihup good point. This is currently missing and should be added. @ivan-ristovic this is something that would fit in your previous line of work.
