### ISSUE TITLE
[TruffleDSL] Reuse fields for @Specialization(assumptions)

### ISSUE THREAD

**Issue by smarr** [oracle/graal#4009]
TruffleRuby relies a lot on assumptions in the context of the TruffleDSL.
In a significant number of cases, the assumptions are already stored in a `final` or `@CompilationFinal` field higher up in the class hierarchy.

The DSL however introduces new fields which can increase the node size quite significantly.

I am imagining that the TruffleDSL could note that the expression for the `assumptions` property of a `@Specialization` is a field and reuse it. This would reduce the footprint for TruffleRuby, especially for "inlined" nodes.

Some examples:

#### InlinedAddNode

https://github.com/oracle/truffleruby/blob/master/src/main/java/org/truffleruby/core/inlined/InlinedAddNode.java#L33

```Java
    @Specialization(rewriteOn = ArithmeticException.class, assumptions = "assumptions")
    protected int intAdd(int a, int b) {
        return Math.addExact(a, b);
    }
```

The `assumptions` field is defined in a super class, `InlinedReplaceableNode`.

```Java
@CompilationFinal(dimensions = 1) protected final Assumption[] assumptions;
```

In the generate class, we get for each specialization a new field, meaning we have:

```Java
    @CompilationFinal(dimensions = 1) private Assumption[] intAdd_assumption0_;
    @CompilationFinal(dimensions = 1) private Assumption[] intAddWithOverflow_assumption0_;
    @CompilationFinal(dimensions = 1) private Assumption[] longAdd_assumption0_;
    @CompilationFinal(dimensions = 1) private Assumption[] longAddWithOverflow_assumption0_;
    @CompilationFinal(dimensions = 1) private Assumption[] floatAdd_assumption0_;
    @CompilationFinal(dimensions = 1) private Assumption[] longDouble_assumption0_;
    @CompilationFinal(dimensions = 1) private Assumption[] ubleLong_assumption0_;
```

#### InlinedEqualNode

`InlinedEqualNode` node very similar.

It defines:

```Java
    final Assumption integerEqualAssumption;
    final Assumption floatEqualAssumption;
```

And also inherits the `assumptions` field from above.

Specializations look like this:

```Java
    @Specialization(assumptions = { "assumptions", "integerEqualAssumption" })
    protected boolean intEqual(int a, int b) {
        return a == b;
    }
```

And it results in:

```Java
    @CompilationFinal(dimensions = 1) private Assumption[] intEqual_assumption0_;
    @CompilationFinal private Assumption intEqual_assumption1_;
    @CompilationFinal(dimensions = 1) private Assumption[] longEqual_assumption0_;
    @CompilationFinal private Assumption longEqual_assumption1_;
    @CompilationFinal(dimensions = 1) private Assumption[] double_assumption0_;
    @CompilationFinal private Assumption double_assumption1_;
    @CompilationFinal(dimensions = 1) private Assumption[] longDouble_assumption0_;
    @CompilationFinal private Assumption longDouble_assumption1_;
    @CompilationFinal(dimensions = 1) private Assumption[] ubleLong_assumption0_;
    @CompilationFinal private Assumption ubleLong_assumption1_;
```

**Comment by smarr** [comment]
I put together a prototype for this ([here](https://github.com/oracle/graal/compare/master...smarr:main/direct-assumption-field-use)), which saves 459 lines of generated code on TruffleRuby. This isn't exactly the number of saved field declarations though. A better approximation is possibly half of it, because some reading and writing code also gets not generated.

The prototype avoids putting fields into the generated subclass, as well as in the generated data classes.

Performance-wise, the change is neutral. There doesn't seem to be anything significant in any direction for TruffleRuby: https://rebench.stefan-marr.de/compare/TruffleRuby/6dd971c7ef070259ee7a414ad59a6597be0ed8aa/5f3b1cc627d57baf88dc6b1ad4521ba9d6ac01af

For the two examples, this gives the following results:

#### InlinedAddNode

These fields are gone, the only remaining fields are:

```Java
    @Child private RubyNode left_;
    @Child private RubyNode right_;
    @CompilationFinal private volatile int state_0_;
    @CompilationFinal private volatile int exclude_;
    @Child private FixnumOrBignumNode longAddWithOverflow_fixnumOrBignum_;
```

#### InlinedEqualNode

Same result for `InlinedEqualNode`. The remaining fields are:

```
    @Child private RubyNode left_;
    @Child private RubyNode right_;
    @CompilationFinal private volatile int state_0_;
    @Child private StringEqualData stringEqual_cache;
```

#### Testing

The patch does not include unit tests. Though, I used the code in the details section below for manual testing/debugging. And, TruffleRuby works without issues.
Given the minimal testing, I didn't turns this into a PR. Though, overall the change seems pretty straightforward, reduces footprint of some key nodes massively, and is probably not going to cause performance regressions.

<details>

```Java
package a1debug.dsl;

import java.util.Arrays;

import com.oracle.truffle.api.Assumption;
import com.oracle.truffle.api.Truffle;
import com.oracle.truffle.api.dsl.Cached;
import com.oracle.truffle.api.dsl.Specialization;
import com.oracle.truffle.api.frame.VirtualFrame;


public abstract class Test1 extends TestParent {

  protected final Assumption assumptionFieldLocal;
  protected final Something  something;

  public static Test1 create() {
    return null;
  }

  public Test1() {
    assumptionFieldLocal = Truffle.getRuntime().createAssumption();
    something = new Something();
  }

  protected static class Something {
    public Assumption aFieldOfSomething;
  }

  protected static Something get() {
    return null;
  }

  public static Assumption getAssumption() {
    return Truffle.getRuntime().createAssumption();
  }

  public static Assumption[] getAssumptions(final int num) {
    Assumption[] as = new Assumption[num];
    Arrays.fill(as, Truffle.getRuntime().createAssumption());
    return as;
  }

  public abstract Object execute(VirtualFrame frame);

  @Specialization(assumptions = "get().aFieldOfSomething")
  public Object useNonTrivialField() {
    return null;
  }

  @Specialization(assumptions = "something.aFieldOfSomething")
  public Object useSomewhatTrivialField() {
    return null;
  }

  @Specialization(assumptions = "assumptionFieldParent")
  public Object useParentAssumptionFieldAndCaches(
      @Cached final Test1 a,
      @Cached final Test1 b,
      @Cached final Test1 c) {
    return null;
  }

  @Specialization(assumptions = "assumptionFieldLocal")
  public Object useLocalAssumptionFieldAndCaches(
      @Cached final Test1 a,
      @Cached final Test1 b,
      @Cached final Test1 c) {
    return null;
  }

  @Specialization(assumptions = "assumptionFieldParent")
  public Object useParentAssumptionField() {
    return null;
  }

  @Specialization(assumptions = "assumptionFieldLocal")
  public Object useLocalAssumptionField() {
    return null;
  }

  @Specialization(assumptions = "getAssumption()")
  public Object doStuff1Assumption() {
    return null;
  }

  @Specialization(assumptions = {"getAssumption()", "getAssumption()"})
  public Object doStuff2Assumption() {
    return null;
  }

  @Specialization(assumptions = {"getAssumptions(3)"})
  public Object doStuff3Array() {
    return null;
  }
}

```

</details>

/cc @eregon @chrisseaton

**Comment by eregon** [comment]
This is great! And doing it only for direct fields makes it clear it gains footprint without costing any extra indirection.
We should probably also check the field is `final` to guard against mutability and ensure we can fold the read in PE code (didn't see that in the commit).

@chumer Sounds good to you? I guess you'd want a PR with tests?

**Comment by chumer** [comment]
Thanks for the suggestion. This is indeed a good optimization.
This is a breaking change though if the node field is mutable.

So i suggest we only consider it a trivial field if:
1. it is a field of type Assumption or Assumption[].
2. the field is marked final or @CompilationFinal if of type Assumption
3. the field is final and marked with @CompilationFinal(dimensions=1) if of type Assumption[]

If this is true for multiple field chains we could allow non-null receivers as well, as long as all field references before are final and no value resolves to a dynamic parameter.

We should emit a warning if just the final, or @CompilationFinal is slightly off for the assumption field. That is very likely a mistake by the user.

Given we change the trivial check, we should move the trivial check to AssumptionExpression instead of DSLExpression because it is not generic enough anymore.

@smarr want to finish this with tests? I can also take it from here, but it might take a few days to get done.

**Comment by chumer** [comment]
> it is a field of type Assumption or Assumption[].

ah. my mistake. that is already checked.

**Comment by smarr** [comment]
If you want to take it from here, that's great. It's first week of university term for me, so, my ability to allocate quality time, is a little, ehm, sporadic and erratic...

**Comment by chumer** [comment]
@smarr  PR is ready for review: https://github.com/oracle/graal/pull/4247
I did not use your prototype as I expanded the scope of this optimization a bit.
