### ISSUE TITLE
LLVM support for Windows?

### ISSUE THREAD

**Issue by TempleLin** [oracle/graal#4011]
The interopable languages that LLVM toolchain provides are pretty significant. Hope Windows OS of GraalVM can have that kind of feature in the future.

**Comment by oubidar-Abderrahim** [comment]
Hi, thank you for your suggestion, I think @zapster would be able to share more about the status of LLVM support on Windows

**Comment by rschatz** [comment]
Hi!

Of course we have Windows support planned at some point, but it is a significant implementation effort. The LLVM language runtime contains a lot of platform dependent code, and while that code is very similar for Linux and MacOS, I expect it will take a bigger effort to port it to Windows.

There are many other important open issues for the GraalVM LLVM runtime, so unfortunately I can't give you a concrete timeframe for Windows support at the current point in time.

**Comment by TempleLin** [comment]
Thank you for the replies. Glad to hear it's planned, and hope to see this feature some day!

**Comment by fniephaus** [comment]
We are adding Windows support in the 22.3 release, see https://github.com/oracle/graal/issues/5007.
