### ISSUE TITLE
GraalVM installation identified as a virus by Windows Defender

### ISSUE THREAD

**Issue by crschnick** [oracle/graal#4012]
**Describe the issue**
Windows Defender quarantines parts of my graalvm installation, more precisely `lib\svm\builder\svm.jar`, and deletes it.

Here is a screenshot from the Windows Defender popup:
![image](https://user-images.githubusercontent.com/72509152/141651072-d2e5bb4f-aa8e-4860-8438-4c4a9313f356.png)

**Steps to reproduce the issue**
1. Download the release from https://github.com/graalvm/graalvm-ce-builds/releases/tag/vm-21.3.0
2. Unpack it somewhere

**Describe GraalVM and your environment:**
 - GraalVM version: **CE 21.3.0**
 - JDK major version: **17**
 - OS: **Windows 10**
 - Architecture: **AMD64**

**Comment by mcraj017** [comment]
@crschnick Thanks for reporting the issue, we will check it out and get back to you

**Comment by mcraj017** [comment]
@crschnick I tried it on windows 10 and did not face any error
Can you please download and try again?

**Comment by crschnick** [comment]
@mcraj017 I recently set up a new Windows installation, so I sadly can't test it anymore on the original one.
When I test this on my new system, I also don't get any error. However, I was able to consistently reproduce it on my old system multiple times.

**Comment by mcraj017** [comment]
@crschnick Thanks for the confirmation.
If you see the issue again, please reopen the issue or report new one
Closing this for now
