### ISSUE TITLE
[GR-35116] Enterprise JIT gives wrong output for String#indexOf with certain characters

### ISSUE THREAD

**Issue by TPGamesNL** [oracle/graal#4022]
**Describe the issue**
When using `String#indexOf(int)` on a String containing a character in the range from `\u0080` to `\u00FF`, with that character as the argument, `-1` is always returned if EE's JIT had compiled the method.

**Steps to reproduce the issue**
Code:
```java
public class MyClass {
	public static void main(String[] args) {
		System.out.println("\u00A6".indexOf('\u00A6'));
	}
}
```
Command: `"<path to GraalVM EE>/bin/java.exe" MyClass.java` (make to execute source file directly, see *more details*)

**Describe GraalVM and your environment:**
 - GraalVM version: **EE 21.3.0**
 - JDK major version: **17**
 - OS: **Windows 10**
 - Architecture: **AMD64**

**More details**
* I think this is caused by EE's JIT for the following reasons:
![image](https://user-images.githubusercontent.com/29547183/142043250-785fee92-99cd-4166-a8a1-969309813385.png)
![image](https://user-images.githubusercontent.com/29547183/142043380-9cdcf6a4-86b2-47b0-bd30-4c34828d564c.png)
* When using `String#indexOf` with a String argument, the correct result is always returned from my testing.
* I've tested all chars from \u0000 to \uFFFF, only those in the range \u0080 to \u00FF cause this issue ([link](https://gist.github.com/TPGamesNL/165e070e54e476c8d83e79da345c6f19)).
* I've tested on CE, but could not replicate the issue with it. I could replicate the issue on EE 21.0.3, the Java 11 version (and 17), but not the Java 8 version.

**Comment by dougxc** [comment]
Thanks for the report with a simple reproducer.
Tracked internally with GR-35116.

**Comment by LiannOM** [comment]
Can someone lmk when issue will be fixed?

**Comment by djoooooe** [comment]
This is fixed in the upcoming 22.0 release.

**Comment by LiannOM** [comment]
Any ETA?

**Comment by dougxc** [comment]
Jan 18th, 2022 (https://www.graalvm.org/release-notes/version-roadmap/)

**Comment by LiannOM** [comment]
Thanks :)
