### ISSUE TITLE
AWT and Swing, on Windows, run with black windows!

### ISSUE THREAD

**Issue by SaltedFishBayonet** [oracle/graal#4037]
I know that new projects tend to be developed in javaFX these days, but I have an old Swing project.
I tried to compile swing programs into EXE using Graal AOT and it worked,
But it runs with a black window.
I know that in traditional Java it should be run with Javaw.exe
In Microsoft VC, you can try removing black Windows with GUI projects, setting window properties to hide, Windows Services projects, and so on.
But I looked through the Graal documentation and found no parameters to help me hide (or did I not see the entry?).
Can you help me?If we don't have this capability now, could we add this simple feature in the future?

**Comment by kristofdho** [comment]
Same question has been answered in this discussion: https://github.com/oracle/graal/discussions/3599

**Comment by oubidar-Abderrahim** [comment]
Please try the solution provided in https://github.com/oracle/graal/discussions/3599 and let us now if it fixed your issue

**Comment by wirthi** [comment]
I am closing this ticket, assuming the link above has solved your problem. If not, please reopen and clarify.
