### ISSUE TITLE
DebugInfo log message are not showing param types in method signatures

### ISSUE THREAD

**Issue by adinn** [oracle/graal#4043]
An error was introduced into the debuginfo code in the patch committed as GR-31277  Full method names printed to the include empty space where a parameter type name should occur in the signature.

Steps to reproduce:

Run a native image compilation with "-H:Log=DebugCodeInfo:3,dwarf:3 -Dgraal.LogFile=out.log" and look in the log for messages starting with "Merge subranges". The method names will include spaces and comma separators i the signatures but will omit type names.

**Comment by zakkak** [comment]
Fixed in https://github.com/oracle/graal/pull/4042
