### ISSUE TITLE
What is the strategy of  memory allocation for SubstrateVM? How do I get more information about that?

### ISSUE THREAD

**Issue by WowYouCanReallyDance** [oracle/graal#4045]
**Describe the issue**
What is the strategy of  memory allocation for SubstrateVM? How do I get more information about that?

**Steps to reproduce the issue**
I notice that the native image got a low memory when application startup (about 30MB with a simple application on JavaFX). But the memory will goes up when I take some simple operation like click button...
Then It will keep on about 320MB stably. I haven't watch the gc happening with a long time (maybe I didn't wait so long enough). So I guess what if it's different from JVM on gc strategy. Cause this is really a high level memory use to executable binary files compares to others like golang...
Hope that somebody help and answer me. Thanks very much!

**And Other Informations**
OS: MacOS Big Sur 11.5.2
ISA: x86_64
GraalVM: 
```bash
openjdk version "11.0.13" 2021-10-19
OpenJDK Runtime Environment GraalVM CE 21.3.0 (build 11.0.13+7-jvmci-21.3-b05)
OpenJDK 64-Bit Server VM GraalVM CE 21.3.0 (build 11.0.13+7-jvmci-21.3-b05, mixed mode, sharing)
```

**Comment by petermz** [comment]
Have you read https://www.graalvm.org/reference-manual/native-image/MemoryManagement/ ? It mostly discusses GC, but also various logging options

**Comment by WowYouCanReallyDance** [comment]
> Have you read https://www.graalvm.org/reference-manual/native-image/MemoryManagement/ ? It mostly discusses GC, but also various logging options

Thanks a lot! That's very helpful.
