### ISSUE TITLE
Need log inside the @Uninterruptible methods for debugging purpose

### ISSUE THREAD

**Issue by ziyilin** [oracle/graal#4050]
**Feature request**

Please include the following information:

**Is your feature request related to a problem? Please describe.**
Current logging class `com.oracle.svm.core.log.RealLog` can't log inside methods with `@Uninterruptible` annotations. However, sometimes we need to track the native image runtime for debugging purpose. 

**Describe the solution you'd like.**
This feature request can be fulfilled with this PR(https://github.com/oracle/graal/pull/4049)

**Comment by wirthi** [comment]
Closing this older ticket, we don't plan on supporting this due to the risks. See https://github.com/oracle/graal/pull/4049
