### ISSUE TITLE
Unable to instantiate class load helper class: org.quartz.simpl.CascadingClassLoadHelper [See nested exception: java.lang.ClassNotFoundException: org.quartz.simpl.CascadingClassLoadHelper]

### ISSUE THREAD

**Issue by liming1010** [oracle/graal#4054]
**Describe the issue**
Quartz is used in the project. It is packaged into an EXE program with native image. The EXE generation is completed, but an error is reported when running
`org.quartz.SchedulerConfigException: Unable to instantiate class load helper class: org.quartz.simpl.CascadingClassLoadHelper [See nested exception: java.lang.ClassNotFoundException: org.quartz.simpl.CascadingClassLoadHelper]
        at org.quartz.impl.StdSchedulerFactory.instantiate(StdSchedulerFactory.java:748)
        at org.quartz.impl.StdSchedulerFactory.getScheduler(StdSchedulerFactory.java:1579)
        at com.st.check.service.QuartzManager.addJob(QuartzManager.java:31)
        at com.st.check.CheckApplication.main(CheckApplication.java:13)
Caused by: java.lang.ClassNotFoundException: org.quartz.simpl.CascadingClassLoadHelper
        at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:53)
        at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:139)
        at org.quartz.impl.StdSchedulerFactory.loadClass(StdSchedulerFactory.java:1533)
        at org.quartz.impl.StdSchedulerFactory.instantiate(StdSchedulerFactory.java:745)
        ... 3 more`

`<graalvm.version>21.3.0</graalvm.version>`

`<dependency>
            <groupId>org.quartz-scheduler</groupId>
            <artifactId>quartz</artifactId>
            <version>2.3.2</version>
        </dependency>
        <dependency>
            <groupId>org.quartz-scheduler</groupId>
            <artifactId>quartz-jobs</artifactId>
            <version>2.3.2</version>
        </dependency>
        <dependency>
            <groupId>org.graalvm.sdk</groupId>
            <artifactId>graal-sdk</artifactId>
            <version>${graalvm.version}</version>
            <scope>provided</scope>
        </dependency>`

`<build>
        <plugins>
            <plugin>
                <groupId>org.graalvm.nativeimage</groupId>
                <artifactId>native-image-maven-plugin</artifactId>
                <version>21.2.0</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>native-image</goal>
                        </goals>
                        <phase>package</phase>
                    </execution>
                </executions>
                <configuration>
                    <skip>false</skip>
                    <imageName>httpchedk</imageName>
                    <mainClass>com.st.check.CheckApplication</mainClass>
                    <buildArgs>
                        --no-fallback
                        --trace-class-initialization=jdk.xml.internal.SecuritySupport
                        --allow-incomplete-classpath
                        --enable-url-protocols=http
                        -H:+AddAllCharsets
                    </buildArgs>
                </configuration>
            </plugin>
        </plugins>
    </build>`

**Comment by rodrigar-mx** [comment]
Hi @liming1010. I need you to share the following information:
i) the specific graalvm version you are using (the output generated by running `java -version` command)
ii) the OS you are using (I suppose it is windows 10)
iii) a reproducer, and the steps to reproduce this issue

As an additional suggestion change `<groupId>org.graalvm.nativeimage</groupId> <artifactId>native-image-maven-plugin</artifactId>` to  ` <groupId>org.graalvm.buildtools</groupId> <artifactId>native-maven-plugin</artifactId>`, which is the new way for building native image with maven. More info [here](https://graalvm.github.io/native-build-tools/latest/index.html#_release_0_9_7_1).
