### ISSUE TITLE
examples or code scraps of how to use crawler4j when pages contain js generated links? ...

### ISSUE THREAD

**Issue by Albretch** [oracle/graal#4058]
java -version
openjdk version "11.0.10" 2021-01-19
OpenJDK Runtime Environment GraalVM CE 21.0.0.2 (build 11.0.10+8-jvmci-21.0-b06)
OpenJDK 64-Bit Server VM GraalVM CE 21.0.0.2 (build 11.0.10+8-jvmci-21.0-b06, mixed mode, sharing)

neither wget nor curl have such a feature and some sites obfuscate access to public domain documents behind js walls

**Comment by mcraj017** [comment]
@Albretch thanks for reporting the issue,
 please elaborate on your issue or requirements, So that we can help you in the right way.

**Comment by Albretch** [comment]
again, how to you crawl pages contain js generated links using java on Truffel?

**Comment by mcraj017** [comment]
@Albretch there is no specific code snippet for this, But I will share links with you to try it out and let us know, if you face errors
Here is the guide to use Java on truffle
https://www.graalvm.org/reference-manual/java-on-truffle/#run-java-on-truffle

Here is the examples of crawler4j
https://github.com/yasserg/crawler4j/tree/master/crawler4j-examples

**Comment by mcraj017** [comment]
Closing this issue now, if you get any error while running your application on Graalvm.
Please create a new issue
