### ISSUE TITLE
Generated proxy-config contains not array but objects from 21.3.0

### ISSUE THREAD

**Issue by KengoTODA** [oracle/graal#4067]
**Describe the issue**

GraalVM 21.2.0 generates the proxy-config as follows, same to the description in the official document:

```json
[
  ["com.example.Printer","com.example.ExitCode"]
]
```

However, GraalVM 21.3.0 generates proxy-config in a different format introduced by #3774:

```json
[
  {
    "interfaces":["com.example.Printer","com.example.ExitCode"]}

]
```

The new format is not described in the [release note](https://www.graalvm.org/release-notes/21_3/), the [reference manual](https://www.graalvm.org/reference-manual/native-image/Reflection/#conditional-configuration), nor the [official medium post](https://medium.com/graalvm/graalvm-21-3-is-here-java-17-native-image-performance-updates-and-more-ac4cbafcfc05).

I wish we have some official references which explain the difference. :)

**Steps to reproduce the issue**

Simply run a jar file using dynamic proxy via `native-image-agent`.
I use a fork of SpotBugs like below:

```
// make sure GraalVM 21.3.0 is in the $JAVA_HOME in advance

$ git clone --branch graalvm git@github.com:KengoTODA/spotbugs.git // f1dcf2c6bcc8f1e173da5f25fc8b96df4fd7b531
$ cd spotbugs
$ ./gradlew assemble -x test
$ cd spotbugs/build/distributions
$ unzip spotbugs-4.5.1-SNAPSHOT.zip
$ export SPOTBUGS=spotbugs-4.5.1-SNAPSHOT/lib/spotbugs.jar
$ java -agentlib:native-image-agent -jar $SPOTBUGS -textui $SPOTBUGS
```

The procedure above will generate `proxy-config.json` like below:

```json
[
  {
    "interfaces":["edu.umd.cs.findbugs.internalAnnotations.SlashedClassName"]}
  ,
  {
    "interfaces":["javax.annotation.Nonnull"]}
  
]
```

**Describe GraalVM and your environment:**
 - GraalVM version: CE 21.3.0
 - JDK major version: **11**
 - OS: macOS 12.0.1 Monterey
 - Architecture: AMD64

**Comment by oubidar-Abderrahim** [comment]
Thank you for reporting this, we will take a look into it and get back to you

**Comment by oubidar-Abderrahim** [comment]
Hi @olyagpl, could you please check with the Dev on the changes introduced in #3774 and reflect them on our reference manual? Thank you

**Comment by olyagpl** [comment]
Will be followed.

**Comment by olyagpl** [comment]
@KengoTODA, thanks for the feedback.We updated https://www.graalvm.org/reference-manual/native-image/DynamicProxy/#manual-configuration and some other places.

**Comment by KengoTODA** [comment]
Hi,

I've checked https://www.graalvm.org/reference-manual/native-image/DynamicProxy/#manual-configuration but no `"interfaces"` JSON parameter found. I guess there is some delay in the site?

**Comment by olyagpl** [comment]
Right, website is refreshed shortly after. The content is single sourced, I should have pointed you to the source https://github.com/oracle/graal/blob/master/docs/reference-manual/native-image/DynamicProxy.md#manual-configuration instead.

**Comment by KengoTODA** [comment]
Thanks @olyagpl! Now I can see the change at both the site and GitHub :)
