### ISSUE TITLE
Graphhopper library shows weird performance pattern when executing with GraalVM 

### ISSUE THREAD

**Issue by thomaswue** [oracle/graal#408]
See https://twitter.com/timetabling/status/993110231252021249

**Comment by karussell** [comment]
This applies only for EE and it is likely as you suggested a warmup problem because increasing the query count to 50K the average response time went down from 19ms to 14ms (similar value we get for the CE)

**Comment by dougxc** [comment]
Hi @karussell , I'm having some problem running the benchmark described at https://discuss.graphhopper.com/t/running-the-routing-engine-on-graalvm-openjdk8-and-openjdk10-shenandoah-gc-zgc/3011. Firstly, it seems as though the dataset URL may be out of date:
```
dsimon@kruger-7 ~/g/graphhopper> ./graphhopper.sh measurement berlin-latest.osm.pbf
## using java 1.8.0_161 (64bit) from /Library/Java/JavaVirtualMachines/jdk1.8.0_161.jdk/Contents/Home
File not found 'berlin-latest.osm.pbf'. Press ENTER to get it from: http://download.geofabrik.de/berlin-latest.osm-latest.osm.pbf
Press CTRL+C if you do not have enough disc space or you don't want to download several MB.

## now downloading OSM file from http://download.geofabrik.de/berlin-latest.osm-latest.osm.pbf and extracting to berlin-latest.osm.pbf
  HTTP/1.1 404 Not Found
  Date: Mon, 07 May 2018 07:57:51 GMT
  Server: Apache/2.4.18 (Ubuntu)
  Content-Length: 317
  Keep-Alive: timeout=5, max=100
  Connection: Keep-Alive
  Content-Type: text/html; charset=iso-8859-1
http://download.geofabrik.de/berlin-latest.osm-latest.osm.pbf:
2018-05-07 09:57:51 ERROR 404: Not Found.
ERROR couldn't download or extract OSM file berlin-latest.osm.pbf ... exiting
```
Browsing around http://download.geofabrik.de I managed to find what I believe is the [right file](http://download.geofabrik.de/europe/germany/berlin-latest.osm.pbf). Now I get another error that I'm not sure how to resolve:
```
dsimon@kruger-7 ~/g/graphhopper> ./graphhopper.sh measurement berlin-latest.osm.pbf
## using java 1.8.0_161 (64bit) from /Library/Java/JavaVirtualMachines/jdk1.8.0_161.jdk/Contents/Home
## using existing osm file berlin-latest.osm.pbf
## existing jar found web/target/graphhopper-web-0.11-SNAPSHOT.jar
## now measurement. JAVA_OPTS=-Xmx1000m -Xms1000m -server

perform measurement via jar=> web/target/graphhopper-web-0.11-SNAPSHOT.jar and ARGS=> config=config.yml graph.location=./berlin-latest.osm-gh datareader.file=berlin-latest.osm.pbf prepare.ch.weightings=fastest prepare.lm.weightings=fastest graph.flag_encoders=car        prepare.min_network_size=10000 prepare.min_oneway_network_size=10000
Error: Could not find or load main class com.graphhopper.tools.Measurement
```
Note that this is with a stock JDK8.

**Comment by karussell** [comment]
Thanks for trying this. Please use the `0.10` branch (sorry, we have to fix the measurement in latest master and also the OSM PBF downloading stuff)

**Comment by dougxc** [comment]
Thanks - 0.10.0 works.
Can you please explain how the numbers in the [table](https://discuss.graphhopper.com/t/running-the-routing-engine-on-graalvm-openjdk8-and-openjdk10-shenandoah-gc-zgc/3011) are extracted 
from the `measurement*.properties` file.

**Comment by karussell** [comment]
Yes, a bit unclear too. Here are the important values (left the key from the measurement properties)

route = routing.mean

route CH = routingCH.mean

route LM4 = routingLM4.mean

prepare CH = prepare.ch.time (is in ms)

The last value prepare.ch.time is only calculated if the graph folder calculated from scratch (can take really long so the default is to avoid calculation if already existent). So the first measurement will contain this value and any follow up measurement will only contain it if one explicitly removes the folder `berlin-latest.osm-latest.osm-gh`.

**Comment by dougxc** [comment]
On my MacBook, I'm unable to reproduce the large outlier time for `route` on Graal EE compared to Graal CE:

measurement | OracleJDK 8u161 | Graal CE | Graal EE
-------------- | ------------- | ------------ | -------------
routing.mean | 9.412532988 | 10.3255645 | 12.907907935999999

I suspect this is result of the slower warmup we currently have for EE.

Please re-open if there's something further you think needs addressing before we solve the warmup issue.

**Comment by karussell** [comment]
Thanks for taking the time for this! Do you have any links to the warmup issue? Or is this an internal issue tracker?

**Comment by dougxc** [comment]
We only have an internal issue tracking the work to compile Graal ahead of time to use as a shared library in HotSpot. It is quite a major change which also requires JVMCI API changes. We hope to have something publicly available within 2 months. I'll be sure to notify https://oss.oracle.com/mailman/listinfo/graalvm-users and https://oss.oracle.com/mailman/listinfo/graalvm-dev once it is out.
