### ISSUE TITLE
ce-builds repository does not mark the most recent released build as latest

### ISSUE THREAD

**Issue by mbarbero** [oracle/graal#4083]
The CE-builds download repository https://github.com/graalvm/graalvm-ce-builds/releases shows release 19.3.6 as the latest release while latest is actually 21.3.0. 

Please mark the most recent release (https://github.com/graalvm/graalvm-ce-builds/releases/tag/vm-21.3.0) as the latest on GitHub.

**Comment by mcraj017** [comment]
@mbarbero thanks for reporting the issue, we will correct it

**Comment by ezzarghili** [comment]
Thank you for the report, this happened due to github changing their sorting algorithm apparently to use committer timestamp instead of publishing stamp and us using a single commit for all releases on the release repo.

Fixed this for now.

**Comment by mbarbero** [comment]
Thank you for the swift fix!
