### ISSUE TITLE
tar: Error opening archive: Failed to open 'graalvm-ce-java17-darwin-amd64-21.3.0.tar.gz'

### ISSUE THREAD

**Issue by ttelang** [oracle/graal#4087]
**Steps to reproduce the issue**
1. Downloaded graalvm-ce-java17-darwin-amd64-21.3.0.tar.gz from this link -> https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-21.3.0/graalvm-ce-java17-darwin-amd64-21.3.0.tar.gz
2. On executing the comment ```$ tar -xzf graalvm-ce-java17-darwin-amd64-21.3.0.tar.gz``` getting error as below: 

> tar: Error opening archive: Failed to open 'graalvm-ce-java17-darwin-amd64-21.3.0.tar.gz'

**Describe GraalVM and your environment:**
 - GraalVM version : graalvm-ce-java17-darwin-amd64-21.3.0
 - JDK major version: 17
 - OS: macOS Big Sur
 - Architecture: AMD64

**Comment by oubidar-Abderrahim** [comment]
Hi, Thank you for reporting this, we will take a look into it and get back to you

**Comment by oubidar-Abderrahim** [comment]
Hi, I downloaded the same version from the link provided and managed to extract it using the `tar -xzf graalvm-ce-java17-darwin-amd64-21.3.0.tar.gz` on macOS Catalina

Please re-download the tar file, it might be corrupted, and also check if you can extract other tar files correctly, it could be something specific to your machine

**Comment by oubidar-Abderrahim** [comment]
I am closing this issue for now, if you still face this problem please reopen it.
