### ISSUE TITLE
LanguageCache.collectLanguages() creates invalid path on Windows

### ISSUE THREAD

**Issue by harmanpa** [oracle/graal#409]
This line fails on Windows:
https://github.com/oracle/graal/blob/3122d963ef7a5e1674ef8f590deda5a85b16ebc0/truffle/src/com.oracle.truffle.api.vm/src/com/oracle/truffle/api/vm/LanguageCache.java#L199

as `((JarURLConnection) connection).getJarFileURL().getPath()` creates a path with a leading slash, e.g. `/C:/path/to/file.jar`

**Comment by vyudenkov** [comment]
The same issue happens when project is merged into the single fat jar file. So path to language on my pc becomes: 
file:/D:/Projects/project/target/project.jar!/BOOT-INF/lib/js-1.0.0-rc16.jar!/META-INF/truffle/language. And Paths.get doesn't understand the nested urls.

**Comment by boris-spas** [comment]
Closing as duplicate, @vyudenkov please open another issue if your problem still persists.
