### ISSUE TITLE
[LLVM] wrong result from bitcode compiled from C source with bitfields

### ISSUE THREAD

**Issue by zhendongsu** [oracle/graal#4091]
GraalVM version or commit id if built from source: GraalVM CE 19.3.6
CE or EE: CE
JDK version: openjdk 11.0.11
OS and OS Version: Ubuntu 18.04
Architecture: amd64
The output of java -Xinternalversion:
OpenJDK 64-Bit Server VM (11.0.11+8-jvmci-19.3-b26) for linux-amd64 JRE (11.0.11+8-jvmci-19.3-b26), built on Apr 12 2021 21:07:52 by "buildslave" with gcc 7.3.0

Also see: https://github.com/oracle/graal/issues/4086

```
[598] % clangg -v
GraalVM wrapper script for clang
GraalVM version: 19.3.6
running: /local/suz-local/software/graalvm-ce-java11-19.3.6/lib/llvm/bin/clang -v
clang version 8.0.0 
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /local/suz-local/software/graalvm-ce-java11-19.3.6/lib/llvm/bin
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/8
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/6
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/6.5.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7.5.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/8
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7.5.0
Candidate multilib: .;@m64
Selected multilib: .;@m64
Found CUDA installation: /usr/local/cuda, version unknown
[599] % lli --version
LLVM (GraalVM CE Native 19.3.6)
[600] % 
[600] % clangg -c -emit-llvm -o small.bc small.c
[601] % 
[601] % lli small.bc
-524288
[602] % 
[602] % clangg small.c; ./a.out
0
[603] % 
[603] % cat small.c
int printf(const char *, ...);
struct  {
  short a;
  int b : 16;
  int c : 19;
} d = {0, 20, 0};
int main() {
  printf("%d\n", d.c);
  return 0;
}
```

Expected output: `0`

This issue does still happen when using the latest snapshot.

**Comment by rodrigar-mx** [comment]
Hi @zhendongsu. GraalVM CE 19.3.6 is a very old version please use GraalVM 21.3.0. Still, I see that you commented that you perform the test in the latest 22.0.0-dev snapshot. I will take a look to this issue and get back to you.

**Comment by mukel** [comment]
The "latest" version was pointing to an old build (but still supported), please see https://github.com/oracle/graal/issues/4083

**Comment by rschatz** [comment]
I think this is actually the same underlying issue as #4086. @rudihorn is currently working on a fix.
