### ISSUE TITLE
VULNERABILITY - RHSA-2021:4374 CVSS Score v3: 9.1 Docker Image - Graal 21.3.0

### ISSUE THREAD

**Issue by debu999** [oracle/graal#4103]
Getting vulnerability - Need fix. Scan is done via AquaSec for the docker image.
RHSA-2021:4374
RHSA-2021:4358
RHSA-2021:4464
RHSA-2021:4595
RHSA-2021:4587
RHSA-2021:4382
RHSA-2021:4059
RHSA-2021:4409
RHSA-2021:4373
RHSA-2021:4424
RHSA-2021:4060
RHSA-2021:4451
RHSA-2021:4451
RHSA-2021:4364
RHSA-2021:4387
RHSA-2021:4386
RHSA-2021:4385
RHSA-2021:4511
RHSA-2021:4489
RHSA-2021:4408
RHSA-2021:4513
Not allowed to procure if there are vulnerabilities in the image. Can this be fixed in new builds of graal VM

**Comment by rodrigar-mx** [comment]
Hi @debu999. Thanks for sharing this. Could you please i) share which graalvm version are you evaluating, ii) steps to generate this report (if possible) iii) and elaborate more on this type vulnerability scan.

**Comment by debu999** [comment]
@rodrigar-mx Thanks for reaching out.
Steps:
We are trying to get the image for version 21.3.0
We use aquasec to scan the images. https://www.aquasec.com/

**Comment by debu999** [comment]
most of them are for the red-hat linux version. All the issues are now having patches, mostly a upgraded redhat linux will solve all the vulnerabilities.

**Comment by debu999** [comment]
More details

https://access.redhat.com/errata/RHSA-2021:4374
https://access.redhat.com/errata/RHSA-2021:4358
https://access.redhat.com/errata/RHSA-2021:4464
https://access.redhat.com/errata/RHSA-2021:4595
https://access.redhat.com/errata/RHSA-2021:4587
https://access.redhat.com/errata/RHSA-2021:4382
https://access.redhat.com/errata/RHSA-2021:4059
https://access.redhat.com/errata/RHSA-2021:4409
https://access.redhat.com/errata/RHSA-2021:4373
https://access.redhat.com/errata/RHSA-2021:4424
https://access.redhat.com/errata/RHSA-2021:4060
https://access.redhat.com/errata/RHSA-2021:4451
https://access.redhat.com/errata/RHSA-2021:4451
https://access.redhat.com/errata/RHSA-2021:4364
https://access.redhat.com/errata/RHSA-2021:4387
https://access.redhat.com/errata/RHSA-2021:4386
https://access.redhat.com/errata/RHSA-2021:4385
https://access.redhat.com/errata/RHSA-2021:4511
https://access.redhat.com/errata/RHSA-2021:4489
https://access.redhat.com/errata/RHSA-2021:4408
https://access.redhat.com/errata/RHSA-2021:4513

**Comment by rodrigar-mx** [comment]
How are you building building/getting the image for graalvm 21.3.0?

**Comment by debu999** [comment]
docker pull ghcr.io/graalvm/graalvm-ce:21.3.0 
Once the image is pulled to staging platfomr, AQUASEC scan the image and details are publish if no vulnerabilty it uploads to private container registry else throw error. The one is have listed above are detected during the scan of the image.

**Comment by rodrigar-mx** [comment]
Thanks @debu999. I have reported this issue internally. An answer will be provided accordingly.

**Comment by dougxc** [comment]
What files in the GraalVM image are these reports related to?

**Comment by debu999** [comment]
More details :
Install Aquasec Trivy: **https://aquasecurity.github.io/trivy/v0.18.3/installation/**
Download the image: **docker pull ghcr.io/graalvm/graalvm-ce:latest**
Run the Scan: **trivy image ghcr.io/graalvm/graalvm-ce:latest**
Attaching the report for reference.

ghcr.io/graalvm/graalvm-ce:latest (oracle 8.4)
==============================================
**Total: 141 (UNKNOWN: 0, LOW: 18, MEDIUM: 73, HIGH: 43, CRITICAL: 7)**

Refer to the attachment for details.

Java (jar)
==========
**Total: 0 (UNKNOWN: 0, LOW: 0, MEDIUM: 0, HIGH: 0, CRITICAL: 0)**


[graalvm-ce-trivy-scan.txt](https://github.com/oracle/graal/files/7749480/graalvm-ce-trivy-scan.txt)

Vulnerable Library:
![Screenshot 2021-12-21 at 10 33 19 AM](https://user-images.githubusercontent.com/1910577/146874364-b88cdfca-00c3-4662-8619-f7cb79911a3b.png)
![Screenshot 2021-12-21 at 10 35 12 AM](https://user-images.githubusercontent.com/1910577/146874369-3ce86ae0-9191-4eb9-aad1-b66997f4c5d0.png)

**Comment by debu999** [comment]
Release | General Availability Date | redhat-release Errata Date* | Kernel Version
--------- | ------------ | ----------------------------- | ------------
RHEL 8.5 | 2021-11-09 | 2021-11-09 RHSA-2021:4356 | 4.18.0-348

I believe moving to the latest RHEL 8.5 will definitely fix most of the issues . Current image is built with RHEL 8.4 which have the vulnerabilities.

**Comment by dougxc** [comment]
Tracked internally by GR-35944.

**Comment by debu999** [comment]
Looking forward to it...

**Comment by debu999** [comment]
Hi Team any thing done in upgrading to latest RHEL version?

**Comment by debu999** [comment]
Hi Team,
Can we expect a new version of Graal with new Rhel Base immage???

**Comment by rodrigar-mx** [comment]
HI @debu999. Still is work in progress. We will notify you as soon as there is any update.

**Comment by debu999** [comment]
Graal new version have the fix we can close it now
