### ISSUE TITLE
[LLVM] wrong result from valid bitcode compiled from C source at -Os (not at the other optimization levels)

### ISSUE THREAD

**Issue by zhendongsu** [oracle/graal#4109]
GraalVM version or commit id if built from source: GraalVM CE 22.1.0-dev-20211209_2306 (the latest snapshot build from https://github.com/graalvm/graalvm-ce-dev-builds/releases)
CE or EE: CE
JDK version: openjdk 11.0.13
OS and OS Version: Ubuntu 18.04
Architecture: amd64
The output of `java -Xinternalversion`:
OpenJDK 64-Bit Server VM (11.0.13+8-jvmci-22.0-b02) for linux-amd64 JRE (11.0.13+8-jvmci-22.0-b02), built on Nov 22 2021 22:03:35 by "buildslave" with gcc 7.3.0

```
[601] % clangg22dev -v
GraalVM wrapper script for clang
GraalVM version: Development Build
running: /local/suz-local/software/graalvm-ce-java11-22.1.0-dev/lib/llvm/bin/clang -v
clang version 12.0.1 (GraalVM.org llvmorg-12.0.1-3-g6e0a5672bc-bgf11ed69a5a 6e0a5672bc058d882dce3d56f90b72b64a6870d7)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /local/suz-local/software/graalvm-ce-java11-22.1.0-dev/lib/llvm/bin
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/8
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/6
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/6.5.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7.5.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/8
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7.5.0
Candidate multilib: .;@m64
Selected multilib: .;@m64
Found CUDA installation: /usr/local/cuda, version 11.0
[602] % 
[602] % lli22dev --version
LLVM 12.0.1 (GraalVM CE Native 22.1.0-dev)
[603] % 
[603] % clangg22dev -Os small.c
[604] % ./a.out
1
[605] % lli22dev ./a.out
0
[606] % 
[606] % cat small.c
int printf(const char *, ...);
short a = 1, b;
int main() {
  for (; b < 1; b++)
      a = a & 1;
  printf("%d\n", a);
  return 0;
}
```

Expected output: `1` (as shown above)
However, lli returns the incorrect result `0`.

**Comment by mcraj017** [comment]
@zhendongsu thanks for reporting the issue, please share a reproducer

**Comment by zhendongsu** [comment]
Thanks @mcraj017; please refer to the detailed report above for reproducing this issue.

**Comment by mcraj017** [comment]
@zhendongsu thanks for the reply, please a sample code or steps to reproduce the error reported in this issue

**Comment by mcraj017** [comment]
@zhendongsu closing this for now, please reopen it with a sample code to reproduce the reported error

**Comment by zhendongsu** [comment]
@rschatz

**Comment by rschatz** [comment]
I think I found the issue. Thanks a lot for reporting this!

**Comment by zhendongsu** [comment]
> I think I found the issue. Thanks a lot for reporting this!

Great; thanks for looking into this and the other bugs, Roland!
