### ISSUE TITLE
Can't install Graalvm native-image on ubuntu 20.04.3 LTS

### ISSUE THREAD

**Issue by zedbeit** [oracle/graal#4112]
**Describe the issue**
I've just downloaded and installed graalvm-ce-java11-21.3.0. By default Native Image is not available, so i needed to add it. so i ran this command `$GRAAL_HOME/bin/gu install native-image` but it failed.

**Describe GraalVM and your environment:**
 - GraalVM version: **[e.g. GraalVM CE 21.3.0]**
 - JDK major version: **[openjdk version "11.0.13"]**
 - OS: **[ubuntu 20.04.3 LTS]**
 - Architecture: **[AMD64]**

**Stack Trace**
```
Downloading: Release index file from oca.opensource.oracle.com
Downloading: Component catalog from www.graalvm.org
Processing Component: Native Image
Downloading: Component native-image: Native Image  from github.com
Installing new component: Native Image (org.graalvm.native-image, version 21.3.0)
Installation of Native Image failed: /home/deehaz/Downloads/graalvm-ce-java11-21.3.0/lib/graal_isolate.h: Operation not permitted
I/O error occurred: /home/deehaz/Downloads/graalvm-ce-java11-21.3.0/lib/graal_isolate.h: Operation not permitted

```

**Comment by fniephaus** [comment]
It looks like there's an issue with file system permissions. Did you download and extract your GraalVM installation as root and then tried to install Native Image as normal user?

**Comment by zedbeit** [comment]
Yeah my bad. It's fixed now. Thanks
