### ISSUE TITLE
[LLVM] Sharing context between threads causes crash when sem_t is used

### ISSUE THREAD

**Issue by roxanan-adyen** [oracle/graal#4134]
**Describe GraalVM and your environment :**
 - GraalVM version or commit id if built from source: **21.2.0**
 - CE or EE: **EE**
 - JDK version: **JDK11**
 - OS and OS Version: * macOS bigSur**
 - Architecture: **amd64**
 - The output of `java -Xinternalversion`:
```
Java HotSpot(TM) 64-Bit Server VM (11.0.12+8-LTS-jvmci-21.2-b06) for bsd-amd64 JRE (11.0.12+8-LTS-jvmci-21.2-b06), built on Jul  1 2021 04:44:57 by "graal2" with gcc 4.2.1 Compatible Apple LLVM 11.0.0 (clang-1100.0.33.17)
```

**Have you verified this issue still happens when using the latest snapshot?**
Yes, I tried 21.3.0 version and I had the same issue. 

**Describe the issue**
I created a simple C shared library with the managed tools where I use `sem_t`. I use this library in a java app. If I load the library in the main thread and in the same thread I execute the C side, everything works fine. But if I load the library in main thread and execute the C function in another thread, this causes a crash in `sem_wait()`. It may be related to [#4133](https://github.com/oracle/graal/issues/4133). 

**How to compile the LLVM bitcode that causes the problem**
 I used llvm managed tools to compile the C library.
 ```
 $GRAALVM_MANAGED_LLVM_TOOLCHAIN/clang -fPIC -shared crash_sem.c -lgraalvm-llvm -o crash.so
 ``` 
Where 
```
export GRAALVM_MANAGED_LLVM_TOOLCHAIN=$($GRAALVM_HOME/bin/lli --print-toolchain-path --llvm.managed)
```

**Code snippet or code repository that reproduces the problem**
This is the C code -- crash_sem.c:
```
#include <stdio.h>
#include <sys/stat.h>
#include <semaphore.h>

sem_t mutex;

int my_function() {
    printf("C started\n");
    sem_init(&mutex, 0, 1);
    sem_wait(&mutex);
    printf("do sth\n");
    sem_post(&mutex);

    return 0;
}
```

This is the Java class where I use only on thread. 
```
import java.io.*;
import org.graalvm.polyglot.*;

class JavaMainThread {
    public static void main(String[] args) throws Exception {
        Context polyglot = Context.newBuilder().allowAllAccess(true).allowIO(true).option("llvm.managed", "true").build();
        File file = new File("crash.so");
        Source source = Source.newBuilder("llvm", file).build();
        Value cpart = polyglot.eval(source);
        cpart.invokeMember("my_function");

    }
}
```
This is the Java class where I use 2 threads.
```
import java.io.*;
import org.graalvm.polyglot.*;

class Java2Threads {
    public static void main(String[] args) throws Exception {
        Context polyglot = Context.newBuilder().allowAllAccess(true).allowIO(true).option("llvm.managed", "true").build();
        File file = new File("crash.so");
        Source source = Source.newBuilder("llvm", file).build();
        Value cpart = polyglot.eval(source);

        Thread myThread = new Thread(() -> { // Lambda Expression
            System.out.println("MyThread running" + Thread.currentThread().getId());
            cpart.invokeMember("my_function");
        });

        myThread.start();
        myThread.join();

    }
}
```

**Steps to reproduce the problem**
1. GRAALVM_MANAGED_LLVM_TOOLCHAIN/clang -fPIC -shared crash_sem.c -lgraalvm-llvm -o crash.so
2. javac JavaMainThread.java && java JavaMainThread
 Output:
```
C started
do sth
```
3. javac Java2Threads.java && java Java2Threads 
Output:
```
MyThread running20
C started
Exception in thread "Thread-5" Illegal null pointer access in 'load i64'.
        at <llvm> my_function(crash_sem.c:10:158)
        at org.graalvm.sdk/org.graalvm.polyglot.Value.invokeMember(Value.java:932)
        at Java2Threads.lambda$main$0(Java2Threads.java:13)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

**Expected behavior**
Calling `sem_wait` in another thread should not have unpredictable behavior.

**Comment by rschatz** [comment]
I'm currently debugging that issue, I have a suspicion what it is. Definitely looks like an issue on our side. Thanks for reporting!

**Comment by rschatz** [comment]
I think this is actually the same issue as https://github.com/oracle/graal/issues/4133
The underlying issue seems to be that `pthread_self` doesn't work, and this is used internally in both `stat` and the sem functions.
