### ISSUE TITLE
Server crashes with sun.awt.geom.Order1.getReversedCurve

### ISSUE THREAD

**Issue by skbeh** [oracle/graal#4140]
**Describe the issue**
The Minecraft server crashes sometimes when there is someone playing in the server. The problematic frame is always `sun.awt.geom.Order1.getReversedCurve`.

**Steps to reproduce the issue**
1. `wget https://github.com/TacoSpigot/TacoSpigot/releases/download/v1.8.8-R1.0/TacoSpigot.jar`
2. `java -jar TacoSpigot.jar`
3. Agree the eula and do step 2 again.
4. Run a 1.8.9 Minecraft client to connect to the server, (do something in the game to warm up?), sometimes it will crash. Maybe you need to add the plugins mentioned in the log.
This problem also happends with [Dionysus](https://github.com/nopjmp/Dionysus) on JDK 17.

**Describe GraalVM and your environment:**
 - GraalVM version GraalVM EE 21.3.0
 - JDK major version: 8 or 17 (maybe also 11)
 - OS: Debian 11
 - Architecture: AMD64

**More details**
[hs_err_pid236682.log](https://github.com/oracle/graal/files/7739256/hs_err_pid236682.log)

**Comment by rodrigar-mx** [comment]
Hi @skbeh. Could you please try deactivating the JVMCI Compiler by using the flag `-XX:-UseJVMCICompiler ` and share if the error persists.

**Comment by kirillp** [comment]
@skbeh 
sun.awt is a Desktop module that is not designed to work on server
One should not use it on server side because its threading model is edt while server threading model does not have a edt.

**Comment by skbeh** [comment]
> @skbeh sun.awt is a Desktop module that is not designed to work on server One should not use it on server side because its threading model is edt while server threading model does not have a edt.

The Minecraft server is really old and I am not familiar with its code. Maybe it is because of historical reason. But I have not faced the problem before I updated graalvm to 21.3.0.

**Comment by rodrigar-mx** [comment]
@skbeh could you please try testing using the requested flag `-XX:-UseJVMCICompiler`, and also performing a test with latest graalvm 22.0.0-dev version https://github.com/graalvm/graalvm-ce-dev-builds/releases.
