### ISSUE TITLE
[Documentation] Small improvement suggestion for the official "tutorial" at "https://www.graalvm.org/docs/getting-started/"

### ISSUE THREAD

**Issue by rubyFeedback** [oracle/graal#4158]
Hey folks,

First, excuse me filing the issue here; I could not find a "Documentation" issue. Adding this to the template may be useful, as my
report here is solely about documentation.

Right now I am working through a graalVM tutorial again. I downloaded graalvm, and it works fine on my linux box. \o/

I could run "javac" and "java" so this is fine.

Next on my todo list is trying to test javascript, just to see how this works (and if) via graalvm.

So I am on that page right now:

https://www.graalvm.org/docs/getting-started/

Have a look at the following text there:

"Run JavaScript and Node.js

GraalVM can execute plain JavaScript code, both in REPL mode and by executing script files directly:

js"

The example showed to type js. It took me a while to realise that this is referring to a file, e. g.
/usr/bin/js.

My suggestion is to add a SHORT sentence mentioning this at the official documentation too,
to avoid this possible tiny confusion users may have.

So here is my suggestion to change this sentence:

"GraalVM can execute plain JavaScript code, both in REPL mode and by executing script files directly:"

To something like that:

"GraalVM can execute plain JavaScript code, both in REPL mode and by executing script files directly,
 via the distributed binary bin/js. Invoke it directly via:"

Or something like that ^^^. The idea here is to denote that "js" is a binary. When I first saw the code
example, I thought it was a header in that div-tag to indicate that what follows next is simply javascript
code, so I was not sure what I'd have to do in order to test javascript. When in reality it just was the
name of the binary - may be obvious to you GraalVM folks, but newcomers do strange things and
get confused a lot as well! Hence why a short clarification would be useful, IMO.

PS: I don't know if filing documentation issues here at github is the right thing to do or not, but from a
user's point of view, it would simplify if we can just use github issues as-is. I know the jruby folks 
handle issues requests from A to Z at github too, which makes it simple to propose (small) changes
such as documentation improvements.

**Comment by rubyFeedback** [comment]
Hmm ... guess I filed the wrong issue tag; I did not add the "bug" label ^^^, that was done automatically.

Are the "documentation issues" labels or something like that? Would seem more logical IMO.

**Comment by olyagpl** [comment]
Hi @rubyFeedback, I've pushed some text updates to the getting started guide. Please expect them this/next week.
thanks for sharing your experience!

**Comment by wirthi** [comment]
Documentation at https://www.graalvm.org/22.2/docs/getting-started/#run-javascript-and-nodejs now clearly shows `js` is a binary from the graalvm directory that you can call.
