### ISSUE TITLE
[Documentation] Small suggestion to add a sentence or so to "native-image" compiling standalone files

### ISSUE THREAD

**Issue by rubyFeedback** [oracle/graal#4159]
Hey folks,

I am continuing to work through the graalvm guide at:

https://www.graalvm.org/docs/getting-started/

So far everything worked very well. The only small suggestion I have is to make it
easier to install emcc, but this is NOT the reason why I created this issue here.

Right now I am at this step:

    javac HelloWorld.java
    native-image HelloWorld

This worked too!

New generated files are helloworld.build_artifacts.txt and a fat 15MB helloworld.

Invoking this via ./helloworld very quickly shows "hello world", so it seems to 
work. Need to test it with larger projects, but the fact that this works for me
on a first try means this is pretty cool. If I can manage to get things to work,
others can do so. I represent Average Joe in the end!

That this is a fat 15MB is a bit strange, but, whatever, size is not that important
these days, unless for a microcontroller, and my primary aim is to just get
this to work. I work on Linux mostly but I like that java works on windows just
fine, so having native-image is like a nifty feature.

Now here is the thing though: I don't know if this will work on windows. I
have a separate windows box so I can test at a later time, but here is my
first suggestion:

"If the above commands are run, and a helloworld file is created on a linux
box, please add to the tutorial whether this works on windows as well or
not."

And then the SECOND issue is:

"IF it does not work on windows when compiled on linux, please consider
adding a short example ONLY for that hello world, what to change on linux
to have this work on windows as well."

The rationale for that last sentence is that ideally I'd love to write the code
on Linux (I am much faster there) and then simply "dump" it onto windows
as-is and have it work there. I believe this would be a huge win-win situation
for many people. Those who prefer windows can work on windows just
as well; and, even if that does not work, it is no big deal for me to
auto-compile this on windows. I know that ruby works on windows fine
so I guess I can install graalvm there and have ruby call these binaries
just like any other binaries, so I think this is also fine - my POINT is more
that, hopefully, it should be MENTIONED in the documentation as-is,
so that people can instantly know it.

I suggest an additional sentence such as "This binary will work on
windows too, if it was generated on linux", or something similar to
that message, so that people know that it works on a first glance without
having to try.

I will try at a later time anyway, but then I know, and thus I am no longer
one of those totally clueless noobs - so this is more a plea to extend
the documentation a little bit in this regard. Thanks for reading!

PS: I can somewhat figure out that this only works on linux, via the
"Invoking it executes the natively compiled code " aka natively
compiled part, so my question is PROBABLY answered. But I'd
like to have this even more clearer in the documentation so people
instantly know that this will not work on windows. Which is fine:
I can use ruby to auto-compile these things anyway on windows,
and then distribute the file to other windows machines from there.

**Comment by hilycker** [comment]
You figured it right, you can run what you compiled only on the platform you used for compilation. So what you're looking for is cross compilation, try searching for it, there is something on the internet although I can't comment on it because I've never tried, just googled out of curiosity. Anyway I'd like to know too if any progress toward implementing cross compilation were made or is it still a feature not looked at

**Comment by olyagpl** [comment]
Hi @rubyFeedback,
What you are talking about is cross compilation, which is not currently possible.  It is stated in the [Native Image guide](https://www.graalvm.org/reference-manual/native-image/) that "...ahead-of-time compiles that reachable code and data to a native executable **for a specific operating system and architecture**". There are parts of the JDK initialized during the image building process that could be platform dependent and then end up in the image. 
You can follow this GitHub feature request https://github.com/oracle/graal/issues/407 to see if this is happening.

You may consider GitHub actions to build images for different platforms, as  @thomaswue suggested in [that discussion](https://github.com/oracle/graal/issues/407#issuecomment-592758158). 
This blog post could be a good reference for you: https://blogs.oracle.com/developers/post/building-cross-platform-native-images-with-graalvm.
 
Lastly, please check a Windows specific blog post: [Using GraalVM and Native Image on Windows 10](https://medium.com/graalvm/using-graalvm-and-native-image-on-windows-10-9954dc071311).

**Comment by wirthi** [comment]
Thanks for your suggestion, I don't think there is an immediate todo for us here. Cross compilation might come eventually and tracked at https://github.com/oracle/graal/issues/407
