### ISSUE TITLE
Exception in thread "main" java.lang.NoSuchFieldError: java.awt.Component.x trying to use JFrame

### ISSUE THREAD

**Issue by BluCobalt** [oracle/graal#4161]
Running a native image compiled with the gradle plugin doesn't work with awt; I have a test app that consists of a simple JFrame that I am trying to compile with native image but runtime fails with the following stack trace:
```
Exception in thread "main" java.lang.NoSuchFieldError: java.awt.Component.x
	at com.oracle.svm.jni.functions.JNIFunctions$Support.getFieldID(JNIFunctions.java:1126)
	at com.oracle.svm.jni.functions.JNIFunctions.GetFieldID(JNIFunctions.java:428)
	at java.awt.Component.initIDs(Component.java)
	at java.awt.Component.<clinit>(Component.java:624)
	at java.lang.Class.ensureInitialized(DynamicHub.java:552)
	at java.lang.Class.ensureInitialized(DynamicHub.java:552)
	at java.lang.Class.ensureInitialized(DynamicHub.java:552)
	at java.lang.Class.ensureInitialized(DynamicHub.java:552)
	at java.lang.Class.ensureInitialized(DynamicHub.java:552)
```
This is what I have in my build.gradle.kts:
```kts
graalvmNative {
    binaries {
        named("main") {
            buildArgs.add("-Djava.awt.headless=false")
        }
    }
}
```
I found #3669 which seems to be the same issue but in that case the gradle plugin wasn't being used.
```
# java -version
openjdk version "11.0.13" 2021-10-19
OpenJDK Runtime Environment GraalVM CE 21.3.0 (build 11.0.13+7-jvmci-21.3-b05)
OpenJDK 64-Bit Server VM GraalVM CE 21.3.0 (build 11.0.13+7-jvmci-21.3-b05, mixed mode, sharing)
```

**Comment by kkriske** [comment]
Not a bug.
You are simply missing [JNI configuration](https://github.com/oracle/graal/blob/master/docs/reference-manual/native-image/JNI.md) of the `Component#x` field, which was also the resolution of the issue you linked.
Try running your app with the [native image agent](https://github.com/oracle/graal/blob/master/docs/reference-manual/native-image/Agent.md) first to collect the required configuration, and include that in your build.

**Comment by BluCobalt** [comment]
Can I have a gradle task that runs my app with the native image agent?

**Comment by kkriske** [comment]
That's part of the feature set of the [GraalVM Native Image plugin](https://graalvm.github.io/native-build-tools/0.9.4/gradle-plugin.html#_reflection_support_and_running_with_the_native_agent), so yes it's possible.
I haven't used it though, but documentation should be sufficient to figure it out.

**Comment by chirontt** [comment]
> Can I have a gradle task that runs my app with the native image agent?

You can configure the `run` task (defined in the `application` plugin) to execute your app with the native-image agent (in Groovy):

```
run {
    mainClass = 'your.main.App'
    jvmArgs = [
        '-agentlib:native-image-agent=config-merge-dir=/path/to/your/native-image/configs'
    ]
}
```
