### ISSUE TITLE
AMD64DarwinUContextRegisterDumperFeature is not triggered for org.graalvm.nativeimage.Platform.IOS_AMD64

### ISSUE THREAD

**Issue by kirillp** [oracle/graal#4162]
After fixing this https://github.com/oracle/graal/pull/3859 
I've found a new issue: AMD64DarwinUContextRegisterDumperFeature is not triggered for 
org.graalvm.nativeimage.Platform.IOS_AMD64
GraaVM 22.0 is affected

As a result we can see a following error in during build

Fatal error: com.oracle.svm.core.util.VMError$HostedError: guarantee failed
	at com.oracle.svm.core.util.VMError.shouldNotReachHere(VMError.java:68)
	at com.oracle.svm.core.util.VMError.guarantee(VMError.java:82)
	at com.oracle.svm.core.SubstrateSegfaultHandlerFeature.beforeAnalysis(SubstrateSegfaultHandler.java:76)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$runPointsToAnalysis$9(NativeImageGenerator.java:694)

**Comment by kirillp** [comment]
I fixed this by adding required annotations
https://github.com/Montura/graal/commit/d9d9a1a4c1e5d331bf9a8fb0ee443ec14c7db4b9

after the fix the build works again

**Comment by jperedadnr** [comment]
I've run into this same issue, and the proposed fix works for me too.

**Comment by teshull** [comment]
From my perspective, the issue here is that IOS is a subclass of DARWIN, but IOS_AARCH64 and IOS_AMD64 are not subclasses of DARWIN_AARCH64 and DARWIN_AMD64. I think also there should be an explicit MACOS leaf platform.

You can track the fix at https://github.com/oracle/graal/pull/4171

**Comment by kirillp** [comment]
can we see this in 22 ?

**Comment by jperedadnr** [comment]
Tested #4171, works fine on macOS (AMD64), iOS (AArch64) and iOS simulator (AMD64).

**Comment by teshull** [comment]
#4171 has been merged, so this should be resolved

**Comment by Noisyfox** [comment]
So will this be released in 22.1 or 22.x?

**Comment by kirillp** [comment]
22.1 I guess, you can find my build in my repo already. We have migrated to 22.1 beta with 17. And then I was removed

**Comment by Noisyfox** [comment]
Yeah I'm trying to apply your patch to 22.0.

**Comment by kirillp** [comment]
My patch is for java 17. We decided to drop j11 since it is maintenance state
