### ISSUE TITLE
Tomcat Native Image build issues

### ISSUE THREAD

**Issue by marcorobiati** [oracle/graal#4164]
EDITED: added info with new tests and better clarification

Tomcat 10.0.14
Windows 10 x64 21H1 OS Build 19043.1415
NetBeans 12.6, maven webapp project
Maven 3.8.4
Ant 1.10.12

openjdk version "11.0.13" 2021-10-19
OpenJDK Runtime Environment GraalVM CE 21.3.0 (build 11.0.13+7-jvmci-21.3-b05)
OpenJDK 64-Bit Server VM GraalVM CE 21.3.0 (build 11.0.13+7-jvmci-21.3-b05, mixed mode, sharing)

openjdk version "17.0.1" 2021-10-19
OpenJDK Runtime Environment GraalVM CE 21.3.0 (build 17.0.1+12-jvmci-21.3-b05)
OpenJDK 64-Bit Server VM GraalVM CE 21.3.0 (build 17.0.1+12-jvmci-21.3-b05, mixed mode, sharing)

GraalVM CE 22.0.0-dev-20211222_1041
openjdk version "11.0.13" 2021-10-19
OpenJDK Runtime Environment GraalVM CE 22.0.0-dev (build 11.0.13+8-jvmci-22.0-b02)
OpenJDK 64-Bit Server VM GraalVM CE 22.0.0-dev (build 11.0.13+8-jvmci-22.0-b02, mixed mode, sharing)

GraalVM CE 22.0.0-dev-20211222_1041
openjdk version "17.0.2" 2022-01-18
OpenJDK Runtime Environment GraalVM CE 22.0.0-dev (build 17.0.2+5-jvmci-22.0-b02)
OpenJDK 64-Bit Server VM GraalVM CE 22.0.0-dev (build 17.0.2+5-jvmci-22.0-b02, mixed mode, sharing)

Followed guide at https://tomcat.apache.org/tomcat-10.0-doc/graal.html

Sorry in advance if not all issues should be reported here but instead are tomcat related, I'm reporting everything here and on their mailing list for completeness.
https://lists.apache.org/thread/pc0cj9dn9ovxs1qqlqq6p3x88k0jwpmk

https://drive.google.com/file/d/1105hPdeA8xqtLfl6QbaI6KTozMJ2bySV/view?usp=sharing
https://drive.google.com/file/d/17_JXqNNBZCfCW8-JDl2Kocx0NzEVdc-J/view?usp=sharing
In these links you can find a folder with everything I used from tomcat stuffed folder downloaded from the github link present in the tomcat AOT guide, to all commands I put in a script for easier testing purpose, source webapp, built webapp, screenshots for tests with graalvm CE 21.3 java 11 and java 17

all commands/script run as admin.
everytime changed JAVA_HOME and graalvm/bin in PATH enviornment variables to reflect actual graalvm used for tests.

I'll start by saying I'm well aware I could definitely have overlooked something, anyway I managed to get to the final native image and it works, BUT:

1a) JAVA 11 and 17: If there is a class extending ServletContextListener, when running command with "--catalina -generateCode" parameter, where you have to access all jsps and servlets, the class extending ServletContextListener (InitClass in this example) will be initialized/used(?) like 2 times, but the second time not completly, resetting everything done in the first initialization.
1b) JAVA 11 and 17: if after mvn package run after ant, classes and jsps are removed from webapps/webappname folder, when running command with "--catalina -generateCode" parameter classes aren't found, jsps are. I accessed page.jsp manually on url, it executed it BUT it run InitClass (which is accessed from that jsp) with the already mentioned problem, only static block is initialized. So it's like it is actually able to access compiled classes inside the jar but in a strange way ??!?!
-This is strange because those files are actually present in the fat jar, and this actually beats the purpose of builidng a native image if you have to ship it with java files.
-If you first run with webapps folder without the webapp and only then copy the BUILT webapp in the folder everything will work correctly, even with ServletContextListener

2a-b) JAVA 11:after -generateCode phase, inside ContextXmlDefault.java "\" in paths in watched resources aren't escaped so need to be manually replaced with / or manually escaped else the following mvn package will fail

3a) JAVA 11 and 17: no problems.
3b) JAVA 11 and 17: (after manually escaping/replacing "/", mvn package runs fine for JAVA 11). Same as 1b)

4a-b) JAVA 17: when building with native-image command, if "-J--add-exports=java.management/sun.management=ALL-UNNAMED" isn't used as additional parameter, errors will pop on run crashing the app.

5a) JAVA 11 and 17: no problems.
5b) JAVA 11 and 17: native binary run, with or without parameters, same behaviour as point 1b)

With dev build, the only difference is that on JAVA 17 there's no need anymore to use -J--add-exports=java.management/sun.management=ALL-UNNAMED

Any idea how to fix: The bundle named: org.apache.catalina.tribes.transport.bio.LocalStrings, has not been found. If the bundle is part of a module, verify the bundle name is a fully qualified class name. Otherwise verify the bundle path is accessible in the classpath.
The bundle named: org.apache.tomcat.util.threads.res.LocalStrings, has not been found. If the bundle is part of a module, verify the bundle name is a fully qualified class name. Otherwise verify the bundle path is accessible in the classpath.

**Comment by marcorobiati** [comment]
Updated with new info and new tests

**Comment by oubidar-Abderrahim** [comment]
Hi, thank you for reporting this issue, could you please provide the following information:

1. Does your application run correctly on the JVM before building the native image?
2. Did you try generating the native-image configuration files using our [native-image-agent](https://www.graalvm.org/reference-manual/native-image/Agent/)?
3. Do you use the x64 Native Tools Command Prompt for generating native images on Windows? please see the Windows section in [here](https://www.graalvm.org/reference-manual/native-image/) for more info.
4. For providing a code example, please upload your code to a Github repository mentioning any necessary prerequisites to have/install in the readme file, and share the repo's link in this issue.

**Comment by marcorobiati** [comment]
Hello, I forgot to specify I've read and followed https://www.graalvm.org/docs/getting-started/ and https://www.graalvm.org/reference-manual/native-image/
1: It does in every configuration, I omitted adding this information because I took it for granted
2: I did, as it's used in the guide I used, which I linked in the post above, and can be found in the files I linked too.
3: I do.
4.https://github.com/marcorobiati/tomcat-native-image-test-j11 and https://github.com/marcorobiati/tomcat-native-image-test-j17

Thanks

**Comment by oubidar-Abderrahim** [comment]
Hi, I did some research on this, and it does seem to be an issue for the Tomcat side. I could be wrong though. I would suggest checking with the Tomcat team before. 
If it turns out otherwise, please don't hesitate to reopen the issue and share any findings from the Tomcat team with us to further investigate the issue.
