### ISSUE TITLE
Unable to use appd with graalvm generated binary , error ERROR registering tracer => com.oracle.svm.core.jdk.UnsupportedFeatureError: Proxy class defined by interfaces [interface com.appdynamics.serverless.tracers.aws.registration.RegistrationService] not found. Generating proxy classes at runtime is not supported. Proxy classes need to be defined at image build time 

### ISSUE THREAD

**Issue by pradeepkusingh** [oracle/graal#4174]
**Describe the issue**
Unable to use appd with graalvm generated binary , error ERROR registering tracer => com.oracle.svm.core.jdk.UnsupportedFeatureError: Proxy class defined by interfaces [interface com.appdynamics.serverless.tracers.aws.registration.RegistrationService] not found. Generating proxy classes at runtime is not supported. Proxy classes need to be defined at image build time 

I have added bellow in dynamic-proxies.json and still seeing above error

[
  ["org.apache.http.conn.HttpClientConnectionManager","org.apache.http.pool.ConnPoolControl","com.amazonaws.http.conn.Wrapped"],
  ["org.apache.http.conn.ConnectionRequest","com.amazonaws.http.conn.Wrapped"],
  ["com.appdynamics.serverless.tracers.dependencies.org.apache.http.conn.HttpClientConnectionManager",
    "com.appdynamics.serverless.tracers.dependencies.org.apache.http.pool.ConnPoolControl",
    "com.appdynamics.serverless.tracers.dependencies.com.amazonaws.http.conn.Wrapped",
    "com.appdynamics.serverless.tracers.aws.registration.RegistrationService"],
    ["com.appdynamics.serverless.tracers.aws.registration.RegistrationService"]
]

**Steps to reproduce the issue**
- Try to setup appd on a graalvm generated binary for aws lambda

**Describe GraalVM and your environment:**
 - GraalVM version " GRAAL_VERSION 20.1.0
 - JDK major version: JDK 8
 - OS: Linux
 - Architecture: x86

**More details**
Consider adding the `--native-image-info` and  `--verbose` flags when building your native image and paste output below.

Add any other information about the problem here. Especially important are stack traces or log output. Feel free to link to gists or to screenshots if necessary.
```
    PASTE YOUR LOG/STACK TRACE HERE
```

AppDynamics Tracer] [INFO]: Creating AppDynamics Tracer with version: 'null'.
[AppDynamics Tracer] [ERROR]: ERROR creating logger => com.amazonaws.services.lambda.runtime.LambdaRuntime$1.log(java.lang.String)
[AppDynamics Tracer] [INFO]: Found environment property [APPDYNAMICS_LOG_LEVEL = DEBUG]
[AppDynamics Tracer] [INFO]: Setting log level to => [DEBUG]
[AppDynamics Tracer] [INFO]: Version Info: [null]
[AppDynamics Tracer] [INFO]: Initializing AppDynamics Agent.
[AppDynamics Tracer] [DEBUG]: Generated hash [01cbe49ca1e273e1f65647281eb636de4389b405] for key [*(-aps-lower.saas.appdynamics.com|443|context-us-east-1-staging|null]
[AppDynamics Tracer] [DEBUG]: Unable to parse integer from port null
[AppDynamics Tracer] [DEBUG]: Proxy server not configured, continuing
[AppDynamics Tracer] [ERROR]: ERROR registering tracer => com.oracle.svm.core.jdk.UnsupportedFeatureError: Proxy class defined by interfaces [interface com.appdynamics.serverless.tracers.aws.registration.RegistrationService] not found. Generating proxy classes at runtime is not supported. Proxy classes need to be defined at image build time by specifying the list of interfaces that they implement. To define proxy classes use -H:DynamicProxyConfigurationFiles=<comma-separated-config-files> and -H:DynamicProxyConfigurationResources=<comma-separated-config-resources> options.

**Comment by oubidar-Abderrahim** [comment]
Hi, Thank you for reporting this, Please use the latest build (currently 21.3.0) and let the native-image-agent generate the configuration for your application while you run it as a Java app with appd, then include the generated configs in the image build. 
please let us know your findings.

**Comment by oubidar-Abderrahim** [comment]
close for inactivity
