### ISSUE TITLE
Support WebAssembly Reference Types Draft externref (0x6F)

### ISSUE THREAD

**Issue by iwangxiaodong** [oracle/graal#4175]
**Feature request**

Please include the following information:

**Is your feature request related to a problem? Please describe.**
bin/wasm ... include-externref.wasm execute result - CompileError: Invalid value type: 0x6F

**Describe the solution you'd like.**
Support WebAssembly Reference Types Draft externref (0x6F)

**Describe who do you think will benefit the most.**
Improve WebAssembly

**Describe alternatives you've considered.**
Nothing

**Additional context.**
Nothing

**Express whether you'd like to help contributing this feature**
Nothing

Thanks!

**Comment by iwangxiaodong** [comment]
No such problem.

Sorry!

**Comment by iwangxiaodong** [comment]
Please add ReferenceTypes.EXTERNREF in ReferenceTypes.FUNCREF 🥺

**Comment by rodrigar-mx** [comment]
Hi @iwangxiaodong. Could you please share _include-externref.wasm_ and the steps to reproduce the error.

**Comment by iwangxiaodong** [comment]
[include-externref.zip](https://github.com/oracle/graal/files/7832126/include-externref.zip)

uploaded


**I tested in chrome:**
```js
/*
(module
  (import "imports" "jsFunc" (func $plus (param externref externref) (result externref)))
  (func (export "wasmFunc") (param externref) (result externref)
    (call $plus (local.get 0) (local.get 0)))
)
*/
    const x = new WebAssembly.Instance(wasmModule, { imports: { jsFunc: (p, p2) => p + p2 } });
    const { wasmFunc } = x.exports;
    console.log(wasmFunc("x"));

**Comment by iwangxiaodong** [comment]
![image](https://user-images.githubusercontent.com/16535878/148626219-5c74b0b9-d0f4-4b92-8218-014b5f7102b7.png)

**bin\wasm** "C:\Users\privacy\Downloads\include-externref.wasm"

**Comment by rodrigar-mx** [comment]
Thanks for sharing @iwangxiaodong. The feature request has now been reported internally. You will receive a response accordingly.
