### ISSUE TITLE
[GR-36201] Avoid control chars in new build output to dumb terminals

### ISSUE THREAD

**Issue by adinn** [oracle/graal#4181]
The new build output is wonderful except when you are running your build inside a dumb terminal (i.e. a shell inside emacs). The control sequences posted to the tty just make a mess of the output so it looks like this:

    $ mx debuginfotest
    . . .
    ================================================================================
    ^[]8;;https://www.graalvm.org/native-image^[\GraalVM Native Image^[]8;;^[\: Generating 'hello.hello'...
    ================================================================================
    [1/7] ^[]8;;https://github.com/oracle/graal/blob/master/docs/reference-manual/native-image/BuildOutput.md#stage-initializing^[\Initializing^[]8;;^[\...                                            (5.3s @ 0.27GB)
     ^[]8;;https://github.com/oracle/graal/blob/master/docs/reference-manual/native-image/BuildOutput.md#glossary-version-info^[\Version info^[]8;;^[\: 'GraalVM dev Java 11 CE'
    . . .

The mx native image build command should check for a dumb terminal (os.getenv(("TERM") == "dumb") and explicitly disable the build output options that generate control chars in this case.

**Comment by adinn** [comment]
n..b this should be assigned to me and marked as being fixed by issue #4180

**Comment by jerboaa** [comment]
Fixed with: https://github.com/oracle/graal/commit/909ae11ee18ea4b25666d341ca56d528b3123818
