### ISSUE TITLE
Creation of native image on windows 10 doesn't work.

### ISSUE THREAD

**Issue by jarostein** [oracle/graal#4186]
Hi there!
I started learning and experimenting with Quarkus framework recently, as training I have developed a couple of microservices using GraalVM CE 21.3.0, on Windows Home 10, Apache Maven 3.8.4. 
In dev mode the microservices are working properly, but when I try to generate the native image using a _**x64 Native Tools Command Prompt for VS 2022**_ for that purpose, with the following command:

mvn package -Pnative -DskipTests=true

or 

mvn package -Dquarkus.package.type=native -Dmaven.test.skip=true

it does not work, throwing the following exception:

[ERROR] Failed to execute goal io.quarkus.platform:quarkus-maven-plugin:2.6.1.Final:build (default) on project microservice_name: Failed to build quarkus application: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
[ERROR]         [error]: Build step io.quarkus.container.image.deployment.ContainerImageProcessor#publishImageInfo threw an exception: java.lang.IllegalArgumentException: The supplied combination of container-image group 'USER_NAME' and name 'microservice_name' is invalid
[ERROR]         at io.quarkus.container.image.deployment.ContainerImageProcessor.publishImageInfo(ContainerImageProcessor.java:81)
[ERROR]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR]         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR]         at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[ERROR]         at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:887)
[ERROR]         at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
[ERROR]         at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
[ERROR]         at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
[ERROR]         at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
[ERROR]         at java.base/java.lang.Thread.run(Thread.java:829)
[ERROR]         at org.jboss.threads.JBossThread.run(JBossThread.java:501)

The Research on internet didn't help, because I didn't found a similar case, thats why I would like to know if you can help me to solve the issue.

**Details of GraalVM and used environment:**
 - GraalVM version: **OpenJDK Runtime Environment GraalVM CE 21.3.0 (build 11.0.13+7-jvmci-21.3-b05)
OpenJDK 64-Bit Server VM GraalVM CE 21.3.0 (build 11.0.13+7-jvmci-21.3-b05, mixed mode, sharing)**
 - JDK major version: **openjdk version "11.0.13" 2021-10-19**
 - OS: **Windows 10 Home**
 - Architecture: **AMD64**
 - Apache Maven: **3.8.4**
 - Eclipse IDE: **IDE for Enterprise Java and Web Developers- 2021-09**

P.S.: Very interesting is that the same exception it is exposed trying to create a linux native image, using the following maven command:

mvn package -Pnative -Dquarkus.native.container-build=true -DskipTests=true

Another curious fact is that the failure happens when some code has been added to the project, this means that, when a new Quarkus project has been brand new created with the wizard of the Eclipse IDE 2021-09, the mvn command generates a native image as expected.

Thanks in advance.

Jaroslav

**Comment by oubidar-Abderrahim** [comment]
Hi, Thank you for reporting this, Could you please share a small reproducer to illustrate the issue on a Github repo? Thank you

**Comment by jarostein** [comment]
Hi @oubidar-Abderrahim, thanks for commenting to my post.

As a part of a training with Quarkus Framework, I have created a very simple project (with only three classes). Using the Wizard offered by **Quarkus Tools 4.21.0.Final** Eclipse's plugin (IDE for Enterprise Java and Web Developers- 2021-09)
 
 this is the corresponding POM:
 
 `<?xml version="1.0"?>
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.ias</groupId>
  <artifactId>microservice_name</artifactId>
  <version>1.0.0-SNAPSHOT</version>
  <properties>
    <compiler-plugin.version>3.8.1</compiler-plugin.version>
    <maven.compiler.release>11</maven.compiler.release>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
    <quarkus.platform.artifact-id>quarkus-bom</quarkus.platform.artifact-id>
    <quarkus.platform.group-id>io.quarkus.platform</quarkus.platform.group-id>
    <quarkus.platform.version>2.6.1.Final</quarkus.platform.version>
    <surefire-plugin.version>3.0.0-M5</surefire-plugin.version>
  </properties>
  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>${quarkus.platform.group-id}</groupId>
        <artifactId>${quarkus.platform.artifact-id}</artifactId>
        <version>${quarkus.platform.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
    </dependencies>
  </dependencyManagement>
  <dependencies>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-arc</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-resteasy</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-resteasy-jsonb</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-container-image-docker</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-junit5</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>io.rest-assured</groupId>
      <artifactId>rest-assured</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-smallrye-openapi</artifactId>
    </dependency>
  </dependencies>
  <build>
    <plugins>
      <plugin>
        <groupId>${quarkus.platform.group-id}</groupId>
        <artifactId>quarkus-maven-plugin</artifactId>
        <version>${quarkus.platform.version}</version>
        <extensions>true</extensions>
        <executions>
          <execution>
            <goals>
              <goal>build</goal>
              <goal>generate-code</goal>
              <goal>generate-code-tests</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>${compiler-plugin.version}</version>
        <configuration>
          <compilerArgs>
            <arg>-parameters</arg>
          </compilerArgs>
        </configuration>
      </plugin>
      <plugin>
        <artifactId>maven-surefire-plugin</artifactId>
        <version>${surefire-plugin.version}</version>
        <configuration>
          <systemPropertyVariables>
            <java.util.logging.manager>org.jboss.logmanager.LogManager</java.util.logging.manager>
            <maven.home>${maven.home}</maven.home>
          </systemPropertyVariables>
        </configuration>
      </plugin>
    </plugins>
  </build>
  <profiles>
    <profile>
      <id>native</id>
      <activation>
        <property>
          <name>native</name>
        </property>
      </activation>
      <build>
        <plugins>
          <plugin>
            <artifactId>maven-failsafe-plugin</artifactId>
            <version>${surefire-plugin.version}</version>
            <executions>
              <execution>
                <goals>
                  <goal>integration-test</goal>
                  <goal>verify</goal>
                </goals>
                <configuration>
                  <systemPropertyVariables>
                    <native.image.path>${project.build.directory}/${project.build.finalName}-runner</native.image.path>
                    <java.util.logging.manager>org.jboss.logmanager.LogManager</java.util.logging.manager>
                    <maven.home>${maven.home}</maven.home>
                  </systemPropertyVariables>
                </configuration>
              </execution>
            </executions>
          </plugin>
        </plugins>
      </build>
      <properties>
        <quarkus.package.type>native</quarkus.package.type>
      </properties>
    </profile>
  </profiles>
</project>`

In dev mode, using the following maven command: 

mvn compile quarkus:dev 

the application runs well, the three classes do what they should also while executing the tests, the project it is successfuly builded with;

mvn test.

 But trying to generate the native image using; 
 
`mvn package -Dquarkus.package.type=native -Dmaven.test.skip=true`
 
 or 
 
`mvn package -Pnative -DskipTests=true` 

thows the exception mentioned in my previous message. 

According to the tracktrace message; 
"java.lang.IllegalArgumentException: The supplied combination of container-image group 'USER_NAME' and name 'microservice_name' is invalid", it seems to be an configuration problem, thats why I'm wondering why it is happening. I have installed the GraalVM and already set properly the enviromental variables; 
JAVA_HOME, ->  C:\Program Files\GraalVM\graalvm-ce-java11-windows-amd64-21.3.0\graalvm-ce-java11-21.3.0

M2_HOME, -> C:\Program Files\apache-maven-3.8.4 ,and 

PATH, ->  %JAVA_HOME%\bin, %M2_HOME%\bin.

**Comment by jarostein** [comment]
After several attempts, I found out the exception is thrown when the **quarkus-container-image-docker** dependency it is used. 
Just commenting out that dependency and the maven command `mvn package -Pnative` works well! 
But I don't understand exactly why that dependency affects generation of the native image.

**Comment by fniephaus** [comment]
It seems this is more of a Quarkus issue rather than of Native Image. Could you please file an issue at https://github.com/quarkusio/quarkus/issues in case you haven't already?

**Comment by Karm** [comment]
@oubidar-Abderrahim This issue can be closed now.
