### ISSUE TITLE
Missing documentation on gu page and CLI options

### ISSUE THREAD

**Issue by aalmiray** [oracle/graal#4191]
**Describe the issue**
This page describe a few options for the `gu` command line https://www.graalvm.org/reference-manual/graalvm-updater/#installation-configuration

Invoking `gu --help` yields similar options but not the same

```
gu -h
GraalVM Component Updater v2.0.0

Usage: 
	gu info [-cClLnprstuvV] <param>         prints info about specific component (from file, URL or catalog)
	gu available [-aClvV] <expr>            lists components available in catalog
	gu install [-0CcDfiLMnosruvyxY] <param> installs a component package
	gu list [-clv] <expression>             lists installed components, or components from catalog
	gu remove [-0DfMxv] <id>                uninstalls a component
	gu upgrade [-cCnLsuxSd] [<ver>] [<cmp>] upgrades to recent GraalVM or edition
	gu rebuild-images                       rebuilds native images. Use -h for detailed usage

Common options:
  -A, --auto-yes              say YES or ACCEPT to all questions.
  -c, --catalog               treat parameters as component IDs from catalog of GraalVM components. This is the default.
  -C, --custom-catalog <url>  use user-supplied catalog at URL.
  -e, --debug                 debugging. Prints stacktraces, ...
  -E, --no-catalog-errors     do not stop, if at least one catalog is working.
  -h, --help                  print help.
  -L, --local-file, --file    treat parameters as local filenames of packaged components.
  -N, --non-interactive       noninteractive mode. Fail when input is required.
  --show-version              print version information and continue.
  -u, --url                   interpret parameters as URLs of packaged components.
  -v, --verbose               be verbose. Prints versions and dependency info.
  --version                   print version.

Use 
	gu <command> -h
to get specific help.

Runtime options:
  --native                                     Run using the native launcher with limited access to Java libraries (default).
  --jvm                                        Run on the Java Virtual Machine with access to Java libraries.
  --vm.[option]                                Pass options to the host VM. To see available options, use '--help:vm'.
  --log.file=<String>                          Redirect guest languages logging into a given file.
  --log.[logger].level=<String>                Set language log level to OFF, SEVERE, WARNING, INFO, CONFIG, FINE, FINER, FINEST or ALL.
  --help                                       Print this help message.
  --help:vm                                    Print options for the host VM.

See http://www.graalvm.org for more information.
```

Note that the page lists gu's install options as  `gu install [-0cCfFiLnorsuvyxY]` while the CLI lists them as `gu install [-0CcDfiLMnosruvyxY]`. The `M` option is missing from the page. Also, descriptions on some of those options are missing in the CLI but available at the page.

**Steps to reproduce the issue**
Please include both build steps as well as run steps
1. sdk install java 21.3.0.r17-grl    
2. gu --help

**Describe GraalVM and your environment:**
 - GraalVM version: **21.3.0**
 - JDK major version: **17**
 - OS: **macOs BigSur**
 - Architecture: **AMD64**

**Comment by olyagpl** [comment]
Andres, thanks for pointing this out. Time to update. I'll follow.

**Comment by aalmiray** [comment]
FWIW I'd prefer if all CLI options & flags were documented in the CLI tools, as well as web pages. For example, `native-image` advanced options are currently only available form the CLI when you run it. This assumes you have access to the CLI to get the list of options and their descriptions. 

What if I'm on an iPad changing/browsing code with an online editor? I can't run the CLI to find the flag that needs tweaking to get my build unstuck, can I?

Please consider keeping CLI tools and docs in sync.

**Comment by rubyFeedback** [comment]
> were documented in the CLI tools, as well as web pages

Completely agreed. I always hated reading man-pages or man-pages like
options; always preferred web-based views and explanations.

I guess the simplest way to maintain this would be to focus on the CLI,
and then simply have some ruby or python script autogenerate the
documentation with a bit of CSS styling (or just the general CSS theme
used on the graalvm homepage). That way people could concentrate
on the CLI, and the information contained therein be automatically
made available on the www, via some fitting styling in place.

**Comment by wirthi** [comment]
Closing this, as `gu` is no longer actively maintained.
