### ISSUE TITLE
Debian and RPM repositories for GraalVM stable and nightly builds.

### ISSUE THREAD

**Issue by Yush08** [oracle/graal#4207]
**Feature request**

**Is your feature request related to a problem? Please describe.**
Whenever I try to install GraalVM, I always have to manually wget the tarball and add the directory to my $PATH. In my opinion, having repositories for Debian and RPM distributions can greatly decrease this hassle. And GraalVM can automatically get upgraded through the package manager as well.

**Describe the solution you'd like.**
By hosting Debian and RPM repositories.

**Describe who do you think will benefit the most.**
Users of GraalVM and CI/CD

**Express whether you'd like to help contributing this feature**
I can help by contributing these repositories by repacking the official tarballs and hosting them on a GitHub repository.

**Comment by rubyFeedback** [comment]
I handle this by just downloading the generic linux variant of graalvm, install into /home/Programs/Graalvm/VERSION_HERE, and then symlink from that bin/ directory onto /usr/bin/. This is a bit similar to GoboLinux and it works very well. I use the same for openjdk.

Now, that does not have much to do with your use case, I understand, but the problem I see is that you have to maintain tons of distribution-specific packages, which really shouldn't be the concern of the GraalVM team. Debian in particular has people that package stuff - it's not anyone else's fault if they are slow. It also confuses people which variant is in use - the same happened to ruby by the way. People on IRC would come to #ruby and ask why their ruby variant (debian specific and modified by debian) misbehaves (e. g. no mkmf and other stdlib parts that the debian guys removed). So I really think this should not be the GraalVM team to add support for what the distribution maintainers should do - and, as I mentioned above, the default download works fine. I use this for libreoffice too and it works - no idea why people are so attached to distributions. (See also the variant I described above - I can upgrade or downgrade just fine, I just have to change one symlink effectively under /home/Programs/).

I suppose if there is an automatic way then the GraalVM team could offer that with specific warnings in place, but other than that IMO I think it is not a good idea to offer +50 different downloads for every linux distribution variant. But of course that is ultimately just my opinion - I just saw how it caused upstream devs to focus on issues that IMO should not be their concern from the beginning. Let the distribution maintainers handle that, and if they are slow, ask them to not be turtles and snails.

**Comment by rodrigar-mx** [comment]
Hi @Yush08. For the moment there are no plans for making available graalvm ce in debian and rpm repositories because that requires extra maintenance and support. (However, for OCI users there are rpm packages available for graalvm ee). 
For CI you can also use the [container images](https://www.graalvm.org/docs/getting-started/container-images/). Also, some users install graalvm through [sdkman](https://sdkman.io/jdks#grl), but this is not maintained directly by the graalvm team.
