### ISSUE TITLE
Is Windows still not supportd by llvm-toolchain component ?

### ISSUE THREAD

**Issue by Revolution2021** [oracle/graal#4215]
Hi, 

I am now trying to run Python on GraalVM(CE) based on this document.
https://www.graalvm.org/python/quickstart/
My OS is Windows 10.

I follow the below process.

===================
Install Python
The Python runtime is not shipped with the default GraalVM installation package, but can be quickly added using the updater utility, gu:

gu install python
The Python runtime requires the LLVM toolchain for its operation, and you will be prompted to install this dependency, if not yet installed:

gu install llvm-toolchain
Once Python’s runtime is installed, the graalpython binary appears in the JAVA_HOME/bin/ directory.

=======================

However, I got the following error.

******************************
C:\WINDOWS\system32>gu --version
GraalVM Updater 21.3.0

C:\WINDOWS\system32>gu install llvm-toolchain
Downloading: Release index file from oca.opensource.oracle.com
Downloading: Component catalog from www.graalvm.org
Error: Unknown component: llvm-toolchain

C:\WINDOWS\system32>java --version
openjdk 11.0.13 2021-10-19
OpenJDK Runtime Environment GraalVM CE 21.3.0 (build 11.0.13+7-jvmci-21.3-b05)
OpenJDK 64-Bit Server VM GraalVM CE 21.3.0 (build 11.0.13+7-jvmci-21.3-b05, mixed mode, sharing)
*******************************

Why ?
Is Windows still not supported by LLvm-toolchain ? 

Regards,

**Comment by fniephaus** [comment]
I'm afraid neither GraalPython nor the llvm-toolchain are supported on Windows at the moment  (and I don't think there is an ETA for any of the two):

> *[Currently, the GraalVM environment on Windows can be extended with Native Image, Java on Truffle, WebAssembly, and Node.js support.](https://www.graalvm.org/docs/getting-started/windows/)*

**Comment by Revolution2021** [comment]
Oh, thanks for your quick reply. 
Got it.
