### ISSUE TITLE
native-image fails to find module resource

### ISSUE THREAD

**Issue by petermz** [oracle/graal#4221]
Looks like module support introduced recently interferes with resource lookup. I'm trying to read a resource from a system module. It works with 21.3 but fails with a recent dev build.

The immediate cause as I see it is that the resource is keyed with a (moduleName, resourceName) pair at image build time, but is looked up using just resourceName at run time:
https://github.com/oracle/graal/blob/6f0aa43ba9982f250e5a444236adcb8ed46a5b8a/substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jdk/resources/ResourceURLConnection.java#L66

**Steps to reproduce the issue**
1. **javac ResourceTest.java**
2. **native-image -H:IncludeResources='/java/lang/uniName.dat' ResourceTest**
3. **./resourcetest**

**Describe GraalVM and your environment:**
 - GraalVM version: **GraalVM 22.1.0-dev Java 11 CE (Java Version 11.0.13+8-jvmci-22.0-b02)**
 - JDK major version: **11**
 - OS: **Oracle Linux**
 - Architecture: **AMD64**

**Output**
```
URL is resource:java/lang/uniName.dat
java.io.FileNotFoundException: resource:java/lang/uniName.dat
	at com.oracle.svm.core.jdk.resources.ResourceURLConnection.getInputStream(ResourceURLConnection.java:87)
	at java.net.URL.openStream(URL.java:1165)
	at ResourceTest.main(ResourceTest.java:10)

```
**Expected output (actually produced by GraalVM 21.3.0)**
```
URL is resource:java/lang/uniName.dat
first byte is 120
```

**Comment by petermz** [comment]
Code to reproduce:
```
import java.io.IOException;
import java.io.InputStream;
import java.net.URL;

public class ResourceTest {
    public static void main(String[] args) {
        URL url = Class.class.getResource("/java/lang/uniName.dat");
        System.out.println("URL is " + url);
        if (url != null) {
            try (InputStream in = url.openStream()) {
                System.out.println("first byte is " + in.read());
            } catch (IOException e) {
                e.printStackTrace();
            }
        }
    }
}
```

**Comment by rodrigar-mx** [comment]
Thanks for reporting this issue. We will take a look into it and get back to you.

**Comment by rodrigar-mx** [comment]
This issue has now been reported internally. Any questions or updates we will let you know.

**Comment by olpaw** [comment]
> Code to reproduce:

@petermz this example does not even work on the JVM. Can you provide me with a working example?

**Comment by petermz** [comment]
What do you mean by "does not work"? It prints two lines and exits, which is not much, but its point is to show that the resource actually exists and can be read from (i.e. `InputStream.read()` succeeds)

**Comment by olpaw** [comment]
Fixed with https://github.com/oracle/graal/commit/86f7b49eb4632f7791d0f30d787a8c3f0023411f

Now e.g.
```java
import java.io.IOException;
import java.io.InputStream;
import java.net.URL;
public class ResourceTest {
    public static void main(String[] args) {
        URL url = Class.class.getResource("uniName.dat");
        System.out.println("URL is " + url);
        if (url != null) {
            try (InputStream in = url.openStream()) {
                System.out.println("first byte is " + in.read());
            } catch (IOException e) {
                e.printStackTrace();
            }
        }
    }
}
```
works on JVM with
```
java --add-opens=java.base/java.lang=ALL-UNNAMED ResourceTest
```
and with native-image using
```
native-image java --add-opens=java.base/java.lang=ALL-UNNAMED -H:IncludeResources=java.base:java/lang/uniName.dat ResourceTest
```

**Comment by petermz** [comment]
Thanks Paul -- my original (more complicated) scenario seems to be working now.
