### ISSUE TITLE
Native image for java swing in windows

### ISSUE THREAD

**Issue by susil556** [oracle/graal#4223]
**Feature request**

Please include the following information:

**Is your feature request related to a problem? Please describe.**ted when [...]

I got to know for java swing native-image conversion availble for linux. When it will be available for windows?

**Describe the solution you'd like.**

**Describe who do you think will benefit the most.**
GraalVM users, GraalVM contributors, developers of libraries and frameworks which depend on GraalVM, or somebody else?

**Describe alternatives you've considered.**

**Additional context.**
Add any other context about the feature request here.
For example, link to the relevant projects, documentation, standards.

**Express whether you'd like to help contributing this feature**
If you'd like to contribute, please read the [contribution guide](https://www.graalvm.org/community/contributors/).

**Comment by kkriske** [comment]
Please look for similar issues before creating a new one: https://github.com/oracle/graal/issues/3659 https://github.com/oracle/graal/issues/2644 https://github.com/oracle/graal/issues/4165 https://github.com/oracle/graal/issues/4072 https://github.com/oracle/graal/issues/3084
Native image definitely works for simple Swing applications, as per previous linked issues.

If you have a specific use-case where it does not work, please create an issue with the required information.

**Comment by rodrigar-mx** [comment]
Closing this issue as it has been requested before, and the native image team is already aware of.
