### ISSUE TITLE
native-image from 22.1.0 has issues resolving core svm classes.

### ISSUE THREAD

**Issue by michael-simons** [oracle/graal#4229]
**Describe the issue**

When creating a native image from a JVM program that depends on a library containing conditional substations for `com.oracle.svm.core.jdk.JDK11OrLater` , native-image fails with `Fatal error: java.lang.TypeNotPresentException: Type com.oracle.svm.core.jdk.JDK11OrLater not present`. The substitutions in the library are compiled with `org.graalvm.nativeimage:svm:21.3.0` in provided scope.

This works fine with up to 21.3.0 and produces a native image.

**Steps to reproduce the issue**

Both a library and client are attached as Maven projects, please download and unzip them both:

[some-library.zip](https://github.com/oracle/graal/files/7891090/some-library.zip) and 
[some-client.zip](https://github.com/oracle/graal/files/7891102/some-client.zip)

```bash
curl -OL https://github.com/oracle/graal/files/7891090/some-library.zip
unzip some-library.zip
cd some-library
mvn install
cd ..
curl -OL https://github.com/oracle/graal/files/7891102/some-client.zip
unzip some-client.zip
cd some-client
mvn package
native-image -jar target/some-client-1.0-SNAPSHOT-jar-with-dependencies.jar
```

**Describe GraalVM and your environment:**

```
java -version
openjdk version "17.0.2" 2022-01-18
OpenJDK Runtime Environment GraalVM CE 22.1.0-dev (build 17.0.2+5-jvmci-22.0-b02)
OpenJDK 64-Bit Server VM GraalVM CE 22.1.0-dev (build 17.0.2+5-jvmci-22.0-b02, mixed mode, sharing)

native-image --version
GraalVM 22.1.0-dev Java 17 CE (Java Version 17.0.2+5-jvmci-22.0-b02)
```

macOS 12.1, Intel

**More details**

Working version

```
java -version
openjdk version "17.0.1" 2021-10-19
OpenJDK Runtime Environment GraalVM CE 21.3.0 (build 17.0.1+12-jvmci-21.3-b05)
OpenJDK 64-Bit Server VM GraalVM CE 21.3.0 (build 17.0.1+12-jvmci-21.3-b05, mixed mode, sharing)

native-image --version
GraalVM 21.3.0 Java 17 CE (Java Version 17.0.1+12-jvmci-21.3-b05)
```

outputs

```
./some-client-1.0-SNAPSHOT-jar-with-dependencies 
Something else
```

This will affect the Neo4j-Java driver.

**Comment by rodrigar-mx** [comment]
Thanks for reporting this issue. We will take a look into it and get back to you.

**Comment by michael-simons** [comment]
Thanks @rodrigar-mx Please let me know if you need input. Right now, our driver can't be used with GraalVM 22.1 and we would love to change or fix that.

**Comment by rodrigar-mx** [comment]
Hi @michael-simons. This PR should fix the issue https://github.com/oracle/graal/pull/4277 and should be integrated in the next dev build.

**Comment by michael-simons** [comment]
Oh that's lovely! Exactly what I have hoped for.

I wonder how to tackle that in the future. `JDK11OrLater` is likely to stay there, right? Library authors are probably fine with removing `JDK8OrEarlier` at some point when Graal doesn't support JDK anymore.

**Comment by michael-simons** [comment]
Aaah, he who reads has an advantage, I did saw the deprecations. Nice solution. Thank you.
