### ISSUE TITLE
Google links broken

### ISSUE THREAD

**Issue by mklueh** [oracle/graal#4232]
In case you are not aware of the issue, when googling for graal-related things, many links are broken and are showing 404 errors, such as

https://www.graalvm.org/reference-manual/native-image/ClassInitialization/

<img width="463" alt="image" src="https://user-images.githubusercontent.com/1553757/150005925-501b1e0b-03bc-4b35-813d-78dc80128157.png">

**Comment by oubidar-Abderrahim** [comment]
Hi, thank you for reporting this, we've set up redirects to our new link: https://www.graalvm.org/22.0/reference-manual/native-image/ClassInitialization/
I've tested it and it should be working, please give it a try and let us know if any link is still not functioning
Thank you
