### ISSUE TITLE
Native image Isolates are not able to access run time set system properties

### ISSUE THREAD

**Issue by zakkak** [oracle/graal#4238]
**Describe the issue**
Invoking `System.getProperty()` to get the value of a run time set system property works as expected in native images, but fails when done from an Isolate.

**Steps to reproduce the issue**
```
cd /tmp
git clone --branch isolates-hardcoded-properties https://github.com/zakkak/issue-reproducers reproducers
cd reproducers
export JAVA_HOME=/opt/jvms/graalvm-ce-java11-21.3.0
mvn package
$JAVA_HOME/bin/native-image \
  --no-fallback -H:+ReportExceptionStackTraces \
  -jar target/reproducer-1.0-SNAPSHOT.jar
./reproducer-1.0-SNAPSHOT -Dproperty.to.override=42
```

**Describe GraalVM and your environment:**
 - GraalVM version: **21.3.0**
 - JDK major version: **11**
 - OS: **Fedora 35**
 - Architecture: **AMD64**

**Comment by AndreiYu** [comment]
We made a workaround - `CustomRuntimeConfigSource` that has higher ordinal than System properties and Environment Variables

https://quarkus.io/guides/config-extending-support#example

Isolates are unable to see changes of system properties (since they have a snapshot of Image Heap at build or start time of native executable), but isolate refreshes env_variable changes with `CustomRuntimeConfigSource` with ordinal 500 and evaluates them at change. Here is a snippet of code:

```
@StaticInitSafe
public class RuntimeEnvConfigSource implements ConfigSource {

	@Override
	public Map<String, String> getProperties() {
		return System.getenv();
	}

	@Override
	public Set<String> getPropertyNames() {
		return System.getenv().keySet();
	}

	@Override
	public int getOrdinal() {
		return 500;
	}

	@Override
	public String getValue(String name) {
		if (name == null) {
			return null;
		}

		// exact match
		var data = System.getenv();
		String value = data.get(name);
		if (value != null) {
			return value;
		}

		// replace non-alphanumeric characters by underscores
		String sanitizedName = replaceNonAlphanumericByUnderscores(name);
		value = data.get(sanitizedName);
		if (value != null) {
			return value;
		}

		// replace non-alphanumeric characters by underscores and convert to uppercase
		return data.get(sanitizedName.toUpperCase());
	}

	@Override
	public String getName() {
		return RuntimeEnvConfigSource.class.getSimpleName();
	}
}
```

**Comment by oubidar-Abderrahim** [comment]
Hi thank you for reporting this, we will take a look into in and get back to you

**Comment by oubidar-Abderrahim** [comment]
Tracked internally on GR--36661

**Comment by christianwimmer** [comment]
@zakkak looking at your example, I would say the current behavior is what we want. The same holds for runtime options too that are set via `-XX:` on the command line: arguments passed on the command line only affect the main isolate that is automatically created for the `main` method. If you create isolates manually, you have full control over system properties and arguments, i.e., nothing is inherited from the creating isolate.

**Comment by zakkak** [comment]
Thanks for looking into this @christianwimmer. 

Is there any documentation around Isolates explaining what's expected to be shared between the main isolate and the other isolates that I failed to locate?
The only resource I could find is [this medium article](https://medium.com/graalvm/isolates-and-compressed-references-more-flexible-and-efficient-memory-management-for-graalvm-a044cc50b67e), according to which the only common state is the initial image heap as generated at build time. Is there anything else that gets inherited/shared other than that?

**Comment by christianwimmer** [comment]
> Is there any documentation around Isolates explaining what's expected to be shared between the main isolate and the other isolates

There is nothing shared between isolates. At least on the Java side - of course all isolates are in the same process so any C static variable exists only once per process.
