### ISSUE TITLE
[native-image] running play on GraalVM/SubstrateVM

### ISSUE THREAD

**Issue by schmitch** [oracle/graal#424]
Hello, 
I wanted to share my knowledge of running Play on GraalVM and wanted to point out some "issues" along the way.

Some error messages I couldn't really resolve are these:
- Error: Must not have a FileDescriptor in the image heap.
- Error: Must not have a started Thread in the image heap.

See: https://gist.github.com/schmitch/469eae4062373b6fe67def99ec220103
(I also created a repository to reproduce them: https://github.com/schmitch/play-scala-starter-example)

After that I tried to create a Play application in the "embedded" mode which is basically described here: https://www.playframework.com/documentation/2.6.x/ScalaEmbeddingPlayAkkaHttp
The good thing is, the issue's above aren't raised, however I had a problem because of the issues I described here: https://discuss.lightbend.com/t/akka-and-graal-s-native-image-tool/940/9

Currently I guess after fixing these "issues" there is still some work for play because in some cases we need proxy's or reflection where we might not need to. But a simple application could probably be made to run under substratevm.

**Comment by cstancu** [comment]
@schmitch thank you for your report. The `Must not have a <unsupported-feature> in the image heap.` errors have been updated and are more descriptive now: 
```
Detected an <unsupported-feature> in the image heap. This is not supported. 
The object was reached from a static initializer. All static class initialization 
is done during native image construction, thus a static initializer cannot 
contain code that captures state dependent on the build machine. Write 
your own initialization methods and call them explicitly from your main entry point.
``` 
,where `<unsupported-feature>` currently can be: `a started Thread`, `a FileDescriptor`, or `a ZipFile object`. 

In the near future we will also support loading resources via `ClassLoader`, probably similarly to how we support [resource bundles](https://github.com/oracle/graal/blob/master/substratevm/RESOURCES.md) currently, i.e., they need to be specified at image build time via a command line option.

We already support reflection through [configuration files](https://github.com/oracle/graal/blob/master/substratevm/REFLECTION.md) and are currently looking into supporting `java.lang.reflect.Proxy`.

That being said, the best way to make an application/framework compatible with SubstrateVM is to, if possible, avoid using unsupported features.

**Comment by schmitch** [comment]
Well we could probably look if we could rewrite some logic that supports SubstrateVM, however without support for `ClassLoader#getResource` it's probably not simple.

I have created some work that now supports image creation, but fails on runtime:
Play branch https://github.com/schmitch/playframework/tree/substrate-vm-optimization
Play project https://github.com/schmitch/play-scala-starter-example/tree/substratevm

Part of Stacktrace:
`Caused by: com.typesafe.config.ConfigException$BugOrBroken: Context class loader is not set for the current thread; if Thread.currentThread().getContextClassLoader() returns null, you must pass a ClassLoader explicitly to ConfigFactory.defaultApplication`

**Comment by cstancu** [comment]
Related: https://github.com/oracle/graal/issues/470#issuecomment-396837552

**Comment by cstancu** [comment]
Is loading resources via `Thread.getContextClassLoader().getResource()` still a problem for you? We added support for `ClassLoader.getSystemClassLoader()` and `Thread.getContextClassLoader()`. See https://github.com/oracle/graal/issues/470#issuecomment-401022008 for reference.

**Comment by schmitch** [comment]
Well unfortunatly it fails with:
`Caused by: com.oracle.svm.core.jdk.UnsupportedFeatureError: Accessing an URL protocol that was not enabled. The URL protocol resource is not tested and might not work as expected. It can be enabled by adding the -H:EnableURLProtocols=resource option to the native-image command.`
now.
But I tried to enable `-H:EnableURLProtocols=resource`

**Comment by cstancu** [comment]
Can you please provide the steps to reproduce this?

**Comment by schmitch** [comment]
Well just clone:

Play branch https://github.com/schmitch/playframework/tree/substrate-vm-optimization
and run `cd framework && sbt publishLocal`
after that clone:
Play project https://github.com/schmitch/play-scala-starter-example/tree/substratevm
and run sh build-2.12.sh (needs `$GRAALVM_HOME` to be set (to the latest version))

**Comment by cstancu** [comment]
As of https://github.com/oracle/graal/commit/427e54ba383cd0addf8b621ac7d6928c89583a00 the `resource` URL protocol is enabled by default and it doesn't require any special config.

**Comment by SchrodingerZhu** [comment]
failed to read configurations for GraalVM 19+/Play 2.7
