### ISSUE TITLE
Whether hot swap is supported

### ISSUE THREAD

**Issue by fendo8888** [oracle/graal#4251]
Whether hot swap is supported？Something like DCEVM https://github.com/dcevm/dcevm

**Comment by oubidar-Abderrahim** [comment]
Hi, thank you for reporting this, let me check and get back to you

**Comment by oubidar-Abderrahim** [comment]
It is not supported on GraalVM by default, but there is something similar on Espresso (Java on Truffle): please see our reference manual for more: https://www.graalvm.org/22.0/reference-manual/java-on-truffle/hotswap-plugin/

**Comment by wirthi** [comment]
I understand the question is answered, closing this ticket. Please reopen if there is anything else to clarify.
