### ISSUE TITLE
native-image on MacOS Apple Silicon returns x86_64 executables instead of arm64 

### ISSUE THREAD

**Issue by perezd** [oracle/graal#4257]
**Describe the issue**

Noticing this is available for linux: https://www.graalvm.org/22.0/reference-manual/native-image/ARM64/
Does this not include MacOS as well?

**Steps to reproduce the issue**
Please include both build steps as well as run steps
1. clone https://github.com/perezd/google-java-format/tree/native-image
2. mvn -Pnative -DskipTests package
3. file ./core/target/google-java-format 

I'm getting `google-java-format: Mach-O 64-bit executable x86_64`

**Describe GraalVM and your environment:**
 - GraalVM version (latest snapshot builds can be found [here](https://github.com/graalvm/graalvm-ce-dev-builds/releases)), or commit id if built from source: **GraalVM 21.3.0 Java 11 CE (Java Version 11.0.13+7-jvmci-21.3-b05)*
 - JDK major version: **11**
 - OS: **MacOS Monterey**
 - Architecture: **arm64**

**Comment by esestt** [comment]
As I known, GraalVM hasn't support Apple ARM yet. You can follow below feature request.
https://github.com/oracle/graal/issues/2666

**Comment by esestt** [comment]
As I known, GraalVM hasn't support Apple ARM yet. You can follow below feature request.
https://github.com/oracle/graal/issues/2666

**Comment by perezd** [comment]
Excellent, thank you!
