### ISSUE TITLE
Difference between TraceTruffleCompilationPolymorphism and TraceTruffleCompilationAST?

### ISSUE THREAD

**Issue by fniephaus** [oracle/graal#426]
What is the difference between `TraceTruffleCompilationPolymorphism` and `TraceTruffleCompilationAST`? Their [help texts appear to be identical](https://github.com/oracle/graal/blob/1b109ea1c9ed59239c5e266ee69ba7350fd9ce37/compiler/src/org.graalvm.compiler.truffle.common/src/org/graalvm/compiler/truffle/common/TruffleCompilerOptions.java#L226-L230) which might be a documentation bug.

**Comment by chumer** [comment]
Sorry for the delayed response.

Thanks for pointing that out. Seems like a copy past error. `TraceTruffleCompilationPolymorphism` is a new flag to debug when a language reports polymorphism that we use for our new splitting heuristic. Read more about this here: https://github.com/oracle/graal/tree/master/truffle/docs/splitting

**Comment by fniephaus** [comment]
@chumer thanks!

**Comment by chumer** [comment]
Sorry `TraceTruffleCompilationPolymorphism` is actually not related with the new splitting. sorry for the noise. It can be used to print nodes with node cost polymorphic on compiles.

**Comment by boris-spas** [comment]
Fixed in https://github.com/oracle/graal/commit/b272dac2408ce296b72112431c9dc1abf1041bc5.
Thanks for the heads up!

**Comment by fniephaus** [comment]
@boris-spas thanks for the fix!
