### ISSUE TITLE
Dockerized cross-platform build

### ISSUE THREAD

**Issue by brettwooldridge** [oracle/graal#4269]
My team currently compiles a custom version of OpenJDK 17. We develop on Mac, but the target is x86_64 embedded Linux. For OpenJDK, there is an extremely handy build that is capable of building for x86_64 Linux from within MacOS.

https://github.com/adoptium/temurin-build

On Mac, invocation goes something like this:
```
./makejdk-any-platform.sh --docker --clean-docker-build --processors 8 --update-version "17.0.1+12" --branch release --tag "jdk-17.0.1+12_adopt" jdk17u
```
This executes the entire build from soup to nuts inside the Docker container, and spits out a tar.gz file in the ``workspace/target`` folder.

Is there anything like this for GraalVM? We would really like to be able to build GraalVM, on our Macs, targeted at x86_64 Linux.

**Comment by rodrigar-mx** [comment]
I think that what you can try to do is run a docker container, install the dependencies required for building graalvm, then build graalvm CE base image ([look here]( https://github.com/oracle/graal/blob/master/vm/README.md)), and then package it in a tar.gz.

**Comment by wirthi** [comment]
As there has not been an answer for several months, I assume this to be resolved by Rodrigo's comment above. Closing.
