### ISSUE TITLE
GU is not working when built from source.

### ISSUE THREAD

**Issue by olymk2** [oracle/graal#4273]
Building from source gu can not find the native images a pre compiled downloaded tar.gz release seems to work how ever.

```
/usr/share/graalvm/bin # ./gu available
Downloading: Component catalog from www.graalvm.org
Could not load channel https://www.graalvm.org/component-catalog/graal-updater-component-catalog.properties: Unsupported Graal VM version: 21.3.0, platform linux/amd64
Error: Unsupported Graal VM version: 21.3.0, platform linux/amd64
```

The downloaded sources are these

```
source     :
    - git|https://github.com/oracle/graal.git : vm-ce-21.3.0
    - git|https://github.com/graalvm/mx.git : 5.317.4
    - https://github.com/graalvm/labs-openjdk-11/releases/download/jvmci-22.0-b02/labsjdk-ce-11.0.13+8-jvmci-22.0-b02-linux-amd64.tar.gz : fc7a9507f720b162fdf3a3fcd20fb9e5200391a52642492ce996e4923d195105

```
The commands to compile are as follows 
```   
    unset CFLAGS
    unset LDFLAGS

    # Setup the custom jdk required to build graal
    # we need a special version of java to build which includes some needed headers
    cp $sources/labsjdk-ce-11.0.13+8-jvmci-22.0-b02-linux-amd64.tar.gz $workdir
    tar xvf labsjdk-ce-11.0.13+8-jvmci-22.0-b02-linux-amd64.tar.gz
    export JAVA_HOME=$workdir/labsjdk-ce-11.0.13-jvmci-22.0-b02/

    # Setup MX build tool
    mkdir -p $workdir/mx-build-tool
    cp -r $sources/mx.git $workdir
    export PATH=$workdir/mx.git:$PATH

    # Finally Build Graal
    cd $workdir/vm
    mx --env ce build
```

Is there some step that needs to be run to make the gu tool pick up the native-image so it can be installed ?
the binaries all seem to work apart from that so a bit confused by this one.

**Comment by MartinBalin** [comment]
The problem is that it reads old remote catalog. You need to point GU to thttps://www.graalvm.org/component-catalog/**v2**/graal-updater-component-catalog-java11.properties or different Java flavour of **v2** version of catalog. Can be done in `release` file or on `gu` command line.

**Comment by fniephaus** [comment]
> Is there some step that needs to be run to make the gu tool pick up the native-image so it can be installed?

If you're building GraalVM from source, note that you can run into incompatibility issues installing components from the catalog. To avoid that, I suggest that you also build native-image from source if your goal is to use native image. You can do this as follows:

```bash
cd graal/substratevm
mx graalvm-show # shows you what's going to be built
mx build
mx graalvm-home # prints the home directory of the GraalVM built from source
$(mx graalvm-home)/bin/native-image ...
```
Have a look at [this README](https://github.com/oracle/graal/tree/master/vm#vm-suite) for more information on how you can configure building GraalVM from source.

**Comment by olymk2** [comment]
okay thanks this seems like the steps I need I did not realize substratevm is the native-image I will give it a try thanks for the tips
