### ISSUE TITLE
Optimize repeated divisions by same divisor using multiplication with shifts

### ISSUE THREAD

**Issue by CAFxX** [oracle/graal#4284]
**Feature request**

Please include the following information:

**Is your feature request related to a problem? Please describe.**

Division/modulo operations executed in a loop with the same divisor (not constant at compile time, but constant at runtime for the duration of the loop) are not strength reduced to multiplications/shifts (as in https://github.com/oracle/graal/issues/593)

**Describe the solution you'd like.**

Extend https://github.com/oracle/graal/issues/593 to cover also repeated division/modulo operations executed in a loop, at least when the loop iteration count is high enough to justify the computation of the magic multiplication/shift constants[^1].

**Describe who do you think will benefit the most.**
GraalVM users (higher peak performance)
Implementors of truffle languages (less per-language optimizations required)

**Describe alternatives you've considered.**

**Additional context.**

Similar issues in other compilers:

- https://gcc.gnu.org/bugzilla/show_bug.cgi?id=100045
- https://github.com/llvm/llvm-project/issues/53332

**Express whether you'd like to help contributing this feature**

[^1]: On my laptop, the crossover threshold is 8 division operations; if more than 8 divisions are performed with the same divisor it is faster to compute the multiplication/shift constants and use them instead of using the division instruction: https://github.com/llvm/llvm-project/issues/53332#issuecomment-1018913465

**Comment by davleopo** [comment]
Hi @CAFxX  thanks for bringing this to our attention. I'm refactoring some code in this part of the code base at the moment and Ill have an initial look what it would take to add the support to graal.

**Comment by davleopo** [comment]
@CAFxX  I have done some experiments with micro benchmarks and then regular Java benchmark suites (dacapo, renaissance, etc) and could not see this pattern occurring out in the wild. Do you have any interesting workloads exhibiting this pattern?

**Comment by davleopo** [comment]
I will close this for now given I have only seen this pattern very rarely appear in hot code in the wild. I currently don't see the added complexity pay off the performance gains. I am very open to re-iterate on this again if a compelling code pattern appears in the wild.

**Comment by CAFxX** [comment]
@davleopo sorry for the late reply

Given that currently that operation is fairly slow, it is common to use something like [libdivide](https://libdivide.com/) to achieve the same effect - so we have a bit of a chicken-and-egg problem, as libdivide existence is precisely due to the fact that compilers don't perform this transformation transparently.

Some users of libdivide can be found [here](https://sourcegraph.com/search?q=context:global+%23include+.%2Blibdivide.h+%28lang:c+OR+lang:c%2B%2B%29&patternType=regexp), and some users of libdivide4j can be found [here](https://github.com/search?q=libdivide4j&type=code).

Another consequence of division being so slow is that often in high-performance code we stick to power-of-2 sizes precisely because division and modulo operations are fast if the divisor is a power of 2. If compilers were able to optimize divisions by an integer divisor to roughly the same speed of division by a power-of-2 divisor, the need to use power-of-2 divisors would be significantly less common. This is yet another chicken-and-egg type of situation.

**Comment by CAFxX** [comment]
FWIW I kinda implemented this in simplelanguage a while back and the microbenchmark clearly showed the benefit: https://github.com/oracle/graal/pull/3646

**Comment by CAFxX** [comment]
@davleopo ping?

**Comment by davleopo** [comment]
@CAFxX  my concern is not the benefit, that is obvious and can be shown by micro benchmarks. My concern is that I tested for this pattern in our regular benchmarks/tests/workloads and I have not seen it. This would mean that if we implement it still only our test cases and micro benchmarks would exercise it which seems like an optimization effort that runs into the void. Regarding the chicken-egg problem : yeah maybe that is true.
However, we know how to implement it and it is straight forward so for now I would keep this issue around and we can revisit in the future.
