### ISSUE TITLE
Install Native Image GraalVM-21.3.0, Corrupted file, digest does not match

### ISSUE THREAD

**Issue by DJViking** [oracle/graal#4287]
After downloading the GraalVM 21.3.0 and unpacking it, then installing the native-image fails.

```
/usr/java/graal-java11-21.3.0/bin/gu install native-image
Downloading: Release index file from oca.opensource.oracle.com
Downloading: Component catalog from www.graalvm.org
Processing Component: Native Image
Downloading: Component native-image: Native Image  from github.com
I/O error occurred: Corrupted file, digest does not match. Expected 89:58:d4:e0:ca:d0:73:40:db:0c:f9:e8:71:77:68:09:e2:f0:8f:e0:c9:39:60:f7:28:fe:c7:5c:4a:96:76:4f, got ae:fe:90:ad:a9:b3:ee:f2:f3:e6:b5:4e:90:b3:c4:55:f2:78:8b:8d:92:9a:4f:f8:48:31:b8:0e:dd:9b:82:40
```

A workaround, download the native image manally and install worked.
```
wget https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-21.3.0/native-image-installable-svm-java11-linux-amd64-21.3.0.jar
$GRAALVM_HOME/bin/gu -L install native-image-installable-svm-java11-linux-amd64-21.3.0.jar
Processing Component archive: native-image-installable-svm-java11-linux-amd64-21.3.0.jar
Installing new component: Native Image (org.graalvm.native-image, version 21.3.0)
```

So I suspect the problem is not the native image, but something wrong with the download itself using the `gu` tool.

**Comment by rodrigar-mx** [comment]
Hi @DJViking which os are you using? can you share exactly the link where you download graalvm 21.3.0?

**Comment by DJViking** [comment]
I downloaded this
https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-21.3.0/graalvm-ce-java11-linux-amd64-21.3.0.tar.gz

Unpacked it, and then run `gu install native-image` to install the native image, which fails.

**Comment by rodrigar-mx** [comment]
Thanks @DJViking. I tested it locally and did not run into any issue. Perhaps the error was caused by a corrupted download. Could you please download it and install the native-image again.

**Comment by rodrigar-mx** [comment]
Please try the above suggestion. If the issue persists, feel free to open a new issue.
