### ISSUE TITLE
[GR-36820] Show native image linking type in build output

### ISSUE THREAD

**Issue by rubyFeedback** [oracle/graal#4289]
Hello GraalVM-devs,

Today I was reading this article on the graalvm homepage:

https://www.graalvm.org/22.0/reference-manual/native-image/StaticImages/

I have not yet built a "mostly static" executable/binary and set out
to try it today (just now). I was trying it first, as always, with my canonical
hello world java example.

For simplicity and reproducibility, let me copy/paste the content of
said .java file next between two _______ lines:

-----------------------------------------------------------------------------

    public class HelloWorld {
      public static void main(String[] args) {
        String x = "Hello world!";
        System.out.println(x);
      }
    }

-----------------------------------------------------------------------------

Next, as on that webpage shown, I was using the following commandline
sample, after having compiled the .java file via "javac" first:

    native-image -H:+StaticExecutableWithDynamicLibC HelloWorld

The output was as follows:

    ========================================================================================================================
    GraalVM Native Image: Generating 'helloworld'...
    ========================================================================================================================
    [1/7] Initializing...                                                                                    (9.3s @ 0.19GB)
     Version info: 'GraalVM 22.0.0.2 Java 17 CE'
    [2/7] Performing analysis...  [*******]                                                                 (29.4s @ 0.49GB)
       2,723 (83.76%) of  3,251 classes reachable
       3,332 (60.26%) of  5,529 fields reachable
      12,333 (73.06%) of 16,881 methods reachable
          28 classes,     0 fields, and   173 methods registered for reflection
          57 classes,    58 fields, and    51 methods registered for JNI access
    [3/7] Building universe...                                                                               (2.1s @ 0.67GB)
    [4/7] Parsing methods...      [*]                                                                        (2.0s @ 0.90GB)
    [5/7] Inlining methods...     [****]                                                                     (2.6s @ 0.78GB)
    [6/7] Compiling methods...    [*****]                                                                   (23.4s @ 1.09GB)
    [7/7] Creating image...                                                                                  (2.8s @ 1.35GB)
       3.99MB (33.37%) for code area:    7,383 compilation units
       6.92MB (57.86%) for image heap:   1,634 classes and 90,781 objects
       1.05MB ( 8.77%) for other data
      11.96MB in total
    ------------------------------------------------------------------------------------------------------------------------
    Top 10 packages in code area:                               Top 10 object types in image heap:
     635.86KB java.util                                            1.76MB byte[] for general heap data
     300.68KB java.lang                                          791.22KB java.lang.String
     283.85KB java.text                                          586.04KB java.lang.Class
     233.44KB java.util.regex                                    487.22KB byte[] for java.lang.String
     193.17KB com.oracle.svm.jni                                 418.97KB java.util.HashMap$Node
     177.57KB java.util.concurrent                               220.47KB java.util.HashMap$Node[]
     144.39KB java.math                                          154.13KB java.util.concurrent.ConcurrentHashMap$Node
     125.04KB com.oracle.svm.core.reflect                        147.27KB java.lang.String[]
      94.35KB java.util.logging                                  143.73KB char[]
      91.34KB sun.util.locale.provider                           139.78KB sun.util.locale.LocaleObjectCache$CacheEntry
          ... 115 additional packages                                 ... 764 additional object types
                                               (use GraalVM Dashboard to see all)
    ------------------------------------------------------------------------------------------------------------------------
                            2.8s (3.7% of total time) in 17 GCs | Peak RSS: 2.54GB | CPU load: 3.20
    ------------------------------------------------------------------------------------------------------------------------
    Produced artifacts:
     /home/x/programming/java/src/hello_world/helloworld (executable)
     /home/x/programming/java/src/hello_world/helloworld.build_artifacts.txt
    ========================================================================================================================
    Finished generating 'helloworld' in 1m 13s.

I had a look at the output but did not see the mention of "static"
anywhere. 

I then did "file helloworld" and indeed it shows this:

    helloworld: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, no section header

So indeed, the part "statically linked" is mentioned when one uses "file" (on
linux).

However had, would it be possible to mention the word static
during the build/inspect time shown above? To indicate that
this will produce a statically compiled executable?

I don't know where it could fit best, but a line or a word or
sentence such as "generating a statically linked executable"
or something like this may be helpful during the "native-image"
process.

You may ask the use case / rationale for this including for other
users. Well, I was not sure whether I was doing anything right
via the above commandline, so to me (and perhaps others) it would
be helpful to kind of get the graalvm to yield a bit more information/feedback
in this regard. The "file executable" I did on my own, so other users
may not necessarily know that. (The documentation on the homepage
could perhaps mention this, but this is a secondary thought.)

It is obviously not a hugely important or relevant issue request, but I
may make some more suggestions in regards to statically compiling
something. (I have not yet tried for musl; I first want to get the
base things right, in this case being for glibc.)

**Comment by fniephaus** [comment]
As of https://github.com/oracle/graal/commit/eb3e617995ea68a4293aafe4bb045249fcb6b985, the Native Image build output shows image kind (exec, shared lib, static exec), C compiler (e.g. musl), and GC info.
