### ISSUE TITLE
windows build failed

### ISSUE THREAD

**Issue by nassimus26** [oracle/graal#4290]
Building on windows 10 return this :

C:\work\graal\vm>mx --env libgraal build
WARNING: The component inclusion list ('--components' or '$COMPONENTS') includes an unknown component: 'svml'
WARNING: The component inclusion list ('--components' or '$COMPONENTS') includes an unknown component: 'svml'
JAVA_HOME: C:\work\jdk-17.0.2
8 unsatisfied dependencies were removed from build (use -v to list them)
5 non-default dependencies were removed from build (use -v to list them, mx build --all to build them)
WARNING: Adding non-default dependency com.oracle.svm.graal.hotspot.libgraal as it is needed by standard dependency GRAAL_HOTSPOT_LIBRARY
WARNING: Adding non-default dependency GRAAL_HOTSPOT_LIBRARY as it is needed by standard dependency jvmcicompiler.dll.image
Archiving GRAAL_SDK... [build JDK changed from C:\GraalVM to C:\work\jdk-17.0.2]
Building Java module org.graalvm.sdk (graal-sdk.jar) from GRAAL_SDK
Archiving LAUNCHER_COMMON... [dependency GRAAL_SDK updated]
WARNING: C:\work\graal\sdk\mxbuild\jdk17\dists\jdk17\launcher-common.jar: skipping update of META-INF/native/linux32/libjansi.so
     using: C:\Users\cd_bo\.mx\cache\JLINE_c3aeac59c022bdc497c8c48ed86fa50450e4896a\jline.jar!META-INF/native/linux32/libjansi.so
  ignoring: C:\Users\cd_bo\.mx\cache\JLINE3_bac1579375a67379d8f308016138f9c37a646dd5\jline3.jar!META-INF/native/linux32/libjansi.so
WARNING: C:\work\graal\sdk\mxbuild\jdk17\dists\jdk17\launcher-common.jar: skipping update of META-INF/native/linux64/libjansi.so
     using: C:\Users\cd_bo\.mx\cache\JLINE_c3aeac59c022bdc497c8c48ed86fa50450e4896a\jline.jar!META-INF/native/linux64/libjansi.so
  ignoring: C:\Users\cd_bo\.mx\cache\JLINE3_bac1579375a67379d8f308016138f9c37a646dd5\jline3.jar!META-INF/native/linux64/libjansi.so
WARNING: C:\work\graal\sdk\mxbuild\jdk17\dists\jdk17\launcher-common.jar: skipping update of META-INF/native/osx/libjansi.jnilib
     using: C:\Users\cd_bo\.mx\cache\JLINE_c3aeac59c022bdc497c8c48ed86fa50450e4896a\jline.jar!META-INF/native/osx/libjansi.jnilib
  ignoring: C:\Users\cd_bo\.mx\cache\JLINE3_bac1579375a67379d8f308016138f9c37a646dd5\jline3.jar!META-INF/native/osx/libjansi.jnilib
WARNING: C:\work\graal\sdk\mxbuild\jdk17\dists\jdk17\launcher-common.jar: skipping update of META-INF/native/windows32/jansi.dll
     using: C:\Users\cd_bo\.mx\cache\JLINE_c3aeac59c022bdc497c8c48ed86fa50450e4896a\jline.jar!META-INF/native/windows32/jansi.dll
  ignoring: C:\Users\cd_bo\.mx\cache\JLINE3_bac1579375a67379d8f308016138f9c37a646dd5\jline3.jar!META-INF/native/windows32/jansi.dll
WARNING: C:\work\graal\sdk\mxbuild\jdk17\dists\jdk17\launcher-common.jar: skipping update of META-INF/native/windows64/jansi.dll
     using: C:\Users\cd_bo\.mx\cache\JLINE_c3aeac59c022bdc497c8c48ed86fa50450e4896a\jline.jar!META-INF/native/windows64/jansi.dll
  ignoring: C:\Users\cd_bo\.mx\cache\JLINE3_bac1579375a67379d8f308016138f9c37a646dd5\jline3.jar!META-INF/native/windows64/jansi.dll
Building Java module org.graalvm.launcher (launcher-common.jar) from LAUNCHER_COMMON
Downloading TruffleJSON from ['https://lafo.ssw.uni-linz.ac.at/pub/graal-external-deps/trufflejson-20201115.jar']
 68926 bytes (100%)
Compiling org.graalvm.component.installer with javac-daemon(JDK 17)... [dependency LAUNCHER_COMMON updated]
Archiving INSTALLER... [dependency org.graalvm.component.installer updated]
Building gu.exe.image-bash... [dependency INSTALLER updated]
Creating native-image.properties for gu-launcher... [dependency INSTALLER updated]
Compiling org.graalvm.jniutils with javac-daemon(JDK 17)... [dependency GRAAL_SDK updated]
Compiling org.graalvm.nativebridge with javac-daemon(JDK 17)... [dependency org.graalvm.jniutils updated]
Compiling org.graalvm.libgraal with javac-daemon(JDK 17)... [dependency GRAAL_SDK updated]
Compiling org.graalvm.compiler.options with javac-daemon(JDK 17)... [dependency GRAAL_SDK updated]
Compiling org.graalvm.compiler.debug with javac-daemon(JDK 17)... [dependency org.graalvm.compiler.options updated]
Compiling org.graalvm.libgraal.jni with javac-daemon(JDK 17)... [dependency org.graalvm.compiler.debug updated]
Compiling org.graalvm.util with javac-daemon(JDK 17)... [dependency GRAAL_SDK updated]
Compiling org.graalvm.compiler.core.common with javac-daemon(JDK 17)... [dependency org.graalvm.util updated]
Compiling org.graalvm.compiler.graph with javac-daemon(JDK 17)... [dependency org.graalvm.compiler.core.common updated]
Compiling org.graalvm.compiler.asm with javac-daemon(JDK 17)... [dependency org.graalvm.compiler.core.common updated]
Compiling org.graalvm.compiler.code with javac-daemon(JDK 17)... [dependency org.graalvm.compiler.graph updated]
Compiling org.graalvm.compiler.lir with javac-daemon(JDK 17)... [dependency org.graalvm.compiler.asm updated]
Compiling org.graalvm.compiler.nodes with javac-daemon(JDK 17)... [dependency org.graalvm.compiler.lir updated]
Compiling org.graalvm.compiler.word with javac-daemon(JDK 17)... [dependency org.graalvm.compiler.nodes updated]
Compiling org.graalvm.compiler.phases with javac-daemon(JDK 17)... [dependency org.graalvm.compiler.word updated]
Compiling org.graalvm.compiler.phases.common with javac-daemon(JDK 17)... [dependency org.graalvm.compiler.phases updated]
Compiling org.graalvm.compiler.virtual with javac-daemon(JDK 17)... [dependency org.graalvm.compiler.phases.common updated]
Compiling org.graalvm.compiler.loop.phases with javac-daemon(JDK 17)... [dependency org.graalvm.compiler.phases.common updated]
Compiling org.graalvm.compiler.core with javac-daemon(JDK 17)... [dependency org.graalvm.compiler.virtual updated]
Compiling org.graalvm.compiler.java with javac-daemon(JDK 17)... [dependency org.graalvm.compiler.phases updated]
Compiling org.graalvm.compiler.replacements with javac-daemon(JDK 17)... [dependency org.graalvm.compiler.java updated]
Compiling org.graalvm.compiler.runtime with javac-daemon(JDK 17)... [dependency org.graalvm.compiler.core updated]
Compiling org.graalvm.compiler.printer with javac-daemon(JDK 17)... [dependency org.graalvm.compiler.core updated]
Compiling org.graalvm.compiler.asm.aarch64 with javac-daemon(JDK 17)... [dependency org.graalvm.compiler.asm updated]
Compiling org.graalvm.compiler.lir.aarch64 with javac-daemon(JDK 17)... [dependency org.graalvm.compiler.lir updated]
Compiling org.graalvm.compiler.core.aarch64 with javac-daemon(JDK 17)... [dependency org.graalvm.compiler.core updated]
Compiling org.graalvm.compiler.replacements.aarch64 with javac-daemon(JDK 17)... [dependency org.graalvm.compiler.replacements updated]
Compiling org.graalvm.compiler.asm.amd64 with javac-daemon(JDK 17)... [dependency org.graalvm.compiler.asm updated]
Compiling org.graalvm.compiler.lir.amd64 with javac-daemon(JDK 17)... [dependency org.graalvm.compiler.lir updated]
Compiling org.graalvm.compiler.core.amd64 with javac-daemon(JDK 17)... [dependency org.graalvm.compiler.replacements updated]
Compiling org.graalvm.compiler.replacements.amd64 with javac-daemon(JDK 17)... [dependency org.graalvm.compiler.replacements updated]
Compiling org.graalvm.compiler.hotspot with javac-daemon(JDK 17)... [dependency org.graalvm.compiler.replacements updated]
Compiling org.graalvm.compiler.hotspot.aarch64 with javac-daemon(JDK 17)... [dependency org.graalvm.compiler.core.aarch64 updated]
Compiling org.graalvm.compiler.hotspot.amd64 with javac-daemon(JDK 17)... [dependency org.graalvm.compiler.core.amd64 updated]
Compiling org.graalvm.compiler.hotspot.jdk17 with javac-daemon(JDK 17)... [dependency org.graalvm.compiler.hotspot updated]
Compiling com.oracle.truffle.api with javac-daemon(JDK 17)... [dependency GRAAL_SDK updated]
Note: Some input files use or override a deprecated API that is marked for removal.
Note: Recompile with -Xlint:removal for details.
Compiling com.oracle.truffle.api.profiles with javac-daemon(JDK 17)... [dependency com.oracle.truffle.api updated]
Compiling com.oracle.truffle.api.dsl with javac-daemon(JDK 17)... [dependency com.oracle.truffle.api updated]
Compiling com.oracle.truffle.api.utilities with javac-daemon(JDK 17)... [dependency com.oracle.truffle.api updated]
Compiling com.oracle.truffle.api.library with javac-daemon(JDK 17)... [dependency com.oracle.truffle.api.dsl updated]
Note: C:\work\graal\truffle\src\com.oracle.truffle.api.library\src\com\oracle\truffle\api\library\LibraryFactory.java uses or overrides a deprecated API that is marked for removal.
Note: Recompile with -Xlint:removal for details.
Compiling com.oracle.truffle.api.strings with javac-daemon(JDK 17)... [dependency com.oracle.truffle.api.profiles updated]
Compiling com.oracle.truffle.api.interop with javac-daemon(JDK 17)... [dependency com.oracle.truffle.api.strings updated]
Compiling com.oracle.truffle.api.exception with javac-daemon(JDK 17)... [dependency com.oracle.truffle.api.interop updated]
Compiling com.oracle.truffle.api.instrumentation with javac-daemon(JDK 17)... [dependency com.oracle.truffle.api.interop updated]
Compiling com.oracle.truffle.polyglot with javac-daemon(JDK 17)... [dependency GRAAL_SDK updated]
Compiling com.oracle.truffle.api.debug with javac-daemon(JDK 17)... [dependency com.oracle.truffle.polyglot updated]
Compiling com.oracle.truffle.api.object with javac-daemon(JDK 17)... [dependency com.oracle.truffle.api.interop updated]
Compiling com.oracle.truffle.object with javac-daemon(JDK 17)... [dependency com.oracle.truffle.api.object updated]
Compiling com.oracle.truffle.host with javac-daemon(JDK 17)... [dependency GRAAL_SDK updated]
Note: C:\work\graal\truffle\src\com.oracle.truffle.host\src\com\oracle\truffle\host\HostClassLoader.java uses or overrides a deprecated API that is marked for removal.
Note: Recompile with -Xlint:removal for details.
Compiling com.oracle.truffle.api.staticobject with javac-daemon(JDK 17)... [dependency com.oracle.truffle.api updated]
Compiling com.oracle.truffle.api.staticobject.jdk17 with javac-daemon(JDK 17)... [dependency com.oracle.truffle.api.staticobject updated]
Compiling com.oracle.truffle.api.staticobject.jdk8 with javac-daemon(JDK 17)... [dependency com.oracle.truffle.api.staticobject updated]
Archiving TRUFFLE_API... [dependency com.oracle.truffle.api updated]
Building Java module org.graalvm.truffle (truffle-api-open.jar) from TRUFFLE_API
Building Java module org.graalvm.truffle (truffle-api.jar) from TRUFFLE_API
Compiling org.graalvm.compiler.truffle.options with javac-daemon(JDK 17)... [dependency GRAAL_SDK updated]
Compiling org.graalvm.compiler.truffle.compiler with javac-daemon(JDK 17)... [dependency org.graalvm.compiler.truffle.options updated]
Compiling org.graalvm.compiler.truffle.compiler.amd64 with javac-daemon(JDK 17)... [dependency org.graalvm.compiler.replacements.amd64 updated]
Compiling org.graalvm.compiler.truffle.jfr with javac-daemon(JDK 17)... [dependency TRUFFLE_API updated]
Compiling org.graalvm.compiler.truffle.runtime with javac-daemon(JDK 17)... [dependency org.graalvm.compiler.truffle.options updated]
Compiling org.graalvm.compiler.truffle.runtime.hotspot.jdk17 with javac-daemon(JDK 17)... [dependency org.graalvm.compiler.truffle.runtime updated]
Compiling org.graalvm.compiler.truffle.runtime.hotspot with javac-daemon(JDK 17)... [dependency org.graalvm.compiler.truffle.runtime updated]
Compiling org.graalvm.compiler.truffle.compiler.hotspot with javac-daemon(JDK 17)... [dependency org.graalvm.compiler.truffle.compiler updated]
Compiling org.graalvm.compiler.truffle.runtime.hotspot.java with javac-daemon(JDK 17)... [dependency org.graalvm.compiler.truffle.compiler.hotspot updated]
Compiling org.graalvm.compiler.truffle.runtime.hotspot.libgraal with javac-daemon(JDK 17)... [dependency org.graalvm.libgraal updated]
Compiling org.graalvm.compiler.truffle.compiler.hotspot.amd64 with javac-daemon(JDK 17)... [dependency org.graalvm.compiler.truffle.compiler.hotspot updated]
Compiling org.graalvm.compiler.truffle.compiler.hotspot.aarch64 with javac-daemon(JDK 17)... [dependency org.graalvm.compiler.hotspot.aarch64 updated]
Archiving GRAAL... [dependency org.graalvm.nativebridge updated]
Building Java module jdk.internal.vm.compiler (graal.jar) from GRAAL
Compiling com.oracle.objectfile with javac-daemon(JDK 17)... [dependency GRAAL updated]
Compiling com.oracle.svm.util with javac-daemon(JDK 17)... [dependency GRAAL_SDK updated]
Compiling com.oracle.svm.common with javac-daemon(JDK 17)... [dependency com.oracle.svm.util updated]
Compiling com.oracle.svm.core with javac-daemon(JDK 17)... [dependency com.oracle.svm.common updated]
Note: Some input files use or override a deprecated API that is marked for removal.
Note: Recompile with -Xlint:removal for details.
Compiling com.oracle.graal.pointsto with javac-daemon(JDK 17)... [dependency com.oracle.svm.common updated]
Compiling com.oracle.svm.hosted with javac-daemon(JDK 17)... [dependency com.oracle.objectfile updated]
Note: Some input files use or override a deprecated API that is marked for removal.
Note: Recompile with -Xlint:removal for details.
Compiling com.oracle.svm.jni with javac-daemon(JDK 17)... [dependency com.oracle.svm.hosted updated]
Compiling com.oracle.svm.reflect with javac-daemon(JDK 17)... [dependency com.oracle.svm.hosted updated]
Compiling com.oracle.svm.graal with javac-daemon(JDK 17)... [dependency com.oracle.svm.hosted updated]
Compiling com.oracle.svm.graal.hotspot.libgraal with javac-daemon(JDK 17)... [dependency com.oracle.svm.jni updated]
Compiling com.oracle.svm.truffle with javac-daemon(JDK 17)... [dependency com.oracle.svm.graal updated]
Compiling com.oracle.svm.hosted.jdk17 with javac-daemon(JDK 17)... [dependency com.oracle.svm.hosted updated]
Compiling com.oracle.svm.core.jdk17 with javac-daemon(JDK 17)... [dependency com.oracle.svm.core updated]
Compiling com.oracle.svm.core.graal.amd64 with javac-daemon(JDK 17)... [dependency com.oracle.svm.core updated]
Compiling com.oracle.svm.core.graal.aarch64 with javac-daemon(JDK 17)... [dependency com.oracle.svm.core updated]
Compiling com.oracle.svm.core.posix with javac-daemon(JDK 17)... [dependency com.oracle.svm.core.graal.amd64 updated]
Compiling com.oracle.svm.core.windows with javac-daemon(JDK 17)... [dependency com.oracle.svm.core.graal.amd64 updated]
Compiling com.oracle.svm.core.genscavenge with javac-daemon(JDK 17)... [dependency com.oracle.svm.core updated]
Compiling com.oracle.svm.core.containers with javac-daemon(JDK 17)... [dependency com.oracle.svm.core updated]
Note: C:\work\graal\substratevm\src\com.oracle.svm.core.containers\src\com\oracle\svm\core\containers\CgroupUtil.java uses or overrides a deprecated API that is marked for removal.
Note: Recompile with -Xlint:removal for details.
Compiling com.oracle.svm.methodhandles with javac-daemon(JDK 17)... [dependency com.oracle.svm.reflect updated]
Archiving OBJECTFILE... [dependency com.oracle.objectfile updated]
Building Java module org.graalvm.nativeimage.objectfile (objectfile.jar) from OBJECTFILE
Archiving NATIVE_IMAGE_BASE... [dependency com.oracle.svm.common updated]
Building Java module org.graalvm.nativeimage.base (native-image-base.jar) from NATIVE_IMAGE_BASE
Archiving POINTSTO... [dependency com.oracle.svm.util updated]
Building Java module org.graalvm.nativeimage.pointsto (pointsto.jar) from POINTSTO
Archiving SVM... [dependency com.oracle.svm.graal updated]
Building Java module org.graalvm.nativeimage.builder (svm.jar) from SVM
Archiving GRAAL_HOTSPOT_LIBRARY... [dependency com.oracle.svm.graal.hotspot.libgraal updated]
Compiling org.graalvm.compiler.truffle.compiler.hotspot.libgraal with javac-daemon(JDK 17)... [dependency org.graalvm.libgraal updated]
Archiving GRAAL_TRUFFLE_COMPILER_LIBGRAAL... [dependency org.graalvm.compiler.truffle.compiler.hotspot.amd64 updated]
Compiling org.graalvm.compiler.hotspot.management with javac-daemon(JDK 17)... [dependency org.graalvm.compiler.hotspot updated]
Compiling org.graalvm.compiler.hotspot.management.libgraal with javac-daemon(JDK 17)... [dependency org.graalvm.libgraal updated]
Archiving GRAAL_MANAGEMENT... [dependency org.graalvm.compiler.hotspot.management updated]
Building Java module jdk.internal.vm.compiler.management (graal-management.jar) from GRAAL_MANAGEMENT
Archiving GRAAL_MANAGEMENT_LIBGRAAL... [dependency org.graalvm.compiler.hotspot.management.libgraal updated]
Archiving HSDIS_GRAALVM_SUPPORT... [C:\work\graal\compiler\mxbuild\windows-amd64\dists\hsdis-graalvm-support.tar does not exist]
Downloading HSDIS from ['https://lafo.ssw.uni-linz.ac.at/pub/graal-external-deps/hsdis/intel/hsdis-amd64-windows-6a388372cdd5fe905c1a26ced614334e405d1f30-2.zip']
 380943 bytes (100%)
WARNING:   File "C:\work\graal\compiler\mx.compiler\suite.py", line 2166 in definition of HSDIS_GRAALVM_SUPPORT:
Adding file which is not in the repository: 'C:\Users\cd_bo\.mx\cache\HSDIS_b603814c8136e0086f33355d38a5f67d115101da\hsdis.extracted\*' in 'hsdis-amd64.dll'
Compiling org.graalvm.compiler.truffle.jfr.impl with javac-daemon(JDK 17)... [dependency org.graalvm.compiler.truffle.jfr updated]
Archiving GRAAL_TRUFFLE_JFR_IMPL... [dependency org.graalvm.compiler.truffle.jfr.impl updated]
Building Java module jdk.internal.vm.compiler.truffle.jfr (graal-truffle-jfr-impl.jar) from GRAAL_TRUFFLE_JFR_IMPL
Compiling com.oracle.graalvm.locator with javac-daemon(JDK 17)... [dependency TRUFFLE_API updated]
Archiving LOCATOR... [dependency com.oracle.graalvm.locator updated]
Building Java module org.graalvm.locator (locator.jar) from LOCATOR
Building graalvm-jimage... [dependency GRAAL updated]
WARNING: Using incubator modules: jdk.incubator.vector, jdk.incubator.foreign
Building gu.exe.image-bash-stage1... [dependency INSTALLER updated]
Creating native-image.properties for jvmcicompiler-library... [dependency GRAAL_HOTSPOT_LIBRARY updated]
Compiling com.oracle.svm.driver with javac-daemon(JDK 17)... [dependency com.oracle.svm.hosted updated]
Building SVM compiler flags... [dependency SVM updated]
Write file C:\work\graal\substratevm\mxbuild\jdk17\svm-compiler-flags-builder\graal-compiler-flags-versions.config
Write file C:\work\graal\substratevm\mxbuild\jdk17\svm-compiler-flags-builder\graal-compiler-flags-8.config
Write file C:\work\graal\substratevm\mxbuild\jdk17\svm-compiler-flags-builder\graal-compiler-flags-11.config
Write file C:\work\graal\substratevm\mxbuild\jdk17\svm-compiler-flags-builder\graal-compiler-flags-17.config
Compiling com.oracle.svm.polyglot with javac-daemon(JDK 17)... [dependency com.oracle.svm.graal updated]
Compiling com.oracle.svm.thirdparty with javac-daemon(JDK 17)... [dependency com.oracle.svm.core updated]
Archiving LIBRARY_SUPPORT... [dependency com.oracle.svm.polyglot updated]
Building Java module org.graalvm.nativeimage.librarysupport (library-support.jar) from LIBRARY_SUPPORT
Archiving SVM_DRIVER... [dependency com.oracle.svm.driver updated]
Building Java module org.graalvm.nativeimage.driver (svm-driver.jar) from SVM_DRIVER
Building native-image.exe.image-bash-stage1... [dependency SVM_DRIVER updated]
Creating native-image.properties for polyglot-launcher... [dependency LAUNCHER_COMMON updated]
Building polyglot.exe.image-bash-stage1... [dependency LAUNCHER_COMMON updated]
Archiving polynative_libpolyglot_macro... [C:\work\graal\substratevm\mxbuild\jdk17\dists\polynative-libpolyglot-macro.jar does not exist]
Compiling com.oracle.svm.jvmtiagentbase with javac-daemon(JDK 17)... [dependency com.oracle.svm.jni updated]
Archiving JVMTI_AGENT_BASE... [dependency com.oracle.svm.jvmtiagentbase updated]
Building Java module org.graalvm.nativeimage.agent.jvmtibase (jvmti-agent-base.jar) from JVMTI_AGENT_BASE
Archiving NATIVE_IMAGE_GRAALVM_SUPPORT... [C:\work\graal\substratevm\mxbuild\windows-amd64\dists\native-image-graalvm-support.tar does not exist]
Archiving NATIVE_IMAGE_LICENSE_GRAALVM_SUPPORT... [C:\work\graal\substratevm\mxbuild\jdk17\dists\native-image-license-graalvm-support.tar does not exist]
Compiling org.graalvm.polyglot.nativeapi with javac-daemon(JDK 17)... [dependency GRAAL_SDK updated]
Archiving POLYGLOT_NATIVE_API... [dependency org.graalvm.polyglot.nativeapi updated]
Archiving POLYGLOT_NATIVE_API_HEADERS... [dependency POLYGLOT_NATIVE_API updated]
Compiling com.oracle.svm.configure with javac-daemon(JDK 17)... [dependency com.oracle.svm.core updated]
Building com.oracle.svm.native.reporterchelper_amd64 with Ninja...
Exception in thread Thread-20 (redirect):
Traceback (most recent call last):
  File "C:\Python310\lib\threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "C:\Python310\lib\threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "C:\mx\mx.py", line 13219, in redirect
    f(_decode(line))
  File "C:\mx\mx.py", line 108, in _decode
    return x.decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 8: invalid start byte
([1/3] CC src\getTerminalWindowColumns.obj
FAILED: src/getTerminalWindowColumns.obj
cl -nologo -showIncludes -IC:\work\jdk-17.0.2\include -IC:\work\jdk-17.0.2\include\win32 -MD -Wall -c C:\work\graal\substratevm\src\com.oracle.svm.native.reporterchelper\src\getTerminalWindowColumns.c -Fosrc\getTerminalWindowColumns.
obj
, -2)

**Comment by fniephaus** [comment]
In what build environment are you running this on Windows? An [x64 Native Tools Command Prompt](https://medium.com/graalvm/using-graalvm-and-native-image-on-windows-10-9954dc071311)?
Also, it seems you're using a stock JDK 17.0.2. For building GraalVM, you need to use a [LabsJDK](https://github.com/graalvm/labs-openjdk-17/releases/).
