### ISSUE TITLE
[GR-36931] Native Image from GraalVM CE does not generate JNI function declarations for shared libraries

### ISSUE THREAD

**Issue by nirvdrum** [oracle/graal#4292]
**Describe the issue**

When building a native shared library with `native-image` from EE, the generated header file includes the following function declarations for managing `graal_isolate_t*` and `graal_isolatethread_t*` from JNI:

```c
graal_isolatethread_t* Java_com_oracle_truffle_polyglot_enterprise_EnterprisePolyglotImpl_createIsolate();

graal_isolate_t* Java_com_oracle_truffle_polyglot_enterprise_EnterprisePolyglotImpl_getIsolateId(void * jniEnv, void * clazz, graal_isolatethread_t* isolateThread);

int Java_com_oracle_truffle_polyglot_enterprise_EnterprisePolyglotImpl_detachIsolate(void * jniEnv, void * clazz, graal_isolatethread_t* isolateThread);

graal_isolatethread_t* Java_com_oracle_truffle_polyglot_enterprise_EnterprisePolyglotImpl_attachIsolate(void * jniEnv, void * clazz, graal_isolate_t* isolate);
```

`native-image` from GraalVM CE, however, does not generate a similar set of function declarations. Naturally, the above ones refer to EE classes, so I wouldn't expect CE to generate the exact same function declarations. But, it was my understanding that JNI is the preferred mechanism for interacting with `native-image`-generated libraries in an embedded scenario.

I was unable to determine if this difference was intentional as a product differentiation point or an oversight. I tried to get clarification on the GraalVM Slack instance, but was unable to find an answer.

**Steps to reproduce the issue**
Please include both build steps as well as run steps
1. **Run `native-image --shared` on a project with a `@CEntryPoint**
2. **Look at generated header file for function declarations**

**Describe GraalVM and your environment:**
 - GraalVM version (latest snapshot builds can be found [here](https://github.com/graalvm/graalvm-ce-dev-builds/releases)), or commit id if built from source: **GraalVM 22.0.0.2 Java 17 CE (Java Version 17.0.2+8-jvmci-22.0-b05)**
 - JDK major version: **17**
 - OS: **macOS 12.2**
 - Architecture: **AMD64 via Rosetta**

**Comment by nirvdrum** [comment]
This was more of general question, but if you need a reproduction case, please let me know.

**Comment by rodrigar-mx** [comment]
Hi @nirvdrum. Yes, can you please share the reproducer

**Comment by nirvdrum** [comment]
Are the JNI function declarations supposed to be present in the generated header on CE?

**Comment by nirvdrum** [comment]
Please see https://github.com/nirvdrum/gr-4292 for a reproduction. It's trivially reproducible with any `@CEntryPoint`, which is why I inquiring if the JNI function declarations should be generated with CE at all. I see the same issue with a half dozen other projects built using the Maven plugin, but I removed Maven to keep the reproduction simpler. Please let me know if you need anything else.

**Comment by rodrigar-mx** [comment]
Thanks @nirvdrum. This issue is now been tracked internally. You will receive a response accordingly.

**Comment by tzezula** [comment]
The `Java_com_oracle_truffle_polyglot_enterprise_EnterprisePolyglotImpl` entrypoints were exported unintentionally.
They are no more exported by default. Only the polyglot isolate shared library exports them.
