### ISSUE TITLE
[ Update documentation at https://www.graalvm.org/22.0/docs/getting-started/ ] native-image shows a deprecation warning

### ISSUE THREAD

**Issue by rubyFeedback** [oracle/graal#4294]
Hey there GraalVM devs,

I am reading through https://www.graalvm.org/22.0/docs/getting-started/ and testing.

When coming to this part:

    javac PrettyPrintJSON.java
    native-image --language:js --initialize-at-build-time PrettyPrintJSON

native-image tells me this:

    ========================================================================================================================
    GraalVM Native Image: Generating 'prettyprintjson'...
    ========================================================================================================================
    [1/7] Initializing...                                                                                    (9.6s @ 0.17GB)
    --initialize-at-build-time without arguments has been deprecated when not using --diagnostics-mode. With GraalVM 22.0.0 --initialize-at-build-time will only work with --diagnostics-mode for debugging purposes.
The reason for deprecation is that --initalize-at-build-time does not compose, i.e., a single library can make assumptions that the whole classpath can be safely initialized at build time; that assumption is often incorrect.
 Version info: 'GraalVM 22.0.0.2 Java 17 CE'
    [2/7] Performing analysis...  [*****

I think it should not show such a deprecation warning. Instead, I suggest to modify the documentation, with whatever else is now
recommended. Right now when copy/pasting the example from the documentation you get the above deprecation warning, which is
IMO not good. It should work without such a deprecation warning (e. g. adjust the commandline flag shown on the documentation).

**Comment by oubidar-Abderrahim** [comment]
Hi, Thank you for reporting this, @olyagpl would you mind checking this out? Thank you

**Comment by olyagpl** [comment]
Sorry for the late reply. Just tested with GraalVM 22.3.0 and could build a native executable without `--initialize-at-build-time` and the program behaves as expected. I'll update the documentation accordingly. Thanks for pointing at this.
