### ISSUE TITLE
Specifing the path of a Source object?

### ISSUE THREAD

**Issue by bakkot** [oracle/graal#4306]
I'm attempting to use graaljs to run some JavaScript which is entirely in-memory. To do that I need to create a Source object. Module resolution in JavaScript modules is done with relative paths, so I need my Source object to carry its Path. But there does not appear to be any way to do this - there's no `withPath` method on `SourceBuilder` or anything similar that I can find.

**Comment by rodrigar-mx** [comment]
Hi @bakkot. What do you mean by "I need my Source object to carry its Path"? In case it helps, here is some doc about [loading modules ](https://www.graalvm.org/22.0/reference-manual/js/Modules/), and [building a source object](https://www.graalvm.org/sdk/javadoc/org/graalvm/polyglot/Source.html)  from a file, url, stream, etc.

**Comment by bakkot** [comment]
I mean that the Source object I am creating needs to have its `path` field set, so that relative module resolution works correctly. I'm creating it from an in-memory String, not from a file, so it doesn't get set automatically. The docs don't appear to cover that case.

**Comment by bakkot** [comment]
Apparently this can be done by creating the Source object from a File object and then setting the contents explicitly to prevent the file from being read from disk: https://github.com/oracle/graaljs/issues/567#issuecomment-1058956808

This works, but is awkward; it still seems like there ought to be a method on SourceBuilder to do this.

**Comment by rodrigar-mx** [comment]
Thanks for the update @bakkot. Would you mind editing this issue or adding a comment following the provided Feature Request template.

**Comment by oubidar-Abderrahim** [comment]
Hi, if this issue is still present in the latest GraalVM versions, please create a new ticket following the template provided and share a reproducer. we'll be happy to give this another look. thank you
