### ISSUE TITLE
Native image crashes on ARMv8 (64-bit) on iOS

### ISSUE THREAD

**Issue by Montura** [oracle/graal#4315]
### Describe the issue
A problem with running the Java code (processed by graalvm-native-image) on ARMv8 (64-bit) (tested on Apple A7)

#### Steps to reproduce the issue

1. **git clone https://github.com/Montura/ios_graalvm**
2. **set `JAVA_HOME` to the GraalVM**
3. ```mvn clean package -Pgraal-ios```
4. **open `ios-graalvm.xcodeproj`**
  * scheme `ios-graalvm-22.0.1` works fine and prints: ```Hello from Java```
  * scheme `ios-graalvm-22.0` crashes

### GraalVM and environment
 - GraalVM version [latest release v22.0.0.2](https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-22.0.0.2/graalvm-ce-java11-darwin-amd64-22.0.0.2.tar.gz)
 - JDK major version: **11**
 - OS: **iOS 12.5.1**
 - Architecture: **ARMv8** (Apple A7)

#### More details

* On ARMv8.3-A works fine (Apple A12)

I think that [the commit in graal v22.0](https://github.com/oracle/graal/commit/8dcf51febac87c9cc60d320b56c1d7cce9e8121b#diff-e20cc7c705399bb4add81b0214fd61b4d7fcc8321666b139d16f6268d58b97e5R571) has to be updated to prevent native-image crash:
  * `Fatal error: Current target does not support the following CPU features that are required by the image: [FP, ASIMD]`
   
I dumped CPU options info for AppleA7 CPU
```
CPU: ARM64_V8
  hw.optional.floatingpoint:   val = 0, errCode = -1, support = false
  hw.optional.neon:            val = 0, errCode = -1, support = false
  hw.optional.armv8_crc32:     val = 0, errCode = -1, support = false
  hw.optional.armv8_1_atomics: val = 0, errCode = -1, support = false
``` 

* Full crash report:
```
  Fatal error: Current target does not support the following CPU features that are required by the image: [FP, ASIMD]

Threads:
  0x0000000102a01e00 STATUS_IN_JAVA (PREVENT_VM_FROM_REACHING_SAFEPOINT) "main" - 0x00000001017d5938, stack(0x000000016f6b8000,0x000000016f7b4000)

Stacktrace for the failing thread 0x0000000102a01e00:
  SP 0x000000016f7b3700 IP 0x00000001006a9dec  [image code] com.oracle.svm.core.jdk.VMErrorSubstitutions.shutdown(VMErrorSubstitutions.java:116)
  SP 0x000000016f7b3700 IP 0x00000001006a9dec  [image code] com.oracle.svm.core.jdk.VMErrorSubstitutions.shouldNotReachHere(VMErrorSubstitutions.java:109)
  SP 0x000000016f7b3730 IP 0x000000010071487c  [image code] com.oracle.svm.core.util.VMError.shouldNotReachHere(VMError.java:65)
  SP 0x000000016f7b3750 IP 0x00000001006640e8  [image code] com.oracle.svm.core.aarch64.AArch64CPUFeatureAccess.verifyHostSupportsArchitecture(AArch64CPUFeatureAccess.java:148)
  SP 0x000000016f7b37e0 IP 0x000000010065a188  [image code] com.oracle.svm.core.JavaMainWrapper.runCore(JavaMainWrapper.java:131)
  SP 0x000000016f7b37e0 IP 0x000000010065a188  [image code] com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:186)
  SP 0x000000016f7b3830 IP 0x000000010067260c  [image code] com.oracle.svm.core.code.IsolateEnterStub.JavaMainWrapper_run_5087f5482cc9a6abc971913ece43acb471d2631b(IsolateEnterStub.java:0)

VM mutexes:
  mutex "mainVMOperationControlWorkQueue" is unlocked.
  mutex "referencePendingList" is unlocked.
  mutex "thread" is unlocked.

Heap settings and statistics:
  Supports isolates: false
  Object reference size: 8
  Aligned chunk size: 1048576
  Incremental collections: 0
  Complete collections: 0
```
[ARM Extensions](https://developer.arm.com/-/media/Arm%20Developer%20Community/PDF/Learn%20the%20Architecture/Understanding%20the%20Armv8.x%20extensions.pdf)[](https://www.google.com/search?q=armv8.0+vs+v8.3&newwindow=1&ei=5kEGYvaON5XdrgTL8YOgCw&ved=0ahUKEwj2mdbYv_f1AhWVrosKHcv4ALQQ4dUDCA4&uact=5&oq=armv8.0+vs+v8.3&gs_lcp=Cgdnd3Mtd2l6EAMyBQghEKABMgUIIRCgATIFCCEQoAE6CAgAEIAEELADOgUIABCiBDoGCAAQFhAeSgQIQRgBSgQIRhgAUIICWKseYLUgaAFwAHgAgAFniAHVBJIBAzcuMZgBAKABAcgBAcABAQ&sclient=gws-wiz#)[](https://webcache.googleusercontent.com/search?q=cache:I0lvExau3p4J:https://developer.arm.com/-/media/Arm%2520Developer%2520Community/PDF/Learn%2520the%2520Architecture/Understanding%2520the%2520Armv8.x%2520extensions.pdf+&cd=3&hl=ru&ct=clnk&gl=ru):

**Armv8.1-A**
  * Atomic memory access instructions (AArch64)
  * Limited Order regions (AArch64)
  * Increased Virtual Machine Identifier (VMID) size, and Virtualization Host Extensions (AArch64)
  * Privileged Access Never (PAN) (AArch32 and AArch64)

**Armv8.2-A**
  * Support for 52-bit addresses (AArch64)
  * The ability for PEs to share Translation Lookaside Buffer (TLB) entries (AArch32 and AArch64)
  * FP16 data processing instructions (AArch32 and AArch64)
  * Statistical profiling (AArch64)
  * Reliability Availability Serviceabilty (RAS) support becomes mandatory (AArch32 and AArch64)

**Armv8.3-A**
  * Pointer authentication (AArch64)
  * Nested virtualization (AArch64)
  * Advanced Single Instruction Multiple Data (SIMD) complex number support (AArch32 and AArch64)
  * Improved JavaScript data type conversion support (AArch32 and AArch64)
  * A change to the memory consistency model (AArch64)
  * ID mechanism support for larger system-visible caches (AArch32 and AArch64)

**Comment by kirillp** [comment]
This is the problem with CPU detection code 
The CPU supports all the FP and SIMD while the detection code failed to detect and a runtime exception raised

**Comment by teshull** [comment]
That's interesting; the problem looks to be on Apple's side, in that the HW features they list don't accurate represent the underlying platform. However, it's fine to always have FP and ASIMD registered as detected features on Apple, as all of their CPUs should have at least that.

#4367 fixes this and will be merged soon.

**Comment by Montura** [comment]
@teshull, thank you. I got the same commit in my fork :) 
 
P.S. And yes, you are right about Apple 64-bit CPU, they have FP and ASIMD (I've set "true" to this values and everything worked fine)

**Comment by kirillp** [comment]
what about these two ?
```
  features->fCRC32 = 1; // !!(cpu_has("hw.optional.armv8_crc32"));
  features->fLSE = 1; // !!(cpu_has("hw.optional.armv8_1_atomics"));
```

**Comment by teshull** [comment]
CRC32 and LSE aren't strictly necessary whereas FP and ASIMD are. Given it's only one old processor which doesn't accurately tell it's features, I don't want to hardcode more features than needed

**Comment by teshull** [comment]
#4367 was merged yesterday
