### ISSUE TITLE
Failed to install native-image on GraalVM 22

### ISSUE THREAD

**Issue by sergey-morenets** [oracle/graal#4329]
**Describe the issue**

native-image tool fails to install in Docker environment.

**Steps to reproduce the issue**

We always use these instructions to install native-image tool in Dockerfile:

```
FROM ghcr.io/graalvm/graalvm-ce:java17-21.3.0 as graalvm
RUN gu install native-image
```

And it always worked fine. However when we upgraded to GraalVM 22:

`FROM ghcr.io/graalvm/graalvm-ce:22 as graalvm`

native-image installation ended without errors:

```
bash-4.4# gu install native-image
Downloading: Release index file from oca.opensource.oracle.com
Downloading: Component catalog for GraalVM Enterprise Edition 22.0.0.1 on jdk17 from oca.opensource.oracle.com
Downloading: Component catalog for GraalVM Enterprise Edition 22.0.0 on jdk17 from oca.opensource.oracle.com
Downloading: Component catalog from www.graalvm.org
Processing Component: Native Image
Component Native Image (org.graalvm.native-image) is already installed.
Refreshed alternative links in /usr/bin/
```

But there is no native-image tool available (and in $JAVA_HOME/bin as well).

**Describe GraalVM and your environment:**
 - GraalVM version: 22
 - JDK major version: 17
 - OS: Linux
 - Architecture: Docker

**Comment by sergey-morenets** [comment]
This issue can be reproduced using this Dockerfile:

```
FROM ghcr.io/graalvm/graalvm-ce:22 
RUN gu install native-image && native-image
```

**Comment by MartinBalin** [comment]
Tested now using` docker run -it ghcr.io/graalvm/graalvm-ce:ol8-java17-22.0.0.2 /bin/sh` and then `gu install native-image` and here is my output
`sh-4.4# ./gu install native-image
Downloading: Release index file from oca.opensource.oracle.com
Downloading: Component catalog for GraalVM Enterprise Edition 22.0.0.1 on jdk17 from oca.opensource.oracle.com
Downloading: Component catalog for GraalVM Enterprise Edition 22.0.0 on jdk17 from oca.opensource.oracle.com
Downloading: Component catalog from www.graalvm.org
Processing Component: Native Image
Downloading: Component native-image: Native Image  from github.com
Installing new component: Native Image (org.graalvm.native-image, version 22.0.0.2)
sh-4.4# ls -l native-image
lrwxrwxrwx 1 root root 27 Feb 21 11:43 native-image -> ../lib/svm/bin/native-image`

It works.

**Comment by sergey-morenets** [comment]
@MartinBalin Yes, it doesn't reproduce on the newest build.
