### ISSUE TITLE
Minimal Java app example to run ruby

### ISSUE THREAD

**Issue by aemadrid** [oracle/graal#433]
I'd like to build a static Ruby app and it seems `native-image` only support Java/JVM languages. Could you provide a simple example of a minimal Java app to run some Ruby code?

**Comment by chrisseaton** [comment]
Do you want to compile a Ruby application to native?

**Comment by aemadrid** [comment]
yes, I want to compile a Ruby app. Just like `mruby` but without the limitations.

**Comment by chrisseaton** [comment]
Graal cannot AOT compile a Ruby application. It can only AOT compile a JVM bytecode application.

It can AOT compile a Ruby interpreter, which is what `mruby` is, and that is what the `ruby` executable you get in GraalVM is - an AOT compiled Ruby interpreter.

**Comment by aemadrid** [comment]
For me it is not so much about the performance improvements but how easy it would be to distribute the app and the garbled/hidden code. Nothing big for the moment but mostly small CLI apps.

**Comment by chrisseaton** [comment]
In the future it may be possible to compile a special version of the Ruby interpreter that has your code already loaded and initialised, so it is ready to start running the code immediately, but this is not something we're actively working on right now.

**Comment by aemadrid** [comment]
I see. I was confused about how the AOT worked. So to run Ruby code the Java code still needs a Ruby interpreter then?

**Comment by chrisseaton** [comment]
Yes that's right.

The reason this doesn't work for Ruby is that compiling pessimistic (never deoptimising) machine code from Java code is tractable and can be reasonably fast. I'm not sure that compiling pessimistic machine code from Ruby code is going to be reasonably fast. There are AOT Ruby compilers but I'm not really sure how much of the Ruby language they implement - I think it's not all of it.

**Comment by eregon** [comment]
FWIW it seems mruby and [mruby-cli](https://github.com/hone/mruby-cli) just add the Ruby code compiled as bytecode in the final executable, and of course still ship the mruby interpreter.
We could probably do something similar by storing the pre-parsed AST of the application Ruby code in the executable. We already do this for the core library, but not yet for application Ruby code.
Note that both of these solutions do not garble/hide the original Ruby code much though.

**Comment by aemadrid** [comment]
It would be enough for me. It’s super easy to distribute and the minimal garbling is just enough for me.

**Comment by eregon** [comment]
Currently, the standard library (both Ruby files and C extensions) are not stored in the native image but in a sibling directory. IIRC some of the libraries expect them to be real files and e.g., be able to `File.read()` them. As Chris said, this is not something we're actively working on right now.

On the other hand, one could distribute an archive containing truffleruby (bin/truffleruby + lib/) + the Ruby application files instead of a single binary and that should work well enough.

**Comment by chrisseaton** [comment]
I think we can close this issue now? We discussed what the native compilation does and doesn't do (it doesn't compile Ruby images). I don't think we're planning to make any kind of bundling tool that puts a Ruby application into the Ruby interpreter at the moment, although I can see that's useful for some people.

We've added some more general documentation on embedding from Java here as well https://github.com/oracle/truffleruby/blob/master/doc/user/jruby-migration.md.

**Comment by aemadrid** [comment]
Sure. I still think that the packaging options of GRAAL could make it much more enticing if we could figure out a way to deliver one single file for other languages just like you can with Java. Hopefully, someday that becomes a possibility.
