### ISSUE TITLE
 `native-image.properties` parses Args in a whitespace sensitive way (unlike command line)

### ISSUE THREAD

**Issue by ddimtirov** [oracle/graal#4331]
**Describe the issue**
When using `native-image.properties`, the `Args` property is picky about whitespace between arguments.

**Steps to reproduce the issue**

In your favorite project, create a `native-image.properties` with the following content:

```
Args = -H:TempDirectory=/tmp                -H:StaticExecutableWithDynamicLibC
```

The build would fail as it would assume the second argument is a single whitespace.

The culprit is here: https://github.com/oracle/graal/blob/e9469bd464f674f6d3445fde621514e7df5011de/substratevm/src/com.oracle.svm.driver/src/com/oracle/svm/driver/NativeImage.java#L1856

The regex needs to be changed to " +" or even better "\\\\s+"

**Describe GraalVM and your environment:**
 - GraalVM version: 21.3
 - JDK major version: **11** (any other would be impacted)
 - OS: Linux, Windows
 - Architecture: **AMD64**

**Comment by rodrigar-mx** [comment]
Hi @ddimtirov. Thanks for contributing to graalvm. We will take a look to your request and get back to you.

**Comment by ddimtirov** [comment]
Hi @rodrigar-mx would you consider a pull request fixing this?

**Comment by rodrigar-mx** [comment]
Hi @ddimtirov. The request is already tracked internally. Any questions or updates I will let you know.

**Comment by rodrigar-mx** [comment]
Issue fixed https://github.com/oracle/graal/commit/7ad29fb97ef93d65ecda3852275f8bd447b05184
