### ISSUE TITLE
[native-image] Process dies without apparent errors

### ISSUE THREAD

**Issue by renatoathaydes** [oracle/graal#434]
I am using GraalVM to compile a native-image for my HTTP server.
It seems to work great, but when I load test it it dies even under modest request loads.

When running on the JVM, it never dies even under much higher loads.

I have tried to simplify my application in order to identify what is causing the process to crash, but interestingly, the process won't die in any of the scenarios I tested with.

The HTTP server is very simple: it creates up a `ServerSocket`, then calls `accept()` on a single Thread, immediately dispatching connected sockets to be handled with an `ExecutorService` (I was using an unbounded thread pool, then limited it to up to 25 Threads, but it still crashes).

I wrote a [blog post](https://sites.google.com/a/athaydes.com/renato-athaydes/posts/a7mbnative-imagejavaappthatrunsin30msandusesonly4mbofram#TOC-Conclusion) about the HTTP server performance on GraalVM...

If you want to reproduce the problem, I suggest checking out my project and running the server:

```
git clone git@github.com:renatoathaydes/rawhttp.git
cd rawhttp
git checkout back-to-java8
./gradlew fatJar
```

The jar is under `rawhttp-cli/build/libs/rawhttp.jar`.

Create a native-image for that:

```
native-image -jar rawhttp-cli/build/libs/rawhttp.jar
```

Start the server on port 8082 serving the `public/` dir:

```
./rawhttp serve public/ --port 8082
```

Benchmark it with `ab` (assumes you have a text file in `public/my-file.txt` with some text):

```
ab -n 1000 -c 2 localhost:8082/my-file
```
 
This should be enough to crash the server.

**Comment by cstancu** [comment]
Thank you for your report. That is indeed unexpected. We'll look into it!

**Comment by Peter-B-Kessler** [comment]
I suspect you are relying on the fact that `FileInputStream` declares an override of the `Object.finalize()` method.  SubstrateVM does not support finalization (for lots of reasons).  [Here](https://github.com/oracle/graal/blob/master/substratevm/LIMITATIONS.md) is the full list of SubstrateVM limitations.

The best thing for you to do would be to explicitly call `FileInputStream.close()` when you are done with a stream.  I have not looked at your code to see where you might do that.

SubstrateVM does support `WeakReference` instances, so you might be able to use those to notify you when a (wrapper of) `FileInputStream` becomes unreachable, at which point you could close the underlying `FileInputStream`.  (Using `WeakReference` and your own polling thread is more reliable than using `Object.finalize()` even where that method is supported.)

In either case, you are relying on "prompt garbage collection" to clean up your native resources.  There is nothing that coordinates pressure on the Java object heap (which causes garbage collection and `finalize` / `WeakReference` notification) and pressure on the number of file descriptors (which causes file opens to fail).  For example, if you were running in a heap with lots of spare space, you might not be notified of unreachable `FileInputStream` instances until after you had run out of file descriptors.

Are you explicitly closing your `FileInputStreams` when you are done with them?  Is that working?

**Comment by renatoathaydes** [comment]
Hello!

There was one place where I indeed forgot to close the `FileInputStream` I was using! Thanks for the great hint.

After I [fixed that and stopped using File*Stream](https://github.com/renatoathaydes/rawhttp/commit/36e84f6c07c14f78eb8b4d2f2cbe86c35c3c66d6) as @cstancu suggested, the server won't crash anymore! And the performance seems to be about the same as before.

Awesome work, thank you very much!

I will update my blog post with these findings. 

Should we close this ticket or you want to improve GraalVM to tell the user why the program crashed, or something like that?

**Comment by cstancu** [comment]
I am closing this issue. When you run out of file descriptors you should now get a `java.io.FileNotFoundException` instead of a dying process.
