### ISSUE TITLE
Running error: Caused by: java.lang.reflect.UndeclaredThrowableException

### ISSUE THREAD

**Issue by fendo8888** [oracle/graal#4341]
openjdk version "1.8.0_302"
OpenJDK Runtime Environment (build 1.8.0_302-b07)
OpenJDK 64-Bit Server VM GraalVM CE 21.2.0 (build 25.302-b07-jvmci-21.2-b08, mixed mode)

There is no problem when compiling, once it runs, it will report an error: Caused by: java.lang.reflect.UndeclaredThrowableException, I checked it, and I don’t seem to be using a proxy here. Is there any way to solve this situation?

de.schlichtherle.xml.PersistenceServiceException: java.lang.reflect.UndeclaredThrowableException
at de.schlichtherle.xml.PersistenceService.load(PersistenceService.java:397)
at de.schlichtherle.license.PrivacyGuard.key2cert(PrivacyGuard.java:174)
at com.xxx.xxxx.loader.license.core.CustomLicenseManager.install(CustomLicenseManager.java:69)
at de.schlichtherle.license.LicenseManager.install(LicenseManager.java:406)
at de.schlichtherle.license.LicenseManager.install(LicenseManager.java:382)
at com.xxx.xxxx.loader.license.core.LicenseVerify.install(LicenseVerify.java:36)
at com.xxx.xxx.loader.launcher.tool.LicenseTool.install(LicenseTool.java:42)
at com.xxx.xxx.loader.launcher.FaasStartApplication.main(FaasStartApplication.java:44)
Caused by: java.lang.reflect.UndeclaredThrowableException
at de.schlichtherle.xml.PersistenceService$1.exceptionThrown(PersistenceService.java:79)
at com.sun.beans.decoder.DocumentHandler.handleException(DocumentHandler.java:359)
at com.sun.beans.decoder.DocumentHandler$1.run(DocumentHandler.java:388)
at com.sun.beans.decoder.DocumentHandler$1.run(DocumentHandler.java:372)
at java.security.AccessController.doPrivileged(AccessController.java:105)
at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
at com.sun.beans.decoder.DocumentHandler.parse(DocumentHandler.java:372)
at java.beans.XMLDecoder$1.run(XMLDecoder.java:201)
at java.beans.XMLDecoder$1.run(XMLDecoder.java:199)
at java.security.AccessController.doPrivileged(AccessController.java:105)
at java.beans.XMLDecoder.parsingComplete(XMLDecoder.java:199)
at java.beans.XMLDecoder.close(XMLDecoder.java:174)
at de.schlichtherle.xml.PersistenceService.load(PersistenceService.java:395)
... 7 more
Caused by: java.io.IOException: Stream closed
at java.io.BufferedInputStream.getBufIfOpen(BufferedInputStream.java:170)
at java.io.BufferedInputStream.fill(BufferedInputStream.java:214)
at java.io.BufferedInputStream.read(BufferedInputStream.java:265)
at com.sun.org.apache.xerces.internal.impl.XMLEntityManager$RewindableInputStream.read(XMLEntityManager.java:2902)
at com.sun.org.apache.xerces.internal.impl.XMLEntityManager.setupCurrentEntity(XMLEntityManager.java:674)
at com.sun.org.apache.xerces.internal.impl.XMLVersionDetector.determineDocVersion(XMLVersionDetector.java:148)
at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:806)
at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:771)
at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:643)
at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(SAXParserImpl.java:327)
at com.sun.beans.decoder.DocumentHandler$1.run(DocumentHandler.java:375)
... 17 more

**Comment by fniephaus** [comment]
Hi @fendo8888, it looks like your `PersistenceService` is using reflection to access certain Java classes, which are not part of the native executable. Do you have a `reflect-config.json` set up for your project or used the [Native Image agent](https://www.graalvm.org/22.0/reference-manual/native-image/Agent/) to create such a config for you?

**Comment by fendo8888** [comment]
> 嗨@fendo8888，看起来您`PersistenceService`正在使用反射来访问某些Java 类，这些类不是本机可执行文件的一部分。您是否`reflect-config.json`为您的项目设置或使用[Native Image 代理](https://www.graalvm.org/22.0/reference-manual/native-image/Agent/)为您创建这样的配置？

Automatically generated with -agentlib

![20220221203925](https://user-images.githubusercontent.com/22114481/154957134-9edef283-a86d-4c4f-bd60-ce5312f03335.png)

`
[
{
  "name":"byte[]"
},
{
  "name":"ch.qos.logback.classic.encoder.PatternLayoutEncoder",
  "allPublicMethods":true,
  "methods":[{"name":"<init>","parameterTypes":[] }]
},
{
  "name":"ch.qos.logback.classic.pattern.DateConverter",
  "methods":[{"name":"<init>","parameterTypes":[] }]
},
{
  "name":"ch.qos.logback.classic.pattern.LevelConverter",
  "methods":[{"name":"<init>","parameterTypes":[] }]
},
{
  "name":"ch.qos.logback.classic.pattern.LineSeparatorConverter",
  "methods":[{"name":"<init>","parameterTypes":[] }]
},
{
  "name":"ch.qos.logback.classic.pattern.MessageConverter",
  "methods":[{"name":"<init>","parameterTypes":[] }]
},
{
  "name":"ch.qos.logback.core.ConsoleAppender",
  "allPublicMethods":true,
  "methods":[{"name":"<init>","parameterTypes":[] }]
},
{
  "name":"com.xxxx.xxx.xxx.license.core.LicenseCheck",
  "allPublicMethods":true
},
{
  "name":"com.sun.beans.decoder.IntElementHandler",
  "methods":[{"name":"<init>","parameterTypes":[] }]
},
{
  "name":"com.sun.beans.decoder.JavaElementHandler",
  "methods":[{"name":"<init>","parameterTypes":[] }]
},
{
  "name":"com.sun.beans.decoder.LongElementHandler",
  "methods":[{"name":"<init>","parameterTypes":[] }]
},
{
  "name":"com.sun.beans.decoder.ObjectElementHandler",
  "methods":[{"name":"<init>","parameterTypes":[] }]
},
{
  "name":"com.sun.beans.decoder.StringElementHandler",
  "methods":[{"name":"<init>","parameterTypes":[] }]
},
{
  "name":"com.sun.beans.decoder.VoidElementHandler",
  "methods":[{"name":"<init>","parameterTypes":[] }]
},
{
  "name":"com.sun.crypto.provider.PBEKeyFactory$PBEWithMD5AndDES",
  "methods":[{"name":"<init>","parameterTypes":[] }]
},
{
  "name":"com.sun.crypto.provider.PBEWithMD5AndDESCipher",
  "methods":[{"name":"<init>","parameterTypes":[] }]
},
{
  "name":"com.sun.crypto.provider.SunJCE",
  "methods":[{"name":"<init>","parameterTypes":[] }]
},
{
  "name":"com.sun.net.ssl.internal.ssl.Provider",
  "methods":[{"name":"<init>","parameterTypes":[] }]
},
{
  "name":"com.sun.org.apache.xerces.internal.jaxp.SAXParserFactoryImpl",
  "methods":[{"name":"<init>","parameterTypes":[] }]
},
{
  "name":"de.schlichtherle.license.LicenseContent",
  "allPublicMethods":true
},
{
  "name":"de.schlichtherle.license.LicenseManager"
},
{
  "name":"de.schlichtherle.xml.GenericCertificate",
  "allPublicMethods":true
},
{
  "name":"java.beans.XMLDecoder"
},
{
  "name":"java.lang.Class",
  "allPublicMethods":true
},
{
  "name":"java.lang.RuntimePermission"
},
{
  "name":"java.lang.String"
},
{
  "name":"java.lang.String[]"
},
{
  "name":"java.net.SocketPermission"
},
{
  "name":"java.security.AlgorithmParametersSpi"
},
{
  "name":"java.security.AllPermission"
},
{
  "name":"java.security.KeyStoreSpi"
},
{
  "name":"java.security.MessageDigestSpi"
},
{
  "name":"java.security.interfaces.DSAPrivateKey"
},
{
  "name":"java.security.interfaces.DSAPublicKey"
},
{
  "name":"java.security.spec.DSAParameterSpec"
},
{
  "name":"java.util.Date",
  "allPublicConstructors":true
},
{
  "name":"java.util.PropertyPermission"
},
{
  "name":"javax.management.ObjectName"
},
{
  "name":"javax.security.auth.x500.X500Principal",
  "allPublicConstructors":true,
  "fields":[{"name":"thisX500Name"}],
  "methods":[{"name":"<init>","parameterTypes":["sun.security.x509.X500Name"] }]
},
{
  "name":"sun.security.ec.SunEC",
  "methods":[{"name":"<init>","parameterTypes":[] }]
},
{
  "name":"sun.security.pkcs.SignerInfo[]"
},
{
  "name":"sun.security.provider.DSA$SHA1withDSA",
  "methods":[{"name":"<init>","parameterTypes":[] }]
},
{
  "name":"sun.security.provider.DSAKeyFactory",
  "methods":[{"name":"<init>","parameterTypes":[] }]
},
{
  "name":"sun.security.provider.DSAParameters",
  "methods":[{"name":"<init>","parameterTypes":[] }]
},
{
  "name":"sun.security.provider.JavaKeyStore$DualFormatJKS",
  "methods":[{"name":"<init>","parameterTypes":[] }]
},
{
  "name":"sun.security.provider.JavaKeyStore$JKS",
  "methods":[{"name":"<init>","parameterTypes":[] }]
},
{
  "name":"sun.security.provider.MD5",
  "methods":[{"name":"<init>","parameterTypes":[] }]
},
{
  "name":"sun.security.provider.PolicyFile",
  "methods":[{"name":"<init>","parameterTypes":[] }]
},
{
  "name":"sun.security.provider.SHA",
  "methods":[{"name":"<init>","parameterTypes":[] }]
},
{
  "name":"sun.security.provider.SecureRandom",
  "methods":[{"name":"<init>","parameterTypes":[] }]
},
{
  "name":"sun.security.provider.Sun",
  "methods":[{"name":"<init>","parameterTypes":[] }]
},
{
  "name":"sun.security.provider.X509Factory",
  "methods":[{"name":"<init>","parameterTypes":[] }]
},
{
  "name":"sun.security.rsa.SunRsaSign",
  "methods":[{"name":"<init>","parameterTypes":[] }]
},
{
  "name":"sun.security.util.ObjectIdentifier"
},
{
  "name":"sun.security.x509.CertificateExtensions"
},
{
  "name":"sun.security.x509.SubjectKeyIdentifierExtension",
  "methods":[{"name":"<init>","parameterTypes":["java.lang.Boolean","java.lang.Object"] }]
}
]

`

**Comment by fniephaus** [comment]
Can you share the lines around at `de.schlichtherle.xml.PersistenceService.load(PersistenceService.java:397)`? It seems the `reflect-config.json` may be missing a class that was not picked up by the Native Image agent.

**Comment by fendo8888** [comment]
> 397

`
    /**
     * Loads a single object, which may form the root of an entire object graph,
     * from XML content in the given input stream {@code xmlIn}.
     * <p>
     * Please note the following:
     * <ul>
     * <li>The stream is connected to a new {@code BufferedInputStream}
     *     with {@code BUFSIZE} as its buffer size and is <em>always</em>
     *     closed (even if an exception is thrown).</li>
     * <li>This method will <em>not</em> tolerate any I/O or other
     *     deserialisation exceptions!</li>
     * </ul>
     *
     * @param  xmlIn the unbuffered stream to input the XML content - may
     *         <em>not</em> be {@code null}.
     * @return The root of the loaded object graph - may be {@code null}.
     * @throws NullPointerException if {@code xmlIn} is {@code null}.
     * @throws PersistenceServiceException if <em>any</em> throwable was thrown
     *         during serialization.
     */
    public static Object load(InputStream xmlIn)
    throws PersistenceServiceException {
        if (null == xmlIn) throw new NullPointerException();
        XMLDecoder decoder = null;
        try {
            // Note that the constructor already loads the complete object
            // graph into memory. If anything goes wrong, an unchecked
            // exception is thrown already HERE!
            decoder = new XMLDecoder(
                    new BufferedInputStream(xmlIn, BUFSIZE),
                    null,
                    createExceptionListener());
            return decoder.readObject();
        } catch (final UndeclaredThrowableException ex) {
            throw new PersistenceServiceException(ex.getCause()); // unwrap cause
        } catch (final Throwable ex) {
            throw new PersistenceServiceException(ex);
        } finally {
            if (null != decoder) {
                try {
                    decoder.close(); // Could throw e.g. OutOfMemoryError (again)!
                } catch (final Throwable paranoid) {
                    throw new PersistenceServiceException(paranoid);
                }
            }
        }
    }
`

**Comment by fendo8888** [comment]
de.schlichtherle.license.PrivacyGuard.key2cert(PrivacyGuard.java:174)

```

    /**
     * Decrypts, decompresses and decodes the given license key
     * and returns the result as a license certificate.
     * Please note that this method does not verify the certificate.
     *
     * @param key The license key to process
     *        - may <em>not</em> be {@code null}.
     *
     * @return The license certificate
     *         - {@code null} is never returned.
     *
     * @throws Exception An instance of a subclass of this class for various
     *         reasons.
     *         Note that you should always use
     *         {@link Throwable#getLocalizedMessage()} to get a (possibly
     *         localized) meaningful detail message.
     */
    public GenericCertificate key2cert(final byte[] key)
    throws Exception {
        final InputStream in = new GZIPInputStream(
                new ByteArrayInputStream(
                    getCipher4Decryption().doFinal(key)));
        final GenericCertificate certificate;
        try {
            certificate = (GenericCertificate) PersistenceService.load(in);
        }
        finally {
            try { in.close(); }
            catch (IOException weDontCare) { }
        }

        return certificate;
    }
```

**Comment by fendo8888** [comment]
xxx.CustomLicenseManager.install(CustomLicenseManager.java:69)

```
    protected synchronized PrivacyGuard getPrivacyGuard() {
        if (null == guard)
            guard = new PrivacyGuard(getLicenseParam().getCipherParam());
        return guard;
    }
```

```
    protected synchronized LicenseContent install(
            final byte[] key,
            final LicenseNotary notary)
            throws Exception {
        final GenericCertificate certificate = getPrivacyGuard().key2cert(key);
}
```

**Comment by fniephaus** [comment]
These are the interesting lines of code:
```java
        try {
            // Note that the constructor already loads the complete object
            // graph into memory. If anything goes wrong, an unchecked
            // exception is thrown already HERE!
            decoder = new XMLDecoder(
                    new BufferedInputStream(xmlIn, BUFSIZE),
                    null,
                    createExceptionListener());
            return decoder.readObject();
        } catch (final UndeclaredThrowableException ex) {
            throw new PersistenceServiceException(ex.getCause()); // unwrap cause
```
I don't know why an unchecked exception is thrown in the constructor of `XMLDecoder` but that seems to trigger your issue.

You could try initializing `XMLDecoder` at run-time via `native-image --initialize-at-run-time=java.beans.XMLDecoder ...`. Does that help?

**Comment by fendo8888** [comment]
It has no effect. After adding it, it still reports an error
```
            <plugin>
                <groupId>org.graalvm.nativeimage</groupId>
                <artifactId>native-image-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <goals>
                            <goal>native-image</goal>
                        </goals>
                        <phase>package</phase>
                    </execution>
                </executions>
                <configuration>
                    <skip>false</skip>
                    <imageName>faas-loader</imageName>
                    <mainClass>com.xxx.xxx.xxx.StartApplication</mainClass>
                    <buildArgs>
                        --no-fallback
                        --allow-incomplete-classpath
                        --initialize-at-run-time=java.beans.XMLDecoder
                        -H:+ReportExceptionStackTraces
                        -H:ConfigurationFileDirectories=D:\3\xxx\xxxx\META-INF\native-image\
                    </buildArgs>
                </configuration>
            </plugin>
```

**Comment by fniephaus** [comment]
Sorry, classes are initialized at run-time by default so that flag should not have any effect. Could you please try with `--initialize-at-build-time=java.beans.XMLDecoder` instead?

**Comment by fendo8888** [comment]
> 抱歉，默认情况下，类是在运行时初始化的，因此该标志不应该有任何影响。你可以试试`--initialize-at-build-time=java.beans.XMLDecoder`吗？

`--initialize-at-run-time=java.beans.XMLDecoder` 😰 It has no effect. After adding it, it still reports an error

**Comment by fniephaus** [comment]
Sorry but without a reproducer, it's hard to debug this any further.

**Comment by fendo8888** [comment]
> Sorry but without a reproducer, it's hard to debug this any further.

😥

**Comment by fendo8888** [comment]
> Sorry but without a reproducer, it's hard to debug this any further.

Are there any relevant debugging techniques to solve this kind of problem?

**Comment by fniephaus** [comment]
I would try to create a small reproducer around `java.beans.XMLDecoder` so we can isolate the problem. Maybe it's `de.schlichtherle.xml.PersistenceService` which needs to be initialized at run-time?

**Comment by oubidar-Abderrahim** [comment]
Hi, if this issue is still present in the latest GraalVM versions, please create a new ticket following the template provided and share a reproducer. we'll be happy to give this another look. thank you
