### ISSUE TITLE
Node.js interacting with c#

### ISSUE THREAD

**Issue by billreynolds007** [oracle/graal#4342]
graalVM has progress significantly since I last worked with it.
We were able to run our backend node.js server and easily interoperate with Java classes.
I saw the various polyglot examples at 

  https://www.graalvm.org/22.0/reference-manual/polyglot-programming/#running-polyglot-applications

What approach is recommended for running a node.js backend wanting to interact with C# code?

Thank you

**Comment by gimbles** [comment]
While as far as I am aware, GraalVM does not have a direct C# connection in the Polyglot API.

I wouldn't exactly *recommend* this, neither is this particularly efficient. But you could export C functions from your C# code and then access it through Java [*Then* you can access it from Graal.jS]

As far as I know, Graal.jS doesn't have a C FFI API so going through Java can help that.

**Comment by rodrigar-mx** [comment]
Hi @billreynolds007. C# is not currently supported with graalvm, but you can follow up the main discussion here https://github.com/oracle/graal/issues/349 where some users have shared an experimental implementation or other alternatives. As mentioned before,  perhaps you can also try using C, and the JNI as an intermediary.
