### ISSUE TITLE
Docs links are broken

### ISSUE THREAD

**Issue by benrkia** [oracle/graal#4345]
**Describe the issue**
At the java quickstart page (https://www.graalvm.org/java/quickstart/). There is a set of broken documentation links:
- [GraalVM Native Image](https://www.graalvm.org/java/..docs/reference-manual/native-image/README.md)
- [GraalVM Updater](https://www.graalvm.org/java/..docs/reference-manual/graalvm-updater.md)
- [the requirements](https://www.graalvm.org/java/..docs/reference-manual/native-image/README.md/#prerequisites)
- [its reference page](https://www.graalvm.org/docs/reference-manual/compiler.md)

**Comment by rubyFeedback** [comment]
Nooooooo ... :(

Information infrastructure apocalypse is happening ...

(I am glad I do tend to store useful information in my local knowledge base, though. The GraalVM docs are very nice, though - on first go-through I was able to figure out a ton of things that can be done with GraalVM, including using native-image. Hopefully new arrivers can soon read the docs again.)

**Comment by rodrigar-mx** [comment]
Hi @benrkia. Thanks for reporting this issue. We will take care of it.

**Comment by olyagpl** [comment]
@benrkia, the links have just been updated. Thank you for reporting!
