### ISSUE TITLE
SIGUSR1 not producing heap dump for shared library 

### ISSUE THREAD

**Issue by rowsimms42** [oracle/graal#4347]
**Describe the issue**
A clear and concise description of the issue. We recommend using the [latest snapshot builds](https://github.com/graalvm/graalvm-ce-dev-builds/releases) to replicate the issue as  bugs are constantly being fixed in the master branch

“kill -SIGUSR1 pid” does not produce a heap dump when using -H:+AllowVMInspection and building the native image as a shared library. Instead, the program terminates.

**Describe GraalVM and your environment:**
 - GraalVM version (latest snapshot builds can be found [here](https://github.com/graalvm/graalvm-ce-dev-builds/releases)), or commit id if built from source: **[e.g. EE 19.3, CE 20.0, CE 20.1.0-dev-20200304_0848]**
 - JDK major version: **[e.g.:8]**11 
 - OS: **[e.g. macOS Catalina]**Linux 
 - Architecture: **[e.g.: AMD64]**

 EE 22.0.0.2

**Comment by rodrigar-mx** [comment]
Hi @rowsimms42. Thanks for reporting this issue. We will take a look into it and get back to you.

**Comment by vjovanov** [comment]
Our shared libraries are non-intrusive with respect to signals so they will not intercept any signals and hence won't heap dump. The signal is something that the host process should catch and then inform the appropriate (or all) isolate(s) in the shared library to perform a heap dump.

The heap dump can be performed via
```
org.graalvm.nativeimage.VMRuntime#dumpHeap
```
for which one can make an entry point in the library.
