### ISSUE TITLE
More broken links in docs

### ISSUE THREAD

**Issue by pietrobraione** [oracle/graal#4357]
**Describe the issue**
In the graal / compiler / docs / Debugging.md file (https://github.com/oracle/graal/blob/master/compiler/docs/Debugging.md) there are some broken links to tools:

* [IGV](https://www.graalvm.org/docs/reference-manual/tools/#ideal-graph-visualizer);
* [C1Visualizer](https://java.net/projects/c1visualizer/);
* [hsdis](https://kenai.com/projects/base-hsdis).

**Comment by olyagpl** [comment]
Thanks for pointing at broken links! Changes are online https://github.com/oracle/graal/blob/master/compiler/docs/Debugging.md.
