### ISSUE TITLE
Hard-coding search for $VALUES prevents GraalVM native-image from working on (some) obfuscated jars

### ISSUE THREAD

**Issue by gnp** [oracle/graal#436]
https://github.com/oracle/graal/blob/8a11ac495df7ebf2b99a3ae2e6dfc018d83d9424/substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/analysis/Inflation.java#L167

Observed problem in the version of SubstrateVM used by this version of GraalVM: _graalvm-ee-1.0.0-rc1-macos-amd64.tar.gz_

To reproduce, download the minecraft 1.12.2 server jar from

https://launcher.mojang.com/mc/game/1.12.2/server/886945bfb2b978778c3a0288fd7fab09d315b25f/server.jar

and rename it to _minecraft-server.1.12.2.jar_.

Then, run:

```
$ native-image -jar minecraft-server.1.12.2.jar
````

and witness error message included in the backtrace:

```
Caused by: jdk.vm.ci.common.JVMCIError: should not reach here: Enumeration does not have static field with enumeration values: AnalysisType<vl, allocated: false, inHeap: false, inTypeCheck: false>
```

Running `javap` this way:

```
$ javap -cp minecraft_server.1.12.2.jar -p vl
```

shows the structure of the class that is tripping up SubstrateVM:

```
Compiled from "SourceFile"
public final class vl extends java.lang.Enum<vl> {
  public static final vl a;
  public static final vl b;
  public static final vl c;
  public static final vl d;
  public static final vl e;
  public static final vl f;
  private final vl$a g;
  private final int h;
  private final int i;
  private final java.lang.String j;
  private static final vl[] k;
  public static vl[] values();
  public static vl valueOf(java.lang.String);
  private vl(vl$a, int, int, java.lang.String);
  public vl$a a();
  public int b();
  public int c();
  public java.lang.String d();
  public static vl a(java.lang.String);
  static {};
}
```

You can see they have a proper `values()` method, but the obfuscator (maybe ProGuard?) is mapping the static `$VALUES` field to `k`. Note this does not prevent normal Java VM from running the application in the jar, so I'd assert it is at least de facto valid (if inconvenient) for the obfuscator to do this.

(Aside) FWIW, IMO the obfuscator probably shouldn't be messing with the name of `$VALUES` anyway (it leaves other important public bits of enumerations alone because it has to, it is maybe gratuitous for it to also not leave the private `$VALUES` member name alone too even if not strictly required for things to run). Nonetheless, a more robust solution in SubstrateVM would be desirable, and seems to me not out of reach...

If we run `javap` again with the `-c` argument to get the decompilation and `-v` argument to see the constant table:

```
$ javap -cp minecraft_server.1.12.2.jar -c -p -v vl
```

we see the implementation of the public static method `values()` is simple:

```
...
   #28 = Fieldref           #2.#27        // vl.k:[Lvl;
...
  public static vl[] values();
    descriptor: ()[Lvl;
    flags: ACC_PUBLIC, ACC_STATIC
    Code:
      stack=1, locals=0, args_size=0
         0: getstatic     #28                 // Field k:[Lvl;
         3: invokevirtual #33                 // Method "[Lvl;".clone:()Ljava/lang/Object;
         6: checkcast     #29                 // class "[Lvl;"
         9: areturn
      LineNumberTable:
        line 3: 0
...
```

I would offer that compiling a simple test enum with regular java results in a similar structure for the compiled `values` method:

```
...
   #1 = Fieldref           #4.#59         // vl.$VALUES:[Lvl;
...
public static vl[] values();
    descriptor: ()[Lvl;
    flags: ACC_PUBLIC, ACC_STATIC
    Code:
      stack=1, locals=0, args_size=0
         0: getstatic     #1                  // Field $VALUES:[Lvl;
         3: invokevirtual #2                  // Method "[Lvl;".clone:()Ljava/lang/Object;
         6: checkcast     #3                  // class "[Lvl;"
         9: areturn
      LineNumberTable:
        line 2: 0
...
```

So, it may not be completely unreasonable to probe for that structure and infer the correct static field with high probability if `$VALUES` is not present in an otherwise legit-looking enum class.

**Comment by gnp** [comment]
Alternatively, if there is only one static member with the required type, it’s probably safe enough to go for it.

**Comment by cstancu** [comment]
Issue is fixed in https://github.com/oracle/graal/commit/77f19a97ff1862461be5f12d18a152c4dc0a785d. [Build from source](https://github.com/oracle/graal/tree/master/substratevm#quick-start) to get the latest fixes.
