### ISSUE TITLE
Dart support

### ISSUE THREAD

**Issue by chengenzhao** [oracle/graal#437]
Newbie question, any reason why Dart is not supported? Would it be possible technically?
Apologies in advance if this is out of scope of the project.

Thanks

**Comment by vmutafov** [comment]
Wouldn't dart2js do the work? Compile Dart to JS and then execute it on the GraalVM. I haven't tried it, but I think of trying it.

**Comment by chengenzhao** [comment]
dart2js is not that elegant actually
a front-end of dart lang would be better 
in that case we could implement dart lang support for vert.x rather than translate dart into js and then use it as js way

**Comment by hbakhtiyor** [comment]
some case that it can use large java ecosystem for developing server-side with dart

**Comment by perezd** [comment]
This would be compelling!

**Comment by Auties00** [comment]
Bump, would love this

**Comment by bwfrieds** [comment]
> Bump, would love this

I recently learned of this...  https://dart.dev/tools/dart2native   Is Dart support on Graal still compelling?

**Comment by gochev** [comment]
@bwfrieds  yes it is since it gives you the possibility to speak between the languages using the Context. I would love to be able to speak and pass data inside a single app running on GraalVM where I have parts in dart and parts in Java.

**Comment by spavlusieva** [comment]
Hi @chengenzhao, this issue has been inactive for more than 180 days. We’ll close it to focus on current issues. In case it’s still relevant, please reopen it and we’ll take another look. Thank you!
