### ISSUE TITLE
native-image is using the wrong classpath ordering

### ISSUE THREAD

**Issue by revintec** [oracle/graal#4374]
suppose `corex-main.jar/MANIFEST.MF` contains `Class-Path: corex-lib.jar`

`native-image -cp corex-main.jar --verbose ...` shows classpath to be `-imagecp .../library-support-enterprise.jar:.../library-support.jar:.../corex-lib.jar:.../corex-main.jar`
but it should be `corex-main.jar` then `corex-lib.jar`(running `java -cp corex-main.jar` is fine, with correct classpath

GraalVM 20.3.4 Java 11 CE (Java Version 11.0.13+10-LTS-jvmci-20.3-b24)

in the meantime of fixing the bug, is there any way that I can tweak the classpath ordering?
tried but not working:
1) using javaagent to patch `lib/svm/builder/svm.jar`(like `native-image -J-javaagent:...`), nothing changed, may be interfered by `native-image`'s own `-javaagent:.../svm.jar`?
2) run the java command outputted by `native-image --verbose` directly, some exception are thrown(they were not thrown when I run `native-image ...`), is running java command directly and different from running `native-image`?
3) usual stuff like `native-image -cp corex-main.jar -cp corex-lib.jar` and some variant of that, can't affect `-imagecp`

**Comment by rodrigar-mx** [comment]
Hi @revintec. Could you please elaborate on how the classpath ordering is affecting the native image build or execution. Please share any error logs or stack traces, if any? Could you please try also using latest [graalvm 22.0.0 ](https://github.com/graalvm/graalvm-ce-builds/releases/tag/vm-22.0.0.2) instead of 20.3.4 version.

**Comment by revintec** [comment]
Hi @rodrigar-mx , thanks for the reply, I'll try the new version and report back to you

suppose we have `a.class` in both `a.jar` and `b.jar`, if classpath ordering is incorrect, we'd use the wrong version of `a.class`

**Comment by revintec** [comment]
@rodrigar-mx using GraalVM 22.0.0.2, latest version as of writing, still exhibits the same problem

-imagecp ...corex-lib.jar:...corex-main.jar:/Library/Java/JavaVirtualMachines/GvmEE-Java17-22.0.0.2/Contents/Home/lib/svm/library-support.jar

**Comment by olpaw** [comment]
@revintec the classpath order problem is fixed for the main branch (`master`) and the 22.1 release branch (`release/graal-vm/22.1`).

**Comment by revintec** [comment]
@olpaw can't find the commit or the branch, can you give me a link?

**Comment by olpaw** [comment]
> @olpaw can't find the commit or the branch, can you give me a link?

https://github.com/oracle/graal/tree/release/graal-vm/22.1

**Comment by revintec** [comment]
@olpaw didn't find the relevant commit in 22.1 or the master branch... can you give me a pointer to the commit?

**Comment by olpaw** [comment]
@revintec please build from `release/graal-vm/22.1`.

    > git clone https://github.com/oracle/graal.git
    > cd graal/substratevm
    > git switch release/graal-vm/22.1
    > mx build
    > mx native-image -cp ... your args

@rodrigar-mx please provide help to the user so that we know the issue is indeed fixed.

**Comment by rodrigar-mx** [comment]
Sure. @revintec Is it possible that you share the jars you are using for building the native image, so I can use them to test  locally with latest build and report the bug if necessary.

**Comment by revintec** [comment]
thanks for all your help, I'd like to see the commit to learn how it's fixed
and I've prepared a jar for you to test, you can run the following command `native-image --verbose -cp main.jar xx|grep -A1 imagecp`, the expected output should have `main.jar` listed before `lib.jar`

[main.jar](https://github.com/oracle/graal/files/8338426/main.txt)
Github doesn't support `.jar` files as an attachment, please change file extension to `.jar` manually

**Comment by rodrigar-mx** [comment]
I have tested it locally with release/graal-vm/22.1 and with  [GraalVM CE 22.2.0-dev-20220323_0052](https://github.com/graalvm/graalvm-ce-dev-builds/releases/latest)  and confirm that the  order is still the same. @revintec I have reported this error internally. Any updates we will let you know.
