### ISSUE TITLE
[native-image] Can't load Shared Libraries

### ISSUE THREAD

**Issue by Anuken** [oracle/graal#438]
I am trying to compile a java libGDX .jar using native-image. No errors are produced during compilation, but when I try to run the resulting executable, I get [this error](https://hastebin.com/utocobukej.sql), despite the fact that all the relevant `.so` files are in the jar file. 

[Here](https://github.com/libgdx/libgdx/blob/master/gdx/src/com/badlogic/gdx/utils/SharedLibraryLoader.java#L288) is the specific method in the libGDX source which tries to load the libraries.

_Graal Version_: Latest commit, built from source.
_OS_: Linux Mint 18

_Full command_: `mx native-image -Djava.library.path=<path to directory with all .so files> -H:+JNI -jar <path to jar file>`

[Download link to jar file.](https://mega.nz/#!Ol41FQQI!NUwFxuAsXO7INXet9SBC7eRdrQMsa3deiSrJtt1c8JU)

Removing `-Djava.library.path` and/or adding a separate `-classpath` argument that points to the unzipped contents of the jar doesn't help. I've also tried using both absolute and relative paths for `-Djava.library.path`.

I've read the README on JNI, but it doesn't seem very clear what I should do when `System.load()` is used in the code-- I've tried creating a [jniconfig.json](https://hastebin.com/duguvexisi.json) file in the folder with the shared libraries, listing the libraries there and passing it to `JniConfigurationFiles`, but that gives me the error `Class <name>.so not found`.

**Comment by Jotschi** [comment]
I had to place the lib files in a `clibraries/linux-amd64` folder. I think you can also use the `-H:CLibraryPath` setting to set the path.

**Comment by Anuken** [comment]
@Jotschi Just tried putting all the shared libraries in the `clibraries/linux-amd64` folder, and then specifying it with `H:CLibraryPath` with both absolute and relative directories. Neither seemed to work-- I think the problem may be with how libGDX loads libraries. It fails when trying to call [getResourceAsStream](https://github.com/libgdx/libgdx/blob/master/gdx/src/com/badlogic/gdx/utils/SharedLibraryLoader.java#L132), which seems to make sense since the normal jar file structure isn't present.

Were you using libGDX specifically? Just curious if I'm doing something wrong or if it is indeed a libGDX issue.

**Comment by Jotschi** [comment]
@Anuken No - sorry. I was referring to my own usecase. I'm also a bit lost but I think you may need to specify the native methods of your class in the JNIConfigurationFile. (Wild guess)

**Comment by Anuken** [comment]
Oh.
After specifying all the classes with JNI in them in the config, I compiled again. This increased the size of the resulting image significantly, but I still ran into the same error.

I finally decided to just replace the libGDX `SharedLibraryLoader` with my own version that loaded from local files-- this worked, surprisingly, but the errors just kept coming. Now I'm getting a `UnsatisfiedLink` [error](https://hastebin.com/ucumopogoz.swift) from a LWJGL class that I have *definitely* added to the JNI [config](https://hastebin.com/xozaxeyiru.json).

**Comment by peter-hofer** [comment]
Addition: we do not support loading native libraries from static constructors, because these are already executed when the class is loaded during the build and no longer at runtime (see also #439).

**Comment by Anuken** [comment]
@peter-hofer Thank you for the response! Yes, I did get that issue as well. To fix it, I had to make a copy of the original file, change the `static{}` initialization to runtime lazy-initilization and save it in the same exact package, then compile it and replace the resulting `.class` files in the jar.

[Here is a new jar with these fixes applied.](https://mega.nz/#!m9gCTQDK!hO8SwadWalzTWfMxw46rixtoEXiyuTb4xdutQX4O2XU)

After I applied these fixes, I found the class that was loading LWJGL libraries from a static block, and replaced the static initializer with a method that I call from `main(String[])` to load these libraries at runtime. However, there were (many) other static initializers in LWJGL that depended on these libraries being loaded... which caused a run-time error while compiling due to a link error. Thus, I made the libraries be loaded both in a static initializer _and_ at runtime. However, running *that* gives me [this error.](https://hastebin.com/owizobotig.go)

**Comment by peter-hofer** [comment]
Indeed we currently don't support JVMTI. So loading the shared libraries works now (despite the necessary changes)?
Please keep us posted, I think running projects like this would make a great use case for Graal native images.

**Comment by Anuken** [comment]
Yes, it does seem to load the libraries now. I've updated my LWJGL3 version to the latest snapshot, and while the JVMTI error seems to be gone now, I'm getting a new, probably-unrelated (native?) [crash](https://hastebin.com/amovepobit.go) related to usage of `sun.misc.unsafe`. 
While it could be related to an error made by me while upgrading, I somehow don't think that's the case.

**Comment by peter-hofer** [comment]
Looking at the LWJGL code, I might have found the problem: `MemoryAccessorUnsafe` determines the offsets of the `address` and `capacity` fields of a `Buffer` in a static initializer using magic constants. That static initializer runs at the native image's build time, but the determined offsets can be (and probably are) different at runtime.
Can you try fixing that too or provide me with your current jar file to debug this?

**Comment by Anuken** [comment]
Oh, I see. It looks like it might be related to one of the issues discussed [here](https://github.com/oracle/graal/issues/304)? It's strange that no compile-time errors are thrown. I'll be away from home for most of today, so I'm not sure if I'll have time to try and fix it right now.

[Here is the link to the updated JAR file.](https://mega.nz/#!akplXYJB!uWWtS06Qennxf-Kj6hlgajn9sP4P-RBAIy-h2aWOYpY) In order for all the libraries to load, I had to place them in the same directory as the executable.

**Comment by peter-hofer** [comment]
I managed to temporarily work around the crash by using the substitutions mechanism to use the correct field offsets: ```@TargetClass(className = "org.lwjgl.system.MemoryAccess", innerClass = "MemoryAccessorUnsafe")
final class Target_org_lwjgl_system_MemoryAccess_MemoryAccessorUnsafe {
    @Alias
    @RecomputeFieldValue(kind = Kind.FieldOffset, declClass = Buffer.class, name = "address")
    static long ADDRESS;

    @Alias
    @RecomputeFieldValue(kind = Kind.FieldOffset, declClass = Buffer.class, name = "capacity")
    static long CAPACITY;
}```

Now I see a crash in invoking the native method `invokePP`, and that seems to be caused by `org.lwjgl.system.Callback` caching the addresses of native functions in a static constructor at build time, which are different from the addresses at runtime.

**Comment by Anuken** [comment]
Is it worth trying to re-write big chunks of LWJGL code and remove **all** static initializers, substituting for runtime initialization?

**Comment by cstancu** [comment]
@Anuken we are investigating the possibility to push some of the static initializers execution at run time to avoid this kind of issues. However, this is just in the idea phase for now and we don't have a concrete time line nor we know if that will solve all the LWJGL issues. For now, replacing the static initializers in LWJGL that cause issues seems to be the only solution.

**Comment by Spasi** [comment]
Hello,

I haven't had a chance to play with `native-image` yet, but it might be interesting to explain why LWJGL 3 works the way it does.

- The `java.nio.Buffer` field offsets are retrieved using magic values to avoid illegal reflective access warnings (and in the future, errors) on Java 9+. Note that LWJGL is one of the few libraries with explicit modules and multi-release (JAR) code. Java 8 is required but 9/10 are fully supported.
- Most static initializers are used to set `static final` fields, using information that's only available at runtime. Doing so is critical for performance on HotSpot/Graal/any other JIT. It's a powerful optimization for having the JIT fully inline constants and the single implementation (chosen at runtime) of particular interfaces. Note that LWJGL is used in game development and other performance-sensitive contexts.
- Some static initializers are used for the lazy, run-once effect. As an example, in OpenGL applications there can be multiple contexts with different capabilities. However, it's very common for most applications to only create one context, or multiple contexts with the exact same capabilities. Taking advantage of this fact, LWJGL lazily "captures" the capabilities of the first context used and a thread-local lookup per OpenGL function call is avoided, while still being able to "de-optimize" to the TLS implementation if necessary.

I currently don't see a way to replace static initializers without a painful performance sacrifice on JIT JVMs. A fork with the necessary changes shouldn't be too much work to maintain though.

**Comment by Anuken** [comment]
I was looking through some comments today and saw the option `--delay-class-initialization-to-runtime` being mentioned-- could this be used to fix LWJGL's issues with static initializers?

**Comment by cstancu** [comment]
@Anuken yes, that is what this option was introduced for. More documentation is coming. In the meantime you can read some details in the [release notes](http://www.graalvm.org/docs/release-notes/#10-rc6).

**Comment by RUSshy** [comment]
I tried to play a bit with that ``--delay-class-initialization-to-runtime`` option

https://gist.github.com/RUSshy/1cfed347c773d6016c453d2035d001bc

Looks like it doesn't handle nested inner classes ?

``org.lwjgl.openal.AL$ICDStatic$WriteOnce``

```
Caused by: java.lang.IllegalStateException: No ALCapabilities instance has been set
    at org.lwjgl.openal.AL$ICDStatic$WriteOnce.<clinit>(AL.java:255)
    ... 45 more
```

**Comment by Anuken** [comment]
@RUSshy According to [this post](https://github.com/oracle/graal/issues/713#issuecomment-427094050), you might need to list the class names between single quotes (`''`)-- have you tried running it with `--delay-class-initialization-to-runtime='org.lwjgl.openal.AL,org.lwjgl.openal.ALC,org.lwjgl.openal.AL$ICDStatic,org.lwjgl.openal.AL$ICDStatic$WriteOnce,org.lwjgl.opengl.NVTextureBarrier,org.lwjgl.opengl.NVShaderBufferLoad,org.lwjgl.opengl.NVSampleLocations,org.lwjgl.opengl.NVQueryResourceTag,org.lwjgl.system.macosx.CoreFoundation,org.lwjgl.system.windows.WindowsLibrary,org.lwjgl.openal.AL$WriteOnce,com.badlogic.gdx.backends.lwjgl3.audio.OpenALAudio'` ?

If that doesn't work, you could try surrounding every single class name with quotes.

**Comment by RUSshy** [comment]
Looks like your method worked, but then i get this:

```
error: Class that is marked for delaying initialzation to runtime got initialized during image building: org.lwjgl.openal.AL$ICDStatic
Error: Image building with exit status 1
```
