### ISSUE TITLE
[GR-37503] Unable to download release sources

### ISSUE THREAD

**Issue by hgeraldino** [oracle/graal#4398]
**Describe the issue**
Once the releases were moved to https://github.com/graalvm/graalvm-ce-builds, links to the Source code downloads (both zip and tarballs) only contains the `graalvm-ce-builds` repo contents (README.md), which means it's no longer possible to download sources for a tagged release.

**Steps to reproduce the issue**
Please include both build steps as well as run steps
1. Go to the graalvm-ce-builds repo
2. Try downloading the sources for any version (e.g. https://github.com/graalvm/graalvm-ce-builds/archive/refs/tags/vm-22.0.0.2.zip)
3. Downloaded file is pretty small, and contains just the README.md file on it.

**Comment by fniephaus** [comment]
I agree this is unfortunate. Nonetheless, downloading "the sources" for a particular release isn't as simple as that: in addition to this repo, there are other repos involved (e.g., labsjdk, mx, language repos) when a GraalVM is built.

For each release, we provide corresponding tags such as https://github.com/oracle/graal/tree/vm-22.0.0.2 that you can download.

If you want to see all source versions used to generate a GraalVM, have a look at the `$GRAALVM_HOME/release` file. Here's an excerpt from the GraalVM CE 20.0.0.2 `release` file:
```
...
SOURCE=".:git:bed3a8040f46+ labsjdk-builder:be1f753b067399105cc0ddf4525e1a7a985d35a9 compiler:e7d7572e8276bc05708d48356e45b8a0978e3fa5 graal-js:cb7aaacc3a6f06481c82f6be6a974aa8aa4c66c5 java-benchmarks:e7d7572e8276bc05708d48356e45b8a0978e3fa5 regex:e7d7572e8276bc05708d48356e45b8a0978e3fa5 sdk:e7d7572e8276bc05708d48356e45b8a0978e3fa5 substratevm:e7d7572e8276bc05708d48356e45b8a0978e3fa5 sulong:e7d7572e8276bc05708d48356e45b8a0978e3fa5 tools:e7d7572e8276bc05708d48356e45b8a0978e3fa5 truffle:e7d7572e8276bc05708d48356e45b8a0978e3fa5 vm:e7d7572e8276bc05708d48356e45b8a0978e3fa5"
GRAALVM_VERSION="22.0.0.2"
...
```

According to that, https://github.com/oracle/graal/commit/e7d7572e8276bc05708d48356e45b8a0978e3fa5 but also https://github.com/oracle/graaljs/commit/cb7aaacc3a6f06481c82f6be6a974aa8aa4c66c5 were used to build the release.

However, I agree that we could add a `Based on Graal commit: https://github.com/oracle/graal/commit/e7d7572e8276bc05708d48356e45b8a0978e3fa5` notice to the GitHub releases as we already do for our dev builds (e.g., https://github.com/graalvm/graalvm-ce-dev-builds/releases/tag/22.1.0-dev-20220317_0419).

Hope this helps.

**Comment by hgeraldino** [comment]
Thanks @fniephaus for your reply.

The commit hashes from the `release` file do help. I could find tags for both oracle/graal and oracle/graaljs for version 22.0.0.2 for JDK 11 (which is the one I have currently installed). I couldn't however find a repository for labsjdk-builder. I checked the graalvm/labs-openjdk-11 but couldn't find a commit that matches the one from the `release` file, so I'm not sure if that's the correct repository.

So basically I'm trying to see if we can validate the licensing for each component that goes in the final graalvm CE. We have some tools to aid us in auditing the licensing from source files (which we've used successfully when evaluating other OpenJDK distributions), and I'm trying to figure out a way to do the same with GraalVM.

Not having a single source file is a bit inconvenient, but easy to overcome. I'll keep poking to see if I can put all pieces together.

Thanks again for your help!

**Comment by fniephaus** [comment]
`labsjdk-builder` is an internal infrastructure repository that builds a LabsJDK using `graalvm/labs-openjdk-11`, `graalvm/labs-openjdk-17`, or internal EE LabsJDK repos, which is then used as a base for a GraalVM release. As such, I don't think it contributes any code to a GraalVM distribution.

Glad I was able to help! I'm closing this issue for now, but please feel free to re-open if you have any further questions.
