### ISSUE TITLE
When config-merge-dir can not find config files it should not skip but create new files

### ISSUE THREAD

**Issue by gocursor** [oracle/graal#4401]
**Describe the issue**
When a developer starts using GraalVM java "-agentlib:native-image-agent" option on a new project it must first start with:
   -agentlib:native-image-agent=config-output-dir=META-INF/native-image
and then switch to:
   -agentlib:native-image-agent=config-merge-dir=META-INF/native-image
in order to capture all reflection/JNI/etc. usages added later.

This two-step is tedious! It would be much easier that in this case developer would just use "native-image-agent=config-merge-dir" right at the beginning. This is however not working, because GraalVM skips gathering reflection/JNI/etc. usages if no files are found in this case!

**Steps to reproduce the issue**
Start new Java project and run it with GraalVM java with option:
    -agentlib:native-image-agent=config-merge-dir=META-INF/native-image

You will get console warnings:
native-image-agent: Warning: file META-INF\native-image\jni-config.json for merging could not be found, skipping
native-image-agent: Warning: file META-INF\native-image\reflect-config.json for merging could not be found, skipping
native-image-agent: Warning: file META-INF\native-image\proxy-config.json for merging could not be found, skipping
native-image-agent: Warning: file META-INF\native-image\resource-config.json for merging could not be found, skipping
native-image-agent: Warning: file META-INF\native-image\serialization-config.json for merging could not be found, skipping
native-image-agent: Warning: file META-INF\native-image\predefined-classes-config.json for merging could not be found, skipping

and no config JSON files will be created.

I would expect that in this case new config JSON files would be created - just like with native-image-agent=config-output-dir - so that no additional step would be necessary!

**Describe GraalVM and your environment:**
 - GraalVM version: 22.0
 - JDK major version: 17
 - OS: Windows
 - Architecture: AMD64

**Comment by chirontt** [comment]
I've always used `config-merge-dir=META-INF/native-image` option, and GraalVM always creates those JSON files for me, even when the `META-INF/native-image` didn't exist in the first place. So, to me, those `skipping` output messages are irrelevant.

Honestly, I've never felt the need to use `config-output-dir=` option at all, but YMMV.

**Comment by oubidar-Abderrahim** [comment]
Hi, Actually you can use `config-merge-dir` directly from the start and it should work, it will show some warning but will work correctly. please give it a try and share with us if you found any issues

**Comment by oubidar-Abderrahim** [comment]
I'm closing this issue, if you have any more questions please feel free to reopen
