### ISSUE TITLE
Intermittent Crashes with Scalac 2.12.5 and GraalVM 22.0.0.2 Java17

### ISSUE THREAD

**Issue by jackkoenig** [oracle/graal#4406]
**Describe the issue**

Infrequent crashes with the dumped log below. The errors occur when compiling Scala code with Scalac 2.12.15 + Zinc_2.12 1.5.8. The crashes don't always seem to happen when compiling the exact same Scala code, but do appear to be consistently crashing with the same stack trace in Scalac, shown below.

**Steps to reproduce the issue**

I apologize but this issue is intermittent. It happens very infrequently when running Scalac on >100,000 lines of Scala code so I am not sure how to go about minimizing my test case. It does happen frequently enough though that it makes our internal CI flakey.

Please let me know if there are things I can try to help minimize the issue.

**Describe GraalVM and your environment:**
 - GraalVM version (latest snapshot builds can be found [here](https://github.com/graalvm/graalvm-ce-dev-builds/releases)), or commit id if built from source: CE 22.0.0.2
 - JDK major version: 17
 - OS: RHEL 8.4 (Linux)
 - Architecture: AMD64

**More details**

I've pasted an example `hs_err*.log` into a gist: https://gist.github.com/jackkoenig/a8d33176ae3fb676603fdb6053a43bef

I did lightly edit it to remove a few things as this the code being compiled is closed-source, but I don't think anything removed is relevant, it's just a wrapper around sbt zinc.

I've included the top few lines of the stack traces because those seem most relevant, but the whole thing is in the gist link above.
```
Current thread (0x00007fbb4401ffc0):  GCTaskThread "GC Thread#25" [stack: 0x00007fba982f1000,0x00007fba983f1000] [id=827682]

Stack: [0x00007fba982f1000,0x00007fba983f1000],  sp=0x00007fba983ee6d0,  free space=1013k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
V  [libjvm.so+0x728e23]  G1ParCopyClosure<(G1Barrier)0, false>::do_oop(narrowOop*)+0x63
V  [libjvm.so+0xbd9643]  OopMapSet::all_do(frame const*, RegisterMap const*, OopClosure*, void (*)(oopDesc**, derived_pointer*, OopClosure*))+0x263
V  [libjvm.so+0x696b16]  frame::oops_do(OopClosure*, CodeBlobClosure*, RegisterMap const*) const+0xb6
V  [libjvm.so+0xd91935]  JavaThread::oops_do_frames(OopClosure*, CodeBlobClosure*) [clone .part.0]+0xb5
V  [libjvm.so+0xd96933]  Threads::possibly_parallel_oops_do(bool, OopClosure*, CodeBlobClosure*)+0x173
V  [libjvm.so+0x72acc3]  G1RootProcessor::process_java_roots(G1RootClosures*, G1GCPhaseTimes*, unsigned int)+0x73
V  [libjvm.so+0x72b391]  G1RootProcessor::evacuate_roots(G1ParScanThreadState*, unsigned int)+0x61
V  [libjvm.so+0x6c27f2]  G1EvacuateRegionsTask::scan_roots(G1ParScanThreadState*, unsigned int)+0x22
V  [libjvm.so+0x6c2f93]  G1EvacuateRegionsBaseTask::work(unsigned int)+0x83
V  [libjvm.so+0xe4663f]  GangWorker::loop()+0x5f
V  [libjvm.so+0xe4669f]
V  [libjvm.so+0xd97f2e]  Thread::call_run()+0xde
V  [libjvm.so+0xbedec1]  thread_native_entry(Thread*)+0xe1

JavaThread 0x00007fbb8802c720 (nid = 827584) was being processed
Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
v  ~RuntimeStub::Stub<new_array_or_null(KlassPointer,int)Object>
J 16639 jvmci java.lang.AbstractStringBuilder.append(Ljava/lang/CharSequence;II)Ljava/lang/AbstractStringBuilder; java.base@17.0.2 (63 bytes) @ 0x00007fbb782531c5 [0x00007fbb78252c00+0x00000000000005c5]
J 47103 jvmci scala.tools.asm.Type.appendDescriptor(Ljava/lang/StringBuilder;)V (90 bytes) @ 0x00007fbb78cca1dc [0x00007fbb78cca0e0+0x00000000000000fc]
J 47161 jvmci scala.tools.asm.Type.getMethodDescriptor(Lscala/tools/asm/Type;[Lscala/tools/asm/Type;)Ljava/lang/String; (66 bytes) @ 0x00007fbb796dfee8 [0x00007fbb796dfaa0+0x0000000000000448]
J 47855 c1 scala.tools.nsc.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genInvokeDynamicLambda(Lscala/tools/nsc/transform/Delambdafy$LambdaMetaFactoryCapable;)Ljava/lang/Object; (580 bytes) @ 0x00007fbb74b21a8c [0x00007fbb74b199e0+0x00000000000080ac]
J 47481 jvmci scala.tools.nsc.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genApply(Lscala/reflect/internal/Trees$Apply;Lscala/tools/nsc/backend/jvm/BTypes$BType;)Lscala/tools/nsc/backend/jvm/BTypes$BType; (2221 bytes) @ 0x00007fbb7979028c [0x00007fbb7978e4e0+0x0000000000001dac]
```

**Comment by jackkoenig** [comment]
Using the very scientific method of just running my code over and over again and seeing how often it fails, I can confirm that this failure does **not** occur in the Java11 variant of 22.0.0.2, but it **does** still occur on the latest dev release of the Java17 variant (https://github.com/graalvm/graalvm-ce-dev-builds/releases/tag/22.1.0-dev-20220318_0752).

I will try OpenJDK next.

**Comment by oubidar-Abderrahim** [comment]
Hi, thank you for reporting this issue, we will take a look into this and get back to you

**Comment by jackkoenig** [comment]
Thanks! I did try OpenJDK Java 17.0.2 and did not notice any failures there either.

**Comment by oubidar-Abderrahim** [comment]
If the issue is still reproducible on the latest GraalVM versions, please reopen or create a new issue for it. Thank you
