### ISSUE TITLE
fatal error: java.lang.InternalError: java.lang.InternalError: Malformed class name

### ISSUE THREAD

**Issue by rtfpessoa** [oracle/graal#441]
I got this issue but I cannot understand what might be the source of it.

https://pastebin.com/6pucZWUe

Any ideas how I can further debug to understand what is causing this?

**Comment by dougxc** [comment]
This looks like something that may have already been fixed by https://github.com/oracle/graal/commit/07cb3e0b2f8b8d765ef89217a7554f8c06b65974#diff-1bac5f5761ba33975a372908063c1111

**Comment by rtfpessoa** [comment]
Thanks for the quick answer @dougxc.

Any way for me to test with that fix on Mac OS? Or even linux (I guess I could do it in a vm or docker)

**Comment by dougxc** [comment]
I don't know of an easy way to test this apart from waiting for the next GraalVM release. @vjovanov or @ansalond may know more.

**Comment by rtfpessoa** [comment]
@chrisseaton  gave me a tip to follow https://github.com/oracle/graal/tree/master/substratevm and seems to let me build `native-image`.

**Comment by rtfpessoa** [comment]
Closing this since seems fixed.
