### ISSUE TITLE
[GR-37588] Graal Updater (GU) "Error: The GraalVM directory ... is invalid"

### ISSUE THREAD

**Issue by Mukul1127** [oracle/graal#4413]
**Describe the issue**
GU doesn't work

**Steps to reproduce the issue**
Install GraalVM ??? IDK

**Describe GraalVM and your environment:**
 - GraalVM version (latest snapshot builds can be found [here](https://github.com/graalvm/graalvm-ce-dev-builds/releases)), or commit id if built from source: **[22.0.0.2]**
 - JDK major version: **[17]**
 - OS: **[Windows 10]**
 - Architecture: **[x64]**

**More details**
Add any other information about the problem here. Especially important are stack traces or log output. Feel free to link to gists or to screenshots if necessary.
```
    $ gu --version
    Error: The GraalVM directory \some\directory\GraalVM-22.0.0.2-JDK17 is invalid.
```
![Screenshot 2022-03-21 192844 1](https://user-images.githubusercontent.com/71291707/159379854-b70c7458-f0ab-4359-b65a-deecbee4cb5f.png)
![Screenshot 2022-03-21 193808 2](https://user-images.githubusercontent.com/71291707/159380259-361acd7f-8ad9-4d9b-8b0e-98111d461c9a.png)

**Comment by Ondrej-Douda** [comment]
Can you please more precisely pinpoint the build that causes this,
there are more and trying all of them would be too laborious...
Also could you share your full Path System variable..?
The way you had it installed might also help...

Maybe could you try newer version..?
This might be some old problem which is already fixed...
Thanks for collaboration...

**Comment by Mukul1127** [comment]
I'm using Oracle GraalVM Enterprise Edition 22.0.0.2 with Java 17
I used a zip to install and all other binaries work except gu.

I don't know what you mean by full system varible so here are all the varibles that are related to GraalVM:
```
(Not "C:\JDK\GraalVM-22.0.0.2-JDK17 because I moved the folder")

GRAAL_HOME = C:\GraalVM 
GRAALVM_HOME = C:\GraalVM 
JAVA_HOME = C:\GraalVM

And in Path I have: "C:\GraalVM\bin"
```

I'm on the latest version that's not dev. (22.0.0.2)
