### ISSUE TITLE
Use script engine in native-image (--no-fallback)

### ISSUE THREAD

**Issue by YU5Z8X2CvH1fv4ep** [oracle/graal#4416]
when i use js/Nashorn sciprting engine in native-image. i get error :

om.oracle.svm.core.jdk.UnsupportedFeatureError: The Nashorn scripting engine is not supported by native-image due to its use of invokedynamic.

Can I use any scripting engine(When the calling class is known)?

 Are there any ways to do it? Or a third-party tool framework?

**Comment by fniephaus** [comment]
If you want to include a JS scripting engine in a native executable, I highly recommend using Graal.js, which is compatible with GraalVM Native Image ([here's an example](https://www.graalvm.org/22.0/examples/native-image-examples/#polyglot-capabilities)). It even provides [Nashorn compatibility](https://github.com/oracle/graaljs/blob/da1d082811d4ee95cea3de7055cf951f6b731a08/docs/user/NashornMigrationGuide.md).

**Comment by YU5Z8X2CvH1fv4ep** [comment]
> If you want to include a JS scripting engine in a native executable, I highly recommend using Graal.js, which is compatible with GraalVM Native Image ([here's an example](https://www.graalvm.org/22.0/examples/native-image-examples/#polyglot-capabilities)). It even provides [Nashorn compatibility](https://github.com/oracle/graaljs/blob/da1d082811d4ee95cea3de7055cf951f6b731a08/docs/user/NashornMigrationGuide.md).
> 
> Please feel free to re-open this issue if you have further questions.

ok.thank for your answer
