### ISSUE TITLE
[BUG] - Error in Turkish locale

### ISSUE THREAD

**Issue by fmatak** [oracle/graal#4437]
The code in below line, "toUpperCase" function is causing problems because of the missing Locale parameter. In Turkish locales, this translates "i" to "İ" (I with dot) instead of "I", so it is causing very strange problems. 

https://github.com/oracle/graal/blob/f08a573c5337059379228c7df01ac4b31bdb0fa7/compiler/src/org.graalvm.compiler.replacements/src/org/graalvm/compiler/replacements/StandardGraphBuilderPlugins.java#L552

A sample problem stack trace is below:

>Caused by: java.lang.IllegalArgumentException: No enum constant org.graalvm.compiler.core.common.memory.MemoryOrderMode.ACQUİRE
	at java.base/java.lang.Enum.valueOf(Enum.java:273)
	at jdk.internal.vm.compiler/org.graalvm.compiler.core.common.memory.MemoryOrderMode.valueOf(MemoryOrderMode.java:42)
	at jdk.internal.vm.compiler/org.graalvm.compiler.replacements.StandardGraphBuilderPlugins.registerUnsafeAtomicsPlugins(StandardGraphBuilderPlugins.java:533)
	at jdk.internal.vm.compiler/org.graalvm.compiler.replacements.StandardGraphBuilderPlugins.registerUnsafePlugins(StandardGraphBuilderPlugins.java:551)
	at jdk.internal.vm.compiler/org.graalvm.compiler.replacements.StandardGraphBuilderPlugins.registerInvocationPlugins(StandardGraphBuilderPlugins.java:211)
	at jdk.internal.vm.compiler/org.graalvm.compiler.hotspot.meta.HotSpotGraphBuilderPlugins$1.run(HotSpotGraphBuilderPlugins.java:212)
	at jdk.internal.vm.compiler/org.graalvm.compiler.nodes.graphbuilderconf.InvocationPlugins.flushDeferrables(InvocationPlugins.java:977)

Notice that `MemoryOrderMode.ACQUİRE` has `İ (I with dot)` instead of `I` in the `ACQUİRE`

**Suggested fix:**

Send locale parameter to toUpperCase function: `toUpperCase( Locale.US )`

**Suggested Additional Actions:**

Make use always pass locale to toUpper / toLower and similar locale sensitive functions. 

**Temporary Workaround:**

Set JVM Locale to a non Turkish one temporarily. (ex. `java  -Duser.language=en -Duser.country=US .....` )

**Comment by rodrigar-mx** [comment]
Hi @fmatak. Thanks for reporting this issue. Do you have an example where the above stack trace is generated?

**Comment by fmatak** [comment]
Hi,

My code is pretty standard: 

`ScriptEngineManager sm = new ScriptEngineManager( ) ;`
`ScriptEngine se = sm.getEngineByName( "js" ) ;`
`se.eval( "{ java.lang.System.err.println( 'hello!!' + ' some math : ' + ( 120 * 33 ) ) ; }" ) ;`

The problem only occurs when the locale is set to Turkish, because lower case letter `i` in Turkish has a different uppercase from the English version. It is `İ` (I with dot) rather than `I`. This causes all kinds of problems in many applications when run on a computer which has Turkish locale. There are also some other locales which has similar characteristics. Therefore, it is best to not use `toUpperCase`, `toLowerCase` and similar locale sensitive functions without the `Locale` parameter.

Thank you

**Comment by rodrigar-mx** [comment]
I have reported this issue internally. Any updates we will let you know.

**Comment by dougxc** [comment]
Thanks for this report. I have a fix in the works. It would be great if you could confirm that it works for you:
[issue4437.patch.txt](https://github.com/oracle/graal/files/8416190/issue4437.patch.txt)

**Comment by fmatak** [comment]
I do not have the environment to apply this patch & compile the sources. I am using the pre-packaged jar files from maven repo. But if you can give me a jar file with the fix (or point to a url so I can download), I can test it. 
But as far as I see from your fix, you already removed the Locale sensitive code and this means testing in any locale should give identical results.

**Comment by dougxc** [comment]
Ok, thanks. I think that's sufficient confirmation for me to just integrate the fix. Please open a new issue if the problem then persists.

**Comment by fmatak** [comment]
Ok, thank you for the quick fix.

**Comment by dougxc** [comment]
Fixed in 6ffa1b6dee06e2e59eb737ad256c1c4d8e982580.
