### ISSUE TITLE
Private Java Method and Field Access

### ISSUE THREAD

**Issue by kjeet** [oracle/graal#444]
In GraalPython only public fields and methods of Java objects are accessible. Digging into the source a little bit, this seems to be enforced in the Truffle Framework, not GraalPython (see [JavaClassDesc.java](https://github.com/oracle/graal/blob/master/truffle/src/com.oracle.truffle.api.interop.java/src/com/oracle/truffle/api/interop/java/JavaClassDesc.java#L95)), so I assume this limitation applies to TruffleRuby and other polyglot languages too. 

Jython has a tremendously useful "python.security.respectJavaAccessibility = false" flag that you could pass at runtime. It was perfect when using Jython as a debug console into your running process or hack up a prototype against an existing code base.

Naturally this ability is a liability when you want to embed and isolate scripts, but so are number of capabilities. Thread creation, class loading are all guarded by flags in [Context.java](https://github.com/oracle/graal/blob/master/sdk/src/org.graalvm.polyglot/src/org/graalvm/polyglot/Context.java), what's one more?

I'm not super acquainted with the whole Truffle codebase but I'm down to take a crack at implementing it if there's interest. Who do I bug to green light this?

**Comment by chumer** [comment]
Interesting idea. no objection if it is guarded behind a flag. However I don't want to make it an access right, because I don't want to make it enabled if `allowAllAccess(true)` is set. I think this should be a debug option not for production use. I suggest  an option you can pass in like `--engine.respectHostAccessibility=false`. Not 100% certain about the option name.

**Comment by kjeet** [comment]
Sounds good. I'll whip up a first pass at it.

**Comment by yufanlu** [comment]
Is there any plan to revisit this feature?

**Comment by spavlusieva** [comment]
Hi @kjeet, this issue has been inactive for more than 180 days. We’ll close it to focus on current issues. In case it’s still relevant, please reopen it and we’ll take another look. Thank you!
