### ISSUE TITLE
Error when reusing Engine across multiple Contexts

### ISSUE THREAD

**Issue by contrapost** [oracle/graal#4475]
**Describe GraalVM and your environment :**
 - GraalVM version or commit id if built from source: **21.2.0**
 - CE or EE: **CE**
 - JDK version: **JDK11**
 - OS and OS Version: **macOS Monterey 12.2.1**
 - Architecture: **amd64**
 - The output of `java -Xinternalversion`:
```
 **OpenJDK 64-Bit Server VM (11.0.11+9-LTS) for bsd-amd64 JRE (Zulu11.48+21-CA) (11.0.11+9-LTS), built on Apr  4 2021 08:04:15 by "zulu_re" with gcc 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.2)**
```

**Have you verified this issue still happens when using the latest snapshot?** YES

**Describe the issue**
We reuse one instance of Engine across multiple Contexts. Upgrade form GraalVM 21.1.0 to 21.2.0 causes failure of some of our concurrent tests (see stacktrace in the thread).
The method call that results in the assertion error is:
```Java
public <T> T as(TypeLiteral<T> targetType) {
    Objects.requireNonNull(targetType, "targetType");
    return dispatch.as(this.context, receiver, targetType);
}
```
The error is located in PolyglotList$Cache.lookup :
```Java
assert cache.valueType == valueType;
```
Calling overload version of as method:
```Java
public <T> T as(Class<T> targetType) throws ClassCastException, IllegalStateException, PolyglotException {
    Objects.requireNonNull(targetType, "targetType");
    if (targetType == Value.class) {
        return (T) this;
    }
    return dispatch.as(this.context, receiver, targetType);
}
```
doesn’t cause the above mentioned problem.

**Code snippet or code repository that reproduces the issue**
```Kotlin
// Context setup
private val hostAccess = HostAccess
        .newBuilder()
        .allowListAccess(true)
        .targetTypeMapping(
            Value::class.java, Any::class.java,
            { v -> v.hasArrayElements() },
            { v -> transformArray(v) }
        ).build()

private val engine = Engine
        .newBuilder()
        .option("js.experimental-foreign-object-prototype", "true")
        .allowExperimentalOptions(true)
        .build()

fun getContext(): Context =
        Context
            .newBuilder()
            .engine(engine)
            .allowHostAccess(hostAccess)
            .build()

fun <T> useContext(execution: (Context) -> T): T =
        getContext().use(execution)

// Util functions
fun <T> Context.evalSource(source: Source, type: TypeLiteral<T>): T {
    return eval(source).`as`(type)
}

fun <T> Context.evalJs(script: String, type: TypeLiteral<T>): T {
    return eval(JsonMapGraalContextFactory.jsLanguageId, script).`as`(type)
}

// Tests
@Test
    fun testOne() {
        useContext { context ->
            val source = Source
                .newBuilder("js", "[1 == 1]", "evalSource_convertableValueWithType")
                .build()
            assertThat(context.evalSource(source, object : TypeLiteral<List<Boolean>>() {})).containsExactly(true)
        }
    }

@Test
    fun testTwo() {
        useContext { context ->
            assertThat(context.evalJs("[1 == 1]", object : TypeLiteral<List<Boolean>>() {})).containsExactly(true)
        }
    }
```

**Steps to reproduce the issue**
Please include both build steps as well as run steps
1. set up GraalVM version 21.1.0
2. run tests
3. change GraalVM version to 21.2.0
4. run tests

**Expected behavior**
Expect the tests to run without failure regardless to the GraalVM version.

**Additional context**
<details><summary>Details</summary>

```
    org.graalvm.polyglot.PolyglotException: java.lang.AssertionError

	at com.oracle.truffle.polyglot.PolyglotList$Cache.lookup(PolyglotList.java:180)
	at com.oracle.truffle.polyglot.PolyglotList.<init>(PolyglotList.java:73)
	at com.oracle.truffle.polyglot.PolyglotList.create(PolyglotList.java:96)
	at com.oracle.truffle.polyglot.PolyglotHostAccess.toList(PolyglotHostAccess.java:107)
	at com.oracle.truffle.host.HostToTypeNode.asJavaObject(HostToTypeNode.java:384)
	at com.oracle.truffle.host.HostToTypeNode.convertImpl(HostToTypeNode.java:194)
	at com.oracle.truffle.host.HostToTypeNode.doCached(HostToTypeNode.java:118)
	at com.oracle.truffle.host.HostToTypeNodeGen.executeAndSpecialize(HostToTypeNodeGen.java:91)
	at com.oracle.truffle.host.HostToTypeNodeGen.execute(HostToTypeNodeGen.java:50)
	at com.oracle.truffle.host.HostLanguageService.toHostType(HostLanguageService.java:117)
	at com.oracle.truffle.polyglot.PolyglotToHostNode.doDefault(PolyglotToHostNode.java:59)
	at com.oracle.truffle.polyglot.PolyglotToHostNodeGen.executeAndSpecialize(PolyglotToHostNodeGen.java:44)
	at com.oracle.truffle.polyglot.PolyglotToHostNodeGen.execute(PolyglotToHostNodeGen.java:30)
	at com.oracle.truffle.polyglot.PolyglotValueDispatch$InteropValue$AsTypeLiteralNode.executeImpl(PolyglotValueDispatch.java:3100)
	at com.oracle.truffle.polyglot.HostToGuestRootNode.execute(HostToGuestRootNode.java:125)
	at org.graalvm.polyglot.Value.as(Value.java:1520)
```
</details>

**Comment by oubidar-Abderrahim** [comment]
Hi, thank you for reporting this we will take a look into it and get back to you

**Comment by oubidar-Abderrahim** [comment]
Is there a reason why your `java -Xinternalversion` doesn't point to GraalVM? also 21.2.0 is almost a year old, could you please try with 21.3.2 and let us know if the issue is still occurring.

**Comment by contrapost** [comment]
1. We depend on GC that is not available in GraalVM Community
2. I got the same results when running tests with GraalVM 22.1.0

**Comment by oubidar-Abderrahim** [comment]
Could you please share the full example to reproduce the issue with the steps to reproduce (command used)?

**Comment by contrapost** [comment]
@oubidar-Abderrahim , [here](https://github.com/utilihive/graal-engin-reusing-error-example/blob/main/src/test/kotlin/ExampleTest.kt) is the test that fail when run together. 
The prod code can be found [here](https://github.com/utilihive/graal-engin-reusing-error-example/blob/main/src/main/kotlin/Util.kt).

**Comment by dimple1024** [comment]
Hello , I have a similar use case , just wanted to understand if this issue is fixed or still open? Also I have to use graalvm with jdk8 , and I will be using graalvm 21.3.0 [https://www.graalvm.org/release-notes/21_3/#platform-updates]

**Comment by oubidar-Abderrahim** [comment]
Hi @dimple1024 , please use GraalVM 21.3.5 as this is the latest version for GraalVM21.
If you still face the issue, please share with us a reproducer with detailed steps on how to reproduce and we can take a look into it.

**Comment by contrapost** [comment]
@oubidar-Abderrahim, can I assume based on your last answer that the issue is solved?

**Comment by oubidar-Abderrahim** [comment]
We will know once we get the result from testing with v21.3.5

**Comment by oubidar-Abderrahim** [comment]
If this issue is still reproducible on our latest builds, please reopen or create a new issue. Thank you
