### ISSUE TITLE
ElfDynamicSection.addressToOffset: sections without a meaningful address aren't ignored.

### ISSUE THREAD

**Issue by eddyb** [oracle/graal#4478]
This method tries to map a relative (virtual) address to a file offset:
https://github.com/oracle/graal/blob/8b10078d06c9bfb4047180ccc4ebc85c3e3bb7f5/sulong/projects/com.oracle.truffle.llvm.parser/src/com/oracle/truffle/llvm/parser/elf/ElfDynamicSection.java#L89-L98

It's specifically used to find the `DT_STRTAB` section (aka `.dynstr`):
https://github.com/oracle/graal/blob/8b10078d06c9bfb4047180ccc4ebc85c3e3bb7f5/sulong/projects/com.oracle.truffle.llvm.parser/src/com/oracle/truffle/llvm/parser/elf/ElfDynamicSection.java#L73

AFAICT there are two issues with the current implementation:
1. ideally `PT_LOAD` segments in the ELF program headers should be used for this purpose - they indicate to a loader how the file maps into memory, and all of the `PT_DYNAMIC`/`DT_*` information is relative to that
    * I believe that the only reason Truffle might look at the section table is to access `.llvmbc`, which doesn't have a program header of its own
2. sections without the `A`(lloc) flag don't have an address (and the field is `0` but doesn't mean "address `0`"), but may have a non-trivial size (especially `.llvmbc`), which can cause false positives in the range comparison

As an example, here are the `.dynstr` and `.llvmbc` sections from a copy of `ruby/lib/mri/openssl.so`:
```
Name              Type            Address          Off    Size   ES Flg Lk Inf Al
.dynstr           STRTAB          0000000000007e34 007e34 004e10 00   A  0   0  1
.llvmbc           PROGBITS        0000000000000000 0804e7 24f704 00      0   0  1
```
You can see that the entirety of `.dynstr` is within `.llvmbc`'s "address" range.

And if `.llvmbc` gets picked, `DT_RUNPATH`/`DT_NEEDED` strings will be random, causing very strange loading errors (usually with invalid UTF-8 and/or random characters like `Aﾟ\ﾺ\ﾺP#`).

The only reason this hasn't caused more issues until now is that the section table ordering happens to have `.llvmbc` late enough to not be hit by the loop in the first place.

However, tools like [`patchelf`](https://github.com/NixOS/patchelf) may reorder the section table without breaking any ELF loaders that rely on `PT_LOAD`.
In the case of `ruby/lib/mri/openssl.so`, this command (needed to fix `DT_NEEDED` names) causes a reorder:
```
patchelf openssl.so --replace-needed libssl.so.10 libssl.so --replace-needed libcrypto.so.10 libcrypto.so
```

I don't have a more thorough reproduction right now, but I wanted to submit my notes so far, having looked into this because @solson hit it while testing `truffleruby` on NixOS (which uses `patchelf` to fix up binaries meant for other Linux distributions - for a dylib that means tweaking `DT_RUNPATH` and/or `DT_NEEDED` entries, usually).

**Comment by oubidar-Abderrahim** [comment]
Hi, thank you for reporting this we will take a look into it and get back to you
