### ISSUE TITLE
Is it possible to use Graal Python on Windows?

### ISSUE THREAD

**Issue by Daniel-Alievsky** [oracle/graal#4483]
Hello! 

I would like to integrate Java and Python using GraalVM, how it is written here:
https://medium.com/graalvm/supercharge-your-java-apps-with-python-ec5d30634d18
To do this, I need GraalVM with Python installed on my computer. I've found your instruction:
https://www.graalvm.org/python/quickstart/
According the instruction, I downloaded the latest Windows build from here
https://github.com/graalvm/graalvm-ce-builds/releases
It is graalvm-ce-java17-windows-amd64-22.0.0.2.zip
Then, according the instruction, I tried to call
gu install python
gu install llvm-toolchain
Results:
...
Error: Unknown component: python
Error: Unknown component: llvm-toolchain
...
Really, gu available command shows only 4 components, and python is not included. I tried several other version of GraalVM, including graalvm-ce-java17-windows-amd64-dev.zip, but results are the same.

Does it mean that currently impossible to use Graal Python on Windows? If yes, when, approximately, are you planning to support Python for Windows? Are there some other ways to install Graal Python today, maybe more complex, but working right now?

**Comment by oubidar-Abderrahim** [comment]
Hi,

> Does it mean that currently impossible to use Graal Python on Windows?

Yes, GraalPython is not supported on Windows

> If yes, when, approximately, are you planning to support Python for Windows?

We don't have a specific date yet. There are many issues that need to be fixed to make Truffle, and GraalPython, work on Windows.

> Are there some other ways to install Graal Python today, maybe more complex, but working right now?

Unfortunately, I don't believe there is a way currently to have GraalPython installed and working for Windows platforms

**Comment by Daniel-Alievsky** [comment]
> We don't have a specific date yet.
Ok, but at least very roughly: are we talking about this year, or will we have to wait many years?

**Comment by Daniel-Alievsky** [comment]
I know another way of good integration Java+Python - Jython. But it works only with very deprecated and not supported Python 2. Maybe you know some other ways?

**Comment by Daniel-Alievsky** [comment]
Also, if I can ask this here - it is important for me and I cannot test it quickly.

I need not only integration Java and Python. I need, in Python part, to use external native libraries like numpy, opencv-python etc. Jython does not support this ability (cannot load .pyd files). 

Is this possible in GraalPython? Is it possible, in GraalVM, to call python module, that uses numpy, from Java code?

**Comment by Daniel-Alievsky** [comment]
Thank you very much!

**Comment by Daniel-Alievsky** [comment]
If possible, let me ask once again.
Are you planning to support other OS, besides Linux, MacOS, Windows, Docker container? In particular, what about Android, iPadOS  and other variants for mobile devices? Today they are powerful enough.

**Comment by oubidar-Abderrahim** [comment]
In the meantime, we do not have plans for supporting other OS besides what we already support, the latest addition to our supported OS is macOS aarch64 (new M1 machines) which is still experimental but the first release will be available today or tomorrow for testing. We might add more OS in the future, but that's a decision that still needs to be taken first.
For Mobile OS, there is an effort made by gluonhq (https://gluonhq.com/) to make native-image available for Android and IOS (https://github.com/gluonhq/substrate), I'm not sure if only native-image was adopted or also the polyglot platform, but it might be worth checking.
