### ISSUE TITLE
Graal CE slower than c1/c2 for factorial

### ISSUE THREAD

**Issue by stephanfrind** [oracle/graal#449]
# graal seems to produce code for a factorial example that is slower than normal jit

It takes 2x longer to compute a factorial if graal is used.

I used
java version "10.0.1" 2018-04-17
Java(TM) SE Runtime Environment 18.3 (build 10.0.1+10)
Java HotSpot(TM) 64-Bit Server VM 18.3 (build 10.0.1+10, mixed mode)
on windows 10

# use graal within jvm
export JAVA_TOOL_OPTIONS="-XX:+UnlockExperimentalVMOptions -XX:+EnableJVMCI -XX:+UseJVMCICompiler -XX:+UseParallelGC -Xmx2G -Xms2G"
java -jar factorial.jar 10000
factorial(10000) bitlength 118459
computation time 228599 ms

# use the current graal from github
export JAVA_TOOL_OPTIONS="--module-path=/C/temp/graalsf/data/org.graalvm.graal_sdk.jar --upgrade-module-path=/C/temp/graalsf/data/jdk.internal.vm.compiler.jar -XX:+UnlockExperimentalVMOptions -XX:+EnableJVMCI -XX:+UseJVMCICompiler -XX:+UseParallelGC -Xmx2G -Xms2G"
java -jar factorial.jar 10000
factorial(10000) bitlength 118459
computation time 171334 ms

# use standard jit
export JAVA_TOOL_OPTIONS="-XX:+UseParallelGC -Xmx2G -Xms2G"
java -jar factorial.jar 10000
factorial(10000) bitlength 118459
computation time 85426 ms

# test code

        private static final BigInteger MINUS_ONE = BigInteger.ONE.negate();
	
	private static BigInteger factorialTail(BigInteger aNumber, BigInteger anAccu) {
		if (BigInteger.ZERO.equals(aNumber)) {
			return anAccu;
		}
		return factorialTail(aNumber.add(MINUS_ONE), aNumber.multiply(anAccu));
	}
	
	private static BigInteger factorial(BigInteger aNumber) {
		return factorialTail(aNumber, BigInteger.ONE);
	}
	
	private static void printAndEval(BigInteger aNumber) {
		// warm up
		BigInteger tempResult = factorial(aNumber);
		
		long t1 = System.nanoTime();
		tempResult = factorial(aNumber);
		long t2 = System.nanoTime();
		System.out.println("factorial(" + aNumber + ") bitlength " + tempResult.bitLength());
		System.out.println("computation time " + ((t2-t1) / 1_000) + " ms");
	}

**Comment by dougxc** [comment]
Hi @stephanfrind , thanks for the report. Do you see the same slow down when comparing stock JDK8 with GraalVM CE or GraalVM EE? Juts trying to narrow down whether this a Graal issue or a JDK10 issue.

**Comment by stephanfrind** [comment]
I have tried it on graalvm-0.30.2-linux-amd64-jdk8.tar.gz

bash-4.2# java -version
java version "1.8.0_151"
Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.71-b01-internal-jvmci-0.38, mixed mode)

bash-4.2# java -XX:-UseJVMCICompiler -jar factorial.jar 10000
factorial(10000) bitlength 118459
computation time 36621 ms

bash-4.2# java -XX:+UseJVMCICompiler -jar factorial.jar 10000
factorial(10000) bitlength 118459
computation time 143018 ms

Here the slowdown with graal is even worse (old graal version).
Hope it helps somehow.

**Comment by chumer** [comment]
Please note that its not 36621 ms but 36621 µs. So it is likely that Graal was not compiling yet. Still the difference should not be this significant if Graal is enabled.

**Comment by stephanfrind** [comment]
I have changed the warmup to 
		int i = 100;
		while (i-- > 0) {
			tempResult = factorial(aNumber);
		}
and fixed the computation time. Sorry for confusion.

result: 
 code is slower

graal seems to compile it because -X:+PrintCompilation  shows
    343  252       3       de.frind.test.Factorial::factorialTail (28 bytes)

Picked up JAVA_TOOL_OPTIONS: --module-path=/C/temp/graalsf/data/org.graalvm.graal_sdk.jar --upgrade-module-path=/C/temp/graalsf/data/jdk.internal.vm.compiler.jar -XX:+UnlockExperimentalVMOptions -XX:+EnableJVMCI -XX:+UseJVMCICompiler -XX:+UseParallelGC -Xmx2G -Xms2G
factorial(10000) bitlength 118459
computation time 42.1967 ms

Picked up JAVA_TOOL_OPTIONS: -XX:+UseParallelGC -Xmx2G -Xms2G
factorial(10000) bitlength 118459
computation time 28.1957 ms

**Comment by dougxc** [comment]
Ok, thanks, I'll investigate further.

**Comment by mukel** [comment]
You are using `graal-ce` bundled with OpenJDK which can be a bit outdated.
The main issue here seems to be warmup; Graal takes more time to warmup than Hotspot; with proper warmup I managed to get within 10% of Hotspot with `graal-enterprise` and within 30% with `graal-ce` on the latest `1.0.0-rc2`. Hotspot is still faster but not 2x faster.

We are working on `libgraal`; an AOT version of Graal that should make Graal and Hotspot even in terms of warmup time.
In this particular case Hotspot is faster, but this is not always the case.

**Comment by dougxc** [comment]
@mukel , can you please show @stephanfrind how you implemented proper warmup.

**Comment by mukel** [comment]
With Graal enabled, `-XX:+PrintCompilation` shows that Graal is also being compiled; this is the overhead `libgraal` aims to remove.

Proper warmup means making sure the method is hot; but how many hits? 100? 1000?

The **proper** way is to use [JMH](http://openjdk.java.net/projects/code-tools/jmh/), and even JMH can be outsmarted by Graal (see #402).
Check Shipilev's [Nanotrusting the Nanotime](https://shipilev.net/blog/2014/nanotrusting-nanotime/) for a rationale.

```java
package graal.benchmarks;

import java.math.BigInteger;
import org.openjdk.jmh.annotations.*;
import org.openjdk.jmh.infra.Blackhole;
import java.util.concurrent.TimeUnit;

public class GH_449 {

    private static final BigInteger MINUS_ONE = BigInteger.ONE.negate();

    private static BigInteger factorialTail(BigInteger aNumber, BigInteger anAccu) {
        if (BigInteger.ZERO.equals(aNumber)) {
            return anAccu;
        }
        return factorialTail(aNumber.add(MINUS_ONE), aNumber.multiply(anAccu));
    }

    private static BigInteger factorial(BigInteger aNumber) {
        return factorialTail(aNumber, BigInteger.ONE);
    }

    @Benchmark
    @BenchmarkMode(Mode.AverageTime)
    @OutputTimeUnit(TimeUnit.MICROSECONDS)    
    public void testFactorial(Blackhole bh) {
        bh.consume(factorial(BigInteger.valueOf(10000)));
    }
}
```

`OpenJDK 10.0.1`
```
# Warmup Iteration   1: 27576.399 us/op
# Warmup Iteration   2: 26942.649 us/op
# Warmup Iteration   3: 27046.848 us/op
```
`graal-ee-1.0.0-rc2`
```
# Warmup Iteration   1: 32941.344 us/op
# Warmup Iteration   2: 27394.534 us/op
# Warmup Iteration   3: 27572.874 us/op
```
Each iteration runs for 10s with a clear difference in warmup time/overhead.
Graal lags a bit, but then stabilizes; Hotspot is fast from iteration 1.

JMH results for different configurations:
```
OpenJDK 10.0.1           27139.852 ±(99.9%) 201.901 us/op
graal-ee-1.0.0-rc2       27394.071 ±(99.9%) 170.567 us/op
graal-ce-1.0.0-rc2       35551.615 ±(99.9%) 177.068 us/op
graal-ce OpenJDK 10.0.1  38054.335 ±(99.9%) 118.110 us/op
```

`graal-ce-1.0.0-rc2` shows some nice improvement over the one bundled with `OpenJDK 10.0.1` .
`graal-ee-1.0.0-rc2` and vanilla OpenJDK 10.0.1 are pretty similar.

```bash
#!/bin/sh
mvn clean install
~/graal/graalvm-ce-1.0.0-rc2/bin/java -XX:+UseParallelGC -Xmx2G -Xms2G -Xss4m -jar target/benchmarks.jar GH_449
~/graal/graalvm-ee-1.0.0-rc2/bin/java -XX:+UseParallelGC -Xmx2G -Xms2G -Xss4m -jar target/benchmarks.jar GH_449
java -XX:+UseParallelGC -Xmx2G -Xms2G -Xss4m -jar target/benchmarks.jar GH_449
java -XX:+UnlockExperimentalVMOptions -XX:+EnableJVMCI -XX:+UseJVMCICompiler -XX:+UseParallelGC -Xmx2G -Xms2G -Xss4m  -jar target/benchmarks.jar GH_449
```

**Comment by stephanfrind** [comment]
Thank's a lot for pointing me at JMH.
I did measure your Benchmark GH_449 with Oracle java 10 (build 10.0.1+10,), JMH 1.19 and Graal head version from git repo.
I used 50 warm up iterations in order to avoid to measure graal compiling itself. I checked that with a run with `-XX:+PrintCompilation` and saw that within the first 30 warm up cycles Graal compiled itself too.
In order to measure code generated by graal I switched off TieredCompilation.

Graal head version from git repo
`export JAVA_TOOL_OPTIONS="--module-path=/C/temp/graalsf/data/org.graalvm.graal_sdk.jar --upgrade-module-path=/C/temp/graalsf/data/jdk.internal.vm.compiler.jar -XX:-TieredCompilation -XX:+UnlockExperimentalVMOptions -XX:+EnableJVMCI -XX:+UseJVMCICompiler -XX:+UseParallelGC -Xss4m -Xmx2G -Xms2G"`

`34391,457 ¦(99.9%) 900,198 us/op [Average]`


Standard JDK
`export JAVA_TOOL_OPTIONS="-XX:+UseParallelGC -Xmx2G -Xms2G"`

`24508,459 ¦(99.9%) 621,751 us/op [Average]`

Result: Benchmark GH_449 took with graal about 1.4x longer than with standard jit

**Comment by dougxc** [comment]
Thanks for confirming the results @stephanfrind . It's also nice to see that Graal EE is on par with the standard JDK. I suspect the inlining algorithm in EE makes the difference here (compared to CE).
Please re-open if you have further questions.
