### ISSUE TITLE
GroovySubstitutions fails with groovy 4

### ISSUE THREAD

**Issue by JnRouvignac** [oracle/graal#4492]
**Describe the issue**
Upgrading groovy 3 to the newly released [groovy 4](https://groovy-lang.org/releasenotes/groovy-4.0.html) made native-image build fail with the following error: `Error: Could not find target method: protected static void com.oracle.svm.polyglot.groovy.Target_org_codehaus_groovy_vmplugin_v7_IndyInterface_invalidateSwitchPoints.invalidateSwitchPoints()`

**Steps to reproduce the issue**

**Describe GraalVM and your environment:**
 - GraalVM version: tested with 
``` 
 $ java -version
openjdk version "11.0.9" 2020-10-20
OpenJDK Runtime Environment GraalVM CE 20.3.0 (build 11.0.9+10-jvmci-20.3-b06)
OpenJDK 64-Bit Server VM GraalVM CE 20.3.0 (build 11.0.9+10-jvmci-20.3-b06, mixed mode, sharing)
```
and:
```
$ java -version
openjdk version "11.0.14" 2022-01-18
OpenJDK Runtime Environment GraalVM CE 22.0.0.2 (build 11.0.14+9-jvmci-22.0-b05)
OpenJDK 64-Bit Server VM GraalVM CE 22.0.0.2 (build 11.0.14+9-jvmci-22.0-b05, mixed mode, sharing)
```
 - JDK major version: 11
 - OS: linux
 - Architecture: AMD64

**More details**
I saw that, while groovy 3 had `IndyInterface.invalidateSwitchPoints()`, groovy 4 does not have this method. These two commits removed it:

* GROOVY-9380: VMPlugin refactor: Coalesce Java5 through Java7 into Java8
    * https://github.com/apache/groovy/commit/6e10c35b7fdc7c6b213372d7fa771f723ca5906a
    * removes `org.codehaus.groovy.vmplugin.v7.IndyInterface` class
* GROOVY-10465: Consolidation of VMPlugin didn't account for API calls in the Groovy runtime
    * https://github.com/apache/groovy/commit/cc1113390f8d93a382d7559cebd1518b4fe79deb
    * adds back `org.codehaus.groovy.vmplugin.v7.IndyInterface` class, but without the `invalidateSwitchPoints()` method this time.

Here is the stack trace reported by the compiler:
```
15:41:32  Error: Could not find target method: protected static void com.oracle.svm.polyglot.groovy.Target_org_codehaus_groovy_vmplugin_v7_IndyInterface_invalidateSwitchPoints.invalidateSwitchPoints()
15:41:32  com.oracle.svm.core.util.UserError$UserException: Could not find target method: protected static void com.oracle.svm.polyglot.groovy.Target_org_codehaus_groovy_vmplugin_v7_IndyInterface_invalidateSwitchPoints.invalidateSwitchPoints()
15:41:32  	at com.oracle.svm.core.util.UserError.abort(UserError.java:68)
15:41:32  	at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.findOriginalMethod(AnnotationSubstitutionProcessor.java:711)
15:41:32  	at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.handleMethodInAliasClass(AnnotationSubstitutionProcessor.java:365)
15:41:32  	at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.handleAliasClass(AnnotationSubstitutionProcessor.java:337)
15:41:32  	at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.handleClass(AnnotationSubstitutionProcessor.java:309)
15:41:32  	at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.init(AnnotationSubstitutionProcessor.java:265)
15:41:32  	at com.oracle.svm.hosted.NativeImageGenerator.createDeclarativeSubstitutionProcessor(NativeImageGenerator.java:921)
15:41:32  	at com.oracle.svm.hosted.NativeImageGenerator.setupNativeImage(NativeImageGenerator.java:855)
15:41:32  	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:556)
15:41:32  	at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:471)
15:41:32  	at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
15:41:32  	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
15:41:32  	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
15:41:32  	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
15:41:32  	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
15:41:32  	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

**Comment by oubidar-Abderrahim** [comment]
Hi, Thank you for reporting this we will take a look into it and get back to you. In the meantime, could you please share the steps to reproduce this issue locally?

**Comment by Torbuntu** [comment]
I ran into this as well.

**Environment:**
- Linux, Fedora Silverblue x86_64
- Groovy version: 4.0.2, JVM: 17.0.3 Vendor: GraalVM Community OS: Linux
```
]$ java --version
openjdk 17.0.3 2022-04-19
OpenJDK Runtime Environment GraalVM CE 22.1.0 (build 17.0.3+7-jvmci-22.1-b06)
OpenJDK 64-Bit Server VM GraalVM CE 22.1.0 (build 17.0.3+7-jvmci-22.1-b06, mixed mode, sharing)
```

**Steps to reproduce:**
- Copy the `gttp.groovy` source from [github/wololock/gttp](https://github.com/wololock/gttp/blob/master/gttp.groovy)
- Compile with `groovyc --compile-static gttp.groovy` 
- Generate configuration with `java -agentlib:native-image-agent=config-output-dir=conf/ -cp .:$GROOVY_HOME/lib/groovy-4.0.2.jar gttp`
- Attempt native-image: `native-image --allow-incomplete-classpath --report-unsupported-elements-at-runtime --initialize-at-build-time --no-fallback --no-server -H:ConfigurationFileDirectories=conf -H:+ReportExceptionStackTraces -cp .:$GROOVY_HOME/lib/groovy-4.0.2.jar gttp`

Results in the same stacktrace as original issue post. 

If there is any other debugging I can try to provide more/better information please let me know.

**Comment by linghengqian** [comment]
- I have to point to something like https://github.com/oracle/graal/blob/vm-ce-22.1.0/substratevm/src/com.oracle.svm.polyglot/src/com/oracle/svm/polyglot/groovy/GroovySubstitutions.java , it is unreasonable for classes like  to not convert `org.codehaus.groovy` namespace to `org.apache.groovy`, which blocks all Groovy 4 applications. 

- In addition, the ability to `generate classic call-site based bytecode` has been removed in Groovy 4, and currently there is only `bytecode targeting the JDK7+ invoke dynamic ("indy") bytecode instructions`.

**Comment by Torbuntu** [comment]
Just confirming that upgrading to the new 4.0.3 version has resolved the issue and I was able to successfully generate a native image!

**Comment by JnRouvignac** [comment]
Thanks for fixing this @paulk-asert, and thanks for confirming this is fixed @Torbuntu !

I am now closing this issue.
The problem existed from groovy 4.0.0 to 4.0.2 included.
Groovy 4.0.3 made a change to its code that fixes this problem.
