### ISSUE TITLE
[Android] tmp dir on Android is wrongly set to /tmp using GraalVM/JDK17

### ISSUE THREAD

**Issue by jperedadnr** [oracle/graal#4497]
**Describe the issue**

Creating a native-image for Android using any recent GraalVM version (like 22.0.0.2 or the latest dev), with JDK17, works almost the same as with JDK11. However there is an issue with the tmp dir: it is set to `/tmp`, and that doesn't exist.

With JDK17+, `Target_jdk_internal_util_StaticProperty` calls:
```
    @Substitute
    @TargetElement(onlyWith = JDK17OrLater.class)
    private static String javaIoTmpDir() {
        return ImageSingletons.lookup(SystemPropertiesSupport.class).javaIoTmpDir();
    }
```
that in turns calls `LinuxSystemPropertiesSupport`:
```
public class LinuxSystemPropertiesSupport extends PosixSystemPropertiesSupport {

    @Override
    protected String javaIoTmpdirValue() {
        /*
         * The initial value of `java.io.tmpdir` is hard coded in libjava when building the JDK. So
         * to be completely correct, we would have to use the value from libjava, but since it is
         * normally initialized to `/tmp` via `P_tmpdir`, this should be fine for now.
         */
        return "/tmp";
    }
```

This works on Linux, but not when building a native image for Android on Linux. 
When running on Android: `/tmp` doesn't exist and typically, `java.io.tmpdir` is set from the [main activity](https://github.com/gluonhq/substrate/blob/master/src/main/resources/native/android/android_project/app/src/main/java/com/gluonhq/helloandroid/MainActivity.java#L129) (before launching the native image) via `getApplicationInfo().dataDir`. However, setting `java.io.tmpDir` now doesn't have any effect.

**Steps to reproduce the issue**

On Linux, modify the [HelloWorld](https://github.com/gluonhq/gluon-samples/tree/master/HelloWorld) main class:

```
package hello;

import java.io.IOException;
import java.nio.file.Files;

public class HelloWorld {

    public static void main(String[] args) {
        System.out.println("Hello World!!");
        try {
            Files.createTempFile("+JXF", ".tmp").toFile();
        } catch (IOException e) {
            e.printStackTrace();
        }
        System.exit(0);
    }

}
```

set  `GRAALVM_HOME` to latest snapshot build with JDK 17.
Connect an Android device, build and deploy with:
`mvn -Pandroid gluonfx:build gluonfx:package gluonfx:install gluonfx:nativerun`

The following exception is shown:
```
D/GraalCompiled(12012): Hello World!!
D/GraalCompiled(12012): java.nio.file.NoSuchFileException: /tmp/+JXF12661050881669947642.tmp
D/GraalCompiled(12012):     at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:218)
D/GraalCompiled(12012):     at java.nio.file.Files.newByteChannel(Files.java:380)
D/GraalCompiled(12012):     at java.nio.file.Files.createFile(Files.java:658)
D/GraalCompiled(12012):     at java.nio.file.TempFileHelper.create(TempFileHelper.java:136)
D/GraalCompiled(12012):     at java.nio.file.TempFileHelper.createTempFile(TempFileHelper.java:159)
D/GraalCompiled(12012):     at java.nio.file.Files.createTempFile(Files.java:923)
D/GraalCompiled(12012):     at hello.HelloWorld.main(HelloWorld.java:37)
```

Note that using JDK11, this would work, and the file would be: `/data/user/0/com.gluonhq.samples.helloworld/+JXF12661050881669947642.tmp`

For reference, for macOS and iOS, the per-user temp folder is [not hardcoded](https://github.com/oracle/graal/blob/master/substratevm/src/com.oracle.svm.core.posix/src/com/oracle/svm/core/posix/darwin/DarwinSystemPropertiesSupport.java#L51), and it works fine with JDK17+, giving for instance:
`/var/folders/zx/s6qr37tn5l98xzzsxttp9lph0000gn/T/+ JXF12661050881669947642.tmp` (macOS)
`/private/var/mobile/Containers/Data/Application/84DB0584-1F14-4C51-905E-38FA109B097A/tmp/+ JXF12661050881669947642.tmp` (iOS)

This is not a minor issue, as many libraries rely on the temporary directory to perform internal operations (for instance, JavaFX [loads](https://github.com/openjdk/jfx/blob/master/modules/javafx.graphics/src/main/java/com/sun/javafx/font/FontFileWriter.java#L90) to the tmpDir the user fonts). 

**Describe GraalVM and your environment:**
 - GraalVM version: **[[22.2.0-dev-20220415_1945]](https://github.com/graalvm/graalvm-ce-dev-builds/releases/download/22.2.0-dev-20220415_1945/graalvm-ce-java17-linux-amd64-dev.tar.gz)**
 - JDK major version: **17**
 - OS: **Linux**
 - Architecture: **AMD64, but building for Android AArch64**

**Comment by oubidar-Abderrahim** [comment]
Hi, thank you for reporting this, I believe this issue is more related to gluonhq/substrate than GraalVM, as GraalVM currently does not support Android
