### ISSUE TITLE
[native-image] allPublicMethods does not include constructors

### ISSUE THREAD

**Issue by vlsi** [oracle/graal#450]
https://github.com/oracle/graal/blob/079591ab18a5694a8ba5cf630ed4f76d3442fe21/substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/config/ReflectionConfigurationParser.java#L154-L155

It is somewhat confusing that `allPublicMethods` does not include `public <init>`.
I think it should either include the constructors or `allPublicConstructors` option should be created.

**Comment by cstancu** [comment]
@vlsi that's a good point. Thanks for reporting. I will add options for `allPublicConstructors` and `allDeclaredConstructors`:
```
            } else if (name.equals("allDeclaredConstructors")) {
                if (asBoolean(value, "allDeclaredConstructors")) {
                    registry.register(clazz.getDeclaredConstructors());
                }
            } else if (name.equals("allPublicConstructors")) {
                if (asBoolean(value, "allPublicConstructors")) {
                    registry.register(clazz.getConstructors());
            }
```
I think it is better to have a finer granularity.

**Comment by cstancu** [comment]
Issue is fixed in https://github.com/oracle/graal/commit/59fc579975dac729c90dc00cbcf29121534dac13. Please [build from source](https://github.com/oracle/graal/tree/master/substratevm#quick-start) to get the latest fixes.
