### ISSUE TITLE
native-image `@argfile` parse failure on Windows with the error `Fatal error: Unsupported OptionOrigin`

### ISSUE THREAD

**Issue by imkiva** [oracle/graal#4502]
## **Describe the issue**

The `@argfile` option of native-image show `Fatal error: Unsupported OptionOrigin: <the arg file>`

For example, this command works (in powershell):
```
native-image '@args.txt'
```
while these do not
```
native-image '@.\args.txt'
native-image '@C:\Users\kiva\git\aya-dev\args.txt'
```

## **Steps to reproduce the issue**
Please include both build steps as well as run steps
1. `git clone --depth 1 https://github.com/aya-prover/aya-dev.git`
2. `.\gradlew nativeCompile`

note: the `args.txt` is just copied from Gradle generated argument file, which is introduced in https://github.com/oracle/graal/pull/3734 but I don't know whether this issue is due to native-image or the Gradle plugin, so I posted here (sorry)

## **Describe GraalVM and your environment:**
 - GraalVM version: https://github.com/graalvm/graalvm-ce-dev-builds/releases/tag/22.2.0-dev-20220421_2218  (the java 17 version)
 - JDK major version: **17**
 - OS: **Windows 10 21H2 (19044.1645)**
 - Architecture: **AMD64**

## **More details**
Possibly this issue was introduced in https://github.com/oracle/graal/pull/4464

File contents of `args.txt` and Stack trace: https://gist.github.com/imkiva/3aa4ee72f01df4774ca5c122e9ac4ff5

**Comment by oubidar-Abderrahim** [comment]
Hi, Thank you for reporting this, we will take a look into it and get back to you

**Comment by ozkanpakdil** [comment]
I am also getting similar error here https://github.com/ozkanpakdil/java-curl/runs/6232783520?check_suite_focus=true

**Comment by michael-simons** [comment]
Same here https://github.com/michael-simons/neo4j-migrations/runs/6349806991?check_suite_focus=true#step:9:247

**Comment by olpaw** [comment]
@michael-simons can you confirm that this issue is windows only?

**Comment by michael-simons** [comment]
Yes I can as stupid me does test the build only on Linux machines https://github.com/michael-simons/neo4j-migrations/runs/6334931402?check_suite_focus=true in contrast to the binaries which I release for windows too.

**Comment by olpaw** [comment]
@imkiva thank you for your detailed bug report. The fix for this issue is in https://github.com/oracle/graal/pull/4561

One way to workaround the issue for the already released version 22.1 is to ensure that `@argfile`-use on Windows does not use complex Windows path strings. E.g. using
```
native-image @myargfile.txt
```
works just fine on Windows with 22.1, but to use e.g.
```
native-image @C:\ADE\OLabs\graal\substratevm\myargfile.txt
```
the changes from my PR are needed.

**Comment by imkiva** [comment]
@olpaw Thank you for the fix!

**Comment by sysmat** [comment]
Same her:

```
ImageClasspath Entry: org.springframework.experimental:spring-native:jar:0.12.0:compile (file:///C:/Users/tomaz/.m2/repository/org/springframework/experimental/spring-native/0.12.0/spring-native-0.12.0.jar)
ImageClasspath Entry: com.example:si:jar:0.0.1-SNAPSHOT (file:///C:/Users/tomaz/Downloads/si/target/si-0.0.1-SNAPSHOT.jar)
jar:file:///C:/Users/tomaz/Downloads/si/target/si-0.0.1-SNAPSHOT.jar!/META-INF/native-image/org.springframework.aot/spring-aot/native-image.properties does not match recommended META-INF/native-image/${groupId}/${artifactId}/native-image.properties layout.
Downloading: Component catalog from www.graalvm.org
Processing Component: Native Image
Downloading: Component native-image: Native Image from github.com
Installing new component: Native Image (org.graalvm.native-image, version 22.1.0)
Executing: C:\Program Files\Java\graalvm-ce-java17-22.1.0\bin\native-image.cmd @C:\Users\tomaz\AppData\Local\Temp\native-image1565914727584519349args
Fatal error: Unsupported OptionOrigin: C:\Users\tomaz\AppData\Local\Temp\native-image1565914727584519349args


```

**Comment by martinformi** [comment]
I am following the example `./mvnw package -Dpackaging=native-image` from documentation. How can I successfully test this on Windows? I am getting the same `Unsupported OptionOrigin` exception.

**Comment by sanshengshui** [comment]
upgrade graalvm from 22.1.0 to 22.2.0, fix the above problem! thx
