### ISSUE TITLE
Simplify DwarfLocSectionImpl#write*Locations implementations

### ISSUE THREAD

**Issue by olpaw** [oracle/graal#4513]
The conversation https://github.com/oracle/graal/pull/4505#discussion_r859671752 shows that there is a way to simplify DwarfLocSectionImpl#write*Locations implementations by making all the put* methods in com.oracle.objectfile.elf.dwarf.DwarfSectionImpl a bit smarter. This should be implemented in a separate PR. See https://github.com/oracle/graal/pull/4505#discussion_r859844959

**Comment by adinn** [comment]
@olpaw @fniephaus @zakkak  Could one of you please assign this to me?

**Comment by adinn** [comment]
Thanks Fabio!

**Comment by olpaw** [comment]
> @olpaw @fniephaus @zakkak Could one of you please assign this to me?

Sorry. For some reason I am not bale to find you in the list when I try to assign someone to an issue. I will try to get this sorted out.

**Comment by olpaw** [comment]
> > @olpaw @fniephaus @zakkak Could one of you please assign this to me?
> 
> Sorry. For some reason I am not able to find you in the list when I try to assign someone to an issue. I will try to get this sorted out.

Interestingly I can assign issues to @zakkak but not to @adinn :exploding_head:

**Comment by fniephaus** [comment]
>@olpaw @fniephaus @zakkak Could one of you please assign this to me?

>am I in danger of becoming a manager?

I'm not sure this is how it works, @adinn :wink:

**Comment by fniephaus** [comment]
Fixed by #4592.
