### ISSUE TITLE
[GR-38429] URLs with `resource` protocol throw `java.io.FileNotFoundException`

### ISSUE THREAD

**Issue by michael-simons** [oracle/graal#4514]
Given code like

```java
package simons.client;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.URL;

public class Main
{
    public static void main( String... a ) throws IOException
    {
        var url = new URL( "resource:foo/bar.txt" );
        try ( var is = new BufferedReader( new InputStreamReader( url.openStream() ) ) )
        {
            is.lines().forEach( System.out::println );
        }
    }
}
```

following https://www.graalvm.org/22.0/reference-manual/native-image/URLProtocols/ using the `resource` protocol together with a config 

```json
{
  "resources": [
    {
      "pattern": "foo/bar\\.txt"
    }
  ]
}
```

triggered by 

```
Args = -H:ResourceConfigurationResources=${.}/resources-config.json
```

in a `native-image.properties` used to work in GraalVM 21.3.0, printing out the content of the given text file.

GraalVM 22.1.0 throws:

```
Exception in thread "main" java.io.FileNotFoundException: resource:foo/bar.txt
	at com.oracle.svm.core.jdk.resources.ResourceURLConnection.getInputStream(ResourceURLConnection.java:91)
	at java.net.URL.openStream(URL.java:1161)
	at simons.client.Main.main(Main.java:13)
```

**Steps to reproduce the issue**

```
curl -OL https://github.com/oracle/graal/files/8573481/some-client.zip
unzip some-client.zip 
cd some-client
mvn package  
./target/some-client
```

GraalVM 21.3.0 prints `Hello, GraalVM rocks.`, GraalVM 22.1.0 fails.

**Describe GraalVM and your environment:**
- GraalVM 22.1.0 Java 17 CE (Java Version 17.0.3+7-jvmci-22.1-b06)
 - OS: macOS 12.2.1 
 - X86_64

Feels related to this comment:
https://github.com/quarkusio/quarkus/issues/22097#issuecomment-99805528

Reproducer [here](https://github.com/oracle/graal/files/8573481/some-client.zip) (see "Steps to reproduce the issue"). Thanks @fniephaus

**Comment by fniephaus** [comment]
Thanks for filing the issue and providing a reproducer, @michael-simons. The Native Image team will look into this.

**Comment by olpaw** [comment]
@michael-simons the observed behavior is the consequence of our fixes for the `com.oracle.svm.core.jdk.resources.NativeImageResourceFileSystemProvider`.
Now instead of
```java
var url = new URL( "resource:foo/bar.txt" );
```
you have to use
```java
var url = new URL( "resource:/foo/bar.txt" );
```

For more info follow the commits related to recent changes in
https://github.com/oracle/graal/blob/master/substratevm/src/com.oracle.svm.test/src/com/oracle/svm/test/NativeImageResourceFileSystemProviderTest.java
https://github.com/oracle/graal/blob/master/substratevm/src/com.oracle.svm.test/src/com/oracle/svm/test/NativeImageResourceTest.java

We are now (to our knowledge) fully compatible in our resource URL handling to the behaviour on the JVM. This required that our schema for encoding a resource from inside the image had to be adjusted.

**Comment by olpaw** [comment]
Also maybe interresting, file
```
some-client/src/main/resources/META-INF/native-image/org.example.client/some-client/native-image.properties
```
in `some-client.zip` is completely redundant. Having
```
some-client/src/main/resources/META-INF/native-image/org.example.client/some-client/resources-config.json
```
alone is enough for native-image to pick it up.

**Comment by michael-simons** [comment]
Thanks, @olpaw Much appreciated. I can apply the change in my tooling, thanks for getting back to me.

With the config: That's great to know! I copied just after "as is" from the original project and adapted.
