### ISSUE TITLE
[Proposal / Suggestion] Provide an additional non-text logo for GraalVM

### ISSUE THREAD

**Issue by rubyFeedback** [oracle/graal#4515]
[Not sure why the "Issue Report" has the label "bug" automatically associated; I'd like to state that this is NOT a bug report
but a suggestion.]

GraalVM on its homepage currently shows a logo and how to use it:

https://www.graalvm.org/logo/

The logo is "GraalVM" as text, using blue and ~orange as colour. So far so fine.

**However had**, I would also like to encourage and propose here that in addition to that the GraalVM team comes up
with some logo or icon that can be used as **identifier** quickly. Something that can serve as logo only without any text as such.

Google's Go has Gopher. This is an example, some logo that can be used as an identifier quickly, aside from
the current text-logo.

Now you may wonder "but why".

Well, my use case here is mostly selfish in that I just want a simple favicon to show for my local knowledge
base in regards to graalvm-related topics. I use favicon-like logos as identifiers for EVERYTHING. For ruby
I just use the ruby logo looking like a  ... well, ruby. For python it's that snakey S or whatever their logo was.
And so on and so forth.

Now: I don't want to recommend to GraalVM what kind of non-text logo to use (in addition to the current one).
I think that can be decided by voting or polls or anything like that. I have no real preference here either way,
I'd just would like to **have** such a logo or identifier. I am not saying it has to be like the gopher, by the way,
but something as alternative (or additionally) to the current text-logo. Some kind of additional identifier.

No idea whether this is acceptable, but I just wanted to propose it so perhaps others may think this could be
useful too, even aside from my super-limited use case of a favicon. :D 

(PS: If there already exists such a non-text logo then perhaps it can be mentioned on https://www.graalvm.org/logo/;
GraalVM has excellent documentation, so grouping more useful content on the homepage is very helpful
to visitors in general. I got a LOT of knowledge from the official homepage which is great - less time to
hunt on external sites for information.)

**Comment by oubidar-Abderrahim** [comment]
Hi, Thank you for your suggestion. I believe the right place for your suggestion to be heard is the email provided at the bottom of the [logo page](https://www.graalvm.org/logo/):

> If you have some questions or requests regarding GraalVM branding, please reach us via this [email](mailto:alina.yurenko@oracle.com)
