### ISSUE TITLE
No svm 22.1.0 artifact in maven central

### ISSUE THREAD

**Issue by danslapman** [oracle/graal#4518]
**Describe the issue**
There is no org.graalvm.nativeimage:svm:22.1.0 artifact in maven central. Building with 22.0.0.2 dependency on graal 22.1.0 leads to error:
```
[error] Error: ImageSingletons.add must not overwrite existing key com.oracle.svm.core.jdk.ProtectionDomainSupport
[error] Existing value: com.oracle.svm.core.jdk.ProtectionDomainSupport@5217f3d0
[error] New value: com.oracle.svm.core.jdk.ProtectionDomainSupport@37ebc9d8
[error] Error: Use -H:+ReportExceptionStackTraces to print stacktrace of underlying exception
```
I'm using svm to implement autofeature:
```
 import com.oracle.svm.core.annotate.*;
import org.bouncycastle.jce.provider.BouncyCastleProvider;
import org.graalvm.nativeimage.ImageSingletons;
import org.graalvm.nativeimage.hosted.Feature;
import org.graalvm.nativeimage.hosted.RuntimeClassInitialization;
import org.graalvm.nativeimage.impl.RuntimeClassInitializationSupport;

import java.security.Security;

@AutomaticFeature
public class BouncyCastleFeature implements Feature {

    @Override
    public void afterRegistration(AfterRegistrationAccess access) {
        RuntimeClassInitialization.initializeAtBuildTime("org.bouncycastle");
        RuntimeClassInitializationSupport rci = ImageSingletons.lookup(RuntimeClassInitializationSupport.class);
        rci.rerunInitialization("org.bouncycastle.jcajce.provider.drbg.DRBG$Default", "");
        rci.rerunInitialization("org.bouncycastle.jcajce.provider.drbg.DRBG$NonceAndIV", "");
        Security.addProvider(new BouncyCastleProvider());
    }
}
```

**Describe GraalVM and your environment:**
 - GraalVM version (latest snapshot builds can be found [here](https://github.com/graalvm/graalvm-ce-dev-builds/releases)), or commit id if built from source: **22.1.0**

**Comment by kristofdho** [comment]
For reference: https://github.com/oracle/graal/discussions/4146#discussioncomment-2171152

**Comment by zakkak** [comment]
Hello @gilles-duboscq are there any updates on that front?

**Comment by gilles-duboscq** [comment]
The necessary configuration landed in master last Friday in b62be627c4e5abf678bc5eaaa27c99a2c4ff2dfa.
Although most changes were in mx (https://github.com/graalvm/mx/commit/939c4757f4d5d0158adf43b445d1f234285c7782).

I have applied the same changes to build the artefacts for 22.1.0, they are now in the pipeline to be published out to maven central.

**Comment by danslapman** [comment]
Thank You, @gilles-duboscq!

**Comment by danslapman** [comment]
I confirm that everything is now fine with new artifact
