### ISSUE TITLE
Provide and use mirrors for external dependencies

### ISSUE THREAD

**Issue by fniephaus** [oracle/graal#452]
When running `mx eclipseinit` in `compiler/`, I'm currently getting errors like this:

```
Downloading TruffleJSON from ['https://lafo.ssw.uni-linz.ac.at/pub/graal-external-deps/trufflejson-20180130.jar']
Downloading https://lafo.ssw.uni-linz.ac.at/pub/graal-external-deps/trufflejson-20180130.jar to /Users/fniephaus/.mx/cache/TruffleJSON_8819cea8bfe22c9c63f55465e296b3855ea41786.jar
WARNING: urlopen() timed out! Retrying without timeout of 20s.
WARNING: urlopen() timed out! Retrying without timeout of 40s.
WARNING: urlopen() timed out! Retrying without timeout of 80s.
WARNING: urlopen() timed out! Retrying without timeout of 160s.
Error reading from https://lafo.ssw.uni-linz.ac.at/pub/graal-external-deps/trufflejson-20180130.jar: <urlopen error [Errno 60] Operation timed out>
** If behind a firewall without direct internet access, use the http_proxy environment variable (e.g. "env http_proxy=proxy.company.com:80 mx ...") or download manually with a web browser.
Could not download to /.mx/cache/TruffleJSON_8819cea8bfe22c9c63f55465e296b3855ea41786.jar from any of the following URLs: https://lafo.ssw.uni-linz.ac.at/pub/graal-external-deps/trufflejson-20180130.jar
```
Obviously, this is because [lafo.ssw.uni-linz.ac.at is down](https://downforeveryoneorjustme.com/lafo.ssw.uni-linz.ac.at). It might be good to provide mirrors that are used as fallbacks to avoid these situations.

**Comment by fniephaus** [comment]
Our CI builds also fail because of this at the moment...

**Comment by sanzinger** [comment]
We're working on that, should be be up soon.

**Comment by sanzinger** [comment]
The fileserver is back up. For the future we should create a hosting mirror for these files.

**Comment by fniephaus** [comment]
@sanzinger thanks!

I've renamed the issue, so it can be used to track the progress of introducing hosting mirrors.

**Comment by olegchir** [comment]
@sanzinger maybe we can just use Github Releases or even better, Bintray? Pretty stable solutions. Cost nothing.

**Comment by sanzinger** [comment]
Yes, this is actually what we are going to do. The change will be avialable next week.

**Comment by olegchir** [comment]
@sanzinger is there any way I can help? I thought about creating Ansible/Docker/... scripts on everything we have in public documentation, but I talked to Oleg and realized that this would be copying the work that you are already doing, which is quite pointless. If you have any ideas on this, please ping me. (+ oleg@jugru.org).

**Comment by fniephaus** [comment]
> @sanzinger maybe we can just use Github Releases or even better, Bintray? Pretty stable solutions. Cost nothing.

IMHO GitHub Releases is way easier to use than Bintray. Bintray have weird limitations (e.g. after 180 days, files cannot be removed anymore) and the UI/UX is quite annoying too.

**Comment by sanzinger** [comment]
Hi @olegchir , the change was a bit delayed. The change came through last night, which downloads now all dependencies from github. dcd7153

**Comment by sanzinger** [comment]
@olegchir For what purpose you think about building a docker image?
