### ISSUE TITLE
Enhance resource limit to include script time out 

### ISSUE THREAD

**Issue by satjadhav** [oracle/graal#4521]
**Feature request**

Currently there is ability to close the execution of the guest script after mentioned statement count. But nothing for script execution timeout. Is it possible to include script timeout as a resource limit? 

**Is your feature request related to a problem? Please describe.**
Long running scripts are causing issues. We want to time them out with proper exception so that resources can be freed. 

**Describe the solution you'd like.**
Add script timeout as resource limit. The script should be timed out with proper timeout exception. 

**Describe who do you think will benefit the most.**
GraalVM users

**Describe alternatives you've considered.**
ExecutionListener(Graal) or ExecutorService(Java)

**Additional context.**
NA

**Express whether you'd like to help contributing this feature**
Yes

**Comment by oubidar-Abderrahim** [comment]
Hi, Thank you for your suggestion, we will take a look into it

**Comment by oubidar-Abderrahim** [comment]
Tracked internally on GR--38556

**Comment by satjadhav** [comment]
Thanks for the consideration. Let me know in case you need any more information. 
Do you have any approximate timelines for its availability?

**Comment by chumer** [comment]
Graal JS with OpenJDK will not support CPU timeout limit. You need to use Oracle GraalVM for that or build your own instrument.

More info on all the sandbox features can be found here: https://www.graalvm.org/latest/security-guide/polyglot-sandbox/
