### ISSUE TITLE
[LLVM] pthread_getspecific crash

### ISSUE THREAD

**Issue by roxanan-adyen** [oracle/graal#4529]
**Describe GraalVM and your environment :**
 - GraalVM version: **22.1.0**
 - **EE**
 - JDK version: **JDK11**
 - OS and OS Version: **macOS Monterey**
 - Architecture: **amd64**
 - The output of `java -Xinternalversion`:
```
 Java HotSpot(TM) 64-Bit Server VM (11.0.15+8-LTS-jvmci-22.1-b05) for bsd-amd64 JRE (11.0.15+8-LTS-jvmci-22.1-b05), built on Apr  4 2022 04:05:20 by "graal1" with gcc 4.2.1 Compatible Apple LLVM 11.0.0 (clang-1100.0.33.17)
```

**Have you verified this issue still happens when using the latest snapshot?**
Yes, I tried only the latest version

**Describe the issue**
I have a small C/C++ program with two exposed functions:
one that calls `pthread_key_create` and one that calls `pthread_getspecific`. This is built as a library that is loaded by a java app. In the java app, I try to create the global phtread_key in the main thread and in another thread I try to use the key (with getspecific function). This is the output of the test: 
```
Exception in thread "Thread-6" Illegal null pointer access in 'load pointer'.
        at <llvm> get_specific(pthread_key.cpp:21:480)
        at org.graalvm.sdk/org.graalvm.polyglot.Value.invokeMember(Value.java:932)
        at Tester.lambda$main$0(Tester.java:16)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

**How to compile the LLVM bitcode that causes the problem**
 Compile C/C++ lib:
 ```
 $GRAALVM_MANAGED_LLVM_TOOLCHAIN/clang++ -std=c++17 -fPIC -shared -O1 -g pthread_key.cpp -o crash.so
 ```
Where 
```
export GRAALVM_MANAGED_LLVM_TOOLCHAIN=$($GRAALVM_HOME/bin/lli --print-toolchain-path --llvm.managed)
```

**Code snippet or code repository that reproduces the problem**
C code: pthread_key.c:
```
#include <iostream>
#include <pthread.h>
#include <thread>

extern "C" {

static pthread_key_t globalkey;
void get_specific();

void create_key() {
    int r = pthread_key_create(&globalkey, NULL);
    get_specific();
}

void get_specific() {
    // This will crash
    int* r = (int*) pthread_getspecific(globalkey);
}

} // extern c
```

Java:
```
import java.io.*;
import org.graalvm.polyglot.*;
import java.lang.reflect.Method;
import java.util.*;
import java.lang.Thread;

class Tester {
    public static void main(String[] args) throws Exception {
        Context polyglot = Context.newBuilder().allowAllAccess(true).allowIO(true).option("llvm.managed", "true").build();
        File file = new File("crash.so");
        Source source = Source.newBuilder("llvm", file).build();
        final Value cpart = polyglot.eval(source);
        cpart.invokeMember("create_key");


        Thread t1 = new Thread(() -> {
            cpart.invokeMember("get_specific");
        });
        t1.start();
        t1.join();

    }
}
```

**Steps to reproduce the problem**
Please include both build steps as well as run steps
1. $GRAALVM_MANAGED_LLVM_TOOLCHAIN/clang++ -std=c++17 -fPIC -shared -O1 -g pthread_key.cpp -o crash.so
2. javac Tester.java && java Tester
 Output:
 ```
Exception in thread "Thread-6" Illegal null pointer access in 'load pointer'.
        at <llvm> get_specific(pthread_key.cpp:21:480)
        at org.graalvm.sdk/org.graalvm.polyglot.Value.invokeMember(Value.java:932)
        at Tester.lambda$main$0(Tester.java:16)
        at java.base/java.lang.Thread.run(Thread.java:834)
```
        
**Expected behavior**
No exception, and being able to use local thread storage correctly.

**Additional notes**
1. If we use lli interpretor and no java app, we don't see this behavior at all. It works just fine.
2. We discovered this by chance, but if in the second thread, before using the global key, we just call pthread_create_key once to create a garbage key, it works. My assumption is that some local table is not properly initialized.
```
void get_specific() {
    // FIX: this is our workaround. calling this function from the side thread solves the issue of exception.
    pthread_key_t localkey;
    int r2 = pthread_key_create(&localkey, NULL);

    // This won't crash now
    int* r = (int*) pthread_getspecific(globalkey);
}
```

**Comment by rschatz** [comment]
This should be fixed in GraalVM 22.2.
