### ISSUE TITLE
Native build tools nativeTestCompile fails due to missing testlist directory

### ISSUE THREAD

**Issue by haffar** [oracle/graal#4532]
**Describe the issue**
When using the gradle plugin, nativeTestCompile is failing due to a missing testlist directory.
I can manually create the directory, and run nativeTestCompile, but it gets deleted at the start of the run and i still get the same error

**Steps to reproduce the issue**
./gradlew nativeTestCompile

**Describe GraalVM and your environment:**
 - GraalVM version 
 openjdk version "11.0.15" 2022-04-19
OpenJDK Runtime Environment GraalVM CE 22.1.0 (build 11.0.15+10-jvmci-22.1-b06)
OpenJDK 64-Bit Server VM GraalVM CE 22.1.0 (build 11.0.15+10-jvmci-22.1-b06, mixed mode)

 - JDK major version: 11
 - OS: macOS Catalina
 - Architecture: aarch64/M1
 - Graal Native Build tools version 0.9.11
 - Gradle Version: 7.1

**More details**
 haffar$ ./gradlew nativeTestCompile
Configuration on demand is an incubating feature.

> Configure project :
The Report.destination property has been deprecated. This is scheduled to be removed in Gradle 8.0. Please use the outputLocation property instead. See https://docs.gradle.org/7.1/dsl/org.gradle.api.reporting.Report.html#org.gradle.api.reporting.Report:destination for more details.
        at build_acz1ee3ihdum6b3qe8ynt4osi$_run_closure3.doCall(/Users/haffar/la1/git/media-metadata/build.gradle:63)
        (Run with --stacktrace to get the full stack trace of this deprecation warning.)
The Report.enabled property has been deprecated. This is scheduled to be removed in Gradle 8.0. Please use the required property instead. See https://docs.gradle.org/7.1/dsl/org.gradle.api.reporting.Report.html#org.gradle.api.reporting.Report:enabled for more details.
        at build_acz1ee3ihdum6b3qe8ynt4osi$_run_closure3.doCall(/Users/haffar/la1/git/media-metadata/build.gradle:63)
        (Run with --stacktrace to get the full stack trace of this deprecation warning.)

> Configure project :webapp
The nativeBuild extension is deprecated and will be removed. Please use the 'graalvmNative.binaries.main' extension to configure the native image instead.

> Task :webapp:generateTestAot
WARNING: Unable to find jar '/Users/haffar/la1/git/media-metadata/webapp/build/resources/test' whilst scanning filesystem
2022-05-03 15:32:52,365 4981 [           main] INFO  o.s.nativex.support.SpringAnalyzer       - Spring Native operating mode: native
2022-05-03 15:32:57,266 4981 [           main] ERROR o.s.nativex.type.TypeSystem              - java.lang.IllegalStateException: Unable to find a single main class from the following candidates [io.resi.media.metadata.MediaMetadataApplication, io.resi.media.metadata.util.Base64TokenGenerator, io.resi.media.metadata.util.Base64EncodedGenerator]
2022-05-03 15:32:57,295 4981 [           main] ERROR o.s.aot.nativex.ConfigurationContributor - java.lang.IllegalStateException: Unable to find a single main class from the following candidates [io.resi.media.metadata.MediaMetadataApplication, io.resi.media.metadata.util.Base64TokenGenerator, io.resi.media.metadata.util.Base64EncodedGenerator]

> Task :webapp:compileAotTestJava
/Users/haffar/la1/git/media-metadata/webapp/build/generated/runtimeSources/aotTest/org/springframework/aot/StaticSpringFactories.java:56: warning: [rawtypes] found raw type: Class
  public static MultiValueMap<Class, Supplier<Object>> factories = new LinkedMultiValueMap();
                              ^
  missing type arguments for generic class Class<T>
  where T is a type-variable:
    T extends Object declared in class Class
/Users/haffar/la1/git/media-metadata/webapp/build/generated/runtimeSources/aotTest/org/springframework/aot/StaticSpringFactories.java:56: warning: [rawtypes] found raw type: LinkedMultiValueMap
  public static MultiValueMap<Class, Supplier<Object>> factories = new LinkedMultiValueMap();
                                                                       ^
  missing type arguments for generic class LinkedMultiValueMap<K,V>
  where K,V are type-variables:
    K extends Object declared in class LinkedMultiValueMap
    V extends Object declared in class LinkedMultiValueMap
/Users/haffar/la1/git/media-metadata/webapp/build/generated/runtimeSources/aotTest/org/springframework/aot/StaticSpringFactories.java:56: warning: [unchecked] unchecked conversion
  public static MultiValueMap<Class, Supplier<Object>> factories = new LinkedMultiValueMap();
                                                                   ^
  required: MultiValueMap<Class,Supplier<Object>>
  found:    LinkedMultiValueMap
/Users/haffar/la1/git/media-metadata/webapp/build/generated/runtimeSources/aotTest/org/springframework/aot/StaticSpringFactories.java:58: warning: [rawtypes] found raw type: Class
  public static MultiValueMap<Class, String> names = new LinkedMultiValueMap();
                              ^
  missing type arguments for generic class Class<T>
  where T is a type-variable:
    T extends Object declared in class Class
/Users/haffar/la1/git/media-metadata/webapp/build/generated/runtimeSources/aotTest/org/springframework/aot/StaticSpringFactories.java:58: warning: [rawtypes] found raw type: LinkedMultiValueMap
  public static MultiValueMap<Class, String> names = new LinkedMultiValueMap();
                                                         ^
  missing type arguments for generic class LinkedMultiValueMap<K,V>
  where K,V are type-variables:
    K extends Object declared in class LinkedMultiValueMap
    V extends Object declared in class LinkedMultiValueMap
/Users/haffar/la1/git/media-metadata/webapp/build/generated/runtimeSources/aotTest/org/springframework/aot/StaticSpringFactories.java:58: warning: [unchecked] unchecked conversion
  public static MultiValueMap<Class, String> names = new LinkedMultiValueMap();
                                                     ^
  required: MultiValueMap<Class,String>
  found:    LinkedMultiValueMap
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
6 warnings

> Task :webapp:generateTestResourcesConfigFile
[native-image-plugin] Resources configuration written into /Users/haffar/la1/git/media-metadata/webapp/build/native/generated/generateTestResourcesConfigFile/resource-config.json

> Task :webapp:nativeTestCompile FAILED

FAILURE: Build failed with an exception.

* What went wrong:
A problem was found with the configuration of task ':webapp:nativeTestCompile' (type 'BuildNativeImageTask').
  - In plugin 'org.graalvm.buildtools.gradle.NativeImagePlugin$Inject' type 'org.graalvm.buildtools.gradle.tasks.BuildNativeImageTask' property 'testListDirectory' specifies directory '/Users/haffar/la1/git/media-metadata/webapp/build/test-results/test/testlist' which doesn't exist.
    
    Reason: An input file was expected to be present but it doesn't exist.
    
    Possible solutions:
      1. Make sure the directory exists before the task is called.
      2. Make sure that the task which produces the directory is declared as an input.
    
    Please refer to https://docs.gradle.org/7.1/userguide/validation_problems.html#input_file_does_not_exist for more details about this problem.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 14s
13 actionable tasks: 9 executed, 4 up-to-date

**Comment by oubidar-Abderrahim** [comment]
Hi, thank you for reporting this, I don't understand exactly what could possibly delete this folder in your case? the native-image builder is not supposed to delete any folders. Also, what's the utility of this folder?

Could you please do the following? try to generate the native image manually from the command line.

**Comment by haffar** [comment]
Hi, sure I can try that. Is there a specific command you want me to run?
I suspect the issue is here (lines 362-267):
https://github.com/addstone/graalvm-native-build-tools/blob/master/native-gradle-plugin/src/main/java/org/graalvm/buildtools/gradle/NativeImagePlugin.java

**Comment by oubidar-Abderrahim** [comment]
1. build your jar normally (using gradle). 
2. run the app with the [native-image agent](https://www.graalvm.org/22.0/reference-manual/native-image/Agent/) to generate config files.
3. build the image with `native-image --no-fallback -H:ConfigurationFileDirectories=<Config_folder> -jar APP.jar`

**Comment by GoodforGod** [comment]
Faced same issue, looks like a regression bug starting from 0.9.10 that was discovered only now cause no one uses nativeTests

Everything works prior to 0.9.9 version

Here is my stacktrace for 0.9.11
```
#8 61.61 > Task :simple-awslambda:compileJava
#8 63.21 Note: Some input files use unchecked or unsafe operations.
#8 63.21 Note: Recompile with -Xlint:unchecked for details.
#8 64.31
#8 64.31 FAILURE: Build failed with an exception.
#8 64.31
#8 64.31 * What went wrong:
#8 64.31 A problem was found with the configuration of task ':nativeTestCompile' (type 'BuildNativeImageTask').
#8 64.31   - In plugin 'org.graalvm.buildtools.gradle.NativeImagePlugin$Inject' type 'org.graalvm.buildtools.gradle.tasks.BuildNativeImageTask' property 'testListDirectory'
 specifies directory '/home/application/build/test-results/test/testlist' which doesn't exist.
#8 64.31
#8 64.31     Reason: An input file was expected to be present but it doesn't exist.
#8 64.31
#8 64.31     Possible solutions:
#8 64.31       1. Make sure the directory exists before the task is called.
#8 64.31       2. Make sure that the task which produces the directory is declared as an input.
#8 64.31
#8 64.31     Please refer to https://docs.gradle.org/7.4.2/userguide/validation_problems.html#input_file_does_not_exist for more details about this problem.
#8 64.31
#8 64.31 * Try:
#8 64.31 > Run with --stacktrace option to get the stack trace.
#8 64.31 > Run with --info or --debug option to get more log output.
#8 64.31 > Run with --scan to get full insights.
#8 64.31
#8 64.31 * Get more help at https://help.gradle.org
#8 64.41
#8 64.41 Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.
#8 64.41
#8 64.41 You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.
#8 64.41
#8 64.42 See https://docs.gradle.org/7.4.2/userguide/command_line_interface.html#sec:command_line_warnings
#8 64.42
#8 64.42 BUILD FAILED in 1m 2s
#8 64.42 5 actionable tasks: 5 executed
```

**Comment by oubidar-Abderrahim** [comment]
If this issue is still happening on the latest native build tools v0.9.28. please reopen the issue or create a new one. Thank you
