### ISSUE TITLE
[GR-38566] Provide an alternate method for generating a download token

### ISSUE THREAD

**Issue by swseighman** [oracle/graal#4535]
**Feature request:** Provide an alternate method for generating a download token

**GraalVM version:** 22.1.0

**Use case:** 
I have downloaded and installed GraalVM EE core and Native Image via the [download site](https://www.oracle.com/downloads/graalvm-downloads.html).

`$ gu install -L native-image.jar`

Now I want to use [GitHub Actions](https://github.com/marketplace/actions/github-action-for-graalvm) with `gds-token:`  ... but I don't have a ~`.gu/config` file:

```
$ gu --show-ee-token
There is no saved download token.
```

The absence of the token may be related to the download method/catalog.  I may not require a token as I accepted the license when downloading from OTN.  Subsequent module installation(s) should prompt you for a token but only if you choose to install additional modules.

NOTE: Installing modules using a 'standard' workflow works as expected (a token can/will be generated).

**Request:** Consider adding a CLI utility/command option to generate a download token for users of this workflow.

Attention @fniephaus

**Comment by fniephaus** [comment]
Thanks for the feature request, @swseighman. We're going to look into it and I will update this issue when I have more info.

**Comment by fniephaus** [comment]
Fixed with https://github.com/graalvm/graalvm-jdk-downloader#set-up-a-download-token-for-graalvm-enterprise-installations.

**Comment by fniephaus** [comment]
This is now possible via `$ bash <(curl -sL https://get.graalvm.org/ee-token)`, see https://github.com/graalvm/graalvm-jdk-downloader#set-up-a-download-token-for-graalvm-enterprise-installations.
