### ISSUE TITLE
Enabling Full Info Points on AArch64 causes compile failures

### ISSUE THREAD

**Issue by adinn** [oracle/graal#4542]
** Describe the Problem**

The latest patch for debug info (PR  #4505) modifies the `GraphBuilderConfiguration` to enable full info point generation. 

    class SVMHost {
      ...
    @Override
    public GraphBuilderConfiguration updateGraphBuilderConfiguration(GraphBuilderConfiguration config, AnalysisMethod method) {
        return config.withRetainLocalVariables(retainLocalVariables())
                        .withUnresolvedIsError(linkAtBuildTimeSupport.linkAtBuildTime(method.getDeclaringClass()))
                        .withFullInfopoints(SubstrateOptions.GenerateDebugInfo.getValue() > 0);
    ...

This is not a problem on x86_64. However, it leads to multiple compile failures on AArch64. They all occur because `LocationMarkerPhase.processState()` has been passed a `FullInfopointNode` referencing a live value in the *link* register `lr` aka `r30`.

    java.lang.NullPointerException
	at com.oracle.svm.core.CalleeSavedRegisters.getOffsetInFrame(CalleeSavedRegisters.java:108)
	at com.oracle.svm.core.heap.SubstrateReferenceMapBuilder.addLiveValue(SubstrateReferenceMapBuilder.java:65)
	at jdk.internal.vm.compiler/org.graalvm.compiler.lir.dfa.RegStackValueSet$1.visitValue(RegStackValueSet.java:155)
	at jdk.internal.vm.compiler/org.graalvm.compiler.lir.ValueConsumer.visitValue(ValueConsumer.java:51)
	at jdk.internal.vm.compiler/org.graalvm.compiler.lir.util.IndexedValueMap.visitEach(IndexedValueMap.java:455)
	at jdk.internal.vm.compiler/org.graalvm.compiler.lir.dfa.RegStackValueSet.addLiveValues(RegStackValueSet.java:158)
	at jdk.internal.vm.compiler/org.graalvm.compiler.lir.dfa.LocationMarkerPhase$Marker.processState(LocationMarkerPhase.java:97)
        ...

The reference map builder assumes that `lr` is a callee saved register which is why it ends up calling `CalleeSavedRegisters.getOffsetInFrame`. Unfortunately, when the call to `getOffsetInFrame` looks up `lr` in the map stored in field `offsetsInSaveArea` the result is `null` leading to a NPE.

**Steps to reproduce the issue**

*Path 1:*
  1 Clone the repo from  #4505
     git clone git://github.com/adinn/graal debug_location_info
  2 Build on Linux/AArch64
     mx build
  3 Run the debug info test
      mx debuginfotest

*Path 2:*
  1 Clone the Oracle master
  2) Modify class SVMHost.updateGraphBuilderConfiguration to always enable full infopoints

      public GraphBuilderConfiguration updateGraphBuilderConfiguration(GraphBuilderConfiguration config, AnalysisMethod method) {
          return config.withRetainLocalVariables(retainLocalVariables())
                        .withUnresolvedIsError(linkAtBuildTimeSupport.linkAtBuildTime(method.getDeclaringClass()))
                        .withFullInfopoints(true);
      ...

  3) Build on Linux/AArch64
     mx build
  4 Run the debug info test
      mx debuginfotest

**Describe GraalVM and your environment:**
 - GraalVM version: Manifests with latest GraalVM head or with version in PR #4505
 - JDK major version: 17 or 11
 - OS: Linux
 - Architecture: AArch64

**Comment by olpaw** [comment]
> The reference map builder assumes that lr is a callee saved register which is why it ends up calling CalleeSavedRegisters.getOffsetInFrame. Unfortunately, when the call to getOffsetInFrame looks up lr in the map stored in field offsetsInSaveArea the result is null leading to a NPE.

@teshull to me it sounds like `SubstrateReferenceMapBuilder#addLiveValue` needs to handle AArch64 differently. Do you have any hints / ideas on how to fix this?

**Comment by teshull** [comment]
hmm. I'm off the rest of this week, but I'll look into it the beginning of next week

**Comment by olpaw** [comment]
> hmm. I'm off the rest of this week, but I'll look into it the beginning of next week

Thanks a lot!

**Comment by adinn** [comment]
Hi Tom, Thanks for taking a look at this.

**Comment by adinn** [comment]
@teshull I discussed a possible fix here https://github.com/oracle/graal/pull/4505#issuecomment-1122133425

**Comment by teshull** [comment]
fixed by #4565
