### ISSUE TITLE
[GR-38592] Usage of BigInteger in SubstrateVM

### ISSUE THREAD

**Issue by ChristophTF** [oracle/graal#4545]
**Problem Description:**
In _CgroupSubsystemController.convertStringToLong_, the Type _BigInteger_ is used to figure out if the conversion failed due to the parsed string representing a too large number.
This makes _BigInteger_ reachable in the Points-to analysis of native-image.

**Involved code:**
https://github.com/oracle/graal/blob/a211b726c51cf1aec18647632e6f567fd43c0a66/substratevm/src/com.oracle.svm.core.containers/src/com/oracle/svm/core/containers/CgroupSubsystemController.java#L240-L255

**Comment by fniephaus** [comment]
[Here's why](https://bugs.openjdk.java.net/browse/JDK-8206243) this code was introduced into the OpenJDK and according to that, it is only needed to handle the case when `memory.limit_in_bytes` exceeds `Long.MAX_VALUE`.

#4559 eliminates the use of `BigInteger` in `CgroupSubsystemController.java`.

Again, thanks for the report!
