### ISSUE TITLE
Graal CE 1.0-rc2 is slower than C1/C2 on SciMark 2.0a

### ISSUE THREAD

**Issue by markehammons** [oracle/graal#455]
[This is](https://math.nist.gov/scimark2/download_java.html) an ancient bench, but it's alarming the results I'm getting for it on graal ce 1.0-rc2. 

GraalCE results
```
Composite Score: 1325.8462963094908
FFT (1024): 1308.998622864666
SOR (100x100):   1174.2565325562568
Monte Carlo : 373.4754170434782
Sparse matmult (N=1000, nz=5000): 1543.3853062092492
LU (100x100): 2229.1156028738033
```

Graal EE results
```
Composite Score: 2229.7684912507
FFT (1024): 1308.0169507497242
SOR (100x100):   1443.9527168147408
Monte Carlo : 920.0873031620079
Sparse matmult (N=1000, nz=5000): 1580.6090258304291
LU (100x100): 5896.176459696598
```

C1/C2 (-XX:-UseJVMCICompiler) results:
```
Composite Score: 2062.1804163920056
FFT (1024): 1360.5621793755013
SOR (100x100):   1366.63467425589
Monte Carlo : 881.5614787923914
Sparse matmult (N=1000, nz=5000): 1900.9717896280133
LU (100x100): 4801.171959908232
```

As you can see, Graal EE is not affected or is not affected as badly as CE is in this bench. It is odd that C1/C2 beats it in fast fourier transform calculations, but otherwise it beats out C1/C2 as expected. CE's performance is shockingly poor though.

**Comment by markehammons** [comment]
I have other benches grabbed from the languages shootout showing performance degradation in some cases from the C1/C2 JITC to Graal's. Should I post those as a seperate issue or would you like that I put them in here?

**Comment by thomaswue** [comment]
Thanks for measuring performance. It is great to see that EE outperforms C1/C2 according to your measurements. We do have a lot of synthetic benchmarks internally. What would be interesting to us are benchmark setups with more real-world workloads; in particular with complex object-oriented abstractions rather than simple mathematical algorithms.

**Comment by lbialy** [comment]
Why do I get a feeling that by not addressing the fact CE was sluggish you're kinda pointing towards the conclusion that this was expected @thomaswue?

**Comment by thomaswue** [comment]
@lbialy For this particular instance of mathematical benchmarks (created in 1999), it is expected that CE is currently lagging. We are working on improving performance of both CE and EE versions. Generally, it is for compilers always a trade-off between compilation speed and peak performance. The EE version compiles slower but then produces the best machine code (also for this instance) while the CE version is compiling faster and produces less optimal machine code. Twitter is reporting their ~12% speed-up with the CE version. We are happy with a result when we e.g. run Twitter's production server-side workloads faster, but lag on artificial numeric benchmarks. We appreciate particularly if people share with us benchmark setups for their real applications and libraries. Realistic benchmark setups are very helpful. When compilers get heavily optimized towards synthetic benchmarks, it might be even negative for their performance in practical setups.

**Comment by spavlusieva** [comment]
Hi @markehammons, this issue has been inactive for more than 180 days. We’ll close it to focus on current issues. In case it’s still relevant, please reopen it and we’ll take another look. Thank you!
