### ISSUE TITLE
Unable to use build Native image when using G1GC with musl static libraries

### ISSUE THREAD

**Issue by Sidhardha95** [oracle/graal#4553]
Unable to use build Native image when using G1GC with musl static libraries

**Describe GraalVM and your environment:**
 - GraalVM version : **22.0.0**
 - JDK major version: **11**

Below is our Native image properties file:
`Args=\
  --features=com.oracle.cx.communications.dx4c.fabric.utils.core.graal.FabricK8sFeature,\
  com.oracle.cx.communications.dx4c.fabric.utils.core.graal.FabricKNativeFeature,\
  com.oracle.cx.communications.dx4c.fabric.utils.core.graal.GlassFishFeature,\
  com.oracle.cx.communications.dx4c.fabric.utils.core.graal.JavaFeature,\
  com.oracle.cx.industries.framework.models.k8s.graal.NativeImageFeature,\
  com.oracle.cx.communications.dx4c.fabric.utils.core.graal.CommonUtilsCoreFeature,\
  com.oracle.cx.industries.framework.routing.graal.NativeImageFeature \
  --install-exit-handlers \
  --gc=G1 \
  -J-Xmx20G \
  --no-fallback \
  --report-unsupported-elements-at-runtime \
  --language:js \
  --enable-url-protocols=http,https \
  -H:+AddAllCharsets \
  --libc=musl \
  --static \
  --initialize-at-build-time=org.slf4j.impl.StaticLoggerBinder,\
  org.slf4j.impl.JDK14LoggerAdapter,org.slf4j.LoggerFactory,\
  io.micrometer.prometheus.PrometheusConfig,\
  io.micrometer.core.instrument.config.NamingConvention,\
  io.micrometer.prometheus.PrometheusNamingConvention,\
  com.oracle.truffle.api.Truffle,\
  java.time.Instant \
`

With above settings , build is failing with below erro
 `[INFO] [6/7] Compiling methods...    [*******]                                                                 (59.6s @ 9.32GB)
[INFO] 
[INFO] [7/7] Creating image...                                                                                  (0.0s @ 8.89GB)
[WARNING] Fatal error: java.lang.RuntimeException: There was an error linking the native image: Linker command exited with 1
[WARNING] 
[WARNING] Linker command executed:
[WARNING] /opt/musl-1.2.2/bin/x86_64-linux-musl-gcc -z noexecstack -Wl,--gc-sections -Wl,-x -o /builds/cx-verticals-dev/fabric-routing-ms/target/service service.o /usr/lib64/graalvm/graalvm22-ee-java11/lib/static/linux-amd64/musl/libnet.a /usr/lib64/graalvm/graalvm22-ee-java11/lib/static/linux-amd64/musl/libjavajpeg.a /usr/lib64/graalvm/graalvm22-ee-java11/lib/static/linux-amd64/musl/libextnet.a /usr/lib64/graalvm/graalvm22-ee-java11/lib/static/linux-amd64/musl/libnio.a /usr/lib64/graalvm/graalvm22-ee-java11/lib/svm/clibraries/linux-amd64/liblibchelper.a /usr/lib64/graalvm/graalvm22-ee-java11/lib/static/linux-amd64/musl/libjava.a /usr/lib64/graalvm/graalvm22-ee-java11/lib/static/linux-amd64/musl/liblcms.a /usr/lib64/graalvm/graalvm22-ee-java11/lib/static/linux-amd64/musl/libawt_headless.a /usr/lib64/graalvm/graalvm22-ee-java11/lib/static/linux-amd64/musl/libawt.a /usr/lib64/graalvm/graalvm22-ee-java11/lib/static/linux-amd64/musl/libfdlibm.a /usr/lib64/graalvm/graalvm22-ee-java11/lib/static/linux-amd64/musl/libsunec.a /usr/lib64/graalvm/graalvm22-ee-java11/lib/static/linux-amd64/musl/libzip.a /usr/lib64/graalvm/graalvm22-ee-java11/lib/svm/clibraries/linux-amd64/libjvm.a -static -v -L/tmp/SVM-7922469978308771623 -L/usr/lib64/graalvm/graalvm22-ee-java11/lib/static/linux-amd64/musl -L/usr/lib64/graalvm/graalvm22-ee-java11/lib/svm/clibraries/linux-amd64 -lg1gc-cr -ldl -lm -lpthread -lstdc++ -lstdc++ -lm -lstdc++ -lz -lpthread -ldl -lrt
[WARNING] 
[WARNING] Linker command output:
[WARNING] Using built-in specs.
[WARNING] COLLECT_GCC=/opt/musl-1.2.2/bin/x86_64-linux-musl-gcc
[WARNING] COLLECT_LTO_WRAPPER=/opt/musl-1.2.2/bin/../libexec/gcc/x86_64-linux-musl/9.4.0/lto-wrapper
[WARNING] Target: x86_64-linux-musl
[INFO] ------------------------------------------------------------------------------------------------------------------------
[WARNING] Configured with: ../src_gcc/configure --enable-languages=c,c++ --disable-bootstrap --disable-assembly --disable-werror --target=x86_64-linux-musl --prefix= --libdir=/lib --disable-multilib --with-sysroot=/x86_64-linux-musl --enable-tls --disable-libmudflap --disable-libsanitizer --disable-gnu-indirect-function --disable-libmpx --enable-initfini-array --enable-libstdcxx-time=rt --with-build-sysroot=/scratch1/kpokkana/github/musl-cross-make/build/local/x86_64-linux-musl/obj_sysroot AR_FOR_TARGET=/scratch1/kpokkana/github/musl-cross-make/build/local/x86_64-linux-musl/obj_binutils/binutils/ar AS_FOR_TARGET=/scratch1/kpokkana/github/musl-cross-make/build/local/x86_64-linux-musl/obj_binutils/gas/as-new LD_FOR_TARGET=/scratch1/kpokkana/github/musl-cross-make/build/local/x86_64-linux-musl/obj_binutils/ld/ld-new NM_FOR_TARGET=/scratch1/kpokkana/github/musl-cross-make/build/local/x86_64-linux-musl/obj_binutils/binutils/nm-new OBJCOPY_FOR_TARGET=/scratch1/kpokkana/github/musl-cross-make/build/local/x86_64-linux-musl/obj_binutils/binutils/objcopy OBJDUMP_FOR_TARGET=/scratch1/kpokkana/github/musl-cross-make/build/local/x86_64-linux-musl/obj_binutils/binutils/objdump RANLIB_FOR_TARGET=/scratch1/kpokkana/github/musl-cross-make/build/local/x86_64-linux-musl/obj_binutils/binutils/ranlib READELF_FOR_TARGET=/scratch1/kpokkana/github/musl-cross-make/build/local/x86_64-linux-musl/obj_binutils/binutils/readelf STRIP_FOR_TARGET=/scratch1/kpokkana/github/musl-cross-make/build/local/x86_64-linux-musl/obj_binutils/binutils/strip-new --build=x86_64-pc-linux-gnu --host=x86_64-pc-linux-gnu
[WARNING] Thread model: posix
[WARNING] gcc version 9.4.0 (GCC) 
[WARNING] COMPILER_PATH=/opt/musl-1.2.2/bin/../libexec/gcc/x86_64-linux-musl/9.4.0/:/opt/musl-1.2.2/bin/../libexec/gcc/:/opt/musl-1.2.2/bin/../lib/gcc/x86_64-linux-musl/9.4.0/../../../../x86_64-linux-musl/bin/
[WARNING] LIBRARY_PATH=/opt/musl-1.2.2/bin/../lib/gcc/x86_64-linux-musl/9.4.0/:/opt/musl-1.2.2/bin/../lib/gcc/:/opt/musl-1.2.2/bin/../lib/gcc/x86_64-linux-musl/9.4.0/../../../../x86_64-linux-musl/lib/:/opt/musl-1.2.2/bin/../x86_64-linux-musl/lib/
[WARNING] COLLECT_GCC_OPTIONS='-z' 'noexecstack' '-o' '/builds/cx-verticals-dev/fabric-routing-ms/target/service' '-static' '-v' '-L/tmp/SVM-7922469978308771623' '-L/usr/lib64/graalvm/graalvm22-ee-java11/lib/static/linux-amd64/musl' '-L/usr/lib64/graalvm/graalvm22-ee-java11/lib/svm/clibraries/linux-amd64' '-mtune=generic' '-march=x86-64'
[INFO]                       17.1s (8.2% of total time) in 112 GCs | Peak RSS: 16.77GB | CPU load: 11.12
[WARNING]  /opt/musl-1.2.2/bin/../libexec/gcc/x86_64-linux-musl/9.4.0/collect2 -plugin /opt/musl-1.2.2/bin/../libexec/gcc/x86_64-linux-musl/9.4.0/liblto_plugin.so -plugin-opt=/opt/musl-1.2.2/bin/../libexec/gcc/x86_64-linux-musl/9.4.0/lto-wrapper -plugin-opt=-fresolution=/tmp/ccp8fAue.res -plugin-opt=-pass-through=-lgcc -plugin-opt=-pass-through=-lgcc_eh -plugin-opt=-pass-through=-lc --sysroot=/opt/musl-1.2.2/bin/../x86_64-linux-musl -m elf_x86_64 -static -o /builds/cx-verticals-dev/fabric-routing-ms/target/service -z noexecstack /opt/musl-1.2.2/bin/../lib/gcc/x86_64-linux-musl/9.4.0/../../../../x86_64-linux-musl/lib/crt1.o /opt/musl-1.2.2/bin/../lib/gcc/x86_64-linux-musl/9.4.0/../../../../x86_64-linux-musl/lib/crti.o /opt/musl-1.2.2/bin/../lib/gcc/x86_64-linux-musl/9.4.0/crtbeginT.o -L/tmp/SVM-7922469978308771623 -L/usr/lib64/graalvm/graalvm22-ee-java11/lib/static/linux-amd64/musl -L/usr/lib64/graalvm/graalvm22-ee-java11/lib/svm/clibraries/linux-amd64 -L/opt/musl-1.2.2/bin/../lib/gcc/x86_64-linux-musl/9.4.0 -L/opt/musl-1.2.2/bin/../lib/gcc -L/opt/musl-1.2.2/bin/../lib/gcc/x86_64-linux-musl/9.4.0/../../../../x86_64-linux-musl/lib -L/opt/musl-1.2.2/bin/../x86_64-linux-musl/lib --gc-sections -x service.o /usr/lib64/graalvm/graalvm22-ee-java11/lib/static/linux-amd64/musl/libnet.a /usr/lib64/graalvm/graalvm22-ee-java11/lib/static/linux-amd64/musl/libjavajpeg.a /usr/lib64/graalvm/graalvm22-ee-java11/lib/static/linux-amd64/musl/libextnet.a /usr/lib64/graalvm/graalvm22-ee-java11/lib/static/linux-amd64/musl/libnio.a /usr/lib64/graalvm/graalvm22-ee-java11/lib/svm/clibraries/linux-amd64/liblibchelper.a /usr/lib64/graalvm/graalvm22-ee-java11/lib/static/linux-amd64/musl/libjava.a /usr/lib64/graalvm/graalvm22-ee-java11/lib/static/linux-amd64/musl/liblcms.a /usr/lib64/graalvm/graalvm22-ee-java11/lib/static/linux-amd64/musl/libawt_headless.a /usr/lib64/graalvm/graalvm22-ee-java11/lib/static/linux-amd64/musl/libawt.a /usr/lib64/graalvm/graalvm22-ee-java11/lib/static/linux-amd64/musl/libfdlibm.a /usr/lib64/graalvm/graalvm22-ee-java11/lib/static/linux-amd64/musl/libsunec.a /usr/lib64/graalvm/graalvm22-ee-java11/lib/static/linux-amd64/musl/libzip.a /usr/lib64/graalvm/graalvm22-ee-java11/lib/svm/clibraries/linux-amd64/libjvm.a -lg1gc-cr -ldl -lm -lpthread -lstdc++ -lstdc++ -lm -lstdc++ -lz -lpthread -ldl -lrt --start-group -lgcc -lgcc_eh -lc --end-group /opt/musl-1.2.2/bin/../lib/gcc/x86_64-linux-musl/9.4.0/crtend.o /opt/musl-1.2.2/bin/../lib/gcc/x86_64-linux-musl/9.4.0/../../../../x86_64-linux-musl/lib/crtn.o
[INFO] ========================================================================================================================
[INFO] Failed generating 'service' after 3m 28s.
[WARNING] /opt/musl-1.2.2/bin/../lib/gcc/x86_64-linux-musl/9.4.0/../../../../x86_64-linux-musl/bin/ld: /usr/lib64/graalvm/graalvm22-ee-java11/lib/svm/clibraries/linux-amd64/libg1gc-cr.a(os_linux.o): in function 'os::Linux::active_processor_count()':
[WARNING] os_linux.cpp:(.text+0x113e): undefined reference to '__sched_cpualloc'
[WARNING] /opt/musl-1.2.2/bin/../lib/gcc/x86_64-linux-musl/9.4.0/../../../../x86_64-linux-musl/bin/ld: os_linux.cpp:(.text+0x11b0): undefined reference to __sched_cpufree
[WARNING] collect2: error: ld returned 1 exit status
[WARNING] 	at com.oracle.svm.hosted.image.NativeImageViaCC.handleLinkerFailure(NativeImageViaCC.java:505)
[WARNING] 	at com.oracle.svm.hosted.image.NativeImageViaCC.write(NativeImageViaCC.java:452)
[WARNING] 	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:695)
[WARNING] 	at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:515)
[WARNING] 	at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:407)
[WARNING] 	at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:585)
[WARNING] 	at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:128)
[WARNING] 	at com.oracle.svm.hosted.NativeImageGeneratorRunner$JDK9Plus.main(NativeImageGeneratorRunner.java:615)
[WARNING] Error: Image build request failed with exit status 1`

**Comment by christianhaeubl** [comment]
This use case will be supported in GraalVM 22.3.
