### ISSUE TITLE
Is there any Native support for Huawei and Windows mobile phone?

### ISSUE THREAD

**Issue by ctoabidmaqbool** [oracle/graal#4560]
Natives support of IOS and Android is exists there.

In a same why any chances of native support of **Huawei and Windows mobile phone**?

**Comment by linghengqian** [comment]
As far as I know, Huawei's Android compatibility layer makes its development no different from pure natural AOSP. Can you provide a failed demo?

**Comment by ctoabidmaqbool** [comment]
> As far as I know, Huawei's Android compatibility layer makes its development no different from pure natural AOSP. Can you provide a failed demo?

Let see, https://esaleanalyst.com/res/eSales%20Analyst%202022.04.26.apk

**Comment by oubidar-Abderrahim** [comment]
Hi, Thank you for your suggestion, although some support for Android and IOS is there, it does not come from the GraalVM team but from the GluonHQ team.
On GraalVM's side, we do not have plans currently to support mobile platforms, but that may change in the future.
I believe it would make more sense to open an issue to https://github.com/gluonhq/substrate regarding this.
