### ISSUE TITLE
GraalServices is not OSGi friendly on stock JDK.

### ISSUE THREAD

**Issue by eerierye** [oracle/graal#4564]
I am working on embedding Graal-JS into an OSGi application. We are using openJDK11.

We have successfully gotten Graal JS running and the Graal compiler optimizing it (its not running in the interpreted mode.) We did need to make some changes to the GraalServices class though.

It would be ideal if some changes can be made that would support both JPMS and OSGi. We are not asking you to distribute with OSGi meta data etc.

**The problem:**
There is code in the GraalServices class that cannot execute if in an unnamed module. In OSGi 

https://github.com/oracle/graal/blob/release/graal-vm/22.0/compiler/src/org.graalvm.compiler.serviceprovider.jdk11/src/org/graalvm/compiler/serviceprovider/GraalServices.java#L142

The module layer is null in an unnamed module, and an NPE is thrown. We changed to `ServiceLoader.load(service)`

and 

https://github.com/oracle/graal/blob/release/graal-vm/22.0/compiler/src/org.graalvm.compiler.serviceprovider.jdk11/src/org/graalvm/compiler/serviceprovider/GraalServices.java#L157

will also fail due to being in an unnamed module.

The solution for us was to remove the module layer argument and to open access via JVM arguments rather than in Graal (i.e. remove the call to openJVMCITo() and use --add-exports).

**Possible solution for all:**

Would it be possible to have some logic that will support non OSGi and OSGi?
I believe GRPC did something similar, see https://github.com/grpc/grpc-java/pull/3479/files and https://github.com/grpc/grpc-java/issues/3273

**Comment by oubidar-Abderrahim** [comment]
Thank you for your suggestion, we will take a look into it and get back to you

**Comment by oubidar-Abderrahim** [comment]
Tracked internally on GR--38726

**Comment by dougxc** [comment]
@eerierye can you please submit your changes as a pull request.

**Comment by dougxc** [comment]
Thinking about this more, we cannot allow GraalServices to load arbitrary code as it potentially opens a hole in a trusted component (i.e. the Graal compiler).

**Comment by ravise5** [comment]
@eerierye How did you embed the graal.js into an osgi bundle. I tried embedding as shown below:
`                        <Embed-Dependency>org.graalvm.sdk:graal-sdk,org.graalvm.js:js;scope=runtime,org.graalvm.js:js-scriptengine</Embed-Dependency>
`
But I can't find the `Graal.js` ScriptEngine during runtime. 
Could you please help me here?
