### ISSUE TITLE
Request for improving the documentation of llvm's compilation for rust.

### ISSUE THREAD

**Issue by psvri** [oracle/graal#4571]
**Feature request**

**Is your feature request related to a problem? Please describe.**
The compiling section of llvm documentation for rust can use some improvements. 

- Most of the times the users of rust ecosystem always use cargo to build their rust projects and very rarely interact with rustc. So it would be good if this section is updated with build details using cargo.
- Also due to rust's release cycle of 6weeks for , it would be better to mention which rust version we should be using. The reasoning being currently when I try to run hello world program in rust 1.60, I get the below output

```
Hello, world!
Unsupported opCode in constant block: 30
        at <llvm> __rust_begin_short_backtrace<fn(), ()>(Unknown)
        at <llvm> {closure#0}<()>(../../../../rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/rt.rs:145:0)
        at <internal/nfi-native> null(Unknown)
        at <internal/nfi-native> null(Unknown)
        at <llvm> lang_start<()>(../../../../rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/rt.rs:144:0)
        at <llvm> main(hello-e53c0caf0a46590b.bc:main:1:0-29)
```
I am guessing the above error is probably because rustc uses a different llvm version. So such issues can be avoided if the required rust version is mentioned.

**Describe the solution you'd like.**
It would help if the document were updated to have a section on how to compile cargo projects to work with graalvm and the minimum rust version we should be using.

**Describe who do you think will benefit the most.**
New comers of both rust and graalvm.

**Describe alternatives you've considered.**
I havent worked with llvm-irs so I couldn't debug the cause.

I tried compiling the code with the below command

```
rustc -C linker=/home/opc/programs/graalvm-ce-java17-22.1.0/languages/llvm/native/bin/clang -C link-args=-lgraalvm-llvm -Og --emit=llvm-bc src/main.rs 
```

But then the code didn't even print hello world in this case and got the below output

```
 lli --lib $(rustc --print sysroot)/lib/libstd-* main.bc
Unsupported opCode in constant block: 30
        at <llvm> {closure#0}<()>(Unknown)
        at <internal/nfi-native> null(Unknown)
        at <internal/nfi-native> null(Unknown)
        at <llvm> main(../../../../rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/rt.rs:144:0)
```

**Comment by oubidar-Abderrahim** [comment]
Hi, thank you for reporting this. 
Regarding the mentioned issue, indeed in rust 1.60 the supported LLVM version is LLVM 14 while we use LLVM 12 in GraalVM, support for LLVM 14 is planned in 22.2.0 coming next July. But until then, you should use 1.55 or lower as this is the last version to support LLVM 12.

**Comment by oubidar-Abderrahim** [comment]
Tracked internally on GR--38770

**Comment by psvri** [comment]
@oubidar-Abderrahim 
Thanks for the info. 
Using rust 1.55 solved the issue.

**Comment by wirthi** [comment]
According to our internal information, this has been resolved in GraalVM. 22.2.
