### ISSUE TITLE
CPUSampler doesn't register anything

### ISSUE THREAD

**Issue by marad** [oracle/graal#4573]
**Describe GraalVM and your environment :**
 - GraalVM version or commit id if built from source: 22.1.0
 - CE or EE: CE
 - JDK version: JDK 17
 - OS and OS Version: Same on Windows and on Arch Linux
 - Architecture: amd64
 - The output of `java -Xinternalversion`:
 For Windows
```
OpenJDK 64-Bit Server VM (17.0.3+7-jvmci-22.1-b06) for windows-amd64 JRE (17.0.3+7-jvmci-22.1-b06), built on Apr 20 2022 05:05:02 by "" with MS VC++ 16.8 / 16.9 (VS2019)
```
For Linux
```
OpenJDK 64-Bit Server VM (17.0.3+7-jvmci-22.1-b06) for linux-amd64 JRE (17.0.3+7-jvmci-22.1-b06), built on Apr 20 2022 11:56:33 by "buildslave" with gcc 10.3.0
```

**Have you verified this issue still happens when using the latest snapshot?**
No

**Describe the issue**
CPUSampler doesn't register anything. Tried debugging it and it seems to not find any stack frames in `SafepointStackSampler.SampleAction.perform()`. Somehow `getStacks()` always return empty list.
Tried setting `--engine.TraceStackTraceInterval=1000` and stack traces seemed all right, but CPUSampler still didn't register anything.

**Code snippet or code repository that reproduces the issue**
Run this test from this commit. Observe empty CPUSampler results.
https://github.com/marad/chi-compiler-kotlin/blob/2ab26eb3267076a44b834a156b4e2e08ff02ba60/chi-truffle-language/src/test/java/InterpreterTest.java#L61-L72

**Steps to reproduce the issue**

1. git clone https://github.com/marad/chi-compiler-kotlin.git
2. cd chi-compiler-kotlin/
3. git checkout 2ab26eb
4. ./gradlew :chi-truffle-language:test -i --tests "InterpreterTest.fibonacci_test" --console=plain
5. Scroll up a bit to see empty CPUSampler output

**Expected behavior**
CPUSampler should have collected some samples.

**Additional context**
CPUSampler output:
![image](https://user-images.githubusercontent.com/1618489/168483281-1dc830c7-1c62-4c92-82cb-c99c066e616c.png)

**Comment by smarr** [comment]
@marad I quickly looked through https://github.com/marad/chi-compiler-kotlin.git but this doesn't look like a Truffle language. https://github.com/marad/chi-compiler-kotlin/blob/main/src/main/kotlin/gh/marad/chi/interpreter/Interpreter.kt doesn't use the Truffle framework. Though, the CPUSampler is designed for languages that are implemented with the framework.

For an example, you may want to look at Simple Language here: 
https://github.com/graalvm/simplelanguage
The code here is pretty well documented: https://github.com/graalvm/simplelanguage/tree/master/language/src/main/java/com/oracle/truffle/sl

**Comment by marad** [comment]
@smarr Look at the commit I've included. I'm in the middle of making it a truffle language.

**Comment by smarr** [comment]
I'd assume that you need to give your root nodes at least a source section (`getSourceSection`) and a name (`getName`).

**Comment by marad** [comment]
@smarr Yesss! This is exactly what I was missing. I thought about the name, but I didn't suspect that missing source section would have such impact on this.

**Comment by marad** [comment]
@smarr Maybe CPUSampler should display some warning about missing name/source section instead of just printing empty results?

**Comment by smarr** [comment]
Are you sure about the safe point poll? If I remember correctly, Truffle does them on function calls implicitly.

And about name and source section, that's likely documented in the bits on the instrumentation API. @chumer would know for sure.

**Comment by marad** [comment]
@smarr You are absolutely right. First time I read [this](https://www.graalvm.org/truffle/javadoc/com/oracle/truffle/api/TruffleSafepoint.html) I noted that it's called by default in the loops, but it's also called in the root nodes so there is no need to add `TruffleSafepoint.poll(this)` by yourself in simple cases.
