### ISSUE TITLE
[GR-38762] Fix errors in debug info param/local var generation and testing on AArch64.

### ISSUE THREAD

**Issue by adinn** [oracle/graal#4582]
Debug info param/local var generation and the associated tests is not fully complete on AArch64.

The generation problems are:

1. Some register passed parameters are associated with the wrong register on AArch64
2. Some stack passed parameters are looked up at the wrong locations because different adjustments are needed before and after stack push to allow for stacked return address and frame pointer.

The test problems are:
1. The check to test the value of passed parameters relies on a method break being placed at the first instruction of the method which is only true on AMD64
2. The check performs the stack adjustment occurs in one instruction which is only true on AMD64
4. The check tests for an x86 format sub instruction as a sanity check which is only appropriate for AArch64

**Comment by adinn** [comment]
@fniephaus @olpaw Could you please assign this to me and also review the associated PR that fixes this issue #4581

**Comment by fniephaus** [comment]
Fixed via https://github.com/oracle/graal/commit/ceea361a4d14f8cca11b0ab79ece69906110b040.
