### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by edrobal** [oracle/graal#4583]
[hs_err_pid6600.log](https://github.com/oracle/graal/files/8715937/hs_err_pid6600.log)
**Describe the issue**
Netbeans crash often and I have this kind of log.

**Describe GraalVM and your environment:**
openjdk version "11.0.14.1" 2022-02-08
OpenJDK Runtime Environment (build 11.0.14.1+1-suse-3.77.5-x8664)
OpenJDK 64-Bit Server VM (build 11.0.14.1+1-suse-3.77.5-x8664, mixed mode)

 - OS: Linux 5.3.18-150300.59.63-default #1 SMP Tue Apr 5 12:47:31 UTC 2022 (d77db66) x86_64 x86_64 x86_64 
 - Architecture: AMD64

```

**Comment by edrobal** [comment]
latest version of which ?

**Comment by oubidar-Abderrahim** [comment]
GraalVM CE 21.3.2

**Comment by edrobal** [comment]
I can't use this version since Java has abandoned backward compatibility.

**Comment by oubidar-Abderrahim** [comment]
What do you mean by "abandoned backward compatibility"? what I wanted to ask is to test the latest version of GraalVM, not of Java, now it should be GraalVM CE java11 21.3.3 (which is built on openJDK version "11.0.16").
Please give this version a try and share your finding, you can download it from here: https://github.com/graalvm/graalvm-ce-builds/releases/tag/vm-21.3.3

**Comment by oubidar-Abderrahim** [comment]
Closed for inactivity
