### ISSUE TITLE
Code cache related JVM crash with OpenJDK 11 + Jargraal: unsafe access to zombie method

### ISSUE THREAD

**Issue by martinhiller** [oracle/graal#4584]
**Describe the issue**

We are experiencing occasional JVM crashes in our application because an internal guarantee in the code cache is violated:

```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  Internal Error (./src/hotspot/share/code/codeCache.cpp:630), pid=5508, tid=6388
#  guarantee(result == NULL || !result->is_zombie() || result->is_locked_by_vm() || VMError::is_error_reported()) failed: unsafe access to zombie method
#
# JRE version: OpenJDK Runtime Environment Temurin-11.0.15+10 (11.0.15+10) (build 11.0.15+10)
# Java VM: OpenJDK 64-Bit Server VM Temurin-11.0.15+10 (11.0.15+10, mixed mode, tiered, jvmci, compressed oops, g1 gc, windows-amd64)
# Core dump will be written. Default location: C:\<APPLICATION>\hs_err_pid5508.mdmp
#
# If you would like to submit a bug report, please visit:
#   https://github.com/adoptium/adoptium-support/issues
#
```

**Steps to reproduce the issue**

Unfortunately, we were not able to find a stable and minimal reproduction yet.

**Describe GraalVM and your environment:**
- JDK: **OpenJDK 11.0.15**
- GraalVM version: **21.3.0** but also reproduced with **22.1.0**
- OS: **Windows Server 2019** but also observed on **Windows 10**
- Architecture: **windows-amd64**

**More details**
You can find the full log here (with some parts redacted): [hs_err_pid5508.log](https://github.com/oracle/graal/files/8717380/hs_err_pid5508.log)

The crash mostly happens during bootstrap of our application (which is when lots of JavaScript code is executed with GraalJS and probably JIT-compiled). In general, the crash is fairly rare and sporadic: Sometimes the application starts up 100 times in succession, but sometimes every other start can result in this crash.

We already experimented with lots of different configurations to come closer to a solution but we are not there yet. Our main observations are:

- Increasing the code cache size (e.g., with `-XX:ReservedCodeCacheSize=512m`) makes the crash less likely. Maybe because a larger code cache reduces the number of code cache sweeps?

- Switching from G1 to another GC (such as SerialGC or ParallelGC) seems to prevent the crash altogether (or makes the crash so rare that we have not observed it yet).

- The crashes happen both with Graal 21.3.0 and Graal 22.1.0. Falling back to C2 (with JavaScript executed in interpreter mode) seems to fix it.

- We have not observed the crash running on GraalVM 22.1.0 with Libgraal yet, but we need to test this scenario more to be sure.

Do you have any suggestions what else we can do to understand this issue better and deliver more useful data?

**Comment by oubidar-Abderrahim** [comment]
Hi, thank you for reporting this, we're going to take a look into this and get back to you

**Comment by oubidar-Abderrahim** [comment]
For reference; the issue is tracked internally on GR--40371. in the meantime, if you can test using the latest release (22.2.0 or 21.3.3), please do so and confirm if you're still facing the same issue? Thank you

**Comment by dougxc** [comment]
The crash in [`hs_err_pid5508.log`](https://github.com/oracle/graal/files/8717380/hs_err_pid5508.log) is not on GraalVM (`Java VM: OpenJDK 64-Bit Server VM Temurin-11.0.15+10`). There could be a bug fix difference between labsjdk and the adoptium JDK used by this runtime. Furthermore, the stack trace in `hs_err_pid5508.log` has no symbols so it's hard to know where in the VM the error is coming from.
If you can reproduce on a GraalVM binary and also attach the `*.mdmp` file, we may have more chance of debugging this.

**Comment by martinhiller** [comment]
Thank you for the response!

We have sinced moved on to Java 17, so we will try to reproduce this issue again on the most recent Adoptium JDK 17 build + most recent Graal compiler, as well as on the full GraalVM distribution.

We will keep you posted in this ticket.

**Comment by martinhiller** [comment]
Thank you for your patience!

The crash is still reproducible with Adoptium JDK 11.0.16 and Graal 22.2.0 compiler (see [hs_err_pid5336.log](https://github.com/oracle/graal/files/9574218/hs_err_pid5336.log)), but we can say with great confidence that the issue is gone if we use the JDK 11 based GraalVM 22.2.0.

With Java 17, the crashes seem to be entirely gone, whether we use Adoptium JDK 17.0.4 + Graal 22.2.0 compiler, or the JDK 17 based GraalVM 22.2.0.

As far as we are concerned, this issue can be closed. Thank you again!

**Comment by ergenbao** [comment]
We encountered similar problems.That’s the relevant error log。

[hs_err_pid1.log](https://github.com/oracle/graal/files/15234469/hs_err_pid1.log)



> 崩溃[`hs_err_pid5508.log`](https://github.com/oracle/graal/files/8717380/hs_err_pid5508.log)不在 GraalVM ( `Java VM: OpenJDK 64-Bit Server VM Temurin-11.0.15+10`) 上。 labsjdk 和该运行时使用的 Adoptium JDK 之间可能存在错误修复差异。此外，堆栈跟踪`hs_err_pid5508.log`没有符号，因此很难知道错误来自虚拟机中的何处。 如果您可以在 GraalVM 二进制文件上重现并附加文件`*.mdmp`，我们可能有更多的机会对此进行调试。

**Comment by dougxc** [comment]
> We encountered similar problems.That’s the relevant error log

The details in `hs_err_pid1.log` show that this is not a Graal related JVM:
```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007faca0137b57, pid=1, tid=0x00007fac9e36d700
#
# JRE version: Java(TM) SE Runtime Environment (8.0_251-b08) (build 1.8.0_251-b08)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.251-b08 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# V  [libjvm.so+0x9f0b57]  ContiguousSpace::par_oop_iterate(MemRegion, ExtendedOopClosure*)+0x47
#
# Core dump written. Default location: /service/app/core or core.1
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
#
```
