### ISSUE TITLE
GraalCE 1.0-rc2 is slower than nashorn on nbody from the languages shootout

### ISSUE THREAD

**Issue by markehammons** [oracle/graal#459]
When comparing graal to nashorn I found that CE is running slower than nashorn. This doesn't seem like it should be happening, as EE completely blows nashorn out of the water on this bench with a ~5x speedup.

[ce_results.txt](https://github.com/oracle/graal/files/2086354/ce_results.txt)
[ee_results.txt](https://github.com/oracle/graal/files/2086355/ee_results.txt)
[ojdk_results.txt](https://github.com/oracle/graal/files/2086394/ojdk_results.txt)

The long and short of the benches are: 

EE optimizes the code as it is run, and generally speeds up from 10s cold run to 7-6s warm run. Openjdk nashorn shows no improvement as it's run and takes around 32-35s. CE similarly shows no improvement from warmup, and runs even slower than nashorn, taking about 8-10s more to run the aforementioned bench. I've tested against graal ce 1.0-rc1 and this behavior is not a regression. I've also tried running the bench straight from the languages shootout with the ```node``` command and get similar performance as above.

You can use [this project](https://github.com/markehammons/languageshootout-jmh) to perform the benchmarking on your own machine. I tested with ```sbt "jmh:run -jvm /path/to/graal/or/openjdk/java n_body"```

[here is a link to the source code of the benchmark in question](https://github.com/markehammons/languageshootout-jmh/blob/master/src/main/scala/mhammons/cnrs/n_body_nashorn.scala) should you wish to look into what it's doing. I currently just use the old nashorn API, as it became obvious when I was first testing that both CE & EE use the polyglot engine to replace nashorn, making it easy to swap them out and test against openjdk. 

I used openjdk-8 from opensuse tumbleweed as the nashorn comparison.

I'm aware that graal EE is supposed to be more performant than CE, but in the other benches I've run it's more on the order of 10-20% speedup.

**Comment by thomaswue** [comment]
Thanks for reporting. This seems indeed like a bug. We will look into it. Good to see the ~5x speed up still ;).

**Comment by thomaswue** [comment]
@brettwooldridge Our benchmarks indicate on average more than a factor 2 better JavaScript performance vs Nashorn with GraalVM CE. And another factor on top of that with GraalVM EE.

The benchmark in question here is heavily dependent on handling of JavaScript objects with 7 primitive number fields and no object fields. This is not your average case outside of physics simulations.

What type of JavaScript programs are you currently running on Nashorn?

**Comment by spavlusieva** [comment]
hi @markehammons , this issue has been inactive for more than 180 days. We’ll close it to focus on current issues. In case it’s still relevant, please reopen it and we’ll take another look. Thank you!
