### ISSUE TITLE
[native-image] Runtime error when using java.lang.reflect.Array in library

### ISSUE THREAD

**Issue by dr-eme** [oracle/graal#4590]
**Describe the issue**
Native application throws `com.oracle.svm.core.jdk.UnsupportedFeatureError` in runtime, while using `java.lang.reflect.Array` to generate a new instance of an object encapsulated in a generic. Adding a type hint did not solve the issue.

The error is observed only when such operation is inside a dependency. Extracting the code from the library and putting it into the application being compiled, seem to trigger a proper reflection autoconfiguration.

It would be interesting to understand how that specific reflection hit can be provided in the native-image configuration.

**Steps to reproduce the issue**
Please include both build steps as well as run steps
1. Extract all files from the attached `sample.tar.gz`
2. Compile and run the native application `./gradlew nativeRun`
3. The extracts that works in the application can be tested by uncommenting lines 29-33 and/or lines 38-39 in the source file CLR.java

**Describe GraalVM and your environment:**
 - GraalVM version CE 22.1.0
 - JDK major version: 17
 - OS: macOS Monterrey
 - Architecture: aarch64
However, the issue has been reproduced as well on our CI pipeline, that runs on GraalVM CE 21.3.0, JDK 11, Linux AMD64

**More details**
```
com.oracle.svm.core.jdk.UnsupportedFeatureError: Cannot allocate 2-dimensional array of org.hipparchus.analysis.differentiation.Gradient
        at com.oracle.svm.core.util.VMError.unsupportedFeature(VMError.java:89) ~[na:na]
        at java.lang.reflect.Array.multiNewArray(Array.java:382) ~[na:na]
        at java.lang.reflect.Array.newInstance(Array.java:114) ~[na:na]
        at org.hipparchus.util.MathArrays.buildArray(MathArrays.java:1656) ~[na:na]
        at org.hipparchus.geometry.euclidean.threed.FieldRotation.<init>(FieldRotation.java:249) ~[na:na]
        at com.example.commandlinerunner.CLR.run(CLR.java:47) ~[commandlinerunner-gradle:na]
...
```
[sample.tar.gz](https://github.com/oracle/graal/files/8743164/sample.tar.gz)

**Comment by oubidar-Abderrahim** [comment]
Hi, thank you for reporting this, we're going to take a look into this and get back to you

**Comment by oubidar-Abderrahim** [comment]
If this issue is still relevant on our latest GraalVM version, please create a new issue and share a reproducer on a Github repository. Thank you
