### ISSUE TITLE
[GR-38835] native-image performance regression when using debug-info generation

### ISSUE THREAD

**Issue by olpaw** [oracle/graal#4595]
Merging of https://github.com/oracle/graal/pull/4505 introduced a native-image performance regression when images are built with debug-info. Using `-g` should not have an affect on the performance of the image that gets built.

**Comment by olpaw** [comment]
@adinn enabling full infopoints cause performance regressions in the runtime of images. (Of course debug info generation time also increased due to debug location info generation but this is not the concern here.)

@farquet provided me with the numbers:
![image](https://user-images.githubusercontent.com/16901644/170294467-c60671eb-9237-42d4-bde2-a794d32087ce.png)
He might be able to provide more pointer to the actual benchmarks results.

Full infopoints keep locals alive beyond the point they would otherwise be the end of their live-range. This has a negative impact on optimizations.

**Comment by adinn** [comment]
@olpaw Thanks for providing those figures. That's definitely a significant regression :-(

**Comment by farquet** [comment]
Benchmark numbers are public: https://graal.d3s.mff.cuni.cz/see/overview

You can browse individual performance regressions/speedups and it will tell you more about the JVM configuration, the absolute scores, candidate culprit commits, hardware info, etc
