### ISSUE TITLE
[Graal-SDK-22.0.0V (and up)] - SyntaxError for passing JsonArray as argument

### ISSUE THREAD

**Issue by DaniShMyGit** [oracle/graal#4602]
Hi,
Lately I updated the graal sdk library from 21.3.2V to 22.1.0V and got some issues with few of my junit tests.
I have the following javascript arrow function:
```
(param1, param2, param3, param4) => { const input = JSON.parse(param4); return param1 + param2 * param3 * input[0]; }

```

And those are the arguments I'm injecting to the function:
```
JsonArray().add("str").add(2).add(3.3).add(JsonArray().add(1))
```

(I'm using vertx JsonArray - io.vertx.core.json)

The test fails on when trying to execute the evaluated expression with the provided arguments:
```
evaluatedExpr.execute(*arguments) // "str", 2, 3.3, [1]

```

The failure I'm getting is: 
```
SyntaxError: Unexpected token o in JSON at position 1
org.graalvm.polyglot.PolyglotException: SyntaxError: Unexpected token o in JSON at position 1
	at <js>.:=>(Unnamed:1)
	at app//org.graalvm.polyglot.Value.execute(Value.java:841)

```

This unit test is working in V21.3.2 (and below) but now with the newer version is failed and I can't understand why.
I'll appreciate any help!

**Comment by oubidar-Abderrahim** [comment]
Hi, Thank you for reporting this, could you please share a reproducer to illustrate this issue?

**Comment by oubidar-Abderrahim** [comment]
Any updates on the reproducer?

**Comment by oubidar-Abderrahim** [comment]
Closing the issue for inactivity
