### ISSUE TITLE
Agent-created serialization-config.json invalid format for native image build

### ISSUE THREAD

**Issue by matusfaro** [oracle/graal#4609]
Using `native-maven-plugin`, Tracing Agent during tests produces a `agent-output` folder. If I pass these generated configs as-is to native image build, it's unable to parse `serialization-config.json`:
```
Error: Error parsing serialization configuration in jar:file:/project/target/<redacted>-1.0.0-SNAPSHOT.jar!/META-INF/native-image/agent-output/test/session-70117-20220531T082209Z/serialization-config.json:
first level of document must be an array of serialization lists
```
`serialization-config.json`:
```json
{
  "types":[
    {
      "name":"org.junit.platform.launcher.TestIdentifier$SerializedForm"
    },
    {
      "name":"org.junit.runner.Result$SerializedForm"
    }
  ],
  "lambdaCapturingTypes":[
  ]
}
```

**Environment**
 - `native-maven-plugin` version 0.9.11
 - graalvm-ce-java17-22.1.0
 - OS: macOS Monterey
 - Architecture: x86_64

**Comment by oubidar-Abderrahim** [comment]
Hi, please use our latest GraalVM version and see if the problem is still occurring. If so, you can reopen this ticket and provide a reproducer. Thank you
