### ISSUE TITLE
[GR-39204] Develop enviroment container

### ISSUE THREAD

**Issue by cyw3** [oracle/graal#4610]
Hi,

Can you provide a develop enviroment docker container of graal?
Developers can use it and don't need to deploy the build environment again.

Thanks!

**Comment by fniephaus** [comment]
Hi @cyw3,
We do provide Docker images:

- GraalVM Community Edition images are at https://github.com/orgs/graalvm/packages
- GraalVM Enterprise Edition images are at https://container-registry.oracle.com/

More download options are available at https://www.graalvm.org/downloads/

In case you were asking for Docker images for developing the Graal compiler, Truffle languages, and other GraalVM components, I don't think we can provide them in a reasonable way as development processes can change over time.

**Comment by cyw3** [comment]
What i need is the docker images for developing the Graal compiler.

Maybe you can use devcontainer with vscode remote-container to provide them.

**Comment by fniephaus** [comment]
Ok, so you are indeed looking for a pre-configured dev environment for GraalVM development. I believe all we could provide is an environment that comes with the main repo checked out, mx installed, and an appropriate LabsJDK. Would that work for you, @cyw3?

**Comment by cyw3** [comment]
Yes, thank you.

**Comment by cyw3** [comment]
#4624

I have a try for it.

**Comment by fniephaus** [comment]
#4624 is now merged! :tada:
