### ISSUE TITLE
Add Loom support (VirtualThreads) to GraalVM

### ISSUE THREAD

**Issue by gato** [oracle/graal#4621]
Add Loom support (Virtual Threads) to current version of GraalVM

**Is your feature request related to a problem? Please describe.**
I've built GraalVM using Loom preview binaries as base. Building process worked flawlessly and projects that uses Loom's Virtualthreads can be built as well, but then fail when running more than a couple thousands Vthreads (threads start to hang with no visible error or exception) 

**Describe the solution you'd like.**
Binary GraalVM distribution with Loom's Virtual Threads support

**Describe who do you think will benefit the most.**
GraalVM users, anyone that needs to create many threads that are basically I/O bound. 

**Describe alternatives you've considered.**
Building GraalVM from source.

**Comment by dougxc** [comment]
This will be delivered as part of the first GraalVM release based on JDK 19. The earliest ETA for that is GraalVM 22.3.

**Comment by gato** [comment]
Thanks! eager to try it :)

**Comment by zakkak** [comment]
> Virtual Threads support has landed in GraalVM Native Image (see #4802). rocket

Source https://github.com/oracle/graal/issues/4920#issuecomment-1268405609
