### ISSUE TITLE
[GR-10518] Native Image heap dumps are polluted by objects created during heap dump creation

### ISSUE THREAD

**Issue by fniephaus** [oracle/graal#4637]
When dumping the heap of a native executable to analyze it in VisualVM, the heap dump is polluted by objects that are created during the heap dump creation.

This makes it hard to analyze smaller heap dumps, especially initial heaps obtained through [`-XX:+DumpHeapAndExit`](https://github.com/oracle/graal/pull/4622), as they are often dominated by the objects created during heap dump creation. Here's an example screenshot of a heap dump for a native `HelloWorld`:
![Screenshot from 2022-06-10 14-45-41](https://user-images.githubusercontent.com/2368856/173067187-28873655-1b97-4e8b-94b2-a16b87fbd31a.png)

The heap dump pollution can be avoided by using only unmanaged, native memory within the heap dump writer rather than managed, heap-allocated objects.

**Comment by fniephaus** [comment]
It seems that the heap dump writer also allocates numerous strings and other objects. Most notably, it seems to allocate 5700+ strings with a value of `utf-8`: 

![image](https://user-images.githubusercontent.com/2368856/173067803-2eced19c-e90e-478d-b29f-42c2be8fce33.png)

**Comment by SergejIsbrecht** [comment]
How about writing out the metadeta (HeapdumpWriterImpl) needed to write the hprof file to an extra file during generation, later on, when an dump should happen, the file will be mapped into memory and used to write the hprof file.
