### ISSUE TITLE
Add support for user defined type casts when crossing from non Java to Java language

### ISSUE THREAD

**Issue by pmlopes** [oracle/graal#464]
One feature that for example `Nashorn` has is the support for dynalink. Although dynalink is quite a complex component one feature would be quite nice to have for polyglot integration.

Imagine that we are working with JavaScript and a scripting language and use a Java library (that was not written by you (so you can't modify its source). Now say that the library definesa method:

```java
void methodA(MyCustomType argumentA);
```
From the JavaScript we know that it is easy to convert a JS object to `MyCustomType` using some small line of code, but doing it in JS everywhere would make the code less readable, so it would be nice that in the internals of the `Value` class we could be able to register converters, for example:

```java
  @Override
  public GuardedInvocation convertToType(Class<?> sourceType, Class<?> targetType, Supplier<MethodHandles.Lookup> lookupSupplier) {
    if (targetType.isAssignableFrom(JsonObject.class)) {
      return new GuardedInvocation(TO_JSONOBJECT);
    }
    if (targetType.isAssignableFrom(JsonArray.class)) {
      return new GuardedInvocation(TO_JSONARRAY);
    }
    // we can't convert
    return null;
  }
```

**NOTE** this is the API of Nashorn but not necessarely required to be like this (this is just for illustration purposes) If we would add converters we could see what converters are already available using the last argument, and then given the source/target (most likely only the target would be important to know) it should allow me to add these custom converters

This will remove many casts from the embedded languages and make scripting easier/cleaner imho.

Probably something like:

```java
Function<R, Value> convertToType(Class<?> targetType, Registry converterRegistry);
```

would be enough (again types just for illustration), given a class return a function that receives a `Value` and returns the matches class, or null if cannot handle it.

returning null would allow going deeper in the lookup list until a proper match is found...

**Comment by chumer** [comment]
@pmlopes what do you think of identity preservation? If you pass the cast value back into JavaScript should it be converted back to the original object?

**Comment by pmlopes** [comment]
I can imagine that that would be nice to have but I also think it could complicate a lot the implementation, as many references between objects would be required. I think that the reverse path could also go through this "interceptor" and would lookup a converter form the Java type to the scripting "type", this would allow users to write the custom converters and probably for cases where both way conversions, they would just rely on "wrapper" objects that would, wrap (when going to java), unwrap (when comming from java). A compromise that would imho avoid many references and pressure on the gc?

**Comment by woess** [comment]
I agree this feature would be nice to have.
Would it be sufficient to have these custom converters only as fallback, i.e., if no other conversions are applicable? Alternatively, we could prioritize them over catch-all conversions (target type `Object`or the like).

**Comment by pmlopes** [comment]
@woess yes, these would be just fallback as I'd expect that most of the times, the default converters are enough.

**Comment by montyz** [comment]
Running into this issue now as we're moving from Nashorn to Graal. Is there any way currently to be able to catch this error and retry with a different type to make it work?

**Comment by boris-spas** [comment]
Tracking internally as Issue GR-20790.

**Comment by chumer** [comment]
Truffle has target type mappings these days (`HostAccess.Builder#targetTypeMapping`) 
I think we can close this.
