### ISSUE TITLE
[GR-39182] Provide `@CEntryPoint`s for advanced debugging

### ISSUE THREAD

**Issue by fniephaus** [oracle/graal#4647]
To further improve the debugging experience of native executables, we need three `@CEntryPoint`s:

- An entry point for allocating an object given a certain class/type, and
- two entry points to pin and unpin an object to ensure that a GC neither collects nor moves them at debugging time.

Potentially, we might want to allow allocating an object that is already pinned if the operation needs to be atomic.

**Comment by fniephaus** [comment]
@vvlevchenko has started to work on this and might provide an initial implementation for this soon.

**Comment by peter-hofer** [comment]
See #5184 for the current design of the advanced debugging API using JNI, addressing the issues of #4723. I have been busy with the 22.3 release up until now and there are quite a few issues that still need to be addressed. @vvlevchenko

**Comment by fniephaus** [comment]
We don't have plans to move this any further. Instead, we are currently working on #5648 and hopefully have something to show.
