### ISSUE TITLE
[GR-39407] Add an env variable like `JAVA_TOOL_OPTIONS`

### ISSUE THREAD

**Issue by dmikusa** [oracle/graal#4650]
**Feature request**

Please include the following information:

**Is your feature request related to a problem? Please describe.**

When running apps with a JVM, you have the option to set flags for the JVM (like `-Xmx`) through the `JAVA_TOOL_OPTIONS` env variable. This is handy in environments where it's not practical or possible to manipulate the process arguments.

Given that you can feed in some GC configuration parameters as process arguments, https://www.graalvm.org/22.1/reference-manual/native-image/MemoryManagement/, it would be convenient if you could do this through an env variable as well.

**Describe the solution you'd like.**

I can understand not wanting to support `JAVA_TOOL_OPTIONS` in GraalVM as it might be confusing or get misused. It would be helpful if we could have a differently named environment variable that functions in the same way. For example, `NATIVE_IMAGE_OPTIONS` or `GRAALVM_OPTIONS`.

**Describe who do you think will benefit the most.**
GraalVM users & developers of libraries and frameworks which depend on GraalVM.

My personal use case is the latter. I work on the Paketo Buildpacks project and we integrate GraalVM into buildpacks. It is tricky and less flexible for our users to set arguments than env variables.

**Describe alternatives you've considered.**

You can set flags as arguments to the process, but this isn't as flexible and causes issues for Cloud-Native buildpack users.

**Additional context.**

N/A

**Express whether you'd like to help contributing this feature**

No

**Comment by fniephaus** [comment]
Hi @dmikusa, while we understand why you'd want this, we share your concerns regarding misuse. Providing the same functionality under a different name won't prevent this. However, maybe #5473 will make it easier to pass in additional arguments from the outside.

**Comment by dmikusa** [comment]
>Providing the same functionality under a different name won't prevent this.

I respectfully disagree. The misuse or perhaps accidental misuse is a better way to describe the concern, comes from the fact that someone would set `JAVA_TOOL_OPTIONS` and entries in said env variable expecting or assuming it to work in the same way that it works with a JVM. Since that does not happen, that would be accidental misuse.

If you change the name of this environment variable then a user must know the name of the environment to add settings through it. To me, that is a user acknowledging the difference, and if they put incorrect settings into a differently named environment variable that is just wrong and the user's fault. A tool can never fully prevent users from making poor choices and incorrectly using the tool.

Not having this on the other hand makes it considerably harder in some environments to pass configuration settings through to the process.

>However, maybe https://github.com/oracle/graal/issues/5473 will make it easier to pass in additional arguments from the outside.

I read through this but I'm not seeing how that would help me pass settings through to the process. Can you expand on your suggestion please?

**Comment by fniephaus** [comment]
>Not having this on the other hand makes it considerably harder in some environments to pass configuration settings through to the process.

That, however, is the point. If the environment can change the configuration arbitrarily, we're going to have a hard time reproducing and debugging problems.

>I read through this but I'm not seeing how that would help me pass settings through to the process. Can you expand on your suggestion please?

These bundles are self-contained and provide everything needed to generate a native executable. This includes sources/jars, dependencies, and *command-line flags*. This means that you can inject options when creating the bundle.

**Comment by dmikusa** [comment]
> > Not having this on the other hand makes it considerably harder in some environments to pass configuration settings through to the process.
> 
> That, however, is the point. If the environment can change the configuration arbitrarily, we're going to have a hard time reproducing and debugging problems.

I agree that it's one more place where a user can change inputs to a program and hence possibly impact the execution of that program, but it's permissible to pass additional configuration as arguments to the program already, why is doing it via env variables that different? You already need to know the user's arguments, so the question when troubleshooting an issue just becomes "Did you set any arguments or pass flags through the environment?".

For what it's worth, the JVM handles this by logging the flags it finds when they are set through the env. That seems perfectly reasonable here as well.

Environment variable configuration is quite popular. Spring Boot allows one to do this, among other configuration options. It's also popular in container-based deployments (i.e. Docker & K8s) because it is an easy way to pass in configuration. There are also popular tools like `direnv` that help manage configuration through env variables. Supporting this option would make it easier to run native-image binaries in all of these situations, not just with buildpacks.

>> I read through this but I'm not seeing how that would help me pass settings through to the process. Can you expand on your suggestion please?
>
>These bundles are self-contained and provide everything needed to generate a native executable. This includes sources/jars, dependencies, and command-line flags. This means that you can inject options when creating the bundle.

OK, I think I'm following now. I could see that technically solving the issue, but I don't think it would be generally acceptable for our users, especially **production** containers. 

1. I think we'd get pushback from users on the fact that it includes source code. Most of our users do not want source code to be in the final image. I don't fully agree but I often see people wanting basically the opposite, i.e. something as obtuse as possible. Just passing along observations but I believe the thought process is that if a container is compromised, they don't want someone to be able to easily see the code that's running.
2. There's a very strong demand for containers that are as small as possible. We get complaints when there's an extra 20 or 30M we could trim. I don't think users will want to include all of the source and dependencies because this is going to make the container size go up quite a bit.


4.

**Comment by fniephaus** [comment]
May I suggest you join the next [Native Image Committer and Community Meeting](https://github.com/oracle/graal/discussions/3933) (I believe the next one is this Thursday) and add this to the agenda?

**Comment by n3ziniuka5** [comment]
I came across this issue when I was building both native and non-native versions of images for my project. It would be great if there was a consistent way to pass java options to both of these images. `JAVA_TOOL_OPTIONS` is mentioned here, but [JDK_JAVA_OPTIONS](https://stackoverflow.com/questions/52986487/what-is-the-difference-between-jdk-java-options-and-java-tool-options-when-using) might be a more suitable choice for this.

I tried doing this within my docker image, for example with `ENTRYPOINT exec /opt/app $JDK_JAVA_OPTIONS`, but this only works in shell form `ENTRYPOINT` and I am using [distroless](https://github.com/GoogleContainerTools/distroless) as the base which doesn't have a shell. So that's why it would be great to have this built-in.

**Comment by fniephaus** [comment]
Good news: we have [added support for a `NATIVE_IMAGE_OPTIONS` environment variable](https://github.com/oracle/graal/pull/7745), which will ship with GraalVM for JDK 22.

**Comment by n3ziniuka5** [comment]
> We thought about this but in many cases, you'd probably want to add and use some Native Image-specific options, which will not be understood by other JDK tools through either `JAVA_TOOL_OPTIONS` or `JDK_JAVA_OPTIONS`.

You are right, but why would this be a problem? It's just the same as some options are only understood by Java 21 and not by Java 17 or older. You have different runtimes, but the way you pass options to them is consistent - via `JDK_JAVA_OPTIONS`.

The `NATIVE_IMAGE_OPTIONS` is a good addition, but it doesn't solve this issue and it shouldn't be closed. `NATIVE_IMAGE_OPTIONS` is about passing options to the `native-image` command. However, this issue is about passing commands to an already built native image, not `native-image` command itself. For example, you would use `JDK_JAVA_OPTIONS="-Xmx100m" ./my-native-image` to set the heap size.

**Comment by fniephaus** [comment]
> You are right, but why would this be a problem? It's just the same as some options are only understood by Java 21 and not by Java 17 or older. You have different runtimes, but the way you pass options to them is consistent - via JDK_JAVA_OPTIONS.

With something like `JDK_JAVA_OPTIONS="-Ob"`, which would enable quick build mode in Native Image, you wouldn't be able to run anything with `java`:

```
$ export JDK_JAVA_OPTIONS="-Ob"
$ java -m jdk.httpserver
NOTE: Picked up JDK_JAVA_OPTIONS: -Ob
Unrecognized option: -Ob
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```

And that's with the same JDK, not just different version.

> The NATIVE_IMAGE_OPTIONS is a good addition, but it doesn't solve this issue and it shouldn't be closed. NATIVE_IMAGE_OPTIONS is about passing options to the native-image command. However, this issue is about passing commands to an already built native image, not native-image command itself. For example, you would use JDK_JAVA_OPTIONS="-Xmx100m" ./my-native-image to set the heap size.

I think we are confusing build-time and run-time option handling here. Since the description mentions buildpacks, I believe we were only talking about build-time option handling. Are you sure `JDK_JAVA_OPTIONS="-Xmx100m" ./my-native-image` does not work? For compatibility, I'd argue it probably should. And if it doesn't , please file a separate issue so that we can address this.
