### ISSUE TITLE
CLibrary annotation with requireStatic doesn't include library

### ISSUE THREAD

**Issue by davecramer** [oracle/graal#4653]
With the following code

```
@CLibrary(value = "test1", requireStatic = true)
public class HelloWorld {

    @CLibrary(value = "test")
    public static void main(String[] args) {

    }
    
    @CEntryPoint(name="addJ")
    static int addJ(IsolateThread thread, int a, int b) {
        return a+b;
    }
    @CEntryPoint(name="subtractJ")
    static int subtractJ( IsolateThread thread, int a, int b) { return a-b; }
}
```

The linker does try to link test, but not test1

**Comment by oubidar-Abderrahim** [comment]
Hi, Thank you for reporting this, could you please share what version of GraalVM you're using? what OS you're using? and the command used to reproduce this issue? Thank you

**Comment by davecramer** [comment]
Sad that you had to ask for this. I routinely ask my bug reporters for the same :( 

/usr/lib/jvm/graalvm-ce-java11-22.1.0/bin/native-image --verbose -cp build/libs//testnative-1.0-SNAPSHOT.jar  org.postgresql.HelloWorld 

answers 2 of the questions

uname -a
Linux LAPTOP-FQV2GSJC 5.10.60.1-microsoft-standard-WSL2 #1 SMP Wed Aug 25 23:20:18 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
davec@LAPTOP-FQV2GSJC:/mnt/c/projects/testnative$ cat /etc/issue
Ubuntu 20.04.4 LTS \n \l

answers the last

**Comment by oubidar-Abderrahim** [comment]
Sorry for this super late response, I believe you shouldn't use 2 `CLibrary` annotations with different library names. Two annotations means you are linking two different libraries. In this case, test1 is linked statically and test is linked dynamically.
