### ISSUE TITLE
[GR-39473] java.lang.NoClassDefFoundError: com.sun.net.httpserver.HttpServer in runtime on JDK 17

### ISSUE THREAD

**Issue by tonivade** [oracle/graal#4671]
**Describe the issue**
 Using com.sun.net.httpserver.HttpServer in native-image (JDK 17) throws NoClassDefFoundError with latest 22.2 dev version.
Version 22.1 it works as expected.

**Steps to reproduce the issue**
1.

```java
import com.sun.net.httpserver.HttpServer;
import java.net.InetSocketAddress;
import java.io.IOException;

public class Test {
    public static void main(String[] args) throws IOException {
        var server = HttpServer.create(new InetSocketAddress("localhost", 8080), 10);
        System.out.println("starting server at localhost:8080");
        server.start();
    }
}
```

2.  javac Test.java
3.   native-image --no-fallback --allow-incomplete-classpath Test
4.   ./test
5.    NoClassDefFoundError

**Describe GraalVM and your environment:**
openjdk version "17.0.4" 2022-07-19
OpenJDK Runtime Environment GraalVM CE 22.2.0-dev (build 17.0.4+7-jvmci-22.2-b04)
OpenJDK 64-Bit Server VM GraalVM CE 22.2.0-dev (build 17.0.4+7-jvmci-22.2-b04, mixed mode, sharing)

- JDK major version: 17
- OS: Linux
- Architecture: AMD64

**More details**
```
 $ native-image --no-fallback --allow-incomplete-classpath Test
Warning: Using a deprecated option --allow-incomplete-classpath from command line. Allowing an incomplete classpath is now the default. Use --link-at-build-time to report linking errors at image build time for a class or package.
WARNING: Unknown module: org.graalvm.nativeimage.llvm specified to --add-exports
WARNING: Unknown module: org.graalvm.nativeimage.llvm specified to --add-exports
WARNING: Unknown module: org.graalvm.nativeimage.llvm specified to --add-exports
========================================================================================================================
 $ ./test 
Exception in thread "main" java.lang.NoClassDefFoundError: com.sun.net.httpserver.HttpServer
        at Test.main(Test.java:7)
```

**Comment by fniephaus** [comment]
Thanks for reporting a regression and providing a small reproducer, @tonivade! We'll look into a fix. As a workaround, the native executable works when you build with `native-image --no-fallback -J--add-modules -JALL-SYSTEM Test`.

**Comment by tonivade** [comment]
Thanks for the workaround

**Comment by inez** [comment]
@fniephaus 's workaround expresses in Gradle (kts):
```
graalvmNative {
    binaries {
        named("main") {
            fallback.set(false)
            buildArgs.add("-J--add-modules")
            buildArgs.add("-JALL-SYSTEM")
        }
    }
}
```

**Comment by tonivade** [comment]
I can confirm it's working with the latest dev build.

Thanks a lot!
