### ISSUE TITLE
Segfault when using -XX:+UseNUMA

### ISSUE THREAD

**Issue by markehammons** [oracle/graal#468]
Hi all,

When using graal EE on a project that i've been testing it with extensively, and activating NUMA mode (cause it's a NUMA arch, and I'm using a ton of threads), I get this segfault:
```
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007fe47d1ac7a6, pid=5792, tid=0x00007fe47e4bd700
#
# JRE version:  (8.0_171-b11) (build )
# Java VM: GraalVM 1.0.0-rc2 (25.71-b01-internal-jvmci-0.43 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# V  [libjvm.so+0x9737a6]  os::Linux::libnuma_init()+0x266
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /home/bioemerg/hs_err_pid5792.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
#
Aborted
```

**Comment by markehammons** [comment]
Thanks @dougxc, i was just in the middle of cleaning that up :+1:

**Comment by dougxc** [comment]
no problem ;-)
Can you please paste the contents of `hs_err_pid5792.log` in a gist and link to it here.

**Comment by markehammons** [comment]
[hs_err_pid5792.log](https://github.com/oracle/graal/files/2094479/hs_err_pid5792.log)

Here it is.

**Comment by dougxc** [comment]
This looks like https://bugs.openjdk.java.net/browse/JDK-8198794 which is [fixed in 8u172](https://bugs.openjdk.java.net/browse/JDK-8200694). GraalVM RC2 is based on 8u171 but the next GraalVM release will be based on 8u172. Until then, you'll have to avoid using NUMA.

**Comment by dougxc** [comment]
Please re-open if the next GraalVM release still has this issue.
