### ISSUE TITLE
Provided tools quick switch on graalvm and back reverse

### ISSUE THREAD

**Issue by cnmade** [oracle/graal#4682]
I am not happy with current graalvm ,because i must use JDK 8 for production , and i personal want try graalvm .

Let them working together is a problem and painful

We should have a tools, easy to switch to graalvm , and switch back if we want

This tool help us export JAVA_HOME, and add path to system PATH.

And after use it , clean JAVA_HOME , remove path from PATH.

Help us working the same time , the same machine, which installed JDk 8  and graalvm (JDK 17)

**Comment by oraluben** [comment]
[sdkman](https://sdkman.io/jdks) can help you to manage different versions of JDK.

**Comment by cnmade** [comment]
@oraluben no that , i have installed them already. not install sdk

**Comment by cnmade** [comment]
@oraluben SDK我装好了。我感觉现在缺的，是一个快速切换环境变量的工具。
或者说graalvm 能自己检测JAVA_HOME 最好。
现在的文档都是说：你可能想export JAVA_HOME
不，用户并不想。。
用户只想：
1. 别动我生产开发的JDK
2. 能快速切换，加载graalvm 需要的环境变量或者配置；
3. 用完了你给我还回去，清理干净；
4. 不要影响我的正常JDK，不要乱改JAVA_HOME

**Comment by oraluben** [comment]
@cnmade see `sdk install` and `sdk use`

**Comment by cnmade** [comment]
> @cnmade see `sdk install` and `sdk use`

Thanks , i am look it
