### ISSUE TITLE
Darwin native toolchain target architecture problem

### ISSUE THREAD

**Issue by crionuke** [oracle/graal#4694]
Hello, there!

Tried to compile java code with quarkus framework to native binary.
As result got next error:
**Error: Darwin native toolchain (x86_64) implies native-image target architecture class jdk.vm.ci.amd64.AMD64 but configured native-image target architecture is class jdk.vm.ci.aarch64.AArch64.**

**Under the hood was native-image command:**
/Library/Java/JavaVirtualMachines/graalvm-ce-java11-22.3.0-dev/Contents/Home/bin/native-image -J-Djava.util.logging.manager=org.jboss.logmanager.LogManager -J-Duser.language=en -J-Duser.country=RU -J-Dfile.encoding=UTF-8 -H:-ParseOnce -J--add-exports=java.security.jgss/sun.security.krb5=ALL-UNNAMED -J--add-opens=java.base/java.text=ALL-UNNAMED -H:InitialCollectionPolicy=com.oracle.svm.core.genscavenge.CollectionPolicy\$BySpaceAndTime -H:+JNI -H:+AllowFoldMethods -J-Djava.awt.headless=true -H:FallbackThreshold=0 --link-at-build-time -H:+ReportExceptionStackTraces -H:-AddAllCharsets -H:EnableURLProtocols=http -H:-UseServiceLoaderFeature -H:+StackTrace quarkus-lambda-1.0.0-SNAPSHOT-runner -jar quarkus-lambda-1.0.0-SNAPSHOT-runner.jar

**Many thanks for any help of how to solve this issue.**

**My configuration:**
Chip -> Apple M1 Pro
xcode-select --install   ->  xcode-select: error: command line tools are already installed, use "Software Update" to install updates
echo $GRAALVM_HOME -> /Library/Java/JavaVirtualMachines/graalvm-ce-java11-22.3.0-dev/Contents/Home
java -version -> 
openjdk version "11.0.16" 2022-07-19
OpenJDK Runtime Environment GraalVM CE 22.3.0-dev (build 11.0.16+7-jvmci-22.2-b04)
OpenJDK 64-Bit Server VM GraalVM CE 22.3.0-dev (build 11.0.16+7-jvmci-22.2-b04, mixed mode)

**Comment by fniephaus** [comment]
It seems that you're somehow mixing aarch64 with amd64 and I'm guessing it's because of Rosetta 2. Are you sure that the terminal you are using is consistently using aarch64? A native-image built on aarch64 only works on aarch64.

**Comment by crionuke** [comment]
@fniephaus thanks for your answer!

My graalvm from darwin-aarch64 archive.
Check my terminal by command arch, and got arm64
Also check compiler by cc --version -> Target: arm64-apple-darwin21.5.0

What do you mean about mixing? Is there any way to verify my configuration?

**Comment by fniephaus** [comment]
What LabsJDK are you using? It must be darwin-aarch64 as well.

**Comment by crionuke** [comment]
@fniephaus 

I don't use labsjds, just download this package: 
https://github.com/graalvm/graalvm-ce-dev-builds/releases/download/22.3.0-dev-20220702_0120/graalvm-ce-java11-darwin-aarch64-dev.tar.gz

**Comment by fniephaus** [comment]
Ok, just wanted to confirm that this is not the problem. Maybe @lewurm or @zakkak have an idea why the quarkus build detect a native toolchain for amd64?

**Comment by zakkak** [comment]
I don't think that Quarkus is doing anything special here but I might be missing something. @galderz can you please have a look?

**Comment by lewurm** [comment]
Where is this `Darwin native toolchain (x86_64) implies native-image target architecture class jdk.vm.ci.amd64.AMD64 but configured native-image target architecture is class jdk.vm.ci.aarch64.AArch64.` message coming from? Quarkus?

Linking the Quarkus issue here: https://github.com/quarkusio/quarkus/issues/26527

**Comment by lewurm** [comment]
I meant which component prints the the error message.  I found it in the meanwhile: https://github.com/oracle/graal/blob/adf58fbd332627188a4ac621c40c08f37b644820/substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/c/codegen/CCompilerInvoker.java#L312

Could you inject `-H:+TraceNativeToolUsage` somehow to the native-image invocation and then post the output? Sorry I don't know how to do that with Quarkus or maven 😕

Maybe let's start with the basics, does a simple Hello World work on your setup? That would be:
```
$ $GRAALVM_HOME/bin/javac Hello.java
$ $GRAALVM_HOME/bin/native-image Hello
$ ./hello
```

Could you post the output of `native-image -H:+TraceNativeToolUsage Hello` too?

**Comment by crionuke** [comment]
@lewurm 

file /Library/Java/JavaVirtualMachines/graalvm-ce-java11-22.3.0-dev/Contents/Home/bin/native-image `Mach-O 64-bit executable arm64`

With -H:+TraceNativeToolUsage next output
```
>> /usr/bin/cc -v     
># Apple clang version 13.1.6 (clang-1316.0.21.2.5)
># Target: x86_64-apple-darwin21.5.0
># Thread model: posix
># InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

So, it looks like that my toolchain that go with official xcode is x86_64. 
Do you know, what is the way to install properly toolchain on mac? Before that i just installed xcode from app store.

**Comment by crionuke** [comment]
@lewurm 
Also launched compilation on hello and got

native-image -H:+TraceNativeToolUsage Hello
```
>> /usr/bin/cc -v     
># Apple clang version 13.1.6 (clang-1316.0.21.2.5)
># Target: **arm64-apple-darwin21.5.0**
># Thread model: posix
># InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**Comment by lewurm** [comment]
Thanks @crionuke.  Xcode ships with universal binaries, so depending on the context it will choose the right binary:

```console
$ arch -arch x86_64 cc -v
Apple clang version 13.1.6 (clang-1316.0.21.2)
Target: x86_64-apple-darwin21.5.0
Thread model: posix
InstalledDir: /Applications/Xcode13.3.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
$ arch -arch arm64 cc -v
Apple clang version 13.1.6 (clang-1316.0.21.2)
Target: arm64-apple-darwin21.5.0
Thread model: posix
InstalledDir: /Applications/Xcode13.3.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

That means something switches into x86_64 mode.  My next guess would be maven; more specifically what's your `JAVA_HOME` and what is the output of `file $JAVA_HOME/bin/java`?

If you invoke the command that you specified as `Under the hood was native-image command` in your first post on the terminal, do you still see the same issue? Make sure your terminal is in the right context, you can tell by the output of `arch`.

**Comment by crionuke** [comment]
@lewurm 
Exactly! The reason of that behaviour was wrong JAVA_HOME that points to x86_64 java. Dispite of my terminal was in arm64 arch, native-image compilation launched from x86_64 proces. I've set JAVA_HOME to GRAAL_HOME and all become works properly.

Thanks a lot! And for that perfect clarification too. Now i understand more from native development :)

**Comment by fniephaus** [comment]
Great that you worked this out! I'm closing this ticket but feel free to re-open or open new ones if you have further questions! :)
