### ISSUE TITLE
Are graphs dumped lazily?

### ISSUE THREAD

**Issue by chrisseaton** [oracle/graal#4695]
```ruby
#!/usr/bin/env ruby

IO.popen(ARGV, :err=>[:child, :out]) do |pipe|
  loop do
    if pipe.readline =~ /Example::example/
      # sleep 3
      Process.kill 'INT', pipe.pid
      Process.wait pipe.pid
      break
    end
  end
end
```

Using this script, and running with

```
% ./watch-for-compilation java -Xbatch -XX:-TieredCompilation -XX:-UseOnStackReplacement '-XX:CompileCommand=dontinline,*::*' '-XX:CompileCommand=compileonly,Example::example' -XX:+PrintCompilation -Dgraal.PrintBackendCFG=true -Dgraal.PrintGraphWithSchedule=true -Dgraal.Dump=:1 Example
```

I don't get any dumps unless I uncomment the `sleep` command.

Why is that? Are graphs dumped in the background? Why? Is there a race?

**Comment by smarr** [comment]
Compilation is done on background threads, no? `-Dpolyglot.engine.BackgroundCompilation=false` should force waiting for the result of the compiler thread, which may or may not avoid the issue.

But generally, dumping graphs into a file is known to be racy: https://github.com/oracle/graal/issues/4013#issuecomment-970672252

**Comment by chrisseaton** [comment]
I thought `-Xbatch` stopped background compilation?

This is Graal not Truffle, so `-Dpolyglot.engine.BackgroundCompilation` not applicable I think.

**Comment by chrisseaton** [comment]
Although actually I do see the same problem in Truffle compilation, and it seems worse.

**Comment by oubidar-Abderrahim** [comment]
When I run the script you provided I get the following stack, am I missing something?
```
<internal:core> core/io.rb:1838:in `readline': end of file (EOFError)
	from ./watch-for-compilation:5:in `block (2 levels) in <main>'
	from <internal:core> core/kernel.rb:407:in `loop'
	from ./watch-for-compilation:4:in `block in <main>'
	from <internal:core> core/io.rb:791:in `popen'
	from ./watch-for-compilation:3:in `<main>'
```

**Comment by chrisseaton** [comment]
What Java program are you trying it with? For example

```java
import java.util.Random;

class Example {

    private final static Random RANDOM = new Random();

    public static void main(String[] args) {
        if (args.length != 0) {
            throw new UnsupportedOperationException("not expecting any arguments");
        }

        while (true) {
            example(RANDOM.nextInt(), RANDOM.nextInt());
        }
    }

    private static int example(int x, int y) {
        return x + y;
    }

}
```

**Comment by tkrodriguez** [comment]
PrintCompilation output occurs before the request for compilation has been handed to the compiler, not after.  So if you kill it at the point you see the output the compile hasn't even started.  https://github.com/tkrodriguez/jdk/blob/master/src/hotspot/share/compiler/compileBroker.cpp#L2173  `-Dgraal.PrintCompilation=true` output occurs after the compile has completed so you might try that instead.

**Comment by chrisseaton** [comment]
Thanks that does work, and I should have checked the implementation of HotSpot's `PrintCompilation` first.
