### ISSUE TITLE
SIGSEGV during execution of the Serial gc every hour

### ISSUE THREAD

**Issue by firanteteam** [oracle/graal#4704]
**Describe the issue**
Approximately every hour there is a moment when our application crashes with SIGSEGV (11 and 128). Judging by the dump that is printed at the end, the problem is with Serial GC

**Describe GraalVM and your environment:**
- GraalVM version: CE 22.1.0 (or 22.2.0-dev-20220624_1523)
- JDK 17
- OS: container Ubuntu 20.04
- Architecture: AMD64

**More details**
We are trying to migrate from spring application to spring-native. Most of the problems were solved quite easily. But for a long time we were faced with this problem, which we could not solve in any way. Apart from this stack trace, we have nothing. 
[gc_and_segfault_stacktrace.txt](https://github.com/oracle/graal/files/9063257/gc_and_segfault_stacktrace.txt)
I could notice that the problem only occurs in threads created from io.reactor packages (boundedElastic, parallel). This may be a coincidence, but I draw your attention to this.
A notable feature of the problem is that the GC starts to speed up as the error approaches. During application startup, it rarely works - once every several tens of seconds. And as the app runs, it speeds up. Just before the fall, it can work a dozen times per second.
I found similar problems, but, unfortunately, there is no solution.
https://github.com/oracle/graal/issues/2344
https://github.com/oracle/graal/issues/4128

**Comment by oubidar-Abderrahim** [comment]
Hi, Thank you for reporting this, we will take a look into it and get back to you

**Comment by oubidar-Abderrahim** [comment]
Tracked internally at GR--40143

**Comment by christianhaeubl** [comment]
Thanks for reporting this issue. Based on the logs, it looks as if some code uses a wrong offset when writing data into an object array (e.g., via `sun.misc.Unsafe` or via some native code). This is most likely an issue with the application itself and not with the GC.

However, without significantly more details, it is pretty much impossible to rule out an error in the GC. Ideally, we would need one of the following:
- a core dump
- the application itself
- a simplified reproducer

If none of the above is possible, then please test your application with GraalVM EE (see license) to check if the crash is also happening there. This would help to narrow down the issue:
- with the default GraalVM EE configuration
- with GraalVM EE and --gc=G1

Please also share the following details:
- a GC log for the whole run
- all heap settings and other VM arguments that you are using when you are executing your application, e.g. -Xmx, -Xms, -XX:...

**Comment by firanteteam** [comment]
Hello. I won't be able to provide a core dump or the application itself. 
I will try to run the application using Graal VM EE. If this does not help, then I will assemble an identical application layout and provide it to you along with all the launch settings. It probably won't be soon.

**Comment by christianhaeubl** [comment]
Closing this stale issue.
