### ISSUE TITLE
Packaging Graal VM

### ISSUE THREAD

**Issue by rahmanusta** [oracle/graal#472]
Hi,

How can I package Graal VM with an application which uses both Java and Ruby ?

Is there any too like that?

**Comment by rahmanusta** [comment]
Hi @shelajev

Actually if I can bundle Java + Ruby together as a native image of a polyglot app, it is enogh for me. I'm thinking to migrate @ AsciidocFx to Graal to be able to use Asciidoctor's Ruby implementation.

However, can I create a native image for a JavaFX application? If I can't I can need to use second option.

**Comment by eregon** [comment]
> Actually if I can bundle Java + Ruby together as a native image of a polyglot app, it is enogh for me.

Yes, that's possible. You just need to pass `--language:ruby` to native-image:
`$ native-image --language:ruby ... MainJavaClass`
and in the Java code you can use Ruby with the [Context API](http://www.graalvm.org/docs/getting-started/#native-images).

I don't know if native-image supports JavaFX though.

**Comment by shelajev** [comment]
I don't think building a native image of the JavaFX will succeed currently. There's some [limitations](https://github.com/oracle/graal/blob/master/substratevm/LIMITATIONS.md) to what programs can be compiled, and I think JavaFX does hit several of them.

**Comment by shelajev** [comment]
To be 100% honest a while ago I tried building a native image of AsciidocFX specifically and it didn't work. So I'm quite sure it won't work now as well. Currently, we're working on supporting compiling native images of more real world applications.

**Comment by rahmanusta** [comment]
Thanks @shelajev. I'll chase the changes about JavaFx.

**Comment by cstancu** [comment]
I'll close this issue as the original question was answered. To get updates about the JavaFX progress you can follow this issue https://github.com/oracle/graal/issues/365. There is no update at this time, but we have moved a long way towards that direction.
