### ISSUE TITLE
IndexRange misleading javadoc 

### ISSUE THREAD

**Issue by numberpi** [oracle/graal#473]
JavaDoc of `com.oracle.truffle.api.instrumentation.SourceSectionFilter.IndexRange.between(int, int)` says `[...] and a second index exclusive` in the text, but
`@param endIndex the end index (inclusive)`
six lines below.
Should be
`@param endIndex the end index (exclusive)`

https://github.com/oracle/graal/blob/49dbd42b7ebc8ef6e01e8656b98cef3f24c00f7d/truffle/src/com.oracle.truffle.api.instrumentation/src/com/oracle/truffle/api/instrumentation/SourceSectionFilter.java#L617

**Comment by chumer** [comment]
You are right. it should be exclusive. Thanks for the catch!

**Comment by boris-spas** [comment]
Fixed in https://github.com/oracle/graal/commit/c1eacb298315fe824b9de973eddf17d6c53f45b5
Thanks!
