### ISSUE TITLE
-H:CLibraryPath is not documented the relation to LD_LIBRARY_PATH not clear

### ISSUE THREAD

**Issue by AdamBien** [oracle/graal#4747]
Related issue: https://github.com/oracle/graal/issues/1393

**Steps to reproduce the issue**

Run the example: https://github.com/AdamBien/graalvm-hello-java-c and replace: -H:CLibraryPath  with LD_LIBRARY_PATH. The example will break.

**Describe GraalVM and your environment:**

openjdk version "17.0.4" 2022-07-19
OpenJDK Runtime Environment GraalVM CE 22.3.0-dev (build 17.0.4+7-jvmci-22.3-b02)
OpenJDK 64-Bit Server VM GraalVM CE 22.3.0-dev (build 17.0.4+7-jvmci-22.3-b02, mixed mode, sharing)

**Comment by oubidar-Abderrahim** [comment]
Hi, I'm not sure I follow what is the issue. `-H:CLibraryPath` is the way to specify the libraries' path while building native-image
