### ISSUE TITLE
When I run any test method, got "ValueKindFactory not found" error

### ISSUE THREAD

**Issue by ibrahimtkk** [oracle/graal#4750]
I downloaded graalvm/mx project from github and labsjdk 17. I tried to run CompileTheWorld test on IntelliJ and got the ValueKindFactory not found error. Then I tried to run another test and got same error. IntelliJ see the class but I didn't build.

The error is:
```
PATH/graal/compiler/src/org.graalvm.compiler.lir.jtt/src/org/graalvm/compiler/lir/jtt/LIRTest.java:134:88
java: cannot access jdk.vm.ci.code.ValueKindFactory
  class file for jdk.vm.ci.code.ValueKindFactory not found
```

**Steps**
- git clone https://github.com/oracle/graal.git
- git clone https://github.com/graalvm/mx.git
- wget https://github.com/graalvm/labs-openjdk-17/releases/download/jvmci-22.3-b03/labsjdk.labsjdk-ce-17.0.4+7-jvmci-22.3-b03-darwin-aarch64.tar.gz
- tar -xzf labsjdk.labsjdk-ce-17.0.4+7-jvmci-22.3-b03-darwin-aarch64.tar.gz
- export JAVA_HOME=`pwd`/labsjdk-ce-17.0.4-jvmci-22.3-b03
- mx intellijinit
- Open the graal/compiler project on the IntelliJ
- Run debug/run any test

**Environments:**
 - JDK major version: **labsjdk-ce-17.0.4-jvmci-22.3-b03**
 - OS: **macOS Monterey 12.2.1**
 - Architecture: **AMD64**

**More details**
```
   PATH/graal/compiler/src/org.graalvm.compiler.lir.jtt/src/org/graalvm/compiler/lir/jtt/LIRTest.java:134:88
java: cannot access jdk.vm.ci.code.ValueKindFactory
  class file for jdk.vm.ci.code.ValueKindFactory not found
```

**Comment by oubidar-Abderrahim** [comment]
Thank you for reporting this we'll take a look into it and get back to you

**Comment by oubidar-Abderrahim** [comment]
Could you please clarify why you're using aarch64 distribution while you use an amd64 machine?

**Comment by fexolm** [comment]
I have the same problem on ARM64 CPU, @ibrahimtkk were you able to resolve this issue?

**Comment by oubidar-Abderrahim** [comment]
Closing the issue for inactivity
