### ISSUE TITLE
Exception when using @CFunction on Windows

### ISSUE THREAD

**Issue by Montura** [oracle/graal#4760]
**Describe the issue**

There is a problem with calling native code corresponing the java functuion annotated _@CFunction_ on Windows platform.

Accrording to  [CInterfaceTutorial.java](https://github.com/oracle/graal/blob/master/substratevm/src/com.oracle.svm.tutorial/src/com/oracle/svm/tutorial/CInterfaceTutorial.java) and the [cinterfecetutorail.c](https://github.com/oracle/graal/blob/master/substratevm/src/com.oracle.svm.tutorial/native/cinterfacetutorial.c)
```
@CContext(NativeTest.CApiDirectives.class)
public class NativeTest {

  static class CApiDirectives implements CContext.Directives { ...}
  
  @CFunction
  public native static int testC();
}
```

```
extern "C" int testC();

int main() {
  testC(); // crashes with exception on Windows
}
```

**Steps to reproduce the issue**
Please include both build steps as well as run steps
1. Use GraalVM CE Build v22.1.0 on Apr 26
2. git clone https://github.com/Montura/graal-native-test
3. https://github.com/Montura/graal-native-test#steps-to-reproduce

**Describe GraalVM and your environment:**
 - GraalVM version [release v22.1.0](https://github.com/graalvm/graalvm-ce-builds/releases/tag/vm-22.1.0)
 - JDK major version: **11**
 - OS and arch:
   -  os: **Windows 10 Pro 19044.1826**, arch: **x64** (Intel Core i3-8100)
   -  os: **Linux Ubuntu 20.04.4 LTS**, arch: **x64** (Intel Core i5-2410M)
   -  os: **Mac OS Big Sur Version 11.5.2**, arch: **x64** (Intel Core i9)

**More details**
* on **Linux** and **Mac Os** works fine:

##### Expected output (digits are not valuable):
```
OS name: mac os
JNI time = 20
C time = 6
dummy time = 6
native time = 1
```

* on **Windows**

##### Actual output (digits are not valuable):
```
OS name: windows 10
JNI time = 20
```
_"Exception thrown at 0x00007FFA0F6F0000 (GraalSample.dll) in native.exe: 0xC0000005: Access violation executing location 0x00007FFA0F6F0000."_

![image](https://user-images.githubusercontent.com/4503006/181037463-2d266da1-e25c-4be1-8557-084028ee8d77.png)

#### Possible cause
* I dumped symbols from shared library for **Mac**, **Linux** and **Windows**:
    * **Mac** and **Linux** are export _undefined symbol_ _**testC**_:  [symbols_mac](https://github.com/Montura/graal-native-test/blob/master/symbols_mac.txt) and [symbols_linux](https://github.com/Montura/graal-native-test/blob/master/symbols_linux.txt) 
    * **Windows** can't export _undefined symbol_ _**testC**_ :  [symbols_windows](https://github.com/Montura/graal-native-test/blob/master/symbols_windows.txt) 
        * I used ["/FORCE:UNRESOLVED"](https://docs.microsoft.com/en-us/cpp/build/reference/force-force-file-output?view=msvc-170) linker option to build shared lib for Windows (so the symbol  _**testC**_ isn't imported)
        * I tried ["/OPT:NOREF"](https://docs.microsoft.com/en-us/previous-versions/visualstudio/visual-studio-6.0/aa278533(v=vs.60)?redirectedfrom=MSDN) and ["/INCLUDE:testC"](https://docs.microsoft.com/en-us/previous-versions/visualstudio/visual-studio-6.0/aa278363(v=vs.60)?redirectedfrom=MSDN), but it doens't help me at all.
         * **GetProcAddress** and **dlsym** proved my assumption: [load_functions.cpp](https://github.com/Montura/graal-native-test/blob/master/native/load_functions.cpp)

**Comment by oubidar-Abderrahim** [comment]
Thank you for reporting this, we will take a look into it and get back to you

**Comment by Montura** [comment]
@oubidar-Abderrahim, hello. Do you have any updates?

**Comment by oubidar-Abderrahim** [comment]
I apologize for the super late response, the issue got buried under many others.
Could you please verify if this issue is still present in our latest build of 22.3.0?

**Comment by oubidar-Abderrahim** [comment]
If this issue is still relevant in the latest GraalVM versions, please create a new issue for it and follow the template provided. Thank you
