### ISSUE TITLE
[VisualVM] Downloadable JAR permissions file references missing directories in lib/visualvm/platform/modules/lib/

### ISSUE THREAD

**Issue by lucaswerkmeister** [oracle/graal#4763]
The downloadable JAR for VisualVM in the 22.2.0 CE builds, [visualvm-installable-ce-java11-linux-amd64-22.2.0.jar](https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-22.2.0/visualvm-installable-ce-java11-linux-amd64-22.2.0.jar), includes entries in the `permissions` file that aren’t actually included in the JAR:

```console
$ wget https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-22.2.0/visualvm-installable-ce-java11-linux-amd64-22.2.0.jar
$ unzip -p visualvm-installable-ce-java11-linux-amd64-22.2.0.jar META-INF/permissions | grep lib/visualvm/platform/modules/lib/
lib/visualvm/platform/modules/lib/i386 = rwxr-xr-x
lib/visualvm/platform/modules/lib/amd64 = rwxr-xr-x
lib/visualvm/platform/modules/lib/x86 = rwxr-xr-x
lib/visualvm/platform/modules/lib/aarch64 = rwxr-xr-x
lib/visualvm/platform/modules/lib/x86_64 = rwxr-xr-x
lib/visualvm/platform/modules/lib/x86_64/libjnidispatch-nb.jnilib = rw-r--r--
lib/visualvm/platform/modules/lib/aarch64/libjnidispatch-nb.jnilib = rw-r--r--
$ unzip -t visualvm-installable-ce-java11-linux-amd64-22.2.0.jar | grep lib/visualvm/platform/modules/lib/
    testing: lib/visualvm/platform/modules/lib/aarch64/libjnidispatch-nb.jnilib   OK
    testing: lib/visualvm/platform/modules/lib/x86_64/libjnidispatch-nb.jnilib   OK
```
The `i386`, `amd64` and `x86` directories aren’t included in this JAR, so they should not be listed in the `permissions` file either. (Usually, “missing” `permissions` entries are a sign that I as the packager have forgotten to copy a directory out of the JAR, so I don’t really want to ignore these errors in general.)

**Comment by oubidar-Abderrahim** [comment]
Thank you for reporting this we will take a look into it and get back to you

**Comment by oubidar-Abderrahim** [comment]
Fixed in https://github.com/oracle/graal/commit/45fc9b1989875f8549dc6474fb9cd90078dcbcad
