### ISSUE TITLE
[Documentation] Big fat overview table "GraalVM supports xyz"

### ISSUE THREAD

**Issue by rubyFeedback** [oracle/graal#4774]
Hey GraalVM devs,

Another request for documentation.

Before I do, a bit of context.

I built a few Swing applications and just use javac to compile it and run it. That works
so far.

Today, just a few hours ago, I actually built my first JavaFX application. \o/

I don't intend to abandon Swing as of yet (so GraalVM supporting Swing
fully would be neat), but now that I know how to use JavaFX, I think I will
build more JavaFX apps in the future - CSS support is huge, sad that
Swing was abandoned in this regard. Anyway.

Now to the issue request here.

Right now I have read that swing works with GraalVM if we add some 
things including that JNI ini thingy or so. At the least someone else got
it to work, I still have not, but I am still a java noob so that is ok.

But I also don't know whether JavaFX is supported. Or SWT!

So my request would be:

- Could someone make a huge overview page for what GraalVM
supports? With that I mean you could have a row called "swing"
and then under "Supported" line you could say "partially, see
xyz" or some link. Next line, JavaFX, supported: "partially, see
abc". And so forth.

My goal here would be that we have ONE overview table for
the homepage at GraalVM where these things can all be
seen at a single glance. It's ok to add more information! 
Like "Supported languages" e. g. ruby python etc... and many
other things. Everything that is useful into a huge HTML
table. \o/

Rationale: right now I have to collect this information from
non-graalVM homepage, aka many blogs and what not.
This is ok but I'd prefer to have it really on the official
homepage.

IF it already exists somewhere, could perhaps more
references be added to it? For instance, if there is an
entry about "GUIs and GraalVM", it could link to that
table or display it. And if there is no such page yet, 
perhaps some heroic docu-writer can write a paragraph
or two about GUIs and GraalVM. I know this is not
GraalVM's primary focus, but application-code and
users may want to know a bit how GraalVM relates
to that. The GUIs are one big reason for me using 
Java in the first place, as otherwise I could use ruby
or python, but I like the speed from Java, native-image
is AWESOME, and I need this for some elderly relatives
(that may also be one reason why I will switch from
Swing to JavaFX eventually, CSS really makes everything
easier). Anyway that's it, please feel free to proceed with
this issue request in any way you see fit. I did use an awkward
word wrapping as I am used to this from my local editor; I 
can not easily read super-long sentences, so I wrap things up
a LOT, sorry.

**Comment by rubyFeedback** [comment]
Oops - not sure why it adds "bug" label. Should be a "documentation" label. Can anyone add that to the github issue tracker? I did not notice a docu label.

**Comment by oubidar-Abderrahim** [comment]
Thank you for your suggestion, we will take it into discussion

**Comment by oubidar-Abderrahim** [comment]
@olyagpl  could you please check if it's doable to provide a list of what we support currently? Thank you

**Comment by olyagpl** [comment]
@rubyFeedback, we created a page collecting Java libraries and frameworks 
ready to use/tested with Native Image https://www.graalvm.org/native-image/libraries-and-frameworks/. These libraries are either continuously tested by its maintainers or tested as part of the [GraalVM Reachability Metadata Repository](https://github.com/oracle/graalvm-reachability-metadata) or some other community-driven project. Please use it as a reference. Thank you for sharing your ideas with us!
