### ISSUE TITLE
[native-image] Can't build static executable images on MacOSX

### ISSUE THREAD

**Issue by sureshg** [oracle/graal#478]
`--static` option gives the following error

```bash
$ native-image --static -H:+JNI -H:+ReportUnsupportedElementsAtRuntime -jar xxxx-uber.jar
Build on Server(pid: 48181, port: 57130)
   classlist:     632.54 ms
       (cap):   1,372.58 ms
       setup:   1,609.18 ms
  (typeflow):   2,159.34 ms
   (objects):     882.54 ms
  (features):      30.92 ms
    analysis:   3,152.37 ms
    universe:     204.18 ms
     (parse):     437.21 ms
    (inline):     550.01 ms
   (compile):   3,284.82 ms
     compile:   4,555.34 ms
       image:     585.21 ms
       write:     717.82 ms
error: DARWIN does not support building static executable images.
Error: Processing image build request failed
```
The documentation or release notes don't mention anything specific about mac osx for static build generation. Is static executable image generation supported on MacOSX?

**Comment by olpaw** [comment]
> Is static executable image generation supported on MacOSX?
No. OS X does not static linking of libc.
See https://developer.apple.com/library/archive/qa/qa1118/_index.html

**Comment by didibus** [comment]
The documentation says that on windows and macOS, the option does nothing ? So does it fail or is it ignored ?

**Comment by olpaw** [comment]
does nothing <-> is ignored

**Comment by didibus** [comment]
Okay, thanks for clarifying!
