### ISSUE TITLE
GVN during graph construction doesn't always seem to work - guard conditions are duplicated

### ISSUE THREAD

**Issue by chrisseaton** [oracle/graal#4788]
TruffleRuby as at `4054469bbd985db7dc5c86299004ff86a2835baf`.

```ruby
require 'delegate'

puts RUBY_DESCRIPTION

class Underlying
  def bar
    14
  end
end

def foo(o)
  o.bar
end

u = Underlying.new

loop do
  o = SimpleDelegator.new(u)
  foo(o)
end
```

(Doesn't matter what the program is doing or why - just care about the GVN of the graph.)

```
% jt graph test.rb
```

My understanding of Graal is that GVN is done during construction. Why does 1450 go into the graph when it should have hashed to the same thing as 789?

And I know the guard nodes themselves are fixed, but should they be added to the graph one after the other like this with no sequence points in between?

<img width="1238" alt="Screenshot 2022-08-04 at 12 23 50" src="https://user-images.githubusercontent.com/341094/182835465-7b05694b-40a4-4593-847f-0afaa7da3a0b.png">

CC @eregon

**Comment by eregon** [comment]
@dougxc Could you take a look or reassign?

**Comment by chrisseaton** [comment]
Graph: [graph.bgv.gz](https://github.com/oracle/graal/files/9292705/graph.bgv.gz)

**Comment by tkrodriguez** [comment]
This looks like some missing incremental canonicalization after `DominatorBasedGlobalValueNumbering`.  GVN of fixed nodes results in some floating nodes having the same inputs but we aren't rerunning GVN on those nodes.  That phase should probably extend `PostRunCanonicalizationPhase`. cc @davleopo

**Comment by chrisseaton** [comment]
I thought new nodes never went into the graph if they were duplicates of existing nodes? Is that not the case? Or is that only during graph building and PE?

**Comment by tkrodriguez** [comment]
It was already in the graph but with different inputs.  Some edges were replaced so that it became equivalent to another node but it requires the canonicalizer to run again to merge the duplicates.  Look at 1450 and 789 before and after `DominatorBasedGlobalValueNumbering`  If we miss it during incremental canonicalization it requires a full canonicalization for it to be cleaned up.

**Comment by davleopo** [comment]
@tkrodriguez  yes I think you are right. Ill put up a PR.

**Comment by davleopo** [comment]
Fixed by https://github.com/oracle/graal/commit/0de93543abe6895db22066e680ad384c72dd1653
