### ISSUE TITLE
[GR-40262] Warning "Unknown module: org.graalvm.nativeimage.llvm specified to --add-exports"

### ISSUE THREAD

**Issue by rubyFeedback** [oracle/graal#4789]
Today I upgraded from 22.1.0 to 22.2.0. I believe a few things may have changed
in native-image. One thing may be a new warning (among other changes).

Example:

    javac AskExamQuestion.java

    native-image -H:+StaticExecutableWithDynamicLibC AskExamQuestion

    WARNING: Unknown module: org.graalvm.nativeimage.llvm specified to --add-exports
    WARNING: Unknown module: org.graalvm.nativeimage.llvm specified to --add-exports
    WARNING: Unknown module: org.graalvm.nativeimage.llvm specified to --add-exports

I am quite sure I did not get this warning on 22.1.0.

So, first ... not sure why I get the warning 3 times. One time should be enough. But I
believe this is a new warning, and I have no idea whether this is problematic or not.
Either way if it is not important perhaps it should not be shown. Or a warning be
shown how to disable it or solve it perhaps.

So this is just a warning issue I guess, not a bug necessarily. I report it just in case
someone may want to fix it.

**Comment by fniephaus** [comment]
Thanks for filling this issue. It's an unfortunate result of two updates in 22.2: the image builder running on the module path and LLVM no longer shipping by default. We're going to fix this in an upcoming release.

**Comment by fniephaus** [comment]
Fixed with https://github.com/oracle/graal/commit/b6f436e5d317914c9c91bebcb3940ec8993cd853, will ship with 22.3.
