### ISSUE TITLE
Inform about deopts caused by TruffleRuntime:: iterateFrames

### ISSUE THREAD

**Issue by fniephaus** [oracle/graal#479]
The Javadoc of [`TruffleRuntime::iterateFrames`](https://github.com/oracle/graal/blob/dede8791b189077c3cf64006f40c02719a72e022/truffle/src/com.oracle.truffle.api/src/com/oracle/truffle/api/TruffleRuntime.java#L159) does not mention that this causes deoptimizations and it took me quite some time to find out about this.
I think it would make sense to elaborate a bit more about the impact and possible use cases of `iterateFrames` in the Javadoc as well as to introduce at least a performance warning for it (printed when `TraceTrufflePerformanceWarnings=true`). Maybe even an exception when it is called from compiled code.

**Comment by woess** [comment]
Does that also happen with `FrameAccess.READ_ONLY`?

**Comment by fniephaus** [comment]
I would assume the answer is no, but I don't know for sure.

**Comment by boris-spas** [comment]
Tracking internally as Issue GR-20791.

**Comment by fniephaus** [comment]
Fixed by @eregon via https://github.com/oracle/graal/commit/1ed1258164a5fae3962765522c555acd30052a8b.
