### ISSUE TITLE
jdeps: Module org.graalvm.js does not read a module that exports com.oracle.truffle.api

### ISSUE THREAD

**Issue by gbecan** [oracle/graal#4791]
**Describe the issue**
`jdeps` fails with following error on a project using `org.graalvm.js:js:22.2.0` library on GraalVM:
`[error] Error: Module org.graalvm.js does not read a module that exports com.oracle.truffle.api`

**Describe GraalVM and your environment:**
- GraalVM: 

> openjdk 17.0.4 2022-07-19
> OpenJDK Runtime Environment GraalVM CE 22.2.0 (build 17.0.4+8-jvmci-22.2-b06)
> OpenJDK 64-Bit Server VM GraalVM CE 22.2.0 (build 17.0.4+8-jvmci-22.2-b06, mixed mode, sharing)

- OS: Fedora Linux

**More details**
On other JVMs, jdeps and jlink run fine.
The only way to make it work on GraalVM is to remove the library `org.graalvm.js:js` but I would like to keep it to support other JVMs.
The project is using sbt-native-packager to call jdeps/jlink.

**Comment by guizmaii** [comment]
Ok we've found what was the issue. 
We were having these dependencies (declared with sbt):
```scala
    "org.graalvm.sdk"     % "graal-sdk"   % graalVersion,
    "org.graalvm.js"      % "js"          % graalVersion
``` 
The fix is to add this dependency too:
```scala
    "org.graalvm.truffle" % "truffle-api" % graalVersion,
````
And because these libs are already present in GraalVM, these dependencies can be declared as provided:
```scala
    "org.graalvm.sdk"     % "graal-sdk"   % graalVersion % Provided,
    "org.graalvm.js"      % "js"          % graalVersion % Provided,
    "org.graalvm.truffle" % "truffle-api" % graalVersion % Provided,
````
