### ISSUE TITLE
GraalVM CE 22.2.0 is missing JavaScript

### ISSUE THREAD

**Issue by Melab** [oracle/graal#4805]
In the version 22.2.0 release of GraalVM Community Edition, the JavaScript folder, and with it, the launcher, is missing from the `languages` folder.

**Comment by plokhotnyuk** [comment]
@Melab, you can install it by `gu install js`, it is logged in release notes:
https://github.com/oracle/graaljs/blob/master/CHANGELOG.md#version-2220

**Comment by fniephaus** [comment]
@plokhotnyuk's info is accurate. Please feel free to re-open if you still have a problem with this.
