### ISSUE TITLE
jdk 18?

### ISSUE THREAD

**Issue by The-Ultimate-Dart-Monkey** [oracle/graal#4813]
**Feature request**

Please include the following information:

**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. E.g. I'm always frustrated when [...]

**Describe the solution you'd like.**

**Describe who do you think will benefit the most.**
GraalVM users, GraalVM contributors, developers of libraries and frameworks which depend on GraalVM, or somebody else?

**Describe alternatives you've considered.**

**Additional context.**
Add any other context about the feature request here.
For example, link to the relevant projects, documentation, standards.

**Express whether you'd like to help contributing this feature**
If you'd like to contribute, please read the [contribution guide](https://www.graalvm.org/community/contributors/).

**Comment by fniephaus** [comment]
We are working on JDK19 support. More updates to follow soon.

**Comment by The-Ultimate-Dart-Monkey** [comment]
alr thanks for letting me know
