### ISSUE TITLE
graalpython copy.copy behaviour with sets different from CPython & PyPy

### ISSUE THREAD

**Issue by twirrim** [oracle/graal#4816]
**Describe the issue**

Using copy.copy() around an iterable that is going to be modified in a loop, I discovered that graalpython behaves differently from CPython and PyPy, when the iterable is a set.

**Steps to reproduce the issue**

```
from copy import copy

def do_something(numbers):
    print(numbers)

foo = set([1, 2, 3, 4, 5, 6, 7, 8, 9])

for _ in copy(foo):
    foo.pop()
    do_something(foo)
```
Execute under various python implementations.  Graal throws error because iterable was changed during the loop, while CPython & PyPy don't have a problem.

**Describe GraalVM and your environment:**
 - GraalVM version (latest snapshot builds can be found [here](https://github.com/graalvm/graalvm-ce-dev-builds/releases)), or commit id if built from source: EE 22.2.0 
 - JDK major version: 17
 - OS: Fedora 36 & Ubuntu 22.04
 - Architecture: AMD64

**More details**
Add any other information about the problem here. Especially important are stack traces or log output. Feel free to link to gists or to screenshots if necessary.

CPython output:
```
$ python example.py 
{2, 3, 4, 5, 6, 7, 8, 9}
{3, 4, 5, 6, 7, 8, 9}
{4, 5, 6, 7, 8, 9}
{5, 6, 7, 8, 9}
{6, 7, 8, 9}
{7, 8, 9}
{8, 9}
{9}
set()
```
PyPy output:
```
$ pypy3 example.py 
{1, 2, 3, 4, 5, 6, 7, 8}
{1, 2, 3, 4, 5, 6, 7}
{1, 2, 3, 4, 5, 6}
{1, 2, 3, 4, 5}
{1, 2, 3, 4}
{1, 2, 3}
{1, 2}
{1}
set()
```
graalpython outout:
```
$ ~/graalvm-ee-java17-22.2.0/bin/graalpython --version
GraalVM Python 3.8.5 (GraalVM EE Native 22.2.0)
$ ~/graalvm-ee-java17-22.2.0/bin/graalpython example.py 
{2, 3, 4, 5, 6, 7, 8, 9}
Traceback (most recent call last):
  File "/home/paul/python/proof_of_concept/example.py", line 8, in <module 'example.py'>
    for _ in copy(foo):
RuntimeError: Set changed size during iteration
```

Using copy.deepcopy, the behaviour matches CPython and PyPy.

**Comment by timfel** [comment]
Indeed, our set.copy implementation is too shallow - it creates a new set but shares the underlying hashmap: https://github.com/oracle/graalpython/blob/ea1a66bce9762dc7aab716ec35c9c02c84e2bb7c/graalpython/com.oracle.graal.python/src/com/oracle/graal/python/builtins/objects/set/SetBuiltins.java#L143

We will fix that for the next release
