### ISSUE TITLE
Native image hangs for more than 12 hours on AWS batch

### ISSUE THREAD

**Issue by agibsonccc** [oracle/graal#4832]
**Describe the issue**
A clear and concise description of the issue. We recommend using the [latest snapshot builds](https://github.com/graalvm/graalvm-ce-dev-builds/releases) to replicate the issue as  bugs are constantly being fixed in the master branch

Hello,
I am running graalvm 22.2 native image on AWS batch. It freezes for at least 12 hours. 
On my local machine it only takes 1h.  Both jobs run in a self contained docker environment.

Monitoring the memory usage it never reaches more than 1g of RAM so I don't think it's a resource usage issue.
I've seen past github issues mention using --no-server to avoid freezes like this. I am doing that as well and it doesn't appear to help.

I am using the maven native-image plugin with the coordinates:
org.graalvm.buildtools:native-maven-plugin:0.9.13

**Steps to reproduce the issue**
Please include both build steps as well as run steps
Run native-image on AWS batch.

**Describe GraalVM and your environment:**
 - GraalVM version (latest snapshot builds can be found [here](https://github.com/graalvm/graalvm-ce-dev-builds/releases)), or commit id if built from source: **[e.g. EE 19.3, CE 20.0, CE 20.1.0-dev-20200304_0848]**
 - JDK major version: **[e.g.:8]** 11
 - OS: **[e.g. macOS Catalina]** linux
 - Architecture: **[e.g.: AMD64]** AMD64

**More details**
Consider adding the `--native-image-info` and  `--verbose` flags when building your native image and paste output below.

Relevant is it gets stuck in the setup phase like this:
```
 setup: 4,661.60 ms, 3.24 GB
```
Other than that nothing else is output.

**Comment by fniephaus** [comment]
Hi @agibsonccc, the versions of Native Image that you're using are rather old and no longer supported. Can you please upgrade to a newer release (latest release is 22.2, latest LTS is 21.3.3). Please re-open the issue if that doesn't fix your problem. Thanks!

**Comment by agibsonccc** [comment]
@fniephaus actually yes it is the latest version 22.2. I'm not allowed to reopen the issue. Could you please help do that?

**Comment by fniephaus** [comment]
That's surprising, the output you mentioned suggests it's a Native Image before 22.2 and the option to re-enable the old build output style was removed in 22.2. Are you sure that you're running a recent GraalVM Native Image?

**Comment by agibsonccc** [comment]
@fniephaus thanks. Looking at the relevant docs the first thing I thought of was potentially a JVM heap size issue. JVMs tend to freeze when they are about out of memory but looking at the monitoring it wasn't using that much RAM despite having way more available. I know in more recent JVMs they're container aware and usually settings like default heap sizes are handled pretty well.
I wouldn't expect the graal team to trouble shoot something AWS related but I would appreciate a way of figuring out why the freeze might be happening.

Regarding your question: 

Actually apologies again. I updated the graalvm version in my project but not the local install when I did the upgrade. Let me do that first and I'll comment on this issue if I still see this when I do the upgrade. Thank you for flagging that!

**Comment by fniephaus** [comment]
No worries! A good starting point to find out why a freeze happens is a thread dump and there're multiple ways of doing that. Native Image deploys a watchdog that I believe also checks the thread dump to identify stalled builds and fails them. We've been tweaking this watchdog in the last years, that's exactly why I suggested updating. It's, for example, possible that there is an endless loop in a part of your application that gets initialized at build time.

**Comment by agibsonccc** [comment]
Thanks..it's just strange because locally the build runs fine. Remotely it freezes though. That's why most of my troubleshooting was around resources and GC. I'll re open this if I see something more concrete after confirming everything is updated and it's still not working.

**Comment by agibsonccc** [comment]
Can confirm something in the older version was the problem. Everything runs in the containerized environment with the latest version.
