### ISSUE TITLE
`@ExportLibrary(InteropLibrary.class)` does not produce meaningful error when running `mx gate`

### ISSUE THREAD

**Issue by 2767mr** [oracle/graal#4833]
**Describe GraalVM and your environment :**
 - GraalVM version or commit id if built from source: **f9726d7f20f (graaljs master - [05ce36976b](https://github.com/oracle/graaljs/commit/05ce36976b644defabee71fe8f70492a3d303379))**
 - CE or EE: **CE**
 - JDK version: **labsjdk-ce-11-jvmci-22.3-b02 or labsjdk-ce-17-jvmci-22.3-b02**
 - OS and OS Version: **Ubuntu 20.04.4**
 - Architecture: **amd64**
 - The output of `java -Xinternalversion`:
```
OpenJDK 64-Bit Server VM (11.0.16+7-jvmci-22.3-b02) for linux-amd64 JRE (11.0.16+7-jvmci-22.3-b02), built on Jul 13 2022 17:12:49 by "buildslave" with gcc 7.3.0
```

**Have you verified this issue still happens when using the latest snapshot?**
yes

**Describe the issue**
After creating a new class like below `mx build` succeeds without issues but `mx gate` does not. When using java 11 it gives a lot of generator errors, none of which relate to the code below. When using java 17 it simply prints "1 error" without any indication of the cause.

```
package com.oracle.truffle.js.runtime.builtins;

import com.oracle.truffle.api.interop.InteropLibrary;
import com.oracle.truffle.api.library.ExportLibrary;
import com.oracle.truffle.api.object.Shape;
import com.oracle.truffle.js.runtime.objects.JSNonProxyObject;

@ExportLibrary(InteropLibrary.class)
public class TestObject extends JSNonProxyObject {
    protected TestObject(Shape shape) {
        super(shape);
    }
}

```

**Steps to reproduce the issue**
Please include both build steps as well as run steps
1. `git clone https://github.com/oracle/graal`
2. `git clone https://github.com/oracle/graaljs`
3. `cd graaljs/graal-js`
4. Paste code above into `src/com.oracle.truffle.js/src/com/oracle/truffle/js/runtime/builtins/TestObject.java`
5. set `JAVA_HOME` to labsjdk-ce-11-jvmci-22.3-b02
6. `mx sforceimports`
7. `mx --dy /compiler,/wasm build`
8. `mx --dy /compiler,/wasm gate`
9. set `JAVA_HOME` to labsjdk-ce-17-jvmci-22.3-b02
10. `mx clean`
11. `mx --dy /compiler,/wasm build`
12. `mx --dy /compiler,/wasm gate`

**Expected behavior**
* An error message along the lines of "Cannot generate library export because no @ExportMessage was found" for `build` as well as `gate` regardless of java 11 or 17.

**Additional context**
I added the log outputs for both java 11 (out.txt) as well as java 17 (out17.txt). As you can see, they do not include the words "TestObject", "ExportLibrary" or "InteropLibrary".

<details><summary>Details</summary>

[out.txt](https://github.com/oracle/graal/files/9394042/out.txt)
[out17.txt](https://github.com/oracle/graal/files/9394043/out17.txt)

</details>

**Comment by oubidar-Abderrahim** [comment]
Hi, Thank you for reporting this, we'll take a look into it and get back to you

**Comment by oubidar-Abderrahim** [comment]
If this issue is still relevant in the latest GraalVM versions, please create a new issue for it and follow the template provided. Thank you
