### ISSUE TITLE
Potential regression on -H:ReportAnalysisForbiddenType

### ISSUE THREAD

**Issue by sdeleuze** [oracle/graal#4839]
With GraalVM 22.2, `-H:ReportAnalysisForbiddenType=sun.java2d.SunGraphics2D` just prints `Error: Forbidden type sun.java2d.SunGraphics2D UsageKind: Reachable` without the stacktrace of how the object is reached.

It is super annoying since we used that extensively in Spring to understand why a class is reachable.

Could you please double check you can reproduce and fix it in dev builds and upcoming GraalVM 22.3 ?

Please tag this issue with the `spring` label.

**Comment by fniephaus** [comment]
Does adding `-H:+ReportExceptionStackTraces` do the trick?

**Comment by sdeleuze** [comment]
Nope

**Comment by sdeleuze** [comment]
FYI this issue impact significantly our capability to optimize the footprint of Spring Boot 3 native applications, so it would be super helpful if GraalVM 22.3 dev builds would contain a fix for this since we can't use previous version due to some incompatibilities.

**Comment by fniephaus** [comment]
Ok, I'll make sure we look into a fix for 22.3

**Comment by sdeleuze** [comment]
After double checking, it is due to the specified class `sun.java2d.SunGraphics2D` which is not tracable, it works with other classes, so nothing to fix.
