### ISSUE TITLE
Use the right GraalVM dependency

### ISSUE THREAD

**Issue by wise-coders** [oracle/graal#4848]
I created an application that uses GraalVM. In Gradle I specify:

```
    implementation 'org.graalvm.js:js:22.2.0'
    implementation 'org.graalvm.js:js-scriptengine:22.2.0'
```
When executing the code I get:
```
Error loading driver /Users/yusuf-mac/.DbSchema/drivers/MongoDb/truffle-api-22.2.0.jar : java.lang.UnsupportedClassVersionError: META-INF/versions/17/module-info has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 59.0. 
Please consider upgrading Java. Your current Java version is AdoptOpenJDK 15.0.2.
```

How do I ensure in Gradle that the dependencies are compatible with OpenJDK 15? I cannot upgrade to a higher version of OpenJDK.

**Comment by oubidar-Abderrahim** [comment]
Hi, the supported JDKs that we provide in GraalVM 22.2 are the LTS versions: JDK 11 and JDK 17, I would suggest either upgrading to JDK 17 or downgrading to JDK 11.
