### ISSUE TITLE
Need an API in IsolateArgumentParser to return long typed option value

### ISSUE THREAD

**Issue by ziyilin** [oracle/graal#4851]
**Feature request**

Class `com.oracle.svm.core.IsolateArgumentParser` parses the options set at runtime for native image isolate. There are 4 options are currently supported, `-Xmx`, `-Xms`, `-Xmn`, and `-XX:-AutomaticReferenceHandling`. The first three of them are long typed, but there is only one `getIntOptionValue` method can return a integer typed option value.

**Describe the solution you'd like.**
Add an API to return the long typed option value.

**Express whether you'd like to help contributing this feature**
I have proposed a PR to fix this issue: https://github.com/oracle/graal/pull/4850

**Comment by oubidar-Abderrahim** [comment]
Thank you for your suggestion, we will take a look into it
