### ISSUE TITLE
Support for universal binaries via Cosmopolitan

### ISSUE THREAD

**Issue by LifeIsStrange** [oracle/graal#4854]
This is not the same thing as the request for supporting cross compilation.
Cosmopolitan is a new technology that allow x86 (and with emulation ARM) binaries to be executed on any OS, with a singles and small binary.
This technology is potentially disruptive and would be a great addition to GraalVM as binaries would become closer to the famous write once run anywhere Philosophy.
https://justine.lol/cosmopolitan/index.html

**Comment by mukel** [comment]
Cosmopolitan is somehow constrained e.g. currently there's no support for pthreads.
native-image can already produce static executables linked against musl. We also need (static) JDK native libraries compiled against Cosmopolitan.

**Comment by ianopolous** [comment]
This would be amazing. I think Cosmopolitan supports pthreads now too.

**Comment by elken** [comment]
Gently nudging this to see if there's any/much activity :smile:

**Comment by sgammon** [comment]
Formally filed at #8350 / `GR-52220`

**Comment by wirthi** [comment]
I am closing this as there is newer discussion on #8350 now. Still, I don't see this very high up our priorities list; if there are easy things to fix on our side to make that easier for you, we might be able to look into it of course.
