### ISSUE TITLE
Using graal as a multi-threading

### ISSUE THREAD

**Issue by kingkong3** [oracle/graal#4860]
Hello, I'm replacing java's script engine with graal from Nashorn.
(in Java8 / newest graal)

However, unlike Nashorn, graal does not support multi-threading, so the following methods were used
To briefly explain my code, :

1. When initializing the server, create a specific number of script engines and add them to the queue

```
Context newEngine = Context.newBuilder("js").option("engine.WarnInterpreterOnly", "false").allowAllAccess(true).allowHostClassLookup(className -> true).build();

ScriptEngineQueue.getInstance().add(newEngine );
```

2. Then poll the script engine and evaluate the script in Java.

```
Context engine = ScriptEngineQueue.getInstance().poll();
engine.eval("js", script);
```

3.  Add the evaluation script engine back to the queue.

`ScriptEngineQueue.getInstance().add(engine);`

It takes up quite a lot of resources to create an engine, so I've created it in advance.
About 200 script engines are generated, and memory leaks are suspected in this situation, so I would like to ask if there is any problem in using them with the above usage.

Please reply. Thank you.

**Comment by djoooooe** [comment]
This issue should be transferred to https://github.com/oracle/graaljs
