### ISSUE TITLE
Outdated kotlin example in docs

### ISSUE THREAD

**Issue by zakkak** [oracle/graal#4861]
**Describe the issue**
The example under ["Build a Native Image of a Java and Kotlin Application"](https://github.com/oracle/graal/blob/master/docs/examples/java-kotlin-aot.md) seems outdated.

1. There is no link to the repository containing the `java-kotlin-aot` example.
2. The external link to the JetBrains [Kotlin-examples repository](https://github.com/JetBrains/kotlin-examples/tree/master/maven/mixed-code-hello-world) is no longer valid.

**Comment by olyagpl** [comment]
Hi Foivos, all GraalVM demos are now stored in https://github.com/graalvm/graalvm-demos and regularly tested using a GitHub workflow. The Java-Kotlin example was moved there too https://github.com/graalvm/graalvm-demos/tree/master/java-kotlin-aot. 
Sorry for so late reply!
