### ISSUE TITLE
Dynamically Register Truffle-Api

### ISSUE THREAD

**Issue by wise-coders** [oracle/graal#4870]
Using URLClassLoader I load the GraalVM, truffle-api.jar, and a jar containig the call to Context as below. The execution throws the exception:
```
No language and polyglot implementation was found on the classpath. Make sure the truffle-api.jar is on the classpath.
```
```
Context context = Context.newBuilder("js").allowAllAccess(true).build();
```

Is any way to dynamically register the truffle-api.jar?

**Comment by wise-coders** [comment]
I found a fix for this issue. I added 
```
Thread.getCurrentThread().setContextClassLoader( Context.class.getClassLoader())
```
to my code. This in the jar loaded dynamically.

**Comment by oraluben** [comment]
Is that related to #4806?

**Comment by wise-coders** [comment]
I think yes. But the solution for my issue was to set the Thread contextClassLoader. This saved me. 
Please test my scenario, when GraalVM libraries are loaded using URLClassLoader. Without the contextclassloader the truffle-api.jar is not loaded.
