### ISSUE TITLE
Bug in documentation for Source.Builder.buildLiteral

### ISSUE THREAD

**Issue by Daniel-Alievsky** [oracle/graal#4873]
In comments to buildLiteral method, it is written:

`Uses configuration of this builder to create new Source object. This method can only be used if the builder was created as string literal builder and otherwise throws an UnsupportedOperationException.`

However, inside the implementation I see simple call of common build() method without any checks of the builder type. Really, I can easily call buildLiteral with source, created from file:

`Source sourceInFile = Source.newBuilder("js", file).buildLiteral();`

(file is an instance of Java File object for an existing JavaScript file). It seems that the documentation to this method is incorrect.

**Comment by olyagpl** [comment]
@Daniel-Alievsky,  [`Source.Builder.buildLiteral()` method description](https://github.com/oracle/graal/blob/master/sdk/src/org.graalvm.polyglot/src/org/graalvm/polyglot/Source.java#L934) was improved. Thank you for the report.
