### ISSUE TITLE
must not contain ".". This can happen implicitly if the builder runs exclusively  ????

### ISSUE THREAD

**Issue by iceman567** [oracle/graal#4874]
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools>native-image -jar E:/workspace/nukeaio/new/nukeaio/client/target/nuke-jar-with-dependencies.jar --no-fallback --allow-incomplete-classpath --native-image-info --verbose
Apply jar:file:///E:/workspace/nukeaio/new/nukeaio/client/target/nuke-jar-with-dependencies.jar!/META-INF/native-image/io.netty/transport/native-image.properties
Apply jar:file:///E:/workspace/nukeaio/new/nukeaio/client/target/nuke-jar-with-dependencies.jar!/META-INF/native-image/io.netty/resolver-dns/native-image.properties
Apply jar:file:///E:/workspace/nukeaio/new/nukeaio/client/target/nuke-jar-with-dependencies.jar!/META-INF/native-image/io.netty/handler/native-image.properties
Apply jar:file:///E:/workspace/nukeaio/new/nukeaio/client/target/nuke-jar-with-dependencies.jar!/META-INF/native-image/io.netty/common/native-image.properties
Apply jar:file:///E:/workspace/nukeaio/new/nukeaio/client/target/nuke-jar-with-dependencies.jar!/META-INF/native-image/io.netty/codec-http2/native-image.properties
Apply jar:file:///E:/workspace/nukeaio/new/nukeaio/client/target/nuke-jar-with-dependencies.jar!/META-INF/native-image/io.netty/codec-http/native-image.properties
Apply jar:file:///E:/workspace/nukeaio/new/nukeaio/client/target/nuke-jar-with-dependencies.jar!/META-INF/native-image/io.netty/buffer/native-image.properties
Warning: Using a deprecated option --allow-incomplete-classpath from command line. Allowing an incomplete classpath is now the default. Use --link-at-build-time to report linking errors at image build time for a class or package.
Executing [
'E:\graalvm-ce-java11\bin\java.exe' \
-XX:+UseParallelGC \
-XX:+UnlockExperimentalVMOptions \
-XX:+EnableJVMCI \
-Dtruffle.TrustAllTruffleRuntimeProviders=true \
-Dtruffle.TruffleRuntime=com.oracle.truffle.api.impl.DefaultTruffleRuntime \
-Dgraalvm.ForcePolyglotInvalid=true \
-Dgraalvm.locatorDisabled=true \
-Dsubstratevm.IgnoreGraalVersionCheck=true \
--add-exports=java.base/com.sun.crypto.provider=org.graalvm.nativeimage.builder \
--add-exports=java.base/jdk.internal.event=org.graalvm.nativeimage.builder \
--add-exports=java.base/jdk.internal.loader=org.graalvm.nativeimage.builder,org.graalvm.truffle \
--add-exports=java.base/jdk.internal.logger=org.graalvm.nativeimage.builder \
--add-exports=java.base/jdk.internal.misc=org.graalvm.nativeimage.builder,org.graalvm.nativeimage.objectfile \
--add-exports=java.base/jdk.internal.module=jdk.internal.vm.compiler,org.graalvm.nativeimage.base,org.graalvm.nativeimage.builder \
--add-exports=java.base/jdk.internal.org.objectweb.asm=org.graalvm.nativeimage.builder \
--add-exports=java.base/jdk.internal.perf=org.graalvm.nativeimage.builder \
--add-exports=java.base/jdk.internal.ref=org.graalvm.nativeimage.builder,org.graalvm.nativeimage.objectfile \
--add-exports=java.base/jdk.internal.reflect=org.graalvm.nativeimage.builder \
--add-exports=java.base/jdk.internal.vm.annotation=org.graalvm.nativeimage.builder \
--add-exports=java.base/sun.invoke.util=org.graalvm.nativeimage.builder \
--add-exports=java.base/sun.net=org.graalvm.nativeimage.builder \
--add-exports=java.base/sun.nio.ch=org.graalvm.nativeimage.builder,org.graalvm.nativeimage.objectfile \
--add-exports=java.base/sun.reflect.annotation=org.graalvm.nativeimage.builder \
--add-exports=java.base/sun.reflect.generics.factory=org.graalvm.nativeimage.builder \
--add-exports=java.base/sun.reflect.generics.reflectiveObjects=org.graalvm.nativeimage.builder \
--add-exports=java.base/sun.reflect.generics.repository=org.graalvm.nativeimage.builder \
--add-exports=java.base/sun.reflect.generics.scope=org.graalvm.nativeimage.builder \
--add-exports=java.base/sun.reflect.generics.tree=org.graalvm.nativeimage.builder \
--add-exports=java.base/sun.security.jca=org.graalvm.nativeimage.builder \
--add-exports=java.base/sun.security.provider=org.graalvm.nativeimage.builder \
--add-exports=java.base/sun.security.ssl=org.graalvm.nativeimage.builder \
--add-exports=java.base/sun.security.util=org.graalvm.nativeimage.builder \
--add-exports=java.base/sun.security.x509=org.graalvm.nativeimage.builder \
--add-exports=java.base/sun.text.spi=org.graalvm.nativeimage.builder \
--add-exports=java.base/sun.util.calendar=org.graalvm.nativeimage.builder \
--add-exports=java.base/sun.util.cldr=org.graalvm.nativeimage.builder \
--add-exports=java.base/sun.util.locale.provider=org.graalvm.nativeimage.builder \
--add-exports=java.base/sun.util.locale=org.graalvm.nativeimage.builder \
--add-exports=java.base/sun.util.resources=org.graalvm.nativeimage.builder \
--add-exports=java.base/sun.util=org.graalvm.nativeimage.builder \
--add-exports=java.desktop/sun.java2d.pipe=org.graalvm.nativeimage.builder \
--add-exports=java.desktop/sun.java2d=org.graalvm.nativeimage.builder \
--add-exports=java.management/com.sun.jmx.mbeanserver=org.graalvm.nativeimage.builder \
--add-exports=java.management/sun.management=org.graalvm.nativeimage.builder,org.graalvm.nativeimage.pointsto \
--add-exports=java.xml.crypto/org.jcp.xml.dsig.internal.dom=org.graalvm.nativeimage.builder \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.aarch64=jdk.internal.vm.compiler,org.graalvm.nativeimage.builder,org.graalvm.nativeimage.objectfile \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.amd64=jdk.internal.vm.compiler,org.graalvm.nativeimage.builder,org.graalvm.nativeimage.objectfile \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.code.site=jdk.internal.vm.compiler,org.graalvm.nativeimage.builder \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.code.stack=jdk.internal.vm.compiler,org.graalvm.nativeimage.builder \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.code=jdk.internal.vm.compiler,org.graalvm.nativeimage.builder,org.graalvm.nativeimage.objectfile,org.graalvm.nativeimage.pointsto \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.common=jdk.internal.vm.compiler,org.graalvm.nativeimage.builder,org.graalvm.nativeimage.pointsto \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.hotspot.aarch64=jdk.internal.vm.compiler \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.hotspot.amd64=jdk.internal.vm.compiler \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.hotspot.sparc=jdk.internal.vm.compiler \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.hotspot=jdk.internal.vm.compiler,org.graalvm.nativeimage.builder \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.meta=jdk.internal.vm.compiler,org.graalvm.nativeimage.builder,org.graalvm.nativeimage.objectfile,org.graalvm.nativeimage.pointsto \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.runtime=jdk.internal.vm.compiler,org.graalvm.nativeimage.builder,org.graalvm.nativeimage.pointsto \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.services=jdk.internal.vm.compiler,org.graalvm.nativeimage.builder \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.sparc=jdk.internal.vm.compiler \
--add-exports=jdk.jfr/jdk.jfr.events=org.graalvm.nativeimage.builder \
--add-exports=jdk.jfr/jdk.jfr.internal.handlers=org.graalvm.nativeimage.builder \
--add-exports=jdk.jfr/jdk.jfr.internal.jfc=org.graalvm.nativeimage.builder \
--add-exports=jdk.jfr/jdk.jfr.internal=org.graalvm.nativeimage.builder \
--add-exports=jdk.management/com.sun.management.internal=org.graalvm.nativeimage.builder \
-XX:+UseJVMCINativeLibrary \
-Xss10m \
-Xms1g \
-Xmx14g \
-Djava.awt.headless=true \
-Dorg.graalvm.version=22.2.0 \
-Dcom.oracle.graalvm.isaot=true \
-Djava.system.class.loader=com.oracle.svm.hosted.NativeImageSystemClassLoader \
-Xshare:off \
-Djdk.internal.lambda.disableEagerInitialization=true \
-Djdk.internal.lambda.eagerlyInitialize=false \
-Djava.lang.invoke.InnerClassLambdaMetafactory.initializeLambdas=false \
'-javaagent:E:\graalvm-ce-java11\lib\svm\builder\svm.jar' \
--module-path \
'E:\graalvm-ce-java11\lib\truffle\truffle-api.jar;E:\graalvm-ce-java11\lib\svm\builder\native-image-base.jar;E:\graalvm-ce-java11\lib\svm\builder\objectfile.jar;E:\graalvm-ce-java11\lib\svm\builder\pointsto.jar;E:\graalvm-ce-java11\lib\svm\builder\svm.jar' \
--module \
org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner \
-imagecp \
'E:\workspace\nukeaio\new\nukeaio\client\target\nuke-jar-with-dependencies.jar' \
-imagemp \
'E:\graalvm-ce-java11\lib\svm\library-support.jar' \
'-H:CLibraryPath=E:\graalvm-ce-java11\lib\svm\clibraries\windows-amd64' \
'-H:Path=C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools' \
'-H:Class@manifest from file:///E:/workspace/nukeaio/new/nukeaio/client/target/nuke-jar-with-dependencies.jar=com.nuke.client.Main' \
'-H:Name@manifest from file:///E:/workspace/nukeaio/new/nukeaio/client/target/nuke-jar-with-dependencies.jar=nuke-jar-with-dependencies' \
'-H:ReflectionConfigurationResources@jar:file:///E:/workspace/nukeaio/new/nukeaio/client/target/nuke-jar-with-dependencies.jar!/META-INF/native-image/io.netty/transport/native-image.properties=META-INF/native-image/io.netty/transport/reflection-config.json' \
'-H:ClassInitialization@jar:file:///E:/workspace/nukeaio/new/nukeaio/client/target/nuke-jar-with-dependencies.jar!/META-INF/native-image/io.netty/resolver-dns/native-image.properties=io.netty.resolver.dns.DefaultDnsServerAddressStreamProvider:run_time' \
'-H:ClassInitialization@jar:file:///E:/workspace/nukeaio/new/nukeaio/client/target/nuke-jar-with-dependencies.jar!/META-INF/native-image/io.netty/resolver-dns/native-image.properties=io.netty.resolver.dns.DnsServerAddressStreamProviders$DefaultProviderHolder:run_time' \
'-H:ClassInitialization@jar:file:///E:/workspace/nukeaio/new/nukeaio/client/target/nuke-jar-with-dependencies.jar!/META-INF/native-image/io.netty/resolver-dns/native-image.properties=io.netty.resolver.dns.DnsNameResolver:run_time' \
'-H:ClassInitialization@jar:file:///E:/workspace/nukeaio/new/nukeaio/client/target/nuke-jar-with-dependencies.jar!/META-INF/native-image/io.netty/resolver-dns/native-image.properties=io.netty.resolver.HostsFileEntriesResolver:run_time' \
'-H:ClassInitialization@jar:file:///E:/workspace/nukeaio/new/nukeaio/client/target/nuke-jar-with-dependencies.jar!/META-INF/native-image/io.netty/handler/native-image.properties=io.netty.handler.ssl.util.ThreadLocalInsecureRandom:run_time' \
'-H:ClassInitialization@jar:file:///E:/workspace/nukeaio/new/nukeaio/client/target/nuke-jar-with-dependencies.jar!/META-INF/native-image/io.netty/common/native-image.properties=io.netty.util.AbstractReferenceCounted:run_time,io.netty.util.concurrent.GlobalEventExecutor:run_time,io.netty.util.concurrent.ImmediateEventExecutor:run_time,io.netty.util.concurrent.ScheduledFutureTask:run_time,io.netty.util.internal.ThreadLocalRandom:run_time' \
'-H:ClassInitialization@jar:file:///E:/workspace/nukeaio/new/nukeaio/client/target/nuke-jar-with-dependencies.jar!/META-INF/native-image/io.netty/common/native-image.properties=io.netty.util.NetUtilSubstitutions$NetUtilLocalhost4LazyHolder:run_time' \
'-H:ClassInitialization@jar:file:///E:/workspace/nukeaio/new/nukeaio/client/target/nuke-jar-with-dependencies.jar!/META-INF/native-image/io.netty/common/native-image.properties=io.netty.util.NetUtilSubstitutions$NetUtilLocalhost6LazyHolder:run_time' \
'-H:ClassInitialization@jar:file:///E:/workspace/nukeaio/new/nukeaio/client/target/nuke-jar-with-dependencies.jar!/META-INF/native-image/io.netty/common/native-image.properties=io.netty.util.NetUtilSubstitutions$NetUtilLocalhostLazyHolder:run_time' \
'-H:ClassInitialization@jar:file:///E:/workspace/nukeaio/new/nukeaio/client/target/nuke-jar-with-dependencies.jar!/META-INF/native-image/io.netty/codec-http2/native-image.properties=io.netty:build_time' \
'-H:ClassInitialization@jar:file:///E:/workspace/nukeaio/new/nukeaio/client/target/nuke-jar-with-dependencies.jar!/META-INF/native-image/io.netty/codec-http2/native-image.properties=io.netty.handler.codec.http2.Http2CodecUtil:run_time,io.netty.handler.codec.http2.Http2ClientUpgradeCodec:run_time,io.netty.handler.codec.http2.Http2ConnectionHandler:run_time,io.netty.handler.codec.http2.DefaultHttp2FrameWriter:run_time' \
'-H:ClassInitialization@jar:file:///E:/workspace/nukeaio/new/nukeaio/client/target/nuke-jar-with-dependencies.jar!/META-INF/native-image/io.netty/codec-http/native-image.properties=io.netty:build_time' \
'-H:ClassInitialization@jar:file:///E:/workspace/nukeaio/new/nukeaio/client/target/nuke-jar-with-dependencies.jar!/META-INF/native-image/io.netty/codec-http/native-image.properties=io.netty.handler.codec.http.HttpObjectEncoder:run_time,io.netty.handler.codec.http.websocketx.WebSocket00FrameEncoder:run_time,io.netty.handler.codec.http.websocketx.extensions.compression.DeflateDecoder:run_time,io.netty.handler.codec.compression.BrotliDecoder:run_time' \
'-H:ClassInitialization@jar:file:///E:/workspace/nukeaio/new/nukeaio/client/target/nuke-jar-with-dependencies.jar!/META-INF/native-image/io.netty/buffer/native-image.properties=io.netty.buffer.PooledByteBufAllocator:run_time,io.netty.buffer.ByteBufAllocator:run_time,io.netty.buffer.ByteBufUtil:run_time,io.netty.buffer.AbstractReferenceCountedByteBuf:run_time' \
-H:FallbackThreshold=0 \
-H:+AllowIncompleteClasspath \
-H:+DumpTargetInfo
]
Fatal error: com.oracle.svm.core.util.VMError$HostedError: The classpath of com.oracle.svm.hosted.NativeImageGeneratorRunner must not contain ".". This can happen implicitly if the builder runs exclusively on the --module-path but specifies the com.oracle.svm.hosted.NativeImageGeneratorRunner main class without --module.
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.util.VMError.shouldNotReachHere(VMError.java:68)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageClassLoaderSupport.<init>(NativeImageClassLoaderSupport.java:130)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.installNativeImageClassLoader(NativeImageGeneratorRunner.java:180)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:123)
Error: Image build request failed with exit status 1
com.oracle.svm.driver.NativeImage$NativeImageError: Image build request failed with exit status 1
        at com.oracle.svm.driver.NativeImage.showError(NativeImage.java:1716)
        at com.oracle.svm.driver.NativeImage.build(NativeImage.java:1413)
        at com.oracle.svm.driver.NativeImage.performBuild(NativeImage.java:1374)
        at com.oracle.svm.driver.NativeImage.main(NativeImage.java:1361)

What went wrong?
What went wrong?
What went wrong?
What went wrong?

**Comment by toohandsome** [comment]
same error , try  remove "." from your classpath environment variable.
but i get another error
```
[1/7] Initializing...                                                                                   (0.0s @ 0.11GB)
Error: Main entry point class 'com.xxx.xiaoai2meidi.Main' neither found on the classpath nor on the modulepath.
classpath: 'F:\xiaoai2meidi\target\xiaoai2meidi-1.0-SNAPSHOT.jar'
modulepath: 'D:\graalvm-ce-java17-22.2.0\lib\svm\library-support.jar'
Error: Use -H:+ReportExceptionStackTraces to print stacktrace of underlying exception
Error: Image build request failed with exit status 1
com.oracle.svm.driver.NativeImage$NativeImageError: Image build request failed with exit status 1
        at com.oracle.svm.driver.NativeImage.showError(NativeImage.java:1716)
        at com.oracle.svm.driver.NativeImage.build(NativeImage.java:1413)
        at com.oracle.svm.driver.NativeImage.performBuild(NativeImage.java:1374)
        at com.oracle.svm.driver.NativeImage.main(NativeImage.java:1361)

```

**Comment by iceman567** [comment]
> same error , try remove "." from your classpath environment variable. but i get another error
> 
> ```
> [1/7] Initializing...                                                                                   (0.0s @ 0.11GB)
> Error: Main entry point class 'com.xxx.xiaoai2meidi.Main' neither found on the classpath nor on the modulepath.
> classpath: 'F:\xiaoai2meidi\target\xiaoai2meidi-1.0-SNAPSHOT.jar'
> modulepath: 'D:\graalvm-ce-java17-22.2.0\lib\svm\library-support.jar'
> Error: Use -H:+ReportExceptionStackTraces to print stacktrace of underlying exception
> Error: Image build request failed with exit status 1
> com.oracle.svm.driver.NativeImage$NativeImageError: Image build request failed with exit status 1
>         at com.oracle.svm.driver.NativeImage.showError(NativeImage.java:1716)
>         at com.oracle.svm.driver.NativeImage.build(NativeImage.java:1413)
>         at com.oracle.svm.driver.NativeImage.performBuild(NativeImage.java:1374)
>         at com.oracle.svm.driver.NativeImage.main(NativeImage.java:1361)
> ```

java  swing   ？？  google   graalvm swing

**Comment by toohandsome** [comment]
> > same error , try remove "." from your classpath environment variable. but i get another error
> > ```
> > [1/7] Initializing...                                                                                   (0.0s @ 0.11GB)
> > Error: Main entry point class 'com.xxx.xiaoai2meidi.Main' neither found on the classpath nor on the modulepath.
> > classpath: 'F:\xiaoai2meidi\target\xiaoai2meidi-1.0-SNAPSHOT.jar'
> > modulepath: 'D:\graalvm-ce-java17-22.2.0\lib\svm\library-support.jar'
> > Error: Use -H:+ReportExceptionStackTraces to print stacktrace of underlying exception
> > Error: Image build request failed with exit status 1
> > com.oracle.svm.driver.NativeImage$NativeImageError: Image build request failed with exit status 1
> >         at com.oracle.svm.driver.NativeImage.showError(NativeImage.java:1716)
> >         at com.oracle.svm.driver.NativeImage.build(NativeImage.java:1413)
> >         at com.oracle.svm.driver.NativeImage.performBuild(NativeImage.java:1374)
> >         at com.oracle.svm.driver.NativeImage.main(NativeImage.java:1361)
> > ```
> 
> java swing ？？ google graalvm swing

no , it's a sping boot application

**Comment by oubidar-Abderrahim** [comment]
Hi, thank you for reporting this, could you please provide a reproducer to this issue with step? thank you

**Comment by iceman567** [comment]
> > > same error , try remove "." from your classpath environment variable. but i get another error
> > > ```
> > > [1/7] Initializing...                                                                                   (0.0s @ 0.11GB)
> > > Error: Main entry point class 'com.xxx.xiaoai2meidi.Main' neither found on the classpath nor on the modulepath.
> > > classpath: 'F:\xiaoai2meidi\target\xiaoai2meidi-1.0-SNAPSHOT.jar'
> > > modulepath: 'D:\graalvm-ce-java17-22.2.0\lib\svm\library-support.jar'
> > > Error: Use -H:+ReportExceptionStackTraces to print stacktrace of underlying exception
> > > Error: Image build request failed with exit status 1
> > > com.oracle.svm.driver.NativeImage$NativeImageError: Image build request failed with exit status 1
> > >         at com.oracle.svm.driver.NativeImage.showError(NativeImage.java:1716)
> > >         at com.oracle.svm.driver.NativeImage.build(NativeImage.java:1413)
> > >         at com.oracle.svm.driver.NativeImage.performBuild(NativeImage.java:1374)
> > >         at com.oracle.svm.driver.NativeImage.main(NativeImage.java:1361)
> > > ```
> > 
> > 
> > java swing ？？ google graalvm swing
> 
> no , it's a sping boot application

This solution solves my problem

**Comment by cforce** [comment]
I didn't get it .. what "." in path bare meant here? What exactly needs to be removed and how  did you achieve that as the maven plugin does the Classpath paramater composition based on the jar path with juts one entry

```
[INFO] --- native-maven-plugin:0.9.15:compile-no-fork (build-native) @ cloud-function-aws ---
[INFO] Executing: C:\Program Files\GraalVM\graalvm-ce-java17-22.2.0\bin\native-image.cmd -cp C:\Users\user\git\spring-native\samples\cloud-function-aws\target\cloud-function-aws-0_0_1-SNAPSHOT-shaded.jar --no-fallback -H:Path=C:\Users\user\git\spring-native\samples\cloud-function-aws\target -H:Name=cloud-function-aws
Fatal error: com.oracle.svm.core.util.VMError$HostedError: The classpath of com.oracle.svm.hosted.NativeImageGeneratorRunner must not contain ".". This can happen implicitly if the builder runs exclusively on the --module-path but specifies the com.oracle.svm.hosted.NativeImageGeneratorRunner main class without --module.
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.util.VMError.shouldNotReachHere(VMError.java:68)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageClassLoaderSupport.<init>(NativeImageClassLoaderSupport.java:130)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.installNativeImageClassLoader(NativeImageGeneratorRunner.java:180)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:123)
Error: Image build request failed with exit status 1
```
