### ISSUE TITLE
A fatal error occurred after invoking the JSSC package

### ISSUE THREAD

**Issue by houyuea** [oracle/graal#4878]
**Problem description**
When  I create the service to read modbusRTU protocol, I introduced the dependency package of modbus4j:3.1.0/rxtx:2.1.7 and JSSC: 2.8.0 When the service was started and the code in the JSSC package was called, a fatal exception occurred and the service exits. The error message is as follows:
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x000000007110b5db, pid=17088, tid=20220
#
# JRE version: OpenJDK Runtime Environment GraalVM CE 22.0.0.2 (11.0.14+9) (build 11.0.14+9-jvmci-22.0-b05)
# Java VM: OpenJDK 64-Bit Server VM GraalVM CE 22.0.0.2 (11.0.14+9-jvmci-22.0-b05, mixed mode, sharing, tiered, jvmci, jvmci compiler, compressed oops, g1 gc, windows-amd64)
# Problematic frame:
# C  [jSSC-2.8_x86_64.dll+0xb5db]
#
# No core dump will be written. Minidumps are not enabled by default on client versions of Windows
#
# An error report file with more information is saved as:
# G:\IOT\edge\demoModbusRTU\hs_err_pid17088.log
#
# If you would like to submit a bug report, please visit:
#   https://github.com/oracle/graal/issues
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#

**Describe GraalVM and your environment:**
 - GraalVM version 22.0.0.2
 - JDK：**11.0.14**
 - OS:** Windows10**
 - Architecture: **AMD64]**

# Thanks

**Comment by oubidar-Abderrahim** [comment]
Hi @houyuea, Thank you for reporting this. First of all, you're using an outdated version of GraalVM. Please use the latest GraalVM version 22.2
If the issue still occurs after upgrading to 22.2, please share the log generated in `G:\IOT\edge\demoModbusRTU\hs_err_pidxxxxx.log` and it would be better if you can provide an example application to reproduce the issue.
