### ISSUE TITLE
Debugger points to wrong position in an expression

### ISSUE THREAD

**Issue by nirvdrum** [oracle/graal#4902]
It looks like our `SourceSection` are wrong or they don't match what the Truffle debugger is expecting. I'm trying to debug a simple Ruby script with VS Code and the helpful arrow to indicate position appears to point at the last token for an expression. Given the following Ruby script:

```ruby
def square(x)
  x * x
end

loop do
  [1, 2, 3, 4].each do |i|
    square(i)
  end
end
```

Set a breakpoint on L6 (the start of the `[1, 2, 3, 4]` array). As you step through the application, the debugger arrow used to indicate where you are in an expression moves around. Stepping over that line will take you into the definition of `loop`, where the "d" in "yield" is highlighted:

![image](https://user-images.githubusercontent.com/12584/188910071-904f27d8-f8d5-471c-a9b9-7a54eb372ddf.png)

Continuing to step through the application, the block argument closing pipe is highlighted rather than the block arguments:

![image](https://user-images.githubusercontent.com/12584/188910246-3f3e7741-b16e-4d15-8d86-a868af0955ae.png)

Stepping into the call to `square`, the "d" in "end" is highlighted:

![image](https://user-images.githubusercontent.com/12584/188910379-65e322c6-a3c7-48b4-840e-8854d97f5f67.png)

**Comment by eregon** [comment]
@nirvdrum Did you use `protocol: chromeDevTools` or `protocol: debugAdapter`?
(From https://www.graalvm.org/dev/tools/vscode/graalvm-extension/polyglot-runtime/#debugging-ruby)

In general I would recommend `protocol: debugAdapter` because it's more complete and supports threads.

**Comment by nirvdrum** [comment]
I did not configure the `protocol` value. I'm not terribly familiar with VS Code to begin with. I thought sticking to the defaults in the GraalVM extension would lead to the best experience.

**Comment by entlicher** [comment]
Fixed by https://github.com/oracle/graal/commit/5b72b3dc6faa58c918fc2fe885096ec82b498d57
