### ISSUE TITLE
Moving jdk.aot (jaotc) module to Graal repo.

### ISSUE THREAD

**Issue by mukel** [oracle/graal#491]
We'll be soon moving jdk.aot into Graal repo, it will be part of our gate (+weekly for aarch64). FYI @theRealAph

**Comment by theRealAph** [comment]
On 06/22/2018 09:44 AM, Alfonso² Peterssen wrote:
> We'll be soon moving jdk.aot into Graal repo, it will be part of our gate (+weekly for aarch64). FYI @theRealAph

Nice to know.  It does make sense, but there is some tight coupling
between HotSpot features and jdk.aot so it'll be interesting to try
to keep it all in step.

-- 
Andrew Haley
Java Platform Lead Engineer
Red Hat UK Ltd. <https://www.redhat.com>
EAC8 43EB D3EF DB98 CC77 2FAD A5CD 6035 332F A671

**Comment by mukel** [comment]
Moved to #492
