### ISSUE TITLE
Confusing error message from debugger console

### ISSUE THREAD

**Issue by nirvdrum** [oracle/graal#4933]
**Describe GraalVM and your environment :**
 - GraalVM version or commit id if built from source: **22.3.0-dev f9726d7f20f5fce7b26578886a01e3750807d5d6**
 - CE or EE: **CE**
 - JDK version: **JDK11**
 - OS and OS Version: **Ubuntu 21.10**
 - Architecture: **amd64**
 - The output of `java -Xinternalversion`:
```
OpenJDK 64-Bit Server VM (11.0.16+7-jvmci-22.3-b02) for linux-amd64 JRE (11.0.16+7-jvmci-22.3-b02), built on Jul 13 2022 17:12:49 by "buildslave" with gcc 7.3.0
```

**Have you verified this issue still happens when using the latest snapshot?**
Yes

**Describe the issue**
While debugging a TruffleRuby application, I misidentified the class of an object and attempted to call a method on it that does not exist in the console. Instead of getting a Ruby `NoMethodError`, I was shown a message that says "Stack frame not valid". I then tried to enter an invalid expression an was given the same error, instead of a parse exception.

![image](https://user-images.githubusercontent.com/12584/189735990-5c59326a-6f82-403c-bf60-192ec863f48f.png)

**Steps to reproduce the issue**
Please include both build steps as well as run steps
1. Debug a Ruby script in VS Code with the GraalVM Tools for Java extension with TruffleRuby
2. At a breakpoint, switch to the "Debug Console" view and input an expression that would raise an exception upon evaluation (e.g., `42.bytesize`)
3. Look at the error message

**Expected behavior**
I'd expect to see the underlying language error message. E.g., `undefined method `bytesize' for 42:Integer (NoMethodError)`. Even better, it would be helpful to see the exception backtrace as well.

**Comment by entlicher** [comment]
Fixed by https://github.com/oracle/graal/commit/92667d41d583ef99010cf9fdc3b0942367a0ea27
