### ISSUE TITLE
Does espresso Support Jdk.jfr？

### ISSUE THREAD

**Issue by qwqawawow** [oracle/graal#4963]
**Describe GraalVM and your environment :**
 - GraalVM version or commit id if built from source: **[bb865f9]**
 - CE or EE: **[CE]**
 - JDK version: **[JDK17]**
 - OS and OS Version: **[Arch Linux arm]**
 - Architecture: **[amd64]**
 - The output of `java -Xinternalversion`:
```
 OpenJDK 64-Bit Server VM (17.0.5+3-jvmci-22.3-b04) for linux-aarch64 JRE (17.0.5+3-jvmci-22.3-b04), built on Sep  2 2022 08:14:45 by "buildslave" with gcc 10.3.0
```

**Have you verified this issue still happens when using the latest snapshot?**
Yes
**Describe the issue**
java -truffle class
jdk.jfr.FlightRecorder.isAvailable()
returns false.
**Code snippet or code repository that reproduces the issue**
```
System.out.println(jdk.jfr.FlightRecorder.isAvailable());
```

**Steps to reproduce the issue**
Please include both build steps as well as run steps
1. Step one [java -truffle classfile ]

**Expected behavior**
support jfr

**Additional context**
Add any other context about the problem here. Specially important are stack traces or log output. Feel free to link to gists or to screenshots if necesary
<details><summary>Details</summary>

```
[To redirect Truffle log output to a file use one of the following options:
* '--log.file=<path>' if the option is passed using a guest language launcher.
* '-Dpolyglot.log.file=<path>' if the option is passed using the host Java launcher.
* Configure logging using the polyglot embedding API.]
[java] WARNING: Failed to link native method: EspressoMethod<Ljdk/jfr/internal/JVM;.registerNatives()V>
```
</details>

**Comment by oubidar-Abderrahim** [comment]
Hi, Thank you for reporting this, we'll take a look into it shortly

**Comment by oubidar-Abderrahim** [comment]
Could you please share a complete example illustrating the issue for clarity? Thank you

**Comment by qwqawawow** [comment]
> Could you please share a complete example illustrating the issue for clarity? Thank you

I'm sorry for replying late.
I just try running a minecraft server.

**Comment by qwqawawow** [comment]
> Could you please share a complete example illustrating the issue for clarity? Thank you

I'm sorry for replying late.
I just try running a minecraft server.

**Comment by qwqawawow** [comment]
> Could you please share a complete example illustrating the issue for clarity? Thank you

I'm sorry for replying late.
I just try running a minecraft server.

**Comment by mukel** [comment]
Hi, I found the same issue when running the latest Minecraft. For some reason Minecraft depends on JFR and I couldn't find a way to disable/ignore it.
Espresso doesn't support JFR right now, but there's been discussions about adding JFR support in Truffle so all languages could use it, or adding it only on Espresso.

**Comment by oubidar-Abderrahim** [comment]
If this issue is still relevant in the latest GraalVM versions, please create a new issue for it and follow the template provided. Thank you
