### ISSUE TITLE
Polyglot function treated as BiFunction returning Value fails with a class cast

### ISSUE THREAD

**Issue by radeusgd** [oracle/graal#4967]
**Describe GraalVM and your environment :**
 - GraalVM version or commit id if built from source: **22.3.0-dev**
 - CE or EE: **CE**
 - JDK version: **JDK11**
 - OS and OS Version: **Ubuntu 22.04.1 LTS**
 - Architecture: **amd64**
 - The output of `java -Xinternalversion`:
```
OpenJDK 64-Bit Server VM (11.0.17+3-jvmci-22.3-b04) for linux-amd64 JRE (11.0.17+3-jvmci-22.3-b04), built on Sep  1 2022 00:00:31 by "buildslave" with gcc 7.3.0
```

**Have you verified this issue still happens when using the latest snapshot?**
I used one of the latest build snapshots.

**Describe the issue**
We can pass a polyglot function to Java and for example treat it as a `Function`, we can expect the return type to be `Value` so that we can handle the Polyglot value in some special ways.

We can also pass a 2 argument polyglot function to Java as a `BiFunction`, for example `BiFunction<Object, Object, Object>`.

Both of these features work correctly on their own. But if we use the two features at once - i.e. want a BiFunction returning a `polyglot.Value` so that we can manipulate it further, it breaks with a CCE.

**Code snippet or code repository that reproduces the issue**
```java
import org.graalvm.polyglot.Context;
import org.graalvm.polyglot.Value;

import java.util.function.BiFunction;
import java.util.function.Function;

public class Foo {
  public static class Proxy {
    public void function_value(Function<Object, Value> f) {
      Value v = f.apply("A");
      System.out.println(v + " (" + v.isString() + ", " + v.isNumber() + ")");
    }

    public void bifunction_object(BiFunction<Object, Object, Object> f) {
      Object o = f.apply("X", "Y");
      System.out.println(o + " (" + o.getClass().getCanonicalName() + ")");
    }

    public void bifunction_value(BiFunction<Object, Object, Value> f) {
      Value v = f.apply("X", "Y");
      System.out.println(v + " (" + v.isString() + ", " + v.isNumber() + ")");
    }
  }

  public static void main(String... args) {
    Context ctx = Context.newBuilder().allowAllAccess(true).build();
    try {
      Value main = ctx.eval("js", "(function(obj) {\n" +
                                  "  obj.function_value(function(x) { return \"F(\" + x + \")\"; });\n" +
                                  "  obj.bifunction_object(function(x, y) { return \"BFO(\" + x + \",\" + y + \")\"; });\n" +
                                  "  obj.bifunction_value(function(x, y) { return \"BFV(\" + x + \",\" + y + \")\"; });\n" +
                                  "})\n");
      main.execute(new Proxy());
    } catch (Exception e) {
      e.printStackTrace();
    }
  }
}
```

**Steps to reproduce the issue**
1. Create file `Foo.java` as above and compile it: `javac Foo.java`.
2. Run the file: `java Foo`.

**Expected behavior**
I would expect all calls to succeed. Instead the last call fails with CCE.

The output is
```
F(A) (true, false)
BFO(X,Y) (java.lang.String)
class java.lang.String cannot be cast to class org.graalvm.polyglot.Value (java.lang.String is in module java.base of loader 'bootstrap'; org.graalvm.polyglot.Value is in module org.graalvm.sdk of loader 'app')
	at Foo$Proxy.bifunction_value(Foo.java:20)
	at <js> :anonymous(Unnamed:4:161-235)
	at org.graalvm.sdk/org.graalvm.polyglot.Value.execute(Value.java:880)
	at Foo.main(Foo.java:33)
Caused by host exception: java.lang.ClassCastException: class java.lang.String cannot be cast to class org.graalvm.polyglot.Value (java.lang.String is in module java.base of loader 'bootstrap'; org.graalvm.polyglot.Value is in module org.graalvm.sdk of loader 'app')
```

We can see that the last call fails - it is because it wants to cast `String` to a `Value`, instead of doing special handling of the `Value` type, like is done in case of a regular `Function`.

**Comment by oubidar-Abderrahim** [comment]
Thank you for reporting this, we'll take a look into it and get back to you

**Comment by woess** [comment]
Thanks for the report. The problem is that our Polyglot function proxies only consider the generic return type of the declared method in the proxied interface but not the generic parameter types of the method they're passed into. I think we could specialize our proxy handlers to take target method information into account, to support this use case.

For now, you can work around this by using a custom functional interface, like so:
```java
    @FunctionalInterface
    public interface BiFunctionReturningValue<T, U> extends BiFunction<T, U, Value> {
        @Override
        Value apply(T t, U u);
    }
```

**Comment by woess** [comment]
Solved by https://github.com/oracle/graal/commit/5539bb2187b15bbc1ba71628f4d45cb21d50d145.
