### ISSUE TITLE
[GR-41098] HeapDumpWriterImpl retains memory after dump

### ISSUE THREAD

**Issue by SergejIsbrecht** [oracle/graal#4985]
**Describe the issue**
After `kill -s USR1 <pid>` a object `HeapDumpWriterImpl` with a field `fieldsMap` is left behind. This instance is visible in the .hprof file. In my case it consumes up to 32MiB of JavaHeap space. 

**Steps to reproduce the issue**
* build native-image with `-H:+AllowVMInspection` and SerialGC
* run native-image -- I my case with -Xmx256 -Xms256
* `kill -s USR1 <pid>`
* open hprof file with VisualVM and search for HeapDumpWriterImpl object. 

![native_image_heapdump](https://user-images.githubusercontent.com/4427685/190729852-31373c7d-f914-4dd9-9e5f-8b7e3581b450.png)
(it is not possible to provide the actual hprof file, but it should be easy to create a re-producible)

**Describe GraalVM and your environment:**
 - GraalVM version (latest snapshot builds can be found [here](https://github.com/graalvm/graalvm-ce-dev-builds/releases)), or commit id if built from source: **CE 22.2.0**
 - JDK major version: **11**
 - OS: **Linux 4.x**
 - Architecture: **aarch64**

**More details**
As far as I see it the object is referenced via JNI global, which means it will not be GC'ed.

The code is as follows:
```
        byte[] fieldsMapData = heapDumpUtils.getFieldsMap();
        if (fieldsMapData.length == 0) {
            throw new IOException("Empty fieldsMap");
        }
        fieldsMap = createFieldsMap(fieldsMapData);
```

`fieldsMap` is never zeroed out and therefore can not be collected (as far as I see it in the source code). 

** Idea ** 
I would clear the reference after the hprof file was written. After the HeapDump is done, the HashMap could be collected by the GC.

** Note **
Is it really a good idea to collect the data into an object on the Java-Heap? When the native-image is already running out of Java-Heap it would certainly fail, when a heap dump is triggered. Furthermore the instance of `HeapDumpWriterImpl` pollutes every created .hprof file. The measurement (hprof file) in this sense is not valid, because it is hard to reason about it. 
Therefore, I would suggest to somehow allocate memory outside of the Java-Heap and throw away the memory after the heap dump is done.

**Comment by fniephaus** [comment]
Thanks for filling this. See https://github.com/oracle/graal/issues/4637 for the issue on heap dump pollution. We'll look into a fix (unless you'd like to open a PR).

**Comment by SergejIsbrecht** [comment]
@fniephaus , thank you for your feedback. I did not find said issue #4637, because I `HeapDumpWriterImpl`. Anyhow, #4637 tries to resolve not polluting the Java-Heap, which is a little bit more, which I am asking for. As a full solution I would prefer HeapDumpWriter to allocate memory out of the JVM and throw it away. This would also resolve the issue with _leaking_ memory.

That being said, I would `null` all fields, which were set during heap dumping. This solution should be easily accomplished and should resolve the memory leak after the heap dump for now. 

In the next iteration I would suggest resolving #4637, which will probably take some more time.

**Comment by fniephaus** [comment]
Sounds good, will push a fix that clears all fields. @christianhaeubl is working on #4637 but that won't land in 22.3.

**Comment by SergejIsbrecht** [comment]
I already null'ed out the values and currently verify whether the GC will pick the null'ed fields up (SerailGC) with current master (HEAD). I am not quite sure how to write a test for it though.

**Comment by fniephaus** [comment]
Fixed via https://github.com/oracle/graal/commit/4e8f80e2b8779d1020eacb27ae79d66de8b7eb92.
