### ISSUE TITLE
[native-image] register resources from `Feature`

### ISSUE THREAD

**Issue by revintec** [oracle/graal#4986]
I'm using native-image on GraalVM 22.2, latest version as of writing
currently resources can be registered via command line `-H:IncludeResources`
but this requires different command lines for different OSes, or we have to pack redundant resources, e.g:
`-H:IncludeResources=jni-library.so -H:IncludeResources=jni-library.dylib -H:IncludeResources=jni-library.dll`

I would like to be able to selectively register resources from `Feature`
https://github.com/oracle/graal/blob/master/sdk/src/org.graalvm.nativeimage/src/org/graalvm/nativeimage/hosted/Feature.java
`registerResource(isLinux()?"jni-library.so":"jni-library.dylib");`

**Comment by revintec** [comment]
while we're at it, is it possible to add control for things like `-J--patch-module` to `native-image.properties` file? that would REALLY shorten our 10 foot long command line

**Comment by revintec** [comment]
some methods in `com.oracle.svm.core.jdk.Resources` seems interesting, is that class supported?

**Comment by fniephaus** [comment]
I believe this can be done with the extended public API that will ship with the 22.3 release next month: https://github.com/oracle/graal/pull/4783/files#diff-5b0b3d042bc6e1a39101162cc6c3ffc19f6369438eb761b6619ce3194527dd9c

Please re-open this if that's not what you are looking for.

**Comment by revintec** [comment]
it almost does the job, but can we also add resources using regularExpression pattern?

**Comment by fniephaus** [comment]
I don't think we want to allow regex matching. Please register each resource explicitly.

**Comment by revintec** [comment]
@fniephaus can I know why? it seems easy to implement, and supporting regex would make resource registration by code fully compatible with the commandline version, so the user won't have to manually enumerate all their resource -- a feature already provided by Graal

**Comment by olpaw** [comment]
@revintec allowing regex for resource registration is problematic for several reasons.
1. it forces us to scan the entire classpath (all files of all classpath entries) to find regex matches (slow, doesn't scale well)
2. it does compose. e.g. a `.*` regex does affect all parts of the classpath not individual entries (think of different libraries containing conflicting resources regex in their `resource-config.json` files).
3. leads to demand to also provide a way to `exclude` resources from getting added (a denylist for resource embedding) which causes even greater composability issues.

If we could turn back time we would have never allowed to specify resource inclusion via regex in the first place. Thus we decided for the public API to only allow explicit resource registration of individual entries. This has no scalability problems ans also does not lead to composablility issues.
