### ISSUE TITLE
[GR-41100] Introduce -XX:HeapDumpPath for native-image

### ISSUE THREAD

**Issue by SergejIsbrecht** [oracle/graal#4987]
**Feature request**

Please include the following information:

**Is your feature request related to a problem? Please describe.**
Currently when a heap dump is triggered via a signal handler (USR1), the heap dump will be written to the current location of application execution. This is sometimes not desired. 

```
    @Override
    public void handle(Signal arg0) {
        DateFormat dateFormat = new SimpleDateFormat("yyyyMMdd'T'HHmmss'Z'");
        dateFormat.setTimeZone(UTC_TIMEZONE);
        String heapDumpFileName = "svm-heapdump-" + ProcessProperties.getProcessID() + "-" + dateFormat.format(new Date()) + ".hprof";
        try {
            VMRuntime.dumpHeap(heapDumpFileName, true);
        } catch (IOException e) {
            Log.log().string("IOException during dumpHeap: ").string(e.getMessage()).newline();
        }
    }
```

**Describe the solution you'd like.**
It should be possible to provide a path, to which a .hprof files should be written, just like in the JVM with `-XX:HeapDumpPath=`.

**Describe who do you think will benefit the most.**
GraalVM users

**Describe alternatives you've considered.**
I could implement an own signal handler and do it myself, but I think such flag would make sense, because it is already available in the JVM

**Additional context.**
/

**Express whether you'd like to help contributing this feature**
If you'd like to contribute

**Comment by fniephaus** [comment]
Would you like to work on this, @SergejIsbrecht?

**Comment by SergejIsbrecht** [comment]
@fniephaus ,

yes, I will give it a go on the weekend.

**Comment by fniephaus** [comment]
I've opened #5344 with an implementation for this.
