### ISSUE TITLE
.rela.dyn expected to be > 100MiB?

### ISSUE THREAD

**Issue by SergejIsbrecht** [oracle/graal#4993]
**Describe the issue**
When building a _big_ (100k classes) application with native-image (default settings; 22.3.0-dev) and GCC 9 on Ubuntu 20.04 the `other data` section is quite large.

```
                                 -H:-IncludeMethodData \
                                 -H:-EnableAllSecurityServices \
                                 -H:+AllowVMInspection \
                                 -H:-UseServiceLoaderFeature \
                                 -H:-SpawnIsolates \
                                 -H:+UseSerialGC \
                                 -H:+ReportExceptionStackTraces \
                                 -H:Log=registerResource:verbose \
                                 --verbose \
                                 --no-fallback \
                                 -J-Xmx27g \
```
(Dwarf debug symbols are disabled, as per default)

```
 111.73MB (34.23%) for code area:   207,272 compilation units
 114.57MB (35.10%) for image heap:1,190,140 objects and 2 resources
 100.11MB (30.67%) for other data // <------
```

In the documentation it is said, that _[other data](https://github.com/oracle/graal/blob/master/docs/reference-manual/native-image/BuildOutput.md#glossary-other-data)_ should not contend for the largest position in the native-image. Therefore I was wondering. When looking at the binary with `readelf -S binary` it becomes apparent why this is:

```
  [ 9] .rela.dyn         RELA             0000000000002e40  00002e40
       000000000628f4d0  0000000000000018   A       5     0     8
```
_.rel.dyn .rela.dyn - relocation entries for dynamic symbols _
(https://blog.k3170makan.com/2018/10/introduction-to-elf-format-part-vi_18.html)

Is it actually expected behavior, that relocation table is that big?

**Steps to reproduce the issue**
Please include both build steps as well as run steps
1. build app with 100k classes with native image and given params
2. `readelf -S binary`

**Describe GraalVM and your environment:**
 - GraalVM version (latest snapshot builds can be found [here](https://github.com/graalvm/graalvm-ce-dev-builds/releases)), or commit id if built from source: **[22.3 HEAD]**
 - JDK major version: **11**
 - OS: **[Ubuntu 20.04 5.x]**
 - Architecture: **[AMD64]**

```
 Version info: 'GraalVM dev Java 11 CE'
 Java version info: '11.0.16+7-jvmci-22.3-b03'
 C compiler: gcc (linux, x86_64, 9.4.0)
 Garbage collector: Serial GC
```

**More details**
_see above_

** Note ** 
I can not provide the binary to reproduce it, but it should be possible with every binary, which more than hello world.

** Workaround ** 
Build with `-no-pie`, which is probably not recommended (https://gcc.gnu.org/bugzilla/show_bug.cgi?id=103398), but reduces the relocation table by a huge amount (from 100MiB to 3 MiB) 

```
                                 --native-compiler-options=-no-pie \
```

```
   1.74MB ( 0.77%) for other data
```

**Comment by SergejIsbrecht** [comment]
Here is some update

```
  [ 9] .rela.dyn         RELA             0000000000002d18  00002d18
       00000000070d9880  0000000000000018   A       5     0     8 // 112 MiB
  [10] .rela.plt         RELA             00000000070dc598  070dc598
       0000000000001158  0000000000000018  AI       5    24     8 // 
  [13] .text             PROGBITS         00000000070df000  070df000
       0000000007d037e4  0000000000000000  AX       0     0     4096 // 125MiB
```

objdump displays, that there are A LOT of this dynamic relocations
```
DYNAMIC RELOCATION RECORDS
OFFSET           TYPE              VALUE 
000000000ede3000 R_AARCH64_RELATIVE  *ABS*+0x0000000012b62cc0
000000000ede3008 R_AARCH64_RELATIVE  *ABS*+0x0000000012b62ce0
000000000ede3010 R_AARCH64_RELATIVE  *ABS*+0x0000000016248de8
000000000ede3018 R_AARCH64_RELATIVE  *ABS*+0x0000000016248e28
000000000ede3020 R_AARCH64_RELATIVE  *ABS*+0x0000000012b62d00
000000000ede3028 R_AARCH64_RELATIVE  *ABS*+0x0000000016248e68
000000000ede3030 R_AARCH64_RELATIVE  *ABS*+0x0000000012b62d20
```

For comparison we have a native c++ application with a 50MiB .text section and a ~4 MiB .rela.dyn section. I would guess the same size for relocations as the .text size seems excessive to me.

**Comment by christianwimmer** [comment]
You are using `-H:-SpawnIsolates`, which is an old mode where there are tons of relocations necessary for the image heap. So I'm not surprised about the size - but there is also no need for `-H:-SpawnIsolates` (which is untested and unsupported anyways).

**Comment by SergejIsbrecht** [comment]
@christianwimmer , thank you for taking a look. 

> but there is also no need for -H:-SpawnIsolates (which is untested and unsupported anyways).

I actually do not know why I am disabling it, maybe because I do not need to have isolates. 

There are some documentation pages suggesting to disable / enable isolates

> -H:+SpawnIsolates: enables isolates. (These are disabled by default when using the LLVM backend because they incur a performance penalty.)
https://www.graalvm.org/latest/reference-manual/native-image/LLVMBackend/

https://www.graalvm.org/latest/reference-manual/native-image/debugging-and-diagnostics/DebugInfo/

Also the flag `SpawnIsolates` seems to be documented
>  Support multiple isolates. 
(https://chriswhocodes.com/graalvm_native_image_ce_jdk17_options.html)

Could you maybe explain which impact (e.g. Performance?) `SpawnIsolates` has in GraalVM CE an what the default value would be?

Thank you

**Comment by christianwimmer** [comment]
> -H:+SpawnIsolates: enables isolates. (These are disabled by default when using the LLVM backend because they incur a performance penalty.)
https://www.graalvm.org/latest/reference-manual/native-image/LLVMBackend/

The documentation is outdated here, `SpawnIsolates` is enabled by default also with the LLVM backend.

We will also remove it from the debug info documentation, that is a bit misleading there too.

**Comment by christianwimmer** [comment]
@adinn There were always enough reasons to keep `SpawnIsolates` for prototyping and experimenting, so for now there we will keep it in the source code. But it certainly is a "if you don't know exactly what this flag is doing, then you should not use it" kind of flag.
