### ISSUE TITLE
Provide API for further use of non-API methods in Quarkus

### ISSUE THREAD

**Issue by zakkak** [oracle/graal#5013]
**Describe the issue**

Quarkus still depends on some Classes/Methods under the package `org.graalvm.nativeimage.impl` which do not appear to have obvious alternatives at the moment. These are:

* [`org.graalvm.nativeimage.impl.RuntimeResourceSupport#ignoreResources`](https://github.com/quarkusio/quarkus/blob/ebdf9223b1d66f3a05cf4f75fa523abf7261604b/core/deployment/src/main/java/io/quarkus/deployment/steps/NativeImageFeatureStep.java#L335-L336)
* [`org.graalvm.nativeimage.impl.RuntimeClassInitializationSupport#rerunInitialization`](https://github.com/quarkusio/quarkus/blob/ebdf9223b1d66f3a05cf4f75fa523abf7261604b/core/deployment/src/main/java/io/quarkus/deployment/steps/NativeImageFeatureStep.java#L259)

Relates to https://github.com/oracle/graal/issues/4919

cc @olpaw

**Comment by olpaw** [comment]
Regarding
> * [`org.graalvm.nativeimage.impl.RuntimeResourceSupport#ignoreResources`](https://github.com/quarkusio/quarkus/blob/ebdf9223b1d66f3a05cf4f75fa523abf7261604b/core/deployment/src/main/java/io/quarkus/deployment/steps/NativeImageFeatureStep.java#L335-L336)

We do not want to make that public API as it violates composability of the resource inclusion in native-image configuration metadata. There a several options to cope with that:
* Get rid of depending on `ignoreResources` by not over-including resources in the first place. I.e. at build time, iterate/walk the resources that you want to have included and register them individually.
* If you want to cancel out resource inclusion done by some other place (resource-config.json in some library that you use) , use `--exclude-config <jar-with-bad-config>` to get rid of its resource inclusion.
* keep using `RuntimeResourceSupport#ignoreResources` by opening up `org.graalvm.nativeimage.impl`

cc @christianwimmer

**Comment by zakkak** [comment]
We have removed the invocations to `org.graalvm.nativeimage.impl.RuntimeResourceSupport#ignoreResources` in https://github.com/quarkusio/quarkus/pull/31185

Is there any feedback regarding `org.graalvm.nativeimage.impl.RuntimeClassInitializationSupport#rerunInitialization`? Are there any plans to make this public as well, or not due to https://github.com/oracle/graal/pull/4684?

cc @christianwimmer

**Comment by christianwimmer** [comment]
> `rerunInitialization` is certainly not going to be API, because as you correctly note https://github.com/oracle/graal/pull/4684 should make every class have the semantic of "rerun" without needing explicit registration.

**Comment by zakkak** [comment]
> > `rerunInitialization` is certainly not going to be API, because as you correctly note #4684 should make every class have the semantic of "rerun" without needing explicit registration.

@christianwimmer apparently that's not true for classes explicitly set for build time initialization (the default for all classes in Quarkus). Such classes still require explicit registration for runtime initialization. As a result Quarkus still depends on `org.graalvm.nativeimage.impl.RuntimeClassInitializationSupport#rerunInitialization`

**Comment by zakkak** [comment]
Oh, I didn't understand this. Thanks @christianwimmer, that seems to do the trick.
