### ISSUE TITLE
Native image tracing agent should register canonical path for relative classpath resource

### ISSUE THREAD

**Issue by sbrannen** [oracle/graal#5029]
## Overview

This is a follow up to #2250.

If you request a **relative** classpath resource on the JVM while running with the native image tracing agent, the agent generates an entry in `resource-config.json` that is an invalid resource pattern.

## Example

If you invoke `getClass().getResourceAsStream("subdir/../example2.txt")`, the agent will generate the following entry in `resource-config.json`.

```json
{
  "resources":[
    {"pattern":"\\Qsubdir/../example2.txt\\E"}, 
  ],
  "bundles":[]
}
```

## Expected Behavior

Instead of generating `"pattern":"\\Qsubdir/../example2.txt\\E"`, the agent should generate a resource pattern for the canonical path: `"pattern":"\\Qexample2.txt\\E"`.

## System Tested

- GraalVM: OpenJDK Runtime Environment GraalVM CE 22.2.0 (build 17.0.4+8-jvmci-22.2-b06)
- Mac OS: Darwin Kernel Version 21.6.0: Mon Aug 22 20:19:52 PDT 2022; root:xnu-8020.140.49~2/RELEASE_ARM64_T6000 arm64

**Comment by oubidar-Abderrahim** [comment]
Hi, Thank you for reporting this, the issue seems clear enough but it would be much appreciated if you could share a small reproducer. Thank you

**Comment by sbrannen** [comment]
Hi @oubidar-Abderrahim,

The example in #2250 is the reproducer for this.

See https://github.com/oracle/graal/issues/2250#issuecomment-1253604659 for details.

Thanks

**Comment by dnestoro** [comment]
I've just [merged a PR](https://github.com/oracle/graal/pull/9577) that solves this issue

**Comment by sbrannen** [comment]
Thanks, @dnestoro! 👍
