### ISSUE TITLE
Image build request failed with exit status 137

### ISSUE THREAD

**Issue by CRY-D** [oracle/graal#5067]
**Describe the problem**
First, when I build a simple Hello world app, it works just fine, but when I try to build my **2.5Mb jar file** I always end up with this Error message **Error: Image build request failed with exit status 137** 
just like so, any hint to overcome this obstacle?

![select-area_20220924174852](https://user-images.githubusercontent.com/16564491/192109667-db481b71-ac55-4f13-8156-cb33043b34ac.png)

**System Info:**
 - OS: [e.g. `Linux Manjaro`]
 - GraalVM Version [`GraalVM 22.1.0 Java 11 CE`]
 - Java Version [`11`]
 - C compiler: gcc (pc, x86_64, 12.2.0)
 - Garbage collector: Serial GC

**Comment by ekoontz** [comment]
@CRY-D run `native-image` with `--verbose` to give more details of what went wrong.

**Comment by wirthi** [comment]
This _might_ be related to your process not having enough memory. How much RAM do you have available? Can you monitor whether you have enough available? Might any other installed tool on your machine send a SIGKILL in case you are tight on memory?

**Comment by dbuschman7** [comment]
I ran into this error this morning on a M1 MacBooK Pro with 32GB ram. Verbose give me this error

> Error: Image build request failed with exit status 137
com.oracle.svm.driver.NativeImage$NativeImageError: Image build request failed with exit status 137
	at com.oracle.svm.driver.NativeImage.showError(NativeImage.java:1762)
	at com.oracle.svm.driver.NativeImage.build(NativeImage.java:1473)
	at com.oracle.svm.driver.NativeImage.performBuild(NativeImage.java:1434)
	at com.oracle.svm.driver.NativeImage.main(NativeImage.java:1421)

Verbose is not very helpful unless you traipse through the source code.

This command works on Intel Macs, just not arm based machines.

**Comment by fernando-valdez** [comment]
@fniephaus, do you think this issue is related to GR-46399?

**Comment by fniephaus** [comment]
Exit status 137 is typically an out of memory error. We have just improve this a bit more by providing a better, more informative error message (see https://github.com/oracle/graal/pull/8161/files#diff-3f9d123cc0d7acc80e5efbb757a2a239830f88d29e2ebe561681f79fda900e47R36).

>do you think this issue is related to GR-46399?

@fernando-valdez yes, that ticket is also about OOM errors.


Given that the latest GraalVM shows build resources, peak RSS, and specific error messages for OOM errors, I think we can close this ticket. There is also a doc on [how to configure the max memory](https://github.com/oracle/graal/blob/master/docs/reference-manual/native-image/BuildOutput.md#build-resources) of the build process.

```
...
 Build resources:
 - 13.24GB of memory (42.7% of 31.00GB system memory, determined at start)
 - 16 thread(s) (100.0% of 16 available processor(s), determined at start)
...
--------------------------------------------------------------------------------
    0.8s (4.6% of total time) in 35 GCs | Peak RSS: 1.93GB | CPU load: 9.61
--------------------------------------------------------------------------------
```
