### ISSUE TITLE
[GR-41353] Potential reflection regression on GraalVM 22.3.0-dev

### ISSUE THREAD

**Issue by sdeleuze** [oracle/graal#5073]
I have just ran a full https://github.com/spring-projects/spring-aot-smoke-tests build with [this commit](https://github.com/oracle/graal/commit/3d56567289285d49f887612cb5762b2d60ea8ece) of GraalVM master, it is mostly fine but I think I have identified a regression. When compiling `session-jdbc` with `./gradlew session-jdbc:nativeCompile` then running `session-jdbc/build/native/nativeCompile/session-jdbc` there is a `Could not find a destroy method named 'shutdown' on bean with name 'dataSource'` error on, I think, `org.springframework.jdbc.datasource.embedded.EmbeddedDatabase` even if the reflection configuration is generated properly:
```
{
    "name": "org.springframework.jdbc.datasource.embedded.EmbeddedDatabase",
    "methods": [
      {
        "name": "shutdown",
        "parameterTypes": [ ]
      }
    ]
  }
```
The same sample is green with 22.2. Same issue on sample `cloud-task`.

**Comment by loicottet** [comment]
The failure happens when trying to get the `shutdown` method on `org.springframework.jdbc.datasource.embedded.EmbeddedDatabaseFactory$EmbeddedDataSourceProxy`, which is not in the metadata. Adding it should solve the problem.

**Comment by sdeleuze** [comment]
Do you know if a specific change in GraalVM between 22.2 and 22.3.0-dev has triggered this change of behavior?

**Comment by loicottet** [comment]
I'm not sure, but if this was working before, I'd say it was a wrong behaviour. Registering an interface method in the metadata should not automatically register its implementations.

**Comment by sdeleuze** [comment]
Ok let me check if we can refine the inference in order to have something working for both 22.2 and 22.3. I will update this issue accordingly.
