### ISSUE TITLE
Deploy vm-1.0.0-rc3 asset on GitHub releases

### ISSUE THREAD

**Issue by vhiairrassary** [oracle/graal#508]
Hi!

Is it possible to get the vm-1.0.0-rc3 asset deployed on GiHub as for rc2: https://github.com/oracle/graal/releases/tag/vm-1.0.0-rc2 (graalvm-ce-1.0.0-rc2-linux-amd64.tar.gz).

Let me know if I can help you with a PR for that.
Thanks!

P.S. Ideally it would be awesome to also have the associated PGP electronic signature (.asc file) and the mac version (available on http://www.oracle.com/technetwork/oracle-labs/program-languages/downloads/index.html).

**Comment by eregon** [comment]
RC3 is available now:
https://github.com/oracle/graal/releases (CE)
http://www.oracle.com/technetwork/oracle-labs/program-languages/downloads/index.html (EE)

**Comment by vhiairrassary** [comment]
Awesome thanks 🎉
