### ISSUE TITLE
Native Image FileSystem throws exception when resolving against an empty Path

### ISSUE THREAD

**Issue by sbrannen** [oracle/graal#5081]
## Overview

As stated in https://github.com/oracle/graal/issues/5020#issuecomment-1258192122 and https://github.com/oracle/graal/issues/5020#issuecomment-1258280110, if you invoke `fileSystem.getPath("")` against the native image `FileSystem` and then invoke `resolve(...)` on that `Path`, you get the following exception.

```
java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 0
       com.oracle.svm.core.jdk.resources.NativeImageResourcePath.resolve(NativeImageResourcePath.java:302)
       com.oracle.svm.core.jdk.resources.NativeImageResourcePath.resolve(NativeImageResourcePath.java:327)
```

Whereas, a `Path` created by the standard OS `FileSystem` does not throw an exception in that scenario.

For example...

```java
System.out.println("FileSystems.getDefault().getPath(\"\"): [%s]".formatted(FileSystems.getDefault().getPath("")));
System.out.println("FileSystems.getDefault().getPath(\"\").resolve(\"test\"): [%s]".formatted(FileSystems.getDefault().getPath("").resolve("test")));
```

... the above code prints the following on the JVM as well as within a native image.

```
FileSystems.getDefault().getPath(""): []
FileSystems.getDefault().getPath("").resolve("test"): [test]
```

Whereas, when executing the following within a native image...

```java
URI root = new URI("resource:/");
FileSystem nativeImageFileSystem = FileSystems.newFileSystem(root, Map.of());

System.out.println("nativeImageFileSystem.getPath(\"\"): [%s]".formatted(nativeImageFileSystem.getPath("")));
System.out.println("nativeImageFileSystem.getPath(\"\").resolve(\"test\"): [%s]".formatted(nativeImageFileSystem.getPath("").resolve("test")));
```

... that prints:

```
nativeImageFileSystem.getPath(""): []
```

... and then throws the aforementioned `ArrayIndexOutOfBoundsException`.

## Cause of the exception

In the following line of code...

https://github.com/oracle/graal/blob/3950e048071d97a24cb299d26ccc76580f00b6d5/substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jdk/resources/NativeImageResourcePath.java#L302

... if `p1.path.length` is 0, then you get the `ArrayIndexOutOfBoundsException`.

## System Tested

- GraalVM: OpenJDK Runtime Environment GraalVM CE 22.2.0 (build 17.0.4+8-jvmci-22.2-b06)
- Mac OS: Darwin Kernel Version 21.6.0: Mon Aug 22 20:19:52 PDT 2022; root:xnu-8020.140.49~2/RELEASE_ARM64_T6000 arm64

**Comment by jovanstevanovic** [comment]
Fix is on a master.

**Comment by sbrannen** [comment]
> Fix is on a master.

Great! 👍 

@fniephaus and @vjovanov, is there any way to have related commits automatically linked to the corresponding GitHub issue?

For example, I would like to see the commit(s) associated with the fix, but I don't know how to find them (at least not easily).
