### ISSUE TITLE
Publish graal-processor.jar in maven repository 

### ISSUE THREAD

**Issue by ziyilin** [oracle/graal#5083]
**Feature request**

When users extend Graal with new features, they may also need to add new options. The option descriptor code is automatically generated by the classes in `graal-processor.jar`. The jar file is shipped with GraalVM release, but is not available in maven repository. So that the users can't manage the dependency by maven pom.

Hope the `graal-processor.jar` file can also published in Maven online repository.

**Comment by superajun-wsj** [comment]
yes, our project extends Graal with new features, but we can't use graal-processor.jar by maven pom file, we hope that the jar was published in maven repository for convenience.

**Comment by oubidar-Abderrahim** [comment]
Thank you for your suggestion, we will take a look into it shortly

**Comment by oubidar-Abderrahim** [comment]
This was not planned
