### ISSUE TITLE
Backport: #5014 to 22.3

### ISSUE THREAD

**Issue by zakkak** [oracle/graal#5102]
**Backport request**

https://github.com/oracle/graal/pull/5014 significantly improves the tracing of object initialization and class instantiation. As a result we would like to see it landing in the 22.3 LTS release. It's OK if it won't make it to 22.3.0. Landing in 22.3.1 would still be good enough. 

cc @gilles-duboscq @ezzarghili

**Comment by gilles-duboscq** [comment]
Thanks for the suggestion. I agree it's worth having in 22.3.0.

**Comment by gilles-duboscq** [comment]
Done in https://github.com/oracle/graal/commit/b791f2ff0ff2a947d1d6f471393dc4fe0caea51e

**Comment by zakkak** [comment]
Thank you @gilles-duboscq !
