### ISSUE TITLE
Threads are duplicated in VS Code debugger "Call Stack" section

### ISSUE THREAD

**Issue by nirvdrum** [oracle/graal#5146]
I'm debugging a TruffleRuby application with VS Code using the GraalVM Tools for Java extension via the DAP adapter. The debugger includes a "Call Stack" view that shows all active threads and, if one is paused, the call stack for that thread. I'm seeing the same thread is appearing multiple times. For example, in the following screenshot you can see the thread with ID 91 appears three times right at the top:

![duplicate_callstack_entries](https://user-images.githubusercontent.com/12584/193827288-315fac35-7d16-403e-a6bd-9a23dc00081c.png)

Selecting one thread entry, selects all of its duplicated entries:

![duplicate_callstack_entries2](https://user-images.githubusercontent.com/12584/193827504-d768e6dd-5058-4044-a247-59f85fd838be.png)

Things get a little odd when expanding the call stack if duplicates appear. In the following video, you can that when I click the expand icon for thread ID 24 nothing happens for the entry I've expanded, but one of its duplicates elsewhere in the UI does expand and collapse:

https://user-images.githubusercontent.com/12584/193827919-98526b33-1afd-4bcd-91c1-bca89f2e3058.mp4

**Comment by entlicher** [comment]
This issue is addressed by https://github.com/oracle/graal/commit/0411993f152099dafa9ea442c39c51185efb8c1a
If some issue persists in this area, please let me know.
