### ISSUE TITLE
Add DAP options to VS Code debugger schema

### ISSUE THREAD

**Issue by nirvdrum** [oracle/graal#5148]
**Feature request**

Please include the following information:

**Is your feature request related to a problem? Please describe.**

Passing DAP options to the VS Code debugger is tedious. VS Code will auto-complete declared options, but since no DAP options are declared, they're not discoverable. Most users probably won't even know there are options. For those that discover [the docs](https://www.graalvm.org/22.2/tools/vscode/graalvm-extension/polyglot-runtime/), they'll see options, but it's not clear how to pass them. They're CLI options that need to be supplied to the runtime, but that seems at odds with the spirit of the launch.json file. The launch.json options should configure the debugger. Configuring the debugger through runtime args is counter-intuitive.

**Describe the solution you'd like.**

I'd like to see new configuration options contributed by the GraalVM Tools for Java extension. I'm indifferent as to whether that's a set of top-level options, like:

* suspend
* waitAttached

Or if there there's a new `dapOptions` key with a set of sub-keys for each configuration option.

**Describe who do you think will benefit the most.**
GraalVM users. Truffle language users.

**Describe alternatives you've considered.**

I've tried to pass arguments to the runtime to control the debugger. I have yet to have this work the way I'd like, but it's unclear if that's due to other debugger issues.

**Comment by entlicher** [comment]
In progress.
I'm proposing to add a configuration like:
```
"debugOptions": {
    "suspend": true/false,
    "sourcePath": e.g.: "/home/user/mylib:${workspaceFolder}/src",
}
```
WaitAttach option should be added implicitly so that the debuggee always waits till the debugger is attached.

**Comment by entlicher** [comment]
We can add
```
"debugOptions": {
    "suspend": true,
}
```
to all predefined launch configurations, to make the user aware of the option and to make it easily customizable.
I'd keep the `suspend: true`, which is also the default for launchers. The user can easily change it immediately, when necessary.
