### ISSUE TITLE
Is there any source code leak in the EXE file compiled by GraalVM?

### ISSUE THREAD

**Issue by chensiweipsp** [oracle/graal#5150]
I didn't find the corresponding JAR file in the temp folder. Does this mean that the EXE file compiled with native-image -jar does not have the problem of source code leakage?

**Comment by wirthi** [comment]
> ... not have the problem of source code leakage?

can you please clarify what exactly you mean by that?

`native-image` generates an executable file that can be used in isolation. You can ship the generated binary (exe) without distributing any source code.

**Comment by chensiweipsp** [comment]
> > ...没有源代码泄漏的问题？
> 
> 你能解释一下你的英文吗？
> 
> `native-image`可以在不分发任何文件的情况下生成一个单独的文件发布文件。

Is the executable file generated by native-image -jar unable to find the corresponding JAR file?

**Comment by fniephaus** [comment]
The generated executable no longer depends on any JAR files so I'm not sure what you are asking. Could you elaborate please?

**Comment by chensiweipsp** [comment]
> The generated executable no longer depends on any JAR files so I'm not sure what you are asking. Could you elaborate please?

The EXE file generated by native-image -jar is essentially dependent on the corresponding JAR package. If the corresponding JAR package EXE file is deleted, it cannot be run, which means that the corresponding JAR file and EXE file need to be released at the same time. , Is there any way to run the corresponding EXE file directly without relying on the JAR package

**Comment by wirthi** [comment]
> The EXE file generated by native-image -jar is essentially dependent on the corresponding JAR package.

That is impossible. All Java code (from JAR file or other sources) needs to be ahead-of-time compiled by native-image. You CANNOT dynamically load Java code at runtime.

**Comment by chensiweipsp** [comment]
> That is impossible. All Java code (from JAR file or other sources) needs to be ahead-of-time compiled by native-image. You CANNOT dynamically load Java code at runtime.

What is the reason that my EXE file must have the corresponding JAR package to run, if the corresponding JAR file is deleted or moved, the EXE file will not run.

**Comment by fniephaus** [comment]
What error do you see when "the EXE file will not run"? Can you share a reproducer?

**Comment by chensiweipsp** [comment]
https://user-images.githubusercontent.com/28744724/194012729-9c552797-78cd-4c0f-a04f-4f093d34d4a2.mp4

**Comment by chensiweipsp** [comment]
https://user-images.githubusercontent.com/28744724/194017737-d0370340-791f-4519-a9f2-d47c352ca9fb.mp4

I use MAVEN to compile the generated JAR

**Comment by vjovanov** [comment]
Did you put the `--no-fallback` flag to the command line?

**Comment by wirthi** [comment]
Closing this ticket, I don't see anything concrete enough that we can follow up on. If you can share a reproducer we can use on our machine, feel free to reopen this ticket.
