### ISSUE TITLE
How GraalVM generates the corresponding EXE file with administrator privileges？

### ISSUE THREAD

**Issue by chensiweipsp** [oracle/graal#5151]
How to use GraalVM to specify administrator privileges to run in the use of packaged EXE files?

**Comment by oubidar-Abderrahim** [comment]
Hi, Thank you for reaching out, could you please explain more about your inquiry? What is the actual behavior of GraalVM? and what is the expected behavior you're getting? What GraalVM version was used? which platform? architecture?

**Comment by oubidar-Abderrahim** [comment]
Any updates?

**Comment by oubidar-Abderrahim** [comment]
This issue will be closed for inactivity. If you still need assistance, please reopen the issue and share the requested details
