### ISSUE TITLE
[GR-41578] When the EXE compiled with native-image -jar runs, there will be a console. How can I prevent the console process from coming out?

### ISSUE THREAD

**Issue by chensiweipsp** [oracle/graal#5158]
![{L0URF)Z2S`OJ$E%) ZGA2](https://user-images.githubusercontent.com/28744724/193985980-47065b82-afdb-4114-9579-5323e849b1a5.png)
I'm developing a GUI program I don't need a console process

**Comment by fniephaus** [comment]
I don't think hiding the console is currently supported but I've filed an internal feature request for doing that when headless is false. I'm not a Windows expert but there should be some property that can be set on the binary to avoid it opening a console.

**Comment by chensiweipsp** [comment]
> 我认为当前不支持隐藏控制台，但我已经提交了一个内部功能请求，以便在 headless 为 false 时执行此操作。我不是 Windows 专家，但应该可以在二进制文件上设置一些属性以避免它打开控制台。
ok thanks problem solved

**Comment by kristofdho** [comment]
For reference, asked and answered in https://github.com/oracle/graal/discussions/3599.

**Comment by fniephaus** [comment]
Thanks, @kristofdho. I couldn't find those tickets for some reason.
