### ISSUE TITLE
Strings and Symbols render oddly in VS Code debugger

### ISSUE THREAD

**Issue by nirvdrum** [oracle/graal#5163]
I haven't used other Ruby debuggers with VS Code, so I don't know if this is normal, but the GraalVM Tools for Java debugger double-quotes strings:

![image](https://user-images.githubusercontent.com/12584/193891609-efc97690-277c-4f8d-9bb2-4e108f4d2ff3.png)

I've not seen that with other languages on VS Code and not in RubyMine with Ruby. Additionally, I don't think the symbol needs to be quoted.

**Comment by entlicher** [comment]
Fixed by https://github.com/oracle/graal/commit/287cfad79334d06d15c07dd4885f615d2279a6cd
