### ISSUE TITLE
GR-41391 Seems to have unintended consequences, causing performance regression in bytecode interpreters

### ISSUE THREAD

**Issue by smarr** [oracle/graal#5167]
When updating Graal in TruffleSOM, I noticed a performance regression, which after bisecting through the history, seems to be attributable to https://github.com/oracle/graal/commit/df01599e76e747cee3b3115917f87df0b23e78cf

The TruffleSOM bytecode interpreter is affect as can be seen for instance here: https://rebench.dev/TruffleSOM/compare/34afd647d957283c8d2ee37081f554a838576e50..ae9ed42b1792cf956d2afe4a9a73381a926b4b06#macro-startup-TruffleSOM-native-interp-bc

To reproduce, the following instructions will checkout TruffleSOM with Graal at the merge of GR-41391:

```
git clone -b slow/with-phi-cycle-change --recursive https://github.com/smarr/TruffleSOM
cd TruffleSOM
```

To inspect the native image compilation, you can do:

```
ant native-bc -Dno.jit=true -Ddump.method=BytecodeLoopNode.executeGeneric -Ddump.cfg=true -Ddbg=true

# -Dno.jit=true  -> disables JIT compilation in the native image
# -Ddbg=true     -> waits for a debugger to connect
# -Ddump.method=BytecodeLoopNode.executeGeneric -Ddump.cfg=true -> dumps the bytecode loop's method to a file (you may want to add `:2` in build.xml
```

For running an affected benchmark, for instance Mandelbrot, run the following after the `native-bc` compilation completed:

```
./som-native-interp-bc -cp Smalltalk:Examples/Benchmarks/LanguageFeatures:Examples/Benchmarks/TestSuite Examples/Benchmarks/BenchmarkHarness.som --gc Mandelbrot 1 50
```

@davleopo this is the requested issue.

**Comment by davleopo** [comment]
@smarr thanks, Ill have a look.

**Comment by davleopo** [comment]
Tracked internally with GR-41605.

So far I had no luck reproducing a noticeable difference neither in performance nor generated code differences. Ill bisect a bit more...

**Comment by davleopo** [comment]
I bisected through a larger range here and cannot reproduce any perf differences for mandelbrot.
Can you check your benchmark setup again, maybe we are missing any flags/jdk versions that are different on your benchmarking ci?

**Comment by smarr** [comment]
I fear I may have sent you on a ghost chase. Not sure what's going on. It doesn't reproduce any longer. Though, it also can't just be a simple machine fluke since the results with slow downs came from two different machines. Odd. 😩
