### ISSUE TITLE
native-image: UnsupportedFeatureError: ObjectInputStream.readObject()

### ISSUE THREAD

**Issue by nanodeath** [oracle/graal#519]
Trying to run RC3's native-image but I get the above error at runtime. Any suggestions? Or perhaps some way I could get a stacktrace?

**Comment by cstancu** [comment]
@nanodeath we don't currently support object serialization. See also: https://github.com/oracle/graal/issues/460. 

> perhaps some way I could get a stacktrace?

You don't get a stack trace leading to the unimplemented method?

**Comment by nanodeath** [comment]
Damn, not sure how I missed that. We can resolve this in favor of #460 if you like.

Re: stacktrace, that's probably just the program I'm running catching and printing just `Exception#message` I bet, so we can disregard that part.

**Comment by cstancu** [comment]
I'll close this. You can track the progress/discussion on #460.
