### ISSUE TITLE
A script to build graalvm-ce-1.0.0-rc3-linux-amd64.tar.gz ?

### ISSUE THREAD

**Issue by volth** [oracle/graal#520]
Could you publish the script which builds tarballs with all Graal/Truffle components ?

I mean the files ```graalvm-ce-1.0.0-rc2-linux-amd64.tar.gz```,  ```graalvm-ce-1.0.0-rc3-linux-amd64.tar.gz```, ...

It would be useful for including Graal into Linux distros (especially to those which need to patch the sources before the comping of the package, e.g. NixOS)

**Comment by thomaswue** [comment]
The build process is quite complicated, but we are working on such a script.

**Comment by ansalond** [comment]
Hello @volth, sorry for the long delay. Please check the GraalVM build instructions in the [README](https://github.com/oracle/graal/blob/master/vm/README.md) of the `graal/vm` suite, which we recently updated.
Here is how to build the base image of GraalVM CE 1.0.0-rc5:
- set the `JAVA_HOME` environment variable to point to the latest [JVMCI-enabled JDK8](https://github.com/graalvm/openjdk8-jvmci-builder/releases)
- if you haven't done it yet:
  - create a new directory
  - clone the [Graal](https://github.com/oracle/graal) and the [mx](https://github.com/graalvm/mx) repositories inside of it
  - add the root dir of the `mx` repository to your `PATH`
- `cd graal/vm`
- `git checkout vm-1.0.0-rc5`
- if you already checked out the `graaljs` or the `sulong` repositories: `mx --env ce sforceimports`, else skip this step
- `mx --env ce build`

Please let us know if you have problems.
