### ISSUE TITLE
An official docker contiainer optimized for CI

### ISSUE THREAD

**Issue by KOLANICH** [oracle/graal#521]

**Comment by shelajev** [comment]
We're working on providing the official docker containers. What do you mean optimized for CI, what would you like to see there or what are the best practices for that?

**Comment by KOLANICH** [comment]
Under `optimized for CI` I mean mostly small size. You know, CIs (at least GitLab one) redownload containers from dockerhub on every launch. So if a container is huge it will consume lot of bandwidth and time.

**Comment by spavlusieva** [comment]
hi @KOLANICH , this issue has been inactive for more than 180 days. We’ll close it to focus on current issues. In case it’s still relevant, please reopen it and we’ll take another look. Thank you!
