### ISSUE TITLE
Support of IBM AIX / PowerPC architecture

### ISSUE THREAD

**Issue by bigredstar** [oracle/graal#5238]
Our product is a java based application supported on AIX, RHEL and Windows. We would like to use Graal VM on those 3 platforms and, in particular, the AOT compiler to build native image for our set of command line tools.

Currently Intel based architecture is supported. Is there a plan to support IBM AIX / PowerPC architecture?

**Comment by oubidar-Abderrahim** [comment]
Hi, thank you for reaching out to the GraalVM team. Currently, we do not have plans to support PowerPC architecture.
