### ISSUE TITLE
GraalVM 22.2 native image cannot execute VirtualMachine.attach()

### ISSUE THREAD

**Issue by Reason94** [oracle/graal#5239]
**Describe the issue**
Package compiled with Graalvm22.2, stuck when executing VirtualMachine.attach(method is stuck, cannot return)

**Steps to reproduce the issue**
code:
```java
vmObj = VirtualMachine.attach(String.valueOf(pid));
LOGGER.info("attached agent to pid: {}", pid);
vmObj.loadAgent(ProbeRuntimeEnv.agentJar(), generateParam4Agent());
```

**Describe GraalVM and your environment:**
 - GraalVM version : 22.2
 - JDK major version: jdk11
 - OS:  CentOS7u6
 - Architecture: x86

**Comment by oubidar-Abderrahim** [comment]
Hi, thank you for reporting this, could you please share a complete reproducer to use for debugging? also, did you verify the issue using the latest snapshot build of 22.3-dev?

**Comment by oubidar-Abderrahim** [comment]
Hi, Any update on this?
