### ISSUE TITLE
Message about TypeError does not include the types

### ISSUE THREAD

**Issue by daiconrad** [oracle/graal#525]
Calling C compiled to llvm bitcode from Javascript produces a rather unhelpful error message when the types don't match. Consider jspart.js, noting the commented-out code that would convert strings to numbers:

```javascript
// jspart.js
"use strict";

// Load and parse the LLVM bitcode into GraalVM
let cpart = Polyglot.evalFile("llvm" ,"cpart.bc");

// Call the C code with the JS arguments
process.argv/*.filter(s => s.match(/\d+/)).map(s => parseInt(s, 10))*/
    .forEach(q => console.log(`${q} queens:`, cpart.queens(q)));
```

calling into the following C code:

```c
// cpart.c

int queens(int n) {
    return n*n; // simplified for demonstration; full file attached
}
```

If you compile cpart.c with clang and run jspart.js under node, you get:

> dconrad@Blofeld 18.04 ~/src/graal
> $ clang -O1 -emit-llvm -c cpart.c
> dconrad@Blofeld 18.04 ~/src/graal
> $ node --polyglot jspart.js 8 9 10 11 12
> unknown:0
> unknown
> ^
> 
> TypeError: INVOKE on foreign object failed due to: UnsupportedTypeException

The problem is we're passing a javascript `string` to a C `int`, but the error message gives no indication of that. (Note: the error message is unchanged if cpart.queens takes and returns `double` instead of `int`.)

If we uncomment the code that filters and maps the strings to numbers (and replace cpart.c with the full n-queens solver, attached), we get:

> dconrad@Blofeld 18.04 ~/src/graal
> $ node --polyglot jspart.js 8 9 10 11 12
> 8 queens: 92
> 9 queens: 352
> 10 queens: 724
> 11 queens: 2680
> 12 queens: 14200

I am running graalvm-ee under WSL on Windows 10, Ubuntu 18.04, java build 1.8.0_171-b11,
GraalVM 1.0.0-rc2 (build 25.71-b01-internal-jvmci-0.43, mixed mode)

cpart.c was compiled with clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
Target: x86_64-pc-linux-gnu

[cpart.c.gz](https://github.com/oracle/graal/files/2170223/cpart.c.gz)

**Comment by woess** [comment]
Thanks for reporting! Error messages have been improved since, so I believe this issue can be closed. Let us know if you still get unhelpful error messages in current releases.
