### ISSUE TITLE
GraalVM(jdk11) throws "OutOfMemoryError" incorrectly when program contains a "try-catch" statement

### ISSUE THREAD

**Issue by ayuan0828** [oracle/graal#5269]
**Description**:

When running the following test case, the program go to the catch statement to capture "OutOfMemoryError". The expected result should be no error reported, just as hotspot did, but GraalVM(jdk11) still throws "OutOfMemoryError".

**Environment**：

```
Ubuntu 18.04 x86_64
```

**Testcase**:

```public class Test {
import java.util.*;
public class Test {
    void generateOOME() throws Exception {
        List<Object> leak = new LinkedList<>();
        try {
            while (true) {
                leak.add(new byte[1024 + 1024]);
            }
        } catch (OutOfMemoryError e) {
        }
    }
    public static void main(String[] args) throws Exception {
        new Test().generateOOME();
    }
}
```

**Output of HotSpot**:

```

```

**Output of GraalVM(jdk11)**:

```
Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "Libgraal MBean Registration"
java.lang.OutOfMemoryError: Java heap space
```

**Comment by oubidar-Abderrahim** [comment]
Hi, Thank you for reporting this, could you please share the GraalVM version and OpenJDK version you used for testing? Thank you

**Comment by ayuan0828** [comment]
Their versions are as follows.

GraalVM jdk11:

```openjdk version "1.8.0_332-internal"
openjdk 11.0.14 2022-01-18
OpenJDK Runtime Environment GraalVM CE 22.0.0.2 (build 11.0.14+9-jvmci-22.0-b05)
OpenJDK 64-Bit Server VM GraalVM CE 22.0.0.2 (build 11.0.14+9-jvmci-22.0-b05, mixed mode, sharing)
```



OpenJDK jdk11:

```openjdk version "11.0.15-internal" 2022-04-19
openjdk version "11.0.14-internal" 2022-01-18
OpenJDK Runtime Environment (build 11.0.14-internal+0-adhoc..jdk-11.0.14-ga)
OpenJDK 64-Bit Server VM (build 11.0.14-internal+0-adhoc..jdk-11.0.14-ga, mixed mode)
```

**Comment by oubidar-Abderrahim** [comment]
Both your GraalVM and OpenJDK versions are old, I tested with our latest release 22.3.0, and could not reproduce the issue. please try 22.3.0 and let us know if it fixes the problem for you.

**Comment by ayuan0828** [comment]
I have installed the latest version. This problem has indeed been fixed. Thank you.
