### ISSUE TITLE
[22.3]: Backport Request: libmanagement_ext.a unconditionally being added when libawt_headless.a is linked in

### ISSUE THREAD

**Issue by jerboaa** [oracle/graal#5273]
The fix of https://github.com/oracle/graal/issues/5119 didn't end up in the 22.3 release tree. We'd like to backport this fix to 22.3.1 if possible.

The change applies cleanly to the 22.3 tree, we've backported it to our mandrel/22.3 branch already. I'd be happy to create a PR targetting the release branch for this.

/cc @gilles-duboscq @ezzarghili as per https://github.com/oracle/graal/discussions/4332#discussioncomment-2361015

**Comment by jerboaa** [comment]
This should be a low risk change.

**Comment by oubidar-Abderrahim** [comment]
Hi @jerboaa, Thank you for reporting this, please create the PR and link it to this issue, we'll take a look into it shortly

**Comment by jerboaa** [comment]
@oubidar-Abderrahim @zakkak created the PR in #5332. Thanks for taking a look!

**Comment by zakkak** [comment]
#5332 is now merged.
