### ISSUE TITLE
[22.3] Backport Request: c++ compatible mangling support to 22.3

### ISSUE THREAD

**Issue by jerboaa** [oracle/graal#5274]
We'd like to backport the improved, perf compatible debuginfo support from 23.x to 22.3 release branch. The current 22.3 branch has issues such as https://github.com/oracle/graal/issues/5064 and would therefore like this backported to **22.3.1**. We've done so in the upcoming [mandrel 22.3.0 release](https://github.com/graalvm/mandrel/pull/445), and would like to get this synced upstream.

It mostly affects debuginfo generation and should therefore be fairly low risk. What's more it fixes a couple of issues with the current debuginfo generation code included in 22.3.

If OK, I can post a backport PR.

/cc @gilles-duboscq @ezzarghili as per https://github.com/oracle/graal/discussions/4332#discussioncomment-2361015

**Comment by oubidar-Abderrahim** [comment]
Hi @jerboaa, Thank you for reporting this, please create the PR and link it to this issue, we'll take a look into it shortly

**Comment by jerboaa** [comment]
@oubidar-Abderrahim @zakkak has created the PR in #5333. I don't have permissions to link the PR here.

**Comment by zakkak** [comment]
#5333 is now merged.
