### ISSUE TITLE
GraalVM 1.0RC3 unable to run native-image

### ISSUE THREAD

**Issue by flatmap13** [oracle/graal#528]
I recently switched from `1.0RC1` to `1.0RC3` and now I'm getting the following error when running `native-image`.

```
$ native-image --help
Error: Unable to use jar-files from directory /Library/Java/JavaVirtualMachines/graalvm-ee-1.0.0-rc3/Contents/Home/lib/svm/builder
Caused by: java.nio.file.NoSuchFileException: /Library/Java/JavaVirtualMachines/graalvm-ee-1.0.0-rc3/Contents/Home/lib/svm/builder
```

I'm getting the same message when I try to compile a jar file to a binary.
This is on OS X (10.12.6) using Graal EE version. I've also tried with RC2 where I get the same error message when running `native-image`. RC1 seems to work fine though. It does appear that the `svm` folder is missing in the `lib` directory but as I understand it, that folder isn't supposed to be present there anyway. I already tried downloading a new copy, with the same result. Did anyone encounter this issue as well or am I missing something?

**Comment by tednaleid** [comment]
I think I saw this same issue yesterday when I was getting things set up.  I think that setting my `JAVA_HOME` to the ...`Content/Home` directory fixed it.

```
echo $JAVA_HOME
/usr/local/graalvm/Contents/Home
```

```
java -version
java version "1.8.0_172"
Java(TM) SE Runtime Environment (build 1.8.0_172-b11)
GraalVM 1.0.0-rc3 (build 25.71-b01-internal-jvmci-0.45, mixed mode)
```

```
native-image --version
SubstrateVM Version Info
dev
GraalVM Version 1.0.0-rc3
```

I also do not have an `svm` directory inside `lib`:

```
ls $JAVA_HOME/lib
ant-javafx.jar ir.idl         missioncontrol sa-jdi.jar     visualvm
ct.sym         javafx-mx.jar  orb.idl        tools.jar
dt.jar         jconsole.jar   packager.jar   visualizer
```
