### ISSUE TITLE
`toString()` returns `0` when invoked on records with `null` boxed types, while it should return `null`

### ISSUE THREAD

**Issue by zakkak** [oracle/graal#5289]
**Describe the issue**
`toString()` returns `0` when invoked on `null` boxed types, while it should return `null`.

**Steps to reproduce the issue**
1. Create the reproducer:
```
cat <<EOF > Records.java
public class Records {
    record IntegerRecord(Integer x) {}
    record DoubleRecord(Double x) {}

    public static void main(String[] args) {
        System.out.println(new IntegerRecord(null).x());
        System.out.println(new IntegerRecord(null).toString());
        System.out.println(new DoubleRecord(null).x());
        System.out.println(new DoubleRecord(null).toString());
    }
}
EOF
```
2. Compile it: `javac Records.java`
3. Build a native image from the result: `native-image Records`
4. Compare JVM output to native:
```
java Records
./records
```

JVM prints:
```
null
IntegerRecord[x=null]
null
DoubleRecord[x=null]
```

Native prints:
```
null
IntegerRecord[x=0]
null
DoubleRecord[x=0.0]
```

**Describe GraalVM and your environment:**
 - GraalVM version: **[GraalVM CE 23.0.0-dev-20221021_2024](https://github.com/graalvm/graalvm-ce-dev-builds/releases/tag/23.0.0-dev-20221021_2024) / https://github.com/oracle/graal/commit/ed4735275f245aa8a4fa530f0b4819b42e0b388c**
 - JDK major version: **17**
 - OS: **Fedora 36**
 - Architecture: **AMD64**

**Comment by oubidar-Abderrahim** [comment]
Hi, Thank you for reporting this issue. we will take a look into it shortly.

**Comment by oubidar-Abderrahim** [comment]
Tracked internally on GR 42136

**Comment by teshull** [comment]
This will be fixed by https://github.com/oracle/graal/pull/5458

**Comment by zakkak** [comment]
Fixed by https://github.com/oracle/graal/pull/5458
