### ISSUE TITLE
[native-image] confusing error message when output file name matches existing directory

### ISSUE THREAD

**Issue by tednaleid** [oracle/graal#530]
I've got a demo repo that shows this issue with graal `1.0.0-rc3` on OSX: https://github.com/tednaleid/graal-issue  Just check that out and run `https://github.com/tednaleid/graal-issue/blob/master/show-issue.sh`

If I run the following command to try to compile a jar in a subdirectory that has the same name as the jar's base name:

    native-image -jar graal-issue-core/build/libs/graal-issue-core.jar

it fails with a confusing error message that says

    fatal error: java.lang.RuntimeException: java.lang.RuntimeException: host C compiler or linker does not seem to work: java.lang.RuntimeException: returned 1

Buried in a bunch of other stack traces, it eventually says:

    ld: can't open output file for writing: /private/tmp/graal-issue/graal-issue-core, errno=21 for architecture x86_64

Which took me far longer to realize than it should have that it was because it was trying to generate a file with the same path as an existing subdirectory in my current directory.

As far as I can tell, there isn't an option in `native-image` to output the file to a different name.  I think there should be clearer upfront detection that the path it is trying to write the binary to isn't valid.   

my environment:
```
java -version
java version "1.8.0_172"
Java(TM) SE Runtime Environment (build 1.8.0_172-b11)
GraalVM 1.0.0-rc3 (build 25.71-b01-internal-jvmci-0.45, mixed mode)
```

```
sw_vers
ProductName:	Mac OS X
ProductVersion:	10.13.5
BuildVersion:	17F77
```

**Comment by tednaleid** [comment]
Just discovered that you can customize the output file name with `-H:Name=my-native-app`

**Comment by olpaw** [comment]
@tednaleid I agree. I will make this error message more reasonable.

**Comment by olpaw** [comment]
Fixed in https://github.com/oracle/graal/commit/473c771a809793f970116f0e05b1e6001d571fe5
