### ISSUE TITLE
[22.3.0] Creating of 1_000_000 virtual (Loom) threads takes 7 minutes

### ISSUE THREAD

**Issue by Hixon10** [oracle/graal#5320]
**Describe the issue**
I started playing with `22.3.0` GraalVM release, which [supports](https://www.graalvm.org/release-notes/22_3/) Loom virtual treads. I've created a demo app, which creates `1_000_000` threads, where each thread just sleeps for `10 second`:
```java
import java.time.Duration;
import java.time.Instant;
import java.util.List;
import java.util.stream.IntStream;

public class Main {

    public static void main(String[] args) throws InterruptedException {
        List<Thread> threads = IntStream.range(0, 1_000_000)
                .mapToObj(value -> Thread.ofVirtual().unstarted(() ->
                {
                    try {
                        Thread.sleep(10_000);
                    } catch (Exception e) {
                        e.printStackTrace();
                    }
                }))
                .toList();

        Instant begin = Instant.now();
        for (Thread thread : threads) {
            thread.start();
        }

        for (Thread thread : threads) {
            thread.join();
        }
        Instant end = Instant.now();
        System.out.println("Created threads: " + threads.size() + ", Time (ms) = " + Duration.between(begin, end).toMillis());
    }
}
```

When I run this program in `JIT` mode, it works for about `7 minutes`, and all cores are pretty busy (up to 100%). It is interesting, that `native images` works fine, and the program finishes in about `20 seconds`. 

**Steps to reproduce the issue**
Please include both build steps as well as run steps
1. Create `Main.java` with a program, which I've posted before
2. `javac --enable-preview --release 19 Main.java`
3. `time java --enable-preview Main`
4. Output is:
```
$ time java --enable-preview Main
Created threads: 1000000, Time (ms) = 453168

real    7m33.581s
user    58m3.522s
sys     0m43.312s
```

**Describe GraalVM and your environment:**
 - GraalVM version (latest snapshot builds can be found [here](https://github.com/graalvm/graalvm-ce-dev-builds/releases)), or commit id if built from source: **VM GraalVM CE 22.3.0**
 - JDK major version: **19**
 - OS: **Ubuntu 18.04 (Windows WSL 2)**
 - Architecture: **AMD64**

**More details**
1. If I run the same program in `native` mode, everything is fine:
```
$ native-image --enable-preview Main
...
Produced artifacts:
/Java19-Graal/src/main (executable)
/Java19-Graal/src/main.build_artifacts.txt (txt)
=====================================================================================================================
Finished generating 'main' in 54.0s.

$ time ./main
Created threads: 1000000, Time (ms) = 19201

real    0m21.450s
user    0m21.646s
sys     0m19.594s
```

2. If I use another distribution of OpenJDK 19 (e.g., `Liberica JDK`), everything is fine:
```
$ java -version
openjdk version "19.0.1" 2022-10-18
OpenJDK Runtime Environment (build 19.0.1+11)
OpenJDK 64-Bit Server VM (build 19.0.1+11, mixed mode, sharing)

$ time java --enable-preview Main
Created threads: 1000000, Time (ms) = 21486

real 0m21.887s
user 1m1.261s
sys  0m26.510s
```

**Comment by oubidar-Abderrahim** [comment]
Hi, Thank you for reporting this, we'll take a look into it shortly.
