### ISSUE TITLE
GraalVM 22.3.0 Linux 64 / Apple M1 shared library JNI invocation failure with byte[] param

### ISSUE THREAD

**Issue by Hellblazer** [oracle/graal#5321]
**Describe the issue**
When passing a **byte[]** parameter to a JNI native method implemented by a GraalVM isolate, the passed parameter is always length **1**

**Steps to reproduce the issue**
Please include both build steps as well as run steps
1. **git clone --depth 1 https://github.com/Hellblazer/graalvm-mac-jni-issue**
2. **mvn clean install**

**Describe GraalVM and your environment:**
 - GraalVM version **CE 22.3.0**
 - JDK major version: **19**
 - OS: **macOS Ventura** and **Linux**
 - Architecture: **arm64** and **linux64**

**More details**
When passing in a **byte[]** parameter to a JNI invocation of a GraalVM native image implementation, the length of the parameter is always **1**

Not sure what's up.  This is the minimal version I could make that demonstrates the issue.  Tried any number of things, but the **byte[]** parameter is always length **1**

Have not tried this on any other OS/platform

** Repository that demonstrates the bug **
The **[repository](https://github.com/Hellblazer/graalvm-mac-jni-issue)** is a multi-module maven build, requiring GraalVM CE 22.3.0 as the java invocation version.  The **[impl](https://github.com/Hellblazer/graalvm-mac-jni-issue/tree/main/impl)** module is the native JNI implementation and calling code as well as creating and packaging the created GraalVM isolate shared library.  The **[f-test](https://github.com/Hellblazer/graalvm-mac-jni-issue/tree/main/f-test)** module is the testing of the created native library using the **[TestMe JUnit Test](https://github.com/Hellblazer/graalvm-mac-jni-issue/blob/main/f-test/src/test/java/com/hellblazer/issue/TestMe.java#L25)**

**Comment by Hellblazer** [comment]
I added a linux profile for the testing and it fails in a completely different way.  Instead of a length of **1**, with the same test I get a length of **32526** instead of the expected length of **3**

So, this seems to be an issue for at least 2 platforms.  Is there something I'm doing wrong here?

`AssertionFailedError: expected: <3> but was: <32526>`

**Comment by oubidar-Abderrahim** [comment]
Hi, Thank you for reporting this issue, we will take a look into it shortly

**Comment by oubidar-Abderrahim** [comment]
Tracked internally on GR 42304

**Comment by Hellblazer** [comment]
If someone can point me in the general direction of the code involved, I'd love to take a look see.  I don't think I could really contribute, but I am interested in the internals here and would love to see what I can get debugged locally in my own env.

**Comment by christianwimmer** [comment]
The code
```
    @CEntryPoint(name = "Java_com_hellblazer_issue_Native_testMe")
    private static int launch(Pointer jniEnv, Pointer clazz, @CEntryPoint.IsolateThreadContext long isolateId,
                              byte[] byteArray, char[] charArray) throws GeneralSecurityException, IOException {
```
cannot work. A method annotated with `@CEntryPoint` can only have primitive parameter types, no Java objects are allowed.

Note that the issue title is a bit misleading, since you are not using JNI by the low-level C interface that native image provides.

When using isolates, it is not possible to share Java objects between isolates, including arrays of primitive types. Only C data structures can be passes between isolates.

**Comment by christianwimmer** [comment]
We have a check that the signature of entry points does not contain object types (for reference: https://github.com/oracle/graal/blob/6ce58a6238d7e4cea4a0f034856bf5820f484d64/substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/code/CEntryPointCallStubMethod.java#L342) but unfortunately that check got disabled by recent refactorings. Sorry about that! I'm working on a fix to bring back that check, which will make image build of your application fail with an error:
```
Error: Entry point method parameter types are restricted to primitive types, word types and enumerations (@CEnum): com.hellblazer.issue.NativeImpl.launch(Pointer, Pointer, long, byte[], char[])
```

**Comment by christianwimmer** [comment]
The missing error is fixed as part of https://github.com/oracle/graal/pull/5587
