### ISSUE TITLE
How to load resources?

### ISSUE THREAD

**Issue by jazdw** [oracle/graal#534]
I'm getting a NullPointerException running a native image on a line that calls `Xxx.class.getClassLoader(xxx).getResourceAsStream()`.

I've tried every `-H:IncludeResources` value I can think of, this is what I believe should work `-H:IncludeResources='.*\.properties$'` to load properties files, but it doesn't.

Version is graalvm-ce-1.0.0-rc3

**Comment by olpaw** [comment]
Hmm, there is nothing wrong with your regex.
Can you provide a small sample that demonstrates what works on JVM but not as image?

**Comment by jazdw** [comment]
Ah great, that explains it. I had no idea that `.getClassLoader()` [could return null](https://docs.oracle.com/javase/8/docs/api/java/lang/Class.html#getClassLoader--). Thanks.

**Comment by n0mer** [comment]
@cstancu @jazdw so is it possible to load resources in native image ?

**Comment by cstancu** [comment]
@n0mer see https://github.com/oracle/graal/blob/master/substratevm/RESOURCES.md

**Comment by agilob** [comment]
The link is now https://github.com/oracle/graal/blob/master/substratevm/Resources.md
