### ISSUE TITLE
Allow to detect if Substrate VM / Graal is used on runtime

### ISSUE THREAD

**Issue by normanmaurer** [oracle/graal#537]
It would be super helpful if we could somehow detect if Substrate VM / Graal is used on runtime to enable / disable stuff by default. For example in netty we have some stuff that fallbacks to use finalizer for somethings if the user does not use our own `Thread` sub-class. While using this "feature" improves performance its not a required thing to use netty, so if Substrate VM / Graal is used we would like to disable it by default as it will never run finalisers.

For example setting java.vm.name would be good enough for us to detect it in a static init block and set defaults correctly.

**Comment by olpaw** [comment]
@normanmaurer I'm currently working on sucha an API.

**Comment by olpaw** [comment]
We added an API that should fit your needs:
https://github.com/oracle/graal/commit/8c07a0f22418b98a5c3c6de7c38d7bec7fbe91b5
