### ISSUE TITLE
Improve clarity around using resources

### ISSUE THREAD

**Issue by ghost** [oracle/graal#5373]
**Describe the issue**
The [resource documentation](https://github.com/oracle/graal/blob/master/docs/reference-manual/native-image/Resources.md) provides examples that don't reflect the Maven [Standard Directory Layout](https://maven.apache.org/guides/introduction/introduction-to-the-standard-directory-layout.html), defined as follows:

``` 
src/main/resources | Application/Library resources
src/test/resources | Test resources
```

How about using an [example directory structure](https://github.com/oracle/graal/blob/master/docs/reference-manual/native-image/Resources.md#example-usage) that is likely to be employed by the majority of Java projects?

That is, rather than the following, which likely isn't used by many projects:

```
my-app-root
└── src
    ├── main
    │   └── com.my.app
    │       ├── Resource0.txt
    │       └── Resource1.txt
    └── resources
        ├── Resource2.txt
        └── Resource3.txt
```

Consider starting with a super-simple example first that probably covers the majority of usages:

```
app-root
└── src
    └── main
        └── resources
            ├── Resource0.txt
            └── Resource1.txt
```

From there, build on complexity, such as:

```
app-root
└── src
    └── main
        └── resources
            ├── Resource0.txt
            └── Resource1.txt
    └── resources
        ├── Resource2.txt
        └── Resource3.txt
```

Followed by the section for resource bundles.

**Comment by oubidar-Abderrahim** [comment]
Hi, Thank you for your suggestion. We'll take a look into it.

**Comment by olyagpl** [comment]
The suggestion was followed: https://www.graalvm.org/dev/reference-manual/native-image/dynamic-features/Resources/. Thanks for the correction!
