### ISSUE TITLE
[Documentation] Clarify location of native-image-agent

### ISSUE THREAD

**Issue by DaveJarvis** [oracle/graal#5375]
**Describe the issue**
The `native-image` [Agent](https://www.graalvm.org/22.0/reference-manual/native-image/Agent/) documentation shows:

``` bash
$JAVA_HOME/bin/java -agentlib:native-image-agent=config-output-dir=/path/to/config-dir/ ...
```

How can this work without specifying the location (somehow) of the native-image-agent shared object library?

**Replicate**
Steps to replicate the problem (Gluon is used, but I suspect core GraalVM has the same issue):

``` bash
cd /tmp
git clone https://github.com/DaveJarvis/keenwrite
cd keenwrite
wget https://github.com/gluonhq/graal/releases/download/gluon-22.1.0.1-Final/graalvm-svm-java17-linux-gluon-22.1.0.1-Final.tar.gz
tar xf graalvm-svm-java17-linux-gluon-22.1.0.1-Final.tar.gz
rm graalvm*
mv graalvm* graalvm
gradle jar
```

At this point, the file `build/libs/keenwrite.jar` exists. Save the following as `keenwrite.sh` inside the `/tmp/keenwrite` directory:

``` bash
#!/usr/bin/env bash

java \
  -agentlib:native-image-agent=config-output-dir=src/main/resources/META-INF/native-image \
  --add-opens=javafx.controls/javafx.scene.control=ALL-UNNAMED \
  --add-opens=javafx.controls/javafx.scene.control.skin=ALL-UNNAMED \
  --add-opens=javafx.graphics/javafx.scene.text=ALL-UNNAMED \
  --add-opens=javafx.graphics/com.sun.javafx.css=ALL-UNNAMED \
  --add-opens=javafx.graphics/com.sun.javafx.text=ALL-UNNAMED \
  --add-exports=javafx.base/com.sun.javafx.event=ALL-UNNAMED \
  --add-exports=javafx.graphics/com.sun.javafx.application=ALL-UNNAMED \
  --add-exports=javafx.graphics/com.sun.javafx.geom=ALL-UNNAMED \
  --add-exports=javafx.graphics/com.sun.javafx.text=ALL-UNNAMED \
  --add-exports=javafx.graphics/com.sun.javafx.scene=ALL-UNNAMED \
  --add-exports=javafx.graphics/com.sun.javafx.scene.text=ALL-UNNAMED \
  --add-exports=javafx.graphics/com.sun.javafx.scene.traversal=ALL-UNNAMED \
  -jar build/libs/keenwrite.jar $@
```

Make the file executable and then run it.

**Expected results**
I expected this to fail.

**Actual results**
Failed as expected:

``` bash
$ ./keenwrite.sh 
Error occurred during initialization of VM
Could not find agent library native-image-agent on the library path, with error: libnative-image-agent.so: cannot open shared object file: No such file or directory
```

**Additional details**
Consider updating the documentation to instruct the users that (on Linux anyway) the `LD_LIBRARY_PATH` must be updated, such as:

``` bash
export LD_LIBRARY_PATH="$(pwd)/graalvm/lib:$LD_LIBRARY_PATH"
```

**Comment by oubidar-Abderrahim** [comment]
Thank you for reaching out, please verify if this issue occurs on GraalVM CE 22.3.0. Thank you

**Comment by DaveJarvis** [comment]
> Thank you for reaching out, please verify if this issue occurs on GraalVM CE 22.3.0. Thank you

It's a documentation issue. Wouldn't it apply to all versions of GraalVM?

**Comment by rubyFeedback** [comment]
Agreed. I found it better to add something like [Documentation] within the title as-is to the issue tracker (title there); this may help the GraalVM team identify what should be modified as-is.

**Comment by oubidar-Abderrahim** [comment]
@DaveJarvis we do not have the agent's location in our documentation because it is not needed. 
If I install GraalVM and set JAVA_HOME correctly, I can use `$JAVA_HOME/bin/java -agentlib:native-image-agent=config-output-dir=/path/to/config-dir/ ...` and it will work as expected without the need to specify the location of the agent. could you please share how did you get this strange error? and if this is a GraalVM issue or a Gluon issue?

**Comment by DaveJarvis** [comment]
> could you please share how did you get this strange error?

The exact steps needed to replicate the problem are shown. You will have to uninstall your version of GraalVM and make sure that your `LD_LIBRARY_PATH` variable is empty (unset). If you have podman or docker, it may be easier to start with a fresh container then run the commands I've listed above.

**Comment by oubidar-Abderrahim** [comment]
Tracked internally on GR 42779

**Comment by oubidar-Abderrahim** [comment]
@DaveJarvis I tested using a clean Linux docker image with an empty `LD_LIBRARY_PATH`, installed GraalVM CE 22.3.0 and native-image, and was able to run the agent without issues. 

I believe the error you shared `Could not find agent library native-image-agent on the library path, with error: libnative-image-agent.so: cannot open shared object file: No such file or directory` occurs when native-image is not installed. if you install it using `gu`, you should be able to use the agent without setting  `LD_LIBRARY_PATH`.
