### ISSUE TITLE
Push image to docker hub

### ISSUE THREAD

**Issue by zgqq** [oracle/graal#5378]
The ghcr.io download is a little slow, and the docker hub has a lot of mirrors to help speed up the download.

**Comment by oubidar-Abderrahim** [comment]
Thank you for your suggestion. I will check with the release team and get back to you

**Comment by oubidar-Abderrahim** [comment]
Apology for the delayed response. It seems we have no plan to use docker-hub for hosting our images at the moment. the only supported repos are:

- https://container-registry.oracle.com/
- https://github.com/orgs/graalvm/packages
