### ISSUE TITLE
how to use Date.toString() in java?

### ISSUE THREAD

**Issue by kingkong3** [oracle/graal#5427]
I am using graal as a script engine in java.

However, an exception occurs when the following script is executed:

 my javascript : 
  ```
var date = new Date();
  date.toString();
```

exception : 
`org.graalvm.polyglot.PolyglotException: java.lang.NoSuchMethodError: com.ibm.icu.text.TimeZoneNames.getTZDBInstance(Lcom/ibm/icu/util/ULocale;)Lcom/ibm/icu/text/TimeZoneNames;`

I wonder if the Date object toString cannot be used as graal.

**Comment by wirthi** [comment]
Hi,

I have tried your example, it is working fine for me on GraalVM 22.2 on Linux.

My guess is that you are not using a full GraalVM, but instead try to operate on a stock JVM with pulling in JAR files? Maybe you are missing a crucial file, like `icu4j.jar`. https://www.graalvm.org/22.1/reference-manual/js/RunOnJDK/

Can you please specify your setup and everything else that might be relevant to reproduce your example?

```
try (Context context = Context.create()) {
    Value sum = context.eval("js", "var date = new Date(); date.toString();");
    System.out.println(sum.asString());
}
```

prints `Fri Nov 18 2022 10:37:43 GMT+0100 (CET)` 

Christian

**Comment by kingkong3** [comment]
```
Context engine = Context.newBuilder("js").option("engine.WarnInterpreterOnly", "false").allowAllAccess(true).allowHostClassLookup(className -> true).build();

Value objResult = engine.eval("js", "var date = new Date(); date.toString();");
```

Here My Code.

I'm probably inexperienced in using graal, so could you tell me something wrong?

I'm currently using it by typing maven in pom.xml as below.
```
<!-- https://mvnrepository.com/artifact/org.graalvm.js/js -->
<dependency>
      <groupId>org.graalvm.js</groupId>
      <artifactId>js</artifactId>
      <version>22.2.0.1</version>
</dependency>
<!-- https://mvnrepository.com/artifact/org.graalvm.js/js-scriptengine -->
<dependency>
      <groupId>org.graalvm.js</groupId>
      <artifactId>js-scriptengine</artifactId>
      <version>22.2.0.1</version>
</dependency>
```

**Comment by wirthi** [comment]
As mentioned above, you are probably missing `ICU4J` in your setup. We explicitly load that in the example in https://www.graalvm.org/22.3/reference-manual/js/RunOnJDK/#graalvm-javascript-on-jdk-11

But again, this is an unsupported way of using Graal.js. We strongly recommend you run on [GraalVM](https://www.graalvm.org/downloads/), then it should work out of the box.
