### ISSUE TITLE
Outdated README: "The Substrate VM is licensed under the GPL 2."

### ISSUE THREAD

**Issue by fcurts** [oracle/graal#544]
https://github.com/oracle/graal/blob/master/substratevm/README.md says "The Substrate VM is licensed under the GPL 2." and does not mention the classpath exception.

**Comment by olyagpl** [comment]
Thanks for notifying! It has been updated.

**Comment by olyagpl** [comment]
https://github.com/oracle/graal/blob/master/substratevm/README.md
