### ISSUE TITLE
[22.3]: Backport Request: Add support for CgroupMetrics.getTotalMemory0

### ISSUE THREAD

**Issue by jerboaa** [oracle/graal#5495]
#5387 describes the issue. It's present with JDK `17.0.6+1` and later and, thus, would like to get the fix of #5390 backported to 22.3.1 as that'll be JDK 17.0.6 based. Therefore, the fix would be needed there too.

I'd be happy to create a PR targetting the `22.3` release branch for this if OK.

/cc @gilles-duboscq @ezzarghili as per https://github.com/oracle/graal/discussions/4332#discussioncomment-2361015

**Comment by oubidar-Abderrahim** [comment]
Yes, please create the PR and assign it to me. Thank you

**Comment by jerboaa** [comment]
> Yes, please create the PR and assign it to me. Thank you

Thanks. Done in https://github.com/oracle/graal/pull/5525
