### ISSUE TITLE
Unable to use runtime.exec

### ISSUE THREAD

**Issue by TheBlindM** [oracle/graal#5509]
**Describe the issue**
Normal under jvm, abnormal under native
![image](https://user-images.githubusercontent.com/48701152/204128356-e6dc4d08-2d11-4df6-bd59-73af0e5ac271.png)

**Steps to reproduce the issue**
```
Runtime runtime = Runtime.getRuntime();
Process process = runtime.exec("cmd.exe /c start " + savePath“);
```

**Describe GraalVM and your environment:**
 - GraalVM version (latest snapshot builds can be found [here](https://github.com/graalvm/graalvm-ce-dev-builds/releases)), or commit id if built from source: **[e.g. EE 19.3, CE 20.0, CE 20.1.0-dev-20200304_0848]**
openjdk version "19" 2022-09-20
OpenJDK Runtime Environment GraalVM CE 23.0.0-dev (build 19+36-jvmci-23.0-b01)
OpenJDK 64-Bit Server VM GraalVM CE 23.0.0-dev (build 19+36-jvmci-23.0-b01, mixed mode, sharing)

Windows 10 AMD64

**Comment by oubidar-Abderrahim** [comment]
Hi, Thank you for reporting this. Could you please specify if you're using the Tracing agent to collect configs? also, it would be helpful to share a complete reproducer for this.
