### ISSUE TITLE
GraalVM Python interpretor for Windows OS

### ISSUE THREAD

**Issue by rakrishna1** [oracle/graal#5545]
GraalPython interpreter for Windows OS

I am looking for  GraalVM implementation of Python.
Currently Graal-Python is not listed under GraalUpdater for Windows.

c:\GraalVM>gu available
Downloading: Component catalog from www.graalvm.org
ComponentId              Version             Component name                Stability                     Origin
---------------------------------------------------------------------------------------------------------------------------------
js                       22.3.0              Graal.js                      Experimental                  github.com
llvm                     22.3.0              LLVM Runtime Core             Experimental                  github.com
llvm-toolchain           22.3.0              LLVM.org toolchain            Experimental                  github.com
native-image             22.3.0              Native Image                  Experimental                  github.com
nodejs                   22.3.0              Graal.nodejs                  Experimental                  github.com
visualvm                 22.3.0              VisualVM                      Experimental                  github.com
wasm                     22.3.0              GraalWasm                     Experimental                  github.com

**Comment by timfel** [comment]
See also https://github.com/oracle/graalpython/issues/156

**Comment by oubidar-Abderrahim** [comment]
@rakrishna1 please follow the discussion at https://github.com/oracle/graalpython/issues/156 for Python's support on Windows. Thank you
