### ISSUE TITLE
java.util.MissingResourceException: Can't find bundle for base name com.sun.tools.javac.resources.compiler, locale zh_CN_#Hans

### ISSUE THREAD

**Issue by CrazyHZM** [oracle/graal#5547]
**Describe the issue**
A clear and concise description of the issue. We recommend using the [latest snapshot builds](https://github.com/graalvm/graalvm-ce-dev-builds/releases) to replicate the issue as  bugs are constantly being fixed in the master branch

**Steps to reproduce the issue**
Please include both build steps as well as run steps
1. **[e.g.: git clone --depth 1 https://git.myrepo.com/projectone ]**
2. **[e.g.: mvn clean package]**

**Describe GraalVM and your environment:**
 - GraalVM version (latest snapshot builds can be found [here](https://github.com/graalvm/graalvm-ce-dev-builds/releases)), or commit id if built from source: 
 ```
openjdk version "17.0.5" 2022-10-18
OpenJDK Runtime Environment GraalVM CE 22.3.0 (build 17.0.5+8-jvmci-22.3-b08)
OpenJDK 64-Bit Server VM GraalVM CE 22.3.0 (build 17.0.5+8-jvmci-22.3-b08, mixed mode, sharing)
```
 - JDK major version: openjdk17
 - OS: macos
 - Architecture: AMD64

**More details**
Consider adding the `--native-image-info` and  `--verbose` flags when building your native image and paste output below.

Add any other information about the problem here. Especially important are stack traces or log output. Feel free to link to gists or to screenshots if necessary.
```
   Caused by: java.util.MissingResourceException: Can't find bundle for base name com.sun.tools.javac.resources.compiler, locale zh_CN_#Hans
        at java.base@17.0.5/java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:2045)
        at java.base@17.0.5/java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1683)
        at java.base@17.0.5/java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1575)
        at java.base@17.0.5/java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1549)
        at java.base@17.0.5/java.util.ResourceBundle.getBundle(ResourceBundle.java:932)
        at jdk.compiler@17.0.5/com.sun.tools.javac.util.JavacMessages.lambda$add$0(JavacMessages.java:121)
        at jdk.compiler@17.0.5/com.sun.tools.javac.util.JavacMessages.getBundles(JavacMessages.java:140)
        ... 38 more

```

**Comment by oubidar-Abderrahim** [comment]
Thank you for opening this issue, please provide more details about your issue

- What is the locale you have on your machine?
- What is the command you use to build your native image?

It would be helpful to have a reproducer for this issue if you can provide one.

**Comment by oubidar-Abderrahim** [comment]
Any updates?

**Comment by CrazyHZM** [comment]
Can't reproduce it for now, close this issue first.

**Comment by Jiehong** [comment]
Just hit the issue, but with a different locale:

```
Exception in thread "main" java.lang.InternalError: Cannot find requested resource bundle for locale en_DE
(...)
```

Running jshell to check my locale, I get this:

```
jshell> Locale locale = Locale.getDefault();
   ...> String lang = locale.getDisplayLanguage();
   ...> String country = locale.getDisplayCountry();
locale ==> en_DE
lang ==> "English"
country ==> "Germany"
```

Looking up online, it seems that GraalVM will only build a native image with a single locale: https://www.graalvm.org/22.1/reference-manual/native-image/Resources/#locales

So a partial fix is to use the `-H:+IncludeAllLocales` option in `native-image` command, but it doesn't seem to be helping, and I get the same exception.

I build like so (MacOS M2):

```sh
/Library/Java/JavaVirtualMachines/graalvm-community-openjdk-21+35.1/Contents/Home/bin/native-image --strict-image-heap -H:IncludeResourceBundles=org.openjdk.tools.javac.resources.compiler --initialize-at-build-time=com.sun.tools.javac.file.Locations -H:+IncludeAllLocales -march=native --no-server -jar ./target/*-jar-with-dependencies.jar test
```
