### ISSUE TITLE
Incorrect JavaScript behavior: ECMA-402 Array.prototype.toLocaleString does not always invoke element methods with two arguments

### ISSUE THREAD

**Issue by gibson042** [oracle/graal#5562]
**Describe the issue**
In JavaScript implementations supporting ECMA-402, `Array.prototype.toLocaleString` must invoke the `toLocaleString` method of each non-undefined non-null element with exactly two arguments per https://tc39.es/ecma402/#sup-array.prototype.tolocalestring step 6.c.i. But GraalJS appears to blindly pass all arguments from the outer invocation to the inner ones, resulting in incorrect behavior when the outer invocation is provided with 0, 1, or more than 2 arguments.

**Steps to reproduce the issue**
```sh
$ graaljs --print-result -e '[{ toLocaleString(){ return arguments.length; } }].toLocaleString()'
Result: 0
```
("0" should have been "2")
See also https://github.com/tc39/test262/pull/3741

**Describe GraalVM and your environment:**
 - GraalVM version: **GraalVM JavaScript (GraalVM CE Native 22.2.0)**

**Comment by oubidar-Abderrahim** [comment]
Hi, Thank you for reporting this, we'll take a look into it shortly.

**Comment by iamstolis** [comment]
Fixed by https://github.com/oracle/graaljs/commit/b250d9603b8eab22b9386665f3f9c1514ecf95e5
