### ISSUE TITLE
Incorrect library in community binaries for arm64

### ISSUE THREAD

**Issue by crmauceri** [oracle/graal#5571]
I'm trying to install GraalVM from the [community binaries](https://github.com/graalvm/graalvm-ce-builds/releases). If this isn't the right repo to ask about this, let me know. The binary repo doesn't have an issues page, and [the GrallVM website community page](https://www.graalvm.org/community/) points here. 

I'm on a Mac with a M1 chip, but I'm running Ubuntu 20.04 on Parallels. I've been following [these instructions](https://www.graalvm.org/22.1/docs/getting-started/linux-aarch64/). 

I download and unpack the tar. When I test the java version, I get the following error

```
java --version
/lib64/ld-linux-x86-64.so.2: No such file or directory
```
This is clearly not the arm64 binary. I've tried with two different recent releases

- graalvm-ce-java11-linux-amd64-22.2.0.tar.gz
- graalvm-ce-java11-linux-amd64-22.3.0.tar.gz

Both have the same error.

**Comment by wirthi** [comment]
I believe on an M1 chip you need the `aarch64` binary, not `amd64`.

**Comment by crmauceri** [comment]
You are correct. A silly mistake.
