### ISSUE TITLE
gu 2.0.0 does not work on aarch64 

### ISSUE THREAD

**Issue by takos78** [oracle/graal#5573]
The 'gu' (GraalVM Component Updater v2.0.0) command does not work on aarch64 system. It always just prints the usage info. Cannot list or install packages.

To reproduce: type 'gu list' or 'gu install native-image'.
GraalVM binary version: graalvm-ce-java17-linux-aarch64-22.3.0

Note: The amd64 version works fine (on another, x86 computer).

**Comment by takos78** [comment]
![gulist-prints-usage](https://user-images.githubusercontent.com/10583084/206156517-fbd15cd5-0444-4f32-90cb-69b56ad247a7.png)

**Comment by oubidar-Abderrahim** [comment]
Hi, Thank you for reporting this, we will take a look into it shortly

**Comment by oubidar-Abderrahim** [comment]
I tested this on a Linux aarch64 VM and `gu` list was printing the correct output. Not sure why you're getting this result, could you please redownload and reinstall GraalVM correctly to test again?
Also please share the exact version of the OS you're using

**Comment by takos78** [comment]
I re-downloaded GraalVM from 'https://github.com/graalvm/graalvm-ce-builds/releases/tag/vm-22.3.0'.
Installed it as described here:
https://www.graalvm.org/22.3/docs/getting-started/linux/

But the result is the same - only prints the usage information. The 'java -version' command prints the correct GraalVM version. Also, the installed GraalVM Java is running java apps without any issues. Only the 'gu' command does not work.  

The system is a Synology NAS DSM 6.x. Linux kernel version:  '4.4.59+'. (proc is ARMv8 aarch64 based).

![gu-error-prints-usage-2](https://user-images.githubusercontent.com/10583084/207725243-42270bb2-dbee-46a5-8071-6399f4bc22c1.png)

**Comment by oubidar-Abderrahim** [comment]
Unfortunately, Oracle GraalVM is not supported on DSM Synology.
