### ISSUE TITLE
SVM: Throw MalformedURLException instead of UnsupportedFeatureError for unsupported protocols

### ISSUE THREAD

**Issue by fcurts** [oracle/graal#558]
Would it make sense to throw `java.net.MalformedURLException` instead of `com.oracle.svm.core.jdk.UnsupportedFeatureError` for disabled and unsupported protocols? This seems more in line with the `java.net.URL` constructor's contract, can be handled without depending on an SVM API (which I'm not even sure where to get from), and is less likely to "crash" an app than throwing a `java.lang.Error`.

From the `java.net.URL` Javadoc:

> @exception  MalformedURLException  if no protocol is specified, or an unknown protocol is found, or {@code spec} is {@code null}.

**Comment by olegchir** [comment]
@cstancu, may I investigate this issue?

**Comment by cstancu** [comment]
@olegchir please do!

**Comment by cstancu** [comment]
Fixed by afc34c7250a026b26f6e18ab44700dc899594938.
