### ISSUE TITLE
Need byte-code manipulation support for native-image generation

### ISSUE THREAD

**Issue by Thevakumar-Luheerathan** [oracle/graal#5585]
**Feature request**

Need byte-code manipulation support for native-image generation.

**Is your feature request related to a problem? Please describe.**
I am working on a java based language implementation project where I need to modify method bodies (modifying class byte codes and executing modified version) in runtime based on few conditions. Native image already supports for loading class dynamically and executing methods on those classes. Additional to that having byte code manipulation(through `asm` library) is much useful. specially in the case of JVM based languages.

**Describe the solution you'd like.**

**Describe who do you think will benefit the most.**
GraalVM users, GraalVM contributors, developers of libraries and frameworks which depend on GraalVM, or somebody else?

**Describe alternatives you've considered.**

**Additional context.**
Add any other context about the feature request here.
For example, link to the relevant projects, documentation, standards.

**Express whether you'd like to help contributing this feature**
If you'd like to contribute, please read the [contribution guide](https://www.graalvm.org/community/contributors/).

**Comment by kkriske** [comment]
This is simply not possible. There is no more bytecode at runtime, so there is nothing to modify. Everything is converted to native instructions.
If you want to modify anything at the bytecode level, you have to make sure it happens ahead of time, either during the build or possibly through generated classes again ahaid of time so they are available at build-time.

**Comment by Thevakumar-Luheerathan** [comment]
@kkriske Thank you for the information
