### ISSUE TITLE
Creating a native image will stop at this error: Fatal error: java.lang.NoClassDefFoundError: jakarta/servlet/Filter

### ISSUE THREAD

**Issue by Anganthier** [oracle/graal#5592]
**Describe the issue**
I am getting the error Fatal error: java.lang.NoClassDefFoundError: jakarta/servlet/Filter while compiling a spring boot 3.0.0 generated project using maven and the profile native as described in the graal documentation

**Steps to reproduce the issue**
Please include both build steps as well as run steps
1. git clone https://github.com/Anganthier/graalvmerror_demo
2. ./mvnw -Pnative -DskipTests clean
3. ./mvnw -Pnative -DskipTests package

**Describe GraalVM and your environment:**
 - GraalVM version 22.03.00
 - JDK major version: 17
 - OS: Mint 21
 - Architecture: x86_64

I recreated an empty project on spring.io, added some of the dependencies in the pom file and added a single stripped down file from the project. Creating the package not using the native profile works fine, but it is actually not a native image.

Log file is attached.
[mvnBuildPackage.log](https://github.com/oracle/graal/files/10207384/mvnBuildPackage.log)

**Comment by oubidar-Abderrahim** [comment]
Hi, thank you for reaching out, please make sure to run the tracing agent to collect Metadata config files before building the native-image (https://www.graalvm.org/22.3/reference-manual/native-image/metadata/AutomaticMetadataCollection/). Let us know if that fixes the issue. Thank you.

**Comment by oubidar-Abderrahim** [comment]
Any updates?

**Comment by Anganthier** [comment]
Sorry for the delay. Spring Boot 3 documentation was updated regarding native builds. I was thinking far to complicated since native build are already integrated into Spring Boot 3 by default.
