### ISSUE TITLE
[native-image] Building on newer versions of Java

### ISSUE THREAD

**Issue by ChadKillingsworth** [oracle/graal#561]
Building closure-compiler on MacOS was a bit involved. I first had to upgrade the JVM, then build graal-jvmci-8. When Java 10 support with jvmci is supported by native-image, this would be much less complicated.

Full build steps: https://github.com/ChadKillingsworth/closure-compiler-graal/blob/master/.travis.yml

**Comment by christianwimmer** [comment]
We are actively working on support for Java 11.

**Comment by neomatrix369** [comment]
Great question, can I understand what it means to build **graalvm suite** with the following JDK:
- JDK 9
- JDK 10
- JDK 11
- JDK 12

Currently the binary I build is based ok JDK 8

**Comment by neomatrix369** [comment]
Oops! Looks like GraamVM with JDK8 support and then JDK 11 onwards - I'll try to catch-up with this in the meanwhile

**Comment by wirthi** [comment]
Closing this issue, we are preparing for Java 20 already.
