### ISSUE TITLE
CContext should not be marked as HOSTED_ONLY

### ISSUE THREAD

**Issue by huahaiy** [oracle/graal#5615]
**Describe the issue**
This is to reopen a closed issue.  https://github.com/oracle/graal/issues/4771#issuecomment-1352401106

Upgraded from 21.3.0 to 22.3.0, when compiling to native image, [C API](https://www.graalvm.org/sdk/javadoc/index.html?org/graalvm/nativeimage/c/package-summary.html) seems to be no longer available for working inside the native image. The same Clojure code works fine in 21.3.0, so it is NOT an issue specific to Clojure. The exception is
com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: type is not available in this platform: org.graalvm.nativeimage.c.CContext

Basically, commit https://github.com/oracle/graal/commit/830e38c47da61ea7576b0a2c0254154cc22ff6d4#r93123371 is the reason for the breakage. It annotated `CContext` as `@Platforms(Platform.HOSTED_ONLY.class)`, so `CContext` is not available for native image. This should not be the case, as it blocks an entire class of use cases, where C interops are needed to be done inside native image. Please undo this. Otherwise, many people will have to abandon GraalVM as a platform. 

**Steps to reproduce the issue**
Please include both build steps as well as run steps

git clone -b graalvm22 https://github.com/juji-io/datalevin
cd datalevin/native
script/compile

**Describe GraalVM and your environment:**

GraalVM version: CE 22.3.0
JDK major version: 17
OS: Ubuntu Linux
Architecture: AMD64

**More details**

[2/7] Performing analysis...  [******]                                                                  (43.8s @ 2.69GB)
  14,182 (89.01%) of 15,933 classes reachable
  18,653 (43.71%) of 42,676 fields reachable
  58,038 (51.74%) of 112,180 methods reachable
     276 classes,   436 fields, and 3,389 methods registered for reflection
      63 classes,    62 fields, and    58 methods registered for JNI access
       8 native libraries: dl, dtlv, lmdb, m, pthread, rt, stdc++, z

Error: Unsupported features in 3 methods
Detailed message:
Error: type is not available in this platform: org.graalvm.nativeimage.c.CContext
Trace: Object was reached by
  indexing into array java.lang.Object[]@7bd01684: [Ljava.lang.Object;@7bd01684
  reading field clojure.lang.PersistentHashMap$BitmapIndexedNode.array of constant
    clojure.lang.PersistentHashMap$BitmapIndexedNode@7507a7bd: clojure.lang.PersistentHashMap$BitmapIndexedNode@7507a7bd
  indexing into array clojure.lang.PersistentHashMap$INode[]@373fad71: [Lclojure.lang.PersistentHashMap$INode;@373fad71
  reading field clojure.lang.PersistentHashMap$ArrayNode.array of constant
    clojure.lang.PersistentHashMap$ArrayNode@145a4ba3: clojure.lang.PersistentHashMap$ArrayNode@145a4ba3
  indexing into array clojure.lang.PersistentHashMap$INode[]@2223a5ab: [Lclojure.lang.PersistentHashMap$INode;@2223a5ab
  reading field clojure.lang.PersistentHashMap$ArrayNode.array of constant
    clojure.lang.PersistentHashMap$ArrayNode@5815db: clojure.lang.PersistentHashMap$ArrayNode@5815db
  reading field clojure.lang.PersistentHashMap.root of constant
    clojure.lang.PersistentHashMap@36b497dc: {primitives-classnames #'clojure.core/primitives-classnames, +' #'clojure.core/+...
  reading field java.util.concurrent.atomic.AtomicReference.value of constant
    java.util.concurrent.atomic.AtomicReference@4eba05c0: {primitives-classnames #'clojure.core/primitives-classnames, +' #'clojure.core/+...
  reading field clojure.lang.Namespace.mappings of constant
    clojure.lang.Namespace@46845db8: datalevin.binding.graal
  reading field java.util.concurrent.ConcurrentHashMap$Node.val of constant
    java.util.concurrent.ConcurrentHashMap$Node@11ec7e0c: datalevin.binding.graal=datalevin.binding.graal
  indexing into array java.util.concurrent.ConcurrentHashMap$Node[]@16839cf9: [Ljava.util.concurrent.ConcurrentHashMap$Node;@16839cf9
  reading field java.util.concurrent.ConcurrentHashMap.table of constant
    java.util.concurrent.ConcurrentHashMap@7262053b: {sci.impl.faster=sci.impl.faster, taoensso.nippy.compression=taoensso.nippy.comp...
  scanning root java.util.concurrent.ConcurrentHashMap@7262053b: {sci.impl.faster=sci.impl.faster, taoensso.nippy.compression=taoensso.nippy.comp... embedded in
    clojure.lang.Namespace.find(Namespace.java:188)
Error: type is not available in this platform: org.graalvm.nativeimage.c.CContext
Trace: Object was reached by
  reading field java.lang.Class.declaringClass of constant
    java.lang.Class@2bd3e84e: interface org.graalvm.nativeimage.c.CContext$Directives
  manually triggered rescan
Error: type is not available in this platform: org.graalvm.nativeimage.c.CContext
Trace: Object was reached by
  reading field java.lang.Class.nestHost of constant
    java.lang.Class@2bd3e84e: interface org.graalvm.nativeimage.c.CContext$Directives
  manually triggered rescan

com.oracle.svm.core.util.UserError$UserException: Unsupported features in 3 methods
Detailed message:
Error: type is not available in this platform: org.graalvm.nativeimage.c.CContext
Trace: Object was reached by
  indexing into array java.lang.Object[]@7bd01684: [Ljava.lang.Object;@7bd01684
  reading field clojure.lang.PersistentHashMap$BitmapIndexedNode.array of constant
    clojure.lang.PersistentHashMap$BitmapIndexedNode@7507a7bd: clojure.lang.PersistentHashMap$BitmapIndexedNode@7507a7bd
  indexing into array clojure.lang.PersistentHashMap$INode[]@373fad71: [Lclojure.lang.PersistentHashMap$INode;@373fad71
  reading field clojure.lang.PersistentHashMap$ArrayNode.array of constant
    clojure.lang.PersistentHashMap$ArrayNode@145a4ba3: clojure.lang.PersistentHashMap$ArrayNode@145a4ba3
  indexing into array clojure.lang.PersistentHashMap$INode[]@2223a5ab: [Lclojure.lang.PersistentHashMap$INode;@2223a5ab
  reading field clojure.lang.PersistentHashMap$ArrayNode.array of constant
    clojure.lang.PersistentHashMap$ArrayNode@5815db: clojure.lang.PersistentHashMap$ArrayNode@5815db
  reading field clojure.lang.PersistentHashMap.root of constant
    clojure.lang.PersistentHashMap@36b497dc: {primitives-classnames #'clojure.core/primitives-classnames, +' #'clojure.core/+...
  reading field java.util.concurrent.atomic.AtomicReference.value of constant
    java.util.concurrent.atomic.AtomicReference@4eba05c0: {primitives-classnames #'clojure.core/primitives-classnames, +' #'clojure.core/+...
  reading field clojure.lang.Namespace.mappings of constant
    clojure.lang.Namespace@46845db8: datalevin.binding.graal
  reading field java.util.concurrent.ConcurrentHashMap$Node.val of constant
    java.util.concurrent.ConcurrentHashMap$Node@11ec7e0c: datalevin.binding.graal=datalevin.binding.graal
  indexing into array java.util.concurrent.ConcurrentHashMap$Node[]@16839cf9: [Ljava.util.concurrent.ConcurrentHashMap$Node;@16839cf9
  reading field java.util.concurrent.ConcurrentHashMap.table of constant
    java.util.concurrent.ConcurrentHashMap@7262053b: {sci.impl.faster=sci.impl.faster, taoensso.nippy.compression=taoensso.nippy.comp...
  scanning root java.util.concurrent.ConcurrentHashMap@7262053b: {sci.impl.faster=sci.impl.faster, taoensso.nippy.compression=taoensso.nippy.comp... embedded in
    clojure.lang.Namespace.find(Namespace.java:188)
Error: type is not available in this platform: org.graalvm.nativeimage.c.CContext
Trace: Object was reached by
  reading field java.lang.Class.declaringClass of constant
    java.lang.Class@2bd3e84e: interface org.graalvm.nativeimage.c.CContext$Directives
  manually triggered rescan
Error: type is not available in this platform: org.graalvm.nativeimage.c.CContext
Trace: Object was reached by
  reading field java.lang.Class.nestHost of constant
    java.lang.Class@2bd3e84e: interface org.graalvm.nativeimage.c.CContext$Directives
  manually triggered rescan

	at com.oracle.svm.core.util.UserError.abort(UserError.java:85)
	at com.oracle.svm.hosted.FallbackFeature.reportAsFallback(FallbackFeature.java:248)
	at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:776)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:578)
	at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:535)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:403)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:580)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:128)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner$JDK9Plus.main(NativeImageGeneratorRunner.java:610)
Caused by: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: Unsupported features in 3 methods
Detailed message:
Error: type is not available in this platform: org.graalvm.nativeimage.c.CContext
Trace: Object was reached by
  indexing into array java.lang.Object[]@7bd01684: [Ljava.lang.Object;@7bd01684
  reading field clojure.lang.PersistentHashMap$BitmapIndexedNode.array of constant
    clojure.lang.PersistentHashMap$BitmapIndexedNode@7507a7bd: clojure.lang.PersistentHashMap$BitmapIndexedNode@7507a7bd
  indexing into array clojure.lang.PersistentHashMap$INode[]@373fad71: [Lclojure.lang.PersistentHashMap$INode;@373fad71
  reading field clojure.lang.PersistentHashMap$ArrayNode.array of constant
    clojure.lang.PersistentHashMap$ArrayNode@145a4ba3: clojure.lang.PersistentHashMap$ArrayNode@145a4ba3
  indexing into array clojure.lang.PersistentHashMap$INode[]@2223a5ab: [Lclojure.lang.PersistentHashMap$INode;@2223a5ab
  reading field clojure.lang.PersistentHashMap$ArrayNode.array of constant
    clojure.lang.PersistentHashMap$ArrayNode@5815db: clojure.lang.PersistentHashMap$ArrayNode@5815db
  reading field clojure.lang.PersistentHashMap.root of constant
    clojure.lang.PersistentHashMap@36b497dc: {primitives-classnames #'clojure.core/primitives-classnames, +' #'clojure.core/+...
  reading field java.util.concurrent.atomic.AtomicReference.value of constant
    java.util.concurrent.atomic.AtomicReference@4eba05c0: {primitives-classnames #'clojure.core/primitives-classnames, +' #'clojure.core/+...
  reading field clojure.lang.Namespace.mappings of constant
    clojure.lang.Namespace@46845db8: datalevin.binding.graal
  reading field java.util.concurrent.ConcurrentHashMap$Node.val of constant
    java.util.concurrent.ConcurrentHashMap$Node@11ec7e0c: datalevin.binding.graal=datalevin.binding.graal
  indexing into array java.util.concurrent.ConcurrentHashMap$Node[]@16839cf9: [Ljava.util.concurrent.ConcurrentHashMap$Node;@16839cf9
  reading field java.util.concurrent.ConcurrentHashMap.table of constant
    java.util.concurrent.ConcurrentHashMap@7262053b: {sci.impl.faster=sci.impl.faster, taoensso.nippy.compression=taoensso.nippy.comp...
  scanning root java.util.concurrent.ConcurrentHashMap@7262053b: {sci.impl.faster=sci.impl.faster, taoensso.nippy.compression=taoensso.nippy.comp... embedded in
    clojure.lang.Namespace.find(Namespace.java:188)
Error: type is not available in this platform: org.graalvm.nativeimage.c.CContext
Trace: Object was reached by
  reading field java.lang.Class.declaringClass of constant
    java.lang.Class@2bd3e84e: interface org.graalvm.nativeimage.c.CContext$Directives
  manually triggered rescan
Error: type is not available in this platform: org.graalvm.nativeimage.c.CContext
Trace: Object was reached by
  reading field java.lang.Class.nestHost of constant
    java.lang.Class@2bd3e84e: interface org.graalvm.nativeimage.c.CContext$Directives
  manually triggered rescan

	at com.oracle.graal.pointsto.constraints.UnsupportedFeatures.report(UnsupportedFeatures.java:129)
	at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:771)
	... 6 more
------------------------------------------------------------------------------------------------------------------------
                        1.9s (3.2% of total time) in 26 GCs | Peak RSS: 6.15GB | CPU load: 5.86
========================================================================================================================
Failed generating 'dtlv' after 57.7s.
Error: Image build request failed with exit status 1
com.oracle.svm.driver.NativeImage$NativeImageError: Image build request failed with exit status 1
	at org.graalvm.nativeimage.driver/com.oracle.svm.driver.NativeImage.showError(NativeImage.java:1730)
	at org.graalvm.nativeimage.driver/com.oracle.svm.driver.NativeImage.build(NativeImage.java:1427)
	at org.graalvm.nativeimage.driver/com.oracle.svm.driver.NativeImage.performBuild(NativeImage.java:1387)
	at org.graalvm.nativeimage.driver/com.oracle.svm.driver.NativeImage.main(NativeImage.java:1374)

**Comment by olpaw** [comment]
Looking how your sources are using our `@CContext` annotation ( `https://github.com/juji-io/datalevin/search?q=CContext`) makes me wonder :raised_eyebrow: 

The sole use of `@CContext` is to let the image builder know where to find the C header-files and what options are needed for query code compilation when you want to define special Java interfaces that allow you call C-functions (or access C-structs) at image runtime. Using it only makes sense in source files that define such interfaces. E.g. have a look at https://github.com/oracle/graal/blob/master/substratevm/src/com.oracle.svm.core.posix/src/com/oracle/svm/core/posix/headers/Pthread.java where we define an interface that allows us to to call pthread-specific C-Library functions from native-image at runtime.

None of your code seems to do anything like that. This seems to be a misuse of our `@CContext` annotation. There is no point in having `CContext` at image runtime since its values are only relevant for the image builder.

cc @christianwimmer

**Comment by olpaw** [comment]
> None of your code seems to do anything like that. This seems to be a misuse of our `@CContext` annotation. There is no point in having `CContext` at image runtime since its values are only relevant for the image builder.

On closer inspection there is one valid `@CContext` usecase in your code. That is in `[native/src/java/datalevin/ni/Lib.java](https://github.com/juji-io/datalevin/blob/bb7d9328f4739cddea5d272b5cd6d6dcb5345da6/native/src/java/datalevin/ni/Lib.java)`. But nowhere else in your code `@CContext` should be used.

**Comment by huahaiy** [comment]
There is nowhere in the documentation it is indicated that this is a build time only feature. If that was the intention, it was not communicated at all. 

Had it worked without adding those annotations, I wouldn’t have added them. It worked after adding those, for multiple versions of graalvm. 

It would have been good if it could work without those annotations. 

I am on vacation right now, and will test it out when I got back.  Hopefully you are right, but I doubt it would be as simple as you made it sound.

**Comment by huahaiy** [comment]
Indeed, removing those extra annotations resolved this problem. Thank you for the clarification.
