### ISSUE TITLE
Spring boot 3 - Caused by: java.lang.IllegalArgumentException: Invalid logger interface org.hibernate.validator.internal.util.logging.Log (implementation not found in jdk.internal.loader.ClassLoaders

### ISSUE THREAD

**Issue by vitorpavanelli** [oracle/graal#5626]
Hi,

I am having this issue when starting up the application:
Caused by: java.lang.IllegalArgumentException: Invalid logger interface org.hibernate.validator.internal.util.logging.Log (implementation not found in jdk.internal.loader.ClassLoaders$

I use the command mvn -Pnative spring-boot:build-image to create my image and then I run with docker run --env DB_ENCRYPTION_KEY=ererererer --rm -p 8080:8080 docker.io/library/my-app:0.0.1-SNAPSHOT

The same issue was found here https://github.com/oracle/graal/issues/1295 but it has been closed.

Please, has anyone seen this issue before and could guide me on how to fix it?

Thank you

GraalVM
java version "17.0.5" 2022-10-18 LTS
Java(TM) SE Runtime Environment GraalVM EE 22.3.0 (build 17.0.5+9-LTS-jvmci-22.3-b07)
Java HotSpot(TM) 64-Bit Server VM GraalVM EE 22.3.0 (build 17.0.5+9-LTS-jvmci-22.3-b07, mixed mode, sharing)

**Comment by Zegeri** [comment]
I had this issue. I found out that I had a dependency to spring-boot-starter-validation in the pom.xml, but I wasn't using it anywhere in my code. After removing it from the pom.xml, it started working.

**Comment by vitorpavanelli** [comment]
> I had this issue. I found out that there was a dependency to spring-boot-starter-validation in the pom.xml, but the code wasn't using it anywhere. After removing it from the pom.xml, it started working.

Hi @Zegeri, thank you for replying. I use that dependency to validate VOs.

**Comment by oubidar-Abderrahim** [comment]
Hi, Thank you for reaching out about this issue.
do you generate Metadata configuration files for your application? if not please do so. you can refer to this doc for more info: https://www.graalvm.org/22.3/reference-manual/native-image/metadata/AutomaticMetadataCollection/

**Comment by vitorpavanelli** [comment]
> Hi, Thank you for reaching out about this issue. do you generate Metadata configuration files for your application? if not please do so. you can refer to this doc for more info: https://www.graalvm.org/22.3/reference-manual/native-image/metadata/AutomaticMetadataCollection/

Hi @oubidar-Abderrahim !! thank you for replying. I don't use but I will check how it works. Thank you

**Comment by matthenry87** [comment]
@vitorpavanelli Do you happen to have an @Validated annotation on a @ConfigurationProperties class or something similar?

I have another project that uses spring-boot-starter-validation and compiles into a native-image just fine, but I'm running into this issue as well with a different project. I got past the Logger error with this:

```java
hints.reflection().registerConstructor(org.hibernate.validator.internal.util.logging.Log_$logger.class.getConstructor(org.jboss.logging.Logger.class), INVOKE);
```

I'm now seeing if this next hint gets me past a similar error:

```java
.registerField(org.hibernate.validator.internal.util.logging.Messages_$bundle.class.getField("INSTANCE"));
```

**Comment by vitorpavanelli** [comment]
> @vitorpavanelli Do you happen to have an @Validated annotation on a @ConfigurationProperties class or something similar?
> 
> I have another project that uses spring-boot-starter-validation and compiles into a native-image just fine, but I'm running into this issue as well with a different project. I got past the Logger error with this:
> 
> ```java
> hints.reflection().registerConstructor(org.hibernate.validator.internal.util.logging.Log_$logger.class.getConstructor(org.jboss.logging.Logger.class), INVOKE);
> ```
> 
> I'm now seeing if this next hint gets me past a similar error:
> 
> ```java
> .registerField(org.hibernate.validator.internal.util.logging.Messages_$bundle.class.getField("INSTANCE"));
> ```

Thank you, @matthenry87 !! I do use @Validated in few places. How did you figure out what and how you need to register the hint the way you did? This is pretty new to me and I am trying to get a project running. I does compile fine, but when it rans, I get the error fot the logging class. Please, do you also happen to have "AutomaticMetadataCollection" enabled? if yes, does it help troubleshoot these problems with hints? Thanks a bunch.

**Comment by matthenry87** [comment]
@vitorpavanelli Well first off another couple questions:

- Are you using a multi-module project?
- Did you remember to add the native plugins to your project?

The JBoss/Validator stuff is odd because they already have hints for those in the metadata repo.

**Comment by vitorpavanelli** [comment]
> @vitorpavanelli Well first off another couple questions:
> 
> * Are you using a multi-module project?
> * Did you remember to add the native plugins to your project?
> 
> The JBoss/Validator stuff is odd because they already have hints for those in the metadata repo.

@matthenry87 , I have a microservice, no modules. I am about to add a hint like you did to see what happens next. I will post the result. Thank you

**Comment by matthenry87** [comment]
@vitorpavanelli Would be interesting to narrow down whether the field validation on the @ConfigurationProperties is the culprit. Here's the hint code:

```java
import org.springframework.aot.hint.RuntimeHints;
import org.springframework.aot.hint.RuntimeHintsRegistrar;
import org.springframework.context.annotation.Configuration;
import org.springframework.context.annotation.ImportRuntimeHints;

import static org.springframework.aot.hint.ExecutableMode.INVOKE;

@Configuration
@ImportRuntimeHints(NativeImageHints.class)
class NativeImageHints implements RuntimeHintsRegistrar {

    @Override
    public void registerHints(RuntimeHints hints, ClassLoader classLoader) {

        try {

            hints.reflection()
                    .registerConstructor(org.hibernate.validator.internal.util.logging.Log_$logger.class.getConstructor(org.jboss.logging.Logger.class), INVOKE)
                    .registerField(org.hibernate.validator.internal.util.logging.Messages_$bundle.class.getField("INSTANCE"));

        } catch (NoSuchMethodException | NoSuchFieldException e) {

            throw new RuntimeHintsException(e);
        }
    }

    private static class RuntimeHintsException extends RuntimeException {

        RuntimeHintsException(Throwable cause) {

            super(cause);
        }

    }

}
```

**Comment by vitorpavanelli** [comment]
> @vitorpavanelli Would be interesting to narrow down whether the field validation on the @ConfigurationProperties is the culprit. Here's the hint code:
> 
> ```java
> import org.springframework.aot.hint.RuntimeHints;
> import org.springframework.aot.hint.RuntimeHintsRegistrar;
> import org.springframework.context.annotation.Configuration;
> import org.springframework.context.annotation.ImportRuntimeHints;
> 
> import static org.springframework.aot.hint.ExecutableMode.INVOKE;
> 
> @Configuration
> @ImportRuntimeHints(NativeImageHints.class)
> class NativeImageHints implements RuntimeHintsRegistrar {
> 
>     @Override
>     public void registerHints(RuntimeHints hints, ClassLoader classLoader) {
> 
>         try {
> 
>             hints.reflection()
>                     .registerConstructor(org.hibernate.validator.internal.util.logging.Log_$logger.class.getConstructor(org.jboss.logging.Logger.class), INVOKE)
>                     .registerField(org.hibernate.validator.internal.util.logging.Messages_$bundle.class.getField("INSTANCE"));
> 
>         } catch (NoSuchMethodException | NoSuchFieldException e) {
> 
>             throw new RuntimeHintsException(e);
>         }
>     }
> 
>     private static class RuntimeHintsException extends RuntimeException {
> 
>         RuntimeHintsException(Throwable cause) {
> 
>             super(cause);
>         }
> 
>     }
> 
> }
> ```

Thank you very much, @matthenry87 !! I added this hint and everything else worked fine. I got an issue with one class that has  @ConfigurationProperties. So I don't believe the problem relies on the  @ConfigurationProperties since I have few classes annotated with it and they work fine. As soon as I get a change, I will try to validate this better, but your help was great. Thank you very much again.

**Comment by matthenry87** [comment]
@vitorpavanelli Do you have any of your @ConfigurationProperties classes also annotated with @Validated, so that you can require the presence (or validate) an application property during app startup? Where you might annotate your instance variables with @NotNull etc so that if a property is missing the app will fail to start with an error message?

**Comment by vitorpavanelli** [comment]
> @vitorpavanelli Do you have any of your @ConfigurationProperties classes also annotated with @Validated, so that you can require the presence (or validate) an application property during app startup? Where you might annotate your instance variables with @NotNull etc so that if a property is missing the app will fail to start with an error message?

Yes, all of them have @Validated. Only one property didn't work as expected, but I will have to check why. The other worked fine. Currently I have 6 classes annotated with  @ConfigurationProperties and @Validated. I throw an error in case a property is missing using @NotEmpty, @NotNull and so on.
