### ISSUE TITLE
Is there a performance analysis and optimization tool for native image binary compiled based on graal

### ISSUE THREAD

**Issue by enderwsp** [oracle/graal#5627]
compiled graal ce 22.3.0 jdk11 Linux（centos）

I encounter a very confusing problem，the native binary is obviously inferior to the jvm running mode on press

i try to use jmx or jstatd with visualvm remotely，but cannot connect success

**Comment by oubidar-Abderrahim** [comment]
Hi, thank you for reaching out. Could you please elaborate what is the issue here? what is the actual behavior vs the expected one?

**Comment by oubidar-Abderrahim** [comment]
Sorry, I just read the title. we don't have such a tool. for optimization, there's PGO for EE which could be helpful (https://www.graalvm.org/22.0/reference-manual/native-image/PGO/)
