### ISSUE TITLE
Please improve jshell startup performance by AOT compilation by 500x

### ISSUE THREAD

**Issue by eGit** [oracle/graal#565]
https://twitter.com/deepities/status/1021711693586554881

![jshell startup time measurement](https://user-images.githubusercontent.com/842855/43139351-ca2d4ed0-8f51-11e8-9e0b-a76c9abe475c.png)

Please compile jshell ahead of time to get the startup from ~5sec to somewhere around ~10ms.

**Comment by thomaswue** [comment]
Challenge accepted.

**Comment by neomatrix369** [comment]
But is this even realistic to achieve?

**Comment by eGit** [comment]
![screenshot_2018-07-26_00-46-43](https://user-images.githubusercontent.com/842855/43231649-87ef0992-906d-11e8-990b-6ca3c3acedcb.png)

Simple AOT compiled HelloWorld I executed on the same oldish laptop I executed jshell on. Obviously this is a minimal example and jshell is probably quite complex. I wonder what jshell is doing, because ~5sec. seems awfully long. Maybe will do some digging later.

**Comment by thomaswue** [comment]
My assumption is that jshell is running quite some initialization code and also loads javac. The main technical challenge for us will be to load and interpret the dynamically generated bytecodes. This is a functionality that we miss at this point in time in native image mode, but it is under active development.

**Comment by lorenzleutgeb** [comment]
I came here trying to find out how I can bake JShell into a Native Image. As of 2020-10-28 the docs on [Dynamic Proxy in Native Image](https://www.graalvm.org/reference-manual/native-image/DynamicProxy/) state:

> Native Image does not provide machinery for generating and interpreting bytecodes at run time. Therefore all dynamic proxy classes need to be generated at native image build time.

The way I understand things, this is a requirement for JShell, since it needs to generate and interpret bytecode at run time. So, no  significant progress here, right?

**Comment by spavlusieva** [comment]
hi @eGit , this issue has been inactive for more than 180 days. We’ll close it to focus on current issues. In case it’s still relevant, please reopen it and we’ll take another look. Thank you!

**Comment by mukel** [comment]
For reference, here's a demo that does exactly this (AOT jshell + execution on Espresso)
 https://github.com/graalvm/graalvm-demos/tree/master/espresso-jshell
