### ISSUE TITLE
Fatal error: org.graalvm.compiler.debug.GraalError: LLVM optimization failed for batch

### ISSUE THREAD

**Issue by Arcane561** [oracle/graal#5666]
**Describe the issue**
When trying to build a native image with an llvm backend and bitcode optimization, a compilation error occurs
Fatal error: org.graalvm.compiler.debug.GraalError: LLVM optimization failed for batch 

**Steps to reproduce the issue**

- wget https://gist.githubusercontent.com/JaroslavTulach/3d10da1ad1cc2e6fb7d9bacb78ea77ea/raw/03f7ef2d0936ba2e0e800e254add7311d24bba6b/Shape.java
- javac Shape.java
- native-image -H:CompilerBackend=llvm -H:+BitcodeOptimizations Shape

**Describe GraalVM and your environment:**

openjdk 17.0.5 2022-10-18
OpenJDK Runtime Environment GraalVM CE 22.3.0 (build 17.0.5+8-jvmci-22.3-b08)
OpenJDK 64-Bit Server VM GraalVM CE 22.3.0 (build 17.0.5+8-jvmci-22.3-b08, mixed mode, sharing)

Logs: 
[logs.txt](https://github.com/oracle/graal/files/10281794/logs.txt)

**Comment by Arcane561** [comment]
Most likely the problem is that the version of llvm was upgraded to 14.x, which removed disable-inlining https://github.com/llvm/llvm-project/commit/096d9814aa07d8bf1939f75c3c632fcff2c3f573
However opt suggests using `disable-preinline` which is described here https://github.com/llvm/llvm-project/blob/f28c006a5895fc0e329fe15fead81e37457cb1d1/llvm/lib/Transforms/IPO/PassManagerBuilder.cpp#L125

**Comment by oubidar-Abderrahim** [comment]
Hi, Thank you for reaching out, we'll take a look into this shortly

**Comment by xbjfk** [comment]
I just ran into this issue, and I think it would be nice if there was a way to override the arguments to `opt`, so you can specify your own. As a temporary workaround I am using a custom `llvm.bin.dir` where everything is symlinked to llvm except `opt` is a custom wrapper script that discards graal's arguments and uses its own. Should I open a new issue for this?

**Comment by SergejIsbrecht** [comment]
It seems I get the same issue:

```
>> /home/sergej/.sdkman/candidates/java/20.0.2-graal/lib/llvm/bin/opt -disable-inlining -O2 -rewrite-statepoints-for-gc -always-inline -o f4525o.bc f4525.bc
># opt: Unknown command line argument '-disable-inlining'.  Try: '/home/sergej/.sdkman/candidates/java/20.0.2-graal/lib/llvm/bin/opt --help'
># opt: Did you mean '--disable-preinline'?
>> /home/sergej/.sdkman/candidates/java/20.0.2-graal/lib/llvm/bin/opt -disable-inlining -O2 -rewrite-statepoints-for-gc -always-inline -o f4526o.bc f4526.bc
>> /home/sergej/.sdkman/candidates/java/20.0.2-graal/lib/llvm/bin/opt -disable-inlining -O2 -rewrite-statepoints-for-gc -always-inline -o f4527o.bc f4527.bc
 !  ~/D/D/S/s/m/j/d/sergejisbrecht  /home/sergej/.sdkman/candidates/java/20.0.2-graal/lib/llvm/bin/opt --version                  1.7m  Mo 04 Sep 2023 17:05:05 CEST
LLVM (http://llvm.org/):
  LLVM version 15.0.6-4-gaeae49c2d7-bg8671e93c04
  Optimized build.
  Default target: x86_64-unknown-linux-gnu
  Host CPU: skylake
```

With 

```
~  native-image --version                                                                                   Mo 04 Sep 2023 17:08:39 CEST
native-image 20.0.2 2023-07-18
GraalVM Runtime Environment Oracle GraalVM 20.0.2+9.1 (build 20.0.2+9-jvmci-23.0-b14)
Substrate VM Oracle GraalVM 20.0.2+9.1 (build 20.0.2+9, serial gc, compressed references)
````

**Comment by oubidar-Abderrahim** [comment]
The original issue was resolved, therefore I'm closing this issue. 
I would suggest creating a feature request to discuss any updates to optimization flags.

**Comment by SergejIsbrecht** [comment]
@oubidar-Abderrahim ,

as far as I see it, the `BitcodeOptimizations` flag does not work.
