### ISSUE TITLE
Error while deploy native image

### ISSUE THREAD

**Issue by wotuthink** [oracle/graal#5681]
When create native docker image I receive following error after deployment. I tried adding dependencies in pom.xml and in application properties but no gain. Receive same below mentioned error. While with jvm it works fine.

ERROR [org.jbo.res.rea.com.cor.AbstractResteasyReactiveContext] (executor-thread-0) Request failed: java.lang.IllegalStateException: Failed to find class com.fasterxml.jackson.databind.deser.std.DateDeserializers$SqlDateDeserializer for handling values of type java.sql.Date, problem: (java.lang.ClassNotFoundException) com.fasterxml.jackson.databind.deser.std.DateDeserializers$SqlDateDeserializer

**Comment by aabbou** [comment]
Hi, Thank you for reporting this issue.
Can you please provide us with more details about the context. The following might be of great help :

**Describe the issue**
Include the type of your project (Micronaut, Springboot, Quarkus, ...)
Include the flags/Args you used for building the native image

**Steps to reproduce the issue**
Share with us how to reproduce the issue (Please include both build steps as well as run steps)

**Describe GraalVM and your (deployment) environment**

- GraalVM version:
- JDK major version: 
- OS: 
- Architecture:

**More details**
 Include the full stack trace of the error

**Comment by fniephaus** [comment]
AFAIK Jackson uses a lot of reflection for serialization, which requires additional [reachability metadata](https://www.graalvm.org/22.3/reference-manual/native-image/metadata/) to work with Native Image. The [trace agent](https://www.graalvm.org/22.3/reference-manual/native-image/metadata/AutomaticMetadataCollection/) may help you find appropriate metadata. But if possible, I'd try and do whatever you use Jackson for at build-time. For that, you need to use `--initialize-at-build-time=your.package.YourClass`.

**Comment by aabbou** [comment]
Closing the issue. Feel free to re-open if the bug still persists.
