### ISSUE TITLE
Native image suddenly stops working

### ISSUE THREAD

**Issue by Hilal-Anwar** [oracle/graal#5685]
**Describe the issue**
I made a native image but there is no problem in formation of native image , the problem is  that the executable stops working at a particular instance.
I don't know is it my project issue or GraalVm issue because the jar file is working fine.
Can anyone please help me.

**Steps to reproduce the issue**
My project gitHub link.
https://github.com/Hilal-Anwar/GameOfLife

My project dependency's

[jline3](https://github.com/jline/jline3)
[jna](https://github.com/java-native-access/jna)
[jansi](https://github.com/fusesource/jansi)

**Describe GraalVM and your environment:**
 - GraalVM 
 - openjdk version "19.0.1" 2022-10-18
OpenJDK Runtime Environment GraalVM CE 23.0.0-dev (build 19.0.1+10-jvmci-23.0-b04)
OpenJDK 64-Bit Server VM GraalVM CE 23.0.0-dev (build 19.0.1+10-jvmci-23.0-b04, mixed mode, sharing)

 - JDK major version: "19.0.1" 2022-10-18*
 - OS: Edition	Windows 11 Home Single Language
     Version	22H2
     Installed on	‎05-‎10-‎2022
    OS build	22621.963
    Experience	Windows Feature Experience Pack 1000.22638.1000.0

 - Architecture: **x64**

![WindowsTerminal_kY26LRpQFl](https://user-images.githubusercontent.com/50636048/210177649-ce891302-fe2d-4c24-8b14-09715cff566b.png)

This is the jar file version

https://user-images.githubusercontent.com/50636048/210177666-4405b5d4-a997-4cdb-976d-e28a3ef70f0f.mp4

This is the executable version.

https://user-images.githubusercontent.com/50636048/210177711-e7382671-185c-46f9-a44a-294d5d0c452e.mp4

**Comment by oubidar-Abderrahim** [comment]
Hi, Thank you for reaching out about this issue, did you generate the Metadata config files using our Tracing Agent? if not, please do so and let us know if this fixes your problem. you can find more about it on this link: https://www.graalvm.org/22.3/reference-manual/native-image/metadata/AutomaticMetadataCollection/

**Comment by Hilal-Anwar** [comment]
Thanks a lot for your reply.
I tried it using  Tracing Agent but could not fix the problem.
I have confusion regarding META-INF/native-image directory ,should I put that in resource directory or in target ,currently it is in target directory where my jar file is.
I am using mvn clean compile assembly:single top make jar.
and then using native-image --no-fallback -jar "GameOfLife-1.0-SNAPSHOT-jar-with-dependencies.jar" to make native image.
Link to meta-inf https://github.com/Hilal-Anwar/GameOfLife/tree/master/target/META-INF/native-image
