### ISSUE TITLE
[ERROR] Server resources are missing

### ISSUE THREAD

**Issue by Nil1one** [oracle/graal#5700]
# As shown in the figure:
![image](https://user-images.githubusercontent.com/47878132/210635676-cdeb2797-f0cf-4817-a6c4-645c8f56322a.png)

**Comment by wirthi** [comment]
We don't currently support those languages on Windows. See https://www.graalvm.org/latest/docs/getting-started/windows/#supported-functionalities

It is on our roadmap to eventually get there. We could enable [LLVM support for Windows as an experimental feature in GraalVM 22.3](https://www.graalvm.org/release-notes/22_3/#llvm-runtime) (you see it listed in your screenshot). This is a major prerequisite and enables us to further work on this for languages like Python. But as of now, it is not available. 

You can follow https://github.com/oracle/graalpython/issues/156 to track progress on this (for Python specifically).
