### ISSUE TITLE
Unsupported method java.io.FileDescriptor.sync() is reachable

### ISSUE THREAD

**Issue by nmcl** [oracle/graal#573]
Hi. Trying to build some code from a project which uses various I/O routines from standard Java and getting the following:

error: Unsupported method java.io.FileDescriptor.sync() is reachable: Native method. If you intend to use the Java Native Interface (JNI), specify -H:+JNI and see also -H:JNIConfigurationFiles=<path> (use -H:+PrintFlags for details)
To diagnose the issue, you can add the option -H:+ReportUnsupportedElementsAtRuntime. The unsupported element is then reported at run time when it is accessed the first time.
Detailed message:
Error: Unsupported method java.io.FileDescriptor.sync() is reachable: Native method. If you intend to use the Java Native Interface (JNI), specify -H:+JNI and see also -H:JNIConfigurationFiles=<path> (use -H:+PrintFlags for details)
To diagnose the issue, you can add the option -H:+ReportUnsupportedElementsAtRuntime. The unsupported element is then reported at run time when it is accessed the first time.
Call path from entry point to java.io.FileDescriptor.sync(): 
	at java.io.FileDescriptor.sync(FileDescriptor.java)

Wondering if this is an issue or there's some alternative approach I should be looking at within my code? Thanks for any pointers.

**Comment by Peter-B-Kessler** [comment]
I am on it.

**Comment by Peter-B-Kessler** [comment]
Implemented in https://github.com/oracle/graal/commit/205f447e64a9b7db98e3b1d5f4573bbd869010c5
