### ISSUE TITLE
Linux distribution contains duplicate files in archive

### ISSUE THREAD

**Issue by sschuberth** [oracle/graal#5740]
**Describe the issue**

As a follow-up to [my Slack conversation](https://graalvm.slack.com/archives/CNBFR78F9/p1673382897985159) with @rschatz, I'd like to point you guys at a potential packaging bug. E.g. https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-22.3.0/graalvm-ce-java11-linux-amd64-22.3.0.tar.gz contains the files `graalvm-ce-java11-22.3.0/lib/graalvm/launcher-common.jar` and `graalvm-ce-java11-22.3.0/lib/libtrufflenfi.so` twice (I haven't checked other distribution archives for other duplicates). While the TAR format basically allows that, it causes [issues e.g. with Gradle's toolchain provisioning](https://github.com/gradle/gradle/pull/23470).

**Steps to reproduce the issue**

1. Download https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-22.3.0/graalvm-ce-java11-linux-amd64-22.3.0.tar.gz
2. Run `tar tzf graalvm-ce-java11-linux-amd64-22.3.0.tar.gz | sort | uniq -d`

**Comment by rschatz** [comment]
I have checked a few older GraalVM distributions I had, and it seems we have this bug for a while now, with various different files:
```
graalvm-ce-java11-20.3.3/lib/graalvm/launcher-common.jar

graalvm-ee-java11-21.1.0/lib/graalvm/launcher-common.jar
graalvm-ee-java11-21.1.0/lib/graalvm/sulong-toolchain-launchers.jar

graalvm-ee-java16-21.1.0/lib/graalvm/launcher-common.jar
graalvm-ee-java16-21.1.0/lib/graalvm/sulong-toolchain-launchers.jar

graalvm-ee-java17-22.0.0.2/lib/graalvm/launcher-common.jar
graalvm-ee-java17-22.0.0.2/lib/graalvm/sulong-toolchain-launchers.jar

graalvm-ce-java17-22.2.0/lib/graalvm/launcher-common.jar
graalvm-ce-java17-22.2.0/lib/libtrufflenfi.so
```
cc @gilles-duboscq

**Comment by gilles-duboscq** [comment]
This should have been fixed on master (i.e., >=23.0) with a3816abe902081d672ae5d65c29114897c396b59.

If this causes issues in some tools, it's probably worth backporting it to older release branches. I'll look into that.

**Comment by rubyFeedback** [comment]
> If this causes issues in some tools

It probably won't cause issues (hopefully not a "famous last words" comment ...) - however had it could be made
an opportunity to look at how the standalone-downloadable files are generated in the first place. Perhaps these
could be auto-packaged via some helper-script that can exclude such issues (file distributed that should not
be distributed). Like some flexible script that could auto-package things.

**Comment by gilles-duboscq** [comment]
FYI this is getting backported to 21.3 and 22.3.

**Comment by gilles-duboscq** [comment]
The original issue was fixed, if there are new occurrences let's open another issue.
I know that we have some warnings in place when this happens, maybe those could be turned into errors (if it's not already done) so we have more chances to catch it.
/cc @ansalond
