### ISSUE TITLE
`bin/gu` fails to install `native-image` when being a copy instead of a symlink

### ISSUE THREAD

**Issue by sschuberth** [oracle/graal#5743]
**Describe GraalVM and your environment :**

 - GraalVM version or commit id if built from source: 22.3.0
 - CE or EE: CE
 - JDK version: JDK11
 - OS and OS Version: Linux (Fedora 37 KDE)
 - Architecture: amd64

**Have you verified this issue still happens when using the latest snapshot?**

No.

**Describe the issue**

As a work-around for not being able to create symlinks, I (re-)created `bin/gu` as a *copy* of `lib/installer/bin/gu` (instead of the symlink that's part of the archive at https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-22.3.0/graalvm-ce-java11-linux-amd64-22.3.0.tar.gz). Then running `bin/gu install native-image` yields `Error: The GraalVM directory ~/.gradle/jdks/graalvm_community-11-amd64-linux is invalid`. The error disappears when turning `bin/gu` into a link again.

**Expected behavior**

I'd expect `bin/gu` to be able to install `native-image` even if it's a copy. If that not possible by design (e.g. due to some directory layout detection going on), then at least the error message should be clear about *what* is "invalid" about the directory.

**Additional context**

This would be a prerequisite for installing native-image tools on a file system that does not support symlinks.

**Comment by oubidar-Abderrahim** [comment]
Hi, Thank you for reaching out about this. 

Since `gu` needs to install components in the correct location, it can only do so by using relative paths from the `lib/installer/bin` folder. it won't be possible to use absolute paths since the path will differ from one user to another. 

For your case, the solution will be to use the `lib/installer/bin/gu` for installing any component you need.

**Comment by sschuberth** [comment]
> Since `gu` needs to install components in the correct location, it can only do so by using relative paths from the `lib/installer/bin` folder.

Understood. But could then (as mentioned) at least the error message be clearer?

**Comment by eliasdaler** [comment]
Indeed. I also think that this should be documented.
Because otherwise it's very hard to use dev builds without installing them system-wide.
