### ISSUE TITLE
Compiler Warning "The expression of type byte is boxed into Byte" in getIntrospectionData

### ISSUE THREAD

**Issue by arthurp** [oracle/graal#575]
The generated `getIntrospectionData` methods in `NodeGen`s cause this warning (if it's turned on). Not a big deal, but I don't see any downside of adding `@SuppressWarnings("boxing")` to `getIntrospectionData`.

**Comment by ljluestc** [comment]
If you'd like to suppress this warning using a Java annotation, you can use `@SuppressWarnings("boxing")` to indicate that you're aware of the boxing occurring in your code.

Here's how you can do it:

```java
@SuppressWarnings("boxing")
public YourType getIntrospectionData() {
    // Your code here
}
```

By adding `@SuppressWarnings("boxing")` above the method declaration, you're informing the compiler to suppress warnings related to boxing that might occur within that method. This can help eliminate the warning without affecting the functionality of your code.

**Comment by selhagani** [comment]
Thanks for the suggestion ljluestc. 
Arthurp, I know that the ticket was opened a long time ago but if you are still interested please feel free to let me know if the suggestion solves your issue.

**Comment by selhagani** [comment]
I am closing this issue because it's been over 2 weeks since my last interaction and I haven't received any updates yet.
