### ISSUE TITLE
Exceptions thrown inside of the delegate of a polyglot `toString` call are swallowed

### ISSUE THREAD

**Issue by radeusgd** [oracle/graal#5755]
**Feature request**

As discussed in [this Slack thread](https://graalvm.slack.com/archives/CNQSB2DHD/p1673412770137559).

Currently, if I override the text representation in an object (`__repr__` in Python, `to_text` in Enso) and my custom implementation throws an exception, that exception is swallowed and the text representation becomes just `Error in toString()` if called through the Polyglot boundary (i.e. if I override the behaviour for a Python object and then pass that object over to a Java method and call `toString` in Java on that Python object's instance). That does not allow me to figure out what has gone wrong nor handle the exception in any way.

Currently, @jtulach has implemented a [workaround in Enso](https://github.com/enso-org/enso/pull/4034) that at least includes the message of the swallowed exception.

However, as discussed in the Slack thread, it may be best to allow to propagate these errors, so that the caller

**Is your feature request related to a problem? Please describe.**

It is problematic to debug any exceptions thrown from a string representation as they are swallowed and I don't even know what is thrown.

I cannot write my logic defensively to include custom logic for handling errors in the text representation because I have no robust way to detect that an error happened inside of that representation (because it is swallowed).

**Describe the solution you'd like.**

As [discussed on Slack](https://graalvm.slack.com/archives/CNQSB2DHD/p1673436829788349?thread_ts=1673412770.137559&cid=CNQSB2DHD), it would probably be best to propagate the exception and allow the caller to handle it.

**Describe who do you think will benefit the most.**
Developers who use the Polyglot features and pass objects between languages.

**Describe alternatives you've considered.**
If the exception must be swallowed, we should at least provide some more details about what was the swallowed exception in the resulting message.

**Additional context.**
Some extra care may be needed at fragile parts of the codebase calling `toString` when the exceptions are no longer swallowed. For example, in the Debugger, if I want to see what objects are defined in the scope and one of these objects has a text representation that will throw, I definitely do not want to be stopped from debugging this scope. So such display should probably be careful and catch the now propagated exceptions and return some fallback representation for such objects (probably something like what is returned now, but ideally with more details, like `Exception in toString(): <exception message>`.

**A repro**

```java
import java.io.ByteArrayOutputStream;
import java.util.Map;
import org.graalvm.polyglot.Context;
import org.graalvm.polyglot.Language;
import org.graalvm.polyglot.Source;
import org.graalvm.polyglot.Value;

public class Foo {
  public static class Inner {
    public void bar(Object o) {
        try {
        System.out.println("[[" + o + "]]");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
  }

  public static void main(String[] args) throws Exception {
    Context ctx = Context.newBuilder()
      .allowExperimentalOptions(true)
      .allowIO(true)
      .allowAllAccess(true)
    //   .logHandler(new ByteArrayOutputStream())
      .build();
    final Map<String, Language> langs = ctx.getEngine().getLanguages();
    System.out.println(langs);

    var code =
    "def foo(inner):\n" +
    "   class KlasCustom:\n" +
    "       def __repr__(self):\n" +
    "           return \"custom-REPR\"\n" +
    "   class KlasException:\n" +
    "       def __repr__(self):\n" +
    "           raise ValueError(\"I'm raising an error within __repr__.\")\n" +
    "   class KlasInvalidType:\n" +
    "       def __repr__(self):\n" +
    "           return 42\n" +
    "   x = KlasCustom()\n" +
    "   print('custom override returning string:')\n" +
    "   inner.bar(x)\n" +
    "   y = KlasException()\n" +
    "   print('custom override raising an exception:')\n" +
    "   inner.bar(y)\n" +
    "   z = KlasInvalidType()\n" +
    "   print('custom override returning an invalid type:')\n" +
    "   inner.bar(z)\n" +
    "foo";
    var src = Source.newBuilder("python", code, "test.py").build();
    var module = ctx.eval(src);
    System.out.println(module);
    var inner = new Inner();
    module.execute(inner);
  }
}
```

Compile this code with `javac Foo.java` and run it with `java Foo`.

On my machine it prints:
```
{llvm=org.graalvm.polyglot.Language@6fd83fc1, js=org.graalvm.polyglot.Language@4f2b503c, python=org.graalvm.polyglot.Language@bae7dc0}
<function foo at 0x4e030feb>
custom override returning string:
[[custom-REPR]]
custom override raising an exception:
[[Error in toString()]]
custom override returning an invalid type:
[[Error in toString()]]
```

We can see that in the last 2 cases the errors are swallowed.

Ideally, the error should be propagated and I should be able to catch it in the Java piece of code or in the Python callsite.

**Comment by chumer** [comment]
Thanks for the report!

Fix: https://github.com/oracle/graal/pull/5779
