### ISSUE TITLE
Support for Windows on ARM

### ISSUE THREAD

**Issue by fzhwenzhou** [oracle/graal#5757]
**Feature request**
I'm developing on an Windows on ARM laptop which has Snapdragon 8cx Gen 3 CPU in it. It's delighted to know that Visual Studio 2022 and OpenJDK (Microsoft Build) can run natively on these devices, which means that the dependencies of GraalVM on this platform are all met. So I wonder if there could be a port for Windows on ARM. Thank you.

**Comment by lewurm** [comment]
Support for Windows-AArch64 is not planned for GraalVM currently.

You can however run WSL2 and use the linux-aarch64 bits that we distribute.
