### ISSUE TITLE
Unexpected getResource behaviour

### ISSUE THREAD

**Issue by nmcl** [oracle/graal#576]
Hi. In an existing jar file (called BasicExample.jar for the purposes of this issue) I'm trying to move to a native image (via native-image -jar <jar file>) I'm seeing some unexpected (to me) behaviour; it may be valid for Graal but I wanted to check before I try to figure out a workaround.

So the code that is exhibiting the behaviour is basically the following:

String classFileName = ConfigurationInfo.class.getSimpleName()+".class";
String pathToThisClass = ConfigurationInfo.class.getResource(classFileName).toString();

where ConfigurationInfo is class within the jar I mentioned earlier.

If I run this normally, I get the following expected behaviour and these two variables end up with contents roughly like this:

classFileName = ConfigurationInfo.class
pathToThisClass = jar:file:/Users/me/source/BasicExample.jar!/foo/bar/common/util/ConfigurationInfo.class

At this point the code then goes off and does some other "magic" to then locate the manifest data within the jar.

Now if I try this with native-image, the contents of those two variables end up roughly like this:

classFileName = ConfigurationInfo.class
pathToThisClass = file:/Users/me/source/foo/bar/common/util/ConfigurationInfo.class

As I said earlier, this may be entirely correct for Graal in the context of building and running a native image.

**Comment by olpaw** [comment]
When you build a native image you have to opt-in any resources that you want to have available at image run-time. See https://github.com/oracle/graal/blob/master/substratevm/RESOURCES.md

Suppose you have:
```
public class App {
    public static void main(String[] args) {
        String classFileName = ConfigurationInfo.class.getSimpleName() + ".class";
        URL resource = ConfigurationInfo.class.getResource(classFileName);
        String pathToThisClass = resource.toString();
        System.out.println("classFileName: " + classFileName);
        System.out.println("pathToThisClass: " + pathToThisClass);
        try {
            String contents = new Scanner(resource.openStream(), "UTF-8").useDelimiter("\\A").next();
            System.out.println("class contents: " + Arrays.toString(contents.getBytes()));
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
}
class ConfigurationInfo {
}
```
If you run that on the JVM you will see:
```
java -jar target/app-1.0-SNAPSHOT.jar 
classFileName: ConfigurationInfo.class
pathToThisClass: jar:file:/home/pwoegere/OLabs/git/GR-11089/app/target/app-1.0-SNAPSHOT.jar!/one/paw/ConfigurationInfo.class
class contents: [-17, -65, -67, -17, -65, -67, -17, -65, -67, -17, -65, -67, 0, 0, 0, 49, 0, 16, 10, 0, 3, 0, 13, 7, 0, 14, 7, 0, 15, 1, 0, 6, 60, 105, 110, 105, 116, 62, 1, 0, 3, 40, 41, 86, 1, 0, 4, 67, 111, 100, 101, 1, 0, 15, 76, 105, 110, 101, 78, 117, 109, 98, 101, 114, 84, 97, 98, 108, 101, 1, 0, 18, 76, 111, 99, 97, 108, 86, 97, 114, 105, 97, 98, 108, 101, 84, 97, 98, 108, 101, 1, 0, 4, 116, 104, 105, 115, 1, 0, 27, 76, 111, 110, 101, 47, 112, 97, 119, 47, 67, 111, 110, 102, 105, 103, 117, 114, 97, 116, 105, 111, 110, 73, 110, 102, 111, 59, 1, 0, 10, 83, 111, 117, 114, 99, 101, 70, 105, 108, 101, 1, 0, 8, 65, 112, 112, 46, 106, 97, 118, 97, 12, 0, 4, 0, 5, 1, 0, 25, 111, 110, 101, 47, 112, 97, 119, 47, 67, 111, 110, 102, 105, 103, 117, 114, 97, 116, 105, 111, 110, 73, 110, 102, 111, 1, 0, 16, 106, 97, 118, 97, 47, 108, 97, 110, 103, 47, 79, 98, 106, 101, 99, 116, 0, 32, 0, 2, 0, 3, 0, 0, 0, 0, 0, 1, 0, 0, 0, 4, 0, 5, 0, 1, 0, 6, 0, 0, 0, 47, 0, 1, 0, 1, 0, 0, 0, 5, 42, -17, -65, -67, 0, 1, -17, -65, -67, 0, 0, 0, 2, 0, 7, 0, 0, 0, 6, 0, 1, 0, 0, 0, 29, 0, 8, 0, 0, 0, 12, 0, 1, 0, 0, 0, 5, 0, 9, 0, 10, 0, 0, 0, 1, 0, 11, 0, 0, 0, 2, 0, 12]
```
To get the same result when you run that example as a native-image you need to build with
```
native-image -jar target/app-1.0-SNAPSHOT.jar -H:IncludeResources='.*ConfigurationInfo.class'
```
Here the use of `-H:IncludeResources` makes sure that the contents of resources matching the regex will be embedded into the image that is created. Running the image will then give you:
```
app> ./app-1.0-SNAPSHOT 
classFileName: ConfigurationInfo.class
pathToThisClass: resource:one/paw/ConfigurationInfo.class
class contents: [-17, -65, -67, -17, -65, -67, -17, -65, -67, -17, -65, -67, 0, 0, 0, 49, 0, 16, 10, 0, 3, 0, 13, 7, 0, 14, 7, 0, 15, 1, 0, 6, 60, 105, 110, 105, 116, 62, 1, 0, 3, 40, 41, 86, 1, 0, 4, 67, 111, 100, 101, 1, 0, 15, 76, 105, 110, 101, 78, 117, 109, 98, 101, 114, 84, 97, 98, 108, 101, 1, 0, 18, 76, 111, 99, 97, 108, 86, 97, 114, 105, 97, 98, 108, 101, 84, 97, 98, 108, 101, 1, 0, 4, 116, 104, 105, 115, 1, 0, 27, 76, 111, 110, 101, 47, 112, 97, 119, 47, 67, 111, 110, 102, 105, 103, 117, 114, 97, 116, 105, 111, 110, 73, 110, 102, 111, 59, 1, 0, 10, 83, 111, 117, 114, 99, 101, 70, 105, 108, 101, 1, 0, 8, 65, 112, 112, 46, 106, 97, 118, 97, 12, 0, 4, 0, 5, 1, 0, 25, 111, 110, 101, 47, 112, 97, 119, 47, 67, 111, 110, 102, 105, 103, 117, 114, 97, 116, 105, 111, 110, 73, 110, 102, 111, 1, 0, 16, 106, 97, 118, 97, 47, 108, 97, 110, 103, 47, 79, 98, 106, 101, 99, 116, 0, 32, 0, 2, 0, 3, 0, 0, 0, 0, 0, 1, 0, 0, 0, 4, 0, 5, 0, 1, 0, 6, 0, 0, 0, 47, 0, 1, 0, 1, 0, 0, 0, 5, 42, -17, -65, -67, 0, 1, -17, -65, -67, 0, 0, 0, 2, 0, 7, 0, 0, 0, 6, 0, 1, 0, 0, 0, 29, 0, 8, 0, 0, 0, 12, 0, 1, 0, 0, 0, 5, 0, 9, 0, 10, 0, 0, 0, 1, 0, 11, 0, 0, 0, 2, 0, 12]
```
Note how the URL for the resource now shows `resource:one/paw/ConfigurationInfo.class` instead. That is the result of embedding the matching resource into the image.
