### ISSUE TITLE
Unexpected user.dir

### ISSUE THREAD

**Issue by nmcl** [oracle/graal#577]
Following on from https://github.com/oracle/graal/issues/576 if the program I'm using can't find manifest data in the jar it defaults to looking for relevant configuration data in some specified places, one of which is user.dir.

Now running outside Graal this property resolves to the current working/executing directory as expected. For Graal it's a bit different and, again, unexpected:

/Users/me/.native-image/machine-id-hostid-0/session-id-2f92/server-id-52c4416f9d4428f66dde9dc05de2016ff99431b8062bf69a2313e1966848d913d8156e0fb35286eb94c98280a3717e3c3f96ae98a566536295ae0a268fc15790

As with the previous issue, I'm not sure if this is a bug or correct behaviour so raising here for clarification. Thanks.

**Comment by nmcl** [comment]
Got it, thanks for the clarification.

**Comment by kinsleykajiva** [comment]
how can one  get the home folder or user home folder for example in Linux one can get "/home/userfolder" when the we run a native image built .
