### ISSUE TITLE
Adding imports to wasm

### ISSUE THREAD

**Issue by bakkot** [oracle/graal#5809]
On the web and in other runtimes, [instantiating a WebAssembly module](https://developer.mozilla.org/en-US/docs/WebAssembly/JavaScript_interface/instantiate#primary_overload_%E2%80%94_taking_wasm_binary_code) allows you to pass an object defining functions and other values which are accessible to the wasm code. Is there an equivalent way to do that in graal, so that you can run existing wasm programs which expect imports?

I see [there are tests](https://github.com/oracle/graal/blob/3e7ececfa33e23b8695fb1ce9ab4017901839b2a/wasm/src/org.graalvm.wasm.test/src/org/graalvm/wasm/test/WasmJsApiSuite.java#L142-L157) which look like they're doing this, but they're not using any documented APIs, from what I can tell.

**Comment by oubidar-Abderrahim** [comment]
Thank you for reaching out, Let me check and I'll get back to you with updates

**Comment by oubidar-Abderrahim** [comment]
`graal-js` implements WebAssembly JavaScript API (which is what your first link points to). Of course, you have to have both `wasm` and `js` installed and you have to enable it (using `--polyglot --js.webassembly --experimental-options`)

**Comment by irishgreencitrus** [comment]
Is this possible currently?

I understand it's hugely important for the containment of wasm for safe function to be called to outside the module meaning that the module never has to be given full trust.

I think if this is currently possible, some clear documentation on the subject would be a nice addition as well.

**Comment by bakkot** [comment]
@oubidar-Abderrahim Thanks, that's helpful if you're using JS to instantiate the WebAssembly. But what if you're [instantiating it directly](https://www.graalvm.org/latest/reference-manual/wasm/#embedding-webassembly-programs)?

**Comment by bakkot** [comment]
@oubidar-Abderrahim I'm confused, why was this closed? Is there now a way of doing this?
