### ISSUE TITLE
Can't find java.home ??

### ISSUE THREAD

**Issue by Hilal-Anwar** [oracle/graal#5810]
I tried make a native image  of my [Tetris](https://github.com/Hilal-Anwar/Tetris]) game.
I have some sound files(.wav) which I want to play as background music in the game.
There is no problem in formation of native image
but  when you  run the native image formed you will get an error like this.
Exception in thread "main" java.lang.Error: Can't find java.home ??
        at java.desktop@19.0.1/com.sun.media.sound.JSSecurityManager.lambda$loadProperties$1(JSSecurityManager.java:90)
        at java.base@19.0.1/java.security.AccessController.executePrivileged(AccessController.java:171)
        at java.base@19.0.1/java.security.AccessController.doPrivileged(AccessController.java:318)
        at java.desktop@19.0.1/com.sun.media.sound.JSSecurityManager.loadProperties(JSSecurityManager.java:87)
        at java.desktop@19.0.1/com.sun.media.sound.JDK13Services.getProperties(JDK13Services.java:192)
        at java.desktop@19.0.1/com.sun.media.sound.JDK13Services.getDefaultProvider(JDK13Services.java:177)
        at java.desktop@19.0.1/com.sun.media.sound.JDK13Services.getDefaultProviderClassName(JDK13Services.java:118)
        at java.desktop@19.0.1/javax.sound.sampled.AudioSystem.getDefaultMixer(AudioSystem.java:1305)
        at java.desktop@19.0.1/javax.sound.sampled.AudioSystem.getLine(AudioSystem.java:360)
        at org.game.tetris.Game.play(Game.java:632)
        at org.game.tetris.GameLauncher.launch(GameLauncher.java:63)
        at org.game.tetris.Main.main(Main.java:7)
I used Tracing Agent to generate META-INF.
I don't understand why this is happing? 

**Steps to reproduce the issue**
Please include both build steps as well as run steps
1. [Tetris](https://github.com/Hilal-Anwar/Tetris])
2. **[ Build the project  : mvn clean compile assembly:single]**

**Describe GraalVM and your environment:**
openjdk version "19.0.1" 2022-10-18
OpenJDK Runtime Environment GraalVM CE 23.0.0-dev (build 19.0.1+10-jvmci-23.0-b04)
OpenJDK 64-Bit Server VM GraalVM CE 23.0.0-dev (build 19.0.1+10-jvmci-23.0-b04, mixed mode, sharing)
 - JDK major version: 19.0.1
 - OS: windows 11
 - Architecture: x64

**Comment by oubidar-Abderrahim** [comment]
From the code of the failing method
https://github.com/openjdk/jdk/blob/jdk-11+17/src/java.desktop/share/classes/com/sun/media/sound/JSSecurityManager.java#L63-L94
you can see that the method looks for the sound property file, you can either provide you own with javax.sound.config.file as a system property or let the app pick the default configuration from JAVA_HOME/conf/sound.properties ( you don't need a complete GraalVM/JDK installation, just the sound file in the correct path, so you need to set your JAVA_HOME to the correct path)

**Comment by kristofdho** [comment]
@oubidar-Abderrahim I don't agree that this is the right solution. A similar thing happens if you need the fontmanager sutff. The proper fix would be that native-image embeds the default resource from `JAVA_HOME/conf/` into the image so there is no longer a dependency on the java.home property in the created native-image. An override of the sound properties would still be possible by (specifically in this case) providing the `javax.sound.config.file` property to the native-image.

**Comment by Hilal-Anwar** [comment]
I am not able it fix the problem.
Can you please elaborate this "so you need to set your JAVA_HOME to the correct path"

My java home path
![SystemPropertiesAdvanced_fSe7cEvno0](https://user-images.githubusercontent.com/50636048/221280394-f8c9dfb3-7c55-4d83-abcd-d6d8c5c1b0f4.png)

**Comment by Hilal-Anwar** [comment]
> From the code of the failing method https://github.com/openjdk/jdk/blob/jdk-11+17/src/java.desktop/share/classes/com/sun/media/sound/JSSecurityManager.java#L63-L94 you can see that the method looks for the sound property file, you can either provide you own with javax.sound.config.file as a system property or let the app pick the default configuration from JAVA_HOME/conf/sound.properties ( you don't need a complete GraalVM/JDK installation, just the sound file in the correct path, so you need to set your JAVA_HOME to the correct path)

I am not able to fix the problem.
Can you please elaborate this "so you need to set your JAVA_HOME to the correct path"

My java home path

![SystemPropertiesAdvanced_fSe7cEvno0](https://user-images.githubusercontent.com/50636048/221280394-f8c9dfb3-7c55-4d83-abcd-d6d8c5c1b0f4.png)

**Comment by oubidar-Abderrahim** [comment]
Could you please share a reproducer and will take a look into it

**Comment by Hilal-Anwar** [comment]
Thanks for your response.
My project link[]( https://github.com/Hilal-Anwar/Tetris)
Native image [](https://github.com/Hilal-Anwar/Tetris/tree/master/target)
Config file generated using Tracing Agent [`](https://github.com/Hilal-Anwar/Tetris/tree/master/src/main/resources/META-INF/native-image)

**Comment by Hilal-Anwar** [comment]
> Could you please share a reproducer and will take a look into it

Thanks for your response.
My project link[]( https://github.com/Hilal-Anwar/Tetris)
Native image [](https://github.com/Hilal-Anwar/Tetris/tree/master/target)
Config file generated using Tracing Agent [`](https://github.com/Hilal-Anwar/Tetris/tree/master/src/main/resources/META-INF/native-image)

**Comment by Hilal-Anwar** [comment]
> > Could you please share a reproducer and will take a look into it
> 
> Thanks for your response. My project https://github.com/Hilal-Anwar/Tetris Native image https://github.com/Hilal-Anwar/Tetris/tree/master/target Config file generated using Tracing Agent https://github.com/Hilal-Anwar/Tetris/tree/master/src/main/resources/META-INF/native-image Build the project using mvn clean compile assembly:single

Can any one please help me

**Comment by Hilal-Anwar** [comment]
> Could you please share a reproducer and will take a look into it

I was finally able to solve the problem using javafx media library( javafx.scene.media.AudioClip ) as an external dependency.
Sound effects are now being played from native image.

https://user-images.githubusercontent.com/50636048/228388082-0e8577e6-47f3-45b4-95c3-b01076421c06.mp4

**Comment by Hilal-Anwar** [comment]
> @oubidar-Abderrahim I don't agree that this is the right solution. A similar thing happens if you need the fontmanager sutff. The proper fix would be that native-image embeds the default resource from `JAVA_HOME/conf/` into the image (if the code requiring it is reachable) so there is no longer a dependency on the java.home property in the created native-image. An override of the sound properties would still be possible by (specifically in this case) providing the `javax.sound.config.file` property to the native-image.

Thank for this explanation
But I was able to fix it using javafx library.
I was finally able to solve the problem using javafx media library( javafx.scene.media.AudioClip ) as an external dependency.
Sound effects are now being played from native image.

https://user-images.githubusercontent.com/50636048/228388082-0e8577e6-47f3-45b4-95c3-b01076421c06.mp4
