### ISSUE TITLE
Running graalvm java17 aarch64 darwin fails

### ISSUE THREAD

**Issue by pkriens** [oracle/graal#5824]
**Describe GraalVM and your environment :**
 -  23.0.0
 - CE 
 - Java 17
 - macOS Monterey
 - aarch64
 - The output of `java -Xinternalversion`:
```
can't run java
```

**Have you verified this issue still happens when using the latest snapshot?**
yes. Tried it with the latest (Java 19) and this Java 17. Same result. I've also used the x86/amd64 version and that works well.

**Describe the issue**
Commands like gu & java crash. I get a dialog with "“graalvm-ce-java17-23.0.0-dev” is damaged and can’t be opened.".
![image](https://user-images.githubusercontent.com/200494/214369781-8eb1b98c-7561-4210-83de-ffb5ec1c3663.png)

```
$ /Library/Java/JavaVirtualMachines/graalvm-ce-java17-23.0.0-dev/Contents/Home/bin/gu 
Killed: 9
$ file  /Library/Java/JavaVirtualMachines/graalvm-ce-java17-23.0.0-dev/Contents/Home/bin/gu 
/Library/Java/JavaVirtualMachines/graalvm-ce-java17-23.0.0-dev/Contents/Home/bin/gu: Mach-O 64-bit executable arm64
$ trace -v /Library/Java/JavaVirtualMachines/graalvm-ce-java17-23.0.0-dev/Contents/Home/bin/gu
Adding default code file /usr/share/misc/trace.codes. Use '-N' to skip this.
Parsed 2981 codes in /usr/share/misc/trace.codes
[     0] 0x 1020000  KTrap_DivideError
[  2980] 0xffbebdcc MSG_clock_alarm_reply

Sorted 2981 codes in /usr/share/misc/trace.codes
lowbound  [     0]: 0x 1020000 KTrap_DivideError
highbound [  2980]: 0xffbebdcc MSG_clock_alarm_reply

Adding code file /Library/Java/JavaVirtualMachines/graalvm-ce-java17-23.0.0-dev/Contents/Home/bin/gu 
Error: while parsing line 1, skip
Error: while parsing line 3, skip
Error: while parsing line 5, skip
....
```

**Comment by fniephaus** [comment]
Sanity check: did you remove the quarantine flag? https://github.com/graalvm/homebrew-tap#macos-catalina-specifics

**Comment by pkriens** [comment]
Nope. Missed that :-) Thanks.
