### ISSUE TITLE
Build native image with okhttp3, Java 17 amd GraalVM 22.3.x fails

### ISSUE THREAD

**Issue by ddobrin** [oracle/graal#5864]
**Env**: Apple M1, GraalVM 22.3, Java 17
openjdk version "17.0.5" 2022-10-18
OpenJDK Runtime Environment GraalVM CE 22.3.0 (build 17.0.5+8-jvmci-22.3-b08)
OpenJDK 64-Bit Server VM GraalVM CE 22.3.0 (build 17.0.5+8-jvmci-22.3-b08, mixed mode, sharing)

1. Clone okhttp3: git@github.com:square/okhttp.git
2. Failure occurs with Java 11 and 17. For building with Java 17, update the build.gradle.kts file and set the JavaLanguageVersion
3. Used okhttp3 version 5 (unreleased) by setting (build.gradle.kts)
  group = "com.squareup.okhttp3"
  version = "5.0.0-SNAPSHOT" or "5.0.0-alpha.11"

4. Build with ./gradlew okcurl:nativeImage
5. Failure:
...
========================================================================================================================
GraalVM Native Image: Generating 'okcurl' (executable)...
========================================================================================================================
Warning: Feature class okhttp3.internal.graal.OkHttpFeature is annotated with the deprecated annotation @AutomaticFeature. Support for this annotation will be removed in a future version of GraalVM. Applications should register a feature using the option --features=okhttp3.internal.graal.OkHttpFeature
[1/7] Initializing...                                                                                   (12.2s @ 0.22GB)
 Version info: 'GraalVM 22.3.0 Java 11 CE'
 Java version info: '11.0.17+8-jvmci-22.3-b08'
 C compiler: cc (apple, x86_64, 14.0.0)
 Garbage collector: Serial GC
 1 user-specific feature(s)
 - okhttp3.internal.graal.OkHttpFeature

Fatal error: java.lang.IllegalAccessError: class okhttp3.internal.graal.OkHttpFeature (in unnamed module @0x45cd7bc5) cannot access class com.oracle.svm.core.configure.ResourcesRegistry (in module org.graalvm.nativeimage.builder) because module org.graalvm.nativeimage.builder does not export com.oracle.svm.core.configure to unnamed module @0x45cd7bc5
------------------------------------------------------------------------------------------------------------------------
        at okhttp3.internal.graal.OkHttpFeature.beforeAnalysis(OkHttpFeature.kt)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.lambda$runPointsToAnalysis$9(NativeImageGenerator.java:736)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:85)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:736)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:578)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:535)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:403)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:580)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:128)
                         0.5s (3.5% of total time) in 9 GCs | Peak RSS: 0.86GB | CPU load: 1.80
========================================================================================================================

**Comment by SergejIsbrecht** [comment]
See https://github.com/square/okhttp/issues/7403

```
 !  ~/D/G/okhttp    export USE_NATIVE_IMAGE_JAVA_PLATFORM_MODULE_SYSTEM=false                                                        5.9m  So 05 Feb 2023 13:46:06 CET
 ~/D/G/okhttp    ./gradlew okcurl:nativeImage --no-daemon  
```

Seems to work

```
> Task :okcurl:nativeImage
========================================================================================================================
GraalVM Native Image: Generating 'okcurl' (executable)...
========================================================================================================================
Warning: Feature class okhttp3.internal.graal.OkHttpFeature is annotated with the deprecated annotation @AutomaticFeature. Support for this annotation will be removed in a future version of GraalVM. Applications should register a feature using the option --features=okhttp3.internal.graal.OkHttpFeature
[1/7] Initializing...                                                                                    (5.8s @ 0.24GB)
 Version info: 'GraalVM 22.3.0 Java 11 CE'
 Java version info: '11.0.17+8-jvmci-22.3-b08'
 C compiler: gcc (linux, x86_64, 12.2.0)
 Garbage collector: Serial GC
 1 user-specific feature(s)
 - okhttp3.internal.graal.OkHttpFeature
[2/7] Performing analysis...  [**********]                                                              (26.7s @ 2.23GB)
   6,214 (85.39%) of  7,277 classes reachable
   8,861 (58.33%) of 15,190 fields reachable
  28,106 (51.41%) of 54,665 methods reachable
     309 classes,     7 fields, and   863 methods registered for reflection
      68 classes,    87 fields, and    56 methods registered for JNI access
       5 native libraries: dl, pthread, rt, stdc++, z
[3/7] Building universe...                                                                               (4.3s @ 1.09GB)
[4/7] Parsing methods...      [**]                                                                       (4.7s @ 3.12GB)
[5/7] Inlining methods...     [***]                                                                      (4.4s @ 4.15GB)
[6/7] Compiling methods...    [*******]                                                                 (50.9s @ 3.31GB)
[7/7] Creating image...                                                                                 (10.6s @ 0.66GB)
  11.73MB (36.39%) for code area:    17,652 compilation units
  19.25MB (59.75%) for image heap:  187,137 objects and 7 resources
   1.25MB ( 3.87%) for other data
  32.23MB in total
------------------------------------------------------------------------------------------------------------------------
Top 10 packages in code area:                               Top 10 object types in image heap:
   1.40MB sun.security.ssl                                     4.39MB char[]
 827.51KB java.util                                            2.54MB byte[] for code metadata
 658.36KB com.sun.crypto.provider                              2.15MB byte[] for java.lang.String
 469.49KB sun.security.x509                                    1.73MB java.lang.String
 354.25KB java.lang                                            1.70MB byte[] for general heap data
 312.55KB java.util.concurrent                                 1.43MB java.lang.Class
 301.13KB java.io                                            582.56KB com.oracle.svm.core.hub.DynamicHubCompanion
 299.47KB java.net                                           404.91KB java.util.HashMap$Node
 274.17KB sun.security.provider.certpath                     387.76KB byte[] for reflection metadata
 264.78KB sun.security.provider                              339.25KB java.lang.String[]
   6.52MB for 215 more packages                                2.77MB for 1711 more object types
------------------------------------------------------------------------------------------------------------------------
                        3.9s (3.4% of total time) in 24 GCs | Peak RSS: 4.95GB | CPU load: 3.64
------------------------------------------------------------------------------------------------------------------------
Produced artifacts:
 /home/sergej/Development/GitHub/okhttp/okcurl/build/graal/okcurl (executable)
 /home/sergej/Development/GitHub/okhttp/okcurl/build/graal/okcurl.build_artifacts.txt (txt)
========================================================================================================================
Finished generating 'okcurl' in 1m 55s.
native image available at build/graal/okcurl (33 MB)

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.6/userguide/command_line_interface.html#sec:command_line_warnings

Execution optimizations have been disabled for 2 invalid unit(s) of work during this build to ensure correctness.
Please consult deprecation warnings for more details.

BUILD SUCCESSFUL in 2m 12s
21 actionable tasks: 5 executed, 16 up-to-date
```

To me it seems it is an Java modules error. The features tries to access something, which it shouldn't.

```
public final class okhttp3.internal.graal.OkHttpFeature implements org.graalvm.nativeimage.hosted.Feature
  minor version: 0
  major version: 52 // Java8
```

I would recommend updating to Java11 or use a public API to register Resources.
```
@AutomaticFeature
class OkHttpFeature : Feature {
  override fun beforeAnalysis(access: Feature.BeforeAnalysisAccess?) {
    val resourcesRegistry = ImageSingletons.lookup(ResourcesRegistry::class.java)

    resourcesRegistry.addResources(
      "\\Qokhttp3/internal/publicsuffix/PublicSuffixDatabase.gz\\E"
    )
  }
}
```

**Comment by fniephaus** [comment]
I believe this is a problem in the support for GraalVM Native Image in the OkHttp client. I left a comment with recommendations at https://github.com/square/okhttp/issues/7403#issuecomment-1419521569. I'm closing this ticket as it cannot be fixed on our side.
