### ISSUE TITLE
ArrayReadNodeGen implementation

### ISSUE THREAD

**Issue by VegetableDog118** [oracle/graal#5869]
Hi when I try to run the Truffle Libray example provided by tutorials, 
[https://github.com/oracle/graal/blob/master/truffle/src/com.oracle.truffle.api.library.test/src/com/oracle/truffle/api/library/test/examples/ArrayStrategy3.java](url)
import com.oracle.truffle.api.library.test.examples.ArrayStrategy3Factory.ArrayReadNodeGen;
This class is not found in the directory. I really need this class to run the code. Thanks

**Comment by mukel** [comment]
This class is generated by the Truffle annotation processor, when you (javac) compile your code you must include Truffle annotation processor; how to do that depends on your build system, but you can specify annotation processors manually to javac.
Here's some information about the Truffle DSL: https://www.endoflineblog.com/graal-truffle-tutorial-part-3-specializations-with-truffle-dsl-typesystem

**Comment by VegetableDog118** [comment]
Thanks for your help. All the best!

**Comment by VegetableDog118** [comment]
> when you (javac) compile your code you must include the Truffle annotation processor

Hi. Thanks for your explanation. However, I have not found any relevant doc about adding the Truffle annotation processor to javac. Is it possible that you share any relevant resources doc or the command. Thanks.
