### ISSUE TITLE
How to build GraalVM from source

### ISSUE THREAD

**Issue by TisonKun** [oracle/graal#588]
as title, maybe worth a paragraph in README

**Comment by neomatrix369** [comment]
@TisonKun Have a look at the scripts at https://github.com/neomatrix369/awesome-graal/tree/master/build/x86_64/linux_macos, they have been written based on the docs from the graal repo  and other repos, with some help from the GraalVM

**Comment by ansalond** [comment]
Hello @TisonKun, please check the GraalVM build instructions in the [README](https://github.com/oracle/graal/blob/master/vm/README.md) of the `graal/vm` suite, which we recently updated.
Here is how to build the latest GraalVM CE base image:
- set the `JAVA_HOME` environment variable to point to the latest [JVMCI-enabled JDK8](https://github.com/graalvm/openjdk8-jvmci-builder/releases)
- `cd graal/vm`
- `git checkout vm-1.0.0-rc5`
- if you already checked out the `graaljs` or the `sulong` repositories: `mx --env ce sforceimports`, else skip this step
- `mx --env ce build`
Please let us know if you have problems.

**Comment by ansalond** [comment]
I forgot to mention that before anything else you need to:
  - create a new directory
  - clone the [Graal](https://github.com/oracle/graal) and the [mx](https://github.com/graalvm/mx) repositories inside of it
  - add the root dir of the `mx` repository to your `PATH`

**Comment by neomatrix369** [comment]
Thanks @ansalond I'll update my scripts with the update

**Comment by TisonKun** [comment]
Here is my process. 

Environment:
```
$ uname -a
Darwin chenzilis-MacBook-Pro.local 17.7.0 Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/RELEASE_X86_64 x86_64
```

- Checkout sources

```
polyglot $ git clone https://github.com/oracle/graal.git
polyglot $ git clone https://github.com/graalvm/mx.git
polyglot $ export PATH=$PATH:$(pwd)/mx
polyglot $ cd graal/vm
vm $ git checkout vm-1.0.0-rc5 
```

- Download proper JVMCI ( for me, it is "labsjdk-8u172-jvmci-0.47-fastdebug-darwin-amd64.tar.gz" ) and set `JAVA_HOME` points to it. ( on macOS, `path/to/jvmci/Contents/Home/` )

- mx build

``
vm $ mx --env ce build
``

ERROR:

meet

```
opt -o bin/abort.bc bin/abort.noopt.bc -mem2reg -globalopt -simplifycfg -constprop -instcombine -dse -loop-simplify -reassociate -licm -gvn
make: opt: No such file or directory
opt -o bin/assert.bc bin/assert.noopt.bc -mem2reg -globalopt -simplifycfg -constprop -instcombine -dse -loop-simplify -reassociate -licm -gvn
make: opt: No such file or directory
make: *** [bin/abort.bc] Error 1
make: *** Waiting for unfinished jobs....
make: *** [bin/assert.bc] Error 1
rm bin/qsort.noopt.bc bin/clock.noopt.bc bin/pthreads.noopt.bc bin/cxa_virtual.noopt.bc bin/abort_message.noopt.bc bin/memcpy.noopt.bc bin/exit.noopt.bc bin/string.noopt.bc bin/fork.noopt.bc bin/cxa_exception.noopt.bc bin/stdlib_exception.noopt.bc bin/assert.noopt.bc bin/cxa_default_handlers.noopt.bc bin/stdlib_new_delete.noopt.bc bin/setjmp.noopt.bc bin/crt0.noopt.bc bin/cxa_handlers.noopt.bc bin/abort.noopt.bc bin/exec.noopt.bc bin/sulong_dispose_context.noopt.bc bin/clone.noopt.bc bin/stdlib_typeinfo.noopt.bc bin/private_typeinfo.noopt.bc bin/stat.noopt.bc bin/cxa_exception_storage.noopt.bc bin/stdlib_stdexcept.noopt.bc bin/builtin.noopt.bc bin/complex.noopt.bc

Building com.oracle.truffle.llvm.libraries.bitcode with GNU Make failed
1 build tasks failed
```

**Comment by TisonKun** [comment]
cc @ansalond Now I can build GraalVM by myself, so I feel free to close this issue.
But I would perfect to mention how to meet this process somewhere our documentation. Thus I leave the decision when to close this issue to you (or someone who assigned to this).

**Comment by TisonKun** [comment]
close but still looking forward to mention this process somewhere, like README or BUILDING

**Comment by ansalond** [comment]
Hi @TisonKun, the build instructions are now described in the README file of the `graal/vm` suite:
https://github.com/oracle/graal/blob/master/vm/README.md
We should probably add a section about the build-time dependencies of GraalVM CE. Thanks for your feedback!

**Comment by AugustNagro** [comment]
Please add that `llvm` is a build requirement in the readme (at least for mac OS). The mx stacktrace is long and easy to miss `Building com.oracle.truffle.llvm.libraries.bitcode with GNU Make failed`

**Comment by TisonKun** [comment]
@AugustNagro you're right. I follow the instruction and meet it as mentioned above. +1 for documenting this dependency.

**Comment by ansalond** [comment]
I added a short list of the build dependencies of GraalVM CE to the [README](https://github.com/oracle/graal/blob/master/vm/README.md) of the `vm` suite.
Please feel free to reopen this issue or create a new one if you have more suggestions. Thanks!

**Comment by devosalain** [comment]
What about freebsd ?
