### ISSUE TITLE
how to Access strings from Java -> C++ code 

### ISSUE THREAD

**Issue by preetnitkkr** [oracle/graal#590]
Hi, 

I want to pass strings from Java code to C/C++ code.
What i have found from polyglot.h is the API:
` uint64_t polyglot_as_string(const void *value, char *buffer, uint64_t bufsize, const char *charset); ` 

which needs to be called from c/cpp code. But using this, i am getting the below error:
```
Exception in thread "main" Can not read member '0'.
	at <llvm> func(strings.c:8:229)
	at org.graalvm.polyglot.Value.execute(Value.java:312)
	at simple.PassString.main(PassString.java:30)

```

**[1]** Could someone please help me in fixing this ? Below are the c and java file code:

// strings.c
```
#include <polyglot.h>
#include <stdio.h>
void func(void *input, char *buffer, uint64_t bufsize, const char *charset)  
{ 
     printf("inside cpp , size of input string is = %lu", polyglot_get_string_size(input));  // this works correctly
     uint64_t bytes = polyglot_as_string(input, buffer, bufsize, charset);  // this gives error
     printf("inside c's func() , input = %s", buffer);  
}
```
// PassString.java
```
import java.io.*;
import java.nio.charset.Charset;
import org.graalvm.polyglot.*;
public class PassString {
	public static void main(String[] args) {
		try (Context context = Context.newBuilder().allowNativeAccess(true).build()) {
			Charset charset = Charset.forName("ISO-8859-1");
			final Value library;
			try {
				library = context.eval(Source.newBuilder("llvm", new File("strings.bc")).build());
			} catch (IOException e) {
				e.printStackTrace();
				return;
			}
			final Value print = library.getMember("func");
			String str = "string from java side";
			byte[] bytes = str.getBytes(charset);
			String parameter = new String(bytes, charset);
			int length = str.length();
			char[] buffer = new char[length+1];
			print.execute(context.asValue(parameter), buffer, length, charset );  // raises above mentioned exception : Exception in thread "main" Can not read member '0'.
			System.out.println("\n=== end of main program ===");
		}
	}
}

```

Also, per polyglot header file, 
```
Polyglot string values can be cast to `char *`, but this will only work
reliably for strings that contain only LATIN-1 characters and no embedded
zero characters. The reverse is not true, exported `char *` values will not
be seen by other languages as polyglot strings.
```
**[2]** Just to confirm, does it mean that we cannot pass UTF-8 strings from Java->C boundaries ? 

Thanks,
Preet

**Comment by preetnitkkr** [comment]
Hi,
I just found the solution for [1] - i was passing the a newly allocated buffer from java and directly accessing it on Cpp side which is wrong. Now i am handling it correctly.

Could someone please answer [2] ? thanks.

**Comment by rschatz** [comment]
Re [1]: Correct, you have to use a C/C++ array as buffer, not a Java array.

> Also, per polyglot header file,
> 
> ```
> Polyglot string values can be cast to `char *`, but this will only work
> reliably for strings that contain only LATIN-1 characters and no embedded
> zero characters. The reverse is not true, exported `char *` values will not
> be seen by other languages as polyglot strings.
> ```
> 
> [2] Just to confirm, does it mean that we cannot pass UTF-8 strings from Java->C boundaries ?

This paragraph refers to directly typecasting a `java.lang.String` (or similar) to a C `char *`, without using the `polyglot_*_string` functions. This is a convenience feature, but with the limitation of only being able to pass `ASCII` or `LATIN-1` strings.

With `polyglot_as_string`, you can use any charset supported by Java, including `UTF-8`.

**Comment by preetnitkkr** [comment]
Thanks for the explanation, Roland. :+1:
