### ISSUE TITLE
java: cannot access jdk.vm.ci.code.ValueKindFactory on ARM64

### ISSUE THREAD

**Issue by fexolm** [oracle/graal#5905]
**Describe the issue**
I'm trying to run testIntegerTest from intellij idea, but it does not build with the following error:
```
java: cannot access jdk.vm.ci.code.ValueKindFactory
  class file for jdk.vm.ci.code.ValueKindFactory not found
```

**Steps to reproduce the issue**
Please include both build steps as well as run steps
1. clone graal master
2. cd graal/compiler
3. export JVMCI_VERSION_CHECK=warn // I've also tried to build with JDK 17, with the same error
4. export JAVA_HOME=labsjdk-ce-11.0.18-jvmci-22.3-b12
5. mx build
6. mx intellijinit
7. run testIntegerTest from intellij idea

**Describe GraalVM and your environment:**
 - GraalVM version: master
 - JDK major version: 11/17
 - OS: Ubuntu 22.04
 - Architecture: ARM64

**Comment by oubidar-Abderrahim** [comment]
Hi, thank you for reporting this, we'll take a look into this shortly

**Comment by oubidar-Abderrahim** [comment]
Hi, any updates?
