### ISSUE TITLE
Standardize folder structure of Mac OSX CE binary

### ISSUE THREAD

**Issue by marc0der** [oracle/graal#591]
The new GraalVM packages are great, but have a non-standard internal folder structure as far as SDK binaries go. As a result, we are not able to host this new binary on SDKMAN right now.

The binary does not follow the same structure as the Linux binary, but instead contains top level _Content/Home/_ folders instead of the expected _graalvm-ce-1.0.0-rc5/_.

If this can be corrected, it would make distribution of CE much easier and make many users very happy :smile:

**Comment by dougxc** [comment]
This top level `Contents/Home` folder is the standard layout for the JDK on macOS and is thus expected by a number of tools.

**Comment by dougxc** [comment]
hi @marc0der , I understand now what you are asking for. However, we are following the OpenJDK standard. For example, the macOS tar.gz available at http://jdk.java.net/10/ has the following structure:
```
> tar tzf ~/Downloads/openjdk-10.0.2_osx-x64_bin.tar.gz | head
./
./jdk-10.0.2.jdk/
./jdk-10.0.2.jdk/Contents/
./jdk-10.0.2.jdk/Contents/Home/
./jdk-10.0.2.jdk/Contents/Info.plist
./jdk-10.0.2.jdk/Contents/MacOS/
./jdk-10.0.2.jdk/Contents/MacOS/libjli.dylib
./jdk-10.0.2.jdk/Contents/Home/bin/
./jdk-10.0.2.jdk/Contents/Home/conf/
./jdk-10.0.2.jdk/Contents/Home/include/
```
We should only deviate from this structure if there's a very good reason. How much work is it to adjust SDKMAN to accomodate this structure?

**Comment by marc0der** [comment]
Thanks for the explanation @dougxc.

I've done some further digging and can confirm that you are right, this is how Oracle currently bundles their OpenJDK tarballs. I also went and did some digging of my own, only to find that we have a [custom hook](https://github.com/sdkman/sdkman-hooks/blob/master/app/views/java_post_openjdk_osx.scala.txt#L19) to deal with this scenario already.

I've cut over our backend service to use this OpenJDK hook for the GraalVM OSX binary and it seems to be working just fine. Thanks for helping and advising!

**Comment by dougxc** [comment]
You're welcome - glad this was an easy fix!

**Comment by breun** [comment]
The GraalVM 1.0.0-rc9 build for macOS doesn't have an `Info.plist` file yet, which causes GraalVM to not be recognised as a JDK by macOS Java tools. I created https://github.com/oracle/graal/issues/801 for this issue.
