### ISSUE TITLE
GraalVM native-image kerberos authentication issue

### ISSUE THREAD

**Issue by louis2845** [oracle/graal#5941]
GraalVM and environment:

OS: Linux RHEL 8
GraalVM version 22.3.1 EE
JDK: 17

Issue:
The Java application code for Kerberos authentication works fine in JVM, but fails to get GSSCredential in native image. 

Issue seems identical to https://github.com/oracle/graal/issues/2745 but the issue is still persisting even though it is supposed to have been solved in 22.0.0

Our codebase eventually calls:

```
Subject.doAs(subject, new PrivilegedExceptionAction<GSSCredential>() {
    @Override
    public GSSCredential run() throws Exception
    {
        GSSManager manager = GSSManager.getInstance();
        return manager.createCredential(GSSCredential.INITIATE_ONLY);

    }
});
```
This call fails to get a credential in the native-image but works fine in the JVM

**Comment by oubidar-Abderrahim** [comment]
Hi, Thank you for reaching out about this issue, could you please share a reproducer example, we can use, to illustrate this bug?

**Comment by louis2845** [comment]
The code within #2745 should provide all you need. 

kinit -f (either username password or provide a keytab and principal - if you can't kinit then you won't be able to reproduce the issue)
javac Sample.java
native-image -H:IncludeResourceBundles=sun.security.util.Resources -H:+IncludeAllLocales --no-fallback Sample
./sample

```
import javax.security.auth.Subject;
import javax.security.auth.login.AppConfigurationEntry;
import javax.security.auth.login.Configuration;
import javax.security.auth.login.LoginContext;
import javax.security.auth.login.LoginException;
import java.security.*;
import java.util.HashMap;
import java.util.Map;

public class Sample {

    public static void main(String[] args) throws PrivilegedActionException, LoginException {
        kerberosTest();
    }

    public static void kerberosTest() throws PrivilegedActionException, LoginException {

        class LoginConfiguration extends Configuration {
            private AppConfigurationEntry entry;

            private LoginConfiguration(Map<String, String> options) {
                entry = new AppConfigurationEntry(
                        "com.sun.security.auth.module.Krb5LoginModule",
                        AppConfigurationEntry.LoginModuleControlFlag.REQUIRED,
                        new HashMap<>(options)
                );
            }

            @Override
            public AppConfigurationEntry[] getAppConfigurationEntry(String name) {
                return new AppConfigurationEntry[]{entry};
            }
        }

        //Kerberos login and get subject
        Subject subject = null;
        Map<String, String> options = new HashMap<>();
        options.put("doNotPrompt", "true");
        options.put("useTicketCache", "true");
        Configuration configuration = new LoginConfiguration(options);
        LoginContext loginContext = new LoginContext("", null, null, configuration);
        loginContext.login();
        subject = loginContext.getSubject();


        Subject.doAs(subject, new PrivilegedExceptionAction<Boolean>() {
            @Override
            public Boolean run() throws Exception {
                final AccessControlContext acc = AccessController.getContext();

                DomainCombiner dc = acc.getDomainCombiner();

                // run the code in JVM will retrieve valid dc but native image will return null for dc
                if (dc == null) {
                    System.out.println("dc is null");
                    return Boolean.FALSE;
                }
                System.out.println("dc is NOT null");

                return Boolean.TRUE;

            }
        });
    }
}
```

**Comment by louis2845** [comment]
Ok, I will try and reproduce the problem without Kerberos when I've got some free time.

**Comment by louis2845** [comment]
I'm not sure I can provide a reproducer in this instance. I'm sorry. 

However, going through the code and the stack trace:

Caused by: org.ietf.jgss.GSSException: No valid credentials provided
at java.security.jgss@17.0.6/sun.security.jgss.GSSCredentialImpl.<init>(GSSCredentialImpl.java:100)
at java.security.jgss@17.0.6/sun.security.jgss.GSSCredentialImpl.<init>(GSSCredentialImpl.java:64)
at java.security.jgss@17.0.6/sun.security.jgss.GSSManagerImpl.createCredential(GSSManagerImpl.java:129)

The code is using GSSManagerImpl which is also subject to a bug here -> #5950 . It is also using the same fields (ProviderList) from that class which seem to be causing issues in the other ticket.

Perhaps the two issues are intrinsically linked.

**Comment by oubidar-Abderrahim** [comment]
Please track this issue on #5950
