### ISSUE TITLE
SSL Handshake errors when Using Native Image Binary after uptaking Helidon 2.5.6

### ISSUE THREAD

**Issue by Sidhardha95** [oracle/graal#5951]
**Describe the issue**

Hi Team ,
We are working on Helidon SE project been using the Graal Generated native binary in our OKE deployments ..
We were on Helidon 2.5.0 and Netty version 1.1.77.Final
Last week we have up-taken Helidon 2.5.6 last week , and generated native binary using the regular process . Binary is generated successfully, but when deployed onto the cluster we are seeing Ssl Handshake timeouts

`2023-02-09 04:41:57.960+0000 |  | ::: |    event-delivery-14 | SYS | ERROR | com.oracle.cx.communications.dx4c.fabric.delivery.Main | Initialization error while starting the application. Shutting down
java.util.concurrent.CompletionException: io.helidon.common.Errors$ErrorMessagesException: FATAL: Failed to load metadata: java.util.concurrent.CompletionException: io.netty.handler.ssl.SslHandshakeTimeoutException: handshake timed out after 10000ms from https://idcs-2723cb00fe0a45a6979cdd1b959bb6f4.identity.pint.oc9qadev.com/.well-known/openid-configuration at java.util.concurrent.CompletionException: io.netty.handler.ssl.SslHandshakeTimeoutException: handshake timed out after 10000ms
        at java.base@11.0.18/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
        at java.base@11.0.18/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319)
        at java.base@11.0.18/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1081)
        at java.base@11.0.18/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
        at java.base@11.0.18/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1742)
        at java.base@11.0.18/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base@11.0.18/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base@11.0.18/java.lang.Thread.run(Thread.java:834)
        at com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:775)`

This is with Graal EE : 22.2.0.1 Java 11 EE

**Describe GraalVM and your environment:**
 - GraalVM version (latest snapshot builds can be found [here](https://github.com/graalvm/graalvm-ce-dev-builds/releases)), or commit id if built from source: **22.2.0.1 Java 11 EE**
 - JDK major version: **11**
 - OS: **OKE / K8S **
 - Architecture: **[e.g.: AMD64]**

We have tried to with Graal 23.3.1 , and saw same errors 

Slack conversation : https://gbu-core.slack.com/archives/CJAB85R1C/p1675921180228909

We have also tried to test the application direct Java jars and we see it working.

**Comment by Sidhardha95** [comment]
[native-image.zip](https://github.com/oracle/graal/files/10704597/native-image.zip)

**Comment by oubidar-Abderrahim** [comment]
Hi, It would be very useful if we can have a reproducer, a code that we can run from our side to produce this issue.

Also, please add `--diagnostics-mode` flag to the native-image build command, and share the reports folder that will be generated by the build process (please use GraalVM 22.3.1 for this)

**Comment by Sidhardha95** [comment]
Hi @oubidar-Abderrahim , I have observed below Warning log messages while building with Helidon 2.5.6 and NI 22.3.1

```
[WARNING] Warning: Could not register io.netty.handler.codec.compression.Lz4FrameDecoder: queryAllPublicMethods for reflection. Reason: java.lang.NoClassDefFoundError: net/jpountz/lz4/LZ4Exception.
2548[WARNING] Warning: Could not register io.netty.handler.codec.compression.Lz4FrameEncoder: queryAllPublicMethods for reflection. Reason: java.lang.NoClassDefFoundError: net/jpountz/lz4/LZ4Exception.
2549[WARNING] Warning: Could not register io.netty.handler.codec.marshalling.CompatibleMarshallingDecoder: queryAllPublicMethods for reflection. Reason: java.lang.NoClassDefFoundError: org/jboss/marshalling/ByteInput.
2550[WARNING] Warning: Could not register io.netty.handler.codec.marshalling.CompatibleMarshallingEncoder: queryAllPublicMethods for reflection. Reason: java.lang.NoClassDefFoundError: org/jboss/marshalling/ByteOutput.
2551[WARNING] Warning: Could not register io.netty.handler.codec.marshalling.MarshallingDecoder: queryAllPublicMethods for reflection. Reason: java.lang.NoClassDefFoundError: org/jboss/marshalling/ByteInput.
2552[WARNING] Warning: Could not register io.netty.handler.codec.marshalling.MarshallingEncoder: queryAllPublicMethods for reflection. Reason: java.lang.NoClassDefFoundError: org/jboss/marshalling/ByteOutput.
2553[WARNING] Warning: Could not register io.netty.handler.codec.protobuf.ProtobufDecoder: queryAllPublicMethods for reflection. Reason: java.lang.NoClassDefFoundError: com/google/protobuf/ExtensionRegistryLite.
2554[WARNING] Warning: Could not register io.netty.handler.codec.compression.Lz4FrameDecoder: queryAllPublicMethods for reflection. Reason: java.lang.NoClassDefFoundError: net/jpountz/lz4/LZ4Exception.
2555[WARNING] Warning: Could not register io.netty.handler.codec.compression.Lz4FrameEncoder: queryAllPublicMethods for reflection. Reason: java.lang.NoClassDefFoundError: net/jpountz/lz4/LZ4Exception.
2556[WARNING] Warning: Could not register io.netty.handler.codec.marshalling.CompatibleMarshallingDecoder: queryAllPublicMethods for reflection. Reason: java.lang.NoClassDefFoundError: org/jboss/marshalling/ByteInput.
2557[WARNING] Warning: Could not register io.netty.handler.codec.marshalling.CompatibleMarshallingEncoder: queryAllPublicMethods for reflection. Reason: java.lang.NoClassDefFoundError: org/jboss/marshalling/ByteOutput.
2558[WARNING] Warning: Could not register io.netty.handler.codec.marshalling.MarshallingDecoder: queryAllPublicMethods for reflection. Reason: java.lang.NoClassDefFoundError: org/jboss/marshalling/ByteInput.
2559[WARNING] Warning: Could not register io.netty.handler.codec.marshalling.MarshallingEncoder: queryAllPublicMethods for reflection. Reason: java.lang.NoClassDefFoundError: org/jboss/marshalling/ByteOutput.
2560[WARNING] Warning: Could not register io.netty.handler.codec.protobuf.ProtobufDecoder: queryAllPublicMethods for reflection. Reason: java.lang.NoClassDefFoundError: com/google/protobuf/ExtensionRegistryLite.
```

**Comment by Sidhardha95** [comment]
[reports.zip](https://github.com/oracle/graal/files/10722281/reports.zip)
Attaching native image diagnostics generated using 23.3.1

**Comment by Sidhardha95** [comment]
[helidon-quickstart-se.zip](https://github.com/oracle/graal/files/10732997/helidon-quickstart-se.zip)

This is a simple Helidon Application with security enabled. We have generated a binary using this project . And generated a Docker image using the Generated Binary .  

Deployed the image to a OKE cluster, and upon making the call we are seeing the failure.

**Comment by Sidhardha95** [comment]
Sample Call : http://localhost:8080/greet - GET

Upon making a call, we saw the IDCS Ssl Handshake errors.

**Comment by oubidar-Abderrahim** [comment]
We can continue the discussion on the internal ticket GRAALVM-4305
