### ISSUE TITLE
[LLVM] Ruby native extension problem with struct resetting

### ISSUE THREAD

**Issue by nirvdrum** [oracle/graal#5955]
**Describe GraalVM and your environment :**
 - GraalVM version or commit id if built from source: **23.0.0-dev (e5310bf91d65cf8871f6adb90656f671cfb27372)**
 - CE or EE: **CE**
 - JDK version: **JDK 20**
 - OS and OS Version: **macOS 13.2**
 - Architecture: **arm64**
 - The output of `java -Xinternalversion`:
```
OpenJDK 64-Bit Server VM (20+30-jvmci-23.0-b06) for bsd-aarch64 JRE (20+30-jvmci-23.0-b06), built on 2023-01-22T22:21:50Z by "graal1" with clang Apple LLVM 12.0.0 (clang-1200.0.32.29)
```

**Have you verified this issue still happens when using the latest snapshot?**

Yes.

**Describe the issue**

I've been trying to debug a logic error with a Ruby native extension. It occurs in a library called _commonmarker_ that is used to render CommonMark (Markdown-derivative) to various formats. The problem I'm seeing is a struct ends up uninitialized when it should be populated. Unfortunately, when I step through the code with a debugger or `printf` the struct members, they're populated. The code in question looks like:

```c
  if (ref != NULL) { // found
    url = chunk_clone(subj->mem, &ref->url);
    title = chunk_clone(subj->mem, &ref->title);
    goto match;
  } else {
    goto noMatch;
  }
```

The `ref` is not `NULL` and both the `url` and `title` are initialized. `chun_clone` returns a struct value. If I read the `url` before the `goto`, I can see the struct is populated correctly. If I don't read it here, when I go to the _match_ label, the struct is uninitialized. In this particular profile, the _noMatch_ block is never run. However, the _noMatch_ block does an early `return`. If I comment out the `return`, then the `url` struct retains its values. This was tricky to debug because if I read the `url` fields before the `goto`, they all look correctly (and carry forward correctly through the _match_ block).

Unfortunately, I haven't been able to reproduce in a smaller example, so these are the steps for reproducing in the original code. I'm assuming that you have a version of TruffleRuby built already and it's on the `$PATH`. I'm currently running a dev build so I have the latest Sulong, but the behavior appears to be the same with the 22.3.0 release.

```bash
git clone --branch v0.23.8 --depth 1 https://github.com/gjtorikian/commonmarker.git
cd commonmarker
bundle install
bundle exec rake compile && bundle exec rake test TEST="test/test_doc.rb" TESTOPTS="-v --name=test_get_url"
```

You should see the test fail. If you apply either of these patches, the test will succeed:

```patch
diff --git a/ext/commonmarker/inlines.c b/ext/commonmarker/inlines.c
index 30f2c17..b7b21ef 100644
--- a/ext/commonmarker/inlines.c
+++ b/ext/commonmarker/inlines.c
@@ -1228,6 +1228,7 @@ static cmark_node *handle_close_bracket(cmark_parser *parser, subject *subj) {
   if (ref != NULL) { // found
     url = chunk_clone(subj->mem, &ref->url);
     title = chunk_clone(subj->mem, &ref->title);
+    printf("URL ptr: %p\n", &url);
     goto match;
   } else {
     goto noMatch;
```

```patch
diff --git a/ext/commonmarker/inlines.c b/ext/commonmarker/inlines.c
index 30f2c17..a93e121 100644
--- a/ext/commonmarker/inlines.c
+++ b/ext/commonmarker/inlines.c
@@ -1228,6 +1228,7 @@ static cmark_node *handle_close_bracket(cmark_parser *parser, subject *subj) {
   if (ref != NULL) { // found
     url = chunk_clone(subj->mem, &ref->url);
     title = chunk_clone(subj->mem, &ref->title);
+    printf("\nURL details -- allocated: %d; length: %d; value: %s\n", url.alloc, url.len, url.data);
     goto match;
   } else {
     goto noMatch;
```

As you can see, either patch isn't doing anything special beyond a read. I provided both just in case accessing a field might result in different semantics than just referencing the address.

**How to compile the LLVM bitcode that causes the problem**

I'm using the toolchain provided by GraalVM and using TruffleRuby's built-in mechanism for compiling native extensions.

**Comment by nirvdrum** [comment]
@rschatz I can pair program with you on this if it'd be helpful.

**Comment by rschatz** [comment]
Found it. It's actually a missing copy in the by-value return. It almost always works, it only breaks if the space on the stack is overridden by something else before the value is used. That's why the printf fixed it, it moved the code that unpacks the values to an earlier place, before whatever destroyed the values on the stack.
