### ISSUE TITLE
Support linkerd on substrateVM

### ISSUE THREAD

**Issue by wmorgan** [oracle/graal#598]
[Linkerd](https://github.com/linkerd/linkerd) is a "service mesh" proxy on the JVM, for which memory footprint and tail latency are critical concerns. Thus, we'd love to try AOT-compiling Linkerd to see just how fast and small we can make it.

Our initial experiments (linkerd/linkerd#1935) suggest that this will require some SubstrateVM changes to get Finagle working.

We've built a basic perf-testing harness here that might be useful as a starting point (currently has OpenJDK and OpenJ9):  https://github.com/linkerd/linkerd-examples/tree/master/perf-baseline/linkerd1-perf

**Comment by cstancu** [comment]
We have looked into linkerd. The blocker is allocating threads in static initializers. We are working on a solution for delaying some class initialization until runtime to avoid these kind of issues.

**Comment by spavlusieva** [comment]
hi @wmorgan , this issue has been inactive for more than 180 days. We’ll close it to focus on current issues. In case it’s still relevant, please reopen it and we’ll take another look. Thank you!
