### ISSUE TITLE
Minor typo in Reflection.md

### ISSUE THREAD

**Issue by nmcl** [oracle/graal#599]
https://github.com/oracle/graal/blob/master/substratevm/REFLECTION.md

Missing comma in the Manual Configuration son example. Should be:

{
    "name" : "java.lang.Class",
    "allDeclaredConstructors" : true,
    "allPublicConstructors" : true,
    "allDeclaredMethods" : true,
    "allPublicMethods" : true
  },

**Comment by cstancu** [comment]
Thank you! We have a PR that will fix this: https://github.com/oracle/graal/pull/512.
