### ISSUE TITLE
What is the meaning of Graph of dashboard ?

### ISSUE THREAD

**Issue by acodervic** [oracle/graal#6017]
I don't understand what the meaning of   Graph of dashboard is. When I hover the mouse in the Graph, I can see some description text.

Like :
```text 
---------------------------
[B in '*':39.2%           <---- byte arry in *( what is  *?) :39.2%
[B in 'image':39.2%  <----byte arry in *( what is  image?) :39.2%
--------------------------
"*" in image: 100%  <----*(what is *? ) in image :100% 
-------------------------
```

Please help me ! Thanks for graal team;
![DeepinScreenshot_select-area_20230217232610](https://user-images.githubusercontent.com/57204004/219696397-6267e156-490b-47f2-bbc9-fcf8532d1776.png)

**Comment by acodervic** [comment]
@fniephaus

**Comment by fniephaus** [comment]
I'm afraid I can't answer that question from the top of my head, but it's very unlikely something you can influence directly. This is unfortunately one of many UX problems of the dashboard and I hope we can improve this soon. In the meantime, please take a look at the build output, which categorizes important byte arrays.

**Comment by acodervic** [comment]
> I'm afraid I can't answer that question from the top of my head, but it's very unlikely something you can influence directly. This is unfortunately one of many UX problems of the dashboard and I hope we can improve this soon. In the meantime, please take a look at the build output, which categorizes important byte arrays.

thanks !
