### ISSUE TITLE
Disallow keyword `state` in guards

### ISSUE THREAD

**Issue by fniephaus** [oracle/graal#606]
Since `state` is a reserved keyword in Truffle's guard mechanism, it should not be possible to use it in a guard definition as this can cause serious problems. The annotation processor should either reject the `state` keyword in guard definitions or the `state` temporary variable produced by the processor should be renamed to avoid this conflict.

Here's an example:
<img width="629" alt="screen shot 2018-08-10 at 3 19 14 pm" src="https://user-images.githubusercontent.com/2368856/43959974-c925e328-9cb0-11e8-9e41-34bfd31f2417.png">

**Comment by fniephaus** [comment]
Oh, forgot to mention that the class also has a `state` field which is shadowed by the `int state` value which is also bad.

Since one can get access to the Truffle `state` this way, I wonder if there are people actually doing this. I can't think of any good reason though, maybe because there isn't :)

**Comment by boris-spas** [comment]
Tracked internally as Issue GR-20793.

**Comment by avirlrma** [comment]
Can I work on this?

**Comment by gracehop** [comment]
yes I would love the help

**Comment by chrisseaton** [comment]
@avirlrma are you still interested in fixing this?

**Comment by rhyadav** [comment]
@fniephaus i'll start working on this
