### ISSUE TITLE
PhantomReference.enqueue casues error

### ISSUE THREAD

**Issue by vlsi** [oracle/graal#607]
related issues: https://github.com/oracle/graal/issues/440 , https://github.com/pgjdbc/pgjdbc/issues/1189

Exception:

```
Unsupported method java.lang.ref.Reference.enqueue() is reachable: The declaring class of this element has been substituted, but this element is not present in the substitution class
To diagnose the issue, you can add the option -H:+ReportUnsupportedElementsAtRuntime. The unsupported element is then reported at run time when it is accessed the first time.
Trace: 
        at parsing org.postgresql.core.v3.SimpleQuery.setCleanupRef(SimpleQuery.java:290)
Call path from entry point to org.postgresql.core.v3.SimpleQuery.setCleanupRef(PhantomReference): 
        at org.postgresql.core.v3.SimpleQuery.setCleanupRef(SimpleQuery.java:288)
        at org.postgresql.core.v3.QueryExecutorImpl.registerParsedQuery(QueryExecutorImpl.java:1882)
        at org.postgresql.core.v3.QueryExecutorImpl.sendParse(QueryExecutorImpl.java:1397)
        at org.postgresql.core.v3.QueryExecutorImpl.sendOneQuery(QueryExecutorImpl.java:1762)
        at org.postgresql.core.v3.QueryExecutorImpl.sendAutomaticSavepoint(QueryExecutorImpl.java:355)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:297)
        at org.postgresql.jdbc.PgConnection.executeTransactionCommand(PgConnection.java:740)
        at org.postgresql.jdbc.PgConnection.commit(PgConnection.java:761)
        at org.postgresql.jdbc.PgConnection.setAutoCommit(PgConnection.java:720)
        at org.avaje.datasource.pool.PooledConnection.close(PooledConnection.java:490)
        at org.example.InsertMain.main(InsertMain.java:31)
        at com.oracle.svm.reflect.proxies.Proxy_1_InsertMain_main.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Method.java:498)
```

 PGJDBC uses `PhantomReference` for automatic cleanup of `java.sql.Statement`/`java.sql.ResultSet` objects.
The case there is to be able to release resources at the DB side even in case user fails to call `close()` appropriately.

However, it does manually enqueue the reference in case user calls `close` manually.

https://github.com/pgjdbc/pgjdbc/blob/08631ccdabdb8ba6d52f398e2b0b46a9cf0cafbf/pgjdbc/src/main/java/org/postgresql/core/v3/SimpleQuery.java#L287-L292

Then comes the problem:
1) GraalVM does not support `PhantomReference.enqueue` :(
2) pgjdbc can't perform DB resources cleanup at random. It need to squeeze cleanup commands at appropriate times when talking to the DB. That is "cleanup" has to be go through a queue. We use `ReferenceQueue` exactly for that, so `reference.enqueue()` is used to pass the the reference for further processing so it is picked up at appropriate time by the DB code.

Do you think there's a feasible solution to enable use of `PhantomReference.enqueue`?
Is it too hard to resolve at GraalVM side?

**Comment by vlsi** [comment]
Is it way more complicated than adding relevant `enqueue` method to https://github.com/oracle/graal/blob/b4fc71922d285ecae7459df6464a616ec6779acb/substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jdk/JavaLangRefSubstitutions.java#L121 ? (I've absolutely no idea how AOT plays with refs, etc)

**Comment by cstancu** [comment]
It looks like we substitute the `java.lang.ref.Reference` class and leave out `enqueue()`. But `enqueue()` is implemented as:
```
    public boolean enqueue() {
        return this.queue.enqueue(this);
    }
```
where `queue` is declared as `volatile ReferenceQueue<? super T> queue;`. We also substitute `java.lang.ref.ReferenceQueue` and for `enqueue()` we just use the original implementation:

```
    @KeepOriginal
    native boolean enqueue(Reference<?> r);
```
Can you try to do the same for `Reference`? That is: add 
```
    @KeepOriginal
    native boolean enqueue(Reference<?> r);
```
to `Target_java_lang_ref_Reference`. I haven't tried this yet but I think that it should work.

**Comment by vlsi** [comment]
@cstancu , ok, will try. I have built substrateVM at least once, so will check if that helps.

**Comment by Peter-B-Kessler** [comment]
My initial triage of this issue is that it would take some work to get SubstrateVM to implement `ReferenceQueue.enqueue()` and `ReferenceQueue.isEnqueued()`.  Not impossible, but difficult.  We do not have the separation between "Java code" and "the garbage collector" implied in the description of `Reference.enqueue()`.

I will add this to our list of [limitiations on References](https://github.com/oracle/graal/blob/master/substratevm/LIMITATIONS.md#weak-references).

Yes, SubstrateVM currently has only a single-threaded, stop-the-world garbage collector.  As you noted, the list of discovered references is, currently, only pushed to during a collection, though it can be popped from by multiple threads.  That would have to change, among other things.

Clearing and enqueuing a `PhantomReference` instance seems like a round-about way to invoke whatever method you are going to call when you remove the instance from the queue.  But that is the way your code is written.

**Comment by Peter-B-Kessler** [comment]
I have pushed https://github.com/oracle/graal/commit/178b40d8ea4bd43349c967de83e0a88925528e41 which implements `Reference.enqueue()` and `Reference.isEnqueued()`.  I am curious if that implementation works for you.

**Comment by ahachete** [comment]
Wow. We're crossing paths.... https://github.com/pgjdbc/pgjdbc/pull/1333 ^_^

**Comment by Peter-B-Kessler** [comment]
Well, maybe the next person will need `Reference.enqueue()`.  Thanks for provoking me into implementing it.
I'm glad to hear that we provoked you into making your code more readable by separating references found to be unreachable by the collector and references that you just wanted to clean up.  I always worry that people count on frequent collections to get them "prompt" cleanup.  Especially for things that have no correlation with heap pressure, like open files, sockets, etc.

**Comment by Sanne** [comment]
Funny thing, three of us crossed paths.  I was also working on a pgjdbc driver patch in the weekend, and yet have other needs for `Refecence.enqueue` .

Thanks to you both!

@ahachete nice to see you around! I'll see if I can still polish my other postgresql jdbc patches and get them ready for pull requests.

**Comment by ahachete** [comment]
It is indeed great to see you around too, @Sanne ! :))

@Peter-B-Kessler glad that you found the https://github.com/pgjdbc/pgjdbc/pull/1333/ approach sound. I hope PR will be merged. In any case, it's great that you implemented `enqueue()` anyway!

**Comment by Peter-B-Kessler** [comment]
I am closing this issue.  If `Reference.enqueue()` or `Reference.isEnqueued()` do not work, please re-open it.
