### ISSUE TITLE
graalpy -m ginstall install numpy success but can't import

### ISSUE THREAD

**Issue by as154** [oracle/graal#6072]
**Describe the issue**
install numpy successfully, but import numpy failed. It shows:

>Traceback (most recent call last):
  File "/home/pi/my_new_venv/lib/python3.8/site-packages/numpy-1.16.4-py3.8-linux-aarch64.egg/numpy/core/__init__.py", line 40, in <module>
    from . import multiarray
  File "/home/pi/my_new_venv/lib/python3.8/site-packages/numpy-1.16.4-py3.8-linux-aarch64.egg/numpy/core/multiarray.py", line 12, in <module>
    from . import overrides
  File "/home/pi/my_new_venv/lib/python3.8/site-packages/numpy-1.16.4-py3.8-linux-aarch64.egg/numpy/core/overrides.py", line 6, in <module>
    from numpy.core._multiarray_umath import (
ImportError: cannot load /home/pi/my_new_venv/lib/python3.8/site-packages/numpy-1.16.4-py3.8-linux-aarch64.egg/numpy/core/_multiarray_umath.graalpy-38-native-aarch64-linux.so: Unsupported Floating Point Type: f128
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pi/my_new_venv/lib/python3.8/site-packages/numpy-1.16.4-py3.8-linux-aarch64.egg/numpy/__init__.py", line 142, in <module>
    from . import core
  File "/home/pi/my_new_venv/lib/python3.8/site-packages/numpy-1.16.4-py3.8-linux-aarch64.egg/numpy/core/__init__.py", line 71, in <module>
    raise ImportError(msg)
ImportError: 
IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!
Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
Here is how to proceed:
>If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.
- If you are simply trying to use the numpy version that you have installed:
  your installation is broken - please reinstall numpy.
- If you have already reinstalled and that did not fix the problem, then:
  1. Check that you are using the Python you expect (you're using /home/pi/my_new_venv/bin/graalpy),
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy versions you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log
     Note: this error has many possible causes, so please don't comment on
     an existing issue about this - open a new one instead.
Original error was: cannot load /home/pi/my_new_venv/lib/python3.8/site-packages/numpy-1.16.4-py3.8-linux-aarch64.egg/numpy/core/_multiarray_umath.graalpy-38-native-aarch64-linux.so: Unsupported Floating Point Type: f128

**Describe GraalVM and your environment:**
 - GraalVM version : graalvm-ce-java11-linux-aarch64-22.3.0
 - JDK major version: 11
 - OS: Raspbian
 - Architecture: aarch64

**Comment by oubidar-Abderrahim** [comment]
Hi, Thank you for sharing this, could you please test v22.3.1?

**Comment by oubidar-Abderrahim** [comment]
Hi, any updates on testing 22.3.1?

**Comment by oubidar-Abderrahim** [comment]
Hi, if this issue is still happening on the latest GraalVM version, please create a new issue and we'll take a look into it. Thank you
