### ISSUE TITLE
WebAssembly GC support

### ISSUE THREAD

**Issue by linux-china** [oracle/graal#6078]
WebAssembly Garbage collection is in Phase 3 - Implementation Phase (CG + WG), and Kotlin 1.8.20 already has Wasm support.  
Please take a look at https://github.com/sdeleuze/kowasm

**Comment by oubidar-Abderrahim** [comment]
Hi, Thank you for your suggestion, we'll take a look into it shortly

**Comment by sgammon** [comment]
WASM GC is now on-by-default in Chrome/V8: https://developer.chrome.com/blog/wasmgc/

**Comment by tarsa** [comment]
Firefox 120 also supports WASM GC extension. See https://www.phoronix.com/news/Firefox-120-Available and https://www.mozilla.org/en-US/firefox/120.0beta/releasenotes/

**Comment by fniephaus** [comment]
Closing this in favor of https://github.com/oracle/graal/issues/9758, the corresponding item on the GraalWasm roadmap.
