### ISSUE TITLE
Native-image Resource Bundle references failing on 1.0 RC5

### ISSUE THREAD

**Issue by ChadKillingsworth** [oracle/graal#608]
Building closure compiler using native-image built from 9b7872c8679d84a0c19e3a70f658cdd0ad167100 works great.

Building the same binary from the 1.0 RC5 releases (both MacOS and Linux) produces null pointer exceptions when a resource build is referenced.

Working build:

 - [build log](https://travis-ci.org/ChadKillingsworth/closure-compiler-graal/jobs/414702625)
 - [build steps](https://github.com/ChadKillingsworth/closure-compiler-graal/blob/93a9a41af7a1acdc8e861c5ad738fac4002e2e04/.travis.yml#L65)

Failing build:

 - [build log](https://travis-ci.org/ChadKillingsworth/closure-compiler-graal/jobs/414724593)
 - [build steps](https://github.com/ChadKillingsworth/closure-compiler-graal/blob/github-download-2/.travis.yml#L36)

**Comment by olpaw** [comment]
@ChadKillingsworth it looks like we are producing buggy machine code. During execution of `org.kohsuke.args4j.Messages.format`
```
public String format( Object... args ) {
    synchronized(Messages.class) {
        if(rb==null)
            rb = ResourceBundle.getBundle(Messages.class.getName());
>       return MessageFormat.format(rb.getString(name()),args);
    }
}
```
after successfully getting the enum name with `name()` we are unconditionally calling
`com.oracle.svm.core.snippets.ImplicitExceptions.createNullPointerException`:
```
 │0xdc11ad <org.kohsuke.args4j.Messages.format(java.lang.Object[])java.lang.String+93>    nop
 │0xdc11ae <org.kohsuke.args4j.Messages.format(java.lang.Object[])java.lang.String+94>    mov    0x20(%rsp),%rdi
 │0xdc11b3 <org.kohsuke.args4j.Messages.format(java.lang.Object[])java.lang.String+99>    callq  0xb80320 <java.lang.Enum.name(java.lang.Object)java.lang.String>
>│0xdc11b8 <org.kohsuke.args4j.Messages.format(java.lang.Object[])java.lang.String+104>   nop
 │0xdc11b9 <org.kohsuke.args4j.Messages.format(java.lang.Object[])java.lang.String+105>   nop
 │0xdc11ba <org.kohsuke.args4j.Messages.format(java.lang.Object[])java.lang.String+106>   callq  0xae77a0 <com.oracle.svm.core.snippets.ImplicitExceptions.createNullPointerException()java.lang.NullPointerException>	
 │0xdc11bf <org.kohsuke.args4j.Messages.format(java.lang.Object[])java.lang.String+111>   nop
 │0xdc11c0 <org.kohsuke.args4j.Messages.format(java.lang.Object[])java.lang.String+112>   mov    %rax,0x8(%rsp)
```
I will report back once I find out more.

**Comment by ChadKillingsworth** [comment]
Let me know if you need me to provide anything else to assist with this. I attempted to use `git bisect` to find the bad commit, but I found builds failed at specific comments for what looked like other reasons.

**Comment by cstancu** [comment]
Fixed in https://github.com/oracle/graal/commit/44db8f7d6d5de0bde30a1b7830028be9039d8f57. Should be available in RC6.

**Comment by ChadKillingsworth** [comment]
Confirmed - works in RC6. Thanks!
