### ISSUE TITLE
Javadoc Publisher seems to clutter git repository

### ISSUE THREAD

**Issue by vlsi** [oracle/graal#611]
Javadoc Publisher creates commits like https://github.com/oracle/graal/commit/3afc074853d5dea5690d1a5ea54385dfb95ea800

Is "timestamp update" really important in those files?

Can `-notimestamp` be added to the javadoc generation, so less clutter is made in the repository?

**Comment by JaroslavTulach** [comment]
I've created GR-11484 for myself to not forget about this issue.

**Comment by JaroslavTulach** [comment]
Available as [bc8e3c95c](https://github.com/graalvm/mx/commit/bc8e3c95ce0ac5e0858e87a48d692bba609ea136). Thanks for raising the issue.
