### ISSUE TITLE
Graalvm native-image windows support

### ISSUE THREAD

**Issue by serdarozturk88** [oracle/graal#6121]
I am trying to convert my quarkus jar file using graalvm native image. However, it gives an error like

`Error: Platform specified as windows-amd64 isn't supported.
Error: Image build request failed with exit status 1`

My Environment is like :

- OS : Windows 10 Home Single Languaage (19045.2604) (Language : Turkish)
- GraalVM : ce-java11-22.1.0 (Windows amd64)
- Microsoft Visual Studio Build Tools 2019 (16.11.24)
- Maven 3.8.1
- x64 Native Tools Command Prompt for VS 2019

There is no problem with another pc having environment like this :

- OS : Windows 10 Pro (19045.2604) (Language : English)
- GraalVM : ce-java11-22.1.0 (Windows amd64)
- Microsoft Visual Studio Build Tools 2019 (16.11.24)
- Maven 3.8.1
- x64 Native Tools Command Prompt for VS 2019

Is language or windows type or any other thing problem ?

**Comment by oubidar-Abderrahim** [comment]
Hi, Thank you for reaching out, please download and use the latest version of GraalVM (currently 22.3.1) and try it.

**Comment by MSBilgin** [comment]
I follwed every step in this [turorial](https://medium.com/graalvm/using-graalvm-and-native-image-on-windows-10-9954dc071311) but having same problem.

**Comment by oubidar-Abderrahim** [comment]
Does this issue still happen on 22.3.1?

**Comment by vinc3nz** [comment]
I opened a different issue for this as it complains about NOT having AMD64 (and I have AMD64). Using 22.3.1 btw #6127

**Comment by muhammedali55** [comment]
"I've been trying to solve this problem for about 3 months. I've reviewed almost all of your documentation, but it wasn't enough, and I had to open and examine your source code, but I still couldn't find a solution. I'm still getting this silly error "Platform specified as windows-amd64 isn't supported". Is it that hard to solve this problem?"

**Comment by oubidar-Abderrahim** [comment]
It seems we've already addressed this issue a while ago, but the fix is not in 22.3.1. Could you please try a recent [dev build](https://github.com/graalvm/graalvm-ce-dev-builds/releases) and confirm that it's working for you?

**Comment by MSBilgin** [comment]
I have tried dev build but no success. 
![image](https://user-images.githubusercontent.com/6252718/229897718-28e2713a-0a22-4b9e-b247-5565499ab57d.png)

**Comment by MSBilgin** [comment]
same result 

![image](https://user-images.githubusercontent.com/6252718/231763388-e1ccdbd9-3379-401c-9602-69b4acf0326a.png)

**Comment by serdarozturk88** [comment]
I think the problem is language. When i changed my os language turkish to english, there was no problem with native compilation.

**Comment by fniephaus** [comment]
I believe we have fixed this with https://github.com/oracle/graal/pull/8058.
