### ISSUE TITLE
Upgrade Grallvm Failed

### ISSUE THREAD

**Issue by yuluo-yx** [oracle/graal#6128]
### Reason
```
[ERROR] Failed to execute goal org.graalvm.buildtools:native-maven-plugin:0.9.19:compile (default-cli) on project nacos-config-example
: Execution default-cli of goal org.graalvm.buildtools:native-maven-plugin:0.9.19:compile failed: GraalVM version 22.3 is required but
 22.1 has been detected, please upgrade. -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
````

### reference
![image](https://user-images.githubusercontent.com/77964041/222955358-38e4dad6-48c8-48f1-8db9-7d5e971ce396.png)
I executed the `gu upgrade` command using Cmd.

### out
![image](https://user-images.githubusercontent.com/77964041/222955381-d366f9d7-0e06-451d-a47f-c54be21d3876.png)

**Comment by marwan-hallaoui** [comment]
Hello @yuluo-yx,
Thank you for reporting this issue.
Could you please try and share with us the output of the following command : 
`gu available --show-updates --edition ce`
Then try to upgrade it with : 
`gu upgrade +22.3.0`

Regards,

**Comment by yuluo-yx** [comment]
> 你好@yuluo-yx， 感谢您报告此问题。 您能否尝试与我们分享以下命令的输出： `gu available --show-updates --edition ce` 然后尝试使用以下命令升级它： `gu upgrade +22.3.0`
> 
> 问候，

I get the following feedback when executing in cmd.
![image](https://user-images.githubusercontent.com/77964041/223284831-f3d322c6-049f-4222-8b8d-f326f723b147.png)

**Comment by yuluo-yx** [comment]
> Hello. I also faced the same issue. In my case, I used sdkman to install graalvm. So below is an example I ran to upgrade graalvm.
> 
> * Find the latest graalvm
>   
>   * `sdk list java`
> * Install it
>   
>   * `sdk install java 22.3.1.r17-grl`
> 
> I hope this will help.

thanks! I use the windows operating system, it is a little tedious to install sdk on it, the support for windows is not very good at present, I did not install it.

**Comment by fernando-valdez** [comment]
closing this ticket as the GraalVM updater is no longer supported. You can see more details about it here  https://github.com/oracle/graal/issues/6855
