### ISSUE TITLE
Allowed to mix "-static" with -H:Kind=EXECUTABLE 

### ISSUE THREAD

**Issue by Sanne** [oracle/graal#614]
version:  graalvm-ce-1.0.0-rc5 on Linux.

Apparently the "-static" option is silentily ignored when -H:Kind is set to EXECUTABLE when invoking `native-image`.

I learned now that this should be Kind=STATIC_EXECUTABLE to get a static output.

I would suggest to have this combination of options validated, and fail with a nice error message.

**Comment by olpaw** [comment]
Hi @Sanne 
using `-H:` (and also `-R:`) options is considered expert use (see `native-image --expert-options`). 
There is no reason to ever use `-H:Kind`.

If you want to build a shared library there is `--shared`. Without `--shared` it will always build an executable. With `--static` it will build a static executable (which has certain drawbacks - see https://github.com/oracle/graal/issues/571#issuecomment-409166471)

**Comment by Sanne** [comment]
Hi @olpaw , thanks for the answer.

Yes I understand I shouldn't be using -H:Kind but I happened to have it and it was overriding the `-static`. 

So this is not an urgent issue at all as I understand it's my fault and there are easy workaround :) Just wanted to report it so that you could consider having better validation fo parameters.

**Comment by olpaw** [comment]
We have support for building shared objects for applications for a while now. `--static` now also works with:
* `native-image --static -jar <myjar.jar>`
* `native-image --static -cp ... my.main.Class`
