### ISSUE TITLE
How to build this project ?

### ISSUE THREAD

**Issue by nassimus26** [oracle/graal#6171]
I have tested the native image build with the last version 19 on windows with the profiling file (`"--pgo-instrument" and --pg="...file"`) to ensure having the best performance.
The result is not extraordinary, actual the performance is a little bit worst than a normal JVM.

Hot spot JVM : >10 seconds
GraalVM without profiling : >30 seconds
GraalVM with profiling : >11 seconds

My code is just doing some String concatenation and replacement with Micronaut.

```
@Controller("/test")
class TestCtrl {
    @get:Get
    val persons: HttpResponse<*>
        get() {
            var res = "AAA BE aaz RR tTT TtyhBhy fffe efEFef erytyb "
            val now = System.currentTimeMillis()
            for (i in 0..80) {
                if (i<20)
                    res += res.replace(('a'.code + i % 26).toString().toRegex(), ('a'.code + i + 5 % 26).toString())
                else
                    res = res.replace(('a'.code + i % 26).toString().toRegex(), ('a'.code + i + 5 % 26).toString())
            }
            return HttpResponse.status<Any>(HttpStatus.OK).body("ok -> " + (System.currentTimeMillis() - now))
        }
}
```
So I am interested to rebuild the `substratevm`, or the hole project (if the `substratevm` can't be built and improved alone) but there's absolutely no documentation for the build of this project or at least I found nothing, please provide some documentation to build this project.

**Comment by oraluben** [comment]
I found this quite suite your need: https://foivos.zakkak.net/tutorials/getting_started_with_graalvm_development/

**Comment by oubidar-Abderrahim** [comment]
I believe there is a misunderstanding here. In terms of performance, native image promises 2 things, faster start-ups, and a smaller memory footprint. native image is not expected to have a better execution time compared to JVM. which is why we introduced [PGO](https://www.graalvm.org/latest/reference-manual/native-image/guides/optimize-native-executable-with-pgo/) to help improve the execution speed.

**Comment by nassimus26** [comment]
A native VM with Ahead of time compilation is supposed to be faster than a ByteCode VM with a Just in time compilation, so how to explain that it's not the case here ?

**Comment by zakkak** [comment]
> A native VM with Ahead of time compilation is supposed to be faster than a ByteCode VM with a Just in time compilation, so how to explain that it's not the case here ?

There is a nice summary by @adinn on that question in https://github.com/oracle/graal/issues/979#issuecomment-480786612
