### ISSUE TITLE
Ask help for metadata information collection

### ISSUE THREAD

**Issue by steverao** [oracle/graal#6206]
**Describe the issue**
I recently hope to collect the metadata configuration information of my project and submit it to the [oracle metadata repo](https://github.com/oracle/graalvm-reachability-metadata). Then I use the [access filter](https://www.graalvm.org/latest/reference-manual/native-image/metadata/AutomaticMetadataCollection/#access-filters) to collect the metadata information related to this project, but I set the following rules:
```
{ "rules": [
   {"excludeClasses": ".**"},
   {"includeClasses": "com.alibaba.cloud.**"}
]
}
```
There are other package configuration information in the final collection file:
I would like to know why the configuration content in non-com.alibaba.cloud.** packages is not excluded? Is it my understanding of the use of access filter? 
![image](https://user-images.githubusercontent.com/25423978/225202336-ff860ce2-4371-4046-8a8f-d0666e66170d.png)

**Describe GraalVM and your environment:**
 - OpenJDK Runtime Environment GraalVM 22.3.0 (build 17.0.5+8-LTS)
 - JDK major version: 17

**Comment by oubidar-Abderrahim** [comment]
Hi, Thank you for reaching out about this, we'll take a look into it shortly.

**Comment by linghengqian** [comment]
@steverao 
- I don't understand why you would have this kind of rule for `access-filter.json`, which is usually considered `caller-filter.json`.
- You need to understand what `caller-filter.json` and `access-filter.json` are combined with Conditional conditions.

**Comment by steverao** [comment]
> @steverao
> 
> * I don't understand why you would have this kind of rule for `access-filter.json`, which is usually considered `caller-filter.json`.
> * You need to understand what `caller-filter.json` and `access-filter.json` are combined with Conditional conditions.

1. For the question one, because, I saw the purpose of `access-filter.json` is  `Therefore, access filters enable directly excluding packages and classes (and their members) from the generated configuration` in [document of access filters](https://www.graalvm.org/latest/reference-manual/native-image/metadata/AutomaticMetadataCollection/#access-filters). I want to only contain configurations from package of `com.alibaba.cloud.**`. But in result configuration files, it still contains others in other packages, such as `org.springframework.**`.
2. For the question two, I think using `access-filter.json` is enough if its function like above description.

**Comment by linghengqian** [comment]
> > @steverao
> > 
> > * I don't understand why you would have this kind of rule for `access-filter.json`, which is usually considered `caller-filter.json`.
> > * You need to understand what `caller-filter.json` and `access-filter.json` are combined with Conditional conditions.
> 
> 1. For the question one, because, I saw the purpose of `access-filter.json` is  `Therefore, access filters enable directly excluding packages and classes (and their members) from the generated configuration` in [document of access filters](https://www.graalvm.org/latest/reference-manual/native-image/metadata/AutomaticMetadataCollection/#access-filters). I want to only contain configurations from package of `com.alibaba.cloud.**`. But in result configuration files, it still contains others in other packages, such as `org.springframework.**`.
> 2. For the question two, I think using `access-filter.json` is enough if its function like above description.

- I think I will write a Chinese article recently to introduce the difference between `access-filter.json` and `caller-filter.json`, and why they are usually used at the same time in Standard Agent Mode, but in Conditional Agent Mode useless. The documentation of GraalVM CE does not make this very clear, leading to some issues like https://github.com/oracle/graalvm-reachability-metadata/issues/159.
- For English materials, you can refer to the Youtube recordings of previous GraalVM offline meetings.

**Comment by oubidar-Abderrahim** [comment]
GraalMV 22.3 is no longer supported, if this issue is still occurring in the latest versions of Oracle GraalVM, please create a new issue
