### ISSUE TITLE
UnsupportedFeatureError: Unresolved element found at runtime

### ISSUE THREAD

**Issue by dsyer** [oracle/graal#622]
If you build a native image with `--report-unsupported-elements-at-runtime` from code that does this:

```java
		try {
			return NonExistentClass.class.isAssignableFrom(myClass);
		}
		catch (Throwable ex) {
			return false;
		}
```

it fails at runtime with `UnsupportedFeatureError: Unresolved element found` (a bit like #511 but different I think).  You can work around it by doing a check for `Class.forName("com.acme.NonExistentClass")` before trying `isAssignableFrom()` it. Seems wrong, because a normal JVM behaves differently.

**Comment by dsyer** [comment]
Ping on this. I found another instance of this in Spring Boot (in addition to the two above). If Graal could just throw `NoClassDefFoundError` like a normal VM it would make these code paths work as expected. is there any reason not to do that?

**Comment by cstancu** [comment]
We have a new, experimental flag: `--allow-incomplete-classpath` which should take care of cases like this. You can try it by [building GraalVM from source](https://github.com/oracle/graal/tree/master/vm). This will be available in the next release, rc10.

**Comment by cstancu** [comment]
This is now supported via the `--allow-incomplete-classpath` flag.
