### ISSUE TITLE
Performance differences between java11 and java17 on the same Testcase

### ISSUE THREAD

**Issue by YuanWangC** [oracle/graal#6242]
**Describe the issue**
Recently, I used the `graalvm-ce-java11-22.3.1` and the `graalvm-ce-java11-22.3.1` which are from  [graalvm-ce-builds](https://github.com/graalvm/graalvm-ce-builds/releases/tag/vm-22.3.1) on the same platform `Linux(amd64)` to execute the following test case, and I found that java11 version took an average of 20 seconds while java17 version takes an average of nearly 40 seconds. Could you please tell me why this is happening, or what VM options should I add to the java17 version?

**Test case**
```java
public class MyJVMTest {
    void test(){
        StringBuffer temp = new StringBuffer();
        for (int i = 0; i <= 6; i++) {
            int tempOffset = 444939863;
            for (int j = 0; j < tempOffset; j++){
                    temp.append('=');
            }
        }
    }

    public static void main(String[] args){
        new MyJVMTest().test();
    }
}
```

**Comment by oubidar-Abderrahim** [comment]
Hi, Thank you for reporting this, We'll take a look into it shortly.

**Comment by wirthi** [comment]
Hi @YuanWangC 

thanks for reporting this issue. I can reproduce it. Note, however, that this is not a GraalVM issue - it can easily be reproduced on upstream JDK builds. On my machine I can reproduce the issue starting with JDK-15.

As this is an upstream issue with the JDK, we can't really do a lot on this. You might want to report the issue to the JDK, or dig through their changelogs. 

Best,
Christian
