### ISSUE TITLE
Support for multiple values in -H:IncludeResources

### ISSUE THREAD

**Issue by dsyer** [oracle/graal#626]
According to the docs `-H:IncludeResources` is a single regex, and that seems to be the way it works. It's just not very convenient, if you want to include specific sets of resources, from more than one location - the only pattern I found that worked is `.*` so the binary image is enormous when it is finished building. Maybe multiple values could be supported through a comma-separated list (like `-H:IncludeResourceBundles` already supports)?

**Comment by olpaw** [comment]
Fixed. See https://github.com/oracle/graal/blob/master/substratevm/RESOURCES.md
