### ISSUE TITLE
[Feature Request] FrameSlot reader and writer implementations

### ISSUE THREAD

**Issue by fniephaus** [oracle/graal#627]
Since FrameSlots appear to be used in quite similar ways, it would be useful if Truffle could provide generic `FrameSlot` reader and writer implementations.

Some Examples:
- TruffleRuby's [WriteFrameSlotNode](https://github.com/oracle/truffleruby/blob/140aae2f44aaccb5940bbd5e58c4f575bd9d45f9/src/main/java/org/truffleruby/language/locals/WriteFrameSlotNode.java#L22)
- Graal.Python's [FrameSlotNode](https://github.com/graalvm/graalpython/blob/4338e8b4a4fe7f4038a149f780745ac946f6304a/graalpython/com.oracle.graal.python/src/com/oracle/graal/python/nodes/frame/FrameSlotNode.java)
- Graal.js's [FrameSlotNode](https://github.com/graalvm/graaljs/blob/9618fb6b96b3e5691c18e9564cd0d94adf9b5fc8/graal-js/src/com.oracle.truffle.js.nodes/src/com/oracle/truffle/js/nodes/access/FrameSlotNode.java)
- Sulong's [LLVMAMD64WriteAddressRegisterNode](https://github.com/graalvm/sulong/blob/d4a688b50a2d52d596216132f653b090431e5f5b/projects/com.oracle.truffle.llvm.nodes/src/com/oracle/truffle/llvm/nodes/asm/support/LLVMAMD64WriteAddressRegisterNode.java) and [LLVMWriteNode](https://github.com/graalvm/sulong/blob/aa5be40480702e631123e4b21591e53f1a8138c4/projects/com.oracle.truffle.llvm.nodes/src/com/oracle/truffle/llvm/nodes/vars/LLVMWriteNode.java)

/cc @eregon

**Comment by fniephaus** [comment]
Had an offline chat with @eregon and he mentioned SL's [SLWriteLocalVariableNode](https://github.com/oracle/graal/blob/4be0852ff2a9159cd4209562e33d5a6eda4e5b43/truffle/src/com.oracle.truffle.sl/src/com/oracle/truffle/sl/nodes/local/SLWriteLocalVariableNode.java). I think that one is probably the best implementation I have seen so far (which you would expect from a reference implementation 😅, so well done!).

**Comment by eregon** [comment]
I agree with @fniephaus, this would simplify a lot of code which is non trivial.

As can be seen from the above implementations, there is a lot of complexity and they all do something slightly different.
Using common nodes would avoid bugs, keep the nodes to the latest API using it in the best way (as illustrated by SL but none of the other languages using the cleaner approach) and ensure the best performance.

@lukasstadler @woess @chumer Any taker for this?

**Comment by boris-spas** [comment]
Tracking internally as Issue GR-20794.

**Comment by chumer** [comment]
This is obsoleted by the upcoming bytecode DSL. It comes with builtin locals support.
