### ISSUE TITLE
No Java 20 flavored graalvm distribution

### ISSUE THREAD

**Issue by anthonydahanne** [oracle/graal#6298]
**Feature request**

**Is your feature request related to a problem? Please describe.**
Under https://github.com/graalvm/graalvm-ce-builds/releases there's no Java 20 based builds; it'd be nice since Java 20 was out 10 days ago or so.

**Describe the solution you'd like.**
Add a new GraalVM release with Java 20

**Describe who do you think will benefit the most.**
GraalVM users, GraalVM contributors, developers of libraries and frameworks which depend on GraalVM

**Describe alternatives you've considered.**
None

**Additional context.**
Was in the process of updating GraalVM paketo buildpack at: https://github.com/paketo-buildpacks/graalvm with Java 20; I guess I can't for now

**Comment by meuzame** [comment]
Graal JDK20 Relese is planned for April 18, 2023 see https://www.graalvm.org/release-notes/release-calendar/#planned-releases

**Comment by petermz** [comment]
In the meantime, there are JDK20 based [dev builds](https://github.com/graalvm/graalvm-ce-dev-builds/releases)

**Comment by fniephaus** [comment]
@meuzame and @petermz are correct :)
