### ISSUE TITLE
[native-image --version] No way to tell version in use when JDK isn't jlinked nor compiled to binary

### ISSUE THREAD

**Issue by jerboaa** [oracle/graal#6319]
**Describe the issue**
After https://github.com/oracle/graal/pull/6302 there is no way for us (Mandrel) to tell which codeline is in use based on the `native-image --version` output. We use the bash launcher (deliberately) and don't jlink the base JDK that is in use (plain OpenJDK).

`java.vendor.version` is a protected property, which cannot be set on the command line:

```
$ java -Djava.vendor.version=foo -XshowSettings:properties --version 2>&1 | grep vendor
    java.specification.vendor = Oracle Corporation
    java.vendor = Red Hat, Inc.
    java.vendor.url = https://www.redhat.com/
    java.vendor.url.bug = https://bugzilla.redhat.com/enter_bug.cgi?product=Fedora&component=java-17-openjdk&version=37
    java.vendor.version = (Red_Hat-17.0.6.0.10-1.fc37)
    java.vm.specification.vendor = Oracle Corporation
    java.vm.vendor = Red Hat, Inc.
```

That means, the new `native-image --version` output solely contains JDK version properties, which is unfortunate since we cannot tell which code line is in use (23.x or 24.x or...).

Example (of a recent mandrel build from graal master):

```
$ native-image --version
native-image 20.0.1-internal 2023-04-18
OpenJDK Runtime Environment null (build 20.0.1-internal-adhoc.sgehwolf.jdk20u)
OpenJDK 64-Bit Server VM null (build 20.0.1-internal-adhoc.sgehwolf.jdk20u, mixed mode)
```

**Comment by jerboaa** [comment]
WIP patch to solve this issue for us would be something like this:

https://github.com/oracle/graal/compare/master...jerboaa:graal:version-mandrel?expand=1

Would that be acceptable?

**Comment by jerboaa** [comment]
@fniephaus Would you have any eta for something like this getting integrated? The version change produces a lot of noise in our CI.

**Comment by fniephaus** [comment]
I will reach out tomorrow and hope we can merge a fix asap and within the next 48 hours.

**Comment by fniephaus** [comment]
I've just opened #6356 with a more comprehensive fix for this (incl updating the build output infra). PTAL and let me know what you think. Thanks!

**Comment by jerboaa** [comment]
Thank you!
