### ISSUE TITLE
Version.getCurrent() broken for distributions not modifying the base JDK

### ISSUE THREAD

**Issue by jerboaa** [oracle/graal#6379]
**Describe the issue**
After https://github.com/oracle/graal/pull/6302 the `org.graalvm.version` property is no longer being passed on to the native image generator. Specifically [this line](https://github.com/oracle/graal/pull/6302/files#diff-9e053bec9eca0799896bd471363fa6aa1df70269e454b89dff1ea5fb844a480cL125) and [this line](https://github.com/oracle/graal/pull/6302/files#diff-9e053bec9eca0799896bd471363fa6aa1df70269e454b89dff1ea5fb844a480cL125) are problematic for distros not using jlink or otherwise modifying the base JDK from upstream OpenJDK, and thus not having a `release` file with `GRAALVM_VERSION` in it.

**Steps to reproduce the issue**
```
$ cat VersionTest.java
import org.graalvm.home.Version;
public class VersionTest {
        private static final String VERSION = Version.getCurrent().toString();
	public static void main(String[] args) {
		System.out.println(VERSION);
	}
}
$ javac -cp $GRAALVM_HOME/lib/jvmci/graal-sdk.jar VersionTest.java
$ native-image --initialize-at-build-time=. VersionTest
[...]
$ ./versiontest
snapshot
```

**Describe GraalVM and your environment:**
Mandrel build of graal master after https://github.com/oracle/graal/pull/6302 with `org.graalvm.version` set in native-image bash launcher.

**Actual Results**
Always prints `snapshot`

**Expected Results**
The actual version in use, (i.e. `23.1.0-dev`) for the build I've tested with.

```
native-image 17.0.6 2023-01-17
OpenJDK Runtime Environment Mandrel-23.1.0-dev (build 17.0.6+10)
OpenJDK 64-Bit Server VM Mandrel-23.1.0-dev (build 17.0.6+10, mixed mode)
```

**Comment by jerboaa** [comment]
We are going to need another follow-up it seems.

**Comment by zakkak** [comment]
@fniephaus it looks like this impacts GraalVM CE builds as well...

I built GraalVM `master` using:
```
mx --primary-suite-path vm --env ce build
```

and I am seeing:
```
$ grep GRAALVM_VERSION $GRAALVM_HOME/release
GRAALVM_VERSION="23.1.0-dev"

$ ./versiontest                             
snapshot

$ $GRAALVM_HOME/bin/native-image --version  
native-image 20 2023-03-21
GraalVM Runtime Environment GraalVM CE (build 20+34-jvmci-23.0-b10)
Substrate VM GraalVM CE (build 20+34, serial gc)
```

Enabling `VERBOSE_GRAALVM_LOCATOR` I see that GraalVM fails to get the value of `org.graalvm.version` (as happens in Mandrel) and then tries to get the GraalVM home directory, but at this point we are not in GraalVM so it fails...

```
$ export VERBOSE_GRAALVM_LOCATOR=true
FORCE_GRAAL_HOME: null
GRAAL_HOME_RELATIVE_PATH: null
Found GraalVM home: null
snapshot
```

I expanded Severin's test as follows:

```
❯ cat VersionTest.java 
import org.graalvm.home.Version;

public class VersionTest {


    final static String version = Version.getCurrent().toString();

    public static void main(String[] args) {
		System.out.println("Baked in: " + version);
		System.out.println("At runtime: " + Version.getCurrent());
	}
}
```

and then compiled it with:

```
❯ $GRAALVM_HOME/bin/native-image --initialize-at-build-time=. -Dcom.oracle.graalvm.locator.verbose=true VersionTest
```

and the result is:

```
Baked in: 23.1.0-dev
FORCE_GRAAL_HOME: null
GRAAL_HOME_RELATIVE_PATH: null
Found GraalVM home: null
At runtime: snapshot
```

Note that with `-Dcom.oracle.graalvm.locator.verbose=true` I got the following message at build time:

```
FORCE_GRAAL_HOME: null          
GRAAL_HOME_RELATIVE_PATH: null
GraalVM home found by java.home property as: /home/zakkak/code/graal/sdk/mxbuild/linux-amd64/GRAALVM_F85B3CA1C2_JAVA20/graalvm-f85b3ca1c2-java20-23.1.0-dev
```

The above test works as expected prior to https://github.com/oracle/graal/pull/6302

**Comment by jerboaa** [comment]
Update: I've updated the description with a better test (capture the graal version at image build time) which illustrated the issue observed in mandrel.

**Comment by jerboaa** [comment]
Closed with: https://github.com/oracle/graal/pull/6377
