### ISSUE TITLE
[native-image] OutOfMemoryError running build with JS language enabled after registering constructors for reflection use

### ISSUE THREAD

**Issue by AFaust** [oracle/graal#639]
I am currently trying to turn a small Java application based on Jetty and Graal.js into something that can be run successfully after compilation via native-image. In one step I added a Feature class to register Reflection usages for the analysis phase. While the native-image build ran fine after adding just classes, fields and methods of relevant classes, and adding the ```--language:js``` flag to the invocation of native-image, the build fails after adding the constructors of the same classes.
This issue has the exact same triggering code change as issue #638 that I just reported, but a completely different behaviour, so I am reporting this as a separate issue.

#### Steps to reproduce
1. Ensure [svm.jar is installed in the local Maven repository](https://github.com/AFaust/webhook-hub/tree/native-image#non-standard-dependency-svmjar)
2. Ensure Docker engine is running locally
3. Checkout the branch [native-image-with-js](https://github.com/AFaust/webhook-hub/tree/native-image-with-js) of my project
4. Build the project using ```mvn package```

#### Expectation
The build succeeds just as it has in the [commit before](https://github.com/AFaust/webhook-hub/tree/b97040af49de98b1f1fcd7a2e762d5c690faab9c), where only classes, fields and methods had been registered and the ```--language:js``` flag added.

#### Observation
Running native-image as part of the Docker image build fails with an OutOfMemoryError after about an hour (Docker process is allowed use of 4 GiB memory of my total 16 GiB system RAM). The following output is reported:
```
[INFO] DOCKER> Step 3/9 : RUN mkdir -p /var/lib/webhook-hub    && mv /tmp/webhook-hub-1.0.0-SNAPSHOT-shaded.jar /var/lib/webhook-hub/webhook-hub.jar    && cd /var/lib/webhook-hub    && /usr/lib/jvm/graalvm-ce-1.0.0-rc5/bin/native-image --language:js -jar ./webhook-hub.jar -H:Name=webhook-hub -H:+JNI -H:EnableURLProtocols=http
[INFO] DOCKER>
[INFO] DOCKER> ---> Running in c0ae76e67c07
[INFO] DOCKER> Build on Server(pid: 12, port: 36953)*
[INFO] DOCKER>
[INFO] DOCKER> classlist
[INFO] DOCKER> :
[INFO] DOCKER> 7,608.73
[INFO] DOCKER> ms
[INFO] DOCKER> (cap)
[INFO] DOCKER> :
[INFO] DOCKER> 1,273.40
[INFO] DOCKER> ms
[INFO] DOCKER> setup
[INFO] DOCKER> :
[INFO] DOCKER> 4,914.07
[INFO] DOCKER> ms
[INFO] DOCKER> 2 fatal errors detected:
[INFO] DOCKER> fatal error:
[INFO] DOCKER> java.lang.OutOfMemoryError: Java heap space
[INFO] DOCKER> Error: Processing image build request failed
[INFO] DOCKER> Removing intermediate container c0ae76e67c07
[ERROR] DOCKER> Unable to build image [orderofthebee/webhook-hub] : The command '/bin/sh -c mkdir -p /var/lib/webhook-hub    && mv /tmp/webhook-hub-1.0.0-SNAPSHOT-shaded.jar /var/lib/webhook-hub/webhook-hub.jar    && cd /var/lib/webhook-hub    && /usr/lib/jvm/graalvm-ce-1.0.0-rc5/bin/native-image --language:js -jar ./webhook-hub.jar -H:Name=webhook-hub -H:+JNI -H:EnableURLProtocols=http' returned a non-zero code: 1  [The command '/bin/sh -c mkdir -p /var/lib/webhook-hub    && mv /tmp/webhook-hub-1.0.0-SNAPSHOT-shaded.jar /var/lib/webhook-hub/webhook-hub.jar    && cd /var/lib/webhook-hub    && /usr/lib/jvm/graalvm-ce-1.0.0-rc5/bin/native-image --language:js -jar ./webhook-hub.jar -H:Name=webhook-hub -H:+JNI -H:EnableURLProtocols=http' returned a non-zero code: 1 ]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:15 h
[INFO] Finished at: 2018-08-26T19:21:10+02:00
[INFO] Final Memory: 34M/413M
[INFO] ------------------------------------------------------------------------
```

**Comment by cstancu** [comment]
This issue cannot be reproduced anymore.
