### ISSUE TITLE
Possible Memory leak with Graal polyglot programing

### ISSUE THREAD

**Issue by Wathsara** [oracle/graal#6398]
**Describe the issue**

Experiencing an issue in a web application that I am working on, I have been getting a warning message when redeploying the webapp and it it's as follows.

```
{org.apache.catalina.loader.WebappClassLoaderBase} - The web application [graal-test] created a ThreadLocal with key of type [java.lang.ThreadLocal.SuppliedThreadLocal] (value [java.lang.ThreadLocal$SuppliedThreadLocal@53b0d886]) 
and a value of type [com.oracle.truffle.api.impl.ThreadLocalHandshake.TruffleSafepointImpl] (value [com.oracle.truffle.api.impl.ThreadLocalHandshake$TruffleSafepointImpl@31f8dd1c]) 
but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.
```

**Describe GraalVM and your environment:**
 - Graal version  - 22.3.1**
 - JDK major version: **[e.g.:11]**
 - OS: **[e.g. macOS]**

**More details**
In my web application, I am using the `org.graalvm.polyglot.Engine`, and I am creating a static engine as follows:
```
private static final Engine polyglotEngine = Engine.newBuilder(LANGUAGE) .option("engine.WarnInterpreterOnly", "false") .build();
```

I am also creating a `org.graalvm.polyglot.Context` using the following code: (I'm creating a new context each time when executing a javascript code)

```
this.context = Context.newBuilder().engine(polyglotEngine).allowHostAccess(HostAccess.NONE).allowHostClassLoading(false).allowEnvironmentAccess(EnvironmentAccess.NONE).allowCreateThread(false).allowCreateProcess(false).allowNativeAccess(false).allowPolyglotAccess(PolyglotAccess.NONE) .build();
  ```
     
After executing  JavaScript code (provided by the user of the application), I am making sure to leave and close the context using the following code:

```
this.context.leave();
this.context.close();
```

Even though I make sure to leave and close in a finally block, Seems like some of the thread locals are not getting cleared properly.

**Comment by chumer** [comment]
Which JDK did you use to reproduce this? I don't think this can happen on a GraalVM JDK.
(please fill out the environment section )

**Comment by chumer** [comment]
This is expected and not a memory leak. Just a tiny amount of memory is wasted here and would not be worth reclaiming by clearing the ThreadLocal. Leaving the context clears out all context-specific data structures from this thread-local, so a memory leak from user-defined data should be impossible.

Thank you for the report, though. It's good to have this documented.
