### ISSUE TITLE
[native-image] Services declared in META-INF/services shouldn't require declaration in reflection.json

### ISSUE THREAD

**Issue by graemerocher** [oracle/graal#640]
Currently you have to declare each class defined in a `META-INF/services` file and loaded via `ServiceLoader` in a reflection.json when using `nativeimage`.

This seems counter intuitive as the classes are already declared ahead of time. The `nativeimage` tool should scan the `META-INF/services` and include them automatically or there should be a flag to enable the ability to do this, otherwise every Java project has to write some build tool to extract all the `META-INF/services` classes and generate a `reflection.json` file.

Relates to #470

**Comment by vhiairrassary** [comment]
If you use constant argument for `ServiceLoader.load(Class)` then hopefully https://github.com/oracle/graal/pull/566 should fix your issue?

**Comment by graemerocher** [comment]
Yes #566 looks like it will resolve it

**Comment by graemerocher** [comment]
This duplicates #563 sorry for the noise
