### ISSUE TITLE
Native-Image Windows 11 support

### ISSUE THREAD

**Issue by hsnene5** [oracle/graal#6438]
When I try to create native image on windows 11 computer I get the error below. And my environment specifications are like this:

- OS : Windows 11 Enterprise 64-bit  (22621) (Language : English)
- GraalVM : ce-java11-22.1.0 (Windows amd64)
- Microsoft Visual Studio Build Tools 2019 (16.11.24)
- Maven 3.8.1
- x64 Native Tools Command Prompt for VS 2019

![image](https://user-images.githubusercontent.com/46786681/232608896-7893095d-5afa-4765-84e2-e0764d8da922.png)

Is there anything wrong with windows 11?

Edit:

This same error occurs on GraalVM version 22.3.1 too.

**Comment by oubidar-Abderrahim** [comment]
Hi, thank you for reporting this, could you please verify with the latest Microsoft Visual Studio Build Tools (2022)?

**Comment by engineersunit** [comment]
Hi GraalVM team,

I have tried the native image creation on the latest windows 11 Visual Studio Build Tools (2022) but it is still failing but with another issue. Please help! 

Details: https://github.com/oracle/graal/issues/6648

**Comment by oubidar-Abderrahim** [comment]
It seems this issue was fixed in our latest dev builds of GraalVM 23.1.0-dev.
