### ISSUE TITLE
GraalVM hotspot crash.

### ISSUE THREAD

**Issue by manonthegithub** [oracle/graal#644]
I am not sure this is right place for reporting. But I've got crash of graalvm on Mac OS X.
[hs_err_pid5453.log](https://github.com/oracle/graal/files/2331644/hs_err_pid5453.log)

**Comment by jacekmusial** [comment]
How did this happen? What steps can we take to reproduce this issue?

[code]
OS:Bsduname:Darwin 17.7.0 Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/RELEASE_X86_64 x86_64
CPU:total 8 (initial active 8) (4 cores per cpu, 2 threads per core) family 6 model 158 stepping 9
vm_info: GraalVM 1.0.0-rc4 (25.71-b01-internal-jvmci-0.45) for bsd-amd64 JRE (1.8.0)
elapsed time: 63501 seconds (0d 17h 38m 21s)

[/code]

**Comment by manonthegithub** [comment]
I run the sbt in the Idea's shell. This has happened when I tried to run of one of sbt's commands right after Mac waked up. I am not able to reproduce it again. I guess it is somehow connected to suspending/waking up of processes in MAC.

**Comment by manonthegithub** [comment]
If it is difficult to you to understand what and how it has happened from the err log, I think this can be archived until it will happen again...
