### ISSUE TITLE
Polyglot can't resolve lambdas to SAM interfaces when there are other overloads

### ISSUE THREAD

**Issue by mikehearn** [oracle/graal#646]
Consider the following code in Kotlin (but the Java equivalent is obvious)

```kotlin
interface SAM {
    fun call(value: String)
}

interface TwoMethods {
    fun one(value: String)
    fun two()
}

fun overloaded(sam: SAM) {}
fun overloaded(twoMethods: TwoMethods) {}
```

Invoking the method `overloaded` from JavaScript like this:

`overloaded((str) => console.log())`

should resolve to the first overload because the passed lambda is a single function, so it can't implement the `TwoMethods` interface. However polyglot can't figure that out and so I get:

> TypeError: INVOKE on JavaClass[net.corda.experimental.js.CordaJSUtils] failed due to: java.lang.IllegalArgumentException: Multiple applicable overloads found for method name overloaded (candidates: [Method[public static final void net.corda.experimental.js.CordaJSUtils.overloaded(net.corda.experimental.js.SAM)], Method[public static final void net.corda.experimental.js.CordaJSUtils.overloaded(net.corda.experimental.js.TwoMethods)]], arguments: [DynamicObject<JSFunction>@320a8ebf (b)])

This is a pain because such APIs are quite common e.g. in RxJava. It makes them unusable without workarounds.

**Comment by woess** [comment]
We should probably prioritize conversion to a functional (SAM) interface, which would fix this.

**Comment by woess** [comment]
This has been fixed in master (https://github.com/oracle/graal/commit/6a75e205de3c8bf1e796ae48624f57e3047ac8cd) and will be part of the GraalVM release scheduled for Sep 28.

**Comment by mikehearn** [comment]
Thanks!
