### ISSUE TITLE
@JSONComponent not honoured

### ISSUE THREAD

**Issue by davecramer** [oracle/graal#6461]
I have a relatively simple command line app that is trying to send json to a webserver
I annotate the object with @JSONComponent but for some reason when using RestTemplate.exchange the object is not serialized.

**Comment by SergejIsbrecht** [comment]
@davecramer ,

could you please fill out the template? It is not clear what the actual problem is. I guess with `JSONComponent` Spring native-image is meant? If yes, I would recommend creating an issue in the Spring-Repo.

**Comment by davecramer** [comment]
Actually I figured this out, not sure if is a bug or desired behaviour.
Because serializing a bean requires reflection you need to add a reflection-json file with the methods.
Naively I figured that annotating it with @JSONComponent would automagically take care of that.
