### ISSUE TITLE
BuildOptions contains duplicates

### ISSUE THREAD

**Issue by ddevlam** [oracle/graal#6488]
When reading https://www.graalvm.org/latest/reference-manual/native-image/overview/BuildOptions/ I noticed that documentation below is duplicated.

`--enable-monitoring: enable monitoring features that allow the VM to be inspected at run time. Comma-separated list can contain heapdump, jfr, jvmstat, or all (defaults to all if no argument is provided). For example: --enable-monitoring=heapdump,jvmstat.`

`--enable-sbom: specify the format for a Software Bill of Materials (SBOM) to be included in the image for passive inspection. Currently, only cyclonedx is supported and the default.`

**Comment by fniephaus** [comment]
Thanks for bringing this up, @ddevlam. It seems we've already fixed this on master, see [this page](https://www.graalvm.org/dev/reference-manual/native-image/overview/BuildOptions/). The docs under `/latest/` will be updated when we're rolling out the next release in June.
