### ISSUE TITLE
java.lang.reflect.Method.getDefaultValue does not work 

### ISSUE THREAD

**Issue by stuartwdouglas** [oracle/graal#649]
While trying to get hibernate validator to run with RC5 I get the following:

`
Error: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: Unsupported method java.lang.Class.getConstantPool() is reachable: The declaring class of this element has been substituted, but this element is not present in the substitution class
To diagnose the issue, you can add the option -H:+ReportUnsupportedElementsAtRuntime. The unsupported element is then reported at run time when it is accessed the first time.
Trace:
	at parsing java.lang.System$2.getConstantPool(System.java:1227)
Call path from entry point to java.lang.System$2.getConstantPool(Class):
	at java.lang.System$2.getConstantPool(System.java:1227)
	at java.lang.reflect.Method.getDefaultValue(Method.java:609)
	at org.hibernate.validator.internal.metadata.core.ConstraintHelper.assertValidationAppliesToParameterSetUpCorrectly(ConstraintHelper.java:939)
`

**Comment by cstancu** [comment]
`Method.getDefaultValue` is not implemented yet. It should be available in the next release.
(Related: https://github.com/oracle/graal/issues/650).

**Comment by pimotte** [comment]
I also have this issue with RC9. Is this still in the pipeline? :)

**Comment by choeflake** [comment]
+1

**Comment by cstancu** [comment]
This was fixed by https://github.com/oracle/graal/commit/ef950cc5fe3506f45403571c4c15badcdf2115d1.
