### ISSUE TITLE
Method.getAnnotatedReturnType does not work

### ISSUE THREAD

**Issue by stuartwdouglas** [oracle/graal#650]
Field.getAnnotatedType(), Parameter.getAnnotatedType() and Constructor.getAnnotatedReturnType() also fails the same way

> Error: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: Unsupported method java.lang.Class.getConstantPool() is reachable: The declaring class of this element has been substituted, but this element is not present in the substitution class
To diagnose the issue, you can add the option -H:+ReportUnsupportedElementsAtRuntime. The unsupported element is then reported at run time when it is accessed the first time.
Trace:
	at parsing java.lang.System$2.getConstantPool(System.java:1227)
Call path from entry point to java.lang.System$2.getConstantPool(Class):
	at java.lang.System$2.getConstantPool(System.java:1227)
	at java.lang.reflect.Executable.getAnnotatedReturnType0(Executable.java:635)
	at java.lang.reflect.Method.getAnnotatedReturnType(Method.java:648)

**Comment by cstancu** [comment]
Those methods are not implemented yet. They should be available in the next release.

**Comment by cstancu** [comment]
Fixed in 76d6fd55125a7da91f6c522ac6e396161610bb5d.
