### ISSUE TITLE
GraalVM Community Edition 22.3.2 is missing macOS (aarch64) and Java 19

### ISSUE THREAD

**Issue by wyvx** [oracle/graal#6535]
**Describe the issue**
GraalVM Community Edition 22.3.2 is missing macOS (aarch64) and Java 19.
Release 22.3.1 had them. There is no explanation in the release notes for the omission.

**Steps to reproduce the issue**
Visit https://github.com/graalvm/graalvm-ce-builds/releases and compare releases.

**Describe GraalVM and your environment:**
 - GraalVM Community Edition 22.3.2
 - JDK major version: 19
 - OS: macOS Ventura
 - Architecture: aarch64

**Comment by aelmassa** [comment]
Hi @wyvx 
GraalVM 22.3.2 will only ship supported components.
Java 19 and GraalVM 22.3.1 for macOS aarch64 are experimental 
[the experimental features matrix for GraalVM Community:](https://www.graalvm.org/latest/docs/introduction/#features-support)

the next feature release (23.0 on [June 13th](https://www.graalvm.org/release-notes/release-calendar/)) will still have all experimental components.

**Comment by aelmassa** [comment]
Hi @wyvx 

Please note that you can find the pre-release build here : [23.0.0-dev]( https://github.com/graalvm/graalvm-ce-dev-builds/releases/tag/23.0.0-dev-20230510_0714)

Feel free to create a new issue if you still need any help!

Thank you for reporting!
