### ISSUE TITLE
IntegerStamp.create misses zero when mayBeSet is just the high bit

### ISSUE THREAD

**Issue by utting** [oracle/graal#6555]
**Describe the issue**
While working on verifying the correctness of the recently improved IntegerStamp algorithms (Oct-2022), I have found some cases where IntegerStamp.create returns an empty stamp, but actually 0 should be allowed.
The problem occurs when the only bit that may be set is the highest (most-significant) bit in the word size, but the low..high bounds exclude the most negative value. 

**Steps to reproduce the issue**
For example, the code IntegerStamp.create(8, -127L, 0L, 0L, 0x80L) returns an empty stamp, but zero is a valid value that satisfies all these constraints (it is in the range -127 ... 0 and it has no bits set).  A unit test is given below that illustrates the problem, for any given number of bits (e.g. 8, 16, 32, 64).

I have not yet found an input Java program that directly triggers this bug, because it seems difficult to construct a variable whose bits are limited to just the highest bit while the range excludes the lowest value - each of these conditions can arise separately, but I have not found a way of combining them yet (Math.min would help, but the stamps seem to ignore it).  However, I think this IntegerStamp bug is still potentially dangerous, because the stamp creation is losing the zero value, which could lead to incorrect optimizations being chosen when this combination of range and allowable bits occurs.

**Describe GraalVM and your environment:**
 - GraalVM version (master branch, for example: commit b79afd6daa25d88339536ca6b83a9b6147826229)
 - JDK major version: 
    openjdk version "17.0.7" 2023-04-18
    OpenJDK Runtime Environment (build 17.0.7+4-jvmci-23.0-b10)
    OpenJDK 64-Bit Server VM (build 17.0.7+4-jvmci-23.0-b10, mixed mode, sharing)
 - OS: macOS Ventura 13.3.1
 - Architecture: Apple M1 processor

**More details**
The following unit test checks that zero is still allowed by the stamp, but it fails (for various values of 'bits'):
```
    @Test
    public void testHighBitOnly() {
        int bits = 32;
        long lo = CodeUtil.minValue(bits) + 1;
        long hi = 0L;
        long mustBeSet = 0L;
        long mayBeSet = 1L << (bits - 1);
        IntegerStamp s = IntegerStamp.create(bits, lo, hi, mustBeSet, mayBeSet, true);
        assertTrue("Stamp = " + s, s.contains(0L));
    }
```
The output of running this unit test is:
```
There was 1 failure:
1) org.graalvm.compiler.nodes.test.VerioptStampTest#testHighBitOnly
java.lang.AssertionError: Stamp = i32<empty>
```

**Comment by tkrodriguez** [comment]
Thanks for reporting this.  https://github.com/oracle/graal/pull/6571
