### ISSUE TITLE
Class.getAnnotationsByType(Class) is not implemented

### ISSUE THREAD

**Issue by stuartwdouglas** [oracle/graal#658]
Error: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: Unsupported method java.lang.Class.getAnnotationsByType(Class) is reachable: The declaring class of this element has been substituted, but this element is not present in the substitution class
To diagnose the issue, you can add the option --report-unsupported-elements-at-runtime. The unsupported element is then reported at run time when it is accessed the first time.

**Comment by cstancu** [comment]
Fixed in https://github.com/oracle/graal/commit/dca98069dc57c458b8bcb3392cf9e66316dd37b6. Will be available in rc7.
