### ISSUE TITLE
Use of default ForkJoinPool during static init is unreliable

### ISSUE THREAD

**Issue by stuartwdouglas** [oracle/graal#660]
If you use the ForkJoinPool during static init it will work most of the time (as it appears this is also used during the build process), unless it results in the creation of a new thread in which case it will fail (and seems to report a stack trace that is not really possible). This can be worked around with `-J-Djava.util.concurrent.ForkJoinPool.common.parallelism=1` but it would be great if this worked out of the box. 

In real terms this means that things like CompletableFuture appear to work normally, but then suddenly stop working if you have enough of a workload to trigger a new thread creation.

**Comment by bobmcwhirter** [comment]
I believe this was fixed by

https://github.com/oracle/graal/commit/e78fc21f53488848f791dca3db394031698177f2

**Comment by cstancu** [comment]
Thanks @bobmcwhirter, I'll close this. @stuartwdouglas please reopen if still an issue.
