### ISSUE TITLE
`org.graalvm.polyglot.Engine` auto-registers its `close` method in the shutdown hooks when built with `Engine.newBuilder` without giving us the option to change this behaviour

### ISSUE THREAD

**Issue by guizmaii** [oracle/graal#6608]
**Describe the issue**
The `org.graalvm.polyglot.Engine` auto-registers its `close` method in the shutdown hooks when built with `Engine.newBuilder` without giving us the option to change this behaviour, preventing us from controlling when we want to close the `Engine`.

It doesn't seem that there's a method in the `Engine.Builder` to change this behaviour.

We see in the `Engine::newEngine` method that if we pass `false` to the `registerInActiveEngines` this behaviour can be disabled:
<img width="899" alt="Screenshot 2023-05-16 at 4 24 26 pm" src="https://github.com/oracle/graal/assets/1193670/a60275dd-ab57-4dec-921e-7aa944ee2c44">

But the `Engine.Builder.build()` method seems to always set this value to `true` (highlighted in red):
<img width="1616" alt="Screenshot 2023-05-16 at 4 23 42 pm" src="https://github.com/oracle/graal/assets/1193670/dc0706ce-7d06-4c5c-9ee6-b1cebf7a1531">

**Describe GraalVM and your environment:**
 - GraalVM version: CE 22.3.2
 - JDK major version: 17

**Comment by chumer** [comment]
The `registerInActiveEngines` is used in closed source to implement polyglot isolates, but not intended to be used from the outside.

Why would you want to disable the shutdown hook registration?

**Comment by guizmaii** [comment]
Because we're writing FP code with libs like [ZIO](https://zio.dev/) in which we control the opening and closing of resources.
It's important as we're using concurrency a lot and need to have clear control over how and when resources are opened and closed.

For this `Engine` resource, leaving the control to the automatic shutdown hook is kind of ok in most cases as we'll probably always boot an Engine in the boot sequence of the program and reuse it everywhere, only closing it at the end of the program.

But it's a problem when you want to write benchmarks and you want a new/clean Engine for each benchmark

**Comment by chumer** [comment]
> I think that, even just philosophically, not giving the control over this to the user is an issue.

The shutdown hook only causes effects if `Engine.close()` was not explicitly called.  The shutdown hook is mainly used to print stuff for debug flags and flushing the log handler in case the user did not call close() manually.

> I understand that in a more traditional Java world, people don't want to bother with / don't care about this kind of thing.

We care a lot about ownership and avoiding opinionated behavior in the polyglot API.

**Comment by guizmaii** [comment]
> Do you have an actual problem with this shutdown-hook? Causing some effects you don't like?

It was a long time ago and I'm not working at the company where we were having the issue anymore but, IIRC, one of the two closings (our manual one or the hook one) was printing an error in the logs (not sure if it was logged as an error or just a normal log). That was the main issue.

Well, I guess, in regard to what you said, I think we can close this ticket.
It seems that the hook is behaving well with any manual closing that would have happened before.
