### ISSUE TITLE
MS Windows Build

### ISSUE THREAD

**Issue by sirinath** [oracle/graal#663]
It is possible to add MS Windows builds for direct download to: https://www.graalvm.org/downloads/

**Comment by dougxc** [comment]
Hi @sirinath we don't yet have Windows builds of GraalVM but rest assured, we're working on it. The downloads will show up at that URL as soon as they're available. Please close this issue if that answers your question.

**Comment by sirinath** [comment]
When can we expect the release?

**Comment by dougxc** [comment]
If all goes according to our estimates, we hope to have a release by the end of 2018.
