### ISSUE TITLE
about org.graalvm.nativeimage.Feature

### ISSUE THREAD

**Issue by fujohnwang** [oracle/graal#665]
I see javadoc of `org.graalvm.nativeimage.Feature` mentioned that `Features explicitly specified on the command line.`, but I can't find any information which command line argument name to use.

I run `native-image --help` and didn't find any arg name for this, and although I saw demo code here([https://github.com/oracle/graal/blob/master/substratevm/REFLECTION.md](https://github.com/oracle/graal/blob/master/substratevm/REFLECTION.md)), but I still don't know how to link it to native-image at build time.

who will please enrich doc or demo on this?  That will help a lot. ^_^

**Comment by fujohnwang** [comment]
and since it's located at package `org.graalvm.nativeimage`, where can I find it? which jar or dependency artifact should I add to classpath?

**Comment by cstancu** [comment]
You need the `-H:Features=` option. 

There are several levels of `help`: 

```
native-image --help
native-image --help-extra
native-image --expert-options
native-image --expert-options-all
```

Under the last level you can find all the options currently available, including:

```
-H:Features="" Comma-separate list of fully qualified Feature implementation classes.
```

`org.graalvm.nativeimage` is part of the `graal-sdk.jar` which is automatically added to the classpath when you run the `javac` command shipped with GraalVM and also when you run the `native-image` command. `graal-sdk.jar` is located under the GraalVM directory `${GRAALVM_HOME}/jre/lib/boot/graal-sdk.jar`.

**Comment by fujohnwang** [comment]
@cstancu Many Thanks, this helps  a lot 👍
