### ISSUE TITLE
Docs apply `javascript` to blocks by default

### ISSUE THREAD

**Issue by abelsromero** [oracle/graal#6685]
**Describe the issue**

You can see some coloring being applied to normal verbatim blocks that have no language set https://github.com/oracle/graal/blob/f749c67d655734b5ca8d047b289c5faf5acb75eb/docs/reference-manual/native-image/guides/use-system-properties.md?plain=1#L74.
And on inspection of the HTML, it seems to apply `javascript` class.

https://www.graalvm.org/latest/reference-manual/native-image/guides/use-system-properties/

<img width="1094" alt="image" src="https://github.com/oracle/graal/assets/5781153/a5943d29-231b-489d-966e-c8b754fc9fef">

**Steps to reproduce the issue**
n/a

**Describe GraalVM and your environment:**
n/a

**More details**
n/a

**Comment by fniephaus** [comment]
Thanks for the report, @abelsromero. We'll look into a fix for this.

**Comment by abelsromero** [comment]
Feel free to change labels "bug" report was the closest I could see to report a docs issue.

**Comment by fniephaus** [comment]
Thanks, but this looks like a bug to me too :)

**Comment by olyagpl** [comment]
@abelsromero, a workaround was applied to prevent this inappropriate highlighting on the _dev_ documentation version:
https://www.graalvm.org/dev/reference-manual/native-image/guides/use-system-properties/. Thank you for the report.
