### ISSUE TITLE
GraalVM Swing still does not work + instructions too complicated

### ISSUE THREAD

**Issue by risharde** [oracle/graal#6686]
**Describe the issue**
Compiling a very simple SWING application created under ant using SWING (JPanel) compiles but FATALLY errors out on execution.

**Steps to reproduce the issue**
Step 1 - Install Netbeans 17.
Step 2 - New project under Java ANT - Select Java Application
Step 3 - Add a JFrameForm by right clicking to get context menu.
Step 4 - Add code in main to open the JFrameForm
Example:
JFrameForm jframe_form = new JFrameForm();
jframe_form.setVisible(true);

**Describe GraalVM and your environment:**
 - GraalVM version: 17 (Windows)
 - JDK major version: 17
 - OS: Windows 11 Pro
 - Architecture: AMD64

**More details**
This has been expressed by users and 2 years later - THIS IS STILL A PROBLEM. 
The proposed solution to add the JAVA_HOME didn't work for me. Neither is this sensible unless I have misunderstood the purpose of native-image - which is to created a binary that is not dependent on the external JDK.

Additionally to fix this seems too complicated - not even compiling a C program is this difficult. Why is no one making compiling and resolving automatically better? There is no way I will continue to use this in the 21st century. I cannot wait 2 more years for the developer team at Oracle or otherwise to resolve this. Absolutely frustrating - if you want better adoption - I strongly suggest the team rethinks all the innovation being made and Youtube boasts and make this an easier tooling to use AND STOP CLOSING THESE THREADS WITHOUT PROPER RESOLUTION!

```
Exception in thread "main" java.lang.NoSuchMethodError: java.awt.Toolkit.getDefaultToolkit()Ljava/awt/Toolkit;
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.jni.functions.JNIFunctions$Support.getMethodID(JNIFunctions.java:1259)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.jni.functions.JNIFunctions$Support.getMethodID(JNIFunctions.java:1244)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.jni.functions.JNIFunctions.GetStaticMethodID(JNIFunctions.java:413)
        at java.desktop@17.0.7/java.awt.Toolkit.initIDs(Toolkit.java)
        at java.desktop@17.0.7/java.awt.Toolkit.initStatic(Toolkit.java:1425)
        at java.desktop@17.0.7/java.awt.Toolkit.<clinit>(Toolkit.java:1397)
        at java.desktop@17.0.7/java.awt.Component.<clinit>(Component.java:624)
        at java.base@17.0.7/java.lang.Class.ensureInitialized(DynamicHub.java:528)
        at java.base@17.0.7/java.lang.Class.ensureInitialized(DynamicHub.java:528)
        at java.base@17.0.7/java.lang.Class.ensureInitialized(DynamicHub.java:528)
        at java.base@17.0.7/java.lang.Class.ensureInitialized(DynamicHub.java:528)
        at java.base@17.0.7/java.lang.Class.ensureInitialized(DynamicHub.java:528)
        at remoteaccess.RemoteAccess.main(RemoteAccess.java:24)
```

**Comment by risharde** [comment]
For those of you experiencing the same issue - this BRIEF and TO THE POINT article explains how to hopefully get your AWT / SWING apps working (while it may not work 100% - the simple app I complained about worked using this).

https://www.praj.in/posts/2021/compiling-swing-apps-ahead-of-time/

This works for Windows as well. Thankfully someone didn't make this into rocket science!
I will test more complicated code to see if this is a viable solution and hopefully provide more updates.

**Comment by fniephaus** [comment]
We are aware that compiling AWT and Swing applications to native is not straightforward and we are working on this as much as our time allows (see https://github.com/oracle/graal/issues/4921 for example). Nonetheless, I don't think your comments are fair.

GraalVM is an open-source project. As such, you are more than welcome to contribute code and improve our documentation (for example, consider contributing [a guide](https://github.com/oracle/graal/tree/115f645cdf32f593cfa60938b1c7b40d7bbb9f76/docs/reference-manual/native-image/guides) or [a demo](https://github.com/graalvm/graalvm-demos/) based on your knowledge). We also welcome feedback and suggestions from the community, as long as it is [respectful](https://www.graalvm.org/community/conduct/). At the same time, however, our team at Oracle Labs has to prioritize and AWT/Swing use cases aren't our top priority at the moment. I hope you understand.

We want to keep the environment of our community positive and respectful, and discussions both technical and constructive. If you want tickets like this not to be closed immediately, consider following our [code of conduct](https://www.graalvm.org/community/conduct/).

**Comment by rubyFeedback** [comment]
> this BRIEF and TO THE POINT article explains how to hopefully get your AWT / SWING apps working

I read that article before as well, but unfortunately I could not get it to work. Although my Java knowledge got better in the last some weeks or so, there are still many things I don't fully understand yet.

I myself, for the time being, transitioned into jruby + SWING, which actually works quite well; and my use cases are for small Java apps, mostly for elderly relatives who have to work on windows. For such use cases jruby is fine. Of course I'd love if I could compile a single .exe via GraalVM have it work, and hopefully that works one day. Meanwhile I'll continue to explore jruby + SWING, for GUIs on windows (and that really works, I was surprised how easy it was too).

> Is it that the Oracle team does not get paid to make this software even though it is open sourced?

I think it may not be of highest priority as such, so it'll be slow moving. We have to be realistic too: the world wide web is a more important focus, and many folks will probably use SWT or JavaFX. So we may be a niche group.

**Comment by ctoabidmaqbool** [comment]
I am a much fan of Javafx over old GUI style e.g. Swing/AWT. But unfortunately manay libraries are still dependent upon Swing/AWT. 

And still Swing/AWT is not usable 100% in GraalVM. Making apps using GraalVM is like inventing the technology rather then focusing on oring problem e.g. createing own Apps!

https://github.com/praj-foss/swing-graalvm-demo/issues/3
