### ISSUE TITLE
[GR-46741] `NoClassDefFoundError` thrown on the JVM but not with native image

### ISSUE THREAD

**Issue by sdeleuze** [oracle/graal#6691]
When a class constructor uses another class not present in the classpath, `getDeclaredConstructors` throws a `NoClassDefFoundError` on the JVM while on native, when related reflection config is specified, no exception is thrown and no constructor is found. This prevents proper support of agent testing in Spring, see https://github.com/spring-projects/spring-framework/issues/30511 related issue. I would expect consistent behavior between JVM and native, so native versions throws a `NoClassDefFoundError` too.

**Steps to reproduce the issue**
The attached repro works on the JVM with `./gradlew test` and fails on native with `./gradlew nativeTest`.
[repro.zip](https://github.com/oracle/graal/files/11575823/repro.zip)

**Describe GraalVM and your environment:**
Reproduced with [GraalVM CE 23.0.0-dev-20230522_1321](https://github.com/graalvm/graalvm-ce-dev-builds/releases/tag/23.0.0-dev-20230522_1321).

**Comment by oubidar-Abderrahim** [comment]
Hi, Thank you for reporting this, we'll take a look into this shortly

**Comment by oubidar-Abderrahim** [comment]
Tracked internally on GR 46741

**Comment by loicottet** [comment]
This was fixed by #8021.
