### ISSUE TITLE
VisualVM / GraalVM or IntelliJ Idea IDE bug - thread dump exception

### ISSUE THREAD

**Issue by gaal-dev** [oracle/graal#672]
Hi.

I debugged my application using Intellij Idea IDE. It has a plugin named as "Visual launcher".And I've got a GraalVM exception when I tried to make a heap dump. It happens if you try to debug and to use VisualVM simultaneously.

And I understood how it works, but it not obvious:) IDE debugging process stops all threads in VisualVM too. You can close this issue if nothing is found.

1) I set the first breakpoint and ran an application "Debug with VisualVM". VisualVM "hangs". (https://plugins.jetbrains.com/plugin/7115-visualvm-launcher)
2) I set the second breakpoint and continued (F9). VisualVM opened windows and showed the info about the application.
3) In VisualVM I chose "Sampler + Memory". It worked fine when I press F8 in Idea IDE.
4) In VisualVM I chose "Monitor + Heap" dump and got an exception.

So can be an IDE bug. The collected logs are attached. I notified them too.

**Comment by spavlusieva** [comment]
hi @gaal-dev , this issue has been inactive for more than 180 days. We’ll close it to focus on current issues. In case it’s still relevant, please reopen it and we’ll take another look. Thank you!
