### ISSUE TITLE
Inspector script uri makes it impossible to debug on vscode

### ISSUE THREAD

**Issue by pmlopes** [oracle/graal#677]
When debugging with vscode using the inspector protocol, vscode can only debug using the loaded scripts from the server in read only mode.

Vscode solved this by introducing 2 variables:

* localRoot
* remoteRoot

```json
{
    "type": "node",
    "request": "attach",
    "name": "Attach to remote",
    "address": "TCP/IP address of process to be debugged",
    "port": "9229",
    "localRoot": "${workspaceFolder}",
    "remoteRoot": "C:\\Users\\John\\project\\server"
}
```

So file are resolved by replacing the given roots depending on the direction we are looking.

Now getting graalvm mapped would be easy if the loaded scripts did not have a random UUID in the path, as vscode has standardized on strings for the launcher configuration for all languages.

I believe that the current format:

```
truffle:UUID/path/file.js
```

Should either drop the UUID or make it optional / configurable.

**Comment by pmlopes** [comment]
`vscode` reference for remote debugging: https://code.visualstudio.com/docs/nodejs/nodejs-debugging#_remote-debugging

Say for example that the UUID segment is removed that I expect that the configuration:

```json
{
    "type": "node",
    "request": "attach",
    "name": "Attach to remote",
    "address": "TCP/IP address of process to be debugged",
    "port": "9229",
    "localRoot": "${workspaceFolder}",
    "remoteRoot": "truffle:"
}
```

would work for `JavaScript` and `Python` out of the box...

**Comment by spavlusieva** [comment]
hi @pmlopes , this issue has been inactive for more than 180 days. We’ll close it to focus on current issues. In case it’s still relevant, please reopen it and we’ll take another look. Thank you!
