### ISSUE TITLE
Value.GetMemberKeys() does not include functions in class

### ISSUE THREAD

**Issue by MichaelHaibinXie** [oracle/graal#678]
I have a function in class, Value.GetMember("functionName") returns true, however Value.getMemberKeys() does not include "functionName" in the keys.

Here is the code that I tried, any idea?

----------Test.java-----------
    Value v = polyglot.eval(Source.newBuilder("js", new File(jsHome + "/college.js")).build());
    Value v1 = polyglot.eval("js", "new College()");
    // *****************this returns true
    System.out.println("is there setName member? " + v1.hasMember("setName"));
   
   // ******************Problem: this does not contain setName function
    System.out.println("all member keys: " + v1.getMemberKeys());

----------College.js-----------
class College {
    constructor() {
        this.name = "defaultcollege";
        this.students = [];
    }

    setName(name) {
        this.name = name;
    }

    getName() {
        return this.name;
    }
    
    addStudent(student) {
        this.students.push(student);
    }

    getStudents() {
        return this.students;
    }

    toString() {
        return this.name + this.students;
    }
}

**Comment by chumer** [comment]
Yes. Non enumerable JS properties currently don't show up in the member keys. We will change that but it currently needs some extension to our interop protocol..

**Comment by MichaelHaibinXie** [comment]
I use CE RC5 version and looks like it works. One follow up question, is there any way to scan parameters of a function? in the example if I get Value representing the fuction by Value.getMember("setName"), can I scan parameters from the Value. I saw it has a member arguments, but when I try to getMember("arguments") it throws exception.

**Comment by MichaelHaibinXie** [comment]
To be more specific, originally I was using ee rc6 when having this issue.

**Comment by MichaelHaibinXie** [comment]
I dont have the exception now as I switched to RC5. I will post later if I see it again. Thanks for help. 

Is there a way to scan parameters of member that is a function?

**Comment by quinton-hoole-2** [comment]
@chumer Was this ever fixed?  I still seem to be seeing the same problem in community RC14.  If not, any estimate on when or if it might ever get fixed?

**Comment by chumer** [comment]
@quinton-hoole-2 Unfortunately no. It takes longer because it involves some interop protocol changes. The way to do this atm is by calling a JavaScript method that returns all the symbols. You can then read/write or invoke them.

**Comment by quinton-hoole-2** [comment]
Thanks @chumer.  We'll use that workaround in the mean time.

**Comment by boris-spas** [comment]
Tracking internally as Issue GR-20913

**Comment by spavlusieva** [comment]
hi @MichaelHaibinXie , this issue has been inactive for more than 180 days. We’ll close it to focus on current issues. In case it’s still relevant, please reopen it and we’ll take another look. Thank you!
