### ISSUE TITLE
calling java.awt.Desktop.isDesktopSupported() lead to SIGSEGV

### ISSUE THREAD

**Issue by SubOptimal** [oracle/graal#679]
When calling the method `java.awt.Desktop.isDesktopSupported()` the JVM crashes with a SIGSEGV.

```
#  SIGSEGV (0xb) at pc=0x00000000000011e0, pid=1820, tid=0x00007f34f3cad700
#
# JRE version: OpenJDK Runtime Environment (8.0_172-b11) (build 1.8.0_172-20180625212755.graaluser.jdk8u-src-tar-g-b11)
# Java VM: GraalVM 1.0.0-rc6 (25.71-b01-internal-jvmci-0.48 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  0x00000000000011e0
```
Code to reproduce the issue
```
class IsDesktopSupported {
    public static void main(String...args) {
        System.out.println(java.awt.Desktop.isDesktopSupported());
    }
}
```
compile and execute as

    javac IsDesktopSupported.java
    java IsDesktopSupported

[hs_err_pid13597.log](https://github.com/oracle/graal/files/2397012/hs_err_pid13597.log)

**Comment by SubOptimal** [comment]
@dougxc I added the file to the original post. It was executed on a machine running `Debian GNU/Linux testing (buster)`. The snippet runs fine with Java 8, 9, 10, 11.

**Comment by dougxc** [comment]
Looking at the crash log, this happens before any Graal compilation could occur. It might be something in the way we build the base JDK. Can you see if it reproduces using the both the product and fastdebug binaries at https://github.com/graalvm/openjdk8-jvmci-builder/releases/tag/jvmci-0.48. Also, does this happen everytime on RC6?

**Comment by SubOptimal** [comment]
Looks like they crash at the same place

[hs_err_openjdk1.8.0_172-jvmci-0.48.log](https://github.com/oracle/graal/files/2398050/hs_err_openjdk1.8.0_172-jvmci-0.48.log)
[hs_err_openjdk1.8.0_172-jvmci-0.48-fastdebug.log](https://github.com/oracle/graal/files/2398051/hs_err_openjdk1.8.0_172-jvmci-0.48-fastdebug.log)

It fails on each run.

**Comment by dougxc** [comment]
Which other exact OpenJDK8 binaries have you tried this on?

**Comment by dougxc** [comment]
@gilles-duboscq could this point to an issue in the way we build these binaries?

**Comment by SubOptimal** [comment]
Following other Java 8 version where used

    OpenJDK Runtime Environment (build 1.8.0_171-8u171-b11-2-b11)
    OpenJDK 64-Bit Server VM (build 25.171-b11, mixed mode)

    Java(TM) SE Runtime Environment (build 1.8.0_172-b11)
    Java HotSpot(TM) 64-Bit Server VM (build 25.172-b11, mixed mode)

    OpenJDK Runtime Environment (Zulu 8.30.0.1-linux64) (build 1.8.0_172-b01)
    OpenJDK 64-Bit Server VM (Zulu 8.30.0.1-linux64) (build 25.172-b01, mixed mode)

**Comment by dougxc** [comment]
@SubOptimal we're having a problem reproducing this crash on any of the Linux systems we have at our disposal. Do you have access to other Linux versions you can try to reproduce on?

For what it's worth, this appears to be the code it is crashing in: http://hg.openjdk.java.net/jdk8u/jdk8u/jdk/file/2a041b1f858d/src/solaris/native/sun/xawt/awt_Desktop.c#l38

**Comment by gilles-duboscq** [comment]
`gtk-x11-2.0` is not loaded so i suspect `gtk2_load` returned `false`. However `gnomevfs-2` is loaded so it probably went down into [`gnome_load`](http://hg.openjdk.java.net/jdk8u/jdk8u/jdk/file/2a041b1f858d/src/solaris/native/sun/xawt/gnome_interface.c). `gnome-2` is not loaded, so either it was not available or it crashed earlier in `gnome_vfs_init`.

**Comment by SubOptimal** [comment]
I could break it down a bit.

It's seems to be related to the library `jre/lib/amd64/libfreetype.so.6` bundled in `GraalVM 1.0.0-rc6 `. Which is a dependency of the library `libfontmanager.so`. This is also the case in `Zulu 8.30.0.1-linux64`.  Contrary this dependency does not exist in `OpenJDK 1.8.0_171-8u171-b11` nor in `Oracle Java 1.8.0_172-b11`.

When I replace
```./graalvm-ce-1.0.0-rc6/jre/lib/amd64/libfreetype.so.6```
with the version
```./zulu8.30.0.1-jdk8.0.172-linux_x64/jre/lib/amd64/libfreetype.so.6```
then the snippet runs as expected.

Examining the libraries with 

    ldd ./graalvm-ce-1.0.0-rc6/jre/lib/amd64/libfreetype.so.6 \
        ./zulu8.30.0.1-jdk8.0.172-linux_x64/jre/lib/amd64/libfreetype.so.6

shows as difference that the library from the GraalVM has a dependency to `libz.so.1`

```
./graalvm-ce-1.0.0-rc6/jre/lib/amd64/libfreetype.so.6:
	linux-vdso.so.1 (0x00007fff9edcf000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007fd20b684000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fd20b4c7000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fd20ba64000)

./zulu8.30.0.1-jdk8.0.172-linux_x64/jre/lib/amd64/libfreetype.so.6:
	linux-vdso.so.1 (0x00007ffde56de000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f1361018000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f13614bb000)
```

**Comment by SubOptimal** [comment]
Where the bundled `libfreetype.so.6` is comming from?

When I rename it and let `libfontmanager.so` chose the version which exists in the Linux distribution

    ldd libfontmanager.so
    ...
    libfreetype.so.6 => /usr/lib/x86_64-linux-gnu/libfreetype.so.6 (0x00007fbabbedc000)

(libfreetype.so.6 is a link to libfreetype.so.6.15.0)

Then the SIGSEGV is gone. Maybe `libfreetype` don't need to be bundled.

**Comment by SubOptimal** [comment]
@gilles-duboscq Thanks for your reply.
I have two cases (Ubuntu Bionic with Mate, Debian Buster with Gnome 3) where it's existence in GraalVM lead into a SIGSEGV. The library is not included in the OpenJDK builds of the distribution.

    openjdk-8-jdk_8u181-b13-0ubuntu0.18.04.1_amd64.deb
    openjdk-8-jdk_8u171-b11-2_amd64.deb

The library is included in the Azul Zulu OpenJDK, but this one does not lead into a SIGSEGV.

Could you share the information in which Distribution the library is needed to prevent a SIGSEGV. I would like to have a look what's different to the mentioned two.

**Comment by spavlusieva** [comment]
hi @SubOptimal , this issue has been inactive for more than 180 days. We’ll close it to focus on current issues. In case it’s still relevant, please reopen it and we’ll take another look. Thank you!
