### ISSUE TITLE
Will GraalVM release a JVM 11 version of the new packages including native-image?

### ISSUE THREAD

**Issue by anthonydahanne** [oracle/graal#6826]
**Feature request**

**Is your feature request related to a problem? Please describe.**
Recently, [GraalVM team announced](https://medium.com/graalvm/a-new-graalvm-release-and-new-free-license-4aab483692f5) new packaging including `native-image` for both Java 17 ans 20.

**Describe the solution you'd like.**
I would like the same packaging, including `native-image` for Java 11 as well

**Describe who do you think will benefit the most.**
GraalVM users, GraalVM contributors, developers of libraries and frameworks which depend on GraalVM

**Describe alternatives you've considered.**
Deprecating Java 11 GraalVM releases?

**Comment by fniephaus** [comment]
Hi @anthonydahanne, thanks for the suggestion. I can see why you'd like the same packaging for Java 11, but I'm afraid we can't backport such a change/feature to the 22.3 release anymore.
I recommend you upgrade to Java 17 or later if you'd like to use the simplified packaging.
