### ISSUE TITLE
Native Image JNI ExceptionOccurred not set when calling FromReflectedMethod on a method not registered for JNI access

### ISSUE THREAD

**Issue by mikehearn** [oracle/graal#6842]
To reproduce:

1. Write some C++ that uses the JNI invocation API to load classes from a native image shared library.
2. Call into Java and get it to reflect a method. Make sure that the method being reflected is registered for reflection lookup but not JNI access in the config JSON.
3. Store the returned `Method` object in a static field.
4. Use JNI to grab the `Method` object.
5. Use `env->FromReflectedMethod` to get a `jmethodid` from that method.
6. Call `env->ExceptionOccurred()`

Expected results:

`true` and the error text can be described.

Actual results:

The returned `jmethodid` is null and `ExceptionOccurred()` returns false indicating nothing went wrong.

**Comment by oubidar-Abderrahim** [comment]
Hi, Thank you for reporting this, please share the following:

- What version of GraalVM you are using? have you tried with the latest build?
- Have you tried generating the JNI config using the Tracing agent? if not please do so.
- Can you share a reproducer code to use for verification? 

Thank you

**Comment by mikehearn** [comment]
Latest Oracle GraalVM. JNI config wasn't produced with tracing agent. A reproducer is hard to share but I believe the description contains all information necessary to track down the bug.

**Comment by oubidar-Abderrahim** [comment]
It would be much appreciated if you can assemble a small example that illustrates this bug. this should make it easier to identify and fix the issue

**Comment by oubidar-Abderrahim** [comment]
Any updates?

**Comment by mikehearn** [comment]
I'll take care of this myself soon.

**Comment by mikehearn** [comment]
On further examination, this behavior does technically follow the JNI spec, even though it's quite annoying. It isn't stated explicitly that if something goes wrong here an exception will be raised. This is a bit of an edge case. I'm not sure it should be fixed in the end.
