### ISSUE TITLE
Backport Request: Fix JFR constant pool ID bug

### ISSUE THREAD

**Issue by roberttoyonaga** [oracle/graal#6856]
The original PR https://github.com/oracle/graal/pull/6799 describes the problem (internal PR https://github.com/oracle/graal/pull/6805). It's been present in previous GraalVM versions but has only been caught by recent tests. This problem could manifest in 23.0 and so should be backported to that version. 

I can create a PR backporting the fix to the 23.0 release branch you agree its ok.

/cc @gilles-duboscq @ezzarghili as per https://github.com/oracle/graal/discussions/4332#discussioncomment-2361015

**Comment by oubidar-Abderrahim** [comment]
Hi @christianhaeubl, could you please take a look at this? Thank you

**Comment by christianhaeubl** [comment]
@roberttoyonaga: thanks, the fix will get backported in the next few days. There is no need to create an extra PR.

**Comment by zakkak** [comment]
Hi @christianhaeubl, can you please share the commit hash(es) of the backport?

https://github.com/oracle/graal/tree/release/graal-vm/23.0 doesn't seem to include it.
