### ISSUE TITLE
[native-image] Error for opaque structs: invalid application of 'sizeof' to an incomplete type

### ISSUE THREAD

**Issue by dpetrick** [oracle/graal#686]
Type of issue: Bug
Environment:
- GraalVM Version 1.0.0-rc6
- MacOs Sierra 10.12.6

We're using the Graal C-API to call Rust functions, exposed in C-style header files, for example:

```
#include <stdlib.h>

typedef struct Greeter Greeter;

const char *greet(const Greeter *greeter, const char *name);

Greeter newGreeter(const char *phrase);
```

The Greeter struct is opaque, and doesn't expose any fields, as we only want to handle pointers to this struct.
Using this header file, our compilation fails with :
```
error: Error compiling query code (in /var/folders/kk/g_m203853j5b4fjj_2c6dhym0000gn/T/SVM-446576004956640517/CIntegrationDirectives.c). Compiler command  gcc /var/folders/kk/g_m203853j5b4fjj_2c6dhym0000gn/T/SVM-446576004956640517/CIntegrationDirectives.c -o /var/folders/kk/g_m203853j5b4fjj_2c6dhym0000gn/T/SVM-446576004956640517/CIntegrationDirectives output included error: /var/folders/kk/g_m203853j5b4fjj_2c6dhym0000gn/T/SVM-446576004956640517/CIntegrationDirectives.c:35:96: error: invalid application of 'sizeof' to an incomplete type 'Greeter' (aka 'struct Greeter')
    C file contents around line 35:
    /var/folders/kk/g_m203853j5b4fjj_2c6dhym0000gn/T/SVM-446576004956640517/CIntegrationDirectives.c:34: int main(void) {
    /var/folders/kk/g_m203853j5b4fjj_2c6dhym0000gn/T/SVM-446576004956640517/CIntegrationDirectives.c:35:     printf("NativeCodeInfo:CIntegrationDirectives:StructInfo:Greeter:PropertyInfo:size=%lu\n", sizeof(Greeter));
    /var/folders/kk/g_m203853j5b4fjj_2c6dhym0000gn/T/SVM-446576004956640517/CIntegrationDirectives.c:36:     return 0;
```

The info we get from this error is `error: invalid application of 'sizeof' to an incomplete type 'Greeter' (aka 'struct Greeter')`. After not knowing what to do about this error, we changed the header file to use `typedef struct Greeter {} Greeter;` instead of `typedef struct Greeter Greeter;`, and our program compiles and executes as expected. We're no C experts, but the header looks valid and should be usable in it's original form in Graal - are we missing something, or is this is a bug in Graal?

We have a repository containing the reproduction here: https://github.com/dpetrick/GraalBugReproduction

Thank you!

**Comment by dpetrick** [comment]
Thank you @christianwimmer, much appreciated!

FYI this works if we have `typedef struct Greeter Greeter;`
```java:
@CStruct(value = "Greeter", isIncomplete = true)
public interface Greeter extends PointerBase {}
```

This, however, does _not_ work, and requires us to add `{}` back to the header file:
```java:
@CPointerTo(nameOfCType = "Greeter")
public interface Greeter extends PointerBase {}
```
The error loooks to be the same / similar:
```
error: Error compiling query code (in /var/folders/kk/g_m203853j5b4fjj_2c6dhym0000gn/T/SVM-9157290472124497284/CIntegrationDirectives.c). Compiler command  gcc /var/folders/kk/g_m203853j5b4fjj_2c6dhym0000gn/T/SVM-9157290472124497284/CIntegrationDirectives.c -o /var/folders/kk/g_m203853j5b4fjj_2c6dhym0000gn/T/SVM-9157290472124497284/CIntegrationDirectives output included error: /var/folders/kk/g_m203853j5b4fjj_2c6dhym0000gn/T/SVM-9157290472124497284/CIntegrationDirectives.c:35:99: error: invalid application of 'sizeof' to an incomplete type 'Greeter' (aka 'struct Greeter')
    C file contents around line 35:
    /var/folders/kk/g_m203853j5b4fjj_2c6dhym0000gn/T/SVM-9157290472124497284/CIntegrationDirectives.c:34: int main(void) {
    /var/folders/kk/g_m203853j5b4fjj_2c6dhym0000gn/T/SVM-9157290472124497284/CIntegrationDirectives.c:35:     printf("NativeCodeInfo:CIntegrationDirectives:PointerToInfo:Greeter:PropertyInfo:size=%lu\n", sizeof(Greeter));
    /var/folders/kk/g_m203853j5b4fjj_2c6dhym0000gn/T/SVM-9157290472124497284/CIntegrationDirectives.c:36:     return 0;
Error: Image building with exit status 1
make: *** [build] Error 1
```

If this is expected, then this question can be considered solved.

As a side note, we would love to have the annotations you mentioned included in the tutorial: https://github.com/oracle/graal/blob/master/substratevm/src/com.oracle.svm.tutorial/src/com/oracle/svm/tutorial/CInterfaceTutorial.java.

**Comment by christianwimmer** [comment]
You are correct, the `@CPointerTo` also tries to find out the size of the C element that it points to. That is unnecessary if the Java type has no accessor method, but also not a big problem since the `@CStruct` with `isIncomplete = true` is the better approach anyway.
