### ISSUE TITLE
Allow compare polyglot objects from java

### ISSUE THREAD

**Issue by pmlopes** [oracle/graal#688]
It would be nice to have the possibility of doing equality checks with the `polyglot` api. One example would be to compare polyglot objects at the host (java) side.

Currently the `Value` class equals method is comparing the wrapper instance instead of the wrapped object.

As a suggestion the `js` types would follow Javascript `===` semantics, `llvm` maybe the pointer memory address, and if the wrapped value is a host object then delegate to the wrapped `equals`...

**Comment by chumer** [comment]
Thanks for creating the issue Paulo.

The current workaround is to do: `value.as(Map.class).equals(otherValue.as(Map.class)` to compare objects.

**Comment by boris-spas** [comment]
Tracked internally as Issue GR-20795.

**Comment by chumer** [comment]
This will be supported in 20.2
