### ISSUE TITLE
Option to list the included resources (from -H:IncludeResources)

### ISSUE THREAD

**Issue by royvanrijn** [oracle/graal#689]
I've been struggling with the regex used in the `native-image` command line option `-H:IncludeResources`. I thought some resources were included but it turns out they weren't.

In the end I checked out the inclusion code from GitHub and ran it myself with the regex to list all the resources myself. This was useful, maybe it is possible to add a command line option to list all the included resources from `native-image`? Or have an option that shows all the resources and if it matches yes/no.

**Comment by olpaw** [comment]
This is now available as `-H:Log=registerResource:`. See updated docu
https://github.com/oracle/graal/blob/master/substratevm/RESOURCES.md

**Comment by jglick** [comment]
I added this option but it does not seem to do anything; no output message mentions anything about resources. Am I missing something?

(I used `-H:IncludeResources=…` and it did fix my bug, so presumably there _was_ some resource being included. I am just not seeing anything about it in `native-image` output.)
