### ISSUE TITLE
Allow Java classes to be extended by guest languages

### ISSUE THREAD

**Issue by hymanroth** [oracle/graal#6902]
**Feature request**

Jruby allows additional attributes and methods to be added to a Java class. We are considering porting a large project from JRuby to Graal/Truffle but we have thousands of lines of legacy code which depend on Java classes which have been extended (monkey patched) using JRuby.

See this stackoverflow question I posted which includes examples: https://stackoverflow.com/questions/76567012/extending-monkey-patching-java-classes-in-truffle-ruby

If, for technical  reasons, it is not possible for Java classes to be extended I would be very grateful if someone could suggest a workaround because right now we're stuck.

I imagine this issue could cause problems for other people trying to port projects from Jruby....

Thanks.

**Comment by oubidar-Abderrahim** [comment]
Hi, Thank you for your suggestion, we'll take a look into it shortly

**Comment by eregon** [comment]
Let's track this in https://github.com/oracle/truffleruby/issues/3139
I think this cannot reasonably be solved in Truffle, or not only, so better to track it as a TruffleRuby issue.
