### ISSUE TITLE
Potential bug in IntegerEqualsNode create method

### ISSUE THREAD

**Issue by default-jamc** [oracle/graal#6907]
# Overview

Hi,

I think there may be a (possibly unreachable?) bug in one of the optimisations / transformations in the `create()` method for `IntegerEqualsNode`. The optimisations are:

```java
((a == b) ? t : f) == t |-> (a == b)
t == ((a == b) ? t : f) |-> (a == b)

((a == b) ? t : f) == f |-> !(a == b)
f == ((a == b) ? t : f) |-> !(a == b)
```

These optimisations don't check that `t` and `f` aren't equal after they're evaluated. If `t` and `f` evaluate to the same value, the first two optimisations don't hold when `(a != b)`, and the last two don't hold when `(a == b)`.

## Example Program
Running the test below and putting a breakpoint at the end of `testErrorOpt` to inspect the `lastCompiledGraph` shows that `test3` has a section which matches the form of the first optimisation: 

`((ReadNode(field) == 0) ? 0xFFFF : ReadNode(field)) == 0xFFFF`

where `field = 0xFFFF`. 

```java
    private static int field = 0xFFFF;

    public static int test3(int arg) {
        int result = 0;
        int val = (field == 0) ? arg : field;
        if (val == arg) {
            result = arg;
        }
        return result;
    }

    @Test
    public void testErrorOpt() {
        runTest("test3", (0xFFFF));
    }
```

Interestingly, this graph section isn't altered / reached during optimisation (it seems like the `ConditionalNode` appears after the `IntegerEqualsNode` is already created). However if the optimisation were to be applied, it wouldn't hold for `(a != b)` (here, `(ReadNode(field) != 0))`) as:

```java
Optimised:     ((ReadNode(field) == 0) ? 0xFFFF : ReadNode(field)) == 0xFFFF |-> (ReadNode(field) == 0)      = False
Non-optimised: ((ReadNode(field) == 0) ? 0xFFFF : ReadNode(field)) == 0xFFFF |-> (ReadNode(field) == 0xFFFF) = True
```

None of these optimisations seem to be encountered when running the current suite of unit tests (using `mx -d unittest` and breakpoints). However they could produce erroneous results if an expression matching the pattern was encountered in future programs.

**Comment by davleopo** [comment]
thanks @default-jamc  we will have a look, tracked internally as GR-46915

**Comment by rmosaner** [comment]
the erroneous (and never executed) optimization has been removed in #6989
