### ISSUE TITLE
When I use native image to build in the Centos environment

### ISSUE THREAD

**Issue by okboyone** [oracle/graal#6921]
When I use native image to build in the Centos environment, it can be successfully built, but after entering this command, no information will appear. On the Windows system, the information at the time of the build can be displayed

**Comment by okboyone** [comment]
I use the "native-image" command and run it on centos without seeing any output information

**Comment by oubidar-Abderrahim** [comment]
Hi, Thank you for reaching out, could you please share the following information:

- What version of GraalVM you're using?
- The output of `java -version`
- What is the exact version of OS used? output of `uname -a`
- What it the full command you run? (with flags)

**Comment by okboyone** [comment]
java version "17.0.7" 2023-04-18 LTS
Java(TM) SE Runtime Environment Oracle GraalVM 17.0.7+8.1 (build 17.0.7+8-LTS-jvmci-23.0-b12)
Java HotSpot(TM) 64-Bit Server VM Oracle GraalVM 17.0.7+8.1 (build 17.0.7+8-LTS-jvmci-23.0-b12, mixed mode, sharing)

Linux MiWiFi-RA72-srv 5.14.0-284.11.1.el9_2.x86_64 #1 SMP PREEMPT_DYNAMIC Tue May 9 17:09:15 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

native-image --gc=G1 -jar
linux ![image](https://github.com/oracle/graal/assets/102574024/7a56f695-d247-46ec-a029-0277a6ff16d8)
windows  ![image](https://github.com/oracle/graal/assets/102574024/33eecb35-9afc-47aa-95ec-b0a2cc550153)

**Comment by oubidar-Abderrahim** [comment]
Can you share a screenshot of the full output of the command `native-image -jar s7demo-1.0-SNAPSHOT-jar-with-dependencies.jar` on your Centos environment?

**Comment by oubidar-Abderrahim** [comment]
Hi, is this issue still occurring with the latest version of GraalVM for JDK17.0.9?

**Comment by okboyone** [comment]
> 嗨，最新版本的 GraalVM for JDK17.0.9 是否仍然会出现此问题？

yes，the latest version is still the same
