### ISSUE TITLE
Thresholded JFR events in SubstrateVM are not obeying the threshold

### ISSUE THREAD

**Issue by jbachorik** [oracle/graal#6944]
**Describe the issue**
When running a native image application with JFR the recording may get swamped with threads like `Monitor Wait` or `Thread Park` which are very short and should have been ignored according to the threshold limit (the default is 10ms).

**Steps to reproduce the issue**
Run any native image application which is using thread pools with JFR and capture the recording (one such recording is attached).

Here are the `Java Monitor Wait Events` with duration of several nanoseconds
<img width="709" alt="Java Monitor Wait Events" src="https://github.com/oracle/graal/assets/738413/59fcd544-2381-47be-8cb9-737bb97fe982">
while the config is defining the threshold of 20ms
<img width="727" alt="Java Monitor Wait Config" src="https://github.com/oracle/graal/assets/738413/ee0c2d65-3c69-450e-8186-090aa659ad25">

**Describe GraalVM and your environment:**
 - Oracle GraalVM 20.0.1+9
 - OS: **Linux/Ubuntu**
 - Architecture: **AMD64**

[JFR Recording](https://drive.google.com/file/d/1DaFr1sGMBe0CMIWoe9dkLs0h4dD_yvn4/view?usp=sharing) (I had to use GDrive because of the 25MiB limit on GitHub)

**Comment by roberttoyonaga** [comment]
Hi @jbachorik. Thanks for bringing this up. I'll work on fixing this next week.
