### ISSUE TITLE
Generate fallback image for shared library

### ISSUE THREAD

**Issue by CGDogan** [oracle/graal#6992]
**Feature request**

Please include the following information:

**Is your feature request related to a problem? Please describe.**
Sometimes it isn't possible to run the tracer for every code path at the beginning of a project so it'd be nice to have a clone `.so` generated that runs with JVM but has the same ABI.

**Describe the solution you'd like.**
A separate `.so` is generated as well that doesn't crash on reflection because it uses JVM.

**Describe who do you think will benefit the most.**
Developers of libraries and frameworks *hugely* benefit; they don't want crashes in production but they'd like to still use the GraalVM's useful API until they run tracer for all cases

**Describe alternatives you've considered.**
The `.so` itself contains both JVM and native forms.

**Additional context.**
Docs gave the impression that the fallback image would run when a new reflection is encountered but this isn't true for libraries which is disappointing.

**Express whether you'd like to help contributing this feature**
Umm sorry.

**Comment by kkriske** [comment]
Fallback images only exist for compliance reasons in the sense that native-image cannot be called a java implementation if it doesn't run for any set of jars you throw at it. So if you throw something at it that would not work in native-image, a fallback image is created that behind the scenes actually just runs the jars on a JVM. This is basically just a wrapper around running java directly.
> Docs gave the impression that the fallback image would run when a new reflection is encountered

This is not correct, a fallback image is created if something would prevent native-image from outputting a runnable executable. Missing reflection configuration does not trigger the creation of a fallback image as relfection does work, it's just up to you to register which calls should be included.
If you are using native-image, a fallback images is never what you want, so in practice you should always run with the `--no-fallback` options.

The point of using native-image is that you don't need a JVM, so always including a fallback as you're suggesting would significantly increase the size of native-image and would again reintroduce the need for a JVM on the runtime system, which defeats the entire point of using native-image in the first place.

**Comment by CGDogan** [comment]
I see, I thought there would be some benefit in testing a shared library with a JVM as well. I understand that given that the shared library will work without bugs, there's no use in this, so I'm closing
