### ISSUE TITLE
Missing link to npx in jre/bin

### ISSUE THREAD

**Issue by pmlopes** [oracle/graal#700]
Npm ships with 2 scripts: `npm` and `npx`, only `npm` is available in `jre/bin`.

`npx` does live in `languages/js/npm` but it is not linked or marked executable. So it might fail for some packages if no node/npm is installed in the system.

**Comment by iamstolis** [comment]
`npx` was added into GraalVM by https://github.com/graalvm/graaljs/commit/699617c55f6f16873d257ff1e7466338a2373546 finally. I feel ashamed that it took that long.
