### ISSUE TITLE
Dynamic loading of Java classes

### ISSUE THREAD

**Issue by WhiteTrashLord** [oracle/graal#703]
Hi, Graal looks like a very interesting project.

Do you think that you can also support dynamic loading of Java classes in a native compiled application in the future? I think this would be very difficult but maybe not impossible.

Something like a module which can be reloaded during runtime would probably also work for me.

**Comment by cstancu** [comment]
This issue is related to https://github.com/oracle/graal/issues/419. Please see this https://github.com/oracle/graal/issues/419#issuecomment-388646918 for an answer.
