### ISSUE TITLE
Potential memory leak in CodeInstaller::record_scope with jargraal

### ISSUE THREAD

**Issue by sherter** [oracle/graal#7035]
Native Memory Tracking reported large amounts of committed memory in the `Internal` memory region in our application and it seemed to only ever grow. A `detail` report showed that most of this memory was allocated by the `CodeInstaller` (in large chunks).

We were able to reproduce similar behavior in a [minimal example](https://github.com/oracle/graal/files/12110888/minimal-example.zip). The example evaluates the same JavaScript source (a rolled up TypeScript compiler) in a loop.  The `Internal` memory usage increases with more iterations. I got 778 MB of committed Internal memory for 10.000 iterations on my machine. 

We compared this result (`Eclipse Temurin 17.0.7+7 + jargraal 23.0.1`) with `GraalVM CE 17.0.7+7.1` (native libgraal) and `LabsJDK 23.0-b12 + jargraal 23.0.1`. For both native GraalVM and LabsJDK+jargraal, native memory tracking reported much less committed memory in the `Internal` region (~25 MB and ~31 MB).

We then profiled memory allocations with `async-profiler` and what stood out immediately in the Temurin+jargraal flamegraph were extremely deep recursive `CodeInstaller::record_scope` calls that were not recursive at all in the other two scenarios (the screenshot is cut off at the top):

![image](https://github.com/oracle/graal/assets/4977136/b9dc5642-5d8a-488b-8f36-5bdcfeec553b)

I realize that this might be something that has to be fixed elsewhere (e.g. in OpenJDK), so I'll rather state this as a question:

***Is it expected or known that code installation with jargraal+openjdk can lead to such deep recursive calls and large amounts of committed "Internal" memory?***

If it is expected, how can we effectively limit the amount of memory used for this? We tried a few truffle compiler options with very limited success.

If this is not expected and not the correct project to report it to, I would appreciate a little hint on where I should report it instead.

**Steps to reproduce the issue**
1. Download and extract [minimal-example.zip](https://github.com/oracle/graal/files/12110888/minimal-example.zip) (includes my results, the flamegraphs are unfortunately quite large)
1. `mvn package`
2. `JAVA_HOME=<Temurin/GraalVM/LabsJDK> mvn exec:exec`

To enable allocation profiling and flamegraph generation, download async-profiler
(https://github.com/async-profiler/async-profiler/releases/tag/v2.9) and adjust
and uncomment the `-agentpath` argument in `pom.xml`

**Describe GraalVM and your environment:**
 - JDK major version: 17
 - OS: Linux
 - Architecture: AMD64

**Comment by dougxc** [comment]
This sounds like Temurin may be missing some patches that are in LabsJDK since the problem does not occur on LabsJDK based binaries. I would suggest opening a ticket on Temurin to have them double check the source diff between labsjdk and Temurin.

**Comment by davleopo** [comment]
@sherter closing this if this is a Temurin bug, please re-open if its a GraalVM issue.
