### ISSUE TITLE
Use graal via the standard JDK 11 installation

### ISSUE THREAD

**Issue by v4umak** [oracle/graal#704]
Hello,

I have project used Nashorn Javascript engine. I'm trying to migrate to java11 and also migrate from Nashorn to Graal. I've read that I can use graal via the standard JDK installation starting from JDK 11 - https://medium.com/graalvm/oracle-graalvm-announces-support-for-nashorn-migration-c04810d75c1f
Also I've read there that Graal-SDK are uploaded to Maven central, and that there is java flag polyglot.js.nashorn-compat for easy migration. I've used both but when I'm trying to get engine by name "graal.js", I've got null:
`ScriptEngine engine = engineManager.getEngineByName("graal.js")`
Also I've read that Graal SDK requires GraalVM to run - should I use it with standard JDK installation?

**Comment by v4umak** [comment]
@wirthi I've figured out that this code works (with compat option) on java from graalvm build (currently java8). Is it correct that there is no way to use graal engine on OpenJDK 11 build with some maven dependencies?

**Comment by wirthi** [comment]
We will publish some documentation and examples on "Graal on JDK11" shortly.

**Comment by ElliotZhang** [comment]
Hi @wirthi , I am looking at the same thing. Any updates?
