### ISSUE TITLE
javax.imageio.read broken with --initialize-at-build-time

### ISSUE THREAD

**Issue by CGDogan** [oracle/graal#7047]
**Describe the issue**
As per https://github.com/oracle/graal/issues/7015, native-image allows System.loadLibrary in static blocks which can be initialized at build time but no effect is left to runtime. This also means that `--initialize-at-build-time` can break some Java libraries such as `javax.imageio`. Here I give a test that shows that this breaks internal JNI in java library.

**Steps to reproduce the issue**

- Download Testimageio.java ([Testimageio.java.tar.gz](https://github.com/oracle/graal/files/12136675/Testimageio.java.tar.gz) or see below):
- Run the following:
```
javac Testimageio.java
java -agentlib:native-image-agent=config-output-dir=META-INF/native-image Testimageio
native-image  --no-fallback --initialize-at-build-time Testimageio --initialize-at-run-time=sun.java2d.Disposer
```

Then the branch that confirms that the JNI Jpeg reader could not be initialized is visited.

The code is:

```java
import java.io.BufferedInputStream;
import java.io.ByteArrayInputStream;

import javax.imageio.ImageIO;
import javax.imageio.stream.ImageInputStream;
import javax.imageio.stream.MemoryCacheImageInputStream;

public class Testimageio {
    public static void main(String[] a) {
        try {
            ImageInputStream stream = new MemoryCacheImageInputStream(new BufferedInputStream(
                    new ByteArrayInputStream(
                            new byte[] {
                                    (byte) 0xFF, (byte) 0xD8, (byte) 0xFF, (byte) 0xE0, (byte) 0x00, (byte) 0x10,
                                    (byte) 0x4A, (byte) 0x46
                            }),
                    81920));
            var b = ImageIO.read(stream);
        } catch (Exception e) {
            // Exception: We've run the JPEG decoder and it decided that it was bad image!
            System.out.println("Seems to work");
        } catch (Error e) {
            // Error: The JPEG decoder was chosen however it could not be loaded
            System.out.println("Broken. " + e.toString());
        }
    }
}
```

**Describe GraalVM and your environment:**
 - GraalVM version: 13 July 2023 v20 snapshot build (latest as of posting this)
 - JDK major version: v20
 - OS: Ubuntu Lunar
 - Architecture: ARM64

**More details**

I couldn't find anything useful in logs.

**Comment by kkriske** [comment]
using `--initialize-at-build-time` without any arguments is:
1. an anti-pattern as it's a blanket option that has major side effects, as you are seeing
2. is deprecated and warns you in the build output that it is
3. will be removed and throw exceptions in an upcomming version

The only fix here is, don't use `--initialize-at-build-time` without arguments, and only initialize classes at build-time that you know do not cause unwanted side-effects.
Putting classes that load native code at build-time has side-effects so you should simply not do that.

**Comment by CGDogan** [comment]
Ah ok thanks
