### ISSUE TITLE
[GR-48812] Native builds fail with most recent GraalVM 17 versions

### ISSUE THREAD

**Issue by DarkAtra** [oracle/graal#7089]
**Describe the issue**

When building [my project](https://github.com/DarkAtra/v-rising-discord-bot) using one of the more recent GraalVM versions (`graalvm-jdk-17_macos-x64_bin/17.0.0/x64/graalvm-jdk-17.0.8+9.1`) the following error occurs:

```
> com.oracle.svm.core.util.VMError$HostedError: com.oracle.svm.core.util.UserError$UserException: Image heap writing found a class not seen during static analysis. Did a static field or an object referenced from a static field change during native image generation? For example, a lazily initialized cache could have been initialized during image generation, in which case you need to force eager initialization of the cache before static analysis or reset the cache using a field value recomputation.
    class: dev.kord.common.entity.optional.Optional$Missing$Companion
  reachable through:
    object: [Ljava.lang.Class;@3a2ff431  of class: java.lang.Class[]
    object: com.oracle.svm.core.code.ImageCodeInfo@4be4e3ff  of class: com.oracle.svm.core.code.ImageCodeInfo
    root: com.oracle.svm.core.code.ImageCodeInfo.prepareCodeInfo()
```

`Optional$Missing` is implemented as follows:
```kotlin
public sealed class Optional<out T> {

    public class Missing<out T> private constructor() : Optional<T>() {

        // ... irrelevant code here

        public companion object {
            private val constantNull = Missing<Nothing>()

            public operator fun <T : Any> invoke(): Missing<T> = constantNull
        }
    }
}
```

I don't get how the value of `constantNull` could change in this situation as it's literally a `val` (e.g. final). Downgrading to `graalvm-ce-java17-darwin/22.3.2/x64/graalvm-ce-java17-22.3.2` fixes the issue.

**Steps to reproduce the issue**
1. ensure you have GraalVM **graalvm-jdk-17.0.8+9.1** installed and set as JAVA_HOME
2. `git clone git@github.com:DarkAtra/v-rising-discord-bot.git`
3. `./mvnw -PnativeTest clean verify`

There's also a github workflow run with the exact same environment and error here: https://github.com/DarkAtra/v-rising-discord-bot/actions/runs/5685610328/job/15410839417#step:4:448
Also, here's the run with the downgraded GraalVM version: https://github.com/DarkAtra/v-rising-discord-bot/actions/runs/5706950594/job/15463156901

**Describe GraalVM and your environment:**
 - GraalVM version: **graalvm-jdk-17_macos-x64_bin/17.0.0/x64/graalvm-jdk-17.0.8+9.1**
 - JDK major version: **17**
 - OS: **macOS 12 Monterey**
 - Architecture: **AMD64**

**Comment by oubidar-Abderrahim** [comment]
Hi, when I try to reproduce the issue, the build finishes successfully with `[WARNING] The requested profile "native-test" could not be activated because it does not exist.`
I checked your repo and I don't see the native plugin in the pom.xml nor a branch that has native support enabled in it

**Comment by DarkAtra** [comment]
> Hi, when I try to reproduce the issue, the build finishes successfully with `[WARNING] The requested profile "native-test" could not be activated because it does not exist.` I checked your repo and I don't see the native plugin in the pom.xml nor a branch that has native support enabled in it

sorry it's `nativeTest` instead of `native-test`

**Comment by DarkAtra** [comment]
@oubidar-Abderrahim have you had a chance to look at this yet?

**Comment by DarkAtra** [comment]
hey @oubidar-Abderrahim, is there any workaround for this issue that you could recommend for the time being? (besides sticking with an older version of graalvm)

**Comment by DarkAtra** [comment]
hey @loicottet, is there any workaround for this issue for the time being? this issue is getting more and more annoying and blocks me from releasing a new version of my project. I'd highly appreciate any hint to why this error occurs and what i could do to prevent it from happening for now (even if it is super hacky).

**Comment by DarkAtra** [comment]
> Hi @DarkAtra, thank you for bringing this up.
> 
> The workaround for this issue is to add classes that show up in the second line of the error message to reflection metadata. In the error message above that would be `dev.kord.common.entity.optional.Optional$Missing$Companion`.
> 
> I applied the following diff to the provided project and the image was built successfully:
> 
> ```
> diff --git i/src/main/kotlin/de/darkatra/vrising/discord/BotRuntimeHints.kt w/src/main/kotlin/de/darkatra/vrising/discord/BotRuntimeHints.kt
> index d775400b0d..3030e26bba 100644
> --- i/src/main/kotlin/de/darkatra/vrising/discord/BotRuntimeHints.kt
> +++ w/src/main/kotlin/de/darkatra/vrising/discord/BotRuntimeHints.kt
> @@ -77,7 +77,9 @@ class BotRuntimeHints : RuntimeHintsRegistrar {
>              ThreadMemberData::class.java,
>              UserData::class.java,
>              VoiceStateData::class.java,
> -            WebhookData::class.java
> +            WebhookData::class.java,
> +            dev.kord.common.entity.optional.Optional.Null.Companion::class.java,
> +            dev.kord.common.entity.optional.Optional.Missing.Companion::class.java
>          )
>  
>          hints.reflection()
> ```

Thanks for your response. The suggested fix works.
