### ISSUE TITLE
native-image wont believe the class file really is V20

### ISSUE THREAD

**Issue by crowlogic** [oracle/graal#7098]
```

crow@hotspot:~/a$ native-image -cp target/classes --verbose --shared  arb.expressions.AddThreeConstants   -H:+ReportExceptionStackTraces

Error: Unable to load 'arb.expressions.AddThreeConstants' due to a Java version mismatch.
Please take one of the following actions:
 1) Recompile the source files for your application using Java 20, then try running native-image again
 2) Use a version of native-image corresponding to the version of Java with which you compiled the source files for your application


crow@hotspot:~/a$ file target/classes/arb/expressions/AddThreeConstants.class 
target/classes/arb/expressions/AddThreeConstants.class: compiled Java class data, version 64.65535

crow@hotspot:~/a$ javap -cp target/classes -verbose arb.expressions.AddThreeConstants
Classfile /home/crow/git/arb4j/target/classes/arb/expressions/AddThreeConstants.class
  Last modified Aug 2, 2023; size 943 bytes
  SHA-256 checksum 1e800b63a691ce89556370dc4c5479e1bc5e2a47105e5b1bf46901393347e6fd
public class arb.expressions.AddThreeConstants implements arb.functions.real.RealFunction
  minor version: 65535
  major version: 64
  flags: (0x0001) ACC_PUBLIC
  this_class: #2                          // arb/expressions/AddThreeConstants
  super_class: #4                         // java/lang/Object
  interfaces: 1, fields: 6, methods: 3, attributes: 0
  
  
  crow@hotspot:~/a$ native-image --version
native-image 20.0.1 2023-04-18
GraalVM Runtime Environment Oracle GraalVM 20.0.1+9.1 (build 20.0.1+9-jvmci-23.0-b12)
Substrate VM Oracle GraalVM 20.0.1+9.1 (build 20.0.1+9, serial gc, compressed references)


```

**Comment by crowlogic** [comment]
[argh.zip](https://github.com/oracle/graal/files/12236993/argh.zip)

zip files containing classes that wont compile

these are generated by objectweb asm but that doesnt matter because the problem exists for regular code compiled with 

crow@hotspot:~$ java -version
java version "20.0.1" 2023-04-18
Java(TM) SE Runtime Environment Oracle GraalVM 20.0.1+9.1 (build 20.0.1+9-jvmci-23.0-b12)
Java HotSpot(TM) 64-Bit Server VM Oracle GraalVM 20.0.1+9.1 (build 20.0.1+9-jvmci-23.0-b12, mixed mode, sharing)

as well

**Comment by petermz** [comment]
> version 64.65535

You probably need `--enable-preview` for this type of class. The error
message might indeed be improved.

**Comment by fniephaus** [comment]
It seems we've already done something about this for the JDK 21 release:
https://github.com/oracle/graal/blob/172f40cffe31ca4a40eb642ec3d215ecb5054df6/substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/NativeImageGeneratorRunner.java#L435-L443

We can improve it further and maybe even backport it to JDK 17.

**Comment by fniephaus** [comment]
I've further improve the handling a bit: https://github.com/oracle/graal/commit/c75ffa8fdc50981cfb2ad534c3421174c2b45cd9
