### ISSUE TITLE
Classes that contain lambas can't be marked for runtime init

### ISSUE THREAD

**Issue by stuartwdouglas** [oracle/graal#711]
It appears that RC7 no longer allows classes that contain lambdas to be marked for runtime init. 

Looking in a debugger it appears processing the lambdas now forces the loading of the runtime init class at native image build time.

This worked in RC6.

**Comment by fniephaus** [comment]
Hey @stuartwdouglas, looks like we haven't responded to your ticket, apologies! A lot of things have changed and improved around run-time init in the meantime. I hope you don't mind that I'm closing this ticket for now. Please let us know if this is still an issue. Thanks!
