### ISSUE TITLE
Can't compile with Onnxruntime library, should svm-enterprise.jar be excluded?

### ISSUE THREAD

**Issue by x-wk** [oracle/graal#7113]
**Describe the issue**
I am working on a Spring Boot project, which uses onnxruntime for inference. When I use the maven command to generate a native executable directly, i get the following error:
```shell
Error: Class-path entry file:///home/xxx/.m2/repository/com/microsoft/onnxruntime/onnxruntime/1.11.0/onnxruntime-1.11.0.jar contains class ai.onnxruntime.ValueInfo. This class is part of the image builder itself (in file:///opt/java/graalvm-jdk-17.0.8+9.1/lib/svm/builder/svm-enterprise.jar) and must not be passed via -cp. This can be caused by a fat-jar that illegally includes svm.jar (or graal-sdk.jar) due to its build-time dependency on it. As a workaround, -H:+AllowDeprecatedBuilderClassesOnImageClasspath allows turning this error into a warning. Note that this option is deprecated and will be removed in a future version.
Error: Use -H:+ReportExceptionStackTraces to print stacktrace of underlying exception
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  17.550 s
[INFO] Finished at: 2023-08-02T23:16:02-07:00
[INFO] ------------------------------------------------------------------------
```

When I added the '-H:+AllowDeprecatedBuilderClassesOnImageClasspath' parameter according to the instructions, I got the following warning:
```shell
Warning: Could not register method com.xxx.embedding.rest.TestController.initialize() for reflection. Reason: java.lang.IllegalAccessError: class com.xxx.embedding.rest.TestController (in unnamed module @0x152a86b0) cannot access class ai.onnxruntime.OrtException (in module com.oracle.svm.svm_enterprise) because module com.oracle.svm.svm_enterprise does not export ai.onnxruntime to unnamed module @0x152a86b0.
```
Although the compilation is successful, it is 404 when accessing. When I checked the files in 'spring-aot' I found that this 'TestController' does not exist.

The documentation doesn't seem to explain why the onnxruntime library is included in svm-enterprise.jar, and how should I fix this?

**Describe GraalVM and your environment:**
 - GraalVM version: **17.0.8+9.1**
 - JDK major version: **17**
 - OS: **Ubuntu**
 - Architecture: **x86_64**

**Comment by zekronium** [comment]
Hi,

We are encountering the same issue with the only difference being we are using Quarkus.

```Warning: Class-path entry native-infer-1.0-SNAPSHOT-native-image-source-jar/lib/com.microsoft.onnxruntime.onnxruntime-1.13.1.jar contains class ai.onnxruntime.providers.NNAPIFlags. This class is part of the image builder itself (in file:///Library/Java/JavaVirtualMachines/graalvm-jdk-17.0.8+9.1/Contents/Home/lib/svm/builder/svm-enterprise.jar) and must not be passed via -cp.```

Shall we reopen this or should I make a new issue

**Comment by JiangWork** [comment]
same issue here. After adding -H:+AllowDeprecatedBuilderClassesOnImageClasspath, then run the code it errors:
`java.lang.NoClassDefFoundError: ai.onnxruntime.OrtEnvironment`

**Comment by oubidar-Abderrahim** [comment]
@JiangWork, @zekronium, thank you for your input, can one of you please create a new issue following the native-image template, and share a reproducer sample code for this issue, we'll gladly take another look into it.
In case you already created the issue, please link it to this one for clarity (only one issue is needed) Thank you
