### ISSUE TITLE
 Error: Classes that should be initialized at run time got initialized during image building

### ISSUE THREAD

**Issue by Co-Maheshh** [oracle/graal#7122]
Issues with Unintentional Class Initialization during Native Image Building in  Project

I'm encountering a problem while attempting to build a native image for in spring boot project. The native image building process is resulting in unintended class initialization, causing errors during the build. I've provided the relevant error message below:

**Error: Classes that should be initialized at run time got initialized during image building:
[INFO] [creator] org.codehaus.groovy.reflection.stdclasses.LongCachedClass was unintentionally initialized at build time. To see why org.codehaus.groovy.reflection.stdclasses.LongCachedClass got initialized use --trace-class-initialization=org.codehaus.groovy.reflection.stdclasses.LongCachedClass
[INFO] [creator] java.beans.Introspector was unintentionally initialized at build time. To see why java.beans.Introspector got initialized use --trace-class-initialization=java.beans.Introspector
[INFO] [creator] org.codehaus.groovy.vmplugin.v8.IndyInterface was unintentionally initialized at build time. To see why org.codehaus.groovy.vmplugin.v8.IndyInterface got initialized use --trace-class-initialization=org.codehaus.groovy.vmplugin.v8.IndyInterface
[INFO] [creator] org.codehaus.groovy.runtime.dgmimpl.arrays.LongArrayGetAtMetaMethod was unintentionally initialized at build time. To see why org.codehaus.groovy.runtime.dgmimpl.arrays.LongArrayGetAtMetaMethod got initialized use --trace-class-initialization=org.codehaus.groovy.runtime.dgmimpl.arrays.LongArrayGetAtMetaMethod
**

is is comming particulery for groovy dependency that i am using in pom.xml                 

this is the dependency i am using 

**<dependency>
			<groupId>org.apache.groovy</groupId>
			<artifactId>groovy-all</artifactId>
			<version>4.0.13</version>
			<type>pom</type>
</dependency>
**

Please provide me solu so how i can resolve this issue;

**Comment by Co-Maheshh** [comment]
@peter-hofer

**Comment by oubidar-Abderrahim** [comment]
Thank you for reporting this, [Class initialization](https://docs.oracle.com/en/graalvm/enterprise/21/docs/reference-manual/native-image/ClassInitialization/#explicitly-specifying-class-initialization) issues are bothersome and don't have a straight forward approach as each case is different from the other, it requires a bit of trial an error to get a successful build

you can add `--trace-object-instantiation=org.codehaus.groovy.reflection.stdclasses.LongCachedClass` to your build command which should reveal the original class that caused this initialization. then try to force its initialization at run-time
You can also try forcing the initialization at build-time.

**Comment by oubidar-Abderrahim** [comment]
I'm closing this issue for now, if you still need assistance please reopen it. Thank you

**Comment by TiluWeb** [comment]
A good solution was provided on https://medium.com/graalvm/working-with-native-image-efficiently-c512ccdcd61b to trace and fix this issues (and others).
