### ISSUE TITLE
graal-sdk-23.0.1.jar contains class com.oracle.svm.core.annotate.TargetElement

### ISSUE THREAD

**Issue by Co-Maheshh** [oracle/graal#7130]
i am getting this error at the time of build image  

graal-sdk-23.0.1.jar contains class com.oracle.svm.core.annotate.TargetElement. This class is part of the image builder itself (in jrt:/org.graalvm.sdk)

i am using graal sdk dependency on pom becouse i need that for  javascript. so i dont want to exclude that dependency also. so is there any solution to resolve this error.

this is my pom

            <dependency>
			<groupId>org.graalvm.js</groupId>
			<artifactId>js</artifactId>
			<version>22.2.0</version>
           <dependency>
          <dependency>
                     <groupId>org.graalvm.sdk</groupId>
		     <artifactId>graal-sdk</artifactId>
          <dependency>

**Comment by Co-Maheshh** [comment]
@petermz

**Comment by oubidar-Abderrahim** [comment]
Thank you for reaching out, can you please use the same version for the JS dependency instead of version 22.2.0

**Comment by oubidar-Abderrahim** [comment]
Hi, Any updates?

**Comment by Co-Maheshh** [comment]
@oubidar-Abderrahim   When i use Context for executing JS code in java then i am getting this error                                                     

com.oracle.truffle.api.TruffleStackTrace$LazyStackTrace: null
Wrapped by: java.lang.IllegalStateException: The Context is already closed.

**Comment by oubidar-Abderrahim** [comment]
> thanks @oubidar-Abderrahim its worked perfect

good to hear that

> Wrapped by: java.lang.IllegalStateException: The Context is already closed.

It's hard to know what went wrong from just the stack trace, but it seems you're trying to call you javascript code (maybe via a callback) after the context was closed. 
The `Context` holds all the necessary information needed for the execution of your code. If it's closed, then you cannot use it.
