### ISSUE TITLE
org.codehaus.groovy and groovy.lang.GroovySystem was unintentionally initialized at build time.

### ISSUE THREAD

**Issue by Co-Maheshh** [oracle/graal#7139]
I'm trying to use a org.apache.groovy:groovy-all 4.0.13  library in the Spring Boot 3.1 application.

I receive a following errors:
Error: Classes that should be initialized at run time got initialized during image building:
[INFO]     [creator]      org.codehaus.groovy.runtime.dgmimpl.arrays.ShortArrayGetAtMetaMethod was unintentionally initialized at build time. To see why org.codehaus.groovy.runtime.dgmimpl.arrays.ShortArrayGetAtMetaMethod got initialized use --trace-class-initialization=org.codehaus.groovy.runtime.dgmimpl.arrays.ShortArrayGetAtMetaMethod
[INFO]     [creator]     org.codehaus.groovy.runtime.dgmimpl.arrays.CharacterArrayGetAtMetaMethod was unintentionally initialized at build time. To see why org.codehaus.groovy.runtime.dgmimpl.arrays.CharacterArrayGetAtMetaMethod got initialized use --trace-class-initialization=org.codehaus.groovy.runtime.dgmimpl.arrays.CharacterArrayGetAtMetaMethod
[INFO]     [creator]     org.codehaus.groovy.reflection.CachedClass was unintentionally initialized at build time. To see why org.codehaus.groovy.reflection.CachedClass got initialized use --trace-class-initialization=org.codehaus.groovy.reflection.CachedClass
[INFO]     [creator]     org.codehaus.groovy.runtime.dgmimpl.arrays.IntegerArrayGetAtMetaMethod was unintentionally initialized at build time. To see why org.codehaus.groovy.runtime.dgmimpl.arrays.IntegerArrayGetAtMetaMethod got initialized use --trace-class-initialization=org.codehaus.groovy.runtime.dgmimpl.arrays.IntegerArrayGetAtMetaMethod
[INFO]     [creator]     org.codehaus.groovy.reflection.CachedClass$3 was unintentionally initialized at build time. To see why org.codehaus.groovy.reflection.CachedClass$3 got initialized use --trace-class-initialization=org.codehaus.groovy.reflection.CachedClass$3
[INFO]     [creator]     org.codehaus.groovy.runtime.dgmimpl.arrays.BooleanArrayGetAtMetaMethod was unintentionally initialized at build time. To see why org.codehaus.groovy.runtime.dgmimpl.arrays.BooleanArrayGetAtMetaMethod got initialized use --trace-class-initialization=org.codehaus.groovy.runtime.dgmimpl.arrays.BooleanArrayGetAtMetaMethod
[INFO]     [creator]     groovy.lang.MetaClassI

**Comment by Co-Maheshh** [comment]
@sdeleuze

**Comment by Co-Maheshh** [comment]
@fniephaus

**Comment by fniephaus** [comment]
@Co-Maheshh you need to find our why classes from `org.codehaus.groovy.runtime` get initialized at build-time. I don't know anything about that package, so I can't really be of much help.

**Comment by sdeleuze** [comment]
It very hard to use Groovy on native image, especially with all the Groovy ecosystem not using static compilation. As a consequence, Spring native supports only supports Java and Kotlin.

**Comment by Co-Maheshh** [comment]
@sdeleuze  i aggree but i am not using groovy for native image,  i have spring boot project where i am using groovy dependency for executing groovy script.

**Comment by Co-Maheshh** [comment]
@sdeleuze  sure. so in my pom.xml this dependency right now i am using for groovy.

<dependency>
           <groupId>org.apache.groovy</groupId>
           <artifactId>groovy</artifactId>
           <version>4.0.13</version>
            <exclusions>
                <exclusion>
                <groupId>org.codehaus.groovy</groupId>
                <artifactId>groovy</artifactId>             
              </exclusion>
            </exclusions>
       </dependency>

**Comment by sdeleuze** [comment]
> please try your sample with https://github.com/graalvm/graalvm-ce-dev-builds/releases/tag/23.1.0-dev-20230801_1722 and let us know if that changes something or not.
>
> Also please share a sample in case GraalVM team want to dig deeper.

**Comment by blackdrag** [comment]
The classes in org.codehaus.groovy.runtime.dgmimpl are helper for callsite caching.  See https://github.com/apache/groovy/blob/GROOVY_4_0_13/src/main/java/org/codehaus/groovy/tools/DgmConverter.java for the class generating them
