### ISSUE TITLE
[GR-47823] Missing license header in `graal_isolate.preamble`.

### ISSUE THREAD

**Issue by koutheir** [oracle/graal#7148]
The file [`substratevm/src/com.oracle.svm.core/headers/graal_isolate.preamble`](https://github.com/oracle/graal/blob/master/substratevm/src/com.oracle.svm.core/headers/graal_isolate.preamble) is missing a license header. This makes its contents, as far as I understand, proprietary.

The contents of `graal_isolate.preamble` are embedded in the generated CAP cache source file `BuiltinDirectives.c`, which in turn also lacks a license header.

Should `graal_isolate.preamble` have a license of some kind? Or maybe `BuiltinDirectives.c` should?

**Comment by koutheir** [comment]
Moreover, many source files under [`vm/tests/all/agentscript/`](https://github.com/oracle/graal/tree/master/vm/tests/all/agentscript) do not have any license headers.

**Comment by koutheir** [comment]
More source files don't have licenses:
- `vm/src/org.graalvm.component.installer.test/src/org/graalvm/component/installer/repo/python/1.0.0.0/jre/languages/python/lib-python/3/_bootlocale.py`
- `vm/src/org.graalvm.component.installer.test/src/org/graalvm/component/installer/repo/python/1.0.1.0/jre/languages/python/lib-python/3/_bootlocale.py`
- `vm/src/org.graalvm.component.installer.test/src/org/graalvm/component/installer/repo/python/1.1.0.0/jre/languages/python/lib-python/3/_bootlocale.py`

**Comment by olyagpl** [comment]
@koutheir, license headers were added where missing. Thanks for reporting!

**Comment by olyagpl** [comment]
Just for your information, we didn't add a header in [substratevm/src/com.oracle.svm.core/headers/graal_isolate.preamble](https://github.com/oracle/graal/blob/master/substratevm/src/com.oracle.svm.core/headers/graal_isolate.preamble), because is is a template file and must not have a license header.

**Comment by fniephaus** [comment]
Closed via https://github.com/oracle/graal/pull/7511.
