### ISSUE TITLE
TargetClass is not very flexible with optional classes

### ISSUE THREAD

**Issue by stuartwdouglas** [oracle/graal#716]
TargetClass has the 'onlyWith' attribute that allows you to control when it is applied, however this is very inflexible when dealing with optional classes, as every single use of this annotation will require a new BooleanSupplier to be defined.

e.g. a common use case is something like:

    static final class Selector implements BooleanSupplier {

        @Override
        public boolean getAsBoolean() {
            try {
                Class.forName("com.sun.xml.bind.v2.model.annotation.LocatableAnnotation");
                return true;
            } catch (ClassNotFoundException e) {
                return false;
            }
        }
    }

It would be better if this was Predicate rather than BooleanSupplier, so the current class name could be passed to it, or better yet just add an 'optional' attribute to TargetClass so if the class is not present it is simply ignored.

**Comment by cstancu** [comment]
This issue was addressed in https://github.com/oracle/graal/commit/81dc2cea7a84a05be45d2bc6db30273c69459a31. Now `onlyWith` accepts either a `BooleanSupplier` or a `Predicate`.
