### ISSUE TITLE
SubstrateVM: static field referenced error with Micronaut/Netty and security module with RC7

### ISSUE THREAD

**Issue by graemerocher** [oracle/graal#717]
Steps to reproduce:

* Use Graal-RC7
* Clone the repo: https://github.com/ilopmar/micronaut-security-jwt-graal
* Execute ./build-native-image.sh

Error:

```
error: Static field or an object referenced from a static field changed during native image generation?
  object:[Ljava.lang.reflect.Parameter;@52524399  of class: java.lang.reflect.Parameter[]
  reachable through:
    object: public sun.net.www.protocol.http.spnego.NegotiatorImpl(sun.net.www.protocol.http.HttpCallerInfo) throws java.io.IOException  of class: java.lang.reflect.Constructor
    root: sun.net.www.protocol.http.Negotiator.getNegotiator(HttpCallerInfo)

Error: Image building with exit status 1
```

Things I have tried:

* Adding `io.netty.handler.ssl.JdkNpnApplicationProtocolNegotiator` to `delay-class-initialization-to-runtime` and/or `rerun-class-initialization-at-runtime`
* Adding to `sun.net.www.protocol.http.Negotiator` to `delay-class-initialization-to-runtime` and/or `rerun-class-initialization-at-runtime`

None of these seem to have worked. The image builds ok on RC6.

**Comment by ilopmar** [comment]
I've tried again with latest Micronaut and Graal versions and the new error is:

```
[mn-security:4641]        image:   4,728.17 ms
Error: Static field or an object referenced from a static field changed during native image generation?
  object:[Ljava.lang.reflect.Parameter;@3fdc07d4  of class: java.lang.reflect.Parameter[]
  reachable through:
    object: public synchronized void sun.net.www.protocol.http.HttpURLConnection.doTunneling() throws java.io.IOException  of class: java.lang.reflect.Method
    root: null

Error: Use -H:+ReportExceptionStackTraces to print stacktrace of underlying exception
Error: Image building with exit status 1
```

P.S: I've updated the test application to use latest Micronaut.

**Comment by graemerocher** [comment]
Still broken in rc13 any update?

**Comment by cstancu** [comment]
Fixed by https://github.com/oracle/graal/commit/f68406219a9edb55922605fc4782f135bb2739b3. See https://github.com/oracle/graal/issues/659#issuecomment-475078954 for details.
