### ISSUE TITLE
encounter 'Shading org.graalvm.shadowed.org.jline failed' when building graalvm

### ISSUE THREAD

**Issue by 16061054** [oracle/graal#7203]
**Describe the issue**
I encounter the '_Shading org.graalvm.shadowed.org.jline failed_' error when building graalvm in docker.

**Steps to reproduce the issue**
Here are steps:
1 Create a container based on basic centos7.9 image
`docker run --name build-graalvm --privileged=true -w /root -d  centos:centos7 /usr/sbin/init`
`docker exec -it build-graalvm bash`
2 Get mx
`yum install -y centos-release-scl && yum install -y rh-python38 which git wget devtoolset-10-gcc* && cd /  && git clone https://github.com/graalvm/mx.git`
3 Get boot jdk
`cd / && wget https://github.com/graalvm/labs-openjdk-20/releases/download/jvmci-23.0-b15/labsjdk-ce-20.0.2+9-jvmci-23.0-b15-linux-aarch64.tar.gz && tar xvf labsjdk-ce-20.0.2+9-jvmci-23.0-b15-linux-aarch64.tar.gz && rm -rf labsjdk-ce-20.0.2+9-jvmci-23.0-b15-linux-aarch64.tar.gz`
4 Build graalvm
`source /opt/rh/rh-python38/enable && cd / && git clone https://github.com/oracle/graal.git graal && cd graal/vm/ && export JAVA_HOME=/labsjdk-ce-20.0.2-jvmci-23.0-b15 && export PATH=/mx:/JAVA_HOME/bin:$PATH && mx --env ce --java-home=/labsjdk-ce-20.0.2-jvmci-23.0-b15 build`

**Describe GraalVM and my environment:**
 - GraalVM version: built from latest source
 - JDK major version: labs-20
 - OS: centos7.9
 - Architecture: aarch64

**More details**
Here is the cleaned output of build result.
```
WARNING:   File "/graaljs/graal-js/mx.graal-js/suite.py", line 474 in definition of GRAALJS_LAUNCHER:
"exclude" attribute contains a jar distribution: JLINE3. Adding it to dependencies. Please move the distribution from "exclude" to "distDependencies".
10 unsatisfied dependencies were removed from build (use -v to list them)
5 non-default dependencies were removed from build (use -v to list them, mx build --all to build them)
WARNING: Adding non-default dependency com.oracle.svm.graal.hotspot.libgraal as it is needed by standard dependency GRAAL_HOTSPOT_LIBRARY
WARNING: Adding non-default dependency GRAAL_HOTSPOT_LIBRARY as it is needed by standard dependency libjvmcicompiler.so.image
Exception in thread Thread-16:
Traceback (most recent call last):
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/mx/mx.py", line 92, in run
    super(_DummyProcess, self).run()
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/mx/mx.py", line 15028, in executeTask
    task.execute()
  File "/mx/mx.py", line 5235, in execute
    buildNeeded, reason = self.needsBuild(newestInput)
  File "/graal/sdk/mx.sdk/mx_sdk_shaded.py", line 171, in needsBuild
    if suite_py_ts.isNewerThan(input_ts):
  File "/mx/mx.py", line 16019, in isNewerThan
    if self.timestamp < getmtime(f):
  File "/mx/mx.py", line 4355, in getmtime
    return os.path.getmtime(_safe_path(name))
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/genericpath.py", line 55, in getmtime
    return os.stat(filename).st_mtime
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
Shading org.graalvm.shadowed.org.jline failed
1 build tasks failed
```

**Comment by woess** [comment]
Should be fixed by https://github.com/oracle/graal/commit/9df44473bc8dc2f9f9aead4736448d4c96a45ecd
