### ISSUE TITLE
Allow setting the Graal Compiler optimization level when running MX Build to compile GraalVM CE

### ISSUE THREAD

**Issue by SamuelJeffersons** [oracle/graal#7268]
**Feature request**

Please include the following information:

**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. E.g. I'm always frustrated when [...]
I am unable to set the compiler optimization level for the Graal Compiler when I am compiling GraalVM Community Edition from source using MX. 

**Describe the solution you'd like.**
An option that allows you to set the -O optimization level and or -march=native, -mtune=native

[libjvmcicompiler:18314]  Java version: 17.0.8+0, vendor version: GraalVM CE 17.0.8+0.1
[libjvmcicompiler:18314]  Graal compiler: optimization level: 2, target machine: compatibility
[libjvmcicompiler:18314]  C compiler: gcc (pc, x86_64, 13.2.1)
[libjvmcicompiler:18314]  Garbage collector: Serial GC (max heap size: 80% of RAM)
[libjvmcicompiler:18314]  1 user-specific feature(s)

(Allowing me to change this)

**Describe who do you think will benefit the most.**
GraalVM users, GraalVM contributors, developers of libraries and frameworks which depend on GraalVM, or somebody else?
GraalVM users who use GraalVM due to its high performance.

**Describe alternatives you've considered.**
Using the awesome-graal build script, though I was unable to make it work.

**Additional context.**
Add any other context about the feature request here.
For example, link to the relevant projects, documentation, standards.
https://www.graalvm.org/latest/reference-manual/native-image/overview/BuildOutput/#:~:text=Graal%20Compiler,-The%20selected%20optimization&text=The%20optimization%20level%20can%20be,speeds%20up%20the%20compilation%20stage.

**Express whether you'd like to help contributing this feature**
If you'd like to contribute, please read the [contribution guide](https://www.graalvm.org/community/contributors/).

**Note**
If this is actually possible, please instruct me on how this can be done.

**Comment by fniephaus** [comment]
You can do this with `--extra-image-builder-argument`, for example:
```
mx --native-images=lib:jvmcicompiler --extra-image-builder-argument=-O1 --extra-image-builder-argument=-march=native build
```
