### ISSUE TITLE
java.util.logging not working in native image

### ISSUE THREAD

**Issue by dsyer** [oracle/graal#728]
```java
import java.util.logging.Logger;

public class Loggers {

	public static void main(String[] args) throws Exception {
		new Loggers().run();
	}

	private void run() throws Exception {
		Logger.getLogger(Loggers.class.getName()).info("Hello World");
	}

}
```

In a normal JVM:

```
Oct 09, 2018 4:17:58 PM Loggers run
INFO: Hello World
```

This app runs with no errors but doesn't log anything in SVM.

**Comment by sdeleuze** [comment]
This is annoying because Logback and Log4j2 are not working with Substrate VM yet, so making that one supported would at least provide a solution to get logs with Graal native images, which seems a pretty basic need.

**Comment by sdeleuze** [comment]
Repro project available here: https://github.com/sdeleuze/graal-issues/tree/master/java-util-logging

**Comment by pekd** [comment]
You could try to add your own [Handler](https://docs.oracle.com/javase/7/docs/api/java/util/logging/Handler.html) that prints log messages to `System.out`.

**Comment by dsyer** [comment]
> You could try to add your own Handler that prints log messages to System.out / System.err.

Isn't that what the default `ConsoleHandler` already does?

**Comment by dsyer** [comment]
Interestingly, the sample above (same as @sdeleuze 's) works for me if I add `--no-server` to the `native-image` command line (similarly it works the first time if there is no existing daemon, and then fails subsequently). So there is something weird about the state in the daemon.

**Comment by cstancu** [comment]
This is fixed in https://github.com/oracle/graal/commit/1f851caa935d2747898a0dcdc04c9382c65c7df9 which will be available in rc14.

**Comment by cstancu** [comment]
I added some [`java.util.logging` documentation ](https://github.com/oracle/graal/blob/master/substratevm/LOGGING.md).
