### ISSUE TITLE
Add option to omit debuglink info

### ISSUE THREAD

**Issue by galderz** [oracle/graal#7287]
When you build a native executable with debug info, it generates a companion debug info file, e.g.

```bash
-rwxr-xr-x.  1 g g  48M Aug 28 12:44 getting-started-reactive-1.0.0-SNAPSHOT-runner
-rwxr-xr-x.  1 g g 144M Aug 28 12:44 getting-started-reactive-1.0.0-SNAPSHOT-runner.debug
```

My understanding was that the debug info would be picked even if the files were renamed, as long as the debug info would just add the `.debug` suffix to the binary name. However, through some testing realised this is not the case.

Speak with @adinn, he said this should work. However, it seems that a link is established directly in the binary file, see `NativeImageDebugInfoStripFeature`:

```java
FileUtils.executeCommand(objcopyExe, "--strip-all", "--keep-symbols=" + exportedSymbolsPath, imageFilePath);
FileUtils.executeCommand(objcopyExe, "--add-gnu-debuglink=" + debugInfoFilePath, imageFilePath);
```

We can also observe that in the binary itself:

```bash
$ objdump -s -j .gnu_debuglink quickstart/target/getting-started-reactive-1.0.0-SNAPSHOT-runner

quickstart/target/getting-started-reactive-1.0.0-SNAPSHOT-runner:     file format elf64-x86-64

Contents of section .gnu_debuglink:
 0000 67657474 696e672d 73746172 7465642d  getting-started-
 0010 72656163 74697665 2d312e30 2e302d53  reactive-1.0.0-S
 0020 4e415053 484f542d 72756e6e 65722e64  NAPSHOT-runner.d
 0030 65627567 00000000 5eafb67b           ebug....^..{
```

There should be an option to avoid adding this link and instead relying on the default mechanism to locate the debug info file.

**Comment by galderz** [comment]
Hmmm, I run some quick experiments and if you remove:

```java
FileUtils.executeCommand(objcopyExe, "--add-gnu-debuglink=" + debugInfoFilePath, imageFilePath)
```

Then the debug symbols are not found any more. Reading the [gdb documentation](https://sourceware.org/gdb/onlinedocs/gdb/Separate-Debug-Files.html), it looks like you really need the debuglink information to link both together.

**Comment by adinn** [comment]
Yes, it appears the debuglink section is necessary to link the image file to its debug info (the other alternative, build-ids, has worse problems).

So, that means if you rename the image file from `/path/to/foo` to `/other/path/to/foobar` you cannot rename the debug info file from `/path/to/foo.debug` to `/other/path/to/foobar.debug`. The `.debuglink` section will still contain string `"foo.debug"` so the lookup algorithm will try to locate the debug info with filename `/other/path/to/foo.debug`.

So, while it's ok to relocate both files to a different directory. What you cannot change is the base file name of the `.debug` file. Which means it is also best not to change the base file name of the original executable.

I don't think there is any easy way round this behaviour and nothing to fix here. I suggest we file this issue under "It's a feature, not a bug".

**Comment by galderz** [comment]
Thanks @adinn for the explanation. I'll close this issue for now.
