### ISSUE TITLE
Add with constant

### ISSUE THREAD

**Issue by PhilippGrulich** [oracle/graal#729]
Hi,

for the following snippet, the generated code is not optimal:

Snippet:
```java
array[0] = array[0] + 3;
```

Generated code:
```
mov       r10d, 0x3                        
add       r10d, [rdx + 16]  
mov       [rdx + 16], r10d   
```

In this case, one operand is a constant.
Therefore we could emit an ADD with immediate instead of the generated code.

```
add       [rdx + 16], 1  
```

As far as I understood the problem, I think that we should extend the addMemory rule in AMD64NodeMatchRules. It should take into account If one of the operands is a constant. 

Is that the right place for this change? 

Best,
Philipp

**Comment by wirthi** [comment]
Closing this older ticket, seems to be answered with no additional action since 2018.
