### ISSUE TITLE
How to debug during the compilation phase

### ISSUE THREAD

**Issue by zenghu1chen** [oracle/graal#7315]
**Describe the issue**
I am trying to adapt some private packages, and after some configuration, when I compile using `mvn -Pnative native:compile`, I encounter the following error:
```
Error: Classes that should be initialized at run time got initialized during image building:
 org.slf4j.LoggerFactory was unintentionally initialized at build time. To see why org.slf4j.LoggerFactory got initialized use --trace-class-initialization=org.slf4j.LoggerFactory
To see how the classes got initialized, use --trace-class-initialization=org.slf4j.LoggerFactory
```

After adding the --trace-class-initialization=org.slf4j.LoggerFactory parameter, the error remained unchanged. 

**Steps to reproduce the issue**
Due to compliance reasons, I cannot share my example.

**Describe GraalVM and your environment:**
 - GraalVM version: graalvm-ce-java17-22.3.3
 - JDK major version: 17
 - OS: macOS Big Sur 11.1
 - Architecture: AMD64

**More details**
Since I am unable to share examples, I would like to know how to analyze problems and if it is possible to debug them on my own. It seems that there is limited developer documentation available on this topic, and I haven't found any similar cases either.

**Comment by oubidar-Abderrahim** [comment]
Class initialization is a tricky issue, as suggested in the stacktrace you can use --trace-class-initialization=org.slf4j.LoggerFactory to find the culprit class and then force its initialization at runtime. 

You can find some information here: https://docs.oracle.com/en/graalvm/enterprise/21/docs/reference-manual/native-image/ClassInitialization/#build-time-initialization-of-native-image-runtime

**Comment by zenghu1chen** [comment]
Okay, I previously configured `--trace-class-initialization=org.slf4j.LoggerFactory` in the `native-image.properties` file, but it didn't work. However, today I found that it works when I configure it in the `pom.xml` file.
```
            <plugin>
                <groupId>org.graalvm.buildtools</groupId>
                <artifactId>native-maven-plugin</artifactId>
                <configuration>
                    <buildArgs>
                        --trace-class-initialization=org.slf4j.LoggerFactory
                    </buildArgs>
                </configuration>
            </plugin>
```
Does this mean that as long as I configure it along the stack trace, I will eventually be able to compile successfully? Or are there certain cases where I have to modify the code?
