### ISSUE TITLE
How to solve the coding problem of programs

### ISSUE THREAD

**Issue by kungoudemahou** [oracle/graal#7342]
"mvn -Pnative native:compile"
The processed exe file can be started, but processing the Excel file in the program will result in "java. nio. charset. Unsupported CharsetException: CP1252"
Use 'native image - H:+AddAllCharsets - cp Main ' for a single Java file "can solve my problem, so I plan to use" native image "to compile my jar file into an exe file, but error" Main entry point class' Main 'neither found on the classpath nor on the modulepath

**Comment by fniephaus** [comment]
You probably need to fix you command line and remove some spaces:
```bash
native image -H:+AddAllCharsets Main 
```

or provide a classpath:
```bash
native image -H:+AddAllCharsets -cp ./ Main 
```
