### ISSUE TITLE
 Add stable option for option -H:-SpawnIsolates, -H:DeadlockWatchdogInterval, -H:-DeadlockWatchdogExitOnTimeout and -HNumberOf Threads=

### ISSUE THREAD

**Issue by adinn** [oracle/graal#7358]
I'm not clear why any of these 4 options are classified as experimental

```
-H:-SpawnIsolates
-H:DeadlockWatchdogInterval
-H:-DeadlockWatchdogExitOnTimeout
-H:NumberOfThreads=...
```

Is there a reason to place them in that category?

**Comment by fniephaus** [comment]
> Is there a reason to place them in that category?

Let's see...

> -H:-SpawnIsolates

Disabling support for multiple isolates is simply not supported. We use this internally for testing purposes. cc @christianwimmer

> `-H:DeadlockWatchdogInterval` and `-H:-DeadlockWatchdogExitOnTimeout`

If users have to use this, then something is wrong with our deadlock watchdog. By keeping the options experimental, we have a chance that users report such problems, so that we can improve the watchdog.

> `-H:NumberOfThreads=...`

The build output should inform you that there is an alternative public API: `--parallelism` (see https://github.com/oracle/graal/pull/6707 for details).

Hope this helps!

-- Fabio

**Comment by adinn** [comment]
> Disabling support for multiple isolates is simply not supported. We use this internally for testing purposes. cc @christianwimmer

Ok, thanks for clarifying.



> >     -H:DeadlockWatchdogInterval and -H:-DeadlockWatchdogExitOnTimeout
> 
> If users have to use this, then something is wrong with our deadlock watchdog. By keeping the options experimental, we have a chance that users report such problems, so that we can improve the watchdog.

Well, I mentioned this because I set them when I am debugging the native image generator using the Java debugger. In that circumstance one can sit under a timer wait for a lot longer than in normal execution. It's rather annoying when part way through debugging a problem to have the watchdog kill the debug session.

Of course, this is a specialized usage not appropriate for normal users of native image.

> > -H:NumberOfThreads=...
> 
> The build output should inform you that there is an alternative public API: --parallelism (see https://github.com/oracle/graal/pull/6707 for details).

Ah, thank you. I did not see that PR go in, nor did I spot the extra output in the warning about use of the -H option.

BTW, the reason I set this is that when debugging the compiler I really need to ensure that compilations happen sequentially. If not then Java breakpoints are regularly skipped -- it's an unfortunate feature of Java debuggers that stepping a stopped thread has the unfortunate corollary requirement of allowing other threads to proceed past a break without stopping.

Unfortunately, this setting is not enough on its own to solve the problem. The thread that kicks off the compilation work steals tasks from the compilation executor pool. So, even if you configure --parallelism 1 you end up with more than one compilation running at once (note that supplyning value 0 is explicitly rejected). Is this that intended meaning for this flag (passing 1 actually means use 2 threads to do compilation)? Is there are reason why it has to be done this way?

I resolved my debugging problem by setting --parallelism 1 building the generator with a patch that causes the main thread to wait for the queue to drain without work stealing. Is there a better solution for this? Or could one be provided?

**Comment by christianwimmer** [comment]
> Well, I mentioned this because I set them when I am debugging the native image generator using the Java debugger. In that circumstance one can sit under a timer wait for a lot longer than in normal execution. It's rather annoying when part way through debugging a problem to have the watchdog kill the debug session.

When you start the image generator with `--debug-attach`, then the deadlock watchdog is automatically disabled.

**Comment by fniephaus** [comment]
> So, even if you configure --parallelism 1 you end up with more than one compilation running at once (note that supplyning value 0 is explicitly rejected). Is this that intended meaning for this flag (passing 1 actually means use 2 threads to do compilation)? Is there are reason why it has to be done this way?
> I resolved my debugging problem by setting --parallelism 1 building the generator with a patch that causes the main thread to wait for the queue to drain without work stealing. Is there a better solution for this? Or could one be provided?

BTW: `--parallelism 1` is currently not supported, the minimum value is `2` at the moment (https://github.com/oracle/graal/commit/272d9d10ef605346821ce72e8a52839daa5b69cb). In the future, we want to do what you're patch is doing when `--parallelism` is set to `1`: let the main thread wait instead of helping the worker threads.
