### ISSUE TITLE
 gu install native-image fails downloading metadata-json

### ISSUE THREAD

**Issue by koraytugay** [oracle/graal#7372]
`gu install` is failing with below:

```
  gu install native-image
  shell: /usr/bin/bash -e {0}
  env:
    JAVA_HOME: /opt/hostedtoolcache/GraalVM/21.3.0-java11/x64
    JAVA_HOME_21.3.0.java11: /opt/hostedtoolcache/GraalVM/21.3.0-java11/x64
Downloading: Release index file from oca.opensource.oracle.com
Error: Error reading component list: https://oca.opensource.oracle.com/gds/meta-data.json
```

**Comment by fniephaus** [comment]
Hi @koraytugay, GraalVM 21.3.0 is using a GU catalog that was recently retired. Please upgrade to ` 21.3.3.1` or later and this should work again. The last GraalVM release with support for JDK 11 is 22.3.X.

Please let me know if you have any further questions. Happy building!

**Comment by koraytugay** [comment]
Thank you @fniephaus , upgrading worked.
