### ISSUE TITLE
Compiling Feature with "--release 17" fails because of missing package org.graalvm.nativeimage.hosted

### ISSUE THREAD

**Issue by petitajt** [oracle/graal#7414]
Compiling a class implementing Feature when passing `--release 17` flag to javac result in failure with following error: `package org.graalvm.nativeimage.hosted does not exist`.

Using `--source 17 --target 17` or no flag at all succeeds.

Failure might be because of `@since  19.0` in `org.graalvm.nativeimage.hosted.Feature`. It seems the compiler mixes GraalVM and Java versions.

**Steps to reproduce the issue**
1. Copy following class
```java
package com.example.config;

import org.graalvm.nativeimage.hosted.Feature;

class RuntimeReflectionRegistrationFeature implements Feature {
        @Override
        public void beforeAnalysis(BeforeAnalysisAccess access) {
        }
}
```
2. try to compile it using command `javac --release 17 RuntimeReflectionRegistrationFeature.java` will fail
3. try to compile it using command `javac --source 17 --target 17 RuntimeReflectionRegistrationFeature.java` will succeed

**Describe GraalVM and your environment:**
 - GraalVM version:
   - Oracle GraalVM 17.0.8+9.1 (build 17.0.8+9-LTS-jvmci-23.0-b14) from SDKMAN
   - OpenJDK 64-Bit Server VM Liberica-NIK-23.0.0-1 (build 17.0.7+7-LTS, mixed mode, sharing) from SDKMAN
   - OpenJDK 64-Bit Server VM GraalVM CE 21-dev+35.1 (build 21+35-jvmci-23.1-b14, mixed mode, sharing)  from https://github.com/graalvm/graalvm-ce-dev-builds/releases
 - JDK major version: 17 / 21
 - OS: linux
 - Architecture: AMD64

**More details**
Complete stacktrace
```
RuntimeReflectionRegistrationFeature.java:3: error: package org.graalvm.nativeimage.hosted does not exist
import org.graalvm.nativeimage.hosted.Feature;
                                     ^
RuntimeReflectionRegistrationFeature.java:5: error: cannot find symbol
class RuntimeReflectionRegistrationFeature implements Feature {
                                                      ^
  symbol: class Feature
RuntimeReflectionRegistrationFeature.java:7: error: cannot find symbol
        public void beforeAnalysis(BeforeAnalysisAccess access) {
                                   ^
  symbol:   class BeforeAnalysisAccess
  location: class RuntimeReflectionRegistrationFeature
RuntimeReflectionRegistrationFeature.java:6: error: method does not override or implement a method from a supertype
        @Override
        ^
4 errors
```

**Comment by oubidar-Abderrahim** [comment]
Thank you for reporting this, we'll take a look into it shortly
Tracked internally on GR 48873

**Comment by vjovanov** [comment]
Thank you for bringing this up. This functionality is by the spec of `--release` as it includes only the modules defined in the [java.se](https://docs.oracle.com/en/java/javase/21/docs/api/java.se/module-summary.html) module.

To fix this issue please include the [native-image module](https://mvnrepository.com/artifact/org.graalvm.sdk/nativeimage) to the `javac` command when `--release` is used.

**Comment by petitajt** [comment]
Thanks for the information.

I can confirm including the module does solve the problem.

Original error came from an attempt to build an simple native spring-boot app, including Feature, built using maven.
Note that the dependency must be defined at scope "provided" to avoid it being passed to native-image's "-cp" (which is not supported).
