### ISSUE TITLE
Clarify effect of -H:+AllowVMInspection

### ISSUE THREAD

**Issue by Sanne** [oracle/graal#744]
This is a suggestion to clarify a paragraph of the documentation.

The page at https://www.graalvm.org/docs/reference-manual/tools/ in section  "Starting Graal VisualVM" has the following note:

> Substrate VM processes are only displayed in the Applications area if created by the native-image tool with the -H:+AllowVMInspection flag. 

So I was trying that and trying to get VisualVM to show the process, and asked on gitter for help on this.

Paul Woegerer helpfully pointed out that the AllowVMInspection is used for something else entirely:

> Dump all stacks with sending SIGQUIT https://github.com/oracle/graal/blob/39cf5a8730c799da059c7ec434b90bd0ec48020f/substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/VMInspection.java#L87
> Generate a heap report on SIGUSR1 https://github.com/oracle/graal/blob/39cf5a8730c799da059c7ec434b90bd0ec48020f/substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/VMInspection.java#L121 ... btw, you should be able to open the dumped *.hprof file with jvisualvm
> Show you info about run-time compiled methods on SIGUSR2 https://github.com/oracle/graal/blob/39cf5a8730c799da059c7ec434b90bd0ec48020f/substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/VMInspection.java#L158

Also apparently to get VisualVM to connect to a native process, this must be built with the EE version of Graal. Would be great for that note to clarify this.

**Comment by olyagpl** [comment]
Hi @Sanne, your suggestion has been taken into account. 
Please see our separate reference manual on generating native heap:  dumps:https://www.graalvm.org/docs/reference-manual/native_heapdump/

**Comment by Sanne** [comment]
Thanks!

The new guide looks very nice. I'd still suggest the wording could use some more clarity about what works in EE and what not though:

the first paragraph states heap dumps aren't an option in non-EE, but then it start explaining an alternative strategy which requires a bit of coding. It's not clear if such additional coding leads to have the functionality on EE only, or both.

Regards,
Sanne
