### ISSUE TITLE
Support Linux running PowerPC64 Little Endian mode (`linux-ppc64le`)

### ISSUE THREAD

**Issue by runlevel5** [oracle/graal#7461]
**Feature request**

PowerPC 64 Little Endian (IBM POWER8 or newer) has been quite popular amongst academics and big enterprises. In fact many Java-based apps are now running on POWER-based hardwares serving so many people in the world.

I think by offering official support for linux-ppc64le, it would really help people in the PPC community adopt Graal.

**Comment by oubidar-Abderrahim** [comment]
Hi, Thank you for your suggestion
Tracked internally on GR 48920

**Comment by oubidar-Abderrahim** [comment]
Unfortunately, we don't have any plans to implement PowerPC support at the moment.
