### ISSUE TITLE
Native-image on aarch64 failed at last step With GraalVM 21

### ISSUE THREAD

**Issue by youngcle** [oracle/graal#7467]
GraalVM 21 released on 2023-09-19, and I switch my app jdk to Oracle GraalVM 21 to do some native-image test.

before I turned to GraalVM 21, I'm with GraalVM 17.0.8+9.1 (build 17.0.8+9-LTS-jvmci-23.0-b14) and everything is right in X86 (ubuntu 2210) and arm (ubuntu 1804 in Qemu) both.

after switched, JVM version and X86 nativeimage runner goes well.

When I try to make the native image in ARM, compiler failed at the last step "creating image" 

I think the key info is 

 undefined reference to `__aarch64_ldadd8_acq_rel'
`__aarch64_cas4_acq_rel'
`__aarch64_cas8_acq_rel'

the full trace is as following:

```
java.lang.RuntimeException: There was an error linking the native image: Linker command exited with 1

Linker command executed:
/usr/bin/gcc -z noexecstack -Wl,--gc-sections -Wl,--version-script,/tmp/SVM-13567779887183742065/exported_symbols.list -Wl,-x -o /data/cast503/develop/develop/sat-scheduler-edge/edge-command/target/edge-command-1.0.0-SNAPSHOT-native-image-source-jar/edge-command-1.0.0-SNAPSHOT-runner edge-command-1.0.0-SNAPSHOT-runner.o /root/graalvm-jdk-21+35.1/lib/svm/clibraries/linux-aarch64/liblibchelper.a /root/graalvm-jdk-21+35.1/lib/static/linux-aarch64/glibc/libnet.a /root/graalvm-jdk-21+35.1/lib/static/linux-aarch64/glibc/libextnet.a /root/graalvm-jdk-21+35.1/lib/static/linux-aarch64/glibc/libnio.a /root/graalvm-jdk-21+35.1/lib/static/linux-aarch64/glibc/libmanagement_ext.a /root/graalvm-jdk-21+35.1/lib/static/linux-aarch64/glibc/libjava.a /root/graalvm-jdk-21+35.1/lib/static/linux-aarch64/glibc/libzip.a /root/graalvm-jdk-21+35.1/lib/svm/clibraries/linux-aarch64/libjvm.a -Wl,--export-dynamic -v -L/tmp/SVM-13567779887183742065 -L/root/graalvm-jdk-21+35.1/lib/static/linux-aarch64/glibc -L/root/graalvm-jdk-21+35.1/lib/svm/clibraries/linux-aarch64 -lg1gc-cr -ldl -lm -lpthread -lstdc++ -lz -ldl -lpthread -lrt -no-pie

Linker command output:
Using built-in specs.
COLLECT_GCC=/usr/bin/gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/aarch64-linux-gnu/7/lto-wrapper
Target: aarch64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu/Linaro 7.5.0-3ubuntu1~18.04' --with-bugurl=file:///usr/share/doc/gcc-7/README.Bugs --enable-languages=c,ada,c++,go,d,fortran,objc,obj-c++ --prefix=/usr --with-gcc-major-version-only --program-suffix=-7 --program-prefix=aarch64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-bootstrap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-libquadmath --disable-libquadmath-support --enable-plugin --enable-default-pie --with-system-zlib --enable-multiarch --enable-fix-cortex-a53-843419 --disable-werror --enable-checking=release --build=aarch64-linux-gnu --host=aarch64-linux-gnu --target=aarch64-linux-gnu
Thread model: posix
gcc version 7.5.0 (Ubuntu/Linaro 7.5.0-3ubuntu1~18.04) 
COMPILER_PATH=/usr/lib/gcc/aarch64-linux-gnu/7/:/usr/lib/gcc/aarch64-linux-gnu/7/:/usr/lib/gcc/aarch64-linux-gnu/:/usr/lib/gcc/aarch64-linux-gnu/7/:/usr/lib/gcc/aarch64-linux-gnu/
LIBRARY_PATH=/usr/lib/gcc/aarch64-linux-gnu/7/:/usr/lib/gcc/aarch64-linux-gnu/7/../../../aarch64-linux-gnu/:/usr/lib/gcc/aarch64-linux-gnu/7/../../../../lib/:/lib/aarch64-linux-gnu/:/lib/../lib/:/usr/lib/aarch64-linux-gnu/:/usr/lib/../lib/:/usr/lib/gcc/aarch64-linux-gnu/7/../../../:/lib/:/usr/lib/
COLLECT_GCC_OPTIONS='-z' 'noexecstack' '-o' '/data/cast503/develop/develop/sat-scheduler-edge/edge-command/target/edge-command-1.0.0-SNAPSHOT-native-image-source-jar/edge-command-1.0.0-SNAPSHOT-runner' '-v' '-L/tmp/SVM-13567779887183742065' '-L/root/graalvm-jdk-21+35.1/lib/static/linux-aarch64/glibc' '-L/root/graalvm-jdk-21+35.1/lib/svm/clibraries/linux-aarch64' '-no-pie' '-mlittle-endian' '-mabi=lp64'
 /usr/lib/gcc/aarch64-linux-gnu/7/collect2 -plugin /usr/lib/gcc/aarch64-linux-gnu/7/liblto_plugin.so -plugin-opt=/usr/lib/gcc/aarch64-linux-gnu/7/lto-wrapper -plugin-opt=-fresolution=/tmp/ccRS9L0e.res -plugin-opt=-pass-through=-lgcc -plugin-opt=-pass-through=-lgcc_s -plugin-opt=-pass-through=-lc -plugin-opt=-pass-through=-lgcc -plugin-opt=-pass-through=-lgcc_s --build-id --eh-frame-hdr --hash-style=gnu --as-needed -dynamic-linker /lib/ld-linux-aarch64.so.1 -X -EL -maarch64linux --fix-cortex-a53-843419 -z relro -o /data/cast503/develop/develop/sat-scheduler-edge/edge-command/target/edge-command-1.0.0-SNAPSHOT-native-image-source-jar/edge-command-1.0.0-SNAPSHOT-runner -z noexecstack /usr/lib/gcc/aarch64-linux-gnu/7/../../../aarch64-linux-gnu/crt1.o /usr/lib/gcc/aarch64-linux-gnu/7/../../../aarch64-linux-gnu/crti.o /usr/lib/gcc/aarch64-linux-gnu/7/crtbegin.o -L/tmp/SVM-13567779887183742065 -L/root/graalvm-jdk-21+35.1/lib/static/linux-aarch64/glibc -L/root/graalvm-jdk-21+35.1/lib/svm/clibraries/linux-aarch64 -L/usr/lib/gcc/aarch64-linux-gnu/7 -L/usr/lib/gcc/aarch64-linux-gnu/7/../../../aarch64-linux-gnu -L/usr/lib/gcc/aarch64-linux-gnu/7/../../../../lib -L/lib/aarch64-linux-gnu -L/lib/../lib -L/usr/lib/aarch64-linux-gnu -L/usr/lib/../lib -L/usr/lib/gcc/aarch64-linux-gnu/7/../../.. --gc-sections --version-script /tmp/SVM-13567779887183742065/exported_symbols.list -x edge-command-1.0.0-SNAPSHOT-runner.o /root/graalvm-jdk-21+35.1/lib/svm/clibraries/linux-aarch64/liblibchelper.a /root/graalvm-jdk-21+35.1/lib/static/linux-aarch64/glibc/libnet.a /root/graalvm-jdk-21+35.1/lib/static/linux-aarch64/glibc/libextnet.a /root/graalvm-jdk-21+35.1/lib/static/linux-aarch64/glibc/libnio.a /root/graalvm-jdk-21+35.1/lib/static/linux-aarch64/glibc/libmanagement_ext.a /root/graalvm-jdk-21+35.1/lib/static/linux-aarch64/glibc/libjava.a /root/graalvm-jdk-21+35.1/lib/static/linux-aarch64/glibc/libzip.a /root/graalvm-jdk-21+35.1/lib/svm/clibraries/linux-aarch64/libjvm.a --export-dynamic -lg1gc-cr -ldl -lm -lpthread -lstdc++ -lz -ldl -lpthread -lrt -lgcc --push-state --as-needed -lgcc_s --pop-state -lc -lgcc --push-state --as-needed -lgcc_s --pop-state /usr/lib/gcc/aarch64-linux-gnu/7/crtend.o /usr/lib/gcc/aarch64-linux-gnu/7/../../../aarch64-linux-gnu/crtn.o
/root/graalvm-jdk-21+35.1/lib/svm/clibraries/linux-aarch64/liblibchelper.a(cSunMiscSignal.o): In function `cSunMiscSignal_atomicIncrement':
graal/substratevm/mxbuild/linux-aarch64/com.oracle.svm.native.libchelper/aarch64/graal/substratevm/src/com.oracle.svm.native.libchelper/src/cSunMiscSignal.c:247: undefined reference to `__aarch64_ldadd8_acq_rel'
/root/graalvm-jdk-21+35.1/lib/svm/clibraries/linux-aarch64/liblibchelper.a(cSunMiscSignal.o): In function `cSunMiscSignal_atomicCompareAndSwap_int':
graal/substratevm/mxbuild/linux-aarch64/com.oracle.svm.native.libchelper/aarch64/graal/substratevm/src/com.oracle.svm.native.libchelper/src/cSunMiscSignal.c:273: undefined reference to `__aarch64_cas4_acq_rel'
/root/graalvm-jdk-21+35.1/lib/svm/clibraries/linux-aarch64/liblibchelper.a(cSunMiscSignal.o): In function `cSunMiscSignal_atomicCompareAndSwap_long':
graal/substratevm/mxbuild/linux-aarch64/com.oracle.svm.native.libchelper/aarch64/graal/substratevm/src/com.oracle.svm.native.libchelper/src/cSunMiscSignal.c:278: undefined reference to `__aarch64_cas8_acq_rel'
collect2: error: ld returned 1 exit status
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.image.NativeImageViaCC.handleLinkerFailure(NativeImageViaCC.java:202)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.image.NativeImageViaCC.runLinkerCommand(NativeImageViaCC.java:152)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.image.NativeImageViaCC.write(NativeImageViaCC.java:118)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:742)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:551)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:538)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:720)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.start(NativeImageGeneratorRunner.java:142)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:97)
```

**Describe GraalVM and your environment:**
x86
6.2.0-33-generic https://github.com/quarkusio/quarkus/pull/33~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Thu Sep 7 10:33:52 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

arm by qemu
Linux ubuntu 4.15.0-213-generic https://github.com/quarkusio/quarkus/pull/224-Ubuntu SMP Mon Jun 19 13:29:44 UTC 2023 aarch64 aarch64 aarch64 GNU/Linux

Output of java -version
x86
Java(TM) SE Runtime Environment Oracle GraalVM 21+35.1 (build 21+35-jvmci-23.1-b15)

arm by qemu
Java(TM) SE Runtime Environment Oracle GraalVM 21+35.1 (build 21+35-jvmci-23.1-b15)

my app is Powered by Quarkus 3.3.3

**Comment by SergejIsbrecht** [comment]
I ran into the same issue, because gcc 7, in my case gcc6, did have this atomics in the libgcc lib. The main problem are different gcc used for creating the native Image and the gcc used to build the graalvm distribution. You have to upgrade your gcc to at least 10 I think or compile the graalvm distribution with `-mno-outline-atomics`.

**Comment by youngcle** [comment]
Thanks a lot. You are right.

I checked In my qemu and this is the right solution.

the gcc in ubuntu 1804 is a little bit old, and oracle graalvm 21 upgrade it inisde.

I think it's much better if they documents this change in the change log or somewhere.

the issue should closed.

> I ran into the same issue, because gcc 7, in my case gcc6, did have this atomics in the libgcc lib. The main problem are different gcc used for creating the native Image and the gcc used to build the graalvm distribution. You have to upgrade your gcc to at least gcc9 or compile the graalvm distribution with `-mno-outline-atomics`. In my experience upgrading to an arm gcc 10 Toolchain is the easiest way to avoid this issue.
> 
> https://developer.arm.com/downloads/-/gnu-rm
> 
> See https://stackoverflow.com/questions/65239845/how-to-enable-mno-outline-atomics-aarch64-flag

**Comment by youngcle** [comment]
Thanks a lot. You are right.

I checked In my qemu and this is the right solution.

the gcc in ubuntu 1804 is a little bit old, and oracle graalvm 21 upgrade it inisde.

I think it's much better if they documents this change in the change log or somewhere.

the issue should closed.

> I ran into the same issue, because gcc 7, in my case gcc6, did have this atomics in the libgcc lib. The main problem are different gcc used for creating the native Image and the gcc used to build the graalvm distribution. You have to upgrade your gcc to at least gcc9 or compile the graalvm distribution with `-mno-outline-atomics`. In my experience upgrading to an arm gcc 10 Toolchain is the easiest way to avoid this issue.
> 
> https://developer.arm.com/downloads/-/gnu-rm
> 
> See https://stackoverflow.com/questions/65239845/how-to-enable-mno-outline-atomics-aarch64-flag

**Comment by youngcle** [comment]
Thanks a lot. You are right.

I checked In my qemu and this is the right solution.

the gcc in ubuntu 1804 is a little bit old, and oracle graalvm 21 upgrade it inisde.

I think it's much better if they documents this change in the change log or somewhere.

the issue should closed.

> I ran into the same issue, because gcc 7, in my case gcc6, did have this atomics in the libgcc lib. The main problem are different gcc used for creating the native Image and the gcc used to build the graalvm distribution. You have to upgrade your gcc to at least gcc9 or compile the graalvm distribution with `-mno-outline-atomics`. In my experience upgrading to an arm gcc 10 Toolchain is the easiest way to avoid this issue.
> 
> https://developer.arm.com/downloads/-/gnu-rm
> 
> See https://stackoverflow.com/questions/65239845/how-to-enable-mno-outline-atomics-aarch64-flag

**Comment by yermukhanJJ** [comment]
I have the same issue, but i used spring webflux 3.1.0 and r2dbc, java 17, graalvm 17. Help me

`java.lang.RuntimeException: There was an error linking the native image: Linker command exited with 1

Linker command executed:
/usr/bin/gcc -z noexecstack -Wl,--gc-sections -Wl,--version-script,/tmp/SVM-6371675945754227237/exported_symbols.list -Wl,-x -o '/home/yermukhan/Рабочий стол/demo/target/demo' demo.o '/home/yermukhan/Загрузки/graalvm-jdk-17.0.8+9.1/lib/svm/clibraries/linux-amd64/liblibchelper.a' '/home/yermukhan/Загрузки/graalvm-jdk-17.0.8+9.1/lib/static/linux-amd64/glibc/libnet.a' '/home/yermukhan/Загрузки/graalvm-jdk-17.0.8+9.1/lib/static/linux-amd64/glibc/libnio.a' '/home/yermukhan/Загрузки/graalvm-jdk-17.0.8+9.1/lib/static/linux-amd64/glibc/libjava.a' '/home/yermukhan/Загрузки/graalvm-jdk-17.0.8+9.1/lib/static/linux-amd64/glibc/libfdlibm.a' '/home/yermukhan/Загрузки/graalvm-jdk-17.0.8+9.1/lib/static/linux-amd64/glibc/libzip.a' '/home/yermukhan/Загрузки/graalvm-jdk-17.0.8+9.1/lib/svm/clibraries/linux-amd64/libjvm.a' -Wl,--export-dynamic -v -L/tmp/SVM-6371675945754227237 '-L/home/yermukhan/Загрузки/graalvm-jdk-17.0.8+9.1/lib/static/linux-amd64/glibc' '-L/home/yermukhan/Загрузки/graalvm-jdk-17.0.8+9.1/lib/svm/clibraries/linux-amd64' -lz -lpthread -ldl -lrt

Linker command output:
Using built-in specs.
COLLECT_GCC=/usr/bin/gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/11/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none:amdgcn-amdhsa
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 11.3.0-1ubuntu1~22.04.1' --with-bugurl=file:///usr/share/doc/gcc-11/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++,m2 --prefix=/usr --with-gcc-major-version-only --program-suffix=-11 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-bootstrap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-plugin --enable-default-pie --with-system-zlib --enable-libphobos-checking=release --with-target-system-zlib=auto --enable-objc-gc=auto --enable-multiarch --disable-werror --enable-cet --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none=/build/gcc-11-aYxV0E/gcc-11-11.3.0/debian/tmp-nvptx/usr,amdgcn-amdhsa=/build/gcc-11-aYxV0E/gcc-11-11.3.0/debian/tmp-gcn/usr --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu --with-build-config=bootstrap-lto-lean --enable-link-serialization=2
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 11.3.0 (Ubuntu 11.3.0-1ubuntu1~22.04.1) 
COMPILER_PATH=/usr/lib/gcc/x86_64-linux-gnu/11/:/usr/lib/gcc/x86_64-linux-gnu/11/:/usr/lib/gcc/x86_64-linux-gnu/:/usr/lib/gcc/x86_64-linux-gnu/11/:/usr/lib/gcc/x86_64-linux-gnu/
LIBRARY_PATH=/usr/lib/gcc/x86_64-linux-gnu/11/:/usr/lib/gcc/x86_64-linux-gnu/11/../../../x86_64-linux-gnu/:/usr/lib/gcc/x86_64-linux-gnu/11/../../../../lib/:/lib/x86_64-linux-gnu/:/lib/../lib/:/usr/lib/x86_64-linux-gnu/:/usr/lib/../lib/:/usr/lib/gcc/x86_64-linux-gnu/11/../../../:/lib/:/usr/lib/
COLLECT_GCC_OPTIONS='-z' 'noexecstack' '-o' '/home/yermukhan/Рабочий стол/demo/target/demo' '-v' '-L/tmp/SVM-6371675945754227237' '-L/home/yermukhan/Загрузки/graalvm-jdk-17.0.8+9.1/lib/static/linux-amd64/glibc' '-L/home/yermukhan/Загрузки/graalvm-jdk-17.0.8+9.1/lib/svm/clibraries/linux-amd64' '-mtune=generic' '-march=x86-64' '-dumpdir' '/home/yermukhan/Рабочий стол/demo/target/demo.'
 /usr/lib/gcc/x86_64-linux-gnu/11/collect2 -plugin /usr/lib/gcc/x86_64-linux-gnu/11/liblto_plugin.so -plugin-opt=/usr/lib/gcc/x86_64-linux-gnu/11/lto-wrapper -plugin-opt=-fresolution=/tmp/ccM128v7.res -plugin-opt=-pass-through=-lgcc -plugin-opt=-pass-through=-lgcc_s -plugin-opt=-pass-through=-lc -plugin-opt=-pass-through=-lgcc -plugin-opt=-pass-through=-lgcc_s --build-id --eh-frame-hdr -m elf_x86_64 --hash-style=gnu --as-needed -dynamic-linker /lib64/ld-linux-x86-64.so.2 -pie -z now -z relro -o /home/yermukhan/Рабочий стол/demo/target/demo -z noexecstack /usr/lib/gcc/x86_64-linux-gnu/11/../../../x86_64-linux-gnu/Scrt1.o /usr/lib/gcc/x86_64-linux-gnu/11/../../../x86_64-linux-gnu/crti.o /usr/lib/gcc/x86_64-linux-gnu/11/crtbeginS.o -L/tmp/SVM-6371675945754227237 -L/home/yermukhan/Загрузки/graalvm-jdk-17.0.8+9.1/lib/static/linux-amd64/glibc -L/home/yermukhan/Загрузки/graalvm-jdk-17.0.8+9.1/lib/svm/clibraries/linux-amd64 -L/usr/lib/gcc/x86_64-linux-gnu/11 -L/usr/lib/gcc/x86_64-linux-gnu/11/../../../x86_64-linux-gnu -L/usr/lib/gcc/x86_64-linux-gnu/11/../../../../lib -L/lib/x86_64-linux-gnu -L/lib/../lib -L/usr/lib/x86_64-linux-gnu -L/usr/lib/../lib -L/usr/lib/gcc/x86_64-linux-gnu/11/../../.. --gc-sections --version-script /tmp/SVM-6371675945754227237/exported_symbols.list -x demo.o /home/yermukhan/Загрузки/graalvm-jdk-17.0.8+9.1/lib/svm/clibraries/linux-amd64/liblibchelper.a /home/yermukhan/Загрузки/graalvm-jdk-17.0.8+9.1/lib/static/linux-amd64/glibc/libnet.a /home/yermukhan/Загрузки/graalvm-jdk-17.0.8+9.1/lib/static/linux-amd64/glibc/libnio.a /home/yermukhan/Загрузки/graalvm-jdk-17.0.8+9.1/lib/static/linux-amd64/glibc/libjava.a /home/yermukhan/Загрузки/graalvm-jdk-17.0.8+9.1/lib/static/linux-amd64/glibc/libfdlibm.a /home/yermukhan/Загрузки/graalvm-jdk-17.0.8+9.1/lib/static/linux-amd64/glibc/libzip.a /home/yermukhan/Загрузки/graalvm-jdk-17.0.8+9.1/lib/svm/clibraries/linux-amd64/libjvm.a --export-dynamic -lz -lpthread -ldl -lrt -lgcc --push-state --as-needed -lgcc_s --pop-state -lc -lgcc --push-state --as-needed -lgcc_s --pop-state /usr/lib/gcc/x86_64-linux-gnu/11/crtendS.o /usr/lib/gcc/x86_64-linux-gnu/11/../../../x86_64-linux-gnu/crtn.o
/usr/bin/ld: demo.o: warning: relocation in read-only section `.svm_heap'
/usr/bin/ld: demo.o:(.data+0x888): неопределённая ссылка на «Java_com_sun_management_internal_OperatingSystemImpl_initialize0»
/usr/bin/ld: warning: creating DT_TEXTREL in a PIE
collect2: error: ld returned 1 exit status
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.image.NativeImageViaCC.handleLinkerFailure(NativeImageViaCC.java:204)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.image.NativeImageViaCC.runLinkerCommand(NativeImageViaCC.java:151)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.image.NativeImageViaCC.write(NativeImageViaCC.java:117)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:724)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:539)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:408)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:612)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.start(NativeImageGeneratorRunner.java:134)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:94)`

**Comment by SergejIsbrecht** [comment]
@yermukhanJJ ,

I would recommend creating a new issue.

 неопределённая ссылка на  -> `undefined reference to`
```
/usr/bin/ld: demo.o: warning: relocation in read-only section `.svm_heap'
/usr/bin/ld: demo.o:(.data+0x888): неопределённая ссылка на «Java_com_sun_management_internal_OperatingSystemImpl_initialize0»
/usr/bin/ld: warning: creating DT_TEXTREL in a PIE
collect2: error: ld returned 1 exit status
```

I guess somehow `Java_com_sun_management_internal_OperatingSystemImpl_initialize0` is not found during linking?

Anyhow, I guess a new ticket with a repo-case is in order -- with all flags passed to native-image
