### ISSUE TITLE
node-inspector server fails intermitently

### ISSUE THREAD

**Issue by pmlopes** [oracle/graal#747]
When a graalvm is started with the tool node inspector enabled, vscode (but not chrome devtools) fails to connect intermittently (which makes it hard to produce a reproducer).

What I've observe is that, once a language context is created if I connect within ~5sec then usually it all works fine. If I connect later then the websocket server replies to vscode with `IllegalStateException` Engine is already closed. If I try to connect asap (meaning the JVM is already starting but no language context  has been fully initialized, the same happens as before Engine is closed, but If I try again later once everything is started and within the same 5sec it will fail forever with Engine is already closed although the application is running without issues...

For some reason chrome devtools do not seem to report any error... (maybe some issue with the protocol?)

**Comment by entlicher** [comment]
Most probably this has the same cause as issue #761 and thus it should be fixed by https://github.com/oracle/graal/commit/189df1de97fc5af2ba6c29a2f0483eee8024561f.
