### ISSUE TITLE
[GR-43389] Please reverse port this fix to graalvm for jdk17.

### ISSUE THREAD

**Issue by fenginsc** [oracle/graal#7479]
https://github.com/oracle/graal/issues/5778
I noticed that the issue has been fixed in the latest graalvm for jdk21 version(https://github.com/oracle/graal/pull/7361), but there is no reverse porting of the patch to graalvm for jdk17. 
Currently graalvm for jdk17 still has the native image compilation error for macOS amd64. 
Hopefully this can be fixed soon.
Thank you very much.

**Comment by fernando-valdez** [comment]
Hi @fenginsc, can you please confirm if this issue is fixed in the latest snapshot?

**Comment by fenginsc** [comment]
I'm not quite sure how to test the latest snapshot, but I tested the latest release:
```
Java version 17.0.9+11-LTS
Vendor version Oracle GraalVM 17.0.9+11.1
```
It still fails, showing `Bus error`.

**Comment by fenginsc** [comment]
@fernando-valdez 
```
 Java version: 17.0.10+11-LTS, vendor version: Oracle GraalVM 17.0.10+11.1
 Graal compiler: optimization level: 2, target machine: x86-64-v3, PGO: off
 C compiler: cc (apple, x86_64, 15.0.0)
```
I tested graalvm 17 again with the latest release so far and this bug has been fixed and it compiles fine now.
