### ISSUE TITLE
When will native-image fully support (--no-fallback) foreign  functions?

### ISSUE THREAD

**Issue by acodervic** [oracle/graal#7492]
Java 21 provides foreign functions, when will native-image fully support it? And memory API?

**Comment by oubidar-Abderrahim** [comment]
Hi, Thank you for reaching out, we do have some support for Foreign Functions and Memory API in native image, you can find more about it here: https://www.graalvm.org/latest/reference-manual/native-image/dynamic-features/foreign-interface/
A complete support is in progress, we do not have an ETA at the moment.
