### ISSUE TITLE
[native image] does not create shared library as PIC with -H:+GeneratePIC

### ISSUE THREAD

**Issue by wkozaczuk** [oracle/graal#750]
I have been trying to make GraalVM app run on OSv unikernel which implements subset of Linux ABI and makes it possible to run Linux apps (such as regular JVM) as long as there are pie. 

In the case of graalVM app we have a simple bootstrap app in C that is a pie which then executes shared library generated by native image (relevant command lines are excerpts from the app Makefile):

```
CFLAGS = -std=gnu99 -fPIC -rdynamic

main.so: libhello.so main.c
	$(CC) -pie -o $@ $(CFLAGS) -I. main.c -L. -lhello -ldl

Hello.class: Hello.java upstream/graalvm-ce-1.0.0-rc7
	upstream/graalvm-ce-1.0.0-rc7/bin/javac -d . Hello.java

libhello.so: Hello.class upstream/graalvm-ce-1.0.0-rc7
	upstream/graalvm-ce-1.0.0-rc7/bin/native-image --no-server --shared -H:Kind=SHARED_LIBRARY -H:+GeneratePIC -H:Name=libhello
```

The resulting libhello.so turns out not to be a PIC even though I pass -H:+GeneratePIC to native:
```
readelf -a libhello.so | grep -i textrel
 0x0000000000000016 (TEXTREL)            0x0
```

However if I try to run main.so with libhello.so on Linux it all works fine. In order to make GraalVM native images work on OSv we need to understand better what +GeneratePIC really does or specifically what flags get passed to gcc. As I understand normally 64-bit shared libraries on Linux have to be compiled with -fPIC unless so called large model is used (-mcmodel=large). Are then native-image shared libraries by designed generated as such? Could you please provide some insight?

Thanks,
Waldek Kozaczuk

**Comment by wkozaczuk** [comment]
Forgot to add a link to full example project - https://github.com/cloudius-systems/osv-apps/tree/master/graalvm-example

**Comment by wkozaczuk** [comment]
Correction: the line in the makefile above:
```
upstream/graalvm-ce-1.0.0-rc7/bin/native-image --no-server --shared -H:Kind=SHARED_LIBRARY -H:+GeneratePIC -H:Name=libhello
```
actually makes resulting library unusable and causes core dump on linux. The libhello.so is suspiciously small.

This one (change -H:+GeneratePIC to -R:+GeneratePIC) makes it work on Linux but not on OSv:
```
upstream/graalvm-ce-1.0.0-rc8/bin/native-image --no-server --shared -H:Kind=SHARED_LIBRARY -R:+GeneratePIC -H:Name=libhello
LD_LIBRARY_PATH=. ./main.so
```

I even generated image without -R:+GeneratePIC or -H:+GeneratePIC and in all 3 cases the libhello.so file had presence of TEXTREL attribute so I am not sure what GeneratePIC really does.

**Comment by olpaw** [comment]
Only our `--shared` option should be used to generate shared-objects. This is supported and known to work for Linux and OSX.

`-H/R:+/-GeneratePIC` on the other hand shines through from the graal compiler that we are using for image building. (One could argue that it should not even show up in `native-image --expert-options-all` - on the other hand end-users are not supposed to use any of those flags anyway.)

Even as an expert option it has no well defined meaning in the context of image building (`-H:`). There might be some exotic usecase where `-R:+GeneratePIC` makes sense. E.g. for images that contain graal in the image itself (which is certainly not the case in your `Hello.java` example). /cc @dougxc

**Comment by wkozaczuk** [comment]
@olpaw Thanks for responding to my issue.

If usage of -H:, -R: is discouraged when why do I have to pass -H:Name=libhello otherwise I get this error:
```
error: No output file name specified. Use '-H:Name=<output-file>'.
Error: Image building with exit status 1
Makefile:12: recipe for target 'libhello.so' failed
make: *** [libhello.so] Error 1
```

Also would you be so kind to explain what options are passed to gcc when building shared object? Clearly it is not simply -shared.

**Comment by olpaw** [comment]
> If usage of -H:, -R: is discouraged

That's not the case. Usage of  `-H:`, `-R:`  options of `OptionType` [org.graalvm.compiler.options.OptionType#User](https://github.com/oracle/graal/blob/6b02fc58e11da47f9e2fa8e064c165ee6d6258b6/compiler/src/org.graalvm.compiler.options/src/org/graalvm/compiler/options/OptionType.java#L35) is fine. Note that we only list the ones with `OptionType#User` when you use `native-image --expert-options`.

> what options are passed to gcc when building shared object?

Adding the following options to your image building should cause that particular kind of information to get dumped to stdout:
```
--no-server -H:Log=InvokeCC:
```
