### ISSUE TITLE
StackValueSnippets referred to in StackValue javadocs is not available anywhere (it seems)

### ISSUE THREAD

**Issue by dsyer** [oracle/graal#751]
I can't find it in the source code or in the distributed jars. I saw #181 (and it is closed as "won't fix") which seems relevant but not exactly the same since it was talking about snippets that were actually navigable.

**Comment by cstancu** [comment]
Is this what you are looking for: https://github.com/oracle/graal/blob/master/sdk/src/org.graalvm.nativeimage/src/org/graalvm/nativeimage/StackValue.java#L134?

**Comment by dsyer** [comment]
Yes, that's it. It's not included in the `graal-sdk.jar` or the `graal-sdk.src.zip` in the GraalVM distribution, so Eclipse can't find it.

**Comment by JaroslavTulach** [comment]
The source code is at bottom of `StackValue.java` class. Just scrolldown.

The reason why IDEs can't find it is that the `StackValueSnippets.class` is intentionally removed from the final JAR file. It doesn't contain production code, it only contains examples showing API usage. Looks like IDEs aren't ready for such setup.

The fix would be to include the snippet class files in the final JAR. However I don't think it is necessary. Just remember the convension and when there is `(.*)Snippets` class, find `\1` and jump to the bottom of the source file. Hopefully it is good enough workaround for now.

**Comment by dsyer** [comment]
OK, that kind of works in a kind of unusable sort of way. Is someone going to try and get the IDEs fixed and link back to here?
