### ISSUE TITLE
nativeimage of oracle graalvm  21 build failed on arm64

### ISSUE THREAD

**Issue by youngcle** [oracle/graal#7513]
I use Oracle Graalvm 21 with ubuntu to build arm version native image.This week I found my aarch64 verion native image got problem on centos system. After some study online, I found the reason is that centos PageSize is 64KB which differes from ubuntu's 4KB.

I've tried to set PageSize param in command line, the build process failed(not sure Is this another issue). so I made a centos qemu for build pagesize 64KB aarch64 nativeimage.

what's strange is the nativeimage build crushed.
I've installed two gcc toolchain in centos:
1 gcc 8.5
2 gcc 10(toolchain set)

I have 2 apps to build .

App A could build in gcc 10,crush in gcc 8.5
APP B could build in gcc 8.5, crush in gcc 10

hope someone can give some help or guide.

thanks 

some crush message is down here

```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x0000ffff93625600, pid=3490, tid=3682
#
# JRE version: Java(TM) SE Runtime Environment Oracle GraalVM 21+35.1 (21.0+35) (build 21+35-jvmci-23.1-b15)
# Java VM: Java HotSpot(TM) 64-Bit Server VM Oracle GraalVM 21+35.1 (21+35-jvmci-23.1-b15, mixed mode, tiered, jvmci, jvmci compiler, compressed oops, compressed class ptrs, parallel gc, linux-aarch64)
# Problematic frame:
# J 19697 jvmci java.util.concurrent.FutureTask.run()V java.base@21 (123 bytes) @ 0x0000ffff93625600 [0x0000ffff93625980+0xfffffffffffffc80]
#
# Core dump will be written. Default location: Core dumps may be processed with "/usr/lib/systemd/systemd-coredump %P %u %g %s %t %c %h %e" (or dumping to /data/code/sat-scheduler-edge/edge-service/core.3490)
#
# If you would like to submit a bug report, please visit:
#   https://bugreport.java.com/bugreport/crash.jsp
```

```


#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x0000ffff9b2b61fc, pid=44091, tid=44220
#
# JRE version: Java(TM) SE Runtime Environment Oracle GraalVM 21+35.1 (21.0+35) (build 21+35-jvmci-23.1-b15)
# Java VM: Java HotSpot(TM) 64-Bit Server VM Oracle GraalVM 21+35.1 (21+35-jvmci-23.1-b15, mixed mode, tiered, jvmci, jvmci compiler, compressed oops, compressed class ptrs, parallel gc, linux-aarch64)
# Problematic frame:
# J 20016 c1 org.graalvm.compiler.nodes.ShortCircuitOrNode.canonicalizeNegation(Lorg/graalvm/compiler/nodes/LogicNode;ZLorg/graalvm/compiler/nodes/LogicNode;ZLorg/graalvm/compiler/nodes/ProfileData$BranchProbabilityData;)Lorg/graalvm/compiler/nodes/ShortCircuitOrNode; jdk.internal.vm.compiler (110 bytes) @ 0x0000ffff9b2b61fc [0x0000ffff9b2b5840+0x00000000000009bc]
#
```

**Comment by Karm** [comment]
Hello @youngcle, 
I am not sure about possible quirks for those gcc versions, but here are things that come to my mind in this context:

* You cannot switch page size at will, you have to have the corresponding kernel for it running, at least that's how it works with CentOS/RHEL 9 like systems AFAIK.

* In our experience, building JDK on 64k big pages and running it on both 64k and 4k page systems is fine, although if you build JDK on a 4kb page system it **might** outright crash on a 64k page system due to misalignment. Could this be related then?

**Comment by youngcle** [comment]
> Hello @youngcle, I am not sure about possible quirks for those gcc versions, but here are things that come to my mind in this context:
> 
> * You cannot switch page size at will, you have to have the corresponding kernel for it running, at least that's how it works with CentOS/RHEL 9 like systems AFAIK.
> * In our experience, building JDK on 64k big pages and running it on both 64k and 4k page systems is fine, although if you build JDK on a 4kb page system it **might** outright crash on a 64k page system due to misalignment. Could this be related then?


thanks for reply.

I tried two app of mine, build on aarch64 centos and  the pagesize is 64k , running on ubuntu 1804,which is 4k page system,
app A runs well
app B failed with the same message

**Comment by youngcle** [comment]
After two days hard working, I found that my Ubuntu2304's Qemu 7.2 is the reason Graalvm crash.
I build a Qemu 8.1.1 on Ubuntu 2304, then everything going well.

I don't if there are other guys meet the same problem like me. 

If you upgrade to graalvm 21 and use qemu for cross compile nativeimage, then maybe you should upgrade your qemu to version 8.x

may this help other people
