### ISSUE TITLE
Support for bridging JObject (Pointer) to Object in native library

### ISSUE THREAD

**Issue by dsyer** [oracle/graal#752]
I'm intrigued by the "build a native library in Java" feature (https://github.com/oracle/graal/blob/master/substratevm/ImplementingNativeMethodsInJavaWithSVM.md). Played with it a bit and hit a roadblock. Maybe it's just something I didn't understand, but it seems like the only way to work with `JObject` messages passed in from the caller to a native method is via the `JNIEnvironment`. E.g. here is a native method that calls "apply" on the incoming inputs and returns the result:

```java
	@CEntryPoint(name = "Java_org_pkg_apinative_Native_run0")
	static JObject run(JNIEnvironment env, JClass clazz,
			@CEntryPoint.IsolateContext long isolateId, JObject function,
			JObject object) {
		JNINativeInterface fn = env.getFunctions();
		try (CTypeConversion.CCharPointerHolder name = CTypeConversion.toCString("apply");
				CTypeConversion.CCharPointerHolder sig = CTypeConversion
						.toCString("(Ljava/lang/Object;)Ljava/lang/Object;");) {
			JClass cls = fn.getGetObjectClass().find(env, function);
			JMethodID apply = fn.getGetMethodID().find(env, cls, name.get(), sig.get());
			JValue args = StackValue.get(1, JValue.class);
			args.addressOf(0).l(object);
			JObject result = fn.getCallObjectMethodA().call(env, function, apply, args);
			return result;
		}
	}
```

It works and it's neat, but I didn't need a native library to do that. What I'd like is a more "natural" API to work with the objects passed in from the JVM, e.g. to take the incoming function and cast it to `Function` in the native method:

```java
	@CEntryPoint(name = "Java_org_pkg_apinative_Native_run0")
	static JObject run(JNIEnvironment env, JClass clazz,
			@CEntryPoint.IsolateContext long isolateId, JObject function,
			JObject object) {
		Function<?,?> function = (Function<?,?>) function.toObject();
		Object result = function.apply(object.toObject());
		return CTypeConversion.toObject(result);
	}
```

(or something). I noticed that `Pointer` actually has that `toObject()` method, but the javadocs rather gnomically warn that it shouldn't be used (and it causes an exception if you try to build a native image). I made up the `CTypeConversion.toObject()` method because I couldn't find anything that looked like it would do that.

Is that possible? Might it be? I can see that there might be issues with the types of objects I use that way, if they are not JDK library classes. It would be interesting to know how bad those issues are.

**Comment by JaroslavTulach** [comment]
Thanks for your interest in this _implement native methods in Java_ feature. Btw. Last Friday I demoed it at GeeCON Prague and used [Matrix the Ultimate](https://github.com/JaroslavTulach/matrixultimate) project to show its benefits. 

_Matrix the Ultimate_ contains possible implementation of the `CTypeConversion.toObject` method: so far it is [hardcoded for a single specific usecase](https://github.com/JaroslavTulach/matrixultimate/blob/50cfbcd8b855476cd6ba88b676ddd6c27c86b14f/src/main/java/org/apidesign/demo/matrixultimate/svm/SVMScientificLibraryJNI.java#L83). Generalizing it would require construction of an object without calling a constructor (I am not sure how) and copying all the fields in there (certainly possible). Casting `JObject` representing function to `Function<?,?>` can also be hardcoded. General support for any interface might be more problematic, but probably possible.

It is just a question where to put such code? So far all the examples contain the necessary support classes. `graal-sdk` is not aware of the _native methods via Java_ concept at all. E.g. I can't even suggest you to create a pull request - there is no code to modify except the [Matrix the Ultimate](https://github.com/JaroslavTulach/matrixultimate) project.

**Comment by JaroslavTulach** [comment]
I've just [made the copy work](https://github.com/JaroslavTulach/matrixultimate/compare/master...GenericObjectCopy) in a more generic way. The next step is to create a library with some annotations and their processors to make it all truly general.

**Comment by JaroslavTulach** [comment]
@dsyer, are you still interested in this or can we close the issue at current state?

**Comment by dsyer** [comment]
I'm still interested. We could leave this issue open as a place to discuss if you like. Your call.

**Comment by JaroslavTulach** [comment]
There is the [manual copy](https://github.com/JaroslavTulach/matrixultimate/compare/master...GenericObjectCopy) example. If it is automated with an annotation processor, will that be enough?

**Comment by dsyer** [comment]
Are there some instructions on how to make it wiggle? I see a README but it only appears to apply to master. How do I see the copy working?
