### ISSUE TITLE
Visual Studio not found when running native-image without privileges

### ISSUE THREAD

**Issue by surculus12** [oracle/graal#7528]
**Describe the issue**
When running native-image without administrative privileges on Windows (from powershell), the following error occurs:

```
PS C:\Users\...> native-image asdf
Error: Failed to automatically set up Windows build environment.
Please make sure that Visual Studio 2022 version 17.1.0 or later is installed on your system. You can download it at https://visualstudio.microsoft.com/downloads/. If this error persists, please try and run GraalVM Native Image in an x64 Native Tools Command Prompt or file a ticket.
```

When run from a privileged powershell instance, native-image runs without problems. The above error seems to occur when the Visual Studio installation cannot be found (https://github.com/oracle/graal/blob/2a18f7bfca31d9c6663ab52bca6069daf2bf583b/substratevm/src/com.oracle.svm.driver/src/com/oracle/svm/driver/WindowsBuildEnvironmentUtil.java#L126). However, I cannot see a reason as to why the non-privileged instance of native-image would be unable to locate the installation.

**Steps to reproduce the issue**
Please include both build steps as well as run steps
1. Install gradlevm
2. Install Visual Studio 2022 with WIndows SDK
3. Run native-image

**Describe GraalVM and your environment:**
 - GraalVM Runtime Environment Oracle GraalVM 21+35.1 (build 21+35-jvmci-23.1-b15)
 - native-image 21 2023-09-19
 - OS: Microsoft Windows 10 Enterprise
 - Architecture: x64

**More details**

```
> native-image asdf --verbose
Apply jar:file:///C:/projects/tooling/graalvm-jdk-21+35.1/lib/svm/library-support.jar!/META-INF/native-image/com.oracle.svm/thirdparty/native-image.properties
Apply jar:file:///C:/projects/tooling/graalvm-jdk-21+35.1/lib/svm/library-support.jar!/META-INF/native-image/com.oracle.svm/polyglot/native-image.properties
Error: Failed to automatically set up Windows build environment.
Please make sure that Visual Studio 2022 version 17.1.0 or later is installed on your system. You can download it at https://visualstudio.microsoft.com/downloads/. If this error persists, please try and run GraalVM Native Image in an x64 Native Tools Command Prompt or file a ticket.
com.oracle.svm.driver.NativeImage$NativeImageError: Failed to automatically set up Windows build environment.
Please make sure that Visual Studio 2022 version 17.1.0 or later is installed on your system. You can download it at https://visualstudio.microsoft.com/downloads/. If this error persists, please try and run GraalVM Native Image in an x64 Native Tools Command Prompt or file a ticket.
        at org.graalvm.nativeimage.driver/com.oracle.svm.driver.NativeImage.showError(NativeImage.java:2332)
        at org.graalvm.nativeimage.driver/com.oracle.svm.driver.WindowsBuildEnvironmentUtil.fail(WindowsBuildEnvironmentUtil.java:150)
        at org.graalvm.nativeimage.driver/com.oracle.svm.driver.WindowsBuildEnvironmentUtil.fail(WindowsBuildEnvironmentUtil.java:146)
        at org.graalvm.nativeimage.driver/com.oracle.svm.driver.WindowsBuildEnvironmentUtil.propagateEnv(WindowsBuildEnvironmentUtil.java:126)
        at org.graalvm.nativeimage.driver/com.oracle.svm.driver.NativeImage.buildImage(NativeImage.java:1674)
        at org.graalvm.nativeimage.driver/com.oracle.svm.driver.NativeImage.completeImageBuild(NativeImage.java:1290)
        at org.graalvm.nativeimage.driver/com.oracle.svm.driver.NativeImage.build(NativeImage.java:1913)
        at org.graalvm.nativeimage.driver/com.oracle.svm.driver.NativeImage.performBuild(NativeImage.java:1878)
        at org.graalvm.nativeimage.driver/com.oracle.svm.driver.NativeImage.main(NativeImage.java:1852)
        at java.base@21/java.lang.invoke.LambdaForm$DMH/sa346b79c.invokeStaticInit(LambdaForm$DMH)
```

**Comment by A-Pupils-form-china** [comment]
Hello. I meet the same problem, maybe worser.  Even with administrative privileges but no in 'system32' path, it doesn't found the vs build tool too.  
![image](https://github.com/oracle/graal/assets/36190484/ffc90d08-b493-4013-9610-d639a47df7e4)
I wonder how you fix that. Thank you.  🙏🙏🙏

**Comment by bawantha** [comment]
How this is completed @surculus12

**Comment by bawantha** [comment]
@chuzhongzai  Did you find a solution for this

**Comment by chuzhongzai** [comment]
> @chuzhongzai Did you find a solution for this

@bawantha update lastest version of vs 2022 community and graalvm. You better install vs 2022 on default path.

**Comment by donniexyz** [comment]
> ... You better install vs 2022 on default path.

This is true. I installed it into `D:\Program Files\Microsoft Visual Studio\2022\Community`, then `native-image` could not find it. Then I created a junction in `C:\Program Files\` with admin access
```
C:\Program Files>junction "Microsoft Visual Studio" "D:\Program Files\Microsoft Visual Studio"

Junction v1.07 - Creates and lists directory links
Copyright (C) 2005-2016 Mark Russinovich
Sysinternals - www.sysinternals.com

Created: C:\Program Files\Microsoft Visual Studio
Targetted at: D:\Program Files\Microsoft Visual Studio

C:\Program Files>
```

After that `native-image` works as normal.
