### ISSUE TITLE
Is it possible to build exactly the same native-image binary from the same source files?

### ISSUE THREAD

**Issue by wkgcass** [oracle/graal#7542]
**Describe the issue**

Is it possible to generate exactly the same binary for each native-image build?  
To be more specific, when I take the following steps:

1. a maven or gradle project
2. clean the project
3. build the project into a single fat jar
4. build native-image with `-jar fat.jar --no-fallback -o result1`
5. clean and build the project into `result2` using the same steps
6. compare `result1` and `result2`

Is it possible to force `result1` and `result2` to be exactly the same?

**Describe GraalVM and your environment:**

The `result1` and `result2` differs when using `macos/x86_64/graalvm-jdk-21+35.1`

---

I believe this is useful when shipping source files along with the binary (or hash).  
The product receivers can compile the source files and compare against the binary file (or hash) to make confirmation.

**Comment by medoussboug** [comment]
Hello, for the time being it is not possible to have deterministic images, we are looking to make them more deterministic but making them 100% deterministic is probably never possible. 

You can check this issue where they discuss why it may never be possible [Reproducible builds for GraalVM Native Image #291]( https://github.com/oracle/graal/issues/291).
