### ISSUE TITLE
:scroll: Please provide a clear Lifecycle Management documentation to manage LTS :calendar: 

### ISSUE THREAD

**Issue by adriens** [oracle/graal#7547]
## :grey_question: ABout

We currently are mainatining GraalVM eols : 

https://endoflife.date/graalvm

... but we are lacking LTS concerns (i it applies):

![image](https://github.com/oracle/graal/assets/5235127/5f93af3b-d6ab-4ffd-bd07-2cd3122bb925)

The aim of this issue is to help complete : 

- https://github.com/endoflife-date/endoflife.date/issues/3665

#" :dart: Action

Helping by providing us some relevant infos related to `LTS` strategy, especially on Java 21, 17,...

**Comment by fniephaus** [comment]
You can find details on LTS releases of Oracle GraalVM on the corresponding download website:

> GraalVM for JDK 21 will receive updates under the GFTC, until September 2026, ... .

https://www.oracle.com/java/technologies/downloads/#graalvmjava21

> GraalVM for JDK 17 will receive updates under the GFTC, until September 2024.

https://www.oracle.com/java/technologies/downloads/#graalvmjava17


Hope this helps! :)

**Comment by zakkak** [comment]
@fniephaus it looks like @adriens is interested in GraalVM CE lifecycle.

@adriens https://www.graalvm.org/release-calendar/ should have the info you need. 
1. GraalVM for JDK 21 seems to EOL on April 23, 2024 (next CPU release date after the last CPU release of that version) 
2. GraalVM for JDK 17 seems to EOL on January 23, 2024 (next CPU release date after the last CPU release of that version)
