### ISSUE TITLE
[GR-49221] Fold thread dump experimental option into enable-monitoring

### ISSUE THREAD

**Issue by galderz** [oracle/graal#7548]
The option to generate a thread dump is currently experimental, e.g. `-H:+DumpThreadStacksOnSignal`. Instead it should be folded into the `enable-monitoring` option.

**Comment by fniephaus** [comment]
Do you mean a `threaddump` argument for `--enable-monitoring`, similar to the `heapdump` argument?

**Comment by fniephaus** [comment]
Done via #7612.

**Comment by galderz** [comment]
Thanks @fniephaus!
