### ISSUE TITLE
Unexpected blocklisted method after upgrade truffle-api from 22.3.0 to 23.0.0

### ISSUE THREAD

**Issue by tisonkun** [oracle/graal#7559]
Repro - https://github.com/korandoru/trufflebf/actions/runs/6421560847/job/17436197944

Failure for upgrades. Unable to understand what to do and how to fix it ..

```
Blocklisted method
   java.lang.StringBuffer.charAt(int) (target: java.lang.CharSequence.charAt(int))
```

**Comment by fernando-valdez** [comment]
Hello @tisonkun, the logs of that link have expired.
Can you please share more details about the error, the version of GraalVM, and even a reproducer so we can take a closer look at the problem?

**Comment by tisonkun** [comment]
This is fixed by adding some TruffleBoundary IIRC.

But I meet some other issue upgrade to 23.1.0 due to missing symbols. Let me open a new issue.
