### ISSUE TITLE
Make library-support jar available via Maven

### ISSUE THREAD

**Issue by dsyer** [oracle/graal#756]
Implementing the sample in https://github.com/oracle/graal/blob/master/substratevm/ImplementingNativeMethodsInJavaWithSVM.md requires classes that I couldn't find anywhere in Maven Central. E.g. `JNIHeaderDirectives` is in library-support.jar in the GraalVM distro.

**Comment by olpaw** [comment]
What about https://search.maven.org/artifact/com.oracle.substratevm/library-support/1.0.0-rc8/jar ?

**Comment by dsyer** [comment]
That's the one, thanks! It has a load of transitive dependencies though. Do I really need all of those (my sample worked before without them)? Maybe they should be optional? Is there any documentation for these locations?

**Comment by olpaw** [comment]
Maybe we should expose the `JNIHeaderDirectives` in our [API](https://www.graalvm.org/sdk/javadoc/org/graalvm/nativeimage/package-summary.html) (then also the transitive dependencies issue disappears). CC @peter-hofer @christianwimmer

**Comment by peter-hofer** [comment]
The classes from this document are examples that are intended to be copied to a local project. Our internal JNI classes are specific to our _implementation_ of JNI and not intended to be used to access JNI. In case of `JNIHeaderDirectives`, the class from the document only shares its name with one of our implementation classes, but their code differs. After copying the classes from the document to your own code base, do you still have any missing dependencies?

**Comment by dsyer** [comment]
I somehow missed that, and it works if I copy the sample code completely. Maybe the code from that guide could be linked to on github or something? An example with a call to a Java object method would be nice as well (I have one now, but it took me 3 days to work out how to do it).

**Comment by dsyer** [comment]
The `JNIHeaderDirectives` from the jar file is actually simpler. Why does it work? If it works as well as the one in the sample app, why not use it?
