### ISSUE TITLE
Native agent's trace output ignores any access/caller filter configuration

### ISSUE THREAD

**Issue by galderz** [oracle/graal#7635]
Native agent's `trace-output` mode ignores any `access-filter-file` and `caller-filter-file` configuration that is passed in. Analysing the trace output gets confusing once you add those in because it seems like the filters are not being applied but actually it's an issue with the `trace-output` itself that it doesn't process those filters.

I think it would help fine tuning the filters if `trace-output` would take the `access-filter-file` and `caller-filter-file` configuration into account.

Will the `trace-output` mode continue, or will it be replaced eventually by `experimental-configuration-with-origins`?

**Comment by hamzaGhaissi** [comment]
Thanks for the feature at least they need to cause a warning.
I don't think that experimental-configuration-with-origins is being worked on at this time.

**Comment by hamzaGhaissi** [comment]
We have discussed this internally, but for now it's not planned for the near future
