### ISSUE TITLE
Clarify Class is already initialized... and allow annotations to make native-image more reliable

### ISSUE THREAD

**Issue by miho** [oracle/graal#766]
I just tried to delay class initialization since graal told me that Threads are no longer supported during image generation. This makes total sense. But unfortunately, delaying the initialization of the problematic class introduces another problem: it is already initialized from somewhere:

    Class is already initialized, so it is too late to register delaying class initialization: 
    sun.java2d.opengl.OGLRenderQueue

In one of your blog post you suggest using a debugger to find the problematic code. As you said yourself in the article, a debugger isn't a user-friendly solution. 

**Here are some suggestions to simplify things:**

- test popular libraries (and more importantly the core APIs) whether `native-image` image works and which set of `--delay-class-initialization...` magic is necessary. Publish the `--delay-class-initialization` arguments for popular & core libraries, e.g., JavaFX, Swing/AWT etc.

- introduce annotations that allow library developers declare delayed initialization to provide an out-of-the-box experience for graal and native-image

- introduce a `--auto-delay-class-initialization` CLI argument that figures out the trace and uses it to delay the initialization of all problematic roots. Also print all problematic classes to the command line or a specified output file

**Comment by christianwimmer** [comment]
Your second suggestion point is already implemented: Library developers can include a `native-image.properties` file in their library (in the `META-INF/native-image` directory or a subdirectory of it) and in that file list the classes that need initialization at run time.

**Comment by miho** [comment]
Good to know. Thanks. What are your thoughts on one and three?

**Comment by vjovanov** [comment]
Testing popular libraries is planned. The following doc describes the process:

https://docs.google.com/document/d/1J7c2HcTCvYn2d17PV8LbsIfD7wlSGrFVJTaZNphC-Rg/edit?usp=sharing

`--auto-delay-class-initialization` is very hard to implement. We have the `--trace-class-initialization` and `--trace-object-instantiation` flags that should allow you to find issues easily.

**Comment by vjovanov** [comment]
This issue is partially fixed and addressed by other issues on the programming model (e.g., https://github.com/graalvm/taming-build-time-initialization/blob/main/PROPOSAL_CLASS_INITIALIZATION.md).
