### ISSUE TITLE
[GR-49773] Add/verify heuristics for Java source lookup for native-image debuginfo-generation

### ISSUE THREAD

**Issue by olpaw** [oracle/graal#7691]
Building native-images with debuginfo from jar-files that are coming from maven should work OOTB. I.e. there should be heuristics that ensure that for a given jar on the class- or module-path the corresponding source zip file should be available for native-debuginfo generation.

com.oracle.svm.hosted.image.sources.SourceCache.SourceRoots#addApplicationSourceRoot already is written in a way that should allow for that. This needs to be tested with maven and gradle based native-image builds and if something is missing in the heuristics it needs to be added/improved.

**Comment by fniephaus** [comment]
FYI @adinn

**Comment by zakkak** [comment]
> I.e. there should be heuristics that ensure that for a given jar on the class- or module-path the corresponding source zip file should be available for native-debuginfo generation.

@olpaw are you suggesting that GraalVM should trigger `mvn dependency:sources` (or the equivalent) or just saying that if the sources are there GraalVM should pick them up?

In the latter case, it looks like things work as expected for `maven`. In the Quarkus docs we mention:

> Sources for third party jar dependencies, including Quarkus source code, are not added to the source cache by default. To include those, make sure you invoke mvn dependency:sources first. This step is required in order to pull the sources for these dependencies, and get them included in the source cache.

**Comment by olpaw** [comment]
@zakkak indeed it seem what I was asking for is already implemented. Thanks for confirmation.
