### ISSUE TITLE
Native-image cannot compile java inside Docker ( com.oracle.svm.core.util.VMError$HostedError)

### ISSUE THREAD

**Issue by rost5000** [oracle/graal#7692]
## System requirements
* Windows 10 (22H2)
* Docker 4.20.1
* GraalVm  21 (Oracle Corporation 21+35-jvmci-23.1-b15)
## Step to reproduce
1. Clone the example [project](https://github.com/rost5000/graalvm-docker-build-bug)
2. Run `docker build -t ex/ex .`
3. You receive the exception:
```text
com.oracle.svm.core.util.VMError$HostedError: Unable to run '/home/app/ms/modules/infrastructure/build/tmp/SVM-1698673226114/AArch64LibCHelperDirectives' to compute offsets in C data structures. Is it possible that your antivirus software interferes and puts the resulting file into quarantine?
```
4. Using Docker UI, I cannot see any additional files in `/tmp` directory: 
![image](https://github.com/oracle/graal/assets/24576320/98c7f15e-fa8c-4d78-8ffc-e89bd95d4b19)

## Expected behavior:
Successfully build the image and run `docker run -it --rm ex/ex` and see `Hello World!`
## Additional info:
1. bug report: [svm_err_b_20231030T135947.745_pid49.md](https://github.com/oracle/graal/files/13206086/svm_err_b_20231030T135947.745_pid49.md)
2. I thought that it was a docker issue, however, it seems to me that the problem is in the `native-build` utility. I run Local build: 
   `./gradlew clean build` -- build project
   `native-image -cp ./build/libs/graalvm-1.0-SNAPSHOT.jar -H:Class=org.example.Main -H:Name=application --no-fallback` -- native build
3. I use multi-stage docker build and my dockerfile looks like:
```dockerfile
FROM ghcr.io/graalvm/native-image-community:21-muslib AS graalvm

WORKDIR /home/app/ms
COPY . .
RUN microdnf install findutils

RUN groupadd --force -g 1000 app && \
    useradd -g app -G app app
RUN chmod -R 777 /home/app
RUN chmod 777 ./gradlew
USER app

RUN ./gradlew clean build

RUN native-image -cp /home/app/ms/build/libs/graalvm-1.0-SNAPSHOT.jar \
    -H:Class=org.example.Main \
    -H:Name=application \
    --no-fallback

FROM frolvlad/alpine-glibc:alpine-3.12
RUN apk --no-cache update && apk add libstdc++
EXPOSE 8080
COPY --from=graalvm /home/app/ms/application /app/application
ENTRYPOINT ["/app/application"]
```

**Comment by ossama-ismaili** [comment]
Hello @rost5000 we are trying to reproduce the issue.

**Comment by ossama-ismaili** [comment]
The issue is not reproducible when building the project in a Linux container. If you encounter this problem while attempting to build the native image on Windows, please make sure to use a directory that is whitelisted by your antivirus software and be sure to include the `-H:TempDirectory=<path-to-whitelisted-directory>` flag.

**Comment by rost5000** [comment]
@ossama-ismaili , thank you for your reply 
The problem was that inside docker. Did you succeed the following command:
```bash
git clone https://github.com/rost5000/graalvm-docker-build-bug.git && cd ./graalvm-docker-build-bug && docker build .
```
Could you, please attach the output. Because I had some problem in my virtual machine in Ubuntu and received the same error as in Windows machine

**Comment by rost5000** [comment]
@jlc488 , yes, I used a wrong tag for docker image build. After using the correct tag of GraalVM image, the problem was solved.

**Comment by jlc488** [comment]
@rost5000 Would you be kind to share me the snippet? appreciated
