### ISSUE TITLE
many spring context could not run

### ISSUE THREAD

**Issue by IEggFriedRice** [oracle/graal#7699]
I have two spring contexts, but I get the error Web application could not be started as there was no org.springframework.boot.web.servlet.server.ServletWebServerFactory bean defined in the context.

graalvm version graalvm-jdk-17.0.9

this is my startup class
`
fun main(args: Array<String>) {
    SpringApplicationBuilder(MainContextConfiguration::class.java)
        .child(ApiContextConfiguration::class.java)
        .web(WebApplicationType.SERVLET)
        .sibling(WebContextConfiguration::class.java)
        .web(WebApplicationType.SERVLET)
        .run(*args)
}
`
dependencies 
`
plugins {
    id("common-conventions")
    id("spring-conventions")
    id("org.graalvm.buildtools.native")
}

dependencies {
    implementation(project(":central:api:apiV1"))
    implementation(project(":central:api:web"))
    implementation(Deps.springBootStarter)
}

`

**Comment by ossama-ismaili** [comment]
Hello @IEggFriedRice, please share more details about your environment (OS and Arch) and the full error stack trace.

**Comment by IEggFriedRice** [comment]
> My environment is Windows 11 with x86 architecture. 

> this is my error message

`***************************
APPLICATION FAILED TO START
***************************

Description:

Web application could not be started as there was no org.springframework.boot.web.servlet.server.ServletWebServerFactory bean defined in the context.

Action:

Check your application's dependencies for a supported servlet web server.
Check the configured web application type.

33 actionable tasks: 2 executed, 31 up-to-date`

> I received a lot of messages during the build process.
`Field org.springframework.aot.AotDetector#inNativeImage set to true at build time
Field org.springframework.web.context.support.StandardServletEnvironment#jndiPresent set to true at build time
Field org.springframework.format.support.DefaultFormattingConversionService#jsr354Present set to false at build time
Field org.springframework.web.context.support.WebApplicationContextUtils#jsfPresent set to false at build time
Field org.springframework.web.context.request.RequestContextHolder#jsfPresent set to false at build time
Field org.springframework.http.converter.support.AllEncompassingFormHttpMessageConverter#jaxb2Present set to false at build time`

**Comment by ossama-ismaili** [comment]
The problem appears to be the result of a misconfiguration in your project, rather than an issue with GraalVM itself. To resolve this, I recommend utilizing [Spring Initializr](https://start.spring.io/) to set up your project correctly.
