### ISSUE TITLE
[GR-51461] Graal jlink images significantly larger than OpenJDK images

### ISSUE THREAD

**Issue by UtilFunction** [oracle/graal#7702]
**Describe the issue**
jlink images generated with GraalVM are a lot bigger than jlink immages generated with OpenJDK.

**Steps to reproduce the issue**
Run `jlink --add-modules java.base --output openjdk --no-header-files --no-man-pages --strip-debug` with both GraalVM and OpenJDK. In my case, the Graal generated image sizes **102MB** and the OpenJDK one **49.6MB**

**Describe GraalVM and your environment:**
 - **OpenJDK Runtime Environment (build 21+35-2513)**
 - **Oracle GraalVM 21+35.1 (build 21+35-jvmci-23.1-b15)**
 - OS: **Ubuntu 22.04.2 LTS**
 - Architecture: **AMD64**

**Comment by ossama-ismaili** [comment]
Hello @UtilFunction, thanks for reporting the issue. We are working to reproduce the issue.

**Comment by dougxc** [comment]
Hi @UtilFunction , the size difference is explained by the addition of libgraal (i.e., `lib/libjvmcicompiler.so`) in the GraalVM jlinked image. As we improve the size of Native Images, the footprint of libgraal will decrease.
