### ISSUE TITLE
Official docker image can't compile static native images

### ISSUE THREAD

**Issue by pmlopes** [oracle/graal#771]
When using: https://hub.docker.com/r/oracle/graalvm-ce/

Compile a hello world example with:

`native-image --static Hello`

Will fail with missing static libs `z`, `c`, etc...

Looks the image only contains the dynamic link libs not the static ones installed.

**Comment by mzachh** [comment]
Hi Paulo,

thanks a lot for your report.

You can install the static packages with the following procedure:
```
yum-config-manager --enable ol7_optional_latest
yum install glibc-static zlib-static
```
Does this work for you?

We need to do some more testing and try to include it in a future image version.

**Comment by mzachh** [comment]
The new oracle/graalvm-ce:1.0.0-rc9 docker image does now include the glibc-static and zlib-static package.
