### ISSUE TITLE
cl.exe

### ISSUE THREAD

**Issue by tinspin** [oracle/graal#7715]
**Feature request**

Please include the following information:

**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I have to install VS and it bloats my C: drive until my Windows computer becomes unusable because it has run out of diskspace.

**Describe the solution you'd like.**
I have extracted cl.exe and it's only 35MB zipped. I extract that into the folders of my native projects instead.
So the --native-compiler-options and --native-compiler-path options should be implemented.
Right now they return Error: Unrecognized option(s): '--native-compiler-options', '--native-compiler-path'

**Describe who do you think will benefit the most.**
Humanity?

**Describe alternatives you've considered.**
There is none.

**Additional context.**
Nope

**Express whether you'd like to help contributing this feature**
Nope

**Comment by Lilianne-Blaze** [comment]
Not exactly Graal-specific, but maybe try moving VS to another disk and creating a symbolic link where it was pointing to the new location. Search for "link shell extension", it's a free program with a guide on how to do that. Symbolic links are completely transparent to most software.

**Comment by kassifar** [comment]
Hello @tinspin,
Thank you for your suggestion, unfortunately, this is not currently on our roadmap. You can check the solution provided by @Lilianne-Blaze above, it should provide some insight for you.
