### ISSUE TITLE
Native Image possible on Parallels Desktop using M1 Mac?

### ISSUE THREAD

**Issue by lukgeasyer** [oracle/graal#7730]
Hey! I am currently trying to create a native executable from my .jar file. I have successfully done so on Mac OS now I want to create a `.exe` for Windows using my M1 Mac and running Parallels Desktop 19 with Windows 11. I have found zero information about whether this is even possible. I did go over the [manual](https://www.graalvm.org/22.3/docs/getting-started/windows/) and even the [extended manual](https://medium.com/graalvm/using-graalvm-and-native-image-on-windows-10-9954dc071311). However, when trying to run `native-image` I always get the error message that the Windows build environment could not be set up correctly. 

**Steps to reproduce the issue**
1. Follow [installation manual for windows](https://www.graalvm.org/22.3/docs/getting-started/windows/)
2. Open up `x64 Native Tools Command Prompt for VS 2022` (as admin) (or `ARM64 Native Tools Command Prompt for VS 2022` or `ARM64_x64 Cross Tools Command Prompt for VS 2022` respectively)
3. Error message occurs when running `native-image`

**Describe GraalVM and your environment:**
 - JDK/GraalVM major version: Java(TM) SE Runtime Environment Oracle GraalVM 21.0.1+12.1 (build 21.0.1+12-jvmci-23.1-b19)
 - OS: Windows 11 (Parallels Desktop 19 under macOS 14.1 (23B74))
 - Architecture: Apple M1
 - Windows Visual Studio: Community 2022 - 17.7.6 
       - installed packages: 
                 - MSVC v143 - VS 2022 C++ x64/x86-Buildtools (newest)
                 - MSVC v143 - VS 2022 C++ ARM64/ARM64EC-Buildtools (newest version)
                 - [...]
                 - Windows 11-SDK (10.0.22621.0)
                 - Windows 11-SDK (10.0.22000.0) 

Error message: 

```
C:\Users>native-image -g --verbose myProgram.jar
Apply jar:file:///C:/Program%20Files/Java/graalvm-jdk-21.0.1+12.1/lib/svm/library-support.jar!/META-INF/native-image/com.oracle.svm/thirdparty/native-image.properties
Apply jar:file:///C:/Program%20Files/Java/graalvm-jdk-21.0.1+12.1/lib/svm/library-support.jar!/META-INF/native-image/com.oracle.svm/polyglot/native-image.properties
Error: Failed to automatically set up Windows build environment.
Please make sure that Visual Studio 2022 version 17.1.0 or later is installed on your system. You can download it at https://visualstudio.microsoft.com/downloads/. If this error persists, please try and run GraalVM Native Image in an x64 Native Tools Command Prompt or file a ticket.
com.oracle.svm.driver.NativeImage$NativeImageError: Failed to automatically set up Windows build environment.
Please make sure that Visual Studio 2022 version 17.1.0 or later is installed on your system. You can download it at https://visualstudio.microsoft.com/downloads/. If this error persists, please try and run GraalVM Native Image in an x64 Native Tools Command Prompt or file a ticket.
        at org.graalvm.nativeimage.driver/com.oracle.svm.driver.NativeImage.showError(NativeImage.java:2332)
        at org.graalvm.nativeimage.driver/com.oracle.svm.driver.WindowsBuildEnvironmentUtil.fail(WindowsBuildEnvironmentUtil.java:150)
        at org.graalvm.nativeimage.driver/com.oracle.svm.driver.WindowsBuildEnvironmentUtil.fail(WindowsBuildEnvironmentUtil.java:146)
        at org.graalvm.nativeimage.driver/com.oracle.svm.driver.WindowsBuildEnvironmentUtil.propagateEnv(WindowsBuildEnvironmentUtil.java:126)
        at org.graalvm.nativeimage.driver/com.oracle.svm.driver.NativeImage.buildImage(NativeImage.java:1674)
        at org.graalvm.nativeimage.driver/com.oracle.svm.driver.NativeImage.completeImageBuild(NativeImage.java:1290)
        at org.graalvm.nativeimage.driver/com.oracle.svm.driver.NativeImage.build(NativeImage.java:1913)
        at org.graalvm.nativeimage.driver/com.oracle.svm.driver.NativeImage.performBuild(NativeImage.java:1878)
        at org.graalvm.nativeimage.driver/com.oracle.svm.driver.NativeImage.main(NativeImage.java:1852)
        at java.base@21.0.1/java.lang.invoke.LambdaForm$DMH/sa346b79c.invokeStaticInit(LambdaForm$DMH)
```

I don't know if what I'm doing is even supposed to work and whether opening up the `x64 Native Tools Command Prompt for VS 2022` even makes sense on a M1 Mac. Sorry!

**Comment by chirontt** [comment]
When you mention your Windows OS as:
```
- OS: Windows 11 (Parallels Desktop 19 under macOS 14.1 (23B74))
```
in your M1 Mac, I assume it's Windows 11 on Arm64 (not the "normal" Windows for x64/Intel/AMD), right? In that case, you need GraalVM for Windows on Arm64, but it's not available.

Because Windows on Arm64 has a transparent x64 translation layer for successful running of x64 programs on it, somebody mentioned (can't recall where) that it's possible to use the `x64 Native Tools Command Prompt for VS 2022` in Windows on Arm64, as well as the GraalVM for x64 Windows, to build native image (for Windows x64), i.e. using all x64 tools to create Windows x64 programs in the Windows on Arm64 environment. But your experience above seems to indicate otherwise...

Note that you can't mix the arm64 tool like `ARM64 Native Tools Command Prompt for VS 2022` with the x64 tool like GraalVM for Windows (x64); you have to use all x64 stuff, or all arm64 stuff, exclusively.

**Comment by lukgeasyer** [comment]
Hey! Sorry for taking so long to respond. I actually made a little bit of progres here. So I had to use VS for another task and installed some additional packages. After resolving the other issue I tried to build the native image again and I did not get an error message this time. However, the build process seems to get stuck at some point. 

So I used 

```mvn --debug native:compile```

after having done all the steps in [this tutorial](https://www.graalvm.org/latest/docs/getting-started/windows/) and then the build process just freezes in this stage:

```
[INFO] Executing: C:\Program Files\Java\graalvm-jdk-21.0.1+12.1\bin\native-image.cmd @target\tmp\native-image-13503875567456046022.args
Warning: The option '-H:Path=C:\\Users\\myName\\IdeaProjects\\myProject\\backend\\target' is experimental and must be enabled via '-H:+UnlockExperimentalVMOptions' in the future.
Warning: The option '-H:Name=myProject.backend' is experimental and must be enabled via '-H:+UnlockExperimentalVMOptions' in the future.
Warning: The option '-H:ReflectionConfigurationResources=META-INF/native-image/org.apache.tomcat.embed/tomcat-embed-websocket/tomcat-reflection.json' is experimental and must be enabled via '-H:+UnlockExperimentalVMOptions' in the future.
Warning: The option '-H:ReflectionConfigurationResources=META-INF/native-image/org.apache.tomcat.embed/tomcat-embed-el/tomcat-reflection.json' is experimental and must be enabled via '-H:+UnlockExperimentalVMOptions' in the future.
Warning: The option '-H:ResourceConfigurationResources=META-INF/native-image/org.apache.tomcat.embed/tomcat-embed-core/tomcat-resource.json' is experimental and must be enabled via '-H:+UnlockExperimentalVMOptions' in the future.
Warning: The option '-H:ReflectionConfigurationResources=META-INF/native-image/org.apache.tomcat.embed/tomcat-embed-core/tomcat-reflection.json' is experimental and must be enabled via '-H:+UnlockExperimentalVMOptions' in the future.
Warning: The option '-H:ResourceConfigurationResources=META-INF/native-image/org.apache.tomcat.embed/tomcat-embed-el/tomcat-resource.json' is experimental and must be enabled via '-H:+UnlockExperimentalVMOptions' in the future.
Warning: The option '-H:ResourceConfigurationResources=META-INF/native-image/org.apache.tomcat.embed/tomcat-embed-websocket/tomcat-resource.json' is experimental and must be enabled via '-H:+UnlockExperimentalVMOptions' in the future.
Warning: Please re-evaluate whether any experimental option is required, and either remove or unlock it. The build output lists all active experimental options, including where they come from and possible alternatives. If you think an experimental option should be considered as stable, please file an issue.
Loading classes is taking a long time. This can be caused by class- or module-path entries that point to large directory structures.
Total processed entries: 13404, current entry: file:///C:/Program%20Files/Java/graalvm-jdk-21.0.1+12.1/lib/svm/builder/svm-enterprise.jar/com/oracle/svm/enterprise/virtualization/vmm/qemu/c.class
```

This is while running in the `x64 Native Tools Command Prompt for WS 2022` (as an admin, to be sure). I noticed that it doesn't make a difference when running in the `ARM64 Native Tools Command Prompt for WS 2022`.

Would be really nice to get it working cause the perfomance of the native binary on macOS is great! 

Remark: This freezing also occurs when simply running `native-compile --verbose -jar myProgram.jar`

**Comment by elkorchi** [comment]
Hello, 

GraalVM doesn't support Windows Aarch64, can you please use Windows X64 using Rosetta to run x86-64
