### ISSUE TITLE
[Sulong] longjmp/setjmp Not Supported

### ISSUE THREAD

**Issue by mrigger** [oracle/graal#776]
Sulong does not support `setjmp` and `longjmp`. There has been some discussion on this in the old repository at https://github.com/graalvm/sulong/issues/51 and a prototype implementation at https://github.com/graalvm/sulong/pull/829.

**Comment by atrosinenko** [comment]
Is it still expected to be implemented?

It looks like the [Emscripten developers' experience](http://kripken.github.io/emscripten-site/docs/porting/guidelines/portability_guidelines.html) on `longjmp` may be relevant. As far as I understand, JavaScript has similar restrictions on stack manipulation, so they decided to restrict themselves to UB-free C programs, for which it is quite simple to implement `longjmp`s with exceptions.

**Comment by spavlusieva** [comment]
hi @mrigger, this issue has been inactive for more than 180 days. We’ll close it to focus on current issues. In case it’s still relevant, please reopen it and we’ll take another look. Thank you!
