### ISSUE TITLE
[Truffle NFI] Support for 80-bit floats

### ISSUE THREAD

**Issue by mrigger** [oracle/graal#777]
The Truffle NFI currently does not support 80-bit floats, which are needed by Sulong when it is used on an x86-64 architecture, where `long double`s are represented as 80-bit floats. See https://github.com/graalvm/sulong/issues/803.

**Comment by rschatz** [comment]
This was fixed in https://github.com/oracle/graal/commit/b11b23d8c7bf139fa5a56b53a9fee70e568afe41 (in 22.3.0 and later). Sorry for forgetting about this ticket.
