### ISSUE TITLE
[native-image] System Properties

### ISSUE THREAD

**Issue by ris58h** [oracle/graal#779]
There are a couple of questions about system properties that aren't covered in docs.

Let's start with simple program which prints system properties:
```java
public class SystemProperties {
  public static void main(String[] args) {
    System.getProperties().forEach((key, value) -> System.out.println(key + ": " + value));
  }
}
```

1. According to [docs](https://www.graalvm.org/docs/reference-manual/aot-compilation/)
> -D<name>=<value> sets a system property;

So it's possible to pass a system property at compile time. Is the property available only at compile time or it's available at run time too? After an experiment 
```
native-image -Dfoo=bar SystemProperties
./systemproperties
```
it seems like the answer is "compile time only".

2. There is nothing in docs about passing system properties at start time. But it seems like we could pass them as parameters. So `./systemproperties -Dfoo=bar` will print `foo: bar`. Shouldn't it be mentioned in the docs?

3. Doesn't passing system properties as parameters with `-D` prefix break a program semantic for users who migrate from JVM to SVM? Consider a program
```java
public class Args {
  public static void main(String[] args) {
    for (String a: args) { System.out.println(a); }
  }
}
```
Running it on JVM as `java Args -Dfoo=bar` prints `-Dfoo=bar`. Running it on SVM as `./args -Dfoo-bar` prints nothing. It's a rare case but it's possible.

**Comment by ris58h** [comment]
> I.e. whenever you are in code that is part of your application but executed at image build-time (usually static field initializations & static initializers).
Thank you for clarification. It would be nice to have such explanation in the docs.

I still have the 3-rd question BTW.

**Comment by olpaw** [comment]
> Running it on JVM as java Args -Dfoo=bar prints -Dfoo=bar. Running it on SVM as ./args -Dfoo-bar prints nothing. It's a rare case but it's possible

Invoking `./args -Dfoo-bar` corresponds to `java -Dfoo=bar Args`. If you don't want native-image executables to perform `-D`-processing you can build you image with `-H:-ParseRuntimeOptions`. Then you will get your `String[] args` exactly as they are passed to the executable.

**Comment by olpaw** [comment]
> It would be nice to have such explanation in the docs

I will add that.

**Comment by drocsid** [comment]
Hello, I'm setting a system property -Dlogback.configurationFile="./logback.xml". When I run my application as a jar with this property argument it respects the logback configuration. But when I run my native image ./binary -Dlogback.configurationFile=./logback.xml it is not respecting the configuration. I think this is contradicting the discussion above. Can someone chime in?

**Comment by drocsid** [comment]
@olpaw ^^

**Comment by olpaw** [comment]
> But when I run my native image ./binary -Dlogback.configurationFile=./logback.xml it is not respecting the configuration. I think this is contradicting the discussion above.

I depends. Where in Java code is system property `logback.configurationFile` used. Is that code probably already executed at at image build-time and thus it's build-time value baked into the native-image? In this case providing a custom value at image-run-time would not have any effect (change what got already determined at image-build time).

**Comment by kdvolder** [comment]
I found the doc that I think were written in response to this ticket. 
https://www.graalvm.org/reference-manual/native-image/Properties/

The docs seem pretty clear, however, it looks like things do not actually work as is described. From what I can tell system properties passed to the image at runtime as `-Dfoo=bar` arguments do not get set. 

I tested this in my app as follows:

```
	public static void main(String[] args) throws MalformedObjectNameException, InstanceAlreadyExistsException, MBeanRegistrationException, NotCompliantMBeanException {
		System.out.println("args = "+Arrays.asList(args));
		System.out.println("foo = "+ System.getProperty("foo"));
                ...
```

And I run my app with:

```
myapp -Dfoo=bar
```

The ouptut is 

```
Warning: Image 'myapp' is a fallback image that requires a JDK for execution (use --no-fallback to suppress fallback image generation and to print more detailed information why a fallback image was necessary).
args = [-Dcom.sun.management.jmxremote]
foo = null
```

So the info here and in the doc is wrong? Or maybe the mistake is mine and I passed the argument in the wrong way? Seeing as the args has `-Dfoo=bar` it looks like is a program argument instead of something sets system properties. 

In normal JVM launches -D argument would be passed not as program arguments but as VM arguments, so it sort of makes sense arguments passed to the executable at runtime, which really are program arguments, do not set system props. However, the question then becomes... how do you actually pass system properties to your image at runtime? Is this even possible?

**Comment by kdvolder** [comment]
I deleted my comment. Explanation: please disregard for now. What I posted before was incorrect. I'm still trying to understand something and may post something again later.
