### ISSUE TITLE
Using Dockerfile to Build a Native Image Error

### ISSUE THREAD

**Issue by lamar666666** [oracle/graal#7793]
The error message is as follows: 

> Unresolveable build extension: Plugin org.graalvm.buildtools:native-maven-plugin:0.9.22 or one of its dependencies could not be resolved: The following artifacts could not be resolved: org.graalvm.sdk:graal-sdk:jar:22.0.0 (absent): Could not transfer artifact org.graalvm.sdk:graal-sdk:jar:22.0.0 from/to central (https://repo.maven.apache.org/maven2): Premature end of Content-Length delimited message body (expected: 623,771; received: 584,704) @

Version based:java17、springboot：3.1.0
This is my Dockerfile file：
```
ROM vegardit/graalvm-maven:latest-java17 as builder

WORKDIR /app

COPY pom.xml /app/
COPY src /app/src/

#Download time link timeout
COPY syft_0.84.0_linux_amd64.tar.gz /app
COPY junit-jupiter-params-5.8.1.jar /app
COPY objectfile-22.0.0.jar /app
COPY groovy-bom-4.0.12.pom.xml /app
COPY objectfile-22.0.0.jar /app

RUN mvn -Pnative native:compile -DskipTests

FROM mirekphd/jenkins-jdk17-on-ubuntu2204:latest

COPY --from=builder /app/target/milvus-native /app/

CMD ["/app/milvus-native"]
```
This is my pom file：
[pom.zip](https://github.com/oracle/graal/files/13316402/pom.zip)

Can someone help me solve the problem？

**Comment by ossama-ismaili** [comment]
Hello @lamar666666, the version 22.0.0 is no longer supported please use the latest version. Check this link for more details: [GraalVM latest containers](https://www.graalvm.org/latest/docs/getting-started/container-images/)

**Comment by lamar666666** [comment]
Okay, thank you for your valuable feedback. However, the new error that has occurred is also related to the version issue of other jars. Do we need to investigate whether all jar packages support the current version one by one?
ERROR:
```
[ERROR]   The project com.isoftstone.aic:milvus-native:1.0.0-SNAPSHOT (/app/pom.xml) has 1 error
[ERROR]     Unresolveable build extension: Plugin org.graalvm.buildtools:native-maven-plugin:0.9.23 or one of its dependencies could not be resolved: The following artifacts could not be resolved: org.junit.platform:junit-platform-reporting:jar:1.8.1 (absent): Could not transfer artifact org.junit.platform:junit-platform-reporting:jar:1.8.1 from/to central (https://repo.maven.apache.org/maven2): Connect to repo.maven.apache.org:443 [repo.maven.apache.org/151.101.108.215] failed: Connect timed out -> [Help 2]

```

**Comment by lamar666666** [comment]
Okay, thank you for your valuable feedback. However, the new error that has occurred is also related to the version issue of other jars. Do we need to investigate whether all jar packages support the current version one by one?
ERROR:
```
[ERROR]   The project com.isoftstone.aic:milvus-native:1.0.0-SNAPSHOT (/app/pom.xml) has 1 error
[ERROR]     Unresolveable build extension: Plugin org.graalvm.buildtools:native-maven-plugin:0.9.23 or one of its dependencies could not be resolved: The following artifacts could not be resolved: org.junit.platform:junit-platform-reporting:jar:1.8.1 (absent): Could not transfer artifact org.junit.platform:junit-platform-reporting:jar:1.8.1 from/to central (https://repo.maven.apache.org/maven2): Connect to repo.maven.apache.org:443 [repo.maven.apache.org/151.101.108.215] failed: Connect timed out -> [Help 2]

```
