### ISSUE TITLE
guice error

### ISSUE THREAD

**Issue by tjeske** [oracle/graal#782]
I have successfully built an image with "--report-unsupported-elements-at-runtime" and added some classes to the reflection config file but now I get the following error during runtime.  
```
Exception in thread "main" com.google.inject.ConfigurationException: Guice configuration errors:

1) Could not find a suitable constructor in mypackage.MyClass. Classes must have either one (and only one) constructor annotated with @Injector a zero-argument constructor that is not private.
  at mypackage.MyClass.class(Unknown Source)
  while locating mypackage.MyClass
```

**Comment by cstancu** [comment]
It looks like you are missing a constructor from your reflection configuration file.

**Comment by tjeske** [comment]
good advice... "allDeclaredConstructors: true" fixes this issue...
