### ISSUE TITLE
[Sulong] Absolute instead of relative path in argv[0]

### ISSUE THREAD

**Issue by mrigger** [oracle/graal#787]
Sulong passes the absolute instead of the relative path of the program to argv[0], see https://github.com/graalvm/sulong/issues/769.

@pekd could reproduce this in the latest Sulong version.

**Comment by spavlusieva** [comment]
hi @mrigger, this issue has been inactive for more than 180 days. We’ll close it to focus on current issues. In case it’s still relevant, please reopen it and we’ll take another look. Thank you!
