### ISSUE TITLE
Crash in the latest Intellij IDEA when using graalvm rc9 to run tests.

### ISSUE THREAD

**Issue by markehammons** [oracle/graal#792]
I have not been able to debug graalvm as per [Troubleshooting Graal](https://www.graalvm.org/docs/reference-manual/languages/jvm/#troubleshooting-graal) so far, so maybe you all can help. I've attached the crash log from the application 
[java_error_in_IDEA_31610.log](https://github.com/oracle/graal/files/2565833/java_error_in_IDEA_31610.log)

I've been able to reliably reproduce the crash by:

1. Starting a test suite running in scala using the intellij idea scala plugin
2. Halt the execution of the tests with the stop button

As soon as the test execution halts, the IDE will crash instantly, producing the error log linked above and nothing else. I've tried looking for the core dump to link as well, but the locations specified in the crash log are empty, and I've yet to find where the core file is.

**Comment by dougxc** [comment]
Hi @markehammons , thanks for the report. The crash report you filed shows that the crash happens while [loading`libnotify.so.4`](https://github.com/JetBrains/intellij-community/blob/master/platform/platform-impl/src/com/intellij/ui/LibNotifyWrapper.java#L54):
```
Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
j  com.sun.jna.Native.open(Ljava/lang/String;I)J+0
j  com.sun.jna.NativeLibrary.loadLibrary(Ljava/lang/String;Ljava/util/Map;)Lcom/sun/jna/NativeLibrary;+256
j  com.sun.jna.NativeLibrary.getInstance(Ljava/lang/String;Ljava/util/Map;)Lcom/sun/jna/NativeLibrary;+154
j  com.sun.jna.Library$Handler.<init>(Ljava/lang/String;Ljava/lang/Class;Ljava/util/Map;)V+205
j  com.sun.jna.Native.loadLibrary(Ljava/lang/String;Ljava/lang/Class;Ljava/util/Map;)Ljava/lang/Object;+68
j  com.sun.jna.Native.loadLibrary(Ljava/lang/String;Ljava/lang/Class;)Ljava/lang/Object;+5
j  com.intellij.ui.LibNotifyWrapper.<init>()V+25
j  com.intellij.ui.LibNotifyWrapper.getInstance()Lcom/intellij/ui/LibNotifyWrapper;+10
j  com.intellij.ui.SystemNotificationsImpl.getPlatformNotifier()Lcom/intellij/ui/SystemNotificationsImpl$Notifier;+50
j  com.intellij.ui.SystemNotificationsImpl.<init>()V+5
v  ~StubRoutines::call_stub
J 1309  sun.reflect.NativeConstructorAccessorImpl.newInstance0(Ljava/lang/reflect/Constructor;[Ljava/lang/Object;)Ljava/lang/Object; (0 bytes) @ 0x00007f9a60f4e503 [0x00007f9a60f4e4a0+0x63]
J 23861 JVMCI sun.reflect.NativeConstructorAccessorImpl.newInstance([Ljava/lang/Object;)Ljava/lang/Object; (89 bytes) @ 0x00007f9a62e0de24 [0x00007f9a62e0ddc0+0x64]
J 23860 JVMCI com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.doGetComponentInstance(Lorg/picocontainer/PicoContainer;)Ljava/lang/Object; (144 bytes) @ 0x00007f9a6230539c [0x00007f9a62305020+0x37c]
```

Even though there are some Graal compiled frame on the stack (those labeled as "JVMCI"), it's hard to see how they can be causing the crash since no values from those frame are passed down to the crashing frame (is that a reasonable assessment @tkrodriguez @gilles-duboscq ?).

@markehammons can you please add `-XX:-UseJVMCICompiler` to the VM options used by IntelliJ to see if this happens on GraalVM when Graal is not used as the compiler.

**Comment by tkrodriguez** [comment]
I agree that it's hard to imagine how this could be related to JVMCI.  You might also try the official version of 1.8.0_192 to see if it's something in the latest JDK.

**Comment by markehammons** [comment]
[java_error_in_IDEA_31521.log](https://github.com/oracle/graal/files/2576097/java_error_in_IDEA_31521.log)

I've confirmed, it's a bug in java 8_u192

**Comment by gilles-duboscq** [comment]
> I've confirmed, it's a bug in java 8_u192

Well, let's say it's a bug that's not related to the Graal compiler: it still crashes when disabling the Graal compiler with `-XX:-UseJVMCICompiler`.
As Doug said, it seems to related to loading the system's `libnotify` and maybe its dependency `libgmodule`. It might still be a bad interaction between the system libraries and some of the libraries shipped with GraalVM.

**Comment by tkrodriguez** [comment]
It would be good to test with the official 8u192 so we can confirm it has nothing to do with our repackaging of 8u192 for graal.

**Comment by markehammons** [comment]
I will test it tomorrow.

**Comment by markehammons** [comment]
Sorry it's been a while. I tested with adoptopenjdk java 8u192, and no crash occurs. Switching back to graalvm to run Intellij causes the crash under the situation I listed above. I also tested with graalvm rc7, and it crashes as well in this case.

**Comment by dougxc** [comment]
Hi @markehammons , I'm not sure it will reveal much but I see there are some debug options in JNA that may provide more clues:
https://github.com/java-native-access/jna/blob/7ac44fee3d6b0e47de6d5d10c32be258b9ed1bef/src/com/sun/jna/Native.java
Could you please enable them for both a graalvm execution and an adoptopenjdk execution and attach the logs here.

As a workaround, GraalVM EE should not have this problem. If you have time and resources, it would help if you can confirm this.

**Comment by dougxc** [comment]
This should do it: `-Djna.debug_load=true -Djna.debug_load.jna=true`

**Comment by markehammons** [comment]
I've looked at the logs and I'm seeing nothing interesting from JNA. I'm still getting the same heap dumps as before too

**Comment by dougxc** [comment]
Hmm, I don't have any further ideas. @gilles-duboscq any idea how one could investigate your theory about a possibly bad interaction between the system libraries and some of the libraries shipped with GraalVM?

**Comment by markehammons** [comment]
I've tested this against graal rc10, and the issue is still present

**Comment by markehammons** [comment]
I've created a minimum test case for this: https://github.com/markehammons/graal-issue-792/tree/master

Hopefully it's no problem to use. I'll also be looking up more JNI debugging methods so maybe I can get an idea of what's failing.

**Comment by markehammons** [comment]
@tkrodriguez I just reproduced this with a fresh install and no jvms installed except graal-ce-rc10

**Comment by greensnark** [comment]
I got this same libnotify crash on Arch Linux using IntelliJ's bundled 1.8.0_152 JVM, with no Graal involved at all, so this is probably not a Graal bug. I reported this bug to JetBrains: https://youtrack.jetbrains.com/issue/IDEA-207451

(For the IntelliJ crash, setting `-Dide.libnotify.enabled=false` in idea64.vmoptions stopped IntelliJ from trying to load libnotify, which fixed the crash for me.)

**Comment by tkrodriguez** [comment]
Thanks for the report.  It certainly seemed like a problem with library dependences that didn't really involve us.

**Comment by markehammons** [comment]
@greensnark I'll test this tomorrow. Maybe graalvm aggravates the bug?

**Comment by dougxc** [comment]
Closing on the assumption this is an Intellij bug. Please re-open if new evidence implicates GraalVM.
