### ISSUE TITLE
`mx igv` does not recognize java homes as right version.

### ISSUE THREAD

**Issue by JornVernee** [oracle/graal#793]
When running `mx igv` on the graal/compiler suite I get this error:

```
PS J:\Projects\graal\compiler> mx igv
Could not find a JDK (< 1.8.0u20 or >= 1.8.0u40) and < 11 for running IGV
The following JDKs are available:
  C:\Program Files\Java\jdk-10
  C:\Program Files\Java\jdk-9.0.4
  C:\Program Files\Java\jdk1.8.0_144
  C:\Program Files\Java\jdk1.8.0_162
Specify one with the --java-home or --extra-java-homes option or with the JAVA_HOME or EXTRA_JAVA_HOMES environment variable.
Or run `J:\Projects\mx/select_jdk.py -p J:\Projects\graal\compiler` to set and persist these variables in J:\Projects\graal\compiler\mx.compiler\env.
```
It looks to me like I have several usable Java installations, but for some reason they are not being picked up.

Retrying with e.g. `--java-home 'C:\Program Files\Java\jdk-10'` throws the same error.

**Comment by fniephaus** [comment]
I cannot reproduce this anymore...a lot of things have changed and improved over the last couple of years. Please let us know if this is still an issue.
