### ISSUE TITLE
Truffle crash

### ISSUE THREAD

**Issue by rbotafogo** [oracle/graal#796]
Doing 

      Polyglot.eval("R", "dev.control(displaylist = 'enable')")

works fine, but the following is crashing truffle:

        Polyglot.eval("R", "dev.control(displaylist = 'inhibit')")

Failure/Error: Polyglot.eval("R", "dev.control(displaylist = 'inhibit')")

RuntimeError:
  java.lang.ClassCastException: com.oracle.truffle.r.runtime.data.RNull cannot be cast to com.oracle.truffle.r.runtime.data.RList (RInternalError)
      from com.oracle.truffle.r.nodes.function.FunctionDefinitionNode.execute(FunctionDefinitionNode.java:321)
      from org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callProxy(OptimizedCallTarget.java:289)
      from org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callRoot(OptimizedCallTarget.java:278)
      from org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callBoundary(OptimizedCallTarget.java:265)
      from org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.doInvoke(OptimizedCallTarget.java:247)
      from org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callDirect(OptimizedCallTarget.java:230)
      from org.graalvm.compiler.truffle.runtime.OptimizedDirectCallNode.callProxy(OptimizedDirectCallNode.java:88)
      from org.graalvm.compiler.truffle.runtime.OptimizedDirectCallNode.call(OptimizedDirectCallNode.java:72)
      from com.oracle.truffle.r.nodes.function.call.CallRFunctionNode.execute(CallRFunctionNode.java:59)
      from com.oracle.truffle.r.nodes.function.RCallNode$DispatchedCallNode.execute(RCallNode.java:1157)
  Caused by:
  com.oracle.truffle.r.runtime.data.RNull cannot be cast to com.oracle.truffle.r.runtime.data.RList (ClassCastException)
      from com.oracle.truffle.r.library.fastrGrid.FastRGridExternalLookup.lambda$lookupDotCall$1(FastRGridExternalLookup.java:172)
      from com.oracle.truffle.r.library.fastrGrid.GridStateSetNode.execute(GridStateSetNode.java:52)
      from com.oracle.truffle.r.nodes.builtin.RExternalBuiltinNode$Arg1.call(RExternalBuiltinNode.java:88)
      from com.oracle.truffle.r.nodes.builtin.RExternalBuiltinNode.call(RExternalBuiltinNode.java:40)
      from com.oracle.truffle.r.nodes.builtin.base.foreign.CallAndExternalFunctions$DotCall.doExternal(CallAndExternalFunctions.java:645)
      from com.oracle.truffle.r.nodes.builtin.base.foreign.CallAndExternalFunctionsFactory$DotCallNodeGen.executeAndSpecialize(CallAndExternalFunctionsFactory.java:156)
      from com.oracle.truffle.r.nodes.builtin.base.foreign.CallAndExternalFunctionsFactory$DotCallNodeGen.execute(CallAndExternalFunctionsFactory.java:113)
      from com.oracle.truffle.r.nodes.builtin.RBuiltinNode$Arg3.call(RBuiltinNode.java:200)
      from com.oracle.truffle.r.nodes.function.RCallNode$BuiltinCallNode.execute(RCallNode.java:1100)
      from com.oracle.truffle.r.nodes.function.RCallNode$FunctionDispatch.dispatch(RCallNode.java:882)

**Comment by steve-s** [comment]
Hello Rodrigo, 

thank you for the reporting the issue. It should be fixed in https://github.com/oracle/fastr/commit/b5066aaec2f2cfddf6ecf2036b78f2e6bdc86f8b.
