### ISSUE TITLE
Capturing env var during build time no longer works.

### ISSUE THREAD

**Issue by borkdude** [oracle/graal#7981]
Repro:

``` java
public class Env {
    public static String FOO = System.getenv("FOO");
    public static void main(String [] args) {
        System.out.println("FOO at build time: " + FOO);
    }
}
```

Compile with CE 22.3.1 and run `FOO=1 $GRAALVM_HOME/bin/native-image --initialize-at-build-time=Env Env`
Running the binary `./env` produces:

```
$ ./env
FOO at build time: 1
```

However with Oracle GraalVM 21:

```
$ ./env
FOO at build time: null
```

**Comment by zakkak** [comment]
Hi @borkdude, starting with GraalVM 23.0.0 you need to [explicitly define which env variables should get embedded in the native image using the `-E` option](https://github.com/oracle/graal/pull/6095).

The following will do the trick in your example:
```
$ FOO=1 native-image --initialize-at-build-time=Env Env -EFOO
...
$ ./env
FOO at build time: 1
```

**Comment by borkdude** [comment]
@zakkak Thanks!
