### ISSUE TITLE
How can I write a java function using graalvm to call a function in python which imports numpy or scipy?

### ISSUE THREAD

**Issue by wangminglyx** [oracle/graal#8018]
(https://github.com/oracle/graal/assets/20805890/e6ea9b9a-63ff-440d-b5da-44800144c66e)
**Describe the issue**
When I want to call a python funtion, I succeeded. But if the python function imports numpy, it reported a bug no module named 'numpy'.  However, I installed graalvm already , and I could not find the file that shows in the picture above. And I failed in installing graalpy with code 'gu install python'  in the version of jdk17, also there is no file named gu.cmd or directory named languages in graalvm version jdk21. Can you do me a favor please?

**Describe GraalVM and your environment:**
 - GraalVM version (latest snapshot builds can be found [here](https://github.com/graalvm/graalvm-ce-dev-builds/releases)), or commit id if built from source: **[e.g. EE 19.3, CE 20.0, CE 20.1.0-dev-20200304_0848]**
 - JDK major version: **17 and  21**
 - OS: **Windows 10**
 - Architecture: ** AMD64 **

**Comment by hamzaGhaissi** [comment]
- As of Graalvm for JDK 21 the Python runtime (GraalPy) is available as a standalone distribution, and there's no `gu install...`
- For NumPy it's not a pure Python package so can't use it
- For Graalvm for JDK 17 There is currently no installer for Windows. Instead, follow [these instructions](https://github.com/oracle/graalpython#user-content-building-from-source) to build GraalPy from source.

**Comment by Zireael07** [comment]
That should be called out somewhere in the docs. Numpy/Scipy are extremely commonly used in the Python world.

**Comment by hamzaGhaissi** [comment]
@Zireael07 ,GraalPy in just a preview build for Windows. you can find limitations here https://www.graalvm.org/latest/reference-manual/python/#graalpy-for-windows
