### ISSUE TITLE
Determine the default locale at runtime, not build time

### ISSUE THREAD

**Issue by Berstanio** [oracle/graal#8022]
**Feature request**

Please include the following information:

**Is your feature request related to a problem? Please describe.**
When shipping a native-image executable to users, where some features for localization depend on determining the system selected locale, there is currently no proper way to do that.
The default locale is determined at image build time, so always the one of the build environment: https://github.com/oracle/graal/blob/c203aac336154710279d84f2c802010923cc31a2/substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jdk/localization/substitutions/Target_java_util_Locale.java#L47
This is very inconvenient, since I need to use e.g. C functions like `setlocale` to try to overcome this limitation.

**Describe the solution you'd like.**
It would be great, if `Locale.getDefault()` would return the user locale using native-image, like it does in a JVM.
I briefly skimmed through the JVM code and I haven't saw a direct reason, why it can't be utilized in native-image too.

**Describe who do you think will benefit the most.**
GraalVM users that ship their applications to users across the world and depend on localization for e.g. formatting.

**Describe alternatives you've considered.**
Currently I'm calling `setlocale(LC_ALL, NULL);` through JNI and try to determine the locale through this. However, looking at the complex JVM code to determine the locale, my code is a rather lazy approach that might have a lot of caveats.

**Express whether you'd like to help contributing this feature**
I'm happy to help out, if I would know, what the right/preferred approach for this is.

**Comment by hamzaGhaissi** [comment]
Native Image does not include all locales by default, because it would increase the size of the binaries.  Please take a look at the options in [https://github.com/oracle/graal/blob/c203aac336154710279d84f2c802010923cc31a2/subs[…]com/oracle/svm/hosted/jdk/localization/LocalizationFeature.java](https://github.com/oracle/graal/blob/c203aac336154710279d84f2c802010923cc31a2/substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/jdk/localization/LocalizationFeature.java#L175)  If you have a use case that is important to your project and not supported at the moment via these options, please create an issue with a reproducer where it can be discussed.

**Comment by Berstanio** [comment]
@hamzaGhaissi 
I'm fully aware that not all locales are included by default. My request is not about that fact, but about adding a option that allows to determine the system locale at run-time, something like `-H:+IncludeAllLocales -H:+DefaultLocaleAtRunTime`. Sorry, if that wasn't clear.
The reproducer is rather trivial:
```java
import java.util.Locale;

public class Test {

    public static void main(String[] args) {
        System.out.println(Locale.getDefault().toString());
    }
}
```
1. export LC_ALL=en_US
2. javac Test.java
3. native-image -H:+IncludeAllLocales Test
4. export LC_ALL=en_UK
5. java Test / ./test

The JVM will report the correct locale while the native-image will report the incorrect "en_US". As far as I can tell, there is no option that native-image reports the correct system locale as default.

I think this issue covers this feature request, should I still open a new issue?
