### ISSUE TITLE
svm-driver doesn't seem to work with stock JDK

### ISSUE THREAD

**Issue by fcurts** [oracle/graal#806]
I’m trying to run the native-image command via `com.oracle.substratevm:svm-driver:1.0.0-rc9` (with Oracle JDK 8 on macOS 10.14), but I’m getting the following:

```
Error: Unable to use jar-files from directory /Library/Java/JavaVirtualMachines/jdk1.8.0_171.jdk/Contents/Home/jre/lib/svm/builder
Caused by: java.nio.file.NoSuchFileException: /Library/Java/JavaVirtualMachines/jdk1.8.0_171.jdk/Contents/Home/jre/lib/svm/builder
```

What am I doing wrong? (I assume the purpose of svm-driver is to be able to run native-image without a GraalVM distribution.)

PS: I couldn't find any docs or examples for how to use svm-driver.

**Comment by olpaw** [comment]
ATM, a JVMCI enabled JDK 8 is required. See https://github.com/oracle/graal/blob/master/substratevm/README.md#quick-start (Alternatively you can use our JVMCI enabled OpenJDK builds from https://github.com/graalvm/openjdk8-jvmci-builder/releases

**Comment by fcurts** [comment]
I see. Looking forward to when this will work with a stock JDK. Until then we'll keep using GraalVM CE.
