### ISSUE TITLE
fonts not appearing in native compiled version

### ISSUE THREAD

**Issue by crowlogic** [oracle/graal#8092]
**Describe the issue**
Check out https://github.com/crowlogic/chatgptapi/
mvn gluonfx:run works
mvn gluonfx:nativeRun on one machine works fine, on the other machine, no fonts are shown

**Steps to reproduce the issue**
not sure, it works on one machine and not the other and they are identically configured

**Describe GraalVM and your environment:**
/usr/lib/jvm/graalvm-svm-java17-linux-gluon-22.1.0.1-Final/

Other people are encountering this issue too

see
https://stackoverflow.com/questions/77109210/javafx-not-rendering-via-gluonfxnativerun-on-graalvm-svm-java17-linux-gluon-22
and
https://stackoverflow.com/questions/75425498/graalvm-native-javafx-application-visual-bugs

**Comment by medoussboug** [comment]
Hello, can you give me more details about the machines you used and the GraalVM version you use.

**Comment by crowlogic** [comment]
The issue still exists, unless there is some rule that says a bug ceases to exist if not followed up on within a certain amount of time?

I ran the compiled binary with -Dprism.debugfonts=true and have attached the results along with the diff, badfonts.txt is the output on the machine where you cant see the fonts

[goodfonts.txt](https://github.com/oracle/graal/files/14003224/goodfonts.txt)
[badfonts.txt](https://github.com/oracle/graal/files/14003225/badfonts.txt)
[fonts.diff.txt](https://github.com/oracle/graal/files/14003226/fonts.diff.txt)

**Comment by crowlogic** [comment]
> Hello, can you give me more details about the machines you used and the GraalVM version you use.

what program can i run to produce this info? I dont think its proper to close an issue as resolved just because followup information was not received on it in some unspecified time frame

**Comment by medoussboug** [comment]
Hello, we have an internal policies to close tickets after 15 days inactivity. Regarding your issue, file this issue to Gluon as Gluon forked graalVM so the issue should be filed to them, and if they find that it is an issue with graalVM they can file a ticket to us. The graalVM version is 2 years old, there have been numerous bug and security fixes since then, kindly upgrade your GraalVM version.

Kind regards,
