### ISSUE TITLE
create() method of generated Node class should be near the top of the file

### ISSUE THREAD

**Issue by fcurts** [oracle/graal#810]
In a Node class generated by Truffle's code generator, the static `create()` method is the method most often called directly from user code. Currently, this method is located at the bottom of the (often large) generated source file. It would be nice if this method was instead located near the top of the file, as this would make it much easier to discover and navigate to.

**Comment by boris-spas** [comment]
Tracking internally as Issue GR-20796.

**Comment by antrix190** [comment]
Hey @boris-spas @fcurts can i work on this if this is still relevant?

**Comment by fcurts** [comment]
@antrix190 This would be a very nice usability improvement.

**Comment by antrix190** [comment]
Waiting for @boris-spas to confirm

**Comment by boris-spas** [comment]
Hey all,

After some consultation it turns out that the order of methods is intentional, first instance methods then static methods then inner classes.

Gonna close this issue.

**Comment by fcurts** [comment]
Did you consider that public methods should come before protected/private ones?

**Comment by chumer** [comment]
No but instance methods before static methods. That is a convention we use all over the Truffle code base.
We will not be able to make everyone happy with the code layout we produce, unfortunately. And making the style configurable is not worth the complexity in my opinion.
