### ISSUE TITLE
In js binary arrows doesn't work

### ISSUE THREAD

**Issue by asm0dey** [oracle/graal#815]
While in node binary they do

**Comment by wirthi** [comment]
Hi @asm0dey,

thanks for your question.  I assume you refer to `arrow functions`: they do work :-)

```
christian@cw-laptop:~$ js
> var a = () => { print("hello world"); }
> a()
hello world
> 
```

But of course, we might have a bugs in cornercases. Can you post a minified code example of what is failing for you?

Best,
Christian
