### ISSUE TITLE
Use -Xms2048m run native image,but the application only use 500m memory?

### ISSUE THREAD

**Issue by wghdir** [oracle/graal#8171]
**Describe the issue**
Use -Xms2048m run native image,but the application only use 500m memory?why small 2048m.Should the minimum allocated memory not be 2048m?

**Comment by selhagani** [comment]
Hi @wghdir, please choose one of the templates mentioned in [this link](https://github.com/oracle/graal/issues/new/choose) that corresponds to your needs. Thank you!
