### ISSUE TITLE
missing character set id 852 is not loaded at image build time

### ISSUE THREAD

**Issue by furen123** [oracle/graal#8172]
hello.when I use springboot3.2.1 with graalvm-jdk-21.0.1+12.1.it built successed.But when connection to oracle database.It report error.
     missing character set id 852 is not loaded at image build time
     at oracle.sql.CharacterSet.make
How can I solve the problem ?

**Comment by selhagani** [comment]
Hi @furen123 , could you please share with me your OS version and your processor's architecture? Also, could you include a concise reproducer for this issue? Thank you.
