### ISSUE TITLE
Error: Failed to automatically set up Windows build environment

### ISSUE THREAD

**Issue by bawantha** [oracle/graal#8173]
**Describe the issue**
A clear and concise description of the issue. We recommend using the [latest snapshot builds]
followed this official video from gralVm YT https://www.youtube.com/watch?v=UWxiO78Pev8

**Steps to reproduce the issue**
Please include both build steps as well as run steps
1. `native-image Hello`
Hello.java
```
public class Hello{
    public static void main(String[] args)
    {
        System.out.println("I am a Geek");
    }
}
```

**Describe GraalVM and your environment:**

 - GraalVM version 
  native-image 17.0.9 2023-10-17
  GraalVM Runtime Environment GraalVM CE 17.0.9+9.1 (build 17.0.9+9-jvmci-23.0-b22)
  Substrate VM GraalVM CE 17.0.9+9.1 (build 17.0.9+9, serial gc)

 - JDK major version: **[e.g.:8]**
   java 17.0.9 2023-10-17 LTS Java(TM) SE Runtime Environment (build 17.0.9+11-LTS-201) Java HotSpot(TM) 64-Bit Server VM 
  (build 17.0.9+11-LTS-201, mixed mode, sharing)

 - OS: **[e.g. macOS Catalina]**
 Edition	Windows 11 Home Version	22H2 Installed on	‎7/‎18/‎2023 OS build	22621.3007 Experience	Windows Feature Experience Pack 1000.22681.1000.0
 - Architecture: **[e.g.: AMD64]**
PROCESSOR_ARCHITECTURE=AMD64 PROCESSOR_IDENTIFIER=AMD64 Family 23 Model 96 Stepping 1, AuthenticAMD PROCESSOR_LEVEL=23 PROCESSOR_REVISION=6001

**More details**
```
Error: Failed to automatically set up Windows build environment.
Please make sure that Visual Studio 2022 version 17.1.0 or later is installed on your system. You can download it at https://visualstudio.microsoft.com/downloads/. If this error persists, please try and run GraalVM Native Image in an x64 Native Tools Command Prompt or file a ticket.


```
Visual Studio

Installed `17.8.4`
![image](https://github.com/oracle/graal/assets/17080593/799871cf-08db-45a5-8d00-99b2e415a834)

Installation details

![image](https://github.com/oracle/graal/assets/17080593/91eda47c-1baf-4241-901a-5e77ae9b80d9)

**Comment by fniephaus** [comment]
@bawantha did you install VS in a non-standard location?

**Comment by bawantha** [comment]
> @bawantha did you install VS in a non-standard location? 

I don't think, it is in C:/  Program files /Microsoft Visual Studio

**Comment by fniephaus** [comment]
Interesting, it seems you are hitting this case:
https://github.com/oracle/graal/blob/69fd1f5ec434ebf7464a93aa01afd6a6005e37dc/substratevm/src/com.oracle.svm.driver/src/com/oracle/svm/driver/WindowsBuildEnvironmentUtil.java#L126

Which means the detection ran but then `VSINSTALLDIR` was still not set correctly.

I'm currently using Windows 10 SDK. Could you maybe try with this configuration?

![image](https://github.com/oracle/graal/assets/2368856/2dbfd194-5198-42b7-b079-071ca29b2d1f)

**Comment by bawantha** [comment]
Used this as well, same output

**Comment by bawantha** [comment]
This is  x64 Native Tools Command Prompt
![image](https://github.com/oracle/graal/assets/17080593/590d7f52-041b-4951-be0a-535d55d0b63b)

**Comment by bawantha** [comment]
I don't know how this relate but after adding` C:\Windows\System32` to Path this was sorted

**Comment by fniephaus** [comment]
>I don't know how this relate but after adding C:\Windows\System32 to Path this was sorted

Isn't that location on the path by default? How come you tried that? It'd still be good to understand how you ran into this problem.
