### ISSUE TITLE
Use mx's auto-shader to dymaically shade ASM and JCODING dependencies for Truffle 

### ISSUE THREAD

**Issue by zakkak** [oracle/graal#8188]
**Feature request**

Use mx's auto-shader to dymaically shade ASM and JCODING dependencies for Truffle, like you already do for ICU4J and others.

**Is your feature request related to a problem? Please describe.**

As discussed in https://github.com/graalvm/mandrel-packaging/pull/369, we would need the ASM and JCODING dependencies used by Truffle to be auto-shaded by `mx` in order to be able to build Mandrel with Truffle support, since for our internal builds we build everything from source.

**Describe the solution you'd like.**
Use mx's auto-shader to dymaically shade ASM and JCODING dependencies for Truffle, like you already do for ICU4J and others. This would allow us to use our builds of ASM and JCODING when building Mandrel internally.

**Describe who do you think will benefit the most.**
Quarkus users that would like to use truffle in their native images.

**Describe alternatives you've considered.**
N/A

**Express whether you'd like to help contributing this feature**
I tried creating the auto-shaded packages but I am not sure how the original shaded packages were generated in the first place, nor am I familiar with mx's auto-shade API, so I am afraid I can't help much.

**Comment by woess** [comment]
> I thought we already do shade those?

We do, just not using mx's source-based auto-shader (yet). There's probably no reason we couldn't do that. We'll look into it for the next release.

**Comment by zakkak** [comment]
WIP PR implementing this: https://github.com/oracle/graal/pull/8257
