### ISSUE TITLE
[native-image] @Substitute unable to process classes whose classpath is incomplete

### ISSUE THREAD

**Issue by Sanne** [oracle/graal#819]
Hello,

`AnnotationSubstitutionProcessor#handleSubstitutionClass` at its very end performs:

https://github.com/oracle/graal/blob/a8b4308f7a8698e598c3365f77bd30f31e65da46/substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/substitute/AnnotationSubstitutionProcessor.java#L492-L494

This won't work with a broken classpath, for example if any of those fields is of a type which is not loadable.

Ironically, I did hit this limitation because I was trying to remove those fields by using `@Delete` annotations as I need to prevent graalvm to ever load those incompatible types.

I see `com.oracle.svm.hosted.ImageClassLoader#handleClassLoadingError` reacts to a similar situation by ignoring the error:

https://github.com/oracle/graal/blob/3c6b9be1a26856ef8714bac11188e9c5c66fb5e1/substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/ImageClassLoader.java#L185-L201

It would be great if this case could also be ignored? I'm not sure why the declared fields need to be loaded - *especially* as I'm marking them for deletion.

In fact I'm trying to replace the whole target class and I wouldn't mind to have it generate a "clean slate" by copying none of the fields at all: currently I have to list all its fields and mark them for removal, when I just meant to replace this implementation class with a dummy implementantation having the same methods but no fields at all.

### Real world need: PostgreSQL JDBC drivers

More concretely, I'm trying to get the PostgreSQL JDBC driver to run in GraalVM. It includes support for some Windows-only features which should be disabled, and which in turn depend on Windows-only additional dependencies.

Since a GraalVM application doesn't run on Windows I thought it would be easiest to just rip out such functionality by using the Substitutions mechanisms.

Fields in `org.postgresql.sspi.SSPIClient` should be deleted as well as they refer to types which aren't available:
 - https://github.com/pgjdbc/pgjdbc/blob/08631ccdabdb8ba6d52f398e2b0b46a9cf0cafbf/pgjdbc/src/main/java/org/postgresql/sspi/SSPIClient.java#L45-L46

### Workaround

I'll see if I can totally dodge this type rather than having to partially substitute its fields. Still, just filing this issue in case there's interest in improving the Substitute mechanism, as I think it should be able to remove fields which aren't loadable.

Thanks!

**Comment by fniephaus** [comment]
Hey @Sanne, looks like we haven't responded to your ticket, apologies! `@Substitute` is a very powerful mechanism and because it's too easy to mess things up, it is not part of the public API of Native Image. I'm sure you have found a different way to resolve this in the meantime, lots of things have changed in the last couple of years too.

I hope you don't mind that I'm closing this ticket for now. Please let us know if this is still an issue. Thanks!
