### ISSUE TITLE
Error while compile elasticsearch

### ISSUE THREAD

**Issue by hacker13ua** [oracle/graal#823]
> openjdk version "11.0.1" 2018-10-16
> OpenJDK Runtime Environment 18.9 (build 11.0.1+13)
> OpenJDK 64-Bit Server VM 18.9 (build 11.0.1+13, mixed mode)

[graal_diagnostics_8819.zip](https://github.com/oracle/graal/files/2614483/graal_diagnostics_8819.zip)

**Comment by dougxc** [comment]
This is a case of OpenJDK missing a JVMCI-8 change. I've filed https://bugs.openjdk.java.net/browse/JDK-8214290 to get it addressed.
