### ISSUE TITLE
Support static linking of JNI libs

### ISSUE THREAD

**Issue by FroMage** [oracle/graal#827]
ATM when using SSL we must run with `-Djava.library.path=$GRAALVM_HOME/jre/lib/amd64` to get the `libsunec.so`, but that's asymmetrical to the rest of the JDK which is statically linked in the executable. Could we get an option to statically link specified JNI libs into the executable to avoid that external runtime dependency?

**Comment by cstancu** [comment]
@FroMage this improvement is on our TODO list. Thanks for the report!

**Comment by neomatrix369** [comment]
I think you now do this already via the `--static` option?

**Comment by lvh** [comment]
That statically links libc and zlib specifically, but not anyhting else, IIUC.

**Comment by lvh** [comment]
FWIW I think resolving this would also resolve #1336.

**Comment by neomatrix369** [comment]
@lvh thanks for the response, I'll update the docs via a PR to express this next to the `--static` option

**Comment by neomatrix369** [comment]
@lvh FYI: just raised a PR https://github.com/oracle/graal/pull/1602

**Comment by lvh** [comment]
FWIW 19.3.0 at least fixes the libsunec case and I think maybe it just lets you link anything now?

**Comment by olpaw** [comment]
Closing issue since 19.3. we depend on static linking of JNI libs of the JDK.

If there are issues with specific JNI libs that cause problems please open individual issues for them.

**Comment by lvh** [comment]
@olpaw is there any documentation on how to use that feature? There's a JNI doc in the repo but it's pretty outdated (still mentions SubstrateVM, for one) :)

concretely: let's say I have a JNI library (ideally the JNI library is actually jnr-ffi), how do I build a native image that uses it?

**Comment by manuel-alvarez-alvarez** [comment]
@lvh did you manage to use a static library with a statically built native image? 

I'm trying to add support for [Brotli4j](https://github.com/hyperxpro/Brotli4j), so far by using `-H:NativeLinkerOption` I'm able to link using a static `libbrotli.a` so the resulting executable appears to be properly built:

```
/project/target # readelf -Ws application | grep brotli
 37260: 0000000001bcea40    72 FUNC    GLOBAL DEFAULT    2 Java_com_aayushatharva_brotli4j_decoder_DecoderJNI_nativeDestroy
 37262: 0000000001bcea90   327 FUNC    GLOBAL DEFAULT    2 Java_com_aayushatharva_brotli4j_encoder_EncoderJNI_nativeCreate
 37379: 0000000001bcee20    72 FUNC    GLOBAL DEFAULT    2 Java_com_aayushatharva_brotli4j_encoder_EncoderJNI_nativeDestroy
 37661: 0000000001bce950   235 FUNC    GLOBAL DEFAULT    2 Java_com_aayushatharva_brotli4j_decoder_DecoderJNI_nativePull
 37908: 0000000001bce7e0   354 FUNC    GLOBAL DEFAULT    2 Java_com_aayushatharva_brotli4j_decoder_DecoderJNI_nativePush
 38116: 0000000001bce5c4    38 FUNC    GLOBAL DEFAULT    2 JNI_OnLoad_brotli
 38290: 0000000001bcebe0   365 FUNC    GLOBAL DEFAULT    2 Java_com_aayushatharva_brotli4j_encoder_EncoderJNI_nativePush
 38375: 0000000001bced50   201 FUNC    GLOBAL DEFAULT    2 Java_com_aayushatharva_brotli4j_encoder_EncoderJNI_nativePull
 38523: 0000000001bce5ea    34 FUNC    GLOBAL DEFAULT    2 JNI_OnUnload_brotli
 38535: 0000000001bce6d0   263 FUNC    GLOBAL DEFAULT    2 Java_com_aayushatharva_brotli4j_decoder_DecoderJNI_nativeCreate
 38773: 0000000001bce610   177 FUNC    GLOBAL DEFAULT    2 Java_com_aayushatharva_brotli4j_common_CommonJNI_nativeSetDictionaryData
```

But all attempts to load the library with `System.loadLibrary("brotli")` yield an `java.lang.UnsatisfiedLinkError: no brotli in java.library.path` exception.

Thanks in advance for any suggestions / help

**Comment by lvh** [comment]
Nope, sorry.
