### ISSUE TITLE
Warning caused by Truffle and Polyglot 

### ISSUE THREAD

**Issue by CptGummiball** [oracle/graal#8314]
**Describe GraalVM and your environment :**
 - GraalVM version or commit id if built from source: **23.1.2**
 - CE or EE: **[e.g.: CE]**
 - JDK version: **JDK 17**
 - OS and OS Version: **Build with Windows 10 IntelliJ** 
 - Architecture: **amd64**
 - The output of `java -Xinternalversion`:
```
Java HotSpot(TM) 64-Bit Server VM (21.0.1+12-LTS-29) for windows-amd64 JRE (21.0.1+12-LTS-29), built on 2023-10-05T13:27:09Z by "mach5one" with MS VC++ 17.1 (VS2022)
```

**Have you verified this issue still happens when using the latest snapshot?**
yes

**Describe the issue**
I have integrated GraalVM into my project for a Spigot plugin and python scripts are also running correctly. However, I get a long error message as soon as a script is executed.

Since I don't know exactly what I should do or what I need to change in my script, I wanted to ask here.
Tried to kill these warnings with options but it makes it even worse. (Plugin dont load)

**Code snippet or code repository that reproduces the issue**
```
https://github.com/CptGummiball/Spython/blob/main/src/main/java/org/cptgum/spython/PythonExecutor.java
```

**Steps to reproduce the issue**
Please include both build steps as well as run steps
1. Step one [e.g.: git clone --depth 1 https://git.myrepo.com/projectone ]
2. Step two [e.g.: mvn clean package]

**Expected behavior**
No warnings ^^ 

**Additional context**

Heres the warning from console:
![image](https://github.com/oracle/graal/assets/151415484/02cbc118-5aac-429b-b004-963e4ea99695)

you can find my pom.xml here:
https://github.com/CptGummiball/Spython/blob/main/pom.xml

```
    PASTE YOUR LOG/STACK TRACE HERE
```
</details>

**Comment by timfel** [comment]
@CptGummiball very simple scripts may work, but these warnings tell you that many more complex things will not. Try using the struct module, email or xml parser for example. You can change the warnings using `log.python.level` if you want to ignore this.

**Comment by timfel** [comment]
@CptGummiball the proper way to fix this for you is to fix your dependency: https://github.com/CptGummiball/Spython/blob/4b2c2bf426014bf1cd7f55dfab13151d1366ac15/pom.xml#L87

You have
```xml
      <dependency>
          <groupId>org.graalvm.python</groupId>
          <artifactId>python-language</artifactId>
          <version>23.1.2</version>
      </dependency>
```

It should be
```xml
      <dependency>
          <groupId>org.graalvm.polyglot</groupId>
          <artifactId>python</artifactId>
          <version>23.1.2</version>
      </dependency>
```

**Comment by CptGummiball** [comment]
@timfel Thx, the polyglot dependency not woked for me before but i think this was just a problem with the IDE.

**Comment by CptGummiball** [comment]
I will close this issue. its working now but i had to add "<type>"

      <dependency>
          <groupId>org.graalvm.polyglot</groupId>
          <artifactId>python</artifactId>
          <version>23.1.2</version>
          <type>pom</type>
      </dependency>
