### ISSUE TITLE
[native-image] main class not considered for reflective access in static analysis

### ISSUE THREAD

**Issue by johanvos** [oracle/graal#838]
By default, the main class of an application is not considered to be subject to reflective access. 
By supplying the class and its constructors via -H:ReflectionConfigurationFiles the main class can be accessed via reflection though.

**Comment by vjovanov** [comment]
I will need to have your setup in order to fix this. I have tried with an incomplete classpath and then I get the following exception: 
```
Exception in thread "main" java.lang.ClassNotFoundException: HelloWorld. This exception was synthesized during native image building from a call to java.lang.Class.forName(String, boolean, ClassLoader) with a constant class name argument.
```

When I have it on the classpath, everything works fine. Do you have a repo/tarball where I could try it out and see why it fails?

**Comment by johanvos** [comment]
This HelloFX file should fail:
```
import javafx.application.Application;
import javafx.scene.Scene;
import javafx.scene.control.Label;
import javafx.scene.layout.StackPane;
import javafx.stage.Stage;

public class HelloFX extends Application {

    @Override
    public void start(Stage stage) {
        String javaVersion = System.getProperty("java.version");
        String javafxVersion = System.getProperty("javafx.version");
        Label l = new Label("Hello, JavaFX " + javafxVersion + ", running on Java " + javaVersion + ".");
        Scene scene = new Scene(new StackPane(l), 640, 480);
        stage.setScene(scene);
        stage.show();
    }

    public static void main(String[] args) {
        ClassLoader cl = HelloFX.class.getClassLoader();
        try {
            Class me = Class.forName("HelloFX", false, cl);
            System.out.println("[JVDBG] I am = "+me);
        }
        catch (Throwable t) {
            System.out.println("[JVDBG] class forName went wrong:");
            t.printStackTrace();
        }
        launch();
    }
}
```
The output is something like this:
```
[JVDBG] HelloFX, main starts now
my classloader = java.lang.ClassLoader@10796b110
[JVDBG] I am = class HelloFX
[JVDBG] in Foo, HelloFX  = class HelloFX
Exception in thread "main" java.lang.RuntimeException: java.lang.ClassNotFoundException: HelloFX
	at java.lang.Throwable.<init>(Throwable.java:310)
	at java.lang.Exception.<init>(Exception.java:102)
	at java.lang.RuntimeException.<init>(RuntimeException.java:96)
	at javafx.application.Application.launch(Application.java:260)
	at HelloFX.main(HelloFX.java:32)
	at com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:164)
Caused by: java.lang.ClassNotFoundException: HelloFX
	at java.lang.Throwable.<init>(Throwable.java:287)
	at java.lang.Exception.<init>(Exception.java:84)
	at java.lang.ReflectiveOperationException.<init>(ReflectiveOperationException.java:75)
	at java.lang.ClassNotFoundException.<init>(ClassNotFoundException.java:82)
	at com.oracle.svm.core.hub.ClassForNameSupport.forName(ClassForNameSupport.java:51)
	at java.lang.Class.forName(DynamicHub.java:1036)
	at javafx.application.Application.launch(Application.java:248)
	... 2 more
```

Note that the Class.forName works when done with known arguments, from the main class.
The main class extends javafx.application.Application, which is part of the vm (in the 8-vm), and which will make a call to Class.forName with the same arguments. Only this call is redirected to ClassForNameSupport.forName. The call in the main() method of the HelloFX call is not redirected to ClassForNameSupport.forName().

I added some delayClassInitialization parameters to fix issues with threads being started from <clinit>s:
```
-H:DelayClassInitialization=com.sun.javafx.tk.quantum.QuantumRenderer \
-H:DelayClassInitialization=javafx.stage.Screen \
-H:DelayClassInitialization=com.sun.javafx.scene.control.behavior.BehaviorBase \
-H:DelayClassInitialization=com.sun.javafx.scene.control.skin.BehaviorSkinBase \
-H:DelayClassInitialization=javafx.scene.control.SkinBase \
-H:DelayClassInitialization=javafx.scene.control.Control \
-H:DelayClassInitialization=javafx.scene.control.PopupControl \
-H:DelayClassInitialization="javafx.scene.control.SkinBase\$StyleableProperties" \
-H:DelayClassInitialization="javafx.scene.control.Labeled\$StyleableProperties" \
-H:DelayClassInitialization="javafx.scene.control.SkinBase\$StyleableProperties" \
-H:DelayClassInitialization="com.sun.javafx.tk.quantum.PrismImageLoader2\$AsyncImageLoader" \
-H:DelayClassInitialization=com.sun.javafx.tk.quantum.PrismImageLoader2 \
-H:DelayClassInitialization=com.sun.prism.PresentableState \

```

**Comment by vjovanov** [comment]
This happens because `Class.forName("HelloFX")` is replaced during compilation with a constant that points to a `Class` that we asked for. This class is not added to the reflection configuration in order to save space in the image heap.

The failure comes from the `Application.launch` where we can't prove that the class name is constant and we can't reduce the call to the `HelloFX.class` constant. Hence, we have to stay with the reflection config that identifies the main class for now. 

This is a bit annoying for general usage as people will have to manually add their class every time. We can fix this by adding a `JavaFXFeature` that will detect (e.g., by seeing which classes extend `Application`) all classes that are reflectively used from launch, and add mark them as reflectively used.

**Comment by vjovanov** [comment]
Fixed [here](https://github.com/oracle/graal/commit/707871dc149f93948284c43f3bf0cb8387ffe5a8).  It would be best that this feature migrates to the JavaFX project once we are done with the implementation. That way it will be easier to maintain the list of classes for which do special treatment.

Now, the image on Java 8 builds with the following command:
```
 native-image -H:Features=com.oracle.svm.hosted.javafx.JavaFXFeature HelloFX
```
