### ISSUE TITLE
Static binary compiled with musl reports question mark for (System/getProperty "user.home")

### ISSUE THREAD

**Issue by borkdude** [oracle/graal#8466]
A static binary compiled with musl returns "?" for `(System/getProperty "user.home")`

According to @vjovanov on Slack:

> Internally we use getpwuid. It seems that statically linking this with musl can cause problems: https://github.com/aristocratos/btop/issues/84

Unfortunately I don't have a full repro for this, but it was reported by one of the babashka users:

https://github.com/babashka/bbin/issues/75

I can't reproduce this myself on a WSL2 Ubuntu system but @vjovanov suggested I would create an issue for this nonetheless.

**Comment by selhagani** [comment]
Hi @borkdude, Thank you for reaching out to us. I'm afraid the issue isn't clear here. Please follow this template to create the issue [Templates](https://github.com/oracle/graal/issues/new/choose)

**Comment by borkdude** [comment]
I don't have any more information but @vjovanov might be able to follow up. If not, there's not much else I can do.
