### ISSUE TITLE
JVM crash when using openjdk jvmci + graal compiler

### ISSUE THREAD

**Issue by markehammons** [oracle/graal#847]
I have been toying with using the [compiler.jar](https://search.maven.org/artifact/org.graalvm.compiler/compiler/1.0.0-rc9/jar) to use graalvm's jitc with openjdk. It seems error prone and crashes a lot though. Also, some software that works with stock openjdk (coursier, a scala library for dependency resolution) fails to function properly with jvmci enabled and the compiler.jar loaded.

Here's a log from a recent crash using this combination:
[hs_err_pid25070.log](https://github.com/oracle/graal/files/2658692/hs_err_pid25070.log)

I'm not sure where the core dump is located even though it says one was generated.

**Comment by markehammons** [comment]
I got this error log and what I hope is a core dump from another attempt at running play's twirl compiler:
[hs_err_pid3950.log](https://github.com/oracle/graal/files/2658989/hs_err_pid3950.log)
[1544222891233.zip](https://github.com/oracle/graal/files/2658990/1544222891233.zip)

**Comment by spavlusieva** [comment]
hi @markehammons, this issue has been inactive for more than 180 days. We’ll close it to focus on current issues. In case it’s still relevant, please reopen it and we’ll take another look. Thank you!
