### ISSUE TITLE
docs/getting-started/windows/   has misleading pictures

### ISSUE THREAD

**Issue by slow-groovin** [oracle/graal#8471]
**Describe the issue**
1. step 3,  Installer windows title is `Visual studio build tools 2019`
https://github.com/oracle/graal/blob/master/docs/getting-started/img/desktop_development_with_C.png
2.  step 6,7, installer window title is `Visual studio Community 2019 `
https://github.com/oracle/graal/blob/master/docs/getting-started/img/windows-10-installed.png

commit: https://github.com/oracle/graal/commit/d6df93a4be9073e062df5b3659a4d3ac763421e3

I follow the guides, and install that two comonents, and it not worked, it maybe has conflict .
After tests, i figure out that the cl.exe of  2019version is not support by newest version native-image, only install the newest version Visual Studio Community (now is 2022) can work.

**Comment by olyagpl** [comment]
@slow-groovin, the [Windows installation guide](https://www.graalvm.org/latest/docs/getting-started/windows/) was updated to be compatible with Windows 11 SDK. Thank you for reporting!
