### ISSUE TITLE
[Substrate VM] Can't use Jackson decoding

### ISSUE THREAD

**Issue by Trumeet** [oracle/graal#848]
I've compiled a jar using graal vm and maven, then build a native image with 
```shell
./bin/native-image \ 
 --verbose --allow-incomplete-classpath \
 --no-server \
 -Dio.netty.noUnsafe=true  \
 -H:Name=my-image \
 -H:+ReportUnsupportedElementsAtRuntime \
 -Dfile.encoding=UTF-8 \
 -jar ./app-prod.jar
```
When I run it and decodes a string into a `JsonObject` using `Jackson`, it said "Cannot construct instance of java.util.LinkedHashMap":
```
Exception in thread "main" io.vertx.core.json.DecodeException: Failed to decode: Cannot construct instance of `java.util.LinkedHashMap` (no Creators, like default construct, exist): no default constructor found
 at [Source: (String)"{ ... (Json string)...","[truncated 4244 chars]; line: 1, column: 1]
.... Stacktrace
```

I have no idea about using reflection with Substrate VM, could anybody give me a hand? Thanks a lot!

**Comment by Trumeet** [comment]
Version: ```graalvm-ce-1.0.0-rc10```

**Comment by pmlopes** [comment]
You need to whitelist the constructor on your reflection json file.

**Comment by Trumeet** [comment]
@pmlopes Thank you for your solution, it has been solved :+1:

**Comment by marcelomrwin** [comment]
> You need to whitelist the constructor on your reflection json file.

Can you show some example?

**Comment by pmlopes** [comment]
@marcelomrwin sure, either do it in json:

```json
[
  {
    "name": "java.util.LinkedHashMap",
    "methods": [
      { "name": "<init>", "parameterTypes": [] }
    ]
  }
]
```

or in code:

```java
@AutomaticFeature
class RuntimeReflectionRegistrationFeature implements Feature {
  public void beforeAnalysis(BeforeAnalysisAccess access) {
    try {
      RuntimeReflection.register(java.util.LinkedHashMap.class.getDeclaredConstructor());
    } catch (NoSuchMethodException e) {
      throw new RuntimeException(e);
    }
  }
}
```

Using JSON is simpler I believe, use code if you're already writing substitutions.
