### ISSUE TITLE
Extending native applications with Java and JS

### ISSUE THREAD

**Issue by guaporocco** [oracle/graal#849]
Hello,

I'd like to use Graal to extend a c++ application to support polyglot execution of Java and JS (ie, [extending a native application](https://github.com/chrisseaton/graalvm-ten-things#7-extend-a-native-application)). 

However, it does not seem possible to use Java as a "guest-language." Would my best bet be to implement Java in truffle? Or is the Graal JVM compiler already using such an AST?

Alternatively, I suppose I could use JNI to embed GraalVM in JVM mode. Then I'd use the ToolProvider api to `javac` a passed .java URI, and then execute. One would lose the security benefit of running in Isolates however.

**Comment by mukel** [comment]
We are already working on a Truffle bytecode interpreter for GraalVM. Still an early prototype but it's already able to run `javac` and compile itself.
Fully dynamic Java code e.g. user provided; it's not supported by SVM.

**Comment by guaporocco** [comment]
Awesome! Looking forward to seeing truffleJava. Since substrate VM doesn't support dynamic loading, I'll just use JNI then (or maybe even a Panama project early access 😉 )

**Comment by mukel** [comment]
We generally want to avoid the name TruffleJava because it implies that the Java we are running is somehow different.
The project name is **Espresso** and is just "Java on GraalVM".
