### ISSUE TITLE
SubstrateVM RC10 not available on Maven Central

### ISSUE THREAD

**Issue by ilopmar** [oracle/graal#850]
It seems that substratevm:svm rc10 is not available on Maven Central. I thought that starting with rc8 all artifacts would be available on Central. 
Last version available is rc9: https://search.maven.org/artifact/com.oracle.substratevm/svm/1.0.0-rc9/jar

Has this done on purpose or is it something that you haven't noticed?

**Comment by olpaw** [comment]
Hi @ilopmar,
that's certainly not on purpose. Thanks for reporting!

**Comment by olpaw** [comment]
Hi @ilopmar,
that's certainly not on purpose. Thanks for reporting!

**Comment by ispringer** [comment]
This is not specific to substratevm. rc10 artifacts have not been published for any of the various Graal jars.

**Comment by ilopmar** [comment]
@ispringer I'm sorry but I don't follow you. Does it mean that you're not going to publish rc10 artifacts or that we need to while until you publish all the artifacts?

**Comment by ispringer** [comment]
I don't work for Oracle. I was just pointing out that rc10 artifacts are missing across the boards. Your original post makes it sound like only the substratevm jar is missing.

**Comment by ilopmar** [comment]
Oh, I see. I only missed that artifact because I wanted to try Graal RC10 support in Micronaut.

**Comment by fcurts** [comment]
Can we get some clarity on what's holding this up? Will you ship rc-10 before the holidays?

**Comment by msteindorfer** [comment]
@olpaw @gilles-duboscq I'm also eagerly awaiting RC 10 artifiacts to hit Maven central. Any updates? I'm not understanding what's causing the delay (compared to previous releases).

**Comment by mthmulders** [comment]
I noticed the RC10 bits are available in Maven Central as of today!

**Comment by flortsch** [comment]
Jep, they have been deployed yesterday. Issue can be closed :)
