### ISSUE TITLE
Main entry point class 'HelloWorld.java'  neither found on... on M2

### ISSUE THREAD

**Issue by SimoneGiusso** [oracle/graal#8501]
**Describe the issue**

> Error: Main entry point class 'src/main/java/org/simonegiusso/buildtimeinizialization/HelloWorld.java' neither found on 
> classpath: '/Users/simonegiusso/Dev/GithubProjects/graalvm' nor
> modulepath: '/Users/simonegiusso/.sdkman/candidates/java/21.0.1-graal/lib/svm/graal-microservices.jar:/Users/simonegiusso/.sdkman/candidates/java/21.0.1-graal/lib/svm/library-support.jar'.

When running:

`native-image src/main/java/org/simonegiusso/buildtimeinizialization/HelloWorld.java`

**Steps to reproduce the issue**
Run the above command on this class:

```java
package org.simonegiusso.buildtimeinizialization;

public final class HelloWorld {
    private HelloWorld() {}

    public static void main(final String[] args) {
        Greeter.greet();
    }

    private enum Greeter {
        ;

        static {
            System.out.println("Greeter is getting ready!");
        }

        static void greet() {
            System.out.println("Hello, World!");
        }
    }
}
```

**Describe GraalVM and your environment:**
      Model Name: MacBook Air
      Chip: Apple M2
      Total Number of Cores: 8 (4 performance and 4 efficiency)
      Memory: 16 GB
      System Firmware Version: 10151.81.1
      Operating System: macOS Sonoma 14.3.1

> $java -version
> java version "21.0.1" 2023-10-17
> Java(TM) SE Runtime Environment Oracle GraalVM 21.0.1+12.1 (build 21.0.1+12-jvmci-23.1-b19)
> Java HotSpot(TM) 64-Bit Server VM Oracle GraalVM 21.0.1+12.1 (build 21.0.1+12-jvmci-23.1-b19, mixed mode, sharing)

If I replace `native-image` with `javac` it compiles.

**Comment by meuzame** [comment]
I believe you have to specify a .class file instead an .java file as an argument to native-image
native-image usage is 
``
Usage: native-image [options] class [imagename] [options]
           (to build an image for a class)
   or  native-image [options] -jar jarfile [imagename] [options]
           (to build an image for a jar file)
   or  native-image [options] -m <module>[/<mainclass>] [options]
       native-image [options] --module <module>[/<mainclass>] [options]
           (to build an image for a module)
```

**Comment by SimoneGiusso** [comment]
> So first running javac src/main/java/org/simonegiusso/buildtimeinizialization/HelloWorld.java and then native-image src/main/java/org/simonegiusso/buildtimeinizialization/HelloWorld.class should work

Unfortunately not:

<img width="1421" alt="Screenshot 2024-03-03 at 23 03 44" src="https://github.com/oracle/graal/assets/26305592/704323c1-eca2-4579-8295-8c7245d6e375">

**Comment by fniephaus** [comment]
Hi @SimoneGiusso,
What you would typically do on HotSpot is:
```bash
javac HelloWorld.java
java HelloWorld
```

Note there is no file extension when running `java` because it is referring to the `HelloWorld` call, which contains the static `main` method. It's automatically picked up if you run the command in the directory of the HelloWorld.class file produced by `javac`. `native-image` is designed to be a drop-in replacement, so you would run:
```bash
javac HelloWorld.java
native-image HelloWorld
./helloworld
```
The `native-image` command generates an executable for your HelloWorld app, and `./helloworld` runs it.

Hope this helps!

**Comment by SimoneGiusso** [comment]
> Hope this helps!

@fniephaus Always stuck with the same error:

<img width="1413" alt="Screenshot 2024-03-04 at 09 12 58" src="https://github.com/oracle/graal/assets/26305592/ab82aed7-4871-40cf-b62c-b2ef31ab7414">

**Comment by fniephaus** [comment]
In you example, you actually need to use `-cp src/main/java` due to the directory structure you have set up. My point is still the same though: first, make sure you can run your example on `java`, then replace `java` with `native-image` to generate an executable.
