### ISSUE TITLE
Classes not getting initialized

### ISSUE THREAD

**Issue by anshu-zs** [oracle/graal#8524]
Hi  
I am trying to create native image using this command

```
native-image --no-fallback indeed -H:ReflectionConfigurationFiles=reflection-config.json -H:IncludeResources=logback.xml -H:IncludeResources=version.properties -H:IncludeResources=.env -H:+ReportUnsupportedElementsAtRuntime   -H:Class=examples.http.Main  -jar rocket-examples-0.31.0.jar
```
but I am not able to see some classes as part of native-image when I run the below command
```
strings indeed | sudo grep UndertowHTTPServer
```
I tried to initialize those classes using --initialize-at-build-time and --initialize-at-run-time but still they are not getting initialized. Also the project is too large and has around 100 classes so how can I figure out this:

- which classes are initialized
- which classes I need to initialize
- when to initiailize (at build time or run time)

Thanks!

**Comment by solaanan** [comment]
This issue has already been mentioned in https://github.com/oracle/graal/issues/8474
