### ISSUE TITLE
[GR-52611] Add the ability to add comments to JSON configuration file entries

### ISSUE THREAD

**Issue by zakkak** [oracle/graal#8543]
**Feature request**

Similar to https://github.com/oracle/graal/issues/7482, it would be nice to have the ability to include comments in all the JSON config files.

**Is your feature request related to a problem? Please describe.**

Right now there is no way to include comments justifying the choices made in configuration files.

**Describe the solution you'd like.**

Introduce a new key in the JSON schema to allow the addition of comments per entry.

**Describe who do you think will benefit the most.**

Everyone using the JSON configuration files.

**Describe alternatives you've considered.**

Dump a separate file with justifications.

**Additional context.**

I am planning to augment Quarkus to give the users more information about the reasons that lead to adding each entry in the json configuration files we generate (e.g. which dependency brings it in, which class hierarchy, etc.) and I think adding that info in the configuration file itself would be best.

**Express whether you'd like to help contributing this feature**

Yes.

**Comment by fernando-valdez** [comment]
Created internal ticket: GR-52611

**Comment by fniephaus** [comment]
When I read "comments in JSON", I thought you're asking that we extend our JSON infra to allow actual comments, which would probably be quite messy. Adding an optional `reason` property for every supported entry is probably a good idea. Do you think it should be `reason` or do we need `reasons` which accepts an array of strings?

**Comment by zakkak** [comment]
I believe `reasons` is more appropriate as there might be multiple reasons/comments to have a configuration present, e.g. more than one classes are reflectively accessing the class we are registering, etc.

**Comment by fniephaus** [comment]
Agreed, and `"reasons": ["only one reason"]` is only two chars longer than `"reason": "only one reason"`. :wink:

**Comment by fniephaus** [comment]
@zakkak I assume you are working on this? We just need to extend the schema files, right?

**Comment by zakkak** [comment]
> @zakkak I assume you are working on this?

Not yet. Now that I have your ACK, I will probably get to it in late March or early May.

> We just need to extend the schema files, right?

Yes, that's my understanding, plus some documentation probably.

**Comment by zakkak** [comment]
WIP PR #9048
