### ISSUE TITLE
--module-path directory: Modules Not Added

### ISSUE THREAD

**Issue by PeteSL** [oracle/graal#8544]
I am trying to create a native image of an application that is currently running with the GraalVM JVM with the following command line arguments in a text file (Windows 10 64 bit latest, up-to-date, GraalVM 21.0.2 Enterprise, VS 2022 Pro up-to-date).
--add-modules java.sql,ALL-MODULE-PATH
-p lib
-m myapp.main

All jars in the lib subdirectory are Java 8 jars with Java 11 multi-release module-info.class and one has a Java 21 class file (to use virtual threading).  The issue is I get the 'mainclass is not found' and in verbose mode, it doesn't look like the module-path is being modified or looked at. (-imagemp does not include the jar files in the lib folder).  I see the add-modules line in the verbose mode and the references to myapp.main but I don't see any references to the lib subdirectory (running in the app directory where lib is a direct subdirectory).

**Comment by hamzaGhaissi** [comment]
Hi can you please share a small reproducer of this issue ?

**Comment by PeteSL** [comment]
I have switched to testing in Linux (due to G1 GC need) and have reproduced with a significant subset of jars (3) from the original. the end of the native-image line using module path is -p lib -m myapp.main (the jars do not show in imagemp or anywhere else).
`Error: Module myapp.main for mainclass not found.
com.oracle.svm.driver.NativeImage$NativeImageError
        at org.graalvm.nativeimage.driver/com.oracle.svm.driver.NativeImage.showError(NativeImage.java:2337)
        at org.graalvm.nativeimage.driver/com.oracle.svm.driver.NativeImage.build(NativeImage.java:1914)
        at org.graalvm.nativeimage.driver/com.oracle.svm.driver.NativeImage.performBuild(NativeImage.java:1873)
        at org.graalvm.nativeimage.driver/com.oracle.svm.driver.NativeImage.main(NativeImage.java:1847)
        at java.base@21.0.2/java.lang.invoke.LambdaForm$DMH/sa346b79c.invokeStaticInit(LambdaForm$DMH)`
When run with -cp 'lib/*' myapp.SrvrMain, the jars are added to -imagecp and it compiles correctly.  Note that myapp.main is a module name and myapp.SrvrMain is a class in the same jar.  Note also the syntax for --module-path/-p is correct and works with any JVM (different from -cp syntax which requires quotes and the /* to denote a folder).  If I add each jar with colon separation, the modules compile (but since I use ServiceLoader, it doesn't run; -cp ServiceLoader works but that is a different issue already on record).

**Comment by hamzaGhaissi** [comment]
Can also share the source code of the app you are running or reproducer ?

**Comment by PeteSL** [comment]
Any multi-module (multi-jar) application will recreate the issue  Simply place the jars in a subdirectory, set the -p to point to that subdirectory (if the subdirectory is named lib, for instance, the -p would look like -p lib), set the -m to be the module containing a main class, and run native-image.  It will fail because it is not going into the subdirectory to find jar files.  When run using Java, it runs fine since that is the way you are supposed to do it with a JVM.

**Comment by Thihup** [comment]
https://github.com/oracle/graal/issues/7271
