### ISSUE TITLE
JVM crash, MacOS

### ISSUE THREAD

**Issue by michbarsinai** [oracle/graal#856]
Running NetBeans on GraalVM rc9. MacOS 10.14.1, MacBookPro. The application lived through a few laptop sleep/wakeup cycles (might have had an effect, not sure).

[graal-no-crash.log](https://github.com/oracle/graal/files/2667446/graal-no-crash.log)

**Comment by gilles-duboscq** [comment]
Hi @michbarsinai, thank you for the bug report.
This looks to me like [JDK-8152683](https://bugs.openjdk.java.net/browse/JDK-8152683) which was fixed in 9 but unfortunately not backported to 8.

**Comment by wirthi** [comment]
Closing this old ticket, as Gilles mentioned this is resolved in newer versions.
