### ISSUE TITLE
SVM Native to Java calls don't retrieve methods on superclasses

### ISSUE THREAD

**Issue by johanvos** [oracle/graal#858]
If class Foo extends Bar, and Bar defines 
`public void bar()
`
a call in native code similar to
`env->GetMethodId(barClass, "bar", "()V");`
should return the method, but it doesn't (even when both Foo and Bar are declared in a jni configuration file).
When asking the method on the superclass explicitly, it works.

**Comment by cstancu** [comment]
I'll close this as the original issue has been fixed. The fix will be part of RC13.
