### ISSUE TITLE
Random deadlocks when creating new context

### ISSUE THREAD

**Issue by monobrov1234** [oracle/graal#8618]
**Describe GraalVM and your environment :**
 - GraalVM version or commit id if built from source: **21.0.2+13.1**
 - CE or EE: **EE**
 - JDK version: **JDK21**
 - OS and OS Version: **Ubuntu 22.04, Windows 11**
 - Architecture: **amd64**
 - The output of `java -Xinternalversion`: 
```
 Java HotSpot(TM) 64-Bit Server VM (21.0.2+13-LTS-jvmci-23.1-b30) for linux-amd64 JRE (21.0.2+13-LTS-jvmci-23.1-b30), built on 2024-01-06T13:26:26Z by "buildslave" with gcc 11.2.0
```

**Have you verified this issue still happens when using the latest snapshot?**
No

**Describe the issue**
I have a game server where players can write scripts (UNTRUSTED policy), each player has his own Context, when eval error occurs then Context is recreated, when player leaves it is closed, all actions with all contexts happen in single thread.

Sometimes deadlock happens when calling Context.newBuilder.build() (the thread just stops on build()), I can't understand why it happens, just at random moments, I tried testing by calling build() many times but everything is fine

I tried on ubuntu and on windows, same issue

**Code snippet or code repository that reproduces the issue**
none

**Steps to reproduce the issue**
none

**Expected behavior**
Not deadlock randomly on context creation

**Additional context**
Add any other context about the problem here. Specially important are stack traces or log output. Feel free to link to gists or to screenshots if necesary
<details><summary>Details</summary>
Stack in profiler:

```
pool-15-thread-1  Runnable CPU usage on sample: 999ms
  com.oracle.truffle.polyglot.enterprise.EnterprisePolyglotImpl.tearDownIsolate(Native Method)
  com.oracle.truffle.polyglot.enterprise.EnterprisePolyglotImpl.tearDownIsolate(stripped:796)
  com.oracle.truffle.polyglot.enterprise.PolyglotJNIConfig$$Lambda.0x00007f96606eb650.applyAsLong()
  org.graalvm.nativebridge.JNIConfig.shutDownIsolate(JNIConfig.java:156)
  org.graalvm.nativebridge.NativeIsolate.doIsolateShutdown(NativeIsolate.java:266)
  org.graalvm.nativebridge.NativeIsolate.shutdown(NativeIsolate.java:167)
  com.oracle.truffle.polyglot.enterprise.EnterprisePolyglotImpl$EngineCleanUpReference.run(stripped:999)
  com.oracle.truffle.polyglot.enterprise.CleanableWeakReference.clean(stripped:45)
  com.oracle.truffle.polyglot.enterprise.CleanableWeakReference.<init>(stripped:26)
  com.oracle.truffle.polyglot.enterprise.EnterprisePolyglotImpl$EngineCleanUpReference.<init>(stripped:992)
  com.oracle.truffle.polyglot.enterprise.EnterprisePolyglotImpl$Lazy.registerEngine(stripped:836)
  com.oracle.truffle.polyglot.enterprise.EnterprisePolyglotImpl.spawnIsolatedEngine(stripped:370)
  com.oracle.truffle.polyglot.enterprise.EnterprisePolyglotImpl.buildEngine(stripped:154)
  org.graalvm.polyglot.Engine$Builder.build(Engine.java:756)
  org.graalvm.polyglot.Context$Builder.build(Context.java:1925)
  ...
  ```

![image](https://github.com/oracle/graal/assets/79697582/d9cd01af-044f-4d5e-9307-8d1890636d29)

Context creation:
```java
Context.newBuilder("js")
            .sandbox(SandboxPolicy.UNTRUSTED)
            .in(InputStream.nullInputStream())
            .out(OutputStream.nullOutputStream())
            .err(OutputStream.nullOutputStream())
            .allowHostAccess(HostAccess.UNTRUSTED)
            .option("engine.MaxIsolateMemory", "32MB")
            .option("sandbox.MaxHeapMemory", "32MB")
            .option("sandbox.MaxCPUTime", "25ms")
            .option("sandbox.MaxCPUTimeCheckInterval", "5ms")
            .option("sandbox.MaxStatements", "100")
            .option("sandbox.MaxStackFrames", "5")
            .option("sandbox.MaxThreads", "1")
            .option("sandbox.MaxASTDepth", "16")
            .option("sandbox.MaxOutputStreamSize", "0B")
            .option("sandbox.MaxErrorStreamSize", "0B")
            .build()
```
</details>

Please, if it's not a bug, explain what I'm doing wrong.

**Comment by fernando-valdez** [comment]
Hi @JustNanix, is it possible to share any error log or any additional information on this?
Also, can you provide a reproducer? it doesn't need to be the whole project, just the minimal code required to get the error.
