### ISSUE TITLE
Graal JIT startup

### ISSUE THREAD

**Issue by stefan-reich** [oracle/graal#862]
I have a question about how the Graal JIT works when I enable it in JDK 11. You keep the bytecode interpreter and replace C1+C2 with Graal, is that correct?

So when the program starts, everything is interpreted, including Graal. Then, Graal goes to work and compiles both parts of itself AND of the application to machine code.

I initially thought that Graal should always be compiled AOT to improve startup times as a JIT is probably a sizable piece of code  - but maybe it's not actually necessary?

It's so amazing - a JIT compiling itself during runtime.

Cheers

**Comment by shelajev** [comment]
Graal replaces C2 as the top tier compiler. The bytecode interpreter and C1 are still used, and Graal is compiled by C1 initially. 

We're working on compiling Graal ahead of time as a native library to improve startup, but it requires changes to JVMCI and is not currently available yet.

**Comment by stefan-reich** [comment]
Gotcha. That should make startup very acceptable I guess. C1 used to be all we had back in the days :D

In fact, I just tried starting a sizable desktop program (my Java "OS") which is a wildly unscientific test as it also does network accesses... but the gist is you don't even notice whether Graal is used or not (33 vs 35 seconds total startup time with many modules in the latest test).

BTW, are these the right options for JDK 11?

`-XX:+UnlockExperimentalVMOptions -XX:+EnableJVMCI -XX:+UseJVMCICompiler`

Is the middle one still needed?

**Comment by dougxc** [comment]
`-XX:+UseJVMCICompiler` [implies](https://github.com/AdoptOpenJDK/openjdk-jdk/blob/dev/src/hotspot/share/jvmci/jvmci_globals.cpp#L81) `-XX:+EnableJVMCI`.

**Comment by stefan-reich** [comment]
Thanks.
