### ISSUE TITLE
Graal JIT stability in JDK 11

### ISSUE THREAD

**Issue by stefan-reich** [oracle/graal#863]
Hi,

I'd like to get a quick statement about the end-user-readiness of the Graal JIT as shipped in JDK 11, specifically for all 3 platforms (Linux/Windows/Mac). Would you say it is stable enough to activate, or should we expect crashes/bugs? (Ignore the speed question for a moment.)

Thanks

**Comment by dougxc** [comment]
The Graal JIT is being used by default in the GraalVM binaries and has not revealed any serious issues. That said, the Graal JIT in JDK 11 is a snapshot of Graal from a while ago. However, it should definitely be stable enough for most workloads so I recommend trying it out and reporting any issues you find here.

**Comment by stefan-reich** [comment]
Thank you, that's helpful.
