### ISSUE TITLE
Graal JIT: Number of optimizations vs C2

### ISSUE THREAD

**Issue by stefan-reich** [oracle/graal#864]
Another quick question... roughly how many optimizations are implemented in the Graal JIT vs C2? Is it in the same ballpark? I understand that these compilers are not identical, so results will definitely vary. I'm mainly asking whether some major tricks that C2 has up its sleeves are unimplemented in Graal.

As I recall, people have also reported cases where Graal already outperforms C2.

**Comment by shelajev** [comment]
Graal Community Edition (CE) is comparable to C2. Graal Enterprise Edition (as found in GraalVM EE on [OTN](https://www.oracle.com/technetwork/oracle-labs/program-languages/downloads/index.html)) includes more sophisticated optimisations such as better partial escape analysis and an advanced inlining algorithm that shows noticeable improvements on modern workloads. For further information, check out [this page](http://www.graalvm.org/docs/why-graal/).

**Comment by christhalinger** [comment]
I'm an advocate of Graal for a very long time now and it provides us with much better performance but it's important to note that Graal CE is missing loop-vectorization. But it's pretty much the only (big) thing that C2 has and Graal doesn't.

**Comment by stefan-reich** [comment]
> provides us with much better performance

How much more (just very roughly)? Does this also hold for Graal CE?

**Comment by shelajev** [comment]
One should evaluate it on their code and their workloads. It heavily depends on the tech stack, abstractions used, etc. Here's for example an article about some benchmarks on the [Stream API performance](https://medium.com/graalvm/stream-api-performance-with-graalvm-be6cfe7fbb52), or [Scala code](https://medium.com/graalvm/compiling-scala-faster-with-graalvm-86c5c0857fa3). 

Internally, we run a large body of benchmarks, but reporting a single number (or even a few) is at best somewhat useless and at worst can be misleading. Like an average temperature in a hospital. 

CE is in general on par with HotSpot, but more sensitive to the workload at hands. Twitter for example is using the open source version of the Graal compiler for their Scala microservices and reports improving throughtput and having noticeably fewer GC cycles. But one should definitely evaluate the performance impact for their codebase. EE is faster than CE.

**Comment by stefan-reich** [comment]
![Scala benchmark)(https://cdn-images-1.medium.com/max/800/1*apLyGpJw_Up5IYrLrNGXHg.png)

Ah... that's all I wanted. I totally agree that the world is more complex than a few numbers. Thanks.

**Comment by christhalinger** [comment]
What @shelajev said. And this: https://youtu.be/PtgKmzgIh4c?t=1338

**Comment by plokhotnyuk** [comment]
@stefan-reich in most cases GraalVM CE/EE provides better throughput in single thread benchmarks, but there are number of cases when C2 outperform it in 2x-4x times.

Please see results of benchmarks for JSON parsing and serialization in Scala on different JDK/JIT:
https://plokhotnyuk.github.io/jsoniter-scala/

Some spotted pref. regressions were reported here:
https://github.com/oracle/graal/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+plokhotnyuk
