### ISSUE TITLE
EconomicMap does not come with @TruffleBoundaries

### ISSUE THREAD

**Issue by fniephaus** [oracle/graal#869]
Truffle provides `EconomicMap` (see [EconomicMapImpl.java](https://github.com/oracle/graal/blob/c5c5934e912166b712a8802374ff3479452e3ac5/sdk/src/org.graalvm.collections/src/org/graalvm/collections/EconomicMapImpl.java)). Unfortunately, its methods are not marked as TruffleBoundaries which they should be as the implementation is highly recursive at some points. Marking appropriate methods as `@TruffleBoundary` would make the map much more usable for language implementers.

**Comment by chumer** [comment]
Rule of thumb is to use TruffleBoundaries in nodes only. If you call into external libraries use a boundary in the node. Spamming TruffleBoundaries to libraries is something that is discouraged.

Besides, we cannot mark them using TruffleBoundary as the Graal SDK has no dependency on Truffle.

**Comment by fniephaus** [comment]
Thanks, that makes sense.
