### ISSUE TITLE
When to use CompilerDirectives#castExact?

### ISSUE THREAD

**Issue by fniephaus** [oracle/graal#870]
[CompilerDirectives#castExact](https://github.com/oracle/graal/blob/c5c5934e912166b712a8802374ff3479452e3ac5/truffle/src/com.oracle.truffle.api/src/com/oracle/truffle/api/CompilerDirectives.java#L337-L357)'s Javadoc does not explain when to use the annotation.

**Comment by smarr** [comment]
Yeah, I also noticed that.
Would be great if the JavaDoc could provide a bit more guidance on the use cases.
