### ISSUE TITLE
Increased cpu usage and latency after migrating to GraalVM

### ISSUE THREAD

**Issue by DigitalMediageek** [oracle/graal#8703]
**Describe the issue**
When migrating from Java VM 17 to GraalVM 22, we experience higher cpu usage and higher latencies in our spring boot microservice

**Steps to reproduce the issue**
Unfortunately, I cannot provide steps to reproduce, right now.

**Describe GraalVM and your environment:**
 - GraalVM 22
 - JDK major version: **build 22+36-jvmci-b02**
 - OS: **ubuntu/latest** on kubernetes
 - Architecture: **AMD64**

**More details**
Spring boot latency increased by almost 100%. We tried to fix this by profiling the service with --pgo-instrument and rebuild it with --pgo=service.iprof. However, performance optimization can be observed for abount 20 minutes only. Afterwards there is an increase of cpu usage and latency, again. See attached chart. Is there another way to get better results?

![image](https://github.com/oracle/graal/assets/29650701/8bd59270-cf1f-4dfb-9720-0f6ba454c6c4)
![image](https://github.com/oracle/graal/assets/29650701/ce0332e7-dbb9-4815-b7b0-e2bd13231c7b)

**Comment by SergejIsbrecht** [comment]
> Afterwards there is an increase of cpu usage and latency

Did you profile what is running on CPU? I would probably build the native-image with enabled FramePointer and use Perf to sample some stacks while it is running "OK" and when it is getting worse. Do you have GC logs enabled? When the application is running OK and later on gets worse, there might be something going on in the VM, most likely the GC (e.g. leaking objects -> Full GC). You have to remember the G1 GC is implemented differently in the GraalVM native-image, than in OpenJDK (17). Are you actually using the G1 GC in the OpenJDK 17 version?

**Comment by DigitalMediageek** [comment]
Thanks for your response. I'll try playing around with GC options.

**Comment by oubidar-Abderrahim** [comment]
Please share the GC logs or a JFR of the application so that we can take a look at it. Thank you

**Comment by DigitalMediageek** [comment]
Thanks to @SergejIsbrecht , I've tried compiling native image with `--gc=G1`. The result is very much better, which you can see after the deployment at 12:30 in the below chart:
![image](https://github.com/oracle/graal/assets/29650701/8489fa49-21c0-4787-a795-00656b2a2380)
This is suggested in "Optimizations and Performance", too:
"The G1 GC is a multi-threaded GC that is optimized to reduce stop-the-world pauses and therefore improve latency, while achieving high throughput. To enable it, pass the option --gc=G1 to the native-image builder. Currently, G1 Garbage Collector can be used with Native Image on the Linux AMD64 and AArch64 architectures. (Not available in GraalVM Community Edition.)"
Unfortunately I didn't came across this part, earlier.
