### ISSUE TITLE
 [GR-53340] The documentation uses the `libz-dev` package which does not exist under Ubuntu 22.04.4

### ISSUE THREAD

**Issue by linghengqian** [oracle/graal#8723]
**Feature request**

Please include the following information:

**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. E.g. I'm always frustrated when [...]

- No.
- The documentation uses the `libz-dev` package which does not exist under Ubuntu 22.04.4. Refer to https://www.graalvm.org/jdk21/reference-manual/native-image/#prerequisites .
```shell
On Oracle Linux use the YUM package manager:

$ sudo yum install gcc glibc-devel zlib-devel

Some Linux distributions may additionally require libstdc++-static.
You can install libstdc++-static if the optional repositories are enabled (_ol7_optional_latest_ on Oracle Linux 7 and _ol8_codeready_builder_ on Oracle Linux 8).

On  Ubuntu Linux use the `apt-get` package manager:

$ sudo apt-get install build-essential libz-dev zlib1g-dev

On other Linux distributions use the DNF package manager:

$ sudo dnf install gcc glibc-devel zlib-devel libstdc++-static
```
- Further confirmed at https://packages.ubuntu.com/search?lang=sv&suite=jammy&searchon=names&keywords=libz-dev . `libz-dev` also does not exist on Ubuntu 24.04.

**Describe the solution you'd like.**

- Removed reference to `libz-dev` in documentation. Or indicate that it's on a more specific Linux distribution?

**Describe who do you think will benefit the most.**
GraalVM users, GraalVM contributors, developers of libraries and frameworks which depend on GraalVM, or somebody else?

- GraalVM users.

**Describe alternatives you've considered.**

- Null.

**Additional context.**
Add any other context about the feature request here.
For example, link to the relevant projects, documentation, standards.

- This is reflected in an Info Log under Ubuntu 22.04.4.
```shell
linghengqian@DESKTOP-TOORFNG:/tmp$ sudo apt-get install build-essential libz-dev zlib1g-dev
正在读取软件包列表... 完成
正在分析软件包的依赖关系树... 完成
正在读取状态信息... 完成
注意，选中 'zlib1g-dev' 而非 'libz-dev'
build-essential 已经是最新版 (12.9ubuntu3)。
zlib1g-dev 已经是最新版 (1:1.2.11.dfsg-2ubuntu9.2)。
zlib1g-dev 已设置为手动安装。
升级了 0 个软件包，新安装了 0 个软件包，要卸载 0 个软件包，有 0 个软件包未被升级。
```

**Express whether you'd like to help contributing this feature**
If you'd like to contribute, please read the [contribution guide](https://www.graalvm.org/community/contributors/).

- `libz-dev` seems to be a legacy issue, I'm not sure which Linux distributions have this deb package.

**Comment by olyagpl** [comment]
Thank you for reporting this. Native Image Linux prerequisites were updated accordingly: 
https://www.graalvm.org/latest/reference-manual/native-image/#prerequisites
