### ISSUE TITLE
[INTEROP] LANGUAGE message

### ISSUE THREAD

**Issue by fniephaus** [oracle/graal#874]
When working with the interop API, one currently needs to send the `KEYS` message to a foreign object to get a list of identifiers that can then be sent to the object.

Let's say we want to retrieve the string representation of a foreign object. For this, we'd need to check which message for its string representation the foreign object understands. But replying on the result of `KEYS` might lead to name clash problems (imagine a Ruby object that happens to understand Python's `__str__`).

If we had an option to query the language ID of a foreign object, it would be possible to select the correct string representation message immediately (`python` -> `__str__`, `ruby` -> `to_s`, ...). On the other hand, language IDs are already "leaking" into "user space" as they are needed when evaluating code via the Polyglot API (e.g. `polyglot.eval(language="js", string="1 + 2")`). Therefore, I believe it makes sense to add a new `LANGUAGE` message to ask Truffle objects for their language ID.

**Comment by boris-spas** [comment]
Tracking internally as Issue GR-20797.

**Comment by fniephaus** [comment]
Fixed in https://github.com/oracle/graal/commit/0a8b3a3885ecb4399cff889b143265eabb271a12.
