### ISSUE TITLE
[GR-53444] Typo in error message "java.lang.AssertionError: Expected number of params 2, actual 2"

### ISSUE THREAD

**Issue by illarionov** [oracle/graal#8765]
**Describe the issue**

When executing a WASM function passing an incorrect number of arguments, the assertion is triggered with the following error message:
```
java.lang.AssertionError: Expected number of params 2, actual 2
org.graalvm.polyglot.PolyglotException: java.lang.AssertionError: Expected number of params 2, actual 2
	at org.graalvm.wasm.nodes.WasmRootNode.moveArgumentsToLocals(WasmRootNode.java:243)
	at org.graalvm.wasm.nodes.WasmRootNode.executeWithContext(WasmRootNode.java:160)
	at org.graalvm.wasm.nodes.WasmRootNode.execute(WasmRootNode.java:144)
	at <wasm> sqlite3__wasm_config_i(Unknown)
	at org.graalvm.polyglot.Value.execute(Value.java:930)
```

The "actual" number of arguments in this message should be 1 and not 2.

This is a typo on the line 
https://github.com/oracle/graal/blob/62b2745925ae06ae3deb4a0e8199fe4b004b48d4/wasm/src/org.graalvm.wasm/src/org/graalvm/wasm/nodes/WasmRootNode.java#L251 (`args.length` should be replaced with `WasmArguments.getArgumentCount(args)`).

**Describe GraalVM and your environment:**
 - GraalVM version 24.0.0
 - JDK major version: 21
 - OS: Linux
 - Architecture: AMD64

**Comment by selhagani** [comment]
Hi @illarionov, thank you for sharing this with us.

I will share this with our dev team and we'll keep you updated.
