### ISSUE TITLE
Current state of iOS platform is not clear

### ISSUE THREAD

**Issue by piiertho** [oracle/graal#8776]
**Describe the issue**
I am working on [godot-kotlin](https://github.com/utopia-rise/godot-kotlin-jvm), a JVM language binding for godot engine.  
Currently we're using graalvm native-image in order to provide iOS support.  
This works with `graalvm-ce-java17-22.1.0`, but we have to rely on gluon's work to get static java libraries and cap cache.  
When upgrading to `graalvm-23.0.3-jdk-17.0.10+11.1` I got troubles as it now miss a cap cache value:  
```
Missing CAP cache value for: NativeCodeInfo:PosixDirectives:ConstantInfo:CLOCK_REALTIME
```
So we'll have to wait for gluon to provide cap cache in order to update graalvm.  
Also I don't know from where static java libraries gluon provide are built.  

This makes me think this is dangerous to use graalvm to provide iOS support as currently we have to rely on gluon's work, and process to get cap cache and jvm static library is pretty opaque.  

On another side, we already succeded to build and run games written in JVM languages using native-image.  
My questions are pretty simple: 
Can we expect a support for native-image iOS platform without having to reverse engineer gluon's work ?
Is there any documentation to understand how to use native-image for iOS ?  

I think iOS support out of the box would be a great game changer, as this would be the best way to provide JVM support with complete features for this platform.

**Comment by solaanan** [comment]
Hello @piiertho, thanks for reaching out!  Unfortunately, we support iOS platform and we currently do not have any plans to support it in the near future. As a result, there is no official documentation available about it at this time.

**Comment by solaanan** [comment]
Hello @piiertho, the labs-openjdk static libs that we provide are living here:
for JDK 23 : [https://github.com/graalvm/labs-openjdk/releases](https://github.com/graalvm/labs-openjdk/releases)
For JDK 22 : [https://github.com/graalvm/labs-openjdk-22/releases](https://github.com/graalvm/labs-openjdk-22/releases)

**Comment by piiertho** [comment]
> Hello @piiertho, the labs-openjdk static libs that we provide are living here:
> 
> * For JDK 23 : https://github.com/graalvm/labs-openjdk/releases
> * For JDK 22 : https://github.com/graalvm/labs-openjdk-22/releases

Thanks a lot ! Will try with them.
May I ask same question for svm static lib ?

**Comment by davidgiga1993** [comment]
> Hello [@piiertho](https://github.com/piiertho), thanks for reaching out! Unfortunately, we don't support iOS platform and we currently do not have any plans to support it in the near future. As a result, there is no official documentation available about it at this time.

@solaanan 
Do you mind providing any details on why exactly? As it seems getting compatibility with iOS isn't too far away given that there are ways to do this already (although very undocumented and with a lot of guesswork involved)?

I would also happy to sponsor this in some form

**Comment by piiertho** [comment]
> > Hello [@piiertho](https://github.com/piiertho), thanks for reaching out! Unfortunately, we don't support iOS platform and we currently do not have any plans to support it in the near future. As a result, there is no official documentation available about it at this time.
> 
> @solaanan 
> Do you mind providing any details on why exactly? As it seems getting compatibility with iOS isn't too far away given that there are ways to do this already (although very undocumented and with a lot of guesswork involved)?
> 
> I would also happy to sponsor this in some form

Indeed that's not too far here is a repo we have for Godot kotlin to provide iOS support: https://github.com/utopia-rise/ios-graal-jdk-21
I'd really like it to be officially supported by oracle. This is currently one of the pain point for JVM.
