### ISSUE TITLE
[GR-53595] Segmentation fault in jvmci JIT method call

### ISSUE THREAD

**Issue by vlofgren** [oracle/graal#8813]
**Describe the issue**

I've gotten a segmentation fault from a JIT method call in the marginalia search crawler.  See the hs_err_pid...log below.  

```#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f43978c87f8, pid=10346, tid=11686
#
# JRE version: Java(TM) SE Runtime Environment Oracle GraalVM 22+36.1 (22.0+36) (build 22+36-jvmci-b02)
# Java VM: Java HotSpot(TM) 64-Bit Server VM Oracle GraalVM 22+36.1 (22+36-jvmci-b02, mixed mode, tiered, jvmci, jvmci compiler, compressed class ptrs, g1 gc, linux-amd64)
# Problematic frame:
# J 17625 jvmci okhttp3.internal.http2.Hpack$Reader.evictToRecoverBytes(I)I (141 bytes) @ 0x00007f43978c87f8 [0x00007f43978c8720+0x00000000000000d8]

...
Current thread (0x00007f1fbc0f8810):  JavaThread "OkHttp senr.osu.edu" daemon [_thread_in_Java, id=11686, stack(0x00007f2001645000,0x00007f2001745000) (1024K)]

Stack: [0x00007f2001645000,0x00007f2001745000],  sp=0x00007f2001743360,  free space=1016k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)

J 17625 jvmci okhttp3.internal.http2.Hpack$Reader.evictToRecoverBytes(I)I (141 bytes) @ 0x00007f43978c87f8 [0x00007f43978c8720+0x00000000000000d8]
J 22066 jvmci okhttp3.internal.http2.Hpack$Reader.readHeaders()V (216 bytes) @ 0x00007f4398705a08 [0x00007f43987056c0+0x0000000000000348]
J 22171 jvmci okhttp3.internal.http2.Http2Reader.readHeaders(Lokhttp3/internal/http2/Http2Reader$Handler;III)V (116 bytes) @ 0x00007f439877a240 [0x00007f439877a180+0x00000000000000c0]
J 23970 jvmci okhttp3.internal.http2.Http2Reader.nextFrame(ZLokhttp3/internal/http2/Http2Reader$Handler;)Z (350 bytes) @ 0x00007f4397816d10 [0x00007f4397816a40+0x00000000000002d0]
J 17753 c1 okhttp3.internal.http2.Http2Connection$ReaderRunnable.invoke()V (133 bytes) @ 0x00007f43905aa42c [0x00007f43905aa300+0x000000000000012c]
J 12600 c1 okhttp3.internal.http2.Http2Connection$ReaderRunnable.invoke()Ljava/lang/Object; (8 bytes) @ 0x00007f438f5bac04 [0x00007f438f5baba0+0x0000000000000064]
```

The crashing method appears to be [this one](https://github.com/square/okhttp/blob/d0d75578228c5530b5c4ad5b3370d08d7bbeb401/okhttp/src/main/kotlin/okhttp3/internal/http2/Hpack.kt#L171), in the okhttp sources.

**Steps to reproduce the issue**

Steps to reproduce are not known.  This happened after running the crawler for several hours in production.   Since it's a kotlin method and not a native call, it's at least a solid guess that it's JVM related.

**Describe GraalVM and your environment:**
 - GraalVM version: **Oracle GraalVM 22+36.1 (22.0+36) (build 22+36-jvmci-b02)**
 - JDK major version: **22**
 - OS: **Linux (Debian 12)**
 - Architecture: **AMD64**

**More details**

[hs_err_pid10346.log](https://github.com/oracle/graal/files/15067243/hs_err_pid10346.log)

A 75 GB core dump was extracted as well, although I cannot attach it to the git issue due to it's size.

**Comment by vlofgren** [comment]
Interestingly, with openjdk, I run into this issue running the crawler: https://bugs.openjdk.org/browse/JDK-8329528

It's not clear to me it's the same issue, but I guess it could be related in some way so I'm sharing it still.

**Comment by fernando-valdez** [comment]
Thanks for reporting this issue. I will take a look at it.
Internal ticket created: GR-53595

**Comment by davleopo** [comment]
@vlofgren  thanks for your report again. 

This is indeed the same as https://bugs.openjdk.org/browse/JDK-8329528 it just fails at another point in time. You can see from the hs_err that there are fields like dynamicTable which are of type FillerArray. Those filler arrays are only used by the gc and the compiled code should never see them. 

Closing this as it is not a GraalVM bug.
