### ISSUE TITLE
[Truffle][NFI] Related DLL Could not be loaded with Specified Module could not be found

### ISSUE THREAD

**Issue by Terrency** [oracle/graal#8834]
**Describe GraalVM and your environment :**
 - GraalVM version or commit id if built from source: **[22.0&21.0.2]**
 - CE or EE: **[CE]**
 - JDK version: **[JDK8]**
 - OS and OS Version: **[Windows 11]**
 - Architecture: **[amd64]**
 - The output of `java -Xinternalversion`:
```
 **Java HotSpot(TM) 64-Bit Server VM (22+36-jvmci-b02) for windows-amd64 JRE (22+36-jvmci-b02), built on 2024-02-25T19:00:14Z by "OCIWIN21Buildbot" with MS VC++ 17.6 (VS2022)**
```

**Have you verified this issue still happens when using the latest snapshot?**
You can find snapshot builds here: https://github.com/graalvm/graalvm-ce-dev-builds/releases

**Describe the issue**
I am trying to use NFI loader for a DLL file on windows with folling nfiSource:
load 'F:\\liblapack.dll'
liblapack file reference libblas.dll\libgcc_s_seh_64-1.dll\libgfortran_64-3.dll\msvcrt.dll, all files on the same folder with liblapack.dll, but it shows The specified module could not be found. 
I have try to use LOAD_LIBRARY_SEARCH_DLL_LOAD_DIR flag in lookup_win32.c file as Oracle engine said, still not work.
Simple Test project: https://github.com/Terrency/graalvm-test-projects.

**Code snippet or code repository that reproduces the issue**
```
**https://github.com/Terrency/graalvm-test-projects**
```

**Steps to reproduce the issue**
Please include both build steps as well as run steps
1. run simple project nfi-test/src/main/java/org.example/Main.main

**Expected behavior**
success load dll file.

**Comment by fernando-valdez** [comment]
Can you provide the exact error message you receive when attempting to load the DLL, including any stack traces? Also, have you modified the Java library path to include the directory where the DLLs reside?

**Comment by Terrency** [comment]
Hi Fernando,

I've resolved the issue with Roland. It pertains to the default search path for the win32 loadLibrary flag without a loader path. After changing the flag to LOAD_LIBRARY_SEARCH_DLL_LOAD_DIR || LOAD_LIBRARY_SEARCH_SYSTEM32, the DLL can be loaded. This DLL references some local DLLs and system32 DLLs. Therefore, we need to ensure that these flags are utilized by the Java side or set them as default.

**Comment by fernando-valdez** [comment]
I am glad the issue was solved!
