### ISSUE TITLE
GraalJS should support Ahead-of-Time(AOT) compilation to Native binary like GraalPy.

### ISSUE THREAD

**Issue by Foxchandaisuki** [oracle/graal#8850]
[GraalPy](https://github.com/oracle/graalpython), which is Python implication of the [GraalVM](https://github.com/oracle/graal), [supports AOT compilation to Native binary.](https://www.graalvm.org/jdk22/reference-manual/python/Python-Runtime/#)
> GraalPy is compiled ahead-of-time to a native executable.
> This means that you do not need a JVM to run GraalPy and it is compact in size.

In time of now, most of main implications of Python and JavaScript do NOT support AOT compilation.

For example, [NodeJS](https://github.com/nodejs/node) , [Deno](https://github.com/denoland/deno), and even [Bun](https://github.com/oven-sh/bun) only supports Just-in-Time(JIT) compilation and they have no plan to support AOT.

However, the case of [GraalPy](https://github.com/oracle/graalpython) shows us that making Script language to be compiled to Native binary is technically possible. And already there is an AOT compiler for Javascript like [ChowJS](https://mp2.dk/techblog/chowjs/), but unfortunately it is a closed source, and maybe a project NOT free of charge.

[Static Hermes](https://www.react-native.eu/talks/tzvetan-mikov-static-hermes-the-next-generation-of-hermes), which is being developed by Meta shows us that AOT compiling of JavaScript could be a killer feature of the project.

**Comment by sgammon** [comment]
It's not quite AOT, but:

- [NodeJS supports standalone executables](https://nodejs.org/api/single-executable-applications.html)
- [Deno supports standalone executables](https://docs.deno.com/runtime/manual/tools/compiler)
- [Bun supports standalone executables](https://bun.sh/docs/bundler/executables)

GraalJs does support AOT, in the sense that you can use GraalJs in a `native-image`, using Truffle's SVM implementation. We do this with GraalJs, GraalPython, and TruffleRuby, all quite effectively.

**Comment by fniephaus** [comment]
Thanks for the feature request, @Foxchandaisuki. I'm guessing you would like to see something similar to [GraalPy's standalone application feature](https://www.graalvm.org/latest/reference-manual/python/standalone-applications/) for Graal.js? Is that correct?

As @sgammon already pointed out: Graal.js it self can already be AOT-compiled and a `js` as well as a `node` distribution of Graal.js is what we release on GitHub, see for example: https://github.com/oracle/graaljs/releases/latest. Graal.js Maven artifacts are published on Maven central.

**Comment by Foxchandaisuki** [comment]
@fniephaus 
> I'm guessing you would like to see something similar to [GraalPy's standalone application feature](https://www.graalvm.org/latest/reference-manual/python/standalone-applications/) for Graal.js? Is that correct?

That's correct.

I hope GraalJS was a something like Kotlin/Native for JavaScript.

**Comment by tarsa** [comment]
> [GraalPy](https://github.com/oracle/graalpython), which is Python implication of the [GraalVM](https://github.com/oracle/graal), [supports AOT compilation to Native binary.](https://www.graalvm.org/jdk22/reference-manual/python/Python-Runtime/#)
> 
> > GraalPy is compiled ahead-of-time to a native executable.
> > This means that you do not need a JVM to run GraalPy and it is compact in size.
> 
> In time of now, most of main implications of Python and JavaScript do NOT support AOT compilation.
> 
> For example, [NodeJS](https://github.com/nodejs/node) , [Deno](https://github.com/denoland/deno), and even [Bun](https://github.com/oven-sh/bun) only supports Just-in-Time(JIT) compilation and they have no plan to support AOT.
> 
> However, the case of [GraalPy](https://github.com/oracle/graalpython) shows us that making Script language to be compiled to Native binary is technically possible. And already there is an AOT compiler for Javascript like [ChowJS](https://mp2.dk/techblog/chowjs/), but unfortunately it is a closed source, and maybe a project NOT free of charge.
> 
> [Static Hermes](https://www.react-native.eu/talks/tzvetan-mikov-static-hermes-the-next-generation-of-hermes), which is being developed by Meta shows us that AOT compiling of JavaScript could be a killer feature of the project.

IIUC, it's not the user's Python code that is AOT compiled, but the GraalPy runtime itself. GraalPy containts lots of Java code and that Java code is AOT compiled, so then you don't need JVM to run that Java code.

There's a Python-to-C++ transpiler https://github.com/shedskin/shedskin which I've used to speed up my toy program years ago: 
https://github.com/tarsa/TarsaLZP/tree/master/python/TarsaLZP -> https://github.com/shedskin/shedskin/tree/master/examples/tarsalzp
