### ISSUE TITLE
Runtime reflection is not supported for public javax.ws.rs.core.Response$StatusType org.jboss.resteasy.specimpl.AbstractBuiltResponse.getStatusInfo()

### ISSUE THREAD

**Issue by yoinercoding** [oracle/graal#8900]
com.oracle.svm.core.jdk.UnsupportedFeatureError: Runtime reflection is not supported for public javax.ws.rs.core.Response$StatusType org.jboss.resteasy.specimpl.AbstractBuiltResponse.getStatusInfo()\n\tat org.graalvm.nativeimage.builder/com.oracle.svm.core.util.VMError.unsupportedFeature(VMError.java:89)\n\tat java.base@17.0.8/java.lang.reflect.Method.acquireMethodAccessor(Method.java:76)\n\tat java.base@17.0.8/java.lang.reflect.Method.invoke(Method.java:566)\n\tat com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:689)\n\tat com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:774)\n\tat com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:178)\n\tat com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:480)\n\tat com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:319)\n\tat com.fasterxml.jackson.databind.ObjectMapper._writeValueAndClose(ObjectMapper.java:4624)\n\tat com.fasterxml.jackson.databind.ObjectMapper.writeValueAsString(ObjectMapper.java:3869)\n\tat ar.com.hipotecario.originacion.microservice.OriginacionMicroService.executeSelect(OriginacionMicroService.java:127)\n\tat ar.com.hipotecario.originacion.microservice.OriginacionMicroService_ClientProxy.executeSelect(Unknown Source)\n\tat ar.com.hipotecario.originacion.service.InfoAdicionalDocumentoService.obtenerInfoAdicionalDocumento(InfoAdicionalDocumentoService.java:65)\n\tat ar.com.hipotecario.originacion.service.InfoAdicionalDocumentoService.getInfoAdicionalDocumento(InfoAdicionalDocumentoService.java:54)\n\tat ar.com.hipotecario.originacion.service.InfoAdicionalDocumentoService_ClientProxy.getInfoAdicionalDocumento(Unknown Source)\n\tat ar.com.hipotecario.originacion.controller.InfoAdicionalDocumentoController.obtenerInfoAdicionalDocumento(InfoAdicionalDocumentoController.java:80)\n\tat ar.com.hipotecario.originacion.controller.InfoAdicionalDocumentoController_ClientProxy.obtenerInfoAdicionalDocumento(Unknown Source)\n\tat java.base@17.0.8/java.lang.reflect.Method.invoke(Method.java:568)\n\tat org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:170)\n\tat org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:130)\n\tat org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:660)\n\tat org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:524)\n\tat org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:474)\n\tat org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)\n\tat org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:476)\n\tat org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:434)\n\tat org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:408)\n\tat org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:69)\n\tat org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:492)\n\tat org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261)\n\tat org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)\n\tat org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)\n\tat org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164)\n\tat org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)\n\tat org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:249)\n\tat io.quarkus.resteasy.runtime.ResteasyFilter$ResteasyResponseWrapper.service(ResteasyFilter.java:70)\n\tat io.quarkus.resteasy.runtime.ResteasyFilter$ResteasyResponseWrapper.sendError(ResteasyFilter.java:76)\n\tat io.undertow.servlet.handlers.DefaultServlet.doGet(DefaultServlet.java:172)\n\tat javax.servlet.http.HttpServlet.service(HttpServlet.java:503)\n\tat javax.servlet.http.HttpServlet.service(HttpServlet.java:590)\n\tat io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:74)\n\tat io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:129)\n\tat io.quarkus.resteasy.runtime.ResteasyFilter.doFilter(ResteasyFilter.java:31)\n\tat io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)\n\tat io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)\n\tat io.smallrye.metrics.jaxrs.JaxRsMetricsServletFilter.doFilter(JaxRsMetricsServletFilter.java:53)\n\tat io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)\n\tat io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)\n\tat io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84)\n\tat io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:63)\n\tat io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:68)\n\tat io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)\n\tat io.undertow.servlet.handlers.RedirectDirHandler.handleRequest(RedirectDirHandler.java:67)\n\tat io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:133)\n\tat io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)\n\tat io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)\n\tat io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)\n\tat io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:65)\n\tat io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60)\n\tat io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77)\n\tat io.undertow.security.handlers.NotificationReceiverHandler.handleRequest(NotificationReceiverHandler.java:50)\n\tat io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)\n\tat io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)\n\tat io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)\n\tat io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:247)\n\tat io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:56)\n\tat io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:111)\n\tat io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:108)\n\tat io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)\n\tat io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)\n\tat io.quarkus.undertow.runtime.UndertowDeploymentRecorder$9$1.call(UndertowDeploymentRecorder.java:595)\n\tat io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:227)\n\tat io.undertow.servlet.handlers.ServletInitialHandler.handleRequest(ServletInitialHandler.java:152)\n\tat io.quarkus.undertow.runtime.UndertowDeploymentRecorder$1.handleRequest(UndertowDeploymentRecorder.java:120)\n\tat io.undertow.server.Connectors.executeRootHandler(Connectors.java:284)\n\tat io.undertow.server.DefaultExchangeHandler.handle(DefaultExchangeHandler.java:18)\n\tat io.quarkus.undertow.runtime.UndertowDeploymentRecorder$5$1.run(UndertowDeploymentRecorder.java:417)\n\tat java.base@17.0.8/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)\n\tat java.base@17.0.8/java.util.concurrent.FutureTask.run(FutureTask.java:264)\n\tat io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:576)\n\tat org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)\n\tat org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)\n\tat org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)\n\tat org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)\n\tat io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)\n\tat java.base@17.0.8/java.lang.Thread.run(Thread.java:833)\n\tat org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:775)\n\tat org.graalvm.nativeimage.builder/com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:203)\n"
}
[properties pom.txt](https://github.com/oracle/graal/files/15265301/properties.pom.txt)
[reflect-config.json](https://github.com/oracle/graal/files/15265303/reflect-config.json)

**Comment by fniephaus** [comment]
Thanks for the ticket, @yoinercoding. According to the stack trace, your application tries to reflectively access `org.jboss.resteasy.specimpl.AbstractBuiltResponse.getStatusInfo()` but I don't see an corresponding entry in your `reflect-config.json`. You probably want to build your app with `-H:+ThrowMissingRegistrationErrors=org.jboss.resteasy` or so, which should turn the error into an actionable task for you: it will tell you exactly what you need to add to your `reflect-config.json`.

Note that `jackson` will likely require a lot of reflection registrations, which Quarkus does not seem to provide out-of-the-box. Quarkus also does not make use of neither the [Native Build Tools](https://github.com/graalvm/native-build-tools) nor the [Reachability Metadata repo](https://github.com/oracle/graalvm-reachability-metadata), so it's probably best you file a ticket against Quarkus if you can't get this to work.

I hope you don't mind if I'm closing this for now. Feel free to add more comments if you need further assistance.

**Comment by yoinercoding** [comment]
Good morning, thanks for the answer @fniephaus I was able to solve it by adding several entries to the reflect-config.json

{
    "name": "javax.ws.rs.core.Response",
    "allDeclaredFields": true,
    "queryAllDeclaredMethods": true,
    "methods": [
      {
        "name": "getHeaders",
        "parameterTypes": [

        ]
      }
    ]
  },
  {
    "name": "javax.ws.rs.core.Response$Status",
    "allDeclaredFields": true,
    "queryAllDeclaredMethods": true
  },
  {
    "name": "javax.ws.rs.core.Response$StatusType",
    "queryAllDeclaredMethods": true
  }
  
Thanks for the help

**Comment by fniephaus** [comment]
Great! Glad it's working for you now! :)
