### ISSUE TITLE
[Enhancement] Create JRE release in addition to the JDK release each time an RC is created

### ISSUE THREAD

**Issue by neomatrix369** [oracle/graal#891]
On the https://github.com/oracle/graal/releases page whenever an RC is created, can you please also create a JRE version of it, the JDK does contain the JRE but would be good to have a JRE version for the respective OSes.

Currently, I'm downloading the JDK, extracting the JRE and discarding the rest of the files just to use the JRE.

**Comment by dougxc** [comment]
Hi @neomatrix369 , can you share the script(s) you have to convert a JDK to a JRE? That would inform us what it takes to do this on our end as well as help others who may want the same thing in the meantime.

**Comment by neomatrix369** [comment]
Sure I can, It's pretty simple stuff, here's the link (starting line 15):
https://github.com/neomatrix369/awesome-ai-ml-dl/blob/master/examples/apache-zeppelin/Zeppelin-Dockerfile#L15

Shameless plug: wrote this post when I found the need to do it - https://medium.com/@neomatrix369/apache-zeppelin-stairway-to-notes-haven-28ec413a185a [Tweet](https://twitter.com/theNeomatrix369/status/1078561255214993408)

**Comment by neomatrix369** [comment]
I'll amend the build scripts at https://github.com/neomatrix369/awesome-graal/tree/master/build/x86_64/linux_macos asap to do that asap

**Comment by neomatrix369** [comment]
I have updated my build scripts on https://github.com/neomatrix369/awesome-graal/blob/master/build/x86_64/linux_macos/lib/archivingArtifacts.sh this one shows how we can just copy the `jre` folder and create an archive from it - the simplest way I see it happen but you could make a switch that can be used to trigger `mx` to only build the `jre` aspect of graal.

Built artifacts (including the JRE artifact) can be found at https://ci.adoptopenjdk.net/job/jdk8-with-graal_build_x86-64_macos/

**Comment by dougxc** [comment]
On second thoughts, I'm not sure we want a JRE-only GraalVM as we want to support compiling against the Graal SDK classes without adding extra options to `javac` and `javac` is not part of the JRE. For now, I think it's easy enough (as shown by your scripts - thanks!) for anyone who wants a JRE to derive one from the GraalVM JDK.

**Comment by neomatrix369** [comment]
Are you happy if I propose an experimental `mx makegraaljre` to added to the `mx` build options? While these scripts still help, would be good to also do it the `mx` way. 

To only demo GraalVM which does not need any compiling, the JRE has worked for me ;) 👍

**Comment by dougxc** [comment]
Ok, please open a PR and ask @ansalond to look at it.

**Comment by tabiStein** [comment]
Hi @neomatrix369 and @dougxc ! Do you know if progress has been/will be made on this ticket? I'm looking to include just the JRE and Tracing Agent in a Docker image, so the tracing agent can be integrated into our build pipeline (that way we can automatically generate metadata/configuration files as our project evolves). Including the entire Graal JDK on top of a Ubuntu base image results in a whopping 1.09G image, so I'd love to avoid that! Thanks in advance.

**Comment by dougxc** [comment]
As of Java 9, the JRE does not exist. Since GraalVM releases for Java 8 have been discontinued, I'm closing this issue.

I'm not sure how feasible it would be to make the Tracing Agent available as a separate download. I suspect the ongoing cost of doing so may not be justifiable. What do you think @gilles-duboscq  or @christianwimmer ?
