### ISSUE TITLE
How to configure Gradle to initialize specific modules at runtime when generating a native image with GraalVM?

### ISSUE THREAD

**Issue by Mohamed-Hammada** [oracle/graal#8923]
I am trying to generate a native image with GraalVM using the `graalvmNative` plugin in Gradle. With simple projects, it works fine when I just apply the `org.graalvm.buildtools` plugin. However, when I need to add other dependencies like `netty-transport-4.1.109.Final` and `netty-resolver-4.1.109.Final`, I get stuck in a loop of tracing and setting individual classes to initialize at runtime, as shown in the following Gradle configuration:

```gradle
graalvmNative {
    toolchainDetection = true
    binaries {
        main {
            agent {
                buildArgs.add('--strict-image-heap')
                // ... (omitted for brevity) ...
                buildArgs.add('--initialize-at-run-time=io.netty.util.NetUtil')
                buildArgs.add('--initialize-at-run-time=io.netty.util.ResourceLeakDetectorFactory')
                // ... (omitted for brevity) ...
            }
        }
    }
}
```

I am using `graalvm-jdk-17_linux-x64_bin` with Spring Boot 3.2.5 and the Gradle plugin version `id 'org.graalvm.buildtools.native' version '0.9.28'`.

Instead of listing individual classes, is there a way to configure Gradle to initialize entire modules or dependencies at runtime when generating the native image? This would make the configuration more concise and maintainable, especially when working with large third-party libraries like Netty.

I tried searching for solutions, but I couldn't find a way to achieve this. Any help or guidance would be greatly appreciated.

**Comment by fernando-valdez** [comment]
Hi Mohamed, 
One option is adding the entire package. It may look like this:
```
graalvmNative {
    toolchainDetection = true
    binaries {
        main {
            agent {
                buildArgs.add('--strict-image-heap')
                // Initialize entire Netty packages at runtime
                buildArgs.add('--initialize-at-run-time=io.netty.util')
                buildArgs.add('--initialize-at-run-time=io.netty.resolver')
                // Add additional packages or modules as needed
            }
        }
    }
}
``` 

You can read more about this here: 
https://www.graalvm.org/latest/reference-manual/native-image/guides/specify-class-initialization/

**Comment by Mohamed-Hammada** [comment]
Thanks for your response @fernando-valdez . It appears that your suggested solution is indeed effective; I had attempted to implement it using `buildArgs.add('--initialize-at-run-time=io.netty')`, but encountered confusion when it didn't yield the desired outcome. Your explanation regarding sub-packages clarified the issue, and now the solution seems works.

However, I've encountered another obstacle:
```
What went wrong:
Execution failed for task ':nativeCompileClasspathJar'.
> Archive contains more than 65535 entries.

To resolve this, please enable the zip64 extension.
For guidance on how to do this, refer to: https://docs.gradle.org/8.7/dsl/org.gradle.api.tasks.bundling.Zip.html#org.gradle.api.tasks.bundling.Zip:zip64
```

Do you have any suggestions on how to address this issue?

**Comment by Mohamed-Hammada** [comment]
It worked perfectly, I really appreciate the time you took to assist me.
