### ISSUE TITLE
problem running compiled file when I have @Qualifier annotation in my code

### ISSUE THREAD

**Issue by Godoy-source** [oracle/graal#9018]
**Describe the issue**
I have a problem related to Spring Security, specifically with a dependency injection (HandlerExceptionResolver) with a qualifier, graalVm does not know how to interpret the order of Beans and ends up breaking my code.
![image](https://github.com/oracle/graal/assets/61835030/e200b231-1087-490c-ab5d-3cf17aeffe8e)
Error:
![image](https://github.com/oracle/graal/assets/61835030/5ac64c20-77fb-47a3-80e6-1226fbc61372)

**Describe GraalVM and your environment:**
 - GraalVM graalvm-jdk-21.0.3+7.1
 - JDK major version: 21
 - OS: **Windows 11**

**More details**
the class is mapped in my reflection json files
![image](https://github.com/oracle/graal/assets/61835030/c6cc9678-bb6a-46c1-98bc-6d4de55280ca)
when I remove this part of the code it works normally
![image](https://github.com/oracle/graal/assets/61835030/f0911b4c-0eb0-41f4-b70d-a227956893af)

**Comment by selhagani** [comment]
Hi @Godoy-source,  Thanks for reaching out to us.

Could you please share a concise reproducer with me alongside the steps you follow to encounter the issue you described?

Thanks.

**Comment by selhagani** [comment]
As I haven't heard back from you in over three weeks, I will be closing this issue for now. If you need further assistance or have any updates, please feel free to reach out at any time.
Thank you for your understanding.
