### ISSUE TITLE
native-image swing program in linux cannot switch to Chinese IME in the JTextField component

### ISSUE THREAD

**Issue by qq602431132** [oracle/graal#9019]
**Describe the issue**
native-image swing program in linux cannot switch to Chinese IME in the JTextField component.  Both the Sogou input method and the sunpinyin input method under the fcitx framework cannot input Chinese characters.

graalvm-jdk-21.0.3+7.1
Kernel: Linux 6.1.32-amd64-desktop-hwe
Architecture: x86-64

**Steps to reproduce the issue** 
1、native-image
`native-image --no-fallback -H:+AddAllCharsets -H:ConfigurationFileDirectories=config --enable-url-protocols=https,http -Djava.awt.headless=false  --allow-incomplete-classpath -J-Xmx16G -Djdk.gtk.version=2 -jar lessions.jar
`
2、run 
`./lessions`
3、cannot input Chinese characters
![image](https://github.com/oracle/graal/assets/138293218/894b662d-691f-4b86-86b9-e45ad1850070)

More information
[https://stackoverflow.com/q/78557921/25339404](https://stackoverflow.com/q/78557921/25339404)
This issue also exists in JavaFX programs.

**Comment by selhagani** [comment]
Hi @qq602431132, thanks for reaching out to us.

Could you please upload a concise reproducer of the issue to a public github repo and share it with me please?

Thanks.

**Comment by qq602431132** [comment]
> Hi @qq602431132, thanks for reaching out to us.
> 
> Could you please upload a concise reproducer of the issue to a public github repo and share it with me please?
> 
> Thanks.

https://github.com/qq602431132/swingapp4

**Comment by selhagani** [comment]
Thank you for providing the reproducer. I reviewed the attachment, but I encountered a different error than the one you described.

Additionally, I noticed that your reproducer is using GraalVM for JDK 22 (22.0.1+8.1, build 22.0.1+8-jvmci-b01), while the issue description mentions GraalVM JDK 21.0.3+7.1. Could you please verify the version you are testing with and ensure the reproducer aligns with that version? This will help us troubleshoot the issue more effectively.

For reference, here is the error I encountered when testing with GraalVM for JDK 22 (as specified in the project.properties file of your reproducer):
`Exception in thread "main" java.lang.UnsatisfiedLinkError: Can't load library: awt | java.library.path = [.]
`

**Comment by qq602431132** [comment]
@selhagani 
This demo can't be run by me now either... I have the same problem as you. Let me answer your questions first.
 
The change of the JDK version for testing, from 21 to 22, is because I wanted to try to solve the problem of being unable to input Chinese by upgrading the JDK version. As a result, the executable programs generated by both cannot input Chinese.
 
In addition, the core point of the problem I raised is that the Swing executable program generated by native-image cannot input Chinese using the fcitx input method. (It also includes Japanese and Korean...)
 
The problem of being unable to load the library is obviously another issue.

**Comment by qq602431132** [comment]
The problem still exists.

**Comment by qq602431132** [comment]
The problem still exists.
