### ISSUE TITLE
absolute relocations in rodata section

### ISSUE THREAD

**Issue by johanvos** [oracle/graal#9037]
After https://github.com/oracle/graal/commit/1cd8a83c17707f145831cd0d90a60fd6acd985ea, code compiled for Android can no longer be linked.
The rodata section contains non-relative relocations. Previously, the ForceNoROSectionRelocations option could be used to make the rodata section writable, but that option is removed, and consequently the linker fails to link.
(see also #1443)

**Comment by fernando-valdez** [comment]
Hi @johanvos, thanks for reporting this issue. Can you please provide more context on this issue? Can you share the steps we can take to reproduce this issue?

**Comment by fernando-valdez** [comment]
closed due to lack of response
