### ISSUE TITLE
com.github.kevinsawicki dependency error

### ISSUE THREAD

**Issue by su-404** [oracle/graal#9052]
When I use the following dependencies, I get a situation where the code executes normally but the request is empty after the package is compiled.
 <dependency>
            <groupId>com.github.kevinsawicki</groupId>
            <artifactId>http-request</artifactId>
            <version>6.0</version>
        </dependency>
![image](https://github.com/oracle/graal/assets/81111471/c5cec941-3c76-4686-b1e8-bb74aeacafa0)
![image](https://github.com/oracle/graal/assets/81111471/34556717-086a-4e1b-8446-ade402592933)
![image](https://github.com/oracle/graal/assets/81111471/a5f712a4-be14-4580-a100-0b869206c4cd)

**Comment by su-404** [comment]
graalvm-ce-java11-22.3.3

**Comment by fernando-valdez** [comment]
Hello, can you please elaborate more on this issue? Are you saying that the GraalVM compiler is having an issue with a dependency? Is this same code working on other JVMs?

**Comment by su-404** [comment]
I used another way to solve the problem, thank you for your reply.
