### ISSUE TITLE
Missleading warning after the integration of proxy registration to the reflection config

### ISSUE THREAD

**Issue by zakkak** [oracle/graal#9057]
**Describe the issue**
Since https://github.com/oracle/graal/pull/8822 GraalVM will print the following warning when a project has a `proxy-config.json` file:

```
Warning: Option 'DynamicProxyConfigurationResources' is deprecated and might be removed in a future release. Please refer to the GraalVM release notes.
```

This warning is missleading as the user doesn't explicitly pass DynamicProxyConfigurationResources`. Instead a warning indicating that `proxy-config.json` has been deprecated would be more suitable.

cc @loicottet 

**Steps to reproduce the issue**
Please include both build steps as well as run steps
1. Create hello world project
2. Create `META-INF/native-image/proxy-config.json` (containing `[]` is enough)
3. Package project in a jar file 
4. Try to build a native image from the jar file

**Describe GraalVM and your environment:**
 - GraalVM version (latest snapshot builds can be found [here](https://github.com/graalvm/graalvm-ce-dev-builds/releases)), or commit id if built from source: **9c0a7a4cfbb0b4690e004a9aa6484514defd3770**
 - JDK major version: **23**
 - OS: **Fedora 40**
 - Architecture: **AMD64**

**More details**
Using `--verbose` we see that the option is automatically passed to native-image

```
'-H:DynamicProxyConfigurationResources@jar:file:///home/zakkak/quarkus-runner.jar!/META-INF/native-image/proxy-config.json+api=META-INF/native-image/proxy-config.json'
```

**Comment by loicottet** [comment]
Thanks for the report! We should indeed change this message.

**Comment by loicottet** [comment]
Fixed by https://github.com/oracle/graal/commit/5fc14c42fd8bbad0c8e661b4ebd8f96255f86e6b

**Comment by zakkak** [comment]
Thank you @loicottet

**Comment by zakkak** [comment]
For future reference the PR fixing this is https://github.com/oracle/graal/pull/9155
