### ISSUE TITLE
[native-image] [Os X] Native desktop application

### ISSUE THREAD

**Issue by tmmlsBE** [oracle/graal#907]
Hi,

Currently I'm testing the GraalVM solution and I'm loving it. I'm able to create a small project and compile it as a native application. It works well when running it from the command line. But how do I compile my project as valid desktop application, contain all required icons?

Thanks

TM

**Comment by shelajev** [comment]
To include the resources in the native image one should probably use a configuration flag: [-H:IncludeResources=](https://github.com/oracle/graal/blob/master/substratevm/RESOURCES.md). Then these files will be available. 

What frameworks do you use for the desktop applications?

**Comment by soynomm** [comment]
I'm also interested in knowing how to add a app icon to the executable.

**Comment by hamzaGhaissi** [comment]
Since 2019 AWT support has improved, if you have any new problem please create a new github issue.
