### ISSUE TITLE
Nondeterministic error with service loader when running native-image

### ISSUE THREAD

**Issue by russelldavis** [oracle/graal#908]
I'm using graal to compile https://github.com/holgerbrandl/kscript to a native image. You can see the issue yourself by loading my branch at https://github.com/russelldavis/kscript/tree/graal-native-image and running `./gradlew nativeImage`. It will sometimes produce the following error:

```
error: Error loading service implementations for service `kotlin.reflect.jvm.internal.impl.builtins.BuiltInsLoader` from URL `jar:file:/Users/russell/dev/kotlin/kscript/build/libs/kscript.jar!/META-INF/services/kotlin.reflect.jvm.internal.impl.builtins.BuiltInsLoader`
Caused by: java.io.FileNotFoundException: JAR entry META-INF/services/kotlin.reflect.jvm.internal.impl.builtins.BuiltInsLoader not found in /Users/russell/dev/kotlin/kscript/build/libs/kscript.jar
        at sun.net.www.protocol.jar.JarURLConnection.connect(JarURLConnection.java:144)
        at sun.net.www.protocol.jar.JarURLConnection.getInputStream(JarURLConnection.java:152)
        at java.net.URL.openStream(URL.java:1045)
```

Two very strange things about this:
1) The file the error mentions actually *does* exist (`META-INF/services/kotlin.reflect.jvm.internal.impl.builtins.BuiltInsLoader`)
2) The error is nondeterministic. As part of debugging it, I installed a local copy of graal, separate from the one that gradle installs (but exact same version, identical binary). I ran it with the exact same command line, and it would succeed, while the gradle-installed version would fail. Later when I would change trivial things in the source (like the name of a variable), my local version of graal would start failing too. I pulled my hair out over this for a while; I'm almost positive this wasn't some weird user error.

I finally discovered the `-H:-UseServiceLoaderFeature` flag, which made the error go away (though I don't fully understand the implications of the flag, and of course the original issue should still be addressed).

**Comment by jramirez-isc** [comment]
Hi @russelldavis I'm looking into this. 
I was able to use the code to build a native image using `option("-H:-UseServiceLoaderFeature")` but I couldn't reproduce the error message when removing that option. 
Also, I've noticed you are using `graalVersion("1.0.0-rc10")`, could you confirm that this issue is still happening with latest version (20.2.0) ?

**Comment by russelldavis** [comment]
Hi @jramirez-isc, I'm no longer working on that project, feel free to close this if you can't reproduce.
