### ISSUE TITLE
Implement Debug Adapter Protocol (DAP) for guest languages

### ISSUE THREAD

**Issue by p-bakker** [oracle/graal#909]
Currently there is an implementation of the Chrome Devtools Protocol so guest languages can be debugged through there.

However, more and more tooling/editors support DAP (https://microsoft.github.io/debug-adapter-protocol/) to support debugging for a multitude of languages.

While it is possible (I think) to debug a guest language in VSCode or Eclipse by connecting using DAP through the VSCode NodeJS DAP in turn connecting to the inspector/Chrome Devtools Protocol implementation currently available for guest languages, a more direct route probably would perform better/have less issues/be better aligned capability-wise

**Comment by smarr** [comment]
If anyone is interested in picking this up, [SOMns](https://github.com/smarr/SOMns/tree/release/src/tools/debugger) has a somewhat language specific prototype, likely of a bit older version of the DAP. Though, it's working in current VSCode versions.

**Comment by jkreindl** [comment]
Implementing this is also an open topic for a BSc.-thesis at JKU Linz. A student already stated that they're interested in doing it, but that's not final and they wouldn't start before late February / early March.

**Comment by p-bakker** [comment]
Interesting. Is there anything online to link to as to track its progress?

**Comment by jkreindl** [comment]
No, there is nothing yet.

**Comment by p-bakker** [comment]
Any idea if it'll utilize lsp4j and if it will support sourcemaps?

**Comment by jkreindl** [comment]
We have not made any decisions about this yet.

**Comment by hamzaGhaissi** [comment]
Looks like this has been implemented ^_^
https://www.graalvm.org/latest/tools/dap/
