### ISSUE TITLE
Current dev cycle is 24.2.0 but there is no 24.1 branch yet

### ISSUE THREAD

**Issue by zakkak** [oracle/graal#9127]
**Feature request**

Hello, since https://github.com/oracle/graal/commit/e3f8f87793cd913453b44b3b315fb3da1f648257 the dev cycle was bumped to 24.2.0 but there is no 24.1.0 branch yet.

**Is your feature request related to a problem? Please describe.**

24.1.0 branch is no longer accessible by the community making it impossible to test.

**Describe the solution you'd like.**

Please create https://github.com/oracle/graal/tree/release/graal-vm/24.1 like with previous versions.

**Describe who do you think will benefit the most.**
GraalVM contributors, developers of libraries and frameworks which depend on GraalVM.

cc @gilles-duboscq @ezzarghili

**Comment by fniephaus** [comment]
We are still working on the release branch for 24.1 internally but I hope it's ready very soon and gets synced in the next couple of days.

**Comment by fniephaus** [comment]
The last commit before the branch off happened is 69baa168b4c0602b078f0bc0b49d95b93582ba95.

cc @jerboaa

**Comment by jerboaa** [comment]
> The last commit before the branch off happened is [69baa16](https://github.com/oracle/graal/commit/69baa168b4c0602b078f0bc0b49d95b93582ba95).

Thanks! We'll use that for now (until the branch is there).

**Comment by ansalond** [comment]
The 24.1 release branches are now mirrored: https://github.com/oracle/graal/tree/release/graal-vm/24.1
Sorry for the delay.

**Comment by jerboaa** [comment]
Thanks very much, @ansalond!
