### ISSUE TITLE
mx version bumped to 7.26 but not available on upstream repository

### ISSUE THREAD

**Issue by zakkak** [oracle/graal#9145]
**Describe the issue**
https://github.com/oracle/graal/pull/9137 bumped the mx version to `7.26.0`, but the version is not yet pushed upstream https://github.com/graalvm/mx/

According to https://github.com/graalvm/mx/issues/282#issuecomment-2167342245 there was some mirroring issue in the `mx` repository that might be related. Could you please have a look?

cc @ansalond @fniephaus

**Comment by fniephaus** [comment]
Thanks for raising this, @zakkak! We had to apply additional rules across our repositories under the `graalvm` org and, unfortunately, that broke our mirroring service. We are currently adjusting the service and we have added tag/branch protections to avoid destructive operations. In the meantime, I've pushed the new tags manually to unblock the Github workflows. So we should be good at the moment.

Related: https://github.com/graalvm/mx/issues/282

**Comment by zakkak** [comment]
Thank you @fniephaus for pushing the tags. Please note that the `master` branch is still out of sync, if you have the appropriate permissions could you please push this as well?

**Comment by fniephaus** [comment]
I'm pining our infra team, surely we cannot just push to the main branch ;)

**Comment by fniephaus** [comment]
I just merged https://github.com/graalvm/mx/pull/283
