### ISSUE TITLE
[GR-54934] Increase in methods being accessed reflectively starting with GraalVM for JDK 23+26

### ISSUE THREAD

**Issue by zakkak** [oracle/graal#9147]
**Describe the issue**
Starting with JDK 23+26 we see a lot of `java.lang.BootstrapMethodError: java.lang.NoSuchMethodError` in Quarkus tests, see https://github.com/oracle/graal/actions/runs/9558273459

The issue seems related to https://bugs.openjdk.org/browse/JDK-8229959.

The naive approach seems to be to register all methods of dynamically proxied classes for reflection, but I wonder if there is anything we could do on the GraalVM side to handle this since I expect many users/frameworks to be affected.

cc @vjovanov @fniephaus 

**Steps to reproduce the issue**
1. Grab the latest GraalVM CE dev build from release https://github.com/graalvm/graalvm-ce-dev-builds/releases
2. Extract it and set `GRAALVM_HOME` to point to the extracted directory
3. `git clone https://github.com/quarkusio/quarkus.git`
4. `cd quarkus`
5. `./mvnw -Dquickly` (that takes some time... might want to use `-T4` or similar if you have multiple cores)
6. `./mvnw -Dnative -pl integration-tests/spring-web -Dnative.surefire.skip -Dformat.skip -Dno-descriptor-tests clean verify -Dquarkus.native.container-build=false -Dtest-containers -Dstart-containers`

**Describe GraalVM and your environment:**
 - GraalVM version: **master**
 - JDK major version: **23 manifests in 24 as well**
 - OS: **Fedora 40**
 - Architecture: **[e.g.: AMD64]**

**More details**

First reported in Quarkus https://github.com/quarkusio/quarkus/issues/41283

**Comment by fernando-valdez** [comment]
Hi @zakkak  Can you please confirm if this issue happens on Oracle GraalVM (instead of the CE edition) ?

**Comment by zakkak** [comment]
Thanks for the quick fix @christianwimmer, I will check our CI tomorrow and report back.

**Comment by zakkak** [comment]
> Hi @zakkak Can you please confirm if this issue happens on Oracle GraalVM (instead of the CE edition) ?

FTR I only tested this with the CE edition.

**Comment by zakkak** [comment]
I confirm this resolves the issue. Thanks again.

@gilles-duboscq @ezzarghili the fix (#9184) should be backported to 24.1 as well. Shall I open a backport PR for it?

**Comment by christianwimmer** [comment]
> the fix (https://github.com/oracle/graal/pull/9184) should be backported to 24.1 as well.

I already have the backporting PR ready for merging, it will go in as soon as the release branch is ready for fixes.

**Comment by zakkak** [comment]
> it will go in as soon as the release branch is ready for fixes.

Hi Christian, could you provide some more details on that part?
What's currently preventing you (the GraalVM team) from merging fixes on the release branch?

We occasionally find ourselves backporting things on our mandrel fork before upstream (e.g. https://github.com/graalvm/mandrel/pull/757) just to be able to test things in a timely manner. We later drop our backport in favor of the upstream one but we believe it would be better if we didn't have to do it this way.
