### ISSUE TITLE
[native-image] UseStackBasePointer increase execution time by 50%

### ISSUE THREAD

**Issue by SergejIsbrecht** [oracle/graal#916]
When following option -H:+UseStackBasePointer is used, the execution time will increase dramatically.

Environment:
* RC11
* Linux sergej-P50 4.18.0-13-generic #14-Ubuntu SMP Wed Dec 5 09:04:24 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

Native Image Compilation options:
* -H:+UseStackBasePointer
* --verbose
* --no-server

Code:
```
public class TopTen {
  private static final Pattern PATTERN_REPLACE = Pattern.compile("[^a-zA-Z]");
  private static final Pattern PATTERN_SPLIT = Pattern.compile("\\b");

  // /usr/bin/time ...
  public static void main(String[] args) {
    Arrays.stream(args)
        .parallel()
        .flatMap(TopTen::fileLines)
        .flatMap(TopTen::split)
        .map(TopTen::replace)
        .filter(word -> word.length() > 0)
        .map(String::toLowerCase)
        .collect(Collectors.groupingBy(Function.identity(), Collectors.counting()))
        .entrySet()
        .stream()
        .sorted((a, b) -> -a.getValue().compareTo(b.getValue()))
        .limit(10)
        .forEach(e -> System.out.format("%s = %d%n", e.getKey(), e.getValue()));
  }

  private static String replace(String word) {
    // word.replaceAll("[^a-zA-Z]", "");
    Matcher matcher = PATTERN_REPLACE.matcher(word);
    return matcher.replaceAll("");
  }

  private static Stream<String> split(String word) {
    // line.split("\\b")
    return Arrays.stream(PATTERN_SPLIT.split(word));
  }

  private static Stream<String> fileLines(String path) {
    try {
      return Files.lines(Paths.get(path));
    } catch (IOException e) {
      throw new RuntimeException(e);
    }
  }
}
```

Inputfile (txt):
https://github.com/SergejIsbrecht/GraalVMTest/blob/master/resources/big2_luther.tar.gz

Result without +UseStackBasePointer:
sergej@sergej-P50:~/Development/GitHub/GraalVMTest/oracleIssue/build/graal$ /usr/bin/time -v ~/Development/GitHub/GraalVMTest/oracleIssue/build/graal/hello-world ~/Downloads/big2.txt 
und = 742224
der = 300752
die = 265888
da = 215936
zu = 161360
sie = 157024
den = 140000
er = 139776
das = 139760
ich = 129824
        Command being timed: "/home/sergej/Development/GitHub/GraalVMTest/oracleIssue/build/graal/hello-world /home/sergej/Downloads/big2.txt"
        User time (seconds): 16.04
        System time (seconds): 0.10
        Percent of CPU this job got: 99%
        **Elapsed (wall clock) time (h:mm:ss or m:ss): 0:16.16**
        Average shared text size (kbytes): 0
        Average unshared data size (kbytes): 0
        Average stack size (kbytes): 0
        Average total size (kbytes): 0
        Maximum resident set size (kbytes): 278324
        Average resident set size (kbytes): 0
        Major (requiring I/O) page faults: 0
        Minor (reclaiming a frame) page faults: 67718
        Voluntary context switches: 1
        Involuntary context switches: 25
        Swaps: 0
        File system inputs: 0
        File system outputs: 0
        Socket messages sent: 0
        Socket messages received: 0
        Signals delivered: 0
        Page size (bytes): 4096
        Exit status: 0

Result with +UseStackBasePointer
sergej@sergej-P50:~/Development/GitHub/GraalVMTest/oracleIssue/build/graal$ /usr/bin/time -v ~/Development/GitHub/GraalVMTest/oracleIssue/build/graal/hello-world ~/Downloads/big2.txt 
und = 742224
der = 300752
die = 265888
da = 215936
zu = 161360
sie = 157024
den = 140000
er = 139776
das = 139760
ich = 129824
        Command being timed: "/home/sergej/Development/GitHub/GraalVMTest/oracleIssue/build/graal/hello-world /home/sergej/Downloads/big2.txt"
        User time (seconds): 24.00
        System time (seconds): 0.09
        Percent of CPU this job got: 99%
        **Elapsed (wall clock) time (h:mm:ss or m:ss): 0:24.10**
        Average shared text size (kbytes): 0
        Average unshared data size (kbytes): 0
        Average stack size (kbytes): 0
        Average total size (kbytes): 0
        Maximum resident set size (kbytes): 277984
        Average resident set size (kbytes): 0
        Major (requiring I/O) page faults: 0
        Minor (reclaiming a frame) page faults: 67711
        Voluntary context switches: 1
        Involuntary context switches: 143
        Swaps: 0
        File system inputs: 0
        File system outputs: 0
        Socket messages sent: 0
        Socket messages received: 0
        Signals delivered: 0
        Page size (bytes): 4096
        Exit status: 0

Flame-Graph: (perf with 99 hertz sampling-rate; -g fp) -> with +UseStackBasePointer
https://gist.github.com/SergejIsbrecht/dc6be9e298d022506c72b053e35d6ae7

Expected:
the overhead should not that big, when activating UseStackBasePointer

**Comment by thomaswue** [comment]
Did you test different type of programs and saw a similar regression? What can happen is that in this particular example having the one general register less available leads to a stack spill in an unfortunate location.

**Comment by SergejIsbrecht** [comment]
I will have a look at different applications. My main application is currently not working. I will provide some feedback in the next week with some example-code.

**Comment by SergejIsbrecht** [comment]
Some updates with Version 19.0.0

sergej@sergej-P50:~/Development/GitHub/GraalVMTest/oracleIssue/build/classes/java/main$ native-image --version
GraalVM Version 19.0.0 CE

sergej@sergej-P50:~/Development/GitHub/GraalVMTest/oracleIssue/build/classes/java/main$ /usr/bin/time -v ./topten ~/Downloads/big2.txt
und = 742224
der = 300752
die = 265888
da = 215936
zu = 161360
sie = 157024
den = 140000
er = 139776
das = 139760
ich = 129824
        Command being timed: "./topten /home/sergej/Downloads/big2.txt"
        User time (seconds): 19.13
        System time (seconds): 0.11
        Percent of CPU this job got: 99%
        Elapsed (wall clock) time (h:mm:ss or m:ss): 0:19.25
        Average shared text size (kbytes): 0
        Average unshared data size (kbytes): 0
        Average stack size (kbytes): 0
        Average total size (kbytes): 0
        Maximum resident set size (kbytes): 273016
        Average resident set size (kbytes): 0
        Major (requiring I/O) page faults: 0
        Minor (reclaiming a frame) page faults: 66695
        Voluntary context switches: 1
        Involuntary context switches: 8
        Swaps: 0
        File system inputs: 0
        File system outputs: 0
        Socket messages sent: 0
        Socket messages received: 0
        Signals delivered: 0
        Page size (bytes): 4096
        Exit status: 0

sergej@sergej-P50:~/Development/GitHub/GraalVMTest/oracleIssue/build/classes/java/main$ java -version
openjdk version "1.8.0_212"
OpenJDK Runtime Environment (build 1.8.0_212-20190420092731.buildslave.jdk8u-src-tar--b03)
OpenJDK GraalVM CE 19.0.0 (build 25.212-b03-jvmci-19-b01, mixed mode)

sergej@sergej-P50:~/Development/GitHub/GraalVMTest/oracleIssue/build/classes/java/main$ /usr/bin/time -v java -cp . TopTen ~/Downloads/big2.txt
und = 742224
der = 300752
die = 265888
da = 215936
zu = 161360
sie = 157024
den = 140000
er = 139776
das = 139760
ich = 129824
        Command being timed: "java -cp . TopTen /home/sergej/Downloads/big2.txt"
        User time (seconds): 8.17
        System time (seconds): 0.28
        Percent of CPU this job got: 115%
        Elapsed (wall clock) time (h:mm:ss or m:ss): 0:07.31
        Average shared text size (kbytes): 0
        Average unshared data size (kbytes): 0
        Average stack size (kbytes): 0
        Average total size (kbytes): 0
        Maximum resident set size (kbytes): 776252
        Average resident set size (kbytes): 0
        Major (requiring I/O) page faults: 8
        Minor (reclaiming a frame) page faults: 186949
        Voluntary context switches: 2651
        Involuntary context switches: 90
        Swaps: 0
        File system inputs: 2880
        File system outputs: 64
        Socket messages sent: 0
        Socket messages received: 0
        Signals delivered: 0
        Page size (bytes): 4096
        Exit status: 0

**Comment by SergejIsbrecht** [comment]
@olpaw ,

I did some testing yesterday. I will publish the results later, but in essence I guess the issue is resolved.

**Comment by SergejIsbrecht** [comment]
Done on Ubuntu AMD64 with

```
 ~/D/preserveframepointer  native-image --version                                           Fr 29 Dez 2023 14:46:32 CET
native-image 17.0.9 2023-10-17
GraalVM Runtime Environment GraalVM CE 17.0.9+9.1 (build 17.0.9+9-jvmci-23.0-b22)
Substrate VM GraalVM CE 17.0.9+9.1 (build 17.0.9+9, serial gc)
```

```
-march=native
	Command being timed: "./topten_ce_17_default /home/sergej/Downloads/big2.txt"
	User time (seconds): 13.44
	System time (seconds): 0.04
	Percent of CPU this job got: 100%

-H:+PreserveFramePointer -march=native
	Command being timed: "./topten_ce_17_preserve_fp /home/sergej/Downloads/big2.txt"
	User time (seconds): 13.95
	System time (seconds): 0.03
	Percent of CPU this job got: 99%

-H:+PreserveFramePointer -H:-DeleteLocalSymbols -march=native
	Command being timed: "./topten_ce_17_preserve_fp_deletelocalsymbols /home/sergej/Downloads/big2.txt"
	User time (seconds): 14.20
	System time (seconds): 0.06
	Percent of CPU this job got: 99%

-H:+PreserveFramePointer -H:+SourceLevelDebug -H:-DeleteLocalSymbols -march=native
	Command being timed: "./topten_ce_17_preserve_fp_sourceleveldebug_deletelocalsymbols /home/sergej/Downloads/big2.txt"
	User time (seconds): 16.82
	System time (seconds): 0.03
	Percent of CPU this job got: 99%
```

@olpaw , it seems applying both `-H:+SourceLevelDebug -H:-DeleteLocalSymbols` flags results in "worse" performance. These are single measurements and should be seen as such. I have to look into a proper benchmarking tool
