### ISSUE TITLE
Please push GraalVM for JDK 23 stabilization release branch

### ISSUE THREAD

**Issue by jerboaa** [oracle/graal#9176]
**Feature request**

Looking at [common.json](https://github.com/oracle/graal/blob/e924e682fe34a5d6e9aa0dd57d75839ea94ec6d9/common.json#L48) it seems the master branch has moved on to the next JDK release (JDK 24, internal version `24.2.0`). Could you please create a publicly visible `release/graal-vm/24.1` branch which integrators could use to build the GraalVM version for JDK 23 from?

Thank you!

/cc @gilles-duboscq @ezzarghili @fniephaus @zakkak

**Comment by jerboaa** [comment]
Failing a branch, please share a common commit id (before the branch) which we should use to build the GraalVM for JDK 23 version.

**Comment by fniephaus** [comment]
Closing this as a duplicate of https://github.com/oracle/graal/issues/9127.

**Comment by jerboaa** [comment]
Sorry about that. Thanks for the pointer.
