### ISSUE TITLE
[bug] There is no way to know how to obtain the native-image binary tool.

### ISSUE THREAD

**Issue by park671** [oracle/graal#9248]
in newer version, gu was removed.
but with the latest document(https://www.graalvm.org/latest/reference-manual/native-image/#build-a-native-executable-using-the-native-image-tool), it say that I can use "native-image" binary tool to convert jvm binary to machine code binary. 

but how can I get the "native-image" binary????? no download link url can be found in the document, oracle download page or github release.

**Comment by oubidar-Abderrahim** [comment]
Hi, Thank you for reaching out. Since Oracle GraalVM for JDK21 (23.1). `gu` is no longer available indeed. 
native-image is bundled by default with Oracle GraalVM core, once you download the GraalVM binary and add it to your path, you will be able to use native-image command without extra steps.
