### ISSUE TITLE
[GR-55550] WASI signature conflict for fd_advise

### ISSUE THREAD

**Issue by heroicefforts** [oracle/graal#9311]
I was attempting to load a WebAssembly file compiled by the .NET AOT LLVM compiler.  However, when I attempt to run the module using the Graal WASM runtime (v24.0.1) it fails with the error:

incompatible import type
  at org.graalvm.polyglot.Value.getMember(Value.java:843)

Debugging into the code, the issue appears to be a conflict in parameter types for the WASI fd_advise method.  The Graal declaration defines:

[defineFunction(context, module, "fd_advise", types(I32_TYPE, **I32_TYPE, I32_TYPE**, I32_TYPE), types(I32_TYPE), new WasiUnsupportedFunctionNode(language, module, "__wasi_fd_advise"));](https://github.com/oracle/graal/blob/0b8875e946628b3df2b8f2227a3f16578aa2ab23/wasm/src/org.graalvm.wasm/src/org/graalvm/wasm/predefined/wasi/WasiModule.java#L69C41-L69C116)

The .NET however imports:

func[3] sig=106 <wasi_snapshot_preview1.fd_advise> <- wasi_snapshot_preview1.fd_advise
type[106] (i32, **i64, i64**, i32) -> i32

The parameters for indexing into the file are defined as I32 in Graal and I64 in .NET.  This is causing the Linker to fail.  It makes sense that such parameters would be i64.  As a 3rd party reference, the WebAssembly wasi-libc also [defines this method](https://github.com/WebAssembly/wasi-libc/blob/b9e15a8af930603183eb13af62e193de0f9f9ee3/libc-bottom-half/sources/__wasilibc_real.c#L95) with i64.

**Comment by selhagani** [comment]
Hi @heroicefforts, 

Thank you for reaching out to us about this. I understand the issue that you're encountering. 

For us to take a further look into this could you please provide with us a concise reproducer for the issue you encountered alongside the steps needed to reproduce it? Also which version of GraalVM were you using? and on which OS and architecture did you test this on?

Thank you.

**Comment by jirkamarsik** [comment]
Hi! Thanks for the report.

We have a fix for this now. It should land in `master` soon and then be available in our next release.
