### ISSUE TITLE
docker pull container-registry.oracle.com/graalvm/native-image -> UNAUTHORIZED

### ISSUE THREAD

**Issue by ReXtrem** [oracle/graal#9325]
`docker pull container-registry.oracle.com/graalvm/native-image:latest` fails on every image now. 

<img width="1302" alt="image" src="https://github.com/user-attachments/assets/ec1645df-9657-4abd-87fe-fab29a7f23e3">

**Comment by selhagani** [comment]
Hi @ReXtrem, thank you for reaching out to us regarding this.

We will take a look into it and I will keep you in the loop.

Thanks

**Comment by selhagani** [comment]
Hi @ReXtrem, 

This should be fixed now. 

Thanks for reporting this.
