### ISSUE TITLE
ManagementFactory.getThreadMXBean() and ManagementFactory.getGarbageCollectorMXBeans() can't get the value under the native image.

### ISSUE THREAD

**Issue by Lorwell** [oracle/graal#9339]
When using the following code for a local image built with graalvm21 in a java project

Thread information
```kotlin
 val threadMXBean = ManagementFactory.getThreadMXBean()
        val allThread = threadMXBean.getThreadInfo(threadMXBean.allThreadIds).filterNotNull()
        val threadStateMap = allThread.groupBy { it.threadState }

// allThread is an empty list, can't get thread information
// @See https://github.com/Lorwell/great-wall/blob/40138bd7bdd3ee97056000645d34091be42d2223/great-wall-server/src/main/kotlin/cc/shacocloud/greatwall/service/scheduled/SystemMetricsScheduled.kt#L95
```

gc information

```kotlin
        val gcInfos = ManagementFactory.getGarbageCollectorMXBeans()
            .map {
                GCInfoMo(name = it.name, count = it.collectionCount, time = it.collectionTime)
            }
// gcInfos is an empty list, can't get gc information
// Note: this only exists when g1 gc is turned on, there is no such problem with the default gc.
// @See https://github.com/Lorwell/great-wall/blob/40138bd7bdd3ee97056000645d34091be42d2223/great-wall-server/src/main/kotlin/cc/shacocloud/greatwall/service/scheduled/SystemMetricsScheduled.kt#L113
```

The above code is all from the `great-wall` application, which can be run with `docker run -d -p 8080:8080 -p 443:443 -p 80:80 --name great-wall ccr.ccs.tencentyun.com/shaco_work/great-wall. 2.4_g1gc` Start a local container and subsequently open it in a browser [http://127.0.0.1:8080/manage/monitor-metrics/server](http://127.0.0.1:8080/manage/monitor-metrics/server) to see the corresponding heap memory and gc information.

Here are some screenshots of my local run for proof of this issue

![image](https://github.com/user-attachments/assets/1b0b9169-ac6f-43a3-8804-05f41005a5f9)
![image](https://github.com/user-attachments/assets/49ab7bfa-2869-4b05-a53b-f8520da0dd0d)
![image](https://github.com/user-attachments/assets/ea3b7199-d1fa-4282-bbc1-ccd4d4694fb4)

As you can see from the image above, the memory fluctuates within a period of time indicating that a gc has occurred, but the corresponding gc information is not available.
Also, we can't get the thread state information.

I'm not sure if I need to use another method to get it under native image, if so please provide it, thanks a lot!

**Comment by fernando-valdez** [comment]
Hello @Lorwell , can you please share the exact version you used of GraalVM? Also, please share the steps you took to build the native image for this app.

**Comment by roberttoyonaga** [comment]
@Lorwell Native Image doesn't yet fully support the ThreadMXBean. Some things are missing (like getting ThreadInfo objects).

**Comment by Lorwell** [comment]
> Hello @Lorwell , can you please share the exact version you used of GraalVM? Also, please share the steps you took to build the native image for this app.你好，你能分享一下你使用的 GraalVM 的确切版本吗？另外，请分享你为这个应用程序构建本地映像所采取的步骤。

The graalvm21 download link used is: https://download.oracle.com/graalvm/21/latest/graalvm-jdk-21_linux-x64_bin.tar.gz

Build using the `gradlew nativeCompile` command in gradle with `id(“org.graalvm.buildtools.native”) version “0.10.2”`.

**Comment by Lorwell** [comment]
> @Lorwell Native Image doesn't yet fully support the ThreadMXBean. Some things are missing (like getting ThreadInfo objects).原生映像尚未完全支持 ThreadMXBean。有些东西缺失（比如获取 ThreadInfo 对象）。

That's right. Thanks for the tip.
