### ISSUE TITLE
graalvm-community-jdk-22.0.2 downloads ...jdk-22.0.0

### ISSUE THREAD

**Issue by weaveworld** [oracle/graal#9348]
Starting to download v22.0.2 from
https://github.com/graalvm/graalvm-ce-builds/releases/tag/jdk-22.0.2
e.g., 
https://github.com/graalvm/graalvm-ce-builds/releases/download/jdk-22.0.2/graalvm-community-jdk-22.0.2_windows-x64_bin.zip

downloads 22.0.0
e.g.,
`graalvm-community-jdk-22.0.0_windows-x64_bin.zip`

**Comment by fernando-valdez** [comment]
Thanks for reporting this, I will take a look at it.

**Comment by fernando-valdez** [comment]
It seems like the link is downloading the right version, for the Windows case:
```
IMPLEMENTOR="GraalVM Community"
JAVA_RUNTIME_VERSION="22.0.2+9-jvmci-b01"
JAVA_VERSION="22.0.2"
```
But the downloaded file name is not showing the right version. Can you please confirm?

**Comment by weaveworld** [comment]
You are right. 
I thought that the link points to the earlier version.
But extracting the file I have the `graalvm-community-openjdk-22.0.2+9.1` directory.
Thus only the links' name refer to the earlier version.

```
C:\_Apps\graalvm-community-openjdk-22.0.2+9.1>bin\java --version
openjdk 22.0.2 2024-07-16
OpenJDK Runtime Environment GraalVM CE 22.0.2+9.1 (build 22.0.2+9-jvmci-b01)
OpenJDK 64-Bit Server VM GraalVM CE 22.0.2+9.1 (build 22.0.2+9-jvmci-b01, mixed mode, sharing)
```

Thank you!

**Comment by ezzarghili** [comment]
Issue is due to the fact that Github is sending the header below
```
content-disposition: attachment; filename=graalvm-community-jdk-22.0.0_linux-x64_bin.tar.gz`
```
We are closing this ticket as non Graal issue and raising this with Github support.
