### ISSUE TITLE
js array cannot be put into java method with Collection parameter

### ISSUE THREAD

**Issue by mungco** [oracle/graal#937]
I am trying to interop with java in js, but encountered a problem, code:

java code
```java
public class SearchServiceImpl {
    public Map<Long, SearchItem> search(Collection<Long> ids) {
        return new HashMap<Long, SearchItem>();
    }
}
```

js:
```javascript
function solution_entry() {
       var searchService = Polyglot.import("searchService")
      searchService.search([1,2,3]);
}
```

java main:
```java
context.getPolyglotBindings().putMember("searchService", searchService);
Value value = context.getBindings("js").getMember("solution_entry");
value.execute();
```
running the code showed me a very Puzzling errors
![image](https://user-images.githubusercontent.com/3231255/51724301-a44a6400-2097-11e9-970b-78c256796102.png)

**Comment by woess** [comment]
There's no support for mapping JS arrays/objects to `Collection`. If you use `List<Long>` instead, your code should work.
See [documentation for Value.as](https://www.graalvm.org/sdk/javadoc/org/graalvm/polyglot/Value.html#as-java.lang.Class-) for the list of supported mappings.

**Comment by mungco** [comment]
thanks a lot
