### ISSUE TITLE
NativeImage crashed with random Stacktrace

### ISSUE THREAD

**Issue by SystemVQ** [oracle/graal#9381]
**Describe the issue**
I compiled a NativeImage for a big project with many libraries.But I noticed the executable crashed with "Fatal error: Object with invalid hub type",the Stacktrace information for each crash is different, but ultimately all of them are related to GC. 
I found that the problem seems to be related to a socket library called “ Netty” 
I want to get detailed information to try to fix it, but the error log does not give me any information that I can understand.

**Steps to reproduce the issue**
Use Netty

**Describe GraalVM and your environment:**
 - GraalVM version: **build 17.0.12+8-LTS-jvmci-23.0-b41** 
 - JDK major version: **17**
 - OS: **Windows10 & Windows11**
 - Architecture: **AMD64**

**More details**
Full error report: https://paste.ubuntu.com/p/62Cy3KQffp/

 Extra agrs

```
                "--initialize-at-run-time=io.netty.channel.epoll",
                "--initialize-at-run-time=io.netty.channel.unix.Errors",
                "--initialize-at-run-time=io.netty.channel.unix.IovArray",
                "--initialize-at-run-time=io.netty.channel.unix.Limits",
                "--enable-url-protocols=https",
                "--native-image-info"
```

**Comment by EkkoWH** [comment]
Does your action of closing this issue mean that a solution is already available?
