### ISSUE TITLE
[GR-57127] Native Image generated by `native-image` tool is not working with ZoomBA project

### ISSUE THREAD

**Issue by nmondal** [oracle/graal#9402]
**Describe the issue**
ZoomBA is a JSR223 interpreted language, and we heavily use it.
https://gitlab.com/non.est.sacra/zoomba
Once the build is done, we tried building `native-image` and it was successful. However, the generated binary does not work - it is a language, and every parsing fails.

**Steps to reproduce the issue**
1. git clone --depth 1 https://gitlab.com/non.est.sacra/zoomba.git 
2. mvn clean install -DskipTests=true 
3. Go to `targets` folder 
4. Run the `native-image -cp ./lib  -jar zoomba.lang.core-0.3-SNAPSHOT.jar zoomba `  
5. Now run the resulting native image `./zoomba`

See this executable runs (this is much better than earlier versions where it would not even run):

```
//h brings this help 
//h key_word : shows help about the keyword 
//q quits REPL. In debug mode runs till next BreakPoint 
//v shows variables 
//c In debug mode, clear this Breakpoint 
//r loads and runs a script from REPL 
Enjoy ZoomBA...(0.3-SNAPSHOT-2024-Jul-27 14:46) running on JRE (22.0.2) 
(zoomba)x=10 
Parse Error: x=10
Options were : 
(zoomba)//q

```
Essentially parsing fails, and the build  is unusable. Try using any expression in the (zoomba) prompt.
Now, one can simply run the `java -jar zoomba-*.jar` and there would be no problem with any expression.

This blocks our usage of zoomba as a full time scripting language.

**Describe GraalVM and your environment:**

openjdk 22.0.2 2024-07-16
OpenJDK Runtime Environment GraalVM CE 22.0.2+9.1 (build 22.0.2+9-jvmci-b01)
OpenJDK 64-Bit Server VM GraalVM CE 22.0.2+9.1 (build 22.0.2+9-jvmci-b01, mixed mode, sharing)

**Comment by selhagani** [comment]
Hi @nmondal, Thank you for reaching out to us.
Could you please tell me which OS and architecture are you using?
Thank you

**Comment by nmondal** [comment]
hi @selhagani 
Thank you for the response!
This is happening with ZorinOS, which is a version of Ubuntu AMD 64.
In my KDE Neon, I get this error:

https://github.com/oracle/graal/issues/7717

```
Failed generating 'zoomba.lang.core-0.3-SNAPSHOT' after 1m 24s.

The build process encountered an unexpected error:

> java.lang.RuntimeException: There was an error linking the native image: Linker command exited with 1

Based on the linker command output, possible reasons for this include:
1. It appears as though libz:.a is missing. Please install it.

```

**Comment by selhagani** [comment]
I was able to reproduce the issue.
I will keep you updated with our findings as soon as possible/
Thank you.

**Comment by selhagani** [comment]
Hi @nmondal , 

I just used the tracing agent and the generated native image works just fine. 
You can do so by running the following commands after going to the target's folder:

`java -agentlib:native-image-agent=config-output-dir=META-INF/native-image -jar zoomba.lang.core-0.3-SNAPSHOT.jar`
`native-image --no-fallback -H:ConfigurationFileDirectories=META-INF/native-image -jar zoomba.lang.core-0.3-SNAPSHOT.jar`
`./zoomba.lang.core-0.3-SNAPSHOT`
