### ISSUE TITLE
VERBOSE_GRAALVM_LAUNCHERS as environment property

### ISSUE THREAD

**Issue by johanvos** [oracle/graal#941]
Is there a reason why NativeImage.verbose is obtained by System.getenv("VERBOSE_GRAALVM_LAUNCHERS") instead of System.getProperty("VERBOSE_GRAALVM_LAUNCHERS")? 

The latter would make it easier for third party code that calls into NativeImage (e.g. a maven or gradle plugin) to control verbosity.

**Comment by olpaw** [comment]
I'm not happy with `VERBOSE_GRAALVM_LAUNCHERS` in any form. Instead `--verbose` should be used instead.

**Comment by olpaw** [comment]
I'd like to remove `System.getenv("VERBOSE_GRAALVM_LAUNCHERS")` from NativeImage.
@johanvos, are you ok with using `--verbose`?

**Comment by johanvos** [comment]
Would there be a way to specify it with an API? If NativeImage.build() is called using external code (e.g. the maven plugin in the repository, or another plugin started from a different VM), it would be nice to have the verbosity turned on/off programmatically.

**Comment by olpaw** [comment]
> (e.g. the maven plugin in the repository, or another plugin started from a different VM), it would be nice to have the verbosity turned on/off programmatically.

The native-image options are the API. This is also true for the `native-image-maven-plugin`.
E.g. if you use the following snippet in your `pom.xml` file
```
      <plugin>
        <groupId>com.oracle.substratevm</groupId>
        <artifactId>native-image-maven-plugin</artifactId>
        <version>1.0.0-rc12</version>
        <executions>
          <execution>
            <goals>
              <goal>native-image</goal>
            </goals>
            <phase>package</phase>
          </execution>
        </executions>
        <configuration>
          <buildArgs>
            --verbose
          </buildArgs>
        </configuration>
      </plugin>
```
the arguments passed to `NativeImage.build(config)` will contain `--verbose`.
```
[INFO] --- native-image-maven-plugin:1.0.0-rc12:native-image (default) @ app ---
[INFO] ImageClasspath Entry: one.paw:app:jar:1.0-SNAPSHOT (file:///home/pwoegere/OLabs/git/HelloMaven/target/app-1.0-SNAPSHOT.jar)
[INFO] WorkingDirectory: /home/pwoegere/OLabs/git/HelloMaven/target
[INFO] ImageClasspath: /home/pwoegere/OLabs/git/HelloMaven/target/app-1.0-SNAPSHOT.jar
[INFO] BuildArgs: [-H:Class=one.paw.App, --verbose]
Executing [
/home/pwoegere/OLabs/labsjdk1.8.0_192-jvmci-0.54/jre/bin/java \
-XX:+UnlockExperimentalVMOptions \
...
[one.paw.app:28447]        image:     332.84 ms
[one.paw.app:28447]        write:      61.83 ms
[one.paw.app:28447]      [total]:  13,166.85 ms
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
...
```
For more info see https://github.com/oracle/graal/blob/ee6b632e002e96a10071d1d939812c20f8b5f3f5/substratevm/src/native-image-maven-plugin/src/main/java/com/oracle/substratevm/NativeImageMojo.java#L238

**Comment by olpaw** [comment]
I.e the API for native image is `NativeImage.BuildConfiguration` that you pass to `NativeImage.build`.

**Comment by johanvos** [comment]
sounds good.
