### ISSUE TITLE
[GR-56749] Missing Documentation Video/Tutorial 

### ISSUE THREAD

**Issue by walksanatora** [oracle/graal#9414]
**Describe the issue**
on the guide/tutorial page on how to implement a new languague truffle the video linked on the page has been removed at some point by youtube

**Steps to reproduce the issue**
Please include both build steps as well as run steps
1. head to [https://www.graalvm.org/latest/graalvm-as-a-platform/language-implementation-framework/LanguageTutorial/](https://www.graalvm.org/latest/graalvm-as-a-platform/language-implementation-framework/LanguageTutorial/)
2. try to play the video
3. `This video is no longer available because the YouTube account associated with this video has been terminated.`

**Describe GraalVM and your environment:**
N/A

**More details**
I want to implement a truffle for another architecture (uxn) but it would appear that is impossible as the docs are not very complete

**Comment by fernando-valdez** [comment]
Thanks for reporting this, @walksanatora.
I created an internal ticket to track the effort: GR-56749

**Comment by olyagpl** [comment]
The original video is now replaced by the presentation from  by Christian Humer on Dynamic Metacompilation with Truffle: [https://www.youtube.com/watch?v=pksRrON5XfU/.](https://www.youtube.com/watch?v=pksRrON5XfU)
The page is updated on the latest, dev, and jdk23 docs versions:
https://www.graalvm.org/latest/graalvm-as-a-platform/language-implementation-framework/LanguageTutorial/
