### ISSUE TITLE
[trffule-dsl] An actual ....NodeGen source/class file

### ISSUE THREAD

**Issue by TisonKun** [oracle/graal#944]
With truffle-dsl we can generate node class. Such generated classes are named with a suffix "...NodeGen". Sometimes I'd like to see what these generated classes looks like. It is an approach to achieve it?

**Comment by boris-spas** [comment]
**NOTE**: You generally should not care about the generated source, and you definitely should not rely on any assumption/conclusion you can make looking at the generated code. With that said:

The DSL does actually create the java files for "*NodeGen" classes. For example, in SimpleLanguage you can find them in `./language/target/generated-sources/annotations/` (eg: `./language/target/generated-sources/annotations/com/oracle/truffle/sl/nodes/expression/SLSubNodeGen.java`)

**Comment by TisonKun** [comment]
@boris-spas thanks for your explanation! When I am working with Intellj IDEA, the IDE complain that it cannot find such NodeGen classes. Is there a way to workaround it?

**Comment by TisonKun** [comment]
@boris-spas thanks for your explanation. Get it!
