### ISSUE TITLE
Migrate from Nashorn: create new context for multithread support

### ISSUE THREAD

**Issue by v4umak** [oracle/graal#952]
We're trying to migrate our Java + Javascript project from Nashorn to Graal. In our project we had js files which are loaded when application starts. When java application receives some event, it calls js function with this event as parameter.
As I understand according https://github.com/graalvm/graaljs/issues/59, for multithreading support we need create org.graalvm.polyglot.Context each time when we call our js function and call "eval" for js file and it's dependencies.
Because of this we should not use classes from JDK like javax.script.ScriptEngine because we cannot transfer polyglot context to them. So we should use poliglot api and our code shold be like this:

```
//once after application start 
Source source = Source.newBuilder("js",  file.toFile()).build();

//every time when we need call js function from java
try (Context context = Context.newBuilder().option("js.nashorn-compat", "true").engine(Engine.create()).build()) {
    context.eval(source);
    context.getBindings("js").getMember("a").execute(params);
}

```
Is it correct?

**Comment by chumer** [comment]
A few remarks:

1) You need to create a context for each parallel thread, not necessarily for each script.
2) You may want to allow some AST sharing between your contexts. See this: http://www.graalvm.org/docs/graalvm-as-a-platform/embed/#enable-source-caching
3) You may use the script engine API and instead enable Nashorn compatibility using `-Dpolyglot.js.nashorn-compat=true` as JVM argument. That being said we recommend using the polyglot API as it provides the most features.
4) Alternatively, you may use GraalJSScriptEngine#create to initialize the script engine from a custom polyglot Context.

**Comment by v4umak** [comment]
Thank you!
