### ISSUE TITLE
getDeclaredFields() and friends returning an empty array if class not registered for reflection

### ISSUE THREAD

**Issue by gsmet** [oracle/graal#954]
Hi,

Given a simple JavaBean class:
```java
public class MyBean {

    private String name;

    private String value;

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getValue() {
        return value;
    }

    public void setValue(String value) {
        this.value = value;
    }
}
```

In native mode, I have `MyBean.class.getDeclaredFields()` returning an empty array without throwing an exception if `MyBean` is not registered for reflection.

I would expect it to throw an error requiring some reflection declaration (obviously, same for getDeclaredMethods() and al.). Is the current behavior expected?

This is very annoying when serializing objects via various JSON libraries. If you forget to register the class for reflection, you have the following behavior:
- in JVM mode, everything works like a charm
- in native mode, the serialized object is just empty as `getDeclaredFields()` and `getDeclaredMethods()` just silently returned empty arrays. No error allowing you to catch the issue.

This with rc11.

**Comment by cstancu** [comment]
In the current implementation we don't make a distinction between a class that doesn't declare any fields and a class that declares fields but the fields were not registered for reflective access. At run time we don't currently have access to the reflection configuration. Fields (similarly methods and constructors) can be registered for reflection either in bulk via `allDeclaredFields`/`allPublicFields` or individually. One question is what should happen if only some of the fields were registered for reflection, maybe an warning could be printed.

**Comment by gsmet** [comment]
@cstancu thanks for the feedback.

IMHO, it's very misleading to have `getDeclaredFields()`/`getDeclaredMethods()` return partial results depending on the reflection registrations.

If we know the information won't be exact, I think we should probably throw an error or at least log a warning.

Basically, here is how we use reflection right now:
 * we want to access a specific field/method, then we register it specifically and we will *never* call `getDeclaredFields()`/`getDeclaredMethods()` as we address the specific element directly;
 * we want the class to be generally available for reflection (this is especially useful for JSON serialization) and in this case, we will need `getDeclaredFields()`/`getDeclaredMethods()` to work properly or throw some sort of error if we haven't registered all the fields - respectively methods - for reflection.

It seems like a less surprising behavior than the current one. I might be missing some use cases though.

**Comment by loicottet** [comment]
This is solved under the new `-H:ThrowMissingRegistrationErrors=` flag.
