### ISSUE TITLE
When using new Date() in JavaScript, if the system time is changed, the returned value is still the time before the modification

### ISSUE THREAD

**Issue by dandelion2** [oracle/graal#9554]
When using new Date() in JavaScript to get the current time and adjusting the system time during the runtime, for example, by setting it back by one hour, it is observed that the time obtained in JavaScript still corresponds to the time calculated before the modification

@Test
    public void testDate() throws IOException {
        try (Context context = Context.create()) {
            for (int i = 0; i < 100; i++) {
                context.eval(Source.newBuilder("js", "console.log(new Date())", "test").build());
                System.out.println("warming up ...");
                Thread.sleep(5000L);
            }

        } // context.close() is automatic
        catch (InterruptedException e) {
            throw new RuntimeException(e);
        }
    }

**Comment by selhagani** [comment]
Hi @dandelion2,

Thank you for getting in touch with us!

To ensure we address your issue efficiently, could you please submit it using the appropriate template found [here](https://github.com/oracle/graal/issues/new/choose)? This will help us provide you with the best support possible.

Thank you!
