### ISSUE TITLE
Add GraalVM support to Homebrew

### ISSUE THREAD

**Issue by fniephaus** [oracle/graal#959]
Now that CE binaries are publicly available, it'd be great to be able to install/upgrade it with [Homebrew](https://brew.sh/).
For this, a Homebrew cast must be maintained at https://github.com/Homebrew/homebrew-cask.
Happy to work on an initial integration, but thought I should ask for permission first.

**Comment by dpishchukhin** [comment]
you can use SDK Manager as an option (https://sdkman.io). It supports GraalVM as a part of Java SDK.

**Comment by fniephaus** [comment]
> You have to think about any interactions between homebrew (e.g. `brew doctor`) and the Graal Updater. The latter adds content to the GraalVM home directory which homebrew may not like.

The [java cask](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/java.rb) installs a JDK in `/Library/Java/JavaVirtualMachines/` and a cask for GraalVM should probably just do the same. I don't see why there could be any problem with Graal Updater and `brew doctor`.

**Comment by dougxc** [comment]
I'll admit I'm not familiar with how brew works so if it can safely install GraalVM and not be upset when another program (i.e. Graal Updater) subsequently modifies the installation directory, then all should be fine.

**Comment by shelajev** [comment]
@fniephaus would you expect it to put only java related things on the path? What about the `node` & `npm` executables? 

Do you know how brew resolves conflicts in the executable names between different casks? What if I run: 
```
brew install java
brew install graalvm
``` 

Which `java` would take precedence? I would love to see GraalVM on brew, but it'd be great if the cask is a good citizen and doesn't interfere with the other packages there.

**Comment by fniephaus** [comment]
@shelajev the [Java cask](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/java.rb) only downloads a JDK and puts it into `/Library/Java/JavaVirtualMachines/`. So it doesn't touch `$PATH`, probably for a good reason. I'd suggest to just do the same with GraalVM. `brew install graalvm` would still be more convenient than finding the release on Github, downloading it, and extracting it manually.

**Comment by abilioesteves** [comment]
Hello all! Is there any schedule for the approval of the PR above? Thanks! 

Also, the GraalVM CE has already been released. The PR should probably be updated then...

Thanks!

**Comment by abilioesteves** [comment]
Just checked the response from homebrew-cask, and they will not merge this PR. I think this issue should be closed here, then. 

Thanks!

**Comment by fniephaus** [comment]
I'm afraid https://github.com/Homebrew/homebrew-cask/pull/58492 was closed due to https://github.com/Homebrew/homebrew-cask/pull/57374#issuecomment-453760711. Also, see the discussion at https://github.com/Homebrew/homebrew-cask/issues/57387. Looks like they only support LTS releases of Java.

What we could do, however, is to add the formula to this repository. This would allow users to install GraalVM via something like `brew install oracle/graalvm/ce`.

**Comment by fniephaus** [comment]
Update: it looks like we'd need to create `github.com/oracle/homebrew-graal` to make this work ([see here](https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap#installing)). What do you think, @dougxc?

**Comment by dougxc** [comment]
Sounds good to me. @thomaswue how do we get a repo under the oracle org created nowadays?

**Comment by dougxc** [comment]
@fniephaus there is now a repo at https://github.com/graalvm/homebrew-repo that we can use for this purpose. I believe all you need to do now is open a PR on that repo.

**Comment by fniephaus** [comment]
@dougxc thanks for the swift response. The repository name, however, defines the second part of the installation command. So with https://github.com/graalvm/homebrew-repo, it would be `brew install graalvm/repo/{formula}`. [The docs](https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap) include a few tips on how to name a custom tap and formula (e.g. a unique formula name is preferred). Here are two naming suggestions:

- `brew install graalvm/ce/graalvm-ce`
- `brew install graalvm/tap/graalvm-ce`

**Comment by dougxc** [comment]
Ok, we will rename https://github.com/graalvm/homebrew-repo to https://github.com/graalvm/homebrew-tap.

**Comment by fniephaus** [comment]
@dougxc working on a PR...

**Comment by dougxc** [comment]
There is now a barebones README at https://github.com/fniephaus/homebrew-tap so you should be able to open a PR now.

**Comment by fniephaus** [comment]
Here you go: https://github.com/graalvm/homebrew-tap/pull/1

**Comment by fniephaus** [comment]
GraalVM CE can now be installed with `brew cask install graalvm/tap/graalvm-ce`! 🚀
If you run into any problems, please open an issue at https://github.com/graalvm/homebrew-tap/issues.

**Comment by vikeri** [comment]
Lately it seems you have to specify a java version:
```
brew cask install graalvm/tap/graalvm-ce-java8
```
or
```
brew cask install graalvm/tap/graalvm-ce-java11
```

**Comment by TLiese** [comment]
This installer does not export `gu` to Path

**Comment by tlight** [comment]
In order to install gu, for OSX I added the following to .bash_profile:

```
export JAVA_HOME=$(/usr/libexec/java_home -v 1.8)
export PATH=$JAVA_HOME/bin:$PATH
```
I then ran the following from my terminal:
```
source ~/.bash_profile
gu install native-image
```
