### ISSUE TITLE
Missing docker image for RC12

### ISSUE THREAD

**Issue by qdeee** [oracle/graal#960]
There is no docker image for RC12:
```
$ docker image pull oracle/graalvm-ce:1.0.0-rc12
Error response from daemon: manifest for oracle/graalvm-ce:1.0.0-rc12 not found
```

When do you plan to push it?

**Comment by mzachh** [comment]
Hi Ruslan,

thanks for the report and sorry for the delay. We will upload the image in the next days.

In the meantime you can build the same image by yourself, with the Dockerfile from: [1]

And `docker build -t oracle/graalvm-ce:1.0.0-rc12 .`

[1] https://github.com/oracle/docker-images/tree/master/GraalVM/CE/1.0.0-rc12

**Comment by qdeee** [comment]
Now I'm able to pull new image, thank you!
