### ISSUE TITLE
Trying to generate native image graalVM with quarkus app on Windows doesn't work

### ISSUE THREAD

**Issue by NotFunnyThomas** [oracle/graal#9609]
**Describe the issue**
I try to generate native image of my app Quarkus on Windows. The generation is good but not the execution because of this: java.lang.ClassNotFoundException: io.quarkus.runner.ApplicationImpl.

io.quarkus.runner.ApplicationImpl is a generated class by Quarkus in the generated-bytecode.jar used by my Main class which runs Quarkus.run(args);

And GraalVM don't find this.

I tried this in my build.gradle:

implementation files('build/quarkus-app/quarkus/generated-bytecode.jar')

but i have some errors after :

Caused by: com.oracle.svm.core.util.VMError$HostedError: Error in @InjectAccessors handling of field org.wildfly.common.net.Inet.INET4_ANY, accessors class io.quarkus.runtime.graal.Inet4AnyAccessor: found no method named set or setINET4_ANY
and this in my execution of graalvmNative :

buildArgs.add('-Djava.library.path=build/quarkus-app/quarkus')

But whithout success.

**Steps to reproduce the issue**
My repo to reproduce : https://github.com/NotFunnyThomas/GraalQuarkusBatchPoc/

**Describe GraalVM and your environment:**
 - GraalVM version **[graalvm-jdk-21.0.4]**
 - JDK major version: **[21]**
 - OS: **[Windows 10]**
 - Architecture: **[AMD64]**

**More details**

**Comment by zakkak** [comment]
Hi @NotFunnyThomas , this doesn't look like a GraalVM issue, please open a Quarkus issue using the following link instead https://github.com/quarkusio/quarkus/issues/new?assignees=&labels=kind%2Fbug%2Carea%2Fnative-image&projects=&template=bug_report_native.yml instead
