### ISSUE TITLE
AudioSystem.getMixerInfo() returns empty list in native image

### ISSUE THREAD

**Issue by kleincode** [oracle/graal#9620]
**Describe the issue**
I'm trying to find Audio devices using the Java Sound API (`javax.sound.sampled.*`). When I list the available audio mixers using `AudioSystem.getMixerInfo()`, I receive several entries on the JVM. However, in the native image, an empty array is returned, so I cannot use any audio input in the native image.

**Steps to reproduce the issue**
Please include both build steps as well as run steps
1. `git clone --depth 1 https://github.com/kleincode/GraalVM_audio_test.git`
2. `cd GraalVM_audio_test/src/main/java`
3. `javac Main.java && java Main` correctly shows the audio devices.
4. `native-image Main && ./Main` shows that zero audio mixers were found in the native image.

**Describe GraalVM and your environment:**
 - Tested with GraalVM CE 24-dev+12.1, GraalVM CE 22.0.2+9.1, GraalVM CE 21.0.2+13.1
 - JDK major version: **24, 22, 21**
 - OS: **macOS Sonoma 14.6.1**
 - Architecture: **arm64 / armv8-a** (MacBook Pro M3)

**More details**
- Full build output at https://gist.github.com/kleincode/7437d6b0f5b243f944b6d1b8925a2ae1
- There are no build or runtime errors.
- I tried using the GraalVM agent and manually configuring JNI/reflection/resources (see [README](https://github.com/kleincode/GraalVM_audio_test?tab=readme-ov-file#using-graalvm-agent)) as suggested [here](https://github.com/oracle/graal/issues/2892#issuecomment-1381284504), with no effect
- I also tried the other suggested fixes in https://github.com/oracle/graal/issues/2892 (setting `-Djava.home` and `-Djavax.sound.config.file`), with no effect

Let me know if you need any more information. Thank you.

**Comment by oubidar-Abderrahim** [comment]
This is not a GraalVM bug, the issue is missing configuration files. please check https://www.graalvm.org/latest/reference-manual/native-image/metadata/AutomaticMetadataCollection/ on how to generate and add them to your build command.

**Comment by bkacjios** [comment]
@oubidar-Abderrahim Is there something special that needs to be done then? I generated configuration files with an agent running my application. Running it with the agent results in audio working as expected. I can even see it picked up `javax.sound.sampled.spi.MixerProvider` in the resource-config.json. Yet when I build the native image it still fails to find any mixers.

I even have the following in my jni-config.json.

```json
{
  "name":"com.sun.media.sound.DirectAudioDevice",
  "methods":[{"name":"addFormat","parameterTypes":["java.util.Vector","int","int","int","float","int","boolean","boolean"] }]
},
{
  "name":"com.sun.media.sound.DirectAudioDeviceProvider$DirectAudioDeviceInfo",
  "methods":[{"name":"<init>","parameterTypes":["int","int","int","java.lang.String","java.lang.String","java.lang.String","java.lang.String"] }]
},
{
  "name":"com.sun.media.sound.PortMixerProvider$PortMixerInfo",
  "methods":[{"name":"<init>","parameterTypes":["int","java.lang.String","java.lang.String","java.lang.String","java.lang.String"] }]
},
```

**Comment by valimaties** [comment]
Hi @bkacjios , did you found any solution for this? I'm also unable to play audio sample files, even if running my jar file with agent I can play them.  I search for a solution for about two years already 😒

**Comment by bkacjios** [comment]
@valimaties nope, I gave up sadly

**Comment by valimaties** [comment]
@bkacjios 
In `reachability-metadata.json` file (this is new format) I've added these lines into `reflection` group. Seems this will load the providers, but I'm unable to play the sound, and I don't know why, there is no more errors about providers...
BTW, I had to add some initialization lines into pom file as well, in profile.

```json
{
	  "type": "com.sun.media.sound.WaveFileReader",
	  "allDeclaredConstructors": true,
	  "allPublicConstructors": true,
	  "allDeclaredMethods": true
	},
	{
	  "type": "com.sun.media.sound.AiffFileReader",
	  "allDeclaredConstructors": true,
	  "allPublicConstructors": true,
	  "allDeclaredMethods": true
	},
	{
	  "type": "com.sun.media.sound.AuFileReader",
	  "allDeclaredConstructors": true,
	  "allPublicConstructors": true,
	  "allDeclaredMethods": true
	},
	{
	  "type": "com.sun.media.sound.MpegAudioFileReader",
	  "allDeclaredConstructors": true,
	  "allPublicConstructors": true,
	  "allDeclaredMethods": true
	},
	{
	  "type": "com.sun.media.sound.FlacAudioFileReader",
	  "allDeclaredConstructors": true,
	  "allPublicConstructors": true,
	  "allDeclaredMethods": true
	},
	{
      "type": "com.sun.media.sound.SoftMidiAudioFileReader",
	  "allDeclaredConstructors": true,
	  "allPublicConstructors": true,
	  "allDeclaredMethods": true
    },
	{
      "type": "com.sun.media.sound.WaveFloatFileReader",
	  "allDeclaredConstructors": true,
	  "allPublicConstructors": true,
	  "allDeclaredMethods": true
    },
	{
      "type": "com.sun.media.sound.WaveExtensibleFileReader",
	  "allDeclaredConstructors": true,
	  "allPublicConstructors": true,
	  "allDeclaredMethods": true
    },
	{
	  "type": "com.sun.media.sound.FloatFormatConverter",
	  "allDeclaredConstructors": true,
	  "allPublicConstructors": true,
	  "allDeclaredMethods": true
	},
	{
	  "type": "com.sun.media.sound.PCMtoPCM",
	  "allDeclaredConstructors": true,
	  "allPublicConstructors": true,
	  "allDeclaredMethods": true
	},
	{
	  "type": "com.sun.media.sound.AlawCodec",
	  "allDeclaredConstructors": true,
	  "allPublicConstructors": true,
	  "allDeclaredMethods": true
	},
	{
	  "type": "com.sun.media.sound.UlawCodec",
	  "allDeclaredConstructors": true,
	  "allPublicConstructors": true,
	  "allDeclaredMethods": true
	},
```
