### ISSUE TITLE
[QUESTION] difference between attachExecutionEventFactory and attachExecutionEventListener

### ISSUE THREAD

**Issue by revintec** [oracle/graal#964]
Hi, I see there are two set of APIs dealing with instrumentation:
`com.oracle.truffle.api.instrumentation.Instrumenter#attachExecutionEventFactory`
`com.oracle.truffle.api.instrumentation.Instrumenter#attachExecutionEventListener`
What are the differences between them?

As far as I know, `attachExecutionEventFactory` covers all the functionalities provided by `attachExecutionEventListener`, and allows one to generate a `Node` to be later inserted into the AST, thus it can potentially be optimized and have better performance, while also enabling stateful instrumentation. Do I get it correctly?

If that's true, in what circumstances should we use `attachExecutionEventListener` instead of `attachExecutionEventFactory`? It seems to me that one should always prefer `attachExecutionEventFactory`, afterall the code complexity and readability is almost the same.

**Comment by chumer** [comment]
Good question. I also tend to prefer `attachExecutionEventFactory` as it gives you the most flexibility. However, it also comes with the highest footprint, as it allocates a node for each source location it is applied to. The listener version of that does not do that. The other reason for the listener is that it is a known pattern, whereas the factory pattern is a new one. New users immediately understand how a listener works, how the node factory works takes a bit longer. 

Now, is the footprint and simplicity worth a separate API? 
IMO, probably not. But one of my co-designers on the API had a strong opinion on this part, and I gave up on challenging it ;-). Fast forward to now, it is no longer worth breaking and removing the listener API.

Please close if this answers your question.

**Comment by revintec** [comment]
Thx for answering, knowing the background, I think I'll stick to the factory one.
About the footprint, if the API is more flexible, we can return the same `ExecutionEventNode` instance every time, like this(`EventContext` parameter added to `onEnter`'s signature):
```java
instrumenter.attachExecutionEventFactory(null,
    (eventContext4Traversal)->new ExecutionEventNode(){ // or a singleton
        /** @param eventContext4Execution may differ from eventContext4Traversal */
        protected void onEnter(EventContext eventContext4Execution,VirtualFrame frame){}
});
```
This of course requires proper changes made to `com.oracle.truffle.api.instrumentation.ProbeNode.EventProviderChainNode#innerOnEnter`, but I guess that'll also make the API a little harder to understand.

IMHO, with proper documentation and sample code, the factory one should be no harder than the listener one, and we can have a unified way of instrumentation.

**Comment by chumer** [comment]
> About the footprint, if the API is more flexible, we can return the same `ExecutionEventNode` instance every time

Note that you can't share the same AST node in multiple locations at the moment. This will fail with an `IllegalStateException`. However I am adding a feature at the moment to allows nodes to be non-adoptable, so they would become sharable between multiple locations. But without that feature, you can't.

**Comment by revintec** [comment]
Thanks for the info, looking forward to this new feature. And I've edited my original code snippet to better reflect the intention.
