### ISSUE TITLE
Java Runtime Error (SIGILL) on AWS Graviton using GraalVM JDK 17

### ISSUE THREAD

**Issue by RuanNunes** [oracle/graal#9661]
I'm encountering a fatal error in my Spring Boot applications running on AWS Graviton instances using GraalVM JDK. The application crashes and restarts with the following error:

```
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGILL (0x4) at pc=0x0000ffffa2d31300, pid=1, tid=29
#
# JRE version: OpenJDK Runtime Environment GraalVM CE 17.0.9+9.1 (17.0.9+9) (build 17.0.9+9-jvmci-23.0-b22)
# Java VM: OpenJDK 64-Bit Server VM GraalVM CE 17.0.9+9.1 (17.0.9+9-jvmci-23.0-b22, mixed mode, tiered, jvmci, jvmci compiler, compressed oops, compressed class ptrs, serial gc, linux-aarch64)
# Problematic frame:
# C  0x0000ffffa2d31300
#
# Core dump will be written. Default location: /app/core.1
#
# An error report file with more information is saved as:
# /app/hs_err_pid1.log
#
# If you would like to submit a bug report, please visit:
#   https://github.com/oracle/graal/issues
#
[error occurred during error reporting (), id 0x5, SIGTRAP (0x5) at pc=0x0000ffffa28ab0f0]
```

Any guidance or help would be appreciated!

**Comment by RuanNunes** [comment]
Thank you for your response. I will perform an update and get back to you if the issue persists.

**Comment by RuanNunes** [comment]
Hi @selhagani , I checked the version and I am using the following image: ghcr.io/graalvm/jdk-community:17.0.9-ol9. From what I verified, this is the most recent version for Java 17.

**Comment by selhagani** [comment]
Unfortunately, that’s an older version of GraalVM. For the Community Edition, you’ll want to use [GraalVM for JDK 23 Community 23.0.0](https://github.com/graalvm/graalvm-ce-builds/releases/tag/jdk-23.0.0), as it includes all the latest updates.

**Comment by RuanNunes** [comment]
Sorry for the delay in responding; I’ve been on vacation for the past few days.
I updated the version according to the recommendation mentioned above, but the same issue persists.

Just to clarify, this issue occurs on ARM processors (AWS Graviton). However, tests conducted on other ARM processors, such as the M1, do not reproduce this issue.

`2024-11-18 14:08:50.685 [http-nio-8080-exec-1]  INFO [ms-loan-hub-bff,e7bb450a72073663,e7bb450a72073663] org.springframework.web.servlet.DispatcherServlet : Completed initialization in 2 ms
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGILL (0x4) at pc=0x0000ffffb596f4a0, pid=1, tid=26
#
# JRE version: OpenJDK Runtime Environment GraalVM CE 23.0.1+11.1 (23.0.1+11) (build 23.0.1+11-jvmci-b01)
# Java VM: OpenJDK 64-Bit Server VM GraalVM CE 23.0.1+11.1 (23.0.1+11-jvmci-b01, mixed mode, tiered, jvmci, jvmci compiler, compressed oops, compressed class ptrs, serial gc, linux-aarch64)
# Problematic frame:
# C  0x0000ffffb596f4a0
#
# Core dump will be written. Default location: Core dumps may be processed with "/usr/lib/systemd/systemd-coredump %P %u %g %s %t %c %h" (or dumping to /app/core.1)
#
# An error report file with more information is saved as:
# /app/hs_err_pid1.log
#
# If you would like to submit a bug report, please visit:
#   https://github.com/oracle/graal/issues
#
[error occurred during error reporting (), id 0x5, SIGTRAP (0x5) at pc=0x0000ffffb54822dc]`
