### ISSUE TITLE
Comprar viagra

### ISSUE THREAD

**Issue by fernichum** [oracle/graal#9685]
**Feature request**

Please include the following information:

**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. E.g. I'm always frustrated when [...]

**Describe the solution you'd like.**

**Describe who do you think will benefit the most.**
GraalVM users, GraalVM contributors, developers of libraries and frameworks which depend on GraalVM, or somebody else?

**Describe alternatives you've considered.**

**Additional context.**
Add any other context about the feature request here.
For example, link to the relevant projects, documentation, standards.

**Express whether you'd like to help contributing this feature**
If you'd like to contribute, please read the [contribution guide](https://www.graalvm.org/community/contributors/).

===================================
Compra viagra en España aquí: [Comprar viagra muy barato](https://www.awin1.com/cread.php?awinmid=11046&awinaffid=576839&ued=https%3A%2F%2Fwww.promofarma.com%2Fes%2Fsearch%3Fq%3Dviagra)
===================================

**Comment by mukel** [comment]
Spam, already reported, please ignore!
