### ISSUE TITLE
Should allow access to GraalVM for JDK 22 documentation

### ISSUE THREAD

**Issue by linghengqian** [oracle/graal#9699]
**Feature request**

Please include the following information:

**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. E.g. I'm always frustrated when [...]

- No. Maybe https://github.com/apache/shardingsphere/pull/32916 .

**Describe the solution you'd like.**

- Should allow access to GraalVM for JDK 22 documentation.
- Now open https://www.graalvm.org/docs/archives/ and go to the documentation for `GraalVM For JDK 22`.
- ![image](https://github.com/user-attachments/assets/65b757c8-34ec-45ae-90e3-78a5e4d9eafc)
- The corresponding https://www.graalvm.org/jdk22/ returns 404. This doesn’t make sense.
- ![image](https://github.com/user-attachments/assets/9aba27f5-cab6-49ea-87dc-a72c32f1cb6f)

**Describe who do you think will benefit the most.**
GraalVM users, GraalVM contributors, developers of libraries and frameworks which depend on GraalVM, or somebody else?

- GraalVM users.

**Describe alternatives you've considered.**

- Null.

**Additional context.**
Add any other context about the feature request here.
For example, link to the relevant projects, documentation, standards.

- Null.

**Express whether you'd like to help contributing this feature**
If you'd like to contribute, please read the [contribution guide](https://www.graalvm.org/community/contributors/).

- I would say the documentation seems to exist in a closed source git?

**Comment by oubidar-Abderrahim** [comment]
Thank you for reaching out about this, but this is an expected behavior. 
JDK22 is not an LTS version. So once JDK23 was released, JDK22 was no longer supported, and thus we removed the corresponding documentation from our website. 
You can still access it using archive (as you demonstrated) which is the expected behavior

**Comment by linghengqian** [comment]
> Thank you for reaching out about this, but this is an expected behavior. JDK22 is not an LTS version. So once JDK23 was released, JDK22 was no longer supported, and thus we removed the corresponding documentation from our website. You can still access it using archive (as you demonstrated) which is the expected behavior

- Where is `archive`? Clicking `archive` directly leads to https://www.graalvm.org/jdk22/ with 404 error.

**Comment by oubidar-Abderrahim** [comment]
Sorry, I see now the issue.

**Comment by oubidar-Abderrahim** [comment]
@olyagpl could you please check the link for JDK22 documentation in the archive section? it seems it is not working properly.

**Comment by olyagpl** [comment]
@oubidar-Abderrahim, the documentation for JDK 20 is now online: https://www.graalvm.org/jdk22/. It was published and then accidentally rewritten. 
<img width="1508" alt="Screenshot 2024-09-20 at 14 08 09" src="https://github.com/user-attachments/assets/ab8f7cf5-a64e-4c82-8fbd-b6c537261e81">
Olga

**Comment by linghengqian** [comment]
- @olyagpl Late reply... At what URL is the relevant fix located? I navigated from https://www.graalvm.org/docs/archives/ to https://www.graalvm.org/jdk22/ but still get `Page not found`.
- ![image](https://github.com/user-attachments/assets/99c36230-3269-4a7b-a2e3-776b4d259a9a)

**Comment by linghengqian** [comment]
- Since no one responded, I've opened https://github.com/oracle/graal/issues/9851 .
