### ISSUE TITLE
[GR-58466] java --enable-preview MyClass.java fails in graalvm 23

### ISSUE THREAD

**Issue by mikael2** [oracle/graal#9708]
public class MyClass {
   public static final void main(String[] argv) {
      System.out.println("Hello, World!");
   }
}

--

java --enable-preview MyClass.java fails with:
error: exporting a package from system module java.base is not allowed with --release
1 error
error: compilation failed
 

**Describe GraalVM and your environment:**
java --version
java 23 2024-09-17
Java(TM) SE Runtime Environment Oracle GraalVM 23+37.1 (build 23+37-jvmci-b01)
Java HotSpot(TM) 64-Bit Server VM Oracle GraalVM 23+37.1 (build 23+37-jvmci-b01, mixed mode, sharing)

**Comment by fniephaus** [comment]
Thanks for filling a ticket for this. We'll look into a fix for this very soon.

**Comment by oubidar-Abderrahim** [comment]
See: https://bugs.openjdk.org/browse/JDK-8340655
