### ISSUE TITLE
C++ support

### ISSUE THREAD

**Issue by cowwoc** [oracle/graal#972]
Hi. It's 2019. If we're going to deprecate JNI in favor of something like Graal, how about supporting C++ as a first-class citizen? :)

**Comment by tarsa** [comment]
Hi,

Where did you get the info that Graal is going to replace JNI?

Replacement for JNI is in the scope of Project Panama: http://openjdk.java.net/projects/panama/ 

Graal is more about cooperation between languages in sanboxed polyglot environment. For running C++ within Graal you have Sulong: https://github.com/oracle/graal/tree/master/sulong

**Comment by cowwoc** [comment]
@tarsa 

> Where did you get the info that Graal is going to replace JNI?

I read https://github.com/oracle/graal/blob/master/substratevm/JNI.md which said:

> By default, the JNI implementation is not enabled and not built into Substrate VM images.

I took this to mean that JNI is being deprecated. Having re-read this page in context of Substrate VM I understand that this probably isn't what was meant. Sorry.

> Graal is more about cooperation between languages in sand-boxed polyglot environment. For running C++ within Graal you have Sulong: https://github.com/oracle/graal/tree/master/sulong

Very cool. Thank you.

**Comment by cstancu** [comment]
It is not a goal of SubstrateVM to deprecate `JNI`. However we explore alternative techniques to express and interact with native code. See for example https://github.com/oracle/graal/blob/master/substratevm/ImplementingNativeMethodsInJavaWithSVM.md.

By the way the `JNI` support is now enabled by default in SubstrateVM. We will update the documentation to reflect that.
