### ISSUE TITLE
[GR-58542] [Native Image] handling `--version` is not consistent 

### ISSUE THREAD

**Issue by vvlevchenko** [oracle/graal#9771]
### Describe the Issue

`--version` with composition with other options report errors in consistent, depending on the way additional options are provided. e.g.
```
~/.sdkman/candidates/java/24.ea.13-graal/bin/native-image --version -o 1.txt
Error: Option --version cannot be combined with other options.
```

and 
```
NATIVE_IMAGE_OPTIONS="-o 1.txt" ~/.sdkman/candidates/java/24.ea.13-graal/bin/native-image --version
Error: Cannot specify main class in environment variable NATIVE_IMAGE_OPTIONS
```

### Using the latest version of GraalVM can resolve many issues.

- [ ] I tried with the [latest version](https://www.graalvm.org/downloads/) of GraalVM.

### GraalVM Version

```
 ~/.sdkman/candidates/java/24.ea.13-graal/bin/java -version
java version "24" 2025-03-18
Java(TM) SE Runtime Environment Oracle GraalVM 24-dev+14.1 (build 24+14-jvmci-b01)
Java HotSpot(TM) 64-Bit Server VM Oracle GraalVM 24-dev+14.1 (build 24+14-jvmci-b01, mixed mode, sharing)
```

### Operating System and Version

Darwin DE-UNIT-1497 23.6.0 Darwin Kernel Version 23.6.0: Mon Jul 29 21:13:04 PDT 2024; root:xnu-10063.141.2~1/RELEASE_ARM64_T6020 arm64

### Build Command

```
Darwin DE-UNIT-1497 23.6.0 Darwin Kernel Version 23.6.0: Mon Jul 29 21:13:04 PDT 2024; root:xnu-10063.141.2~1/RELEASE_ARM64_T6020 arm64
```

### Expected Behavior

It'd be better to ignore all options in case of `--version`, that let use `NATIVE_IMAGE_OPTIONS` with build-native-tools more freely. 

### Actual Behavior

```
~/.sdkman/candidates/java/24.ea.13-graal/bin/native-image --version -o 1.txt
Error: Option --version cannot be combined with other options.
```

and 
```
NATIVE_IMAGE_OPTIONS="-o 1.txt" ~/.sdkman/candidates/java/24.ea.13-graal/bin/native-image --version
Error: Cannot specify main class in environment variable NATIVE_IMAGE_OPTIONS
```

### Steps to Reproduce

`native-image --version -o 1.txt`
or
`NATIVE_IMAGE_OPTIONS="-o 1.txt" native-image --version`

**Comment by selhagani** [comment]
Hi @vvlevchenko, 

Thank you for reaching out to us. I tested the cases you provided and I confirm the outcome you observed. We'll take a closer look into this and I'll make sure to keep you updated.
