### ISSUE TITLE
[Native Image] -Dsun.security.jgss.native=true is not getting set in native image 

### ISSUE THREAD

**Issue by yogeshkumargeek** [oracle/graal#9778]
### Describe the Issue

Hi graalvm team,

We are trying to build a graalvm native image of our application from micronaut.

**While executing the Kerberos authentication --> we are seeing the following error
where the GSSContext is not getting instantiated			
It seems -Dsun.security.jgss.native=true this property is not getting set in the native image**	
		
```
micronautVersion=4.6.2
kotlinVersion=1.9.25
```

### Using the latest version of GraalVM can resolve many issues.

- [ ] I tried with the [latest version](https://www.graalvm.org/downloads/) of GraalVM.

### GraalVM Version

OpenJDK Runtime Environment GraalVM CE 21.0.2+13.1

### Operating System and Version

linux

### Diagnostic Flag Confirmation

- [ ] I tried the `-H:ThrowMissingRegistrationErrors=` flag.

### Run Command

./gradlew nativeCompile

### Expected Behavior

Expect sun.security.jgss.native flag to set as true

### Actual Behavior

Actual behavior should be GSSContext should return an instance while calling it 

### Steps to Reproduce

Use this build args 
```
buildArgs.add('--verbose')
buildArgs.add('--strict-image-heap')
buildArgs.add('--add-opens java.base/java.lang=ALL-UNNAMED') //for reflection
buildArgs.add('--enable-native-access')
buildArgs.add('-Dsun.security.jgss.native=true')
buildArgs.add('-H:AdditionalSecurityProviders=sun.security.jgss.SunProvider')
buildArgs.add('-H:IncludeResourceBundles=sun.security.util.Resources')
buildArgs.add('-H:+EnableSecurityServicesFeature')
```

### Additional Context

This is the warning received while running nativeCompile command  
WARNING: Unknown module: -Dsun.security.jgss.native=true specified to --enable-native-access

### Run-Time Log Output and Error Messages

14:13:25.234 [default-nioEventLoopGroup-1-2] ERROR i.m.http.server.RouteExecutor - Unexpected error occurred: null
java.lang.NullPointerException: null
        at java.security.jgss@21.0.2/sun.security.jgss.GSSContextImpl.acceptSecContext(GSSContextImpl.java:339)
        at java.security.jgss@21.0.2/sun.security.jgss.GSSContextImpl.acceptSecContext(GSSContextImpl.java:303)

**Comment by yogeshkumargeek** [comment]
Hi @selhagani , Can you help with this issue ?

**Comment by oubidar-Abderrahim** [comment]
Thank you for reaching out, if you use `native-image --help` you can see the following  
```
 --enable-native-access               <module name>[,<module name>...]
                                                     modules that are permitted to perform restricted native operations.
                                                     <module name> can also be ALL-UNNAMED.
```
so when you specify `--enable-native-access` as an argument, the following argument is expected to be the module name, yet it finds `-Dsun.security.jgss.native=true` which is not a valid module name, hence the error: `WARNING: Unknown module: -Dsun.security.jgss.native=true specified to --enable-native-access`

**Comment by yogeshkumargeek** [comment]
Hi @oubidar-Abderrahim , Even after removing --enable-native-access , Gss Context is not getting initialized and seeing the same null pointer exception stated earlier .
Please help in fixing that
