### ISSUE TITLE
[Native Image] GSS context is not getting initialized in native image 

### ISSUE THREAD

**Issue by yogeshkumargeek** [oracle/graal#9805]
### Describe the Issue

I wanted to use the GSS context for kerberos token verification. 
The normal gradlew run is working correctly with micronaut and I am able to authenticate the  token
But , not able to do it in the native Image 

### Using the latest version of GraalVM can resolve many issues.

- [ ] I tried with the [latest version](https://www.graalvm.org/downloads/) of GraalVM.

### GraalVM Version

OpenJDK Runtime Environment GraalVM CE 21.0.2+13.1

### Operating System and Version

linux

### Diagnostic Flag Confirmation

- [ ] I tried the `-H:ThrowMissingRegistrationErrors=` flag.

### Run Command

./gradlew nativeCompile

### Expected Behavior

Gsscontext should be initalized 

### Actual Behavior

```
21:28:18.451 [default-nioEventLoopGroup-1-4] ERROR i.m.http.server.RouteExecutor - Unexpected error occurred: null
java.lang.NullPointerException: null
        at java.security.jgss@21.0.2/sun.security.jgss.GSSContextImpl.acceptSecContext(GSSContextImpl.java:339)
        at java.security.jgss@21.0.2/sun.security.jgss.GSSContextImpl.acceptSecContext(GSSContextImpl.java:303)
```

### Steps to Reproduce

buildArgs.add('--verbose')
buildArgs.add('--strict-image-heap')
buildArgs.add('--add-opens java.base/java.lang=ALL-UNNAMED') //for reflection
buildArgs.add('--enable-native-access')
buildArgs.add('-Dsun.security.jgss.native=true')
buildArgs.add('-H:AdditionalSecurityProviders=sun.security.jgss.SunProvider')
buildArgs.add('-H:IncludeResourceBundles=sun.security.util.Resources')
buildArgs.add('-H:+EnableSecurityServicesFeature')

**Comment by yogeshkumargeek** [comment]
Linked issue : https://github.com/oracle/graal/issues/9778

**Comment by oubidar-Abderrahim** [comment]
Hi, Please provide a reproducer to this issue

**Comment by yogeshkumargeek** [comment]
Hi , @oubidar-Abderrahim ,
When we are running the micronaut application, using ./gradlew run , we are able to get the GSS context and authenticate the token

But when creating a native executable using ./gradlew nativeCompile 
args used in build.gradle 
```
buildArgs.add('--verbose')
buildArgs.add('--strict-image-heap')
buildArgs.add('--add-opens java.base/java.lang=ALL-UNNAMED') //for reflection
buildArgs.add('--enable-native-access')
buildArgs.add('-Dsun.security.jgss.native=true')
buildArgs.add('-H:AdditionalSecurityProviders=sun.security.jgss.SunProvider')
buildArgs.add('-H:IncludeResourceBundles=sun.security.util.Resources')
buildArgs.add('-H:+EnableSecurityServicesFeature')
```
Then we are seeing this error : 
```
21:28:18.451 [default-nioEventLoopGroup-1-4] ERROR i.m.http.server.RouteExecutor - Unexpected error occurred: null
java.lang.NullPointerException: null
        at java.security.jgss@21.0.2/sun.security.jgss.GSSContextImpl.acceptSecContext(GSSContextImpl.java:339)
        at java.security.jgss@21.0.2/sun.security.jgss.GSSContextImpl.acceptSecContext(GSSContextImpl.java:303)
```
Code : 
```
import org.ietf.jgss.GSSContext;
import org.ietf.jgss.GSSCredential;
import org.ietf.jgss.GSSException;
import org.ietf.jgss.GSSManager;
import org.ietf.jgss.GSSName;

GSSManager gssManager = GSSManager.getInstance();   
GSSContext gssContext = gssManager.createContext((GSSCredential)null);   Not able to set context here 
```

**Comment by yogeshkumargeek** [comment]
@oubidar-Abderrahim , Have seen others also facing similar issue 
[https://github.com/oracle/graal/issues/8674](https://github.com/oracle/graal/issues/8674) 
Please help

**Comment by oubidar-Abderrahim** [comment]
@yogeshkumargeek we would be able to help you better if you share a reproducer code to this issue. Thank you

**Comment by oubidar-Abderrahim** [comment]
If this is a similar issue to #8674 then please follow-up on that issue instead

**Comment by oubidar-Abderrahim** [comment]
Closing for duplication, duplicates #8674

**Comment by yogeshkumargeek** [comment]
Hey @oubidar-Abderrahim , Getting no response on that issue , even after follow ups .
Kindly expedite the process
