### ISSUE TITLE
[Native Image] Not able to launch native App created using SWT

### ISSUE THREAD

**Issue by shireeshakalle** [oracle/graal#9810]
### Describe the Issue

I'm getting the following exception when I try to launch the native app which created using swt.

SWT version:3.126.0
JDK:21
GraalVM Version:graalvm-jdk-21.0.4+8.1
 
When I try to load shell = new Shell(SWT.CLOSE | SWT.MIN);I'm getting the following error.
I'm passing all config files(proxy-config.json, reflect-config.json, jni-config.json, resource-config.json)  

Exception in thread "main" java.lang.NoSuchFieldError: org.eclipse.swt.internal.win32.GESTURECONFIG.dwBlock
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.jni.functions.JNIFunctions$Support.getFieldID(JNIFunctions.java:1357)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.jni.functions.JNIFunctions.GetFieldID(JNIFunctions.java:449)
        at org.eclipse.swt.internal.win32.OS.SetGestureConfig(Native Method)
        at org.eclipse.swt.widgets.Control.checkGesture(Control.java:692)
        at org.eclipse.swt.widgets.Control.createWidget(Control.java:709)
        at org.eclipse.swt.widgets.Scrollable.createWidget(Scrollable.java:160)
        at org.eclipse.swt.widgets.Decorations.createWidget(Decorations.java:375)
        at org.eclipse.swt.widgets.Shell.<init>(Shell.java:318)
        at org.eclipse.swt.widgets.Shell.<init>(Shell.java:281)
        at org.eclipse.swt.widgets.Shell.<init>(Shell.java:207).

 Can someone please help me on this!!!

### Using the latest version of GraalVM can resolve many issues.

- [ ] I tried with the [latest version](https://www.graalvm.org/downloads/) of GraalVM.

### GraalVM Version

I have tried with 
1.graalvm-jdk-21.0.4+8.1, java 21 version and 
2.Java 17 and graalvm-ce-java17-22.3.1.
 

### Operating System and Version

Windows 11

### Diagnostic Flag Confirmation

- [ ] I tried the `-H:ThrowMissingRegistrationErrors=` flag.

### Run Command

just double click on native image.

### Expected Behavior

it should launch an app with login credentials.

### Actual Behavior

its throwing an error which is mentioned above.

### Steps to Reproduce

Just create simple swt application  to open dialogue box and run native image.

**Comment by shireeshakalle** [comment]
Here is the sample code to reproduce the issue.

public class SimpleShell {
    public static void main(String[] args) {
    	try {
			// Create display and shell
			Display display = new Display();
			Shell shell = new Shell(display, SWT.SHELL_TRIM); // Adds min, max, and close buttons
 
			// Set the shell title
			shell.setText("SWT Shell with Min/Max/Close");
 
			// Set size and open the shell
			shell.setSize(400, 300);
			shell.open();
 
			// Event loop to keep shell open
			while (!shell.isDisposed()) {
			    if (!display.readAndDispatch()) {
			        display.sleep();
			    }
			}
 
			// Dispose the display when shell is closed
			display.dispose();
			System.out.println("....end....");
		} catch (Exception e) {
			System.out.println("....error....");
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
    }
}

Please any one help me on this

**Comment by oubidar-Abderrahim** [comment]
Hi, can you please provide a complete reproducer? the example you shared is missing the imports and the dependencies needed to compile it

**Comment by shireeshakalle** [comment]
package test;
import org.eclipse.swt.SWT;
import org.eclipse.swt.widgets.Display;
import org.eclipse.swt.widgets.Shell;
 
public class SimpleShell {
    public static void main(String[] args) {
    	try {
			// Create display and shell
			Display display = new Display();
			Shell shell = new Shell(display, SWT.SHELL_TRIM); // Adds min, max, and close buttons
 
			// Set the shell title
			shell.setText("SWT Shell with Min/Max/Close");
 
			// Set size and open the shell
			shell.setSize(400, 300);
			shell.open();
 
			// Event loop to keep shell open
			while (!shell.isDisposed()) {
			    if (!display.readAndDispatch()) {
			        display.sleep();
			    }
			}
 
			// Dispose the display when shell is closed
			display.dispose();
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
    }
}                      



<dependency>
			<groupId>
				org.eclipse.platform</groupId>
			<artifactId>org.eclipse.swt.win32.win32.x86_64</artifactId>
			<version>
				3.126.0</version>
			
		</dependency>



Please find the sample code and SWT dependency which I have used

**Comment by shireeshakalle** [comment]
@oubidar-Abderrahim  Any update please let me know ?

**Comment by oubidar-Abderrahim** [comment]
I was able to build the provided example as a native-image and run it without issues, here are the steps taken:

1 - Created a simple maven architecture
2 - add `org.eclipse.swt.win32.win32.x86_64 version: 3.126.0` as a dependency to pom.xml
3 - build a fat jar using maven-assembly-plugin
4 - run the app to generate the Metadata files using: `java -agentlib:native-image-agent=config-merge-dir=configs -jar target\SimpleShell-0.0.1-SNAPSHOT-jar-with-dependencies.jar`
5 - build the image using: `native-image -H:ConfigurationFileDirectories=configs --no-fallback -Djava.awt.headless=false -jar target\SimpleShell-0.0.1-SNAPSHOT-jar-with-dependencies.jar`
6 - execute the generated image

This is the Main app in src\main\java\test\SimpleShell.java (same code as above)
```
package test;
import org.eclipse.swt.SWT;
import org.eclipse.swt.widgets.Display;
import org.eclipse.swt.widgets.Shell;

public class SimpleShell {
    public static void main(String[] args) {
    	try {
			// Create display and shell
			Display display = new Display();
			Shell shell = new Shell(display, SWT.SHELL_TRIM); // Adds min, max, and close buttons
 
			// Set the shell title
			shell.setText("SWT Shell with Min/Max/Close");
 
			// Set size and open the shell
			shell.setSize(400, 300);
			shell.open();
 
			// Event loop to keep shell open
			while (!shell.isDisposed()) {
			    if (!display.readAndDispatch()) {
			        display.sleep();
			    }
			}
 
			// Dispose the display when shell is closed
			display.dispose();
			System.out.println("....end....");
		} catch (Exception e) {
			System.out.println("....error....");
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
    }
}
```
This is the pom.xml content:
```
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>test</groupId>
  <artifactId>SimpleShell</artifactId>
  <version>0.0.1-SNAPSHOT</version>

  <name>SimpleShell</name>
  <url>http://maven.apache.org</url>

  <properties>
     <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
     <maven.compiler.source>21</maven.compiler.source>
     <maven.compiler.target>21</maven.compiler.target>
	 <main.class>test.SimpleShell</main.class>
  </properties>

  <build>
	<plugins>
		<plugin>
			<groupId>org.apache.maven.plugins</groupId>
			<artifactId>maven-assembly-plugin</artifactId>
			<version>3.3.0</version>
			<configuration>
				<descriptorRefs>
					<descriptorRef>jar-with-dependencies</descriptorRef>
				</descriptorRefs>
				<archive>
					<manifest>
						<addClasspath>true</addClasspath>
						<mainClass>test.SimpleShell</mainClass>
					</manifest>
				</archive>
			</configuration>
			<executions>
				<execution>
					<id>assemble-all</id>
					<phase>package</phase>
					<goals>
						<goal>single</goal>
					</goals>
				</execution>
			</executions>
		</plugin>
	</plugins>
  </build>
  
	<dependencies>
		<!-- https://mvnrepository.com/artifact/org.eclipse.platform/org.eclipse.swt.win32.win32.x86_64 -->
			<dependency>
				<groupId>org.eclipse.platform</groupId>
				<artifactId>org.eclipse.swt.win32.win32.x86_64</artifactId>
				<version>3.126.0</version>
			</dependency>
	</dependencies>
</project>
```
The testing was done on a Windows 11 machine using Oracle GraalVM for JDK 21.0.5
```
java version "21.0.5" 2024-10-15 LTS
Java(TM) SE Runtime Environment Oracle GraalVM 21.0.5+9.1 (build 21.0.5+9-LTS-jvmci-23.1-b48)
Java HotSpot(TM) 64-Bit Server VM Oracle GraalVM 21.0.5+9.1 (build 21.0.5+9-LTS-jvmci-23.1-b48, mixed mode, sharing)
```

**Comment by shireeshakalle** [comment]
> I was able to build the provided example as a native-image and run it without issues, here are the steps taken:
> 
> 1 - Created a simple maven architecture 2 - add `org.eclipse.swt.win32.win32.x86_64 version: 3.126.0` as a dependency to pom.xml 3 - build a fat jar using maven-assembly-plugin 4 - run the app to generate the Metadata files using: `java -agentlib:native-image-agent=config-merge-dir=configs -jar target\SimpleShell-0.0.1-SNAPSHOT-jar-with-dependencies.jar` 5 - build the image using: `native-image -H:ConfigurationFileDirectories=configs --no-fallback -Djava.awt.headless=false -jar target\SimpleShell-0.0.1-SNAPSHOT-jar-with-dependencies.jar` 6 - execute the generated image
> 
> This is the Main app in src\main\java\test\SimpleShell.java (same code as above)
> 
> ```
> package test;
> import org.eclipse.swt.SWT;
> import org.eclipse.swt.widgets.Display;
> import org.eclipse.swt.widgets.Shell;
> 
> public class SimpleShell {
>     public static void main(String[] args) {
>     	try {
> 			// Create display and shell
> 			Display display = new Display();
> 			Shell shell = new Shell(display, SWT.SHELL_TRIM); // Adds min, max, and close buttons
>  
> 			// Set the shell title
> 			shell.setText("SWT Shell with Min/Max/Close");
>  
> 			// Set size and open the shell
> 			shell.setSize(400, 300);
> 			shell.open();
>  
> 			// Event loop to keep shell open
> 			while (!shell.isDisposed()) {
> 			    if (!display.readAndDispatch()) {
> 			        display.sleep();
> 			    }
> 			}
>  
> 			// Dispose the display when shell is closed
> 			display.dispose();
> 			System.out.println("....end....");
> 		} catch (Exception e) {
> 			System.out.println("....error....");
> 			// TODO Auto-generated catch block
> 			e.printStackTrace();
> 		}
>     }
> }
> ```
> 
> This is the pom.xml content:
> 
> ```
> <project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
>   xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
>   <modelVersion>4.0.0</modelVersion>
> 
>   <groupId>test</groupId>
>   <artifactId>SimpleShell</artifactId>
>   <version>0.0.1-SNAPSHOT</version>
> 
>   <name>SimpleShell</name>
>   <url>http://maven.apache.org</url>
> 
>   <properties>
>      <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
>      <maven.compiler.source>21</maven.compiler.source>
>      <maven.compiler.target>21</maven.compiler.target>
> 	 <main.class>test.SimpleShell</main.class>
>   </properties>
> 
>   <build>
> 	<plugins>
> 		<plugin>
> 			<groupId>org.apache.maven.plugins</groupId>
> 			<artifactId>maven-assembly-plugin</artifactId>
> 			<version>3.3.0</version>
> 			<configuration>
> 				<descriptorRefs>
> 					<descriptorRef>jar-with-dependencies</descriptorRef>
> 				</descriptorRefs>
> 				<archive>
> 					<manifest>
> 						<addClasspath>true</addClasspath>
> 						<mainClass>test.SimpleShell</mainClass>
> 					</manifest>
> 				</archive>
> 			</configuration>
> 			<executions>
> 				<execution>
> 					<id>assemble-all</id>
> 					<phase>package</phase>
> 					<goals>
> 						<goal>single</goal>
> 					</goals>
> 				</execution>
> 			</executions>
> 		</plugin>
> 	</plugins>
>   </build>
>   
> 	<dependencies>
> 		
> 			<dependency>
> 				<groupId>org.eclipse.platform</groupId>
> 				<artifactId>org.eclipse.swt.win32.win32.x86_64</artifactId>
> 				<version>3.126.0</version>
> 			</dependency>
> 	</dependencies>
> </project>
> ```
> 
> The testing was done on a Windows 11 machine using Oracle GraalVM for JDK 21.0.5
> 
> ```
> java version "21.0.5" 2024-10-15 LTS
> Java(TM) SE Runtime Environment Oracle GraalVM 21.0.5+9.1 (build 21.0.5+9-LTS-jvmci-23.1-b48)
> Java HotSpot(TM) 64-Bit Server VM Oracle GraalVM 21.0.5+9.1 (build 21.0.5+9-LTS-jvmci-23.1-b48, mixed mode, sharing)
> ```

**Comment by shireeshakalle** [comment]
Hi,
@oubidar-Abderrahim I have tried the same code which you have given also in the same way, but still its not working in few machines which are in our dev team. In couple of machines it worked and couple of machines its not working. Same error is coming. We can show you the issue ,in our systems its reproducible. Kindly Please help us @oubidar-Abderrahim.

Exception in thread "main" java.lang.NoSuchFieldError: org.eclipse.swt.internal.win32.GESTURECONFIG.dwBlock
at org.graalvm.nativeimage.builder/com.oracle.svm.core.jni.functions.JNIFunctions$Support.getFieldID(JNIFunctions.java:1357)
at org.graalvm.nativeimage.builder/com.oracle.svm.core.jni.functions.JNIFunctions.GetFieldID(JNIFunctions.java:449)
at org.eclipse.swt.internal.win32.OS.SetGestureConfig(Native Method)
at org.eclipse.swt.widgets.Control.checkGesture(Control.java:692)
at org.eclipse.swt.widgets.Control.createWidget(Control.java:709)
at org.eclipse.swt.widgets.Scrollable.createWidget(Scrollable.java:160)
at org.eclipse.swt.widgets.Decorations.createWidget(Decorations.java:375)
at org.eclipse.swt.widgets.Shell.(Shell.java:318)
at org.eclipse.swt.widgets.Shell.(Shell.java:281)
at org.eclipse.swt.widgets.Shell.(Shell.java:207).

**Comment by shireeshakalle** [comment]
Hi @oubidar-Abderrahim ,

Any help on this error , because In couple of machines we are facing this issue still. but In couple of machines it's working fine. Still we are struggling to fix, please help us on this.
