### ISSUE TITLE
Mismatch of analysisExecutor and compilationExecutor

### ISSUE THREAD

**Issue by johanvos** [oracle/graal#982]
The NativeImageGeneratorRunner calls NativeImageGenerator.run() with the executors in the order analysisExecutor, compilationExecutor  where the NativeImageGenerator expects them in the reverse order.

This can be relevant when the maximum number of threads is supplied for one of the executors (it will be implied to the wrong one)

**Comment by olpaw** [comment]
Merged on master. Thanks for the fix!
