### ISSUE TITLE
Add new labels for issues related to community repositories 

### ISSUE THREAD

**Issue by zakkak** [oracle/graal#9825]
**Feature request**

Please add the following new label for issues related to community repositories:

* `community-21` (or `community-jdk21u` if you prefer) to indicate that the issue affects builds based on https://github.com/graalvm/graalvm-community-jdk21u

**Is your feature request related to a problem? Please describe.**
See https://github.com/oracle/graal/discussions/9590

cc @jerboaa @simonis

**Comment by Karm** [comment]
@dchuyko ^^^  17?

**Comment by dchuyko** [comment]
> @dchuyko ^^^ 17?

21 is what makes practical sense for us as well at the time.

**Comment by zakkak** [comment]
Hi @fniephaus @alina-yur, this is a kind reminder.

**Comment by fniephaus** [comment]
Thanks for the ping, @zakkak, and apologies for the delay.

As per your request, I have added a [new label called `community-jdk21u`](https://github.com/oracle/graal/labels/community-jdk21u).

**Comment by zakkak** [comment]
Great, thank you :)
