### ISSUE TITLE
[GR-58918] Make `HomeFinder.getVersion` or equivalent available in `org.graalvm.sdk:nativeimage` without dependency on polyglot

### ISSUE THREAD

**Issue by zakkak** [oracle/graal#9831]
**Feature request**

When `graal-sdk` got split in the four maven artifacts (in GraalVM for JDK 21):

* [org.graalvm.polyglot](https://mvnrepository.com/artifact/org.graalvm.polyglot) » [polyglot](https://mvnrepository.com/artifact/org.graalvm.polyglot/polyglot)
* [org.graalvm.sdk](https://mvnrepository.com/artifact/org.graalvm.sdk) » [collections](https://mvnrepository.com/artifact/org.graalvm.sdk/collections)
* [org.graalvm.sdk](https://mvnrepository.com/artifact/org.graalvm.sdk) » [nativeimage](https://mvnrepository.com/artifact/org.graalvm.sdk/nativeimage)
* [org.graalvm.sdk](https://mvnrepository.com/artifact/org.graalvm.sdk) » [word](https://mvnrepository.com/artifact/org.graalvm.sdk/word)

`HomeFinder` was packaged in `org.graalvm.polyglot:polyglot`, as a result to get the native-image version being used during compilation (e.g. in a native image Feature) one needs to either depend on polyglot, even if not using it, or implement a similar API.

**Is your feature request related to a problem? Please describe.**
In Quarkus we implement similar logic to the one offered by HomeFinder.getVersion in https://github.com/quarkusio/quarkus/pull/43696 in order to be able to get the version at build time without depending on polyglot. While that works fine for Quarkus I suspect that it's something useful to a broader audience and would preferably be fixed in GraalVM.

**Describe the solution you'd like.**
I would like to be able to programmatically get the native-image version at build-time, e.g. in a custom Feature, without the need to bring in the polyglot dependency.

**Describe who do you think will benefit the most.**
Developers of libraries and frameworks which depend on GraalVM, as they will be able to make compile time decisions based on the GraalVM version being used (e.g. to test new features are adapt to new defaults).

**Describe alternatives you've considered.**
Quarkus already implements its own alternative.

**Express whether you'd like to help contributing this feature**
I am willing to implement the solution we will agree on.

**Comment by selhagani** [comment]
Hi @zakkak, 

Thank you for reaching out to us! I shared this with our dev team and I'll make sure to keep you updated.

**Comment by gilles-duboscq** [comment]
In the context of aligning the graalvm version and the java version as well as truffle unchained, the first thing would be to figure out what "get version" would mean in the context of native image and how that relates to polyglot's notion of "get version".

The way I understand the alignment of GraalVM's version with the Java version, there would be no need for a "get version" method in the native image APIs, since that would just return the java version. That alignment will happen for JDK 25.
So we'd be introducing an API that would get immediately deprecated.

You could also argue that for some special builds, a newer native-image might be used with an older JDK version. After all it's still possible to build native image with JDK 21 with current master. But as far as i understand, the goal is to get rid of that.

**Comment by zakkak** [comment]
> In the context of aligning the graalvm version and the java version as well as truffle unchained, the first thing would be to figure out what "get version" would mean in the context of native image and how that relates to polyglot's notion of "get version".

In the context of native image I guess the context would be "what GraalVM source code was this build based on? Does it include the X and Y features?", at least that's how we use it in Quarkus.

> The way I understand the alignment of GraalVM's version with the Java version, there would be no need for a "get version" method in the native image APIs, since that would just return the java version. That alignment will happen for JDK 25.
So we'd be introducing an API that would get immediately deprecated.

That's a good point.

> You could also argue that for some special builds, a newer native-image might be used with an older JDK version. After all it's still possible to build native image with JDK 21 with current master. But as far as i understand, the goal is to get rid of that.

Correct, but it's still something that gets brought up from time to time, so I still kind of keep it in the back of my mind.

Closing as not planned then. The timing is not good and a re-implementation of the logic as a work-around is not that hard.
