### ISSUE TITLE
Should allow access to GraalVM for JDK 22 documentation

### ISSUE THREAD

**Issue by linghengqian** [oracle/graal#9851]
**Feature request**

Please include the following information:

**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. E.g. I'm always frustrated when [...]

- No. Maybe https://github.com/apache/shardingsphere/pull/32916 .
- Also for #9699 .

**Describe the solution you'd like.**

- Should allow access to GraalVM for JDK 22 documentation.
- Now open https://www.graalvm.org/docs/archives/ and go to the documentation for `GraalVM For JDK 22`.
- ![image](https://github.com/user-attachments/assets/65b757c8-34ec-45ae-90e3-78a5e4d9eafc)
- The corresponding https://www.graalvm.org/jdk22/ returns 404. This doesn’t make sense.
- ![image](https://github.com/user-attachments/assets/9aba27f5-cab6-49ea-87dc-a72c32f1cb6f)

**Describe who do you think will benefit the most.**
GraalVM users, GraalVM contributors, developers of libraries and frameworks which depend on GraalVM, or somebody else?

- GraalVM users.

**Describe alternatives you've considered.**

- Null.

**Additional context.**
Add any other context about the feature request here.
For example, link to the relevant projects, documentation, standards.

- Null.

**Express whether you'd like to help contributing this feature**
If you'd like to contribute, please read the [contribution guide](https://www.graalvm.org/community/contributors/).

- I would say the documentation seems to exist in a closed source git?

**Comment by olyagpl** [comment]
On it.

**Comment by olyagpl** [comment]
The documentation for GraalVM for JDK 22 is back on the website:
![Screenshot 2024-10-10 at 15 42 52](https://github.com/user-attachments/assets/4d155c94-ca08-4b19-9d64-c7275712f408)
Thank you for letting us know!

**Comment by linghengqian** [comment]
- @olyagpl Um... I wonder if the archive URL has changed?😲 I still get `Page not found` when I visit https://www.graalvm.org/jdk22/ .
- ![image](https://github.com/user-attachments/assets/90c1f27a-467a-4d1d-8053-d6e4e9f11c72)

**Comment by olyagpl** [comment]
I have a guess why it happens. We published some changes to the main documentation yesterday evening, and it must have overwritten JDK22 version. Looking into this.

**Comment by linghengqian** [comment]
Should I close this issue? It looks like the problem has been solved.

**Comment by olyagpl** [comment]
Yes, please. Thank you, @linghengqian!
