### ISSUE TITLE
How to make a SourceSection

### ISSUE THREAD

**Issue by nodingneu** [oracle/graal#986]
How do I create my own instance of org.graalvm.polyglot.SourceSection?

I see no constructor [in its docs](https://www.graalvm.org/sdk/javadoc/org/graalvm/polyglot/SourceSection.html), and [org.graalvm.polyglot.Source](https://www.graalvm.org/sdk/javadoc/org/graalvm/polyglot/Source.html) has no `SourceSection createSection(...)` methods unlike [com.oracle.truffle.api.source.Source](https://www.graalvm.org/truffle/javadoc/com/oracle/truffle/api/source/Source.html).

I want to create a new org.graalvm.polyglot.SourceSection from a previous SourceSection that spans the lines the previous section does in the Source. 

I tried

    SourceSection getLines(SourceSection section) {
        return section.getSource().createSection(section.getStartLine(), -1, section.getEndLine(), -1);
    }

but `Source.createSection(int, int, int, int)` is undefined for org.graalvm.polyglot.Source.

So what am I meant to do?

**Comment by fniephaus** [comment]
I think you're supposed to use `com.oracle.truffle.api.source.Source` instead of the one you mentioned.

**Comment by boris-spas** [comment]
@theonlygusti Can you elaborate on your use case? In general, one should not need to create org.graalvm.polyglot.SourceSection instances. As @fniephaus pointed out, do you mean to use https://www.graalvm.org/truffle/javadoc/com/oracle/truffle/api/source/SourceSection.html ?

**Comment by wirthi** [comment]
Closing this stale old issue, an answer has been provided already. If you have follow-up questions, feel free to reopen.
