### ISSUE TITLE
[native-image] command line option -H:IncludeResources=... deletes characters

### ISSUE THREAD

**Issue by turing85** [oracle/graal#988]
**Graal Version**: 1.0.0-RC12, EE and CE

**Expected Behaviour**: Resources should be included as-is

**Actual Behaviour**: in some cases, the first letter of a resource path gets deleted

When adding resources through command-ine option `-H:IncludeResources=...`, the first letter willof the resource path will be deleted. I have some sample code on [github][github], that packages (`mvn package) and compiles (execute script `native/scripts/nativeCompile.sh`) fine, and the created exeuctable run as exepcted. When you, however, alter the command 

    $GRAAL_HOME/bin/native-image --no-server -cp ./dus.graal.native-1.0-SNAPSHOT.jar:../../benchmarks/target/dus.graal.benchmarks-1.0-SNAPSHOT.jar de.consol.dus.graal.numbercrunching.wordcount.WordCountStreamNative -O1 -da --static -H:IncludeResources='.*wordCount/.*\.txt$' -H:Log=registerResource

to

    $GRAAL_HOME/bin/native-image --no-server -cp ./dus.graal.native-1.0-SNAPSHOT.jar:../../benchmarks/target/dus.graal.benchmarks-1.0-SNAPSHOT.jar:. de.consol.dus.graal.numbercrunching.wordcount.WordCountStreamNative -O1 -da --static -H:IncludeResources='.*wordCount/.*\.txt$' -H:Log=registerResource

(the difference is the `.` at the end of the classpath), while compilation, one observes the following output:

    > ls -lisa   
    classes  dus.graal.native-1.0-SNAPSHOT.jar  generated-sources  maven-archiver  maven-status
    > native-image --no-server -cp ./dus.graal.native-1.0-SNAPSHOT.jar:../../benchmarks/target/dus.graal.benchmarks-1.0-SNAPSHOT.jar:. de.consol.dus.graal.numbercrunching.wordcount.WordCountIterativeNative -O1 -da --static -H:IncludeResources='.*wordCount/.*\.txt$' -H:Log=registerResource
    [de.consol.dus.graal.numbercrunching.wordcount.wordcountiterativenative:2515]    classlist:   1,497.81 ms
    [de.consol.dus.graal.numbercrunching.wordcount.wordcountiterativenative:2515]        (cap):   1,014.72 ms
    [de.consol.dus.graal.numbercrunching.wordcount.wordcountiterativenative:2515]        setup:   2,377.18 ms
    [Use -Dgraal.LogFile=<path> to redirect Graal log output to a file.]
    [thread:27] scope: ForkJoinPool-4-worker-1
      [thread:27] scope: ForkJoinPool-4-worker-1.registerResource
      ResourcesFeature: registerResource: lasses/wordCount/war_and_peace.txt #folder should be called "classes", not "lasses"
      [thread:27] scope: ForkJoinPool-4-worker-1.registerResource
      ResourcesFeature: registerResource: lasses/wordCount/le_grand_cyrus.txt #folder should be called "classes", not "lasses"
      [thread:27] scope: ForkJoinPool-4-worker-1.registerResource
      ResourcesFeature: registerResource: wordCount/war_and_peace.txt
      [thread:27] scope: ForkJoinPool-4-worker-1.registerResource
      ResourcesFeature: registerResource: wordCount/le_grand_cyrus.txt
    [...]

[github]: https://github.com/turing85/graal-playground

**Comment by olpaw** [comment]
Thanks for the bug report. I will fix this.

**Comment by olpaw** [comment]
Note that this is just a bug in the logging of what gets registered as a resource (the missing of the first character). The registration itself works as fine.

**Comment by olpaw** [comment]
Fixed on master (84a80c90728). Btw, by adding `.` to the classpath you are additionally putting `graal-playground/native/target` on the classpath. That causes the resources not only to be taken from the jar file but also from `graal-playground/native/target/classes/wordCount` which is likely **not** what you want.
