### ISSUE TITLE
[native-image]route META-INF\native-image\com.sangfor.gop\gop.auth\resource-config.json can be read, but META-INF\native-image\com.sangfor.gop\gop-auth\resource-config.json cannot be read

### ISSUE THREAD

**Issue by XenoAmess** [oracle/graal#9899]
**Describe the issue**
route `META-INF\native-image\com.sangfor.gop\gop.auth\resource-config.json` can be read, but `META-INF\native-image\com.sangfor.gop\gop-auth\resource-config.json` cannot be read

what is wrong with -?

**Steps to reproduce the issue**
Please include both build steps as well as run steps
1. **[e.g.: git clone --depth 1 https://git.myrepo.com/projectone ]**
2. **[e.g.: mvn clean package]**

**Describe GraalVM and your environment:**
java version "21.0.5" 2024-10-15 LTS
Java(TM) SE Runtime Environment Oracle GraalVM 21.0.5+9.1 (build 21.0.5+9-LTS-jvmci-23.1-b48)
Java HotSpot(TM) 64-Bit Server VM Oracle GraalVM 21.0.5+9.1 (build 21.0.5+9-LTS-jvmci-23.1-b48, mixed mode, sharing)

**More details**
Add any other information about the problem here. Especially important are stack traces or log output. Feel free to link to gists or to screenshots if necessary.
```
    PASTE YOUR LOG/STACK TRACE HERE
```

**Comment by selhagani** [comment]
As I haven't heard back from you in over three weeks, I will be closing this issue for now. If you
need further assistance or have any updates, please feel free to reach out at any time.
Thank you for your understanding.
