### ISSUE TITLE
Documentation on dynamic proxies is confusing

### ISSUE THREAD

**Issue by dsyer** [oracle/graal#998]
In [this document](https://github.com/oracle/graal/blob/master/substratevm/DYNAMIC_PROXY.md#manual-configuration) there is a nice example of JSON configuration for dynamic proxies, but it doesn't really explain what it means. It's an array of arrays of FQNs of Java interfaces. Why are there 3 arrays in one sample, and 1 in the other (the empty one)? How do they get applied to the proxies that need to be created by the app (e.g. if there are 10 different calls to `Proxy.newProxyInstance()` in the app, how do the FQNs from the JSON get used in each case?

**Comment by olpaw** [comment]
Providing e.g.
```
[
    ["java.lang.AutoCloseable", "java.util.Comparator"],
]
```
as DynamicProxyConfiguration allows you to write code such as
```
Proxy proxy = Proxy.newProxyInstance(classLoader, new Class<?>[]{java.lang.AutoCloseable.class, java.util.Comparator.class}, myHandler);
```
where the following asserts hold
```
Assert.assertTrue(java.lang.AutoCloseable.class.isAssignableFrom(proxy.getClass()));
Assert.assertTrue(java.util.Comparator.class.isAssignableFrom(proxy.getClass()));
```

**Comment by dsyer** [comment]
That's useful (and could therefore be incorporated in the docs immediately). What about if the proxy is created like this?

```java
private X createProxy(Class<?> y, InvocationHandler z) {
  return Proxy.newProxyInstance(classLoader, new Class<?>[] {y}, z);
}
```

Do I need an entry in the JSON for every possible value of `y` at runtime (assuming I even know)?

**Comment by olpaw** [comment]
> Do I need an entry in the JSON for every possible value of y at runtime (assuming I even know)?

Yes for all classes that you might create a proxy for (at image runtime) you will need an entry in the DynamicProxyConfiguration. As with reflection (and JNI) we require upfront knowledge. /cc @peter-hofer

**Comment by olpaw** [comment]
The original comment https://github.com/oracle/graal/issues/998#issuecomment-465642723 is outdated. For calls like
```
Proxy proxy = Proxy.newProxyInstance(classLoader, new Class<?>[]{java.lang.AutoCloseable.class, java.util.Comparator.class}, myHandler);
```
we can autodetect the Proxy use. For code like in https://github.com/oracle/graal/issues/998#issuecomment-465652142 we still require DynamicProxyConfiguration.
